### ISSUE TITLE
git-annex: custom downloaders

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#10]
As we originally planned, we would need custom helpers to fetch data from e.g. image databases neither exposing their data via HTTP, nor providing a universal "key store" like facility, so prohibiting development of dedicated special remote handlers for them.

One way to mitigate this would be to have in git-annex some way to specify custom "downloaders" given a specific URI pattern.  E.g. for URL regexp "http.*\.torrent" still use built-in wget/curl for checking content presence and ```aria2c %(url)s``` for fetching the content.  Such custom downloaders would also have their registry of authorization credentials for data sources requiring them.  Also we could support extraction from locally present archives, via custom downloaders, see e.g. https://github.com/datalad/datalad/blob/54b71be5d514991aa432931564698744492bcb6c/docs/design.rst#L277 on details.

If support of custom downloaders would not be implemented directly in git-annex, it might be implementable by datalad in many cases by "proxying" calls to wget and/or curl and then checking/fetching content accordingly.

Currently annex only has support for regular wget/curl and quvi (for youtube videos), with hardcoded logic.

Related:
- all issues tagged as new-datatransfer-protocol https://github.com/datalad/datalad/issues?q=is%3Aopen+is%3Aissue+label%3Anew-datatransfer-protocol
- Using an external client (addurl torrent support)
http://git-annex.branchable.com/todo/Bittorrent-like_features/#index2h1

**Comment by joeyh** [comment]
I think we can close this one, git-annex has had the changes for some time, and afaik datalad is using them.

**Comment by joeyh** [comment]
I think we can close this one, git-annex has had the changes for some time, and afaik datalad is using them.
