### ISSUE TITLE
need not duplicate name of installed dataset in the info log msg

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1001]
with #959 (but may be master as well)
```
Installing subdataset <Dataset path=/home/yoh/datasets.datalad.org/openfmri/ds000007> in order to get /home/yoh/datasets.datalad.org/openfmri/ds000007
```
might be sensible "technically" but imho is just a waste of the screenspace in comparison to eg

```
Installing subdataset <Dataset path=/home/yoh/datasets.datalad.org/openfmri/ds000007>
```

**Comment by mih** [comment]
It is doable to test for this condition and shorten the message. Master has a similar message AFAIK with a similar problem.

**Comment by bpoldrack** [comment]
Yes, same "issue" in master.
