### ISSUE TITLE
RFC: Dataset.is_installed should not leak errors

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1012]
```
> /home/yoh/picts/mris/heudiconv/bin/heudiconv(1188)add_to_datalad()
-> if not ds.is_installed():
(Pdb) p ds
<Dataset path=/home/yoh/picts/mris/dartmouth-phantoms/bids_test4-20161014/bids-output>
(Pdb) n
ERROR: <class 'git.exc.NoSuchPathError'>: /home/yoh/picts/mris/dartmouth-phantoms/bids_test4-20161014/bids-output
INFO: Failed to detect a valid repo at /home/yoh/picts/mris/dartmouth-phantoms/bids_test4-20161014/bids-output
> /home/yoh/picts/mris/heudiconv/bin/heudiconv(1189)add_to_datalad()
-> lgr.info("Initiating %s", ds)
```

I think it would be logical to swallow error messages -- after all we are asking if is installed. agreed?

**Comment by mih** [comment]
As long as they are not swallowed in the constructor again: #897

**Comment by yarikoptic** [comment]
Ha, good point. So resolution for this particular one is just to check if path exists at all first ;-)

**Comment by yarikoptic** [comment]
hm... can't reproduce in a clean test like 
```
$> DATALAD_LOG_LEVEL=INFO python -c "from datalad.api import Dataset; print Dataset('/tmp/123111nonexisting').is_installed()"
False
```
so it might be something in addition to trigger such a msg

**Comment by yarikoptic** [comment]
just FTR:  may be smth like https://pypi.python.org/pypi/errator  could be of use  sometime -- so you pretty much buildup a 'stack' of narrations so if error happens, then (unlike log which logs always) you would  include relevant levels into the message.
