### ISSUE TITLE
auto-add-changes also adds files.  Origin: create saves into super-dataset before it commits to git/annex of the sub

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1016]
not yet how or when but I think it might happen when you create a new dataset (in hierarchical layout), but then (without first adding it to the super) call "datalad save -r" it would add those files of the sub-dataset to the git/annex of the super-dataset... I have observed such a "result" and not direct sequence of actions yet (thus not yet sure on the cause and too late to try to replicate atm)

**Comment by yarikoptic** [comment]
FTR: failed to replicate in what I thought could have lead to such behavior (recursive save in newly created datasets):

```shell
$> d=/tmp/test; sd=$d/sub1; sd2=$sd/sub2; fd=$sd2/d; f=$fd/file.dat; chmod +w -R $d; rm -rf $d; mkdir -p $fd; touch $f; datalad create --force $d; datalad create --force $sd; datalad create --force $sd2; datalad save -m "saving" -a -r -d $d; ls -ld $f
```

**Comment by yarikoptic** [comment]
ok -- here is the test which replicates it :-/  and it is related to our aggressive default pre-committing changes (related or not, even if not under git/annex at all) 
```shell
@with_tree({'ds2': {'file1.txt': 'some'}})
def test_saving_prior(topdir):
    # the problem is that we might be saving what is actually needed to be
    # "created"

    # we would like to place this structure into a hierarchy of two datasets
    # so we create first top one
    ds1 = create(topdir, force=True)
    # and everything is ok, stuff is not added BUT ds1 will be considered dirty
    ok_(ds1.repo.dirty)
    # And then we would like to initiate a sub1 subdataset
    ds2 = create('ds2', dataset=ds1, force=True)
    # But what will happen is file1.txt under ds2 would get committed first into
    # ds1, and then the whole procedure actually crashes since because ds2/file1.txt
    # is committed -- ds2 is already known to git and it just pukes with a bit
    # confusing    'ds2' already exists in the index
```

so if we are to save changes by default -- shouldn't we just save actual "changes" not all the files under that dataset, some of which might not even be in the dataset?  and then make it possibly
```--auto-add=changes|all``` ?

**Comment by bpoldrack** [comment]
I think, this would lead to going away from the goal to provide a tool, that makes things easier for non-git people. I'd prefer to 

1. keep `all`, but allow for exclusions. So `create` can exclude that path when saving before. (But: That means, you actually can not restore the state "before" completely, which doesn't seem to be desirable)

or

2. consider `create` a command, that doesn't provide a `save_before` functionality, since the thing to save the state in, isn't existing yet. I think this is the easiest solution and can absolutely be justified.

or

3. creation of a subdataset needs to take that result of `save` into account and move things. More complicated to achieve but best behaviour, I guess.

**Comment by yarikoptic** [comment]
Let me drop a quick additional argument - do we provide a .gitignore oracle? Or in other words, with all top be default behavior, we quickly guarantee that many files added would be junk, especially in mixed source+ code repositories

**Comment by bpoldrack** [comment]
I'd argue, that in such a case you should configure a different default default for `--if-dirty` and/or provide a proper .gitignore respectively.

**Comment by bpoldrack** [comment]
I increasingly feel, that we are building an API in flavor of special cases and git people, instead of aiming for a clean and simple concept for the people we are supposed to target. Defaults should be best for the simple cases and configurable to cover different setups, I think.

**Comment by yarikoptic** [comment]
- but we shouldn't alienate git people of which there is an increasing number! ;)
- making if-dirty configurable I think is a good idea.  I think this is a level where indeed per-user configuration might make sense.  I would still like people to use 'add' ... need to read that gitless paper. But look at their API (http://gitless.com/) -- it has "track" and "untrack", which is I guess what "add", and somewhat of "remove" does -- introduces tracking of specific files.  Adding just everything in a directory would just lead to all kinds of junk getting in imho.
- unlikely we can provide ultimate *proper* .gitignore but I think we indeed should provide some with most common cases

Here is e.g. a reasonable starting selection from a pool of repos I have on the drive (debian packaging and whatnot, total of 2789 .gitignore files, some are repetetive, coming from the same projects, could improve analysis based on unique files)
```shell
$> locate .gitignore | xargs grep -h . 2>/dev/null| grep -v -e '^ *#' -e '\.\(png\|pdf\|jpg\|jpeg\|tgz\|.gz\)$'| sort | uniq -c | sort -n | tail -n 50
     48 configure
     48 /dist
     50 config.status
     50 .mr.developer.cfg
     51 .ropeproject
     52 *.debhelper*
     52 tmp
     54 *.pyo
     56 .pc
     57 bin
     57 *.substvars
     59 .idea
     59 *.orig
     60 /Makefile.in
     61 *.exe
     61 files
     65 /*~
     66 Makefile.in
     68 nosetests.xml
     72 .#*
     74 *.mo
     75 .o
     76 .installed.cfg
     77 /build
     81 *.egg
     81 MANIFEST
     82 .tox
     83 Makefile
     87 pip-log.txt
     88 vmlinux.lds
     94 .pydevproject
    100 *.py[cod]
    108 *.a
    110 dist/
    123 *.bak
    126 *.egg-info
    127 build/
    127 !.gitignore
    133 .project
    136 *
    140 dist
    142 *.log
    172 *.o
    199 build
    213 *.swp
    215 .coverage
    217 .DS_Store
    218 *.so
    349 *.pyc
    356 *~
```

interesting hit is `*`!  apparently often ppl ignore EVERYTHING unless otherwise explicitly added (with --force probably).  Quite frequently they have 

```
*
!.gitignore
```

which hints on the fact that some git-savvy ppl might prefer to complete avoid any magical 'add' in favor of explicit statements.  After all, explicit (add) is better that implicit (especially hidden under "updates" word)

**Comment by yarikoptic** [comment]
I thought we have already dealt with this issue, but apparently we didn't one way (to have auto-add-changes add actual changes not new content, which would make creation of subdatasets within present content possible, see above)  or another...  and I have ran into it again :-/

**Comment by mih** [comment]
Added the proposed test and a slightly more complete form to #1169 -- no longer an issue.

**Comment by mih** [comment]
Fix merged.
