### ISSUE TITLE
`add_sibling` documentation insufficient

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1017]
Introductory text (currently missing) should reference the term `sibling`.

The docs of the URL parameter should reference `--force` to say that it can also work otherwise.

> List of currently available placeholders: %NAME the name of the dataset

What actually is the "name" of a dataset? I would have to guess.

**Comment by bpoldrack** [comment]
> What actually is the "name" of a dataset? I would have to guess.

The name of its base dir. What term you'd propose to use instead of "name"?

**Comment by mih** [comment]
Resolved in #1579
