### ISSUE TITLE
RFC: ENH: create --to-annex-scheme  to set a policy which files are (not) added to annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1021]
in light of #1019 I wondered if we should add an option to `create` which would provide a few choices for default behavior of "add/save" -- what files should go to annex. I see a few possible schemes we could easily set:
- **all** -- that is what we have ATM. no .gitattributes generated, everything goes to annex unless explicitly aid to go to git
- **largenontext** -- which would generate .gitattributes

``` shell
* annex.largefiles=(largerthan=100kb and not (mimetype=text/*))
```
- **nontext** -- I think this is what should be our default, and which would generate .gitattributes

``` shell
* annex.largefiles=not (mimetype=text/*)
```

I haven't tried those specific values for largefiles yet, but according to https://git-annex.branchable.com/tips/largefiles/  should work, right @joeyh ?

possibly relates to #925 (create-sibling), #996 (`add --to=git|annex`) ...

**Comment by yarikoptic** [comment]
possibly relates to #925 (create-sibling) ...

**Comment by mih** [comment]
This is now possible via `create --cfg-proc` and dataset procedures, such as `cfg_text2git`, or `cfg_yoda`.
