### ISSUE TITLE
Dataset singletons

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1028]
It is @bpoldrack 's dream to have those.  And flyweight pattern is probably the way to go:
http://zqpythonic.qiniucdn.com/data/20060526140550/index.html#id17 by establishing a weakref directionary, so there will be no guarantee to always get the same dataset (of which you could access thousands in a good session) but at least the same if you still have it referenced somewhere

**Comment by yarikoptic** [comment]
While thinking about dataset singletons, think also about GitRepo singletons...   that could become crucial whenever we finally decide to think about locking which is a topic we masterfully ignored but at some point it would byte us very badly I am afraid -- ATM we are ignorantly blessed by performing actions among hierarchies of datasets/repositories but situation would become much more worrisome happen two datalad processes operate on the same dataset(s).  I am starting to see nightmares about deadlocks etc since independent operations could originate from different super/sub-datasets (especially as long as we allow for `get_superdataset`) thus leading to a banal deadlock if we just lock repository upon creation of *Repo class...  So I thought that may be having singleton *Repos could at least minimize possibility of screw ups within the same process.

**Comment by bpoldrack** [comment]
Yeah - agree.
