### ISSUE TITLE
SSH ControlPath in inappropriate location

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1032]
````
In [5]: ssh = sm.get_connection('localhost:/tmp/dummy')
In [6]: ssh.open()
mih@localhost's password: 
In [7]: ssh.open()
In [8]: ssh.ctrl_path
Out[8]: '/home/mih/.config/datalad/localhost'
````

ssh_config(5) says:

> It is recommended that any ControlPath used for opportunistic connection sharing include at least %h, %p, and %r (or alternatively %C) and be placed in a directory that is not writable by other users.

This is not true in our default setup.

The placement of the socket might also be related to the issues of SSH connections not being reused #826 #865 (of which at least the former is still present in master as of now). Moreover, the control master socket is no config file. I could imagine people having their `.config` in a VCS.

The socket could go into `~/cache/datalad/sockets` which would be made `700`. Actual target directory should come from a config setting.

One more: We do `ControlPersist=yes`. Are we 100% positive that under any circumstances we will not leave behind something that could be used for (un)intentional evil? Or should we at least use something like `ControlPersist=1h`?

@bpoldrack?

**Comment by bpoldrack** [comment]
Originally another path was used for the socket. That was changed at some point for a reason I don't recall atm. Looking into it.

Re `ControlPersist`: We should make sure to not leave sth behind, yes. But a fixed time? We use these connections for git and annex. Downloading the content of a TB dataset might last ... While I see the point of it, I doubt it would be nice to require the user to provide credentials after 1 hour again.

**Comment by mih** [comment]
See #826 for a recipe to easily leave open connection sockets behind.

**Comment by mih** [comment]
> Re ControlPersist: We should make sure to not leave sth behind, yes. But a fixed time? We use these connections for git and annex. Downloading the content of a TB dataset might last ... While I see the point of it, I doubt it would be nice to require the user to provide credentials after 1 hour again.

This is not true. They would have to reauthenticate an hour after the conenction was last used for anything. I consider that quite OK. See ssh_config(5)

> If set to a time in seconds, or a time in any of the formats documented in sshd_config(5), then the backgrounded master connection will automatically terminate after it has remained idle (with no client connections) for the specified time.

**Comment by bpoldrack** [comment]
Agree. Recalled wrongly. But then the time to be set there should be even shorter, I guess.

**Comment by mih** [comment]
Fine with that.
