### ISSUE TITLE
Found conflicting annex-ssh-options for remote ... -o ControlMaster=auto

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1038]
Got flooded with (I think during `save -r`, yet to figure out details) such messages

```
WARNING: Found conflicting annex-ssh-options for remote 'smaug':
-o ControlMaster=auto -S /home/yoh/.config/datalad/smaug
Did not touch it.
WARNING: Found conflicting annex-ssh-options for remote 'smaug':
-o ControlMaster=auto -S /home/yoh/.config/datalad/smaug
Did not touch it.
WARNING: Found conflicting annex-ssh-options for remote 'smaug':
-o ControlMaster=auto -S /home/yoh/.config/datalad/smaug
Did not touch it.
```

**Comment by yarikoptic** [comment]
if that is due to the fact that previously set (by datalad) options are now in conflict with new ones -- we need to "upgrade" them automagically (with an INFO log message)

**Comment by bpoldrack** [comment]
First of all: The fact, that existing options are in conflict with new ones isn't new. So, there is more to it.
Second: This can happen in `AnnexRepo.__init__` only. So the "new" one would be the automatically generated one. If there's something different present, this might be set manually and therefore I doubt, that any magic would be reasonable.
Third: Looking into it ... ;-)

**Comment by bpoldrack** [comment]
Okay, got it, I think. The directory used for the sockets changed, but needed to be written to .git/config for annex. So, these repos need an upgrade indeed. But still: Upgrade in general can't be the way to go, I think. We need to start recording a datalad version in the repos in order to figure out necessary upgrades like this.

**Comment by yarikoptic** [comment]
hold on -- are you in hawaii now or should I kick you back to bed?! ;)

while at it -- please centralize all the handling/setup of those -- there seems to be 3! locations where those settings are setup within annexrepo.py ...  upgrade is the only way to go for me with already probably > 50 repositories and probably now across multiple boxes, where this setting is set I guess ;)   re: record version -- not sure if feasible to handle spreadout settings unless we record version per each setting.  In this specific case we know what was previous value and what is a new one -- so we can check and replace.  yes -- it is somewhat a pain but much lesser pain imho than doing it manually now across all the repos and boxes

```
datalad/support/annexrepo.py-                if url is not None:
datalad/support/annexrepo.py-                    if is_ssh(url):
datalad/support/annexrepo.py-                        c = ssh_manager.get_connection(url)
datalad/support/annexrepo.py:                        cfg_string = "-o ControlMaster=auto -S %s" % c.ctrl_path
datalad/support/annexrepo.py-                        sct = "remote \"%s\"" % r
datalad/support/annexrepo.py-                        opt = "annex-ssh-options"
datalad/support/annexrepo.py-                        reader = self.repo.config_reader()
--
datalad/support/annexrepo.py-            writer = self.repo.config_writer()
datalad/support/annexrepo.py-            writer.set_value("remote \"%s\"" % name,
datalad/support/annexrepo.py-                             "annex-ssh-options",
datalad/support/annexrepo.py:                             "-o ControlMaster=auto"
datalad/support/annexrepo.py-                             " -S %s" % c.ctrl_path)
datalad/support/annexrepo.py-            writer.release()
datalad/support/annexrepo.py-
--
datalad/support/annexrepo.py-            writer = self.repo.config_writer()
datalad/support/annexrepo.py-            writer.set_value("remote \"%s\"" % name,
datalad/support/annexrepo.py-                             "annex-ssh-options",
datalad/support/annexrepo.py:                             "-o ControlMaster=auto"
datalad/support/annexrepo.py-                             " -S %s" % c.ctrl_path)
datalad/support/annexrepo.py-            writer.release()
datalad/support/annexrepo.py-
```

**Comment by bpoldrack** [comment]
You should kick me. ;-)

Sure - these repos need an upgrade. I just don't want to replace these options to not overwrite custom settings. But: We can do it indeed. Because the only thing we actually need to replace is the path. And since this is about sharing connections, we probably should overwrite that path in any case. So, let's replace the path to ControlMaster whenever it is conflicting, but keep everything else as is. Agree?

Re centralizing: Agree.
