### ISSUE TITLE
RFC API: create-sibling*s -- should we RF into similar to export 'plugin' setup?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1040]
In light of #1018 I wondered if we should adopt similar to implemented by @mih `export` plugin structure? 

Also worth thinking how we would name `create-*-s3` etc for annex special remotes?  S3 and other services are there and we should expose this important functionality of annex to the user, so they could easily publish to github and offload data to not only a real `sibling` but also a `bastard` (I guess, if we follow the scheme) -- a special remote which has nothing in common in terms of git history but serves a key store for data

**Comment by mih** [comment]
Cannot say yet. Let's first have two or three implementations. It should become fairly obvious what is common among them, once we have the code.

**Comment by mih** [comment]
I looked at that, and it would require a lot more than the exporter interface. I am not plaining to work on this. but see #1279
