### ISSUE TITLE
create-test-dataset should be gone/completed/documented/not pollute the user API

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1048]
Or any combination of the above. At present it generates something that is not a dataset.

**Comment by mih** [comment]
I think it should become a tool that we ship, rather than an integrated command. @yarikoptic what do you think? Any advantage from taking up a slot in the public API?

**Comment by yarikoptic** [comment]
I would prefer keeping it in the "datalad API" but annotating it somehow that it is not a "user level" command.  I thought I have expressed such wishlist at some point but couldn't find it on a quick look.
Reasons are multiple
- to take advantage of the API handling (manpages, completion, etc)
- to stay uniform in anything "APIish"
- it might come handy in some cases to troubleshoot by users... so we could just say run `datalad create-test-dataset ..<options>..` and see how command `datalad X` works
- it would be somewhat similar to how git  has "HIGH-LEVEL COMMANDS (PORCELAIN)" which are usually used by users, and then "LOW-LEVEL COMMANDS (PLUMBING)".

**Comment by mih** [comment]
It is in plumbing now
