### ISSUE TITLE
automate/simplify to degree possible recent release installation of annex on Windows test VM

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#105]
@joeyh  -- so is there any way for us to avoid all the clicking dance on windows?

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> @joeyh -- so is there any way for us to avoid all the clicking dance on
> windows?

I could ship a tarball or zip file containing the git-annex files for
windows.

There are some things in the nullsoft installer that a zip file couldn't
do, like know what the git install directory is, and install menu files.

I wonder if there's some way to automate installation of nullsoft
installers though. Surely you're not the 1st one to want to do that..

-- 
see shy jo

**Comment by mih** [comment]
We have this in the appveyor builds now.
