### ISSUE TITLE
Think about offline data retrieval

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1054]
What if data is so bulky/protected that there. is no way to obtain it over the web. Can we have a "floppy-based" method to obtain data? So in a sense an offline special remote...

**Comment by yarikoptic** [comment]
I guess this is more of a git-annex question.  Here is a sample discussion: http://git-annex.branchable.com/forum/Managing_a_large_number_of_files_archived_on_many_pieces_of_read-only_medium___40__E.G._DVDs__41__/   

I will close it for now. Feel free to reopen if feel otherwise
