### ISSUE TITLE
build git-annex-standalone Debian package to be made available across all (Neuro)Debian releases

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#106]

**Comment by yarikoptic-private** [comment]
partially addressed:  we have git-annex-standalone package now available throughout neurodebian.  There is a PR in git-annex to somewhat finalize it:  https://github.com/joeyh/git-annex/pull/41

**Comment by hanke** [comment]
Seems done. Close?

**Comment by yarikoptic** [comment]
indeed
