### ISSUE TITLE
physionet collection of datasets

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1062]
includes some EEG/MEG data of interest e.g. to mne-python project

it is an interesting case with meta-data associated with datasets and some files: see
https://physionet.org/physiotools/pbs/ so, for a per file meta-data support, it might be a good use-case.  They provide search utility etc

also their "publication" format somewhat reminds ours -- a simple webindex with some decoration to provide details of the dataset

unfortunately do not version (at least visibly I don't see) the data files

**Comment by yarikoptic** [comment]
related issue on physionet:  https://github.com/MIT-LCP/physionet/issues/16

**Comment by mih** [comment]
This issue was moved to datalad/datasets#11
