### ISSUE TITLE
provide handling of "agree to the license/rules" popups

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1069]
e.g. kaggle for some datasets, when you click to download any specific file might pop up a dialog:
http://www.onerussian.com/tmp/kaggle-accept-rules.png
asking you to agree first. (there is similar pain with nitrc)   So, for some providers we should not only enable custom check for 'failed login' but also for such 'not yet authorized' attempts.  I wonder if we could somehow bring up a browser session with currently active cookie...  otherwise user would need to login in the browser first and "agree"

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
