### ISSUE TITLE
Recent git-annex update fails on windows

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#108]
Currently tests on windows are failing, because every git annex init fails.

Reproduce it:

    $> mkdir test
    $> cd test
    $> git init
    Initialized empty Git repository in .../test/.git/
    $> git annex init
    init
    Detected a filesystem without fifo support.
    Disabling ssh connection caching.
    Detected a crippled filesystem.
    fatal: Not a valid object name --no-gpg-sign
    git-annex: user error (git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","commit-tree","4b825dc642cb6eb9a060e54bf8d69288fbee4904","--no-gpg-sign"] exited 128)
    failed
    git-annex: init: 1 failed

    $>git annex version
    git-annex version: 5.20150409-g3575ee5
    build flags: Assistant Webapp Webapp-secure Pairing Testsuite S3 WebDAV DNS Feeds Quvi TDFA TorrentParser
    key/value backends: SHA256E SHA1E SHA512E SHA224E SHA384E SKEIN256E SKEIN512E MD5E SHA256 SHA1 SHA512 SHA224 SHA384 SKEIN256 SKEIN512 MD5 WORM URL
    remote types: git gcrypt S3 bup directory rsync web bittorrent webdav tahoe glacier ddar hook external
    local repository version: unknown
    supported repository version: 5
    upgrade supported from repository versions: 2 3 4

**Comment by joeyh** [comment]
So this is a git-annex/git version mismatch. I recently got the windows autobuilder updated to the current version of msgit, and so it builds git-annex using this new-ish git option, which  is needed to avoid a bug.

I can convert it to a run-time check, but it would need to check the git version every time git-annex runs. 

Easiest fix then would be to upgrade your msgit to something more recent..

**Comment by joeyh** [comment]
Correction, that was --literal-pathspecs, --no-gpg-sign is some other problem. Apparently the current version of msgit dropped the option. Looking into it.

**Comment by joeyh** [comment]
Huh, the windows autobuilder admin upgraded it to git 2.1.0, but the newest msgit I can find to download is 1.9.5. Thus the mismatch. I've pinged him to see what's up.

**Comment by bpoldrack** [comment]
Ok. Thank you, @joeyh.

2015-04-13 20:06 GMT+02:00 Joey Hess <notifications@github.com>:

**Comment by yarikoptic** [comment]
On Mon, 13 Apr 2015, Joey Hess wrote:

>    Huh, the windows autobuilder admin upgraded it to git 2.1.0, but the
>    newest msgit I can find to download is 1.9.5. Thus the mismatch. I've
>    pinged him to see what's up.

I guess he just built it manually.  But if there is such an API
breakage, I guess it would be way too common a catch that people might
have "outdated" git with a newer annex, so probably something should be
done on the annex side

**Comment by yarikoptic-private** [comment]
I think one was resolved now (Yuri said there was some obscure update of msgit from 2. whenever 1.9.x was expected). thus closing
