### ISSUE TITLE
sugaring: ds['subds'] -> subds (as a Dataset)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1081]
ATM we would need to do smth like Dataset(opj(ds.path, 'subds')) which is imho ugly and inefficient. 
any objections for  employing `__getitem__` for this?

This one though brings IMHO interesting question either here we should refer to submodule by its name or by its path??  so far we pretty much assumed that name == path, but it could be not the case. @mih -- did you have such setups by any chance?

```shell
(git)hopa:/tmp/datasets.datalad.org/neurovault[master]git
$> git submodule add --name nidm $PWD/../nidm nidm-path 
Cloning into '/tmp/datasets.datalad.org/neurovault/nidm-path'...
done.
cached/staged changes:                                                           
 .gitmodules | 3 +++
 nidm-path   | 1 +

$> python -c 'from datalad.api import Dataset; print Dataset(".").get_subdatasets()'         
[u'nidm-path', u'snapshots']
cached/staged changes:                                                           
 .gitmodules | 3 +++
 nidm-path   | 1 +

$> cat .gitmodules 
[submodule "archive"]
	path = snapshots
	url = ./archive
[submodule "nidm"]
	path = nidm-path
	url = /tmp/datasets.datalad.org/neurovault/../nidm
```

**Comment by bpoldrack** [comment]
I'm already at it. This involves similar issues, I'm addressing.

**Comment by yarikoptic** [comment]
@bpoldrack - do you remember what you were addressing and either it is still WiP? ;-)

**Comment by mih** [comment]
This hasn't materialized in 5 years. I think we can close this without loss of momentum.
