### ISSUE TITLE
enable post-commit hook on the webserver to avoid direct edits break the access

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1087]
While messing around with #1074 straight on the webserver I have realized that no git update-server-info  was ran.  I am not quite sure why git folks templated that action only in post-update hook and no in post-commit as well.  I guess it is rearer for folks to manipulate git repo straight on the server, but still...

**Comment by mih** [comment]
I am not convinced that we want to do that. How do we even know that the purpose for creating a sibling is to be accessible via a webserver. Maybe we want to limit that to cases where a URL is provided.

**Comment by mih** [comment]
Checking back in 5 years later. Can this be closed?

**Comment by bpoldrack** [comment]
I think it can be closed indeed.
Whether someone wants that or not is highly specific to the usecase. It should be done by the respective user, not by some datalad guessing. Overall looks more like wrong expectations with git, which is nothing we can (or should) fix. Especially not by turning the correct expectation for git behavior upside down with datalad.
