### ISSUE TITLE
Support CKAN API http://docs.ckan.org/en/latest/user-guide.html

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1090]
Apparently it is one of the standards and used eg by #1089 . We could at least use it to consume, but may be also to expose our datasets.

**Comment by nicholsn** [comment]
Note that CKAN has an extension supporting import/export of frictionless datapackages that could leverage the existing metadata extractor in datalad: https://github.com/frictionlessdata/ckanext-datapackager

**Comment by yarikoptic** [comment]
seems to be of no immediate need/interest so I will let it RiP for now

**Comment by yarikoptic** [comment]
also besides https://data.gov/ ... I think it is well worth supporting even if only for consumption!
