### ISSUE TITLE
Evaluate content of datalad/const.py for to-be-added config vars

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1095]
Things that immediately come to mind are:

- `LOCAL_CENTRAL_PATH`
- `ARCHIVE_TEMP_DIR`

**Comment by bpoldrack** [comment]
Probably everthing, we use `AppDirs` as default for.

- `LOCAL_CACHE_DIR`
- `LOCAL_CONFIG_DIR`
- `LOCAL_SOCKET_DIR`

**Comment by mih** [comment]
I ever addressed, it should include #2054

**Comment by mih** [comment]
I am closing this old issue of mine. There is clearly no interest in this.
