### ISSUE TITLE
publish claims that sibling doesn't exist.  should report under which repo

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1099]
```shell
(git)smaug:/mnt/datasets/datalad/crawl[master]git
$> datalad publish -r --to datalad-public
[ERROR  ] No sibling 'datalad-public' found. [publish.py:__call__:289] (ValueError) 
(venv-tests)1 10221 ->1.....................................:Mon 07 Nov 2016 11:45:48 PM EST:.
(git)smaug:/mnt/datasets/datalad/crawl[master]git
$> git remote                            
datalad-dev-public
datalad-public
changes on filesystem:                                                                                          
 crcns      | 2 +-
 dicoms     | 2 +-
 indi       | 2 +-
 kaggle     | 2 +-
 labs       | 2 +-
 neurovault | 2 +-
 nidm       | 2 +-
```
tried with both current master  and #1037.. and then realized that it is probably due to some burried down dataset... indeed it was due to some dataset underneath... so at least error msg should say for which dataset this remote doesn't exist.

hopefully tomorrow I will brush up the current state of our collection and get it published -- all openfmri datasets are ready

**Comment by mih** [comment]
Let's rename `remote' to `faraway` and `sibling` to `littleone` -- that will settle the frequent parenthetical statement in issue titles -- I am sure!

**Comment by yarikoptic** [comment]
Parenthetical statements are made for mortals who have no clue in datalad terms but verse in git. Adding more aliases doesn't help anyhow
