### ISSUE TITLE
API: `add` vs `save`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1106]
I keep being confused about the desired purpose of `add` in contrast to `save`. I was just about to file an issue about why `save` has no `--to-git` -- and of course `add` has...

What about this:

- `add` is about adding stuff to a dataset that is not already in its directory tree
- `save` is about everything that is already there

Rational: we are doing auto-adds, auto-commits, etc. Keeping this add/commit commit distinction just for files in the working tree seems inconsistent.

`save` already deals with untracked submodules that it happens to find. Being able to check files into git directly (non-annex) seems like the last missing piece.

**Comment by bpoldrack** [comment]
> `add` is about adding stuff to a dataset that is not already in its directory tree

Like what? Would that be different from `install`?

**Comment by mih** [comment]
Candidates from the git annex command list:

````
  addurl          URL ...      add urls to annex
  import          PATH ...     move and add files from outside git working copy
  importfeed      URL ...    import files from podcast feeds
````

My intuition tells me that having `install` work on individual remote files will not be a popular proposal...

**Comment by bpoldrack** [comment]
Yeah, okay. Forgot about these.
So: I agree.

**Comment by yarikoptic** [comment]
Agree too. I have already expressed my dislike of save --auto-add-changes adding actual new files, which as you agree now, should probably be the job of add

**Comment by mih** [comment]
Haha, as usual I was implying the exact opposite.

**Comment by mih** [comment]
Superseded by #1169
