### ISSUE TITLE
uninstall --kill removes paths outside datasets

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1114]
This is presently the case, and I think it should not be.

If I don't see a veto, I will change that now. @yarikoptic @bpoldrack 

Started going through the other uninstall-related bugs.

**Comment by bpoldrack** [comment]
No veto.

**Comment by yarikoptic** [comment]
What do you mean by "paths outside of datasets" -- that it follows symlinks leading outside, or that you could run it even without being under a dataset, or ... ?  but in general I agree -- shouldn't remove anything not under datalad control

**Comment by mih** [comment]
Merci!
