### ISSUE TITLE
AutoMagicIO should support Alohomora!

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1117]
Currently, and even with #1116 in place, a Python script trying to write to an annexed file will fail with AutoMagicIO enabled. We should have a switch that enables/allows AutoMagicIO to automatically unlock such files on write (and maybe even re-save) -- not just to obtain content on read.

For inspiration regarding switch naming I recommend: https://en.wikipedia.org/wiki/List_of_spells_in_Harry_Potter

**Comment by yarikoptic** [comment]
I guess as soon as we have an interface for `unlock` in our AnnexRepo -- should be very easy to implement, right?

**Comment by mih** [comment]
Does it have to be AnnexRepo? We have a top-level command in some form or shape.

**Comment by yarikoptic** [comment]
It feels like there should be one within AnnexRepo, similar to all others (add/get/...)  which would get also interfaced at the top level API  (and thus linked to dataset etc)

**Comment by mih** [comment]
Closing in favor of #1739 and now #1924
