### ISSUE TITLE
`get` should work without an explicit `path` argument

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1119]
This came up in #1113. No `path` should refer to the entire dataset. This works in `create`,  `unlock`, with #1118 also in `uninstall` so it should also work with `get`.

**Comment by yarikoptic** [comment]
What do you mean by `No path should refer to the entire dataset`? Sure thing we want to be able to be able to specify paths pointing to entire datasets in get, install, etc

**Comment by mih** [comment]
To conclude this one:

`datalad get -d someds` should be equivalent to `datalad get -d someds .`
