### ISSUE TITLE
Warning on file names with trailing spaces required

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#113]
Just a reminder regarding "lintian" commands to warn about cross-platform issues.
On windows a file "something " is the very same file as "something". This is not handled correctly by git, which gets confused by this.

**Comment by mih** [comment]
I will close this issue. Windows has way more limitations than this. There can also be no trailing dots, no quote chars, and many more. In the past five years this issue hasn't bubbled up to the range where anyone would do anything about it.
