### ISSUE TITLE
GitRepo.add_submodule() is incompatible with direct mode

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1131]
In its core it calls `git submodule`, which does not work:

````
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'submodule', 'add', '--name', 'some/what/deeper', './some/what/deeper', './some/what/deeper'] under '/tmp/datalad_temp_test_create_subnjhdlspb'. Exit code=1. out= err=fatal: /usr/lib/git-core/git-submodule cannot be used without a working tree.
````

**Comment by bpoldrack** [comment]
Judging from that message it misses the git options, that are required for direct mode.
Will look into that one.

**Comment by bpoldrack** [comment]
How did you produce this one? I suspect `add_submodule` was called on an instance of `GitRepo` instead of an `AnnexRepo`.

**Comment by mih** [comment]
These are produced by your travis runs with direct mode enabled ;-)

**Comment by bpoldrack** [comment]
Ah - okay. So I'll find it. Thanks.
