### ISSUE TITLE
Query for "untracked files" broken in direct-mode (e.g. ok_clean_git)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1132]
Also access to `Dataset.repo.repo.untracked_files` does not work, or anything that executes:

````
git status --untracked-files
````

internally.

**Comment by bpoldrack** [comment]
FTR: Actually it's not about "untracked". `ok_clean_git` just used GitPython directly while our `AnnexRepo` class was not involved. GitPython on its own can't deal with direct mode of course.

There are several very similar things, where we perform git operations, circumventing our classes. Especially in `tests/utils.py`

**Comment by mih** [comment]
Closing in favor of #1180
