### ISSUE TITLE
*Repo.repo.is_dirty() is broken in direct_mode

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1133]
Which in turn breaks `save`. The culprit is:

````
cmdline: git -c receive.autogc=0 -c gc.auto=0 diff --abbrev=40 --full-index --raw
  stderr: 'fatal: This operation must be run in a work tree'
````

**Comment by bpoldrack** [comment]
Not sure, but there's a good chance, #1134 solves this too.

**Comment by bpoldrack** [comment]
Two things in this one:
1. I highly recommend to not use GitPython directly in toplevel functions. We should put this as a rule somewhere. None of our solutions and mechanics can come to effect this way.
2. `GitRepo.dirty` property is there already, `AnnexRepo.dirty` was introduced in `rf-repos` branch. Will fix it there to respect direct mode.

**Comment by mih** [comment]
Yeah, but #781 

Last time I looked at that, it could not do the same thing. I kept using GitPython directly in order to generate evidence on what aspects of the functionality are to be exposed.

**Comment by bpoldrack** [comment]
Yes, I'm aware and will provide a more fine grained `dirty()` for the repos.
And I'm not blaming anybody - just wanted to use the opportunity to point out, that this kind of things cause a lot of trouble.

**Comment by bpoldrack** [comment]
Note: This is related to #1180

**Comment by mih** [comment]
Done now?

**Comment by bpoldrack** [comment]
At least this flavor of the issue was dealt with.
