### ISSUE TITLE
aggregate-metadata causes git-annex over and over ask for a password

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1139]
```shell
(git)smaug:/mnt/btrfs/datasets-dev-20161125/datalad/crawl[master]git
$> datalad --dbg aggregate-metadata --guess-native-type -r
[INFO   ] aggregating meta data for <Dataset path=/mnt/btrfs/datasets-dev-20161125/datalad/crawl/crcns/aa-1> 
yoh@datasets.datalad.org's password: 
yoh@datasets.datalad.org's password: 
[INFO   ] aggregating meta data for <Dataset path=/mnt/btrfs/datasets-dev-20161125/datalad/crawl/crcns/aa-2> 
yoh@datasets.datalad.org's password: 
yoh@datasets.datalad.org's password: 
[INFO   ] aggregating meta data for <Dataset path=/mnt/btrfs/datasets-dev-20161125/datalad/crawl/crcns/ac-1> 
yoh@datasets.datalad.org's password: 
...
```
and actually then stopped for subsequent subdatasets... I guess there was something special about those that annex wanted to talk to them... unfortunately AFAIK we don't have a way to make annex avoid any network operation  for such use-cases when we don't need any network'ed information (probably here it was asking for uuid for some new remote(s))... then after it crashed (some stale git lock) and I reran -- it didn't ask again (I guess was happy already with what it knew).... still thought to bring to your attention since I think somewhere annex is not reusing the same control

**Comment by mih** [comment]
This "feature" is gone in #1630.
