### ISSUE TITLE
Switch everything to v6 repos ASAP

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1143]
I played with git annex on windows for a while, and it led me back to the realization that we need to switch all logic to v6 mode repositories ASAP. The possibility to have mixtures of locked an unlocked files, the option to have adjusted branch whose content needs to get `annex sync`'ed at some point put an additional level of complexity on the program logic -- which we are completely ignoring now. I think the longer we wait with this switch, the more we have to redo again.

For the record, here are a few pointers with essential information:

- https://git-annex.branchable.com/tips/unlocked_files/
- https://git-annex.branchable.com/git-annex-adjust/
- https://git-annex.branchable.com/git-annex-sync/

We already have a few bugs with infos and issues:

https://github.com/datalad/datalad/issues?q=v6+label%3Aannex-v6

**Comment by mih** [comment]
I am increasingly under the impression that we should ship v6 repos in unlocked state from datasets.datalad.org.

FTR: https://git-annex.branchable.com/forum/converting_a_v5_repo_to_an_always_unlocked_v6_repo/

At the same time we need to expose `annex.thin` via `install`.

**Comment by mih** [comment]
FTR: In v6 unlocked repo mode (and in any direct mode repository too!), we need to run:

````
git annex sync --no-push --no-pull
````

before we perform any checks on whether "master" is of a particular state. The above command syncs all potential changes in the "adjusted" (or "annex/direct/...." branch into the actual master -- without talking to remotes.

**Comment by mih** [comment]
Still playing with it to get some real life impression. I am doing this (https://git-annex.branchable.com/forum/converting_a_v5_repo_to_an_always_unlocked_v6_repo/) with a single repo (40k files with some 700GB of data). The `sync` part is taking ages. It passes all files individually through the clean smudge filter on commit -- we are talking hours of runtime.

Here is an impression of the commands running during the commit stage:

````
git-annex smudge --clean 'SOMEFILE'
git --git-dir=.git --work-tree=. --literal-pathspecs check-attr -z --stdin annex.backend annex.numcopies annex.largefiles --
git --git-dir=.git --work-tree=. --literal-pathspecs cat-file --batch
git --git-dir=.git --work-tree=. --literal-pathspecs cat-file --batch-check=%(objectname) %(objecttype) %(objectsize)
````

**Comment by yarikoptic** [comment]
Iirc 40k files is already a notable burden even for regular git  manipulations
-- 
Sent from a phone which beats iPhone.

**Comment by yarikoptic** [comment]
On November 26, 2016 1:18:06 PM EST, Michael Hanke <notifications@github.com> wrote:
>I am increasingly under the impression that we should ship v6 repos in
>unlocked state from datasets.datalad.org.
>
>FTR:
>https://git-annex.branchable.com/forum/converting_a_v5_repo_to_an_always_unlocked_v6_repo/
>
>At the same time we need to expose `annex.thin` via `install`.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/1143#issuecomment-263077883

I thought that the annex format we store them on remote could be different from the local clones... Was I wrong?
-- 
Sent from a phone which beats iPhone.

**Comment by mih** [comment]
> I thought that the annex format we store them on remote could be different from the local clones... Was I wrong?

If you are thinking repository indirect vs direct mode for sure. In v6 it is possible to actually commit whether a single file is locked or unlocked. I have yet to fully explore how much of that is propagated to remotes under what conditions. But in any case, for clones from datasets.d.o it is somewhat less important to protect files from getting lost/modified. Any such change is easily recovered from by reobtaining the necessary version. Going unlocked by default also addresses the "my file browser is lost in the annex store" problem.

**Comment by mih** [comment]
Git 2.11 is out with multifile smudge filtering. This should bring a major speedup for v6.

**Comment by mih** [comment]
Re discussion: here is the quote on mixing locked and unlocked files in a single repo:

> mixing locked and unlocked files
> A v6 repository can contain both locked and unlocked files. You can switch a file back and forth using the git annex lock and git annex unlock commands. This changes what's stored in git between a git-annex symlink (locked) and a git-annex pointer file (unlocked). To add a file to the repository in locked mode, use git annex add; to add a file in unlocked mode, use git add.
> If you want to mostly keep files locked, but be able to locally switch to having them all unlocked, you can do so using git annex adjust --unlock. See git-annex-adjust for details. This is particularly useful when using filesystems like FAT, and OS's like Windows that don't support symlinks.

**Comment by yarikoptic** [comment]
I think we could postpone this utopian idea for now
