### ISSUE TITLE
datalad install --shared

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1146]
(should also be in `create`): Could be just `group` to setup full group shared (rw) repository, or may be even in addition `group-ro` which would inherit group settings and assure that stuff is group readable.

the setting specified during install should be stored within `.git/config` so it could be inherited while installing sub-datasets later

**Comment by bpoldrack** [comment]
Note: within `Install` `git_clone_opts` are ignored. They need to be passed to the clone helper function and then down to `GitRepo.clone`, which has `**kwargs` for this. Implementation of a fix is just about the correct passing of options like this.

**Comment by mih** [comment]
Given https://github.com/datalad/datalad/issues/1893 it might not be useful to have this at all. Alternatively, we could offer it as a "reckless" mode. Multiple reckless-flavors are now possible with https://github.com/datalad/datalad/pull/3966

**Comment by yarikoptic** [comment]
well, not "not useful" but just a bit "dangerous" ;)
But it might (still) be needed for any centralized collaborative work (if there is no alternative permissions handling framework like of gitlab etc is there to do it).  It is not really about "reckless"ness - those are pretty much orthogonal if I see it right
