### ISSUE TITLE
GitRepo.add_submodule() should properly report .gitignore error

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1149]
This is what I get right now

````
datalad.support.exceptions.CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'submodule', 'add', '--name', 'bba/bbaa', './bba/bbaa', './bba/bbaa']' failed with exitcode 1
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'submodule', 'add', '--name', 'bba/bbaa', './bba/bbaa', './bba/bbaa'] under '/tmp/datalad_temp_tree_test_save_hierarchy591jgb5z/b/bb'. Exit code=1. out= err=The following path is ignored by one of your .gitignore files:
bba/bbaa
Use -f if you really want to add it.
````

In order to properly act upon this condition it should be reported using a dedicated exception, not a generic command error. I haven't checked, but likely this is something that needs to be introduced in other methods (like `add`) too.

**Comment by bpoldrack** [comment]
Note to myself: Check for common errors like this in except clause when calling runner. Additionally figure out, how GitPython reacts to these.
