### ISSUE TITLE
Uninstall uninstalls a top-level dataset when not desired

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1150]
````
ds.uninstall('sub', check=False)
````

will also uninstall `ds`, not just `sub`.

This is bad!

**Comment by yarikoptic** [comment]
On December 2, 2016 4:11:56 AM EST, Michael Hanke <notifications@github.com> wrote:
>````
>ds.uninstall('sub', check=False)
>````
>
>will also uninstall `ds`, not just `sub`.
>
>This is bad!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/1150

Yikea
-- 
Sent from a phone which beats iPhone.

**Comment by mih** [comment]
Well, I cannot replicate this one (anymore?). In current master. Moreover, `datalad/distribution/tests/test_uninstall.py:test_uninstall_subdataset` seem to test for exactly that already.

Either I was hallucinating, or it had something to do with the other changes in that branch. Either way: good that it doesn't happen. Closing.
