### ISSUE TITLE
Redo exceptions caused by calls to git/git-annex

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1152]
This again came to attention by #1149 

PR #1151   shows the direction to go, I think. 

Needs a better and more general way to go through search patterns and probably a proper hierarchy of exceptions:
```
CommandError -> GitCommandError ( name reserved by GitPython), AnnexCommandError
GitCommandError -> GitIgnoreError, ... whatever we need
AnnexCommandError -> NotInAnnexError, SpecialRemoteError, InsufficientNumberOfCopiesError, ... whatever
```

Plus: Catch from `Runner` as well as from GitPython.

**Comment by mih** [comment]
We have done quite well for the past 3 years without this change. Please reopen, if there is a concrete need, stating what it is. Thx.
