### ISSUE TITLE
Consider adopting _CommandBase by other (than of uninstall family) commands as well

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1161]
as briefly discussed in #1160

**Comment by mih** [comment]
I have some commit that merge that class with Interface. Will try to
extract them...

**Comment by mih** [comment]
Not sure if this needs to stay open. `Interface` has this functionality in current master now. Anyone RF'ing the API can make use of it.

**Comment by mih** [comment]
Closing, nothing to add.
