### ISSUE TITLE
*Repo.commit should report ValueError if instructed to commit untracked content

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1170]
Currently it looks like this:

````
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'commit', '-m', 'set of new files', '/tmp/datalad_temp_clone_url_g9n4z4od/one.txt', '/tmp/datalad_temp_clone_url_g9n4z4od/two.txt'] under '/tmp/datalad_temp_clone_url_g9n4z4od'. Exit code=1. out= err=error: pathspec '/tmp/datalad_temp_clone_url_g9n4z4od/one.txt' did not match any file(s) known to git.
error: pathspec '/tmp/datalad_temp_clone_url_g9n4z4od/two.txt' did not match any file(s) known to git.
````

without such exception users (as in higher-level functions) would need to test upfront whether something is known (which can be pretty expensive) or would not be able to tell what kind error happened.

Affects the implementation of #1169

**Comment by bpoldrack** [comment]
`*Repo.commit` has a `careless` parameter now, that allows to not fail at all in these cases or raise a ValueError otherwise.
