### ISSUE TITLE
*Repo.commit() should get flag whether or not to fail when there is nothing to commit

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1171]
In the spirit of a result-oriented error behavior, it can be useful to be able to call `commit()` and expect success even if no new commit was made. The "careless" mode could be off by default.

**Comment by bpoldrack** [comment]
Note to myself: See `save_dataset` in `datalad/interface/utils.py`

**Comment by mih** [comment]
OK, let's close this in favor of #1291 -- the two are linked already.
