### ISSUE TITLE
ok_clean_git() broken in direct mode

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1180]
https://travis-ci.org/datalad/datalad/jobs/191620349

only one test running here and all indirect ones are fine.

````
======================================================================
FAIL: datalad.distribution.tests.test_uninstall.test_kill
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 536, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/distribution/tests/test_uninstall.py", line 339, in test_kill
    ok_clean_git(ds.path)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 183, in ok_clean_git
    ok_(repo.head.is_valid())
AssertionError: None
````

**Comment by mih** [comment]
Moving the following content from #1132 -- duplicate of this never one with better info.

---------------

Also access to Dataset.repo.repo.untracked_files does not work, or anything that executes:

````
git status --untracked-files
````
internally.

**Comment by mih** [comment]
Also see @bpoldrack comment: https://github.com/datalad/datalad/issues/1132#issuecomment-264080051

**Comment by bpoldrack** [comment]
Note: For direct mode there is `git annex status --json`, which could be used. Didn't check for V6 yet. Additionally would need to check whether looking for untracked files that way would involve the same performance issue, @mih mentioned somewhere.

**Comment by bpoldrack** [comment]
Generally, I'd like `ok_clean_git` to rely on `GitRepo.dirty` or `AnnexRepo.dirty` respectively.
For that to work properly in direct mode and especially V6, we need to decide, what status we would like to consider "dirty". Is an uncommitted type change due to `git annex unlock` in V6 something to be counted as "dirty"? What do you think, @mih ?

**Comment by mih** [comment]
In the sense of "a clean git" yes.

Be aware of #1153

**Comment by bpoldrack** [comment]
Right, thanks for linking this!

**Comment by mih** [comment]
This is also leading to this kind of error:

````
======================================================================
ERROR: datalad.distribution.tests.test_install.test_guess_dot_git(True,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 401, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 473, in newfunc
    return tfunc(*(args + (path, url)), **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 536, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/distribution/tests/test_install.py", line 118, in _test_guess_dot_git
    ok_clean_git(tdir, annex=annex)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 185, in ok_clean_git
    eq_(sorted(repo.untracked_files), sorted(untracked))
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/git/repo/base.py", line 615, in untracked_files
    return self._get_untracked_files()
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/git/repo/base.py", line 641, in _get_untracked_files
    finalize_process(proc)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/git/util.py", line 341, in finalize_process
    proc.wait(**kwargs)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/git/cmd.py", line 291, in wait
    raise GitCommandError(self.args, status, errstr)
GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git status --porcelain --untracked-files
  stderr: 'fatal: This operation must be run in a work tree
````

**Comment by bpoldrack** [comment]
Currently fixing `Repo.dirty` in PR #1231 

I'd propose to simply replace the use of `ok_clean_git(repo.path)` by `ok_(not repo.dirty)` in the tests.
While the implementation of `ok_clean_git` currently gives detailed information what exactly isn't clean if the assertion is not true, this doesn't work that way for direct mode and V6.
I think the pain of having it not work at all currently is more important than figuring out a way to shorten debugging time by a few seconds.
Agree, @yarikoptic , @mih ?

**Comment by mih** [comment]
I think that would be an overreaction. Why not keep `ok_clean_git()` do what it does now, unless it encounters a direct mode repo. In the latter case it could do something less or different (like you suggested). I am increasingly under the impression that direct mode is something that won't be with us for too long. But we should nevertheless have some basic support for it.

**Comment by bpoldrack** [comment]
Right, but guess taht part won't work for V6 as well

**Comment by mih** [comment]
This is likely true, but we still have a lot to learn which parts of out logic are invalid for V6. Disabling any errors without having identified the root causes will not do us a favor. For direct mode OTOH I think we have clearly identified the problem (a work tree that is not a work tree).

**Comment by bpoldrack** [comment]
Tried to keep current behaviour in PR #1231. (https://github.com/datalad/datalad/pull/1231/commits/2550682cdcfb93427ea39415987d77797368713f)

Didn't manage to do it entirely yet.

But I suspect you misunderstood my intention, @mih: I didn't propose to disable any error! Instead the consequence would be to loose the functionality of `ok_clean_git` to specify modifications, that are ignored when determining whether the repo is clean and the more detailed output when `ok_clean_git` fails. But it would still consider the very same things to be (not) clean.
