### ISSUE TITLE
annex --json doesn't report anything when get fails to get a file from a specified source

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1186]
Found this in `test_get.py` -- better becomes an issue:

````
    # TODO: annex --json doesn't report anything when get fails to do get a
    # file from a specified source, where the file isn't available from.
    # File report for Joey (plus other failures like not existing when
    # called with --json)
````

**Comment by mih** [comment]
@yarikoptic @bpoldrack awareness ping!

**Comment by yarikoptic** [comment]
For non existing, I think I have added handling recently while processing street output of json call.
Don't remember if I saw the one about non availability

**Comment by mih** [comment]
I have implemented high-level reporting for things that annex is silent about in #1485
