### ISSUE TITLE
remote sensing (with specification of git to use) and other properties

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1188]
To continue https://github.com/datalad/datalad/pull/1182#issuecomment-272613416  discussion.  I think we might end up with remote sensing indeed, but IMHO it will not be only for git invocations but for any command since those might invoke git directly or not so might need to be there not only for `create-sibling` probably

Related issues:

- [x] #1192 
- [x] #1240 
- [x] #1241 Git(-annex) version sensing and targeted execution

**Comment by mih** [comment]
We might actually need a whole remote sensing kit. Just found a note in `create_sibling` asking for remote sensing of the path separator.

**Comment by mih** [comment]
From my PoV this is done.
