### ISSUE TITLE
Better exception(s) for paths outside of a repo

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1200]
We already have `PathOutsideRepositoryError`, which is to be thrown if a repo was asked to operate on a path outside of its scope. Therefore this exception currently expects a repo to be specified.
In `Interface._prep()` (`datalad/interface/base.py`) we also need a very similar exception without a specific repository. Additionally such an exception needs to be able to properly deal with reporting multiple paths. We should either make `PathOutsideRepositoryError` more general or have base exception for it in order to not have several not related exceptions, which basically indicate the same thing.

**Comment by mih** [comment]
Obsolete now, such errors are simply 'error' results with an explanatory message.
