### ISSUE TITLE
RF `--since` out of `publish` and into `AnnotatePaths`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1202]
Major obstacle for `publish` RF is the --since functionality. It implies performing dataset tree traversal twice, once in `_prep()` for input argument sorting, and then again for `--since`.

After discussing this with @bpoldrack for a brief moment it seems that it may be useful to factor this functionality into `_prep()` itself. Consequently, `--since` could become more generally used. However, not many things are obvious use cases. I can only think of `get`, i.e. "get data for all files that were changed since ...."

What do you think @yarikoptic ?

**Comment by mih** [comment]
I think I see a way to RF this into a standalone function that doesn't need to query for subdatasets again, and can be applied to filter path dicts...

**Comment by yarikoptic** [comment]
implementation wise -- I have no opinion ATM.  Interface wise -- I just know that I do need it direly ;)

**Comment by mih** [comment]
Draft now in #1203

**Comment by mih** [comment]
Done now.
