### ISSUE TITLE
Provide `diff` command

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1217]
We need `diff`. We currently use GitPython's diff, but it is kinda heavy and not flexible enough (e.g. direct mode submodules). We also need `status`, but `status` is pretty much a diff (ignoring the patch generation) of the workdir against HEAD. Ideally, we would like to have enough flexibility to also be able to do as little as `ls` (with recursion).

Plan (based on #1506):

- [x] wrap `git diff --raw SOMETHING`, where SOMETHING is anything that Git supports
- [x] provide results via a generator that yields annotated paths (`git diff` readily informs us about the pre/post nature of any path...)
- [x] support recursion in the standard fashion
- [ ] re-use `AnnexRepo.get_status()` tests

**Comment by mih** [comment]
Any plans anyone to make this happen? @yarikoptic @bpoldrack

**Comment by yarikoptic** [comment]
Fwiw Myself I just use gitpython's diff in the crawler... What I at times feel need for is diff which works also for annexed files content with some configurable diff per type of file... But that is our of scope of this over I guess.

**Comment by mih** [comment]
I came up with a basic wrapper around `git diff` that yields annotated paths. Will turn into a proper command next. PR will follow.

**Comment by mih** [comment]
From #1506:

````
mih@meiner /tmp/datasets.datalad.org (git)-[master] % datalad --on-failure continue diff --revision HEAD~2..HEAD~1 -r
modified: .datalad/meta/crcns/meta.json(file)
[WARNING] fatal: bad revision 'HEAD~2..HEAD~1' [diff(/tmp/datasets.datalad.org/TEST2)] 
modified: crcns/aa-2(dataset)
modified: crcns/aa-1/.datalad/meta/meta.json(file)
modified: crcns/aa-2/.datalad/meta/meta.json(file)
added: crcns/aa-3/.datalad/meta/meta.json(file)
modified: crcns/ac-1/.datalad/meta/meta.json(file)
modified: crcns/ac-2/.datalad/meta/meta.json(file)
<snip>
added: crcns/hc-2/ec016.582/ec016.582.dat.tar.gz-b(file)
added: crcns/hc-2/ec016.582/ec016.582.dat.tar.gz-c(file)
added: crcns/hc-2/ec016.582/ec016.582.mpg.tar.gz(file)
added: crcns/hc-2/ec016.582/ec016.582.tar.gz(file)
modified: crcns/hc-3/.datalad/meta/meta.json(file)
modified: crcns/hc-4/.datalad/meta/meta.json(file)
<snip>
````

**Comment by mih** [comment]
Done with #1506
