### ISSUE TITLE
`get` should report which files it failed to get.

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1221]
At present it does things like

````
[INFO   ] Getting 17732 items of dataset <Dataset ...> ... 
[INFO   ] Actually getting 13416 files 
                                                                                                                              
Tried to get 13416 files. Got 12529.  Failed to get 887.
````

It seems redundant to have the difference count, failure count and success count. And I have no idea which ones are missing (all from the same remote?, all from the same subject?, no useful hint to start looking for the cause of the failure).

Related to #1218

**Comment by yarikoptic** [comment]
>    It seems redundant to have the difference count, failure count and success
>    count.

It is redundant but helpful to avoid doing metal algebra on sometimes long numbers

as for absent clarity -- agree, and we had discussion before about some kind of a "verbose" mode

**Comment by mih** [comment]
Target for `get` RF in #1350

**Comment by mih** [comment]
With #1350 this is no longer an issue:

In this example `clone` is a dataset that is present, has two annexed files, of which one has no sibling that has its content:
````
% datalad --output-format json --on-failure continue get clone
{"status": "notneeded", "action": "install", "type": "dataset", "path": "/tmp/getoutput/clone"}
{"status": "ok", "action": "get", "path": "/tmp/getoutput/clone/here", "type": "file", "annexkey": "MD5E-s0--d41d8cd98f00b204e9800998ecf8427e"}
{"status": "error", "action": "get", "path": "/tmp/getoutput/clone/nothere", "type": "file", "annexkey": "MD5E-s5--7e22497dabca0e6910ff014c8097821e"}
[ERROR  ] could not perform all requested actions: Command did not complete successfully [{'status': 'error', 'annexkey': 'MD5E-s5--7e22497dabca0e6910ff014c8097821e', 'action': 'get', 'path': '/tmp/getoutput/clone/nothere', 'type': 'file'}] [utils.py:generator_func:1032] 
-> exit 1
````

**Comment by mih** [comment]
Current master now yield results for individual files and provides a summary in addition.
