### ISSUE TITLE
Errors due to nice hardware ;-)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1222]
Result of `datalad get` when parts of the content are already present and the rest could be obtained real fast.

````
[ERROR  ] n (-139366835) cannot be negative [_tqdm.py:update:795] (ValueError) 
````

Should we have `--slow`? ;-)

**Comment by yarikoptic** [comment]
gy
1. does it lead to complete crash of datalad? (so we should guard then with try/except)
2. what version of tqdm you have?

**Comment by mih** [comment]
I don't think it crashed. On that machine tqdm is version 4.8.4.

**Comment by yarikoptic** [comment]
if not crushed -- then could sure be our fault or tqdm's ;)  if reproducible somehow -- would be nice to try with freshier tqdm (looking into building a backport atm, should build iirc since Sandro I think disabled performance tests which previously were failing in our builds)

**Comment by yarikoptic** [comment]
FWIW -- super fresh backport build of tqdm 4.11.2 was uploaded to neurodebian

**Comment by mih** [comment]
Thanks!

**Comment by yarikoptic** [comment]
ok -- running into the same (?) case now ... I think it is our fault somewhere ... really need to have it fixed, and managed to reproduce so will do that now.

**Comment by yarikoptic** [comment]
ok -- after some pain (which caused me to reboot laptop... no more tmpfs based /tmp for me!!! enough) I caught it "by hand" ;-): http://git-annex.branchable.com/bugs/__34__byte-progress__34___could_jump_down_upon_initiating_re-download_--_report_actual_one_first__63__/?updated   
will workaround for now by completely skipping the first update reported by annex but also add a safeguard so we do not crash if some other reason leads to it
