### ISSUE TITLE
`add_sibling` -> `configure_sibling`?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1235]
I was asking myself whether this would be a more appropriate name. Adding is mostly done through `create-sibling` commands, but reconfiguration will more frequently be done via this command. More issue aspects:

- [ ] Git considers a remote to exist as soon as there is a single `remote.<name>.something` variable. We OTOH can do very little without at least a url.
- [ ] In addition to the above, `add_sibling` requires `--force` to configure anything once a remote is already known. It would make sense IMHO to be able to reconfigure some aspects and still be able to have it test that the major setting -- the url -- stays unmodified.
- [ ] GitPython will fail to fetch from a remote unless there is a `remote.<name>.fetch` config variable. At present we do not check that configuring a sibling always results in such a var to be set.

**Comment by yarikoptic** [comment]
Well... I hear you, but it is  `git remote add` ... All the custom diversions from API semantics people might be familiar with is IMHO not benefiting... Having said that I am yet to check what configuration changes this command does ATM in comparison to create-sibling, or what could be moved into it

**Comment by mih** [comment]
OK, so you want to keep `add_sibling`. So be it (although the argument is lame: `git remote add` is one of many subcommands for `remote`).

This means we need another command: `(re)configure-sibling` it needs to do all things "what to fetch", "what to push", "what to prefer".... that came up in the context of `update` and `publish`. Its interface needs to be duplicated in `add-sibling`, and in `create-sibling`, to some degree also in `create-sibling-github`. Don't have a full list of related issues, but one is #712.

**Comment by bpoldrack** [comment]
I lean towards renaming `add_sibling`. However, if @yarikoptic wants an explicit `add_sibling` for consistency with `git`, it should call `configure_sibling` internally with a safe guard switch to make sure the sibling doesn't exist already. It's just a short cut and I don't really care whether we have it.

Re GitPython's fetch needs a `remote.<name>.fetch` entry: This is true only, if no refpec was passed. Just saying to not let that potentially confusing statement be uncommented. :-)

Otherwise: I agree on what `configure-sibling` should be able to do.

**Comment by yarikoptic** [comment]
I am ok to the plan of action such as
- get a sparkling new configure_sibling
- keep add_sibling as a shim with a proper deprecation warning.  We really should start adding those warnings and Changelog entries on what has changed in the API -- I keep running into being unable, sometimes with silent/absent error (see #1309), to perform what I could have done before, and needing to dig/ask/etc to figure out what I should do now.  Thus I would vote against renaming a command to another one to merely improve some semantical notion without even leaving any deprecation trail.

**Comment by bpoldrack** [comment]
Re deprecation warning/changelog: I agree. It's a point, we should start to care for.

**Comment by yarikoptic** [comment]
we might then want to adopt instead of my ad-hoc one -- better one Matthew Brett came up with for nibabel project:  https://github.com/nipy/nibabel/blob/HEAD/nibabel/deprecator.py
