### ISSUE TITLE
SSHRI ignores port

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1242]
````
>>> SSHRI(hostname='remote', port=2222, username='mih', path='home').as_str()
mih@remote:home
````

**Comment by yarikoptic** [comment]
I guess because it can't be placed into the "ssh RI" (which uses designation of : to separate out the path as scp does) and need to be accessed specifically from `.port`?

**Comment by mih** [comment]
Shouldn't it then warn? All those classes warn all the time, when something changes shape....

**Comment by mih** [comment]
Ignore me. Will close.
