### ISSUE TITLE
Git-annex bundled Git may not behave like system Git (i.e. hooks/ directory missing)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1251]
TL;DR:

> I suspect that Git from git-annex only comes with the actual tools, but not all the convenience grease. `hooks/` content is typically just sample files by default, and I guess they just aren't available.
> So we should not assume that things have to look identical.

In #1237 we see weird behavior of `git init` that inits a repo without creating the complete set of usual directories under `.git/`. Here is how to get this outside datalad:

````
% ssh localhost 'mkdir /tmp/s3; git -C /tmp/s3 init'
Initialized empty Git repository in /tmp/s3/.git/
% tree -d s3/.git
s3/.git
├── branches
├── hooks
├── info
├── objects
│   ├── info
│   └── pack
└── refs
    ├── heads
    └── tags

% ssh localhost 'export "PATH=/usr/lib/git-annex.linux:$PATH"; mkdir /tmp/s5; git -C /tmp/s5 init'
Initialized empty Git repository in /tmp/s5/.git/
% tree -d s5/.git
s5/.git
├── objects
│   ├── info
│   └── pack
└── refs
    ├── heads
    └── tags
````

needs no SSH to get there:

````
% export "PATH=/usr/lib/git-annex.linux:$PATH"; mkdir /tmp/s8; git -C /tmp/s8 init
Initialized empty Git repository in /tmp/s8/.git/
tree -d s8/.git
s8/.git
├── objects
│   ├── info
│   └── pack
└── refs
    ├── heads
    └── tags
````

Git versions are both recent-ish but not identical.

````
% export "PATH=/usr/lib/git-annex.linux:$PATH"; git --version
git version 2.10.2
% /usr/bin/git --version
git version 2.11.0
````

After upgrading git-annex to 6.20170101+gitg93d69b1-1~ndall+1 the version is identical, but the behavior still isn't.

````
% export "PATH=/usr/lib/git-annex.linux:$PATH"; git --version
git version 2.11.0
% export "PATH=/usr/lib/git-annex.linux:$PATH"; mkdir /tmp/s9; git -C /tmp/s9 init
Initialized empty Git repository in /tmp/s9/.git/
% tree -d s9/.git
s9/.git
├── objects
│   ├── info
│   └── pack
└── refs
    ├── heads
    └── tags
````

**Comment by mih** [comment]
I might have found another side-effect of this:

````
File does not exist: .../demoannex/.git/info
````

As a result of `create-sibling`.

**Comment by mih** [comment]
It seems to get worse and worse. Git annex `copy --to` fails with

````
copy probe (checking target1...) (not found) failed
git-annex: copy: 1 failed
````

on the server I see `.git/annex` but no `.git/annex/objects`.

**Comment by bpoldrack** [comment]
Is it a matter of using the bundled git from `/usr/lib/git-annex.linux` or does it hapen with plain git 2.11.0, too?

**Comment by mih** [comment]
i don't know

**Comment by mih** [comment]
The hour of information is over.
