### ISSUE TITLE
Why is it important to be notified when URL quoting happens?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1253]
From my logs:

````
[WARNING] Parsed version of URL 'http://kumo.ovgu.de/%7Emih/demoannex' differs from original 'http://kumo.ovgu.de/~mih/demoannex' 
````

Do we need that? With a warning? Can we go to defcon 2?

**Comment by mih** [comment]
Please let me know whether this can be silenced @bpoldrack @yarikoptic

**Comment by yarikoptic** [comment]
may be move it indeed to DEBUG level for now... theoretically str of parsed should always be identical to original but in this case (explicit `~` vs encoded) - not sure, thus I guess it is safe.  but there could be spots where such warnings would hint to omitted  portion of the url... well -- we could rely on tests of cause ;-)
