### ISSUE TITLE
save should use PWD as reference dataset if none is given and PWD contains one

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1254]
```shell
(git)smaug:/mnt/btrfs/datasets/datalad/crawl/labs/tarr/face_place[master]git
$> git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   README3_0.pdf
        new file:   README3_0.txt
        new file:   datapackage.json

(git)smaug:/mnt/btrfs/datasets/datalad/crawl/labs/tarr/face_place[master]git
$> datalad save -S -m "Added README and basic meta-data for the dataset" -a
cached/staged changes:
 README3_0.pdf    |  1 +
 README3_0.txt    | 57 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 datapackage.json | 14 ++++++++++++++
```
those are new files which were staged to be added (may be that matters that they didn't exist in index before)

using current master 0.4.1-330-gc3f4ad0

**Comment by yarikoptic** [comment]
rright -- probably I had to specify the paths for files I had to save (despite -a) -- then it kinda works (different case already):
```shell
(git)smaug:/mnt/btrfs/datasets/datalad/crawl/labs/tarr/face_place[master]git
$> datalad save -S -m "fixed up json" -a datapackage.json
Exception IOError: IOError("Lock at u'/mnt/btrfs/datasets/datalad/crawl/openfmri/ds000210/.git/index.lock' could not be obtained",) in <bound method AnnexRepo.__del__ of <AnnexRepo path=/mnt/btrfs/datasets/datalad/crawl/openfmri/ds000210 (<class 'datalad.support.annexrepo.AnnexRepo'>)>> ignored
Total: 100%|███████████████████████████████████████████████████████████████████| 939/939 [00:00<00:00, 7.05KB/s]
Saved state: fc494114731ef116d50f297c081f122fef881104 for <Dataset path=/mnt/btrfs/datasets/datalad/crawl/labs/tarr/face_place>
Saved state: 6deb77618d1652f9b782939e0a01f64e3d78b583 for <Dataset path=/mnt/btrfs/datasets/datalad/crawl/labs/tarr>
Saved state: 9c88abf5a9e89a11a91cdffc2161b67d16908d5f for <Dataset path=/mnt/btrfs/datasets/datalad/crawl/labs>
Saved state: 7a4bd3aed58a6a8065586edbfad237e6e346e681 for <Dataset path=/mnt/btrfs/datasets/datalad/crawl>
datalad save -S -m "fixed up json" -a datapackage.json  19.41s user 12.80s system 93% cpu 34.502 total
```
and you can see that
-  it seems to do the correct thing 
- it runs really wild -- why to go into openfmri ? (probably all those get_submodules calls or smth like that)
- it takes a while (20sec)

**Comment by yarikoptic** [comment]
I also note that `-S` effect on message while saving in super-datasets seems have lost an "origin:" message portion it had before for where that "save" was originating from. e.g. on top repository I have got now:
```
    fixed up json

 labs | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```
which you could compare to how they looked before:
```
    initial data [origin: dicoms/dartmouth-phantoms/bids_test5-20170120]
```
which I considered informative already quite few times

**Comment by mih** [comment]
re "doesn't save": I guess with `datalad save -d . ...` is would. We should put this behavior back (i.e. no path and no dataset -> try looking into PWD).

**Comment by mih** [comment]
re "origin message lost": Yes, this is known. Previously, this information was readily available, as `save` was call recursively. Now it is unclear (at the very least) what the precise reason for a dataset being saved actually is. Could be an input path, the content of a directory of an input path, dataset recursion, could be `-S`, could be any combination of the above. Currently, I have no plans to put this kind of complexity back in -- at least not until the foundations stand.

**Comment by yarikoptic** [comment]
> re "origin message lost": Yes, this is known.
wasn't known to me and IMHO if "new and improved" doesn't allow for what was previously possible quite easily - it is `HUGE!` ;)
