### ISSUE TITLE
publish --since=None (default) should consider only changes since last push

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1256]
Originally reported in https://github.com/datalad/datalad/issues/1250#issuecomment-277379955

The point of having --since is to minimize amount of work needed based on the changes since the last push, while being able to force it to consider more changes by providing explicit value for --since.  Recent refactoring in publish seems removed that magic, and now with empty since nothing might get published at all, although current one was ahead of the remote

here is a copy from that other report:
```shell
(git)smaug:/mnt/btrfs/datasets/datalad/crawl[master]git
$> datalad publish --to=datalad-public -r
Nothing was published
```
which is really sad since
```shell
$> git lg datalad-public/master..master 
* 624430e - (HEAD -> master) [DATALAD] aggregated meta data (24 minutes ago) [Yaroslav Halchenko]
* ae4afa5 - [DATALAD] auto-saved changes (26 minutes ago) [Yaroslav Halchenko]
* 7a4bd3a - fixed up json (34 minutes ago) [Yaroslav Halchenko]
* 3b37735 - [DATALAD] aggregated meta data (7 days ago) [Yaroslav Halchenko]
* 4a9e730 - [DATALAD] auto-saved changes (7 days ago) [Yaroslav Halchenko]
```
and so `--since` should have done correct detection as it did before (I think)... and indeed probably since now is handled only if explicitly specified.  So I deactivated virtualenv and went back to released 0.4.1, and it did the right thing:
```shell
$> datalad publish --to=datalad-public -r
[INFO   ] Publishing <Dataset path=/mnt/btrfs/datasets/datalad/crawl/labs/haxby/raiders> to datalad-public 
[INFO   ] 3bf7193..07861d6
|  
[INFO   ] f5d4b54..df51dc4
|  
[INFO   ] Publishing <Dataset path=/mnt/btrfs/datasets/datalad/crawl/labs/haxby> to datalad-public 
[INFO   ] c88cc54..f0f80c2
|  
[INFO   ] Publishing <Dataset path=/mnt/btrfs/datasets/datalad/crawl/labs/mitchell/science2008> to datalad-public 
[INFO   ] a1bb300..514aa4a
...
```

**Comment by mih** [comment]
Cannot say that I completely understood the issue. But in `get --since` I am observing undesired behavior that I am studying right now. Let's hope this is the same problem.

**Comment by yarikoptic** [comment]
issue was that it published nothing whenever it should have published a number of unpublished commits

**Comment by bpoldrack** [comment]
I looked into it and at first it seemed to happen for me, too. That's why I was commenting on #1237 a bit too fast ;-)
But: I was wrong. Actually the current implementation does, what it is supposed to do, I think. Problem was: I missed an error message, since it's on debug level ATM. Push simply failed, because I was publishing to a dataset, that wasn't set up by `create-sibling` and therefore lacked `receive.denyCurrentBranch updateInstead` config setting.
@yarikoptic : Would you mind trying this with log level DEBUG?

**Comment by bpoldrack** [comment]
FTR: With proper config on remote end, it worked fine for me.

**Comment by mih** [comment]
I agree, otherwise it should have popped up in the tests too.

Can we somehow read out a "version" of the setup we have on the other side? Remote confige variable query....? This way we could given meaningful errors when an upgrade is needed.

**Comment by yarikoptic** [comment]
Next time I have something to push of this kind I will check with DEBUG level.  but as I have shown in the original report using previous version I have managed to publish just fine, so it doesn't look to me as being `receive.denyCurrentBranch` setting issue... moreover:
```shell
(git)falkor:/srv/datasets.datalad.org/www[master]git
$> git submodule foreach --recursive git config --get receive.denyCurrentBranch
Entering 'crcns'
updateInstead
Entering 'crcns/aa-1'
updateInstead
Entering 'crcns/aa-2'
updateInstead
Entering 'crcns/ac-1'
updateInstead
Entering 'crcns/ac-2'
updateInstead
Entering 'crcns/alm-1'
...
```
ie they all have it set seems to me since they were created using create-sibling.

**Comment by mih** [comment]
It is not about whether you used `create-sibling`, but whether you used a `create-sibling` that found and used the bundled `git` in the remote end.

**Comment by yarikoptic** [comment]
unlikely it was such a new one.

**Comment by bpoldrack** [comment]
> Can we somehow read out a "version" of the setup we have on the other side? Remote confige variable query....? This way we could given meaningful errors when an upgrade is needed`

As long as we are talking an SSH remote, we can look at the remote's config. I don't know a way for a HTTP remote ATM.

**Comment by mih** [comment]
I don't think that is true. How can we read the Github remote config via
SSH, for example?

**Comment by bpoldrack** [comment]
How about` SSHConnector('cat .git/config')` or sth quite similar?

**Comment by bpoldrack** [comment]
Oops. GitHub! I don't know. Didn't look into what the API provides.

**Comment by yarikoptic** [comment]
FYI: I have updated git-annex (and thus bundled git) as well on falkor, so hopefully next publish goes smoothly... if it does -- I will close this

**Comment by yarikoptic** [comment]
it kinda worked so closing for now
