### ISSUE TITLE
summarize changes since 0.4.1 in the CHANGELOG

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1270]
1. should become 0.5.0
2. there were lots of changes in behavior and some in API IIRC.  It would be difficult if not impossible to summarize them by reviewing logs/changes later on (currently we have 599 commits since 0.4.1)

@mih and @bpoldrack -- since you have a better idea of what changes were done, could someone list those at least at the highest level in CHANGELOG, in particular changes in behavior of `save` and anything else

**Comment by mih** [comment]
Nobody touched `update` yet, `publish` is still incomplete and buggy, `install` .... well, meta data is a mess.

Overall, I am not confident that we can get basic functionality implemented without more major RF. I am against a release unless I get a written and signed statement that nobody will complain about break of API or functionality.

**Comment by mih** [comment]
I consider it critical that we decide on and implement a return value concept for a new release.
