### ISSUE TITLE
publish seems to publish data "by default" now?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1274]
So -- did manage to create remote sibling (see #1273 ), noted btw that none of the 'push' settings aren't yet set in .git/config for that remote (thought that we have had that settled already, I guess I was wrong), and decided to publish
```shell
(venv)mvdoc@smaug /mnt/btrfs/dbic/inbox/bids (master) $ cat Wheatley/Beau/.git/config            
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[submodule "1007_personality"]
        url = /mnt/btrfs/dbic/inbox/bids-test/Wheatley/Beau/1007_personality
[remote "rolando"]
        url = ssh://rolando.cns.dartmouth.edu/inbox/BIDS/Wheatley/Beau
        fetch = +refs/heads/*:refs/remotes/rolando/*
(venv)mvdoc@smaug /mnt/btrfs/dbic/inbox/bids (master) $ cd -
/mnt/btrfs/dbic/inbox/bids/Wheatley/Beau/1007_personality
(venv)mvdoc@smaug /mnt/btrfs/dbic/inbox/bids/Wheatley/Beau/1007_personality (master) $ datalad publish --to=rolando -r                                                                                                
[INFO   ] Publishing <Dataset path=/mnt/btrfs/dbic/inbox/bids/Wheatley/Beau/1007_personality> to rolando 
[INFO   ] Publishing data of dataset <Dataset path=/mnt/btrfs/dbic/inbox/bids/Wheatley/Beau/1007_personality> ... 
```
and now staring at the terminal (oh those lovely progress bars -- where are you?) and data meanwhile is flowing...
here actually it is intended for data to eventually being transfered but I do not think I have set it up for that and feels like logic in datalad some where is flawed... I will check whenever it is done copying on some other repository I guess or there is some obvious explanation?

**Comment by mih** [comment]
FTR: I have never worked on those progress bars, they are very low on my list of things to learn.

issue 1: push vars are set by publish when there is nothing set yet.

issue2: I don't have a good concept what I am supposed to discover in this Rohrschach test. Your hands seem OK in size -- don't worry ;-) If that 1007 is your personality and you have no backup, go see a shrink immediately!!!

**Comment by mih** [comment]
Just realized that this is a question: No publish doesn't publish data by default now, it did that before. Of course it depends on what "before now" you compare against.

**Comment by bpoldrack** [comment]
FTR: You listed `Wheatley/Beau/.git/config`, @yarikoptic. But what would be interesting instead is `Wheatley/Beau/1007_personality/.git/config`.

**Comment by yarikoptic** [comment]
rright @bpoldrack
```shell
 $> cat Wheatley/Beau/1007_personality/.git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[annex]
	thin = true
	uuid = 116be361-f85f-4132-9e99-70ea0dea6834
	version = 5
[remote "rolando"]
	url = ssh://rolando.cns.dartmouth.edu/inbox/BIDS/Wheatle/Beau/1007_personality
	fetch = +refs/heads/*:refs/remotes/rolando/*
	annex-ignore = false
	annex-uuid = 5fa6fdf9-7d06-4372-b654-4c80cc963cd9
	push = master
	push = git-annex
```
if that matters ;)
2 @mih: "before now" is the behavior of the last released version (0.4.1). If I start publishing all the data to datasets.datalad.org -- that would be a "DISASTER!" label since I must not publish data for some datasets (those requiring authentication to fetch the data from site of origin)

**Comment by yarikoptic** [comment]
so to some degree it boils down to us finally setting appropriate "preferred-content" for git annex siblings, as it was just discussed briefly on hangout and present in summary issue https://github.com/datalad/datalad/issues/1280

**Comment by mih** [comment]
re publish by default: I have no problem seeing to need for that, but @yarikoptic @bpoldrack please enlighten me what the exact nature of the switch was that turned publication of file content on and off. Here is the code

https://github.com/datalad/datalad/blob/94a721d6c31b6ca7e4b583154e1aadcd0457342e/datalad/distribution/publish.py

and it not clear to me. Hence, I cannot quickly put the logic back into the new implementation. In general, we should move to what we talked about today.

**Comment by yarikoptic** [comment]
I believe before it was assumed that specifying some `--annex-copy-opts`  (e.g. `.`) to publish would trigger the annex copy

**Comment by yarikoptic** [comment]
since issue is there I am reopening... here is a verified quickly example of data being published by default now -- I will leave it to the other interested party to inspect behavior in the released version
```shell
$> datalad create test-source 
[INFO   ] Creating a new annex repo at /tmp/test-source 
                                                                                 
                                                                                 
Created dataset at /tmp/test-source.
(dev) 2 11559.....................................:Fri 10 Feb 2017 01:19:00 PM EST:.
hopa:/tmp
$> cd test-source
W: git-annex repositories not (yet) supported in the prompt
(dev) 2 11560.....................................:Fri 10 Feb 2017 01:19:01 PM EST:.
hopa:/tmp/test-source
$> echo 123 > 123
(dev) 2 11561.....................................:Fri 10 Feb 2017 01:19:04 PM EST:.
hopa:/tmp/test-source
$> datalad add 123
                                                                                 
Added /tmp/test-source/123
(dev) 2 11562.....................................:Fri 10 Feb 2017 01:19:07 PM EST:.
hopa:/tmp/test-source
$> datalad create-sibling -s target ../test-target
[ERROR  ] Unsupported SSH URL: '../test-target', use ssh://host/path or host:path syntax [create_sibling.py:__call__:344] (ValueError) 
(dev) 2 11563 ->1.....................................:Fri 10 Feb 2017 01:19:17 PM EST:.
hopa:/tmp/test-source
$> datalad create-sibling -s target ssh://localhost/tmp/test-target 
[INFO   ] Connecting ... 
[INFO   ] Creating target dataset /tmp/test-source at /tmp/test-target 
[INFO   ] Adjusting remote git configuration 
[INFO   ] Enabling git post-update hook ... 
(dev) 2 11564.....................................:Fri 10 Feb 2017 01:19:30 PM EST:.
hopa:/tmp/test-source
$> datalad publish --to test-target  
[ERROR  ] Unknown target sibling 'test-target' for <Dataset path=/tmp/test-source> [publish.py:__call__:353] (ValueError) 
(dev) 2 11565 ->1.....................................:Fri 10 Feb 2017 01:19:42 PM EST:.
hopa:/tmp/test-source
$> datalad publish --to target     
[INFO   ] Publishing <Dataset path=/tmp/test-source> to target 
[INFO   ] Publishing data of dataset <Dataset path=/tmp/test-source> ... 
1 item was published:
Dataset: /tmp/test-source

(dev) 2 11566.....................................:Fri 10 Feb 2017 01:19:48 PM EST:.
hopa:/tmp/test-source
$> ls -l /tmp/test-target/
total 0
lrwxrwxrwx 1 yoh yoh 108 Feb 10 13:19 123 -> .git/annex/objects/pF/Zf/MD5E-s4--ba1f2511fc30423bdbb183fe33f3dd0f/MD5E-s4--ba1f2511fc30423bdbb183fe33f3dd0f
(dev) 2 11567.....................................:Fri 10 Feb 2017 01:19:54 PM EST:.
hopa:/tmp/test-source
$> file -L /tmp/test-target/123
/tmp/test-target/123: ASCII text
```

**Comment by bpoldrack** [comment]
Re "before" - logic: If either a path or `annex_copy_opt` was specified, `annex copy` call was invoked. Otherwise just the dataset would be (may be recursively) published. But this logic of course doesn't quite fit the current API approach, since it assumed we are talking ONE toplevel dataset to be published, which could be derived from CWD or `-d`. Now that we want to be able to work across several, possibly unrelated datasets (which need to be specified), that doesn't work the exact same way.

I think we should keep the part regarding `annex_copy_opt`, since you can specify options, that determine what files to copy without specifying any path.
I'd suggest that given paths, pointing to a file, should trigger `annex copy`, but paths specifying a (sub)dataset shouldn't by default. Therefore we would need a switch.

As far as I can see it, the logic right now is such, that any given path results in an `annex copy` call and even if no path is given, the path to the detected dataset is used.

The required change (if you guys agree on the proposed logic) don't seem to be big, though. It's just an additional filtering of `paths` in line 150 of publish.py plus the switch, I guess.

**Comment by bpoldrack** [comment]
Re wrong `.git/config`: @yarikoptic it matters because of your comment on it in the first post:

> noted btw that none of the 'push' settings aren't yet set in .git/config for that remote (thought that we have had that settled already, I guess I was wrong)

In the `.git/config` you posted now, there are push settings. Maybe the sibling of the dataset above was created before and you now did it again with the new subdataset, using the switch to skip existent ones?

**Comment by yarikoptic** [comment]
> Maybe the sibling of the dataset above was created before and you now did it again with the new subdataset, using the switch to skip existent ones?

Might be -- hard to tell now ;-)  although I think it was a new dataset, so unlikely was "reconfigured" or smth.  And here is an independent attempt to just show that yes by default we publish data now:

```shell
hopa:/tmp/test-publish
$> builtin cd /tmp/; chmod +w -R test-publish*; rm -rf test-publish*; datalad create test-publish; cd test-publish; echo "123" > 123.dat; datalad add 123.dat; datalad create-sibling localhost:/tmp/test-published; datalad publish --to=localhost; file -L ../test-published/123.dat; ls -ld ../test-published/123.dat 
[INFO   ] Creating a new annex repo at /tmp/test-publish 
                                                                    
Created dataset at /tmp/test-publish.
W: git-annex repositories not (yet) supported in the prompt
                                                                                                                                  Added /tmp/test-publish/123.dat
[INFO   ] Connecting ... 
[INFO   ] Creating target dataset /tmp/test-publish at /tmp/test-published 
[INFO   ] Adjusting remote git configuration 
[INFO   ] Enabling git post-update hook ... 
[INFO   ] Publishing <Dataset path=/tmp/test-publish> to localhost 
[INFO   ] Publishing data of dataset <Dataset path=/tmp/test-publish> ... 
1 item was published:
Dataset: /tmp/test-publish

../test-published/123.dat: ASCII text
lrwxrwxrwx 1 yoh yoh 116 Feb 14 10:13 ../test-published/123.dat -> .git/annex/objects/K1/xV/MD5E-s4--ba1f2511fc30423bdbb183fe33f3dd0f.dat/MD5E-s4--ba1f2511fc30423bdbb183fe33f3dd0f.dat
```

> I'd suggest that given paths, pointing to a file, should trigger annex copy, but paths specifying a (sub)dataset shouldn't by default.

(while playing with it ran into related #1293 if we do "copy" if paths are specified)

sounded sensible first but then -- not ;)  e.g. if I do "datalad publish ." to publish all the data of the dataset (since how otherwise?).  I guess it would get resolved to full path before the "analysis"?  Also, may be it is worth keeping in mind behavior of `get` since it is somewhat complementary to `publish` -- `get` would obtain all the content of the dataset if we point get to a subdataset.  So IMHO `publish` should behave similarly

Altogether it would feel like we are trying to "outsmart" annex somewhat by trying to accommodate functionality offered by two modes of annex operation (`copy` and just `sync` without --content) within a single `publish` command by doing magical analysis of provided "PATH"s.    I think we might be better off by

- relying more on what annex was configured to do, i.e. use "wanted" settings (which could/should be set during `create-sibling`, #925), so if nothing special was configured -- just do `annex sync` upon publish which would do nothing to the content by default, and then `annex copy --auto` which would also do nothing if no wanted was set for that repository

```shell
$> builtin cd /tmp/; chmod +w -R test-publish*; rm -rf test-publish*; datalad create test-publish; cd test-publish; echo "123" > 123.dat; datalad add 123.dat; datalad create-sibling localhost:/tmp/test-published; file -L ../test-published/123.dat; git annex sync localhost; git annex copy --to=localhost --auto ;file -L ../test-published/123.dat;         
...
../test-published/123.dat: cannot open `../test-published/123.dat' (No such file or directory)
```
but if any wanted setting is set for that remote -- copy --auto would warrant it
```shell
$> builtin cd /tmp/; chmod +w -R test-publish*; rm -rf test-publish*; datalad create test-publish; cd test-publish; echo "123" > 123.dat; datalad add 123.dat; datalad create-sibling localhost:/tmp/test-published; git annex wanted localhost standard; git annex group localhost backup; file -L ../test-published/123.dat; git annex sync localhost; git annex copy --to=localhost --auto ;file -L ../test-published/123.dat;                                                                                                                     ...
copy 123.dat (checking localhost...) (to localhost...) 
MD5E-s4--ba1f2511fc30423bdbb183fe33f3dd0f.dat
              4 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/1)
ok
(recording state in git...)
../test-published/123.dat: ASCII text
```
(with `manual` instead of `backup` would not transfer, as it is desired)

- here I assumed that we would like to use `annex sync` but I am not yet 100% sure due to all the additional synced/ pointers being set etc.  May be just regular `git push` (with `annex merge` dance) while respecting git config push settings would be cleaner
- we probably do not want to call `annex sync --content` since that 
    - seems to cause content upload if no wanted set
    - there is no --json and --json-progress so we would not be able to reflect progress upon user
- we probably do not want to come up with additional `remote.*.datalad-publish` config settings, which was originally discussed with @mih (see e.g. https://github.com/datalad/datalad/issues/925#issuecomment-279376970) especially to simplify inheriting settings within new sub-datasets from super-datasets since it would complicate logic

So what to do about PATHs?  feels like the easiest to comprehend from a user perspective would be -- if any path is specified on the cmdline/API **explicitly** -- should be passed to `copy` which then should be invoked without `--auto`, i.e. content pointed to should be published.  This way we would stay analogous to `get` and to `annex copy` and the only magic which would be easy to document would be adding `--auto` mode for `copy` invocation.  Thus If I just merely specify on which dataset to operate `publish -d PATH` (`copy --auto`) -- it would differ from `publish PATH` (`copy PATH`)

**Comment by yarikoptic** [comment]
additional note for "cons" of my approach of relying directly/too much on `git-annex wanted`.  It would not scale "seamlessly"  as is to the case

I am working on a clone of a dataset which has e.g. `backup` group set, so everything should be published to it.  But locally I have added in a branch some derived data which I do not want to publish (yet or ever), but I might have some branch/files changes to which could be published no problem.  `copy --auto` would respect only the `wanted` as recorded in annex for that remote (i.e. `backup`), but I need to be able to say that e.g. another policy to apply really, at least for now (e.g. to not publish files with `distribution-protected` meta assigned).
To overcome this, I see us indeed adding some option, e.g. `remote.*.datalad-publish-wanted` which would override wanted known to annex from `git-annex` branch for that remote (i.e. `backup` in this example). But I am not sure if that is possible from looking at `git annex copy --help`, @joeyh?  if not possible (and couldn't be made possible), I guess we would need to use `annex find` I guess to define which PATHs should be explicitly passed to `annex copy` instead of using `annex copy --auto`

**Comment by joeyh** [comment]
Locally overriding wanted is not currently supported, but could certainly be added in theory.

However, that would mean that other repositories wouldn't be able to see the locally overridden wanted values. This risks a situation where repo A copies some files to B that B is on record as wanting, but B locally doesn't, so drops them, and then they get copied again and again..

Some solution would need to be found for that. 

But, you speak of deciding when to publish a file, and I think that could be added separate from wanted. Repo A may be a backup repo and want every file, but if B has the only copy of the file, and doesn't want to publish it yet, B can not send it to A.

It may be that a better preferred content expression for A would be one that somehow specified that only files in particular branches are wanted, and not files in other, unpublished branches. Or something like that.

This comment would be a good start at a git-annex todo item.
