### ISSUE TITLE
publish should publish current branch (possibly even make it available on remote by default)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1275]
it was kinda cool that things were actually made easier for me even while dealing with code repository:
```shell
(git)hopa:~/picts/mris/heudiconv[mvdoc-fixup-protocols]git
$> datalad create-sibling -s smaug smaug:proj/heudiconv
[INFO   ] Connecting ... 
ECDSA host key for IP address '129.170.233.9' not in list of known hosts.
[INFO   ] Creating target dataset /home/yoh/picts/mris/heudiconv at proj/heudiconv 
[INFO   ] Adjusting remote git configuration 
[INFO   ] Enabling git post-update hook ... 

$> datalad --dbg publish -r --to smaug                                                 
[INFO   ] Publishing <Dataset path=/home/yoh/picts/mris/heudiconv> to smaug 
ECDSA host key for IP address '129.170.233.9' not in list of known hosts.
1 item was published:
Dataset: /home/yoh/picts/mris/heudiconv

```

so I thought -- holy cow, I am done "publishing" my code to a new host... but not really since current branch wasn't pushed, not to say that it wasn't made the "default" one.
I think, for a simplistic use-case, we actually might want publish to reflect current branch on the remote end... eg. in this case I would have been a happy camper right away ;)

**Comment by mih** [comment]
How do we decide that we have a simple case?

We cannot always take the active branch (think direct mode). What if next time you publish the branch is different? You want previous branch published too? Or replace with the new one? What about master? Never publish if you are on a different branch?

Ultimately the question is: Is there any subset of the `git push` interface that we do not wish to generalize to work across any repositories?

I'd prefer if we first try to get a consistent implementation of the basic functionality done, before we implement the fancy ones.

**Comment by mih** [comment]
Precondition: #1212

**Comment by yarikoptic** [comment]
#1212 marked fixed. Ran into this issue again

**Comment by mih** [comment]
Conclusion to this issue is unclear to me (as is the actual problem description). See unanswered questions in https://github.com/datalad/datalad/issues/1275#issuecomment-278928873
