### ISSUE TITLE
`create-sibling` -> `create-sibling-ssh`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1279]
I do not think #1040 is a viable path. I hereby announce to perform the rename above in the near future.

**Comment by yarikoptic** [comment]
may be let's keep it as is -- breaking interface from what we have been using nohow helps imho unless there is a need to free it up for something else... moreover create-sibling could be made to work on localhost as well and possibly even over https (webdav) with exactly the same interface, just different types of RIs.
