### ISSUE TITLE
GitRepo.publish() needs more flexible API

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1284]
At present I can specify exactly one refspec to be pushed. However `publish()` needs more flexible ways. Push multiple branches at once, honor `remote.<name>.push` configuration(s), and, in addition, push a particular set of tags branches.

From my PoV, a low-level approach would be to be able to flexibly pass Git configuration items to the `GitRepo` method. Ala `git -c var=value -c .... push`. This way `publish()` could easily, and dynamically amend an existing configuration. More convenient would be a way to list any number of values for `remote.<name>.push` directly, instead of, or amending the current `refspec` argument.

A resolution of this issue is required for moving forward with things like #1275, and selective publication in general, without having to introduce custom code wrapping each `push()` call.

**Comment by bpoldrack** [comment]
> honor remote.<name>.push configuration(s)

Do you mean pass those configurations via `-c` or are you confident, that it currently ignores those settings in the config file?

**Comment by mih** [comment]
I mean, that we need support for both simultaneously.

**Comment by mih** [comment]
Same is needed for `fetch` in the context of `update` and #1199.

**Comment by bpoldrack** [comment]
Looked into it. Easiest way to pass per call options to git for `GitRepo.push()`, `fetch()`, `pull()` would be that way:

```python
r = GitRepo(path)
r.repo.git(c="remote.{}.push=\"refs/heads/whatever\"".format(remote_name))
r.push(remote_name)
```

Calls like in the second line set git options for next call using that `Git` instance (`r.repo.git`) only. No need to reset.

**Comment by bpoldrack** [comment]
Not sure, whether we want to integrate this in the `GitRepo` methods, since it's a one-liner anyway.

**Comment by mih** [comment]
thanks, will try that.

**Comment by bpoldrack** [comment]
Thinking of integration - there's a reason to do it indeed. That is: How to pass options to git ATM depends on the `GitRepo` method, since it's different if don't use GitPython therein. So it would be nice to have consistent way for the Repo classes. Therefore keep that issue open, but may be it's not as urgent as assumed before.

**Comment by mih** [comment]
`push()` (that came with #4206) uses a `git push --dry-run` to infer and honor all related Git configuration. So the conclusion is to use that new command and configure Git as intended.
