### ISSUE TITLE
create-sibling --inherit-settings

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1295]
As we have discussed with @mih, we might want to lessen my and hopefully others pain while creating and publishing new sub-datasets to the siblings for which their super-datasets have everything set already.   We need it scalable and flexible (e.g. some sub-sets of datasets could have different policy from others, like I have for ///labs/haxby).

For `url` and `pushurl` -- in case of non-hierarchical setups gets tricky, I am not yet having a good grip, but could be detected/marked somehow.  For what to push/upload - somewhat of two possible ways
1. **custom config variable in super-** 
First we thought about having some additional config `remote.*.datalad-publish` which would be recorded within super's `.git/config` so that sub-dataset could just take them and use while configuring itself...   thinking about it though, "I don't like it" since it would not accommodate ad-hoc/custom setups I might have by interacting directly with `git config` and `git annex wanted` to achieve necessary effect.    Those two sets of settings would diverge and lead to chaos.  So I would prefer `2.`:
2. **inherit all relevant settings**, i.e. rely more on git/annex settings instead of ad-hoc ones.

What we really need is to inherit (depends on resolution of how publish behave, my view is here: https://github.com/datalad/datalad/issues/1274#issuecomment-279747603)
- what to push: `--get-all remote.SIBLING.push`
- what to upload: all non-empty values of `git annex wanted SIBLING` and if set to `standard` or `groupwanted`: `git annex group`, and in addition if `groupwanted` only: `git annex groupwanted`. 
- and only then inherit also any additional relevant custom variables (e.g.`datalad-publish-depends` and `datalad-publish-wanted` in https://github.com/datalad/datalad/issues/1274#issuecomment-279755509)

### Difficulties with 2.

- `shared` setting -- I don't think it is easy/viable to figure out from an existing one of the super-dataset... I could be wrong

I guess since I am the one mudding the waters and needing it most ATM, I could take a try at it

edit 1: added `datalad-publish-depends` into the list of vars to inherit
edit 2: added `Difficulties` pointing to `--shared` setting.
edit 3: +1c to those who wish all datasets to be annexes.  We cannot inherit "wanted" settings from the super dataset if it is just a pure git... heh... boomer!

**Comment by bpoldrack** [comment]
2. sounds preferably to me, too.

**Comment by yarikoptic** [comment]
just a note -- having both `create-sibing` and `create-sibling-github` complicates invocation from within `publish` to achieve ultimate ideal behavior.

**Comment by mih** [comment]
Please keep in mind that -github is just one example for API-based remote
creation. rsync.net, S3,... many more arr possible. Any design should not
lock us into the present set.

**Comment by yarikoptic** [comment]
re API -- counter example is "git annex initremote" which allows for all the varieties without creating initremote-TYPE for each one of them.  I do hear you that it might be trick(ier) to implement given us trying to fulfill both cmdline and Python interfaces, but it is not completely impossible.

**Comment by yarikoptic** [comment]
re --shared, I guess there is some dichotomy from documented and actual in git:
```
$> builtin cd /tmp; rm -rf test; mkdir test; cd test; git init --shared=all; git config --get core.sharedrepository; ls -ld .git/objects
Initialized empty shared Git repository in /tmp/test/.git/
2
drwxrwsr-x 4 yoh yoh 80 Feb 14 14:48 .git/objects/

$> builtin cd /tmp; rm -rf test; mkdir test; cd test; git init --shared; git config --get core.sharedrepository; ls -ld .git/objects   
Initialized empty shared Git repository in /tmp/test/.git/
1
drwxrws--- 4 yoh yoh 80 Feb 14 14:48 .git/objects/

$> builtin cd /tmp; rm -rf test; mkdir test; cd test; git init --shared=0x731; git config --get core.sharedrepository; ls -ld .git/objects 
Initialized empty shared Git repository in /tmp/test/.git/
1
drwxrws--- 4 yoh yoh 80 Feb 14 14:49 .git/objects/
```
so it looks like it doesn't give too much about having explicit permissions specified?  more over doc says:
```
       core.sharedRepository
           When group (or true), the repository is made shareable between several users in a group (making sure all the files and objects are
           group-writable). When all (or world or everybody), the repository will be readable by all users, additionally to being group-shareable.
           When umask (or false), Git will use permissions reported by umask(2). When 0xxx, where 0xxx is an octal number, files in the repository
           will have this mode value.  0xxx will override user’s umask value (whereas the other options will only override requested parts of the
           user’s umask value). Examples: 0660 will make the repo read/write-able for the owner and group, but inaccessible to others (equivalent to
           group unless umask is e.g.  0022).  0640 is a repository that is group-readable but not group-writable. See git-init(1). False by
           default.
```
and is just or'ing inverse of umask for any setting:
```shell
(git)hopa:/tmp/test[master]
$> umask 000
2 12046.....................................:Tue 14 Feb 2017 02:51:31 PM EST:.
(git)hopa:/tmp/test[master]
$> builtin cd /tmp; rm -rf test; mkdir test; cd test; git init --shared=0x660; git config --get core.sharedrepository; ls -ld .git/objects
Initialized empty shared Git repository in /tmp/test/.git/
1
drwxrwsrwx 4 yoh yoh 80 Feb 14 14:51 .git/objects/
2 12047.....................................:Tue 14 Feb 2017 02:51:33 PM EST:.
(git)hopa:/tmp/test[master]
$> builtin cd /tmp; rm -rf test; mkdir test; cd test; git init --shared=0x640; git config --get core.sharedrepository; ls -ld .git/objects 
Initialized empty shared Git repository in /tmp/test/.git/
1
drwxrwsrwx 4 yoh yoh 80 Feb 14 14:51 .git/objects/
2 12048.....................................:Tue 14 Feb 2017 02:51:39 PM EST:.
(git)hopa:/tmp/test[master]
$> builtin cd /tmp; rm -rf test; mkdir test; cd test; git init --shared; git config --get core.sharedrepository; ls -ld .git/objects      
Initialized empty shared Git repository in /tmp/test/.git/
1
drwxrwsrwx 4 yoh yoh 80 Feb 14 14:51 .git/objects/
2 12049.....................................:Tue 14 Feb 2017 02:51:45 PM EST:.
(git)hopa:/tmp/test[master]
$> builtin cd /tmp; rm -rf test; mkdir test; cd test; git init --shared=all; git config --get core.sharedrepository; ls -ld .git/objects 
Initialized empty shared Git repository in /tmp/test/.git/
2
drwxrwsrwx 4 yoh yoh 80 Feb 14 14:51 .git/objects/
```

**Comment by yarikoptic** [comment]
I guess it might please @mih, added edit 3  to the original post ;-)

**Comment by bpoldrack** [comment]
Re `--shared`: Just from looking at what you did and the man page you posted:
Did you notice that they are talking about `0640` where you pass `0x640`? I'd expect it too work, too, but might be worth trying ...

**Comment by yarikoptic** [comment]
great catch @bpoldrack ! ;)
```shell
$> builtin cd /tmp; rm -rf test; mkdir test; cd test; git init --shared=0x640; git config --get core.sharedrepository; ls -ld .git/objects
Initialized empty shared Git repository in /tmp/test/.git/
1
drwxrws--- 4 yoh yoh 80 Feb 16 15:07 .git/objects/

$> builtin cd /tmp; rm -rf test; mkdir test; cd test; git init --shared=0640; git config --get core.sharedrepository; ls -ld .git/objects                 
Initialized empty shared Git repository in /tmp/test/.git/
0640
drwxr-s--- 4 yoh yoh 80 Feb 16 15:07 .git/objects/
```
so we can just pass over the core.sharedrepository value into the call
