### ISSUE TITLE
`update` cannot update a plain git repo to an annex

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1307]
https://github.com/datalad/datalad/pull/1304/commits/cedd9afc1775a88d10d8f573874f67f709a0d899

**Comment by mih** [comment]
Note, also needs a check whether the new reusable dataset repo instances mechanics can deal with the situation that a previous GitRepo at a given path, needs to become an AnnexRepo.

**Comment by bpoldrack** [comment]
Since 'fix-implemented' was assigned - can you confirm that just calling `Dataset.repo` to reevaluate the underlying Repo does the job?

**Comment by mih** [comment]
Verified in a test in #1304

**Comment by mih** [comment]
Done.
