### ISSUE TITLE
"new" behavior of git-annex 6.20170220+gitgbfb38eece - upon publish new commit on remote git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1319]
Was checking new version and one test (only) started to fail:
```
$> DATALAD_TESTS_SSH=1 nosetests -s -v datalad/distribution/tests/test_publish.py:test_publish_simple
                                                                                                                                              
FAIL
Versions: cmd:annex=6.20170220+gitgbfb38eece-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.11.0 tqdm=4.11.2

======================================================================
FAIL: datalad.distribution.tests.test_publish.test_publish_simple
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 734, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 564, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 564, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/tests/test_publish.py", line 99, in test_publish_simple
    list(source.repo.get_branch_commits("git-annex")))
AssertionError: [<git.Commit "2c3b83d1e068ad5df9ed38068b0babb8ae07e363">, <git.Commit "754322640238eeb5245f648efedc1aa907d56f33">, <git.Commit "31c5239a5b50aa1afe3d2f0c9cf2c88240ce7d7e">, <git.Commit "8dddd0901575a723b2452532d559bf0c3165bad1">, <git.Commit "7431e40519e765c12796a1e967c14a1ae20ff271">, <git.Commit "dfe848b0ca52af62f5c2e2e497674f6d632adaab">, <git.Commit "96d7e23796be713e2056cfd56d25deb2fc4d44ad">, <git.Commit "013d4cff32e12e9b57a79944fd2c63da03ac8d30">] != [<git.Commit "754322640238eeb5245f648efedc1aa907d56f33">, <git.Commit "31c5239a5b50aa1afe3d2f0c9cf2c88240ce7d7e">, <git.Commit "8dddd0901575a723b2452532d559bf0c3165bad1">, <git.Commit "7431e40519e765c12796a1e967c14a1ae20ff271">, <git.Commit "dfe848b0ca52af62f5c2e2e497674f6d632adaab">, <git.Commit "96d7e23796be713e2056cfd56d25deb2fc4d44ad">, <git.Commit "013d4cff32e12e9b57a79944fd2c63da03ac8d30">]
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 14.781s

FAILED (failures=1)
DATALAD_TESTS_SSH=1 nosetests -s -v   5.50s user 2.14s system 47% cpu 15.986 total
```

the reason is that upon last publish, annex manages to update on remote end uuid.log to finally list that repository within it (which is kinda sensible), making remote 'git-annex' branch ahead of the local one (which is minor but imho not desired if we really want to keep them in 'sync').  It is not clear to me why git-annex decided to do that only then, after all the previous pushes (may be hook was not triggered for it at all or smth like that)?

FWIW -- I uploaded that new git-annex into the '-devel' of neurodebian for now if you want to give it a shot (here is a direct link to the directory: http://neuro.debian.net/debian-devel/pool/main/g/git-annex/ . but if you feel that we should just allow git-annex to do that and do nothing about it, we could workaround in the test for that new (and keeping compatibility with old I guess) behavior and upload new git-annex.

alternative would be to merge remote git-annex after each publish I guess.... heh

**Comment by yarikoptic** [comment]
so any feedback on what should we do about this @mih @bpoldrack ?  happens also with  cmd:annex=6.20170220+gitg75a15e1ad-1~ndall+1  which you dare to see uploaded ;)

**Comment by bpoldrack** [comment]
May be we should first clarify with Joey when exactly this is happening before coming up with a strategy on how to adapt/avoid/trigger it earlier/whatever else.

Until then I'd just work around it in the test. Merging the remote after publish sounds like we are begging for trouble.

**Comment by yarikoptic** [comment]
@joeyh switching from 6.20170209+gitg16be7b5cc-1~ndall+1 to yesterday's builds
(e.g. 6.20170220+gitg75a15e1ad-1~ndall+1) one of our tests started to 
fail which checks that on remote end upon all the 'git push' etc we do,
we have the same state of git-annex branch.  apparently now git-annex 
adds on remote end an entry to uuid.log on that remote annex -- not sure 
why not before the last push with some changed files -- probably hood doesn't trigger before then; also not sure how come this version specifically does it when previous didn't.  
With your fresh memory of changes in annex -- do you see the change you did which resulted in new behavior?  
do you think that we just need to do "git pull --ff-only REMOTE git-annex" after the push? (I guess you are doing smth like that in sync already)

thanks in advance for the clarification

**Comment by yarikoptic** [comment]
@bpoldrack I will wait for Joey to reply to avoid ad-hoc tests fix ups -- may be resolution is quick/obvious.  
new version got just uploaded (http://neuro.debian.net/debian-devel/pool/main/g/git-annex/) -- had to remove previous one manually since in our git-annex-standalone versions we do not have incremental number after the original version -- so sorting doesn't always work out if reuploading two versions from the same date

**Comment by joeyh** [comment]
Probably this is due to the new post-receive hook, which runs git-annex and so auto-inits the repo at a different point in time than would have happened before. Probably if you disable that git hook in the remote repository, the test will clear.

**Comment by bpoldrack** [comment]
Confirming: Disabling that hook clears the test indeed.

Since the failing assertion semantically is about making sure, the remote received all we wanted it to receive, we should just change it to not assert the commits in both git-annex branches are equal, but that the remote one contains all we need.

**Comment by joeyh** [comment]
I've put a change in git-annex that should fix this behavior.

-- 
see shy jo

**Comment by bpoldrack** [comment]
Thank you, @joeyh .
