### ISSUE TITLE
get_subdatasets  should become a generator

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1323]
I wondered why `ls` is quite slow to "start"...  it is because it first traverses entire hierarchy of subdatasets into a list before actually listing it.... not sure if making get_subdatasets into a generator would immediately provide remedy (probably not) but IMHO it should be the right thing to do (unless they are required to be returned in sorted order but even then could be achieved) and possibly would allow for more responsive interface without major staggering while traversing deep hierarchies of the datasets

**Comment by mih** [comment]
This is already done in #1409

**Comment by mih** [comment]
Was merged.
