### ISSUE TITLE
update (I think) might end up generating "classical" submodules under super .git/modules

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1325]
have a case with a super dataset being a regular git, was playing with current implementation of `update` and fixing it up slightly... it seems that because of it I ended up with a leaf annex repository with .git being a symlink pointing upstairs... 
just wanted to 'share' so we are beware/check/fix

**Comment by mih** [comment]
hmm, haven't seen this yet, and would not know what part of the remaining code base would do this. Maybe the issue is gone after the massive RF over the past months.

**Comment by yarikoptic** [comment]
now hard to say what it was, so let's close and see if we run into it again
