### ISSUE TITLE
create-sibling should check if user.email/name configuration is set

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1326]
and if not -- ask for it and set on remote host (we could run those git commands there no problem)

since otherwise I believe git-annex doesn't digest that nice leading to ` Exit code=135. out=init   err=error: git-annex died of signal 7` although may be reason was different but after I set them -- works nice

**Comment by mih** [comment]
This issue is describing one of many aspects that require a general overhaul of the `create-sibling` command. This overhaul effort is being tracked by the meta-issue #6149. I am closing this issue here, after having added it to that TODO list.
