### ISSUE TITLE
make test -- intended to work?

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#133]
So I found this datalad on github and thought: wow! They even have tests. So I was like "Let me run some tests", and I do `make test`. But then it turns on me and my computer goes all crazy and screams at me ERROR and FAIL. Why so mean?

**Comment by yarikoptic** [comment]
it used to work ;-)  but now that we need venv -- it would need tune up

**Comment by hanke** [comment]
https://github.com/hanke/datalad/tree/bettermake

**Comment by yarikoptic** [comment]
On Fri, 24 Apr 2015, Michael Hanke wrote:

>    https://github.com/hanke/datalad/tree/bettermake

just send a PR for easier digestion etc

we might as well add it to the tests battery ;)

**Comment by yarikoptic** [comment]
was dealt with in #137
