### ISSUE TITLE
What is to be pushed by publish?

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1339]
PR #1308 was accidentally merged and thereby introduced a failure into master.
Then PR #1333 came to clean up master.

Therefore the changes around https://github.com/datalad/datalad/pull/1333/files#diff-18445826672fc8f047d0b7d56512986cL172 are not really agreed on yet.

This Issue is for further discussion of publish paradigm and to preserve the state of discussion in #1308.

**Comment by mih** [comment]
No discussion is happening....
