### ISSUE TITLE
wget 1.15 has no --show-progress

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#134]
That makes minimum 1.16 a dependency.

**Comment by hanke** [comment]
and 1.16 is not that widely available

**Comment by yarikoptic** [comment]
Which system did you run into they problem on? Isn't wget get bundled into annex distribution? For older Debians that would be the way too deliver annex

On April 24, 2015 3:18:40 AM EDT, Michael Hanke <notifications@github.com> wrote:
>and 1.16 is not that widely available
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/134#issuecomment-95832104

-- 
Sent from a phone which beats iPhone.

**Comment by hanke** [comment]
The system was my laptop. I had the latest git-annex from NeuroDebian, but nothing forced this dependency (version). `whohas wget` shows quite a few systems where this we be an issue.

**Comment by yarikoptic** [comment]
yeah -- I should probably just wipe out that build from neurodebian... install git-annex-standalone and welcome to report this issue to @joeyh  ;-)

**Comment by yarikoptic** [comment]
not sure if anything else to be done for this one, people are doomed to use recent git-annex by now, thus git-annex-standalone on neurodebian systems, which would come with up to date wget
