### ISSUE TITLE
ds.repo.get_deleted_files() is 'fragile' to crap laying around

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1341]
```shell
bids@rolando:/inbox/BIDS$ git diff --raw '--name-status'
fatal: This operation must be run in a work tree
fatal: 'git status --porcelain' failed in submodule tmp/.t/tmprepo158
```
not sure yet what operation managed to add (might be 'save -a' from prev version used) all the crap under tmp/ directory, and now started to fail in some subdirectory which was created by 'git annex test'.
just wanted to let us know ;)

**Comment by bpoldrack** [comment]
Looks as if the submodule was in direct mode. Is this possible, @yarikoptic ?
If so, solution should wait for PR #1277 to be merged.

**Comment by mih** [comment]
Is this still an issue?

**Comment by yarikoptic** [comment]
well... now I don't remember details of this encounter... FWIW, reran and it didn't blow up (I don't think it was in direct mode btw):
```shell
bids@rolando:/inbox/BIDS$ git diff --raw --name-status
M       dbic
```
