### ISSUE TITLE
install command should expose "*wanted*" options, get should use those as well

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1347]
Since #1299 we have 
```shell
  --annex-wanted EXP    expression to specify 'wanted' content for the
                        repository/sibling. See https://git-
                        annex.branchable.com/git-annex-wanted/ for more
                        information. Constraints: value must be a string
                        [Default: None]
  --annex-group GROUP   expression to specify a group for the repository. See
                        https://git-annex.branchable.com/git-annex-group/ for
                        more information. Constraints: value must be a string
                        [Default: None]
  --annex-groupwanted EXPR
                        expression for the groupwanted. Makes sense only if
                        --annex-wanted="groupwanted" and annex-group is given
                        too. See https://git-annex.branchable.com/git-annex-
                        groupwanted/ for more information. Constraints: value
                        must be a string [Default: None]
```
(no yet our custom "easier" one) ... we might want to enable those also for install, since during install we are generating a new (unique uuid) clone and thus it could have its annex wanted set.  Moreover, if those are specified, but even without `-g` (explicit `get data` option) we could then run `get --auto` to respect provided wanted settings and thus fetch files as needed/specified.  I guess then `datalad get` also could, whenever no custom PATHs specified, and wanted setting is set, call `annex get --auto` to fetch all the data this particular clone "desires" (currently would fail and demand a path)

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
