### ISSUE TITLE
using Control socket logging into systems using kerberos/afs does not gain necessary permissions/variables

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1357]
it might as well be the problem specific to our system setup (will clarify with the admin) but was worth reporting imho.

If I first establish the ssh socket first (and login/permissions work just nice in there), the subsequent calls to ssh do not gain needed permissions to access $HOME and also does not get correct $PATH settings... so feels like then it does not process "login" settings for the shell (i.e. /etc/profile etc), even if a session is interactive:
```shell
$> ssh -o 'ControlPath=/home/yoh/.cache/datalad/sockets/258a056af1cad68ee3e93a7012d80a88' yohtest@rolando.cns            
Could not chdir to home directory /afs/dbic.dartmouth.edu/usr/haxby/yohtest: Permission denied
-bash: /afs/dbic.dartmouth.edu/usr/haxby/yohtest/.bash_profile: Permission denied
```

that causes all kinds of troubles when trying to `datalad install` from that system, requiring more than a single 'ssh' interaction (e.g. `datalad install -r`)

**Comment by yarikoptic** [comment]
possible quick workaround which might work somewhat/partial is if during establishing initial connection we also get all env variables (such as PATH, LD_LIBRARY_PATH etc) and use them somehow explicitly during subsequent calls... but since passing env variables into remote shell calls is not that simple, not sure if a feasible workaround :-(

**Comment by mih** [comment]
I am closing this issue now. The problem and workaround are documented, so code changes are planned.

**Comment by yarikoptic** [comment]
not sure what the workaround is, and what changes are planned. But let's let this issue RiP
