### ISSUE TITLE
Invalid error message from `uninstall`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1358]
````
% datalad uninstall -r src/*
[ERROR  ] refusing to uninstall current or parent directory [uninstall.py:__call__:245] (ValueError) 
````

**Comment by bpoldrack** [comment]
I think, this is basically the same thing as in #1356.
Several commands lost the `require_dataset` to figure out a default dataset to operate on. We now determine (possibly unrelated) datasets based on the paths given and then do whatever needs to be done on these. So the error message doesn'T come from the dataset "." but the one(s) found in `src`, which don't know that they were called from above. Am I right, that it works if `-d .` is explicitly given?

**Comment by mih** [comment]
OK, cannot reproduce. Will close for now.
