### ISSUE TITLE
AnnexRepo.add to commit only what was added

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1361]
ATM the `commit` option for `AnnexRepo.add` just calls `git commit`. Would be reasonable to just commit, whatever files `add` was called with, I think.

**Comment by yarikoptic** [comment]
ohyeah, please! and test that behavior please please pleaase

**Comment by mih** [comment]
@bpoldrack is this done now?

**Comment by mih** [comment]
Also trygin to grasp whether and how this could be related to #1420

**Comment by mih** [comment]
@bpoldrack is this still an issue?

**Comment by yarikoptic** [comment]
I thought that `commit`  was stripped from `.add` of the base Git/Annex interfaces, And `add` interface command does commit only what is added , so I think this issue is "resolved"
