### ISSUE TITLE
we should somehow pre-initiate ssh connection(s) for 'annex get -J' call

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1373]
not sure yet how, but if all ssh connections go through our shim, should be possible with appropriate locking of other shim's execution until initial one establishes the connection.. ATM all parallel invocations start to demand password

```shell
(git)smaug:/tmp/dbic[master]
$> datalad get -r -J3 .
[INFO   ] Obtaining <Dataset path=/tmp/dbic>  recursively 
[INFO   ] Obtaining <Dataset path=/tmp/dbic/1000-dbic-dataset>  recursively 
[INFO   ] Obtaining <Dataset path=/tmp/dbic/dbic-animals>  recursively 
[INFO   ] Obtaining <Dataset path=/tmp/dbic/dbic-animals/derivatives>  recursively 
[INFO   ] Obtaining <Dataset path=/tmp/dbic/dbic-animals/derivatives/mriqc>  recursively 
[INFO   ] Getting 1 items of dataset <Dataset path=/tmp/dbic/1000-dbic-dataset> ... 
[INFO   ] Actually getting 345 files 
Total:   0%|                                                                        | 0.00/73.7G [00:00<?, ?B/s]yohtest@rolando.cns's password: yohtest@rolando.cns's password: yohtest@rolando.cns's password: 
```

**Comment by yarikoptic** [comment]
actually I do not see our shim somewhere in the stack, so may be I misunderstood how things work, and this is something for annex to deal with: http://git-annex.branchable.com/bugs/get_-J_cannot_be_used_with_password-based_authentication/

**Comment by mih** [comment]
This log looks like this happens at the stage of a single dataset's `annex get` call. If that is correct, `sshrun` should be called from inside `annex` -- simultaneously for each connection (as you suspected).

Not sure how to counteract that. We could try to make the connection attempt known to the `SSHManager` immediately, even before it is successfully established, and by that create a mechanism to delay subsequent connection attempts. @bpoldrack what do you think?

**Comment by yarikoptic** [comment]
I think this issue was addressed at the level of git-annex and only a single password or ssh key prompt should appear
