### ISSUE TITLE
Fate and scope of "result summaries"

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1380]
Current `master` implementation of `get` provides a result renderer that summarized the results, rather than rendering each result. This is somewhat in conflict with the changes in #1350.

In #1350 there is already a slot to enable per-command custom rendering of individual results. However, in order to provide result summaries, we need to collect the results. This contradicts the principle of a generator that relays them upstairs, one by one. Moreover, we do provide the ability to "transform" results in arbitrary ways, making it effectively impossible to render the outcome. The latter is not a problem for individual results, as we transform after rendering. But we can only render summaries after aggregation, which has to take place after transformation.

We could establish an additional slot of result summary renderer. Not just the custom ones that we had, but for each relevant output format.

- `json`: no meaningful summary possible if JSON output is desired
- `simple`: aggregate results by status and report how many we get per status
- `tailored`: whatever makes sense and we can think of
- ....

The summary would be rendered in the `return_func` wrapper that is wrapping the generator function created in `eval_results`. It would evoke the summary renderer for the desired output format, if:

- a summary renderer is available
- no `result_xfm` were active

In #1350 we force-disable any `result_xfm` from the cmdline API, so this would never prevent being able to render a summary. However, we run commands as a generator for the cmdline, to be able to relay the results as quickly as possible. This implies that we cannot rely on the rendering the `return_func` wrapper. But we have to duplicate this functionally when we unwind the command generator in the cmdline entrypoint.

How do you feel about this?

**Comment by bpoldrack** [comment]
I feel the approach you are proposing is pretty straight forward and in line with what I understand is PR #1350. As for the duplication in `return_func` and the cmdline entrypoint: There is no reason to not have a single helper or sth, that is used by both of them and lives in `datalad.interface`, right? So I don't consider this to be an issue.

**Comment by mih** [comment]
See #1408 for the implementation

**Comment by mih** [comment]
Chnage merged.
