### ISSUE TITLE
adding an existing sub-dataset is taking WAY TOO LONG

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1388]
With intent to add a new already present annex as a subdataset, ran following command but gave up on waiting

```shell
(venv-tests)3 10571.....................................:Sun 19 Mar 2017 11:06:40 AM EDT:.
(git)smaug:/mnt/datasets/datalad/crawl/openfmri[master]git
$> datalad add -d . ds000017
^CERROR: 
Interrupted by user while doing magic:  [genericpath.py:isdir:41]
(venv-tests)3 10572 ->1.....................................:Sun 19 Mar 2017 11:09:07 AM EDT:.
```

as you can see I gave up after waiting almost 3 minutes for add to do what should take a second (git submodule add, git commit).  It is also not clear what the heck it is actually doing since no debug messages at any level.  Here interrupting after waiting for just a few seconds:

```
...
[DEBUG  ] Using existing Git repository at /mnt/datasets/datalad/crawl/openfmri/ds000017 
[DEBUG  ] Running: ['git', 'config', '-z', '-l', '--file', '/mnt/datasets/datalad/crawl/openfmri/ds000017/.datalad/config']
| cwd: /mnt/datasets/datalad/crawl/openfmri/ds000017 
[Level 8] Finished running ['git', 'config', '-z', '-l', '--file', '/mnt/datasets/datalad/crawl/openfmri/ds000017/.datalad/config'] with status 0 
[DEBUG  ] Running: ['git', 'config', '-z', '-l']
| cwd: /mnt/datasets/datalad/crawl/openfmri/ds000017 
[Level 8] Finished running ['git', 'config', '-z', '-l'] with status 0 
[Level 5] Parsed ri /mnt/datasets/datalad/crawl/openfmri/ds000017A into fields {'username': '', 'scheme': '', 'fragment': '', 'hostname': '', 'query': '', 'path': '/mnt/datasets/datalad/crawl/openfmri/ds000017A', 'password': '', 'port': ''} 
[Level 5] Detected file ri 
[Level 5] Parsed ri ../ds000017B into fields {'username': '', 'scheme': '', 'fragment': '', 'hostname': '', 'query': '', 'path': '../ds000017B', 'password': '', 'port': ''} 
[Level 5] Detected file ri 
[DEBUG  ] Running: ['git', 'config', '-z', '-l', '--file', '/mnt/datasets/datalad/crawl/openfmri/ds000017/.datalad/config']
| cwd: /mnt/datasets/datalad/crawl/openfmri/ds000017 
[Level 8] Finished running ['git', 'config', '-z', '-l', '--file', '/mnt/datasets/datalad/crawl/openfmri/ds000017/.datalad/config'] with status 0 
[DEBUG  ] Running: ['git', 'config', '-z', '-l']
| cwd: /mnt/datasets/datalad/crawl/openfmri/ds000017 
[Level 8] Finished running ['git', 'config', '-z', '-l'] with status 0 
[Level 5] Removing temp file: /home/yoh/.tmp/datalad_temp_logs_mNU_n3 
^CERROR: 
Interrupted by user while doing magic:  [genericpath.py:isdir:41]
```

while I was composing this one, it finally completed but I have lost that history due to limited terminal history size.  I suspect that it is due to mentioned somewhere else before now detailed listing of all sub-datasets (we care just to know the list of them) while trying to figure anything out about another sub-dataset.  Here there is a good number of them, so takes a while, although probably not really necessary

**Comment by mih** [comment]
Looks like this is on an NFS mount? I cannot find it now, but we had such observation before -- delay of several minutes. Not related to `add` AFAIK, but looked like a more general NFS + git + annex issue.

**Comment by mih** [comment]
Here #721

**Comment by yarikoptic** [comment]
nope -- this one straight on btrfs mount
```shell
$> df /mnt/datasets/datalad/crawl/openfmri 
Filesystem       1K-blocks        Used   Available Use% Mounted on
/dev/md10      46883131392 31625666308 15255454108  68% /mnt/datasets

$> mount | grep mnt/datasets
/dev/md10 on /mnt/datasets type btrfs (rw,noatime,compress=lzo,space_cache,subvolid=1478,subvol=/datasets)
```

**Comment by bpoldrack** [comment]
I don't know why you don't get debug output - I do.
It doesn't take much time for me, but it probably depends on the size of the subdataset, which is admittedly a bad and unnecessary thing.
`add` (at least in master) uses `git add` and a subsequent call to `git annex add`. Additionally a dry run of `git add .`. I think that kind of analyzing what exactly to add leads to a lot of overhead and that case.

**Comment by bpoldrack** [comment]
Before caring for that, please note, that there is in issue with committing submodules in direct mode, as shown in PR #1277 . So that's the kind of "compound operations" I was talking about.

**Comment by yarikoptic** [comment]
@bpoldrack there is a **long** period of silence in debug messages --- that is where all that recursive traversal is happening fishing out the subdatasets.  Yes -- this symptom is for large datasets.  Try e.g. `datalad install /-r //` to your laptop and play within it then ;)  But my point in #1407 that traversal is often just too aggressive in many cases for no good reason
