### ISSUE TITLE
Speeding up the tests

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1396]
The test run time is getting too long. @yarikoptic has started slimming the test battery.

Another angle to approach this problem would be to gradually move to a more layered testing approach, where we don't always run the rather heavy top-level commands with their substantial condition checking penalties, but use intermediate commands (from future RF) that execute functionality under a more constrained set of requirements.

**Comment by yarikoptic** [comment]
Duplicate of https://github.com/datalad/datalad/issues/1383
?

**Comment by mih** [comment]
Indeed.
