### ISSUE TITLE
We need a clear concept for passing additional options to Git/Annex

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1406]
Many of our high-level command make the impression that they can relay options to Git and annex. In reality hardly any one actually does that.

All these placeholder options should be disabled and only come back when they can actually deliver.

For that it would be critical to have some documentation on how options are supposed to be passed to Git/annex in order to establish a general pattern.

**Comment by yarikoptic** [comment]
+1
In my use cases I think I never manually specified any of those and in general we should aim to avoid such a need

**Comment by yarikoptic** [comment]
Besides wanted and copy settings for annex since so far application of those was clear and warranted

**Comment by mih** [comment]
OK, started disabling the ones that I stumbled over, and are not passed onwards.
