### ISSUE TITLE
Protect tests against connection issues

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1410]
As PR #1377 showed, we are (probably often) assuming that any connection will remain available during the tests if they were in the beginning. In that case it has been about a `AnnexRepo.drop()` in the test for `AnnexRepo.get()`. When using the testrepo from github (`clone` succeeded) `drop` failed, saying that github was "unsafe" and therefore it wouldn't count for the minimum number of required copies.

I'm pretty sure this means, that `annex drop` wasn't able to connect to github at that point. So, the failing of `annex drop` is actually correct, but the test failed.

**Comment by mih** [comment]
This would be nice to have, but nothing has happened in more than two years, and the performance of the test battery has continuously improved. I will close this for now. Feel free to reopen with the intention to turn it into a PR.
