### ISSUE TITLE
Need ability to execute Git command via our helpers (also in direct mode) without all of GitPython

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1422]
During `subdatasets` command RF. I find myself needing to run `git submodules` but I cannot use custom_git_command, because I need to avoid Repo instantiation. I see no way to do this while retaining all  of the support for direct mode. @bpoldrack

**Comment by mih** [comment]
Related PR in #1423

**Comment by bpoldrack** [comment]
I think the cleanest way would be to RF GitRepo to have a lazy loading `repo` (GitPython `Repo`) attribute. That way instantiation would be cheap and as long as `get_submodules` and the likes don't use GitPython, that command should remain quick. But this might take a bit of time to discover side effects in the tests ...

Alternatively there would be a quick solution for `subdatasets` command. It would be kind of a code duplication and not automatically 'updated' whenever `GitRepo` is improved. But it's quickly available.
This is, what it would look like:

In `_parse_git_submodules(dspath)` you need to look into `dspath/git/config` and figure out, whether it is in direct mode (see `AnnexRepo._is_direct_mode_from_config`). If so just add `-c core.bare=False` to your `git submodule` call.

**Comment by mih** [comment]
Cool. Any reason not to add this option unconditionally? Seem to not have side-effects on regular repos.

**Comment by mih** [comment]
Hmmm:

````
/tmp/direct (git)-[annex/direct/master] % git -c core.bare=False submodule
fatal: $program_name cannot be used without a working tree.
````

**Comment by bpoldrack** [comment]
The reason is in that 'seems' ;-)
I really don't know under what circumstances there would be side effects. Plus: Sadly it doesn't work with all commands under all circumstances. Sometimes we still need `annex-proxy` or even more complex workarounds

**Comment by bpoldrack** [comment]
@mih: You're using recent git, right? I forgot.

There is this bug, that this option's priority over `.git/config` isn't repected. Workaround in `AnnexRepo`: Write it to `.git/config` before the call and restore old value afterwards.

See `AnnexRepo._git_custom_command`

**Comment by mih** [comment]
Too bad, that makes one call to `git config` to figure out whether this is needed and two more in direct mode to mitigate. Thanks anyways.

**Comment by mih** [comment]
What about this?

````
git --work-tree=. submodule
````

Seems to work, requires no config ping pong.

**Comment by bpoldrack** [comment]
Hm. Sounds like it should work for submodule commands indeed.

**Comment by bpoldrack** [comment]
Solved. We have a lazy loading `repo` attribute.
