### ISSUE TITLE
create-sibling might want to make remote repo use current branch as the default

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1428]
ATM it is just always 'master', but if we are working in another branch and want that one to be default I need manually to go to the server and check it out after push, and run hook (post-update) manually (if it is a datalad web frontend). Example dataset http://datasets.datalad.org/?dir=/workshops/nipype-2017/ds000114

Although it would be more of a magic to switch a branch upon publish, at least during `create-sibling` IMHO target location should have current local branch checked out.  Or if at publish time -- we would need to verify that current local branch/hexsha on local dataset corresponds to the same branch/hexsha on remote location and then checkout on remote end, and rerun post-update.  Actually we might as well just migrate necessary for web-frontend actions into 'post-checkout' hook

**Comment by mih** [comment]
This issue is describing one of many aspects that require a general overhaul of the `create-sibling` command. This overhaul effort is being tracked by the meta-issue #6149. I am closing this issue here, after having added it to that TODO list.
