### ISSUE TITLE
missing git-annex should be an error not a warning...

### ISSUE THREAD

**Issue by chrisfilo** [datalad/datalad#1429]
`[WARNING] Installation of ///workshops/nipype-2017/ds000114 has failed: git-annex of version >= 6.20161210 is missing. Install  git-annex-standalone  from NeuroDebian (http://neuro.debian.net) [annexrepo.py:_check_git_annex_version:351]`

**Comment by mih** [comment]
After months of pondering....I agree ;-)

**Comment by bpoldrack** [comment]
This appears to already be an error in current `master`.

Note to ourselves in case the issue raises again:
It's an Exception `OutdatedExternalDependency` which is catched in `datalad/cmdline/main.py`.
