### ISSUE TITLE
Use PY3 for generated entrypoints?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1439]
Because we are gradually switching to PY3 idioms as standard implementation, I think it makes sense to use Python 3 in the cmdline entrypoints by default. @yarikoptic @bpoldrack any counter arguments?

**Comment by yarikoptic** [comment]
I don't mind
I don't remember any module we depend on being PYTHON 2 only. just would need to check scrapy and noticed since iirc they were behind on that end

**Comment by yarikoptic** [comment]
on the other hand -- to what extent it would help us?
besides may be us test driving it more in python3 mode but then making less access on still IMHO prevalent python2?

**Comment by mih** [comment]
This comes back more than I thought. I repeatedly had the impression that the tests run faster on PY3. Are we testing less under PY3, or is the increasing use of PY3 idioms having an effect?

**Comment by mih** [comment]
We are almost there. Testing is now primarily done on PY3. @yarikoptic wants to ship Debian package with PY3 as default.

**Comment by yarikoptic** [comment]
FTR:  entrypoints use the python used to produce them:
```shell
$> head -n 1 venvs/*/bin/datalad        
==> venvs/dev3.4/bin/datalad <==
#!/home/yoh/proj/datalad/datalad/venvs/dev3.4/bin/python3.4

==> venvs/dev3.5/bin/datalad <==
#!/home/yoh/proj/datalad/datalad/venvs/dev3.5/bin/python3.5

==> venvs/dev3.6/bin/datalad <==
#!/home/yoh/proj/datalad/datalad/venvs/dev3.6/bin/python3.6

==> venvs/dev/bin/datalad <==
#!/home/yoh/proj/datalad/datalad/venvs/dev/bin/python2

==> venvs/dev-pure/bin/datalad <==
#!/home/yoh/proj/datalad/datalad/venvs/dev-pure/bin/python2
```
so while preparing debian package, if we take then from python3-datalad package build, they should be "all set" automagically

**Comment by mih** [comment]
@yarikoptic perfect!
