### ISSUE TITLE
Update bundled git to version 2.13.0 (or later)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1448]
We have been suffering from a bug in Git for a while, where we cannot override config options via a cmdline `-c` option. According to https://github.com/git/git/blob/master/Documentation/RelNotes/2.13.0.txt this might have been fixed:

>  * The code to parse "git -c VAR=VAL cmd" and set configuration
       variable for the duration of cmd had two small bugs, which have
       been fixed.

**Comment by yarikoptic** [comment]
cool.  might take awhile since now with the stretch freeze it would take awhile to suck that version into stretch and even in experimental it might appear with a delay, currently:
```shell
     1:2.12.2+next.20170324-1 300
        300 http://http.debian.net/debian experimental/main amd64 Packages
```

**Comment by mih** [comment]
Experimental has 2.13 now!

**Comment by mih** [comment]
I guess this is done now.
