### ISSUE TITLE
Re-classify "misc" commands

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1449]
Status quo:

````
*Miscellaneous commands*

  test
      Run internal DataLad (unit)tests
  crawl
      Crawl online resource to create or update a dataset
  crawl-init
      Initialize crawling configuration
  ls
      List summary information about URLs and dataset(s)
  clean
      Clean up after DataLad (possible temporary files etc.)
  add-archive-content
      Add content of an archive under git annex control
  download-url
      Download content
````

I would like to re-classify `test`, `add-archive-content`, and `download-url` as plumbing commands -- possibly also `clean`.

Objections?

**Comment by bpoldrack** [comment]
No objections.

**Comment by yarikoptic** [comment]
`test` -- sure, although it is not plumbing (low level and used by other commands) command
`add-archive-content` is the plumbing indeed, but as much as `install` and `get` -- it is to be used by users directly, similar to `add`.  
`download-url` -- should have really been our version of `addurl`, so I am even thinking of renaming it to `add-url`.  Not sure if any other command uses it directly (thus it is not really plumbing)
Altogether -- unless there is some better/more strict definition of `Miscellaneous` -- those fit in that category quite well IMHO.

On the other hand, I see possibly `rewrite-urls` being a plumbing and rarely (if ever used insofar) command... ;)

**Comment by mih** [comment]
Ok, leaving it as is. We can always have 'other' and 'more' in addition to 'misc'...
