### ISSUE TITLE
annex add by default ignores files starting with . ... we either should expose that option or add them by default

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1454]
now `datalad add -r .` doesn't actually add "everything" since skips files/directories which start with `.`.  adds additional pain...   I am somewhat inclined to add all files (including starting with .) by default and add an option `--exclude-dotfiles` which then would instruct to not add `--include-dotfiles` to `git annex add`

**Comment by yarikoptic** [comment]
apparently still the case with 0.9.2
```shell
$> datalad create /tmp/ddd; cd /tmp/ddd; touch .file; datalad add .
[INFO   ] Creating a new annex repo at /tmp/ddd 
create(ok): /tmp/ddd (dataset)                                                   
add(notneeded): /tmp/ddd (dataset) [nothing to add from /tmp/ddd]
save(notneeded): /tmp/ddd (dataset)
action summary:
  add (notneeded: 1)
  save (notneeded: 1)
1 15119.....................................:Thu 08 Mar 2018 12:05:07 PM EST:.
(git-annex)hopa:/tmp/ddd[master]
$> git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.file
```
@datalad/developers - what do you think?

**Comment by bpoldrack** [comment]
Since this surfaced again, I'd like to point out, that I prefer the current behavior over the suggestion. After all - why would I "hide" something and simultaneously expect it to be found by some general tool like datalad? Doesn't make much sense to me. As long as it is possible to explicitly add/save it, it's fine as is, I think.

**Comment by kyleam** [comment]
@bpoldrack, FWIW, I prefer the current behavior as well.

**Comment by simon-dube** [comment]
@bpoldrack Here is actually a situation I am facing regarding hidden folders as described in https://github.com/datalad/datalad/issues/274. Via a RESTful API, users can launch scientific pipelines executions on the server. Once the executions are done, the standard output and standard error are stored in a hidden folder within an execution specific folder on the server. This folder is hidden as we do not want to expose these files directly to our users (users can list and obtain their executions generated files through the API). However, via some specific endpoints, users can retrieve these files content so we need them to be published. Usually, when a pipeline execution completes, we manually save and publish the execution folder which in turn contains the hidden folder. However, we also have to manually publish the hidden folder. This is not too big of a deal for as long as things run smoothly. 

On the other hand, as a fail safe, when starting the server, to insure all data is in sync, we save and publish the dataset. As hidden folders are not saved automatically, this forces us to manually explore our dataset to explicitly save the different hidden folders. Having an option to specify the inclusion of hidden folders on save would be a great addition. We would only perform one save for our execution folder and would be able to save our dataset without having to manually save each hidden folder.

**Comment by simon-dube** [comment]
Additionally, I just tested the following case with unexpected result. With the following file structure:
```
dataset
└───.hidden
│   │   file1.txt
│   └───.hidden-child
│       │   file2.txt
```
Saving .hidden saved both `file1.txt` and `file2.txt`.

However, with this file structure:
```
dataset
└───folder
│   │   file1.txt
│   └───.hidden
│       │   file2.txt
```
Saving `folder` resulted only in the saving of `file1.txt`. 
Is this the expected result?

**Comment by kyleam** [comment]
> Is this the expected result?

Hmm, I didn't know what to expect.  It does match `git annex add`s behavior, though, so it's expected in that sense.

**Comment by bpoldrack** [comment]
> Is this the expected result?

I agree, this is a somewhat strange result and IIRC we actually can and should do sth about it to have it more straightforward. Thanks for pointing that one out!

As for your usecase @simon-dube: Generally, I get why you hide those folders and that you want to save and publish them anyway. However, I'd imagine there has to be some process creating those folders, so those processes know what exactly to add to the dataset without the need to discover it after the fact. So at some point in the workflow there should be a way to reasonably call and explicit `datalad-add` and/or `datalad-save`.

Nonetheless: I'm fine with an option like `--include-dot-files` as @yarikoptic proposed. That's just another way to explicitly state what is to be saved or added. My concern is about the paradigm. While I often don't really care what's the default as long as I can achieve everything, this is one of the cases where I think the default matters. And I'm strongly voting in favor of a default behavior that respects that things were "hidden" for a reason and not just treat it as if the leading dot has no meaning whatsoever.

**Comment by simon-dube** [comment]
@bpoldrack In normal cases, I will be able to `datalad add` and `datalad save` the hidden folder manually. However, if the process is killed for any reason (e.g. power outage), I would like to insure that my server is in a safe state by saving the entire dataset without having to manually save all hidden folders.

However, I also agree that the default behaviour should be as it is right now. It is true that someone would expect hidden files not to be automatically saved and published unless stated explicitely via a direct save or an option. Since Datalad builds on top of git-annex, it only makes sense for it to apply the same default behaviour. The addition of an option like `--include-dot-files` would however offer a nice flexibility for special use cases like mine.

**Comment by kyleam** [comment]
master now includes the behavior proposed and implemented by @mih above (i.e. call `annex add` with `--include-dotfiles` for consistency with git's behavior), so I think this can be closed.
