### ISSUE TITLE
add locking

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1455]
now that we have singletons all around we should add at least trivial locking that those *Repo objects should lock (where have permissions) operations on those upon themselves until they die off. So lock probably should contain host, PID, and *Repo object ID, so if dies off without cleaning up the lock, we could always (try) to verify if it is safe for us to remove that lock and proceed with a fresh one.  who knows -- may be it wouldn't be that painful ;)

**Comment by mih** [comment]
This could be extra motivation: https://travis-ci.org/datalad/datalad/jobs/229865267

````
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 592, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/interface/tests/test_crawl_init.py", line 27, in _test_crawl_init
    crawl_init(args=args, template=template, template_func=template_func, save=save)
  File "/home/travis/build/datalad/datalad/datalad/interface/crawl_init.py", line 94, in __call__
    % (exc_str(exc), get_func_kwargs_doc(pipeline_func)))
RuntimeError: Running the pipeline function resulted in Lock at '/tmp/datalad_temp__test_crawl_initxp7ka5gp/.git/index.lock' could not be obtained [util.py:open:314].FYI this pipeline only takes the following args: ['dataset', 'versioned_urls', 'topurl', 'versions_overlay_level', 'leading_dirs_depth', 'prefix', 's3_prefix']
````

or I broke something...

**Comment by yarikoptic** [comment]
I think such errors do pop up in different places from time to time... I am wondering if it is not some side effect of Singleton dying and somehow not invoking gitpython's deconstructor or smth which should have removed it... Or race condition when recently Singleton died but gitpyhton object not yet but then new class for that location is requested.
Can you reproduce it reliably?

**Comment by mih** [comment]
No, only saw it once in travis (see link).

**Comment by yarikoptic** [comment]
you restarted it, right? (I was about to do so to check as well if reproducible)

**Comment by yarikoptic** [comment]
FTR we now have locking used while extracting archives and in our special remotes . It is not  repository locking which is the topic of this issue so I will keep it open

**Comment by mih** [comment]
I think we can close this one. The latest installment is #5131 and a previous attempt was #4808 (but wasn't merged).
