### ISSUE TITLE
sshrun does not actually pass stdin? (or doesn't spitout received stdout?)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1458]
compare

```shell
$> echo 123 | ssh yoh@localhost cat 
123
$> echo 123 | datalad sshrun yoh@localhost cat 
$>
```

**Comment by mih** [comment]
I routinely use it to "tail -f ..." on remote machines, so the former is more likely than the latter.

**Comment by yarikoptic** [comment]
Lucky you
See the fix - it was former

**Comment by yarikoptic** [comment]
This commit https://github.com/yarikoptic/datalad/commit/2982e64c8aec1ee327efdad20ee5c5e29376a467

**Comment by mih** [comment]
Awesome, should read emails more often. My fix has a few characters different ;-)
