### ISSUE TITLE
More testrepos

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#146]
By now we have testrepos/basic/r1, which is a git-annex repository.
We need to have more of them and differentiate the types of repos, so we have annex/r1 instead of basic/r1, and add at least one git/something, handle/something and collection/something. So with_testrepos provides the option to only use repos of a certain type without changing it (For example: @with_testrepos('handle/*') )

**Comment by yarikoptic** [comment]
```
> git grep 'def with_testrepos' 
datalad/tests/utils.py:def with_testrepos(t, paths='*/*', toppath=None, flavors='auto', skip=False):
```
just to make it clearer -- we do already support specifying which repos to use, we just need to specify in the corresponding tests... but generic tests should sweep through all I guess... I expect that all of our repos will be annex repos -- or am I wrong?  if so -- we indeed might like to dedicate some `annex-` prefix  at the first level.

**Comment by bpoldrack** [comment]
Well, to test GitRepo-class for example it doesn't need to be an annex. And by now, collections are supposed to be a git repository, not an annex. That's why I noticed.

**Comment by yarikoptic** [comment]
to test GitRepo indeed it doesn't need to be annex, but can as well be annex ;)

may be we should just extend it to make use of  INFO.txt so we could select based on versions of annex/git and some other tags we add in there.  that would be more flexible I guess than just by path

**Comment by bpoldrack** [comment]
Re GitRepo:
For some basic operations: Yes. But: Think of having an annex in direct
mode and then try to test GitRepo-class with it. By now the test just
create a new git repo to test on, but to see whether commands work on an
independtly created one, we need to have a "pure" git repository.

Re INFO.txt
Smells like overkill to me at a first glance.

2015-04-30 14:51 GMT+02:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by yarikoptic** [comment]
Re GitRepo: indeed, concur!
Re INFO.txt: nah -- it was a brilliant idea, we just need to standardize it a bit ;)

**Comment by bpoldrack** [comment]
See your point with having such features. Just need to figure out a good
way to implement it and keep it handy.Let's sleep on this ;)

2015-04-30 15:26 GMT+02:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by mih** [comment]
Timeout....
