### ISSUE TITLE
TODO: abstract for CRCNS

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1466]
deadline is 21st... will be traveling but hope to scavenge some time
anything particularly exciting from of the last year developments?
- we do have functionality now for full loop of consuming/producing with publication to github+another portal for data 
- I would like to finish #1446 so we could publish datasets to zenodo
- possibly present/note DBIC BIDS setup

- not sure if it is worth a talk this year since gave one last year so ppl are aware of it already and for them it might be "all the same old" since majority of changes are just incremental from my point of view

**Comment by mih** [comment]
Sounds good to me.

**Comment by yarikoptic** [comment]
very preliminary and vague draft of an abstract is under crcns-2017-abstract doc onthe google drive, please chime in

**Comment by yarikoptic** [comment]
was done, submitted
