### ISSUE TITLE
RF `install` for return-values/generator/new-style API

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1470]
I'll put things in this issue that I want to change in `install` when I touch it in the context of #1468. @yarikoptic please chime in and let me know what you think -- so we can avoid ping-pong during review:

- [x] Rip out `if_dirty` option.  `install` is one of the last commands to have it (#1175) and we agreed to be able to work with semi-dirty datasets. Current default behavior is to save the entire dataset.
- [x] Turn most exceptions into "error" results. `install` calls itself repeatedly when multiple sources are given, and we need to be able to relay failure upstairs while still being able to decide whether to ignore, continue, or stop upon first error.
- [x] Figure out what Python API `install` should return in case a path to a directory in a subdataset is given as install `path` argument. In this case there will be no single result in response, and mixture of success and failure result status is easily possible. Any solution that requires aggregation of multiple results automatically rules out a default generator behavior, and also requires a further extensions of the post-processing API. One solution, compatible with the discussion in #1409 would be to have `install` not return anything about non-datasets by default. However, that seems awkward, unless we merely keep `install`'s ability to pass file/directory path arguments to `get` as a secondary convenience. However, keeping in mind that we planned to support complex source argument values (give me this file from this dataset at that version), we may need a more flexible default setup.
- [ ] Present `install` does not produce results matching the order of input args. Reason is that it sorts list-args into two lists (URLs and paths), and then first installs the URLs and then the paths. This makes processing faster, but yielding individual results can put them out in an order that does not match the input args. Two easy ways out: 1. don't care (this only happens in calls where URLs and local paths are randomly mixed in one call; rather unlikely in any real-world use case), 2. process one-by-one (makes the common case slower, but guarantees the special case). I am leaning towards (1), plus documenting that this will happen in such cases.

**Comment by yarikoptic** [comment]
Sounds reasonable

**Comment by mih** [comment]
@yarikoptic @bpoldrack I started to RF `install`. The switch to a generator might involve some non-trivial changes to the code. If you need to fix any logic in the `install/get/clone` dust circle, I would highly appreciate if you would either postpone that, or do it on top of #1468!

**Comment by mih** [comment]
Ping @yarikoptic new return value scenario needs your thoughts. Thanks.

**Comment by yarikoptic** [comment]
What about keeping install returning dataset(s)... So for a path within (sub)module return the dataset which contains that path? If that path is a subdataset itself, would return that subdataset

**Comment by mih** [comment]
Sounds good @yarikoptic. This mode of operation will not even require code modifications.

**Comment by mih** [comment]
@yarikoptic One more thing came up. Please check.

**Comment by mih** [comment]
Closing this one. I am happy with the new status quo.
