### ISSUE TITLE
`add` should use meaningful remote URL for registering submodules

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1474]
````
% datalad create . --force
% datalad --output-format json install -d . --reckless -s ../aligned src/aligned
% datalad --output-format json uninstall src/aligned
% datalad --output-format json get src/aligned
[ERROR  ] Installation of subdatasets /home/mih/forrest/collection/demo/src/aligned failed with exception: clone `source` and destination `path` are identical. If you are trying to add a subdataset simply use `add` %s [clone.py:__call__:137] 
[ERROR  ] could not perform all requested actions: Command did not complete successfully [{'type': 'dataset', 'status': 'error', 'path': '/home/mih/forrest/collection/demo/src/aligned', 'action': 'install'}] [utils.py:generator_func:1058] 
````

**Comment by mih** [comment]
So this is a compound issue. First the error message is misleading, as our internal call to clone is already happening with values that should not be there.

Second, the submodule is configured with the wrong "URL" setting:

````
% cat .gitmodules
[submodule "src/aligned"]
	path = src/aligned
	url = ./src/aligned
````

which clearly should be "../aligned". Digging out where this is coming from.

**Comment by mih** [comment]
Reason for the misconfiguration is the switch from a custom helper to the `add` command for registering a freshly installed, previously unknown subdataset. While this is all nice in terms of using common code, it presently refuses to acknowledge any information about the source URL. I propose to adjust `add`, which uses `datalad.distribution.utils._install_subds_inplace()`, to use the URL of `origin` (or whatever effectively primary remote) for `.gitmodules`. In case of a freshly clone subdataset (original situation in this issue)  that will be exactly the URL is was cloned from.

**Comment by yarikoptic** [comment]
sounds logical although somewhat too magical.
