### ISSUE TITLE
Common logging and result report concept

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1476]
The aim is to agree on one and then to write it up in here.

### Q1: When to just log vs yield a result

[this is about command implementations; the situation in low-level code is different. I'd argue that low-level code should only ever trigger debug messages (maybe distinguish different levels). It generally cannot decide or know whether a low-level error is actually a problem. We see this in numerous scary messages that are not that meaningful for a user]

Results can always easily be logged by including a logger in the result dict. Pure logging (without yielding a result) should only happen for progress info or decision making that may not lead to any result, e.g. a download attempt. Any result-oriented reporting (e.g. "i couldn't do what you requested", or "I got this") should happen in the form of a yielded result.

### Q2: Reporting individual results vs summaries?

Reporting summarizes comes with the need to aggregate across mutliple results. This aggregation practically prevents the ability to immediately yield intermediate results (a function that yields can only return `None`).  Summary rendering should focus on cmdline use (where we relay result dicts to the top-level anyways, and do not need to rely on custom return values (like in the Python API).

Command summaries might be highly custom, but maybe there is a meaningful default summary implementation. Something like

````
Performed actions:
  install (ok: 200, notneeded: 3, error: 1)
  get (impossible: 12876)
````

### Q3: Default format of reporting individual results?

It should be uniform across all commands. Proposal:

````
% datalad --output-format simple install -s ~/forrest/collection/phase2
install(notneeded): /tmp/phase2 [dataset <Dataset path=/tmp/phase2> was already cloned from '/home/mih/forrest/collection/phase2']
````

more formal: <**action label**>(<**status label**>): <**result path**> [**result annotation/message/note**]

This is semi-structured and at the same time somewhat human readable.

### Q4: What individual results to report?

Some commands (install/get) could make use of the principle "ignore implicit results by default" in order to avoid overwhelming the user. We have to keep in mind that yielded results are logged if desired, but that doesn't imply that they have to be rendered as a result at the same time. In general, it seems difficult to come up with a common principle to decide what to render and what not.

**Comment by mih** [comment]
@yarikoptic @bpoldrack Please have a look!

**Comment by yarikoptic** [comment]
Sounds reasonable BUT so far the most unpleasant experience with datalad for me is not when it reports too much by default, and not even some wires it might report but when it does something for a while (minutes) without saying anything..  oops plane is taxing.. Going offline

**Comment by mih** [comment]
FTR: With current improvements in #1468 we get this:

````
% datalad --on-failure ignore get README.rst filenothere
install(notneeded): /tmp/aligned [<Dataset path=/tmp/aligned> is already installed]
[WARNING] path does not exist: /tmp/aligned/filenothere 
get(impossible): /tmp/aligned/filenothere [path does not exist: /tmp/aligned/filenothere]
get(notneeded): /tmp/aligned/README.rst [/tmp/aligned/README.rst is already present]
````

`README.rst` is a file directly committed to Git, the other does not exist.

If you explcitly operate on a dataset, it will not talk about its discovery as a result:

````
% datalad --on-failure ignore get -d . README.rst filenothere
[WARNING] path does not exist: /tmp/aligned/filenothere 
get(impossible): filenothere [path does not exist: /tmp/aligned/filenothere]
get(notneeded): README.rst [/tmp/aligned/README.rst is already present]
````

**Comment by mih** [comment]
#1468 made the switch to the Q3 proposal, Q4 is now "more possible", I will attempt an implementation of a default along the lines of Q2.

I have heard nothing negative on Q1, hence I would start to turn low-level logging to `DEBUG` level, and rip out custom result-oriented high-level logging in the commands that are generators (if such still exists).

**Comment by yarikoptic** [comment]
I would have first worked out all the rendering of the results (i.e. finalize #1468 and #1409 and have them merged first), and then proceeded with downgrading log messages to debug level when we feel that some are really duplicating information and results rendering provides adequate updates on ongoing activities.  as I have mentioned before -- my main problem often is lack of any feedback on what is going on, so it would not get better IMHO with some messages disappearing.

**Comment by mih** [comment]
True, "rip out" is the wrong word -- "adjust to match the new concept" is better.

**Comment by mih** [comment]
All in here is now a reality in master.
