### ISSUE TITLE
improve @with_temp

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#148]
we have already a few test cases where we wanted

1. temp file with some content
2. tempfile with an obscure filename

so may be worth a new issue to extend `with_tempfile` with  `load=None` and  `obscure=False`, where if obscure=True, we use it as an addition suffix to the tempfile name ?

**Comment by bpoldrack** [comment]
Well, for now with_tempfile delivers just a name, which is often used for a
directory. So, this is to keep in mind when changing it, to correctly adapt.

2015-04-30 15:21 GMT+02:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by yarikoptic** [comment]
BTW, `content=` option was already implemented.  Not sure if we should bother about `obscure` option so I will close this one for now
