### ISSUE TITLE
drop should be able to drop load from other branches/commits

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1482]
ATM, we can only drop load associated with current branch.  To drop anything else I need to use annex directly.  not sure how much of versatility of annex drop we should expose

**Comment by mih** [comment]
If this is just about passing a `--branch REF` option it shouldn't be hard. Is that the case?

**Comment by mih** [comment]
`foreach-dataset` is an official command now. The desired feature is now accessible for recursive processing like so:

```
datalad foreach-dataset -r git annex drop --branch otherbranch
```

The `foreach-dataset` command has flexible means to constrain recursion. I consider this good enough, given that there is no further record of demand after the original request ~5 years ago.
