### ISSUE TITLE
rewrite-description

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1484]
Our annex descriptions for the siblings/remotes aren't consistent, and I would like to change descriptions for all datasets which we host on `datasets.datalad.org` to be public URLs pointing to that website (not personal SSHRIs), so ppl could easily 'find' them.

we have `rewrite-urls` which adjusts .gitmodules to rewrite urls.  I wanted to adjust git annex descriptions for the annexes.  I see interface which takes
- `[--sibling NAME]`  by default would adjust of the local one, but can adjust for the remote ones as well
- `--dry-run` (ATM we have `--dryrun` in `create_sibling_github` and used to have `dry-run` for crawler, and that is inline with git) just to visualize
- `--recursive` (with other recursive options we have)
- `desc` which could be just a freetext or some kind of RI (SSHRI or URL) allowing for the same rewrites as `rewrite-urls` does

am I missing anything @mih and @bpoldrack ?  ideally should somehow be used/inline with default description create and create-sibling (at the moment none is custom specified, so annex creates).  so ideally should be some kind of option I guess somewhere they could `inherit`

**Comment by mih** [comment]
Another flavor of #1500 IMHO. Added to the list.
