### ISSUE TITLE
datalad publish --since is not in effect really (with -r)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1495]
I think it wasn't like that before at some point but I could be wrong.  
The idea of having `--since` was to minimize amount of work needed depending on what submodules actually got changed and how.  But I guess ATM publish having received -r is happily first queries for all present submodules only later making analysis that actually may be there is nothing to publish at all or it could be just a single submodule.   Actually not even sure if --since is in effect since now that everything is published I still see it going through submodules and trying to push some data where data might needed to be pushed:
```shell
(git)smaug:/mnt/btrfs/datasets/datalad/crawl[master]
$> datalad publish --to=datalad-public --missing=inherit -r
[INFO   ] Publishing <Dataset path=/mnt/btrfs/datasets/datalad/crawl/workshops/nipype-2017/ds000114> data to datalad-public 
...
$> datalad --version
datalad 0.5.1.dev95
...
```

**Comment by yarikoptic** [comment]
it hurts so bad

**Comment by mih** [comment]
In #1544 `publish` is now using the common modification detection from `annotate-paths`. Please check how you feel about that.

**Comment by yarikoptic** [comment]
usecase:
- you have a collection of datasets which you published before
- by default to publish you need to publish only changes from the previous state
- so it used to look at the common commit with the remote, and take that point as the argument for --since

**Comment by mih** [comment]
As we discussed and agreed upon during telco on June 9 2017: `since=''` should mean: check the diff between HEAD and the branch which a matching name on the remote, and only act upon that. Perform the modification detection on the base dataset, and use the result to filter out subdataset, in order to avoid having to process them all.

**Comment by mih** [comment]
`since` logic is in place now with `create_sibling` in #1544

**Comment by yarikoptic** [comment]
Yeap, that is what we agreed upon and then realized that for publish we needed some way to say "from the last commit point" how it used to be before when since was set to default None

**Comment by mih** [comment]
This should work now, if not please give demo/test.

**Comment by yarikoptic** [comment]
ok... got it now... so the default behaviour changed... if before, `since=None` was to trigger "since last publish", now I need to use `since=''`. Doing doc fix, and tune ups for your review
