### ISSUE TITLE
wishlist: aggregate errors in reports?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1504]
version 0.5.1.dev304 which is #1502 I believe atm

if I do smth like
```
hopa:/tmp/datasets.datalad.org/labs/haxby/raiders
$> datalad --on-failure=continue get */anatomy/
```
which would fail on 110 files (but that is ok -- I do expect that some files would fail), my screen is flooded with identical error messages, then equal number of WARNINGS, and then one HUGE ERROR aggregating all of them, probably to complete the assault on my visual system so I couldn't even scroll back to regain some memory of the past.

I really love that now we can see those messages from annex about where file might be available from, but IMHO we should add some smartness to it -- we should try to avoid flooding the screen.  E.g. may be we need group errors having the same content and state that "X" failed with error msg "blah"?   Error message with  ` Command did not complete successfully ` dump should also become human friendly and limit amount of output.  It is after all just a log message and we have "proper" return values now happen someone really need to analyze what is going on.

**Comment by mih** [comment]
Ok, these are many issues in one.

1) Not dumping the IncompleteResultsError -- easy, fine with me

2) re grouping: difficult, anything that changes the order of things requires something more than result comes in, we act on it, done. we either want constant output, or we don't IMHO. Grouping in general would be easy -- I made the messages template plus values, so we can easily decide which ones are of the same kind.

3) they rest I cannot comment on right now. for the first few hundred MBs and minutes it looked quite nice to me (mostly progress bars). I stopped it then.

4) at present we render results (way more than before) AND we log (as much as before) -- I mentioned before that I think this should change, but got no super-threshold feedback on it yet.

**Comment by yarikoptic** [comment]
re groupping -- don't we pass up also results on failures?  then we could include error message in those (if not yet there), parse them (for get commands) to compile a list of remotes which need to be provided and output it at the end?  for error log messages -- we could  just swallow/filter out those specific ones whenever we expect them to possibly happen

**Comment by yarikoptic** [comment]
I also wonder if default mode of reacting to errors should be 'continue' for get, drop, and install so a single run could be as complete as it could get?

**Comment by bpoldrack** [comment]
Re 2.: 
I agree that is difficult in the sense of "not flooding the screen". But as an additional output at the end the way @yarikoptic proposed it ("compile a list of remotes which need to be provided and output it at the end") it's doable and may be useful.

Re logging:
I don't find the issue right now, but yes: @mih already pointed it out and proposed to at least change the log level (and the default level to actually print them out) at most layers. And I agree. I don't think swallowing them is a good approach though. We should have a consistent idea of what to log at what level and get away from the idea, that logging is some kind of default user output. Personally, I wouldn't even have a default level to print at all, but instead log to proper log files by default.

**Comment by mih** [comment]
I was planning to switch to `continue` as default error behavior for a while now.

re logging: I am configuration the result status setting so that warnings are informative for the caller, this would be my preferred default log level.

**Comment by mih** [comment]
We do have error aggregation now -- in the form of the aggregation of results when using the generic result renderer (i.e. most commands).

It the particular scenario described by OP there would be, by default, 10 error results, and then:

`  [38 similar messages have been suppressed; disable with datalad.ui.suppress-similar-results=off]`

followed by a 

```
action summary:
  get (error: 48, impossible: 1)
```

at the very end.

A special case is caused by `get`'s behavior to produce an input argument dependent reporting (which is rather unique in datalad). For a failure occurring for a requested it would issue an additional

```
get(impossible): release-notes (directory) [<long list of all files that failed in the message>]
```

This is possibly undesired, but has little to do with (error) result aggregation.

Hence I considered this issue solved.
