### ISSUE TITLE
failing test at times: test_target_ssh_simple  assert (len(metafiles) >= 1)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1514]
I saw this one multiple times already, e.g. in https://travis-ci.org/datalad/datalad/jobs/230261758 but usually doesn't show its face upon rebuild
```
FAIL: datalad.distribution.tests.test_create_sibling.test_target_ssh_simple
....
  File "/home/travis/build/datalad/datalad/datalad/distribution/tests/test_create_sibling.py", line 252, in test_target_ssh_simple
    process_digests_mtimes(orig_digests, orig_mtimes)
  File "/home/travis/build/datalad/datalad/datalad/distribution/tests/test_create_sibling.py", line 236, in process_digests_mtimes
assert (len(metafiles) >= 1)
AssertionError
```
and it seems to come often with `TMPDIR=/var/tmp/sym link`, but I failed to replicate locally.

**Comment by mih** [comment]
Same as in #1502 where it is fairly reliable.

**Comment by bpoldrack** [comment]
Can't reproduce either. So it's not just about the symlinked tmp dir.
But I also don't quite get, what exactly you are testing with that line, @yarikoptic . Apparently it means that the post_update hook wasn't executed on the target, but I'm not exactly sure how this is related to the number of log files ...

**Comment by bpoldrack** [comment]
FTR:
Here is a build running `test_create_sibling.py` only with logging enabled:

https://travis-ci.org/datalad/datalad/jobs/231117281

**Comment by bpoldrack** [comment]
Looks like everything beneath `.git/datalad/web` was created but nothing beneath `.git/datalad/logs`.

**Comment by bpoldrack** [comment]
Strangely this is what I find in the log of the failing test, but NOT in the passing one, that I tried to replicate it locally with:
```
[DEBUG  ] ...>case:151,393,329,197>utils:846,762,592,592>test_create_sibling:207>create_sibling:575  Running post-update hooks in all created siblings 
[DEBUG  ] ...>case:329,197>utils:846,762,592,592>test_create_sibling:207>create_sibling:580>sshconnector:126,178  Checking SSHConnection(ctrl_path=<<'/home/travis/.cache/d...>>, sshri=SSHRI(hostname='localhost')) by calling ['ssh', '-O', 'check', '-o', 'ControlPath="/home/travis/.cache/datalad/sockets/5fa07251"', 'localhost'] 
[DEBUG  ] ...>utils:846,762,592,592>test_create_sibling:207>create_sibling:580>sshconnector:126,180>cmd:392,506  Running: ['ssh', '-O', 'check', '-o', 'ControlPath="/home/travis/.cache/datalad/sockets/5fa07251"', 'localhost'] 
[DEBUG  ] ...>case:329,197>utils:846,762,592,592>test_create_sibling:207>create_sibling:580>sshconnector:126,189  Check of SSHConnection(ctrl_path=<<'/home/travis/.cache/d...>>, sshri=SSHRI(hostname='localhost')) has succeeded 
[DEBUG  ] ...>case:197>utils:846,762,592,592>test_create_sibling:207>create_sibling:580>sshconnector:160>cmd:392,506  Running: ['ssh', '-o', 'ControlPath="/home/travis/.cache/datalad/sockets/5fa07251"', 'localhost', 'export "PATH=/usr/lib/git-annex.linux:$PATH"; cd \'/var/tmp/sym link/datalad_temp_test_target_ssh_simpleauf_WC/basic/.git\' && hooks/post-update'] 
```

**Comment by yarikoptic** [comment]
thanks!
nothing under .git/datalad/logs means that the hook either didn't run or just didn't run correctly!!!  may be I forgot some "" around the filename/directory.... gee  .... let's see if https://github.com/datalad/datalad/pull/1516  resolves it
