### ISSUE TITLE
`subdatasets` needs mode to query only a subset of the subdatasets

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1529]
At present we can only ask for all, and for all + recursive. In a dataset with many sub-subdatasets it could be very costly to ask for everything, if we already know that we only need a particular subset.

First use-case that comes to mind is `Dataset.get_containing_subdataset()` which _repeatedly_ asks for the list of all subdatasets with recursion, only to perform a few path string check on the results. This function is presently used in `get`, `aggregate-metadata`, and `Interface._prep()`, so it would likely be quite noticeable to speed this up.

**Comment by mih** [comment]
Although this is not the same issue as #1255, it is related, as internally subdatasets are traversed quite a bit, and likely without real need to do so.

**Comment by yarikoptic** [comment]
That is exactly what I kept trying to point out that full traversal (either directly or with a single git submodule --recursive call) is in general not needed and thus should generally be avoided IMHO. And indeed `Dataset.get_containing_subdataset` is a good example of the abuse.

I wondered if in some cases there could be some helper structure ("cached_submodules") which would be (optionally, similarly to memo in `copy` implementation) passed into e.g. `get_containing_subdataset` so it could reuse information to which dataset a directory belongs, so we could often quickly determine containing dataset if that dir (for any file) was previously queried.  If there is no information on that directory -- should go up in the hierarchy, while filling up those cached entries with information while discovering submodules.   If organized "smartly" annotating those directories with information either information about submodules under them was queried or not before, the same structure could be used also to list all present submodules (while finally doing full traversal where/when needed). Making it all in a 'generator' fashion might also bring benefits.

Why to pass that structure around --  so it has a life span only for a single point of invocation.  May be another fancier implementation could be cooked up with e.g. a context manager which, if caching structure defined at some module level is not present, would establish such cache and then clean it up upon `__exit__` if that context was the one which initiated/created it.  This way block of code on the top  where you expect such querying to happen and cache to be reused by anything within it, would establish the cache, use it, and then it would get cleaned up.  But it might be that explicit would be better than implicit and passing it around would be clear(er)?

**Comment by yarikoptic** [comment]
or may be above is overkill if all the sorting of paths happens in a single location, where all that discovery should happen.
