### ISSUE TITLE
Lower-level annex functions should not sort results into success and failure

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1533]
IMHO annex support layer should relay results as plainly as possible to the next layer. Concrete example: `AnnexRepo.copy_to()` sorts into good results and bad results, returns only the good and raises an exception for any bad. This counteracts the error handling we have at the toplevel. I propose to delete the respective code and relay JSON plainly.

**Comment by yarikoptic** [comment]
Shouldn't it then do translation into results structure you use elsewhere at least? And probably should become a generator while at it

**Comment by mih** [comment]
Closing, as we have #1769 for the general problem.
