### ISSUE TITLE
Support python3

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#154]
https://docs.python.org/3/howto/pyporting.html seems to be a good source of up-to-date HOWTO.  May be we could even simply switch to python3 altogether while leaving possibility of 3to2 backporting (if such thing is possible) to exist happily on older systems?

**Comment by jgors** [comment]
i looked, but couldn't find it anywhere...and as per that docs link, i think we should only be supporting python>=2.7, so should have something like:

```
import sys
pyversion = float(sys.version[:3])
if pyversion < 2.7:
    raise SystemExit("Requires Python >= 2.7; Current version is %s" % pyversion)
```

in ```datalad/__init__.py``` or maybe in ```setup.py``` before anything even gets run?
