### ISSUE TITLE
make --on-failure=continue to be default behavior for get

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1543]
I have ran already into this way too many times -- starting some what I think a long 'get', switching to do something else, to come later to see that it failed may be just 10 sec after since some file failed to download.  IMHO for get it makes more sense to continue on errors -- similar to how  annex get, and our browsers behave ;)

**Comment by mih** [comment]
Errr, with #1506 merged -- this is the default for any command.

**Comment by yarikoptic** [comment]
ah! will check, thanks

**Comment by yarikoptic** [comment]
FWIW -- confirming, works indeed this way now. thanks!
