### ISSUE TITLE
Testrepo setup causes `git push` to fail

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1548]
Here is the story: I have a non-bare repo that is clean and set up for pushing directly into it

````
mih@meiner /tmp/datalad_temp_testrepo_6H1oIv/subm 2 (git)-[master] % git config --list |grep receive
receive.denycurrentbranch=updateInstead
mih@meiner /tmp/datalad_temp_testrepo_6H1oIv/subm 2 (git)-[master] % git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
````

I have a clone of it also:

````
mih@meiner ...p_test_publish_recursiveuDdu37/subm 2 (git)-[master] % git remote -v
origin	/tmp/datalad_temp_testrepo_6H1oIv/subm 2 (fetch)
origin	/tmp/datalad_temp_testrepo_6H1oIv/subm 2 (push)
target	/tmp/datalad_temp_test_publish_recursiveOwurEY (fetch)
target	/tmp/datalad_temp_test_publish_recursiveOwurEY (push)
````

However, I cannot push to origin, because Git claims origin is not clean -- except Git confirmed before that it is:

````
mih@meiner ...p_test_publish_recursiveuDdu37/subm 2 (git)-[master] % git push
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 683 bytes | 0 bytes/s, done.
Total 6 (delta 1), reused 0 (delta 0)
To /tmp/datalad_temp_testrepo_6H1oIv/subm 2
 ! [remote rejected] master -> master (Working directory has unstaged changes)
error: failed to push some refs to '/tmp/datalad_temp_testrepo_6H1oIv/subm 2'
````

I can do this multiple times (rechecking that origin is still clean), and also naming the remote explicitly -- no luck:

````
1 mih@meiner ...p_test_publish_recursiveuDdu37/subm 2 (git)-[master] % git push origin
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 683 bytes | 0 bytes/s, done.
Total 6 (delta 1), reused 0 (delta 0)
To /tmp/datalad_temp_testrepo_6H1oIv/subm 2
 ! [remote rejected] master -> master (Working directory has unstaged changes)
error: failed to push some refs to '/tmp/datalad_temp_testrepo_6H1oIv/subm 2'
````

and the clone is clean too (although this should not matter at all)

````
mih@meiner ...p_test_publish_recursiveuDdu37/subm 2 (git)-[master] % git st
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
````

@bpoldrack @yarikoptic Can anyone enlighten me please?

(and BTW this is happening in our tests, I am simply exposing Git's errors now...)

**Comment by mih** [comment]
Follow-up: If I change the branch on the remote I can push -- makes no sense, if the working tree was clean, it would not get clean after that, still it works:

````
mih@meiner /tmp/datalad_temp_testrepo_6H1oIv/subm 2 (git)-[master] % git co -b _
Switched to a new branch '_'
mih@meiner ...p_test_publish_recursiveuDdu37/subm 2 (git)-[master] % git push origin
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 683 bytes | 0 bytes/s, done.
Total 6 (delta 1), reused 0 (delta 0)
To /tmp/datalad_temp_testrepo_6H1oIv/subm 2
   1ce9dd9..b47b1a7  master -> master
````

**Comment by mih** [comment]
Just pushed demo (see above) leads to:

````
[ERROR  ] failed to push to origin: master -> origin/master [remote rejected] (Working directory has unstaged changes); pushed: ['a2760cf..57cf5af'] [publish(/tmp/datalad_temp_test_publish_recursive0rXeh9/subm 2)] 
````

If PDB'ed prior to the `publish` call, a manual `git push` call replicates the problem. So it seems to be the setup, and not the `publish` call itself.

**Comment by bpoldrack** [comment]
I think I found the issue.
The setup doesn't use `datalad install` for creating `origin`. This leads to `origin` having a `.git` symlink instead of directory, while `source` has its own `.git` dir. If you adapt origin accordingly, the push works just fine.

**Comment by bpoldrack** [comment]
We need to use `datalad` for creating those testrepos or have a (plumbing?) command to fix up hierarchies with symlinked .git

**Comment by mih** [comment]
Thanks!

Now the question is: how do we adjust? The way you suggest will fix the issue for ourselves, but it is (and should be) absolutely possible that people use datalad with non-datalad repos.

**Comment by bpoldrack** [comment]
Well, it's about being able to publish to a non-datalad repo. How about letting `configure-sibling` do the fix? It wouldn't convert it to an actual datalad repo, but just replace those symlinks. (No .datalad creation or sth)

**Comment by bpoldrack** [comment]
BTW: I wonder whether we should ask git folks whether this is considered to be a bug. If .git is allowed to be a symlink as well as a directory, this should not prevent pushing, I think.

**Comment by mih** [comment]
Tests for `push()` no longer use testrepos.
