### ISSUE TITLE
"fuse" like operation when used a Python module

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#155]
We could provide a basic overload of "open" (and may be some of os.path) to automagically fetch requested files (e.g. upon `import datalad.magicio` or smth like that).  Use-case -- when running some tutorial, which opens (nibabel) files, we could check if file_has_content and if not -- fetch it only then passing call to stock 'open'.  Even though it might be fragile etc it might be a silver bullet working in 9x% of cases. TODO: verify operation in conjunction with nipype ;)  In comparison to proper fuse overlay, this one would be OS-agnostic.

**Comment by bpoldrack** [comment]
Not sure whether or not I got your use case right, but in principle -
sounds like a nice thing to have.

2015-05-29 20:15 GMT+02:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by yarikoptic** [comment]
usecase: we had PyMVPA workshop and decided to demonstrate one of the demo scripts which needed data which was not prefetched.  Now I needed to go for each failure and manually run "git annex", whenever if I had an decorated "open"  call, it could just check if file is not there and fetch it for me -- automation! ;)

**Comment by yarikoptic** [comment]
perspective PR to address this: #205
