### ISSUE TITLE
Use exclusion list to disable select tests from direct mode testing

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1562]
ATM we test a little bit of code for compliance with direct mode, using hand-picked tests. IMHO this should change. There is quite a chunk of usable functionality in direct mode, but from the test perspective it doesn't look like it. I think we should switch to a negative list, disabling only test that fail (possibly for a known reason). The current approach will or will not allow for the status quo to get worse -- we just won't know -- hence it isn't suitable for making progress towards direct mode compatibility.

**Comment by bpoldrack** [comment]
I agree. Additionally the same is true for v6.

**Comment by bpoldrack** [comment]
This is a bit more of an effort than I expected it to be.
Apparently `nose` can't easily exclude a list of tests out of the box, but only entire files/directories.
Current approach: Have a "dry-run" of nose to discover all tests (sadly by name), do a lot of `grep`'ing and `sed`'ing to get a unique list of tests adressed via `/path/to/file.py:test`, build difference to exclusion list and build a nose.cfg from the result to run those tests only.
