### ISSUE TITLE
insufficient amount of detail is provided upon "install" failure

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1563]
I think that entire stderr should be brought up/out since otherwise it is not clear why install failed and requires probably running in debug mode or just git command directly:

```shell
smaug:/tmp
$> datalad install -s /mnt/btrfs/datasets/datalad/crawl-misc/indi/adhd200/surfaces                         
[INFO   ] Cloning dataset from '/mnt/btrfs/datasets/datalad/crawl-misc/indi/adhd200/surfaces' (trying 1 location candidates) to '/tmp/surfaces' 
[ERROR  ] Failed to clone data from any candidate source URL: ['/mnt/btrfs/datasets/datalad/crawl-misc/indi/adhd200/surfaces'] [install(/tmp/surfaces)] 
install(error): /tmp/surfaces (dataset) [Failed to clone data from any candidate source URL: ['/mnt/btrfs/datasets/datalad/crawl-misc/indi/adhd200/surfaces']]
datalad install -s   3.76s user 9.20s system 29% cpu 44.503 total

smaug:/tmp
$> ls -l /mnt/btrfs/datasets/datalad/crawl-misc/indi/adhd200/surfaces -a
total 4
drwx--S--- 1 yoh datalad  72 Jun  5 21:12 ./
drwx--S--- 1 yoh datalad 116 May 25 07:57 ../
drwx--S--- 1 yoh datalad  50 May 25 07:57 .datalad/
drwx--S--- 1 yoh datalad 214 Jun 12 09:54 .git/
-rw------- 1 yoh datalad  20 May 25 07:57 .gitattributes
drwx--S--- 1 yoh datalad   6 May 30 16:56 freesurfer/
(dev)3 11862.....................................:Mon 12 Jun 2017 10:01:37 AM EDT:.
smaug:/tmp
$> git clone /mnt/btrfs/datasets/datalad/crawl-misc/indi/adhd200/surfaces
Cloning into 'surfaces'...
done.
error: unable to create symlink freesurfer/5.3/9956994/mri/talairach_with_skull.log (No space left on device)
error: unable to create symlink freesurfer/5.3/9956994/mri/talairach_with_skull_2.log (No space left on device)
fatal: cannot create directory at 'freesurfer/5.3/9956994/mri/transforms': No space left on device
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

git clone /mnt/btrfs/datasets/datalad/crawl-misc/indi/adhd200/surfaces  1.55s user 5.33s system 25% cpu 26.586 total
```

**Comment by mih** [comment]
This is another flavor of us not handling 'disk-full' issues nicely.

However, I am not sure that barfing everything out is the best approach. Few weeks back you suggested that "just run it with debug, if you really want to know what is going on" would be a better strategy then reporting all errors that happening during `get` -- and this is quite close to that.

**Comment by yarikoptic** [comment]
well -- there could be also other issues (just "regular" failures to clone from http with some objects not found etc)
thinking about it... indeed when we are trying multiple sources it wouldn't be clear which stderr to report as associated with failure... but indeed we could catch/analyze stderr more diligently for most common issues (like out of space) and include that in the report

**Comment by mih** [comment]
#1624 has some fix for some specific type of clone failure -- we need to see how it could be generalized. Exit code of Git are not informative. I haven't investigated whether there are reliable principles on how messages are formated.

Fundamental categories of errors are:

1. fixable by trying to clone from another URL
2. not fixable via another URL (e.g. #1624)

**Comment by mih** [comment]
There have been tons of changes and what is reported and how error s are detected and handles. While possible not yet in a perfect place, I will close this now, because we need an up-to-date reference or demo in order to derive any concrete actions from it. Reopen with updates as needed.
