### ISSUE TITLE
RI type guessing cannot handle windows paths

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1565]
````
% python -c 'from datalad.support.network import _guess_ri_cls as g; print(g("C:\poor\soul"))'
<class 'datalad.support.network.SSHRI'>
````

This is the current obstacle to usage on windows (not the last one, though ;-)

**Comment by bpoldrack** [comment]
So, we need to test for an absolute path first, I guess and only then try parsing it.

**Comment by mih** [comment]
Jup, pushed that -- trying now.

**Comment by mih** [comment]
Worked.
