### ISSUE TITLE
`get` on windows fails when trying to remove a tmp logfile that is "used by another process"

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1574]
In `get` we are having a windows issue. The German message in the screenshot below (last line) says that the log file that it tries to remove is still "in use" by another process. I assume this other process is the downloader. If that is correct, we need to work on the timing of these actions.

If we can get this to work, we can consume our public datasets on windows -- major milestone if you ask me....

Ah, and to be clear: this happens during cleanup -- it did actually download the file successfully before. So it is really just this tiny bit missing.

Any advice on where to start looking @yarikoptic ?

![image](https://user-images.githubusercontent.com/136479/27098851-4263ed78-5079-11e7-83f0-d7c0b51199a1.png)

**Comment by bpoldrack** [comment]
Looking into `rmtemp`, I suspect, it's just a WindowsError instead of a OSError (which is what is catched there in).

**Comment by mih** [comment]
So what is the meaning of `WindowsError` in contrast to `OSError` in this context. I know that Windows cannot handle this situation, so what do we do?

**Comment by bpoldrack** [comment]
What I mean is, that on Windows the same situation might raise a `WindowsError` instead of an `OSError`. So we should do the same thing: Try again several times as we do when an `OSError` is raised.
I might be wrong of course, but that's what I'd try.
Actually: I WILL try, since you assigned me ;-)

**Comment by mih** [comment]
That's the spirit! ;-) thanks.

**Comment by mih** [comment]
@bpoldrack this is done now
