### ISSUE TITLE
why uninstall can't uninstall without '-d .' ?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1581]
```shell
hopa:/tmp/datasets.datalad.org/corr/RawData
$> datalad install Utah_1
get(notneeded): /tmp/datasets.datalad.org/corr/RawData/Utah_1 (dataset) [already installed]
2 19974.....................................:Wed 14 Jun 2017 03:45:33 PM EDT:.
hopa:/tmp/datasets.datalad.org/corr/RawData
$> datalad uninstall Utah_1
uninstall(error): /tmp/datasets.datalad.org/corr/RawData/Utah_1 (dataset) [will not uninstall top-level dataset (consider `remove` command)]
2 19975 ->1.....................................:Wed 14 Jun 2017 03:45:36 PM EDT:.
hopa:/tmp/datasets.datalad.org/corr/RawData
$> datalad uninstall -d . Utah_1
drop(notneeded): Utah_1 (directory) [nothing to drop from /tmp/datasets.datalad.org/corr/RawData/Utah_1]
uninstall(ok): Utah_1 (dataset)
action summary:
  drop (notneeded: 1)
  uninstall (ok: 1)
```

IMHO more logical to have symmetric api here and be able to uninstall what we install with similar invocation.

Moreover I thought that `remove` should actually remove (`git rm`) upon completing drop/uninstall... otherwise I am  really not clear on their difference(s)

**Comment by mih** [comment]
Make sense. AFAIK we never actually came up with a proper concept on what needs to do what, so this is all very organic.

re remove: It will do that, but it will require `-d` for removal from a dataset. It doesn't have to be the immediate dataset that is given as a base, but a containing dataset. Without that `remove` operates like system `rm`: It will uninstall everything below and then wipe out the top-level path that was given as an argument.

**Comment by mih** [comment]
in master uninstall can do what was requested
