### ISSUE TITLE
Desired setup for preferred content management

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1582]
### NOTE: top-level comment is summary of discussion below

At the moment we have minimal support for preferred content management via git annex. There is expressed demand to expose more of that via the API of common commands (e.g. #1347 or #925). With PR #1579 the `siblings` command can query and set the respective properties for local repos and remotes.

Now the question is what is our concept of making use of this?

- What commands need to expose this?
  - `install`
  - `get`
  - `update`
  - `publish`
- When do we act upon it? For example, should an `install` figure out whether the just obtain repo has a `required` preferred content setting and start downloading matching data? If not, when would we make an attempt at fulfilling the promise?

from #1347:

>  Moreover, if those are specified, but even without -g (explicit get data option) we could then run get --auto to respect provided wanted settings and thus fetch files as needed/specified. I guess then datalad get also could, whenever no custom PATHs specified, and wanted setting is set, call annex get --auto to fetch all the data this particular clone "desires" (currently would fail and demand a path)

### Identified TODOs

- [ ] `drop` needs a `--force` option to override `required` setting. Likely needs better name to be distinguishable from `--no-checks` that disables redundancy tests

### Tentative TODOs

- `install` and `get`, possibly others get a `--content` option (replacing the `get_data` flag). Values would be 'all', 'none', 'wanted', 'required'. Default for `install` could be 'required', for `get` 'wanted'.
- `install` needs to invoke `get` with either `-g` or a `required` preferred content setting
- default setting of `get` should change from "yes, get data" to "get wanted"

**Comment by bpoldrack** [comment]
- Yes, I think, by default `install` and `get` should download content, that is `required`. Apart from what is considered to be the default, they need to be able to respect it.

- This raises the question, whether `update` should consider it. If `required` changed it might get additional content ... Not sure about this one.

- As discussed before, `publish` needs to respect those settings for the sibling to publish to, too.

- May be `drop` needs a `--force` or something to drop it?

**Comment by bpoldrack** [comment]
Additionally it might be nice to be able to specify that `drop`, `get`, `save`, `add` should respects only/all paths matching preferred content settings? Either a restriction to path specifications or an alternative specification of what to deal with (instead of path(s)).

**Comment by mih** [comment]
How could this be done in a uniform fashion. No path arguments would be confusing: `save` would no longer just save staged content.

Maybe a generic `--auto(-content`? But even that is not clear: `drop --auto` vs `get --auto` is drop all not wanted vs get all wanted.

**Comment by bpoldrack** [comment]
Needs an explicit option - I agree.
May be like `--content='wanted'|'required'|...`?

**Comment by yarikoptic** [comment]
what is the difference between `wanted` and `required`?

`install` shouldn't get any data unless some option (ATM `-g` to get all the data) is given. 
 `drop --auto` and `get --auto` make sense to me 

I wonder also if we need `--annex-get-opts` to pass arbitrary options to get while `install`.

I also wonder if we might like to provide a "path" sugaring to `install`, so e.g. `datalad install ///openfmri/ds000006//sub-*/ses-*/anat` so we use `//` to indicate the boundary between dataset root and then a glob for paths.  (orthogonal to this) For install we are yet to figure out how to specify specific version (committish) to be installed.     I thought we had an issue for that but can't find ATM.

**Comment by mih** [comment]
`required` is 'hard-wanted' standard git-annex functionality.

**Comment by bpoldrack** [comment]
`install shouldn't get any data unless some option (ATM -g to get all the data) is given.`

Right! What I meant is: If there is `-g` then `--content` (in my notation - see above) could specify what data and default to `required`.

**Comment by mih** [comment]
Discussion can be considered over now
