### ISSUE TITLE
Fate of --pbs-runner?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1588]
Currently this is an argument of every command -- not a common argument (like `--output-format`), but really one of each and every command. This makes already long option lists even longer. I'd argue that for a number of commands this is pretty useless (e.g. `create`, all plumbing commands).

**Comment by mih** [comment]
Any response @yarikoptic

**Comment by yarikoptic** [comment]
Yeah, feels like probably not for every one, but it's implementation is very generic and sits in the common args processing. I do use it from time to time but indeed only with crawl command

**Comment by mih** [comment]
Nobody cares.
