### ISSUE TITLE
How much would it take to have no (semipermanent) GitPython Repo instances anymore?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1600]
GitPython self-describes as "leaky", not suitable for long running processes. Despite that we have repeatedly RF'ed our code to _increase_ the lifetime of GitPython `Repo` instances.

I would like to assess how much it would take to minimize the usage of these instances. Please contribute your concerns and insights!

### Interim conclusion:

It seems viable to remove *ANY* usage of GitPython API outside outside our own Repo classes.

Moreover, with lazy loading of GitPython Repo instances in-place, our own repo classes should try hard not to access `self.repo` as much as possible.

### Usage of GitPython API (please help complete):

- `crawler` uses GitPython API to manage commits and tags, and all kinds of other things
- `crawler` tests use it for `diff`s
- `remove` to locate submodules (gone with #1604)
- `update` tests to query tags (gone in #1602)
- `save` to ask for the lastest commit shasum (gone with #1605)
- ~~`aggregate` to add a file to git~~  [false positive]
- `Dataset` to get the gitdir path (gone in #1606), and to checkout a commit (rarely used, if ever)
- ~~`get` to update submodules~~ [false positive]
- `publish` to diff against the latest commit, check remote branch existance (gone in #1544)

**Comment by mih** [comment]
So as far as I can see the crawler is the last bit to use GitPython API directly. @yarikoptic any reason (other than old age) why the crawler should not be using our highlevel API, and stick with the Repo interface only?

**Comment by yarikoptic** [comment]
Probably age and doing some quick and dirty solution are times (eg for use of diff)
