### ISSUE TITLE
Should meta-data be unified

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1601]
Related to #1589 
I wondered if we should make meta-data handling hierarchical, similar to the configuration (`where` currently supporting `datalad`, `local`, `global`) with  inheriting, so possible `where` for defining meta could be
- `dataset` -- `.datalad/meta` thus using the schema we already have) 
- `directory` -- not supported at all ATM, but we could have .datalad/meta there similar to dataset level) 
- `file` ( git-annex)

while unifying/extending our scheme (http://docs.datalad.org/en/latest/metadata.html#json-ld-meta-data-format)?

**Comment by mih** [comment]
I think supporting hierarchical would be useful, but at the same time also tricky. I would be able to set a "tag" for all files in a subtree. At the same time, I would not be able to use such a tag to move data via annex.

I find it difficult to map triples onto annex' meta data capabilties. Hence in #1589 I went for unification with annex (except for key definitions). I think this works well. Provides a meaningful, yet minimal metadata system that complements "bigger", but separate metadata sets.
