### ISSUE TITLE
`create` should initialize datasets with a default README file

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1612]
This file should identify a repository as a datalad one, and should give an uninitiated reader some info on datalad and how to make use of the repo, as a dataset. This is related to #1462 

Some inspiration for default README content could be taken from: https://github.com/psychoinformatics-de/studyforrest-data-phase2/blob/master/README.rst

**Comment by yarikoptic** [comment]
I don't think we should create by default... Should be a part of templating

**Comment by mih** [comment]
This is no possible by running the `add_readme` plugin via `--run-after` on `create`.
