### ISSUE TITLE
Use of `///` in documentation is confusing

### ISSUE THREAD

**Issue by chrhaeusler** [datalad/datalad#1631]
Hey magicians, 

I am reading through the documentation to familiarize myself with datalad but I am stuck at the example using the -dataset argument ("datalad install -d/// crcns"; s. [API-Principles](http://docs.datalad.org/en/latest/basics.html#api-principles)). 

What I have done so far:
- manually created the folder ~/datalad and made it my current directory
- ran "datalad install ///" to clone the superdataset to the subdirectory "datasets.datalad.org"

The problem:
- running the suggested command "datalad install -d/// crcns" raises the Error
> [ERROR  ] No installed dataset found at /home/psyinfolaf/datalad. [dataset.py:require_dataset:529] (ValueError) 
- running the alternatively suggested command "datalad install $HOME/datalad/crcns" raises a warning
> [WARNING] path not associated with any dataset [get(/home/psyinfolaf/datalad/crcns)] 
> get(impossible): /home/psyinfolaf/datalad/crcns [path not associated with any dataset]

Do you have any tips regarding what might be the problem or what I might have overlooked?
Olaf

edit:
I switched to using "datalad install -r ///crcns" that works as expected

**Comment by mih** [comment]
This is indeed confusing:

````
mih@meiner /tmp % mkdir bug
mih@meiner /tmp % cd bug
mih@meiner /tmp/bug % datalad install ///
[INFO   ] Cloning dataset from 'http://datasets.datalad.org/' (trying 2 location candidate(s)) to '/tmp/bug/datasets.datalad.org' 
install(ok): /tmp/bug/datasets.datalad.org (dataset)
mih@meiner /tmp/bug % datalad install ///crcns
[INFO   ] Cloning dataset from 'http://datasets.datalad.org/crcns' (trying 2 location candidate(s)) to '/tmp/bug/crcns' 
install(ok): /tmp/bug/crcns (dataset)
mih@meiner /tmp/bug % datalad install -d/// crcns
[INFO   ] Cloning dataset from 'http://datasets.datalad.org/crcns/.git' (trying 1 location candidate(s)) to '/home/mih/datalad/crcns' 
[INFO   ] Submodule HEAD got detached. Resetting branch master to point to a4e0e979. Original location was f70f9822 
install(ok): crcns (dataset) [Installed subdataset in order to get /home/mih/datalad/crcns]
````

but this only worked, because I had `///` installed at $HOME/datalad. When I move it aside, and wipe `/tmp/bug` I get this:

````
mih@meiner /tmp/bug % datalad install ///
[INFO   ] Cloning dataset from 'http://datasets.datalad.org/' (trying 2 location candidate(s)) to '/tmp/bug/datasets.datalad.org' 
install(ok): /tmp/bug/datasets.datalad.org (dataset)
mih@meiner /tmp/bug % datalad install -d/// crcns
[ERROR  ] No installed dataset found at /home/mih/datalad. [dataset.py:require_dataset:529] (ValueError) 
````

**Comment by mih** [comment]
So the immediate bug is that the documentation does not make it clear that `///` and `///` are two different things (in the current implementation), depending on whether the symbol appears as a source/path argument to `install` (maybe others too) or as an argument to `--dataset` for any command. If one reads closely, it is possible to get that -- but it is not easy.

Not sure how to rectify this. Any ideas @yarikoptic ?

**Comment by yarikoptic** [comment]
Yeah, a little confusing. I guess we should just indeed explain a bit more this part is magic.
As for the original issue, just remove your manually created `~/datalad`, and either do `datalad install -s/// ~/datalad` or just `datalad search something` which would do it for you

**Comment by mih** [comment]
@chrhaeusler  are you happy with the present state?

**Comment by chrhaeusler** [comment]
I think it is fine the way it is.

**Comment by mih** [comment]
Cool, closing.
