### ISSUE TITLE
RFC: should may be each plugin command  be also an independent 'datalad' command?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1633]
I wondered "why not" I should type "datalad plugin wtf" instead of just "datalad wtf", or "datalad plugin wtf --show-plugin-help" instead of "datalad wtf --help"... ?

**Comment by mih** [comment]
Sure. But be careful: plugins are user supplied, hence a user needs to be prevented to replace datalad's own commands, including future ones.

Second, to write a plugin, one needs to provide a single python function, with almost no boilerplate code. To turn this into a proper command requires significantly more work.

Also, plugin calls fit into config items. Command calls can be rather complex.

That being said, I definitely see some functionality start off as a plugin, and later make its way to become a full command.

**Comment by mih** [comment]
Yes, it should and things are (slowly moving in this direction). The last part of my counter argument above become obsolete with 'procedures'.
