### ISSUE TITLE
[wishlist] run/rerun tandem

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1650]
Just discovered https://dataversioncontrol.com/ from the blog post https://medium.com/towards-data-science/how-to-version-control-your-machine-learning-task-cad74dce44c4  and thought that it is a nice feature to have indeed and should be very easy to implement!

1. `run cmd args` would 
   - verify that we are in a clean state
   - go through args and check if any point to file under annex control, and if that one is not present locally -- download it
   - execute the `cmd args`
   - `datalad -m "RUN <cmd> <args>" save` all changes

2. `rerun` (repro in DVC) probably with options for either to

 - `--steps=[all,N]` to rerun all commands or just last N,
- `--use-current-state` -- to use current state (thus using recent code version, I think it is what DVC does) or by default checkout previous states to check  if external changes impact our results

and with that it would

  - traverse git history (so we do not need to store anything else) to establish which files were output (thus changed) in any 'RUN' commit, and which were input, so we could build DAG on the fly, collect commands needed to be reran
  - execute commands, while either checking out those commits in case of no `--use-current-state` or just replacing input files with symlinks to their keys as discovered by traversing the history

Even without `rerun` I think it could be quite neat!  paired with the power of `git reset [--hard]` and `git commit --amend` I think I might use it pretty much for anything I would run in that repository ;) And then rerun could come handy as well.  There could be additional options

- `--branch=name` to rerun in a specific branch, may be even cherry picking (or even rerunning?) commits which do not have anything to do with this file.  This way we could later compare, similar to testkraut, at which step diversion happened etc while reproducing a full history

**Comment by yarikoptic** [comment]
Implementation details to keep in mind:
- storing command in the commit message should use e.g. `repr` on the list of arguments to guarantee being able to get back to it in case of spaces in the filenames etc

**Comment by mih** [comment]
I think the `rerun` case might come with lots of corner cases. However, the `run` case is straightforward, and coincidentally exactly the way that I use to construct my datasets. I would give this a go, if nobody beats me to it.

**Comment by mih** [comment]
Thought: it can be tough to figure out which data files a command will need from the command line. We could go testkraut-style and which the actual syscalls to intercept anything that aims for something underneath a dataset. But that also comes with its own problem.

That being said, even without the auto-download aspects (for which we could eventually have multiple methods) it would still be useful. In my original datasets I typically have all data available anyways, hence for these cases I'd loose none of the benefits.

**Comment by yarikoptic** [comment]
I am yet to play a bit with DVC and see may be we could just adopt it instead of reimplementing partially or fully ;)

**Comment by mih** [comment]
Functionality that is available in current master is good enough for me for now. Unassigning.

**Comment by mih** [comment]
Will close this for now as nobody is working on it. The command is present and can be improved once the need arises.
