### ISSUE TITLE
publish doesn't publish anything if provided a path to publish (in enh-metadata 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1655]
```shell
$> datalad publish --to=atlantis.dartmouth.edu .
```
just returns silently in enh-metadata (0.7.0-171-gdf33bb9b) or dev-master (0.7.0-88-g210a3d73)

I guess there might have been a change of API/behavior again

**Comment by mih** [comment]
I will close this as that branch has been completely rebased, and, moreover, isn't finished yet. We had a bunch of `publish` bugs that were fixed. The thing that needs attention is `--transfer-data=auto` (default) in combination with a given path. At present the above command means: publish this dataset (in a git push sense) and leave it to annex to decide what data to copy. That may or may not make sense, but if not we have to tackle this on a more conceptual level and need an issue that summarizes the various flavors of apparent `publish` confusion (human and machine).
