### ISSUE TITLE
copy_to/publish ATM do not report errors back :-/

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1659]
ATM (0.7.0-77-gd9b44b2b) if some files failed to be copied (in my case was due to outdated UUID for that remote recorded, see #1656) doesn't provide any error output... it is that results rendering which I haven't yet mastered/fixed... may be @mih already did it in his development branch (but API of which has possibly changed, see #1655)

**Comment by mih** [comment]
this should not be reported properly in master
