### ISSUE TITLE
NF: create/update dataset with urls (CSV) pasted from the clipboard/loaded from file

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1665]
brought up by @satra
someone using http://openneu.ro/metasearch/  could easily obtain a CSV with urls (or just a list of urls AKA CSV with 1 column), would be nice if we could populate a dataset from them while having flexibility for the filenames, based on the columns present in URL

options to provide:
- construct the filename from url (e.g. stripping url portion, or common prefix)
  - `--filename-format {1}{subjid}.nii.gz`
  - reserve may be special field `url_filename` and may be `disposition_filename` to be available as well?
- construct filename from the CVS columns (e.g. if the 2nd column contains unique subjid).  Add option to fail if existing/override happens.
- construct URL from the pasted content (similar to filename)
   - `--url-format http://prefixedurl/{1}`
   - `--csv-header --format http://prefixedurl/{subjid}` 
- construct subdatasets automagically
   - `--subds-regex `
   - `--subdataset-format {subjid}//{preprocessing}` -- so may be use magical `//` to identify dataset boundary (e.g. oposed to `{subjid}/{preprocessing}` which would be a subdataset under root dataset but under subdirectory 
- `--use-disposition-filename` ... might need to be automagic???
- support addurl --fast mode of operation with URL backend instead of smth else.  It might work surprisingly well whenever URLs include versioning information (e.g. version for S3 http urls etc)
- should handle also loading from .json containing a list of items (dicts or lists), so the same as csv just in json (such as @satra gave for dropbox entries)

**Comment by mih** [comment]
This screams to be a plugin (first).

**Comment by satra** [comment]
are you screaming with a glass of scotch?

**Comment by mih** [comment]
Scotch is waiting for the Gin to calm down...

**Comment by mih** [comment]
Hmm, so a CSV file with a bunch of URLs is then not a suitable way to provide a dataset template? Just gimme a single function that does that and I will put in the two additional lines to make it a plugin.

**Comment by satra** [comment]
git-annex addurl already takes care of many of these things.

`cat freesurf.txt \
  | git-annex addurl --fast --batch --with-files -J10`

freesurf.txt is here: https://www.dropbox.com/s/8tqs6d3ez0kvd1b/freesurf.txt?dl=0

**Comment by yarikoptic** [comment]
one of the initial usecases will be the http://openneu.ro/metasearch to get that spreadsheet and crate a DataLad dataset with metadata tags attached to each file to easily create views and selections using git-annex.

**Comment by satra** [comment]
or add a metasearch skin on top of datalad datasets, which can then create new datasets.

**Comment by yarikoptic** [comment]
yeap, metasearch skin could be yet another consumer for the metadata we "aggregate" (as discussed in all those recent issues I keep loosing track of ;-) ).

**Comment by yarikoptic** [comment]
I consider it resolved by adding addurls which should be released as a part of the 0.10 release
