### ISSUE TITLE
--on-failure=ignore seems to not work

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1692]
As mentioned in issue #1691, calling `datalad --on-failure=ignore publish -r --to=public` in the workflow of the nipype example still returns non-zero for some reason.
Need to have a closer look.

**Comment by bpoldrack** [comment]
Tried to build a minimal case. Empty dataset (`datalad create` in an empty dir).
`--on-failure=ignore` works for `get`, but doesn't for `publish`, which still returns non-zero:

```
ben@tree /tmp/TEST_ON_FAILURE % datalad get non-existent 
get(impossible): /tmp/TEST_ON_FAILURE/non-existent [path does not exist]
ben@tree /tmp/TEST_ON_FAILURE % echo $?
1
ben@tree /tmp/TEST_ON_FAILURE % datalad --on-failure=ignore get non-existent
get(impossible): /tmp/TEST_ON_FAILURE/non-existent [path does not exist]
ben@tree /tmp/TEST_ON_FAILURE % echo $?
0
ben@tree /tmp/TEST_ON_FAILURE % datalad publish --to=non-existent
ben@tree /tmp/TEST_ON_FAILURE % echo $?
1
ben@tree /tmp/TEST_ON_FAILURE % datalad --on-failure=ignore publish --to=non-existent
ben@tree /tmp/TEST_ON_FAILURE % echo $?
1
```

**Comment by bpoldrack** [comment]
FTR: This is on dev-master.

**Comment by bpoldrack** [comment]
Update: Turns out introducing an additional debug output in `interface/utils.py`, line 479

```python
        if res['status'] == 'error':
            lgr.debug("Got an error: {0}\non-failure: {1}".format(res, on_failure))
```

results in:
```
Got an error: {'status': 'error', 'process_content': True, 'action': 'publish', 'path': '/tmp/TEST_ON_FAILURE', 'message': ("Unknown target sibling '%s' for publication", 'non-existent'), 'type': 'dataset', 'refds': '/tmp/TEST_ON_FAILURE'}
| on-failure: continue
```

So, somehow the value `ignore` changed to `continue`.

**Comment by bpoldrack** [comment]
Okay, `common_params` appear to generally ignored by `publish` - they don't make it to `eval_func` in `interface/utils.py`. Instead it's all default.

**Comment by bpoldrack** [comment]
Got it, I guess. `publish` looks refactored and uses `@eval_results`, `@build_docs` and so on, but it's still excluded in `interface/base.py`, line 392.
@mih: Is this intentional?

**Comment by mih** [comment]
No, not intentional! There are a few more rough things in it, it seems. Please fix!

**Comment by mih** [comment]
I guess this can be closed now.
