### ISSUE TITLE
add-archive-content needs to deal with already existing special remote

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1693]
While exercising the nipype example step by step I ran into this one. Due to something missing in the `PATH`, `datalad add-archive-content` failed, which is fine. But then I couldn't call it again. It would fail in any case, since it tries to call `annex initremote`. And that part worked in the first run already. Now the special remote already existed, which is why the call to `initremote` fails, recommending to call `enableremote`.
@yarikoptic : Is there a way to deal with it, which I may have missed?

**Comment by yarikoptic** [comment]
> Due to something missing in the PATH, datalad add-archive-content failed

I guess that is the first thing to figure out what was missing and why, since nothing should be missing

**Comment by bpoldrack** [comment]
That's not the point. I know what was missing (couldn't find patoolib). But when this issue is fixed, the command wouldn't run anyway. That's the point. As soon as there is a special remote `datalad-archives` already `add-archive-content` fails, since `annex initremote` fails. `add-archive-content` needs a way to not fail, when the special remote is already there, I guess. Meaning: It should either use `enableremote` instead or just proceed.

**Comment by yarikoptic** [comment]
1. yes -- check/actions should be improved:
https://github.com/datalad/datalad/blob/master/datalad/interface/add_archive_content.py#L294
currently
```
        if ARCHIVES_SPECIAL_REMOTE not in annex.get_remotes():
            init_datalad_remote(annex, ARCHIVES_SPECIAL_REMOTE, autoenable=True)
```
2. all archives are added using the same remote, so indeed would be applicable to adding any archive

**Comment by bpoldrack** [comment]
Hm. This is confusing, since it apparently is supposed to call `initremote` only if it wasn't there. But I got a failure from `initremote` stating, that the special remote already exists and I should try using `enableremote` instead.

**Comment by bpoldrack** [comment]
Long standing, not addressed yet. Looking at it, I think the line above should use `get_special_remotes` instead.

**Comment by yarikoptic** [comment]
so what did you find @bpoldrack ? ;)
