### ISSUE TITLE
Workflow demo: Within-lab data-sharing

### ISSUE THREAD

**Issue by mih** [datalad/datalad#170]
Cheap memory saving clones, nice separation of workspaces between co-workers, structured exchange of data

**Comment by yarikoptic** [comment]
would indeed be nice to have it

**Comment by mih** [comment]
To some degree in `3rdparty_analysis_workflow.rst`, but could be accompanied by a demo on nested datasets and cheap copies.

**Comment by mih** [comment]
Good enough.
