### ISSUE TITLE
Providing a dataset instance as `source` for `install` yields `None` and no error

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1701]
Just a note for now, discovered when debugging merge conflicts. @bpoldrack can you investigate this, please?

**Comment by bpoldrack** [comment]
FTR (if we later run into something similar): Reporting no error is fine, since `install` (as well as `clone`) is supposed to work with a `Dataset` instance as `source` argument (and does so). The issue is the result reporting, which went wrong due to a bug in `ìnstall`'s default result filter.
