### ISSUE TITLE
[wishlist] User convenience: registry of the available (to me) hosting servers

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1702]
Upon ultimate datalad configuration wizard could ask about available hosting resources of the types we might support (github, Dropbox, Box, public ssh-accessible-to-you HTTP servers, google drive), so kinda similar to what rclone does.

When user attempts to publish a dataset to a given registered name, it would automagically figure out the server/type/etc and publish it there UNDER some location. 
We kinda implement it already with `--inherit` for operation within a hierarchy (which disambiguates where on the hosting service to place it under) but it would be nice also to be able to support this way somehow disjoint datasets.

Greedy user might want us to be able to be able to split data load across multiple servers and it still work ;)

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
