### ISSUE TITLE
removed dataset even though drop of one file was impossible!

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1703]
```shell
drop(impossible): /home/yoh/datalad/workshops/mind-2017/sherlock (directory) [could not drop some content in /home/yoh/datalad/workshops/mind-2017/sherlock [u'/home/yoh/datalad/workshops/mind-2017/sherlock/1']]
uninstall(ok): /home/yoh/datalad/workshops/mind-2017/sherlock (dataset)

```
using 0.8.0

**Comment by mih** [comment]
Hehe, this is a side-effect of our move to "continue despite errors for as long as possible". The current code `distribution/remove.py` around line ~260 was written under the assumption that yielding `impossible` will stop the process. I was afraid something like this would pop up....

**Comment by yarikoptic** [comment]
may be for some commands (like remove) we could switch it to the "fail as soon as possible mode"?

**Comment by bpoldrack** [comment]
Shouldn't this be closed by now?

**Comment by mih** [comment]
No, we only close when fixes end up in master -- hence we have so many with "fix implemented".
