### ISSUE TITLE
!datalad --help  in ipython with systemwide installed, goes to man pages -- rendering is screwed up

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1711]
![rendering](http://www.onerussian.com/tmp/gkrellShoot_08-11-17_132239.png)
I do not think it is our fault, since I could run e.g. `!man ls` or `!git commit --help` to get the same screw up.

ipython is 
```
The version of the notebook server is 4.0.6 and is running on:

Python 3.5.3 | packaged by conda-forge | (default, Feb  9 2017, 14:37:12) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

```

it is a problem similar to the progressbars handling in ipython (#1541) -- we could only discover that we are under IPython session but cannot tell anything about frontend and its capabilities really.  E.g. terminal ipython would render our progressbars and manpages just fine, while web frontend would require custom progressbars and `--help-np` output.  It feels that we might want by default to assume safest default, which would be a mix of -- our broken-in-webfrontent progressbar + --help-np output. And then allow explicit specification of the mode (e.g. `datalad.set_ipython_frontend('web')`)

**Comment by mih** [comment]
I don't care much about this particular usage in ipython, but whatever change is made should not impair behavior in the common case, shell + a proper terminal. Can you suggest a robust test to distinguish this case from the more exotic ones like the ipython use case?

**Comment by yarikoptic** [comment]
as I have mentioned in the description, I do not know any way (yet).  But why would I particularly care, let's just turn away and consider it never happened -- I will leave it for someone else to reopen when they discover this hidden treasure
