### ISSUE TITLE
--annonimize-date 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1718]
git annex now allows to specify the date for to be used while recording time stamp(s) within git-annex branch files.  It allows now to fake all the dates stored in the git/git-annex repo:

```shell
$> da=40; d0="Thu Jan 1 00:00:$da 1970 +0000"; rm -rf /tmp/test; GIT_ANNEX_VECTOR_CLOCK=$da GIT_AUTHOR_DATE="$d0" GIT_COMMITTER_DATE="$d0" datalad create /tmp/test
[INFO   ] Creating a new annex repo at /tmp/test
create(ok): /tmp/test (dataset)                                                                                                                         
2 10381.....................................:Tue 15 Aug 2017 01:33:12 PM EDT:.
hopa:/tmp
$> git -C /tmp/test log -p git-annex
commit 5af2c2a04319a362417250aef269002e25c1d356 (git-annex)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Thu Jan 1 00:00:40 1970 +0000

    update

diff --git a/uuid.log b/uuid.log
new file mode 100644
index 0000000..748db51
--- /dev/null
+++ b/uuid.log
@@ -0,0 +1 @@
+97b0f01c-d7eb-44ed-813f-7c0723fd8a90 yoh@hopa:/tmp/test timestamp=40s

commit 0096b601c565ac1efd2535363880ebe7c8f278e1
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Thu Jan 1 00:00:40 1970 +0000
```

We are going to use it within the scope of heudiconv, but I wondered if we should provide interface to this functionality within datalad itself.

- pros: might come handy in other use cases where dates should be obfuscated
- cons: REALLY easy to shot yourself in the foot, so it would warrant at least some checks (that previous commit in git and git-annex has date(s) before or == etc)

**Comment by ljchang** [comment]
This seems like it could be useful functionality to have built into datalad at some point and not fully relying on heudiconv.  I'm imagining a scenario where someone wants to publicly publish a dataset and wants to ensure the data are fully anonymized.  This might include scrubbing names and scrambling dates.  They might not have used heudiconv at the outset and also not realize that the data creation dates might be tied to identifying subject information.

**Comment by yarikoptic** [comment]
The strategy should probably be
- for initial commit - take some date in the past
- take the latest date from
  - the last commit within the branch and git-annex branch in the dataset
  - the same for each subdataset to be committed
- increment by some amount of past time (1 second)

And it should be implemented at the level of `commit` operation based on some envvar flag to trigger it (since would be difficult if not impossible to channel that flag for all commands which `commit/save`)

**Comment by mih** [comment]
I think this is done now. Reopen, if I am wrong.
