### ISSUE TITLE
git-annex protocol field splitting breaks TRANSFER command parsing in some cases

### ISSUE THREAD

**Issue by joeyh** [datalad/datalad#1727]
The git-annex special remote protocol is somewhat unusual in that the last field of a line can contain whitespace, while all previous fields cannot. So, simply splitting by whitespace can result in more fields than expected, when there is in fact whitespace in the last field.

This is particularly a problem for TRANSFER, since the filename passed as its last field does contain whitespace in some edge cases. Note that the external special remote documentation used to incorrectly say it never contained whitespace.

datalad/customremotes/base.py appears to have this problem. In _loop, it calls self.read(n=-1). I believe that splits each word into a separate string. If the command was "TRANSFER SEND somekey multi word file", it will probably blow up in some way.

One way to test for the problem is to make a git-annex repository in direct mode that contains an annexed file with a space in its name. Transferrring the file to the special remote will pass the filename to the TRANSFER command. That may also happen when transferring the file from the special remote, but I've not checked.

(Also, there'a a TODO in read() asking how git-annex deals with filenames starting/ending with spaces. The answer is that it simply puts the space there, so it's possible to have eg, "TRANSFER SEND key  " where the filename part is " ". I don't know if your current code handles this case when read() is called with the correct number of words to split into. Depends on how python's string splitting works..)

**Comment by joeyh** [comment]
Here's a git-annex special remote, also written in python, that seems to handle this in a nice way: https://github.com/bgilbert/gcsannex/blob/master/gcsannex.py

It seems to be introspecting the function that will be called to handle a command, to determine how many parameters it expects:

                argv = self._splitargv(argstr,
                          len(get_function_args(method)) - 1)

**Comment by yarikoptic** [comment]
Thanks for the note. Yeap, I will fix up for it with function signature introspection later on

**Comment by yarikoptic** [comment]
@joeyh Should I become completely paranoid and assume that that last argument might also start with a space? ;)  the "pythonish" problem is that `.split()` splits on multiple spaces too, i.e.:
```ipython
In [2]: "1  spaces ".split(None, 1)
Out[2]: ['1', 'spaces ']
```
so leading to `spaces` space is swallowed.  We could easily workaround by using more strict `re.split(" ", ...)` but thought to avoid such heavy artillery.  
NB might be of interest to @bgilbert as well ;)

**Comment by joeyh** [comment]
Yes, it's possible that the last argument contains a leading space.

-- 
see shy jo
