### ISSUE TITLE
RF interface/diff.py:_get_untracked_content() into *Repo.get_status()

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1731]
... and RF accordingly.
See https://github.com/datalad/datalad/pull/1724#discussion_r133929993

**Comment by mih** [comment]
Maybe the issue title could be tailored a little, to be able to decide if this has been dealt with.

**Comment by mih** [comment]
https://github.com/datalad/datalad-revolution has both low-level Repo.status() and high-level `rev-status` command.
