### ISSUE TITLE
Add unlocking handling to AutomagicIO mode 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1739]
ATM just handles `'r'` only operations and skips the rest.  Should monitor for `w` and `a` and automatically get it first (if `'a'`), then unlock (in either `'a'` or `'w'` modes)

**Comment by mih** [comment]
Now that we can easily produce asciicasts, we should have one that shows how to use automagic IO in a Python script for, e.g. a demo.

**Comment by mih** [comment]
Close in favor of #1924
