### ISSUE TITLE
Have something else than fMRI data to show

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#174]

**Comment by hanke** [comment]
- Stimulus database (faces, music, ...)
- Simple timeseries or other statistics (e.g. from http://ec.europa.eu/eurostat/data/database)

**Comment by yarikoptic** [comment]
1. some experiments/datasets come with stimuli (e.g. haxby2001)
2. we already have some annexes of non-fMRI nature, so if we include them -- it would resolve this issue
- https://github.com/datalad/nih--videocast
- https://github.com/datalad/brainfacts--2012-edition
- https://github.com/datalad/mlbooks

**Comment by hanke** [comment]
Cool.

**Comment by hanke** [comment]
No need to keep this open at this point.

**Comment by mih** [comment]
With this https://github.com/datalad/datalad/pull/1630/commits/c6a55f0673f05d72363f1f222f8d4db79fe1b273 datalad is now also a music database.
