### ISSUE TITLE
Installers for major platforms

### ISSUE THREAD

**Issue by mih** [datalad/datalad#176]
- [x] Debian/Ubuntu, NeuroDebian

ATM manualish (git-annex + pip within conda or not):
- [x] Mac
- [ ] Windows

AFAIK as of today (20180111) git annex standalone builds run fine across a variety of elderly kernels/distributions

Ongoing related efforts:
- Nuitka build: https://github.com/datalad/datalad/pull/1889
- Conda recipe (awaiting acceptance of git-annex first): https://github.com/conda-forge/staged-recipes/pull/1720

P.S. @yarikoptic introduced changes updating the status of affairs

**Comment by yarikoptic** [comment]
* (Neuro)Debian -- should be easy now, that there is git-annex-standalone ;)  I can take care about that one
* Mac, Windows -- had those beasts in mind from day one as you know (datalad executable on windows already generated if you do setup.py install), so for those we could start with upload to pip (which we should do anyways), but that would not resolve git-annex dependency.  Ultimate solution would be monolithic bundles for those platforms.  While "bundling up" we might consider making also a bundle for any Linux

**Comment by hanke** [comment]
Quick feedback on platform availability. I asked the openfmri guys to use
git annex to pull in the new data release. They came back with "cannot
fullfill kernel version requirements on our platform". They are on some
Redhat version. Didn't investigate if that issue is real or not.

**Comment by yarikoptic** [comment]
On Tue, 23 Jun 2015, Michael Hanke wrote:

>    Quick feedback on platform availability. I asked the openfmri guys to use
>    git annex to pull in the new data release. They came back with "cannot
>    fullfill kernel version requirements on our platform". They are on some
>    Redhat version. Didn't investigate if that issue is real or not.

just ask which RH.  We will check in VM and then I should initiate a
docker for testing with some centos

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by hanke** [comment]
It is RHEL5 with a 2.6.18 kernel. Welcome to the real world ; -)

**Comment by yarikoptic** [comment]
@joeyh (if you have any internet wherever you are ATM) -- have you had a joy of trying git-annex on such an old beast? (RHEL5 with 2.6.18 kernel)?

**Comment by yarikoptic** [comment]
FWIW @hanke: I am pooling in some random centos 5.6 vagrant image to try on smaug

**Comment by yarikoptic** [comment]
FWIW -- indeed:

```
[vagrant@localhost tmp]$ git annex version
FATAL: kernel too old
[vagrant@localhost tmp]$ cat /etc/redhat-release 
CentOS release 5.6 (Final)
```
So let's wait for @joeyh 's advice ;)  most probably it could be built, but it would be a bitch I guess

**Comment by yarikoptic** [comment]
FWIW -- annex standalone passes all the tests on centos6 with 2.6.32-431.el6.x86_64

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> [vagrant@localhost tmp]$ git annex version
> FATAL: kernel too old

This is actually glibc complaining..

-- 
see shy jo

**Comment by yarikoptic** [comment]
And it would be prohibitively difficult (or impossible) to setup standalone build system on a similarly old box?

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> And it would be prohibitively difficult (or impossible) to setup standalone
> build system on a similarly old box?

Would need bringing up ghc on this platform from scratch, so at least as
hard as adding a new CPU architecture. Plus possibly missing functions
in the old glibc..

-- 
see shy jo

**Comment by yarikoptic** [comment]
official whining at git-annex bugs:  http://git-annex.branchable.com/bugs/Set_some_reasonable_requirements_lower-bound_for_linux_standalone_builds:_no_longer_usable_on_CentOS_6.5

**Comment by satra** [comment]
hey folks, i ran into this just now. any solutions yet? btw, the git-annex install page has no link to source :(

**Comment by yarikoptic** [comment]
@satra how old is your base system Satra?

**Comment by yarikoptic** [comment]
@satra as for source -- install page has "Building it yourself" section which leads to information on sources source ;-)

**Comment by satra** [comment]
2.6.32-504.30.3.el6.x86_64

**Comment by satra** [comment]
my my - so blind!

**Comment by yarikoptic** [comment]
@satra try this build ;)  https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-i386-ancient.tar.gz

**Comment by satra** [comment]
386? so 32 bit only? will it be good with large files?

**Comment by yarikoptic** [comment]
as ancient as it could get I guess ;)  try and share you experience ;)

**Comment by yarikoptic** [comment]
https://github.com/takluyver/pynsist might come handy for windows whenever/if we support it again

**Comment by yarikoptic** [comment]
conda update -- git-annex is now available from conda-forge for Linux!  DataLad recipe updated and being worked on: https://github.com/conda-forge/staged-recipes/pull/1720 -- I think we are not lacking any depends any longer in conda.

**Comment by mih** [comment]
I think we can close this now. Installation is quite possible on all major platforms now, and we have moved on to actually making things run ;-)

http://handbook.datalad.org/en/latest/intro/installation.html
