### ISSUE TITLE
Consolidate calling `git update-server-info`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1765]
After #1764 we now have two implementations that are fairly similar, one in publish.py and the other in create_sibling.py

**Comment by yarikoptic** [comment]
imho duplication is so small that not sure if worthwhile sweating over some centralized implementation ATM.  Please reopen if disagree

**Comment by mih** [comment]
FTR: @bpoldrack had fun today with this one

**Comment by bpoldrack** [comment]
Right, ended up with post-update-hook not called at all. I'll make a proper report once I'm done with what I'm actually doing.

**Comment by bpoldrack** [comment]
FTR: post-update hook was created the way it is defined in `create-sibling` and is executable. However, it didn't run. It doesn't even have any effect, if I run it manually. It just exits zero, but there's neither any `.datalad/logs` created nor any output.

to be continued
