### ISSUE TITLE
Any sense in completely throwing away runtime ENV in Runner.run()?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1776]
When I use `AnnexRepo._run_annex_command()` and I need to pass in a single ENV var, I use the `env=` kwarg. However, that seems to throw away the entire ENV customization that we internally need to actually make any sensible git or annex calls. I fail to see any application where we would want to use this feature.

If that is correct: we should change this behavior to **update** the runtime env with the dict that is given to `Runner.run()`.

If that is not correct: we need another kwarg to do exactly that.

Please advise

**Comment by yarikoptic** [comment]
Yes, we could refactor but we will need to check the code first if we ever rely on passing entire or sanitized environment. I remember in at least one case (probably more) just updating os.environ. one use case, when sanitization is needed for some env variables, setting their value to none in the dictionary could signal that they needed to be removed (still allowing for an empty string)

**Comment by yarikoptic** [comment]
I wouldn't call it a bug though ;-)

**Comment by bpoldrack** [comment]
Well, I'm not sure. I tend to agree we should update instead. But: That would mean we have no way to have full control of the environment a call is running in. Might be troublesome.
However, there is a way in between. `Runner` also has an attribute `env`, which can be set via `__init__()`. May be the default for this attribute should be `os.environ` and the `env` parameter of `run()` should update this one. As of now the default is just empty.
That way we can easily set up a `Runner` instance with full customized environment if needed.

**Comment by bpoldrack** [comment]
Additional note: In any case this also requires to adapt `GitRunner`. Just saying, so we are aware.

**Comment by mih** [comment]
OK, I can feel the anxiety...

No full control: I am making an explicit call to `run()`, I pass the env var -- I am in control.

But what happens is that ANY command will fail, because it expects a tailored environment that I have no idea about. Hence, when I set `env=` things break.

We can call this a feature, but we have no such tag.

**Comment by mih** [comment]
Alternatively, how can I set an env var for a single call? Sure thing I can bypass the Repo classes and it would just work...

**Comment by mih** [comment]
It seems that this is the only code that needs changing for my particular issue:

```py
    @staticmethod
    def get_git_environ_adjusted(env=None):
        """
        Replaces GIT_DIR and GIT_WORK_TREE with absolute paths if relative path and defined
        """
        # if env set copy else get os environment
        git_env = env.copy() if env else os.environ.copy()
 ````

env should update os.environ and not replace it.

**Comment by bpoldrack** [comment]
Re "the only code to be changed":
Would work, but leads to an inconsistency, I think. Once at it, we should do it similarly if `Runner` is used directly instead of using `GitRunner`.

**Comment by mih** [comment]
There is no interest in this...
