### ISSUE TITLE
Why getpass_echo() and not input()/raw_input()?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1782]
`getpass_echo()` seems to have numerous issues, some described in its code. What is the reason for having it at all, and not using the standard methods in PY2 and PY3 respectively?

Reason from the code:

```
            #     # TODO: raw_input works only if stdin was not controlled by
            #     # (e.g. if coming from annex).  So we might need to do the
            #     # same trick as get_pass() does while directly dealing with /dev/pty
            #     # and provide per-OS handling with stdin being override
            #     response = (raw_input if PY2 else input)()
 ```

**Comment by mih** [comment]
Nobody is in the mood to talk about this.

**Comment by yarikoptic** [comment]
Not sure which standard methods you referred to, but the primary reason was to be able to request credentials while very deep in the sandwich of datalad annex datalad, and stdio is used for communication, not UI
