### ISSUE TITLE
Replace credential management with something simpler/more focused

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1783]
Re discussion at last meeting: We could switch to `pass`/pypass to have datalad manage the credentials it needs for its own purpose. We would be free to implement and naming scheme, would have the chance to search and list particular credentials.

`pass` uses a directory with GPG encrypted files as a password store. `annex` already relies on GPG, so there would be no additional dependency. `pass` is merely a bash script. `pypass` is a simple reimplementation of `pass`. Before we start doing something from scratch, we should consider using/building upon `pypass`.

**Comment by mih** [comment]
Initial rough test of `pypass` on windows:
- pip install pypass (check)
- run/import pypass (does not find some executable, presumably gpg)
- located gpg shipped with git-annex by hand and verified that it is functional (check)

TODOs:
- we would need to adjust how pypass locates gpg, I guess in the same fashion that we are using the Git that comes with git-annex.
- we would need to support generating a GPG key, if there is none already -- that would also be beneficial for being able to support annex content encryption more out-of-the-box

Otherwise, pypass seems to give us all features that I can think of.
- we have completely freedom on where to put the password store and how to structure it
- there are many pass client available to provide a management UI
- the password store itself is a git repo (very fitting)

**Comment by yarikoptic** [comment]
How password store is "unlocked"?

**Comment by mih** [comment]
all gpg

**Comment by yarikoptic** [comment]
Think about lame user without gpg agent... Will we need to ask password for every separate invocation of datalad? Or we will use current system to store that one systemwide?

**Comment by mih** [comment]
It seems short sighted to draw the line just prior proper gpg support for datalad. That will likewise exclude any data encryption management, and leave that to "experts". Especially for a community that both wants to use public services and exchanges sensitive data this seems like a major issue.

**Comment by mih** [comment]
ah, and to be clear. When we properly support encryption, pypass gives credential management for free.

**Comment by mih** [comment]
FTR: for a GNOME user unlocking via GPG key or via master password of credential store uses the exact same UI and works out-of-the-box

**Comment by bpoldrack** [comment]
Update on "missing executable on windows":

What is missing actually isn't `gpg`. It's `which`!
So `import pypass` fails if python is started from a windows shell, while it's working out of the box from within git-bash on windows.

**Comment by bpoldrack** [comment]
Using `pypass` on windows will not easily work.
It uses things like `which`, `grep`, etc., suggesting that it will either work in git-bash only or increase dependencies to account for these tools to be available in a regular windows shell.
Furthermore it depends on `pxshh` from `pexpect` which isn't supported on windows. (In addition the respective import statement used in `pypass` is incorrect)
So, we would basically need to fork `pypass` in order to make it work, I guess. Not sure what else would be waiting for us to be dealt with. On the other hand: It's not that big a piece of code, so it might be doable.

**Comment by mih** [comment]
FYI: git for windows comes with a credential manager.

**Comment by yarikoptic** [comment]
Keyring module supports extensions, so it should be possible to write backed for that one as well

**Comment by mih** [comment]
I am closing this one, it has outlived its purpose.
