### ISSUE TITLE
Support rclone-based special remotes

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1784]
Ship and test https://github.com/DanielDent/git-annex-remote-rclone to add out-of-the-box support for a bunch of commerical cloud storage provider (this is itself a wrapper around rclone; version in Debian is recent). Like with the webdav special remote credential management is left to a user and datalad could step in

TODO BUG: https://github.com/DanielDent/git-annex-remote-rclone/issues/29

**Comment by mih** [comment]
https://github.com/datalad/git-remote-rclone

**Comment by yarikoptic** [comment]
I do not think we should or will incorporate those inside, so should this be closed?

**Comment by mih** [comment]
Yes
