### ISSUE TITLE
version is out of date, no?

### ISSUE THREAD

**Issue by jgors** [datalad/datalad#179]
__version__ in datalad/version.py, though the newest tag is 0.0.2

**Comment by yarikoptic** [comment]
On Mon, 27 Jul 2015, jason gors wrote:

>    version in datalad/version.py, though the newest tag is 0.0.2

you are totally correct!  next time just fix such bold errors ;)

as for versioning -- I think we better adopt the way I did it in
duecredit (setup.py creates it, anyway we need to "deploy" for testing
development to generate entry points etc), or even use 
https://github.com/warner/python-versioneer
(remember lighting talk at pycon 14) although that one seems grew up a
bit into smth not that lightweight
