### ISSUE TITLE
Put benchmark run into Makefile?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1790]
I have to confess that I don't know how to run the benchmarks on my system. Any chance that this knowledge could make it into the Makefile? Thanks.

**Comment by yarikoptic** [comment]
And what should it do - run all benchmarks on all commits? Or some bench marks on some commits?

**Comment by yarikoptic** [comment]
again -- what do you want to benchmark really?  

PS `dict` knows about UX but not about DX.  What is it -- Developer experience? ;)

**Comment by yarikoptic** [comment]
I will add into CONTRIBUTING description of few common workflows for using asv.

**Comment by mih** [comment]
Ping. Short doc in contributuing.md would be much appreciated.

**Comment by yarikoptic** [comment]
WiP: #2413 - feel free to contribute
