### ISSUE TITLE
How to add things to git instead of annex?

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1798]
Our current approach doesn't work very well. Except for special cases (like `datalad create`) where we write to `.gitattributes`, the general approach is to distinguish between `git-add` and `git-annex-add` if we want to add a certain file to git.
This doesn't work with V6. Even if we successfully added sth to git this way, this is ignored later on when possible changes are made to that file and it needs to be staged again. There are several ways for such a file to end up in annex later on. As far as I'm aware a distinction entirely based on `.gitattributes` works well in V5 (direct and indirect mode) and V6. This suggests to do it this way only (RF everything involving `to-git`). But then we probably end up in a mess if we continue to allow for adding single files to git, since we then need to keep track, what is addressed by any pattern in `.gitattributes` already and figure out conflicts or redundant entries. An alternative would be to stop supporting single files being added to git.
Is there another solution (to that kind of issues when switching to a pure `.gitattributes` approach) you can think of?

Related question: Do we have any clue how to move sth. from annex to git and making sure it's not annex'ed again due to `.gitattributes`?
How about the opposite direction?

What about moving/renaming files/directories? Do we want to consider any kind of magic or aid to possibly adapt `.gitattributes`? Or are we just saying: "You messed it up, clean it!"

What are your thoughts on the matter, @yarikoptic , @mih ?

FTR: Somewhat related issues:
#1651, #1597, #1021, #358, #1462

**Comment by yarikoptic** [comment]
Valid concern!  Ideally v6 should operate similar to v5, and thus before anything, would be worth may be coming back to still open in annex http://git-annex.branchable.com/bugs/Too_difficult_if_not_impossible_to_explicitly_add__47__keep_file_under_git___40__not_annex__41___in_v6_without_employing_.gitattributes/

**Comment by bpoldrack** [comment]
Well, I did kind of come back to it, but it's really about a side-effect, not a fundamental thing. In general, Joey clearly stated, that `.gitattributes` is the way to go. Using a per-call `-c annex.largefiles=whatever` will not work, since it is insufficient to do this only when adding a file the first time. We would need to keep track of all files, that were explicitly added to git and call basically any annex command involving those files with that option again. So, we would end up building our own `.gitattributes` while still not being able to do it properly, since we don't always know what files will be touched by the smudge filtering.
Until now, we have the option to decide between git and annex on a per file basis.

So, from my point of view there are two options:
 1. a) keep that option and write files, that were explicitly added to git into `.gitattributes`. In the long run and depending on use cases, this might become a nightmare of a `.gitattributes` file. If we want to do that, how do we approach analyzing `.gitattributes` for matching, contradicting or identical entries?

    b) as above, but don't care about the possibly messed up `.gitattributes` and leave it to the user. Basically we are saying: That option is a convenience to add an entry to `.gitattributes`, but there's nothing more: we do not maintain that file for you.

 3. or we simply don't allow to add anything directly to git via a datalad command's option, but only via user-editing of `.gitattributes` (and special cases we manage on our own without user interaction)

**Comment by yarikoptic** [comment]
2 wouldn't work since there is still just git add people could use

I think the issue shopping be fixed at annex level, since that is what knows if any particular path was under git or annex... I do appreciate possible tech difficulty of implementation, but anything else wouldn't be robust IMHO. What is your thoughts ATM @joeyh?

**Comment by bpoldrack** [comment]
> 2 wouldn't work since there is still just git add people could use

That doesn't matter in v6. ;-)

**Comment by bpoldrack** [comment]
To be clear: "since there is still just git add people could use" doesn't make sense to me as an argument. This is true in any case. And I don't know how that matters. `git add` will respect `.gitattributes`

**Comment by yarikoptic** [comment]
RRight! Forgot about that. I think we should at least issue a big day warning when adding --to-git is used in v6. I would still not prevent it entirely.

**Comment by bpoldrack** [comment]
So, this is basically a vote in favor of 1b)?

Am 14.09.2017 14:44 schrieb "Yaroslav Halchenko" <notifications@github.com>:

**Comment by yarikoptic** [comment]
I guess so ;-)

**Comment by mih** [comment]
This issue is now obsolete (story in annex bug linked about). A file once in git, stays in git. No need for attribute settings, no need to switch away from `git add`
