### ISSUE TITLE
Store list of filenames in metadata to enable full identification of matching from from superdatasets

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1816]
One central issue of our recent discussion on metadata was the case of file look-up when a particular target dataset is still unknown, or unavailable.

In particular it was the issue of our inability to report exact filenames matching metadata records, when these records define the associated subset of file via a regex. Being able to report matching filenames is desirable, because this output can be used directly in subsequent processing (within datalad, e.g. `get`), or 3rd-party code.

One approach to make this happen would be to store a full list of filenames for each dataset in its aggregated metadata. More precisely, NOT storing metadata per file, but store a separate plain list of filenames for the purpose of resolving regex to concrete filename matches.

To check the feasibility of this approach I produced such a list for the entire super-dataset from datasets.d.o:

```sh
% find -H . -type f,l ! -path '*/.git/*' -a ! -path '*/.datalad/*' > filenames.txt
find -H . -type f,l ! -path '*/.git/*' -a ! -path '*/.datalad/*' >   5.27s user 31.69s system 91% cpu 40.346 total
% gzip -9 -c filenames.txt > files.gz
% du -sh file*
85M	filenames.txt
3.9M	files.gz
% wc -l < filenames.txt
1208830
```

So we have 1.2M files and would need to carry a total of 4MB of additional metadata combined across all datasets.

Note, that in my demo I store filenames with full paths down from the top-most superdataset (which we would not do, but store only filenames relative to the root of each respective dataset).

Also note, that such additional metadata storage does not live in Git (but is annexed), could be obtained on demand when such lookup is needed, and could be as much compressed as necessary. Likewise, there would be no single file, but, as with the other metadata, one file with filenames per dataset in the metadata object store of the superdataset.

I think this is a pretty good deal.

**Comment by bpoldrack** [comment]
I agree. This seems to be a good compromise.

**Comment by mih** [comment]
Done in #1630.
