### ISSUE TITLE
Use '--' path separator in GitRepo._git_custom_command()?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1817]
This code https://github.com/datalad/datalad/blob/master/datalad/support/gitrepo.py#L1366

essentially appends given files to a command, but it does not inject a '--' separator. Shouldn't that be done in order to avoid name clashing with arguments and options?

**Comment by yarikoptic** [comment]
Generally I see why not, but
- I remember seeing adding -- in the code manually, probably passed to this function
- so -- could be specific outside and this function shouldn't add any of there is -- before files

**Comment by bpoldrack** [comment]
I'm not sure what approach you are in favor of, @yarikoptic.

I guess, Michael is right.

**Comment by yarikoptic** [comment]
I didn't say that Michael is wrong. I think approach is sound too. I just made a note for what to look after while implementing it
