### ISSUE TITLE
we need --nosave to remove as well

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1822]
as discovered while playing with #1821-- for consistent (with `add`) API / expected behaviour

**Comment by mih** [comment]
What we really need is #1424 -- all these save/nosave switches are just a symptom of its absence. nosave breaks the typical behavior of commands and creates a situation that then needs manual fixing. All use-cases for nosave that I am aware of are either for internal use only, or for debugging. For the latter #1424 would also be the better approach, as after debugging you are still left with a mess with nosave.

**Comment by yarikoptic** [comment]
I do not quite see direct relationship with #1424.  Usecases for nosave
- incrementally add with multiple commands multiple files and finally save with a single commit message (the same as we do in typical git workflow)
- the same for remove/install/etc while trying to aggregate multiple actions into a single annotated commit
