### ISSUE TITLE
Problems with AFP server on Ubuntu

### ISSUE THREAD

**Issue by billbrod** [datalad/datalad#1825]
I'm not sure I can make this specific enough to get help, but I've been having issues using datalad on an AFP server. My OS is Ubuntu 16.04 LTS, and I've mounted the AFP server both with [afpfs-ng](https://github.com/simonvetter/afpfs-ng) and [gvfs-mount](http://manpages.ubuntu.com/manpages/trusty/man1/gvfs-mount.1.html). In both cases I can mount the server and navigate to it, both in Nautilus (my file explorer) and on the command line. I'm able to create two datasets on my machine's hard drive and everything seems to work fine, so I don't think it's my datalad install, but when dealing with the server, I have trouble with the most basic tasks.

When creating a dataset while the AFP server was mounted using gvfs-mount, the dataset would be created without any problems, but attempting to do any git or datalad commands within that directory cause a `fatal: This operation must be run in a work tree` to be printed and nothing happens. After poking around online, I thought this might have to do with the total path length (like the Windows issue #82), since gvfs-mount uses a very long mount point name by default. 

However, using afpfs-ng allowed me to get a much shorter name for the mount point, but I still occasionally have this issue. Just now, I was just attempting to re-create a dataset to reproduce other issues I ran into, but now I can't get anywhere because I immediately run into the above issue (with a path name length of 62 characters). I'm now running a VPN in order to mount the drive, but that's the only thing that's changed from this afternoon, when I was able to create the dataset.

When I create a new dataset on my machine's hard drive using the server dataset as a source (using `dataset install --source /mnt/path/to/dataset test`), it creates it correctly (and copies the data, if any), but when I navigate into the directory and type git status, it tells me `Your branch is based on 'origin/master', but the upstream is gone. (use "git branch --unset-upstream" to fixup)`, which googling tells me means that the branch is gone. When I try to then update from one dataset to the other, they're unable to do so, often without an error message (I can't find the error message that would be occasionally returned, since I'm unable to create the dataset on the server without any problems).

I had other issues as well, but I think they're all related and I currently can't reproduce them because of this `fatal: This operation must be run in a work tree` issue, which I think means that git thinks I'm not in a git directory (despite both `.git` and `.datalad` being present and containing files). Any ideas what might be going on?

**Comment by yarikoptic** [comment]
thanks for the report... never had "pleasure" yet to work with AFP.
The main culprit, `fatal: This operation must be run in a work tree`, means that git-annex detected underlying file system as being "crippled" (most of the time just that it does not support symlinks) and switched mode of operation to ["direct mode"](https://git-annex.branchable.com/direct_mode/).  Unfortunately full support of such mode of operation is 'tricky' to say the least and we are not fully yet compatible with it.  We are expecting to support fully soon ["v6 mode"](https://git-annex.branchable.com/tips/unlocked_files/) of git-annex operation .  But that one we also do not fully support yet :-/  but YMMV and other @datalad/developers could chime in with more specific information

**Comment by billbrod** [comment]
Thanks for your response! I am able to create symlinks on the server (at least as far as I can tell, there are no immediately noticeable errors), so is it possible that something else is going on?

**Comment by billbrod** [comment]
Quick update on that: when I create a directory and run `git init` and then `git annex init`, I receive the following messages:

```
init  
  Detected a filesystem without fifo support.

  Disabling ssh connection caching.

  Detected a crippled filesystem.

  Disabling core.symlinks.

  Enabling direct mode.
ok
(recording state in git...)
```

But, like I said, I can create symlinks myself without an issue.

**Comment by yarikoptic** [comment]
> I am able to create symlinks on the server
what about on the client, where you mount from the server? (I thought that it is there were datalad fails for you, not on the server)

**Comment by billbrod** [comment]
Sorry, my knowledge of the terminology isn't great. When I mount the server on my laptop and navigate to it on the terminal, I'm able to create symlinks without any problems but (from the same terminal session, same location), `git annex init` prints the above messages.

**Comment by bpoldrack** [comment]
Just to clarify what is happening on which machine: The output of `git annex init` you posted above, was received while creating a repository on the server, right @billbrod ?

If so, then we probably can't do much about it until support for annex V6 repositories (or direct mode) gets better (working on it). While you might be able to create symlinks (or at least something similar), git-annex apparently can't. That's something we cannot fix, since we build on top of it.

Depending on the functionality of datalad you actually need, you might want to give it a try using V6.
If you set the env variable `DATALAD_REPO_VERSION=6` datalad will create datasets using `git annex init --version=6` underneath.

**Comment by yarikoptic** [comment]
@billbrod if symlinks are supported, should be something else... would you be so kind to troubleshoot it a bit more? (eventually we might setup AFP here but can't atm) e.g. run annex init with --debug, smth like

``` mkdir -p t; cd t; git init; git annex init --debug ```

and paste output -- may be it would give more clues on why annex considers it crippled

also -- which version of git-annex?

**Comment by billbrod** [comment]
Thanks for all your help!

Here's the output of `mkdir -p t; cd t; git init; git annex init --debug`

I'll also check whether setting `DATALAD_REPO_VERSION=6` helps in some way.

```
Initialized empty Git repository in /mnt/WinawerAcadia/Projects/spatial_frequency_preferences/t/.git/
init  [2017-09-12 12:32:34.543824133] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--hash","refs/heads/git-annex"]
[2017-09-12 12:32:34.755345508] process done ExitFailure 1
[2017-09-12 12:32:34.755464204] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--verify","-q","origin/git-annex"]
[2017-09-12 12:32:34.86699819] process done ExitFailure 1
[2017-09-12 12:32:34.965127253] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","write-tree"]
[2017-09-12 12:32:35.588827918] process done ExitSuccess
[2017-09-12 12:32:35.58905694] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","commit-tree","4b825dc642cb6eb9a060e54bf8d69288fbee4904","--no-gpg-sign"]
[2017-09-12 12:32:36.199327911] process done ExitSuccess
[2017-09-12 12:32:36.199467869] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","update-ref","refs/heads/git-annex","f612b1599e125c173cb0e5efe24719721c0fb23c"]
[2017-09-12 12:32:37.476566111] process done ExitSuccess
[2017-09-12 12:32:37.660698968] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","config","annex.uuid","6c557bed-d6dc-43fd-b0e1-7bfd19f81053"]
[2017-09-12 12:32:38.126505627] process done ExitSuccess
[2017-09-12 12:32:38.126626269] read: git ["config","--null","--list"]
[2017-09-12 12:32:38.45265832] process done ExitSuccess

  Detected a filesystem without fifo support.

  Disabling ssh connection caching.
[2017-09-12 12:32:38.844779108] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","config","annex.sshcaching","false"]
[2017-09-12 12:32:39.290759538] process done ExitSuccess
[2017-09-12 12:32:39.290873354] read: git ["config","--null","--list"]
[2017-09-12 12:32:39.506322291] process done ExitSuccess

  Detected a crippled filesystem.
[2017-09-12 12:32:39.926188031] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","config","annex.crippledfilesystem","true"]
[2017-09-12 12:32:40.376084961] process done ExitSuccess
[2017-09-12 12:32:40.376234153] read: git ["config","--null","--list"]
[2017-09-12 12:32:40.636058792] process done ExitSuccess

  Disabling core.symlinks.
[2017-09-12 12:32:40.636194382] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","config","core.symlinks","false"]
[2017-09-12 12:32:41.767668124] process done ExitSuccess
[2017-09-12 12:32:41.767890604] read: git ["config","--null","--list"]
[2017-09-12 12:32:42.111262073] process done ExitSuccess
[2017-09-12 12:32:42.111400517] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","git-annex"]
[2017-09-12 12:32:42.586290257] process done ExitSuccess
[2017-09-12 12:32:42.58740727] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--hash","refs/heads/git-annex"]
[2017-09-12 12:32:42.979306735] process done ExitSuccess
[2017-09-12 12:32:43.047358778] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","log","refs/heads/git-annex..f612b1599e125c173cb0e5efe24719721c0fb23c","--pretty=%H","-n1"]
[2017-09-12 12:32:43.66086062] process done ExitSuccess
[2017-09-12 12:32:44.000484124] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch"]
[2017-09-12 12:32:44.001932865] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)"]
[2017-09-12 12:32:44.989781945] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","config","annex.version","5"]
[2017-09-12 12:32:45.306913387] process done ExitSuccess
[2017-09-12 12:32:45.307050612] read: git ["config","--null","--list"]
[2017-09-12 12:32:45.541966311] process done ExitSuccess
[2017-09-12 12:32:45.542081775] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","symbolic-ref","-q","HEAD"]
[2017-09-12 12:32:45.765041534] process done ExitSuccess
[2017-09-12 12:32:45.765148673] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","refs/heads/master"]
[2017-09-12 12:32:46.125626053] process done ExitFailure 1

  Enabling direct mode.
[2017-09-12 12:32:46.1258077] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","ls-files","--cached","-z","--","."]
[2017-09-12 12:32:46.383580259] process done ExitSuccess
[2017-09-12 12:32:46.383694391] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","symbolic-ref","-q","HEAD"]
[2017-09-12 12:32:46.627298662] process done ExitSuccess
[2017-09-12 12:32:46.627406401] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--hash","refs/heads/master"]
[2017-09-12 12:32:46.921917874] process done ExitFailure 1
[2017-09-12 12:32:46.922027859] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","checkout","-q","-B","annex/direct/master"]
[2017-09-12 12:32:47.487813018] process done ExitSuccess
[2017-09-12 12:32:47.487926796] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","config","core.bare","true"]
[2017-09-12 12:32:47.975297812] process done ExitSuccess
[2017-09-12 12:32:47.975413629] read: git ["config","--null","--list"]
[2017-09-12 12:32:48.207521336] process done ExitSuccess
[2017-09-12 12:32:48.207645421] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","config","annex.direct","true"]
[2017-09-12 12:32:48.557830883] process done ExitSuccess
[2017-09-12 12:32:48.557942382] read: git ["config","--null","--list"]
[2017-09-12 12:32:48.791819874] process done ExitSuccess
[2017-09-12 12:32:49.253466028] read: uname ["-n"]
[2017-09-12 12:32:49.254321451] process done ExitSuccess
ok
[2017-09-12 12:32:50.281490548] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","hash-object","-w","--stdin-paths","--no-filters"]
[2017-09-12 12:32:50.307292039] feed: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","update-index","-z","--index-info"]
[2017-09-12 12:32:51.237432907] process done ExitSuccess
[2017-09-12 12:32:51.237554884] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--hash","refs/heads/git-annex"]
[2017-09-12 12:32:51.59477049] process done ExitSuccess
(recording state in git...)
[2017-09-12 12:32:51.647909922] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","write-tree"]
[2017-09-12 12:32:52.352311811] process done ExitSuccess
[2017-09-12 12:32:52.352431284] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","commit-tree","cc5511747f51e84c664379873d3b95df8997934d","--no-gpg-sign","-p","refs/heads/git-annex"]
[2017-09-12 12:32:53.191216364] process done ExitSuccess
[2017-09-12 12:32:53.191337695] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","update-ref","refs/heads/git-annex","07cb22e0227836485d0bbcfc8444160bdf52a9c7"]
[2017-09-12 12:32:54.071772895] process done ExitSuccess
```

**Comment by billbrod** [comment]
And when I set `DATALAD_REPO_VERSION=6`, I can create a dataset without any problems, but when I attempt to add a file, I get issues.


```
$ touch test
$ datalad add test
                          Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'add', '--json', 'test'] under '/mnt/WinawerAcadia/Projects/spatial_frequency_preferences/t'. Exit code=1. out= err=sqlite worker thread crashed: SQLite3 returned ErrorError while attempting to perform prepare "SELECT null from content limit 1": no such table: content
git-annex: sqlite query crashed
CallStack (from HasCallStack):
  error, called at ./Database/Handle.hs:78:42 in main:Database.Handle
sqlite worker thread crashed: SQLite3 returned ErrorError while attempting to perform prepare "SELECT null from content limit 1": no such table: content
git-annex: sqlite query crashed
CallStack (from HasCallStack):
  error, called at ./Database/Handle.hs:78:42 in main:Database.Handle


```

**Comment by billbrod** [comment]
And `git annex version` returns the following

```
$ git annex version
git-annex version: 6.20170815+gitg22da64d0f-1~ndall+1
build flags: Assistant Webapp Pairing Testsuite S3(multipartupload)(storageclasses) WebDAV Inotify DBus DesktopNotify ConcurrentOutput TorrentParser MagicMime Feeds Quvi
dependency versions: aws-0.14.1 bloomfilter-2.0.1.0 cryptonite-0.20 DAV-1.3.1 feed-0.3.11.1 ghc-8.0.1 http-client-0.4.31.1 persistent-sqlite-2.6 torrent-10000.0.0 uuid-1.3.12 yesod-1.4.3
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav tahoe glacier ddar hook external
```

**Comment by yarikoptic** [comment]
ah, apparently there is not good enough of logging (@joeyh would be nice to have more diagnostics output) to state why crippled
but looking at the code
```haskell
probeCrippledFileSystem' :: FilePath -> Annex Bool
#ifdef mingw32_HOST_OS
probeCrippledFileSystem' _ = return True
#else
probeCrippledFileSystem' tmp = do
    let f = tmp </> "gaprobe"
    liftIO $ writeFile f ""
    uncrippled <- probe f
    void $ liftIO $ tryIO $ allowWrite f
    liftIO $ removeFile f
    return $ not uncrippled
  where
    probe f = catchBoolIO $ do
        let f2 = f ++ "2"
        liftIO $ nukeFile f2
        liftIO $ createSymbolicLink f f2
        liftIO $ nukeFile f2
        liftIO $ preventWrite f
        -- Should be unable to write to the file, unless
        -- running as root, but some crippled
        -- filesystems ignore write bit removals.
        ifM ((== 0) <$> liftIO getRealUserID)
            ( return True
            , do
                r <- liftIO $ catchBoolIO $
                    writeFile f "2" >> return True
                if r
                    then do
                        warning "Filesystem allows writing to files whose write bit is not set."
                        return False
                    else return True
```
it suggests that another culprit could be if file system allows to modify read-only files.  Could you try

```shell
$> echo 123 > testfile; chmod a-w testfile; echo more >> testfile
zsh: permission denied: testfile
```
would you get the same permission denied message?

**Comment by yarikoptic** [comment]
also @joeyh could you please have a pick at [above crash message](https://github.com/datalad/datalad/issues/1825#issuecomment-328912049) from v6 mode and sqlite?

**Comment by billbrod** [comment]
I do not get that permission denied message when I run 
```
$> echo 123 > testfile; chmod a-w testfile; echo more >> testfile
```
And then testfile contains 
```
123
more
```

**Comment by yarikoptic** [comment]
that is the problem :-/ -- in indirect mode (using symlinks to read-only files) git-annex relies on ability to "protect" data files from being modified... otherwise integrity could not be guaranteed and many things could go wrong.  So the only way for us would be to get v6 mode fixed up.  We had some [similarish (but different) looking issues](https://git-annex.branchable.com/bugs/drop_blows_on_lustre__58___SQLite3_returned_ErrorIO/) while trying it awhile back on lustre as well  . 

I see that there were some sqlite related issues/fixes in git-annex since the version you are using... I do not see them directly related (from commit msgs) so unlikely they would help, but if you could try most recent development snapshot, it could be of great help so we could file an issue with git-annex as seek @joeyh help.

**Comment by billbrod** [comment]
Okay, this definitely seems like it's an issue with this specific filesystem, not AFP or its interactions with Ubuntu; I've recreated the problem on my machine when the server's mounted using sshfs and on a Mac using both sshfs and AFP. I'm trying to figure that issue out, but I guess if datalad supported v6 mode, then that should work too.  

For the second part of your comment, the most recent development snapshot would be installing it from source, right? And then which part would you like me to re-run?

**Comment by yarikoptic** [comment]
yes -- it has to do with the local layer ( afpfs-ng and gvfs-mount). would be nice to demo it on a simple case and let upstream of those projects know

snapshot -- ... right... you are using neurodebian already and the most recent one... although current snapshot builds, it doesn't pass the tests (already reported to @joeyh) which forbids generation of the package ATM.  so may be hold on for a bit

the question is then
- do you have access to the AFP server directly? should probably just work there 
- or just use datalad locally on non AFP mounted partition

**Comment by billbrod** [comment]
I'm not sure what you mean by access to the AFP server directly. I can ssh into it, but still have able to write to files I shouldn't have write access to problem there. 

I probably will end up using datalad to manage the copies of the data that aren't on the AFP server, but being able to use datalad for all locations would be easier, so I am going to see if I can figure out what's going on with the filesystem.

**Comment by joeyh** [comment]
Does the sqlite crash only happen when running git-annex in the
filesystem that has been giving other problem, or can you reproduce it
on a filesystem such as ext4?

> sqlite worker thread crashed: SQLite3 returned ErrorError while
> attempting to perform prepare "SELECT null from content limit 1": no
> such table: content

The content table is part of the keys database, which should be located
at .git/annex/keys/db in the git repository. Running sqlite3 on that
file and then running the ".dump" command should list two tables,
including content. This error kind of looks like the database file
exists but the table somehow does not, which I can't see how could
happen unless something seriously confused sqlite.

-- 
see shy jo

**Comment by billbrod** [comment]
This is almost certainly unrelated, but there's no `datalad run` in my datalad install. Running `datalad run` with any command prints the following

```
usage: datalad [-h] [-l LEVEL] [--pbs-runner {condor}] [-C PATH] [--version]
               [--dbg] [--idbg] [-c KEY=VALUE]
               [--output-format {default,json,json_pp,tailored,'<template>']
               [--report-status {success,failure,ok,notneeded,impossible,error}]
               [--report-type {dataset,file}]
               [--on-failure {ignore,continue,stop}]
               [--run-before PLUGINSPEC [PLUGINSPEC ...]]
               [--run-after PLUGINSPEC [PLUGINSPEC ...]] [--cmd]
               {create,install,get,add,publish,uninstall,drop,remove,update,create-sibling,create-sibling-github,unlock,save,plugin,search,metadata,aggregate-metadata,test,crawl,crawl-init,ls,clean,add-archive-content,download-url,annotate-paths,clone,create-test-dataset,diff,siblings,sshrun,subdatasets}
               ...
datalad: error: invalid choice: 'run' (choose from 'create', 'install', 'get', 'add', 'publish', 'uninstall', 'drop', 'remove', 'update', 'create-sibling', 'create-sibling-github', 'unlock', 'save', 'plugin', 'search', 'metadata', 'aggregate-metadata', 'test', 'crawl', 'crawl-init', 'ls', 'clean', 'add-archive-content', 'download-url', 'annotate-paths', 'clone', 'create-test-dataset', 'diff', 'siblings', 'sshrun', 'subdatasets')
```

And my datalad version is 0.8.1, installed from neurodebian. I get the same thing if I installed datalad using pip.

**Comment by billbrod** [comment]
@joeyh I've only had the sqlite crash when running git-annex in the filesystem that has been giving the other problem, I can't reproduce it elsewhere.

**Comment by yarikoptic** [comment]
re `run` -- it was added just recently... we are plowing forward to release 0.9.0 asap, but still there is few more issues to fix.  will come out within few days.  With pip you could install directly from github: `pip install git+http://github.com/datalad/datalad` but I would advise to do that in a virtualenv so you could later just disable it and install recent one from neurodebian pkg

**Comment by joeyh** [comment]
William F. Broderick wrote:
> @joeyh I've only had the sqlite crash when running git-annex in the filesystem
> that has been giving the other problem, I can't reproduce it elsewhere.

Does the .git/annex/keys/db sqlite database exist after the crash?

-- 
see shy jo

**Comment by billbrod** [comment]
@yarikoptic Okay, I'll wait for 0.9.0 to be released then.

@joeyh I'm actually no longer having that sqlite crash issue, weirdly. I didn't change anything on my end, but the IT people at my department are looking into the server, so it's possible they've changed something. They should be finished by tomorrow, so I can double-check then to see if the issue is still happening.

**Comment by billbrod** [comment]
The permissions issue was fixed on the server, so that `$> echo 123 > testfile; chmod a-w testfile; echo more >> testfile` raises an error as expected, and now datalad works as expected, both with `DATALAD_REPO_VERSION=6` and without.

Thanks for your help!

**Comment by yarikoptic** [comment]
That is awesome @billbrod -- thanks for making it happen.  Do you know any detail on how it was fixed on the server side, and which client side ( afpfs-ng or gvfs-mount)  you ended up using which allowed to work in indirect (not v6) mode?

**Comment by billbrod** [comment]
I'll get more info as to what was done to the server. I'm actually currently using `sshfs`. 

But I may have spoke too soon: I'm able to create datalad datasets and add things that I have created myself (by echoing to a text file or using `touch test` or the like), but when I try to add the existing nifti and text files that came off of our scanner, I get the following (in both indirect and v6 modes)

```
add(error): /mnt/WinawerAcadia/Projects/spatial_frequency_preferences/wl_subj042/20170823_prisma_pilot/raw/15+cmrr_mbepi_s6_2mm_66sl_PA_TR1.0/wl_subj042_20170823+15+cmrr_mbepi_s6_2mm_66sl_PA_TR1.0-header.txt (file)

File(s) unknown to git
```

with logging level set to debug, I get the following

```
[DEBUG  ] Determined class of decorated function: <class 'datalad.distribution.add.Add'> 
[DEBUG  ] Determined class of decorated function: <class 'datalad.interface.annotate_paths.AnnotatePaths'> 
[DEBUG  ] Determined class of decorated function: <class 'datalad.interface.annotate_paths.AnnotatePaths'> 
[DEBUG  ] Adding content to repo <AnnexRepo path=/mnt/WinawerAcadia/Projects/Retinotopy/wl_subj042/20170713_PrismaPilot/RAW/15+T1_MPRAGE (<class 'datalad.support.annexrepo.AnnexRepo'>)>: {'/mnt/WinawerAcadia/Projects/Retinotopy/wl_subj042/20170713_PrismaPilot/RAW/15+T1_MPRAGE/PrismaPilot2+15+T1_MPRAGE-header.txt': {'orig_request': 'PrismaPilot2+15+T1_MPRAGE-header.txt', 'raw_input': True, 'parentds': '/mnt/WinawerAcadia/Projects/Retinotopy/wl_subj042/20170713_PrismaPilot/RAW/15+T1_MPRAGE', 'action': 'add', 'path': '/mnt/WinawerAcadia/Projects/Retinotopy/wl_subj042/20170713_PrismaPilot/RAW/15+T1_MPRAGE/PrismaPilot2+15+T1_MPRAGE-header.txt', 'type': 'file'}} 
[DEBUG  ] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'add', '--dry-run', '-N', '--ignore-missing', '--verbose', 'PrismaPilot2+15+T1_MPRAGE-header.txt'] 
Total:   0%|                                                             | 0.00/13.4K [00:00<?, ?B/s][DEBUG  ] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'add', '--debug', '--json', 'PrismaPilot2+15+T1_MPRAGE-header.txt'] 
[DEBUG  ] Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'add', '--debug', '--json', 'PrismaPilot2+15+T1_MPRAGE-header.txt'] under '/mnt/WinawerAcadia/Projects/Retinotopy/wl_subj042/20170713_PrismaPilot/RAW/15+T1_MPRAGE'. Exit code=1. out={"command":"add","success":false,"file":"PrismaPilot2+15+T1_MPRAGE-header.txt"}
|  err=[2017-09-14 11:58:28.732684967] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","ls-files","--others","--exclude-standard","-z","--","PrismaPilot2+15+T1_MPRAGE-header.txt"]
| [2017-09-14 11:58:28.764174569] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","check-attr","-z","--stdin","annex.backend","annex.numcopies","annex.largefiles","--"]
| [2017-09-14 11:58:28.764570289] read: git ["--version"]
| [2017-09-14 11:58:28.76612046] process done ExitSuccess
|   PrismaPilot2+15+T1_MPRAGE-header.txt: setFileMode: permission denied (Permission denied)
| [2017-09-14 11:58:28.79792409] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","ls-files","--modified","-z","--","PrismaPilot2+15+T1_MPRAGE-header.txt"]
| [2017-09-14 11:58:28.821290428] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","diff","--name-only","--diff-filter=T","-z","--","PrismaPilot2+15+T1_MPRAGE-header.txt"]
| git-annex: add: 1 failed
|  
                                                                                                     [DEBUG  ] received JSON result from annex: {u'command': u'add', u'file': u'PrismaPilot2+15+T1_MPRAGE-header.txt', u'success': False} 
add(error): /mnt/WinawerAcadia/Projects/Retinotopy/wl_subj042/20170713_PrismaPilot/RAW/15+T1_MPRAGE/PrismaPilot2+15+T1_MPRAGE-header.txt (file)
[DEBUG  ] Determined class of decorated function: <class 'datalad.interface.save.Save'> 
[DEBUG  ] Determined class of decorated function: <class 'datalad.interface.annotate_paths.AnnotatePaths'> 
[DEBUG  ] Determined class of decorated function: <class 'datalad.interface.annotate_paths.AnnotatePaths'> 
[DEBUG  ] Using existing Git repository at /mnt/WinawerAcadia/Projects/Retinotopy/wl_subj042/20170713_PrismaPilot/RAW/15+T1_MPRAGE 
[DEBUG  ] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'add', '--dry-run', '-N', '--ignore-missing', '--verbose', u'PrismaPilot2+15+T1_MPRAGE-header.txt'] 
Total:   0%|                                                             | 0.00/13.4K [00:00<?, ?B/s][DEBUG  ] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'add', '--debug', '--json', u'PrismaPilot2+15+T1_MPRAGE-header.txt'] 
[DEBUG  ] Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'add', '--debug', '--json', u'PrismaPilot2+15+T1_MPRAGE-header.txt'] under '/mnt/WinawerAcadia/Projects/Retinotopy/wl_subj042/20170713_PrismaPilot/RAW/15+T1_MPRAGE'. Exit code=1. out={"command":"add","success":false,"file":"PrismaPilot2+15+T1_MPRAGE-header.txt"}
|  err=[2017-09-14 11:58:29.068174681] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","ls-files","--others","--exclude-standard","-z","--","PrismaPilot2+15+T1_MPRAGE-header.txt"]
| [2017-09-14 11:58:29.09918062] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","check-attr","-z","--stdin","annex.backend","annex.numcopies","annex.largefiles","--"]
| [2017-09-14 11:58:29.099534008] read: git ["--version"]
| [2017-09-14 11:58:29.101758226] process done ExitSuccess
|   PrismaPilot2+15+T1_MPRAGE-header.txt: setFileMode: permission denied (Permission denied)
| [2017-09-14 11:58:29.13181893] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","ls-files","--modified","-z","--","PrismaPilot2+15+T1_MPRAGE-header.txt"]
| [2017-09-14 11:58:29.153946152] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","diff","--name-only","--diff-filter=T","-z","--","PrismaPilot2+15+T1_MPRAGE-header.txt"]
| git-annex: add: 1 failed
|  
                                                                                                     [DEBUG  ] Committing via direct call of git: ['git', 'commit', '-m', 'Adds header'] 
[DEBUG  ] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'commit', '-m', 'Adds header', u'PrismaPilot2+15+T1_MPRAGE-header.txt'] 
[DEBUG  ] Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'commit', '-m', 'Adds header', u'PrismaPilot2+15+T1_MPRAGE-header.txt'] under '/mnt/WinawerAcadia/Projects/Retinotopy/wl_subj042/20170713_PrismaPilot/RAW/15+T1_MPRAGE'. Exit code=1. out= err=error: pathspec 'PrismaPilot2+15+T1_MPRAGE-header.txt' did not match any file(s) known to git.
|  
File(s) unknown to git
```

**Comment by yarikoptic** [comment]
Hi @billbrod ,  I have generated snapshot packages of datalad and uploaded them to "debian-devel" of neurodebian.  So you could just get needed .deb's from http://neuro.debian.net/debian-devel/pool/main/d/datalad/  (version 0.8.1+git226-gb20e2a3c-1) or enable that devel repo as well by adding one more apt source file

```shell
$> cat /etc/apt/sources.list.d/neurodebian-devel.sources.list 
# NeuroDebian -devel repository
deb     http://neuro.debian.net/debian-devel stretch main contrib non-free
deb-src http://neuro.debian.net/debian-devel stretch main contrib non-free
```
Let us know if this one fails the same way.

note (from your last msg I got suspicion) that once you upgraded repository to v6 -- that is it, you would not be able to use it in regular indirect way.  Do you have now two copies -- one in indirect and one in v6?  whenever cut/pasting output, also include original command as you typed it in shell (like I did above) -- could help to identify confusion/culprit.

**Comment by billbrod** [comment]
Thanks @yarikoptic . Somehow the write permission issue has re-appeared, so the issues from earlier have re-surfaced. Hopefully we'll get that figured out soon and then I'll see if my other issue appears as well (I have updated my datalad to the version in the debian-devel repo).

Sorry about the confusing (I'll include the command from now on) -- those were all done in clean repos, after I had unset `DATALAD_REPO_VERSION`, so that I'm pretty sure it was working in the regular indirect way.

**Comment by yarikoptic** [comment]
Thank you @billbrod for not giving up. Please later share what was done on the AFP server side to mitigate it.
Cheers

**Comment by bpoldrack** [comment]
> Sorry about the confusion (I'll include the command from now on) -- those were all done in clean repos, after I had unset DATALAD_REPO_VERSION, so that I'm pretty sure it was working in the regular indirect way.

Reading this, I'm not sure whether you are aware @billbrod . Therefore please note: `DATALAD_REPO_VERSION` just defines the default to use when creating (or installing) a new dataset. The version used by an annex repository is a property of that repository. So, once created using v6, it remains a v6 repository even if you unset `DATALAD_REPO_VERSION`. You can inspect the repository version if you have a look at its `.git/config` file (section `[annex]` has an entry `version = ...`).

**Comment by yarikoptic** [comment]
@billbrod - is there anything we could/should do on datalad side or this issue could be closed?

**Comment by billbrod** [comment]
I think this can be closed, I'm don't think there's any thing to be done on the datalad side

**Comment by yarikoptic** [comment]
thank you @billbrod !
