### ISSUE TITLE
Strange testrepo setup

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1826]
In the test repo `basic_annex` (which others depend on), we have a file in git and a file in annex.
The annexed one is added via `addurl`, pointing to the file already in git! (`file:///tmp/wherever/..`)

This has weird effects in V6, leading to a lot of tests to fail. I don't fully understand what's going on in V6 yet, but apart from the need to reproduce this and probably consult Joey: Is there a specific reason to have that strange construct of the same content being in git and annex, @yarikoptic ?
Otherwise I'd just change that to be a file of different content.
And even if we need to have that for some reason, I'd not consider that setup "basic" and have a separate test repo for that.

**Comment by bpoldrack** [comment]
Just FTR and not to be solved here: The most apparent effect is, that after the annexed file is dropped during testrepo creation, a clone of that testrepo has the file's content present immediatly after `git annex init --version=6`. I failed to reproduce this using git and git-annex only for now, but what I could observe though is that the drop of the annexed file causes the content of the file in git to change to a relative path to `/annex/objects/SHA256E ....`.
`git status` therefore reports that file modified, but a `git checkout -- [that file in git]` would NOT restore its content.

**Comment by yarikoptic** [comment]
That is an interesting side effect IMHO, that if I got it right, annex smudge filter could augment other files under direct git control of content matches it may be regardless... Remember that in v6 it is only gitattributes mandating what goes where if no explicit option given to the call

**Comment by yarikoptic** [comment]
As for original idea for url - I guess just so that we guarantee to have it, it?

**Comment by bpoldrack** [comment]
Yes, generally I'm aware, but somehow annex V6 manages to shoot itself in this case. If the file just ended up in annex or sth like this, I'd not consider it strange. But here annex ends up just loosing the files' content and confusing itself about the URL. However, what exactly happens and what part might be a bug is another topic.

> As for original idea for url - I guess just so that we guarantee to have it, it?

Yeah, may have been the reason. But this wouldn't necessarily require the local target of that URL to be in the very same repository. Could be outside of it as well. So, if nothing else comes to mind I'll change that.

**Comment by bpoldrack** [comment]
There might have been another reason: The remote testrepo on github https://github.com/datalad/testrepo--basic--r1
The `test-annex.dat` points to `test.dat` (as in the local case mentioned above), therefore we can have that annex on github. Now, that the `BasicAnnexTestRepo` (as of PR #1845 ) changed and has its own content for `test-annex.dat` the one on github is invalid and can't easily be replaced with the new one.

Not testing with a remote repository at all is not an option, I think. So we need to come up with a solution. For now I'll simply disable the flavor `'network'` for it, but we need a replacement. To a certain extend, this about the entire setup of test repositories.
Can we have test repositories/datasets on datalad.org?

I'd currently vote in favor of an approach to testrepositories where we have a bunch of them remotely available. Furthermore I'd throw away all of the local efforts to build them. Instead they would need to be cloned. They local building was meant to allow for tests to run without a network connection. We can do this by having a non-temporary place to keep those clones, so you need to download them only once. This location should be protected in the sense, that no test can ever mess with those "original" clones. Tests would still run on temporary clones from the protected ones.
Question remains how (and when) to get them and where exactly they should reside.
  - automatically (try to) get them when tests are started
  - have dedicated command
  - ...?
What about possible updates or new additional ones?
Any suggestions or concerns, @yarikoptic , @mih ?

**Comment by mih** [comment]
I am closing this old issue. We are currently generating a file URL pointing to an external tmp location.
