### ISSUE TITLE
unify behavior of commands in terms of present changes

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1829]
ATM 
- `aggregate-metadata` saves changes before operating
- `crawl`, `run` etc refuse to proceed until things are clear

we should get through commands and unify their behavior one way or another... IMHO, we should do less magic and if command needs a clean state (`run` and `crawl`), then it is ok to fail!  so I think we should adopt that for aggregate-metadata (which might actually be smarter and not care about changes to irrelevant pieces... with knowing type of metadata it could see if any related file is dirty and then fail, or otherwise proceed)

**Comment by mih** [comment]
Most commands work fine with dirty datasets now. `run` refuses that for good reasons. I will close this generic issue now. If particular commands behave in suboptimal fashion, we need to have dedicated issues arguing what exactly needs changing, where.
