### ISSUE TITLE
Datalad remote sync

### ISSUE THREAD

**Issue by yassinebha** [datalad/datalad#1834]
Hi, is it possible to push a datalad project to a remote server (like github) then pull to new machine in order to continue working on that project from different machine?

**Comment by mih** [comment]
Yes, perfectly possible. Check out the demos on datalad.org/features for some of the supported publication scenarios.

I am closing this issue for now. Feel free to open a new one, should you run into trouble.

Note that most demos use features of the upcoming 0.9 release.
