### ISSUE TITLE
`remove(check=False)` implies that no data is dropped

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1837]
If was about to implement an option to be able to remove a file from Git in an annex repo -- without dropping its content (so it would still be present in another branch) -- but apparently `check=False` already does that.

It came as a surprise to me. Not sure yet whether the fix is just in adjusting the documentation, or whether we better have a dedicated mode option for this scenario.

**Comment by yarikoptic** [comment]
Duplicate of https://github.com/datalad/datalad/issues/1823

**Comment by mih** [comment]
Was already marked a duplicate 4 years ago
