### ISSUE TITLE
Open MEG archive

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1840]
https://www.mcgill.ca/bic/resources/omega

from webpage:

> This free-access continuously expanding repository also contains anatomical MRI volumes, demographic and questionnaire information, and eventually will feature other forms of electrophysiological data (e.g., EEG, field and cell recordings). OMEGA features the technological framework for multi-centric data aggregation, and is amongst the largest freely available resting-state MEG datasets presently available.
>
> Everyone can access and use the data for research and educational purposes. We only require that every outcome (papers, slides, posters, websites, etc.) cites the seminal open-access journal article introducing the project - thank you!
> - First open data repository fully dedicated to MEG
> - Contains data in raw and processed forms, including source image volumes: 184 participants, 255 resting-state MEG records: 150 from healthy controls, 34 from patient volunteers (ADHD, chronic pain, etc.)
> - Current focus in on resting-state, but task data can also be contributed

There is some sample data in BIDS format already.

The site is based on an OwnCloud instance. WebDav access is enabled, but the user-credentials provided after registration are insufficient for webdav-login (username missing). When this is fixed, this could become a first-class data portal for datalad.

**Comment by yarikoptic** [comment]
I have got in touch with the guys... they are moving it to another platform atm (CKAN), which would be more modular in terms of defining what is a dataset etc, so best to wait until that is done.  Supporting crawling of OwnCloud folders would be useful though regardless

**Comment by mih** [comment]
This issue was moved to datalad/datasets#3
