### ISSUE TITLE
Make ConfigManager deal with empty strings in config items

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1842]
First and foremost this is about using env variables to set datalad config items.
As seen in PR #1841, there is a need to a general solution on how to approach this.
At the very least an env variable set like `SOME_THING=` is to be treated as if it wasn't set at all, I think, which means the value we get from `ConfigManager` likely shouldn't be an empty string.
However, it also might not be a good solution to always return `None` in that case.
ATM I think this should be dealt with in the constraints, that are used to define the domain of the config item in `common_cfg` and then consequently use `ConfigManager.obtain()` instead of its `get()`, so that the conversion by those constraints actually takes place. That way, an item expected to be an integer can be considered to be `None` in case of an empty string, while for an item expected to be string, it might still be okay to simply stick with the empty string.

**Comment by mih** [comment]
So one thing is how envars are converted into config items, and another thing is how config items are converted into Python dtypes. We should keep these things mentally separate.

**Comment by bpoldrack** [comment]
I agree. Those are different layers. But they need to work together. If we allow config items to be empty, the conversions need to be able to deal with those items. And ATM they don't in general. And since config items can be set in different ways (not just env vars), we need to account for all of them.
However, I'm not yet sure what is the right approach.

**Comment by bpoldrack** [comment]
Of topic: What do you want me to believe, @yarikoptic ?

**Comment by bpoldrack** [comment]
Okay. As expected I'm running into this again ATM, since I'm enhancing possibilities to deal with known failures (ultimately in order to fix them, of course).

Right now, I'm in favor of fixing this by just skipping empty env variables when loading them into `ConfigManager`. This means, that in case an env variable corresponding to a datalad config item was set to an empty string it actually gets the default value assigned as defined in `common_cfg.py`. Any objections to that approach?

**Comment by yarikoptic** [comment]
I don't think I like that.  Being defined with an empty value is just that -- being defined with an empty value.  I do not think we should add magical sprinkles on top ;-)

**Comment by bpoldrack** [comment]
Well, but what is this supposed to mean? If we have a datalad config item defined in `common_cfg.py` as sth, that is supposed to be a boolean for example and that has a default value - what's the desired difference between defining the corresponding env variable as `DATALAD_WHATEVER=` and not defining it at all?
Is it reasonable to deal with it in the conversion to a bool? If so: Does empty equal `False`, while not defining it might evaluate to `True`, since this is the default? Does this make sense to you?

**Comment by bpoldrack** [comment]
Or do we just fail when it's empty, since this is an invalid value?

**Comment by yarikoptic** [comment]
if expects bool,  and it is not among 0, 1, True, False, we could fail imho

**Comment by bpoldrack** [comment]
Well, just failing might be okay. I feel it's somewhat counterintuitive to say "I can't deal with an empty entry for that configuration, but if you don't have an entry at all I'm fine", but I don't strongly oppose it.
Do you agree to just fail,  @mih ?
