### ISSUE TITLE
(the use of) ConfigManager needs attention

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1848]
This is somewhat related to #1842

For configuration we have `common_cfg.py` for definitions and `ConfigManager` actual access and interaction. The definitions may include default values, domain constraints and definitions on how to interactively ask for values.
The only method using `common_cfg` seems to be `ConfigManager.obtain()`. But throughout the code we often use `get()` or similar methods, which don't enforce the constraints (including the conversion to python dtypes) and don't respect the defaults.

The issue I'm running into ATM is, that if I use `obtain()` it interactively asks for everything that isn't explicitly defined, even if there is a default value in `common_cfg`. This is especially annoying for config items to be used for testing. Since their desired values are constantly changing it's not exactly convenient to have a stored configuration that needs to be changed for each test run or to always have to define all of them via an env variable.

So, the first thing we need is a way to just use the default values from `common_cfg` without interaction for everything that isn't explicitly specified, but nevertheless have the constraints and conversion applied, I think. But I'm not sure how to approach this ATM. It might be desirable only for certain configuration items (like `datalad.tests.whatever`) and therefore an additional switch for `obtain()` might do it. What are your thoughts on this, @mih and @yarikoptic ?

Apart from that, the second thing is to make use of the mechanic provided by `obtain()` more often and systematically, so we can benefit from it's ability to interact and to actually store into a user- or dataset-specific configuration. For a 1.0.0 release this should be well applied throughout the code base, I think.

**Comment by bpoldrack** [comment]
Please note, that in general I like `obtain`'s approach to ask even if there is a default, since it then is able to store that value after confirmation and not ask again next time.

Now, that i wrote that remark, it might also be a valid solution to not ask if there is a default and `store` is `False`. That's actually kind of what the docstring says, but there's either a bug or a misunderstanding or may be a confusion of the argument `default` and the defaults from `common_cfg`.

**Comment by bpoldrack** [comment]
Guys, excuse my confusion! Apparently sometimes I have to write things down to get it ;-)
Forget about the first point. It works, it's just that some of those config settings (namely `datalad.repo.version` and `datalad.repo.direct`) simply had no default, since by default it should be annex who decides. I'm fixing this.


However, I'll leave this open, since the second issue:

> Apart from that, the second thing is to make use of the mechanic provided by obtain() more often and systematically, so we can benefit from it's ability to interact and to actually store into a user- or dataset-specific configuration. For a 1.0.0 release this should be well applied throughout the code base, I think.

is still valid and needs some ironing.

**Comment by mih** [comment]
+1 on the switch from `get()` to `obtain()` (for type handling alone). However, I fear that this is another one of those issues that stay open forever, because there is no natural end. At least I will tag this as FOI -- so we could ignore it properly ;-) But 300+ open issues present an attention problem...

**Comment by mih** [comment]
Closing FOI issue with TODOs or progress indication.
