### ISSUE TITLE
Probably race condition in tests for test_create_test_dataset

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1852]
In direct mode build the tests in `test_create_test_dataset.py` marked as known failure sometimes pass and sometimes don't. Therefore probing might fail wrongly assuming it was fixed.

**Comment by bpoldrack** [comment]
Okay, it's not a race condition. It's random because it's meant to be random. Well - kind of. ;-)

The issue is the test dataset created by `create-test-dataset`. It randomly uses `GitRepo` or `AnnexRepo`. And in direct mode it only fails if `AnnexRepo` was choosen, of course.

Don't know yet how to solve the resulting issue with the `known_failure_direct_mode` decorator in #1845 (Probing fails if `GitRepo` was choosen so the expected failure doesn't happen)

**Comment by yarikoptic** [comment]
Fwiw
I think we had assumption that any annex repo should also be treatable as a regular git repo. That assumption night then be exercised in some tests. But it wouldn't be the case in case of the direct mode.

**Comment by bpoldrack** [comment]
Yes, and to a certain extend that's true. And where it isn't, it might be achievable to treat it similarly even if in direct mode. The issue here is the random character of that test dataset. This basically means we have tests, that are not operating on well defined, distinguishable environments.
Anyways, the only thing of actual concern ATM is, that we can not "probe" this failure as proposed in #1845 . We only can skip it in direct mode without an option to automatically notice that it works - if it works at some point.
So, that's what I'll do for now: Just skip it always in direct mode and have no other hint than a `# FIXME`.

**Comment by kyleam** [comment]
45a762620 was merged a long time ago, so this can be closed.  Well actually 66944933c (RF: replace all @skip_direct_mode with @known_failure_direct_mode, 2018-08-14) reverted the changes from 45a762620 as part of a bulk substitution, but given that direct mode is ripped out of master and that the @known_failure_direct_mode probe is an allowed failure, I don't think it's worth doing anything about.
