### ISSUE TITLE
Metadata inheritance (aggregation down the "hierarchy")?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1855]
How, and what level we would describe specific fields... 
Eg if we break down a bids dataset with subdatasets per each session/subject..  what meta data will be present within those subdatasets? Ideally an aggregator would be smart enough to propagate information from the parent dataset (defined at the level of the bids dataset) into a child subdataset (that it was subject x, age y etc).
Or we don't care but then subdatasets lack any metadata of their own

**Comment by mih** [comment]
From my POV this should be the task of a database that get's queried, and has little to do with aggregation.
