### ISSUE TITLE
How to unlock in V6?

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1860]
In PR #1845 I'm currently overhauling `datalad unlock` in order to have proper result reporting in direct and indirect mode. Looking into V6 raises a question though:

In V5 you can't unlock a file the content of which isn't present. Therefore it's now yielding an "impossible". This makes sense, since editing unknown content is obviously troublesome.
In V6 however you can unlock a file without having its content and overwrite it with new content. If you unlock such a file in V6, what you get is a "pointer file" (one line containing the link target). As mentioned, replacing it entirely works just fine. But: In opposition to an unlocked file in V5 the content you'd see if you open that file isn't the actual content of that file. In addition those pointer files seem to be interpreted by reading that first line no matter what comes next, leading to the effect that you lose your possible modification of that file if you appended something to the unlocked file. In that case committing will silently throw away those changes.

Now: What do we do if `unlock` is called on files without content in V6? We probably should indeed unlock, since that is what annex does. But should we file a warning or at least an info message? What about python API: Is there a reasonable way to indicate, that we can't rely on the assumption that the content of an unlocked file actually is its content? Or do we just need to make sure we simply don't assume this anywhere?

Any thoughts on that matter, @mih , @yarikoptic ?

Edit:
BTW in V6 we also need to throw away the assumption that committing re-locks the file!

**Comment by kyleam** [comment]
> In V5 you can't unlock a file the content of which isn't present. Therefore it's now yielding an "impossible". This makes sense, since editing unknown content is obviously troublesome. In V6 however you can unlock a file without having its content and overwrite it with new content.

In my view, the fact that you can unlock a file without content in V6 is an implementation detail. You're still editing unknown content. If editing unknown content in V5 is troublesome, I don't see why it wouldn't be so in V6.

> What do we do if unlock is called on files without content in V6? We probably should indeed unlock, since that is what annex does.

I think we should consider deviating from git-annex here. If a file's content isn't present, continue to report "impossible". This is consistent both from the UI perspective and conceptually.

**Comment by mih** [comment]
@kyleam 's conclusion is also the state of things in master. I am closing this issue, as there hasn't been a need to change that or discuss this topic for a year now.
