### ISSUE TITLE
licence spec of tarr/face_place dataset is not valid

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1863]
```
  "licenses": [{
    "url": "https://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US",
    "name": "Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License",
    "version": "3.0",
    "id": "cc-by-sa-nc-3.0"
  }]
```

according to the standard https://specs.frictionlessdata.io/data-package/#licenses `url` must be `path`, and it has no idead about `id` (less critical).

**Comment by yarikoptic** [comment]
got it, thanks.  I guess I will also remove version since it is not in the standard

did you adjust the parser to use 'path' not 'url' while at it?

**Comment by mih** [comment]
Parser was fixed this morning.

**Comment by mih** [comment]
This issue was moved to datalad/datasets#2
