### ISSUE TITLE
Performance issue of save() with many files

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1865]
Haven't investigated it, but `datalad add` on a directory with 40k files is very snappy until the `save` stage (single dataset), where an insane waiting period is interrupting the process. CPU is going full tilt, so the machine is clearly pondering some ideas.

I suspect that something in the "sorting" phase of `save` is implemented sub-optimally. We are still calling stuff twice in order to get stats for a progress bar (IIRC), and to be compatible with direct mode. 

Update: After 45min it finally crashed:

```
[ERROR  ] Failed to start ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'add', '--dry-run', '-N', '--ignore-missing', '--verbose', '--', <snip 40k files>
[Errno 7] Argument list too long [subprocess.py:_execute_child:1024]
[ERROR  ] add: [Errno 7] Argument list too long 
[ERROR  ] [Errno 7] Argument list too long [subprocess.py:_execute_child:1024] (OSError) 
datalad add study_20140724_095117357  2680,36s user 29,57s system 99% cpu 45:24,90 total
```

The add stage took less than a minute (I think), which is OK for 40k files with about 1GB total.

After the crash evrything was nicely staged, and a simple `git commit` was sufficient to finish the process in:

```
git commit -m save  4,21s user 1,24s system 69% cpu 7,836 total
```

datalad had already staged all files within that initial minute, so `save` spend 40+ minutes only to blow up eventually.

Conclusion: Our approach to pass a long list of files to git is fundamentally broken in such scenario. I know that we have to do this, because we want to be able to work with any flavor of dirty repositories, but clearly we need workarounds to still be able to work with lots of files. And most importantly we should be aware that we are paying a substantial price for this flexibility -- at least with the current implementation.

**Comment by yarikoptic** [comment]
I had similar issue with annex get , so now batch multiple calls to it in case of to many files

**Comment by mih** [comment]
That would only solve the cause of the crash, not the 40min of waste leading up to it :(

**Comment by yarikoptic** [comment]
Sure. The speeds - welcome to my world of using the beast with real data ;-)
I am wondering if we would end up eventually adding an option `--straight` or something like that, which would skip all the paths handling for across datasets detection etc, and would just proceed to the target git or annex call

**Comment by bpoldrack** [comment]
Would be nice to have a full log with timestamps enabled to see what's going on and what exactly the time  is spend on. I doubt it's the dry run of add. (BTW I think we don't call anything "to be compatible" with direct mode, but __in__ direct mode only)
Or enable a line profiling for `add`. Or may be we can even have a reproducible scenario? ;-)

**Comment by mih** [comment]
Somebody needs to write a test that generates a few thousand files and saves them. All slowness is long before any git call.

**Comment by mih** [comment]
Here is the test:

```sh
datalad create
for i in $(seq 10000); do echo $i > $i.txt; done
datalad add .
```

Everything, including the staging of the added files takes few seconds, and then the big sleep...

**Comment by bpoldrack** [comment]
Thanks. I think I got it and it's us! ;-)

**Comment by mih** [comment]
@bpoldrack was spot on: the culprit is the use of `swallow_logs` in `Dataset.repo`. With it removed the runtime for the above code is down from 5min to:

```
datalad add .  20,09s user 5,31s system 109% cpu 23,270 total
```

For comparison (on the same problem with 10k files)

```
bash -c "git annex add .; git commit -m save"  9,94s user 4,40s system 90% cpu 15,844 total
```

**Comment by mih** [comment]
also, for this particular `add` call there was not a single undesired log message after removing the `swallow_log` call.

**Comment by yarikoptic** [comment]
what!? swallow logs had such a detrimental effect???
how come -- was it raising loglevel or smth?  just interested to know
and yeah -- ideally code should not have any of those swallows now I guess.

**Comment by bpoldrack** [comment]
> how come -- was it raising loglevel or smth? just interested to know

Not sure, what you mean by this. The call of `swallow_logs()` has no paramters. It did not involve a new level.

And just FTR: confirming Michael's experience with the little test above.
Current implementation:
`datalad add .  255.72s user 7.60s system 100% cpu 4:21.94 total`
Removed `swallow_logs()`:
`datalad add .  25.92s user 6.16s system 108% cpu 29.506 total`

**Comment by yarikoptic** [comment]
Great
Re new level: 
`def swallow_logs(new_level=None, ...`

**Comment by bpoldrack** [comment]
Okay, so the answer is: No. There was no new log level, that caused this issue.

**Comment by mih** [comment]
Update: not sure how it was possible, but I merged master now, and removed `swallow_logs` from `Dataset.repo` manually, then ran `add` on the manyfiles dataset again:
```
action summary:
  add (ok: 36402)
  save (ok: 1)
datalad add .  239,26s user 32,19s system 118% cpu 3:49,39 total
```

This time includes all annexing and everything. Not fast, but not ultra-slow either. I am surprised how it not crash due to the nargs issue seen above. Maybe we have something clever in place. This time the dataset wasn't mixed-dirty, but only had things untracked that were actually added... Anyways, DATALAD!

**Comment by mih** [comment]
Just came back top this issue to see where we are in this respect with -revolution:

```
mih@meiner /tmp/alot % . ~/env/datalad3-dev/bin/activate
(datalad3-dev) mih@meiner /tmp/alot % datalad rev-create
[INFO   ] Creating a new annex repo at /tmp/alot 
create(ok): /tmp/alot (dataset)                                                                                              
(datalad3-dev) mih@meiner /tmp/alot (git)-[master] % for i in $(seq 10000); do echo $i > $i.txt; done
(datalad3-dev) mih@meiner /tmp/alot (git)-[master] % datalad rev-save
....
add(ok): 9999.txt (file)
save(ok): . (dataset)
action summary:
  add (ok: 10000)
  save (ok: 1)
datalad rev-save  23.04s user 8.76s system 129% cpu 24.613 total
```

for comparison with the same test scenario:

```
% time bash -c 'git annex add . > /dev/null; git commit -m "test" > /dev/null'
bash -c 'git annex add . > /dev/null; git commit -m "test" > /dev/null'  8.60s user 6.27s system 104% cpu 14.198 total
```

Ten sec more (without any parallelization), which is quite a bit faster than the original 3:49min. Importantly the save stage is now almost instantaneous, and pretty much all time is spent on add.

**Comment by yarikoptic** [comment]
cool
