### ISSUE TITLE
Implement output renderer that can look into result properties

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1871]
Our present adhoc template renderer cannot look into result fields, like `metadata`. With the new search powers it is becoming more interesting to use more flexible result extraction.

**Comment by mih** [comment]
If anything then this is a documentation issue. In order to report the `author` value in the `metadata` value of a result dict one could simply say `--output-format '{metadata[author]}`.

Learn your Python, Michael....

But it seems more complicated for fields that have a vocabulary prefix:

```sh
% datalad --output-format '{metadata[name]}' search score --max-nresults 1
[INFO   ] Query completed in 0.00144505500793 sec. Reporting max. 1 top match. 
Ghost Love Score
% datalad --output-format '{metadata[music:genre]}' search score
[INFO   ] Query completed in 0.00165200233459 sec. Reporting max. 20 top matches. 
[ERROR  ] Missing ']' in format string [base.py:<lambda>:405] (ValueError) 
```

**Comment by mih** [comment]
Jup. From https://docs.python.org/2/library/string.html#format-string-syntax

> Because arg_name is not quote-delimited, it is not possible to specify arbitrary dictionary keys (e.g., the strings '10' or ':-]') within a format string. 

Too bad...

Should we change the prefix separator?

**Comment by bpoldrack** [comment]
Well, it's just about that `arg_name` we use for `format`, not about the actual names of the fields, right?
So it should be doable from within `base.py`, I think.

**Comment by bpoldrack** [comment]
We just need to generate sth like `arg_1, arg_2, ...` and have a mapping to the actual strings if I get it right.

**Comment by bpoldrack** [comment]
Well, this will for now :-)
