### ISSUE TITLE
Have a clone of datasets.datalad.org on github?!

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1878]
#### What is the problem?

I think that being able to file bugs against the dataset collection _directly_ in cases like #1863 or all of https://github.com/datalad/datalad/labels/new-dataprovider-portal would help to expose these in a more appropriate forum and not disguise them by the clutter of the actual software bugs.

#### Is there anything else that would be useful to know in this context?

I get grumpy on Fridays...

**Comment by bpoldrack** [comment]
Sounds reasonable to me.

**Comment by yarikoptic** [comment]
+1
The full hierarchy flattened. We always wanted that and proposed in the proposal  ;-) 
but I am not sure if we ever finalized needed support for installation from such a flattened hierarchy.

**Comment by mih** [comment]
full hierarchy worked at some stage, maybe still does. However, full hierarchy is a secondary problem. Just the root would already be helpful.

**Comment by mih** [comment]
https://github.com/datalad/datasets
