### ISSUE TITLE
Maintainable crawler tests

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#1879]
#### What is the problem?
Those tests are hard to adapt to changes, since it's not clear (in a human-readable way) what the actual assumptions are.
We need to either better comment the assertions or to base them on more reliable things. For example:
An index of the list of commits is not exactly telling! If the determination of a commit that is part of an assertion was based on it's message, a human being would be able to understand what the assertion is about. :-)
#### What steps will reproduce the problem?
Particularly any change in the number, order or tree of the commits.
#### Is there anything else that would be useful to know in this context?
Yes. Have a look at the changes and particularly the comments in 29a3d87cac5c69331d77327505bd8ed78485978e
#### Have you had any success using DataLad before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)
DATALAD!

**Comment by mih** [comment]
Closing, no longer in the code base of this repo.
