### ISSUE TITLE
add doesn't error out if asked to add some bogus path

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1880]
#### What is the problem?
```shell
$> datalad create buga; datalad add -d buga buga/nonexisting
[INFO   ] Creating a new annex repo at /tmp/buga 
create(ok): /tmp/buga (dataset)                                                                                 
add(notneeded): /tmp/buga (dataset)
2 13993.....................................:Fri 06 Oct 2017 07:48:29 AM EDT:.
hopa:/tmp
$> echo $?
0
```

#### Is there anything else that would be useful to know in this context?

I just woke up

**Comment by bpoldrack** [comment]
Looks like `add` doesn't respect the guideline to report on `raw_input` and treats it as if it was a discovered one.

**Comment by bpoldrack** [comment]
Just looking into it.
Strange thing: Parameter `path` within `Add.__call__` contains `.datalad` instead of `buga/nonexisting`.
Does that ring a bell?

**Comment by bpoldrack** [comment]
Fixed.

```
$> datalad create buga; datalad add -d buga buga/nonexisting            
[INFO   ] Creating a new annex repo at /tmp/buga 
create(ok): /tmp/buga (dataset)                                                                     
[WARNING] path does not exist: /tmp/buga/buga/nonexisting [add(/tmp/buga/buga/nonexisting)] 
add(impossible): buga/nonexisting [path does not exist: /tmp/buga/buga/nonexisting]
$> echo $?
1
```

Yes, there's a logging issue, but that's another story ;-)

**Comment by bpoldrack** [comment]
Oh, and: You specified a wrong path anyway in case you didn't notice. Using `-d` a relative path will be interpreted as relative to that dataset!

**Comment by yarikoptic** [comment]
Right... In real use case paths were full paths
