### ISSUE TITLE
add could crash due to expanded list of files to be too long

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1883]
```shell
...
3mm/003418.dcm', '008-dwi_acq-DTI-256-p2-s4-3mm/013910.dcm', '007-dwi_acq-DTI-256-s2-3mm/009427.dcm']'': [Errno 7] Argument list too long [subprocess.py:_execute_child:1024]
[ERROR  ] add: [Errno 7] Argument list too long
[ERROR  ] [Errno 7] Argument list too long [subprocess.py:_execute_child:1024] (OSError)
```

**Comment by bpoldrack** [comment]
@mih: You have experienced sth similar recently. Was it about `add`, too, or `commit`?

**Comment by mih** [comment]
This is the same error as in #1865. It happened with `add`, but the problem would appear anywhere where we just pass a list of files.

**Comment by bpoldrack** [comment]
So I'd propose to:
 - make sure all calls to git/git-annex are taking place in the `*Repos` (should be done anyway)
 - make sure `normalize_paths` is used within those classes, wherever we pass a (list of) file(s) (should be done anyway)
 - enhance that `normalize_paths` decorator (and may be rename it), to split into several calls of the function it decorates whenever the list is "too" long (whatever that means on what kind of system) and then compose the results into a single one afterwards

Any objections?

**Comment by mih** [comment]
Sounds like an improvement. One point is missing

- write this done in a document that tell a future developer that this is how it is supposed to be

**Comment by yarikoptic** [comment]
Now: There is already some splitting elsewhere as well, remember doing it for get. 
Splitting in the decorator sounds like a great idea, which should probably cover many cases, but
- ideally shouldn't be done for the ones with batched execution
- might not cover the cases where list of parts is first expanded to eg figure out target size of download, and that expanded list is the one passed to call

**Comment by yarikoptic** [comment]
And right it is the #1865 which got more into the performance side discussion
Ideally, commands should just use batched version I guess, which would avoid any limits issue. But iirc some annex commands still don't have it

**Comment by mih** [comment]
My two cents: I don't think a generalized solution in some decorator will cur the mustard.

Depending on the specific use case the solution will have to be different. For `add` and `get` type scenarios  it will be fine to inspect `os.sysconf('SC_ARG_MAX')` to anticipate a long cmdline and split it into two or more calls. But cases like a massive partial commit (a commit with paths specified) will be harder to deal with. Here one would want to make two commits initially and then squash them, or make one commit and ammend that one with further commit calls. In either case the solution will be specific to commit. Furthermore, if a decorator would decided how often a function is called, it is better made sure that the inner function does nothing but running the cmdline, as any further setup would be duplicated between those calls.

The me it sounds like `git_custom_command` or some friend of it, need to get a parameter to split a call into a sequence of calls, if the caller states that it is safe to do so.

**Comment by yarikoptic** [comment]
FWIW, we already deal/split in `_run_annex_command_json` depending on our hardcoded `CMD_MAX_ARG` in datalad/utils.py (I guess I didn't know about `os.sysconf('SC_ARG_MAX')` which we should use there instead)
indeed for core git invocations solution is doomed to become smarter.

**Comment by mih** [comment]
Will look into this, but I had specifically `_run_annex_command_json` crash on my due to long cmdlines, so whatever it does is not yet the real thing.

**Comment by yarikoptic** [comment]
just to make sure -- with the current release or master?  The 0.10.3.1-35-g6a998ef0 (6a998ef0b79f6744c0b358c5c53717bed8957b2c) was the most recent fix there.  I would be interested in general to know why it still failed since it could instruct in shortcoming of this solution so "real thing" could avoid it.

**Comment by mih** [comment]
I run master, as of few min ago.

**Comment by yarikoptic** [comment]
ha ha -- wrong paranthesis!  Will submit a fix

**Comment by mih** [comment]
Debugging inside the crashing _run_annex_command_json`
````
len(files)
30000
# max arg is fine
(Pdb) CMD_MAX_ARG
2097152
(Pdb) os.sysconf('SC_ARG_MAX') 
2097152
# it kept just a single chunk?!
(Pdb) len(file_chunk)
30000
```

**Comment by yarikoptic** [comment]
if you are still in that session try
```python
                maxl = max(map(len, files))
                chunk_size = max(
                    1,  # should at least be 1. If blows then - not our fault
                    (CMD_MAX_ARG
                     - len(command)
                     - sum((len(x) + 3) for x in annex_options)
                     - 4   # for '--' below
                     - 50  # for safety since we are to add more options
                     ) // (maxl + 3)  # +3 for possible quotes and a space
                )
```
and see what you would get... PR is coming

**Comment by mih** [comment]
not sufficient, debugging

**Comment by yarikoptic** [comment]
```shell
In [1]: 1947850 + 15860
Out[1]: 1963710

In [2]: 2091579 - (1947850 + 15860)
Out[2]: 127869
```
so even with whitespaces we would have 127k spare
```shell
In [4]: (2091579 - (1947850 + 15860))/15860.
Out[4]: 8.062358133669608
```
which would be sufficient for about additional 8 per each cmdline argument.  anything special about those paths? (e.g. spaces in each one of them, which get escaped, or unicode symbols which get encoded???)

**Comment by yarikoptic** [comment]
unicode would be my closests/wildest guess -- what is the type of elements of cmd and what happens if you encode them all into utf8? ;)
FWIW when I was troubleshooting similar failure on a use case I pretty much did a bit of bisection on `subprocess.Popen` call trimming down cmd until it passes.

**Comment by yarikoptic** [comment]
related -- max filename length relates to this one
```
Size of command buffer we are actually using: 131072
```
which defines the maximal length it could tolerate also in cmdline somewhat
```
$> python -c "import os; from datalad.utils import CMD_MAX_ARG; print(os.system('ls ' + 'a'*(131072-1)))"
32512
```
so non-0 code is not the standard ls exit code (up to 3) and no output is produced -- `-4` makes it "work"
```
...
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa': File name too long
512
```
and with `shell=True` we get it at
```
python -c "from datalad.cmd import Runner; Runner()('ls ' + 'a'*(131072-4), shell=True)"
```

with shorter filenames that limit is escaped but there is another one on # of arguments:
```
$> python -c "from datalad.cmd import Runner;  from datalad.utils import CMD_MAX_ARG; out, err=Runner()(['ls'] + ['a']*((CMD_MAX_ARG-200)/2), shell=False); assert not err"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "datalad/cmd.py", line 187, in __call__
    return self.run(cmd, *args, **kwargs)
  File "datalad/cmd.py", line 487, in run
    stdin=stdin)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
```
which I didn't figure out relationship yet to any other above.

So, apparently there is indeed more to take into the picture here while deciding on how to chop the cmdline list of files.

**Comment by yarikoptic** [comment]
oh, I wonder if  that slight detail in the comment:
```shell
$> grep ARG_MAX $PWD/linux/limits.h
#define ARG_MAX       131072	/* # bytes of args + environ for exec() */
```
is what matters here, i.e that we need to account also for the environment variables!?

**Comment by yarikoptic** [comment]
meanwhile here is a completion of my binary search
```shell
$> python -c "from datalad.cmd import Runner;  from datalad.utils import CMD_MAX_ARG; fnl=100; out, err=Runner()(['ls'] + ['a'*fnl]*int(1918700./fnl)); assert not err"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 187, in __call__
    return self.run(cmd, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 487, in run
    stdin=stdin)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
(dev) 1 17380 ->1.....................................:Tue 06 Nov 2018 09:25:23 AM EST:.
hopa:/tmp
$> python -c "from datalad.cmd import Runner;  from datalad.utils import CMD_MAX_ARG; fnl=100; out, err=Runner()(['ls'] + ['a'*fnl]*int(1918699./fnl)); assert not err" 
```
so for our runner I can pass 1918699//100+1 = 19187 arguments on my system whenever each (but one `ls` of 2) length is 100... changing filename length to 50 causes it to pass ... so there is no hardcoded "# of args" limit, and it boils down to algebra ... but then indeed not a straightforward one since environment indeed matters:
```
hopa:/tmp
$> python -c "from datalad.cmd import Runner;  from datalad.utils import CMD_MAX_ARG; fnl=100; out, err=Runner()(['ls'] + ['a'*fnl]*(19186), env={'LONG': 'a'*10000}); assert not err" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 187, in __call__
    return self.run(cmd, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 487, in run
    stdin=stdin)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
(dev) 1 17403 ->1.....................................:Tue 06 Nov 2018 09:31:29 AM EST:.
hopa:/tmp
$> python -c "from datalad.cmd import Runner;  from datalad.utils import CMD_MAX_ARG; fnl=100; out, err=Runner()(['ls'] + ['a'*fnl]*(19186), env={'LONG': 'a'*1000}); assert not err" 
(dev) 1 17404.....................................:Tue 06 Nov 2018 09:31:37 AM EST:.
hopa:/tmp
$> python -c "from datalad.cmd import Runner;  from datalad.utils import CMD_MAX_ARG; fnl=100; out, err=Runner()(['ls'] + ['a'*fnl]*(19187)); assert not err"        
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 187, in __call__
    return self.run(cmd, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 487, in run
    stdin=stdin)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
```

**Comment by yarikoptic** [comment]
ok, I think it boils down to subtracting `sum(len(k) + len(v)+3 for k, v in os.environ.items())`, 3 is for end of string in both key and value, and 1 for may be = or just for a safe measure... altogether let's add 4! ;)

**Comment by yarikoptic** [comment]
ok, I am switching to other things for now... if noone would take the challenge for a proper fix (move all the splitting of positional args into Runner itself with full account for env which it is the one who knows), I would prep PR may be this evening.

@mih what is btw your `python -c 'import os; print sum(len(k) + len(v)+3 for k, v in os.environ.items())'` .   Where you offsetting by `300000` as growing by x10? (i.e. may be there is even more to all this mess)

**Comment by yarikoptic** [comment]
and that gap is still something I didn't find account for
```shell
$> python -c "import os; from datalad.utils import CMD_MAX_ARG; print(CMD_MAX_ARG - ((2+19186*100) + sum(len(k) + len(v) +3 for k, v in os.environ.items())))" 
174801
```
so may be environ data structure is longer or per each argument and env var we need a higher multiplier.

**Comment by yarikoptic** [comment]
@joeyh do you know may be the gory details on how to estimate maximal number of arguments cmdline could consume?

**Comment by joeyh** [comment]
It varies by OS and by version of OS in some cases.

And bear in mind that ARG_MAX includes the size of environ.

I have not had any complaints about a conservative 10240 so far.

-- 
see shy jo

**Comment by yarikoptic** [comment]
thanks @joeyh .  yeah -- sounds like futile chase to figure it out exactly, so we might as well adopt some "not too scientific" limit/offset.
10240 arguments for a command call or an entire size of the cmdline string (all arguments space-concatenated)?  I only found
```
* `annex.queuesize`

  git-annex builds a queue of git commands, in order to combine similar
  commands for speed. By default the size of the queue is limited to
  10240 commands; this can be used to change the size. If you have plenty
  of memory and are working with very large numbers of files, increasing
  the queue size can speed it up.
```
which sounds a bit different but gives me an idea to increase it on the devel server  ;-)

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> thanks @joeyh . yeah -- sounds like futile chase to figure it out exactly, so
> we might as well adopt some "not too scientific" limit/offset.
> 10240 arguments for a command call or an entire size of the cmdline string (all
> arguments space-concatenated)? I only found

ARG_MAX is the total size of all arguments plus environ.

> * `annex.queuesize`
> 
>   git-annex builds a queue of git commands, in order to combine similar
>   commands for speed. By default the size of the queue is limited to
>   10240 commands; this can be used to change the size. If you have plenty
>   of memory and are working with very large numbers of files, increasing
>   the queue size can speed it up.
> 
> which sounds a bit different but gives me an idea to increase it on the devel
> server ;-)

That's not connected to command-line length limits, it can be
arbitrarily large, although for many git commands the queue does involve
arguments, and so large commands will be split up.

-- 
see shy jo
