### ISSUE TITLE
Dataset from tarball without crawling (or with "local crawling")

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1885]
#### What is the problem?
I have a tarball with files locally. Due to the specific timing of a processing pipeline I have access to this tarball locally, but it is not yet available from a final (remote) location yet -- but I can reliably predict its future ssh URL.

My goal is to produce a dataset with the content of the extracted tarball, but set it up in a way that datalad would be able to obtain and use the tarball in order to get the dataset content to some machine. The situation is pretty much identical to what the crawler does and yields, but I (probably) cannot use the crawler itself, because the tarball is not at its remote location yet -- moreover although there is access to the tarball locally at the time of processing, there might be insufficient authorization to access the remote location (think: automated processing in trusted environment vs. personal access to storage with sensitive data).

How would I go about this? Any pointers on what pieces are the best starting point? Any thoughts in RF direction of crawler code, if necessary at all?

**Comment by yarikoptic** [comment]
I don't think it had anything to do with the crawler. You just needed to use http://docs.datalad.org/en/latest/generated/man/datalad-add-archive-content.html
And have datalad-archives special remote enabled later on if you would like to fetch content from an archive (and if needed, fetch archive first).

**Comment by mih** [comment]
Great, I was hoping it would be that simple.

What is still unclear, is how exactly I inform datalad about the access to the private SSH server that hosts the tarballs.

**Comment by yarikoptic** [comment]
Have a regular git remote for it, which annex would be aware of, I guess. Or that ssh access isn't under git/annex? Then register URL for that file to point to ssh url, and probably would needed to enable datalad remote which should be able to handle it. I don't remember if I tested this use case

**Comment by mih** [comment]
Cool, thanks. I will give it a spin.
