### ISSUE TITLE
DLMSEP#2: --show-uvalues

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1897]
#### What is the problem?
`--show-keys` is great since it orients user among the keys to query.  For some collections it would also be reasonable to output unique values present for each of those keys (and since we have already `--max-nresults`) may be with an additional option to limit up to how many to report (`--max-nuvalues`), since for some it would be way too many ;)).  This way I could already perform some meta-data "analysis", e.g. were all studies (or scans!) acquired on the same version of the magnet software simply by looking through this summary of values

**Comment by mih** [comment]
Keep in mind that DataLad only sees the (unique) values on index generation. Afterwards they are scattered across the documents in the search index. So what you are aiming for needs a new kind of query, and/or more info stored in the index, and/or a separate dump of unique values (at index generation time).

From my POV this has little (if anything) to do with `search`, but it is as you say: 'some meta-data "analysis"'. The appropriate metadata representation for this is the aggregated metadata in the dataset, not the (possibly vastly inflated) representation that the search is running on.

There are a ton of possibilities what could be done with the metadata, ranging from summary stats, visualization, export to a different format. I think those should be their own thing and not seep into the core commands.

**Comment by mih** [comment]
No disagreement...closing.
