### ISSUE TITLE
DLMSEP#3: report that there is more results which aren't shown

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1898]
#### What is the problem?
ATM, naive (or even experienced) user might assume that whatever he sees is all matching records.  But by default it is not so -- only up to 10(?) reported, and there is no notification that there might be more!  The easiest way would be, if # of results == max-nresults, add a message "There might be more results, please set --max-nresults to higher value or 0 to see all" or something like that.  It would immediately
- trigger attention to presence of such a flag
- break any script which just pipes output somewhere for processing, so they will make sure to specify --max-nresult

**Comment by mih** [comment]
The presence of this switch has a single reason: In a big index, it can take a very long time to tell how many matches there are. Whoosh provides ways to estimate this without having to do an exhaustive search, but in my experience those number can be confusing (if you check previous implementations, you can see how this could work).

I do not mind to switch to a 'as slow and as exact as possible' behavior by default, but one major concern leading up to this implementation was the slowness of search when there is a lot of data. If we consider this secondary to the problem outlined above than let's switch and use this issue to remind us to not complain about it in the future ;-)

**Comment by mih** [comment]
So? Slow&exhaustive by default OR fast&incomplete? I personally do not mind either way (I know that I can change the behavior easily).

FTR: Whenever there is any match, DataLad reminds about the result number limit every single time:

```
% datalad search anything
[INFO   ] Query completed in 0.0247230529785 sec. Reporting max. 20 top matches. 
```

**Comment by yarikoptic** [comment]
See #1933
