### ISSUE TITLE
install (and update for that purpose) should be able to install from non-origin

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1905]
#### What is the problem?

`install` considers only the origin (and current dataset) to deduce full URL for a sub-dataset, although origin might be not the one having that submodule

#### What steps will reproduce the problem?
```python
#!/usr/bin/python

import datalad.api as dl
from datalad.utils import chpwd, getpwd, rmtree
from os import mkdir
from os.path import exists

topdir = 'test-update'
origin_ = 'origin'
clone1_ = 'clone1'
clone2_ = 'clone2'

if exists(topdir):
   rmtree(topdir)
mkdir(topdir)
chpwd(topdir)

origin = dl.create(origin_, no_annex=True)
clone1 = dl.install(source=origin_, path=clone1_)
print("Initial clone")
clone1.create_sibling('ssh://localhost%s/%s' % (getpwd(), clone2_), name=clone2_)

print("Creating clone2")
clone1.publish(to=clone2_)
clone2 = dl.Dataset(clone2_)
print("Initiating subdataset")
clone2.create('subds1')

print("Updating")
clone1.update(merge=True, sibling=clone2_)
print("Installing within updated dataset -- should be able to install from clone2")
clone1.install('subds1')
```
would result at the end at
```

datala[INFO   ] Cloning /home/yoh/trash/test-update/origin/subds1 to '/home/yoh/trash/test-update/clone1/subds1' 
[ERROR  ] Failed to clone data from any candidate source URL: ['/home/yoh/trash/test-update/origin/subds1'] [install(/home/yoh/trash/test-update/clone1/subds1)] 
[ERROR  ] Installation of subdatasets /home/yoh/trash/test-update/clone1/subds1 failed with exception: InstallFailedError: 
Failed to install dataset from: ['/home/yoh/trash/test-update/origin/subds1'] [get.py:_install_subds_from_flexible_source:150] [install(/home/yoh/trash/test-update/clone1/subds1)]
.... 
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'status': 'error', 'message': ('Installation of subdatasets %s failed with exception: %s', '/home/yoh/trash/test-update/clone1/subds1', "InstallFailedError: \nFailed to install dataset from: ['/home/yoh/trash/test-update/origin/subds1'] [get.py:_install_subds_from_flexible_source:150]"), 'action': 'install', 'path': '/home/yoh/trash/test-update/clone1/subds1', 'type': 'dataset', 'refds': '/home/yoh/trash/test-update/clone1'}]
```
so it didn't even try to get it from clone2 (did try for origin and itself clone1 though ;))

# Resolution?

if to be done in a smart way, we could check for the most recent commit which dealt with the subdataset path, check which remote(s) have that commit, sweep through those remotes as possible candidates for the installation of that submodule

**Comment by yarikoptic** [comment]
primarily happens due to
```python
def _get_flexible_source_candidates_for_submodule(ds, sm_path, sm_url=None):
     ...
     remote_name, remote_url = _get_tracking_source(ds)
```
so only the tracking remote is considered.
I think we should, for consistency, allow to specify sibling for `install`.  The only gotcha is that we have `-s` for `--source` in `install`, so we either need to break "API" or provide just a long option `--sibling` and/or make `-s` handling automagic (e.g. if name matches a sibling name -- think it is a sibling not a source url)

**Comment by bpoldrack** [comment]
In that case automagic should be doable, I think. A sibling's name doesn't fit a URL-scheme, so the only thing to watch out for in terms of ambiguity is a matching relative local path. If we are to allow for sibling names in `-s`, we should fail in that case with a message suggesting to use explicit `--source` or `--sibling` instead.
