### ISSUE TITLE
AutomagicIO: make it great? (should behavior of `os.path.exists` also change?)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1924]
In our code (and in general), many file-open attempts are conditioned with something like `if os.path.exists`. For AutomagicIO to have any effect in such cases, one would need to patch any code to use `lexists` to be compatible with V5 annex repos. This seems unreasonable, hence I wonder if AutomagicIO should also make an attempt to acquire file content when `exists` is called on a file?

If that question get's a YES, we need to also consider `os.stat` at minimum.

Continuing along these lines:

- os.remove -> `datalad uninstall` for subdatasets,  `datalad remove` for files.
- closing a file descriptor that is open for write -> `datalad add`
- open an annex'ed file -> `datalad unlock` (originally suggested by @yarikoptic #1739, or maybe even @mih #1117)

If we do that, people would need to know next to nothing to get automatic data management in all their Python code.

What do you think?

**Comment by bpoldrack** [comment]
Sounds like a nice-to-have to me, but I think this would need some kind of configurable behavior of `AutomagicIO`, determining what to patch and what to possibly exclude. I doubt every code people might want to use with datalad is easy with auto-getting things whenever `exists` is called for example.

**Comment by bpoldrack** [comment]
A little more on the point of `exists`:
As of now, code using `exists` could be executed in a way that it's doing stuff only, if the file is present in a V5 repo without adapting that code. Could be nice in some cases. With the enhancement you propose, that kind of code would need to be rewritten to use our `file_has_content`.

I guess there are cases where it'S nice to have that enhancement and cases where it actually increases the effort. So, providing a config or parameters to adjust the behavior would allow for more code to seamlessly being used with datalad.

**Comment by yarikoptic** [comment]
Side note: the last problem with AutomagicIO somewhat undermined my trust into the approach of it is used within the code eg as a context manager (not as python -m datalad for the entire process) - we might be too late to monkey patch of those functions already imported and bound locally (eg from io import open). 
The only generic python level solution there would be to somehow change the actual code behind those functions but I am not sure if it is possible. More reliable way could be to overload those few syscalls which lie beneath all of them, but I don't know how feasible that would be to do at runtime, and smells like a generic fuse system for annex.

**Comment by adelavega** [comment]
Any updates on this front? I too rely on code that often tries `exists` prior to `open`, so in some cases AutoMagic is not an option for me.

**Comment by yarikoptic** [comment]
Would it be too much to ask to try 0.9.x branch version? We should release that one very soon, and knowing that it covers your usecase would be great. exist check should work https://github.com/datalad/datalad/blob/0.9.x/datalad/auto.py

**Comment by adelavega** [comment]
I'll give that a shot, thanks!

**Comment by adelavega** [comment]
I tried 0.9.x branch, and using `isfile` was useful for getting file, and `exists` also worked. However, a related issue I'm having is that it seems not all packages deal well with symlinks. For example, the mime library (which `pliers` uses when opening files), return type 'inode/symlink' rather than the type of the file under version control. 

Thus, I would normally `get` and `unlock` each file manually prior to calling pliers. Any tips here for avoiding that? It's not the end of the world but ideally I'd like my code to be datalad agnostic. Thanks!

**Comment by yarikoptic** [comment]
thanks for the report @adelavega again.  Workaround is obvious -- dereference the link
```ipython
In [11]: import magic  # requires libmagic, so import here
    ...: print magic.from_file(os.path.realpath('sub-01_inplaneT2.nii.gz'), mime=True)
application/gzip
```
but it should imho be done as an option to the `from_file` call similarly to `file` command in cmdline having `--dereference` (ref: https://github.com/ahupp/python-magic/issues/159), although it is quite cheap/easy to call realpath yourself.  One way (annex) or another (just a regular symlink) imho pliers should not care about discovering the symlinks but should care about content.

**Comment by adelavega** [comment]
Yes I agree. I think I'll patch that function in pliers then! Thanks.

**Comment by adelavega** [comment]
Actually this does not work. If the file is not downloaded yet, pointing to realpath will not trigger `get`, and thus will return a `FileNotFound` error. In contrast, giving the original symlink path *will* trigger `get` but since magic looks at the symlink, it returns mimetype symlink. 

For now, I will explore changing pliers to use `isfile` instead of `exists` as a workaround. Thanks!

**Comment by yarikoptic** [comment]
yes, those are 2 'orthogonal' issues
- `isfile` to trigger download
- `realpath` to magic.mime content instead of symlink

**Comment by mih** [comment]
I think we have moved away from automagicio as a whole -- at least for now.
