### ISSUE TITLE
Not ready for parallel processing

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1927]
#### What is the problem?

Recent switch to parallel indexing of metadata triggered a condition that leads to parallel access to repo instances. I do not yet know what the pattern is exactly, but it is clear that I do not have a concept on how to tell datalad to not screw up in this situation.

#### What steps will reproduce the problem?

```
% datalad search female --reindex
[INFO   ] Rebuilding search index 
[INFO   ] Scanning for metadata keys 
[INFO   ] Added 2 documents on dataset . 
[INFO   ] Added 134 documents on dataset ds000001 
Exception IOError: IOError("Lock at '/tmp/openfmri/.git/index.lock' could not be obtained",) in <bound method AnnexRepo.__del__ of <AnnexRepo path=/tmp/openfmri (<class 'datalad.support.annexrepo.AnnexRepo'>)>> ignored
Exception IOError: IOError("Lock at '/tmp/openfmri/.git/index.lock' could not be obtained",) in <bound method AnnexRepo.__del__ of <AnnexRepo path=/tmp/openfmri (<class 'datalad.support.annexrepo.AnnexRepo'>)>> ignored
[INFO   ] Added 280 documents on dataset ds000002 
[INFO   ] Added 389 documents on dataset ds000006 
Exception IOError: IOError("Lock at '/tmp/openfmri/.git/index.lock' could not be obtained",) in <bound method AnnexRepo.__del__ of <AnnexRepo path=/tmp/openfmri (<class 'datalad.support.annexrepo.AnnexRepo'>)>> ignored
...
```

**Comment by bpoldrack** [comment]
Minor Update: The actual error comes from within `gitdb`, so it's GitPython complaining. Need to figure out, why exactly GitPython is even involved. To get that working, it might be sufficient to avoid a possibly unnecessary instantiation of `git.Repo` even though this wouldn't solve the parallel processing issues in general.

**Comment by mih** [comment]
I will close this. We have no GitPython anymore, but still issues with parallelization #450 #2665. No need to keep this open.
