### ISSUE TITLE
pyliblzma is failing to import lzma on debian stable (and may be elsewhere)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1934]
on nd90 buildbot (http://smaug:8020/builders/datalad-pr-docker-dl-nd90/builds/3338/steps/nosetests/logs/stdio)
```
  File "/home/buildbot/datalad-pr-docker-dl-nd90/build/datalad/metadata/search.py", line 40, in <module>
    from datalad.support.json_py import dump2fileobj as jsondump2file
  File "/home/buildbot/datalad-pr-docker-dl-nd90/build/datalad/support/json_py.py", line 14, in <module>
    import lzma
ImportError: /home/buildbot/datalad-pr-docker-dl-nd90/build/venv-ci/local/lib/python2.7/site-packages/lzma.so: undefined symbol: lzma_alone_encoder
```

from within that buildbot docker venv session:
```shell
$ /home/buildbot/datalad-pr-docker-dl-nd90/build/venv-ci/bin/python -c 'import lzma'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/buildbot/datalad-pr-docker-dl-nd90/build/venv-ci/local/lib/python2.7/site-packages/lzma.so: undefined symbol: lzma_alone_encoder
$ ldd /home/buildbot/datalad-pr-docker-dl-nd90/build/venv-ci/local/lib/python2.7/site-packages/lzma.so 
	linux-vdso.so.1 (0x00007ffde7ffb000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f02aee5f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f02aeac1000)
	/lib64/ld-linux-x86-64.so.2 (0x0000557264799000)
$ apt-cache policy liblzma-dev
liblzma-dev:
  Installed: 5.2.2-1.2+b1
  Candidate: 5.2.2-1.2+b1
  Version table:
 *** 5.2.2-1.2+b1 500
        500 http://httpredir.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
$ dpkg -l liblzma*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  liblzma-dev:am 5.2.2-1.2+b1 amd64        XZ-format compression library - d
un  liblzma-doc    <none>       <none>       (no description available)
ii  liblzma5:amd64 5.2.2-1.2+b1 amd64        XZ-format compression library
```

I thought it is the issue of outdated liblzma5, but that one seems to be the same as on a local system and it imports just fine there:

```shell
$> virtualenv --python=python2 venv-lzma          
Running virtualenv with interpreter /usr/bin/python2
New python executable in /tmp/venv-lzma/bin/python2
Also creating executable in /tmp/venv-lzma/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

$> venv-lzma/bin/pip install pyliblzma
Collecting pyliblzma
  Using cached pyliblzma-0.5.3.tar.bz2
Building wheels for collected packages: pyliblzma
  Running setup.py bdist_wheel for pyliblzma ... done
  Stored in directory: /home/yoh/.cache/pip/wheels/c0/1e/0b/ca8019b28cafea9e47394f33ab353744133efcc1410def31eb
Successfully built pyliblzma
Installing collected packages: pyliblzma
Successfully installed pyliblzma-0.5.3

$> venv-lzma/bin/python -c 'import lzma; print lzma'
<module 'lzma' from '/tmp/venv-lzma/local/lib/python2.7/site-packages/lzma.so'>
```

**Comment by yarikoptic** [comment]
That pyliblzma smells like some elderly (release we "use" from 2010!?) bindings for lzma.  yes, there are debian packages for it (I didn't install them on buildbots yet, thus we are lucky to catch this problem). BUT isn't https://pypi.python.org/pypi/backports.lzma or https://pypi.python.org/pypi/lzmaffi/0.3.0 what we want ?? (although if backports.lzma, then we need to import as backports.lzma... bleh)

**Comment by mih** [comment]
We don't care very much. Functionality is developed based on the lzma support that is baked into Python 3.3+. Both pyliblzma and backport.lzma should work fine. Locally I use the debian package python-lzma.

**Comment by yarikoptic** [comment]
I only care to the degree that I (user) should be able to install it (datalad) via pip, and have datalad working properly. Current master is installable (if needed -dev is available) but not working

**Comment by yarikoptic** [comment]
OK, `pyliblzma` installs incorrectly if pkg-config is missing .

Not sure what we should do about that.  May be we could/should catch ImportError, and if detecting that message in there -- throw a more meaningful description , e.g. "pyliblzma was installed incorrectly. Most likely reason is that pkg-config was missing when pip install was run, so the library was not built properly. Please remove current version of lzma module, install pkg-config, and if you installed pyliblzma via pip, do next install with --no-cache-dir option".

This will avoid us having some kind of FAQ somewhere and referring ppl to it.

Meanwhile, I will install pkg-config in buildbots, but also will just install the python-lzma pkg.

**Comment by mih** [comment]
I guess this is good now. Reopen if I am wrong.

**Comment by yarikoptic** [comment]
actually more interesting even the fact of needing to load search, lzma for a non-metadata related work... may be lzma import should be delayed until actually needed
