### ISSUE TITLE
export the entirety of git metadata

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1944]
I think it would be cool to have `--export-git` option (I might even like it to be default) where within the tarball we also provide `.git` directory with condensed (we would first clone into a temp dir, then `git gc --prune=now` for a good measure).

Pros:

- exact identification of the verion(s) etc
- we could later "datalad install" from such a tarball (pretty much download, extract, datalad add while possibly consulting the HEAD about which files are under git and which under annex, so we unambiguously place them back) (relates to #1943 on how we deal with excluded files)
- as a result those exports would be full featured datalad datasets and we could rely on those services for archival

**Comment by mih** [comment]
You didn't mention which command what get this option.

In any case, why would actually archive anything and then add `.git`? Why not `git clone`, `prune`, `tar the whole thing to get an actual repo, without having to rebuild one from the archive?

**Comment by yarikoptic** [comment]
I was talking about `export*` plugins (`export_archive` and `export_to_figshare`).  Cloning (with recless I guess, and making sure not to `get` any file which isn't in the original repo but available from elsewhere) and pruning, and `git remote remove origin`, and then exporting the entire tree sounds like a legit way as well BESIDES that we would need to make sure that files aren't symlinks (if we really want to not rebuild from archive):  'unlock' or upgrade to v6 in thin mode (to avoid copies?) or to allow copying .

**Comment by yarikoptic** [comment]
This is pretty much implemented within https://github.com/datalad/git-remote-rclone/blob/master/git-remote-rclone where only a few pieces are `rclone` specific but largely about export/import (rclone just transfers) of git metadata

**Comment by yarikoptic** [comment]
#4671 is a "newer" version of this desire from the code duplicator himself who wants to absorb it in a single location (here), so I will leave that one open instead
