### ISSUE TITLE
pybids no longer functional with PY2

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1951]
This is an issue for us, because datalad needs to run on old machines where it is unreasonable to require people to obtain Python3. We have the following options:

- maintain PY2 support in pybids (filed https://github.com/INCF/pybids/issues/86 to register the compatibility issue for now). @yarikoptic are you involved in the release process of pybids somehow? If not, then we would be running after pybids with each and every release. We could setup a test run that exercises the pybids test under PY2 within datalad to get notified.
- fork pybids: the scope of functionality we require from pybids is limited, we can fork and fix up the bits that we actually need from time to time,

**Comment by yarikoptic** [comment]
Not involved

**Comment by bpoldrack** [comment]
Where did you get the idea from, that not supporting PY2 is intentional by pybids folks, @mih? Should we take that for a fact already? If so, we probably should fork, I think. If not, we might want to push in the "right" direction. ;-)

**Comment by yarikoptic** [comment]
Please no forking, doesn't scale
You could find somewhere my comment, and there was a PR, from Tal dropping python 2

**Comment by bpoldrack** [comment]
Found the "discussion". Somewhat funny to "officially" drop support on stop testing on PY2, while the README for grabbids still explicitly speaks of "python 2 and 3".
Anyways, so you are in favor of us trying to keep up with pybids and provide PY2 fixes every time they introduce a change, that wouldn't work with PY2?

**Comment by mih** [comment]
pybids 4.1 is good with PY2 again.
