### ISSUE TITLE
Subdataset installation from guessed location within a nested hierarchy at a configured remotefrom an alternative location: misleading message, always origin

### ISSUE THREAD

**Issue by mvdoc** [datalad/datalad#1956]
Problem 1: Installing a subdataset available only from non-origin; datalad reports being installed anyway from origin:

```shell
(datalad) contematto@talete ~/Documents/experiments_work/budapest (master*) $ datalad install mriqc
[INFO   ] Cloning git@github.com:mvdoc/budapest.git/mriqc to '/Users/contematto/Documents/experiments_work/budapest/mriqc'
install(ok): /Users/contematto/Documents/experiments_work/budapest/mriqc (dataset) [Installed subdataset in order to get /Users/contematto/Documents/experiments_work/budapest/mriqc]
```
but instead, it's being installed from the sibling named `hydra_data`:

```shell
(datalad) contematto@talete ~/Documents/experiments_work/budapest (master*) $ datalad siblings
.: here(+) [git]
.: gh-mvdoc(-) [git@github.com:mvdoc/budapest.git (git)]
.: hydra_data(+) [hydra:/data/budapest (git)]
.: hydra(+) [hydra:/home/contematto/annex/experiments_work/budapest (git)]
```

```shell
(datalad) contematto@talete ~/Documents/experiments_work/budapest/mriqc (master) $ datalad siblings
.: here(+) [git]
.: origin(+) [hydra:/data/budapest/mriqc (git)]
```

Problem 2: the correct name of the sibling doesn't get propagated to subdatasets; the sibling gets named `origin` and not `hydra_data`.

Dictated and approved by @yarikoptic

**Comment by mih** [comment]
I will retitle this abandoned issue to make clear that this refers to a special kind of alternative location: A hypothesized nested subdataset at one of the configured remotes.

**Comment by mih** [comment]
In #3966, there is now a proper progress report detailing the clone attempts for various source URL candidates. I have filed a separate issue for the remote naming aspect, which is related to `get()` at #4005. Closing this issue.
