### ISSUE TITLE
support .gz "archives" for crawler/add-archive-content

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1967]
#### What is the problem?

it already works! but
- [ ] crawlers do not list .gz (or any other similar compression algorithms) as supported
- [ ] does not retain the original filename (uses the key of the file upon decompression)

we tried it on strings-dbg

e.g.
```shell
 datalad crawl-init --save --template=simple_with_archives url=https://string-db.org/cgi/download.pl 'a_href_match_=.*COG.links.v10.5.txt.gz$'   
```

**Comment by mih** [comment]
Should this issue move to the crawler extension? I think add-archive can handle compressed tarballs.

**Comment by bpoldrack** [comment]
IIRC add-archive still doesn't list correctly supported compressions and
wouldn't correctly deal with the file name extensions. So, it's really
about add-archive, not the crawler, I think.

2018-06-12 7:17 GMT+02:00 Michael Hanke <notifications@github.com>:

**Comment by yarikoptic** [comment]
the point of this one was a purely .gz'ed files, not .tar.gz'ed files .  E.g. if we have some "singularity.img.gz" and want to have its extracted version.  I do not remember where I left it on -- just remember that something was working and something not ;-)

**Comment by yarikoptic** [comment]
@bpoldrack do you remember which extensions it doesn't list correctly?
I've tried with .gz and seems to work just fine:
```bash
$> datalad add-archive-content --delete 1.dat.gz
[INFO   ] Adding content of the archive 1.dat.gz into annex <AnnexRepo path=/tmp/testds (<class 'datalad.support.annexrepo.AnnexRepo'>)> 
[INFO   ] Initiating special remote datalad-archives 
[INFO   ] Finished adding 1.dat.gz: Files processed: 1, renamed: 1, +annex: 1 

$> lst
total 4
lrwxrwxrwx 1 yoh yoh 189 Jul 10 11:35 1.dat -> ../.git/annex/objects/9F/X5/SHA256E-s0--e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.dat/SHA256E-s0--e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.dat

$> git annex whereis 1.dat
whereis 1.dat (2 copies) 
  	55cb2b71-2cbf-4689-98de-c125ddad2217 -- yoh@hopa:/tmp/testds [here]
   	c04eb54b-4b4e-5755-8436-866b043170fa -- [datalad-archives]

  datalad-archives: dl+archive:SHA256E-s26--80ddb8ce62210c7f73b1b58457c71e434a66d16f66d976caa442ac7ca5a9ae36.dat.gz#path=1.dat&size=0
```

**Comment by yarikoptic** [comment]
upon some additional tries seems to work, although not sure what exactly "fixed it". Crawler needs additional fixes/testing (https://github.com/datalad/datalad-crawler/issues/24) facilitated by #3049, but as for the core code base -- we are done
