### ISSUE TITLE
multiprocessing (for serve_path_via_http) gives hurdle under cygwin

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#197]
our windows VM has cygwin as well now -- thought to get it as a simple way to get to windows box to test remotely... probably not really a real "use case", but wouldn't hurt to make it work there, but may be it would be too much pain:
http://www.onerussian.com/tmp/gkrellShoot_09-02-15_124818.png ?

**Comment by bpoldrack** [comment]
Well, first of all I think it would be very nice to have.
It's certainly pain, but on the other hand: The need to get the tests
running and to figure what things may not work on windows/cygwin, is
independent on where we figure it out. We need to solve those things
anyway, don't we?

2015-09-02 18:50 GMT+02:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by mih** [comment]
I think cygwin is off the table with the current level of windows support (native and WSL 1/2). Closing.
