### ISSUE TITLE
metadata-aggregation fails to rewrite an unavailable object file

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1971]
#### What is the problem?

A dataset was clone. The actual data content was made available locally, but none of the aggregated metadata objects that were annex'ed due to their size are available locally. Re-aggregation in this situation computes the exact same information and wants to write it in the a file of the same name as before (all correct). But this happens:

```
[ERROR  ] [Errno 2] No such file or directory: '.../.datalad/metadata/objects/bd/cn-dc6cf454dd1fa41257afb374ef6666' [json_py.py:dump2xzstream:67] (IOError) 
```

Because the existing link does not point to an actual file.

In this case even `unlock()` is not the right thing to do, but we should rather `git rm` the file without a commit, before rewriting them, maybe.

**Comment by yarikoptic** [comment]
yeah, for any file which is to be overwritten (and where prev content doesn't matter), it should be just "rm"ed first, new one created and added

**Comment by mih** [comment]
This needs to be tested explicitely in #2115
