### ISSUE TITLE
`publish` does not publish aggregated metadata

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1987]
This has not been confirmed yet, but could be an explanation for behavior reported by @cni-md

**Comment by mih** [comment]
Test is in, proper behavior confirmed.

**Comment by yarikoptic** [comment]
Shouldn't metadata publishing (or not) be configurable somehow, eg this git annex wanted?

**Comment by mih** [comment]
Maybe. What is the use case you are thinking of?

**Comment by yarikoptic** [comment]
Datasets with sensitive metadata where it is ok to publish empty annex repo and might even be ok to publish dataset level metadata but not per file?

**Comment by mih** [comment]
Given that we are using the same mechanism for data and metadata, we should use whatever tag to the annex metadata too. However, at the moment we only annex metadata objects larger than 20kb. So the setup will be rather cumbersome.

**Comment by mih** [comment]
Also, by default, the dataset metadata contain a flattened version of the file metadata. This would have to be turned off too. In most cases. Overall, this sounds like another use case for dataset config templates. ATM we have two unrelated PR that implement something like this. Maybe we should have one implementation that does all of that.
