### ISSUE TITLE
Metadata parsing

### ISSUE THREAD

**Issue by kskyten** [datalad/datalad#1994]
Thanks for making Datalad. It looks awesome.

I'm trying to use Datalad for automating document scanning. The plan is to have the documents contain metadata in the form of barcodes that then gets added for the processed files.
It seems like Datalad supports parsing metadata from image files, but I couldn't find out how to do this.
Here's what I tried (with version 0.9.1 of Datalad):
```
datalad create test
cd test
mv ../cat.jpg .
datalad add cat.jpg
``` 
I assumed this would have parsed the metadata from the image file, but running
```
git annex metadata cat.jpg
```
does not return anything.

How do I parse metadata and how would I add a new parser? Can I just use git annex directly to add the metadata? It seems like Datalad does not have an option for adding bulk metadata as json like git annex does.

**Comment by kskyten** [comment]
I'm also interested in indexing the content of the files (#1996). Would it work to just extract the text content of the file and add that to the metadata? What kind of schema should I use? I'm not very familiar with json-ld. In case of a custom schema, is it possible to store the schema in the repository as well? Where is the whoosh index stored?

**Comment by mih** [comment]
Yes, it is possible to just store the plain text content as metadata. Yes, you can make up any schema you like, and yes, you can store the description of that schema within the dataset itself (actually, that desciption becomes part of the metadata).

As an example you could check out this parser: https://github.com/datalad/datalad/blob/master/datalad/metadata/parsers/nifti1.py

You'll see that it defines its own vocabulary at the top, and that this vocabulary is included in the returned dataset-global metadata under the `@context` key. This is pretty much what the JSON-LD context is made for: a description of the keys used in the other parts of the JSON structure.

While this is all very flexible, I would strongly advice to do a little research if anyone already came up with a standard for doing something like this (e.g. storing OCR data in a PDF; maybe there is a demo somewhere how to achieve that with XMP (https://www.adobe.com/products/xmp.html), which datalad supports already. If that is the case, I would make sure to be *heavily* inspired by that (choice of key names, links to existing definitions for such keys, choice and format of values,...). In my experience, there is  much to learn from existing solutions to metadata problems...

**Comment by mih** [comment]
Re whoosh index location: At the moment, the whoosh index is auto-generated when needed by `search` and is stored under the local repositories `.git/` folder. There is some debate whether to attempt a more portable solution instead, but at the moment we have no clear use case that would justify this effort.

**Comment by kskyten** [comment]
How do I add the metadata without a parser in bulk? For the document scanning use case I have `.tiff` files with possibly multiple separate documents inside each file  I then separate the documents and gather the metadata for each document. While it is possible to make this a parser, it is pretty specific to my use case. Adding the metadata separately would also allow for incremental processing.

**Comment by mih** [comment]
I see several angles:

- Everything is pretty specific to someone's use case ;-) I still think that a parser is the most suitable approach.
- Incremental metadata aggregation is already on the TODO list, and will be done sooner or later (if you are interested in helping out with this we could discuss that separately)
- Dumping some (expensive to generate) metadata into a dedicated place is something that should be supported by DataLad. However, I would want to avoid inventing needless formats and standards.

My recommendation for your use case would be this:

- take a look at Adobe XMP as means to store your metadata
- XMP can be embedded in TIFF file directly (see https://en.wikipedia.org/wiki/Extensible_Metadata_Platform), so you could process each file separately and directly, without creating additional ones
- XMP can also be stored in sidecar files, in case you do not want to modify the original files
- we have a XMP parser prototype (https://github.com/datalad/datalad/blob/master/datalad/metadata/parsers/xmp.py) -- needs much work and would also need to get the ability to "see" sidecar files, but would be a good start
- this page has the specs on how to structure metadata in XMP: http://www.adobe.com/devnet/xmp.html -- importantly XMP pretty much take any vocabulary, so you can be as standard or free as you desire, without imposing any constraints on the DataLad parser (or vice versa).
- going with XMP is building on something that is universally known, e.g. any desktop search engine, or Google know how and where to look for XMP metadata

**Comment by kskyten** [comment]
Indeed, XMP is definitely the way to go. Supposedly git-annex also supports [extracting metadata with exiftool](http://git-annex.branchable.com/tips/automatically_adding_metadata/), but I couldn't get it to work.

**Comment by mih** [comment]
We have a parser for exif too.

**Comment by mih** [comment]
I am closing this issue for now, as the topic seems to have been exhausted. Please feel free to (re)open another issue, if the need arises.
