### ISSUE TITLE
datalad add-archive-content: better documentation

### ISSUE THREAD

**Issue by mvdoc** [datalad/datalad#1997]
#### What is the problem?

1. I have no clue on how to use `datalad add-archive-content`, and the error message/documentation could be more informative.
~~2. It fails to add the content of the archive under git annex.~~ (dumb me I had `.gitignore` set to ignore the files that were in the tar)

#### What steps will reproduce the problem?

I have a tarball, which is untracked. The tarball is the only file that is untracked. Naturally, I would do `datalad add-archive-content mytarball.tgz` (as the documentation suggests). I would expect this to do two things: 1. add `mytarball.tgz` to annex; 2. extract `mytarball.tgz` and add the content to annex. 

Instead, I get this error

```terminal
mvdoc@euclid ~/exp/hauntedhouse_mne/singularity (master*) $ datalad add-archive-content hauntedhouse.img.tgz
[ERROR  ] You better commit all the changes and untracked files first [add_archive_content.py:__call__:235] (RuntimeError)
```
Which doesn't really suggest that I should add the tarball to annex, but I tried to do it anyway:
`datalad add mytarball.tgz && datalad add-archive-content mytarball.tgz`, and that did the trick.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad plugin wtf`)?

```terminal
mvdoc@euclid ~/exp/hauntedhouse_mne/singularity (master) $ datalad --version
datalad 0.9.1
```

#### Have you had any success using DataLad before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)

I can't live in a world without datalad <3

**Comment by bpoldrack** [comment]
Well, the man page for `datalad add-archive content` actually reads:
```
Add content of an archive under git annex control.

This results in the files within archive (which should be under annex
control itself) added under annex referencing original archive via
custom special remotes mechanism
```

Apparently, it's still misleading, but I'm not sure what part of the documentation we should change in what way to make that clear. Do you have any suggestion where and how to mention it?

**Comment by mih** [comment]
I guess what it should say is that `files within archive (which MUST be under annex control itself)...`

**Comment by bpoldrack** [comment]
Fair point.

**Comment by mvdoc** [comment]
+1 for @mih's suggestion. In addition, I would also change the error message to something more informative, e.g. if the file I'm trying to add is not added to annex already, it could say something like

```
mvdoc@euclid ~/exp/hauntedhouse_mne/singularity (master*) $ datalad add-archive-content hauntedhouse.img.tgz
[ERROR  ] File hauntedhouse.img.tgz is not under annex. Please run datalad add hauntedhouse.img.tgz before adding its content to annex.
```

Which, at that point, it could be something that `add-archive-content` does automatically if the tarball is not already in annex.

**Comment by yarikoptic** [comment]
That might be a great point to become datalad contributor!! :-) might be faster as well than to wait for an old grumpy Yarik to do it

**Comment by mih** [comment]
+1 for a non-grumpy contributor!

**Comment by mvdoc** [comment]
OK 👍
