### ISSUE TITLE
XNAT

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2]
http://xnat.org is the most widely used FOSS platform for neuroimaging data management and distribution.  Used by openfmri, nitrc, humanconnectome, etc.

Pros:
- python-xnat provides programmable interface so should be relatively straightforward

TODOs:
- no built-in facility for versioning data files

**Comment by yarikoptic** [comment]
Sample projects to work on
- big project:  ABIDE on NITRC-IR  http://www.nitrc.org/ir/app/action/DisplayItemAction/search_element/xnat%3AprojectData/search_field/xnat%3AprojectData.ID/search_value/ABIDE

**Comment by jbpoline** [comment]
@yarikoptic : In a quick search in the neuroimaging and crawler repo I could not locate the xnat crawler : do you know where it is and if it is maintained?  David Rottenberg at CAMH would like to use it

**Comment by yarikoptic** [comment]
It is part of the crawler extension. But to crawl multiple datasets we would need to finish https://github.com/datalad/datalad-crawler/pull/9 . Just bring us in touch so we could iron it out on this particular use case

**Comment by jbpoline** [comment]
@yarikoptic Thanks ! I am still a bit confused :  egrep -R 'xnat|Xnat|XNAT' * on the does not return anything on the datalad/datalad-crawler repo - the only thing I can find in datalad/datalad is below - but the closed issue #2409 seems to point to datalad/crawler/pipelines/xnat.py - which may be only in Christian's branch ? Sorry : I may be missing something obvious !

"""
CONTRIBUTING.md:      http, S3, XNAT) via a unified interface.
datalad/downloaders/configs/hcp.cfg:                   XNAT_CSRF=
datalad/downloaders/configs/hcp.cfg:[provider:hcp-xnat]
datalad/downloaders/configs/hcp.cfg:url_re = xnat://somewhereIdon'tknowyet
datalad/downloaders/configs/hcp.cfg:authentication_type = xnat
datalad/downloaders/tests/test_providers.py:    #eq_(provider_names, {'crcns', 'crcns-nersc', 'hcp-http', 'hcp-s3', 'hcp-web', 'hcp-xnat', 'openfmri'})
datalad/downloaders/providers.py:    'xnat': NotImplementedAuthenticator,
docs/design.rst:XNAT, COINS, ...
"""

**Comment by jbpoline** [comment]
@yarikoptic Thanks ! I am still a bit confused :  egrep -R 'xnat|Xnat|XNAT' * on the does not return anything on the datalad/datalad-crawler repo - the only thing I can find in datalad/datalad is below - but the closed issue #2409 seems to point to datalad/crawler/pipelines/xnat.py - which may be only in Christian's branch ? (see [here](https://github.com/datalad/datalad/pull/2409/commits/32afbe860b24a01c70cc0e4f2061774691936827#diff-78bd947238172355b3c594878f7f8eaf) 
Sorry : I may well be missing something obvious !

"""
CONTRIBUTING.md:      http, S3, XNAT) via a unified interface.
datalad/downloaders/configs/hcp.cfg:                   XNAT_CSRF=
datalad/downloaders/configs/hcp.cfg:[provider:hcp-xnat]
datalad/downloaders/configs/hcp.cfg:url_re = xnat://somewhereIdon'tknowyet
datalad/downloaders/configs/hcp.cfg:authentication_type = xnat
datalad/downloaders/tests/test_providers.py:    #eq_(provider_names, {'crcns', 'crcns-nersc', 'hcp-http', 'hcp-s3', 'hcp-web', 'hcp-xnat', 'openfmri'})
datalad/downloaders/providers.py:    'xnat': NotImplementedAuthenticator,
docs/design.rst:XNAT, COINS, ...
"""

**Comment by kyleam** [comment]
> but the closed issue #2409 seems to point to datalad/crawler/pipelines/xnat.py

After the crawler was split into an extension, PR #2409 was closed and migrated to the (still open) datalad/datalad-crawler#9.

> - which may be only in Christian's branch ? Sorry : I may be missing something obvious !

I don't think you're missing anything.  AFAICT the only xnat support exists in that unmerged PR.

**Comment by jbpoline** [comment]
Ok ! thanks  @kyleam !

**Comment by mih** [comment]
We have https://github.com/datalad/datalad-xnat now. I think this can be closed.
