### ISSUE TITLE
datalad create-sibling-github interactive configuration does not support 2FA

### ISSUE THREAD

**Issue by mvdoc** [datalad/datalad#2004]
#### What is the problem?

I set up two factor authentication (as everybody should! ;)), and the interactive configuration of `datalad create-sibling-github` doesn't work. Also the suggested method in the manpage (using https://github.com/sociomantic/git-hub) fails, because they do not support 2FA yet. The solution is to create manually a personal access token here: https://github.com/settings/tokens/new. 

I can update the manpage if desired.

#### What steps will reproduce the problem?

```terminal
contematto@head1 /data/famface/openfmri/data (master) $ datalad create-sibling-github famface_data
You need to authenticate with 'github' credentials. https://github.com/login provides information on how to gain access
user: mvdoc

password:
password (repeat):
[ERROR  ] 401 {'message': 'Must specify two-factor authentication OTP code.', 'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication'} [Requester.py:__check:180] (TwoFactorException)
```

**Comment by yarikoptic** [comment]
I believe it was fixed in https://github.com/datalad/datalad/pull/3180 within 0.11.5 release
