### ISSUE TITLE
Implement a datalad_datasink for nipype

### ISSUE THREAD

**Issue by mih** [datalad/datalad#201]
Simply write workflow output into a repo, unlock the relevant files on re-runs, commit changes with their meta data (if availble).

**Comment by yarikoptic** [comment]
we might be able to join this with https://github.com/datalad/datalad/issues/155 as a "mode".  I will take a crack at 'open for reading' facility right away (which would automagically fetch content), and then we could see how we could make it work whenever file is intended to be written -- unlock and move previous one to the sink?

**Comment by mih** [comment]
Closing this issue of mine, acting on the apparent lack of motivation to work on it.
