### ISSUE TITLE
Q: why my search provided inconsistent results across different capitalizations of the query?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2018]
#### What is the problem?
no results whatsoever if I search for originally Cased name
```shell
(git)hopa:/tmp/crawl[master]git
$> datalad search *haxby* type:dataset
[INFO   ] Query completed in 11.6319460869 sec. Reporting up to 20 top matches. 
search(ok): labs/haxby
search(ok): labs/haxby/attention
search(ok): labs/haxby/life
search(ok): labs/haxby/raiders
action summary:
  search (ok: 4)
datalad search *haxby* type:dataset  12.38s user 0.39s system 102% cpu 12.432 total

$> datalad search *Haxby* type:dataset
[INFO   ] Query completed in 11.5955178738 sec. No matches. 
```

**Comment by mih** [comment]
The underlying question is what kind of processing (chunking) whoosh should do.

**Comment by mih** [comment]
As #2032 shows, there is no need to do so, in order to get matches regardless of capitalization.

**Comment by yarikoptic** [comment]
ok, I rephrased the question ;-)  if I could "get matches regardless of capitalization" - why I had such a different experience?  why no other dataset, with Haxby in the dataset metadata were reported?

**Comment by mih** [comment]
I don't know. Can we first figure out what is supposed to happen (feedback on #2032), then identify when it doesn't happen (possibly here), and then fix those.

**Comment by mih** [comment]
Oh and let me say it again: Please no `*haxby*`, just `haxby`.

**Comment by yarikoptic** [comment]
I believe I tried that one too, and I could answer "what is supposed to happen" regarding this particular aspect right here (#2032 seems to have a broader scope): if casing is not important -- results should be the same.

**Comment by mih** [comment]
Did you ever try on another machine, this is not the first time smaug is behaving differently: https://github.com/datalad/datalad/issues/1958#issuecomment-343723420

**Comment by yarikoptic** [comment]
aggregation was done on smaug, since that is where all the datasets are, and where all of us have access to.  Search (thus index construction) was done on the laptop (name `hopa` from HP + [jopa](https://www.urbandictionary.com/define.php?term=jopa) ) but so far it didn't live up to its name.  I will try now search on smaug and with python3 to rule out python2 effect ;-), while installing from the same location (`smaug:/mnt/btrfs/datasets-openfmri-crawl-20171120/datalad/crawl`).  Did it work for you?

**Comment by mih** [comment]
No, as reported in that issue. Smaug does not work.

**Comment by yarikoptic** [comment]
Please be more specific - smaug itself is working just fine. Your guess, is it aggregation which doesn't work correctly or what step/functionality?  Anyways we would need to figure out why/what doesn't work and fix for it

**Comment by mih** [comment]
All I know is in the issue. I also know that I see the behavior posted in
the demo on other machines too, but not smaug. Once we agree on how it is
supposed to work, I will start tracking down the issues. I have yet to hear
from anyone that the posted demo is worth making to work (on smaug too).

**Comment by mih** [comment]
As hinted in #2014 AutomagicIO might be a factor to could explain the diff in behavior on smaug and elsewhere. But not necessarily AutomagicIO itself, but the fact that it might not be in use at all on other machines:

```
mih@meiner /tmp % datalad create test
[INFO   ] Creating a new annex repo at /tmp/test 
create(ok): /tmp/test (dataset)                                                          
mih@meiner /tmp % cat test/.datalad/config
[datalad "dataset"]
        id = 09b85ca2-e485-11e7-aeb5-f0d5bf7b5561
mih@meiner /tmp % cat test/.gitattributes
* annex.backend=MD5E
mih@meiner /tmp % cat test/.datalad/.gitattributes
# Text files (according to file --mime-type) are added directly to git.
# See http://git-annex.branchable.com/tips/largefiles/ for more info.
** annex.largefiles=nothing
metadata/objects/** annex.largefiles=(largerthan=20kb)
```

Freshly created datasets look like this, but the ones on smaug are much older and probably have `metadata/objects/*` annexed unconditionally. In practice it is rare to observe metadata objects that exceed 20kb, hence a broken AutomagicIO should have no/little negative effect on recent dataset.

I think this would be worth investigating....

**Comment by mih** [comment]
#2115 has a new default search mode now, that (still) doesn't show the behavior that is described in here -- using a subset of the `///` that was reaggregated locally. As soon as the big dataset got frshly aggregated metadata we can figure out what is happening, and if it is happening still.

**Comment by mih** [comment]
No longer an issue.

Please see #2326 for a related RF.
