### ISSUE TITLE
What should search do different by default?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2032]
@yarikoptic We had quite a few discussions on what to do differently. Given that the `///` is not a viable beast to play with, I decided to take a few datasets from it, reaggregate them and re-published them (without data). I will use this to implement further tests. Moreover, I would be glad to get comments on the default behavior. I give a sample below. Please chime in with your feedback and suggestions.

The following protocol is what is possible after a plain reaggregation, without any change in the dataset configuration.

```sh
% datalad install -s http://psydata.ovgu.de/aggdemo/demo/ aggdemo
[INFO   ] Cloning http://psydata.ovgu.de/aggdemo/demo/ to '/tmp/aggdemo' 
[INFO   ] access to dataset sibling "psydata" not auto-enabled, enable with:
|               datalad siblings -d "/tmp/aggdemo" enable -s psydata 
install(ok): /tmp/aggdemo (dataset)
% cd aggdemo
% datalad search
[INFO   ] Building search index 
[INFO   ] Scanning for metadata keys 
[INFO   ] Added 1 document on dataset . 
[INFO   ] Added 9457 documents on dataset crcns-vim-2 
[INFO   ] Added 4 documents on dataset openfmri 
[INFO   ] Added 134 documents on dataset openfmri/ds000001 
[INFO   ] Added 280 documents on dataset openfmri/ds000002 
[INFO   ] Search index contains 9876 documents 
% datalad search nishimoto
[INFO   ] Query completed in 0.00141906738281 sec. Reporting up to 20 top matches. 
search(ok): crcns-vim-2
% datalad search poldrack
[INFO   ] Query completed in 0.00161004066467 sec. Reporting up to 20 top matches. 
search(ok): openfmri/ds000002
search(ok): openfmri/ds000001
search(ok): openfmri
action summary:
  search (ok: 3)
% datalad search POldrack
[INFO   ] Query completed in 0.00153279304504 sec. Reporting up to 20 top matches. 
search(ok): openfmri/ds000002
search(ok): openfmri/ds000001
search(ok): openfmri
action summary:
  search (ok: 3)
% datalad search female --max-nresults 2
[INFO   ] Query completed in 0.00117993354797 sec. Reporting up to 2 top matches. 
search(ok): openfmri/ds000001/sub-10/anat/sub-10_T1w.nii.gz
search(ok): openfmri/ds000001/sub-12/func/sub-12_task-balloonanalogrisktask_run-03_bold.nii.gz
[INFO   ] Reached the limit of 2 top matches, there could be more which were not reported. 
action summary:
  search (ok: 2)
% datalad search PDDL
[INFO   ] Query completed in 0.00128984451294 sec. Reporting up to 20 top matches. 
search(ok): openfmri
search(ok): openfmri/ds000002
search(ok): openfmri/ds000001
action summary:
  search (ok: 3)
% datalad search 'bids:age(years):[24 TO 26]' --max-nresults 2
[INFO   ] Query completed in 0.00272512435913 sec. Reporting up to 2 top matches. 
search(ok): openfmri/ds000001/sub-09/func/sub-09_task-balloonanalogrisktask_run-01_bold.nii.gz
search(ok): openfmri/ds000001/sub-09/func/sub-09_task-balloonanalogrisktask_run-02_bold.nii.gz
[INFO   ] Reached the limit of 2 top matches, there could be more which were not reported. 
action summary:
  search (ok: 2)
```

**Comment by yarikoptic** [comment]
Just in attempt to answer the formulated question and echoing my whining in #2079, I think that "by default" we should:
- parse all, aggregate, and make available all metadata from the datasets we provide
- make this metadata easily usable by users

So what `search` should do differently by default? only that it should be **usable** by users on datasets.datalad.org .  Either it requires any changes to search -- might be not and just educating me how to accomplish the mission!

For what I meant with "usable" -- above  examples are great and worked for me wonderfully, thanks! But  on a larger datasets.datalad.org though, creation of index does take way too long during initial `search` if we index **all** metadata by "default".  So "someone" should decide to index e.g. only datasets level metadata in such case.  What I was trying to suggest in #2079 is that "by default" we might want to search "dataset" level metadata only.   But as @mih 's example above nicely demonstrates it is quite feasible in smaller use-cases to index and search through all of metadata, which is sweet.  So, I guess, that is where I, as a curator of the super-dataset, (probably already, as @mih tried to tell me) could state (via config/command `???`) that if someone installs this particular super-dataset (e.g. `///` or even `///openfmri`) -- by default, it should index only dataset-level metadata (even though subdatasets might carry content metadata, and if I install them -- content metadata will be indexed while searching in them)  and let user know about that and include instructions on how to make it index and search across all levels, e.g. with a message: 
```
INFO: only dataset-level metadata is indexed and searched for this dataset by default.
INFO: Run XXX to enable indexing also per-file metadata. Note that this operation might take considerable amount of time (minutes or hours) on this large dataset
```
So, may be, such commands/settings as `???` and `XXX` already exist and allow to achieve desired default "scale-dependent" behavior?

**Comment by bpoldrack** [comment]
> For what I meant with "usable" -- above examples are great and worked for me wonderfully, thanks! 

Great. That's what I wasn't sure about in previous discussions and that's what I first and foremost wanted to know by means of the hangout I proposed in #2079 .

**Comment by mih** [comment]
With #2127 `search` does all that. At least in principle. Once we have new-style aggregated metadata for `///` we can test and fix any remaining issues that come up.
