### ISSUE TITLE
AnnexRepo doesn't allow access "not yet touched by annex" git (with annex) clone if create=False

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#204]
AnnexRepo create=False fails to initialize if dir is a fresh clone of an annex, so there is no local .git/annex yet.

Use-case -- try to overlay AnnexRepo on a directory which might (e.g. that fresh clone) or might not be annex (should puke).  With create=True it would initialize that directory to become annex if it is not an annex (wrong), with create=False it would puke although it is an annex, just didn't experience any git annex command/hook to be ran yet.

**Comment by bpoldrack** [comment]
So, look for a git-annex branch instead?

**Comment by yarikoptic** [comment]
I guess... but it might still be among remote branches

**Comment by bpoldrack** [comment]
Right. Okay.

**Comment by yarikoptic** [comment]
note that annex itself doesn't run 'annex init' in non-annex repo -- it would just exit with
```
(git)hopa:~deb/bats[debian]git
$> git annex get .
git-annex: First run: git-annex init
```
but if repository is annexed (there is a remote git-annex branch), then it does something (not necessarily full blown 'annex init', I just don't know and not sure if we could rely on that assumption) to make remote git-annex branch usable.  If no remote git-annex branch available among any remotes -- it asks to run init

**Comment by bpoldrack** [comment]
Re 'read-only' from #205 
I'm absolutely fine with the different detection of whether a repo is an annex as described above.
What I don't really get is: What else besides the information "this is an annex" do you imagine to read from an annex without calling an annex-init?

**Comment by yarikoptic** [comment]
ideally I just need a command which would tell me that a file is under annex control (thus doesn't work for direct mode atm since I rely on git to tell me that), then discover what is the root dir of that Annex, then to check if it has content (we have one already), and then request content (we have that one already too)

**Comment by yarikoptic** [comment]
actually let's just ask @joeyh :  is there an annex command I could run on an arbitrary file in an arbitrary directory to figure out if it is under control of annex (rooted somewhere above, and possibly in the direct mode, thus not just a symlink to .git/annex/objects)? and then (or at the same time) to figure out the root directory (we could traverse up until hitting .git but I bet annex does it already as well and better, respecting $GIT_DIR etc) of that annex repo?

**Comment by bpoldrack** [comment]
Well, my point is the question whether annex would be able to tell about an annexed file without invoking 'init'. That's what I try to understand regarding "read-only".

As for the functionality itself: What about checking get_file_key()? No key, no annex, right?

**Comment by yarikoptic** [comment]
On Wed, 16 Sep 2015, bpoldrack wrote:

> Well, my point is the question whether annex would be able to tell about an
> annexed file without invoking 'init'. That's what I try to understand regarding
> "read-only".

> As for the functionality itself: What about checking get_file_key()? No key, no
> annex, right?

that should work indeed!  so we just need to figure out for a file what
is the possible repo root  dir.... we could check if a symlink (would
work only on non-crippled FS) and points to somewhere in .git/annex and
broken then it must be in annex and indirect mode, and we can
figure out topdir and get it.  If file is not a symlink and for direct
mode/crippled FS I guess we need to traverse up to find .git and then
use get_file_key()

**Comment by bpoldrack** [comment]
To me it's just not clear where to do the detection of the root dir. 
datalad commands should work like git/git-annex commands. So, most of them should figure out where they are in anyway and get a fitting repo instance (see cmdline/helpers/get_repo_instance). I'm not sure at what point we would need to use the automagic without already knowing the root dir.

**Comment by yarikoptic** [comment]
ah -- cool. missed that `get_repo_instance`. could/should use it I guess. minor wishlist comment then what if it would accept path to be a path to file -- would it may be beneficial may be inspect if a symlink and where it points to and if to '(\.\./)+/\.git/' take that path?  or you don't expect any speedups from that logic?

**Comment by joeyh** [comment]
git annex info run on a file will tell you that. It didn't work in
direct mode until recently; does now.

As to finding the top of the git repository: git rev-parse --git-dir

-- 
see shy jo

**Comment by yarikoptic** [comment]
@joeyh cool, thanks!

**Comment by yarikoptic** [comment]
@bpoldrack meanwhile RFed to use `get_repo_instance` in bbf6a7793cfe0c06df071215026530ad85dfa8fd BUT then we get back to needing to detect not-yet-inited annexrepo as annexrepo (test would fail now ) ;)

**Comment by yarikoptic** [comment]
btw annex also imposes itself a bit too much ;)  http://git-annex.branchable.com/bugs/may_be_annex_should_be_more_attentive_to_non-annex_repos_and_not_annexify_them__63__/

**Comment by yarikoptic** [comment]
Placing agreed to be done RFing to remove "creation" from constructors for Repos, this issue was resolved by introducing init=False to AnnexRepo in b2a5bcd9b0c03d17c22e660fefa5e1e9473c26fa
