### ISSUE TITLE
publish .  says that the directory is not in annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2042]
#### What is the problem?
IIRC we thought to be able to publish (annex copy) subdirectories but seems to be not so (if I point to individual file -- does ok)

```shell

$> datalad publish --to=origin .
[INFO   ] Publishing <Dataset path=/home/yoh/proj/pymvpa/papers> data to origin 
File not in annex: xxxx/locs% 
```
datalad current master 0.9.1-521-gf16f652d

**Comment by mih** [comment]
Tried now, not an issue with 0.12.2
