### ISSUE TITLE
Stop using /// in tests

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2044]
#### What is the problem?
it makes it impossible to figure out popularity of datasets, and of the /// altogether since tests are also ran in CI, which goes through a wide range of IPs, thus making it virtually impossible to figure out if access to a dataset is real or a "test".  E.g.

```bash
> zcat datasets.datalad.org-access-comb.log.2.gz | sed -n -e '/"git\/[12345]/s,^\([0-9\.]*\) .*"GET \(.*\)\.git/.*,\1 \2,gp'  | sort | uniq | awk '{print $2;}' | sort | uniq -c  | sort -n  | grep '^ *[0-9][0-9]'
     12 /workshops/nih-2017/ds000114/derivatives/fmriprep/
     12 /workshops/nih-2017/ds000114/derivatives/freesurfer/
     15 /workshops/nih-2017/ds000114/
     24 /dbic/QA/
     46 /labs/tarr/
     46 /labs/tarr/face_place/
     46 /nonexisting/
     48 /labs/
    168 /openfmri/ds000114/
    270 /
    276 /crcns/
```
made me think that `face_place` is very popular, just to find that we are using it in `test_remove_recursive_2` :-(

I think we should
1. change the tests to use some other, dedicated collection (could be a snapshot of current/some datasets.datalad.org)
2. add the test of the /// into buildbot set of tests though, so we do verify healthy state of ///

**Comment by yarikoptic** [comment]
@mih could you please register an A for `datasets-tests.` to also point to falkor?

**Comment by mih** [comment]
Done. Using datasets-dev would also be an option.

**Comment by yarikoptic** [comment]
I thought about it too, but better to keep -dev for experimentation etc.  With a dedicated -tests I can simply point to the same location but collect "independent" logs, which would be the point. doing it now, PR is coming
