### ISSUE TITLE
make IncompleteResults report more complete whenever aggregation fails

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2049]
#### What is the problem?
ATM, e.g. while running tests (when no other errors output) I just get
```shell
IncompleteResultsError: Command did not complete successfully [{'action': 'aggregate_metadata', 'path': '/home/yoh/.tmp/datalad_temp_tree_test_aggregation7B4P9z/origin', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}, {'action': 'aggregate_metadata', 'path': '/home/yoh/.tmp/datalad_temp_tree_test_aggregation7B4P9z/origin/sub', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}, {'action': 'aggregate_metadata', 'path': '/home/yoh/.tmp/datalad_temp_tree_test_aggregation7B4P9z/origin/sub/subsub', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}]
```
I wondered if message could include at least some clue on what has actually has failed

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
