### ISSUE TITLE
Consts should likely not define dir paths including '.git'

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2054]
#### What is the problem?

In `consts.py` we define stuff like this:

```
DATALAD_GIT_DIR = join('.git', 'datalad')
ANNEX_TEMP_DIR = join('.git', 'annex', 'tmp')
```

I think this is inappropriate, because `.git` can easily be a file. That is why we have `get_git_dir(path)` that will report the actual location of `.git/`, possibly by reading it from a .git file. Such constants should probably just identify the name inside the `.git/` directory.

**Comment by yarikoptic** [comment]
Good find
But do we support at all working in those repos with .git being a file? For submodules we assure it is not so the second one should be ok since iirc otherwise annex wouldn't work at all in Independence mode...
But probably indeed better to remove dependency on such assumptions where possible

**Comment by yarikoptic** [comment]
marked it as a target for 1.0, but note that `.consts` aren't a part of the core (at least not yet to any part of it) ;)

**Comment by mih** [comment]
Today, the only place of `DATALAD_GIT_DIR` usage is other consts:

```
datalad/consts.py:ARCHIVES_TEMP_DIR = join(DATALAD_GIT_DIR, 'tmp', 'archives')
datalad/consts.py:WEB_META_LOG = join(DATALAD_GIT_DIR, 'logs')
datalad/consts.py:WEB_META_DIR = join(DATALAD_GIT_DIR, 'metadata')
```

where `WEB_META_LOG` is only used in `create_sibling` (in a remote context, where a const declaration might be OK).

and where `WEB_META_DIR` is not used in the core package at all.

`ARCHIVES_TEMP_DIR` is used by the `clean` command and `datalad/support/archives.py`, and could be easily replaced with a proper `.dotgit` usage. Same goes for the `ANNEX_TEMP_DIR` const.

**Comment by mih** [comment]
I am linking this in #1095 -- it is pretty much the same thing. No need to keep them both around. Consts that are not that, should not be in consts.py
