### ISSUE TITLE
ENH: enable AutomagicIO upon import by setting an environment variable

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2062]
#### What is the problem?

I want to be able to trigger DataLad's AutomagicIO e.g. by simple enabling an environment variable (`DATALAD_AUTO_ENABLE=1` ?), so a tool which imports datalad (e.g. heudiconv) could then trigger its activation for the duration of that run.

**Comment by adelavega** [comment]
Given that AutomagicIO is deprecated, it seems this issue can be closed?

**Comment by yarikoptic** [comment]
Yeah, let's just close. Thanks @adelavega for the buzz
