### ISSUE TITLE
ENH: datalad shell  command

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2063]
#### What is the problem?

while thinking about #2062 I though that it might be nice to have a simple `datalad shell` command which would by default simply start a new shell session, but it could provide superpowers
- `--auto` option would enable AutomagicIO, at least for the sub-processes which import datalad (hence could be activated using env var #2062). Eventually an implementation providing overrides for basic syscalls and thus more of FUSE like functionality could be provided
- `-d DS` would just cd to that dataset directory, so it is more of "pushd/popd" tandem
- `--record-runs` - if we could pull off to use `datalad run` for any command executed, might be quite cool! VCS controlled shell all the way down
- anything else (shell aliases of some kind? ;) )

**Comment by kskyten** [comment]
Building on top of ipython is probably the easiest way to buid a custom shell. [Pyfilesystem](https://www.pyfilesystem.org/) is really nice for building custom filesystems. I think it might be possible to FUSE mount them.

**Comment by bpoldrack** [comment]
Generally, I agree - we thought about some kind of a dedicated shell as a possible UI at the very beginning of the project. Back then, the idea was to have a tailored bash (which Alex said was easy to do), may be even as part of a "GUI", allowing users to click some fancy buttons that would produce preformed commands in that shell. Basically tricking GUI-affin people into using a proper shell eventually ;-)

However, building on top of ipython might work as well. I guess, the question is: Should that shell provide superpowers for using the CLI or the python API of datalad? The former might be harder to do on top of ipython and vice versa.

**Comment by kskyten** [comment]
I think it's more robust to interact with the API directly. In addition to wrapping `datalad run`, it would be useful to have wrappers for certain shell commands (e.g curl, wget, aria2c) so that you get asked whether to add the files to the dataset.

An additional bonus for using Ipython is that it should be straightforward to add support for using datalad from inside jupyter notebooks as well.

**Comment by bpoldrack** [comment]
Re jupyter notebooks: That's a really good point!

And while there is 'git bash' and some basic linux support layer on windows nowadays, I guess building on top of ipython also works more reliably on windows than a bash.
But I never looked into how to do it. So I can't estimate effort. Apart from that - Sounds good to me.

**Comment by yarikoptic** [comment]
re jupyter: you know that I have been a fan and supporter of the ipython/jupyter project for quite a long time, and it is currently "omnipresent" everywhere.  BUT I think that whatever shell we design then should ideally be modular enough so could be used with ipython as a frontend, or some, may be less appealing, or may be custom GUI frontend.  I do not think we should bring in ipython as the (heavy) dependency to get any `datalad shell` functionality.

**Comment by kskyten** [comment]
Juoyter notebooks  are no longer bundled in with Ipython like it used to be. The notebook interface can be added optionally and adding ipython as a  dependency is not as heavy anymore.

**Comment by yarikoptic** [comment]
While thinking about such an interface, among old issues ran into https://github.com/datalad/datalad/issues/81 which pointed us to http://weboob.org . Might be yet another frontend

**Comment by yarikoptic** [comment]
another thing to consider, at least on the systems where possible, is to "misrepresent symlinks as files".  Here is a LD_PRELOAD-based workaround targetting firefox as original use case https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=691099#14

**Comment by yarikoptic** [comment]
Just ran about https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/README.rst which seems to be used by many projects and might be the one to use if we decide to provide our own shell

**Comment by mih** [comment]
@yarikoptic prompt-toolkit looks good!

**Comment by mih** [comment]
Closing and connecting to #2979
