### ISSUE TITLE
Add duecredit support/entry

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2065]
#### What is the problem?
I thought we already have it but apparently not.  For now at least we should add a basic support to cite ourselves.
Later on, ideally, we should `.cite` any dataset which gets installed/accessed if it has reference information.  We haven't looked into standardizing/harmonizing that information yet AFAIK, did we?

**Comment by tyarkoni** [comment]
👀

**Comment by mih** [comment]
#3184 fixed this, but didn't close it
