### ISSUE TITLE
shouldn't list-collections list "localcollection" as well?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#207]
or intent is to list only "remote" and/or explicitly created collections?

**Comment by bpoldrack** [comment]
Was intended to not list it, since this is not registered collection. So, theoretically, the user doesn't even need to know about it. But this is open to discussion anytime.

**Comment by hanke** [comment]
I would vote for treating it as a special case and not list it. It is implicit in many ways. Listing it, we would need to face things like "why can't I unregister it?".

**Comment by bpoldrack** [comment]
So, can we close it or still disagreement here?

**Comment by yarikoptic** [comment]
lets let it RIP (for now at least ;) )
