### ISSUE TITLE
Split datalad run into run and rerun commands?

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2072]
If we go in the direction of extending `datalad run`'s rerun
capabilities (#2070 and beyond), things start to get a little crowded,
with lots of options only in effect if the `--rerun` flag is given.
Perhaps we should have a dedicated `datalad rerun` command that would
set up the rerun and call `run` underneath.

#2070 still needs a good amount of refactoring, so this could be done
as part of that PR.

**Comment by mih** [comment]
Yes, please! AFAICS this will greatly simplify things and I see very little benefit of keeping these things together in one command (actually none that I can see).

**Comment by yarikoptic** [comment]
Well done @kyleam . Hereby I am officially assigning you to lead the *DataLad Communication Committee* to facilitate immediate approvals by the German side!

**Comment by yarikoptic** [comment]
I don't know why github didn't close it -- we had Closes statement. heh. Was closed by #2076
