### ISSUE TITLE
Error when running datalad crawl

### ISSUE THREAD

**Issue by ntraut** [datalad/datalad#2073]
#### What is the problem?
error when running `datalad crawl` from the example in http://datalad.org/for/data-consumers

#### What steps will reproduce the problem?
Exactly the same steps as in the example:
```
datalad create --text-no-annex demo
cd demo
datalad crawl-init --save --template=simple_with_archives url=http://www.fmri-data-analysis.org/code 'a_href_match_=.*d=1$'
datalad crawl
```
[INFO   ] Loading pipeline specification from ./.datalad/crawl/crawl.cfg 
[INFO   ] Creating a pipeline to crawl data files from http://www.fmri-data-analysis.org/code 
[INFO   ] Not adding annex.largefiles=exclude=README* and exclude=LICENSE* to git annex calls because already defined to be (not(mimetype=text/*)) 
[INFO   ] Running pipeline [<function Annexificator.switch_branch.<locals>.switch_branch at 0x10c2c5620>, [[<datalad.crawler.nodes.crawl_url.crawl_url object at 0x10c2bb908>, a_href_match(query='.*d=1$'), <datalad.crawler.nodes.annex.Annexificator object at 0x10a1debe0>]], <function Annexificator.switch_branch.<locals>.switch_branch at 0x10c2c5510>, [<function Annexificator.merge_branch.<locals>.merge_branch at 0x10c2c56a8>, [find_files(dirs=False, fail_if_none=True, regex='\\.(zip|tgz|tar(\\..+)?)$', topdir='.'), <function Annexificator.add_archive_content.<locals>._add_archive_content at 0x10c2e0840>]], <function Annexificator.switch_branch.<locals>.switch_branch at 0x10c2e08c8>, <function Annexificator.merge_branch.<locals>.merge_branch at 0x10c2e0950>, <function Annexificator.finalize.<locals>._finalize at 0x10c2e09d8>] 
[INFO   ] Found branch non-dirty -- nothing was committed 
[INFO   ] Checking out master into a new branch incoming 
[INFO   ] Fetching 'http://www.fmri-data-analysis.org/code' 
[ERROR  ] isinstance() arg 2 must be a type or tuple of types [matches.py:__call__:64] (TypeError)

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad plugin wtf`)?
datalad 0.9.1 on mac os

#### Is there anything else that would be useful to know in this context?
The issue was solved by installing the scrapy package: `conda install -c conda-forge scrapy`, but there is no error message telling that the scrapy package is missing.

#### Have you had any success using DataLad before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)
I ran successfully the first example.

**Comment by yarikoptic** [comment]
was addressed by #2078
