### ISSUE TITLE
error in converted example script reproducible_analysis.sh

### ISSUE THREAD

**Issue by ntraut** [datalad/datalad#2074]
#### What is the problem?
The downloadable script `reproducible_analysis.sh` contains the wrong line `subdir="sub-\$(printf 000 \$count)"` which should be `subdir="sub-\$(printf %03d \$count)"`.
#### What steps will reproduce the problem?
Download the script reproducible_analysis.sh from the home page.
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad plugin wtf`)?
datalad 0.9.1
#### Is there anything else that would be useful to know in this context?
My guess is that replacing all the `printf` by `echo` (and thus removing all the \n) in `tools/cast2script` should be fine and fix the issue.
#### Have you had any success using DataLad before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)
I did not see any error of conversion in the examples before.

**Comment by yarikoptic** [comment]
was fixed by #2081
