### ISSUE TITLE
Why many "bids:" for majority of the fields but "comment<participant#sex>" ?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2075]
#### What is the problem?

@mih - I just wonder what is the logic to decide between using `bids:` prefix vs the `comment`?  because BIDS does not prescribe the units (years vs months)?

**Comment by mih** [comment]
I will not make an attempt to explain the rational as the basis for this decision and its necessity is gone with the work that started in #2045. The short answer is that is was a stupid idea that deserves this names as it cannot scale.

Re the prefix issue: `bids:` was is meant for stuff that is, in principle, defined in BIDS. Work has started to make "in principle" "in fact".
