### ISSUE TITLE
RFC: "Aggregate" original metadata representations up the hierarchy

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2086]
#### What is the problem?

There is no problem ;)  Just an idea which came up from discussion the NIDM folks and possibly useful to discuss/keep in mind:

- datalad metadata parsing ATM concentrates on extraction and aggregation (across datasets) key/value metadata pairs
- ATM we are using whoosh, but as reiterated recently in https://github.com/datalad/datalad/issues/2082#issuecomment-358249883, there could be other applications built on top of aggregated metadata, e.g. a full SPARQL query engine
- PROV/NIDM provides *richer* metadata beyond key-value pairs.  

So, to facilitate the best utility for the aggregated metadata to be used by various applications, either our parsers/aggregation should be as expressive as any possible metadata representation, and then possibly just duplicate what is provided in the original (to be parsed) `.json` file, or may be we could just "aggregate" and propagate them "as-is" all the way up, so they could be used (or ignored) by the application (while constructing the index).

From other perspective, all our metadata parsers now harmonize metadata found in the dataset into jsonld for `ds-` and a list of key/value pairs for each file within `cn-` as the "metadata of the dataset".  Then whoosh index is aware of how to build search index from it.  Parsers are nohow participate in construction of the index.  But we could also just propagate other possible metadata descriptors (e.g., `nidm-` file with NIDM metadata representation) and extend parsers' API to implement "software specific" handling during index construction.  Then for whoosh it would extract key value pairs from `nidm-` portion.  for sparql engine, just return already consumable by it representation.

CC @satra @jbpoline @dbkeator @gkiar

**Comment by mih** [comment]
This is already in the works.

**Comment by mih** [comment]
To further clarify: We already need the ability to aggregate arbitrarily nested metadata for other reasons. Supporting NIDM and others is a special case of that AFAICS, hence this will come, and is actually already in progress. Also, AFAICS the only piece of code affected (or limiting right now) is the merging of values from multiple parser -- the parsers themselves can stay as they are (conceptually). I already have an alternative implementation that works with deeply nested values, based on the principle "if anything in such a structure is different from another one, the entire nested structure is considered as a different/unique value". This works nicely, so far.

There is one conceptual problem where input would be much appreciated: So far we considered the git-annex metadata as means to "fixup" metadata coming from other parsers. I am more and more starting to think that we have to abandon this concept. Instead we should consider git-annex metadata as just another metadata source, and introduce a different datalad-specific "fixup" overlay (at some point). Reasons:

- git-annex cannot deal with heavy metadata
- git annex has substantial limitations in the composition of key names (and would therefore impose those limitations on all other layers)
- the (our) (comandline) API is presently to simplistic to handle anything else then simple key=value assignments, and introducing sequence-values (which it can do already) really messes up the merges with other metadata sources.

**Comment by mih** [comment]
One negative note: I am *not* convinced that adding the ability to "aggregate" (but actually gather and duplicate) arbitrary files is a good thing.
- we will re-enter to situation that file number becomes problematic
- we loose the ability to get nice compression across all metadata sources
- I do not see any advantages other than that 3rd-party applications do not have to understand Datalad's API to extract metadata -- but bypassing the API is a substantial disadvantage as we are declaring the "internal" representation of aggregated metadata as public and thereby fixed forever (unless we want to break 3rd-party software, and I doubt that we would want that ;-)

The alternative is to do what we do for any other standard: use proper keys with proper definitions. Also possible, simplistic solutions like the consistent use of a `nidm:` prefix, and if really needed maybe even encapsulation into a single top-level structure `nidm:stuff` will achieve the same level of capabilities (ability to handle absolutely any arbitrarily structured metadata) without any of the downsides.

Anticipating the argument that NIDM/PROV tends to be heavy in size: Again not special. If we are seeing issues with file sizes (and so far we haven't), we better implement support for compartmentalization of any metadata, and not carry a specific solution for a single source.

**Comment by satra** [comment]
@mih - we are going to do some empirical generation using the datalad bids repos to start with and once that's ready it would be good to have a chat in the upcoming weeks to see how we may help and generate a reusable NIDM library that you could plug in.

**Comment by mih** [comment]
@satra great! I carved out a place to get NIDM support into datalad: https://github.com/datalad/datalad/pull/2095/commits/c324a6c0be7f70efcf68df173d41f4a8f63c1322

**Comment by mih** [comment]
Original metadata structure can now be aggregated with #2115 -- however, they will still get incorporated into datalad's internal file format, but with no change to content.
