### ISSUE TITLE
rerun --continue, --abort

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2092]
#### What is the problem?

if during `rerun` command fails we would just end up in some branch or detached HEAD, possibly in a dirty repository.  
It would be nice to be able to retrospect 
- the logs from ran command
- the commit message of the original commit we were rerunning (might have precious notes)
and decide what to do, either
- `save` and `--continue` or 
- `--abort` (so similar to merge and cherry-pick git commands).

The same would be applicable to when we start to handle merges

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
