### ISSUE TITLE
1000genome

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#21]
not neuroimaging but a good/interesting use-case (versioned files via suffixes) available via aspera or S3 (bucket without versioning. versioning was not enabled even though advised in private correspondence).  Locations: http://ftp.ncbi.nlm.nih.gov/1000genomes/  and s3://1000genomes
Contains only 462826 (including versioned copies) of files on s3 atm.

**Comment by mih** [comment]
This issue was moved to datalad/datasets#5
