### ISSUE TITLE
bash/zsh completions

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#210]
I guess we could do it manually but quick search brought me to  https://argcomplete.readthedocs.org which seems to be quite neat:
following minimal intrusion:

```
$> git diff
diff --git a/datalad/cmdline/main.py b/datalad/cmdline/main.py
index 5c4c88a..5e5de9a 100644
--- a/datalad/cmdline/main.py
+++ b/datalad/cmdline/main.py
@@ -10,7 +10,7 @@
 
 __docformat__ = 'restructuredtext'
 
-
+import argcomplete
 import argparse
 import logging
 import sys
@@ -172,6 +172,7 @@ def generate_api_call(cmdlineargs=None):
 
 def main(cmdlineargs=None):
     parser = setup_parser()
+    argcomplete.autocomplete(parser)
     # parse cmd args
     cmdlineargs = parser.parse_args(cmdlineargs)
     # run the function associated with the selected command
```

pros: allows to define extended completions (e.g. handles, collections) within python code itself.  Should generally be more homogeneous with the rest

cons: additional 3rd party dependence (present in Debian/ubuntus), requires its own installation within completions system

**Comment by hanke** [comment]
+100

I don't want to craft anything within Python that figures out how/where to install stuff outside Python's scope. But it is trivial to grab the generated completions and put then where they belong in the Debian packaging (or an RPM for that matter). So: yes to generate, no to Python-based install.

Looks like you have a patch. Is that all it needs?

**Comment by yarikoptic** [comment]
starcluster (btw -- they apparently have similar to our system, just no "Python API" generation, but with shortcut aliases for commands etc), and  uses similar (which inspired this one) module -- optcomplete  (for optparse) but that one doesn't require any "global" enabling shim, so startcluster's completion setup for a user is just a single tiny file to source...
so I guess we just need a closer look into this beast on how to make it easier to "deploy" for the user, but indeed probably is the way to go and indeed those 2 lines changes is enough to start but then Python code should provide additional goodies may be even linked into Constraints system

**Comment by bpoldrack** [comment]
+1 for linking into constraints.

**Comment by hanke** [comment]
I implemented minimal support and install in Debian.

**Comment by hanke** [comment]
This is all merged (and installed for Debian) now. Closing.

Quick final note: for zsh people still have to set up the zsh config so it sources the bash completion script for datalad. This works fine. I hope argcomplete eventually implements proper support for zsh completions.
