### ISSUE TITLE
rerun --message to become a "format" template

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2100]
Originally came up in https://github.com/datalad/datalad/pull/2076#discussion_r163448394

ATM it would be the same message for all reran commits which is kinda boring. It would be nice it it provided a way to template it while providing possibly useful information as dict for its formatting
- author -- author of original commit
- date -- date of the previous commit
- commit -- hexsha of the reran commit
- message -- previous commit message ful
- message-plain -- message with RUN json portion stripped out

Then I could do something like `--message={message-plain}\n This commit was a reran of the original one by {author} on {date}`

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
