### ISSUE TITLE
install a specific version of a dataset

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2109]
#### What is the problem?
ATM we do not have AFAIK datalad way to install a specific version of a dataset. Although whenver it is a git-annex repo in indirect or v6 mode it should be trivial, direct mode makes it not so trivial, and with side-effects (just tried git annex proxy call and was left with bunch  of empty directories for the previous version)

I though I had somewhere an issue for this but could not find.
It is a common convention to use `@` in url to point to a specific commitish, but I wonder if we should make it more explicit via url option to be handled on the client side (e.g., `///path/repo#version=commitish` and correspondingly with a regular url)

related: #1671 - recursive checkout/merge

**Comment by yarikoptic** [comment]
anyone has ideas/recommendations, or should I just kick out initial version as a PR and we would decide from there?

**Comment by mih** [comment]
re `@` vs a url parameter: I think the key question is what we would want to encode that is equally important as the version (because I think the `@` makes for a rather intuitive URI.

In the worst case, we could treat the entire thing as the URL and still parametrize it, e.g.

`///openfmri/ds000113b@v1.2?unlock=all`

**Comment by bpoldrack** [comment]
+1 for `@`

I think giving a commitish isn't really a parameter, that might control what to do with something, but rather part of specifying the thing it is about. Plus, it is an existing convention.

**Comment by yarikoptic** [comment]
> @

I still have a filling that we should avoid it since it is "reserved" and used for specific purpose(s).  It is used as a delimeter of user from address (in email), but it is not even used as a delimiter for the "end of path" (https://tools.ietf.org/html/rfc3986), so
```
In [13]: urlparse("http://datalad.org/sub1@1.0.0#get")
Out[13]: ParseResult(scheme='http', netloc='datalad.org', path='/sub1@1.0.0', params='', query='', fragment='get')
```
we leak into path, and more fun:

```
In [11]: URL("http://datalad.org@1.0.0#get")
Out[11]: URL(fragment='get', hostname='1.0.0', scheme='http', username='datalad.org')
```
- we made it completely obscure (comprehends as a user at 1.0.0 domain).

> ?unlock=all

`?` is usually for "server (or local JS code talking to that remote server) side" options.  Not the case here -- it is also not about really identifying some "query" (what it is for: https://tools.ietf.org/html/rfc3986#section-3.4).

So, to stay safe(r) and somewhat consistent,  IMHO we might prefer us to (ab)use the "#fragment" portion.  https://tools.ietf.org/html/rfc3986#section-3.5 -- seems to be generally also not constrained anyhow.  It would be up to us to parse it into components, since ATM it would just be passed as is, but could be accessed parsed:

```
In [20]: URL("http://datalad.org/path?q=1;q=2#get=sub-1*;get=sub-2*;unlock=derivatives/mriqc*;checkout=0.10.0")
Out[20]: URL(fragment='get=sub-1*;get=sub-2*;unlock=derivatives/mriqc*;checkout=0.10.0', hostname='datalad.org', path='/path', query='q=1;q=2', scheme='http')

In [21]: URL("http://datalad.org/path?q=1;q=2#get=sub-1*;get=sub-2*;unlock=derivatives/mriqc*;checkout=0.10.0").query_dict
Out[21]: OrderedDict([('q', '2')])

In [22]: URL("http://datalad.org/path?q=1;q=2#get=sub-1*;get=sub-2*;unlock=derivatives/mriqc*;checkout=0.10.0").fragment_dict
Out[22]: 
OrderedDict([('get', 'sub-2*'),
             ('unlock', 'derivatives/mriqc*'),
             ('checkout', '0.10.0')])
```

(note, that it is a dict, so in below example second `get` overloads first one -- we might make it possible to "schema" it so some fields like `get`, `unlock` could be specified multiple times, and the value would always be a list).  
We could add some special treatment to `@` in the fragment, but  again I think it wouldn't be a good idea.

**Comment by mih** [comment]
Hmm, at least in the context of #4017 this proposal sounds complicated. I still think the original proposal is clean and workable enough for this purpose and also does not conflict with any conventions or regulation. Maybe we should decouple it from the general question of how to build URLs.

FTR:

```
>>> URL('ria+http://store.datalad.org#6d69ca68-7e85-11e6-904c-002590f97d84@bf-25')                                       
URL(
    fragment='6d69ca68-7e85-11e6-904c-002590f97d84@bf-25',
    hostname='store.datalad.org',
    scheme='ria+http')
```

I consider `6d69ca68-7e85-11e6-904c-002590f97d84@bf-25` to be a nice identifier for a particular version of a particular dataset. The use of a "fragement" to a store URL makes intuitive sense. The `@` delimiter is used inside the fragment, so doesn't conflict with any other type of URL (emails, ...).

**Comment by yarikoptic** [comment]
we don't need to dive/implement general URL handling, but adding `@` to one "URL" would later introduce inconsistency where it could not be used as a mentioned in https://github.com/datalad/datalad/issues/2109#issuecomment-573451395 . So I would have preferred if we didn't postpone such "general URL handling" discussion if there is a URL style to be introduced for any type of URL.

**Comment by bpoldrack** [comment]
As also mentioned in #4022, in this case that `@` is part of URL parameters anyway (after `#`), not of the URL itself. So, the conflict you mentioned above wouldn't apply in case of RIA.

**Comment by dorianps** [comment]
This feature would be of great help to data managers. We plan to "curate + distribute" data. Curation is achieved through commits, while distribution will tag the dataset at specific commits with `--version-tag`. So, hopefully, in the future we can give anyone a dataset with included subdatasets at any version they want by specifying either a tag or a commit. Our use is on a local server though, not online dataset.

**Comment by mih** [comment]
Implementation coming via https://github.com/datalad/datalad/pull/4036
