### ISSUE TITLE
Publishing to sibling after changes to subdataset only works partially 

### ISSUE THREAD

**Issue by ejolly** [datalad/datalad#2118]
#### What is the problem?
After changing/adding a file in a subdataset and running `datalad save` on both the subdataset and the parent, `datalad publish` throws an error. The sibling *does* receive the updated symlinks to files, but `git status` on the sibling shows that the changes are not committed. 

Calling `datalad save` on the sibling after the pseudo-fail publish commits the changes correctly.

#### What steps will reproduce the problem?

``` 
[ejolly@ndoli fnl]$ datalad publish --to gza -r
publish(notneeded): preprocessed (dataset)
[ERROR  ] sequence item 1: expected string, NoneType found [publish.py:has_diff:90] (TypeError)
```
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad plugin wtf`)?
0.9.1
Using branch 0.9.x does not solve the issue

#### Is there anything else that would be useful to know in this context?
Both machines are running linux though different flavors: Cent OS 6 (Dartmouth Discovery Cluster) is trying to publish to Ubuntu Xenial machine. 

#### Have you had any success using DataLad before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)

Datalad is awesome.  The ability to easily maintain shared file trees with optional data-files across machines (though just the tip the iceberg of `datalad`'s functionality) makes life SO much better :)

**Comment by yarikoptic** [comment]
thanks for the report!  Is issue reproducible for you?  from the location `publish.py:has_diff:90` it smells like may be a subdataset (or parent) in detached HEAD mode?  `datalad ls -r .` could be of help for a quick review

NB next time may be retain full path in the shell prompt dump? ;) I could may be peek (if permissions allow)

**Comment by yarikoptic** [comment]
Hi @ejolly - is this issue still there with 0.9.3 (there was lots of fixes)? was it a detached head?

**Comment by mih** [comment]
This issue hasn't received a response in two years, and I fail to replicate the issue. Closing.
