### ISSUE TITLE
Tests fail when Debian package is built on offline system

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#212]
Here is the pattern:

````
make[2]: Leaving directory '/home/mih/hacking/datalad/git'
PATH=/home/mih/hacking/datalad/git/bin:$PATH dh_auto_test
	pybuild --test --test-nose -i python{version} -p 2.7 --dir .
I: pybuild base:170: cd /home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build; python2.7 -m nose 
.E....E.........................SS............S......S...........SS.............................S.....S.......S........S......EEEEEEEEEEEEEEEE.S..............S...............EEEEEE...........
````

example failure:

````
======================================================================
ERROR: datalad.tests.test_main.test_page2annex_same_incoming_and_public('relaxed',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 223, in newfunc
    t(*(arg + (d,)), **kw)
  File "/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 288, in newfunc
    tfunc(*(args + (path, url)), **kwargs)
  File "/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/tests/test_main.py", line 89, in check_page2annex_same_incoming_and_public
    stats1_dry = drepo.page2annex(dry_run=True)
  File "/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/crawler/main.py", line 163, in page2annex
    urls_all = collect_urls(top_url, recurse=scfg['recurse'], hot_cache=hot_cache, cache=cache)
  File "/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/support/network.py", line 196, in collect_urls
    page = (hot_cache and hot_cache.get(url, None)) or fetch_page(url, cache=cache)
  File "/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/support/network.py", line 115, in fetch_page
    return _fetch_page(url, retries=retries)
  File "/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/support/network.py", line 98, in _fetch_page
    openurl = retry_urlopen(url, retries=retries)
  File "/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/support/network.py", line 86, in retry_urlopen
    return urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
-------------------- >> begin captured logging << --------------------
datalad.network: WARNING: Received exception while reading http://127.0.0.1:22310/: <urlopen error [Errno 111] Connection refused>
datalad.network: WARNING: Received exception while reading http://127.0.0.1:22310/: <urlopen error [Errno 111] Connection refused>
datalad.network: WARNING: Received exception while reading http://127.0.0.1:22310/: <urlopen error [Errno 111] Connection refused>
--------------------- >> end captured logging << ---------------------
````

The same tests work fine, even when offline, when ran outside a package build (i.e. `dpkg-buildpackage`).

No idea yet....

**Comment by yarikoptic** [comment]
Just woke up
If you use pybuild, that one overrides http_proxy which messes up testing here I guess.... recent versions have some fix (need to check how-to overcome within vcr) but we might have difficulty backporting then

On September 16, 2015 2:56:23 AM EDT, Michael Hanke <notifications@github.com> wrote:
>Here is the pattern:
>
>````
>make[2]: Leaving directory '/home/mih/hacking/datalad/git'
>PATH=/home/mih/hacking/datalad/git/bin:$PATH dh_auto_test
>	pybuild --test --test-nose -i python{version} -p 2.7 --dir .
>I: pybuild base:170: cd
>/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build; python2.7
>-m nose 
>.E....E.........................SS............S......S...........SS.............................S.....S.......S........S......EEEEEEEEEEEEEEEE.S..............S...............EEEEEE...........
>````
>
>example failure:
>
>````
>======================================================================
>ERROR:
>datalad.tests.test_main.test_page2annex_same_incoming_and_public('relaxed',)
>----------------------------------------------------------------------
>Traceback (most recent call last):
>File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in
>runTest
>    self.test(*self.arg)
>File
>"/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py",
>line 223, in newfunc
>    t(*(arg + (d,)), **kw)
>File
>"/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py",
>line 288, in newfunc
>    tfunc(*(args + (path, url)), **kwargs)
>File
>"/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/tests/test_main.py",
>line 89, in check_page2annex_same_incoming_and_public
>    stats1_dry = drepo.page2annex(dry_run=True)
>File
>"/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/crawler/main.py",
>line 163, in page2annex
>urls_all = collect_urls(top_url, recurse=scfg['recurse'],
>hot_cache=hot_cache, cache=cache)
>File
>"/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/support/network.py",
>line 196, in collect_urls
>page = (hot_cache and hot_cache.get(url, None)) or fetch_page(url,
>cache=cache)
>File
>"/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/support/network.py",
>line 115, in fetch_page
>    return _fetch_page(url, retries=retries)
>File
>"/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/support/network.py",
>line 98, in _fetch_page
>    openurl = retry_urlopen(url, retries=retries)
>File
>"/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/support/network.py",
>line 86, in retry_urlopen
>    return urlopen(url)
>  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>    return opener.open(url, data, timeout)
>  File "/usr/lib/python2.7/urllib2.py", line 431, in open
>    response = self._open(req, data)
>  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
>    '_open', req)
>  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
>    result = func(*args)
>  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
>    return self.do_open(httplib.HTTPConnection, req)
>  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
>    raise URLError(err)
>URLError: <urlopen error [Errno 111] Connection refused>
>-------------------- >> begin captured logging << --------------------
>datalad.network: WARNING: Received exception while reading
>http://127.0.0.1:22310/: <urlopen error [Errno 111] Connection refused>
>datalad.network: WARNING: Received exception while reading
>http://127.0.0.1:22310/: <urlopen error [Errno 111] Connection refused>
>datalad.network: WARNING: Received exception while reading
>http://127.0.0.1:22310/: <urlopen error [Errno 111] Connection refused>
>--------------------- >> end captured logging << ---------------------
>````
>
>The same tests work fine, even when offline, when ran outside a package
>build (i.e. `dpkg-buildpackage`).
>
>No idea yet....
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/212

-- 
Sent from a phone which beats iPhone.

**Comment by yarikoptic** [comment]
#215 should provide means to address this one

**Comment by hanke** [comment]
Much better! Thanks.

Only left with those now:

````
I: pybuild base:170: cd /home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build; python2.7 -m nose 
...F.F.....F..................................S......S...........SS..................................S.......S.F......S.......................S..............F...............................
======================================================================
FAIL: datalad.tests.test_annexrepo.test_AnnexRepo_file_has_content
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 472, in newfunc
    assert(testrepos_uris)
AssertionError

````

**Comment by hanke** [comment]
Ah, that may be me not having merged all things....

**Comment by hanke** [comment]
All good now.
