### ISSUE TITLE
download_url should get an option to add downloded file into annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2123]
#### What is the problem?
and register that url with it
so pretty much to do what `annex addurl` does 

also should become a `@datasetmethod`, so if a dataset is provided, it could be even assumed that it should be added to annex and url added

**Comment by yarikoptic** [comment]
@kyleam would you be so kind to work this one out?  necessity for the `--pathdepth -1` is driving me away from pure `git annex addurl`.  Also would be cool to get an option `--add-archive-content` to immediately (after `save` I guess) pass obtained file to `add_archive_content(delete=True)`

**Comment by kyleam** [comment]
Sure, I'll look into it.
