### ISSUE TITLE
Better argparse

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#213]
As we are trying to add dependencies, what about this one:
https://github.com/bw2/ConfigArgParse

Drop in replacement for argparse, also replaces our custom Config parser.

?

**Comment by yarikoptic** [comment]
looks neat... for debian backport packages we would need to wait for their new release (minor) to get tests going: https://github.com/bw2/ConfigArgParse/issues/11#issuecomment-140750904

**Comment by yarikoptic** [comment]
on the closer look -- how would we be able to specify configuration options for e.g. specific commands?  this one seems to be a flat structure and e.g. section names are simply ignored (treated as comments).  

also not sure if that 'flexibility' (either python-style or yaml-style but neither of those strictly specifically enforced) wouldn't kick us at some point

but yeah - something like that

**Comment by bpoldrack** [comment]
I agree, ignoring sections doesn't seem to be a promising idea.

Besides adding dependencies, what's the great benefit? We can provide a config file for setting default options or something anyway.

**Comment by yarikoptic** [comment]
On Wed, 16 Sep 2015, bpoldrack wrote:

> I agree, ignoring sections doesn't seem to be a promising idea.

> Besides adding dependencies, what's the great benefit? We can provide a config
> file for setting default options or something anyway.

just sounds like something we could avoid implementing ourselves ;)

**Comment by hanke** [comment]
as they have no support for sections, let's no do this at this point. Closing....
