### ISSUE TITLE
Add a list of extractors to the "Aggregate metadata for dataset ..." message

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2146]
#### What is the problem?
no problem but it would be very handy -- this way I could possibly catch datasets without any/inappropriate extractors configured etc

Something like
```
Aggregate metadata for dataset /mnt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053: bids, nifti1
```
should suffice, or they could even go before the path since path is so long and not rel to curdir

**Comment by mih** [comment]
#2157 will bring this:

```
% datalad aggregate-metadata -r
[INFO   ] Aggregate metadata for dataset /tmp/lit 
[INFO   ] Engage metadata extractors: ['datalad_core', 'xmp'] 
[INFO   ] Update aggregate metadata in dataset at: /tmp/lit 
aggregate_metadata(ok): /tmp/lit (dataset)                                                                                   
```
Doing it in one log message would require substantial RF to make info available in one place -- seems to have no benefit.

**Comment by yarikoptic** [comment]
are engaged metadata extractors yielded back somehow in that record (if I change output to json*)?

**Comment by mih** [comment]
They do not necessarily yield something. You wanted a list of things that run, to be able to spot if something is missing. If you want to see what was produced you can look at the keys in the metadata structure. There will be one for each extractor that produced something, and where the result did not get filtered as a consequence of one of your other settings.

**Comment by yarikoptic** [comment]
I meant aggregate-metadata command, I assumed it is a generator as everything in your flashy new API

**Comment by mih** [comment]
Ah, in the result record of `aggregate-metadata`. No, there are not in there. Might indeed be a useful bit of info. I will have to look into this.

**Comment by mih** [comment]
What about this?

```
% datalad --dbg -f json_pp aggregate-metadata
[INFO   ] Aggregate metadata for dataset /tmp/lit 
[INFO   ] Engage metadata extractors: ['datalad_core', 'xmp'] 
[INFO   ] Update aggregate metadata in dataset at: /tmp/lit 
{                                                                                                       
  "action": "aggregate_metadata", 
  "content_info": "/tmp/lit/.datalad/metadata/objects/0a/cn-0a893378f6e3a8bbe7ab30a0a10c81.xz", 
  "dataset_info": "/tmp/lit/.datalad/metadata/objects/0a/ds-0a893378f6e3a8bbe7ab30a0a10c81", 
  "extractors": [
    "datalad_core", 
    "xmp"
  ], 
  "id": "b29ce4ca-0e6d-11e8-9628-f0d5bf7b5561", 
  "path": "/tmp/lit", 
  "refcommit": "fe1da1aaaafe5ded64eb091f6e64717256c6589f", 
  "status": "ok", 
  "type": "dataset"
}
```

**Comment by yarikoptic** [comment]
looks nice, so I could hackup my output format then I guess to see which extractors for which path were used, cool

**Comment by mih** [comment]
I pushed one more commit that adds the version of datalad that was used to aggregate the metadata for a particular dataset with the listed extractors. That is how much I love you!

**Comment by mih** [comment]
```
% datalad -f '{path}: {datalad_version} {extractors}' metadata --get-aggregates
/tmp/lit: 0.9.1.dev1 [u'datalad_core', u'xmp']

```

**Comment by yarikoptic** [comment]
oh, you are already in the mood for tomorrow. Glad to see that our coding creates a positive vibe benefiting those who are dear to us ;)

hugs

now we just need to reincarnate it reporting `git describe` output and see how to fight whatever caused me to disable it
