### ISSUE TITLE
open_r_encdetect -- 1kB might not be enough!

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2147]
#### What is the problem?
`open_r_encdetect` helper promises to guess the encoding of the file by first reading first 1kB and guessing the type from it, and then reading using `io.open` while providing encoding

IMHO it is principally incorrect -- unicode character might happen to come anywhere in the text file (happens for 53) even in the last position in the text.  

overall `io` module afaik is more of a plumbing than user-oriented.  I do not see why we should not just read the entire file in bytes, and then guess encoding on the entirety of the content.  I thought even to some degree that is what stock `open` is intended to do and does in this particular use case just fine:
```
*(Pdb) print type(open(README_fname).read())
<type 'unicode'>
```
so what problem this helper was intended to solve?

**Comment by yarikoptic** [comment]
ok, not that fast @yarikoptic . apparently pdb session somehow is different:
```shell
$> python -c 'c=open("README").read(); print(type(c), len(c))'
(<type 'str'>, 2472)
$> python -c 'c=open("README").read().decode(); print(type(c), len(c))' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1188: ordinal not in range(128)
(dev)3 10221 ->1 [1].....................................:Mon 12 Feb 2018 11:25:59 AM EST:.
(git)smaug:\u2026nt/btrfs/datasets-meta6-1-redo1/datalad/crawl/openfmri/ds000053[master]
$> python -c 'c=open("README").read().decode("utf-8"); print(type(c), len(c))'
(<type 'unicode'>, 2467)
```
but we have a helper which we could use already (and that one might need to absorb the magical sensing of `open_r_encdetect`):
```shell
$> python -c 'from datalad.utils import assure_unicode; c=open("README").read(); c=assure_unicode(c); print(type(c), len(c))'
(<type 'unicode'>, 2467)
```
so I will for now fix by using that one instead if no big objections

**Comment by mih** [comment]
It sounds OK to me.
