### ISSUE TITLE
Location for subdatasets with computational environments

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2148]
In some secret plan we determined a location for subdataset(s) with container(s). In principle such location is arbitrary, but I nevertheless want to propose

`.datalad/singularity/<nameofcontainer>`

A use case for such a default location would be a convenience option to `datalad run` that executes a particular command in a specified container (and maybe even a particular version of a given type of container).

What do you think @bpoldrack @yarikoptic ?

**Comment by yarikoptic** [comment]
Why do hide them under `.datalad/`.  I would recommend that in our YODA principles we suggest `environments/` (or `envs/`) with `singularity/` under so people could find them and not really dependent on `.datalad/`

**Comment by mih** [comment]
That is one perspective. The other is: "why pollute my beautiful dataset layout with your stinking conventions" ;-)

**Comment by yarikoptic** [comment]
... so we pollute it so noone could see that sh.t?  Overall I guess it would depend on the usecase etc and should be configurable probably.

**Comment by mih** [comment]
Good point!
