### ISSUE TITLE
Generalize extractors into larger domains? meta-extractors?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2166]
#### What is the problem?

with autodetection of metadata types disabled imho it would be somewhat silly to generate and require specification of an extractor for each filetype in neuroimaging. So I wondered if nifti1 could/should be generalized into a more generic `neuroimaging_files`  or alike, which would provide extractors for other relevant datatypes ('.mgz', '.HEAD/.BRIK', etc) some of which are already supported by nibabel -- so it might be just a matter of a few additional dictionaries to define term mappins.

We could actually may be make 'meta-extractors' which provide such aggregation of different domain-specific ones.   I would just hate to go through each dataset and see which file types are in there... with every crawl/commit.  So I could just specify a set of domains for which to enable extractors for, in case they find some relevant file.

**Comment by mih** [comment]
I see no technical reason why a `neuroimaging_files` extractor could not call a `nifti1` extractor internally. From a user/semantics POV things will change though. The metadata is structured per extractor. In the above case `nifti1` would vanish as a namespace, and with it its semantics. Now it would be `neuroimaging_files` responsibility to provide "a few additional dictionaries to define term mapping" (i.e. provide a proper `@context`). I think I have seen people try and wither in the processing of producing those mappings ;-)

**Comment by mih** [comment]
Please see #2326 for a related RF.

**Comment by mih** [comment]
https://github.com/datalad/datalad-revolution/pull/84 let's extractor do anything they want, including calling other extractors internally.

**Comment by yarikoptic** [comment]
do not thing it is fixed-in-anywhere but the idea did not formalize properly anyways, so RiP
