### ISSUE TITLE
subdatasets --recursive behavior is inconsistent when some submodules aren't initialized

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2184]
#### What is the problem?
Originally discovered while using `datalad diff` in https://github.com/datalad/datalad/issues/2171 and later troubleshooted to just having those submodules which aren't recursed into being non-initialized.  The issue is that if I do specify the `--recursion-limit` then I would get listing of also non-initialized submodules.  I think that behavior should not differ

NB I still think that the issue was not merely due to non-initialized submodules, but since could not reproduce, I will forget about it for now.

**Comment by mih** [comment]
In master now.
