### ISSUE TITLE
How .datalad/metadata/dataset.json to be born?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2189]
#### What is the problem?
Code for datalad_core extractor cares about that file somehow but after aggregating all the metadata in all the datasets I see no such thing.  Moreover apparently code which loads it if it exists, never is executed by the tests:  see [coverage](https://codecov.io/gh/datalad/datalad/pull/2188/src/datalad/metadata/extractors/datalad_core.py#L27)
So I wondered how it should come about and what it is for?

**Comment by mih** [comment]
This was the file that `metadata` used to populate when setting dataset-global metadata. This functionality no longer exists. Not sure how to move forward for now. Ultimately we would likely want support for such a thing. But maybe not for now, and instead rely on any of the other extractors?

**Comment by mih** [comment]
Please see #2326 for a related RF.

**Comment by mih** [comment]
Closing "question"-type issue with a response, and no further activity.
