### ISSUE TITLE
Best way to mock patch config variable?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2195]
#### What is the problem?
@mih - how do you do it?  might be nice to have `patch_config` cm helper

**Comment by mih** [comment]
Thanks to you, the tests run in a dedicated HOME. You should be able to alter the actual config in a test run, without having to mock it. Before you made this change, i failed to come uo with another solution for this.

**Comment by yarikoptic** [comment]
nah, that doesn't address the use case (unittest while changing quickly/temporarily a config setting). ok - will push as a part of #2190

**Comment by yarikoptic** [comment]
let's consider it fixed by #2190
