### ISSUE TITLE
(Allow to) fail on result rendering error

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#2201]
#### What is the problem?
In context of #2144 I ran into this one:
```
datalad '--output-format={metadata[dicom][Series][0][PatientID]}' metadata -d /home/mih/scratch/cbbstest/3t/tmp.487whULJ5C/dicoms --reporton=datasets
[WARNING] Result rendering failed for: {'status': 'ok', 'refcommit': u'51024730e7122f5b06e068319dbd28a9d3cc6e7d', 'dsid': u'f4ee5912-13e5-11e8-9c26-a0369fb55db0', 'action': 'metadata', 'path': '/home/mih/scratch/cbbstest/3t/tmp.487whULJ5C/dicoms', 'type': 'dataset', 'refds': '/home/mih/scratch/cbbstest/3t/tmp.487whULJ5C/dicoms', 'metadata': {u'@context': {u'@vocab': u'http://docs.datalad.org/schema_v2.0.json'}, u'datalad_core': {u'@id': u'f4ee5912-13e5-11e8-9c26-a0369fb55db0'}, u'dicom': {u'@context': {u'dicom': {u'type': u'http://purl.org/dc/dcam/VocabularyEncodingScheme', u'@id': u'http://semantic-dicom.org/dcm#', u'description': u'DICOM vocabulary (seemingly incomplete)'}}}}} [u'Series' [base.py:<lambda>:413]]
```

This exited zero. Since doc for `--on-failure` reads it considers failures based on result status, that somehow does make sense, but failures of result renderer need to be similarly accessible.

**Comment by mih** [comment]
I think we moved in the opposite direction suggested here. We allow the command not to die when there are problems in the results (missing properties), or issues with a particular renderer (unexpected result structure, etc.).

**Comment by yarikoptic** [comment]
Marked as DX. I think it would be nice to have some more granular setup for allowing to fail and end up at the point of failure instead of just propagating some result records marked as errors.  Probably the same here.

**Comment by mih** [comment]
I am going to close this now. Several years have passed and there is now proposal on how to make this happen, and why.

The current behavior is

```
% datalad -f '{funky}' status
N/A
```

this is CLI-specific. The equivalent in Python would be:

```
d = datalad.status(result_renderer=lambda x, **kwargs: print(x['funky']))
[WARNING] Result rendering failed for: {'type': 'file', 'gitshasum': '59157cbb56d57fbc0404856778418fdafe2787e5', 'bytesize': 125, 'prev_gitshasum': '59157cbb56d57fbc0404856778418fdafe2787e5', 'state': 'clean', 'path': '/tmp/some/.datalad/.gitattributes', 'parentds': '/tmp/some', 'status': 'ok', 'refds': '/tmp/some', 'action': 'status'} [KeyError('funky')] 
```

Importantly, a uniform desire to fail in both cases is questionable, because in Python the results are returned just fine, while the result rendering is more like an anecdote.

As for

> I think it would be nice to have some more granular setup for allowing to fail and end up at the point of failure

I consider this an entirely different issue. It comes up frequently, but I am not aware of a proposal how to implement it. Any implementation would certainly not be limited to result rendering, I think.
