### ISSUE TITLE
curl call in `annex addurl` does not work with gvfs

### ISSUE THREAD

**Issue by cni-md** [datalad/datalad#2208]
#### What is the problem?
singularity run ../import/cbbs-imaging.simg import  does not work with gvfs 

#### What steps will reproduce the problem?
singularity run ../import/cbbs-imaging.simg import /run/user/1002/gvfs/smb-share:server=linsamba,share=mri-data2/probanden3T/tarfiles/klein.20180214.104817.37.tar.gz

+ [INFO   ] Creating a new annex repo at /home/jstadler/LIN/Projekte/datalad/3T/tmp.kjcDsNHhiR/dicoms 
create(ok): /home/jstadler/LIN/Projekte/datalad/3T/tmp.kjcDsNHhiR/dicoms (dataset)                    
+ import_dicom_tarball /run/user/1002/gvfs/smb-share:server=linsamba,share=mri-data2/probanden3T/tarfiles/klein.20180214.104817.37.tar.gz klein.20180214.104817.37.tar.gz
+ local path=/run/user/1002/gvfs/smb-share:server=linsamba,share=mri-data2/probanden3T/tarfiles/klein.20180214.104817.37.tar.gz
+ local filename=klein.20180214.104817.37.tar.gz
+ git checkout -b incoming
Switched to a new branch 'incoming'
+ git annex initremote datalad-archives encryption=none type=external autoenable=true externaltype=datalad-archives uuid=c04eb54b-4b4e-5755-8436-866b043170fa
initremote datalad-archives ok
(recording state in git...)
+ git annex addurl file:///run/user/1002/gvfs/smb-share:server=linsamba,share=mri-data2/probanden3T/tarfiles/klein.20180214.104817.37.tar.gz --file klein.20180214.104817.37.tar.gz
addurl file:///run/user/1002/gvfs/smb-share:server=linsamba,share=mri-data2/probanden3T/tarfiles/klein.20180214.104817.37.tar.gz 
curl: (37) Couldn't open file /run/user/1002/gvfs/smb-share:server=linsamba,share=mri-data2/probanden3T/tarfiles/klein.20180214.104817.37.tar.gz
failed
git-annex: addurl: 1 failed

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad plugin wtf`)?
datalad 0.9.1.dev1
System
======
OS          : posix Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04)
Distribution: debian/9.3

Environment
===========
GIT_PYTHON_GIT_EXECUTABLE: /usr/lib/git-annex.linux/git
GIT_PROMPT_EXECUTABLE: python

Externals
=========
appdirs=1.4.3
boto=2.48.0
cmd:annex=6.20171211+gitgba511f4de-1~ndall+1
cmd:git=2.11.0
cmd:system-git=2.11.0
cmd:system-ssh=7.4p1
git=2.1.8
gitdb=2.0.3
humanize=0.5.1
iso8601=0.1.12
msgpack=0.5.4
requests=2.12.4
six=1.10.0
tqdm=4.19.5
wrapt=1.10.11

#### Have you had any success using DataLad before? (Sometimes we get tired of reading bug reports all day and a lil' positive end note does wonders)
YES ;) 
+ cp /run/user/1002/gvfs/smb-share:server=linsamba,share=mri-data2/probanden3T/tarfiles/klein.20180214.104817.37.tar.gz  ~/temp
+ singularity run ../import/cbbs-imaging.simg import  /home/jstadler/temp/klein.20180214.104817.37.tar.gz 
is working, but I do not want to copy 10TB first

**Comment by mih** [comment]
Thanks for reporting!

@datalad/developers For context: the top-level code that is executed here is a datalad-based shell script that runs in a container (datalad on current master revision). The incompatibility with a gvfs mount is a general datalad/annex issue, though.

**Comment by mih** [comment]
@bpoldrack could it be that this has nothing to do with datalad, but it is simply singularity that did not bind-mount (if it can) the gvfs mount?

**Comment by bpoldrack** [comment]
I guess, that's at least a missing pre-condition for this to work, yes!
Gimme a second, I'll try.

**Comment by bpoldrack** [comment]
Yes. For me it works with gvfs, if a pass the respective mount point.

@cni-md Please try 
```
singularity run --bind /run/user/1002 ~/cbbs_imaging/conv-container/cbbs-imaging.simg import /run/user/1002/gvfs/.....
```
instead. Singularity doesn't automatically mount the entire FS for the container. Apart from the user's HOME and CWD, we need to pass needed mount points via `--bind`.
It would probably also work to just mount `/run/user` (no permission issue - you are the same user inside as outside), or to be even more specific (like `/run/user/1002/gvfs`)

**Comment by cni-md** [comment]
With --bind /run/user/1002 it is working now. Thanks a lot
