### ISSUE TITLE
Installation docs need work

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2209]
Relaying a report from @cni-md:

Does it only work as root?

```
$ python3 setup.py install --user

Writing /tmp/easy_install-z56yz1o4/patool-1.12/setup.cfg
Running patool-1.12/setup.py -q bdist_egg --dist-dir
/tmp/easy_install-z56yz1o4/patool-1.12/egg-dist-tmp-cw11s954
error: Setup script exited with error: SandboxViolation:
open('/usr/local/lib/python3.5/dist-packages/_patool_configdata.py', 'w') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

**Comment by yarikoptic** [comment]
FWIW
I do not see any relevant explicit write attempt in patool.
It installs just fine into virtualenv:
```
$> venv/bin/pip install patool
Collecting patool
  Using cached patool-1.12-py2.py3-none-any.whl
Installing collected packages: patool
Successfully installed patool-1.12
```
I am trying to avoid `--user` mode and direct invocation of setup.py install as much as I could afford (actually always)

**Comment by cni-md** [comment]
As root without --user it does not work either. The same problems occurs with python3-openssl, python3-duecredit, libffi-dev, liblzma-dev

**Comment by yarikoptic** [comment]
Did you try pip install, ideally within a virtualenv? Then you could just alias/symlink to that datalad binary installed within virtualenv and it would use modules installed within virtualenv

**Comment by cni-md** [comment]
No I didn't. It is running now, and I will not touch it anymore. I had a long fight with our firewall and guesing the right git proxy settings. :)

**Comment by bpoldrack** [comment]
Despite not needed for @cni-md anymore, that's actually a nice trick to remember, @yarikoptic.
We should put that somewhere as a fallback solution.

**Comment by mih** [comment]
@cni-md At http://kumo.ovgu.de/~mih/datalad-master_180228.simg you can find a singularity image (300M) that has a full installation of datalad with all bells and whistles. The image itself (when executable) could be used as a drop-in replacement of a manual datalad installation.

The recipe used to build this image is in #2242

**Comment by mih** [comment]
And now also: `singularity pull shub://datalad/datalad:fullmaster`

**Comment by mih** [comment]
Done now.
