### ISSUE TITLE
Aggregate metadata (dicom) stumbles upon some unicode issue without traceback

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#2210]
#### What is the problem?
As reported by @cni-md, `aggregate-metadata` fails on a DICOM dataset with an unicode related issue. Reproduced it with more detailed logging. Sadly, we don't get any useful traceback by the logs - it throws up all the way to main.py before it gets logged.

```
[INFO   ] datalad:8>main:359>interface.base:432>utils:408,475>aggregate:690,198>metadata:411  Engage metadata extractors: ['datalad_core', 'dicom']
[INFO   ] datalad:8>main:359>interface.base:432>utils:408,475>aggregate:690,198>metadata:437>dicom:61  Attempting to extract DICOM metadata from 11396 files
[DEBUG  ] datalad:8>main:359>interface.base:432>utils:408,475>aggregate:690,236>dataset:437>utils:322  Determined class of decorated function: <class 'datalad.interface.unlock.Unlock'>
[DEBUG  ] ...>utils:475>aggregate:690,236>dataset:437>utils:463,451,408,475>unlock:91>utils:322  Determined class of decorated function: <class 'datalad.interface.annotate_paths.AnnotatePaths'>
[DEBUG  ] ...>interface.base:432>utils:408,475>aggregate:690,236>dataset:437>utils:463,451,408,505  not controlled by annex, nothing to unlock [unlock(/home/bpoldrack/scratch/test2/utf8-session/dicoms/.datalad/metadata/objects/d8/ds-c87983928f4268a24922883d65be8c)]
[ERROR  ] datalad:8>main:389  'utf8' codec can't decode byte 0xb0 in position 0: invalid start byte [utf_8.py:decode:16] (UnicodeDecodeError)
```

However, I ran it via python API (PY2) and got:

```
[INFO   ] Attempting to extract DICOM metadata from 11396 files
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/datalad/distribution/dataset.py", line 437, in apply_func
    return f(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/datalad/interface/utils.py", line 463, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/datalad/interface/utils.py", line 451, in return_func
    results = list(results)
  File "/usr/local/lib/python2.7/dist-packages/datalad/interface/utils.py", line 408, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/usr/local/lib/python2.7/dist-packages/datalad/interface/utils.py", line 475, in _process_results
    for res in results:
  File "/usr/local/lib/python2.7/dist-packages/datalad/metadata/aggregate.py", line 690, in __call__
    to_save)
  File "/usr/local/lib/python2.7/dist-packages/datalad/metadata/aggregate.py", line 243, in _extract_metadata
    store(meta, objpath)
  File "/usr/local/lib/python2.7/dist-packages/datalad/support/json_py.py", line 53, in dump
    return dump2fileobj(obj, f)
  File "/usr/local/lib/python2.7/dist-packages/datalad/support/json_py.py", line 60, in dump2fileobj
    **json_dump_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 278, in dump
    for chunk in iterable:
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 678, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 635, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 635, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 515, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 635, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 482, in _iterencode_list
    yield buf + _encoder(value)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 54, in encode_basestring
    s = s.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
```

To be continued ...

**Comment by bpoldrack** [comment]
So, the issue is happening when the DICOM metadata is dumped into a file.
The piece that `utf_8_decode` is choking on, is:

```
(Pdb) d
> /usr/local/lib/python2.7/dist-packages/simplejson/__init__.py(278)dump()
-> for chunk in iterable:
(Pdb) chunk
u',\n"5.3.0.3"'
```
Which looks weird indeed. Judging by its value it is coming from DICOM header field "SoftwareVersions". The aggregated metadata contains the following for that key:

```
(Pdb) [x['SoftwareVersions'] for x in obj['dicom']['Series']]
[['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], '5.3.0', ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3'], ['5.3.0', '5.3.0.3', 'G1619@tzres.dll,-322']]
```
ATM that's confusing to me, since the last entry is the only nonsense I notice, but doesn't appear to contain the `u',\n"5.3.0.3"'` in question.

**Comment by bpoldrack** [comment]
Hold on.

On the deepest level, it's
```
> /usr/lib/python2.7/encodings/utf_8.py(16)decode()
-> return codecs.utf_8_decode(input, errors, True)
(Pdb) input
'\xb0G\x841\x9f6\x841\xa49@tzres.dll,-322'
```
(as one would expect from the values above).

So, I'm posting too fast ... ;-)

**Comment by bpoldrack** [comment]
@mih ,  @cni-md, do you have any idea how something like "G1619@tzres.dll,-322" (regardless of encoding) could end up in a DICOM header as "SoftwareVersion"?

**Comment by cni-md** [comment]
grep "tzres.dll" *
Übereinstimmungen in Binärdatei PSg.1.3.46.670589.11.38317.5.0.7584.2018021408330042001.1
Philips MR Imaging DD 005
I have no clue what are the PSg.* files are used for. Real images starts with MR.*

gdcmdump PSg.... 
(0018,1030) LO [DEFAULT PRESENTATION STATE]                       # 26,1 Protocol Name

No repetition time, no Echo time.... strange file

**Comment by bpoldrack** [comment]
Hm Quick search brought me to http://compgroups.net/comp.protocols.dicom/what-is-psg-file/2211546

The "we" in the answer refers to OFFIS, I guess, which - I conclude - is this one http://dicom.offis.de/software.php.en .
Since I'm not exactly familiar with the details of scanning and what part of the software stack produces output that we really want to see in the dicom dataset, I don't feel qualified to judge, whether or not this means, we can simply ignore those files.

However, while this might be a solution in your case, guarding against that kind of sh** probably is a more general issue.

**Comment by bpoldrack** [comment]
BTW: Not exactly surprising it works in python 3.

In python 2 I didn't find a way to deal with that kind of string yet, except using `decode(errors='ignore')`, which prob. would be fine in that case. However, that call comes from within `simplejson.dump`, so we can't pass that one in there. :-/

**Comment by cni-md** [comment]
Ok, the PSg file strores only the display parameters on the Philips Scanner. If you reload the the dataset on the scanner you get the same display options (contrast settings, zoom,...) as before. 

I am wondering that we got this entry only once. We have 8 runs (localizer, 3x EPI, 3x DTI, fieldmap) but I use an automatic QC pipeline from Philips and this pipeline tend to crash after run 5. I assume this shitty entry is an result of this crash?!
I will check the other QA Scans.

**Comment by mih** [comment]
I believe this was fixed.

Please see #2326 for a related RF.
