### ISSUE TITLE
export_to_figshare's annex check is always true

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2213]
The export_to_figshare plugin seems to make the same false assumption that I made about boolean flags in the plugin interface.

```python
def dlplugin(dataset, filename=None,
             missing_content='error',
             annex=True,
             # project_id=None,  # TODO: support working with projects and articles within them
             article_id=None
             ):
    """[...]
    annex : bool, optional
      If True generated .zip file would be added to annex, and all files
      would get registered in git-annex to be available from such a tarball. Also
      upon upload we will register for that archive to be a possible source for it
      in annex.
```

At least as a user, I'd assume that I could then pass `annex=False`.  This won't work, however, because the string 'False' is used as the value.  As a result, the `if annex:` check always evaluates to true.

As a simple example of the behavior

```python
def dlplugin(dataset, false_flag=False, true_flag=True):
    print("false_flag: {!r}".format(false_flag))
    print("true_flag: {!r}".format(true_flag))
```

Unsupplied defaults are OK:

```
$ datalad plugin bool
false_flag: False
true_flag: True
```

Non-defaults are strings:

```
$ datalad plugin bool false_flag=True true_flag=False
false_flag: 'True'
true_flag: 'False'
```

**Comment by kyleam** [comment]
I suppose my title "export_to_figshare's annex check is always true" isn't true.  It could be false if `annex` is set to an empty string.

**Comment by mih** [comment]
Thanks for pointing this out. One more reason to look into #2085

**Comment by mih** [comment]
I guess the minimal action (despite fixing this particular bug) is to make clear that plugins cannot do automatic type conversion, because they lack any information about possible types.

**Comment by mih** [comment]
Anybody interested in getting this resolved should answer the last open question in #2085. Once that is done, we should convert the plugins to commands and this issue here evaporates.
