### ISSUE TITLE
Singularity recipe for DataLad?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2221]
Does any of you already have one? It would be nice to keep it lean, no useless X cruft etc. But at the same time all functionality...

**Comment by yarikoptic** [comment]
Not a crafted one yet... Would be easy to do but If you really want a minimal one, it could be made with reprozip probably. Otherwise better not to install  recommends since you end up again with to much

**Comment by mih** [comment]
I will look into reprozip.

By 'recommends' you mean Debian recommends? I cannot use the Debian package ;-)

**Comment by yarikoptic** [comment]
Yes I meant Debian package
You could install and then uninstall datalad packages to fetch in all critical depends to avoid listing then manually.
You btw could tag/release 0.10a and produce Debian package (just do it in debian-devel branch off debian) for Debian-devel of NeuroDebian anytime btw,

**Comment by mih** [comment]
Recipe is coming in #2242
