### ISSUE TITLE
`remove` should remove metadata?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2228]
Boils down to a conceptual decision. If we remove a direct subdataset, should `remove` remove the aggregate metadata for it too. if so, then any remove requires a traversal upwards to adjust superdataset content beyond the `save` of the subdataset change (which it is already recording).

If we do it for datasets, what about files? If we do it for files, we would have to re-aggregate on remove of a single file. Which changes the state of the dataset, hence flags reaggregation in any superdataset.

I don't think this would be wise....

**Comment by yarikoptic** [comment]
I think it is the same as with any other operation which changes files (add/commit/etc) -- the operation might invalidate metadata (including upstairs upon "save' being called in them as well to reflect new state of the subdataset) which was for the previous state/version. So in my opinion remove is not much different.
Which boils again to that other discussion on incremental update of the metadata to have it anyhow scalable.

**Comment by mih** [comment]
It some sense it is similar, but the change is decremental, not incremental.

**Comment by yarikoptic** [comment]
so to some degree of lesser detrimental effect -- if you found something which is no longer there, you immediately know that your search index/metadata is outdated.  If you found something which might not longer be valid, and you don't know that for sure -- that is a greater evil imho
