### ISSUE TITLE
TODO: Make initial search run logging less obnoxious and more informative

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2261]
#### What is the problem?
```shell
$> datalad search haxby
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/datalad-meta6-4/.datalad/metadata/objects/35/ds-a047ea14d57bbe48d73c87917e4951 
...
```
with rapidly blinking (displayed and quickly disappearing) download progress bar.
This is still going on already for a while without any warning that it is to happen (and why) and for how long would it be going on.

#### Expected
- Similar to what we had - some message alerting user that we will need to build an index and now might need to fetch additional files
- Avoid all the automagicIO messages with blinking progressbars -- ideally there should be one progressbar indicating progress. Don't we know which files we would need to fetch?

as soon as I typed it -- my initial query finally finished!
```
datalad search haxby  77.75s user 31.71s system 52% cpu 3:28.45 total
```
output was lost somewhere in the hundreds of AutomagicIO messages:  that single
```
search(ok): /home/yoh/datalad-meta6-4/labs/haxby (dataset)
```
was preceded by some and followed by even more ;)

**Comment by mih** [comment]
Some time back someone uograded the loglevel for automagic io. Downgrade again?

**Comment by mih** [comment]
If that is using master, I am surprised by the runtime. Unless the new dataset version has substantially more heavy metadata.

**Comment by mih** [comment]
> Similar to what we had - some message alerting user that we will need to build an index

Your search didn't build any index.

**Comment by mih** [comment]
re blinking progressbar: ATM we use automagic IO which behaves exactly this way. We open one file, and automagic IO unconditionally(?) creates a progress bar. So if anything needs to change then the change should be made here (too).

We could certainly stop using automagic IO and retrieve all files references as current metadata objects in one go. However, using automagic IO at least points out the issues that it has. This is the one and only place where we do this.

**Comment by mih** [comment]
OK, whoever wrote AutomagicIO... #2255 has abandoned it -- caused to many complaints...

**Comment by mih** [comment]
Current state of #2255 now gives one single progressbar for obtaining all needed metadata blobs. Makes it not a single second faster, but less "flood"-like with an idea on how many files and how heavy they are:
```
[INFO   ] Actually getting 489 files 
Total (115 ok out of 489) 38%|██████████████████████                                    | 3.22M/8.47M [02:49<51:29, 1.70KB/s]
```

Sidenote: the "actually getting" is an old-timer, i know, but it still sounds as if datalad is surprised by itself. In this context, and quite a few others it makes no sense to log this, with this wording, and at this level.

In my test case above just shy of 500 files have to be obtained via SSH, and it seems that they are obtained one by one, strictly serial,. Not sure if there is a dedicated authentication run for each of them. There is about one second delay between two files.

If you want to try:

```
% datalad install -s smaug:/mnt/btrfs/datasets-meta6-4/datalad/crawl hotnewshit
% datalad search haxby
datalad search haxby  36.74s user 12.24s system 8% cpu 9:46.15 total
```

(nine minutes waiting for IO)

**Comment by mih** [comment]
Closing, as the core issue has been dealt with. We still have have #2262 as a general OMG-this-is-bad outburst ;-)
