### ISSUE TITLE
`^` to indicate the topmost dataset is broken in zsh

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2265]
ZSH is using this symbol for something else and is expanding it to a list of some file names (didn't check the details). While bash is fine, and it could be escaped in zsh, we probably want something that just works.

Suggestions?

**Comment by yarikoptic** [comment]
just specify without space before? i.e. `-d^` instead of `-d ^` ?

**Comment by mih** [comment]
You are absolutely right. And upon a more careful look this is exactly what the docs were trying to tell me.
