### ISSUE TITLE
Use case docs need overhaul

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2266]
Example: http://docs.datalad.org/en/latest/generated/examples/3rdparty_analysis_workflow.html

Screams for use of `run/rerun` and `subdatasets`, but is doing things as if we would still have none of those helpers.

**Comment by mih** [comment]
There is now a better home for this kind of documentation: http://handbook.datalad.org/en/latest/#use-cases

ping @adswa

**Comment by adswa** [comment]
This use case is implicitly covered in the sections on [collaboration in the handbook](http://handbook.datalad.org/en/latest/basics/101-116-sharelocal.html) and many others are on the todo-list (see https://github.com/datalad-handbook/book/issues/36).

But I very much like the brevity of the two use cases in the docs, and I could overhaul them to use the helpers mentioned by @mih above and put them straight into the use-case section of the handbook (which is very empty anyway so far)

**Comment by mih** [comment]
@adswa That would be great, if it doesn't end up being just a duplicate of the rest of the book. But maybe it would even be useful to officially present it as a summary of the basics on collaboration. Some people might prefer that as an entry point to get a quick idea.

**Comment by mih** [comment]
When https://github.com/datalad-handbook/book/pull/134 is merged, we should simply remove the use case docs from the datalad docs, but likely keep running them in the tests.

**Comment by mih** [comment]
This is done now.
