### ISSUE TITLE
run --shell=...

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2275]
#### What is the problem?

As we have just discovered with @kyleam while torturing (Well, enjoying) the `run` command, by default the POSIX compliant `/bin/sh` is used, forbidding various rudimentary bashisms such as `${var//from/to}`.  

@kyleam dropped an idea to rely on using `$SHELL` env variable to the user could get consistent operation within datalad as in his current shell.  But that might complicate re-execution so not sure...

**Comment by mih** [comment]
I think it is very useful to record/use the parent shell. I am not so sure that a dedicated `--shell` would see much use. The primary pattern would be to specify the shell that one uses anyways, and then we have the exact same "complicate re-execution" situation we already have.

**Comment by mih** [comment]
FTR: the idea of a `run --interactive` from #2158 is somewhat related, as a solution for this issue could also qualify as a solution for that case.

**Comment by yarikoptic** [comment]
Few bullet points
- parent shell is only useful if it is the shell used within the `run`.  So I think we should record what shell was **used** if not a `/bin/sh`.  
- as for `--shell` -- I am using `zsh` but really what I `run` is typically `/bin/bash` so could be ran on machines even without `zsh` which would be forced upon for `rerun` if I record `zsh`.
- we might actually want to make `run` to allow for non-shell execution (although I do not think I have a handy use-case ATM, besides pointing to all the warnings of security danger of shell=True ;))
- note that both `bash` and `zsh` known to change through time, so we ideally should also then record their versions, but that places us into all that tracing/provenance collection domain which we might want to avoid for now.

**Comment by kyleam** [comment]
> besides pointing to all the warnings of security danger of shell=True

I don't  understand the concern.  Isn't the main worry just shell injection?  To use the [example from the subprocess docs][0]:

```python
>>> from subprocess import call
>>> filename = input("What file would you like to display?\n")
What file would you like to display?
non_existent; rm -rf / #
>>> call("cat " + filename, shell=True) # Uh-oh. This will end badly...
```

Sure, that's bad because the intention is to just cat a file.  But in our case, we're saying "we're running what you're giving us.  If you want to do something stupid, we're not going to stop you anymore than your shell would."  On other words, if the user is specifying the whole command, there can be no shell injection.  Am I missing something?

[0]: https://docs.python.org/2/library/subprocess.html#frequently-used-arguments

**Comment by bpoldrack** [comment]
From my point of view, doing this right ultimately leads to treating the shell like a container aka computational environment, which you then need to reference properly, provide version, etc.
Only, to then come up with convenience switches and (changing) default values in order to figure out, how to make that beast useable in 90% of the cases.

I'd honestly just go for standard shell (`/bin/sh` for POSIX). If you need sth special - call it! After all it's about reproducibility, so it's okay to require people to specify things.

Re security:
What @kyleam says.

**Comment by yarikoptic** [comment]
> If you need sth special - call it!

That is where `--no-shell` or `--shell=` should come in then since otherwise it would be a mess with all the escaping if I need to `run /bin/bash -c "cmd"` which in turn is then converted to `/bin/sh -c "/bin/bash -c \"...` internally if we cannot forbid having no shell.
But indeed may be then it should be `--runner` or something like that, not `--shell`?

**Comment by bpoldrack** [comment]
Well, the escaping mess is a valid point, although I guess, that in most "real" cases you'd rather simply call a script which in return specifies the shell to use than having more or less complex commands within the call to `datalad-run`.

I don't  entirely get the idea of  `--runner`. What exactly would you pass in? And how would you combine it with the needs datalad itself has for the Runner, so we use the correct git/annex for the calls datalad run actually is for? Just asking - not sure, whether that's actually easy.

**Comment by yarikoptic** [comment]
not sure... I know that I am so special but here you go -- a dump of the commands I have (tried or succeded) to `datalad run` recently:
```shell
datalad -l 2 run "find -iname *..nii.gz | while read f; do git mv \$f \${f//../.}; done"
datalad -l 2 run "find -iname *..nii.gz | while read f; do nf=\$(echo \$f | sed -e 's,\.\.,.,g' ); echo git mv \$f \$nf; done"
datalad -l 2 run "find -iname *..nii.gz | while read f; do nf=\$(echo \$f | sed -e 's,\.\.,.,g' ); git mv \$f \$nf; done"
datalad run "awk '{print \$2;}' _stats/content-counts | while read f; do find -lname $f; done | sort > _stats/content-duplicates"
datalad run "awk '{print \$2;}' _stats/content-counts | while read f; do find -lname \$f; done | sort > _stats/content-duplicates"
datalad run "awk '{print \$2;}' _stats/content-counts | while read f; do find -lname \$f; done | sort  | xargs md5sum > _stats/content-duplicates"
datalad run "echo 123 > 123"
datalad run "echo 123 | tr 1 2  > 123"
datalad run "echo 123 | tr 1 2  > 1234"
datalad run 'find -iname *..nii.gz | while read f; do git mv $f ${f//../.}; done'
datalad run 'find -iname *..nii.gz | while read f; do git mv \$f \${f//../.}; done'
datalad run "find -iname *..nii.gz | while read f; do git mv \$f \${f//../.}; done"
datalad run "mkdir -p _stats; find -type l -ls | awk '{print $13;}' | sort  > _stats/content-counts"
datalad run 'mkdir -p _stats; find -type l -ls | awk "{print $13;}" | sort | uniq -c -d | sort -n >| _stats/content-counts'
datalad run 'mkdir -p _stats; find -type l -ls | awk \'{print $13;}\' | sort | uniq -c -d | sort -n >| _stats/content-counts'
datalad run "mkdir -p _stats; find -type l -ls | awk '{print $13;}' | sort | uniq -c -d | sort -n >| _stats/content-counts"
datalad run "mkdir -p _stats; find -type l -ls | awk '{print $13;}' | sort | uniq -c -d | sort -n > _stats/content-counts"
datalad run "mkdir -p _stats; find -type l -ls | awk '{print \$13;}' | sort | uniq -c -d | sort -n >| _stats/content-counts"
datalad run "mkdir -p _stats; find -type l -ls | awk '{print $13;}' | sort | uniq -c -d  > _stats/content-counts"
datalad run "mkdir -p _stats; find -type l -ls | awk '{print $13;}' | sort | uniq -c   > _stats/content-counts"
datalad run "mkdir -p _stats; find -type l -ls | awk '{print \$13;}' | sort | uniq -c   > _stats/content-counts"
datalad run "mkdir -p _stats; find -type l -ls  > _stats/content-counts"
datalad run "mkdir _stats; echo 123 | tr 1 2  > _stats/1234"
datalad run --rerun
datalad run xvfb-run tcsh s05.ap.uber
echo datalad -l 2 run "find -iname *..nii.gz | while read f; do nf=\$(echo \$f | sed -e 's,\.\.,.,g' ); echo git mv \$f \$nf; done"
echo datalad run "awk '{print \$2;}' _stats/content-counts | while read f; do find -lname $f; done | sort > _stats/content-duplicates"
echo datalad run "find -type l -ls | awk '{print $13;}' | sort | uniq -c | sort -n >| /tmp/counts"
echo datalad run "mkdir -p _stats; find -type l -ls | awk '{print $13;}' | sort | uniq -c -d | sort -n >| _stats/content-counts"
echo datalad run -m "" wget -O .datalad/crawl/incoming.csv https://raw.githubusercontent.com/OpenNeuroLab/metasearch/master/docs/data/phenotype_mri.csv
gshaa 'datalad.* run' | sort | uniq
SHELL=/bin/bash datalad -l 2 run "find -iname *..nii.gz | while read f; do git mv \$f \${f//../.}; done"
SHELL=/bin/bash datalad -l 2 run "find -iname *..nii.gz | while read f; do nf=\$(echo $f | sed -e s,\.\.,.,g); git mv \$f \$nf; done"
SHELL=/bin/bash datalad -l 2 run "find -iname *..nii.gz | while read f; do nf=\$(echo \$f | sed -e s,\.\.,.,g); git mv \$f \$nf; done"
SHELL=/bin/bash datalad -l 2 run "find -iname *..nii.gz | while read f; do nf=\$(echo \\\$f | sed -e s,\.\.,.,g); git mv \$f \$nf; done"
SHELL=/bin/bash datalad -l 2 run "find -iname *..nii.gz | while read f; do nf=\${echo \$f | sed -e s,\.\.,.,g); git mv \$f \$nf; done"
time datalad --output-format '{path}' search run-01
```

**Comment by bpoldrack** [comment]
Okay, okay. ;-)

So, how about passing SHELL in via SINGULARITYENV_SHELL (to be SHELL from outside by default) and record that value? Basically the same thing, I was talking about in #2158.

**Comment by yarikoptic** [comment]
Let's chat about it on Fri hangout

**Comment by mih** [comment]
I wonder what the outcome of that chat three years ago was... Maybe we figured out that this issue can be closed, because nobody would work on it... ;-)

**Comment by yarikoptic** [comment]
Yes, test of time showed that we are ok so far without carrying too much about it
