### ISSUE TITLE
remove --unregister-only ?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2281]
#### What is the problem?
Not clear (if possible) how to unlink a sub-dataset.  E.g. I have a dataset which I was to "redo", while keeping this current version somewhere for backup.  So the steps could be
```
  datalad remove -d . --unregister-only subds  # which does not remove it, just unlists from modules
  mv subds newlocation/
```

from the docs it sounds like `git submodule deinit subds` should do it but it seems to not :-/:
```shell
$> /usr/lib/git-annex.linux/git submodule deinit metasearch 
Submodule work tree 'metasearch' contains a .git directory
(use 'rm -rf' if you really want to remove it including all of its history)
$> git submodule
+1d0a34d2debb14c77e2bfd47b62a193ca818add7 metasearch (heads/views/species=_;sex=_;site_id=_)
```
so no effect... didn't get an answer on git IRC on this question. @kyleam - do you know?
for now I just did something like `mv metasearch{,.aside}; mkdir metasearch; cd metasearch; git init; cd ..; datalad remove -d . metasearch`

**Comment by kyleam** [comment]
Sorry, I  missed this issue.  I just came across it when searching for something else.

`git submodule deinit` barfs because datalad creates "old-form" submodules (to use the phrase from `man gitsubmodules`) rather than those that are gitlinks to .git/modules/.  In any case, IIUC what you're after, that wouldn't do what you want because it clears the subds directory rather than unregistering it as submodule.

But, if you reverse your proposed steps above, I think you get what you want:

```bash
$> mv subds{,.aside} && datalad remove -d. -m"unregister subds" -r subds
```

---

A more complete snippet:

```bash
$> datalad create /tmp/dl-2281
$> cd /tmp/dl-2281
$> echo 1 >foo
$> datalad add .

$> datalad create -d. subds
$> cd subds
$> echo 2 >bar
$> datalad add .
$> cd ..

$> git submodule
+24579372567b6e586d09448658dc19c44221b4dd subds (heads/master)
$> tree
.
├── foo -> .git/annex/objects/06/7v/MD5E-s2--b026324c6904b2a9cb4b88d6d61c81d1/MD5E-s2--b026324c6904b2a9cb4b88d6d61c81d1
└── subds
    └── bar -> .git/annex/objects/GK/31/MD5E-s2--26ab0db90d72e28ad0ba1e22ee510510/MD5E-s2--26ab0db90d72e28ad0ba1e22ee510510

1 directory, 2 files

$> mv subds{,.aside}
$> datalad remove -d. -m"unregister subds" -r subds
$> git submodule
$> tree
.
├── foo -> .git/annex/objects/06/7v/MD5E-s2--b026324c6904b2a9cb4b88d6d61c81d1/MD5E-s2--b026324c6904b2a9cb4b88d6d61c81d1
└── subds.aside
    └── bar -> .git/annex/objects/GK/31/MD5E-s2--26ab0db90d72e28ad0ba1e22ee510510/MD5E-s2--26ab0db90d72e28ad0ba1e22ee510510

1 directory, 2 files
```

**Comment by kyleam** [comment]
I'll close this because `mv subds{,.aside} && datalad remove -d. -m"unregister subds" -r subds` does what you want, I think, and it's as short as your proposed sequence.  Please reopen if it doesn't work for you.
