### ISSUE TITLE
for parameters with nargs='+' docstring should report "list of"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#229]
e.g. now 
```
    _params_ = dict(
        paths=Parameter(
            doc="path(s) to data content that is to be obtained",
            constraints=EnsureStr(),
            metavar='file',
            nargs='+'))

    def __call__(self, paths):
```
for get results in a docstring
```
paths : str
  path(s) to data content that is to be obtained. Constraints: value
  must be a string.
```
whenever it expects a list of str

**Comment by yarikoptic** [comment]
may be there could/should be a magic logic allowing for a single instance of that type to be passed but then it should get wrapped into a list

**Comment by hanke** [comment]
Hmm, I would not want to mix Constraints doc string generation logic with argparse semantics. nargs='+' will always yield a list, hence the Constraint should match that and use EnsureListOf(str).

Question is whether argparse will run it on individual values or the entire list...

**Comment by hanke** [comment]
So it seems to want a single argument. Not sure how to do this best. The parameter itself clearly needs EnsureListOf(str) -- this is fix one. But it breaks argparse' behavior.

So from this angle it is not primarily about the docstring. It is about supporting the use case that only a single item in a (potential) container is evaluated. This might need an extension of the constraint interface.

Suggestions?

**Comment by yarikoptic** [comment]
unfortunately I don't "speak" constraints/argparse machinery yet to the degree to give a sensible suggestion... thus not sure why "only a single item" since ideally all the elements of the list should be evaluated to guarantee they are all str.

**Comment by hanke** [comment]
The constraint is used a `type` in argparse. That is a callable that gets used to evaluate any single argument. In case of nargs='+' every single element in what will become a list assembled by argparse. OTOH the python API will want to make sure it gets the list right away.

**Comment by hanke** [comment]
So let's get this settled. It seems that if the `paths` argument can deal with single str and list(str) equally well. The solution to this issue is:

`contraints=EnsureStr() | EnsureListOf(str)`

which leads to:

````
NAME : str or list(str), optional
  path(s) to data content that is to be obtained. Constraints: value
  must be a string, or value must be convertible to list(str).
  [Default: 'SOME']
````

(for the Python docstring).

This solution doesn't require interpreting argparse logic and ensures that the Python API is fully described at the same time.

I consider this base issue closed.
