### ISSUE TITLE
More specifically specify relationship between datasets were possible

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2290]
#### What is the problem?
ATM with #2289 we would get basic (partOf) relationship between subdatasets.
 [FAIR I3](https://www.go-fair.org/fair-principles/i3-metadata-include-qualified-references-metadata/) desires to have "more qualified" relationships declared.  In our datasets most typical and often presented relationship is having a derivative dataset:
- `./derivatives/subds1` isDerivativeOf  '.' but it goes backward in the hierarchy since we are aggregating into the superdataset.  So I may be we could have `hasDerivatives` similar to `hasParts`?
- in case of hierarchies where original dataset is subdataset (like @mih does in study forrest) then isDerivativeOf would work natively

Any other relationship we could have?

**Comment by mih** [comment]
Please see #2326 for a related RF.

**Comment by mih** [comment]
PR is merged.
