### ISSUE TITLE
Extract previous  'datalad run' commands into a script

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2291]
@yarikoptic just brought up the point that it'd be nice to be able to extract all previous `datalad run` commands into a script.  If we get a handle on determining inputs, it'd even be possible to extract them into rules targeting various workflow systems.

**Comment by mih** [comment]
That guy is worth his money!

**Comment by mih** [comment]
Are you planing to implement this some time soon? If not, I'll do it. I would do it as an option to `rerun`, to inherit the same flexibility in reporting that we have in re-execution.

**Comment by kyleam** [comment]
> Are you planing to implement this some time soon?

It wasn't a priority, but now that I know somebody wants to use it some time soon, yes!  I'll do it sometime today.  In my view, the second sentence is actually much more interesting (not surprising I think that because I tacked it on to the original idea), but that of course would have to wait.

**Comment by mih** [comment]
Absolutely aggree. But that is tricky thing. We might, however, get quite far by simply allowing users to optionally specify inputs -- just as a stored annotation. `run` itself could already use that info to fetch file content. We would merge that usually needed step under the control of run, and would have more confidence that we know what the inputs are.

It doesn't have to super tailored. Even saying `--inputs .` to communicate that I *want* all content to be present for execution would be helpful. A `rerun` could later on make sure that file that were present back then are available now (not necessarily all files that are present in the current state of the repo.)

**Comment by mih** [comment]
This is done, but see #2432
