### ISSUE TITLE
--report-status none

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2293]
#### What is the problem?
I love so much being not flooded with success messages when working with more than 2 files.... but some times I want even less of error messages -- just to have a summary (so many failed, so many succeeded) but it seems there is no way.  IMHO we should get an addition to report-status to say to report nothing

any objections?

**Comment by mih** [comment]
As long as we don't make this the default in order to start re-introducing tons of INFO log messages, I am fine with that.

**Comment by mih** [comment]
We have suppression of repetitive results now.
