### ISSUE TITLE
CERN's Zenodo

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#23]
Provides portal to upload software/data with versioning etc. See
https://zenodo.org/search?p=980__a:dataset
so might be useful to keep in mind at least for "crawling" and exposing via annex, ideally -- for publishing to ;)

**Comment by yarikoptic** [comment]
Related #486

**Comment by mih** [comment]
https://github.com/CONP-PCNO/conp-dataset/issues/104 is talking about code than can pull a Zenodo dataset as represent it as a DataLad dataset

**Comment by yarikoptic** [comment]
Note: We were also going to export to zenodo with .git/objects included so installation could result in getting a proper clone

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
