### ISSUE TITLE
datalad get   should not glob by default

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#230]
It leads to obscure behavior such as 
```
$> datalad get kasdfjkh                                                                                          
2015-09-21 13:43:39,544 [ERROR  ] Failed to start ['git-annex', 'get', []]'': execv() arg 2 must contain only strings (cmd.py:229)
2015-09-21 13:43:39,545 [ERROR  ] execv() arg 2 must contain only strings (TypeError) (main.py:206)
```
which if even we quiet down -- is not helping -- it would quietly succeed whenever it should have failed ("requested file doesn't exist").
IMHO there should be options ("glob", "regex") to specify if to treat given names as globs or regular expressions for more powerful specification of what to obtain.  Otherwise -- it is shell's job to expand those (as comment there in the code stated ;) )

**Comment by mih** [comment]
Re-evaluate in the context of #613. And close accordingly, if addressed.
