### ISSUE TITLE
Info on metadata standards

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2303]
https://fairsharing.org/

**Comment by yarikoptic** [comment]
I guess it will be closed when datalad gets listed there?

**Comment by mih** [comment]
We can close it now. Didn't get the memo that we want to minimize the number of needlessly open issues. ;-)

I am awaiting the closing of dozens of other issues within the next moments....

**Comment by yarikoptic** [comment]
actually I was not trying to be funny -- I wondered if this could reflect on our FAIR exploration and see if we could push making published datasets (e.g. http://datasets.datalad.org) as FAIR as needed to get listed at that registry
