### ISSUE TITLE
API docs of plugins are ugly due to local imports

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2313]
#### What is the problem?

http://docs.datalad.org/en/docs/generated/datalad.plugin.add_readme.html#module-datalad.plugin.add_readme

Not sure what could be done without hacking the whole autodoc chain.... :(

**Comment by mih** [comment]
The solution is to declare these pseudo plugins as "extensions" by declaring the entire set as a command suite via the new functionality in #2353 
Once done, no relative import ugliness is needed anymore.

**Comment by yarikoptic** [comment]
Where documentation for those "extensions" will live?

**Comment by mih** [comment]
Wherever they want. If e.g. MNE provides a datalad extension, they likely want it in their own docs.

**Comment by mih** [comment]
We now have an extension of our own, the documentation is here docs.datalad.org/projects/neuroimaging (readthedocs can expose "child" projects under a joint parent URL).

**Comment by mih** [comment]
Nothing else to be said here. Just the plugin conversion to commands still needs doing.
