### ISSUE TITLE
(ab)use .git/objects for storing annexed content without incurring permanent drag on the clones

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2319]
#### What is the problem?
We have lots of small (thanks to .xz) metadata files under git annex control now.  Fetching them one by one via ssh or http shown to be "not amazingly fast" to say the least.  Some bundled annex fetching is being thought about/through by @joeyh, but I thought to bring to the table yet another idea I thought we exercised mentally at some point.

At some point we discussed a wild ideas of (ab)using git object store  which provides compression and packing for efficient access to textual data.  I wonder if we could still do it somehow, in particular for the "most recent .datalad/metadata": e.g. using "git/objects" as a special remote of some kind for annex, so we could push those objects (pretty much a tree object with all the metadata files) to the server but in such a way that a regular "git clone" would not need to fetch them (disconnected branch).  Then a local special remote would request those objects from git, which might in turn fetch them if they haven't yet arrived locally.  The point is to make them not pointed by any branch which would get into reflog, but in principle we could create a disconnected commit for all current metadata files, make annex special remote know that they are present in there, request git commit, extract from the (git) tree object.

**Comment by mih** [comment]
Yeah, I was thinking about something similar. Maybe we can hack something up next week.

**Comment by mih** [comment]
Please see #2326 for a related RF.

**Comment by yarikoptic** [comment]
metadata handling has a new life in https://github.com/datalad/datalad-metalad/ now.  As for git objects based special remote, we have a prototype in https://github.com/datalad/datalad/blob/master/sandbox/git-annex-remote-gitobjects but nobody is too excited to use it, so we will just let this idea to RiP
