### ISSUE TITLE
"search" migration HOWTO

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2324]
#### What is the problem?
With 0.10.x advance search capabilities search API is refactored completely, so for the sake of previous search users (likes yours truly) it would have been nice if at least documentation outlined how we could achieve results the same or similar to the previous `search`.  Here I am providing use cases I had/used on a regular basis during demonstrations or actual use of the datasets

#### pre-0.10: 
`datalad search query | xargs datalad install`
#### pre-0.10:
```shell
$> datalad search --regex -r name -r author multi.*echo 
openfmri/ds000210:
 author: Elizabeth DuPre, Wen-Ming Luh, R. Nathan Spreng
 name: Multi-echo fMRI replication sample of 
  autobiographical memory, prospection and 
  theory of mind reasoning tasks
...
```

**Comment by mih** [comment]
I will close this now. Part of that is asking for general documentation on how any command works, part of that is waiting for search functionality  that I thought we agreed on not coming from me. I will propose a PR that reverts search to the exact same behavior and capabilities it had in 0.9.

**Comment by yarikoptic** [comment]
Then let's close with that PR.

**Comment by mih** [comment]
I unassigned from this issue as the present situation is that "search is different" with no prospect of exact feature parity with the 0.9 branch any time soon. Hence there is no migration. There is just RTFM -- coming in #2345
