### ISSUE TITLE
RF "0.10" metadata handling into a separately installable unit

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2326]
This will implement an idea we had a while back (cannot find the issue ATM).

Advantages for the core tool: 
- shrink the code base by about 7k lines (that is more than 15% of the entire Python code base)
- massive reduction in the dependencies (including a reduced focus on neuroimaging as a field of application)
- faster testing

Advantages for the metadata functionality:
- separate release cycle at a different pace
- muuuch faster testing
- compatibility with multiple versions of datalad

The metadata package will be a regular python package that declares an install-dependency on datalad (>=0.10), as it will need the newly added ability for dynamically loading full command implementations. This can then also serve a role model for other extensions (crawler is a candidate), tailored DICOM/BIDS support (bids2scidata) is another. Naturally such extensions can also depend on each other.

Inclusion into DataLad proper will work similar to "plugins". However, extensions can provide entire suits of commands, hence will be able to declare "section names" for proper listing in `datalad --help`. Extensions will be able to shadow commands provided by datalad core, to enable development of customized extensions that can later on easily move into datalad core without requiring API changes, and user-end modifications.

Given the 9 month development that make up the diff between 0.9 and 0.10 a selective rebase is probably not feasibly as means to get it out of the mainline.
```
% git log --oneline 0.9.3..master |wc -l
821
```
However, it is quite easily possible to remove all the code at once (I test drove that in #2325), and replace the respective matching files with the code in 0.9.x. There will be some effort necessary to revert the (minimal) adjustments made to the crawler, but other than that it should be pretty much copy&paste, as there are no further contact point with the metadata handling code and the rest. The only thing we need to look out for is the LZMA support handling in json_py. While this could stay in, datalad core doesn't use it in any way and it should not be a dependency. The metadata tool will then have to use another helper in its own code base.

If you have a better idea on how to wrangle the Git history to get this out in a clean fashion, please chime in.

I assigned this to the 0.10 release milestone, as we must sort this out prior release.

**Comment by yarikoptic** [comment]
Even after having thought about it I am still having a split opinion.  Could we discuss it (before action happens) when we see each other in a few hours instead of torturing the keyboards?

**Comment by mih** [comment]
We can now have extension modules (#2353), but also decided to make this part of the core.
