### ISSUE TITLE
--all (or just --git-annex-options?) for datalad drop

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2328]
#### What is the problem?
ATM we provide no interface to drop content from previous versions etc.  I thought that either we would need to provide some "helpers" (`--all`, `--unused`, `--not-referenced`) which would translate one-to-one to some pre-crafted git-annex drop commands, or just make it possible to specify options for git-annex drop for maximum flexibility, while benefiting from our `-r` etc functionality

**Comment by mih** [comment]
Slowly getting around to this. I absolutely agree that we need `--all`, we also need the ability to drop content from a specific branch (think `add-archive-content` result, and wanting to drop the source archive).

I am less certain about `--unused` as it would imply running another annex command first.

For clarification: Where do you draw the line between `--unused` and `--not-referenced`? They sound pretty much identical to me.

**Comment by kyleam** [comment]
> Where do you draw the line between --unused and --not-referenced? 

My guess: `--not-referenced` would refer to content whose commit is unreachable from any branch, tag, or other reference.
