### ISSUE TITLE
Field-selective value matching for egrep search

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2337]
@akeshavan Want to find all 't1w' files across all datasets, and then report the URL we have on record for that.

The use case is to get this information exported once, hence it is pretty useless to build a search index. Moreover, the field value is a proper tag, hence no chunking or stemming is needed or helpful. Consequently, the egrep mode is the best way to implement this.

**Comment by mih** [comment]
@yarikoptic any chance you could give this a try?

**Comment by yarikoptic** [comment]
may be... can't promise though... I guess we still need to drill down that idea we had about yet another cmdline option to specify "--query-format"?  ATM we have per mode specific, but I guess it could be a number of them ("key-value", "plain") with defaults varying per each mode?

**Comment by mih** [comment]
Yes, that sounds good.

**Comment by mih** [comment]
Reassigning to a later release -- everyone is too busy...

**Comment by mih** [comment]
It seems to me that https://pypi.org/project/pyparsing/ could provide a straightforward way to implement a minimal query language for `egrep` search, primarily to address the usecase of this issue.
