### ISSUE TITLE
(optional) per metadata extractor file

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2341]
#### What is the problem?
while chatting the point came up for datasets which mixed set of extractors some of which could leak sensitive data, they might need to have a dedicated/separate `cn-` file so it could be placed into annex and marked as sensitive.  That data then might also not be aggregated into `ds-` unique values field

PS filing so just that we do not forget to possibly elaborate on this

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
