### ISSUE TITLE
Develop set of demo scripts

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#235]
What we have is here:

https://github.com/hanke/datalad/commit/0bf4bf534be5d2183ead4f77fb86734341e31a56

This should be extended into a family of script for the following steps:

1. create handles + add data + add metadata + create collection + publish collection
2. obtain published collection + obtain one handle therein + modify something in handle + republish collection elsewhere
3. update collection from (1) with published modifications from (2) + show handle upgrade

**Comment by yarikoptic** [comment]
since we have some of those under docs/examples introduced in 7d35a3e33c397ce0adbc4731f1d99cbd6207ddc8 and 69b8b6d36553c6a5a983adc607e908180a49a0ef, I would close this one
