### ISSUE TITLE
Return values of "api" functions

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#236]
Please correct me if I am wrong but ATM those do not (intend) to return any value.  I think that at least in Python API allowing to return values would be beneficial.  E.g. I see myself using smth

```python
import mvpa2.suite as mv
import datalad.api as dl

hndl = dl.install_handle('openfmri/ds00001')
ds = mv.OpenFMRIDataset(hndl.path)
...
```
NB side-point is that install_handle shouldn't fail on consecutive runs, thus allow to "install" to succeed if handle already installed.

edit 1: return handle object, not just path
@hanke what do you think? ;-)

**Comment by yarikoptic** [comment]
which also somewhat relates to the question of the "master local collection".  Happen I have installed openfmri/ds00001 before somewhere -- what should happen 

- fail? (bad -- I want demos to use datalad and work on every box)
- would I get path to that installed one (possibly diverged)?
- should we allow such functions as `install_handle` accept a name/instance of a collection? i.e. I would need to generate some local collection first I guess then
- ...
?

**Comment by bcipolli** [comment]
@yarikoptic Do you mean, if the data has been installed, but isn't using `git annex` / `datalad`?

I would hope that it'd fail--supporting a collection *not* using `git annex` seems like a lot of work for not a lot of benefit, for a new project.

Perhaps `install_handle` could take an optional argument (`convert`, default `False`), that could attempt to convert downloaded files into a collection supported by `git annex` efficiently (i.e. don't download already downloaded files), and `install_handle` could throw a meaningful message to the user to pass `convert=True` if they like.

**Comment by yarikoptic** [comment]
No, I was simpler - that it was installed with datalad... May be I took it incorrectly (or patched incorrectly,  since working on that atm, wiki send pr wherever again online)... Will make sure that multiple installs succeed

**Comment by yarikoptic** [comment]
continuing this topic, now some actions just print to the stdout (e.g. list-handles) which is somewhat useless for Python API where it would e.g. expect a list of those entries to be returned.   It feels that such functions should just return a list which the cmdline "executioner" should know how to interpret (i.e. print entries to the stdout)

**Comment by yarikoptic** [comment]
#285 was merged and we provided some reasonable initial return values, thus closing
