### ISSUE TITLE
Make our silent UIs (e.g. SilentConsoleLog) provide ".question"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2364]
#### What is the problem?
ATM non interactive UIs simply do not implement the requiring interaction `.question`, and whenever non-interactive UI is used (e.g. in the tests) and code didn't explicitly check for e.g. having credentials available, it would fail with a non-informative 
```
'SilentConsoleLog' object has no attribute 'question'
```

I think they should provide .question which would just blow with a summary -- the question, so we at least know what code triggered the blow

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
