### ISSUE TITLE
web-app idea: selector of files for a datalad command based on metadata 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2383]
#### What is the problem?
Just to "borrow" the JS frameworks used by e.g. http://openneu.ro/metasearch/ to provide webui which would have the table with all the files and their (selected) metadata fields, so user could subselect interactively, click the button for the command (get/drop/unlock/add/???) to be ran

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
