### ISSUE TITLE
API commands should report at INFO level on accomplished actions

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#239]
Currently it goes very silently without any feedback to the user (besides 0 exit code) if anything was accomplished, e.g.
```
$> datalad install-handle -l info http://data.pymvpa.org/datasets/tutorial_data/.git /tmp/tutorial_data6 
$>
```
IMHO it should be sufficient to provide at least a single line output at INFO level about the action being finished successfully (and some action specific information, e.g. confirming installation path of the handle in this case and may be reporting that handle was registered within local collection; or reporting that nothing was done since handle as already installed in the given location)

**Comment by mih** [comment]
I think this is a general habit now. If it remains an issue, there should be a milestone to track individual issues, and not another general bug.
