### ISSUE TITLE
We need test "bots" for result handling

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2392]
Cases like #1963 can happen in tons of places and it is not feasible to have dedicated tests for such combinatorial problems for each manifestations. We should develop an approach that allows us to inject test code in the central bits of our result processing that can, for example, verify the internal consistency of any result dataset seen during an entire test run. In the case of #1963 we want a policy check that ensures that any `path` property is always an absolute path.

**Comment by yarikoptic** [comment]
I am not quite sure what kind of bots you envision.  Combinatorics are largely avoided by dedicated "unittests" and "sweeping" of the spaces of possible values/instances (like we do with our sample repos, or `hypothesis` module could do for more trivial datatypes) AFAIK.

**Comment by mih** [comment]
Not worth keeping this open.
