### ISSUE TITLE
Allow to pass options directly into annex'es call

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#240]
Some commands (e.g. get, drop) are just proxies to annex.  We should allow to pass options into them.  The question is _how_: 
- `--annex-opts`
- `--  annex-opts` i.e. make it possible to enable convention of many tools to pass parameters non-processed after a double dash `--` (didn't look if easy to accomplish with argparse and our current interface magic)

**Comment by mih** [comment]
This past 3.5 years have shown that there is no simple/generic solution and that command gravitate towards more than simple proxies. I think it is time to close this.
