### ISSUE TITLE
boilerplate copy/pasting should be reduced across main code/extensions

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2404]
#### What is the problem?
setup_support.py and some code in setup.py is now duplicated in the main code base and then in https://github.com/datalad/datalad-neuroimaging   I wondered if we are doomed to do something about it?

Proper solution probably could be to 

P1. establish yet another python module (datalad-setup or alike) which would provide that common code.  Pros -- might be helpful even for non-datalad projects. Cons --  even more packaging/maintenance, version dependencies etc .

"uglyish" (re)solutions could be:

U1. migrate setup_support.py, formatters.py (and whatelse) under `datalad/support/` in the main code base, so we could just import them as a file within main codebase setup.py, while all dependent extensions could properly import from `datalad.support.setup`?
U2. setup a "datalad-core-base" repository which would keep those files and possibly README.md with some common sections (Acknowledgement?), which we keep merging (if common change is needed) within all "official" repositories

What do you think @datalad/developers ?

**Comment by bpoldrack** [comment]
At a first glance, I tend to prefer U1. It keeps the additional maintenance effort away, while still being easily available for non-datalad developers of extensions. I don't find that particularly "ugly".

**Comment by bpoldrack** [comment]
P1 and U2 both require additional awareness and knowledge of required dependencies/workflows not just for us but for non-datalad developers as well. ATM I don't see an advantage that's worth it.

And BTW - P1:
> [a] python module [..] which would provide that common code ...

That's exactly what `datalad-core` is for, isn't it? I don't even find that cleaner than U1.

**Comment by yarikoptic** [comment]
not exactly.  In P1 we could just do smth like `from datalad_core.setup import *` whenever in U1 we would not be able to import `datalad` module directly (no presence of required wrapt etc could be assumed) and would need to resort to some dance with `import_module` etc

**Comment by bpoldrack** [comment]
Well, first of all I obviously misunderstood what P1 is meant to be. But I still might not get it entirely. If it's just a python module within datalad-core, then what do you mean by 
> even more packaging/maintenance, version dependencies etc .

**Comment by yarikoptic** [comment]
I guess I am also missing what is the  `datalad-core` you are talking about ;)

**Comment by mih** [comment]
Ping: https://github.com/datalad/datalad-extension-template/issues/2

The duplication is actually more extensive then what is discovered here (e.g. `formatters.py`). However, when I was faced with the decision copy vs. package, I looked at the changes done to these bits, and found very few and rather infrequent -- conclusion: not worth the trouble.

**Comment by yarikoptic** [comment]
Indeed not frequent, so pains also wouldn't be frequent, but still possible fixes and improvements would not propagate, and then when moment comes someone would need to do it across all instead of fixing in one spot (same story as Debian packaging/modularization)

**Comment by mih** [comment]
With https://github.com/datalad/datalad/pull/3600 merged, I think this deserves to be closed. Thx!
