### ISSUE TITLE
should we migrate "metadata-extra" into "metadata"?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2411]
#### What is the problem?
Found that it crashed after 5 hours of aggregating:
```shell
...
[INFO] Aggregate metadata for dataset /mnt/btrfs/datasets-meta6-5/datalad/crawl/dicoms/dcm2niix-tests
[INFO] Engage metadata extractors: ['datalad_core', 'annex', 'xmp', 'dicom']
[ERROR] ("Failed to load metadata extractor for '%s', broken dataset configuration (%s)?: %s", 'xmp', <Dataset path=/mnt/btrfs/datasets-meta6-5/datalad/crawl/dicoms/dcm2niix-tests>, 'No module named libxmp.utils [xmp.py:<module>:19]') [metadata.py:_get_metadata:454] (ValueError)
datalad aggregate-metadata -r 2>&1  14117.70s user 3824.31s system 100% cpu 4:57:04.09 total
tee .git/logs/aggregate.log  0.15s user 2.26s system 0% cpu 4:57:04.09 total
```

I did "pip install -e ." in datalad-neuroimaging which should have pulled all needed dependencies etc... apparently something was left behind for my usecase ... will need to do manual installation of github url with `[full]`... apparently can't just do `pip install git+https://github.com/datalad/datalad.git\[full\]`, heh ... 
so decided to bring this to discussion: may be we should ERROR gracefully and just skip that extractor with a warning or smth?

**Comment by yarikoptic** [comment]
Ha ha, I did feel that he indeed complained the other way around, but I no longer trust his whining ;-)

**Comment by mih** [comment]
Closing "question"-type issue with a response, and no further activity.
