### ISSUE TITLE
Reference demo notebook in docs

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2424]
@satra pointed to http://nbviewer.jupyter.org/github/ReproNim/reproducible-imaging/blob/master/index.ipynb and in particular to https://github.com/satra/reproducible-imaging/blob/master/notebooks/introductory_data.ipynb as a demo notebook with an intro to datalad.

We should at least reference this in the docs, but maybe even take it over to have it evolve with the API.

**Comment by satra** [comment]
> maybe even take it over to have it evolve with the API.

+1

**Comment by yarikoptic** [comment]
+2

**Comment by mih** [comment]
I think we settled on the handbook as the main source of information.
