### ISSUE TITLE
Add `--inputs`/`--env` to `run`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2432]
Continuing from #2291: It would be very useful to be able to indicate what inputs need to be around for a `run` invocation. It doesn't have to super tailored. Even saying --inputs . to communicate that I want all content to be present for execution would be helpful. A rerun could later on make sure that file that were present back then are available now (not necessarily all files that are present in the current state of the repo.)

Like `--inputs`, `--env` would be useful to have. `run` could use it to capture the respective environment variables, and `rerun` could set or check for conflicting values in the re-execution environment.

**Comment by kyleam** [comment]
I'm missing something wrt `--env` to "capture the respective environment variables".  I imagine it'd look like `datalad run --env ENV=val command`, but  can't you already capture them in the run call with `datalad run ENV=val command`?

Perhaps the idea is that with the `--env` variant we'd know the environment variables and then could "check for conflicting values"?  I'm not sure what the check for conflicting values would entail, though my initial feeling is that it's outside the scope of something should do.

**Comment by mih** [comment]
Here is a use case: The software FSL requires a bunch of env vars to be set (a bunch of others do that too). The particular values can be different across system, but the vars have to be set to make the commands not fail. If I could say `--env FSLDIR` datalad could use this info to test for the var being set and record the setting. On rerun it could perform the same check and additionally test if the expected value is present.

We could of course allow for other modes of operations, like set any missing variable, but here I would draw the line, given that we are not in the business of recreating execution environments.

I really see this as a tool to specify conditions for running commands.

**Comment by kyleam** [comment]
OK, thanks for expanding on the idea.  I'd prefer to draw that line in a different location than you, but I think I understand what you have in mind enough to implement it.

**Comment by yarikoptic** [comment]
So --env is like --run-if-env-is-set? Indeed sounds a bit too far beyond the line to draw but such feature could be thought of when we get back to discussion of having different "runners". So being able to specify the conditions (have fallen, have gpus,. ..) might be specific to the runner but interfaced back to datalad (as skip-condition-not-met of some kind)

**Comment by mih** [comment]
I see it more like --this-env-was-critical-for-command-execution. Think DATALAD_RANDOM_SEED... Not having that value would make it impossible to rerun with the aim of similar results, regardless of a runner alternative.

**Comment by yarikoptic** [comment]
If we run commands in a shell, shouldn't then be sufficient to prepend with those definitions in command line to be executed? Would not need any custom option, and would become party of the command, and would work when exported to the script

**Comment by yarikoptic** [comment]
FWIW -- to `run` a command which requires first unlocking output files (so not `input`) so they could be overridden, had to include unlocking into 'run'.  From my use case points could be
- `--output` might be desired
- `--output` (and thus `--input`) specs might need to allow for globs, e.g. to be able to rerun a command on all files of a specific type.

Here is my command I had to use
```shell
$ datalad run 'datalad unlock *nii; for f in *mnc; do mnc2nii $f ${f%.*}.nii; done'
```

**Comment by kyleam** [comment]
> to run a command which requires first unlocking output files

I'm confused.  Are you modifying files in-place?

**Comment by yarikoptic** [comment]
that is the "pain point" of using majority if not all tools on git-annex'ed files -- typically an output file is not removed before being opened for writing, so tools just issue `open(..., 'w')` syscall effectively modifying target files inplace.  That is why either manual "rm" or "unlock" is needed to (re)run things if output files already might exist

**Comment by kyleam** [comment]
But the part I'm confused about is modifying it in-place.  Seems like bad practice.

**Comment by kyleam** [comment]
> That is why either manual "rm" or "unlock" is needed to (re)run things 

A manual unlock shouldn't be needed to rerun things.  Are you hitting situations where it is?

**Comment by kyleam** [comment]
> that is the "pain point" of using majority if not all tools on git-annex'ed files

Hmm, dunno,  I'd say that's certainly user-specific because I've used a lot of tools with git-annex and have only experienced this as a "pain point" with build tools like snakemake, which want to regenerated any number of output files in the dag based on updated inputs.

**Comment by yarikoptic** [comment]
Try convert ;-)

**Comment by kyleam** [comment]
> Try convert ;-)

OK, seems to work:

```
tdir=/tmp/convert-test
test -d $tdir && datalad remove --nocheck -r $tdir
datalad create $tdir
cd $tdir
git annex addurl --file dragon.gif http://www.imagemagick.org/Usage/resize/dragon.gif
git annex add dragon.gf
git commit -m"dragon"

datalad run convert dragon.gif -resize 64x64 resize_dragon.gif
```

```
[...]
add(ok): resize_dragon.gif (file)
save(ok): /tmp/convert-test (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)

```

Care to be more specific?

**Comment by yarikoptic** [comment]
now run the last command again.
`rerun` is "smart" to unlock all new or modified files it knows about. But it might not be sufficient (e.g. if command operates on a globbed expression)

**Comment by mih** [comment]
Here is a realworld case that I just hit:

```
INFO: Populating template files under /home/mih/hacking/datalad/datalad-neuroimaging/datalad_neuroimaging/tests/data/bids/
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/home/mih/hacking/heudiconv/heudiconv/cli/run.py", line 120, in main
    process_args(args)
  File "/home/mih/hacking/heudiconv/heudiconv/cli/run.py", line 330, in process_args
    overwrite=args.overwrite,)
  File "/home/mih/hacking/heudiconv/heudiconv/convert.py", line 211, in prep_conversion
    getattr(heuristic, 'DEFAULT_FIELDS', {}))
  File "/home/mih/hacking/heudiconv/heudiconv/bids.py", line 93, in populate_bids_templates
    with open(events_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/home/mih/hacking/datalad/datalad-neuroimaging/datalad_neuroimaging/tests/data/bids/sub-02/func/sub-02_task-oneback_run-01_events.tsv'
```

heudiconv converting another scan session for a subject that already exists in the bids dataset. heudiconv feels like opening a files that is already annexed (although I think heudiconv shouldn't do that, because it is converting a T1w scan, but that is another issue).

I guess this puts me in dead lock. If I unlock the file the dataset isn't clean, if it stays locked the heudiconv call fails.

**Comment by kyleam** [comment]
> now run the last command again.

I did, without an issue.

> rerun is "smart" to unlock all new or modified files it knows about. But it might not be sufficient (e.g. if command operates on a globbed expression)

I don't think it's a good idea to use globs in a way that results in overwriting existing output files that weren't produced by the previous call.

**Comment by yarikoptic** [comment]
```shell
$> tdir=/tmp/convert-test
test -d $tdir && datalad remove --nocheck -r $tdir            
datalad create $tdir    
cd $tdir
git annex addurl --file dragon.gif http://www.imagemagick.org/Usage/resize/dragon.gif
git annex add dragon.gf
git commit -m"dragon"

datalad run convert dragon.gif -resize 64x64 resize_dragon.gif
datalad run convert dragon.gif -resize 64x64 resize_dragon.gif
[INFO   ] Creating a new annex repo at /tmp/convert-test 
create(ok): /tmp/convert-test (dataset)                                                                                                           
addurl http://www.imagemagick.org/Usage/resize/dragon.gif 
(to dragon.gif) ok
(recording state in git...)
git-annex: dragon.gf not found
git-annex: add: 1 failed
[master 36371fe] dragon
 1 file changed, 1 insertion(+)
 create mode 120000 dragon.gif
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) ===== 
add(ok): resize_dragon.gif (file)                                                                                                                 
save(ok): /tmp/convert-test (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
[INFO   ] == Command start (output follows) ===== 
convert-im6.q16: unable to open image `resize_dragon.gif': Permission denied @ error/blob.c/OpenBlob/2761.
[INFO   ] == Command exit (modification check follows) ===== 
[INFO   ] The command had a non-zero exit code. If this is expected, you can save the changes with 'datalad save -r -F.git/COMMIT_EDITMSG .'
```
and just now spotted the typo (`git annex add dragon.gf`) but it is of no effect anyways

globs is just an example.  It could be a user script (in our case it was typically a nipype workflow) which might get an idea to redo some files which may be were not created by some previous `run` command etc.  Sure thing it might be given to users as a "feature" but I do not think that we should enforce it without providing an alternative way (e.g. stating what needs to be unlocked in addition to automagically deduced)

**Comment by kyleam** [comment]
During the call, we mentioned two scenarios where a user might want to modify an output in-place: (1) an update of the current content and (2) an overwrite of the content, ignoring the previous content.  That makes me wonder what the "action" of --output should be.  For --input, it's a "get".  In (1) above, you need the content present, so it'd be a "get" and "unlock".  In (2), it could be an "unlock" or a less expensive "rm".

So, if we just unlocked, it would be insufficient for use case (1).  I suppose one option is to restrict --output to unlocking and say that, if you want (1), you should specify the file with both --input **and** --ouput, so that it would be "get" then an "unlock".  Thoughts?

**Comment by mih** [comment]
@kyleam I agree with your final thought:

- `--input` -> `get()`
- `--output` -> `unlock()`

I am not sure whether it is worth going through the pain of figuring out whether it is `unlock` or `rm` that should be executed. That would depend on whether something matches `input` and `output` or just `output`. However, here is another complication (maybe that is what you hinted at):

```
(datalad3-dev) mih@meiner /tmp/demo (git)-[master] % ll
total 4.0K
lrwxrwxrwx 1 mih mih 108 Apr 28 13:39 this -> .git/annex/objects/2W/kW/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e
(datalad3-dev) mih@meiner /tmp/demo (git)-[master] % datalad unlock this
[WARNING] no content present, can't unlock [unlock(/tmp/demo/this)] 
unlock(impossible): /tmp/demo/this (file) [no content present, can't unlock]
```

which leaves the broken symlink as it was before. So in such case `rm` is the only choice, assuming `inputs` are processed first and there should have been content, if it would be an input.

**Comment by kyleam** [comment]
> However, here is another complication (maybe that is what you hinted at):

No, hadn't thought about that.  Good point.

**Comment by kyleam** [comment]
Most of this is addressed by some combination of #2464 and datalad/datalad-container#11.  @mih, would you like me to open a separate issue for `--env`?

**Comment by mih** [comment]
I am undecided. Wouldn't hurt. OTOH it will be self-evident when the need arises.

**Comment by kyleam** [comment]
Alright, I'll go with the other hand.
