### ISSUE TITLE
not clear what "search-handle" is actually searching for and where

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#244]
e.g. I have described some local collection with a name and license, but search (despite spending almost 2 sec) returned nothing:
```
$> cat .datalad/datalad.ttl 
@prefix : <file:///tmp/tutorial_data4/.datalad/datalad.ttl#> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix dctypes: <http://purl.org/dc/dcmitype/> .
@prefix dlns: <http://www.datalad.org/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix pav: <http://purl.org/pav/> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

dlns:this a dlns:Handle ;
    dct:license "BSD-3" ;
    pav:createdBy <#author> .

<#author> a prov:Person,
        foaf:Person ;
    foaf:name "Yarik" .

(venv-tests)2 15336 [2].....................................:Thu 24 Sep 2015 12:40:05 AM EDT:.
hopa:/tmp/tutorial_data4
$> datalad list-handles
tutorial_data3
tutorial_data2
tutorial_data5
tutorial_data4
tutorial_data6
forrest_gump
(venv-tests)2 15337 [2].....................................:Thu 24 Sep 2015 12:40:13 AM EDT:.
hopa:/tmp/tutorial_data4
$> datalad search-handle Yarik 
(venv-tests)2 15338 [2].....................................:Thu 24 Sep 2015 12:40:23 AM EDT:.
hopa:/tmp/tutorial_data4
$> time datalad search-handle Yarik 
datalad search-handle Yarik  0.93s user 0.27s system 93% cpu 1.278 total
```

**Comment by bpoldrack** [comment]
Okay, first of all, it's supposed to search for handle, whose metadata contain that string. So, you were using it right and it should have returned your tutorial_data4.
Second, it searches in the metadata known to the local master collection.
Third: Second point is the problem. The metadata in the master collection wasn't updated.

The question is, under what circumstances we want to update it. We can change the metadata of a locally available collection or handle. In case of collection, it makes sense to let the master fetch this collection at the end. In case of a handle, it's less clear what is to be updated automatically.

**Comment by bpoldrack** [comment]
Since #248 is merged, that usecase should work as expected. Do you want to test again before closing this, @yarikoptic?

**Comment by yarikoptic** [comment]
I will try after I can wait that long ;) (e.g see #305).

**Comment by yarikoptic** [comment]
Since all this functionality was RFed away -- closing for now
