### ISSUE TITLE
Inconsistent behavior of save() between v5 and direct mode

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2441]
Recently we had #2043, but afterwards I noticed this

https://github.com/datalad/datalad-neuroimaging/commit/1e07b06a5debeb533917e7c160c32c262c605783

Havent investigated yet, but it smells like an issue related to change detection. Given the substantially different models of v5 and direct mode repos the question is to what degree we should and could make them behave in a similar way.

The only way I see to make them one and the same would be to limit any implementation to features available for the "dumbest" backend. But I dont feel comfortable with that.

**Comment by bpoldrack** [comment]
Actually, this is about adding to git in direct mode.

https://github.com/datalad/datalad-neuroimaging/commit/1e07b06a5debeb533917e7c160c32c262c605783

can be reverted as soon as the fix is merged.
