### ISSUE TITLE
datalad[full] no longer installable under PY2

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2442]
Here is the evidence: https://travis-ci.org/datalad/datalad-neuroimaging/builds/370442197

The cause is

```
Collecting secretstorage; sys_platform == "linux2" or sys_platform == "linux" (from keyring>=8.0->datalad==0.10.0.dev1->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/02/de/e4590cf025c714635637d4b2d19acfb1015f2d0c6cfe843b2b8f776ec819/SecretStorage-3.0.0-py2.py3-none-any.whl
SecretStorage requires Python '>=3.5' but the running Python is 2.7.14
```

Possible actions are:

- drop this dependency for PY2
- change the world
- time travel

**Comment by yarikoptic** [comment]
Fix have been in works within secretstorage module.

**Comment by mih** [comment]
Fixed outside datalad.

**Comment by yarikoptic** [comment]
confirming the fix: https://travis-ci.org/nipy/heudiconv/builds/370368742 build passed
