### ISSUE TITLE
Should we add new MRI datasets, listed in cMadan/openMorph?

### ISSUE THREAD

**Issue by miykael** [datalad/datalad#2450]
I just discovered @cMadan's comprehensive list about open-access human anatomical MRI images: https://github.com/cMadan/openMorph

Would it make sense to go through this list and try to add missing datasets to datalad or is there an obvious reason why this doesn't make sense?

**Comment by cMadan** [comment]
One barrier is that some of those datasets require specific data use terms to be agreed (e.g., HCP, CamCAN, ADNI). In some cases agreeing to the terms automatically allows for access to the data, but in other cases there is some review process by the data managers for the specific dataset. I think this issue applies to about 30-40% of the datasets in my list.

**Comment by mih** [comment]
This makes perfect sense. The only reason I can think of that this wasn't done yet (apart from license terms for some, as @cMadan pointed out) is lack of time. So this would be a great contribution. Please coordinate with @yarikoptic who is the chief data maul for DataLad.

Also, let's move this over to https://github.com/datalad/datasets (which should get a README, to make this more obvious...).

**Comment by yarikoptic** [comment]
Note also that some of those datasets are already available from http://datasets.datalad.org AKA datalad's `///`

**Comment by yarikoptic** [comment]
migrated to https://github.com/datalad/datasets/issues/18
