### ISSUE TITLE
datalad fails under python -OO

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2461]
#### What is the problem?

Several places (`_where_reload`, `find_files`, `_split_out_parameters`, maybe others) in datalad assume that `__doc__` is always a string, but under `python -OO` it will be `None`.

#### What steps will reproduce the problem?

```bash
%> cat <<EOF >/tmp/datalad_import.py
from datalad.support import annexrepo
EOF

%> python -OO /tmp/datalad_import.py
```

---

This is a minor issue (perhaps not worth addressing?), since it is unlikely datalad will be used in a way that triggers it.

**Comment by yarikoptic** [comment]
In pumps pymvpa we were religious about supporting -O ... In reality never used it and even I think I saw slower performance with it ;-) but yeah, making it kosher wouldn't hurt
