### ISSUE TITLE
Incorrect/confusing comment in .datalad/.gitattributes

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2466]
The comment in .datalad/.gitattributes looks wrong.

```bash
% datalad create foods
% cat foods/.datalad/.gitattributes
# Text files (according to file --mime-type) are added directly to git.
# See http://git-annex.branchable.com/tips/largefiles/ for more info.
** annex.largefiles=nothing
metadata/objects/** annex.largefiles=(largerthan=20kb)
```

If I'm reading these attributes correctly, they say to add files (not just text files) directly to git if they are anywhere within the .datalad subdirectory except metadata/objects.  If the file is in .datalad/metadata/objects, add it directly to git unless it is larger than 20kb.

I think the comment should be moved above the content that `create --text-no-annex` writes:

https://github.com/datalad/datalad/blob/b5c67a4b5e0d02c5ad1bffdfffe5f4a21e0462b7/datalad/distribution/create.py#L342-L344

Or just deleted altogether.

**Comment by mih** [comment]
Deletion would be my choice.
