### ISSUE TITLE
Misleading error message, error old git-annex version, but successful download

### ISSUE THREAD

**Issue by tstoeter** [datalad/datalad#2470]
#### What is the problem?
Datalad successfully installs dataset although it complains about old git-annex version with an error message. This is misleading, I expected the dataset install to have failed after this message.

#### What steps will reproduce the problem?
- old git-annex version is installed
$ datalad install ///openfmri/ds000002
[INFO   ] Cloning http://datasets.datalad.org/openfmri/ds000002 to '/home/user/ds000002' 
[ERROR  ] git-annex of version >= 6.20170220 is missing. Visit http://git-annex.branchable.com/install/. You have version 5.20151208-1build1 [annexrepo.py:_check_git_annex_version:734] (OutdatedExternalDependency) 
- install new git-annex version
$ datalad install ///openfmri/ds000002
install(notneeded): /home/user/ds000002 (dataset) [dataset <Dataset path=/home/user/ds000002> was already cloned from 'http://datasets.datalad.org/openfmri/ds000002']

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.9.3

**Comment by mih** [comment]
The reason for this behavior is that annex is only needed once a successfully cloned repository is locally initialized. Prior to the clone we cannot know whether this is needed. Moreover, DataLad works with plain Git repositories too, hence we would not want to error on a missing or outdated annex right away.

I see your point, but I don't think we can do anything about it, without complicating the situation even further. If datalad was installed via a system package manager (e.g. APT) it should always yield a working datalad+annex+git combo. If those pieces are installed from separate sources we cannot do much more than error as soon as we become aware of an issue.

I am closing this now, but please feel free to reopen, if you see a viable path to get this issue addressed.
