### ISSUE TITLE
DataLad installing/running on Win10 Professional

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2475]
Had the chance to see datalad 0.10 being install and run on Win10 in the linux subsystem by @fluese.

- enable Neurodebian for 16.04
- install git-annex-standalone
- install virtualenv
- install python3-all-dev (for twisted for scrapy)
- install libexempi3 (for xmp extractor)
- pip install datalad-neuroimaging

**Comment by yarikoptic** [comment]
Iirc problem wasn't installing but functioning - some syscall needed by git annex were not implemented. Did you have a chance to run eg our tests?

**Comment by yarikoptic** [comment]
and as soon as we release/package for debian installation worth going to documentation would be `apt-get install datalad-neuroimaging` I guess

**Comment by mih** [comment]
re tests: we ran a few that past (didn't have enough time). We tried only a few things of real use too. Will do more later.

Would be good to get a sense of what kind of functionality is not supported "by design".

**Comment by yarikoptic** [comment]
if that is within Ubuntu shell on windows, then sounds correct.  We could detect "on_windows_linux_shell" somehow I guess if needed

**Comment by joeyh** [comment]
Last I tried it, git-annex test passed 100% in this environment.

There were some syscall problems preventing the assistant and webapp from working. May have been fixed since then.

**Comment by mih** [comment]
@joeyh great. I had the impression that execution is rather slow in win10 -- about 50% the speed. But I haven't carefully compared the host machine capabilities.

**Comment by joeyh** [comment]
git-annex from the standalone tarball is very slow when run inside WSL. I think it has something to do with runshell being a little slow there (due to syscall emulation etc) and getting run repeatedly. Installed with apt, it's much faster.

**Comment by yarikoptic** [comment]
not sure if anything to be added here, thus closing
