### ISSUE TITLE
Returning a non-zero exit code in the cli, results in the python api

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2479]
@yarikoptic and I wanted to make the `check_dates` extension have the following behavior:

1.  When called via the CLI, dump "hits" (offending dates) to stdout as json records and exit with some particular **non-zero exit code** to indicate that there were hits.

2.  When called via the Python api, return the hits.

But I couldn't figure out how to make that work.  To get a non-zero exit code, I could abuse a `CommandError`, which is handled specifically in datalad/cmdline.main.py:

<https://github.com/datalad/datalad/blob/43e37edc6f00b6edf250f1edc0116b9bd62f3f87/datalad/cmdline/main.py#L400-L414>

But then calls via the python interface would fail with a `CommandError` exception when there are any hits.

Am I overlooking an easy way to accomplish this using datalad's interface for commands?

**Comment by yarikoptic** [comment]
Because a grumpy Russian was demanding it! In short: because it is how check/test commands should behave in command line - fail (exit with non 0) if the check fails. Otherwise scripting using them becomes more painful, requiring output processing instead of just simple execution.

**Comment by bpoldrack** [comment]
If the "error" status in the results still is fine, than `--on-failure=continue` should do, I guess. So you would still yield all results despite them being reported as "error" and get your non-zero exit code at the end.

**Comment by kyleam** [comment]
@bpoldrack  Thanks for your comments.

> Why do you need the non-exit code in the first place and don't just return results (as json) with status "error"? Just saying, that the "indication" sounds somewhat superfluous

@yarikoptic already gave the rationale, but yes it is strictly unnecessary for determining the "hits".  From the json records, it is already possible to determine what the hits are, and, with the default renderer, only hits are displayed on stdout.

> If the "error" status in the results still is fine, than --on-failure=continue should do, I guess. So you would still yield all results despite them being reported as "error" and get your non-zero exit code at the end.

Hmm, yeah, I'd guess that things could be rearranged in that manner, but that's a bit tricky because there is a legitimate "error" case where we want to abort.  Also, while I'm OK using a specific non-zero exit code as a signal, I'm not too keen on marking a hit as an error.

@yarikoptic, IMO signaling with a non-zero exit code isn't worth recasting the results as errors.

**Comment by bpoldrack** [comment]
> Also, while I'm OK using a specific non-zero exit code as a signal, I'm not too keen on marking a hit as an error.

Well, that's the main issue here, I guess. You guys want it both ways: The command should behave like other "test/check" commands in that it returns non-zero (usually indicating some kind of error, while simultaneously having non-error results in addition. I lean towards finding that inconsistent. If the command is supposed to test a condition, then violating things are errors. Or it is more a reporting command, then non-zero exit is inappropriate as long as there is no real error.

How about having an option `--test` or something, that exits non-zero and has just that one result "condition not met"?

**Comment by yarikoptic** [comment]
I don't see any inconsistency. Consult your favorite popular command (eg grep, nosetests) for examples ;-)

**Comment by bpoldrack** [comment]
The inconsistency is in not giving results the status "error" if they report something, that means "Check failed for this". How does it make sense to say `check_dates` and then have a response `some-notion-of-failed (ok)`? At least from my point of view that's weird.

However, technically, you need to give a feedback in case of the CLI, but not in case of python API, which is ruling out an Exception. Despite me being not comfortable with the approach it's still of academic interest, whether there is an actual solution to this. ;-)

I think the only way is to enhance `cmdline/main.py` in a way, that you can return some special result that will be evaluated therein and determines the exit code.

**Comment by bpoldrack** [comment]
Plus: We would properly need to apply a result filter (to swallow that special one) in case of python API. Basically adding a special result filter to whatever is specified when commands are imported to `datalad.api`. Not going to be neat ...

**Comment by bpoldrack** [comment]
Or: We could have an additional status `failed` (or similar), that might feel more appropriate for you to use in that case, and that (different than `error` and its `--on-failure`) would result in a non-exit code no matter what.

**Comment by kyleam** [comment]
> Well, that's the main issue here, I guess. You guys want it both ways: The command should behave like other "test/check" commands in that it returns non-zero (usually indicating some kind of error), while simultaneously having non-error results in addition.

I don't disagree with that, but I think it could be viewed another way.  Common command line tools use exit codes for multiple purposes, with the specific code documented as having a specific mean.   So, it could be that the program failed (one specific exit code) or that a check failed (some other specific exit code).  But in the datalad result system, there isn't this distinction.

> Or: We could have an additional status failed (or similar), that might feel more appropriate for you to use in that case, and that (different than error and its --on-failure) would result in a non-exit code no matter what.

I think I'd vote for this one because it addresses the distinction above.  Of course, whether getting the superfluous exit code is worth the effort is another question.

**Comment by mih** [comment]
FTR: Adding a new status puts significant additional load on developers. Each command will have to decide what to do, when it sees a `failed` result (which seems like some kind of `ok-error`).

I have the impression, however, that an alternative approach would be doable.

- having error codes for errors (that can turn into exit codes) is a good thing in general, not just for the present use case, and not just for the cmdline API
- but we have to remember that any typical command generates many results, with potentially non-uniform error codes -- so any machinery needs to be able to deal with that
- the distinction between an error and a failed test seems expensive and not useful
- the present switches to handle errors seem insufficient, in particular it seems that for the present use-case we want an `on_failure=('ignore', action='check-dates')` to get any errors that match these criteria (think the method we use for `assert_results_count()`) past the guards (equally in both Python and cmdline API), and in the very end, and only for the cmdline API have something independent evaluate the error codes in all the result records and produce the one final exit code for the command.

**Comment by mih** [comment]
Closing "question"-type issue with a response, and no further activity.
