### ISSUE TITLE
Run the tests of essential extensions on travis for datalad-core

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2480]
Now that we have extensions we still want to develop everything as a consistent stack of tools. It would be very helpful to have (a selected) of tests run for each extension whenever datalad-core changes.That would avoid the delayed impact of core changes until any test run for an extension repo is performed next.

However, I have no idea if travis can do this easily. It is not really a matrix facet that is needed here. more like a completely different test run.

**Comment by bpoldrack** [comment]
Should be doable. Travis' setup is done per build, so we could have additional ones in the matrix, that would install the respective extension instead of datalad itself and call nose on that package's tests.

**Comment by mih** [comment]
Note that it would need to install Datalad from git (as done now), and only then install the extension via pip from the respective Git repo. Only this way we can test the present extension master state against the propsoed change in datalad.
