### ISSUE TITLE
OPT: even basic datalad command(s) terribly slow to start

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2494]
#### What is the problem?
With all the extensions etc `datalad` cmdline invocation grew unacceptably slow to start.  Here are some timings from a run of `datalad` on smaug (although it is IO busy ATM) which takes over a second.
I have trimmed the boring lines, and the number upfront shows how long it takes from that log line to the next.  We can see that it is something within main `__init__` which takes awhile (unlikely ssh manager takes that long ), and then entry point for neuroimaging loading (I guess since there is not much of log messages within it -- can't tell where exactly 300ms is wasted)
```shell
(git)smaug:~datalad/datalad-neuroimaging[master]git
$> DATALAD_LOG_TIMESTAMP=1 DATALAD_LOG_LEVEL=2 datalad 2>&1 | ../datalad-master/tools/dtime
  572 2018-05-16 10:24:03,788 [Level 5] Instantiating ssh manager
    1 2018-05-16 10:24:04,360 [Level 5] Done importing main __init__
  314 2018-05-16 10:24:04,361 [Level 5] Importing cmdline.main
    1 2018-05-16 10:24:04,675 [Level 5] Done importing cmdline.main
    0 2018-05-16 10:24:04,676 [Level 5] Starting main(None)
   57 2018-05-16 10:24:04,676 [Level 5] Starting to setup_parser
    6 2018-05-16 10:24:04,733 [Level 5] Importing support.network
...
   37 2018-05-16 10:24:04,740 [Level 5] Importing dataset
  320 2018-05-16 10:24:04,777 [DEBUG] Loading entrypoint neuroimaging from datalad.extensions
    2 2018-05-16 10:24:05,097 [Level 5] Importing module datalad.distribution.create
  ...
    0 2018-05-16 10:24:05,207 [DEBUG] Building doc for <class 'datalad.distribution.create_test_dataset.CreateTestDataset'>
  294 2018-05-16 10:24:05,207 [DEBUG] Building doc for <class 'datalad.support.sshrun.SSHRun'>
    6 2018-05-16 10:24:05,501 [DEBUG] Building doc for <class 'datalad_neuroimaging.bids2scidata.BIDS2Scidata'>
...
```
upon invocation of some (in this case `install`) command situation seems to differ a bit:
```shell
$> DATALAD_LOG_TIMESTAMP=1 DATALAD_LOG_LEVEL=2 datalad install -s /// /tmp/123333  2>&1 | ../datalad-master/tools/dtime
    5 2018-05-16 10:30:37,744 [Level 5] Instantiating ssh manager
    0 2018-05-16 10:30:37,749 [Level 5] Done importing main __init__
  286 2018-05-16 10:30:37,749 [Level 5] Importing cmdline.main
    0 2018-05-16 10:30:38,035 [Level 5] Done importing cmdline.main
    0 2018-05-16 10:30:38,035 [Level 5] Starting main(None)
   72 2018-05-16 10:30:38,035 [Level 5] Starting to setup_parser
    9 2018-05-16 10:30:38,107 [Level 5] Importing support.network
...
    2 2018-05-16 10:30:38,117 [DEBUG] parseParameters: Given "with_urls_only : bool, optional
   47 2018-05-16 10:30:38,119 [Level 5] Importing dataset
  303 2018-05-16 10:30:38,166 [DEBUG] Loading entrypoint neuroimaging from datalad.extensions
    2 2018-05-16 10:30:38,469 [Level 5] Importing module datalad.distribution.install
...
    0 2018-05-16 10:30:38,576 [Level 5] Detected url ri
  239 2018-05-16 10:30:38,576 [DEBUG] Git clone from http://datasets.datalad.org/.git to /tmp/123333
    1 2018-05-16 10:30:38,815 [DEBUG] Git clone completed
   18 2018-05-16 10:30:38,816 [Level 9] Running: ['git', 'version']
```
so import of main proceeds faster, we do not build not needed docs, but then still spend a lot while importing cmdline.main somehow and  loading of `neuroimaging` (not really needed for anything here) is taking a good toll.  If we get even more extensions, impact would be even higher! (although installing `crawler` into this added "only" 78ms, so not as bad, but still not good since it is not needed for anything in install)

So I feel that 
- [x] `from pkg_resources import iter_entry_points` should always be delayed until point/func of use to avoid heavy import time impact upon merely importing our submodules (#2495)
- [x] no need to generate full docs if only list of commands need to be presented
- [ ] no need to build docs for classes for which --help is not asked for
- [ ] no need to look at extensions if a command of interest is internal/known.
  - I thought even that eventually we might want to keep a registry of some commands and extensions from which they might come, so we could let user known that `crawl command is provided by datalad-crawler extension. It could be installed via "pip install datalad-crawler"` (patched correspondingly for debian)
- [ ] "extensions" functionality should be loaded "lazily" by `.api` somehow instead of upon every command invocation
- [ ] come back and see if we could do anything about not bothering with ssh manager instantiation (IMHO should be relevant only if we at least work with some Dataset or GitRepo so may be could be done then, need to find an issue where we discussed it before)

**Comment by mih** [comment]
Satisfied for now?

**Comment by yarikoptic** [comment]
to some degree I guess... you want to close it? ok
