### ISSUE TITLE
Allow for "lean" annex views with only files having a content

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#25]
NB I thought I have filed it here but it must have been elsewhere, so backlink will be provided later

`git annex view` provides great functionality to take advantage of meta-data (tags) associated with data files for custom views.  One of the stumble points might often be "installation" of laarge datasets where only a handful of files are actually needed/used.  ATM it results in a directory hierarchy where possibly majority of files are broken links, which makes navigation difficult and non-productive.

It would be great if there was a way to generate a "lean" view where only files with content available are visible.

Somewhat related would be #6, i.e. to carry an update while maintaining a lean view

**Comment by yarikoptic** [comment]
Since @joeyh has mentioned he might be interested to implement such feature straight in git-annex, I will assign to him for now.

**Comment by yarikoptic** [comment]
I believe this issue is addressed by using version 6 mode and adjusted branches, see e.g. https://git-annex.branchable.com/design/adjusted_branches/  although I have not tried yet to see how I could make it into this "lean" view

**Comment by mih** [comment]
This is correct. The is `annex adjust` now, with support for `--hide-missing`, which can be re-executed to update a branch based on current availability.
