### ISSUE TITLE
`uninstall` should be guarded to not remove datasets which have no remote

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#250]
e.g. if created locally... it will be not really uninstall but remove

**Comment by bpoldrack** [comment]
So, we could introduce a --force option, e.g. without force it will not remove a handle, that has no remote. Agree?

**Comment by hanke** [comment]
IMHO we should first clarify what "uninstall" means. Is it perceived like "unregister" for collections? Or like "delete". In the latter case, I would be extra extra careful. Even if it has a remote, it is not clear whether that remote still has all data.

Maybe we should go in safe-mode by default and do:

````
git annex drop .
````

and if that works, we can safely delete the local repo.

**Comment by yarikoptic** [comment]
On October 1, 2015 4:45:34 AM EDT, bpoldrack <notifications@github.com> wrote:
>So, we could introduce a --force option, e.g. without force it will not
>remove a handle, that has no remote. Agree?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/250#issuecomment-144657979

Sounds good

**Comment by yarikoptic** [comment]
On October 1, 2015 5:11:04 AM EDT, Michael Hanke <notifications@github.com> wrote:
>IMHO we should first clarify what "uninstall" means. Is it perceived
>like "unregister" for collections? Or like "delete". In the latter
>case, I would be extra extra careful. Even if it has a remote, it is
>not clear whether that remote still has all data.
>
>Maybe we should go in safe-mode by default and do:
>
>````
>git annex drop .
>````
>
>and if that works, we can safely delete the local repo.
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/250#issuecomment-144665073

Indeed :-)

**Comment by bpoldrack** [comment]
Well, since install-handle creates a local clone and adds it to the local master collection, I thougth uninstall-handle should do the opposite. But I agree that may be isn't the way to go.

**Comment by hanke** [comment]
Will retitle and leave open as a reminder.

**Comment by mih** [comment]
In #796 I implemented the "drop first by default" behavior. Moreover, the removal of an entire repository (i.e. uninstall cannot be undone) requires an additional switch. I consider this safe enough.

Please close! @yarikoptic

**Comment by mih** [comment]
Will help. Closing.
