### ISSUE TITLE
pzliblyma dep needs attention

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2513]
Haven't investigated yet: https://travis-ci.org/datalad/datalad-container/jobs/381627084

**Comment by yarikoptic** [comment]
That is python 3 build - why it is trying to install it via pip?

**Comment by mih** [comment]
Exactly!

**Comment by mih** [comment]
Restarted -crawler test run 18 https://travis-ci.org/datalad/datalad-crawler

No change in code (plain restart, passed before) -- let's see if the breakage comes form the outside.

**Comment by mih** [comment]
No breakage there. So fuck up must be in -container. Only obvious diff is dependency on rc4 instead of rc3.

**Comment by mih** [comment]
Not clear why, but this fixed it: https://github.com/datalad/datalad-container/commit/364e12582eb5fff26eb62394691a306d699d4786
