### ISSUE TITLE
Testrepo setup broken on windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2527]
I never figured out how this is all meant to work, but `_get_testrepos_uris()` doesn't even create the rest repos. And if I enable this (by removing the on_windows test) I end up without any URIs.

Any pointers on where to start with this?

In general many real life use cases work just fine. Our test battery seems to be the primary failure source on windows.

**Comment by mih** [comment]
For now I have adjusted the decorator to `raise SkipTest` on Windows, as there is no chance for any of those tests to pass.

**Comment by yarikoptic** [comment]
well -- there is this line `if not on_windows` (https://github.com/datalad/datalad/blob/master/datalad/tests/utils.py#L762) which might be culprit? it was done by a mysterious
```
Author: unknown <test@nowhere.com>
Date:   Fri Aug 21 05:02:14 2015 -0400

    BF: trying to revert to use online clone of testrepo on windows
```
may be it is time to reconsider his actions? ;)

**Comment by mih** [comment]
I did reconsider, removed this switch in full or part. It leads to other failures that I do not comprehend (e.g. report no test repo specs to remain at all) and gives no additional running test.

**Comment by yarikoptic** [comment]
there is an effort to bring back with_testrepos on Windows at least to some degree (I do not remember which runs were not included on windows): https://github.com/datalad/datalad/pull/2870

**Comment by mih** [comment]
As of today, I had some success in running a test for `clone()` with the `local` flavor of the test repos. Any `network` or `url` flavor depends on key-based access to a machine that I cannot provide ATM.

**Comment by mih** [comment]
Had a closer, sobering look. Generated testrepos seem to be empty. I suspect broken setup due to adjusted branches.

**Comment by mih** [comment]
Made progress with https://github.com/datalad/datalad/pull/3975 Basic testrepos are now generated properlyon a win10 box.

**Comment by mih** [comment]
Here is a commit with the testrepo setup enabled on windows and a bunch of additional tests running. https://github.com/datalad/datalad/pull/3975/commits/2f62fd362d51261e7af752baface70ad4f987730

There is still too much broken to make it worthwhile enabling these permanently, but there is hope now!

**Comment by mih** [comment]
I have now enabled the test repos on windows https://github.com/datalad/datalad/pull/3975. I have manually marked all new test failures as "known".

Here is one common crash type: https://ci.appveyor.com/project/mih/datalad/builds/29840837/job/knf7wvyli124f9ic

```
======================================================================
1583ERROR: datalad.cmdline.tests.test_helpers.test_get_repo_instance_annex
1584----------------------------------------------------------------------
1585Traceback (most recent call last):
1586  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
1587    self.test(*self.arg)
1588  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1195, in newfunc
1589    raise exc_info[1]
1590  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1167, in newfunc
1591    ret = func(*args, **kwargs)
1592  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 761, in newfunc
1593    testrepos_uris = _get_testrepos_uris(regex, flavors_)
1594  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 695, in _get_testrepos_uris
1595    _basic_annex_test_repo.create()
1596  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils_testrepos.py", line 90, in create
1597    self.populate()
1598  File "C:\Miniconda35\envs\test-environment\lib\contextlib.py", line 77, in __exit__
1599    self.gen.throw(type, value, traceback)
1600  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 1173, in swallow_outputs
1601    yield adapter
1602  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils_testrepos.py", line 90, in create
1603    self.populate()
1604  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils_testrepos.py", line 116, in populate
1605    self.repo.add_url_to_file("test-annex.dat", fileurl)
1606  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\gitrepo.py", line 231, in newfunc
1607    return func(self, file_new, *args, **kwargs)
1608  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\annexrepo.py", line 1895, in add_url_to_file
1609    % (url, str(out_json)))
1610datalad.support.exceptions.CommandError: CommandError: command 'addurl'
1611Error, annex reported failure for addurl (url='file://C/Users/appveyor/AppData/Local/Temp/1/datalad_temp_testrepo_6m28kn2c'): {'note': 'to test-annex.dat', 'command': 'addurl', 'success': False, 'file': 'test-annex.dat', 'key': 'SHA256E-s28--2795fb26981c5a687b9bf44930cc220029223f472cea0f0b17274f4473181e7b.dat', 'error-messages': ['git-annex: MoveFileEx ".git\\\\annex\\\\tmp\\\\URL-s28--file&c%%C%Users%appveyor%AppData-97eef9c15974e39702c8c6b35a0243cf" Just ".git\\\\annex\\\\objects\\\\8f8\\\\9ce\\\\SHA256E-s28--2795fb26981c5a687b9bf44930cc220029223f472cea0f0b17274f4473181e7b.dat\\\\SHA256E-s28--2795fb26981c5a687b9bf44930cc220029223f472cea0f0b17274f4473181e7b.dat": does not exist (The system cannot find the path specified.)']}
```

It occurs (mostly, or exclusively?) on appveyor. I have yet to see a single one of them on a readl win10 box -- we really need a more modern test setup...

**Comment by mih** [comment]
There is no general "this cannot possibly work" issue anymore --  but still lots of breakage in the details.
