### ISSUE TITLE
We need a cross-platform convention for paths

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2546]
We have path issues on non-POSIX systems (i.e. Windows). See e.g. #2528 #2531 

One source of problems is how GitPython handles paths on Windows.  For example, our `GitRepo.get_indexed_files()` returns the keys in GitPython's index (which are relative paths within the repository), but they are always POSIX paths.

That conflicts with our apparent assumption that we could simply turn them into absolute paths with `os.path` functions on any platform. Soooo, what shall we do?

1. Always return any path in POSIX conventions
    - shifts a substantial amount of platform dependent code to become a user's responsibility
    - we would have to test/convert any incoming path specification to POSIX

2. Always return platform dependent paths
    - most gentle to users
    - we would have to convert any path specification that needs to become POSIX to get properly tested (for equality, etc.), or needs to get stored in Git (e.g. gitmodules, etc.) ourselves.

I think the responsible choice is (2), while (1) is sending the message "do not use this on non-POSIX platforms" (in which case I would argue that we should declare any effort to get anything to run on windows as futile and discouraged).

**Comment by mih** [comment]
@yarikoptic @kyleam Thoughts?

**Comment by yarikoptic** [comment]
Throughout the code we use is.path.join, which votes 2 afaik

**Comment by mih** [comment]
OK, so decision would be to consider any POSIX path coming out of the low-level API to be a bug (assuming this is the level we want to take care of this, which seems to make sense to me).

**Comment by bpoldrack** [comment]
Yes, except it's supposed to return a (part of) URL, which might confusingly be called `path`. In that case it should still return a "POSIX path" but it needs to be called `url` instead. Just saying, since the implicit assumption that a path can be treated that way is still widespread.

**Comment by yarikoptic** [comment]
yes, making it clear(er) where a "path" component is the "urlpath" (or "posixpath") would be useful!

**Comment by mih** [comment]
So that is settled.

**Comment by mih** [comment]
I am reopening this: https://bytes.com/topic/python/answers/19793-convert-between-windows-style-paths-posix-style-paths

It looks like we are doing it wrong, and NT supports POSIX paths, just not at the command prompt. Hence we might want to rethink our judgement.

**Comment by yarikoptic** [comment]
just 1c in favor of (2) -- users will specify native to the system paths and ideally they should get paths reported to them in the same fashion, otherwise confusions such as https://github.com/datalad/datalad/issues/2643#issuecomment-405036688 might keep happening where the reason for incorrect behavior does not become immediately apparent

**Comment by yarikoptic** [comment]
From the aforementioned link about support of `/` in NT paths (which I've verified briefly to indeed work with basic Python's `open` call) it is not yet clear how "full path" would look like since it must contain the drive letter, and I think it is the MSYS*/MINGW* internal convention on mapping it to `/X/` which also somewhat fails since if there is any single lettered directory (not even conflicting) in the directory they consider `/` it is not made available within this `/` pathname.

**Comment by mih** [comment]
There is not really THE full path. There are DOS paths (with drive letter) and UNC paths, boths are supported by NT

**Comment by yarikoptic** [comment]
heh heh, ok -- call it "absolute" path not a "full" one.
Both conventions (DOS and UNC) are not posix, include server or drive within, and rely on back slashes.  So what am I missing on how they could/should be mapped into POSIX paths for internal manipulations if we were to go "all posix" way? (e.g. "use UNC and replace all backslashes with forward slashes, hip hip hoorra!")

**Comment by mih** [comment]
I think step one is for us to not worry about backslashes at all, as NT handles slashes just fine in both variants of absolute paths. That makes any relative path POSIX compatible. This leaves absolute paths. For those I would be leaning to UNC, but I gind it hard to predict the type and amount of fallout.

**Comment by mih** [comment]
I have now verified that at least from Windows Vista onwards, POSIX paths typed/copied into the windows terminal as arguments of datalad commands yield the desired behavior.

**Comment by mih** [comment]
I spend the day wrangling paths, and I think the core problem would be elegantly solved by using Path instances from `pathlib` (https://docs.python.org/3/library/pathlib.html). A backport for PY2 is available.

I am implementing a demo in https://github.com/datalad/datalad-revolution/pull/1 now.

**Comment by yarikoptic** [comment]
So the idea is to have pathlib's Paths which would be returned/stored (`.path`) throughout the API?

note, backported for python2 package is called pathlib2 (python-pathlib2 in debian)

**Comment by mih** [comment]
https://github.com/datalad/datalad-revolution now uses pathlib for internal handling and sticks with path string in the result records to minimize impact on datalad-core.

Path resolution works a bit different (is guaranteed to become abspath underneath the reference dataset, no matter how originally specified). Path handover dataset<-> is happening in high-level API code (not a low-level decorator) to be able to see the full context, including any descrepancy between dataset and repo paths.

This seems to work quite well on all platforms (incl. Windows). I will close this for now until real-world exposure tells me how for this holds up.

**Comment by yarikoptic** [comment]
What about adding a label fixed-in-revolution and keep it open here since issue remains in this code base
