### ISSUE TITLE
Strange failure on test_install_handle_basic

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#255]
I'm currently experiencing something strange.
That test fails due to the try to create an import branch that is already existing, when installing a handle a second time.
But, this test is sometimes failing and sometimes it isn't. Even if I call it directly via nosetests:

    nosetests -s -v datalad.interface.tests.test_install_handle:test_install_handle_basic

It first fails, but when repeating it several times, it sometimes doesn't fail in between. Sometimes it passes on python2 but fails on python3, sometimes and fails both times. Calling the to be tested command directly works for me. Any ideas?

**Comment by yarikoptic** [comment]
smells like a race condition somewhere.  I failed to replicate with e.g. `for f in {1..10}; do nosetests -s -v datalad.interface.tests.test_install_handle:test_install_handle_basic; done  `
so would be for you to dig in :-/  would it go away if you make it verbose? DATALAD_LOGLEVEL=1 ("good" race conditions often hide away under heavy IO).  If not -- capture both failing and not and then compare.

is that the code where it fails? `self.git_checkout(name=src_name, options='-b')` or...?  may be different/outdated version of GitPython?

**Comment by bpoldrack** [comment]
That's where it fails, yes. But it seems to be an issue with the metadata
itself, which happens to become ambigous due to a mistake I made. I'm about
to fix it - hopefully.

2015-10-05 21:34 GMT+02:00 Yaroslav Halchenko <notifications@github.com>:
