### ISSUE TITLE
Switch from platform conditions to capability conditions

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2553]
ATM we do stuff like `if on_windows`, but we really should be testing for the actual capability within a specific environment and/or repository that we need. The reason is that simple platform switches are inappropriate and imply potentially wrong choices.

Examples:

- no SSH on windows: false #2539 
- no symlinks on windows: false #2536 
- stuff must be in the path if it is available at all: false (git for windows installer makes it configurable what exactly ends up being in the path)
- no useful shell on windows: false (git installer lets you decide whether to go with git-bash or plain windows shell)
- and of course all the combinations of crippled conditions that one can have on any non-windows system

It would probably be best to implement platform checks in the externals system, and enhance the Repo classes with lazily evaluated flags on whether other relevant capabilities are present (e.g. a symlink actually pointing to the target, or being an entity of its own that `realpath()` does not resolve...)

**Comment by yarikoptic** [comment]
makes sense.  We should probably follow annex's suite and record "discovered" (in)capabilities within .git/config

**Comment by mih** [comment]
I wonder if it would be the simplest if we enhance ConfigManager to exec any callable that is passed via `default=` and store its result in the config, before giving it back. A callable can never come from `git config`, so there cannot be confusion.

Which callable (i.e. test) to run for any particular capability, could either come from a central library of tests, or could be specified ad-hoc for rare/unique cases. In both scenarios the config handling could/would be the same.

Given that capabilties could vary across datasets, we should probably give these test callables a mandatory dataset argument.

Having written that, we might just add a dedicated capability test method to ConfigManager and be done with it ;-)

**Comment by mih** [comment]
We are doing something like this in many places now. The most prominent is a `is_managed_branch()` call as an implicit test that all bets are off. No need to keep this issue open any longer.

**Comment by yarikoptic** [comment]
Just FTR: We also have `has_symlink_capability`/`skip_wo_symlink_capability` used by some tests... indeed might be quite nice to formalize it all even further and indeed record in `.git/config` in some dedicated section, e.g. `datalad.capabilities` which could have bool or even more elaborate lists where needed (nothing comes to mind ATM ;))
