### ISSUE TITLE
Updating metadata

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#256]
Current datalad-update command led to confusion, which leads to general questions about how to handle this.
datalad update is intended to just fetch remotes of the local master collection in case of registered collections and/or remotes (i. e. origin) of installed handles/collections.
Another kind of 'update' has to be done, when the metadata of local handle/collection was changed by a command like datalad-describe, so that a collection, the modified handle is in, gets to know about the new metadata. I think this should not be done automatically, since collections don't need to use the metadata, that a handle provides itself. Do we want to have a dedicated command for this purpose? Technically it would make sense to use datalad-import-metadata, but may be in a case like this, that naming is confusing for users. What similiar things do you may be have in mind, that should be considered in that context? Any questions on how things are intended by now?

**Comment by yarikoptic** [comment]
During one of the upcoming hangouts we should review currently accumulated API and clear this up

**Comment by mih** [comment]
Obsolete now.
