### ISSUE TITLE
`run` should get some kind of `--wait` or `--lockfile` switch

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2583]
Which takes some kind of  expression (probably another shell) command that get evaluated and `run` blocks until this expression gets a zero exit code.

Or simpler: `--wait` or `--lockfile` gets the path to a lock file that `run` will create before it starts executing the command (but after it determined the dataset to be clean). It will then block until that lock file is no longer there.

I like the latter!

Use case: Command execution on a cluster system. I have my code and my submit files in the dataset, so all nice and tidy, but `run` will never get the results unless I use some kind of blocking submission. Which would push the duty to find such command for any given batch system onto the user, but any job should be able to `rm` such a file. The file could be (should be) in any location, not just within the dataset to be able to deal with system that do not have a fully shared file system.

**Comment by kyleam** [comment]
I like the lock file approach better too.

@yarikoptic was just talking about this problem last week, so hopefully he can add some thoughts here about what a good solution would look like.

**Comment by yarikoptic** [comment]
Ftr: https://github.com/datalad/datalad/blob/master/datalad/support/locking.py used by special remotes

**Comment by yarikoptic** [comment]
although probably not of concern here for `run` but tricky part could be with anything which ascends the hierarchy of datasets which might then be a reason for the deadlock (depending on the implementation of cause ;-))

**Comment by mih** [comment]
This is obsolete.
