### ISSUE TITLE
Polish and rethink AnnexRepo's addurl functionality

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2585]
This is a dedicated issue for the discussion started in #2501, starting [here](https://github.com/datalad/datalad/pull/2501#issuecomment-391091277).

Some of the main points:

- [ ] The functionality in `AnnexRepo.add_url_to_file` and `AnnexRepo.add_urls` marked as "not implemented" should be implemented

- [ ] `AnnexRepo.add_urls` should use `AnnexRepo.add_url_to_file`

- [ ] `api.download_url` should be used unless there is a specific need for `git annex addurl` (e.g., `--fast`)

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
