### ISSUE TITLE
Dataset methods don't resolve "./path" to current dataset

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2589]
I expected "./path" to be resolved when passed as a path to a dataset method.  "./" is unnecessary, but it's nice in terms of being able to `os.path.join(dirname, path)`, where dirname may be `os.path.curdir`.

But this fails.  As an example:

```python
#!/usr/bin/env python3

import os.path as op
import tempfile
from datalad.api import Dataset

repo = tempfile.mkdtemp()
ds = Dataset(repo).create()

with open(op.join(repo, "foo"), "w") as fh:
    fh.write("ok")
ds.add("./foo")
```

```bash
% /tmp/scratch.py
[INFO   ] Creating a new annex repo at /tmp/tmpk5_0ksad
[WARNING] path not associated with reference dataset
[WARNING] path not associated with any dataset [add(/tmp/foo)]
Traceback (most recent call last):
  File "/tmp/scratch.py", line 15, in <module>
    ds.add("./foo")
  File "/home/kyle/src/python/datalad/datalad/distribution/dataset.py", line 444, in apply_func
    return f(**kwargs)
  File "/home/kyle/src/python/datalad/datalad/interface/utils.py", line 470, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/kyle/src/python/datalad/datalad/interface/utils.py", line 458, in return_func
    results = list(results)
  File "/home/kyle/src/python/datalad/datalad/interface/utils.py", line 446, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'message': 'path not associated with reference dataset', 'status': 'impossible', 'action': 'add', 'refds': '/tmp/tmpk5_0ksad'}, {'status': 'impossible', 'raw_input': True, 'action': 'add', 'orig_request': './foo', 'message': 'path not associated with any dataset', 'state': 'absent', 'path': '/tmp/foo', 'refds': '/tmp/tmpk5_0ksad'}]
```

The path is resolved to the current directory rather than the dataset directory.

**Comment by yarikoptic** [comment]
I believe that it is a feature... If dataset is known and relative path, but not starting with curdir or pardir, then from top of the dataset, otherwise from current directory.

**Comment by mih** [comment]
Yes, it is a feature.

**Comment by kyleam** [comment]
Eh, a feature that makes "this" different than "./this"? IMO there shouldn't be a magical distinction between the two.

**Comment by mih** [comment]
Ah, I misread this. I read "not resolved wrt relative path, but relative path to dataset".

Maybe a good time to write down a convention to stick to (ping #1819)

**Comment by yarikoptic** [comment]
Yes, we need to document the convention, or get away from it (echoing @kyleam displease with it, and original use case where passed directory is just curdir ie .) but then there would be no way to specify "file in the current directory" while working with dataset's methods.

**Comment by mih** [comment]
I thought to fix this such that `./path` is equivalent to `path`, but it seems more fundamental change is desired. So far I was under the impression that "specify 'file in the current directory' while working with dataset's methods" is not a frequent use case, as we only work with absolute paths internally and generally produce portable code that uses the location of a dataset as *the* reference and not some PWD in some relation to a dataset.

**Comment by yarikoptic** [comment]
>  So far I was under the impression that "specify 'file in the current directory' while working with dataset's methods" is not a frequent use case

I guess as infrequent as adding a subdataset within a subdirectory, while being in that subdirectory. 
I guess workaround could be "you have to specify full paths" but it wouldn't scale if there are multiple entries.   I do feel that there were other, similar to `add` usecases mandating to use `-d .` or alike (`remove`?) but cannot recall since do not use them often.
Overall -- I do think that ./path vs path distinction is ugly and not well documented and confusing.  But I fear that inability to work in command line within subdirectories (our tests really do not cover those use cases that often) without being able to specify current short paths would bite even more.

**Comment by mih** [comment]
Now we are talking past each other. You were talking about "dataset methods" -- that is an invalid concept for the cmdline. I considered the "./path vs path distinction" a bug that I wanted to fix. However, if dataset methods shall start operating relative to the PWD and not relative to the dataset root this complicates the issue massively. So what is this bug about?

**Comment by kyleam** [comment]
With #3435, `save` would no longer treat "./path" and "path" differently when passed a dataset instance.  Closing this issue, because if gh-3435 is merged this can be considered fixed (at least in commands that don't use annotate_paths) and if it isn't merged this can be considered "won't fix".
