### ISSUE TITLE
Urgent: `run-procedure` command

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2593]
More and more stuff is creeping into the code base that is concerned with setting up datasets for particular use cases. We have long identified the need to have some kind of dataset templates, to be able to do `datalad create --template howIneedittobe`. But no effort ever got there.

So let me propose something simple, with little required effort and high potential:

- a template is a tarball (but see the end)
- such tarball get's extracted at the location of a just created dataset (think `create_tree`). It is extracted after creation so the flags like `--force` still work as desired.
- after extraction a Python script that is located in the root of the tarball (with a special name, maybe `.configure`) is executed, the sole argument being the absolute path of the dataset  and performs arbitrary (re-)configurations, additions, whatever
- this script can use different interpreters (python for platform independence, bash for simplicity)
- after the script is done the results are commited -- in practice this means we use `run` to perform this step
- such template tarballs are looked up at a configurable set of locations (system, user)
- a tarball doesn't actually need to be a tarball, but can also just be the configure

- `create` should be able to execute multiple templates sequentially, so we can orthogonalize the scenarios we want to support.

afterwards anybody can come up with and share there preferred dataset setups.

### candidates for API removal after this works:

- `create(native_metadata)`
- `create(text_no_annex)`
- completely discontinue the Python-only plugin interface code and implementations: either proper commands or this new one for any given functionality

### other related aspects
- entire business of inheriting configuration from a parent dataset
- this is basically an interface for canned procedures. Configuration of datasets is just one flavor of where this functionality is useful. I think what this will lead to is the return of the `--run-before/after` functionality that we briefly enjoyed in the API. This time however, there is no need to go through plugins or something as complicated, because we have `run` now. This will enable us to even implement "canned procedures" that require input arguments.

### conclusion

So we end up with a new command `run-procedure` that sorts out, how such a script needs to be executed, and tailors a call to `run` to execute it (analog to `containers-run` but without containtainers). That means we can support extensions of datalad functionality that do not require going through the Python API.

One aspect would need a further extension of the `run` API: ATM we require a clean dataset before `run` does anything. But a simple `add` can work with a dirty dataset just fine. Nobody says that a canned procedure must not create datalad commands directly and must rely on `run` to capture all the changes. So we either need to extend the `run` API to support all the running aspects without the result capture (i.e. a mere frontend for the `Runner` class). Or we need to expose and reuse the pieces of `run` that do that and also use them for `run-procedure`. I'd prefer to first solution, as the handling of `--inputs` and `--outputs` is already *very* convenient.

@kyleam what do you think?

**Comment by bpoldrack** [comment]
And FTR: tarball (or any kind of archive) should be an option indeed.

**Comment by kyleam** [comment]
I'm still digesting this, especially since I'm not really familiar with the previous thoughts/attempts in this direction, but it sounds like a good approach.

> So we either need to extend the run API to support all the running aspects without the result capture (i.e. a mere frontend for the Runner class). Or we need to expose and reuse the pieces of run that do that and also use them for run-procedure. I'd prefer to first solution

IIUC the first option seems OK to me -- essentially a flag that says "don't complain if the repo is dirty and don't save", right?

**Comment by mih** [comment]
@kyleam yes, exactly. Don't complain, don't save, leave everything to the commands you are running.

**Comment by mih** [comment]
Few more thoughts on the to-be-implemented `run` flag. We would need something that enabled a more surgical operation than what `run` supports right now.

Status quo:
- check and fail on any pre-existing modification
- capture ANY modification and commit

Desired:
- check and fail on any pre-existing modification of any *specified* `inputs`/`outputs`
- capture any modification of a *specified* `output`

Essentially a switch to disable "I'll do it for you" and turn on "You tell me exactly what I shall do".

This should be a useful functionality for `run` regardless of this present context (it enables operation more in line with the behavior of other core commands). In this context of `run-procedures` it would solve the problem by not calling `run` with any `input`/`output` option (hence no checks), but still enable additional `run` calls with such options as part of any procedure script.

**Comment by kyleam** [comment]
> Essentially a switch to disable "I'll do it for you" and turn on "You tell me exactly what I shall do".
>
> This should be a useful functionality for run regardless of this present context [...]

I agree.

>  In this context of run-procedures it would solve the problem by not calling run with any input/output option (hence no checks)

I still think there might be a need for the "don't save" part of the "don't complain, don't save" flag.  For example, this would let a caller group conceptually related outputs of different runs into a single commit (losing the run record, of course).

**Comment by mih** [comment]
@kyleam I think we are on the same page already. Let me lay out the core cases, and let's call the new flag `--strict`:

1. `run`
   - repo must be clean on start
   - nothing obtained, nothing unlocked
   - all changes are commited at the end

2. `run --input`
   - inputs are obtained, otherwise like (1)

3. `run -- output`
   - outputs are unlocked, otherwise like (2)

4. run --strict
   - repo can be dirty on start
   - nothing obtained, nothing unlocked
   - NO changes are commited at the end

5. `run --strict --input`
   - inputs are obtained, otherwise like (4)
   - (possibly fail on absence of any inputs, but not sure yet if that helps with any use case)

6. `run -- output`
   - outputs are unlocked
   - only modifications of specified outputs are committed
   - otherwise like (4)

>  I still think there might be a need for the "don't save" part of the "don't complain, don't save" flag. For example, this would let a caller group conceptually related outputs of different runs into a single commit (losing the run record, of course).

So in my plan above "no save" equals not giving any outputs in conjunction with `--strict`.

The name `strict` is not optimal, but cannot come up with a better one right now.

**Comment by kyleam** [comment]
Michael Hanke <notifications@github.com> writes:

> @kyleam I think we are on the same page already. Let me lay out the core cases, and let's call the new flag `--strict`:

Thanks for outlining the details.  Makes sense to me.

> The name `strict` is not optimal, but cannot come up with a better one right now.

Hmm, yeah... it seems strict for the outputs ("only save these"), but I
view the "allow modifications" part as relaxed rather than strict.
Perhaps "--explicit" because the caller is expected to explicitly
provide both the inputs and outputs?

**Comment by mih** [comment]
I like `explicit`!

I started the implementation here: https://github.com/datalad/datalad/pull/2603

**Comment by mih** [comment]
Had one more realization. `run` should probably not enforce the presence of an installed dataset, when it does not actually need one, because it does not try to make a commit, i.e. with `explicit=True` and `output=None`.

**Comment by bpoldrack** [comment]
Re no dataset required:

In a way that makes sense. On the other hand: Even if there's nothing to commit, there might still be something to get/unlock. And if not so: Why would you want to use `datalad-run` at all, if you don't run it on a dataset? How would that be different from just calling whatever you want to run without `datalad-run`?

**Comment by mih** [comment]
Because if I cannot use `run` I have to use `Runner` and therefore almost double the size of the implementation of `run-procedure`.

If there is something to `unlock` it mean that `output` has to be given, and if it is, fail on `dataset=None`.

**Comment by mih** [comment]
I am cutting the answers short to keep it manageable in this forum (we better talk about this in a meeting).

Importantly, procedures implement templating, but they are not the same thing. Hence the argument whether a particular procedure does something that counts as a template does not really apply here.

> template overlays

Yes, multiple procedures can run after one another (already in #2603) -- achieving the desired effect without being "template overlays".

> `allow_dirty`

This seems to be a topic of much and surprising controversy. We need this, but it seems the envisioned approach is apparently unacceptable.

> stretching analogy

As said above, there is no analogy to be stretched. I removed the term "template" form the title to make it more obvious.

**Comment by mih** [comment]
One more thought: Another issue with the current options of `create` (`--text-no-annex` and friends) is that they are only available in `create`. However, in real life I frequently find myself in need of later reconfiguration of a dataset, and doing that via hand editing files. Procedures can do that in a more reliable way.

**Comment by mih** [comment]
FTR: The original intend of this issue has been resolved with #2603 It is probably better to take individual aspects brought up here into dedicated issues if they require further work.
