### ISSUE TITLE
allow to drop "old" files (e.g. not referenced after commit X)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#26]
I wondered if there is a convenience construct already which would allow to drop (may be forcefully) some files which are no longer "of interest".

use case: carrying out an analysis while keeping results under git-annex control.  With reiterations of the analyses a pile of results accumulates but may be majority of them is not even worth keeping at all (not just locally).  It would be nice to have ability to drop all the load which e.g. is not referenced by any commit after X (in a given branch, situation with multiple branches might be trickier)

**Comment by hanke** [comment]
I just "discovered" this use case myself. However, in my case a simple "not referenced after commit X" is not enough. I have a large chunk of data that got annex'ed after some defined state of a data set that I need to preserve in history, but in the meantime it became obsolete and got replaced. I think what we might want is some kind of history squashing between commits X and Y.

**Comment by joeyh** [comment]
Currently git-annex unused assumes that all "important" revisions of files will have a tag or a branch pointing at them. Files for intermediate revisions are unused and can be dropped with dropunused.

The only alternative approach I can think of using the "unused" approach is to make git annex unused find only files that are referred to by no commits at all. Then you'd rebase your branch to remove commits that pointed to now-obsolete files. Fundamentally git-annex unused needs to use something for reference counting to decide which files are unused, and branches/tags and commits are the only candidates..

I think that might be an interesting mode for git-annex unused, although difficult to implement efficiently. I don't know if it meets your use case though.

It might as well be that your use case can be handled by keeping tags/branches pointing at the files you want to keep, and letting the intermediate/temp files drop out by git-annex unused.

Of course, some kind of `git annex drop --all --before-commit XXX --force` could be added. Avoid the reference counting approach and have the user manually tell git-annex what to drop. Implementing --before-commit efficiently seems hard though.

Using metadata might be another approach. You could tag files created by today's analysis (`git annex metadata -t analysis-12-may`), and then drop files matching that tag when starting the next day's analysis.

One thing both the last paragraphs need is `git annex drop --all` which is not currently implemented. So, I think I should implement that as a first step!

**Comment by joeyh** [comment]
drop --all implemented

**Comment by yarikoptic** [comment]
thanks @joeyh for the --all .  Let me bring another use-case to the table to may be make the necessity even clearer.  We would like to "install" data with annexes (just one way, no sync back of information on availability locally etc) and then "upgrade" them.  During "upgrade" we will fetch all needed new files/versions and then would like to drop all previously used but now not referenced in the HEAD keys, regardless either they are present on the remote or not, and regardless either they were mentioned in any previous tag -- why to drag that load along if we went forward, right? ;) that is where smth like ```drop --all --before-commit XXX --force``` would be valuable BUT it needs to make sure to not drop any file referenced also after XXX ;)

**Comment by joeyh** [comment]
Yaroslav's use case could be handled easily by extending `git annex
unused` with an option to specify the branches/tags that are "used"; all
other content not pointed to by a used branch/tag would then be handled
as unused and could be dropped or moved to archive, or whatever.

Is that the primary use case, or are there other ones?

Proposal for such an option to git-annex unused:
http://git-annex.branchable.com/todo/unused_by_refspec/

-- 
see shy jo

**Comment by joeyh** [comment]
http://git-annex.branchable.com/todo/unused_by_refspec/ is implemented now, and I think yarikoptic likes it. :)

**Comment by yarikoptic** [comment]
as it got implemented, closing this one.
Cheers!
