### ISSUE TITLE
whereis without argument (or with explicit --all) should list all handles

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#260]
I know that I can pipe

```
$> datalad list-handles | xargs -n 1 datalad whereis 
/home/yoh/proj/datalad/datalad-debian/docs/examples/forrest_gump
/home/yoh/proj/datalad/datalad/repos/sfn2015
/home/yoh/proj/datalad/datalad-debian/docs/examples/haxby2001
/home/yoh/proj/datalad/datalad-debian/docs/examples/tutorial_data
/tmp/forrest_gump2
/home/yoh/proj/datalad/datalad-debian/docs/examples/mnist
```

but it is not user friendly... also note that if multiple names provided, it is bails.

In --all mode it might be preferable to prepend with the handle name, e.g.

```
$> datalad list-handles | while read h; do echo -n "$h ";  datalad whereis $h; done
forrest_gump /home/yoh/proj/datalad/datalad-debian/docs/examples/forrest_gump
sfn2015 /home/yoh/proj/datalad/datalad/repos/sfn2015
haxby2001 /home/yoh/proj/datalad/datalad-debian/docs/examples/haxby2001
tutorial_data /home/yoh/proj/datalad/datalad-debian/docs/examples/tutorial_data
forrest_gump2 /tmp/forrest_gump2
mnist /home/yoh/proj/datalad/datalad-debian/docs/examples/mnist
```

**Comment by bpoldrack** [comment]
What about an option --whereis or --locations for the list-handles command instead?

**Comment by yarikoptic** [comment]
On Mon, 12 Oct 2015, Benjamin Poldrack wrote:

> What about an option --whereis or --locations for the list-handles command
> instead?

indeed -- might be even a better choice.  thanks!

we could even add (I thought I have already wishlisted somewhere) --ls
which would make output even more verbose, listing e.g. sizes of
local/total as reported by git annex, date of last commit, git describe etc

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by bpoldrack** [comment]
So, since we apparently agree on integrating it in list-handles instead, could be closed?

**Comment by mih** [comment]
Closing, there is no `whereis` command (anymore).
