### ISSUE TITLE
Windows test logging setup broken

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2606]
Logging in the test suite uses StringIO, but StringIO has no working `.fileno()`:

```
(Pdb) stdout.fileno()
*** io.UnsupportedOperation: fileno
```

Apparently this is known. From cmd.py:

```
        # TODO: if outputstream is sys.stdout and that one is set to StringIO
        #       we have to "shim" it with something providing fileno().
        # This happens when we do not swallow outputs, while allowing nosetest's
        # StringIO to be provided as stdout, crashing the Popen requiring
        # fileno().  In out swallow_outputs, we just use temporary files
        # to overcome this problem.
        # For now necessary test code should be wrapped into swallow_outputs cm
        # to avoid the problem
 ```

I am not clear on why this is NOT a problem on Linux (but happens on Windows all the time).

Some guidance would be appreciated.

**Comment by mih** [comment]
Maybe `ignore_nose_capturing_stdout` would help, but why only needed on windows...

**Comment by mih** [comment]
A second aspect is that `swallow_logs` does not work as expected on windows. A setup like:

```
with swallow_logs(new_level=logging.DEBUG) as cml:
    ds.run("echo blah", outputs=["not-there"]
```
sucessfully switches on DEBUG, but dumps them to the screen. And with the max buffer size of the windows terminal (999 lines) it is a true pleasure to figure out what is happening;-)

**Comment by yarikoptic** [comment]
Try commenting out colorama imports and see if anything changes... I think it is the only (other) thing which messes with stdout and Windows specific

**Comment by mih** [comment]
Windows testing no longer has this issue.
