### ISSUE TITLE
Need a dedicated test for having a custom results renderer

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2617]
Coverage in pr would be one line less than in master according to results in https://codecov.io/gh/datalad/datalad/pull/2613/changes for the https://github.com/datalad/datalad/pull/2613
That interferes with ability to merge on the phone

**Comment by mih** [comment]
The codecov link doesn't work anymore. Would be good to know which piece of code is not covered.

**Comment by mih** [comment]
I am closing this issue now. It is unclear what the original problem was, and it is unlikely that it is a significant one, given the time passed.
