### ISSUE TITLE
Limiting to 20 hits before filtering by type is "suboptimal"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2639]
#### What is the problem?
Didn't analyze in detail but just now got:
```shell
$> datalad --report-type file search --mode egrep MRI 
[INFO   ] Reached the limit of 20 top matches, there could be more which were not reported. 
action summary:
  search (ok: 20)
```
which is confusing/suboptimal at least to me-a-newbie-user

`egrep` doesn't have "syntax" to specify what kind of an entry to consider (file vs dataset), so the only way to filter is by report-type.  But that one

I am not sure if anything could be done given current architecture, but decided to check... may be if there were no "built-in" limit for egrep and other dummy search backends which would just keep yielding than theoretically limiting could be done (if needed at all) at the "process results" stage?

**Comment by mih** [comment]
I think your analysis is correct. In the `egrep` case it would make sense to not have any result limiter.
