### ISSUE TITLE
Figure out scalable way to publish .datalad/metadata for the collection

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2645]
#### What is the problem?
ATM  if someone calls `datalad install -g ///openfmri/ds000001` without even carying about metadata, it would lead to a failed execution since some metadata files which were not published.

They were not published since now some metadata objects files might get into annex. We have to  either instruct git annex via wanted (gets complicated if wanted is already set to some expression) or be `publish` needs to get invoked directly with those paths in `publish` call so they get copied to the remote.

What do you think should be the way to set it up for new repos/siblings?

**Comment by mih** [comment]
Closing "question"-type issue with a response, and no further activity.
