### ISSUE TITLE
Get rid of GitPython

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2654]
"Not sure if we are better or worse after such move" is the common response to that. Here is some stuff for the "better" part:

- Failing (randomly) test(s?): Ref 'a7b0fde' did not resolve to an object #2550 
- Disable batched annex on windows? (also on inability to rmtree etc due to locked files) #2518
- Not ready for parallel processing #1927
- GitPython doesn't support WorkTree #753
- some progress indication for "install" of a dataset #1564

**Comment by yarikoptic** [comment]
Overall I feel that then we would just reimplement, and possibly not better/and slower, some portions of GitPython for little to know benefit.
Re failing test -- we will find a workaround if my assumption of auto.gc screwing it up

We do not want to disable batched processes -- we just want to be in control ;-)  Locked files -- need to find leftovers which leave them open, and handle them.  Did you try that `DATALAD_ASSERT_NO_OPEN_FILES` which was cooked up for this reason and also already helped to identify/fix some (I think it was those batched git calls)

worktree is indeed a "valuable one", but I forgot -- does git-annex support worktree?  I thought not, and then the whole issue is of limited applicability/interest.  I rarely (if ever) use datalad commands on worktree'ed development repositories

progress -- I guess might be better just to contribute than to re-implement.

paralell processing -- I think it was just a generic `'git` issue which would lock repo for its operations, not anyhow GitPython's fault.

**Comment by mih** [comment]
GitPython is what is between us and a stateless system. I cannot see any feature that it provides that we actually need or use. I will close this, as there seems to be general resistance to overhaul any low-level code.
