### ISSUE TITLE
Paradigm shift: --nosave -> --amend ?!

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2657]
Over the past year we have gravitated towards a model where we recommend  (and sometimes require) datasets to be clean. In the context of #2428 I keep thinking about one source of complications that we are "causing" ourselves: `add --nosave`.

This is a very useful feature for people that care about "readability" of a datasets history. I use this pretty much every day. However, I noticed that I do the following:

```
datalad add ... --nosave
...
git commit
```

where the first command stages my addition, and the final commit creates the commit and gets the dataset clean. I do this, because it is the only reliable way to achieve the outcome, given the various complications in the behavior of `add` and `save.

This has two issues:

1. It breaks the paradigm, as the dataset is not clean in between the command (which might correspond to a loooong time, with intermediate memory loss on what this was about).
2. it pushes me (and by extension any datalad user) to use Git directly instead of DataLad

I propose to:

1. discontinue the `save=` option
2. replace it (and potentially enhance other commands) with an `--amend` flag.

This will achieve a few things:
- anyone can commit any change right away, and incrementally build up changesets with `--amend` across individual command calls
- as a consequence a dataset will tend to be clean more often
- users can stay in the DataLad world for this basic management task

If we go down this path, there is even less reason for keeping `add/save` as two separate commands.

**Comment by yarikoptic** [comment]
Why do you use `git commit` and not `datalad save` in the 2nd one?  

I think adding `--amend` shouldn't require killing `--nosave` just for the sake of some kind of "purity".  They both could coexist and I see use cases for using both.

**Comment by mih** [comment]
The point was to simplify the API, not adding even more options. Closing for now.
