### ISSUE TITLE
Use case question: how to contribute a file via a PR without annex

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2666]
If you have a plain git repo on github you can add a file to it via a PR (simply uploading the file to Github via the web interface). Is there any way to provide the same functionality, but have the PR add the file to the annex -- **without having to have a annex installation somewhere on a local machine**.

**Comment by yarikoptic** [comment]
So you are asking for a functionality support from web portal. Sounds reasonable to check/add to gin. For GitHub we could may be somehow make Travis react on some special annotation in the process, which would do annex addurl based on the info in PR description or alike, and which would then submit two new prs with corresponding changes to master and GitHub branches or something like that.   But it all sounds too complex to be robust
