### ISSUE TITLE
datalad.testing to provide helpers for developers to use DataLad

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2667]
It came up in the context of heudiconv tests which already use DataLad to download a sample dataset for testing.  The problem is that we do not have any type of fixture to share the same dataset across multiple runs of tests so it downloads it over and over again.  Instead of coming up with a (pytest) fixture we (with @leej3) thought it would be nice if datalad provided `.testing` module (similar to the one in numpy and other toolkits like pymvpa) which either provided testing platform specific fixtures or just helper functions like `get_testing_dataset("///openfmri/ds0000001", version="1.0.0-or-hexsha", get='sub*')`

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
