### ISSUE TITLE
Interoperability with GIN-hosting

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2680]
Datasets hosted with/at GIN https://web.gin.g-node.org should be working nicely with DataLad. However, there are a few things that needs to polish:

- the GIN webUI only offers "GIN" and "SSH" access (not sure if anonymous HTTP is intentionally unavailable). This means that DataLad users need to register, generate, and upload an SSH key to be able to `datalad install` from GIN. That seems needlessly complicated, but we might not be able to do anything about it at our end.

- the "public" datasets use datacite as metadata standard (dataset-level), but in the YAML file format flavor. At present DataLad only understands the XML flavor.

- some datasets contain the actual data files as ZIP archives (e.g. https://web.gin.g-node.org/bendalab/Henninger2017_electrosensory), maybe we can have a helper that sifts through such a dataset, and unpacks the archives (in the spirit of add-archive).

New dev contact is @achilleas-k

Tasks (from must-have to nice-to-have)

- [x] enable read access to annex'ed files (see below for failure report)
- [x] enable annex `copy --to` operations
- [x] add CI test to make sure that datalad and GIN remain interoperable (we have approval to host small test datasets and access them for CI purposes)
- [x] enable anonymous read access (see https://github.com/datalad/datalad/issues/2680#issuecomment-412152760)
- [ ] enable programmatic creation of repos (analog to what we have for SSH server, GitHub and GitLab, ie. `create-sibling...`)
- [ ] check what of the GIN client functionality we should wrap (or reimplement) to make it fit into datalad's API
- [ ] check to which degree DataLad can work (and be advertised) as an alternative GIN client: https://gin.g-node.org/G-Node/Info/wiki/GinClientHelp

**Comment by mih** [comment]
Had a productive chat with @cgars (thanks!). They will try to provide a URL that datalad can use for pull access, so we can treat the GIN service as a type-Git special remote, in the same way that we do it for SSH webservers.

There is still a question of whether we have to generate that URL from a GIN ID, but that should be easy to do.

**Comment by mih** [comment]
OK, trying to pick this up again. Here is the state of things regarding regular SSH-based access:

```
$ datalad install git@gin.g-node.org:/ddrise/high-gamma-dataset.git 
[INFO   ] Cloning git@gin.g-node.org:/ddrise/high-gamma-dataset.git into '/tmp/high-gamma-dataset' 
Warning: Permanently added the ECDSA host key for IP address '141.84.41.219' to the list of known hosts.
install(ok): /tmp/high-gamma-dataset (dataset) 
$ datalad status --annex all
28 annex'd files (0.0 B/23.0 GB present/total size)

$ datalad -l debug get data/test/1.mat
[DEBUG  ] Command line args 1st pass. Parsed: Namespace() Unparsed: ['get', 'data/test/1.mat'] 
[DEBUG  ] Discovering plugins 
[DEBUG  ] Building doc for <class 'datalad.interface.annotate_paths.AnnotatePaths'> 
[DEBUG  ] Building doc for <class 'datalad.distribution.clone.Clone'> 
[DEBUG  ] Building doc for <class 'datalad.distribution.get.Get'> 
[DEBUG  ] Parsing known args among ['/home/mih/env/datalad3-dev/bin/datalad', '-l', 'debug', 'get', 'data/test/1.mat'] 
[DEBUG  ] Determined class of decorated function: <class 'datalad.distribution.get.Get'> 
[DEBUG  ] Determined class of decorated function: <class 'datalad.interface.annotate_paths.AnnotatePaths'> 
[DEBUG  ] Determine what files match the query to work with 
[Level 11] Failed to run ['git-annex', 'get', '-c', 'remote.origin.annex-ssh-options=-o ControlMaster=auto -S /home/mih/.cache/datalad/sockets/d23394af', '--json', '--json-progress', '-J4', '--', 'data/test/1.mat'] under '/tmp/high-gamma-dataset'. Exit code=1. 
[WARNING] Running get resulted in stderr output: git-annex: get: 1 failed
 
[DEBUG  ] received JSON result from annex: {'command': 'get', 'wanted': [{'here': False, 'uuid': '1226bda2-5981-468c-95d1-8a74b5ab3dc9', 'description': 'annex.backend'}, {'here': False, 'uuid': '4c447cb8-a897-4d73-9f3d-e105dee3a029', 'description': 'git@d675242d8c76:~/tmp/appdata/tmp/local-repo/432'}, {'here': False, 'uuid': 'fb9320bf-20a4-4443-b292-e6b882773c73', 'description': 'git@6f72981f1cdf:~/repos/robintibor/high-gamma-dataset.git'}], 'note': 'not available\nTry making some of these repositories available:\n\t1226bda2-5981-468c-95d1-8a74b5ab3dc9 -- annex.backend\n \t4c447cb8-a897-4d73-9f3d-e105dee3a029 -- git@d675242d8c76:~/tmp/appdata/tmp/local-repo/432\n \tfb9320bf-20a4-4443-b292-e6b882773c73 -- git@6f72981f1cdf:~/repos/robintibor/high-gamma-dataset.git\n', 'skipped': [], 'success': False, 'key': 'MD5-s297068703--1d1184d4a026fba9d79d16b9a26cd3bb', 'file': 'data/test/1.mat'} 
[ERROR  ] not available; Try making some of these repositories available:;      1226bda2-5981-468c-95d1-8a74b5ab3dc9 -- annex.backend;       4c447cb8-a897-4d73-9f3d-e105dee3a029 -- git@d675242d8c76:~/tmp/appdata/tmp/local-repo/432;   fb9320bf-20a4-4443-b292-e6b882773c73 -- git@6f72981f1cdf:~/repos/robintibor/high-gamma-dataset.git [get(/tmp/high-gamma-dataset/data/test/1.mat)] 
get(error): /tmp/high-gamma-dataset/data/test/1.mat (file) [not available; Try making some of these repositories available:;         1226bda2-5981-468c-95d1-8a74b5ab3dc9 -- annex.backend;       4c447cb8-a897-4d73-9f3d-e105dee3a029 -- git@d675242d8c76:~/tmp/appdata/tmp/local-repo/432;   fb9320bf-20a4-4443-b292-e6b882773c73 -- git@6f72981f1cdf:~/repos/robintibor/high-gamma-dataset.git]
[DEBUG  ] could not perform all requested actions: Command did not complete successfully [{'type': 'file', 'status': 'error', 'path': '/tmp/high-gamma-dataset/data/test/1.mat', 'action': 'get', 'annexkey': 'MD5-s297068703--1d1184d4a026fba9d79d16b9a26cd3bb', 'message': 'not available; Try making some of these repositories available:; \t1226bda2-5981-468c-95d1-8a74b5ab3dc9 -- annex.backend;  \t4c447cb8-a897-4d73-9f3d-e105dee3a029 -- git@d675242d8c76:~/tmp/appdata/tmp/local-repo/432;  \tfb9320bf-20a4-4443-b292-e6b882773c73 -- git@6f72981f1cdf:~/repos/robintibor/high-gamma-dataset.git'}] [utils.py:generator_func:448] 

$ git annex get data/test/1.mat      
get data/test/1.mat (not available) 
  Try making some of these repositories available:
        1226bda2-5981-468c-95d1-8a74b5ab3dc9 -- annex.backend
        4c447cb8-a897-4d73-9f3d-e105dee3a029 -- git@d675242d8c76:~/tmp/appdata/tmp/local-repo/432
        fb9320bf-20a4-4443-b292-e6b882773c73 -- git@6f72981f1cdf:~/repos/robintibor/high-gamma-dataset.git
failed
git-annex: get: 1 failed
```

So fresh out of the box plain git access works, but git-annex in non-functional.

**Comment by mih** [comment]
I have created a public test repo on GIN for test purposes -- no annex'ed files yet: https://gin.g-node.org/mih/datalad-test0

On initial install, the dataset is not an AnnexRepo, because datalad finds no hint that it would/should be:

```
% dl install git@gin.g-node.org:/mih/datalad-test0.git
[INFO   ] Cloning git@gin.g-node.org:/mih/datalad-test0.git into '/tmp/datalad-test0' 
install(ok): /tmp/datalad-test0 (dataset)                                                    
(datalad3-dev) mih@meiner /tmp % cd datalad-test0
% dl wtf -S dataset
# WTF
## dataset 
  - path: /tmp/datalad-test0
  - repo: GitRepo
  - metadata: <SENSITIVE, report disabled by configuration>
% git branch -a |cat
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
```

After uploading a small-ish binary file via the web UI, I can update the dataset without issues
```
% datalad update --merge
[INFO   ] Fetching updates for <Dataset path=/tmp/datalad-test0> 
[INFO   ] Applying updates to <Dataset path=/tmp/datalad-test0>                              
update(ok): . (dataset)
```

While the test file is checked directly into git, the repo is now an AnnexRepo (I assume the initial upload triggered that change on the server side):

```
% dl wtf -S dataset
# WTF
## dataset 
  - path: /tmp/datalad-test0
  - repo: AnnexRepo
  - metadata: <SENSITIVE, report disabled by configuration>
```

Adding a new file (actually the same file under a different name) and publishing it to GIN works nicely. The second file is annex'ed (although identical), so the decision annex or no for the initial upload must have been made by server-side logic and is not reflected in the dataset itself -- worth keeping in mind):

```
% git annex addurl https://der-roe.de/wp-content/uploads/final_testbild.png --file testfile2.png
addurl https://der-roe.de/wp-content/uploads/final_testbild.png 
(to testfile2.png) ok
(recording state in git...)
% datalad save
save(ok): . (dataset)
% dl status --annex all
1 annex'd file (5.8 KB/5.8 KB present/total size)
(datalad3-dev) mih@meiner /tmp/datalad-test0 (git)-[master] % datalad publish --to origin --transfer-data all
[INFO   ] Publishing <Dataset path=/tmp/datalad-test0> data to origin 
[INFO   ] Publishing <Dataset path=/tmp/datalad-test0> to origin 
publish(ok): . (dataset) [pushed to origin: ['[up to date]', '990cba7..f736bc4']]            
```

The result of the upload is visible here https://gin.g-node.org/mih/datalad-test0/src/master/testfile2.png

It seems everything is nice and dandy.

**Comment by mih** [comment]
Another scenario: Create an empty repo on GIN https://gin.g-node.org/mih/datalad-test1 and push an existing local dataset

```
% dl create test2
[INFO   ] Creating a new annex repo at /tmp/test2 
create(ok): /tmp/test2 (dataset)                                                             
(datalad3-dev) mih@meiner /tmp % cd test2

% dl siblings add -s gin --url git@gin.g-node.org:/mih/datalad-test1.git
[INFO   ] Failed to enable annex remote gin, could be a pure git or not accessible 
[WARNING] Failed to determine if gin carries annex. 
.: gin(-) [git@gin.g-node.org:/mih/datalad-test1.git (git)]

% echo 123 > dummy
% datalad save
add(ok): dummy (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
dl status --annex all
1 annex'd file (4.0 B/4.0 B present/total size)

% dl publish --to gin --transfer-data all 
[INFO   ] Publishing <Dataset path=/tmp/test2> data to gin 
publish(ok): dummy (file)                                                                    
[INFO   ] Publishing <Dataset path=/tmp/test2> to gin 
publish(ok): . (dataset) [pushed to gin: ['f1ef9f1..da015a1', '[new branch]']]               
action summary:
  publish (ok: 2)

% git annex fsck -f gin
fsck dummy (checksum...) ok
(recording state in git...)
```

Flawless.

**Comment by mih** [comment]
Subdataset scenario -- looking good too:

```sh
# fresh dataset
% dl create test3
[INFO   ] Creating a new annex repo at /tmp/test3 
create(ok): /tmp/test3 (dataset)                                                             
% cd test3

# install two datasets from GIN as subdatasets
% dl install -d . -s git@gin.g-node.org:/mih/datalad-test0.git test0
[INFO   ] Cloning git@gin.g-node.org:/mih/datalad-test0.git into '/tmp/test3/test0' 
install(ok): test0 (dataset)                                                                 
action summary:
  add (ok: 1)
  install (ok: 1)
  save (ok: 1)
% dl install -d . -s git@gin.g-node.org:/mih/datalad-test1.git test1
[INFO   ] Cloning git@gin.g-node.org:/mih/datalad-test1.git into '/tmp/test3/test1' 
install(ok): test1 (dataset)                                                                 
action summary:
  add (ok: 2)
  install (ok: 1)
  save (ok: 1)

# add freshly create repo on GIN as a remote
% dl siblings add -s gin --url git@gin.g-node.org:/mih/datalad-test2.git
[INFO   ] Failed to enable annex remote gin, could be a pure git or not accessible 
[WARNING] Failed to determine if gin carries annex. 
.: gin(-) [git@gin.g-node.org:/mih/datalad-test2.git (git)]

# publish
% dl publish --to gin --transfer-data all 
[INFO   ] Publishing <Dataset path=/tmp/test3> data to gin 
[INFO   ] Publishing <Dataset path=/tmp/test3> to gin 
publish(ok): . (dataset) [pushed to gin: ['a68e897..b1c1545', '[new branch]']]               

# recursive installation of all datasets
% dl install -r -s git@gin.g-node.org:/mih/datalad-test2.git test2clone
[INFO   ] Cloning git@gin.g-node.org:/mih/datalad-test2.git into '/tmp/test2clone' 
install(ok): /tmp/test2clone (dataset)                                                       
[INFO   ] Installing <Dataset path=/tmp/test2clone> recursively 
[INFO   ] Cloning git@gin.g-node.org:/mih/datalad-test2.git/test0 [1 other candidates] into '/tmp/test2clone/test0' 
[INFO   ] Cloning git@gin.g-node.org:/mih/datalad-test2.git/test1 [1 other candidates] into '/tmp/test2clone/test1' 
action summary:                                                                              
  install (ok: 3)
```

Bingo!

**Comment by achilleas-k** [comment]
Hi Michael.  I've been catching up with the progress of this issue and I'd like to chime in.

> Adding a new file (actually the same file under a different name) and publishing it to GIN works nicely. The second file is annex'ed (although identical), so the decision annex or no for the initial upload must have been made by server-side logic and is not reflected in the dataset itself -- worth keeping in mind)

We have a general rule that files over 10 MiB are annexed automatically.  This is a rather arbitrary threshold and we could apply some smarter filters based on filetype, but I find it's a decent and simple heuristic.  I understand that there may be a lot of situations where files might be < 10 MiB and appropriate for git-annex versioning instead, so this is [configurable in the GIN client](https://gin.g-node.org/G-Node/Info/wiki/GinCliConfig#filtering-files-to-git-or-git-annex).  For web-uploads this can't be configured.
Of course, if you're adding files to the repository directly using git or git-annex commands, everything should work as expected.

If you have any questions I can answer directly, let me know here.  I realise the datalad<->gin integration has been a long standing issue that I haven't been keeping up with but I'd like to help move this forward faster now.

**Comment by mih** [comment]
Thank you for the feedback!

> Of course, if you're adding files to the repository directly using git or git-annex commands, everything should work as expected.

Just FTR: I have noticed that you allow putting much larger content straight into Git. I cloned a dataset which was very slow (was suspecting the wifi), and later on my machine felt rather sluggish. Turned out this this was the problem:

```
% du -sh .git
4.0G    .git
% du -sh .
30G     .
% git annex info
git-annex: First run: git-annex init
```

Working with this dataset is not very practical. Not sure what would be a good method to force users to use git annex other than limiting the total size of git objects.

**Comment by achilleas-k** [comment]
Yes, we don't enforce any of the limits.  The 10 MiB filtering is done on the web uploader and in the default gin-cli configuration.  Beyond that, users can create repositories as they like.  If a user creates a git repository without annex and `git add`s a 10 GiB file and pushes, we don't block it in any way.

I suppose one (not sure if good, bad, or neutral) method would be a server-side pre-receive hook that checks file sizes against a threshold.  On failure it could return a message to the pusher with instructions on how to annex the large file.

We haven't had much trouble with repositories getting out of hand like that so far, so our policies are rather lax.  I'll certainly consider it, though.

Is the repository you came across the gin-cli-releases one?  I purposefully kept that one git-only for (no-longer relevant) simplicity reasons.

**Comment by yarikoptic** [comment]
I find our rule for datalad datasets created with `-c text2git` which adds .gitattributes rule to place only text files (according to libmagic assessment) into git working out quite well . So far I saw it not being sufficient only for large xml files produced by some tools.

**Comment by achilleas-k** [comment]
That seems like a nice default for the GIN client (and web uploads).  I'll add it to the planned feature list, thanks.  I'm still considering a hard policy for git file sizes, but I'll have to think more about it.

**Comment by yarikoptic** [comment]
I think it might be feasible to relatively quickly get a largest object/blob size (@kyleam ?). That might be an easier to warrant limiting factor indicative of a data file being committed to git

**Comment by achilleas-k** [comment]
Is it slow to iterate through the sizes of new blobs during a push?

**Comment by kyleam** [comment]
> Is it slow to iterate through the sizes of new blobs during a push (pre-receive)?

I'd guess that comes down to `rev-list --objects $old..$new` followed by a batched cat-file and some processing of that output.  I don't expect that'd be too slow, though perhaps you'd feel it for an initial push with a long history.

With a newer git on the server, it might be a bit faster to avoid the cat-file call using --filter/--filter-print-omitted.  Something like

```sh
#!/bin/sh

limit=20 # bytes, ridiculously low limit for testing

above_limit () {
    git rev-list --objects --filter="blob:limit=$limit" \
        --filter-print-omitted "^$1" "$2" | \
        grep -q "^~"
}

while read oldref newref refname; do
    if test "$oldref" = "0000000000000000000000000000000000000000"
    then
        oldref="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
    else
        oldref="$oldref"
    fi

    if above_limit "$oldref" "$newref"
    then
        echo "Blob above $limit bytes found in $oldref..$newref" 2>&1
        exit 1
    fi
done
```

**Comment by achilleas-k** [comment]
That seems very reasonable to me.  I'd definitely experiment with some extreme/edge cases before moving forward.  Thanks @kyleam.

**Comment by mih** [comment]
Read-only anonymous access is now live!! Thanks @achilleas-k

**Comment by mih** [comment]
FTR: @achilleas-k confirmed that it is OK to talk to GIN for CI purposes.

**Comment by mih** [comment]
Established DataLad's home: https://gin.g-node.org/datalad

Created minimal dataset for CI purposes:

```
datalad create datalad-ci-target
cd datalad-ci-target
mkdir git annex
echo '\ngit/** annex.largefiles=nothing' >> .gitattributes
echo 'annex/** annex.largefiles=(anything)' >> .gitattributes
datalad save .gitattributes --to-git -m 'Basic setup'
echo one > git/one
echo two > annex/two
datalad save -m Payload
# as instructed by GIN
git remote add origin git@gin.g-node.org:/datalad/datalad-ci-target.git
# but push via datalad
datalad push --to origin -f datatransfer
```

made public and available at https://gin.g-node.org/datalad/datalad-ci-target
