### ISSUE TITLE
`run` permission dance issue

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2683]
Usecase: I wanted to `singularity build` an image inside `datalad run`. The build itself needs to run as root, but ideally datalad itself would not need to. Here is my attempt:

```
% datalad run -d . --input Singularity --output container.simg -m "Build Singularity image from Docker" \
    sudo singularity build {outputs} {inputs}
```

which leads to:

```
[INFO   ] == Command exit (modification check follows) ===== 
Total:   0%|                                                                | 0.00/4.55G [00:00<?, ?B/s][WARNING] Running add resulted in stderr output:   container.simg: setFileMode: permission denied (Operation not permitted)
git-annex: add: 1 failed
 
Total:   0%|                                                                | 0.00/4.55G [00:00<?, ?B/s][WARNING] Running add resulted in stderr output:   container.simg: setFileMode: permission denied (Operation not permitted)
git-annex: add: 1 failed
 
File(s) unknown to git
```

which is not unexpected:

```
% ll
total 4.3G
-rwxr-xr-x 1 root root 4.3G Jul  1 09:21 container.simg*
-rw-rw-r-- 1 mih  mih    86 Jul  1 09:04 Singularity
```

I wonder what you guys think would be a better approach. Running the entire command through `sudo` will probably mess up permissions in the object store(s), but most importantly DataLad will have no record that this particular command needs god-mode.

**Comment by mih** [comment]
FTR: Permissions were messed up with global sudo, but seems to have been rectified with a 
```
sudo chown -R $(whoami): .
```

**Comment by kyleam** [comment]
> I wonder what you guys think would be a better approach

Something like

    % datalad run -d . --input Singularity --output container.simg -m "Build Singularity image from Docker" \
      "sudo singularity build {outputs} {inputs} && sudo chown $(whoami) {outputs}"

**Comment by mih** [comment]
Uhm....that...seems....straightforward...

thx!

**Comment by mih** [comment]
Actually, there is still a problem (not worth keeping this issue open): the original user name will get encoded in the run record, and will make it generally impossible to rerun this as another user. Although, Git really doesn't care what user owns the file.

**Comment by kyleam** [comment]
Right.  The two ways I see to get a record that's re-runnable on other machines are (1) the user creates a short wrapper script for the command or (2) add a placeholder `user` for `getpass.getuser()`.
