### ISSUE TITLE
How to list available (remote) handles?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#269]
may be there is a command already but couldn't find.

E.g. after I registered a remote collection, how could I discover what it provides?  I can envision having e.g. `list-handles -r [collection]` which would list all handles available from remote collections  (or just from `[collection]`) or a new command `list-collection [collection]` which does that

**Comment by bpoldrack** [comment]
Indeed. By now only search-handle would include these (or a sparql-query).
I'd vote for the "list-handle -r" approach.
