### ISSUE TITLE
datalad aliases

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2693]
#### What is the problem?
no problem, but thought to share/document an idea to have `datalad.alias` section in config (similar to `alias` of regular git) which  would provide similar functionality.  Implementation should be reasonably straightforward since it would be just a matter of adjusting `sys.argv` to replace the aliased command with the alias (split the same was as shell splits). 
Similar to git we could go one step further and provide "python formatting" aliases (may be similarly starting with `!` to indicate that) which we would feed all the options and positional arguments given after the alias command.

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
