### ISSUE TITLE
Converting/importing existing git annex repo into datalad

### ISSUE THREAD

**Issue by aragilar** [datalad/datalad#2694]
(This is more of a support question than a bug, but I figure asking this publicly means the next person should find a potential solution more easily).

I have ~4 years of data (HDF5 files) stored in a git annex repo. I'd like to take advantage of some of datalad's features, and wonder if there's a way of converting that repo to something that is natively handled by datalad?

**Comment by aragilar** [comment]
Cool, this seemed to work fine on my repo (feel free to close this if need be).

**Comment by yarikoptic** [comment]
Feel welcome to ask more @aragilar ;-)
