### ISSUE TITLE
add-archive-content fails with a (particular) zip file

### ISSUE THREAD

**Issue by mvdoc** [datalad/datalad#2695]
#### What is the problem?

`add-archive-content` (or patool?) can't unzip a zip file. It can be unzipped using `unzip` on mac.
```terminal
(datalad) contematto@talete ~/Documents/experiments_work/famretino2/vtcdata/code (master) $ datalad add-archive-content socmodel.zip
[INFO   ] Adding content of the archive socmodel.zip into annex <AnnexRepo path=/Users/contematto/Documents/experiments_work/famretino2/vtcdata (<class 'datalad.support.annexrepo.AnnexRepo'>)>
[ERROR  ] error extracting b'/Users/contematto/Documents/experiments_work/famretino2/vtcdata/.git/annex/objects/jj/42/MD5E-s496421104--d3320841134a74e8bafbfcca4f8c1ac4.zip/MD5E-s496421104--d3320841134a74e8bafbfcca4f8c1ac4.zip': 'bytes' object has no attribute 'seek' [py_zipfile.py:extract_zip:46] (PatoolError)
```
#### What steps will reproduce the problem?

```terminal
cd /tmp
mkdir test-socmodel
cd test-socmodel
wget http://kendrickkay.net/socmodel/socmodel.zip
datalad create -f --text-no-annex .
datalad add socmodel.zip
datalad add-archive-content -d socmodel.zip
```

The zip is ~480mb.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

```terminal
$ datalad --version
datalad 0.10.1
```

**Comment by kyleam** [comment]
> add-archive-content (or patool?) can't unzip a zip file. It can be unzipped using unzip on mac.

I don't think it's patool.  Using it directly works fine for me:

```python
import patoolib
patoolib.extract_archive("socmodel.zip", outdir="blah")
```

This seems to be a py2/py3 issue.  Running datalad under python 2 works fine, but I see the same failure as you when running python 3.

I can make the python 3 run work with the following change:

```diff
diff --git a/datalad/support/archives.py b/datalad/support/archives.py
index 38f13150a..0bfc1a8ee 100644
--- a/datalad/support/archives.py
+++ b/datalad/support/archives.py
@@ -145,6 +145,7 @@ def decompress_file(archive, dir_, leading_directories='strip'):
         outdir = unixify_path(dir_)
         if not PY2:
             # should be supplied in PY3 to avoid b''
+            archive = assure_unicode(archive)
             outdir = assure_unicode(outdir)
         patoolib._extract_archive(unixify_path(archive),
                                   outdir=outdir,
```

But I haven't tested this more widely or dug into the history of the code in order to understand if that will break other things.

Also, just a note: As of v0.10, you can combine the wget/add/add-archive-content steps into

```bash
%> datalad download-url --archive http://kendrickkay.net/socmodel/socmodel.zip
```

**Comment by kyleam** [comment]
> with a (particular) zip file

I'm guessing the "particular" is because you didn't test with other zip files.  Or do some other zip files work for you?  (That'd surprise me since I don't see how a zip file's content or name could affect this issue.)

**Comment by yarikoptic** [comment]
@kyleam please submit a proposal with that little fix - if tests pass let's consider it to be the way ;-)

**Comment by mvdoc** [comment]
Yes, particular == "I thought it worked with other zip files (looking at
other examples in other issues)"
