### ISSUE TITLE
what search-collection output should be? ;)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#270]
ATM
```
$> datalad search-collection .     
(rdflib.term.Literal(u'demo_collection'), rdflib.term.URIRef(u'ssh://datalad.org/srv/collections.datalad.org/www/demo/DATALAD_COL_demo_collection'))
(rdflib.term.Literal(u'demo_collection'), rdflib.term.URIRef(u'ssh://datalad.org/srv/collections.datalad.org/www/demo/DATALAD_COL_demo_collection'))
(rdflib.term.Literal(u'demo_collection'), rdflib.term.URIRef(u'ssh://datalad.org/srv/collections.datalad.org/www/demo/DATALAD_COL_demo_collection'))
```
is it aiming to output collections or handles or ...?
I guess the goal was to identify which collections match the criteria and output those, which should be a subset of output of
```
$> datalad list-collections   
demo-remote
```
in my case

**Comment by yarikoptic** [comment]
I guess similar logic should go for search-handle
```
$> datalad search-handle .
(rdflib.term.Literal(u'demo_handle1'), rdflib.term.URIRef(u'ssh://datalad.org/srv/collections.datalad.org/www/demo/demo_handle1'))
(rdflib.term.Literal(u'demo_handle1'), rdflib.term.URIRef(u'ssh://datalad.org/srv/collections.datalad.org/www/demo/demo_handle1'))
(rdflib.term.Literal(u'demo_handle1'), rdflib.term.URIRef(u'ssh://datalad.org/srv/collections.datalad.org/www/demo/demo_handle1'))
```

**Comment by bpoldrack** [comment]
Almost. It's intended the same way as search-handles, meaning it should list collections (including remote ones), that match the criteria. But the output should be ironed. ;)
And, these commands are trying to match a search string, so I'm not sure atm what they are actually doing with the "." What's your cwd?

**Comment by yarikoptic** [comment]
Ooh, cwd probably lost by now :-) with . I guess they look for a . eg the end of a sentence :-)

**Comment by yarikoptic** [comment]
and again -- what should be the output?  to the user it would be interesting to see not just a list of names/paths but what has matched.  Now I might jsut get 3 identical entries for a single handle:
```
$> datalad search-handle a  
demo_handle1	ssh://datalad.org/srv/collections.datalad.org/www/demo/demo_handle1
demo_handle1	ssh://datalad.org/srv/collections.datalad.org/www/demo/demo_handle1
mnist       	/home/yoh/proj/datalad/datalad-debian/docs/examples/mnist
mnist       	/home/yoh/proj/datalad/datalad-debian/docs/examples/mnist
```
I think, as I have mentioned in another report -- we should decide on output of the API etc

**Comment by bpoldrack** [comment]
Well, so let's dicuss and define it. I think to show what has matched might
be an option. By default I'd like to see just the collection/handle
name(s), that were found to contain the searched string.
The output of the actual match might be not an easy thing to do in a
readable way. To be considered a reasonable output, it would need to show
the connection of the found string to the collection/handle. These graphs
can grow ...

2015-10-16 0:54 GMT+02:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by mih** [comment]
Obsolete now. Closing.
