### ISSUE TITLE
coloring of default output rendering on windows is not understood/working

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2700]
#### What is the problem?
Whenever pip output colors nicely, and our logger doesn't use coloring on windows (so there is no bad side-effect), default output renderer is filling up output with those ansi sequences I guess:

![bogus ansi](http://www.onerussian.com/tmp/gkrellShoot_07-13-18_135015.png)

@kyleam I think you played with all the ANSI handling in pyout, would you mind having a look on how we could make it all proper here?

Above installation: anaconda with 3.6, some things installed via pip. datalad is 0.10.2+

**Comment by kyleam** [comment]
I don't think I know any more than you about ANSI handling on Windows.  Following  `colorama.init()`, `colorama` should filter stdin/stdout for a certain set of sequences and map them to something useful on Windows.

**Comment by yarikoptic** [comment]
pushing the fix within #2707 - colorama needs to be imported earlier!
