### ISSUE TITLE
Practical issue with `run` {inputs} handling

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2701]
Command:

```
datalad run --input 'sub-06_acq-r*_T1w.nii.gz' code/mridefacer/mridefacer --verbose --apply {inputs}
```

Will fail, because `{inputs}' is expanded to a list of filenames but stays a single argument:

```
Failed to run "code/mridefacer/mridefacer --verbose --apply 'sub-06/anat/sub-06_acq-r14_T1w.nii.gz sub-06/anat/sub-06_acq-r20_T1w.nii.gz sub-06/anat/sub-06_acq-r20mb_T1w.nii.gz sub-06/anat/sub-06_acq-r30_T1w.nii.gz'"
```

`mridefacer` is a bash script that operates on multiple images that come in one-by-one via `argv` -- standard operation, I think.

Dunno how to handle this with the current `{inputs}` expansion behavior. `--expand inputs` does not have the desired effect on the nature of the cmdline call, only on the commit message content (as described).

**Comment by yarikoptic** [comment]
I wonder if us introducing some .format formatters (used in  https://github.com/datalad/datalad/blob/master/datalad/interface/ls.py look for Formatter) to be able to say to expand those won't be too late in the process?

**Comment by kyleam** [comment]
That's working as intended since `shlex_quote` is mapped over the argument list.  The way around it is to quote the whole command:

```
datalad run --input 'sub-06_acq-r*_T1w.nii.gz' 'code/mridefacer/mridefacer --verbose --apply {inputs}'
```

I don't see a viable approach to make the non-quoted variant work, but I should cover this issue in the command's "Command format" section.

**Comment by mih** [comment]
Ah, I knew it would be possible somehow. Thanks for putting it in the docs!
