### ISSUE TITLE
Combined short command line arguments do not seem to work

### ISSUE THREAD

**Issue by chrisfilo** [datalad/datalad#2709]
#### What is the problem?
Combined short command line arguments do not seem to work
#### What steps will reproduce the problem?
```
me@christop ~/datalad (annex/direct/master) $ datalad ls -Lr .
[ERROR] unknown argument: -Lr
usage: datalad ls [-h] [-r] [-F] [-a] [-L] [--config-file CONFIG_FILE]
                  [--list-content {None,first10,md5,full}]
                  [--json {file,display,delete}]
                  [PATH/URL [PATH/URL ...]]
```
me@christop ~/datalad (annex/direct/master) $ datalad get -J4 openfmri/ds000*/sub-*/anat
[ERROR] unknown argument: -J4
usage: datalad get [-h] [-s LABEL] [-d PATH] [-r] [--recursion-limit LEVELS]
                   [-n] [-D DESCRIPTION] [--reckless] [-J NJOBS] [-v]
                   [PATH [PATH ...]]
```

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
Running current master
```
me@christop ~ $ datalad wtf
DataLad
=======
Version     : 0.10.2
Full version: 0.10.2

System
======
OS             : nt Windows 10 10.0.17134
Distribution   :   10/10.0.17134/SP0/Multiprocessor Free
Max path length: 259  You are left with 247 characters under C:/Users/me

Locale/Encoding
===============
default        : utf-8
filesystem     : utf-8
locale.prefered: cp1252

Environment
===========
LANG='en_US.UTF-8'
PATH='c:\\users\\me\\miniconda3\\Library\\bin;C:\\Users\\me\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\ConEmu\\ConEmu\\Scripts;C:\\Program Files\\ConEmu;C:\\Program Files\\ConEmu\\ConEmu;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.2\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.2\\libnvvp;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files\\Docker\\Docker\\Resources\\bin;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\PuTTY;C:\\Program Files (x86)\\MIT\\Kerberos\\bin;C:\\Program Files\\Intel\\WiFi\\bin;C:\\Program Files\\Common Files\\Intel\\WirelessCommon;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\nodejs;C:\\Users\\me\\Miniconda3;C:\\Users\\me\\Miniconda3\\Library\\mingw-w64\\bin;C:\\Users\\me\\Miniconda3\\Library\\usr\\bin;C:\\Users\\me\\Miniconda3\\Library\\bin;C:\\Users\\me\\Miniconda3\\Scripts;C:\\Users\\me\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\me\\AppData\\Local\\atom\\bin;C:\\Program Files\\dcm2niix;C:\\Program Files\\Intel\\WiFi\\bin;C:\\Program Files\\Common Files\\Intel\\WirelessCommon;C:\\Users\\me\\AppData\\Roaming\\npm;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl'
PYTHONIOENCODING='UTF-8'

Externals
=========
appdirs=1.4.3
boto=2.48.0
cmd:annex=6.20180626-gb091dac13
cmd:git=2.18.0.windows.1
cmd:system-git=2.18.0.windows.1
cmd:system-ssh=7.7p1
git=2.1.10
gitdb=2.0.3
humanize=0.5.1
iso8601=0.1.12
msgpack=0.5.6
requests=2.18.4
six=1.11.0
tqdm=4.23.4
wrapt=1.10.11

Installed extensions
====================

Known metadata extractors
=========================
annex: OK
audio: BROKEN (No module named 'mutagen' [audio.py:<module>:17])
datacite: OK
datalad_core: OK
datalad_rfc822: OK
exif: BROKEN (No module named 'exifread' [exif.py:<module>:16])
frictionless_datapackage: OK
image: OK
xmp: BROKEN (No module named 'libxmp' [xmp.py:<module>:20])

Configuration
=============
<Sensitive data, use -s=some or -s=all to show>
```

#### Is there anything else that would be useful to know in this context?
I like squirrels.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Still trying to get it to work :)

**Comment by yarikoptic-gitmate** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1692 (--on-failure=ignore seems to not work), https://github.com/datalad/datalad/issues/1119 (`get` should work without an explicit `path` argument), https://github.com/datalad/datalad/issues/1887 (Make --run-before/after work with any command), and https://github.com/datalad/datalad/issues/28 (seems to be lacking last 'commit').

**Comment by kyleam** [comment]
Eh, looks like I broke this with gh-2547:

```
commit be49a95dd53ec9284c56ce24d56c9cfe760a843a
Date:   Thu May 24 09:14:38 2018 -0400
    ENH: cmdline: Disable abbreviations for long options

    argparse's abbreviation feature makes it impossible to add a subparser
    long option that is a prefix of a long option from the top-level
    parser.  For example, adding --report to a subparser would fail with
    "datalad: error: ambiguous option: --report could match
    --report-status, --report-type".
```
