### ISSUE TITLE
Command to remove a sibling?

### ISSUE THREAD

**Issue by tedstrauss** [datalad/datalad#2713]
#### What is the problem?

I need to start over with a github sibling, is there a command to remove a previously create one? 

#### What steps will reproduce the problem?

Run `datalad create-sibling-github` then run it again with new arguments.
Get error message `already had a configured sibling "github"`

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

0.10.1

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)

Still a beginner.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1669 (siblings command fails on special remotes), https://github.com/datalad/datalad/issues/517 (Remove from annex), https://github.com/datalad/datalad/issues/2423 (siblings remove -s nonexisting  produces no output), https://github.com/datalad/datalad/issues/2281 (remove --unregister-only ?), and https://github.com/datalad/datalad/issues/1135 (remove causes AttributeError).

**Comment by tedstrauss** [comment]
The first command seemed to work, but got a permission error.
Have to 'manually'  `git remote remove github' to complete the operation.
