### ISSUE TITLE
providers (or credentials) should support HTTP "realm" as alternative/complement to "url"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2714]
#### What is the problem?
@yarikoptic didn't know the standards and was misguided by "custom websites" to forget about realms provided as a part of 401 http code, and could be used to identify which credential (provider) to use for access.  ATM, and even in #2708 realm is ignored, but could be stored associated with the provider so next failure could search up provider/credential by looking for that realm.  Concern - realm is a custom string, so could be "abused" I guess, so may be main domain or alike should be used alongside with it

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2059 (Support GigaDB as a data provider), https://github.com/datalad/datalad/issues/1473 (figshare could be supported as a provider and for export), https://github.com/datalad/datalad/issues/5 (aspera support), https://github.com/datalad/datalad/issues/30 (academictorrents support), and https://github.com/datalad/datalad/issues/154 (Support python3).

**Comment by yarikoptic** [comment]
Some notes from "14.8 Authorization" of https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

> If a request is authenticated and a realm specified, the same credentials SHOULD
> be valid for all other requests within this realm (assuming that
> the authentication scheme itself does not require otherwise, such
> as credentials that vary according to a challenge value or using
> synchronized clocks).

Well, according to https://www.ietf.org/rfc/rfc2617.txt 

>  The realm directive (case-insensitive) is required for all authentication schemes that issue a challenge.
>  The realm value  (case-sensitive), in combination with the canonical root URL (the
>  absoluteURI for the server whose abs_path is empty; see section 5.1.2
>  of [2]) of the server being accessed, defines the protection space.

and I believe Digest auth is using such combination for the digest.

So , pretty much, realm should be an extra property to identify a provider by. But then we must not pre-emptively authenticate if realm is known/specified for the provider, since we would need to first "sense" which realm to authenticate "against" to not provide "incorrect" credential, or to leak it to "incorrect party".

**Comment by mih** [comment]
The credential system provided by https://github.com/datalad/datalad-next supports this. From my POV this issue could be closed, but I am not certain that there are no plans to address something like this in the "providers" feature -- which is the primary subject here.

**Comment by mih** [comment]
At this point I think it is unlikely that anything will be done about this, other than eventually importing this functionality from datalad-next. I am closing this.
