### ISSUE TITLE
ZeroDivisionError when publishing an empty file for the first time

### ISSUE THREAD

**Issue by simon-dube** [datalad/datalad#2716]
#### What is the problem?
In some situations, I want to publish empty files to a Google Drive remote, sibling to a GitHub remote. However, when publishing the file, although the file is correctly transferred to the given remotes, a ZeroDivisionError is raised.
`[ERROR  ] float division by zero [annexrepo.py:get_size_from_perc_complete:3625] (ZeroDivisionError) `
#### What steps will reproduce the problem?
1. In a dataset, create an empty file with `touch zero.txt`
2. `datalad save zero.txt`
3. `datalad publish --to github --transfer-data all`
#### What version of DataLad are you using?
Version: datalad 0.10.1
Operating system: Ubuntu 18.04 LTS
#### Is there anything else that would be useful to know in this context?
This error appears to happen only when publishing a 0 byte file **for the first time**. Using `datalad remove` to remove the file and publishing a new empty file afterwards do not cause the error.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1063 (was asked 4 times for a password during publish), https://github.com/datalad/datalad/issues/1480 (publish should publish (annex copy) data first before pushing), https://github.com/datalad/datalad/issues/283 (whereis-published), https://github.com/datalad/datalad/issues/282 (publishing layout), and https://github.com/datalad/datalad/issues/733 (published index.html (and other files) have ).
