### ISSUE TITLE
datalad.api docstring should be populated with the description of available "commands"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2718]
#### What is the problem?
`datalad --help` provides a nice list of commands to use, but neither `datalad` nor `datalad.api` docstring give **any** hints on what is available and how should be used.  I think they should
- get a better generic description, possibly mimicking what is presented by `datalad --help`
- get the docstring populated with description of the commands (which do get imported while importing .api)

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2063 (ENH: datalad shell  command), https://github.com/datalad/datalad/issues/2693 (datalad aliases), https://github.com/datalad/datalad/issues/1193 (datalad mv), https://github.com/datalad/datalad/issues/537 (provide API command "credentials"), and https://github.com/datalad/datalad/issues/168 (Online index of available collections (datalad.org)).

**Comment by kyleam** [comment]
> datalad --help provides a nice list of commands to use, but neither datalad nor datalad.api docstring give any hints on what is available and how should be used. I think they should
> 
> * get a better generic description, possibly mimicking what is presented by datalad --help

I'm not sure what you mean by a "generic" description, so I'll assume you're referring to the one-line command summaries shown by `datalad --help`.

> * get the docstring populated with description of the commands (which do get imported while importing .api)

In my view, trying to dynamically modify `datalad{,.api}.__doc__`  introduces unnecessary complexity.  I'd propose to

  * Add a function `print_help` or `print_commands` (or something else?) to `datalad.api` that will print something similar to what `get_description_with_cmd_summary` generates for `datalad --help`.  We should be able to pull out common bits from `datalad.cmdline.main`.

    Running `help(datalad.api)` or `datalad.api?` or `pydoc datalad.api` would then show that function and its docstring, making it easily discoverable.

  * In `datalad.__doc__`, point to `datalad.api` as the Python entry-point for datalad.

**Comment by yarikoptic** [comment]
> I'll assume you're referring to the one-line command summaries shown by datalad --help.

yes!

> introduces unnecessary complexity

may be for us, but not for the user.  Adding a non conventional function to api would add the complexity for user... I typically appreciate just being able to `?` things in ipython session and get good docs. E.g. try `numpy?`.  And since we are already loading all the modules/functions there should be little to no run-time impact to adjust the `__doc__`.

> In `datalad.__doc__`, point to `datalad.api` as the Python entry-point for datalad.

yes, please

**Comment by kyleam** [comment]
Never mind, I was stupidly thinking of the read-only docstrings of classes.  Modifying a module-level `__doc__` shouldn't add any complexity.
