### ISSUE TITLE
datalad copy PATHs DEST

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2727]
to copy and add files across repositories while copying also URLs where they could be obtained from (possibly including  even information on original tarballs keys if they came from them)

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1193 (datalad mv), https://github.com/datalad/datalad/issues/2693 (datalad aliases), https://github.com/datalad/datalad/issues/227 (datalad get  barfes), https://github.com/datalad/datalad/issues/562 (datalad create   booms), and https://github.com/datalad/datalad/issues/696 (datalad install doesn't handle paths (urls?) with spaces correctly).

**Comment by mih** [comment]
This time GitMate is right, this issue pretty much the same as #1193, minus the `git rm`.

**Comment by yarikoptic** [comment]
indeed! thank you @yarikoptic-gitmate ;-) closing as duplicate
