### ISSUE TITLE
API: composite command

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2729]
An idea for discussion, although not sure yet if effort worth it at this point of human evolution

ATM extensions could provide their additional commands to be added to the API.  That is great, but also adds toll on import time and also the "length" of the list of the commands etc.  I wondered if we should add support and RF for "two level" commands, e.g. instead of `datalad containers-run` after installation of `datalad-containers` (see datalad/datalad-container#48) we would get `datalad containers run`.

That later could be adopted for RFing `aggregate-metadata` into `metadata aggregate`, `extract-metadata` into `metadata extract`, `create-sibling` -> `siblings create` etc  to make whole cmdline api more sensible

At Python level, such an API could also go through attributes of the (composite) command class, where `__call__()` would do what it does now (e.g. for `siblings`) and then submethods would implement their own commands:
`metadata.aggregate`, `metadata.extract`, `siblings.create`

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/362 (include api command into NAME of the manpage), https://github.com/datalad/datalad/issues/239 (API commands should report at INFO level on accomplished actions), https://github.com/datalad/datalad/issues/537 (provide API command "credentials"), https://github.com/datalad/datalad/issues/1449 (Re-classify "misc" commands), and https://github.com/datalad/datalad/issues/1217 (Provide `diff` command).

**Comment by kyleam** [comment]
> I wondered if we should add support and RF for "two level" commands, e.g. instead of datalad containers-run after installation of datalad-containers (see datalad/datalad-container#48) we would get datalad containers run.

I like the idea of allowing an additional "namespace" for extensions.   Though as you say,  I'm not sure if anyone will care enough to actually spend time implementing it.

> That later could be adopted for RFing aggregate-metadata into metadata aggregate, extract-metadata into metadata extract, [...]

Hmm, but I'm not sure that I like that.  It think for core commands it'd be a bit of an overkill.

**Comment by mih** [comment]
I had a go at this once, but couldn't manage to come up with something nice in a short amount of time.

**Comment by mih** [comment]
Closing "question"-type issue with a response, and no further activity.
