### ISSUE TITLE
When do we decide if yarikoptic-gitmate is here to stay?

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2730]
As I understand @yarikoptic-gitmate (no relation to @yarikoptic), he's an experiment.  So far, I find him noisy and obnoxious (very unlike the human @yarikoptic, of course).  Perhaps others find him helpful, and I know he's supposedly still learning.

At any rate, for transparency (and perhaps something to look forward to), when do we declare the experiment a success or failure?

**Comment by yarikoptic** [comment]
> very unlike the human @yarikoptic, of course

LOL ;-)  
I really hoped that gitmate would help to point to duplicate issues since we have an honorable number of them.  So far indeed his "hints" were not really useful.  Should we give him may be another month and then either embrace him or kick him out?

**Comment by kyleam** [comment]
> Should we give him may be another month and then either embrace him or kick him out?

Sounds good.  Thanks :-)

**Comment by kyleam** [comment]
OK, it's been a month.  Opinions?

**Comment by yarikoptic** [comment]
It seems to rarely have positive hits, but doesn't annoy me that much

**Comment by kyleam** [comment]
All right, seems everyone else is more welcoming than I am :-)  I'll register my solo vote against @yarikoptic-gitmate, and close this.

**Comment by mih** [comment]
I have yet to see a true positive contribution of that bot and the answer count of the issues became meaningless, as there is now a pointless response to every single one. Net loss, if you ask me.

**Comment by driusan** [comment]
Its false positives often entertain me, but that's not a very strong argument in favour of keeping the noise that it generates.

**Comment by yarikoptic** [comment]
ok, presumably disabled it. let's see with the next issue etc
