### ISSUE TITLE
--proc-post doesn't play nicely with `create`?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2732]
#### What is the problem?
```shell
$> datalad --proc-post setup_yoda_dataset --cmd create yodads 
[INFO   ] Creating a new annex repo at /tmp/yodads 
create(ok): /tmp/yodads (dataset)                                                
[ERROR  ] No dataset found [dataset.py:require_dataset:500] (NoDatasetArgumentFound) 
usage: datalad create [-h] [-f] [-D DESCRIPTION] [-d PATH] [--no-annex]
                      [--nosave] [--annex-version ANNEX_VERSION]
                      [--annex-backend ANNEX_BACKEND]
                      [--native-metadata-type LABEL] [--shared-access MODE]
                      [--git-opts STRING] [--annex-opts STRING]
                      [--annex-init-opts STRING] [--text-no-annex]
                      [--fake-dates]
                      [PATH]
```
datalad 0.10.2 

could be just a "user error", but my guess is that procedures assume to be ran in "current dataset" which I have none here (running under /tmp).  With `create`, I could argue, that it makes sense to run procedures in created dataset.  But I could also see some procedures to be intended to be run in 'parent' dataset.  So how could `create` be used with procedures with intent for them to be ran within the newly created dataset (which I guess would be more common usecase).

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/780 (`create` doesn't support path resolution), https://github.com/datalad/datalad/issues/403 (git submodule doesn't play nice with relative paths while cloning from http://.../.git), https://github.com/datalad/datalad/issues/597 (Publish doesn't do much), https://github.com/datalad/datalad/issues/1426 (publish still "doesn't publish" (without -r)), and https://github.com/datalad/datalad/issues/1987 (`publish` does not publish aggregated metadata).

**Comment by yarikoptic** [comment]
AWESOME! thank you @kyleam .  Indeed might be worth documenting somewhere.  
We do have https://github.com/datalad/faq/ but I think that disconnect, since we can't just move issues between is not working. So I will move those questions from there here and we then could tag with new FAQ label the ones we consider worth it.  I think this one is a good one ;)
