### ISSUE TITLE
add version information for installed extensions in `wtf` output

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2734]
#### What is the problem?

ATM no information
```shell
/tmp > datalad wtf
DataLad
=======
Version     : 0.10.2.dev22
...
Installed extensions
====================
container
```

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1455 (add locking), https://github.com/datalad/datalad/issues/2471 (Documentation versions), and https://github.com/datalad/datalad/issues/179 (version is out of date, no?).

**Comment by mih** [comment]
@kyleam I will take you off this one, and implement this together with a solution to #2415

**Comment by kyleam** [comment]
OK, thanks.  #2415 sounds like a good idea.

**Comment by mih** [comment]
PR is pushed as #2741

**Comment by mih** [comment]
In master now.
