### ISSUE TITLE
How to get DataLad (or any other python) process into "interactive mode"?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2736]
If running within e.g. Git shell for windows, by default DataLad (or python  itself for that matter) would not consider the session interactive.  You need to run your command via `winpty` command to make it "interactive", e.g.

![gkrellshoot_07-17-18_145149](https://user-images.githubusercontent.com/39889/42839213-fd208cac-89d0-11e8-8d5a-3444798fa414.png)

originally: https://github.com/datalad/faq/issues/2

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/227 (datalad get  barfes), https://github.com/datalad/datalad/issues/2461 (datalad fails under python -OO), https://github.com/datalad/datalad/issues/1128 (Bug on "datalad get" python version 3.5), https://github.com/datalad/datalad/issues/2369 (datalad get with ssh target), and https://github.com/datalad/datalad/issues/2706 (correct way to figure out interactive "mode" on windows?).
