### ISSUE TITLE
FOI: publish --to=cache must avoid merging/pushing that remote's git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2737]
#### What is the problem?

With #2668 we can now get efficient caching etc.  But as discussed in http://git-annex.branchable.com/tips/local_caching_of_annexed_files we must not fetch or `annex merge` it.  So whenever we would "publish" to such a remote we must avoid doing anything what we typically do (fetch/merge/sync) for publishing to make it succeed.  So we should consult git settings for that remote and avoid doing those operations.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2636 (publish does not merge remote git-annex branch before pushing), https://github.com/datalad/datalad/issues/722 (Can we annex copy before git push when publishing ?), https://github.com/datalad/datalad/issues/2521 (git-annex-standalone must avoid using .xz for compression), https://github.com/datalad/datalad/issues/765 (publish does't merge remote git-annex upon publish, thus not "propagating" the knowledge about location of the load), and https://github.com/datalad/datalad/issues/18 (git-annex diff).

**Comment by yarikoptic** [comment]
FOI noted, I guess I will close it, added it to the git annex caching project
