### ISSUE TITLE
search query "adapters"?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2740]
#### What is the problem?
relates to https://github.com/datalad/datalad/issues/2726
I wondered, if may be for some simple(r) search engines where we have a flexibility to establish some custom syntax (see eg #2735) we could add "type conversion" to be performed at the query (not indexing) time (e.g. to instruct that a field is a `float`) and provide syntax for basic numerical comparisons (e.g. similar for woosh'es range)

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2052 (search '*a*' never completes), https://github.com/datalad/datalad/issues/2032 (What should search do different by default?), https://github.com/datalad/datalad/issues/1853 (basic search crashes ), https://github.com/datalad/datalad/issues/2018 (Q: why my search provided inconsistent results across different capitalizations of the query?), and https://github.com/datalad/datalad/issues/2257 (Search usecases).

**Comment by mih** [comment]
Good luck with that ;-)

**Comment by bpoldrack** [comment]
I don't think that's possible without building an index based on those types.
If you don't do that on the index itself, then you would need to be able to translate those constraints into something you can actually search for in the index, right? Which, if it's possible at all, means that you already can do it (and vice versa I think). So, if you can come up with a "translated" query for - say "a float >=2" - I'm willing to believe it's possible. ;-)

If the relation you're basing your search on is not applicable to the index, you can't make any use of it. Which in return not only means it's slow, but that it's the worst performing search possible: Just grep everything that's there, try to convert it and apply your comparison if conversion was successful.


Another story would be to apply an additional filter afterwards, of course. If the actual query can be articulated without the notion of those types and there relationships, then you can have a "syntax" to further restrict the results. If that is what you are asking for, then it's just a matter of "Is it worth the effort?", obviously.

**Comment by mih** [comment]
Closing "question"-type issue with a response, and no further activity.
