### ISSUE TITLE
grunt test fails in travis runs

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2742]
Uniformly it looks like this, and seems to affect every PR.

```
Testing datalad/resources/website/tests/test.html 
>> There was an error with headless chrome
Fatal error: net::ERR_FILE_NOT_FOUND at file:///home/travis/build/datalad/datalad/node_modules/grunt-contrib-qunit/datalad/resources/website/tests/test.html
The command "grunt test --verbose" exited with 1.
```

I have no idea what these tests do. @yarikoptic can you take a look, please.

**Comment by kyleam** [comment]
It looks like this is an [issue with 3.0.0][0], so #2748 is probably the best we can do right now.

[0]: https://github.com/gruntjs/grunt-contrib-qunit/issues/148
