### ISSUE TITLE
Support for .gitattributes manipulation and query

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2743]
Everything we have in this regard is a hack. I plan to add proper methods to GitRepo.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/154 (Support python3), https://github.com/datalad/datalad/issues/1288 (AnnexRepo() needs support for annex metadata access and manipulation), https://github.com/datalad/datalad/issues/5 (aspera support), https://github.com/datalad/datalad/issues/30 (academictorrents support), and https://github.com/datalad/datalad/issues/486 (Support installation from ZENODO).
