### ISSUE TITLE
Hidden folders files not saved when using `datalad save`

### ISSUE THREAD

**Issue by simon-dube** [datalad/datalad#2745]
#### What is the problem?
When using `datalad save` on a folder container a hidden-folder, the files from the hidden-folder are not saved. In my situation, I have user dependant files that are placed inside a hidden config folder which I want to save and publish to my remotes. However, currently, I must call an explicit save on that hidden folder for it to be successfully saved.
#### What steps will reproduce the problem?
1. Using any dataset, create a hidden folder `.name` inside a standard folder.
2. `datalad save` the parent folder
3. The hidden folder is not saved
#### What version of DataLad are you using? On what operating system?
Datalad: datalad 0.10.1
OS: Ubuntu 18.04.1 LTS
#### Is there anything else that would be useful to know in this context?
When calling `datalad save` with the hidden folder path, it is successfully saved. Only when trying to save it through a save on a parent folder is the hidden folder content not saved.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1678 ("Out of memory, getdelim failed" when using datalad save), https://github.com/datalad/datalad/issues/1723 (`datalad diff` cannot detect untracked files), https://github.com/datalad/datalad/issues/1413 (datalad add does not save files if they were staged before), https://github.com/datalad/datalad/issues/1419 (save recursive saves untracked files in submodules), and https://github.com/datalad/datalad/issues/1865 (Performance issue of save() with many files).

**Comment by kyleam** [comment]
IIUC this boils down to #1454.

**Comment by simon-dube** [comment]
Yes, I missed it. Sorry about that.
