### ISSUE TITLE
Missing files in result from datalad get and drop for identical files

### ISSUE THREAD

**Issue by simon-dube** [datalad/datalad#2746]
#### What is the problem?
If in a given folder (including its subfolders), many files happen to have the same content, when doing a `datalad get`on the parent folder, the result only contains an entry for one of the files. The same is also taking place when using `datalad drop` on a folder with many identical files.
#### What steps will reproduce the problem?
1. Inside a dataset, create a folder. Inside that folder, create 2 copies of the same file with different names. Then create a subfolder and copy the previously created file in this subfolder with a different name.
2. Use `datalad save` and `datalad publish` to send the data to any remote.
3. Use `datalad drop` to drop the folder through the Python API. The result will only display one path for a dropped file as if only a single file was dropped although three files were dropped.
3. Use `datalad get` on the first folder created in step one using the Python API. Looking at the result will only display one path for the file as they all share the same annexkey.
#### What version of DataLad are you using?
Datalad: datalad 0.10.1
OS: Ubuntu 18.04.1 LTS
#### Is there anything else that would be useful to know in this context?
I am not sure if this is a limitation from git-annex or this this was a design choice. I understand that git-annex uses the files MD5 to generate the annex key so in reality, only one git-annex object is gotten and dropped each time. However, I believe it could be a nice addition for the user to have a list of paths when many files point to the same git-annex object.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/227 (datalad get  barfes), https://github.com/datalad/datalad/issues/1953 (-J support for datalad drop), https://github.com/datalad/datalad/issues/2673 (--no-drop for datalad remove), https://github.com/datalad/datalad/issues/2369 (datalad get with ssh target), and https://github.com/datalad/datalad/issues/2276 (datalad run  misses original files which were renamed and leaves them deleted).

**Comment by bpoldrack** [comment]
This is indeed a result of datalad using git-annex, since git-annex itself is yielding results based on keys not paths. So, after the drop in your description an `git-annex get . --json` will return just one result.
There might be a way for us to figure out more precisely which paths are concerned with that key and yield less confusing results. However, I'd consider this a low-priority nice-to-have feature, which might not even be worth the effort. Whatever way we might discover to solve it might be something that doesn't really scale nicely with a reasonably big hierarchy of datasets.

**Comment by simon-dube** [comment]
I guess that git-annex in the background actually traverses every file in a folder when performing a get (however it may do something smarter which would not require this). Nonetheless, this should not be a responsibility for Datalad as like you said, this would most probably not scale nicely with bigger datasets. Thanks for the quick reply!
