### ISSUE TITLE
Symlinks not saved to the dataset

### ISSUE THREAD

**Issue by simon-dube** [datalad/datalad#2747]
#### What is the problem?
In my current setup, I have a Google Drive remote with a GitHub sibling.
When I create a symlink in a dataset and save it, I get this for result:
`save(ok): [path to dataset]`
If I publish it, it is then present on GitHub as a symlbolic link.

However, `git-annex whereis [path to symlink]` returns nothing.
Additionnally, the file cannot be dropped, resulting in: `drop(notneeded): [path to symlink] (file) [no annex'ed content]` 
When performing a `datalad get`, the following result is displayed `get(notneeded): [path to symlink] (file) [already present]`
#### What steps will reproduce the problem?
1) Create a symbolic link to any file on disk via `ln -s`
2) `datalad save [path to symlink]`
3) `datalad publish --to [remote] --transfer-data all`
#### What version of DataLad are you using?
Datalad: datalad 0.10.1
OS: Ubuntu 18.04.1 LTS
#### Is there anything else that would be useful to know in this context?
I experimented with hardlinks and I was wondering if the results I had were expected. When saving a hardlink, the actual file content was added to the `.git/annex/objects`. However, what this does is that it actually creates a copy of the file. According to what I found regarding [hard links](https://stackoverflow.com/questions/185899/what-is-the-difference-between-a-symbolic-link-and-a-hard-link), the fact that what was previously a link to a given file is now its own separate file may feel a bit odd. Usually, the hard link would still link to the original data and if this data is modified, this would appear when opening the file from the hard link. I am still new to symlinks and hardlinks, but I was wondering if an option to transform the hardlink into a symlink could be a good option. Still such a thing would also mean that deleting the original file would result in the actual file deletion which is not the case with hardlinks. The current implementation might be the best trade off regarding them, but I was curious to see if such an option could be a nice to have.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1877 (datalad save -d subds -S manages to save its top dataset where it is not even registered), https://github.com/datalad/datalad/issues/1418 (save -u  commits moved annexed files without adjusting their symlinks), https://github.com/datalad/datalad/issues/807 (Should `Dataset.create_subdataset()` save the dataset addition), https://github.com/datalad/datalad/issues/1028 (Dataset singletons), and https://github.com/datalad/datalad/issues/804 (Dataset() should be hashable).

**Comment by simon-dube** [comment]
It's a pleasure to use Datalad. The learning curve was steep (didn't know about git-annex just a few weeks ago), but once you start understanding how the different commands and the git-annex workflow, it becomes quite straight forward.

Regarding my issue, the current behaviour, that is saving the symlink itself, is actually what I want. However, it appears like it isn't tracked properly for some reason. After saving and publishing it, `git-annex whereis [symlink]` does not indicate to me where the actual symlink was published although I can see it on GitHub. I also cannot drop the symlink (possibly because it is trying to drop the file pointed to which in my case was not part of the dataset). I would have expected to be able to drop and get this symlink as any other standard file part of my dataset.

**Comment by bpoldrack** [comment]
I think, this is simply a misunderstanding of what either a symlink is or what `git-annex whereis` is for. What `git-annex whereis` is telling you, is where the actual CONTENT of a file can be found. But a symlink is a special file. In particular it is one that has no content whatsoever. There is nothing you could possibly get or drop and therefore there is nowhere `git-annex whereis` could possibly point you to. All the symlink itself is about is its sheer existence. And that's probably what you expected `git-annex whereis` to tell you, IIUC: Where is a remote repository, that also has "this" file, that happens to be a symlink? As opposed to: Where is a remote that provides the content of this file (which happens to be nothing at all in case of a symlink)?

> I would have expected to be able to drop and get this symlink as any other standard file part of my dataset.I would have expected to be able to drop and get this symlink as any other standard file part of my dataset.

This boils down to the same concept, I think. `get` and `drop` are not concerned with the existence of a file, but with the presence of its content. If you drop a file you normally end up with a broken symlink (or one-line-textfile in case of direct mode). So, in case you save the symlink itself, that's the thing you already have. If you want the symlink itself to disappear, this would be a matter of version control - switching the repository to state, that doesn't know that particular file.

Is that a comprehensible answer?

**Comment by simon-dube** [comment]
First, thank for for taking the time to provide me such a detailed answer. 

I would have thought that all files under git-annex would have been treated the same. In that sense, saving a symlink would have created a git-annex object that is itself a symlink pointing to where the original symlink pointed. However, this could possibly break relative symlinks.
The way `git-annex whereis` manages symlinks, meaning that it looks at where the linked file is saved remotely, and not the symlink itself, is what I suspected as to why I wasn't getting any results in my example.

After further testing, I realized that symlinks can actually be `datalad save`, `datalad remove` and `datalad publish` like any other file, which matches my needs. How `git-annex whereis` manages such file really threw me off. 

Thanks again!

**Comment by simon-dube** [comment]
@bpoldrack I have done some more experimenting with symlinks and I encountered a situation and I can't decide whether this should actually be implemented at my application level or within Datalad. Let's say I have a symlink at `dataset/folder1/symlink -> dataset/folder2/file.txt`. When I perform a `datalad get` on the symlink, although the file it points to is within the dataset, Datalad will not attempt to retrieve the file.

Maybe this should be implemented at my application level, meaning that I should explore symlinks when I perform `datalad get` on files or folder, but I was wondering if this is something that should/could be implemented at the Datalad level via an option like `--follow-symlinks`.

However, `git-annex get` is not implemented this way and does not offer such options. As this changes git-annex default feature, I believe if this could be implemented, that it should be done via an option. What are your thoughts on this?

**Comment by simon-dube** [comment]
Through the Python API, using `os.path.realpath` for a file provides me with the git-annex object path (`dataset/.git/annex/object/...`) from which I cannot perform a 'datalad.get'.

As of now, I have what I believe to be a correctly working implementation. I decided to use `readlink`, but on its own, this does not deal with all possible cases. For example, if I have a chain of symlinks, I must explore it until I reach the symlink that directly references the git-annex object, otherwise the `datalad get` will not provide me with the data my original symlink points to. That said, if I originally planned to perform a `datalad get` on a symlink to a file, this will manage the possible cases easily. However, if I originally wanted to perform a `datalad get` on a folder that contains symlinks, then the situation gets a bit more messy as I have to look at all the files of that folder and to search for symlinks that do not directly reference a git-annex object (meaning they are not normal files managed as symlinks by git-annex). 

Additionally, symlinks can also reference folders. In that case, I have to manually add the referenced folder (given that it is part of the dataset) to the `datalad get`. But, this folder, may also contain symlinks which I will also have to resolve to get to their actual file.

On top of that, when having a folder path that includes folder symlinks, I cannot simply perform a `os.path.join` if the symlink is relative. For example, if the symlink path is joined with `/dataset/folder2/symlink-to-folder1/file.txt` instead of `/dataset/folder1/file.txt`, then joining the git-annex relative symlink with the first path gives `/dataset/folder2/symlink-to-folder1/../.git/[...]` which is erroneous.

In addition, in order to minimize the amount of `datalad get` and to make sure no circular links could cause issues, if an actual file or folder to be gotten is already dealt with by another `datalad get` required to service the original path (most likely a parent folder), then the path is ignored.

Maybe I am getting into too much low details about the possible problems and my own implementation, but I just wanted to show that if, for a `datalad get`, I want symlinks to folders to resolve their actual folders (meaning these folders should also have their symlinks resolved), and symlinks to file to resolve their actual files, there are a few special cases to take into account making the situation a bit more complex.

**Comment by bpoldrack** [comment]
Ok, I think there's a bit of confusion here, since I thought we are just talking about symlinks pointing to other files in the dataset (not targeting something within `.git/annex/objects`), which than `datalad get` can be called on. 
However, you do have a point here, since I can see how confusing it might be for people to get their head around on what to resolve and what not to resolve in order to get done whatever they aim for. 
So, I tend to agree - can be done in datalad and probably should be done in datalad.

**Comment by mih** [comment]
Hey, it would speed up the process of fixing this, if we could have a small code snippet that creates a tiny demo dataset that illustrates the context and also the `get` call that currently fails. If I can have that I can turn it into a proper test and look into the fix.

**Comment by mih** [comment]
ATM it is unclear what can be done. Feel free to re-open with additional, though. Thx!
