### ISSUE TITLE
Convention for generator methods in *Repo classes

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2755]
The `*Repo` classes are not really intended to be the user-facing interface, but historically they offer some convenience functionality (e.g. path normalization and type conversion). Some if this turned into more of a problem than an aid. For example, when results are forcibly gathered into a list, thereby preventing any benefits of implementing top-level commands as generator.

In #2749 I started working on rectifying this, but rewriting the low-level methods to work as generators. I have added `add_()` as the generator for `add()`, while keeping the old one around. The motivation for the latter was to keep the tests/old code working.

However, the Q is, whether we should use this as a common convention to ease use even for methods that are only available as generators now (e.g. `set_metadata()`).

Please tell me what you think.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/299 (__repr__ for *Repo classes (and others)), https://github.com/datalad/datalad/issues/2488 (Even with #2417 cooked *Repo.add() still cannot become generators), https://github.com/datalad/datalad/issues/2546 (We need a cross-platform convention for paths), https://github.com/datalad/datalad/issues/1323 (get_subdatasets  should become a generator), and https://github.com/datalad/datalad/issues/1200 (Better exception(s) for paths outside of a repo).

**Comment by driusan** [comment]
I recently (yesterday) learned `set_metadata()` is a generator while writing datalad/datalad-crawler#13. As an external developer, I don't think having an `_` convention would have helped since I wouldn't have known the convention. A clear statement in the doc block (rather than having to trace through the code to find a yield statement) would have been more useful for me.

**Comment by kyleam** [comment]
> A clear statement in the doc block (rather than having to trace through the code to find a yield statement) would have been more useful for me.

Isn't this already the case?

https://github.com/datalad/datalad/blob/d0d332c9b5e17cd6b97841697d188aacd55f870c/datalad/support/annexrepo.py#L3232-L3235

**Comment by kyleam** [comment]
> However, the Q is, whether we should use this as a common convention to ease use even for methods that are only available as generators now (e.g. set_metadata()).

I vote no.  Like @driusan, I'm satisfied as long as its mentioned in the docstring.

**Comment by mih** [comment]
Let me clarify: Yes, it should be in the docstring (like in the example above). However, I was more thinking along the lines of (always) providing a companion function that works like a generate (with `_` suffix), but keep the non-generator that we already have in general.

**Comment by kyleam** [comment]
I'm fine with the `method{,_}`  pairing for cases where a non-generator function `method` already exists.  That seems preferable to the pain or churn of a wholesale conversion of `method`.
