### ISSUE TITLE
shortcut syntax to access metadata fields in the output

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2760]
Moved from https://github.com/datalad/datalad/pull/2725

we need to provide some way to shorten path to the fields in the metadata. To access any metadata field you need `{metadata[extractor][FIELD]}` to get actual field.  Since we cannot use `.` as a separator, I thought that may be we could provide support for `/` (which shouldn't be anywhere in the keys, right?) with some glob or regex semantic.  E.g. so instead of

`'{path}: {metadata[annex][participant_id]!r} {metadata[annex][sex]:>6} {metadata[annex][age]}'`

(where `!` and `:` are just for an example) I could say

'{path}: {annex/participant_id!r} {annex/sex:>6} {annex/age}'

or even

`'{path}: {*/participant_id!r} {*/sex:>6} {*/age}'`

with crash or join (`', '.join`) happening if multiple metadata records provide those fields.
edit: may be `/` in the hierarchy should/could be used in the 'query' itself to stay consistent with the output formatting...?

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1994 (Metadata parsing), https://github.com/datalad/datalad/issues/1896 (DLMSEP#1: avoid need to specify 'metadata[]' in --output-format), https://github.com/datalad/datalad/issues/935 (RF access the aggregated metadata via a parser too ), https://github.com/datalad/datalad/issues/1288 (AnnexRepo() needs support for annex metadata access and manipulation), and https://github.com/datalad/datalad/issues/256 (Updating metadata).

**Comment by yarikoptic** [comment]
if anything -- we will search it up ;)
