### ISSUE TITLE
Make a standard mode of data management operation work across all scenarios

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2765]
I want to see the following working, regardless of whether one is running on Linux, Windows, on a USB stick or wherever:

1. create a dataset (support for an arbitrary number of arbitrarily nested subdatasets)
2. apply a default configuration for annex largefiles (via .gitattributes)
    - default: everything goes into annex
    - dedicated exceptions are explicitly declared (e.g. all of `code/` has largefiles=nothing) upfront
    - support for a finite number of standard/domain-specific scenarios
3. any invocation of `run` on such a dataset leaves a clean dataset behind (assuming it started clean)
4. any manual manipulation of dataset content can be recorded with a single command, that restores the dataset to a clean state (the alternative to (3) for anything that (for whatever reasons) cannot be done through `run` (no user should be bothered with the difference of untracked/staged/typechange/whatever it should just make it clean according to configuration).

Essentially, this is implementing a "clean dataset" paradigm, where users do not have to know about or distinguish between `commit/save` and `add`, but instead split processing into some steps, and everything else is done by datalad.

I think such a mode of operation should be explained and advertised in the documentation as THE way to do things for anyone who has no preferences (or expert ambitions). Everything beyond this can require a deeper knowledge  about Git and annex, but the above should work flawless and robust without any of that.

The commands involved should have a clean (preferably minimal) API that requires minimal reading to understand it in *full*. ANY further tweaking, edge case support or geek-stuff should be implemented elsewhere. The involved commands should be promoted as the (e.g.) "convenience data management API". The set would include:

- the equivalent of minimalistic `create`
- `run`
- a command that saves everything under all circumstances according to a predefined configuration (not runtime options)

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/133 (make test -- intended to work?), https://github.com/datalad/datalad/issues/1887 (Make --run-before/after work with any command), https://github.com/datalad/datalad/issues/858 (Make ls command meta data aware), https://github.com/datalad/datalad/issues/1211 (GitRepo.tag() not working in direct mode), and https://github.com/datalad/datalad/issues/29 ("Reviewer mode").

**Comment by jbpoline** [comment]
Possibly adding "datalad retrieve my-dataset-before-last-run "

**Comment by yarikoptic** [comment]
- I am all ok for the "clean dataset" mode (config option may be?) of operation.  
- I am not convinced yet if dedicated new commands are needed/desired
- We definitely shouldn't make it the only way datalad could be used.  DataLad does provide other conveniences on top of regular git/git-annex (all the transparent boundaries between datasets, etc), so making it either "you do it this only way" or "use git/git-annex directly" would not be acceptable.

**Comment by mih** [comment]
https://github.com/datalad/datalad-revolution/pull/6 lays some ground for the save aspect of this.

**Comment by mih** [comment]
In conjunction with `run` from -core the necessary set of commands is now available in https://github.com/datalad/datalad-revolution
