### ISSUE TITLE
Kanpai!

### ISSUE THREAD

**Issue by tedstrauss** [datalad/datalad#2766]
A little sake to say thanks to @yarikoptic & @mih for steady support with this project and https://github.com/nipy/heudiconv !  

![img_1815](https://user-images.githubusercontent.com/930560/44002725-772f730c-9e15-11e8-8ca5-dacaddf06e9b.jpg)

**Comment by yarikoptic** [comment]
I guess we should keep the issue open until consumption (may be somewhere back in CA in Dec/Jan ;-))

**Comment by yarikoptic** [comment]
damn, the bottle is still unopen, but  # of issues to grave to keep pleasanties around, I will close it for now ;-)
