### ISSUE TITLE
Option to wait on running transfer when issuing a datalad get on the same file many times

### ISSUE THREAD

**Issue by simon-dube** [datalad/datalad#2768]
#### What is the problem?
In certain situations, we may call `datalad get` on the same file many times. Currently, when requesting the file content a second time, the following error is thrown:
```bash
Total (0 ok, 1 failed out of 1):   0%| | 0.00/61.5M [00:00<?, ?B/s][WARNING] Running get resulted in stderr output: git-annex: get: 1 failed
 
                                                                      [ERROR  ] transfer already in progress, or unable to take transfer lock; Unable to access these remotes: google; Try making some of these repositories available:; 	9b7e766e-eecb-4cc9-a893-cb6329d1fe1b -- [google]; ; (Note that these git remotes have annex-ignore set: github) [get(/home/simon/Documents/carmin-server/data/admin/test82/9.txt)] 
get(error): /home/simon/Documents/carmin-server/data/admin/test82/9.txt (file) [transfer already in progress, or unable to take transfer lock; Unable to access these remotes: google; Try making some of these repositories available:; 	9b7e766e-eecb-4cc9-a893-cb6329d1fe1b -- [google]; ; (Note that these git remotes have annex-ignore set: github)]
```
Note: The error was formatted this way in my terminal.

I looked at the Datalad documentation and didn't find any option that would, when calling `datalad get` on a given file another time, wait for the first `get` operation to complete and then exit normally. Such an option would solve some of the possible issues our platform could encounter through its usage of Datalad. (Please ping @glatard if further information is needed)  
 
#### What steps will reproduce the problem?
1. Publish a large file to a remote sibling.
3. Drop the large file.
2. Perform 2 concurrent `get` operations of the large file.

#### What version of DataLad are you using?
Datalad: datalad 0.10.1
OS: Ubuntu 18.04.1 LTS
Remotes: Github with a dependency to Google Drive

#### Have you had any success using DataLad before?
I have been using Datalad a lot throughout the last 7 weeks and I really enjoyed my experience. It was very challenging at first due to the particular use cases I had and the technological stack that git-annex and Datalad both represent for newcomers, but very straight forward and easy to use once the workflow is understood.

**Comment by yarikoptic** [comment]
yeah, error reporting from underlying tools could be improved

> [ERROR  ] transfer already in progress, or unable to take transfer lock

is by `git-annex` which "rightfully" locks to prevent multiple conflicting operations from happening.  If the behavior of "wait for the lock" (instead of "fail if can't acquire a lock") is **really** needed, I guess we could implement it one way (at git-annex level may be, @joeyh?) or another (in datalad).  The question would be -- wouldn't you keep piling up the processes waiting to get a lock?

**Comment by yarikoptic** [comment]
> I have been using Datalad a lot throughout the last 7 weeks and I really enjoyed my experience

THANK YOU and the feedback, and I'm really glad you found it enjoyable overall!

**Comment by simon-dube** [comment]
If the operation holding the lock is a `get` (I noticed that `update` and `publish` locks were confliting, but they weren't conflicting with `get` so I do not know if the `get`operation has its own independant lock), the idea I had was not that the second `get` should wait for the lock, but should wait for the `get` completion.

In other words, if two threads or processes try to perform `datalad get` on the same file, the thread that requested it second would only wait for the first thread to finish the `get` operation and would then use its result as its own (meaning only 1 actual `get` would have been issued in total). In that sense, maybe an option could be added to force the release of the lock so that, when the second thread tries to issue the `datalad get`, it would interrupt the first thread and initiate its own `get`.

As with some other issues I opened earlier this week, I am unsure if this is actually something that should or even could be implemented at the Datalad level. I haven't investigated to see if git-annex offers such an option, but I suppose such a feature would probably make more sense directly in there than in Datalad. It may also be much easier to implement there.

**Comment by joeyh** [comment]
I've pondered before making git-annex wait for transfer locks rather
than failing, at least as an option.

One problem with it is that if a process gets suspended with ctrl-z,
unrelated commands will hang.

When git-annex is configured to use a pid lock, there is no fine-grained
locking, so any transfer would wait on any other transfer -- but the
same lack of fine grained locking currently makes any second transfer
(by a different process) fail.

-- 
see shy jo

**Comment by disadone** [comment]
Is this problem fixed?
 How can I restart a failed one?

>Total (4 ok, 16 failed out of 149)

**Comment by yarikoptic** [comment]
For failed one, just rerun and it will try fetch they ones still missing if any left

**Comment by yarikoptic** [comment]
I believe there were a good number of fixups on git-annex end for "parallel" requests to the same key, so I would assume that the issue was resolved. And indeed subsequent `get` should get anything if something was left missing.  Feel welcome to reopen if issue persists

**Comment by jbwexler** [comment]
I seem to be running into this same issue (using git-annex 8.20210903-ga4d179c).  I'm running fmriprep subjects in parallel on TACC and each is trying to use datalad to get files from the templateflow datalad dataset. Usually one subject succeeds and the others fail due to race conditions. Here's the error output:

> (base) login4.frontera(1011)$ cat /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/.reproman/jobs/local/20220124-113614-ea3a/stderr.4
> /opt/conda/lib/python3.8/site-packages/bids/config.py:39: FutureWarning: Setting 'extension_initial_dot' will be removed in pybids 0.16.
>   warnings.warn("Setting 'extension_initial_dot' will be removed in pybids 0.16.",
> Process Process-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 201, in _datalad_get
>     api.get(filepath, dataset=str(TF_LAYOUT.root))
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
>     return return_func(generator_func)(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
>     results = list(results)
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 461, in generator_func
>     raise IncompleteResultsError(
> datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
> [{'action': 'get',
>   'annexkey': 'URL-s32363109--https://files.osf.io/v1/resourc-8aba28ce90c05e5ddadb7dcdf0c36539',
>   'error_message': 'transfer already in progress, or unable to take transfer '
>                    'lock\n'
>                    'transfer already in progress, or unable to take transfer '
>                    'lock',
>   'path': '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/sourcedata/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz',
>   'refds': '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/sourcedata/templateflow',
>   'status': 'error',
>   'type': 'file'}]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
>     retval["workflow"] = init_fmriprep_wf()
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
>     single_subject_wf = init_single_subject_wf(subject_id)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 259, in init_single_subject_wf
>     anat_preproc_wf = init_anat_preproc_wf(
>   File "/opt/conda/lib/python3.8/site-packages/smriprep/workflows/anatomical.py", line 376, in init_anat_preproc_wf
>     brain_extraction_wf = init_brain_extraction_wf(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/anat/ants.py", line 198, in init_brain_extraction_wf
>     tpl_target_path, common_spec = get_template_specs(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/utils/misc.py", line 78, in get_template_specs
>     tpl_target_path = get_template(in_template, **template_spec)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 31, in wrapper
>     return func(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 73, in get
>     _datalad_get(filepath)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 203, in _datalad_get
>     if exc.failed[0]["message"] == "path not associated with any dataset":
> KeyError: 'message'

Any recommendations?

**Comment by yarikoptic** [comment]
> (using git-annex 8.20210903-ga4d179c)

```
git-annex (8.20211231) upstream; urgency=medium 
    
...
  * Fix locking problems when annex.pidlock is set and concurrency is
    enabled eg with -J.
```

and there might have been other related fixes since then.  Is there a chance you could upgrade git-annex @jbwexler ?

**Comment by jbwexler** [comment]
Oh nice, that looks promising! I was having some trouble getting it to update on TACC but I'll try again and report back.

**Comment by jbwexler** [comment]
I can't seem to get a version newer than 8.20211123 with anaconda (https://anaconda.org/conda-forge/git-annex). And I've only ever been able to get git-annex working successfully on TACC using anaconda. Any idea how to get a newer version with anaconda? Maybe I'll leave a note on the git-annex forum.

**Comment by jbwexler** [comment]
Ok, finally was able to update to git-annex 8.20211231-gf360641 ! But unfortunately didn't solve the problem. Got various errors, sharing them all here:

> =========.reproman/jobs/local/20220130-154644-6adb/stderr.0=========
> Process Process-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 201, in _datalad_get
>     api.get(filepath, dataset=str(TF_LAYOUT.root))
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
>     return return_func(generator_func)(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
>     results = list(results)
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 461, in generator_func
>     raise IncompleteResultsError(
> datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
> [{'action': 'get',
>   'annexkey': 'URL-s32363109--https://files.osf.io/v1/resourc-8aba28ce90c05e5ddadb7dcdf0c36539',
>   'error_message': 'git-annex: git [Param "config",Param '
>                    '"remote.gin-src.annex-uuid",Param '
>                    '"5051dd1f-b5e4-47e2-89e4-989c070aa543"] failed\n'
>                    'CallStack (from HasCallStack):\n'
>                    'error, called at ./Git/Command.hs:42:17 in '
>                    'main:Git.Command',
>   'path': '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/sourcedata/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz',
>   'refds': '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/sourcedata/templateflow',
>   'status': 'error',
>   'type': 'file'}]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
>     retval["workflow"] = init_fmriprep_wf()
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
>     single_subject_wf = init_single_subject_wf(subject_id)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 259, in init_single_subject_wf
>     anat_preproc_wf = init_anat_preproc_wf(
>   File "/opt/conda/lib/python3.8/site-packages/smriprep/workflows/anatomical.py", line 376, in init_anat_preproc_wf
>     brain_extraction_wf = init_brain_extraction_wf(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/anat/ants.py", line 198, in init_brain_extraction_wf
>     tpl_target_path, common_spec = get_template_specs(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/utils/misc.py", line 78, in get_template_specs
>     tpl_target_path = get_template(in_template, **template_spec)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 31, in wrapper
>     return func(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 73, in get
>     _datalad_get(filepath)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 203, in _datalad_get
>     if exc.failed[0]["message"] == "path not associated with any dataset":
> KeyError: 'message'
> 
> 
> 
> 
> 
> 
> =========.reproman/jobs/local/20220130-154644-6adb/stderr.1=========
> 
> 
> 
> 
> 
> 
> =========.reproman/jobs/local/20220130-154644-6adb/stderr.2=========
> Process Process-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 201, in _datalad_get
>     api.get(filepath, dataset=str(TF_LAYOUT.root))
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
>     return return_func(generator_func)(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
>     results = list(results)
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 461, in generator_func
>     raise IncompleteResultsError(
> datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
> [{'action': 'get',
>   'annexkey': 'MD5E-s1751209--e401c5b0311864c4c2f3625c9617374f.nii.gz',
>   'error_message': 'transfer already in progress, or unable to take transfer '
>                    'lock\n'
>                    'transfer already in progress, or unable to take transfer '
>                    'lock\n'
>                    'transfer already in progress, or unable to take transfer '
>                    'lock',
>   'path': '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/sourcedata/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-fMRIPrep_boldref.nii.gz',
>   'refds': '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/sourcedata/templateflow',
>   'status': 'error',
>   'type': 'file'}]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
>     retval["workflow"] = init_fmriprep_wf()
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
>     single_subject_wf = init_single_subject_wf(subject_id)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 370, in init_single_subject_wf
>     func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/bold/base.py", line 438, in init_func_preproc_wf
>     initial_boldref_wf = init_bold_reference_wf(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/func/util.py", line 192, in init_bold_reference_wf
>     enhance_and_skullstrip_bold_wf = init_enhance_and_skullstrip_bold_wf(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/func/util.py", line 447, in init_enhance_and_skullstrip_bold_wf
>     bold_template = get_template(
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 31, in wrapper
>     return func(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 73, in get
>     _datalad_get(filepath)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 203, in _datalad_get
>     if exc.failed[0]["message"] == "path not associated with any dataset":
> KeyError: 'message'
> 
> 
> 
> 
> 
> 
> =========.reproman/jobs/local/20220130-154644-6adb/stderr.3=========
> Process Process-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 201, in _datalad_get
>     api.get(filepath, dataset=str(TF_LAYOUT.root))
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
>     return return_func(generator_func)(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
>     results = list(results)
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 461, in generator_func
>     raise IncompleteResultsError(
> datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
> [{'action': 'get',
>   'annexkey': 'URL-s32363109--https://files.osf.io/v1/resourc-8aba28ce90c05e5ddadb7dcdf0c36539',
>   'error_message': 'transfer already in progress, or unable to take transfer '
>                    'lock\n'
>                    'transfer already in progress, or unable to take transfer '
>                    'lock',
>   'path': '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/sourcedata/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz',
>   'refds': '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/sourcedata/templateflow',
>   'status': 'error',
>   'type': 'file'}]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
>     retval["workflow"] = init_fmriprep_wf()
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
>     single_subject_wf = init_single_subject_wf(subject_id)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 259, in init_single_subject_wf
>     anat_preproc_wf = init_anat_preproc_wf(
>   File "/opt/conda/lib/python3.8/site-packages/smriprep/workflows/anatomical.py", line 376, in init_anat_preproc_wf
>     brain_extraction_wf = init_brain_extraction_wf(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/anat/ants.py", line 198, in init_brain_extraction_wf
>     tpl_target_path, common_spec = get_template_specs(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/utils/misc.py", line 78, in get_template_specs
>     tpl_target_path = get_template(in_template, **template_spec)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 31, in wrapper
>     return func(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 73, in get
>     _datalad_get(filepath)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 203, in _datalad_get
>     if exc.failed[0]["message"] == "path not associated with any dataset":
> KeyError: 'message'
> 
> 
> 
> 
> 
> 
> =========.reproman/jobs/local/20220130-154644-6adb/stderr.4=========
> Process Process-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 201, in _datalad_get
>     api.get(filepath, dataset=str(TF_LAYOUT.root))
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
>     return return_func(generator_func)(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
>     results = list(results)
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 461, in generator_func
>     raise IncompleteResultsError(
> datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
> [{'action': 'get',
>   'annexkey': 'MD5E-s1751209--e401c5b0311864c4c2f3625c9617374f.nii.gz',
>   'error_message': 'git-annex: '
>                    '.git/annex/tmp/MD5E-s1751209--e401c5b0311864c4c2f3625c9617374f.nii.gz: '
>                    'removeLink: does not exist (No such file or directory)',
>   'path': '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/sourcedata/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-fMRIPrep_boldref.nii.gz',
>   'refds': '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/sourcedata/templateflow',
>   'status': 'error',
>   'type': 'file'}]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
>     retval["workflow"] = init_fmriprep_wf()
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
>     single_subject_wf = init_single_subject_wf(subject_id)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 370, in init_single_subject_wf
>     func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/bold/base.py", line 438, in init_func_preproc_wf
>     initial_boldref_wf = init_bold_reference_wf(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/func/util.py", line 192, in init_bold_reference_wf
>     enhance_and_skullstrip_bold_wf = init_enhance_and_skullstrip_bold_wf(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/func/util.py", line 447, in init_enhance_and_skullstrip_bold_wf
>     bold_template = get_template(
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 31, in wrapper
>     return func(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 73, in get
>     _datalad_get(filepath)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 203, in _datalad_get
>     if exc.failed[0]["message"] == "path not associated with any dataset":
> KeyError: 'message'
> 
> 
> 
> 
> 
> 
> =========.reproman/jobs/local/20220130-154644-6adb/stderr.5=========
> Process Process-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 201, in _datalad_get
>     api.get(filepath, dataset=str(TF_LAYOUT.root))
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
>     return return_func(generator_func)(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
>     results = list(results)
>   File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 461, in generator_func
>     raise IncompleteResultsError(
> datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
> [{'action': 'get',
>   'annexkey': 'MD5E-s3926061--4e45306d37914e8cd24a9de931db6f22.nii.gz',
>   'error_message': 'git-annex: '
>                    '.git/annex/tmp/MD5E-s3926061--4e45306d37914e8cd24a9de931db6f22.nii.gz: '
>                    'removeLink: does not exist (No such file or directory)',
>   'path': '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/sourcedata/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_label-brain_probseg.nii.gz',
>   'refds': '/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/sourcedata/templateflow',
>   'status': 'error',
>   'type': 'file'}]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
>     retval["workflow"] = init_fmriprep_wf()
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
>     single_subject_wf = init_single_subject_wf(subject_id)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 370, in init_single_subject_wf
>     func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
>   File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/bold/base.py", line 438, in init_func_preproc_wf
>     initial_boldref_wf = init_bold_reference_wf(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/func/util.py", line 192, in init_bold_reference_wf
>     enhance_and_skullstrip_bold_wf = init_enhance_and_skullstrip_bold_wf(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/func/util.py", line 489, in init_enhance_and_skullstrip_bold_wf
>     get_template(
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 31, in wrapper
>     return func(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 73, in get
>     _datalad_get(filepath)
>   File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 203, in _datalad_get
>     if exc.failed[0]["message"] == "path not associated with any dataset":
> KeyError: 'message'
