### ISSUE TITLE
Travis runs for master are failing

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2769]
See https://travis-ci.org/datalad/datalad/builds/415960427

Here is a snippet from [datalad/jobs/415960430](https://travis-ci.org/datalad/datalad/jobs/415960430):

```
======================================================================
ERROR: Failure: CommandError (CommandError: command '['git', 'config', '-z', '-l', '--show-origin']' failed with exitcode 134
Failed to run ['git', 'config', '-z', '-l', '--show-origin'] under None. Exit code=134. out=rm: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type
_LC_TIME[0]))' failed.
Aborted (core dumped)
 err=cmp: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Aborted (core dumped)
rm: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Aborted (core dumped)
)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
  File "/home/travis/build/datalad/datalad/datalad/__init__.py", line 53, in <module>
    cfg = ConfigManager()
  File "/home/travis/build/datalad/datalad/datalad/config.py", line 204, in __init__
    self.reload(force=True)
  File "/home/travis/build/datalad/datalad/datalad/config.py", line 258, in reload
    stdout, stderr = self._run(run_args, log_stderr=True)
  File "/home/travis/build/datalad/datalad/datalad/config.py", line 526, in _run
    out = self._runner.run(['git', 'config'] + args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/cmd.py", line 672, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/cmd.py", line 532, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
CommandError: CommandError: command '['git', 'config', '-z', '-l', '--show-origin']' failed with exitcode 134
Failed to run ['git', 'config', '-z', '-l', '--show-origin'] under None. Exit code=134. out=rm: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type
_LC_TIME[0]))' failed.
Aborted (core dumped)
 err=cmp: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Aborted (core dumped)
rm: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Aborted (core dumped)
```

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2742 (grunt test fails in travis runs), https://github.com/datalad/datalad/issues/2530 (Known-to-fail test runs on windows), https://github.com/datalad/datalad/issues/12 (gets stuck on travis while running annex command), https://github.com/datalad/datalad/issues/843 (git clone fails in master branch (actually: NOT)), and https://github.com/datalad/datalad/issues/2480 (Run the tests of essential extensions on travis for datalad-core).

**Comment by yarikoptic** [comment]
I suspect locale handling issue where we reverted to use "stock git-annex" approach (attn @joeyh) ... I will now "quickly" reintroduce my debian/patches/standalone-no-LOCPATH patch and reupload unless @joeyh has a direct/quicker clue/fix ;-)

**Comment by yarikoptic** [comment]
if https://travis-ci.org/datalad/datalad/builds/416028559 pass we will declare a victory! (or at least not a complete disaster) - I've blindly uploaded 6.20180807+git63-gbafc55c4a-1~ndall+1 fresh build where I reintroduced that patch.  If no crashes - I do not know if that is due to may be some fixup in haskell libraries since the last moment or indeed not setting LOCPATH and just relying on system wide locales was sufficient, but at least it would keep us going

**Comment by yarikoptic** [comment]
and it did pass

**Comment by yarikoptic** [comment]
@joeyh FYI: our "CRON" runs of datalad testsuite on travis have dedicated runs against your stock (not our neurodebian) builds of git-annex.  We rarely look at them unfortunately but apparently they were failing for a while with that locale issue, see e.g. https://travis-ci.org/datalad/datalad/builds/411848815  where only those two runs where we test against your build (DL_UPSTREAM_ANNEX) and the neurodebian -devel version (DL_DEVEL_ANNEX, where I've uploaded 6.20180720+gitg03978571f-1~ndall+1 first) where failing.
