### ISSUE TITLE
FOI: git gc cound be running in the background from the previous git command

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2771]
#### What is the problem?
https://stackoverflow.com/questions/39600398/how-can-i-view-progress-of-git-gc-in-the-background

well, we usually just disable gc entirely (should probably re-enable during `commit` ;-)) so we do not see it much but I just ran into it while doing that "ultimate cache" script and wasn't aware of it.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2291 (Extract previous  'datalad run' commands into a script), https://github.com/datalad/datalad/issues/1887 (Make --run-before/after work with any command), https://github.com/datalad/datalad/issues/2315 (FOI OSX: sysctl: command not found), https://github.com/datalad/datalad/issues/2072 (Split datalad run into run and rerun commands?), and https://github.com/datalad/datalad/issues/1738 (Missing commands to be able to avoid git for most common usage).

**Comment by yarikoptic** [comment]
I think we know about it now, so could just close
