### ISSUE TITLE
Doc builds on Travis fail with latest Sphinx 

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2774]
The `make -C docs html doctest` step of [Travis runs](https://travis-ci.org/datalad/datalad/builds/418405497) seem to be consistently failing with

```
Warning, treated as error:
/home/travis/build/datalad/datalad/docs/source/generated/cfginfo/dataset.rst:document isn't included in any toctree
```

This seems to be related to Sphinx v1.7.7, which was released two days ago.  I don't spot any Travis runs that have this failure with Sphinx v1.7.6, and locally I can reproduce the issue with v1.7.7 but not v1.7.6.

I've yet to dig further.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2769 (Travis runs for master are failing), https://github.com/datalad/datalad/issues/2197 (Travis and docs refer to obsolete variable), https://github.com/datalad/datalad/issues/2742 (grunt test fails in travis runs), https://github.com/datalad/datalad/issues/116 (Build module reference (I guess with sphinx)), and https://github.com/datalad/datalad/issues/212 (Tests fail when Debian package is built on offline system).

**Comment by kyleam** [comment]
See sphinx-doc/sphinx#5327
