### ISSUE TITLE
can't register (well -- "add") a locally available handle to the master/localcollection

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#278]
which as to me once again just a ramification of the "masterfulness" specialty of the localcollection: `add-handle` demands `collection` in the argument but refuses to understand magical word "localcollection"

**Comment by bpoldrack** [comment]
Okay, two things:
1. You're right - it should understand "localcollection", of course.
2. Why would you need to manually add a handle to the master? Just want to understand the usecase.

**Comment by yarikoptic** [comment]
otherwise how do I "Register" a handle I might have got locally? (may be I had it hidden in some archive somewhere on a stick etc)

**Comment by bpoldrack** [comment]
No, you're totally right. There is no specialty of the localcollection
intended. It should understand it's own name. I just forgot to do it. It's
a bug. "add-handle" is supposed to work in that case.

2015-10-17 19:29 GMT+02:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by hanke** [comment]
Obsolete.
