### ISSUE TITLE
datalad siblings add hangs 

### ISSUE THREAD

**Issue by jbpoline** [datalad/datalad#2781]
#### What is the problem?

I would like to add some metadata to some existing datasets in datalad.datasets.org. I thought I could
1) install datalad.datasets.org locally
2) create a git repo named datalad.datasets.org in my github workspace
3) add locally some metadata
4) create a new "siblings" with 

`datalad siblings add -d . -s jb --url git@github.com:jbpoline/datasets.datalad.org.git`

change things locally and then publish on git@github.com:jbpoline/datasets.datalad.org.git

This takes a **very** long time ... but eventually (5-10min ?) tells me:
[INFO   ] Failed to enable annex remote jb, could be a pure git or not accessible 
[WARNING] Failed to determine if jb carries annex. Remote was marked by annex as annex-ignore.  Edit .git/config to reset if you think that was done by mistake due to absent connection etc 

So, **DataLad is right** :)  There was nothing at this url yet. 
But 1) should it just quickly say that there is not annex ?  2) what kind of check is done at that stage ? 3) am I taking the right route ? 
 

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

DataLad
=======
Version     : 0.10.2
Full version: 0.10.2

System
======
OS          : posix Linux 4.4.8-040408-generic #201604200335 SMP Wed Apr 20 07:37:30 UTC 2016
Distribution: Ubuntu/16.04/xenial

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1438 (add sibling should understand DataLad RIs), https://github.com/datalad/datalad/issues/1191 (infinite recursion of datalad ls  when create-sibling), https://github.com/datalad/datalad/issues/1682 (datalad publish hangs indefinetely while pushing when it has no permission?), https://github.com/datalad/datalad/issues/2005 (datalad create-sibling-github doesn't support oauth), and https://github.com/datalad/datalad/issues/1264 (datalad ls --siblings  to list status/diff from siblings status).

**Comment by yarikoptic** [comment]
To which particular datasets you would like to add metadata and in what format?

**Comment by jbpoline** [comment]
to the adhd200 - format would be the jsonld (as flat as possible, still experimenting !) coming from the nidm ttl ... (Nolan started something with Michael on this)
Then - may be there is a way to update the dataset on datalad.datasets.org ?

**Comment by yarikoptic** [comment]
if you are adding it to the entirety of the adhd200, not per site, then it is sufficient to publish the clone for that dataset alone http://datasets.datalad.org/?dir=/adhd200/RawDataBIDS  .  You could use `datalad create-sibling-github` to create a github repo for it, but we would need some location to push the jsonld metadata file.  If you would like to have them per each site (we have them as separate subdatasets) - that would be trickier with github. @mih could remind if we have got the "flattening" feature working properly.

**Comment by mih** [comment]
I am closing this issue now, because I believe @yarikoptic has answered it appropriately at the time. Meanwhile the messaging and progress reporting should have been improved substantially.

If this stays or becomes an issue again, please feel free to reopen it. Thx!
