### ISSUE TITLE
datalad-run: globs are expanded too early (not often enough)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2789]
When inputs come from an uninstalled subdataset glob expansion does not work as expected (by me). Globs are expanded giving the initial state on the file system, before `get` will obtain the missing subdataset. This will results in something like this:

```
install(ok): inputs/raw_eyegaze (dataset) [Installed subdataset in order to get inputs/raw_eyegaze/sub-*/beh/sub-*_task-movie_run-*_recording-eyegaze_physio.tsv.gz]
get(notneeded): inputs/raw_eyegaze/sub-*/beh/sub-*_task-movie_run-*_recording-eyegaze_physio.tsv.gz (file) [already present]
```

with no files being obtained. Simply running the exact same command again gives the desired result, as the subdataset is now present.

I suspect the same would happen on `rerun` with just the root dataset present, unless arguments get expanded in the run record.

It would be nice to catch this condition.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/230 (datalad get   should not glob by default), https://github.com/datalad/datalad/issues/2660 (datalad run does not save staged changes), https://github.com/datalad/datalad/issues/2073 (Error when running datalad crawl), https://github.com/datalad/datalad/issues/1193 (datalad mv), and https://github.com/datalad/datalad/issues/2475 (DataLad installing/running on Win10 Professional).

**Comment by kyleam** [comment]
Thanks for pointing that out.  That is a problem.
