### ISSUE TITLE
Make "central super-dataset" location configurable

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2792]
Per @notestaff wish:  why not to make central super-dataset location configurable (common_cfg.py) instead of a plain constant in consts.py ?

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1028 (Dataset singletons), https://github.com/datalad/datalad/issues/656 (ADHD200 dataset), https://github.com/datalad/datalad/issues/1799 (datalad run  records pwd as was ran within super-dataset), https://github.com/datalad/datalad/issues/36 (Mitchell's dataset), and https://github.com/datalad/datalad/issues/804 (Dataset() should be hashable).

**Comment by notestaff** [comment]
@yarikoptic Until this is implemented, is it safe to make a symlink from the home dir to somewhere else?

**Comment by yarikoptic** [comment]
It should be. We have paid special attention to symlinks in the paths, and have some test runs on Travis in obscure setups... Having said that, YMMV ;-)
