### ISSUE TITLE
Enable codecov on appveyor

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2797]
Original appveyor setup already includes some commented out snippet, and atm we do not have coverage contribution from appveyor. Example https://www.appveyor.com/blog/2017/03/17/codecov/ is quite different from the snippet we have

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2062 (ENH: enable AutomagicIO upon import by setting an environment variable), https://github.com/datalad/datalad/issues/1781 (Inform about non-auto-enabled special remotes), https://github.com/datalad/datalad/issues/852 (Enable `aggregate_metadata` to obtain meta data files), and https://github.com/datalad/datalad/issues/1087 (enable post-commit hook on the webserver to avoid direct edits break the access).

**Comment by mih** [comment]
Looks identical in both setups now.
