### ISSUE TITLE
question: what is .datalad/.gitattributes

### ISSUE THREAD

**Issue by notestaff** [datalad/datalad#2799]
Is this file used somehow?   Its default contents seems odd:

# Text files (according to file --mime-type) are added directly to git.
# See http://git-annex.branchable.com/tips/largefiles/ for more info.
** annex.largefiles=nothing

It seems consecutive asterisks need to be next to a slash?  https://git-scm.com/docs/gitignore
And why would you specify largefiles=nothing?   @yarikoptic

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1193 (datalad mv), https://github.com/datalad/datalad/issues/2693 (datalad aliases), https://github.com/datalad/datalad/issues/227 (datalad get  barfes), https://github.com/datalad/datalad/issues/2466 (Incorrect/confusing comment in .datalad/.gitattributes), and https://github.com/datalad/datalad/issues/562 (datalad create   booms).

**Comment by kyleam** [comment]
> Text files (according to file --mime-type) are added directly to git.

This line is incorrect and was removed in fcf57f847 (DOC: Delete an incorrect comment from .datalad/.gitattributes, 2018-05-21).

>     ** annex.largefiles=nothing
>
> It seems consecutive asterisks need to be next to a slash? https://git-scm.com/docs/gitignore

I don't believe so.  This matches everything in ".datalad/", though the second "*" is redundant.

> And why would you specify largefiles=nothing?

To make annex add files in ".datalad/" directly to git.  This line has been replaced by something more specific in 7002bdce8 (RF: Leaner .gitattribute settings forcing content into Git, 2018-05-18).

**Comment by yarikoptic** [comment]
I think that clarifies it
