### ISSUE TITLE
[question] the "dataset id" is meant to be the same for all siblings, correct?

### ISSUE THREAD

**Issue by notestaff** [datalad/datalad#2801]
Just to confirm my understanding: unlike git-annex's repository uuid, which denotes a specific copy of the repository, and is different for different copies, Datalad's "dataset id" is meant to be the same across all siblings and all branches of a dataset?  @yarikoptic

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1028 (Dataset singletons), https://github.com/datalad/datalad/issues/656 (ADHD200 dataset), https://github.com/datalad/datalad/issues/804 (Dataset() should be hashable), https://github.com/datalad/datalad/issues/2762 (Documentation - dataset.siblings() does not have result_renderer to None by default), and https://github.com/datalad/datalad/issues/36 (Mitchell's dataset).

**Comment by kyleam** [comment]
Yes, that's correct.

**Comment by yarikoptic** [comment]
Correct!  It is the "identity" of the DataLad dataset, so later on we could identify clones of the same dataset.
We considered alternatives (e.g. hexsha of the first left most commit in the history etc) but none provided robust way to say "this is some version of the dataset X", so every dataset now gets its ID upon creation.  You can use `datalad create --force REPO` to initiate such `.datalad/config` in an existing git or git-annex repository.
For completeness, altogether following "ids" could be identified which serve different identification purposes 
- DataLad dataset id (`datalad.dataset.id` config, typically in custom `.datalad/config` to be carried along with dataset) - identify the entire dataset (at any version or location)
- Git-annex uuid (`annex.uuid` config, in `.git/config`) - identity of a git clone of a dataset.  So each DataLad dataset id could have multiple Git-annex uuids
- Commit id (hexsha, or a tag, stored in git history) - identifies a version within a particular dataset.  Typically unique to a DataLad dataset id, but it is possible that multiple DataLad datasets could have some common ancestor (e.g. from a template repo, thus shared commits), but different DataLad dataset ids
- git-annex key (typically some checksum, stored in git) - identifies the content of (version of) a file, as stored in git using git-annex.  The same key could be present in multiple datasets, so not necessarily uniquely associated with any of them.

**Comment by mih** [comment]
I am reopening this, as this info should be in the docs.
