### ISSUE TITLE
simplify path produced while download-url --archive

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2802]
```
(git)smaug:/mnt/btrfs/scrap/tmp/UCLA_pamenc20[master]
$> datalad download-url --archive https://afni.nimh.nih.gov/pub/dist/data/misc/UCLA_pamenc20.tgz
[INFO   ] Downloading 'https://afni.nimh.nih.gov/pub/dist/data/misc/UCLA_pamenc20.tgz' into '/mnt/btrfs/scrap/tmp/UCLA_pamenc20/./.' 
download_url(ok): /mnt/btrfs/scrap/tmp/UCLA_pamenc20/././UCLA_pamenc20.tgz (file)                                    
add(ok): UCLA_pamenc20.tgz (file)
save(ok): /mnt/btrfs/scrap/tmp/UCLA_pamenc20 (dataset)
[INFO   ] Adding content of the archive /mnt/btrfs/scrap/tmp/UCLA_pamenc20/././UCLA_pamenc20.tgz into annex <AnnexRepo path=/mnt/btrfs/scrap/tmp/UCLA_pamenc20 (<class 'datalad.support.annexrepo.AnnexRepo'>)> 
[INFO   ] Initiating special remote datalad-archives 

```

Unnecessary `././` looks "suboptimal"

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2652 (download-url fails on URLs that end with a /), https://github.com/datalad/datalad/issues/493 (URL handling), https://github.com/datalad/datalad/issues/9 (parallel download of a file from multiple URLs (and special remotes?)), https://github.com/datalad/datalad/issues/792 (there should be no .. on top url), and https://github.com/datalad/datalad/issues/223 (install-handle URL without path should not install into curdir).
