### ISSUE TITLE
Add buildbot under WSL

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2805]
Travis doesn't support WSL yet, and not clear if it will for free in the future. Ref: https://github.com/appveyor/ci/issues/1295
So I guess I should setup buildbot instance under WSL within Windows virtual box instance.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1455 (add locking), https://github.com/datalad/datalad/issues/322 (add priorities for credentials), https://github.com/datalad/datalad/issues/1361 (AnnexRepo.add to commit only what was added), https://github.com/datalad/datalad/issues/2065 (Add duecredit support/entry), and https://github.com/datalad/datalad/issues/2781 (datalad siblings add hangs ).
