### ISSUE TITLE
Query flyweight collection of repos to precommit them while rmtree

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2807]
As noted also in the comment within the code: https://github.com/datalad/datalad/pull/2806/files#diff-31ee38bd569c9911a55587f967c2828bR329

This problem arises on Windows while frequently creating and removing temporary repositories.  There could remain some batch processes lingering around ran from the repository directory, and that causes Windows to become unhappy.  For now it is resolved by ad-hoc execution of `.precommit` within the tests where necessary, but ideally IMHO we should get some "registry" of used repositories probably as a weakref dictionary, which gets populated by our flyweight repo constructor, so `rmtree` could verify that the path to be removed does not contain any of them, and if it does, call its `.precommit`

**Comment by mih** [comment]
This entire setup is now very different, including helper waiting for pending process exit for a limited time only. I think it is save to close this issue.

**Comment by yarikoptic** [comment]
FWIW re "waiting" -- it IMHO should be fixed not become back "until complete", see #4998
