### ISSUE TITLE
Urgent: Need info on how to cite DataLad

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2810]
This is the "all versions" DOI from Zenodo: https://doi.org/10.5281/zenodo.808846

Do we already have an example of DataLad cited in the literature?

This info should go into the docs and on the website ASAP.

Thx

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1193 (datalad mv), https://github.com/datalad/datalad/issues/2693 (datalad aliases), https://github.com/datalad/datalad/issues/989 (breadcrumbs need the same aliasing datasets.datalad.org -> //), https://github.com/datalad/datalad/issues/1199 (`update` needs attention), and https://github.com/datalad/datalad/issues/1415 (need DATALAD_RNG_SEED setting).

**Comment by yarikoptic** [comment]
https://www.google.com/search?q=hanke+datalad+zenodo&oq=hanke+datalad+zenodo&aqs=chrome..69i57.6166j0j4&client=ms-android-tmobile-us&sourceid=chrome-mobile&ie=UTF-8#ip=1 does give a few hits ;-)

**Comment by mih** [comment]
Hmm, are you referring to the zenodo snippet:

Yaroslav Halchenko, Michael Hanke, Benjamin Poldrack, Kyle Meyer, Debanjum, Gergana Alteva, … Feilong Ma. (2018, July 10). datalad/datalad 0.10.2 (Version 0.10.2). Zenodo. http://doi.org/10.5281/zenodo.1308268

or to your two papers?

Am I correct to assume that you are indifferent to the citation details?

**Comment by yarikoptic** [comment]
To my two papers 
What do you mean by citation details?

**Comment by mih** [comment]
One paper just cites the URL of the webpage, the other does this:

> the DataLad data distribution (http://datalad.org; Halchenko et al., 2017; RRID:SCR_003932, RRID:SCR_003931)

where "Halchenko et al., 2017" is pointing to a version specific zenodo DIO (10.5281/zenodo.1000098), RRID:SCR_003932 does not resolve and RRID:SCR_003931 points here: 
https://scicrunch.org/scicrunch/Any/record/nlx_144509-1/SCR_003931/resolver?q=*&l=

(that last record has issues IMHO, e.g. https://github.com/datalad/datalad.org is listed as alternate URL, but it better be the code repo, not the website repo).

Q remains: what kind of citation should our docs recommend. I was proposing to use the "all versions" DOI, you seem to suggest otherwise -- maybe the next riddle will bring clarity ;-)

**Comment by yarikoptic** [comment]
RRID:SCR_003932 seems to [resolve](https://scicrunch.org/scicrunch/Any/record/nlx_144509-1/SCR_003932/resolver?q=*&l=) to Git

Indeed we should probably refer ppl to use the "all versions" doi, although it might (incorrectly) point to the version of DataLad they aren't using since it would always return the latest:
```shell
$> curl -LH "Accept: application/x-bibtex; charset=utf-8" https://doi.org/10.5281/zenodo.808846       
@misc{https://doi.org/10.5281/zenodo.808846,            
  doi = {10.5281/zenodo.808846},
  author = {Halchenko, Yaroslav and Hanke, Michael and Poldrack, Benjamin and Meyer, Kyle and {Debanjum} and Alteva, Gergana and Gors, Jason and MacFarlane, Dave and Häusler, Christian Olaf and Olson, Taylor and Waite, Alex and Vega, Alejandro De La and {Bhanuprasad14} and {Yetanothertestuser} and {Tstoeter} and {Anisha Keshavan} and {Yarikoptic-Private} and Lau, Vicky C and Hardcastle, Nell and Castello, Matteo Visconti Di Oleggio and {Kusti Skytén} and Christian, Horea and {Feilong Ma}},
  title = {Datalad/Datalad 0.10.2},
  publisher = {Zenodo},
  year = {2018}
}
```
so we might ask them to check/adjust accordingly?

**Comment by yarikoptic** [comment]
closing for now, reopen if we should discuss it further

**Comment by mih** [comment]
Reopening until this info is in the docs (and on the web page)

**Comment by mih** [comment]
Or even a Zenodo badge in the README for this repo....

**Comment by tclose** [comment]
I just had a paper accepted that uses the citation above and the journal proof editors noticed that some of the authors are listed by username instead of their real names, e.g. {Bhanuprasad14} and {Yetanothertestuser} and {Tstoeter}. Is this intentional?

**Comment by yarikoptic** [comment]
Probably you used am old citation record? Looking eg at https://zenodo.org/record/3233911/export/hx#.XQjLTHUpD3A I no longer see those

**Comment by emdupre** [comment]
I think adding the zenodo badge to the README would be super valuable ! I just came here looking for it :smile_cat: I've opened PR #3485 to add it.

**Comment by bpoldrack** [comment]
Thanks! Closing, since that PR is merged.

**Comment by mih** [comment]
https://www.datalad.org/about.html:

![image](https://user-images.githubusercontent.com/136479/124226004-ac304d00-db08-11eb-8e6d-656fbb7cfef7.png)
