### ISSUE TITLE
BF? for direct mode: diff to invoke diff/status with manual recursion or a git shim?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2813]
#### What is the problem?

It seems that we are closer to support direct mode of operation than ever before ;-)

One of the outstanding issues is inability to get `status` or `diff` in a dataset with submodules in direct mode. It is because we cannot pass --work-tree=. -c core.bare=False to the internal invocations of git, which it runs within submodules, which are also in direct mode and thus those git invocations fail.  
But for e.g. status we could tell to ignore submodules, and query status inside of them similarly "manually", and just assemble that all information ourselves through hierarchy

```shell
 $> git -c receive.autogc=0 -c gc.auto=0 --work-tree=. -c core.bare=False status
fatal: This operation must be run in a work tree
fatal: 'git status --porcelain' failed in submodule subds1

$> git -c receive.autogc=0 -c gc.auto=0 --work-tree=. -c core.bare=False status --ignore-submodules=dirty
On branch master                                                                  
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .gitmodules
	new file:   subds1
```

So it feels that we either need to manually recurse or may be provide a `git` shim like this one?

```
$> cat /tmp/git-direct/git                         
#!/bin/bash               
set -eu
cmd=$(basename $0)
thisgit=`which $cmd`
git=`which -a $cmd | grep -v "^$thisgit\$" | head -n 1`
if [ -z "$git" ]; then
    echo "Cannot find $cmd other than $thisgit in the PATH=$PATH" >&2
    exit 1
fi
echo "E: this=$thisgit git=$git"
echo I: $git --work-tree=. -c core.bare=False "$@"
$git --work-tree=. -c core.bare=False "$@"
```

which (might have some craft to be pruned, since initially I was trying to change PATH before I found GIT_EXEC_PATH) seems to help in case of status at least

```
$> GIT_EXEC_PATH=/tmp/git-direct git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .gitmodules
	new file:   subds1

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	modified:   subds1 (modified content)

```

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1210 (Prevent GitRepo from calling `git add` in direct mode), https://github.com/datalad/datalad/issues/1180 (ok_clean_git() broken in direct mode), https://github.com/datalad/datalad/issues/1264 (datalad ls --siblings  to list status/diff from siblings status), https://github.com/datalad/datalad/issues/1131 (GitRepo.add_submodule() is incompatible with direct mode), and https://github.com/datalad/datalad/issues/1211 (GitRepo.tag() not working in direct mode).

**Comment by yarikoptic** [comment]
upon discussion with @kyleam decided that it is not a good idea
