### ISSUE TITLE
--git-opts are not just ignored -- they interfere for create --shared-access

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2818]
#### What is the problem?
Originally reported https://neurostars.org/t/datalad-throwback-doing-as-im-told/2144
```
$ datalad create -D "Central Repo (origin) Project" -d . --shared-access group --git-opts bare project
[WARNING] `git_opts` argument is presently ignored, please complain!
[ERROR  ] 'str' object does not support item assignment [create.py:__call__:291] (TypeError)
```

Clearly if it is ignored, shouldn't interfere and/or error message should be more adequate
```shell
$> datalad_ --dbg create --shared-access group --git-opts bare project 
[WARNING] `git_opts` argument is presently ignored, please complain! 
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 495, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/base.py", line 628, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 491, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/create.py", line 301, in __call__
    git_opts['shared'] = shared_access
TypeError: 'str' object does not support item assignment
()
> /home/yoh/proj/datalad/datalad/datalad/distribution/create.py(301)__call__()
-> git_opts['shared'] = shared_access
(Pdb) p git_opts
'bare'
(Pdb) p shared_access
'group'
```

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1314 (git-annex-status to ignore submodules), https://github.com/datalad/datalad/issues/1223 (Unclear git-annex "access" failure), https://github.com/datalad/datalad/issues/204 (AnnexRepo doesn't allow access "not yet touched by annex" git (with annex) clone if create=False), https://github.com/datalad/datalad/issues/2582 (git-annex: failed to create OS thread: Cannot allocate memory), and https://github.com/datalad/datalad/issues/2473 (Should `run` have --to-git?).

**Comment by bpoldrack** [comment]
I'm clearly for a plain `git init` call. Particularly, since this actually is the last part, where GitPython's `Repo` is not lazily instantiated. (Apart from that I want to remove it entirely anyway)
Giving it a quick try didn't instantly work, since that direct call failed to create the directory if it wasn't there. That's confusing because via command line `git init` does create it. Need to figure why this fails when called via `GitRunner`.

**Comment by mih** [comment]
FTR: This PR now does create without a GitPy init (which speeds things up) and also let's one pass arbitrary option through to `git init`: https://github.com/datalad/datalad-revolution/pull/38

**Comment by mih** [comment]
With #3383 merged, this is now fixed in master.
