### ISSUE TITLE
publishing layout

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#282]
I think it would be cozier (i.e. user accessible etc) if instead of

```
URL/<collection>/DATALAD_COL_<collection>/ # collection level
URL/<collection>/handle1/
URL/<collection>/handle2/
```

we get

```
URL/<collection>/.git # collection level
URL/<collection>/DATALAD_COL_HANDLES/handle1/
URL/<collection>/DATALAD_COL_HANDLES/handle2/
...

then it would allow easier registering of a collection etc

**Comment by bpoldrack** [comment]
Since (after implementing ;) ) we agreed on not to do it - closed.

**Comment by yarikoptic** [comment]
but we agreed to move the prefix into the suffix, right? i.e. to have
```
URL/<collection>/<collection-name>.datalad-collection/ # collection level
URL/<collection>/handle1/
URL/<collection>/handle2/
```
right? may be even `<collection-name>` could be optional and it could become `/.datalad-collection`? ;)  benefit would be -- absent duplication of collection-name, thus avoiding possibility to diverge the name from the one within the collection... then by default we could have just .datalad-collection but if necessary, in case of multiple collections available, discriminate with that optional name
