### ISSUE TITLE
whereis-published

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#283]
It might be useful to know where the hell a collection was published before (and may be in 'status' or some other command show if it is up-to-date)

**Comment by bpoldrack** [comment]
Do we really want to distinguish between remotes, that were used with datlad publish at some point and remotes, that weren't? Instead, we can have a simple check whether or not a certain remote(sibling) is up-to-date (or may be in-sync) with the local dataset.

**Comment by mih** [comment]
Closing this dated issue that is using ancient terminology and pointing the interested reader (hello, and nice to meet you!) to #1264.
