### ISSUE TITLE
Describe basic structure of extracted metadata under `.datalad/metadata`

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2831]
#### What is the problem?

http://docs.datalad.org/en/latest/metadata.html lacks any detail on how that metadata is organized. We need to describe `aggregate_v1.json` and it referencing `objects/` files within.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2753 (Exploration protocol, desired metadata structure), https://github.com/datalad/datalad/issues/1193 (datalad mv), https://github.com/datalad/datalad/issues/2189 (How .datalad/metadata/dataset.json to be born?), https://github.com/datalad/datalad/issues/1994 (Metadata parsing), and https://github.com/datalad/datalad/issues/2098 (`metadata()` will set annex metadata on annex metadata blobs).

**Comment by mih** [comment]
This is a substantial task that will take a minute...
