### ISSUE TITLE
Broken `remove` in direct mode

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2836]
Direct mode dataset with one file
```
% DATALAD_REPO_DIRECT=yes datalad create bug
[INFO   ] Creating a new annex repo at /tmp/bug 
create(ok): /tmp/bug (dataset)
(datalad3-dev) mih@meiner /tmp % cd bug
(datalad3-dev) mih@meiner /tmp/bug (git)-[annex/direct/master] % mkdir subdir
(datalad3-dev) mih@meiner /tmp/bug (git)-[annex/direct/master] % touch subdir/dummy
(datalad3-dev) mih@meiner /tmp/bug (git)-[annex/direct/master] % datalad add .
add(ok): /tmp/bug/subdir/dummy (file)
add(ok): /tmp/bug (dataset)
save(ok): /tmp/bug (dataset)
action summary:
  add (ok: 2)
  save (ok: 1)
```

`git status` not performing, as expected.
```
(datalad3-dev) mih@meiner /tmp/bug (git)-[annex/direct/master] % git status
fatal: this operation must be run in a work tree
```

Now remove the file
```
(datalad3-dev) 1 mih@meiner /tmp/bug (git)-[annex/direct/master] % datalad remove subdir/dummy --nocheck
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', '-c', 'core.bare=False', '--work-tree=.', 'rm', '-r', '--', 'subdir/dummy'] under '/tmp/bug'. Exit code=1. out= err=error: the following file has local modifications:
    subdir/dummy
(use --cached to keep the file, or -f to force removal)

error: the following file has local modifications:
    subdir/dummy
(use --cached to keep the file, or -f to force removal)
```

`git status` is now in operation?!
```
(datalad3-dev) 1 mih@meiner /tmp/bug (git)-[annex/direct/master] % git status
On branch annex/direct/master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        typechange: subdir/dummy

no changes added to commit (use "git add" and/or "git commit -a")
```

We cannot recover from this status (a `git commit` will do it, however)
```
(datalad3-dev) mih@meiner /tmp/bug (git)-[annex/direct/master] % datalad add .
add(notneeded): /tmp/bug (dataset) [nothing to add from /tmp/bug]
save(notneeded): /tmp/bug (dataset)
action summary:
  add (notneeded: 1)
  save (notneeded: 1)
(datalad3-dev) mih@meiner /tmp/bug (git)-[annex/direct/master] % datalad save
save(notneeded): /tmp/bug (dataset)
```

(datalad3-dev) mih@meiner /tmp/bug (git)-[annex/direct/master] % git annex info
repository mode: direct
trusted repositories: 0
semitrusted repositories: 3
        00000000-0000-0000-0000-000000000001 -- web
        00000000-0000-0000-0000-000000000002 -- bittorrent
        7aaa24be-6126-4195-9b1f-c6f437b0f27b -- mih@meiner:/tmp/bug [here]
untrusted repositories: 0
transfers in progress: none
available local disk space: 20.95 gigabytes (+1 megabyte reserved)
local annex keys: 1
local annex size: 0 bytes
annexed files in working tree: 1
size of annexed files in working tree: 0 bytes
bloom filter size: 32 mebibytes (0% full)
backend usage: 
        MD5E: 1

**Comment by kyleam** [comment]
Hrm I don't understand what's going on with the status.  I'll try to dig deeper some time today.  Regarding the failure itself, see d65ac64c (TST: Mark test_remove_more_than_one as a known direct mode failure, 2018-08-20).

**Comment by kyleam** [comment]
> Hrm I don't understand what's going on with the status. I'll try to dig deeper some time today.

Somehow `core.bare` is changing from true to false after the remove step.

```
cd /tmp
DATALAD_REPO_DIRECT=yes datalad create bug
cd bug
git config core.bare  # => true
mkdir subdir
touch subdir/dummy
datalad add .
git config core.bare  # => true
datalad remove subdir/dummy --nocheck
git config core.bare  # => false
```

Need to look further into where this is happening.  I can't trigger it by replacing the `datalad remove` call with a direct call to `git -c core.bare=False --work-tree=. rm -r -- subdir/dummy`.

**Comment by mih** [comment]
Ah, I think I recall that @bpoldrack temporarily changed this switch for some kind of workaround.

**Comment by kyleam** [comment]
Right, looks to be here:

https://github.com/datalad/datalad/blob/e34a20c2f5d9352a9f34e5f3871102f5e5d4a59f/datalad/support/annexrepo.py#L1225-L1237

I'll wrap that in a try-except so that core.bare always gets restored.

**Comment by mih** [comment]
Direct mode is no longer a thing.
