### ISSUE TITLE
No functioning addurl on Windows

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2869]
#### What is the problem?
Apparently addurl is busted on Windows in v6 or direct: http://git-annex.branchable.com/bugs/addurl_unittest_failing_under_windows/#comment-ad2070215a42720e17bc6b7385047346 ,  so expect many tests to fail until it is addressed

**Comment by mih** [comment]
I am closing this. I cannot replicate the issue on a win10 box with a recent git-annex.
