### ISSUE TITLE
When is the time to let direct-mode support RIP?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2877]
I would appreciate feedback on this question.

My POV: *Now*, given that direct mode support has never reached a level of functionality that allowed for meaningful operations (I am talking about actual hands-on usage, not a test that could be made to run under some circumstances). At the same time, having to care for direct-mode, and even having to wait for test runs that assure that pointless functionality isn't broken comes with real costs.

**Comment by bpoldrack** [comment]
Since it looks like v6 support is at the very least not worse ATM and annex itself solved some issues, making possible to improve at our side, I agree. We should ensure v6 to be the default on "crippled FS", since this is not (yet) the case for annex itself. This should be the first step and second disabling the test builds. Third, remove a lot of code and fourth work on better support for v6.
However, I have no really strong opinion regarding the order of the first two steps. I do see the argument for disabling tests being more urgent. But it shouldn't lead to us forgetting about the other one for a too long time ...

**Comment by yarikoptic** [comment]
@chrislfilo You are the most dedicated Windows user we have, and you previously reported success with using datalad to get some datasets.  Have you tried to do anything beyond getting datasets on Windows? Or you did, it didn't work and you just gave up on trying...?

@mih is pushing for dropping support for 'direct' mode of operation on windows in favor of v6 mode.  Both are IMHO largely workarounds for the fact of absent symlinks etc on Windows file systems. direct mode is the initial, really crude workaround, where v6 is much better and more inline with git and seamless operation.

If you are keen to try v6 mode of operation, you could `set DATALAD_REPO_VERSION=6` in your Windows shell and try to do all the regular `datalad install/get/save/add/...` and see how it goes.  It all should largely (there are corners... but much more functional than original "direct" mode) be functional already if you have recent git-annex.

You feedback would be invaluable to instruct our direction to take.

**Comment by mih** [comment]
`git config --global --add datalad.repo.version 6`

**Comment by chrisfilo** [comment]
I'll try to find some time to test it. I have not used datalad in a while.

Best,
Chris

**Comment by yarikoptic** [comment]
re default mode for crippled systems (i left a comment on that in some other breed of the same "discussion") on git annex end: monitor http://git-annex.branchable.com/todo/configuration_option_for_default___34__mode__34___on_crippled_file_systems/

**Comment by kyleam** [comment]
I tend to have a "rip it all out" reaction when it comes to decisions to drop kludges like this, so I sat on this a bit to see what arguments were raised against removing direct mode support.  I don't see a good reason to continue to support it, so I agree we should mark 0.10.3 as the last supported version, drop all the direct mode handling, and focus on improving V6 support.

**Comment by kyleam** [comment]
> What about, mark 0.10 series as the last supporting it? ;-)

Sure, and master targets to 0.11.

> So far I didn't see a single point where "improving V6 support" required removal of direct mode support, but I could be wrong.

"focus on" was the key bit the came before "improving V6 support".  It's about the headache, bandwidth, time, and messiness of maintaining some semblance direct mode support.

**Comment by mih** [comment]
I think you are. I will not touch anything in this domain, until I do not have to care about it anymore. There is need to look into add/save and lots of related bits. That is all waiting for this decision that, for some, *unkown* reason is even being debated. What is missing is a single argument in favor of continuing to "support" it. What is it that we are gaining?

**Comment by yarikoptic** [comment]
> I think you are

"I am" indeed in general... what? or how? am I specifically in this case though, I am not sure.
Anyways -- we keep running in a circle.  
If you really feel like going on a crusade right now - go and kill all direct mode support.  If needed, I will maintain a 0.10.x branch with critical bugfixes for a bit from the point before we merge that PR.
If you like to improve v6 first, while disregarding direct mode support - I would wholeheartedly welcome you!

**Comment by mih** [comment]
> If you really feel like going on a crusade right now

Erm, not really. But I do want to disable direct mode tests, because substantial improvements are vastly more costly when having to maintain direct mode "support".

**Comment by bpoldrack** [comment]
> So far I didn't see a single point where "improving V6 support" required removal of direct mode support

I guess, that's the main confusion on what we are talking about. To "stop supporting" it, doesn't necessarily mean to instantly delete all code regarding DM, but to disable DM test builds (or move them to `allow_failure`). All it really is about for now is to not require those builds to pass (and therefore spend time debugging DM) when filing a PR.
Can we agree on this, @yarikoptic ?

**Comment by mih** [comment]
It is dead!
