### ISSUE TITLE
Enhance `datalad siblings` to list all (including not yet enabled) special remotes

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2884]
ATM
```shell
$> datalad  siblings    
.: here(+) [git]
.: s3-PUBLIC(+) [git]
.: origin(-) [https://github.com/OpenNeuroDatasets/ds000001 (git)]
```
whenever
```shell
$> git annex info
repository mode: indirect
trusted repositories: 0
semitrusted repositories: 5
	00000000-0000-0000-0000-000000000001 -- web
 	00000000-0000-0000-0000-000000000002 -- bittorrent
 	1b4b718e-91d9-4da9-9b80-02a2d1bb9363 -- s3-PRIVATE
 	2f2712ed-a89d-4216-9a8c-0237503e0db4 -- yoh@hopa:/tmp/ds000001 [here]
 	b5dd2e3d-825f-4bc2-b719-cba1059f6bfc -- root@93184394ac19:/datalad/ds000001
untrusted repositories: 1
	deaa691f-c824-4416-9bf8-a94a47dd31b5 -- [s3-PUBLIC]
transfers in progress: none
available local disk space: 20.51 gigabytes (+1 megabyte reserved)
local annex keys: 0
local annex size: 0 bytes
annexed files in working tree: 80
size of annexed files in working tree: 2.42 gigabytes
bloom filter size: 32 mebibytes (0% full)
backend usage: 
	MD5E: 80
```
we seems to
- list only enabled
   - [ ] would be nice to get `--all` flag or a like to list all known remotes, e.g. here `s3-PRIVATE`, `root@93184394ac19:/datalad/ds000001`. Not sure about web and torrent since they are omnipresent
- even for special remotes list them as `[git]` (I guess because there a git remote configured for it now by annex, although git can do nothing with it).  
   - [ ] Would be nice to have annex special remotes as `[annex-special]`, git remotes with annex-uuid as `[annex]`.

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.

**Comment by adswa** [comment]
ping #4193
