### ISSUE TITLE
How to handle/provide annex.retry  option?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2896]
#### What is the problem?
Apparently the recently added to annex ability to retry failed downloads is disabled ([annex.retry defaults to 0](http://git-annex.branchable.com/bugs/some_transfers_for_get_-J4_fail_over_ssh__47__rsync_and_require_retry/#comment-cd8d46adf300f4b92a2caca6c6f5e803)) by default.  I first thought that we could just hardcode to provide e.g. `-c annex.retry=3` to all annex calls (`self._ANNEX_GIT_COMMON_OPTIONS`), but then thought that we better have a config setting for it defaulting to 3, BUT this is already git-annex'es config setting, which might be set and we would be forcefully overriding it.  So I wondered what should be our course of action?

I think we could 
- define `datalad.annex.retry` common_cfg defaulting to 3 and describing that it would be used ONLY if configuration is not defining `annex.retry` config option
- set it in `AnnexRepo.__init__` conditional as described above

Sounds like a reasonable plan or am I missing something?

**Comment by yarikoptic** [comment]
your input @datalad/developers would be appreciated!

**Comment by yarikoptic** [comment]
ping @datalad/developers

**Comment by kyleam** [comment]
> Sounds like a reasonable plan or am I missing something?

Sounds reasonable to me.

**Comment by mih** [comment]
Verdict was "got for it", removed "on hold" tag.
