### ISSUE TITLE
fetch autoenabled special remote if it is a regular git remote

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2897]
#### What is the problem?
ATM if we e.g. clone from github with another http `git` special remote autoenabled, we do enable it, but then we do not fetch it. If its `git-annex` branch is advanced forward from what we have pushed to github, local clone lacks that information.  So I wondered if we should also `fetch` upon autoenable if that git remote (after `enableremote`) has a `url` field defined (AFAIK that is a sign that it is a regular git remote).  What do you think?

**Comment by yarikoptic** [comment]
Oh hoh, we (well @chaselgrove) ran into it within https://github.com/ReproNim/containers/issues/44 .  We better have it resolved and it should be "easy".  @kyleam would be you kind to have a look?

**Comment by kyleam** [comment]
> @kyleam would be you kind to have a look?

The original recipe from ReproNim/containers#44 fails on my end too and is resolved by #4783.
