### ISSUE TITLE
Creating subdatasets linearly slows with number of subdatasets

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2908]
Variants of this issue have been reported previously #1874 #2015 (private reports). Here is a demo that demos a particular aspect of this issue. Script to create 500 straight subdatasets of a single superdataset:

```sh
set -e -u

datalad create many
cd many
for i in $(seq 500); do
	echo $i
	/usr/bin/time -o ../create_timing.txt --append -f "%D\t%K\t%M\t%e\t%S\t%U" datalad create -d . $i
done
```

Plotting the runtime log of each invocation of `create` we can clearly see a trend were the duration more than doubles from the first to the last run:

![image](https://user-images.githubusercontent.com/136479/46650727-f07fa000-cb9d-11e8-9eed-7efe8cb0576a.png)

A likely source is the particular behavior of path annotation (which is already being addressed in https://github.com/datalad/datalad-revolution), but other explanations are possible.

**Comment by bpoldrack** [comment]
For comparison I did the same thing using just git/annex to see to what extend it's our responsibility:

```sh
set -e -u

mkdir many
cd many
git init
git annex init
for i in $(seq 500); do
	echo $i
	/usr/bin/time -o ../create_timing.txt --append -f "%D\t%K\t%M\t%e\t%S\t%U" /tmp/fake_create.sh $i
done
```

`fake_create`:

```sh
mkdir $1
git -C $1 init
git -C $1 annex init
git submodule add "./$1" $1
git commit -m "Added $1"
```

**Comment by bpoldrack** [comment]
Apart from path annotation, we do query subdatasets from within `create` to figure a possible collision. That might contribute as well. But I agree - path annotation looks like the most important factor to me.

**Comment by mih** [comment]
Update with various performance improvements from https://github.com/datalad/datalad-revolution/pull/12. Essentially there is only a single path annotation run (and a leaner one per create call). Also subdataset detection is now done differently.

![image](https://user-images.githubusercontent.com/136479/46687647-a6c5a280-cbfb-11e8-90c5-5a49b06f9142.png)

Here is the same code, but with subdataset collision detection in the parentds disabled:

![image](https://user-images.githubusercontent.com/136479/46688562-f9a05980-cbfd-11e8-8ad3-c7d8cf73cb52.png)

Going one step further and completely disable any path annotation does not seem to have a major effect either.

Side note:  the comparison with the plain git calls is not really appropriate, as those submodules do not even have a commit. We have machinery running that adds content to each subdataset etc.

**Comment by mih** [comment]
Another comparison, this time all in a single python session to avoid cost of repeated initialisation

```py
from datalad.api import rev_create as create
from time import time

ds = create('many')
for i in range(400):
    print(i)
    t = time()
    ds.rev_create('sub{}'.format(i))
    with open('create_timing_py.txt', 'a') as f:
        f.write('{}\n'.format(time() - t))
```

This is using `create` with all but the initial (single-)path annotation removed. For comparision I also disabled collision detection, and also the dry-run to figure out file sizes to be added. Nothing removes the trend. And lastly, switching to v6 also doesn't have an impact.

![image](https://user-images.githubusercontent.com/136479/46715182-3b152100-cc5f-11e8-8245-5213c73ef0d5.png)

**Comment by mih** [comment]
And just as a sanity check: creating, but no registering with a superdataset really happens at constant time...

![image](https://user-images.githubusercontent.com/136479/46716256-96e1a900-cc63-11e8-8a72-e1793932ebf0.png)

**Comment by bpoldrack** [comment]
Improvement by revolution seems pretty good to me!

> Side note: the comparison with the plain git calls is not really appropriate, as those submodules do not even have a commit. We have machinery running that adds content to each subdataset etc.

Also tried to have a commit per submodule before adding as a submodule - didn't notably change anything. My point was to figure a lower boundary on what we possibly can achieve. Even that oversimplified plain git/annex simulation shows an increase by 30%. So, we can't remove the trend itself. We only can try to come close to this.

> Not sure if we can do anything better at this point.

Not sure either. However, revolution seems to be the right approach. Since it aims to reduce the sheer number of git calls altogether, I think it's likely to yield additional improvement over time, even if just by a constant (which matters in reality).

**Comment by mih** [comment]
Alrighty. No need to keep this open any longer, I guess.
