### ISSUE TITLE
RFC: our reliance on PWD env var backfires...

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2910]
#### What is the problem?
If users use datalad as a python module, and they, or some other process (jupyter?), switches to another workdir (obviously using `os.chdir`, not our `chpwd`) then any datalad command operating on relative filenames would fail with confusing errors or just would do the wrong thing... causes confusion, frustration, etc. Definitely we should mitigate it somehow.

Background: Use of env var PWD was introduced with the sole purpose of being able to operate on (compare etc) full paths while some directory in the path is a symlink and then `os.getcwd()` would return dereferenced path. It might be that one of the initial use-cases was a "subdataset" which is just symlinked from another location? because otherwise I think we could have just used/report full dereferenced path.  Overall - not sure now what problem we were/are solving besides reporting the full path user expects to see whenever in his shell he is within such a symlinked directory.

And now I wonder what should we do in respect to the original problem that we are not really in full control of current directory.  I see possibilities

- in `getpwd` verify that envvar PWD and `os.getpwd()` point to the same directory (after realpath'ing it), and if not - return `os.getpwd()` (with some warning?).
- completely eliminate reliance on PWD and use `getpwd()`.  That might ruin that use-case which might no longer exist, and would cause a somewhat confusing reported paths not matching what user expects (e.g. on OSX IIRC users' homes might be symlinked etc)

**Comment by mih** [comment]
Had a long brain storming today re relativ paths. My conclusion was that we cannot really work with them, but have to transform them as soon as they come in, for various reasons. Not sure yet exactly what the conditions are, but I started looking into it.   re reporting: I do not yet see an elegant solution that could report paths in the same style as the input. One issue are the various reference directories we are using: Repos use the realpath (flyweight), datasets use the normpath. Paths that are exchanged between the two change their reference, ... It is a complciated beast.

**Comment by mih** [comment]
I think this issue has served its purpose. Current datalad has a pretty consistent handling of paths (absolute an relative) now.
