### ISSUE TITLE
Give hints on how to revert/cleanup whenever "run" fails

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2924]
#### What is the problem?
Follow up to https://github.com/datalad/datalad/pull/2922#issuecomment-429996043

If `run` fails, repo could be left in a dirty state with some new  and/or changed (unlocked) files.  User would need to figure out not only how to fix his command to run, but also how to revert back to the clean state.  So it would be nice to give either specific instruction or hints ("Use `git reset --hard && git clean -dfx` to get to the clean state before running the command again")

**Comment by adswa** [comment]
This has been addressed by https://github.com/datalad/datalad/pull/6112
