### ISSUE TITLE
Rename ok_clean_git's {index,head}_modified parameters?

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2925]
I was confused recently when I saw a test call `ok_clean_git(..., index_modified=<paths>)`. I guessed that meant "the state of <paths> in the index is changed compared to HEAD" (i.e. these paths have staged changes). Instead it means "these paths in the index have changes compared the working tree" (i.e. these paths have unstaged changes). While the index is modified compared to the working tree, `index_modified` is confusing given that the most common way to get in this state is to change paths in the working tree but *not* update/modify the index.

On the other hand, I didn't have a guess about what `head_modified` would mean because it's not clear what's being diffed against HEAD. It turns out that the *index* is being diffed against HEAD, giving us staged changes. This adds to the confusion of the `index_modified` name.

So

-   `index_modified` -> index modified compared to working tree -> unstaged files
-   `head_modified` -> index modified compared to HEAD -> staged files

I'd like to rename `index_modified` to `unstaged_paths` and `head_modified` to `staged_paths`. None of the extensions that I checked used these parameters, so it looks like only the callers in datalad itself would need to be changed.

Thoughts?

**Comment by yarikoptic** [comment]
yeah, seems that naming is completely off.  I am not sure though if `(un)staged_paths` anyhow hints on files being modified.  If for "staged" it is somewhat implied, for "unstaged" not really.  `_changes` instead of `_paths`?  i.e. `unstaged_changes`, `staged_changes`?

**Comment by mih** [comment]
FTR: while only tangentially related: In -revolution I replaced this entirely with a helper that tests conditions that exist across repo modes and platforms in a more homogeneous way.

**Comment by kyleam** [comment]
> I am not sure though if (un)staged_paths anyhow hints on files being modified. 

True, there's an implied (and confusing) "modified" there.

> If for "staged" it is somewhat implied, for "unstaged" not really. _changes instead of _paths?

Sounds better to me.

**Comment by mih** [comment]
FTR: https://github.com/datalad/datalad-revolution/blob/master/datalad_revolution/tests/utils.py#L23

**Comment by kyleam** [comment]
I no longer plan to do this given that we have assert_repo_status() in master.
