### ISSUE TITLE
Need help re symlink handling concept

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2928]
I am confused, and the datalad code base seems to share some of that confusion.

Example:
```
ds/
  symlink/ -> subds/dir1/dir2
  subds/
    dir1/
      dir2/
        file
```

Two paths to `file` are possible:
- `<pathto_ds>/symlink/file`
- `<pathto_ds>/subds/dir1/dir2/file`

If I want to figure out what dataset `file` is in (e.g. to find the dataset to commit it too, or `get_dataset_root()` I always want to find `subds`. Given the above paths, this is only possible when symlinks get resolved. No biggie so far.

Now what happens, if `pathto_ds` itself contains a symlink, e.g.
- `PWD` is a dir that involves a symlink (we have `dlabspath()` to somewhat deal with this situation, but it doesn't seem to be used consistently)
- `pathto_ds` is an abspath that involves one or more symlinks

I both cases the symlink resolution above might cause the path to `subds` no longer share a common prefix with the path to `ds`, or with the original query path (at which point a substantial amount of logic in datalad falls apart). Of course, `symlink` could also point completely outside `ds`, in which case this would be "fine" and we would want to error in a meaningful way.

Note, however, that in case of initial path resolution it is unknown whether there is a `ds` or `subds` at all, hence much of the relevant context for specific decision  making isn't yet available and only becomes clear much further down the road, when paths are resolved already and now need to be interpreted.

But things might be worse in some cases. While we are not causing this situation ourselves, a repo might be a submodule that has its `.git` in the standard location underneath the `.git` of the parent repo. If we resolve *any* symlink that belongs to an annexed file, it would resolve into another dataset entirely... and leave me in tears.

So it looks to me as if:
- we always want to resolve paths with symlinks that point to directories (not the entire path, but any symlink that is a component in that path)
- we never want to resolve paths with symlinks that point to files (same constraint as above)

Two further aspects that make things even more complicated:

1. We are dealing with path requests to things that do not (yet) exist on the file system on a regular basis. In such cases we cannot apply the above decision rules (in full), until the situation can be inspected on in the FS
2. So far we are trying to report result paths in the same reference frame as the input path, e.g. when a dataset is known (instance was created with a path that contains symlinks), symlinks are not resolved.
    This works when a dataset is explicitly given, or if dataset discovery upwards of a path does not hit any symlinks on the way to the first dataset root, but in the general case it does not work (as shown above).

As far as I am aware this summaries the root cause of all issues with symlinks in paths that we have. We have a bunch of places that wrangle such paths, and we should condense them to a single one -- but ATM I have no concept of how we should deal with this in general.

Please let me know what you think.

Specifically:

- in which cases should we maintain symlinks in reported paths?
- what is a sane symlink resolution logic for an arbitrary input path (when no dataset reference is known yet, i.e. look for the containing dataset as in the initial example), for both absolute and relative paths -- that latter is even trickier IMHO

### Use of normpath()

We are using this approach heavily to simplify paths for "in-dataset?" comparisons. But I think this is dangerous (and it least I am not aware of a centralized protection again abuse in datalad). Demo:

```
% tree
.
├── dir1
│   └── dir2
│       └── file
└── link -> dir1/dir2
```

Regardless of whether using absolute paths or relative ones the outcome is always wrong:

```
In [2]: op.normpath('link/../dir2/file')
Out[2]: 'dir2/file'

In [3]: op.normpath('/tmp/this/link/../dir2/file')
Out[3]: '/tmp/this/dir2/file'
```

And again, in any situation were those paths are not yet available (e.g. if `dir2` is an uninstalled subdataset, we have no chance of detecting such error of judgement).

I think any use of normpath() is evil when there is any chance that symlinks are involved.

**Comment by bpoldrack** [comment]
Re normpath:
Agree, that's an issue. It was introduced to have a canonical form to compare paths (for common prefix for example). And for that, it's kind of the right thing, but only after whatever resolution strategy we come up with regarding the more general issue. Does pathlib provide something similar to `os.normpath`? May be we don't need it at all, when we switch?

Re general symlink resolution:
Need to think about it. Solution isn't obvious to me.

**Comment by mih** [comment]
pathlib does not have normpath or anything like it, because what normpath does is simply not valid for an arbitrary POSIX path that may or may not contain symlinks to directories (pathlib docs call this functionality "a naïve approach").

At the very least we would have to have specific normpath implementation that does NOT remove any `..` if any of the components is a symlink to a directory. But keep in mind: in the general case, we will not know whether this is the case (nothing yet on the filesystem), hence, in general, we cannot do what normpath does.

**Comment by mih** [comment]
More fun: I just learned that even on Windows (without any symlinks involved) we might need to resolve input paths, as they might come in in "DOS path" form, and need to become a full windows path in order to have our machinery working:

These guys:

`C:\PROGRA~1` -> `C:\Program Files`

Life is a bitch.

**Comment by bpoldrack** [comment]
Re windows: There has to be some (windows only) package dealing with that. It actually is not like a symlink (FS feature), but a different (older) windows API, that reports those 8.3 char paths for backwards compatibility. However, finding such a package or tool may enable us to deal with it like a symlink. If I'm not mistaken we could detect such a thing by its containing `~` and then resolve it, following the same strategy. Yes - we don't have a strategy yet, but at least it possibly can be treated the same way instead of raising an additional and different issue.

**Comment by yarikoptic** [comment]
yet to fully comprehend/analyze so pardon if this comment has 0 value, but regarding `normpath`:

> Regardless of whether using absolute paths or relative ones the outcome is always wrong:
> 
> ```
> In [2]: op.normpath('link/../dir2/file')
> Out[2]: 'dir2/file'
> 
> In [3]: op.normpath('/tmp/this/link/../dir2/file')
> Out[3]: '/tmp/this/dir2/file'
> ```

output sounds actually "correct" to me, since `normpath` does not (and should not) resolve any symlinks, neither test for existence of files etc.  If you need some other function, which does some clever symlink resolution, it would be something else but `normpath`.

**Comment by mih** [comment]
The output of normpath is correct, no question. But the output path no longer points to the user-intended location, and THAT is what causes some of the grief we are seeing in datalad operations.

**Comment by yarikoptic** [comment]
> ... But the output path no longer points to the user-intended location...

To me, as the user of `normpath` it points exactly to the location I intend it to point.
Indeed though, if the intention is to dereference symlinked directories while at it (e.g. for the purpose of identifying the dataset containing the symlinked location), then it would be the "incorrect" location, but such job is not of `normpath`. So indeed it smells like we need some additional helper (e.g. `dereferenced_normpath`) which would not simply operate on path strings without considering current state of the filesystem, but probably perform the checks/logic you have described.  Note that because it would need to consult the filesystem it would require corresponding (sub-)datasets to be installed, and probably must fail if any component of the path is not there... I wonder if there would be some intended uses where such actions would not be appropriate (e.g. normalizing the path for a perspective dataset/file).
Having that in mind, related 1c -- I fear that symlinks across datasets is asking for a trouble.

**Comment by mih** [comment]
I think we should focus on datalad users not normpath users. So are you saying that my example above is something that datalad should not support? That would simplify path handling quite a bit-- but it would also impact actual usage.

**Comment by yarikoptic** [comment]
> So are you saying that my example above is something that datalad should not support? 

no

**Comment by mih** [comment]
We need to come up with a definitive rule, otherwise it is impossible to even decide what a real bug looks like. For example #2885 is a real problem IMHO. Any solution should be derived from some sort of 
fundational rule.

**Comment by notestaff** [comment]
not-sure-if-relevant sidenote: git-annex commands don't follow symlinks:
https://git-annex.branchable.com/todo/symlinks_to_symlinks_to_the_annex/
maybe you can help me convince joey that they should :)

**Comment by yarikoptic** [comment]
> ... it is impossible to even decide what a real bug looks like. 

https://youtu.be/EHX7NZS8zAI
Sorry I don't know if there is CC

**Comment by mih** [comment]
@notestaff thx this ia very helpful!

**Comment by mih** [comment]
FTR: https://github.com/datalad/datalad-revolution/pull/28 now documents the behavior re symlinks in -revolution. Bottom line: a symlink is a symlink (and just that), unless it is used as a placeholder for an annexed file (by git annex itself, in locked modes). In the latter case it is treated as if it would be the actual file (reported as type 'file').

So far that seems to scale across platforms and modes -- but this is probably not the end of the journey...

**Comment by mih** [comment]
I will close this for now. When I have used the current implementation in practice for a while, I will reevaluate this.
