### ISSUE TITLE
Any test uses `get_most_obscure_supported_name()` fails on old windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2929]
It seems that the most obscure name is too obscure on windows vista, win7 seems fine. Not sure what to do about it.

No longer sure about the 'win7' is fine.

**Comment by yarikoptic** [comment]
Seeing example of failure in eg test_gitrepo could have helped to provide informed feedback.

**Comment by mih** [comment]
There is no need for feedback. Quoting breaks down. This is just a pointer for a useful starting point once a push for full windows-compat is made. Any test  that uses the default OBSCURE filename in any command execution fails.

**Comment by yarikoptic** [comment]
cool, so it is insufficient or incorrect quoting/escaping? Seeing example of failure still could have helped my hungry mind even if nobody cares about my feedback.

**Comment by yarikoptic** [comment]
What is vista? ;)
I do not think that "Any test that uses the default OBSCURE filename in any command execution fails." any longer but quoting indeed seems still to cause some issues, e.g. https://github.com/datalad/datalad/pull/5117#issuecomment-721456122 . But altogether I feel that this issue could be closed, and more specific ones should be created/tackled.
