### ISSUE TITLE
`run` helper to fake the actual execution part?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2934]
In https://github.com/datalad/datalad-htcondor we can compute results via execution on a cluster system. These results materialize back on localhost in the shape of a tarball (but that specific form is not relevant here). Other than the fact the execution happened remotely the Git record of this action should not differ (too much) from the plain `run` equivalent.

For example, when a singularity container based execution is performed, the results should be just as re-runnable locally, even if the original results were obtained from a cluster job.

I was thinking that it would be nice to have the actual "record" part of `run` be RF'ed such that one can give the original arguments as if `run` was called normally, but inputs are only obtained when a dedicated additional flag is given, and outputs are unlocked, an external mechanism now drops in the results, and then `run` takes over again and makes the record as if `run` would have orchestrated the entire thing.

Of course it doesn't actually have to be `run` that does all that, and there is no need to expose this functionality as a dedicated cmdline tool -- (two) python functions would be just fine.

**Comment by kyleam** [comment]
Yes, we also need something along these lines for @yarikoptic's vision of remote execution in niceman.  I'll have a go at this.
