### ISSUE TITLE
a way to limit search output with a single (or specified # of) hit per dataset

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2935]
#### What is the problem?
Quite a few times I wanted to find datasets which satisfy my search query, and see what (file(s)) actually satisfied it.  E.g. now I wanted to see datasets which carry files with `_acq-ap` in their names (for suggesting an enhancement to BIDS) I have used
```
datalad -f dataset -c datalad.search.index-egrep-documenttype=all search path:.*_acq-ap.*
```
which keeps dumping lots of hits per each dataset, wasting time and screen space.
Limiting output to `-f '{parentds}'` and piping to `uniq` provides a list of datasets but wastes time and cannot be used with `{path}` to also see "sample hit(s)".

I am not sure yet if there is any other similar usecase to have such a feature implemented at a "base" level (and either it would be easy to do so while interrupting underlying command generator before it exhausts itself), but definitely makes sense for the search command.

What do you think?

**Comment by yarikoptic** [comment]
@mih - your input would be greatly appreciated. I keep running into this use case, and thinking about either adding an additional option or extending existing
```
  --max-nresults MAX_NRESULTS
                        maxmimum number of search results to report. Setting
                        this to 0 will report all search matches. Depending on
                        the mode this can search substantially slower. If not
                        specified, a mode-specific default setting will be
                        used. Constraints: value must be convertible to type
                        'int' [Default: None]
```

to be able to say smth like `--max-nresults parentds=2` which would limit to 2 outputs per each `parentds`

**Comment by yarikoptic** [comment]
a user use case: https://neurostars.org/t/datalad-search-openneuro/18386

**Comment by mih** [comment]
This issues refers to functionality that has been removed in https://github.com/datalad/datalad/pull/7014
