### ISSUE TITLE
get_repo_instance doesn't even go to parent if target class_ is specified

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#294]
and I don't like that it calls _class without guarding with create=False... I know that it might not be known to GitRepo -- but it mustn't even try to create anything there.  Should go upstairs first to detect .git anyways.

Here is the example
```
(git)hopa:/tmp/test-archive-annex[master]svgtune-0.2.0
$> python -c 'from datalad.cmdline.helpers import get_repo_instance;  from datalad.support.annexrepo import AnnexRepo;  print get_repo_instance(class_=AnnexRepo)'
INFO:rdflib:RDFLib Version: 4.2.1                                                                                                                                 
2015-11-09 23:12:54,636 [ERROR  ] /tmp/test-archive-annex/svgtune-0.2.0 (gitrepo.py:260)
ERROR  :datalad.gitrepo:/tmp/test-archive-annex/svgtune-0.2.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/helpers.py", line 202, in get_repo_instance
    (type_, abspath_))
RuntimeError: No annex repository found in /tmp/test-archive-annex/svgtune-0.2.0
(venv-tests)2 12408 ->1.....................................:Mon 09 Nov 2015 11:12:54 PM EST:.
(git)hopa:/tmp/test-archive-annex[master]svgtune-0.2.0
$> git annex info
repository mode: indirect
trusted repositories: 0
semitrusted repositories: 4
	00000000-0000-0000-0000-000000000001 -- web
 	00000000-0000-0000-0000-000000000002 -- bittorrent
 	06dd3743-9932-4823-9017-749d2ff727a8 -- yoh@hopa:/tmp/test-archive-annex [here]
 	81b8e5ba-1d80-46b4-a8c5-c701b55bad8b -- [datalad-archives]
untrusted repositories: 0
transfers in progress: none
available local disk space: 1.05 gigabytes (+1 megabyte reserved)
local annex keys: 5
local annex size: 17.87 kilobytes
annexed files in working tree: 4
size of annexed files in working tree: 12.75 kilobytes
bloom filter size: 32 mebibytes (0% full)
backend usage: 
	SHA256E: 9
```

**Comment by bpoldrack** [comment]
- calling without create=False wasn't intended. Corrected this.

- that helper should go upstairs first and it does for me. I can't reproduce your example. If I create a fresh annex with a subdir, your code works fine for me. In base dir as well as in subdir it creates an AnnexRepo instance pointing to the repo's base dir.

**Comment by bpoldrack** [comment]
You get an InvalidGitRepository by GitPython, because the subdir is passed to the GitPython call (which  doesn't work). When I try it, the repo's basedir is passed. Does your example rely on master?

**Comment by yarikoptic** [comment]
my branch is up to date with master indeed, and I don't carry any differences to that code.  calling class_(dir_) without create=False I guess instantiates a repository in the subdirectory (didn't trace the detail yet) leading not to go upstairs...   actually looking at the logic with fresh eye - it should indeed work (check for .git/ is first), not sure why it didn't now...  but if create=False is due please send a patch ideally with a test that it does behave as it should whenever invoked within a subdirectory.  Use getpwd and chpwd to step into subdir -- should be legit ;)

**Comment by bpoldrack** [comment]
I'm about to. But this led to discovery of another bug ;)

2015-11-12 14:44 GMT+01:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by yarikoptic** [comment]
I think I have misread the logic and #295 has addressed another concern (with create=False), so closing ;) thanks!
