### ISSUE TITLE
Dataset ID and checkout --orphan

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#2948]
Our dataset ID actually is bound to a branch, since it is committed in `.datalad/config`.
In context of PR #2946 this leads to an interesting question. Therein `test_run.py:test_rerun_just_one_commit` fails, because `rerun` complains, that the original run record was ran from a different dataset. This is because the dataset id is in master and the test checks out an orphan branch to operate on. Now `rerun` compares the original dataset id to `None` (no `.datalad/config` in that branch) and fails. There's a little bit more details to that test failures regarding what is reevaluted at what point in time, but that's not the point.

The point is: Such branch would get a different dataset id than 'master' one way or another (including even no id at all unless `create` is also called on that branch). I think that's fine, since the orphan branch actually has no common history with master. But it might have weird side effects. What do you think - do we want it that way, @mih , @yarikoptic , @kyleam ? Otherwise datalad id needs to go into `.git/config` instead, I guess.

**Comment by kyleam** [comment]
> Such branch would get a different dataset id than 'master' one way or another (including even no id at all unless create is also called on that branch). I think that's fine, since the orphan branch actually has no common history with master. 

I think that's fine too.

**Comment by bpoldrack** [comment]
@kyleam : If it is to stay that way, I'd need to adapt that `rerun` test I mentioned above. It states, that it does checkout out that orphan branch to test the "one commit in a repo" case. Now, there'd be two options:
1. Call `create` before in order to have a dataset id. That seems to make the test case pointless, since there'd be a commit before the run record.
2. `run` would need to be able to record `None` as the dataset id. But what would be the correct behavior of `rerun` in that case?

**Comment by bpoldrack** [comment]
I think `None` would be ok and as long as `rerun` only compares (None == None) everything is fine. But I wonder whether this would have unwanted implications later on, when there is a dataset id.

**Comment by kyleam** [comment]
> If a later commit adds the dataset ID, a rerun won't compare None to None. It will just run it:

So I think the above check should just be updated to also "just run" when `dset.id is None`, probably logging a warning as well.  There shouldn't be a need to store `None`.

**Comment by bpoldrack** [comment]
Yes, I think I just need to fix `GitRepo.checkout` to reload `config` and be done. This should result in the correct dataset id (None) when `run` is called and that's it. The test should then still run on an empty branch with no need to further changes. Thanks!

**Comment by kyleam** [comment]
> Yes, I think I just need to fix GitRepo.checkout to reload config and be done

Makes sense.  Thanks.

**Comment by bpoldrack** [comment]
> Makes sense. Thanks.

FTR:
But sadly it's insufficient. This is because it's not necessarily the checkout that might change `.datalad/config`, but `git reset` (as is case with this test). For now I'll do the additional reload just within the test and make the question on when to reload config in that context a separate issue.

**Comment by bpoldrack** [comment]
Apparently the mentioned fix failed to link the issue. Closing.
