### ISSUE TITLE
frontend (Python vs cmdline) specific arguments

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#296]
Do we have already ability to provide arguments to the `__call__` of interfaces which would be frontend specific?  

E.g. in Python API I might like to be able to pass existing instance of the repository instead of requiring establishing a new AnnexRepo

**Comment by yarikoptic** [comment]
related to this -- we have quickly added cmdline argument for Interface in  a8472b31249de0705273a702f8177cf5c4fa8082 to be able to tell which interface to be invoked

**Comment by hanke** [comment]
The `cmdline` argument was removed again (switch from class instances required it). Otherwise the original use case has been implemented via optional arguments.

Closing for now...
