### ISSUE TITLE
realpath'ing Repo path -vs- ok_file_under_git

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2961]
Originally ran into within https://github.com/datalad/datalad/pull/2898 ([failed travis run](https://travis-ci.org/datalad/datalad/jobs/442291459)), not sure how it didn't float up before (at least for me):  
in [GitRepo._flyweight_id_from_args](https://github.com/datalad/datalad/blob/master/datalad/support/gitrepo.py#L576) we realpath'ing every path so any repository's path is the realpath (although we do have `.realpath` for that purpose).  But in other spots (like `ok_file_under_git`) we seems to not do that at causes incorrect assessment.  Here are examples in both DataLad proper and the -revolution one:

```shell
$> python -c 'from datalad.support.gitrepo import GitRepo; p="/var/tmp/sym link/datalad_temp_tree_wrappedVlKRSJ/ds-clone"; print(GitRepo(p)); from datalad.tests.utils import ok_file_under_git; ok_file_under_git(p + "/in-annex", annexed=True)' 
<GitRepo path=/tmp/datalad_temp_tree_wrappedVlKRSJ/ds-clone (<class 'datalad.support.gitrepo.GitRepo'>)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 226, in ok_file_under_git
    assert_in(file_repo_path, repo.get_indexed_files())  # file is known to Git
  File "/usr/lib/python2.7/unittest/case.py", line 804, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: '../../../var/tmp/sym link/datalad_temp_tree_wrappedVlKRSJ/ds-clone/in-annex' not found in [u'.gitattributes', u'.datalad/.gitattributes', u'in-annex', u'.datalad/config', u'in-git']
(dev) 1 14949 ->1.....................................:Mon 29 Oct 2018 08:35:53 PM EDT:.
(git)hopa:~datalad/datalad-revolution[master]git
$> python -c 'from datalad_revolution.gitrepo import RevolutionGitRepo as GitRepo; p="/var/tmp/sym link/datalad_temp_tree_wrappedVlKRSJ/ds-clone"; print(GitRepo(p)); from datalad.tests.utils import ok_file_under_git; ok_file_under_git(p + "/in-annex", annexed=True)'             
<GitRepo path=/tmp/datalad_temp_tree_wrappedVlKRSJ/ds-clone (<class 'datalad_revolution.gitrepo.RevolutionGitRepo'>)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 226, in ok_file_under_git
    assert_in(file_repo_path, repo.get_indexed_files())  # file is known to Git
  File "/usr/lib/python2.7/unittest/case.py", line 804, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: '../../../var/tmp/sym link/datalad_temp_tree_wrappedVlKRSJ/ds-clone/in-annex' not found in [u'.gitattributes', u'.datalad/.gitattributes', u'in-annex', u'.datalad/config', u'in-git']
```

Quick solution of ok_file_under_git adjustment would be ok, but I am not sure if that would be the "correct" one...

**Comment by mih** [comment]
In -revolution I do not use these helpers -- for the reason above, but also because they only query one property at a time, while pretty much all relevant properties together can be determined from a single `Repo.(annex)status()` call. Going through the top-level `rev-status` command should take care of all symlink issues (that come from this possibility of dataset and repo being in two different aparent paths -- at least those that I am aware of.

**Comment by bpoldrack** [comment]
> Quick solution of ok_file_under_git adjustment would be ok, but I am not sure if that would be the "correct" one...

If `ok_clean_git` isn't aware of `*Repo.path` being realpath, then yes - that's a correct solution, IMO.
However, another "solution" is to just stop calling `ok_clean_git` with a path and pass the `*Repo` instead. We do that all the time and it's actually unnecessary (and costs to figure out what it is).

**Comment by bpoldrack** [comment]
> (although we do have .realpath for that purpose)

We do have `.realpath` and we should remove it, I think. But: It's not "for that purpose". It's important part of the idea, that `.path` is used that way by flyweight not that there's `realpath` somewhere.
