### ISSUE TITLE
setting metadata

### ISSUE THREAD

**Issue by notestaff** [datalad/datalad#2965]
There's no simple command to assign a key-value pair to a dataset, a directory, or a file?

**Comment by yarikoptic** [comment]
No, since there is no generic way to assign them according to all available metadata extractors we have. You can use git annex metadata to assign at that level. We aggregate it later on

**Comment by mih** [comment]
I am closing this issue. There are no plans to approach this in -core. Such functionality is likely something for an extension, choosing a particular format and approach.
