### ISSUE TITLE
Make uninstall uninstall top-level datasets

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2967]
I think we had that discussion at some point but I do not think we have an explicit issue.  I think that API should become a bit more "symmetric".  We already can `drop` what we `get`, `remove` what we `add`, and IMHO we should be able to `uninstall` what we `install`.  But that is not the case ATM with top level datasets:

```shell
$> datalad install https://github.com/OpenNeuroDatasets/ds001499
[INFO   ] Cloning https://github.com/OpenNeuroDatasets/ds001499 [1 other candidates] into '/mnt/btrfs/scrap/tmp/openneuro/ds001499' 
install(ok): /mnt/btrfs/scrap/tmp/openneuro/ds001499 (dataset)

$> datalad uninstall ds001499 
uninstall(error): /mnt/btrfs/scrap/tmp/openneuro/ds001499 (dataset) [will not uninstall top-level dataset (consider `remove` command)]
```
and I cannot recall the original motivation for having it so (IIRC it was very much intentional).

**Comment by mih** [comment]
The reason was to reflect the impact of the action. When one uninstall a top-level dataset it is actually gone, and cannot be brought back from what is left after the operation. The is different for any of the other "undo" examples that you gave above.

**Comment by yarikoptic** [comment]
Well, I can bring back any dataset which I installed from somewhere else no problem (like in the above example). And I could have a subdataset which was locally created with content still available somewhere (eg s3) which if I uninstall I loose. Altogether I am not sure if availability of the installation url within git should be the factor deciding between uninstall and remove. I could even argue that removing something which is not a part of a dataset is inconsistent with above pairing of commands.

Git annex verifies presence of files to be dropped on remotes, I wonder if we just should verify availability of the datasets on the remotes they have and if no remotes have it, then refuse to uninstall it, as a factor to decide when to refuse to uninstall (unless --force)

I could have
