### ISSUE TITLE
Account for annex.version 7

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#2969]
We need to make the codebase v7-aware.  At the very least, this means going through places where we say `config.get("annex.version") == "6"` and rethinking the naming of things like `skip_v6`.

https://git-annex.branchable.com/news/version_7.20181031/
https://git-annex.branchable.com/devblog/day_551__v6_or_v7/

**Comment by yarikoptic** [comment]
Wow, I didn't expect it to happen that soon. I will build/upload fresh annex when on stable internets again to see what breaks ;-)

**Comment by yarikoptic** [comment]
FWIW https://github.com/datalad/datalad/pull/2915#issuecomment-435467641 now should be running with a fresh git-annex from -devel of neurodebian

**Comment by bpoldrack** [comment]
I think we need to do more. ATM we happily accept `datalad.repo.version = 6`, while silently creating a v7 repository. This is misleading. Similar to `supports_unlocked_pointers` (introduced by PR #2975) we should probably have `supported_repo_versions` and get a list from git-annex. With current version this would yield `5, 7` (no `6`!). If `datalad.repo.version` is requesting an unsupported version, we should fail or at least issue a warning.
Subsequently we should also change the Travis builds, so they don't suggest to test sth, they actually do not test.

**Comment by yarikoptic** [comment]
Well... I don't think we need to fail, I am not sure even if warning is the level to report at, butt may be indeed info message that it was automagically upgraded to 7 could be issued

**Comment by kyleam** [comment]
@yarikoptic:
> I don't think we need to fail, I am not sure even if warning is the level to report at, butt may be indeed info message that it was automagically upgraded to 7 could be issued

An info message seems appropriate to me too.  A warning seems a bit much since v7 will behave like v6 as far as most users are concerned: I can't see many users thinking "man, I really want v6's post-merge/post-checkout hooks".

@bpoldrack:
> Subsequently we should also change the Travis builds, so they don't suggest to test sth, they actually do not test.

Agree, but that'd need to wait for a bump in the minimum git-annex requirement, right?

**Comment by bpoldrack** [comment]
Yeah, INFO level probably is fine. Just be silent about it is not.

> Agree, but that'd need to wait for a bump in the minimum git-annex requirement, right?

Right. Good point.

**Comment by kyleam** [comment]
With gh-3045 and the just-opened gh-4000, the remaining to-dos from the meta-issue have dedicated issues.
