### ISSUE TITLE
test_datasets_datalad_org fails on appveyor

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2976]
#### What is the problem?

Since https://github.com/datalad/datalad/pull/2941 which introduced this test we got the failure, although it did pass then (https://ci.appveyor.com/project/mih/datalad/builds/19892298).  Seems to be related to introduction of v7 (started to fail [here](https://ci.appveyor.com/project/mih/datalad/builds/19963437/job/gpudc71cnjh44yye) with annex 7. and preceding green [run](https://ci.appveyor.com/project/mih/datalad/builds/19920699/job/87fwsw40qs2v0gkm) had 6) but https://github.com/datalad/datalad/pull/2975 unfortunately still exhibits it in its current shape

<details>
<summary>extract from appveyor</summary>

```
======================================================================
FAIL: datalad.distribution.tests.test_install.test_datasets_datalad_org('',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 818, in newfunc
    return func(*args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 592, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_install.py", line 931, in check_datasets_datalad_org
    status='ok')
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1208, in assert_result_count
    dumps(results, indent=1, default=lambda x: str(x))))
AssertionError: Got 0 instead of 1 expected results matching {'status': 'ok'}. Inspected 1 record(s):
[
 {
  "status": "notneeded",
  "type": "file",
  "path": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_4udmjxa7\\001-anat-scout_ses-{date}\\000001.dcm",
  "action": "get",
  "refds": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_4udmjxa7",
  "message": "already present"
 }
]
======================================================================
FAIL: datalad.distribution.tests.test_install.test_datasets_datalad_org('/.git',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 818, in newfunc
    return func(*args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 592, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_install.py", line 931, in check_datasets_datalad_org
    status='ok')
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1208, in assert_result_count
    dumps(results, indent=1, default=lambda x: str(x))))
AssertionError: Got 0 instead of 1 expected results matching {'status': 'ok'}. Inspected 1 record(s):
[
 {
  "status": "notneeded",
  "type": "file",
  "path": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_lqhcp78s\\001-anat-scout_ses-{date}\\000001.dcm",
  "action": "get",
  "refds": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_lqhcp78s",
  "message": "already present"
 }
]

```
</details>

**Comment by bpoldrack** [comment]
> Seems to be related to introduction of v7 

Interesting. I didn't notice that connection. I want to also point out, that this is concerning one of the appveyor builds as far as I'm aware. And this is default (prob. still direct mode), while explicit v6 build passes.

**Comment by yarikoptic** [comment]
good catch!  forgot to look at what is the difference between the two runs! ;-)

**Comment by yarikoptic** [comment]
note that current annex [there](https://ci.appveyor.com/project/mih/datalad/builds/20683751/job/vcbxx9lflac6j07n) is cmd:annex=7.20181106-g6ba6c6b53   so I believe that by default it should be a v7 repository, not direct mode on windows.

Is anyone (@mih ?) working on a Windows machine/VM to check if situation is replicable outside of the appveyor?

**Comment by yarikoptic** [comment]
confirming that the issue seems to be addressed by the super-fresh git-annex
```shell
$> sudo dpkg -i /tmp/git-annex-standalone_7.20181121+git58-gbc4aa3f0e-1\~ndall+1_amd64.deb 
...
$> tools/eval_under_testloopfs venvs/dev/bin/python -m nose -s -v datalad/distribution/tests/test_install.py:test_datasets_datalad_org
I: vfat of 10:  /home/yoh/.tmp/datalad-fs-dYXUO
10+0 records in
10+0 records out
10321920 bytes (10 MB, 9.8 MiB) copied, 0.00378638 s, 2.7 GB/s
mkfs.fat 4.1 (2017-01-24)
I: running venvs/dev/bin/python -m nose -s -v datalad/distribution/tests/test_install.py:test_datasets_datalad_org
datalad.distribution.tests.test_install.test_datasets_datalad_org('',) ... ok
datalad.distribution.tests.test_install.test_datasets_datalad_org('/.git',) ... ok
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=7.20181121+git58-gbc4aa3f0e-1~ndall+1 cmd:git=2.19.2 cmd:system-git=2.19.1 cmd:system-ssh=7.6p1 exifread=2.1.2 git=git gitdb=2.0.3 humanize=0.5.1 iso8601=0.1.11 keyring=16.0.0 keyrings.alt=3.1 msgpack=0.5.6 mutagen=1.40.0 requests=2.18.4 scrapy=1.5.0 six=1.11.0 tqdm=4.19.5 wrapt=1.9.0
Obscure filename: str= ;abcΔЙקم๗あ repr=u' ;abc\u0394\u0419\u05e7\u0645\u0e57\u3042'
Encodings: default='ascii' filesystem='UTF-8' locale.prefered='UTF-8'
Environment: GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git' LANG='en_US.utf8' GIT_PAGER='less --no-init --quit-if-one-screen' PATH='/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/sbin:/usr/sbin:/usr/local/sbin'

----------------------------------------------------------------------
Ran 2 tests in 27.407s

OK
I: done, unmounting
tools/eval_under_testloopfs venvs/dev/bin/python -m nose -s -v   15.17s user 8.12s system 80% cpu 28.842 total
```

**Comment by yarikoptic** [comment]
And I wonder if we should monitor/catch for such behavior (adjusted branch but v5 - git annex upgrade) or "nah"?

**Comment by kyleam** [comment]
> And I wonder if we should monitor/catch for such behavior (adjusted branch but v5 - git annex upgrade) or "nah"?

I don't think it's worth explicitly checking for.

**Comment by yarikoptic** [comment]
> > And I wonder if we should monitor/catch for such behavior (adjusted branch but v5 - git annex upgrade) or "nah"?
> 
> I don't think it's worth explicitly checking for.

Then we would just need to wait for a new release / build for windows for appveyor to become happy again ;-)

**Comment by kyleam** [comment]
> Then we would just need to wait for a new release / build for windows for appveyor to become happy again ;-)

We could also just remove that appveyor run and once the new build comes out temporarily revert it to confirm the fix.

**Comment by yarikoptic** [comment]
Indeed
I will just disable that single unit test for that run for the case of older annex, so nothing would need to be changed later

**Comment by kyleam** [comment]
> I will just disable that single unit test for that run for the case of older annex, so nothing would need to be changed later

OK, though aside from that test, I think there is no reason to keep that entire appveyor run around.

**Comment by yarikoptic** [comment]
well, it has already shown that without explicit `git annex upgrade` there might still be be gotchas awaiting, happen we enable more tests on appveyor.  So I would have kept it at least for a bit longer - those runs are relatively quick
