### ISSUE TITLE
#!datalad

### ISSUE THREAD

**Issue by theovanerp** [datalad/datalad#2979]
Would it be possible to turn datalad into "a new unix shell" in a way that people could execute their usual shell commands and/or scripts with the shebang #!/bin/datalad such that the shell would then interpret the commands, convert them to proper datalad syntax generating provenance but removing the overhead of learning datalad/git syntax?

**Comment by yarikoptic** [comment]
Thanks @theovanerp for chiming in.
Note that if you already have a script you could just `datalad run` it and thus record its effect within git history.  Indeed to gain the most of benefit from using `run` you would need to specify `--input` and `--output` arguments.
But if we "marry" datalad to reprozip (kudos to @remram44 and the team) with ability to trace/deduce input/outputs, and then even possibly if we hook into pre-call state of syscalls to call `datalad get` needed annexed files, then it could get quite cool. But even then I am not quite certain if it would warrant `datalad` in a shebang as opposed to just calling smth like `datalad run --with-trace script`, which would have benefit to work on any script, not just a shell script.
I guess all of this also is very related to the https://github.com/datalad/datalad/issues/2063, in particular to suggested there `--record-runs` option (i even forgot that I did suggest that ;-) -- thanks github Search).

**Comment by yarikoptic** [comment]
overall, since the script could just remain a `shell` script and run datalad commands, I am not yet sure what benefit from using datalad as interpreter would provide.  I will close but if the idea is still "hot", feel welcome to chime back in!
