### ISSUE TITLE
creating super datasets from inside out

### ISSUE THREAD

**Issue by satra** [datalad/datalad#2981]
#### What is the problem?
No problem, but looking for a how to.

say you have a folder structure
```
L1 -> L2a-> L3
L1 -> L2b
L1 -> L2c
```

I would like to programmatically recurse into each `L2*` directory and create a datalad dataset there. Then jump back out to L1 and create a dataset that adds each of the sub datasets as submodules.

After this I would like to use the new git-annex data caching feature to link the files in the sub-datasets to locations on the Web.

is there a way to carry this workflow out.

more generally is there a datalad way of doing this for any arbitrary inside configuration of datasets? I place datalad datasets at any place in a tree. then at the top level i want to create a super dataset that adds any datalad dataset inside as submodule, but adds any non-annexed/non-git files to the super dataset. essentially an overlay of data.

e.g. say i want to add nidm files to each repo, but i don't want them added to openneuro dataset, but create a reprobids dataset that adds these on.

**Comment by mih** [comment]
Oi, this has never received a reply. I assume it is no longer relevant. Feel free to reopen @satra
