### ISSUE TITLE
Failed `datalad.api.run()` should log Python invocation (not cmdline)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2986]
```shell
$> python -c 'from datalad.api import run; run("touch 1234; exit 1");'
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) ===== 
[INFO   ] The command had a non-zero exit code. If this is expected, you can save the changes with 'datalad save -r -F .git/COMMIT_EDITMSG .' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 479, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 467, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 491, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/run.py", line 220, in __call__
    sidecar=sidecar):
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/run.py", line 639, in run_command
    raise exc
datalad.support.exceptions.CommandError: CommandError: command 'touch 1234; exit 1' failed with exitcode 1
```
and ideally we should have 
```
[INFO   ] The command had a non-zero exit code. If this is expected, you can save the changes with 'save(path='.', recursive=True, message_file=".git/COMMIT_EDITMSG")' 
```

**Comment by bpoldrack** [comment]
I'm not sure what you mean by this:

> should log Python invocation (not cmdline)

However, I agree to this:

> and ideally we should have 
```
[INFO   ] The command had a non-zero exit code. If this is expected, you can save the changes with 'save(path='.', recursive=True, message_file=".git/COMMIT_EDITMSG")'
```

**Comment by yarikoptic** [comment]
> I'm not sure what you mean by this:
> 
> > should log Python invocation (not cmdline)

that it logs what next command to run in cmdline, and should log how to do it in Python

**Comment by bpoldrack** [comment]
Ah, I see. Right!

**Comment by kyleam** [comment]
Is there currently a way to know the a command is running through the Python API?

**Comment by yarikoptic** [comment]
If there is one, @mih would be the one to know.  If we don't have one yet, we should define some `datalad.__api__ = "python"` which gets redefined by cmdline's main.

**Comment by bpoldrack** [comment]
> If we don't have one yet, we should define some datalad.__api__ = "python" which gets redefined by cmdline's main.

I'm pretty sure, we don't have such a construct, but I think that would be a reasonable way to do it.
Although we should spend a minute to think through, what that would mean for syscalls calling datalad again. Think of datalad special remotes as well as using `run` or `run-procedure` with another datalad call.

**Comment by bpoldrack** [comment]
I guess the issue with that is, that it isn't even obvious to me, what we want such processes to "think" of themselves. Should they consider themselves to be something that was called via python API because the parent process was or are they supposed to identify as a command being called via cmdline interface?

**Comment by kyleam** [comment]
> I guess the issue with that is, that it isn't even obvious to me, what we want such processes to "think" of themselves. 

Not obvious to me either.  The answer could probably go either way depending on who's inspecting, but...

> Should they consider themselves to be something that was called via python API because the parent process was or are they supposed to identify as a command being called via cmdline interface?

I lean towards saying the last invocation should win because I'm not sure how we would determine the parent's state, but it seems it would certainly be more complicated (both to implement and to document/explain).  And if we inspect it just to give a more appropriate error message, I think it's acceptable if there are some edge cases.

**Comment by yarikoptic** [comment]
What about -- If you process `sys.argv` arguments or otherwise react to bear a `__name__` == `"__main__"` - you are a cmdline beast ;)   if you are called from cmdline -- e.g. special remotes -- you are a command line beast.  The rest (default) is Python.  Who you nest in is your own problem since we can't know better really.  
Having said that, I remember we (or I) had an idea for a top datalad process to establish its presence to the underlying datalad processes (e.g. datalad custom special remotes which could call annex and in turn yet another datalad special remote etc), so we could channel information on logging and progress.  I thought to do it via top level process establishing some evn variable pointing to a socket for such communications (e.g. `DATALAD_INTERNAL_SOCKET_PATH` or alike).  So in principle we could do the same here to make a decision on `__top_api__` and `__self_api__` but I am not sure if at any current level we would know which one to react to... so what is the point?   we could solve it at least for now here for direct invocation of `run` so we know that it is the `self` to worry about

**Comment by bpoldrack** [comment]
To be clear: I think that the simple `datalad.__api__` is good enough. It's clearly an improvement for a lot of cases. And it's the "last invocation wins" approach. I just wondered whether we can even conceptionalize what we'd ideally want for those processes and if so, whether we can come up with a solution for that. But as long as we are not clear about the first part, it's of no value to me apply a partial "solution" propagating the parent's state under some special circumstances.

So, I guess, keep it simple for now. If we actually build some coordinating process, we can still think about it again. As long as we have something to ask for what the current process is, that something can change whenever we have a better idea.

**Comment by mih** [comment]
Fixing this issue is now trivially possibly by querying the new apimode indicator
