### ISSUE TITLE
RFC: flake8_diff?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2989]
just ran into 
https://github.com/scikit-learn/scikit-learn/blob/master/build_tools/travis/flake8_diff.sh
and thought to ask if we would be interested to make at least new/changed code forcefully flake8 compliant.

**Comment by yarikoptic** [comment]
Michael uses https://github.com/alfredodeza/khuno.vim which seems to use flake8 and has config to ignore

- E402 module level import not at top of file

I guess we would need to ignore 
- E401 multiple imports on one line
- E722 do not use bare except
- F401 '.version.__version__' imported but unused - for our imports to get stuff bound

**Comment by mih** [comment]
2+ years in, we can close this, I guess.
