### ISSUE TITLE
__repr__ for *Repo classes (and others)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#299]
ATM we are very thin on them and that makes them ugly in many realms

**Comment by yarikoptic** [comment]
not as a solution and not to discourage proper `__repr__`s but I introduced `@auto_repr` which could be used as a decorator to classes to automagically create reprs for them: 
https://github.com/yarikoptic/datalad/blob/nf-ui-auth-downloaders/datalad/utils.py#L47

example is in the test:
https://github.com/yarikoptic/datalad/blob/nf-ui-auth-downloaders/datalad/tests/test_utils.py#L220

**Comment by mih** [comment]
Time out after 1.5 years.
