### ISSUE TITLE
academictorrents support

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#30]
Now that annex got built-in support for torrents (http://git-annex.branchable.com/devblog/day_239-240__bittorrent_remote/) we might consider exposing torrents from http://academictorrents.com/browse.php?cat=6   Chris's test-retest  and few other related datasts (http://academictorrents.com/browse.php?search=fmri&c6=1) are available there

**Comment by yarikoptic** [comment]
@kyleam could you please check on how difficult it would be to crawl them all?

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
