### ISSUE TITLE
 Running copy resulted in stderr output:   verification of content failed 

### ISSUE THREAD

**Issue by adelavega** [datalad/datalad#3016]
#### What is the problem?
I'm trying to publish a dataset to a common data source (corral on TACC), and publish to github. I'm *almost* there, but it looks like verification fails at the end, so the file structure is not created on the remote, or or github.

#### What steps will reproduce the problem?
````
datalad add .
datalad create-sibling -s mddatasrc delavega@ls5.tacc.utexas.edu:/corral-repl/utexas/neuroscout

/neuroscout-datasets/SherlockMerlin --as-common-datasrc tacccorral --target-url https://web.corral.tacc.utexas.edu/neuroscout-datasets/SherlockMerlin/.git --ui true
[INFO   ] Considering to create a target dataset /home/alejandro/datasets/neuroscout-datasets/SherlockMerlin at /corral-repl/utexas/neuroscout/neuroscout-datasets/SherlockMerlin of ls5.tacc.utexas.edu 
[INFO   ] Fetching updates for <Dataset path=/home/alejandro/datasets/neuroscout-datasets/SherlockMerlin> 
TACC Token Code:
TACC Token Code:
.: mddatasrc(+) [https://web.corral.tacc.utexas.edu/neuroscout-datasets/SherlockMerlin/.git (git)]
[INFO   ] Adjusting remote git configuration 
[INFO   ] Enabling git post-update hook ... 
[INFO   ] Uploading web interface to /corral-repl/utexas/neuroscout/neuroscout-datasets/SherlockMerlin 
[INFO   ] Running post-update hooks in all created siblings 
create_sibling(ok): . (dataset)

datalad create-sibling-github --github-organization neuroscout-datasets --github-login adelavega --github-passwd MYPASS --publish-depends mddatasrc --access-protocol ssh SherlockMerlin

[INFO   ] Configure additional publication dependency on "mddatasrc" 
.: github(-) [git@github.com:neuroscout-datasets/SherlockMerlin.git (git)]
'git@github.com:neuroscout-datasets/SherlockMerlin.git' configured as sibling 'github' for <Dataset path=/home/alejandro/datasets/neuroscout-datasets/SherlockMerlin>

datalad publish --to github --transfer-data all


[INFO   ] Transferring data to configured publication dependency: 'mddatasrc' 
[INFO   ] Publishing <Dataset path=/home/alejandro/datasets/neuroscout-datasets/SherlockMerlin> data to mddatasrc 
Total (541 ok, 3 failed out of 544): 100%|█████████████████▉| 18.2G/18.2G [03:56<00:00, 117MB/s]2, 42.5B/s[WARNING] Running copy resulted in stderr output:   verification of content failed  verification of content failed  This could have failed because --fast is enabled.

````

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.11.1

Any clues here? FWIW I have to enter a 2FA password for most ssh operations. Not sure if that would mess anything up. Datalad is installed on the remote client through anaconda.

**Comment by adelavega** [comment]
To add more detail: The remote server's UI is blank: `https://web.corral.tacc.utexas.edu/neuroscout-datasets/SherlockMerlin` as is the github repo. But file were definitely transfeed, as the `.git` folder has many objects totaling 17 GB.

**Comment by yarikoptic** [comment]
hm... `verification of content failed `  
could you please first run `git annex fsck` on your local repository to verify that no annexed file got screwed up (e.g. forcefully modified/replaced/etc)

**Comment by yarikoptic** [comment]
`git-annex -> mddatasrc/git-annex [rejected] (non-fast-forward)`

should have not happened since we should have annex merged remote `git-annex` branch first...  do first `datalad update -s mdatasrc` (so `git annex merge happens`) and then try `publish` again
