### ISSUE TITLE
support for git-annex v6 repos?

### ISSUE THREAD

**Issue by notestaff** [datalad/datalad#3018]
You still support v6 git-annex repos, right?  Do you plan to continue supporting them?

**Comment by kyleam** [comment]
> You still support v6 git-annex repos, right?

Yes, the minimum git-annex version is still earlier than 7.20181031, which introduced v7.

https://github.com/datalad/datalad/blob/e1eaf413864f392733a9722afe29f830371d7942/datalad/support/annexrepo.py#L120

> Do you plan to continue supporting them?

@yarikoptic's comment [here]:  "I don't think we have bandwidth to support also previous versions of annex, so we should just boost minimal version for annex." 

[here]: https://github.com/datalad/datalad/pull/2975#issuecomment-435715315

**Comment by yarikoptic** [comment]
Yeah, probably in 0.12 we should boost minimal annex version with the revolution or not and possibly price some craft

**Comment by yarikoptic** [comment]
I think the question was answered, this closing

**Comment by notestaff** [comment]
@yarikoptic given that bugs involving v7 git-annex repos still regularly crop up, maybe you could postopne dropping support for v5 repos? (My original question was meant to be about v5 not v6).  Not 'direct mode' v5 repos, just usual ones.

**Comment by mih** [comment]
I dont see ourselves dropping support for those any time soon.

**Comment by yarikoptic** [comment]
I can only confirm that as long as git-annex supports v5 (indirect mode), we would support it, so no worries! ;)
