### ISSUE TITLE
`run` broken on windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3030]
`run` is currently broken on windows. That doesn't really surprise anyone, but I think it is worth making it run.

So here is the (growing) list of things that don't work:

- [ ] crashes due to bytes-representation of message. See here for a demo https://ci.appveyor.com/project/mih/datalad-revolution/builds/20644761
    there is an explicit `assure_bytes()` call in the code that is the culprit here. Not sure what the reason is/was.
- [ ] test_run_failure uses sh cmd:  `echo x$(cat grows) > grows && false`  it looks as if a simple failing command would do too, but for some reason the aspect of repeated invocation is tested(?) Is that needed?

**Comment by kyleam** [comment]
>  `echo x$(cat grows) > grows && false`  it looks as if a simple failing command would do too, but for some reason the aspect of repeated invocation is tested(?) Is that needed?

It could be something else, provided that it produces an output file so that there's something to be saved and reran.

**Comment by mih** [comment]
@kyleam Is this still an issue? Should not, right?

**Comment by kyleam** [comment]
The two specific issues mentioned should be resolved and, as of gh-3251, tested.  I'm sure there are still Windows-compatibility issues for `run` (there definitely are for `rerun`), but with gh-3251 -core should match -revolution's compatibility.
