### ISSUE TITLE
search-handle should output for remote handles collection/name not the url

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#304]
from #303 
```
$> datalad search-handle a                      
demo_handle1	ssh://datalad.org/srv/collections.datalad.org/www/demo_collection/demo_handle1
demo_handle1	ssh://datalad.org/srv/collections.datalad.org/www/demo_collection/demo_handle1
```
which imho should have been
```
demo-remote/demo_handle1
demo-remote/demo_handle2
```
since then I could do just cut/paste to execute concise `datalad install-handle demo-remote/demo_handle1`

**Comment by hanke** [comment]
This corresponds to obsolete code.Closing.

Would make sense to bring this one up again in the context, of what kind of implicit meta data to generate for each repository, which could then be "found" via generic query commands.
