### ISSUE TITLE
Travis builds started to fail due to getting stuck on test_annexrepo.test_annex_ssh

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3041]
noted in #3036 that after recent rebase many runs in travis get stuck! (restarted this morning, but that didn't help)
```
datalad.support.tests.test_annexrepo.test_annex_ssh ... 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```
seems to be the case in master as well now  https://travis-ci.org/datalad/datalad/builds/462355716
The last [successful travis build](https://travis-ci.org/datalad/datalad/builds/462355149) seems was for bdfe50832ca68e2a63be7542bba9910e29c75558 after merging #3039 . After that #3038, #3035, #3027  were merged in rapid succession.  Not yet clear if it us or something else which changed

Any ideas?

**Comment by kyleam** [comment]
> After that #3038, #3035, #3027 were merged in rapid succession. Not yet clear if it us or something else which changed
> 
> Any ideas?

Oy, looks like #3027 is the culprint since its runs show the same error: https://travis-ci.org/datalad/datalad/jobs/461508043

**Comment by kyleam** [comment]
I still don't know what's going on, but I'd guess it involves this bit of `test_annex_ssh`:

https://github.com/datalad/datalad/blob/4d7a99572e8809e89b25bb57affe67dea956d508/datalad/support/tests/test_annexrepo.py#L1196-L1218

**Comment by kyleam** [comment]
> crap... I could have sworn that I've looked at the travis results before merging it, but I guess I didn't. Sorry about that.

No worries.  I should have noticed to.

> I would blame the visual fatigue from having appveyor constantly red and us considering "it is ok".

Indeed.  Wish I had any clue what the source of that appveyor failure is.

**Comment by kyleam** [comment]
> Appveyor
> It seems to be that annex doesn't find switch to v7 there [#3047 (comment)](https://github.com/datalad/datalad/pull/3047#issuecomment-443559675)

Right, didn't see that until after I responded.  Even better than a clue :]
