### ISSUE TITLE
both list-collections and search-handle are way way way too slow if any reasonably sized collection is added

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#305]
You can use https://github.com/datalad/datalad/blob/master/docs/examples/make_large_bogus_collection.sh now to generate arbitrarily sized collection with a bunch of bogus handles.  I did with a 100.  Now 

```
$> datalad list-collections | ts                                                                               
Nov 19 23:13:03 bogus-100_collection
Nov 19 23:13:03 bogus-1_collection
datalad list-collections  32.72s user 43.72s system 59% cpu 2:08.02 total
ts  0.03s user 0.00s system 0% cpu 2:08.02 total
```
so it took 30 seconds just to list those collections -- the operation which should be nearly instantaneous.  I am really not sure what it was doing since this operation AFAIK should just check few files and list of remotes.

```
$> datalad search-handle a | ts 
Nov 19 23:18:39 bogus64-100 	/home/yoh/proj/datalad/datalad-master/docs/examples/bogus64-100
Nov 19 23:18:39 bogus64-100 	/home/yoh/proj/datalad/datalad-master/docs/examples/bogus64-100
Nov 19 23:18:39 bogus98-100 	/home/yoh/proj/datalad/datalad-master/docs/examples/bogus98-100
Nov 19 23:18:39 bogus98-100 	/home/yoh/proj/datalad/datalad-master/docs/examples/bogus98-100
Nov 19 23:18:39 bogus98-100 	/home/yoh/proj/datalad/datalad-master/docs/examples/bogus98-100
...
Nov 19 23:23:38 bogus8-100  	/home/yoh/proj/datalad/datalad-master/docs/examples/bogus8-100
datalad search-handle a  141.77s user 251.29s system 73% cpu 8:54.40 total
ts  0.03s user 0.00s system 0% cpu 8:54.40 total
```
i.e. took over 4 minutes.  I will not even attempt to simulate a more realistic scenario with about 10 collections of 100-1000 handles each  ATM ;)

**Comment by yarikoptic** [comment]
ok, list-collections seems to list them relatively fast but then for some reason doing smth with current directory through git (I am under datalad git repository after all):

```
$> datalad  list-collections 
bogus-100_collection
bogus-1_collection
pymvpa
pymvpa-remote
<now it is stuck doing smth>
```
if ran with high debug output I see a lot of 

```
| 100644 blob 2f7cace981a3f84341bd480ad798f26f8ee7ebb9	bogus98-100/config.ttl
| 100644 blob 07c15758866c296eb8788a4fc9af6caa0a616aae	bogus98-100/datalad.ttl
| 100644 blob 8c06864da231c478ca7aee05f28639b494dcbffb	bogus99-100/config.ttl
| 100644 blob b92512b91b2079ded89861dc5535fea250b15424	bogus99-100/datalad.ttl
| 100644 blob 08131f732e112f29ad5fe011b2c705e368ab2d7e	config.ttl
| 100644 blob 5190464a33de7e39deb6c0d321bebe36ac4deb94	datalad.ttl
| 100644 blob 0f18ca310640f18fb0d12671345015f860d9a1a5	mnist/config.ttl
| 100644 blob 8a57de7cd31c8e4c939137bbaa4b3a37885d9665	mnist/datalad.ttl (cmd.py:323)
2015-11-24 09:21:14,154 [Level 8] Finished running ['git', 'ls-tree', '-r', 'master'] with status 0 (cmd.py:323)
2015-11-24 09:21:14,155 [DEBUG  ] Running: ['git', 'ls-tree', '-r', 'master'] (cmd.py:323)
```

**Comment by bpoldrack** [comment]
First of all, I don't see anything happen with current directory here. Where did you see this?

Secondly, the slowness comes from creating the Collection instances (and therefore all the handle instances) to build the return value for the API function, which is actually not required when running from command line.

Third, fixed it in that sense, that most of the time was spend due to a "laziness bug" in Handles. Furthermore, there is another bottleneck (partly removed), which was calling git instead of using the already in memory object tree of GitPython.

But still it's unnecessary to build the return value at all. I think this will be addressed anyway, since we already talked about distinguishing API calls from command line and from other python code. Agree?

**Comment by yarikoptic** [comment]
1. 
> First of all, I don't see anything happen with current directory here. Where did you see this?

do you mean where in the code?  I thought you have remembered the point ;) ok - let me find... I left a comment there for you
```
$> git grep 'TODO: replace with a check for a present directory instead of'
datalad/support/collectionrepo.py:        # TODO: replace with a check for a present directory instead of
```
2. Hm,  how long that would take? We still want Python API being usable, right? ;)
3. cool

**Comment by bpoldrack** [comment]
1. Yes - I remember the point. But this is not operating on current directory (which was datalad folder in your case), but on the collection repos directory. You stated in your comment:

> ... but then for some reason doing smth with current directory through git (I am under datalad git repository after all):

I just don't see what observation you were refering to.

**Comment by bpoldrack** [comment]
Improved search-handles, too.
With a bogus-100 and a bogus-1 collection I currently get:

    % time datalad list-collections
    bogus-100_collection
    bogus-1_collection
    2015-12-09 12:50:49,967 [ERROR  ] Time to build return list: 1.43238282204 (list_collections.py:49)
    datalad list-collections  0.98s user 0.74s system 99% cpu 1.729 total

Where the error log is just inserted to figure out the time, that is used to build the return value. 

And for search-handle:
    % time datalad search-handle a
    ...
    datalad search-handle a  4.68s user 1.63s system 99% cpu 6.336 total

**Comment by yarikoptic** [comment]
Cool, it better now. Try with a 1000! ;-)

**Comment by hanke** [comment]
Obsolete now, respective code is gone.
