### ISSUE TITLE
create needs --m| -message option to be used with -d .

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3069]
As any other command which saves and has `--nosave` option already

**Comment by mih** [comment]
Tangentially related side note: IMHO no command should have --nosave, and it would be good to offer --message for all meaningful cases.

**Comment by mih** [comment]
I came to the conclusion that this is not a good idea. For the same reason `install` also needs `--message`. I will open a dedicated issue.

**Comment by mih** [comment]
Superseded by @yarikoptic #3316
