### ISSUE TITLE
run: record --explicit within run record and/or add --explicit to rerun

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3074]
#### What is the problem?
If I `run` a command with `--explicit` there seems to be no way to rerun it.

Cons of relying on `--explicit` in rerun that it would be applied to all reruns.

**Comment by yarikoptic** [comment]
Just ran into the same scenario again -- need to rerun a commit in a dirty tree.  The run record has all needed inputs/outputs listed, none of which is dirty ATM.  I cannot rerun since it has no `--explicit` and just need to recompose command line invocation from the json record... boring, probably will just end up running it manually and saving

**Comment by kyleam** [comment]
I actually regret exposing --explicit on the command line.  It could have just been added to run_command(), given that its only intent was to open up run for internal use.  We're stuck with that decision for now, but I think we should still very much encourage running with a clean repo and am not convinced we should lift the clean repo requirement from rerun.

**Comment by yarikoptic** [comment]
Hm... purity is not always achievable or desired.  I am really not sure why you are regretting having a feature which is useful and is used!

**Comment by yarikoptic** [comment]
FWIW, dirty or not, with current speed of `status` on rich hierarchies (#3311, and "resolved" #3342), `--explicit` is the only way to `run` anything without waiting for minutes for an initial feedback on either "it is all kosher".

**Comment by kyleam** [comment]
> FWIW, dirty or not, with current speed of `status` on rich hierarchies (#3311, and "resolved" #3342), `--explicit` is the only way to `run` anything without waiting for minutes for an initial feedback on either "it is all kosher".

Worth noting, though from my POV that's an issue to deal with in `status` (or some alternative approach) rather than a reason to add --explicit to rerun.

**Comment by yarikoptic** [comment]
I just keep running into it over and over again.  Some times it is "speed", some times it is just a matter of having some unrelated (to `rerun`) uncommitted changes still present.  I would really appreciate this to be supported... I will look into sending a PR later today/tomorrow

**Comment by kyleam** [comment]
Given that nobody else has weighed in and you're footing the bill, as you wish.  I'll move this to the top of the queue and submit a PR.

**Comment by yarikoptic** [comment]
Thank you!
