### ISSUE TITLE
Provide only summary + truncated listing in error and warnings for `get`

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3078]
It just keeps flooding my screen, hiding away previous warnings and errors.
Instead of 

```
[WARNING] could not get some content in /mnt/btrfs/datasets/datalad/crawl/openneuro/ds000241 [u'/mnt/btrfs/datasets/datalad/crawl/openneuro/ds000241/derivatives/mriqc/T1w.csv', u'/mnt/btrfs/datasets/datalad/crawl/openneuro/ds000241/derivatives/mriqc/bold.csv', u'/mnt/btrfs/datasets/datalad/crawl/openneuro/ds000241/derivatives/mriqc/reports/sub-00_task-ak6_run-01_bold.html', u'/mnt/btrfs/datasets/datalad/crawl/openneuro/ds000241/derivatives/mriqc/reports/sub-00_task-ak6_run-03_bold.html', u'/mnt/btrfs/datasets/datalad/crawl/openneuro/ds000241/derivatives/mriqc/reports/sub-00_task-ak6_run-02_bold.html', u'/mnt/btrfs/datasets/datalad/crawl/openneuro/ds000241/derivatives/mriqc/reports/bold_group.html', u'/mnt/btrfs/datasets/da...
```
we should report

```
[WARNING] could not get some content in 1023 files:  /mnt/btrfs/datasets/datalad/crawl/op....
```

and instead of the flood ( I think we might have an issue on that already) of
```
[ERROR  ] from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 	8f89a624-8f2b-4037-808d-116691c9ec85 -- [s3-PUBLIC];  	a4d3451b-6689-400c-84fc-59ae36719dd6 -- root@2964ce471527:/datalad/ds000241; ; (Note that these git remotes have annex-ignore set: origin) [get(/mnt/btrfs/datasets/datalad/crawl/openneuro/ds000241/sub-11/func/sub-11_task-ak6_run-10_bold.nii.gz)] 
[ERROR  ] from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 	8f89a624-8f2b-4037-808d-116691c9ec85 -- [s3-PUBLIC];  	a4d3451b-6689-400c-84fc-59ae36719dd6 -- root@2964ce471527:/datalad/ds000241; ; (Note that these git remotes have annex-ignore set: origin) [get(/mnt/btrfs/datasets/datalad/crawl/openneuro/ds000241/sub-11/func/sub-11_task-ak6_run-09_bold.nii.gz)] 
```
we should come up with a way to summarize and provide a meaningful description that following remotes should be enabled to provide access to X files.  Or just report a single ERROR (per dataset) stating that there may be more, and advise to consule `git annex where` or smth like that

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
