### ISSUE TITLE
update: --fast-forward

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3079]
I need a way to "reliably" fast-forward subdatasets. I could use `update --merge` but that might cause a real merge to happen, which I would like to prevent/avoid.  So it could be interfaced via a dedicated `--fast-forward` (to complement `--merge`) or we could deprecate `--merge` in favor of e.g. `--changes=merge,fast-forward`. Or we could add a config option (would suffice for my purposes I guess) `update.merge.gitopts` (or alike inline with others we might have) which I could give `--ff-only`.

**Comment by kyleam** [comment]
> or we could deprecate `--merge` in favor of e.g. `--changes=merge,fast-forward`

Sounds OK to me, though I'd slightly prefer keeping --merge as a non-deprecated shortcut for --changes=merge.

**Comment by mih** [comment]
Are there still plans to put this into 0.12? If not, please remove the milestone. I am trying to get a clear trajectory towards a release. Thx.
