### ISSUE TITLE
run: an option to unlock inputs?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3081]
In the light of #317, I thought to have all input .gz files first unlocked. For now I just also specified them in outputs for that purpose
```shell
datalad run -m "gunzipping all .gz'ed DICOMS" --input '*/*/*/*.gz' --output '*/*/*/*.gz' gunzip '{inputs}'
```
(not sure if succeeds, still running, and I think it is incorrect to specify outputs incorrectly since those will actually be gone)
but I wonder if it is worthwhile adding an option to run to unlock also input files?  
could also be useful in indirect mode where the tool is too sensitive to the symlinks in the filenames.

**Comment by kyleam** [comment]
> but I wonder if it is worthwhile adding an option to run to unlock also input files?

Given that some tools have issues dealing with symlinked input files, it seems worth considering.  I suppose the main decision is whether it's common enough that adding another option is worth it to avoid a workaround---either the abuse of --outputs you mention or a command like "datalad unlock {inputs} && <regular command>".

This touches a separate issue (related to issues #2276 and #2454) of how `run` should consider deleted files, which don't nicely fit into the concept of an output.  From a technical point of view, though, your currently failing example should succeed with datalad-revolution's rev-save (and quickly testing, it does).  Not worth much, but without rev-save, this particular example could avoid #2454 by using gunzip's --keep.

**Comment by yarikoptic** [comment]
Hm, keep seems to be of no good effect for me:
```
$> gunzip linked.gz 
gzip: skipping: linked.gz is a symbolic link

$> gunzip --keep linked.gz
gzip: skipping: linked.gz is a symbolic link
1 7334 ->1.....................................:Mon 10 Dec 2018 11:15:37 AM EST:.

$> ls
123.gz  linked.gz@

$> gunzip --version       
gunzip (gzip) 1.9
Copyright (C) 2007, 2011-2017 Free Software Foundation, Inc.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <https://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

Written by Paul Eggert.
1 7337.....................................:Mon 10 Dec 2018 11:17:11 AM EST:.
hopa:/tmp/testgz
$> apt-cache policy gzip
gzip:
  Installed: 1.9-2.1
  Candidate: 1.9-2.1
  Version table:
 *** 1.9-2.1 600
        600 http://http.debian.net/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by yarikoptic** [comment]
Just FTR, for `gzip`, a good enough workaround seems to be adding `-f` (`--force`) option. heh heh.
Some other tools from my memory which are very touchy with symlinks and require some other workarounds are AFNI, so I wouldn't be surprised if @afni folks eventually come about with some requests like this.  but otherwise I am ok to have this one closed until we run into a similar need again.

indeed on a quick try rev-run performs better (I do need to list --outputs identical to inputs to have the deletion saved though in --explicit mode)

**Comment by yarikoptic** [comment]
we have unlocked mode atm etc, and earth is even more round, may be later someone would look into this
