### ISSUE TITLE
TMPDIR does not cause `with_tempfile` paths to be relocated

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3083]
So far I was under the impression that setting TMPDIR in a test run will cause all tempdirs to be located under this path. But it seems that is only true for the location of the test repos created for the test battery. 

I am not sure if this is intentional.

```
TMPDIR='/tmp/sym link' python -m nose -s -v datalad_revolution/tests/test_save.py:test_save
(Pdb) tmpdir
'/tmp/datalad_temp_test_saveizuiamfs'
(Pdb) path
'/tmp/sym link/datalad_temp_clone_url_u3iqz75e'
```

with 

```python
@with_testrepos('.*git.*', flavors=['clone'])
@with_tempfile(mkdir=True)
def test_save(path, tmpdir):
    ...
```

**Comment by yarikoptic** [comment]
oh, I don't think it is intentional and actually strange and might as well be a regression (i.e. we used to create with consideration of `TMPDIR`)

**Comment by kyleam** [comment]
Is this the same issue as  #2640?

**Comment by mih** [comment]
Looks like it!

**Comment by yarikoptic** [comment]
might be! also I got a bit mislead because apparently if TMPDIR doesn't exist it gets back to defaults:
```shell
$> TMPDIR=/tmp/buu python3 -c 'from datalad.tests.utils import with_tempfile; with_tempfile(lambda x:print(x))()'
/tmp/buu/datalad_temp_<lambda>bse2skas

$> TMPDIR=/tmp/buunonexist python3 -c 'from datalad.tests.utils import with_tempfile; with_tempfile(lambda x:print(x))()' 
/tmp/datalad_temp_<lambda>mfcprjac
```

**Comment by mih** [comment]
I can confirm that my failure to replicate the last issue in https://github.com/datalad/datalad-revolution/pull/62 is due to the missing change proposed in #2641

**Comment by mih** [comment]
This is no longer an issue.
