### ISSUE TITLE
Progress is printed to stderr even if not attached to a TTY

### ISSUE THREAD

**Issue by driusan** [datalad/datalad#3092]
#### What is the problem?

When not attached to a TTY, datalad still attempts to print a progress bar and other diagnostic information to stderr, which acts as noise when trying to programmatically do something with its output in a script such as in a unix pipeline.

#### What steps will reproduce the problem?

`datalad create 2>&1 | cat > ../x` and open file `x` with a text editor. Note the number of `\r` characters output as well as progress information which is meaningless when not attached to an interactive terminal. (You can replace `datalad create` with your favourite subcommand.)

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

I happened to be using 0.10.1 when I just tried, but given that there's no related issues that GitHub is finding I suspect nothing's been done to change it.

#### Is there anything else that would be useful to know in this context?

I'm just relaying a message from someone I heard complain about this and thought it would be worth noting. The specifics are about the progress bar, but the general complaint can be summarized as "it should be easier to systematically parse the output when invoked in a script."

**Comment by bpoldrack** [comment]
Hm. FTR: I can't reproduce that.

```
$ /tmp % datalad create some
[INFO   ] Creating a new annex repo at /tmp/some 
create(ok): /tmp/some (dataset)
```
```
$ /tmp % datalad create some 2&>1 | cat > x
$ /tmp % cat x
create(ok): /tmp/some (dataset)
$ /tmp % datalad --version
datalad 0.11.1.dev86
```

@yarikoptic Also, a reminder that there's at least `datalad.log.target`, which redirects the logging (into a file for example)
Compare to first one above:
```
$ /tmp % DATALAD_LOG_TARGET=some.log datalad create some
create(ok): /tmp/some (dataset)
$ /tmp % cat some.log
[INFO] Creating a new annex repo at /tmp/some 
```

**Comment by kyleam** [comment]
> Hm. FTR: I can't reproduce that.

Yeah, I haven't had any luck triggering an issue with `create`, but I can get some ugly progress bars when redirecting:

```
datalad download-url https://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz >out 2>&1
```

out's content:
```
[INFO] Downloading 'https://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz' into '/tmp/tmp.XA9qbf4B4c-dlcont' 
^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:   0%|          | 0.00/44.3M [00:00<?, ?B/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:   5%|▍         | 2.10M/44.3M [00:00<00:04, 9.95MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:   7%|▋         | 3.15M/44.3M [00:00<00:04, 8.99MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:   9%|▉         | 4.19M/44.3M [00:00<00:04, 8.24MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  12%|█▏        | 5.24M/44.3M [00:00<00:04, 7.81MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  14%|█▍        | 6.29M/44.3M [00:00<00:05, 6.73MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  17%|█▋        | 7.34M/44.3M [00:01<00:05, 6.42MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  19%|█▉        | 8.39M/44.3M [00:01<00:06, 5.90MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  21%|██▏       | 9.44M/44.3M [00:01<00:06, 5.43MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  24%|██▎       | 10.5M/44.3M [00:01<00:07, 4.38MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  26%|██▌       | 11.5M/44.3M [00:02<00:11, 2.76MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  28%|██▊       | 12.6M/44.3M [00:03<00:15, 2.04MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  31%|███       | 13.6M/44.3M [00:04<00:17, 1.78MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  33%|███▎      | 14.7M/44.3M [00:04<00:17, 1.69MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  36%|███▌      | 15.7M/44.3M [00:05<00:17, 1.67MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  38%|███▊      | 16.8M/44.3M [00:06<00:16, 1.67MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  40%|████      | 17.8M/44.3M [00:07<00:22, 1.18MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  43%|████▎     | 18.9M/44.3M [00:08<00:18, 1.40MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  45%|████▌     | 19.9M/44.3M [00:08<00:16, 1.49MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  47%|████▋     | 21.0M/44.3M [00:09<00:15, 1.49MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  50%|████▉     | 22.0M/44.3M [00:10<00:15, 1.42MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  52%|█████▏    | 23.1M/44.3M [00:10<00:15, 1.40MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  54%|█████▍    | 24.1M/44.3M [00:11<00:14, 1.39MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  57%|█████▋    | 25.2M/44.3M [00:12<00:13, 1.41MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  59%|█████▉    | 26.2M/44.3M [00:13<00:12, 1.45MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  62%|██████▏   | 27.3M/44.3M [00:13<00:11, 1.49MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  64%|██████▍   | 28.3M/44.3M [00:14<00:10, 1.57MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  66%|██████▋   | 29.4M/44.3M [00:14<00:08, 1.67MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  69%|██████▊   | 30.4M/44.3M [00:15<00:07, 1.84MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  71%|███████   | 31.5M/44.3M [00:15<00:06, 2.04MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  73%|███████▎  | 32.5M/44.3M [00:15<00:05, 2.30MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  76%|███████▌  | 33.6M/44.3M [00:16<00:04, 2.46MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  78%|███████▊  | 34.6M/44.3M [00:16<00:03, 2.54MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  81%|████████  | 35.7M/44.3M [00:17<00:03, 2.70MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  83%|████████▎ | 36.7M/44.3M [00:17<00:03, 2.44MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  85%|████████▌ | 37.7M/44.3M [00:18<00:04, 1.60MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  88%|████████▊ | 38.8M/44.3M [00:19<00:04, 1.28MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  90%|█████████ | 39.8M/44.3M [00:21<00:03, 1.19MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  92%|█████████▏| 40.9M/44.3M [00:21<00:02, 1.17MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  95%|█████████▍| 41.9M/44.3M [00:22<00:01, 1.19MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz:  97%|█████████▋| 43.0M/44.3M [00:23<00:00, 1.28MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz: 100%|█████████▉| 44.0M/44.3M [00:24<00:00, 1.41MB/s]^Mhttps://ftp.wayne.edu/gnu/emacs/emacs-26.1.tar.xz: 100%|██████████| 44.3M/44.3M [00:24<00:00, 1.44MB/s]^M                                                                                                       ^Mdownload_url(ok): /tmp/tmp.XA9qbf4B4c-dlcont/emacs-26.1.tar.xz (file)
add(ok): emacs-26.1.tar.xz (file)
save(ok): /tmp/tmp.XA9qbf4B4c-dlcont (dataset)
action summary:
  add (ok: 1)
  download_url (ok: 1)
  save (ok: 1)
```

**Comment by driusan** [comment]
@bpoldrack have you tried opening the file in a text editor?

`cat`ing it will echo the `\r` to the terminal, which will be interpreted as a carriage return, and the next line will overwrite it but it'll happen quickly enough that you can't see it.

**Comment by kyleam** [comment]
> @bpoldrack have you tried opening the file in a text editor?

I did when I tried the `create` snippet and didn't see any control sequences.  Looks like its version dependent.

Contents (not what the terminal displays) on master (07b952c): 

```
# datalad create $(mktemp -d) >out 2>&
[INFO] Creating a new annex repo at /tmp/tmp.Gl4Js4brOs 
create(ok): /tmp/tmp.Gl4Js4brOs (dataset)
```

And on the version you report, v0.10.1:

```
[INFO] Creating a new annex repo at /tmp/tmp.QI4hVZ3hQo 
^MTotal:   0%|          | 0.00/21.0 [00:00<?, ?B/s]^M                                                 ^MTotal:   0%|          | 0.00/250 [00:00<?, ?B/s]^M                                                ^Mcreate(ok): /tmp/tmp.QI4hVZ3hQo (dataset)
```

That bisects to the merge commit 2517f6146 (Merge pull request #2749 from mih/rf-generator, 2018-08-15).  I don't yet understand why the merge doesn't show the progress output while both parents do.

**Comment by kyleam** [comment]
I said

> That bisects to the merge commit 2517f6146 (Merge pull request #2749 from mih/rf-generator, 2018-08-15).  I don't yet understand why the merge doesn't show the progress output while both parents
do.

That bisect looks like nonsense.  I'm having no luck triggering the `create` progress bars now.  On any version I've tried, I don't see progress bars when using `datalad create $(mktemp -d) >out 2>&1`.  Dunno.

Anyway, any command that uses a progress bar from `ConsoleLog.get_progressbar` (like `download-url`, but not `create`) will show progress bars even with no tty attached.

@yarikoptic says:

> I actually thought that we are disabling all the "fancy" UI elements such as progress bars in non-interactive runs... but then realized that probably we didn't since progress bars might be useful even then.

Right, if `is_interactive` returns false, `ui` sets the backend to `ConsoleLog`, not `SilentConsoleLog`, so we'll still see progress bars.

https://github.com/datalad/datalad/blob/52719b0e52628c1db912663fe3aad4ee6f06eb49/datalad/ui/__init__.py#L82

> But may be we should disable

I'd vote for that (i.e. use `SilentConsoleLog` rather than `ConsoleLog` when `is_interactive` returns false).

> or change them to be minimalistic (e.g. progress bar just a growing sequence of .s  or so) indeed so we do not pollute the logs if output is not a tty.

Or we could start using `log_progress` more.  That switches to using log messages to indicate progress when we're non-interactive.

In terms of this issue specifically, I think we can consider it resolved once we use `SilentConsoleLog` when non-interactive or at least make it possible to configure this.  Users should then be able to quiet the output to their liking by configuring log level/target and possibly `report_status`.

But stepping back a bit, the initial post said

> The specifics are about the progress bar, but the general complaint can be summarized as "it should be easier to systematically parse the output when invoked in a script."

Depending on what the specifics are here, rather than parsing the output it could be better to use the python api and deal with the result dictionaries.  You could also get theses records with `-f json` from the command line, but the progress bars when not attached to a tty would still be an issue in this case.
