### ISSUE TITLE
Add dataset ID to superdataset .gitmodules

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3095]
ATM we exclusively rely on the URL in .gitmodules of a superdatasets for obtaining subdatasets. This is rather fragile (those could change at any point). I propose to add the subdataset's dataset UUID as a gitmodule property as well (on `install -d`, `add/rev-save -d`, and `create -d`). This will enable querying a dataset resolver in the future.

Having such additional identifying information also makes it more easy to work with dataset hierarchies without having to reflect the hierarchy composition 1:1 on the file system. This added flexbility will make it straighforward to build a **dataset-centric** view (as opposed to a directory-centric view like on http://datasets.datalad.org) of a large collection of datasets. Such as dataset-centric view (one page per dataset), is, for example, a precondition to be maximally compatible with Google dataset search, as metadata will need to be attached to this webpage.

Alternatively, we could not do that, but exclusively rely on metadata queries for subdatasets. The latter sounds attractive, but while easy to use/do implies more complex operations under the hood.

**Comment by yarikoptic** [comment]
In general I support the initiative. It shouldn't hurt. But pragmatically, besides verifying that installed dataset is there one we expect, I don't see immediate use for it. It might come useful in the future if we get a registry of datasets going though
Also note that some might be pure git/annex repos without uuid (when just looking to external ones without modifying their repos)

**Comment by mih** [comment]
Ok, metadata access it will be then.
