### ISSUE TITLE
expose "S3 client" capabilities to custom special remotes

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#31]
a really wild question:  to provide access to S3 buckets not exposed publicly (thus requiring authentication via IAM credentials, such as HCP) and through the prefix/revisionids, instead of just to a pure keystore (as in native git-annex S3 special remote), we would need to provide an external special remote which would need again to implement S3 client capabilities for basic authentication/fetching.  It can be done but we will grow dependencies implementing the same functionality as what git-annex already has inside.
So a wild thought came:  may be git-annex could somehow expose S3 functionality to e.g. external special remotes through some API? ;)  could well be made into something even more generic.  git-annex has already capabilities for talking to a plethora of data hosting providers and thus may be could serve as a glorified "ultimate downloader"? or to say may be to expose itself  as yet another special remote capable of TRANSFER?

**Comment by joeyh** [comment]
Well, git-annex doesn't have S3 functionality inside. It uses a library.
I think that using a library is a good solution.

I mean, look at git-annex's code to retrieve a file from S3:

retrieve :: S3Handle -> Retriever
retrieve h = fileRetriever $ \f k p -> liftIO $ runResourceT $ do
        (fr, fh) <- allocate (openFile f WriteMode) hClose
        let req = S3.getObject (bucket info) (bucketObject info k)
        S3.GetObjectResponse { S3.gorResponse = rsp } <- sendS3Handle' h req
        responseBody rsp $$+- sinkprogressfile fh p zeroBytesProcessed
        release fr
  where
        info = hinfo h
        sinkprogressfile fh meterupdate sofar = do
                mbs <- await
                case mbs of
                        Nothing -> return ()
                        Just bs -> do
                                let sofar' = addBytesProcessed sofar (S.length bs)
                                liftIO $ do
                                        void $ meterupdate sofar'
                                        S.hPut fh bs
                                sinkprogressfile fh meterupdate sofar'


Only 2 lines of that have anything to do with S3. The entire rest of it
is to do with streaming the bytes out to a file, with progress meter update.

And all of it is written to the abstraction level git-annex needs, which
is "retrieve this Key with progress sent to this MeterUpdate, and
provide a ContentSource to the passed callback action to consume it",
which is not the abstraction level a general-purpose library would need.

(Nor is it a stable abstraction, all this has been massively reworked once in
the last year, and may well be again. I want flexability of implementation
internals so I can make them better; exposing a library API is counter to
that.)

-- 
see shy jo

**Comment by yarikoptic** [comment]
"It uses a library. I think that using a library is a good solution"
yes -- it is a great solution to use a library whenever it is available ;)  
What I meant is that to provide a custom downloader from S3 we will also need to use some library.  But by 'using' a library git-annex already has all the needed functionality built-in to provide e.g. fetches from S3.  Moreover you have here already a "proper" progress meter update for git-annex.   Wouldn't it be neat then (this is all just a food for thought, feel free just to say No and close) if from within my custom special remote I could rely on git-annex'es built-in functionality (thus with "standard" progress metter) to fetch from S3 instead of relying on 1 more library (e.g. s3cmd) on my end?

**Comment by yarikoptic** [comment]
since interactions with S3 could be quite tricky anyways, we will just handle them on our side through boto
