### ISSUE TITLE
Reconsider choice of XZ format for content metadata

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3105]
Considering the long-term perspective this got me thinking whether the size gain fully justifies the complexity: http://www.nongnu.org/lzip/xz_inadequate.html

**Comment by yarikoptic** [comment]
Interesting find/analysis... Thanks, yet to read it in full and provide feedback

**Comment by mih** [comment]
FTR: Here are the bits that introduced this choice (with some stats): https://github.com/datalad/datalad/pull/1630

**Comment by mih** [comment]
It looks as if a sensible alternative would be to keep lzma compression (same storage impact), but replace the xz container format with standard ZIP. ZIP also supports LZMA and the Python zipfile module supports it since Python 3.3.

I could not find a backport of zipfile for Python 2, but issue will resolve itself at the end of the year.

https://docs.python.org/3.5/library/zipfile.html#zipfile.ZIP_LZMA
https://en.wikipedia.org/wiki/Zip_(file_format)#Compression_methods

An alternative could be https://en.wikipedia.org/wiki/Lzip but I did not see Python support for it.

**Comment by yarikoptic** [comment]
Here is what we would get now for all our extracted metadata at datasets.datalad.org placed into a .tar (1.074GB) with default and `-9` for gzip, bzip2 (-9 produced the same as default) and xz:
```shell
$> du -scm objects*tar*
1074    objects.tar
166     objects-default.tar.gz
161     objects-9.tar.gz
103     objects.tar.bz2
38      objects-default.tar.xz
36      objects-9.tar.xz
```

**Comment by yarikoptic** [comment]
note: Added bzip2 and lzip to the report [above](https://github.com/datalad/datalad/issues/3105#issuecomment-451980567), lzip -9 comes up as a winner

**Comment by yarikoptic** [comment]
here is some discussion on the analysis on https://www.reddit.com/r/linux/comments/58swzc/xz_format_inadequate_for_longterm_archiving/
which seems to summarize for mortals/us that unless file is damaged we should be just fine.  And we have git/annex to validate transmission etc. To that degree the widespread of .xz use in the wild (debian, gnome, etc) attests - so far I've not heard about "oh, .xz killed my data".

**Comment by mih** [comment]
Hmm, I remember "do not use xz for this and that debian package" and the lzip package also has a discussion on failure to extract on busybox.

**Comment by bpoldrack** [comment]
> which seems to summarize for mortals/us that unless file is damaged we should be just fine. And we have git/annex to validate transmission 

I don't think this is correct. It's not just about transmission errors. The flaws regarding error detection/correction are concerned with the comparison of the compressed, containerized data within the xz file to the original, uncompressed data. Annex doesn't know anything about the latter. If you added a corrupted xz file, that's fine for annex (of course!). And generally that's okay for us as well. But: If you look in that analysis (unchecked length fields for example), it might well be, that the corruption remains undiscovered during decompression. And that is a problem. You might notice only by a human looking at the actual decompressed data. That's bad design indeed. If there's a better way, particularly while still using the same compression algorithm, we should go there, I think.

**Comment by bpoldrack** [comment]
Note, that this is different from using it purely for delivering. If you have an uncompressed file and a checksum for it, then compress and deliver it, decompress and compare the checksum for the extracted file again - then you have the means to detect the corruption and don't need another one provided by the compression container. But this is not our situation.

**Comment by yarikoptic** [comment]
> Hmm, I remember "do not use xz for this and that debian package" and the lzip package also has a discussion on failure to extract on busybox.

I only remember "do not use .xz for source packages since older dpkg we use in neurodebian's backports, doesn't support it".  do you have an example url?

**Comment by yarikoptic** [comment]
> But: If you look in that analysis (unchecked length fields for example), it might well be, that the corruption remains undiscovered during decompression. And that is a problem. You might notice only by a human looking at the actual decompressed data.

sounds like there should then be an example file/invocation which leads to such a corrupted file.  Could you point to one?

**Comment by yarikoptic** [comment]
Buzz @bpoldrack and @mih if you are aware of the specific example cases where .xz performs incorrectly beyond inability to catch transmission errors? If not, then IMHO there is no rush to switch, although switching probably would be warranted whenever there is a ready to use alternative implementation.

**Comment by mih** [comment]
I could not find any concrete case that is immediately relevant for us. We could close this, and I will now.
