### ISSUE TITLE
Wanted minimal metadata fields

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3107]
I want to implement support for populating a minimal set of metadata fields from a dataset's individual metadata extract (which is in whatever format). The idea is to not have an automated mechanism report random blobs, but have a clear and tailored mapping in a dataset's configuration that defines which native metadata field to use to populate a specific field in the standard set.

My idea of a minimal set was written down (a long time ago) here:
http://docs.datalad.org/en/latest/metadata.html#rfc822-compliant-metadata-datalad-rfc822

Today I would probably add some kind of "tag" list.

I personally see the target audience to be humans (pretty much a necessity, when no defined terms for the metadata values (not keys) are used).

Moreover, I see this as an entirely optional feature. It won't solve the data discovery problem to any reasonable extent, but I acknowledge that I can hide the severity of the problem to some degree.

Please comment on the particular selection of metadata fields for this minimal set. Please also comment on the desired structure of the values. I personally think that anything beyond free-form text is useless, as it won't be significantly more useful (compared to actual linked data), but substantially increases the burden on users of this functionality. Hence I'd put "must be a human-readable string" a instructions.

PS: I should clarify that such a mapping from native to common fields would be defined in the dataset that is being aggregated _into_ to avoid the need to modified subdatasets for this purpose (and for a particular purpose that may or may not be what the "main" function of any dataset is envisioned to be).

**Comment by yarikoptic** [comment]
- I think that the set should be the subset of https://schema.org/Dataset and not introduce new/different fields (e.g `Funding` vs `funder`)
- `I should clarify that such a mapping from native to common fields would be defined in the dataset that is being aggregated into to avoid the need to modified subdatasets for this purpose`.  I think it should be configurable, as it is already the case for aggregation.  Shouldn't be such harmonization step be a post-processing on aggregation and thus no specific logic on "when/whereto" is actually specific to it?

**Comment by mih** [comment]
Ping @christian-monch to document one of the aspects motivating a minimal dataset description.

**Comment by mih** [comment]
Closing this issue of mine, acting on the apparent lack of motivation to work on it. And there is https://github.com/datalad/datalad-metalad/pull/62 now.
