### ISSUE TITLE
Add command that aid cleanup of WiP handles

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#311]
When working with handles (mostly with derived data) it often happens that data is regenerated. Often the outdated/previous results/files are no longer interesting.

We should have a convenience wrapper around git annex' `unused`, `log`, and `dropunused` commands that aids intermediate cleanup procedures. With git annex I need to do:

1. run `unused` to get a long list of keys that I need to look up by 
2. run `log' to figure out where the key was used last
3. run `dropunused` with an index(/range) to get rid of the annexed content

Minimal use case would be "drop all keys for all files that are still present, but have updated content". Another one could be "delete these files (with all there annex'ed content)". The latter sounds dangerous, though....

**Comment by yarikoptic** [comment]
May be it is the morning effect but I am not sure what you actually want to accomplish here...  e.g. with "drop all keys for all files that are still present, but have updated content" do you want to drop (delete without leaving a copy anywhere in graveyard) previous versions of all the files, or?  why did you need to associate keys with filenames (from the log).

From the first paragraph it seems that you just want to delete (drop without graveyarding) all the previous versions of any file which is not referenced by any branch ATM, which would be `git annex unused; git annex dropunused --force all`. what am I missing?

**Comment by hanke** [comment]
Your suggested command will drop all annex content that is no longer referenced. I want to drop only content that is no longer referenced, but we its old reference (link) now points to some new content. I want to keep all content that is no longer referenced, but no new content is known.

**Comment by hanke** [comment]
In other words: I want to keep the last version of everything, and the last version only.

As if I was certain that I know what I am doing and I only regenerate files when I know I don't need the old content anymore.

**Comment by yarikoptic** [comment]
I think I can understand "keep the last version of everything, and the last version only", where everything would be a "file". Indeed since annex operates on 'keys', it requires log traversal to figure out what file was it for a key to be removed, so you don't remove those if it was the last version of that file.  BUT what is the use-case?  why do you want to keep a copy of some file you no longer have, while you might not have associated versions for the other files (which were changed since then) in that previous commit?

**Comment by hanke** [comment]
Because I find it attractive to be able to delete files aggressively all the time, and still have a safety net until judgement day comes. Think I am crazy? ;-)

**Comment by yarikoptic** [comment]
but what such a safety net will give you if you would not have the rest of the content at that commit?

**Comment by hanke** [comment]
I am not talking about rm-ing the symlinks, I am talking aboutt `git rm`s with commits and all that. I just want to be able to trim things down along the way.

But OK maybe a bad idea (which means I wasted my entire morning doing this to free up space). Will revisit this issue again, when I have to perform this task the next time.

**Comment by yarikoptic** [comment]
one possible workflow which could be of help is to tag those "interesting-to-keep" commits, and then drop the content not referenced by any branch or any tag.  This would allow to prune intermediate results, make clear for which points you have complete data
