### ISSUE TITLE
Test against `master` of datalad extensions, not released versions

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3112]
At the moment we install extensions from PyPi to run their tests. However, when changes have to be made at both ends, as in

https://github.com/datalad/datalad/pull/3111
https://github.com/datalad/datalad-crawler/pull/31

the ping pong chain to get things clean again is quite long. Should we switch to test against the latest `master` branch content of an extension to speed things up a bit?

**Comment by yarikoptic** [comment]
Then we might end up releasing extension which doesn't work with released datalad.... Can versions dependency point >= -dev in setup to prevent that somewhat?

**Comment by mih** [comment]
This would effect the release of an extension, and that can be tested in the tests of that extension. The problem here affects -core, which would be broken until any broken extension has the fix in a released version. Failure at the center is more sever than at the edges IMHO.

**Comment by kyleam** [comment]
Closed by #4163.

**Comment by yarikoptic** [comment]
For completness -- https://github.com/datalad/datalad-extensions will be setup with cron jobs to test released extensions against master of datalad.  Making sure that they are all green before release of the core- should be a part of the release process.
