### ISSUE TITLE
requests: provide a plugin interface to allow implementation of data loading and "streaming

### ISSUE THREAD

**Issue by satyaog** [datalad/datalad#3120]
#### What is the problem?
General information
#### What steps will reproduce the problem?
N/A
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
N/A
#### Is there anything else that would be useful to know in this context?
No
#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
N/A

Hi, I'm not sure this is the right channel to discuss this so let me know if I there's a better to discuss this.

I'm working at Mila, an AI research institute, and we are looking for solutions to distribute and load the datasets we have in our cluster, for our researchers at first. The distribution would be internally in the cluster and externally to other compute graphs depending on the workflow of each researcher.

We looked into DataLad and we really liked that it's harnessing the flexibility and power of git/git-annex, the ability easily track the updates on a dataset and the organization of datasets and super-datasets.

Features that for us would be useful and in which we don't seam to find a fit in DataLad in it's current state would be regarding data loading and "streaming". Data loading would be in the form of a simple plugin interface that abstracts the load of an entire dataset, the load by batch by returning an iterator of batches of entries from the dataset or the load of a specific partition of the dataset, if the dataset can be separated by partitions. The idea behind this would be to provide a simple way for our users to implement the actual loading of data using the library or method that they prefer without having to worry too much about the plumbing.

A "streaming" feature could be very useful in the case the dataset is very big and the user doesn't want to wait until the complete download of the dataset before starting an experiment. This would be very dependent on the data format but if it allows random access, the user could download a batch of entries and pre-download the next batch while the processing of the previous is happening. I imagine however that this part could be difficult to implement since git-annex would need to provide an interface allowing to specify which bytes to download.

I hope this is somewhat clear, could you let me know what you think of that?

Thank you

**Comment by yarikoptic** [comment]
It was followed by a duplicate #3121 to which was a reply comment posted, so closing this one
