### ISSUE TITLE
datalad add * adds subdir/subrepo/* to itself instead of within subdir/subrepo (with or without -r)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3139]
I think I have ran into this situation in the field but then didn't have minimal use case and blamed `git annex sync` somehow.  Now I have ran into it with smaller case and replicated.  If `add`'ing subdirectory (behaves ok if subds is at the top level of the ds), with a git repository under (not registered as a git submodule) where there is untracked file, it gets added to the top dataset, not gets ignored (no `-r` for add invocation):

```shell
$> mkdir ds && cd ds && git init && touch file && mkdir -p d1/subds && git -C d1/subds init && touch d1/subds/subfile && datalad add *                                                                                                
Initialized empty Git repository in /tmp/ds/.git/
Initialized empty Git repository in /tmp/ds/d1/subds/.git/
add(ok): /tmp/ds/d1/subds/subfile (file)
add(ok): /tmp/ds/file (file)
add(ok): /tmp/ds/d1 (directory)
save(ok): /tmp/ds (dataset)
action summary:
  add (ok: 3)
  save (ok: 1)
(dev) 1 19071 [1].....................................:Mon 04 Feb 2019 09:13:31 AM EST:.
(git)hopa:/tmp/ds[master]
$> git status
On branch master
nothing to commit, working tree clean
(dev) 1 19072 [1].....................................:Mon 04 Feb 2019 09:13:42 AM EST:.
(git)hopa:/tmp/ds[master]
$> git -C d1/subds status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	subfile

nothing added to commit but untracked files present (use "git add" to track)
```

with `add -r` it seems to manage to perform another atrocious act - add file in both top level and subdataset (note that subds isn't getting added as a submodule, I guess due to the lack of `-d .`):
```shell
$> mkdir ds && cd ds && git init && touch file && mkdir -p d1/subds && git -C d1/subds init && touch d1/subds/subfile && datalad add -r *                                                                                                                   Initialized empty Git repository in /tmp/ds/.git/
Initialized empty Git repository in /tmp/ds/d1/subds/.git/
add(ok): /tmp/ds/d1/subds/subfile (file)
add(ok): /tmp/ds/d1/subds (dataset)
add(ok): /tmp/ds/d1/subds/subfile (file)
add(ok): /tmp/ds/file (file)
add(ok): /tmp/ds/d1 (directory)
save(ok): /tmp/ds/d1/subds (dataset)
save(ok): /tmp/ds (dataset)
action summary:
  add (ok: 5)
  save (ok: 2)
(dev) 1 19076 [1].....................................:Mon 04 Feb 2019 09:16:49 AM EST:.
(git)hopa:/tmp/ds[master]
$> git status
On branch master
nothing to commit, working tree clean
(dev) 1 19077 [1].....................................:Mon 04 Feb 2019 09:16:57 AM EST:.
(git)hopa:/tmp/ds[master]
$> git log --stat
commit fab8c31578c13ad0eb7e7c8e09257e71ecf0b195 (HEAD -> master)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Mon Feb 4 09:16:49 2019 -0500

    [DATALAD] added content

 d1/subds/subfile | 0
 file             | 0
 2 files changed, 0 insertions(+), 0 deletions(-)
(dev) 1 19078 [1].....................................:Mon 04 Feb 2019 09:17:00 AM EST:.
(git)hopa:/tmp/ds[master]git
$> git -C d1/subds log --stat 
commit da8a0d17c73d00cdc9db92be5fad2559181eb015 (HEAD -> master)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Mon Feb 4 09:16:49 2019 -0500

    [DATALAD] added content

 subfile | 0
 1 file changed, 0 insertions(+), 0 deletions(-)
(dev) 1 19079 [1].....................................:Mon 04 Feb 2019 09:17:11 AM EST:.
(git)hopa:/tmp/ds[master]git
$> git status                
On branch master
nothing to commit, working tree clean
(dev) 1 19080 [1].....................................:Mon 04 Feb 2019 09:18:38 AM EST:.
(git)hopa:/tmp/ds[master]git
$> cat .gitmodules
cat: .gitmodules: No such file or directory
```
datalad  0.11.1-143-ga1935397

**Comment by yarikoptic** [comment]
please show `git log --stat` -- since otherwise actually looks like an issue with revolution as well since there is  `add(ok): d1/subds/subfile (file)`

**Comment by kyleam** [comment]
> FTR: seems to be a non-issue in -revolution:

I think it's still an issue.  Note the second status call:

```
% mkdir ds && cd ds && git init && touch file && mkdir -p d1/subds && git -C d1/subds init && touch d1/subds/subfile && datalad rev-save *
Initialized empty Git repository in /tmp/dl-zvW8ZkY/ds/.git/
Initialized empty Git repository in /tmp/dl-zvW8ZkY/ds/d1/subds/.git/
add(ok): d1/subds/subfile (file)
add(ok): file (file)
save(ok): . (dataset)
action summary:
  add (ok: 2)
  save (ok: 1)

% git status
On branch master
nothing to commit, working tree clean

% git -C d1/subds status
On branch master                                  
 
No commits yet

Untracked files:
	subfile

nothing added to commit but untracked files present
```

**Comment by mih** [comment]
True, I will investigate.

**Comment by mih** [comment]
Update: The -revolution failure is due to the specifics of bug demo code. It uses empty repositories (without a single commit) that obviously cannot be added to a superdataset. With datasets it behaves as expected. I will adjust the code to foresee this possibility.

**Comment by mih** [comment]
The reason for the actual failure (in -revolution) is that `git ls-files` does not treat repos without an initial commit like repos with a commit.

Starting from the same original state of the test above:
```
% git ls-files --stage -d -m --exclude-standard -o
d1/subrepo/subfile
file.txt
100644 b540820107ca5718dc0f196a08edf3729239bfef 0       .datalad/.gitattributes
100644 7ab9c7d6877fac805d76818b07e7a3e35fa1cc12 0       .datalad/config
100644 c3aaefef9a2470b31ba9213350046ff7cde75737 0       .gitattributes

% git -C d1/subrepo add subfile
% git -C d1/subrepo commit -m first
% git ls-files --stage -d -m --exclude-standard -o
d1/subrepo/
file.txt
100644 b540820107ca5718dc0f196a08edf3729239bfef 0       .datalad/.gitattributes
100644 7ab9c7d6877fac805d76818b07e7a3e35fa1cc12 0       .datalad/config
100644 c3aaefef9a2470b31ba9213350046ff7cde75737 0       .gitattributes
```

Note how the file is present in the first output, but only the repo is present in the second one. This is precisely the test condition that is used in -revolution to detect subdataset without expensive tests.

*IF* we would want to support users placing empty non-dataset repositories inside dataset and not have them be ignored (like `ls-files`), but treated as subdatasets (which they are not), then we will have to test all parent directories of any untracked file for evidence of a repository root. Once found, we would then ignore such repository and all files therein. Unfortunately, this is a relatively expensive test, as it will have to happen on an expanded list of untracked files, in any repository, regardless of whether there is a subrepository or not.

Given this assessment, I personally think it is best to document that such scenario is not supported.

**Comment by kyleam** [comment]
> Given this assessment, I personally think it is best to document that such scenario is not supported.

Sounds sensible to me.

**Comment by yarikoptic** [comment]
> Given this assessment, I personally think it is best to document that such scenario is not supported.

I am ok to not support such scenario even though would be a blow to our pride imho while claiming that the mighty datalad works across repositories boundaries etc.
But it is not merely a documentation issue. If not supported, we must either blow (exception) when we run into such case (e.g., while annotating paths) with some informative instruction ("make a commit in repo X or make it into a proper datalad dataset") or issue a warning with similar message and then ignore any related path.  DataLad must not perform incorrect operation (adding file into super repo ignoring present .git in subrepo).

**Comment by kyleam** [comment]
I think we can consider this closed given that there are [patches] to address this upstream.  With a little luck, those should land and `git ls-files` will start listing repos without an initial commit in the same way as it lists other repos.

Once that makes it into a release, I'll update the note in rev-save's help and test_surprise_subds accordingly.

[patches]: https://public-inbox.org/git/20190409230737.26809-1-kyle@kyleam.com
