### ISSUE TITLE
manpages do not provide the version of datalad

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3152]
I thought I had it, but tested also on smaug with 0.11.1 installed system wide -- there is no DataLad version in the last line, like I thought it used to be (if it was) and how other tools have it (e.g. do `man git` or `man ls` and go to the end)

**Comment by mih** [comment]
They do in todays master. Closing.

**Comment by yarikoptic** [comment]
Yeap, I believe fixed as a part of https://github.com/datalad/datalad/pull/3600 so also fixed in 0.11.x
