### ISSUE TITLE
Datalad get not working with on a specific network

### ISSUE THREAD

**Issue by adelavega** [datalad/datalad#3154]
#### What is the problem?
I'm trying to install and download this dataset: https://github.com/OpenNeuroDatasets/ds001545

As an example, trying to get this file `datalad get sub-01/func/sub-01_task-movie_run-01_bold.nii.gz`
and doing a `datalad install`

I've gotten the following errors:

datalad 0.10.2
```
Total (0 ok, 1 failed out of 1):   0%|                                                                                 | 0.00/280M [00:00<?, ?B/s][WARNING] Running get resulted in stderr output:   Remote is configured to use versioning, but no S3 version ID is recorded for this key
git-annex: get: 1 failed
 
[ERROR  ] from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:;       41c48007-5636-4d32-bf50-a372ccc28c77 -- root@db67d735f607:/datalad/ds001545;  	67152e11-096c-4d56-a362-05ff2daa5775 -- [s3-PUBLIC];  	df4b8ac1-b5b1-4ea1-b7ae-a3696ba696a0 -- s3-PRIVATE; ; (Note that these git remotes have annex-ignore set: origin) [get(/home/zorro/datasets/ds001545/sub-01/func/sub-01_task-movie_run-01_bold.nii.gz)] 
get(error): /home/zorro/datasets/ds001545/sub-01/func/sub-01_task-movie_run-01_bold.nii.gz (file) [from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 	41c48007-5636-4d32-bf50-a372ccc28c77 -- root@db67d735f607:/datalad/ds001545;  	67152e11-096c-4d56-a362-05ff2daa5775 -- [s3-PUBLIC];  	df4b8ac1-b5b1-4ea1-b7ae-a3696ba696a0 -- s3-PRIVATE; ; (Note that these git remotes have annex-ignore set: origin)]
```
and
datalad 0.11.0
```
[WARNING] Running get resulted in stderr output:   Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
git-annex: get: 1 failed
 
[ERROR  ] from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 	41c48007-5636-4d32-bf50-a372ccc28c77 -- root@db67d735f607:/datalad/ds001545;  	67152e11-096c-4d56-a362-05ff2daa5775 -- [s3-PUBLIC];  	df4b8ac1-b5b1-4ea1-b7ae-a3696ba696a0 -- s3-PRIVATE; ; (Note that these git remotes have annex-ignore set: origin) [get(/home/alejandro/datasets/raw/ds001545/sub-01/func/sub-01_task-movie_run-01_bold.nii.gz)] 
get(error): /home/alejandro/datasets/raw/ds001545/sub-01/func/sub-01_task-movie_run-01_bold.nii.gz (file) [from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 	41c48007-5636-4d32-bf50-a372ccc28c77 -- root@db67d735f607:/datalad/ds001545;  	67152e11-096c-4d56-a362-05ff2daa5775 -- [s3-PUBLIC];  	df4b8ac1-b5b1-4ea1-b7ae-a3696ba696a0 -- s3-PRIVATE; ; (Note that these git remotes have annex-ignore set: origin)]
```

#### What steps will reproduce the problem?
I'm having a hard time diagnosing this, as at first I thought it was a datalad version, but I tried two versions. Very oddly though, this problem only seems to occur on the UT network (not at home), and I've had no issues with other OpenNeuro datasets. 

Will try again when I'm home with upgraded datalad to see if problem persists. 

Also, side question: is there a way to get datalad 0.11.0 on Ubuntu 18.10?

**Comment by adelavega** [comment]
Apologies maybe I should have posted this on OpenNeuro (it may just be an improperly configured remote)

**Comment by yarikoptic** [comment]
There are outstanding issues with some openneuro datasets from the mid-ages (i.e. most old ones should be good, and recent ones should be good), see the whinings of yours truly at https://github.com/OpenNeuroOrg/datalad-service/issues/created_by/yarikoptic  -- choose your favorite one.  in this particular one you would get a better message with newer annex:
```shell
$> datalad install ///openneuro/ds001545
[INFO   ] Cloning http://datasets.datalad.org/openneuro/ds001545 [1 other candidates] into '/tmp/ds001545' 
[INFO   ] access to dataset sibling "s3-PRIVATE" not auto-enabled, enable with:  
| 		datalad siblings -d "/tmp/ds001545" enable -s s3-PRIVATE 
install(ok): /tmp/ds001545 (dataset)

$> git annex get sub-01/anat 
get sub-01/anat/sub-01_T1w.nii.gz (from s3-PUBLIC...) 

  Remote is configured to use versioning, but no S3 version ID is recorded for this key

  Unable to access these remotes: s3-PUBLIC

  Try making some of these repositories available:
  	41c48007-5636-4d32-bf50-a372ccc28c77 -- root@db67d735f607:/datalad/ds001545
   	67152e11-096c-4d56-a362-05ff2daa5775 -- [s3-PUBLIC]
   	df4b8ac1-b5b1-4ea1-b7ae-a3696ba696a0 -- s3-PRIVATE
failed
git-annex: get: 1 failed
```
so it is the https://github.com/OpenNeuroOrg/datalad-service/issues/83 issue.
I could just crawl those datasets in good old fashion to populate full length URLs for those files pointing to the s3 bucket, so at least those clones from datasets.datalad.org could finaly provide you access to the data... but I remain hopeful for a proper resolution at openneuro side

**Comment by yarikoptic** [comment]
nothing for us to fix in DataLad itself, so I will close this one. Thanks for whining along

**Comment by adelavega** [comment]
Oh, great to know about that repo! I wasn't sure where to whine.

**Comment by yarikoptic** [comment]
> Also, side question: is there a way to get datalad 0.11.0 on Ubuntu 18.10?

18.10 (cosmic) -- ho ho -- I have missed that ubuntu 6-month-matured completely!  I will need to rebuild archive for it. FWIW we got datalad 0.11.2 out today...   I will build fresh datalad for 18.10 first I guess before that entire rebuild, or otherwise I bet you could just dpkg -i one from 18.04 or debian sid no problem

**Comment by adelavega** [comment]
Yeah, turns out it has much better battery management so I went for it! Mostly worth it;)

**Comment by yarikoptic** [comment]
BTW cosmic ppl now should be happy ppl @adelavega
