### ISSUE TITLE
uninstall-handle  doesn't remove its directory with meta-data from 'master collection'

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#316]
I am not yet quite certain but seems to be that (in particular if using DATALAD_COLLECTION_PATH)

```
(git)hopa:~datalad/datalad-master[rf-repo-classes]docs/examples/collection-1000
$> mkdir -p master-collection; DATALAD_COLLECTION_PATH=$PWD/master-collection DATALAD_LOGTRACEBACK=1 datalad uninstall-handle bogus361-1000

$> ls -ld /home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus-1000_collection/bogus361-1000 
drwx------ 2 yoh yoh 4096 Dec 10 12:15 /home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus-1000_collection/bogus361-1000/

$> ls -ld /home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus-1000_collection/bogus361-1000

$> mkdir -p master-collection; DATALAD_COLLECTION_PATH=$PWD/master-collection DATALAD_LOGTRACEBACK=1 datalad uninstall-handle bogus361-1000
2015-12-10 14:25:53,034 [ERROR  ] datalad:9>main:207  Handle 'bogus361-1000' unknown. [uninstall_handle.py:__call__:54] (ValueError) (main.py:207)

$> ls -ld /home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus-1000_collection/bogus361-1000 
drwx------ 2 yoh yoh 4096 Dec 10 12:15 /home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus-1000_collection/bogus361-1000/
```

**Comment by yarikoptic** [comment]
also it still seems to carry it in its datalad.ttl
```
(git)hopa:…alad-master/docs/examples/collection-1000/bogus-1000_collection[master]git
$> git diff
diff --git a/datalad.ttl b/datalad.ttl
index f62681d..82db756 100644
--- a/datalad.ttl
+++ b/datalad.ttl
@@ -303,6 +303,7 @@ dlns:this a dlns:Collection ;
         <file:///home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus359-1000>,
         <file:///home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus36-1000>,
         <file:///home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus360-1000>,
+        <file:///home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus361-1000>,
         <file:///home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus37-1000>,
         <file:///home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus38-1000>,
         <file:///home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus39-1000>,
changes on filesystem:                                                                                           
 datalad.ttl | 1 +

$> mkdir -p master-collection; DATALAD_COLLECTION_PATH=$PWD/master-collection DATALAD_LOGTRACEBACK=1 datalad uninstall-handle bogus361-1000
2015-12-10 14:29:17,461 [ERROR  ] datalad:9>main:207  Handle 'bogus361-1000' unknown. [uninstall_handle.py:__call__:54] (ValueError) (main.py:207)
```

**Comment by bpoldrack** [comment]
Okay, first of all, we need to clarify, what exactly we want uninstall-handle to do. See also #250 .
Secondly, what I see in your posts, is the handle not being removed from the bogus-100 collection - you look into this one instead of master-collection.
This nevertheless might be considered a bug, but I'm not so sure about it. Why would uninstall-handle modify a collection other than the master-collection?
Was the actual handle repository removed? What does master-collection look like? It doesn't find a bogus261-1000 anymore, so this looks good to me.

**Comment by yarikoptic** [comment]
ha -- I could swear that it did remove the actual handle but I guess I was wrong... 
```
hopa:/tmp/collection-1000
$> ls -ld bogus381-1000  
drwx------ 4 yoh yoh 100 Dec 10 14:38 bogus381-1000/

$> DATALAD_COLLECTION_PATH=$PWD/master-collection datalad uninstall-handle bogus381-1000             

$> ls -ld bogus381-1000                                                                 
drwx------ 4 yoh yoh 100 Dec 10 14:38 bogus381-1000/

$> DATALAD_COLLECTION_PATH=$PWD/master-collection datalad list-handles | grep bogus381-1000
DATALAD_COLLECTION_PATH=$PWD/master-collection datalad list-handles  27.85s user 0.56s system 98% cpu 28.769 total
grep --color=auto -d skip bogus381-1000  0.00s user 0.00s system 0% cpu 28.769 total
```

so indeed handle remained physically present, so this action resulted in "unregistering" that handle within local master collection (note that it took 28sec to list handles!) and not within its original collection:

```
$> grep bogus381-1000 master-collection/datalad.ttl 

$> grep bogus381-1000 bogus-1000_collection/datalad.ttl 
        <file:///home/yoh/proj/datalad/datalad-master/docs/examples/collection-1000/bogus381-1000>,
```
I feel that in terms of API names, we should uniformize 'register' with 'add' and 'unregister' with 'remove', and `uninstall-handle` in current implementation of it is more of 'unregister'.    What command currently allows to remove/unregister handle from a given (not master) collection?

P.S. To me this is yet another example of having 'master collection' as the beast which tracks all of the handles, instead of following filesystem hierarchy as git/etc do, introduces unnecessary level of complication

**Comment by bpoldrack** [comment]
Actually, the current implementation should remove the handle repo. So, could you look the handle up before uninstall? (using datalad whereis) May be your custom master collection is talking about another location, than you do?

**Comment by yarikoptic** [comment]
ah -- right.  I forgot that all those locations are with absolute paths (thank you RDF! bleh... although may be it is not the RDF to blame ... ;) )!!!  and it did remove it... bleh

and now I see that in original report I was checking that directory not under master but under original collection, so report is invalid, closing it

Having said that, such actions as removing handle, unregistering within collection should have had log messages at the level of info at least, now nothing gets spit out
