### ISSUE TITLE
FOI: datalad publish  to "stable" environments is tricky of usually outdated system-wide git

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3163]
Because we typically need `receive.denyCurrentBranch=updateInstead` support in git, we need some recent git (forgot when it was introduced but is present in e.g. 2.14). But institutional systems still might run some trusted RH release such as `Red Hat Enterprise Linux Server release 7.6 (Maipo)` which comes with git 1.8.3.1 !  Because we are operating in non-interactive sessions, there is IMHO no way to make login shell tune up PATH (e.g. that is causes troubles for git annex on OSX where it is not available in default PATHs).
I wondered if we could do anything about it!?

Actually, to my surprise, on the system in question I just adjusted PATH in .bashrc to point to git-annex bundled git (at the end, just did `module load datalad`) and it was in effect for a non-interactive session and `datalad publish` worked out as it should.  On my local system (Debian), adjusting .bashrc for a sample user was not in effect for non-interactive session (which is what I have remembered). So I guess there is a peculiarity about that particular system configuration. Or could someone enlighten me?

**Comment by kyleam** [comment]
> On my local system (Debian), adjusting .bashrc for a sample user was not in effect for non-interactive session

My Debian .bashrc has the lines

```bash
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

Does yours have something like that?

**Comment by yarikoptic** [comment]
eh heh heh heh -- that explains everything, besides my reading `man bash` (unless it was also tuned) ! eh, thank you Debian. On CentOS .bashrc seems to be much leaner
```shell
$> docker run -it --rm centos bash -c 'adduser test; cat ~test/.bashrc'      
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
```
and without any policing. 
So FOI and good to know... and now I wonder WTF was my bad memory about OSX!? since
```
$> ssh  yoh@datalads-imac.kiewit.dartmouth.edu cat .bashrc
export PATH=/usrrrr:$PATH

$> ssh  yoh@datalads-imac.kiewit.dartmouth.edu 'echo $PATH'
/usrrrr:/usr/bin:/bin:/usr/sbin:/sbin
```
so seems to be tuneable, and thus I am not sure what wrong memory I had about this case.

**Comment by yarikoptic** [comment]
thank you @kyleam !
