### ISSUE TITLE
gzip: Too many levels of symbolic links

### ISSUE THREAD

**Issue by mih** [datalad/datalad#317]
Protocol of an observation that will likely end up under "known issues":

% gzip -d -k SOMANNEXEDFILE
gzip: SOMEANNEXDFILE: Too many levels of symbolic links

**Comment by mih** [comment]
Closing, this is just FTR.

**Comment by yarikoptic** [comment]
I just ran into this!  @joeyh - is that a known limitation with "nothing to do about it" status or there is some workaround?

**Comment by joeyh** [comment]
Sounds like a symlink loop.

-- 
see shy jo

**Comment by yarikoptic** [comment]
yeap, IMHO it is a bug in gzip:
```shell
$> mkdir /tmp/testgz; cd /tmp/testgz; echo 123 > 123; gzip 123; ln -s 123.gz linked.gz; gunzip linked.gz
gzip: linked.gz: Too many levels of symbolic links
```

**Comment by yarikoptic** [comment]
Just FTR - filed a bug with Debian maintainers and CCed us all (forgot to tag it as upstream, heh)

**Comment by Manukapp** [comment]
Hello, I am a MSc student looking to analyse the ses-movie dataset of studyforrest. I have not found any solution to actually get the data from the .nii.gz files. I have downloaded the whole dataset (I think, after several hours of ~440GB download), but still have .nii.gz files that do not gunzip. I receive the 'Too many levels of symbolic links' error. 
Could you please help me accessing the data for it to be pre-processed in SPM?

Thank you for your help.
@mih 
@yarikoptic

**Comment by adswa** [comment]
Oh I never realized that there has been an issue about this... I have run into this many times - what "fixes" it is using ``gunzip -f`` (``--force``). Good luck with your analysis!

**Comment by adswa** [comment]
PS: If you don't need to use all of the 440GB of data, drop files you do not need with ``datalad drop`` to free up the disk space again

**Comment by Manukapp** [comment]
Hello adswa,

Thank you very very much! All of this worked! I am now starting the data analysis engine!!

Speak soob
