### ISSUE TITLE
patool/datalad.Runner/gzip indigestion - stalls on a sample tiny file

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3175]
Troubleshooting stalling run of a test for the crawler https://github.com/datalad/datalad-crawler/pull/37 , which came about when I recently introduced support for crawling .gz files.

My exploration, first trying on trusty env to just realize the difference in execution with local:

- installing `p7zip-full` "mitigates" the issue. patool then uses `7z` and things work lovely
- with either regular gzip or pigz we would get it stalling at us running them for patool 
- we default to log stdout and stderr in the Runner
- ... more to come ... just wanted to protocol it

**Comment by yarikoptic** [comment]
additional aspect is inconsistency in patool's/archivers behavior for extracting a file, which is in our case is relevant if file is annexed and its filename is actually the annex key: https://github.com/wummel/patool/issues/67

**Comment by kyleam** [comment]
I think this is OK to close. Please re-open if I'm mistaken.
