### ISSUE TITLE
Feedback: move metadata filter/uniqueification extraction->aggregation

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3177]
At the moment lots of metadata processing is done during extraction. However, I believe that at the time of extraction information on the application context (what is it being extracted for) is insufficient to make proper decisions. Hence I believe that stuff like:

- black-listing of metadata fields
- metadata size limits
- generation of unique-value lists

must be moved to a later stage, i.e. become a part of the metadata aggregation step.

For global context of related changes: https://github.com/datalad/datalad-revolution/issues/54

Please close on ACK. Thx.

**Comment by yarikoptic** [comment]
I am not sure if we have such a clean boundary between extraction and aggregation, do we? e.g. if I do not have a hierarchy and just a single dataset, extracted in a dataset metadata is the "aggregated" one, so when then any filtering etc to be done?

**Comment by mih** [comment]
In -core it is all one big blob. in -revolution it is strictly separate, i.e. aggregation call the public extraction API.

> if I do not have a hierarchy and just a single dataset, extracted in a dataset metadata is the "aggregated" one

No. Extracted is what `extract-metadata` reports, aggregated is what `aggregate-metadata` stores. They could be very different.

**Comment by mih** [comment]
Feedback came, issue served its purpose.
