### ISSUE TITLE
fatal: unable to write new index file

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3181]
git for some reason refuses to write index under /tmp which has a good amount of space left, and resides on a different partition:

```shell
$ datalad create -d . --force Badal
[INFO   ] Creating a new annex repo at /data/.../sourcedata/Badal
[ERROR  ] Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)
|   cmdline: /usr/lib/git-annex.linux/git -c receive.autogc=0 -c gc.auto=0 read-tree --index-output=/tmp/datalad_temp_7drd148k 443e4211f974430771bebc575230fece04085620
|   stderr: 'fatal: unable to write new index file' [cmd.py:execute:821] (GitCommandError)
```

and indeed so even with system wide git
```shell
$ git -c receive.autogc=0 -c gc.auto=0 read-tree --index-output=/tmp/datalad_temp_7drd148k 443e4211f974430771bebc575230fece0408562
fatal: unable to write new index file
```
and there is enough space there
```shell
$ df -h /tmp
Filesystem      Size  Used Avail Use% Mounted on
/dev/md7        9.4G  5.7G  3.7G  61% /tmp
```
@kyleam are you aware of any obvious reasons (cross-filesystem?) which would cause the problem with temporary index?  I guess we better use .git/tmp for it

**Comment by kyleam** [comment]
I didn't know that, but yeah, guess it needs to be created on the same file system.

>  I guess we better use .git/tmp for it

Sounds good, though I'd prefer a more specific name: ".git/datalad-temp.index" or even a temporary file name with a "datalad-" prefix.

**Comment by kyleam** [comment]
Ah, from the lovely manual:

```
       --index-output=<file>
           Instead of writing the results out to $GIT_INDEX_FILE, write the resulting index in the named file.
           While the command is operating, the original index file is locked with the same mechanism as usual. The
           file must allow to be rename(2)ed into from a temporary file that is created next to the usual index
           file; typically this means it needs to be on the same filesystem as the index file itself, and you need
           write permission to the directories the index file and index output file are located in.
```

**Comment by kyleam** [comment]
@yarikoptic What's your preference on closing via the 0.11.x branch?  Should we leave issues that were fixed in 0.11.x open until a periodic merge of 0.11.x into master or would you prefer to close manually?  I suppose one advantage of the former is that it serves as a reminder to do the merge.

**Comment by yarikoptic** [comment]
I think it makes sense to have them indeed closed by merge into master, avoiding manual

**Comment by vassiki** [comment]
Happy to report that I didn't run into this bug while using the branch 0.11.x as a developer. Version of datalad was 0.11.3.dev13. Thanks @yarikoptic and @kyleam!
