### ISSUE TITLE
Restructure source tree

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3192]
I believe we agree that the source tree is a bit out of sync with the internal (dependency) structure of the code. I would like to propose a restructuring as follows (lumping together stuff that is scattered across -core and the -revolution extension for now):

- [ ] move core dataset and repo classes into `dataset/` (or rather `core/dataset/`)
  - [ ] it might make sense to split Git/AnnexRepo into a core and an extended interface also (via inheritance), the number of rarely used methods is substantial ATM
- [ ] `core/` -- in the spirit of #2765, introduce `core/` for a minimal set of commands that serve as the foundation for others and receive special scrutiny regard API composition and changes.
  - [ ]  `local/` -- essential commands for working with a single local dataset(-hierarchy)
    - [ ] `status`
    - [ ] `diff`
    - [ ] `save`
    - [ ] `create`
    - [ ] `run`
    - [ ] `metadata` (anything that is concerned with *accessing* the internal metadata representation)
    - [ ] `extract-metadata` (coming via -revolution, stable interface to execute extractors)
  - [ ] `distributed/` -- key commands needed for communication with other dataset instances
    - [ ]  `clone`
    - [ ]  `get`
    - [ ]  `update`
    - [ ]  `publish`
    - [ ]  `siblings`

In addition, there is a second set of categories that are identical by name, but are treated more like applications instead of foundation with the goal of having them move faster (or at all) in order to expose features and/or adapt to changes in the software/service ecosystem
- [ ] `local/`
  - [ ] `rerun`
  - [ ] `run-procedure`
  - [ ] `add*`
  - [ ] `download-url`
  - [ ] `ls`
  - [ ] `subdatasets`
    - [ ] `aggregate-metadata` (not a core command, there could be multiple ways of aggregation, as long as the result is a data structure that the core `metadata` command can access)
    - [ ] `search`
- [ ] `distributed/`
    - [ ]  `install` (placed here and not in core, because we have plans for complex features that could be difficult to keep stable long-term, hence this could be seen as an "application" that installs dataset via all kinds of ways)
    - [ ]  `drop`
    - [ ] `create-sibling*`
    - [ ] `export-*`

Other (more "leafy") commands could either be injected in these categories, or populate to additional ones, to possibly better indicate (and enforce?) their (in)dependence on/from others:
- remove
- uninstall
- clean

Given the target directories do not conflict with anything, we could approach such a transitions slowly and keep import shims in place for any length of time to ease the pain.

**Comment by yarikoptic** [comment]
I would urge to delay this RF until later, when we actually have solid idea of what is what, and soon to release the beast. Renaming now IMHO wouldn't solve anything but will be an additional cause for conflicts etc with 0.11.x.

**Comment by mih** [comment]
This is not about doing it, but how to do it. I expect this process to be very slow (years). I dont think we can achieve this via rename, but we will axtually have to develop the implementations that fit the concept. The issue is mostly about where to put them, when they are done.

**Comment by kyleam** [comment]
Most of the proposed structure makes sense to me, but I couldn't convince myself that `metadata/` is special.  Couldn't all of the metadata commands be considered "local"?

**Comment by mih** [comment]
I agree.

**Comment by mih** [comment]
I think this issue served its purpose and does not need to stay open for the duration of the process.
