### ISSUE TITLE
RST changelog conversion broken

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3194]
If one would run `make update-changelog` the result would not pass a doc build on travis: 

```
Warning, treated as error:
/home/travis/build/datalad/datalad/docs/source/changelog.rst::Anonymous hyperlink mismatch: 2 references but 0 targets.
See "backrefs" attribute for IDs.
```
https://travis-ci.org/datalad/datalad/jobs/501145688

The bug is already in master, the RST changelog was last updated 4 months ago.

**Comment by yarikoptic** [comment]
Should be used/triggered while building docs, not as independent to do, I guess

**Comment by mih** [comment]
This has been addressed a long time ago.
