### ISSUE TITLE
Test failure due to version string "0.12.0rc1"

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3198]
0.12.0rc1 release broke test assumptions, or was a mistake. @yarikoptic please clarify whether this test can simply be deleted? It did not show up before the merge, and failure only after a merge seems not useful.

```
======================================================================
FAIL: datalad.tests.test_version.test__version__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/test_version.py", line 69, in test__version__
    assert_greater(lv_changelog_version, lv__version__)
AssertionError: LooseVersion ('0.12.0rc1') not greater than LooseVersion ('0.12.0rc1.dev1')
```

#3197

**Comment by kyleam** [comment]
My uninformed guess is that the test (or rather its author, @yarikoptic) wants something like 2606c7697 (Show must go on, 2019-02-19) to come right after a release.  So this fixes it:

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index fff95b2e8..9f623ec85 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -10,6 +10,22 @@ We would recommend to consult log of the
 [DataLad git repository](http://github.com/datalad/datalad) for more details.
 
 
+## 0.12.0rc2 (??? ??, 2019) -- will be better than ever
+
+bet we will fix some bugs and make a world even a better place.
+
+### Major refactoring and deprecations
+
+- hopefully none
+
+### Fixes
+
+?
+
+### Enhancements and new features
+
+?
+
 ## 0.12.0rc1 (Mar 03, 2019) -- to boldly go ...
 
 ### Major refactoring and deprecations
```

I don't like the idea of spawning entries for each rc (discussed already a bit [here]), or at least I'd like to collapse them once the final release is made.  At any rate, I think the above diff is what that test is after.

[here]: https://github.com/datalad/datalad/pull/3193#issuecomment-469054099

**Comment by yarikoptic** [comment]
Was fixed in https://github.com/datalad/datalad/pull/3207, sorry I have missed the issue

**Comment by kyleam** [comment]
Thanks for the fix!
