### ISSUE TITLE
add's --to-annex is unreachable

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3204]
I was looking at command-line options that use `dest=` to see if there are any other options that flip like `--nosave -> save` and thus have the same problem described in #3203.  I didn't spot any, but I did get confused by `add`s `--to-annex`:

https://github.com/datalad/datalad/blob/c3fe0350b12c2001b24d400a0b3c2b4a5f156013/datalad/distribution/add.py#L150-L159

It reuses `--to-git`s variable by design: 49f296ba7 (ENH: add --to-annex (reuse to_git Python interface though) to force adding to annex, 2017-07-26).  There is a [comment] in the corresponding PR that said "seems to work", but it doesn't work now (c3fe0350b):

```
% datalad add --to-annex blah
[ERROR  ] unknown argument: --to-annex
usage: datalad add [-h] [-d PATH] [--to-git] [--nosave] [-m MESSAGE]
                   [-F MESSAGE_FILE] [-r] [--recursion-limit LEVELS] [-S]
                   [--git-opts STRING] [--annex-opts STRING]
                   [--annex-add-opts STRING] [-J NJOBS]
                   PATH [PATH ...]
```

[comment]: https://github.com/datalad/datalad/pull/1652#issuecomment-318089627

**Comment by mih** [comment]
Tangentially related issue: I think we should align ourselves more with git-annex re this kind of options (we can still have dedicated commandline opts to trigger them). In particular, I think we should support this kind of call:

`datalad -c annex.largefiles=... add/rev-save`

ATM `rev-save` still has `--to-git` that does too complicated things, but it should really do `annex.largfiles=nothing`.

At the core, this would mean to make `AnnexRepo.add` call git-annex with a properly adjusted configuration. That piece of code is used both by -core and -revolution.

**Comment by kyleam** [comment]
> I think we should align ourselves more with git-annex re this kind of options (we can still have dedicated commandline opts to trigger them). In particular, I think we should support this kind of call:
>
> `datalad -c annex.largefiles=... add/rev-save`

From a UI perspective I like the consistency.  My one reservation is that the consistency could cause confusion: Would users see that and think "oh, I can pass along `-c annex.*` options to any underlying git annex command"?

**Comment by mih** [comment]
I see it as "specifying ad-hoc configuration that also (and that is the new part) affect underlying calls (plural) to git and git-annex", but not additional options for a particular call. The latter we tried to achieve with the old `annex-opts` -- and failed, due to the lack of precise association of options with specific calls. Resorting/restricting to configuration items should not have this issue.

**Comment by kyleam** [comment]
This isn't worth keeping open now that `add` is obsolete and the 0.12.0 release is near.
