### ISSUE TITLE
run/rerun: an option to NOT unlock outputs

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3206]
Use case is that `output` is quite heavy (GBs), already exists, but will be rewritten not inplace, so it would be perfectly fine to just keep it locked - files will get removed and new ones added.  So to not wait for eternity for the `unlock` to happen it would be convenient to specify to not bother unlocking outputs.  Even if that setting is not stored in the `run` record command should be able to `rerun`.
May be the solution could be joined with #3081 by introducing `--unlock` option which would default to `outputs`, but could be a combination of `intputs` and `outputs` (e.g. comma separated)?

**Comment by mih** [comment]
I was suffering from this too. I think we have an oportunity now to use `status` to make things more clever.

We get the results from get() hence every single input file. We can now resolve the output specification using status(). Only files in the intersection of the two sets need to be unlocked. Everything else can be os.remove()'d. Whatever doesn't match status() does not exist to begin with.

This avoids adding another argument.

**Comment by yarikoptic** [comment]
rm'ing outputs (which aren't inputs) might have undesired effects of wiping out outputs which aren't (re)created, and run recording changes as they were removed by the ran command.
My recent use case is running fmriprep on a subset of subjects.  So inputs was the original bids dataset, and outputs - well, the entirety of the fmriprep output, which already contained a number subjects.  Lazy/busy user me, would not specify all outputs one by one (in many cases it would not be even feasible if outputs are not having one clear subdirectory) - I just specify the entire output dataset.  I know that outputs would not chock on already committed previously outputs - they are either directly in git, or would be created a new, or rm'ed first by the script.  So, most logical option for me is to disable unlocking of the outputs.

In the light of the multi-stage proposal (#3162) we could allow to explicitly list or disable (with `-`), and may be even later on to enable (with `+`) some optional operations (procedures?).  E.g. in this case I would have specified `--stages=-unlock` or more explicit `--stages=-unlock-outputs`, if such a stage (`unlock` or `unlock-outputs`) was defined.  In some cases, to not waste time, I might say `--stages=-get-inputs` if I know that inputs are already present, and so on.

**Comment by yarikoptic** [comment]
and ran into this while preparing what I thought would be a smooth demo... until I got to this issue again - output files to reproduce are not available to be obtained, and even if they were, `rerun` doesn't get outputs, so cannot unlock what is not there, and kaboom!
```
$> datalad install -r https://github.com/yarikoptic/demo-cifar-preproc
[INFO   ] Cloning https://github.com/yarikoptic/demo-cifar-preproc [1 other candidates] into '/tmp/demo-cifar-preproc' 
[INFO   ]   Remote origin not usable by git-annex; setting annex-ignore                                                          
install(ok): /tmp/demo-cifar-preproc (dataset)
[INFO   ] Installing <Dataset path=/tmp/demo-cifar-preproc> recursively 
[INFO   ] Cloning https://github.com/yarikoptic/demo-cifar-preproc/data/rawdata [2 other candidates] into '/tmp/demo-cifar-preproc/data/rawdata' 
action summary:                                                                                                                  
  install (ok: 2)

$> cd demo-cifar-preproc 
README.md  code/  data/  environments/

$> datalad rerun run-preproc2
[INFO   ] Making sure inputs are available (this may take some time) 
get(ok): environments/preproc.simg (file) [from web...]                                                                          
...
get(ok): data/rawdata/cifar-10-batches-py (directory)
CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'unlock', '--', 'data/preproc2']' failed with exitcode 1
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'unlock', '--', 'data/preproc2'] under '/tmp/demo-cifar-preproc'. Exit code=1. out=unlock data/preproc2/test-100.h5 
failed
unlock data/preproc2/train-100.h5 
failed
 err=  content not present; cannot unlock
  content not present; cannot unlock
git-annex: unlock: 2 failed

unlock data/preproc2/test-100.h5 
failed
unlock data/preproc2/train-100.h5 
failed
  content not present; cannot unlock
  content not present; cannot unlock
git-annex: unlock: 2 failed
```

not yet sure what to do for the workaround

**Comment by kyleam** [comment]
[ The install command fails on my end, so I haven't tried to run it but... ]

While not unlocking outputs would allow you to work around this issue, it looks like a bug in `_unlock_or_remove`s logic: it doesn't consider that the path could be a directory.

So an immediate workaround would (hopefully) be to (1) explicitly list the output paths or (2) drop --output and let the automatic output detection happen on the initial run.

**Comment by yarikoptic** [comment]
keep running into it... just need to not use `run` in the short run ;-)

**Comment by yarikoptic** [comment]
and again.  I have ~1400 .feat directories already, need to produce more for the missing ones (~300 more), so need to run something like

```shell
for f in *.fsf; do ff=${f/.fsf/.feat}; [ -e $ff ] || echo $f; done| xargs parallel -j 2  ../../.datalad/environments/fslanal/run feat -- 
```

As output I want to just say `--output '*.feat'` since have no time (and might exhaust command line max size) to get those 400 `--output` entries.  But I cannot wait for the outputs to get unlocked.

**Comment by yarikoptic** [comment]
The "unlock" stage disabling would be also handy for `rerun`.  ATM `rerun` unlocks all outputs as found in the initial `run`.  But I often rerun some elder commit to just "add" more results based on new files added to the dataset (so my initial command checks first either results are available already like in the example above). So unlocking of prior outputs is really not necessary and just wastes time.  Disabling unlocking could also be taken as additional measure to prevent some incorrect execution (since command would fail it decides to write to some files which it was not supposed to).

**Comment by yarikoptic** [comment]
just ran into this use case of `rerun` again.  If a script is to incrementally populate a dataset, it is not worthwhile to unlock what was added in the original `run` (which was not even a good citizen and had `outputs` empty).  Meanwhile adjusting the title
