### ISSUE TITLE
add priorities for credentials

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#322]
we need "catch all" credentials, e.g. some default S3 creds which could be used for palpating s3 http urls etc.  ATM we would need to specify one for each one of them... may be we should even allow for some a sweep/list of credentials to be tried? (kinda a security hazard imho)

**Comment by yarikoptic** [comment]
once again ran into it.  I guess it should be implemented via adding explicit priority field.  E.g. by default all could have priority 0, and we sort them in increasing order allowing negative numbers ;)

**Comment by mih** [comment]
https://github.com/datalad/datalad-next provides a credential system that can provided sorted query results based on arbitrary criteria. Comnands in that extension implement a 'select last updated matching credential' as one example of a sorting approach. Any datalad feature could immediately start using explicit priorities, if that is actually desirable.
