### ISSUE TITLE
Should we disambiguate semantic of having `-d PATH` specification?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3230]
With revolution upon/within us, I wondered if we could simplify the semantic of having `-d` specification of the dataset in the commands.  At the moment I see it mixing-in at least 2 possible semantics:

### `#1`. How to treat relative paths relative to the top of the specified dataset

The rationale for this is the consistency with Python use of all those as methods of a dataset instance.

<details>
<summary>peculiarity of `-d .`</summary>

Note that `-d` should point to the top directory of the dataset, so `-d .` does not mean "this dataset", and thus all of the following commands fail, even if we prepend relative path with `./` (which I apparently incorrectly) thought we coded for to describe that it is relative to cwd, not top of the dataset:

```shell
(git-annex)hopa:/tmp/superds[master]
$> git status
On branch master
nothing to commit, working tree clean

$> mkdir subdir

$> cd subdir

$> touch 123

$> datalad add -d . 123
[WARNING] path not part of the reference dataset at /tmp/superds/subdir [add(/tmp/superds/subdir/123)] 
add(impossible): 123 (file) [path not part of the reference dataset at /tmp/superds/subdir]

$> datalad add -d . ./123
[WARNING] path not part of the reference dataset at /tmp/superds/subdir [add(/tmp/superds/subdir/123)] 
add(impossible): 123 (file) [path not part of the reference dataset at /tmp/superds/subdir]

$> datalad rev-save -d . ./123   
[ERROR  ] No installed dataset found at /tmp/superds/subdir. [dataset.py:require_dataset:612] (ValueError)
```
</details>

But then many commands also add additional semantic beyond "how to treat relative paths":

### `#2`. either to consider (only new?) paths to be a part of the dataset

So `install -d . URL` adds installed dataset, and `install URL` doesn't. 
Similarly `create` and even `rev-create` (https://github.com/datalad/datalad-revolution/issues/97) would not add new subdataset.
I no longer remember what was (if any) the rationale for not adding installed or created subdatasets (without -d) right away.  Note that with aforementioned `-d .` gotcha it is actually quite inconvenient to add subdatasets in deep subdirectories within subdatasets.

Because of this confusion I didn't even reply right away to @kyleam suggestion for a fix in 
https://github.com/datalad/datalad-container/issues/72#issuecomment-472925070 since I am not sure what effect that would have, e.g. may be then making behavior different in the top directory of the dataset from how it would behave in subdirectory.

I am not sure if there is yet another specific to command semantic encoded, as I have summarized the 2nd one based on my short-term memory and there might be more?

### Suggestion

But I wonder if we could get rid of the `#2`, command specific behavior, always figure out the dataset we are in, and behave as it was specified, besides the `#1` aspect of how to treat the provided paths?

**Comment by kyleam** [comment]
Related to #2589.

> even if we prepend relative path with ./ (which I apparently incorrectly) thought we coded for to describe that it is relative to cwd, not top of the dataset:

You can see that behavior in action with the Python example at #2589.  You can see it on the command-line too if you work around what you noted about `-d.` not resolving to the top-level directory of the repo.

Without "./", the file is taken relative to the specified dataset:

```
% d=$(mktemp -dt dl-3230-XXX) && cd $d
% datalad create
% mkdir subdir && cd subdir && touch foo
% git rev-parse --show-cdup
../
% datalad add -d../ foo
% (cd ../ && git status -uall)
On branch master
Untracked files:
        subdir/foo

nothing added to commit but untracked files present
```

"foo" doesn't exist in the top-level, so adding it fails (though I was surprised about not getting any message about "foo" not existing).

With "./", it is added:

```
% git rev-parse --show-cdup
../
% datalad add -d../ ./foo
add(ok): subdir/foo (file)
save(ok): /tmp/dl-3230-3Sb (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
% (cd ../ && git status -uall)
On branch master
nothing to commit, working tree clean
```

**Comment by yarikoptic** [comment]
Oh right, I mixed two issues into one. So the prefixing with ./ had an effect - good. The main issue remains

**Comment by mih** [comment]
I don't comprehend the full extend of the implications yet, but I can report that one motive for -revolution was to stop making any assumptions of what a caller probably would have wanted to say and stick to the arguments at their face value.

Rational: it is typically easy to construct use cases where some "decoding" of semantics in the absence of proof is perfectly straightforward, but it is very hard to confirm that it doesnt lead to mindboggling combinatorics elsewhere.

**Comment by yarikoptic** [comment]
But that is exactly my point - a face value of having -d isn't clear ATM, and we do have combinations of effects, which vary across commands. And that is why it is not even clear what implications would be.

**Comment by bpoldrack** [comment]
Actually, I think it is clear what `-d`is. It is: "operate on THIS dataset". The only inconsistency I see is `add`. `create` and `install` behave perfectly fine in that regard, since those commands do not operate on any dataset by default (hence not adding), but bring one into existence. If told to operate on an existing ds, those commands create a subdataset. I find that perfectly fine and reasonable.

`add` is a different story, though. IIRC it has a similar distinction although it would operate on the same dataset both ways. If we are to keep add, then it needs to be reworked.

Path handling is admittedly confusing. And we should iron that out at some point. I agree, but I don't have a solution ATM.

**Comment by yarikoptic** [comment]
> Actually, I think it is clear what `-d`is. It is: "operate on THIS dataset".

There is to it if you do specify `-d` + the relative paths resolution, and possibly restrict operation (e.g. if full or relative path points outside of it), or extend it (`add -d . subds/file` would add/save both subds and ds, whenever without `-d` it would add/save only within ds)

> since those commands do not operate on any dataset by default 

Not exactly true. If you don't specify `-d` the semantic is "operate on current dataset or a dataset, to which the specified path belongs".  That is how all commands, including `add` (on files/directories) operate (you don't need `-d` to add files), even `install subds` installs that subds of the ds you are in. And indeed thus `add`, `create`, and `install` are inconsistent from the rest in adding this additional semantic of "do not care about (sub)datasets as related to current one, even if explicitly specified on the command line".  
So it is especially strange is the fact that `add subds` doesn't add that subds (even though explicitly specified) without `-d` but goes into subds and adds within it (#3232).

**Comment by bpoldrack** [comment]
WRT `add` we have no disagreement. 

> Not exactly true. If you don't specify -d the semantic is "operate on current dataset or a dataset, to which the specified path belongs". That is how all commands, including add (on files/directories) operate (you don't need -d to add files), even install subds installs that subds of the ds you are in. 

Yes. I don't see a contradiction to what I wrote is the meaning of using `-d`. What you just described is the default behavior of those commands. I still don't see how `-d` deviates from my description of what `-d` means. And `install exisiting/path` is different of course. But the difference is not `-d` here. In that case it is not "creating" something new. So it behaves the way you described as all commands' default. Looks fine to me.

> adding this additional semantic of "do not care about (sub)datasets as related to current one, even if explicitly specified on the command line".

Hm. Not clear to me. What do you mean? If explicitly specified they do. Isn't that what you wrote about `install`?
> So install -d . URL adds installed dataset, and install URL doesn't.

`install something-new` : just install, don't care about "current".
`install -d . something-new` : explicitly specified to care about `.` so - add it.
Same for create.

I have a feeling you look at `add` as the model. I think it's the outlier. Take it out (like revolution does) and things look consistent to me. So, `add` is the thing to either throw away or rethink entirely. (I agree with revolution and do think we don't need it at all)

**Comment by mih** [comment]
I have spent some thought on the following move (which also results in a disambiguation):

1. Giving `--dataset` does not alter the actual behavior of a command in any way, it is only used a) to turn (non-explicit) relative paths into absolute paths, and b) to identify a dataset to operate on (as a precise instruction, not a random pointer somewhere inside a dataset (to keep the semantics of the Python API).

2. Previous additional behavior like "install/create and register in a super" is discontinued and left for an explicit call to `rev-save` in the context and scope of the dataset(-level) that should be saved.

**Comment by yarikoptic** [comment]
> 1. Giving `--dataset` does not alter the actual behavior of a command in any way, 

In my PoV it does -- (original `#2`) it results in adding subdatasets whenever they aren't added if there is no `-d`.

> ... and b) to identify a dataset to operate on (as a precise instruction, not a random pointer somewhere inside a dataset (to keep the semantics of the Python API).

But overall -- so you agree that it is 2 aspects which brought together.
Re "identify dataset" -- More than that, at least with the current `add` and `rev-create` ( and not exactly that. It is more of "identifies the scope" or "identifies datasets" (not a single dataset) to operate on. E.g. `-d superds subds/file` results in adding/saving not only within `subds` but also saving adjusted state within `superds` .

Re `save` vs `status` scoping - makes sense, but not sure how relates to having or not `-d`.

> Rational for the discontinuation of the "called on a dataset" behavior switch ...

here I got a bit lost/confused on either you are agreeing for the need to change or not. Sorry, I might just be slow

**Comment by yarikoptic** [comment]
>> Wrt the latter issue, I don't think there will be a single standard rule, as we have to live with inherently conflicting behavior. Example: I run `rev-save` in a subdirectory of an unspecified dataset. "Clearly" I want to save anything underneath this directory, but not everything throughout the entire dataset. Same setup different command: `rev-status`: "Clearly" I want to have `rev-status` behave very similar to `git status`, which is to report the status of the entire dataset, regardless of the PWD.

> Re `save` vs `status` scoping - makes sense, but not sure how relates to having or not `-d`.

Actually - "hold on" ;)   If I am just running `rev-save` without restricting by paths, I would expect it to save changes to the entire dataset (similar how `git commit` would do).  And if I want to save this directory only, I specify the `.` path to restrict the scope.  Exactly the same way `datalad|git status` behaves.  I do not see why there could be no "standard rule".

**Comment by yarikoptic** [comment]
re @bpoldrack 

> WRT add we have no disagreement.

It seems we talked a bit over each other's head, may be due to my insufficient quoting of the original reply.
My point was that in all commands we assume "current dataset we are in" to be the dataset we are working on, unless the path is outside the dataset (`-d` does restrict commands to not go outside of that dataset though). And you are describing the current behavior that "install" and "create" do not operate on any dataset (unless `-d`), and that is what I am "questioning" by the discussion here. It all pretty much boils down to how we assume and specify/restrict the scope of commands (hence relates to @mih 's comments), and I feel that there is discrepancy between commands, like the one you stated (`create`, `install` not operating on any dataset by default).

**Comment by bpoldrack** [comment]
@yarikoptic 
> It seems we talked a bit over each other's head

Yes. I think I got your point now. In my words: You see an inconsistency in `install/create` *without `-d` as compared to other commands, since they then don't make a difference on whether or not PWD is within a ds. I don't find that confusing, but I see how it's not perfect ;-)


Re your very first answer to @mih:

> > 1. Giving --dataset does not alter the actual behavior of a command in any way,

> In my PoV it does -- (original #2) it results in adding subdatasets whenever they aren't added if there is no -d.
> ..
> here I got a bit lost/confused on either you are agreeing for the need to change or not. 

I guess now you guys are talking over each other's head. ;-) As I read it, @mih suggests a change. 1. and 2. are outlining how envisions the future, not describing the current state.

**Comment by mih** [comment]
FTR: I have lost track of who wants what, and what is a description of a goal rather that the status quo. Let's talk about this in a conference call? Ideally with a concrete proposal.

**Comment by mih** [comment]
Registering one more critical case here: We need to identify a subdataset record in a super vs (the content of) a subdataset itself -- in a way that also works in the Python API. The -revolution commands try to implement:

- `-d super sub` -- the `sub` subdataset record in `super`
- `-d super sub/` -- the content of sub, even though it is adressed through `super` (like rsync distinguished between a directory vs its content)

Alternatively a subdataset could be addressed standalone (with `-d`), but that would lead to ugly patterns in Python code (we need to get a subdataset object first, and then call its method -- doable, but a fundamental change, and has nasty implications, like having to know what subdatasets exists)

**Comment by yarikoptic** [comment]
> FTR: I have lost track of who wants what, and what is a description of a goal rather that the status quo. Let's talk about this in a conference call? Ideally with a concrete proposal.

+1  I have stopped replying since wanted to get a clear(er) picture as well.  Whatever we decide, the first step of the "proposal" in either case should be a description, which would makes it clear of what is the effect(s) having `-d` specified or not.

I am not sure about `sub` vs `sub/`, since its utility is for a limited set of specifications (e.g. a list of directories only at a specific depth) or requires explicit handling to guarantee having `/`, and thus might complicate scripting, where people would need to assure that there is no/is trailing `/` specified.

I still wonder if default context of operation should just be shifted to current dataset (if there is any) as the dataset to operate on, and then `-r` flag would explicitly tell either we are interested in the subdatasets (content or whatever). The gotcha is with outside paths (e.g. `../friendlyds` or by full path). ATM without `-d` the "context" just entirely switches to those (sub or outside) datasets, and thus it works just fine, but looses "connection" to the dataset where command was launched. Yes - could be considered a feature, but so far it just kept biting me, and hence me whining.

**Comment by yarikoptic** [comment]
according to @mih it is resolved by https://github.com/datalad/datalad/issues/3282
