### ISSUE TITLE
Improve (automated) commit messages

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3236]
ATM automated commit messages ("Added content", "Recorded changes", ...) are useless.
Some (if not majority) of the commands, e.g. `*create` do not even allow to have commit message specified.  I wonder if we could improve upon that.

In many cases the intention/result of the command is clear. e.g. if I `create .../subds`, I think it would be better to commit "Added subdataset subds" and "Recorded changes caused by "Added subdataset subds'".  If there is multiple objects of action, they could be quantified (`X files, Y datasets`, etc).  And I think it should be possible if we collect a list of actions which were taken by the command before `*save` was invoked.

<details>
<summary>I do something like that in the (good, khe khe) and (definetely) old crawler:</summary>

```
    [DATALAD] Added files from extracted archives
    
    Files processed: 6202
     skipped: 4
     +annex: 6168
    Branches merged: incoming->incoming-processed

commit c6259378478bbcc634b3295b0c710886b9eecb01 (origin/incoming, synced/incoming, incoming)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Tue May 16 23:20:05 2017 -0400

    [DATALAD] Updated git/annex from a remote location
    
    URLs processed: 34
    Files processed: 35
     skipped: 34
     +git: 1
```
</details>

Related: 
- https://github.com/datalad/datalad-revolution/pull/71 - for non-automated/user input messages

**Comment by mih** [comment]
I do not believe that adding information to commit messages that can be readily extracted from the rest of the commit itself actually improves the commit messages. What we are lacking is the ability to say "why", not "what" or "how". I think we need https://github.com/datalad/datalad-revolution/pull/71

And for that one, we need an improved Runner that actually permits us from behaving like `git commit` in asking for human input.

**Comment by yarikoptic** [comment]
For "why", indeed the user is the only source of such information.  But "why" usually is described in the extended description, not in the summary of the commit.

But ATM even "what" and "how" - which is what typically summarized in the summary line of the commit message - we do have an idea.  "what" is primarily instructed by the top level invoked command.

**Comment by yarikoptic** [comment]
and some messages are now a complete lie in case of `add`. `save` and `rev-save`'s messages at least do not lie, although as meaningful as having no message (sure thing there were some changes which were recorded -- we do not allow empty commits)

```shell
$> git show
commit 3648ea509bc3d6a90cc52b4ef7899a0bd256d0ee (HEAD -> master)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Thu Mar 28 10:46:23 2019 -0400

    [DATALAD] added content

diff --git a/123 b/123
index a0c8c4c..94ebaf9 100644
--- a/123
+++ b/123
@@ -1,5 +1,4 @@
 1
 2
-edit1
 3
```

**Comment by yarikoptic** [comment]
as a quick workaround I have succeeded by disabling allowing empty commit messages and adding `--edit` to our commit invocation while providing `GIT_EDITOR=gvim` to start editor in a new GUI window
```shell
--- a/datalad/support/gitrepo.py
+++ b/datalad/support/gitrepo.py
@@ -1299,12 +1299,12 @@ class GitRepo(RepoInterface, metaclass=Flyweight):
 
         options = options or []
 
-        if not msg:
-            if options:
-                if "--allow-empty-message" not in options:
-                        options.append("--allow-empty-message")
-            else:
-                options = ["--allow-empty-message"]
+        # if not msg:
+        #     if options:
+        #         if "--allow-empty-message" not in options:
+        #                 options.append("--allow-empty-message")
+        #     else:
+        #         options = ["--allow-empty-message"]
 
         if date:
             options += ["--date", date]
@@ -1326,7 +1326,7 @@ class GitRepo(RepoInterface, metaclass=Flyweight):
         # Therefore, for now always use direct call.
         # TODO: Figure out, what exactly is going on with gitpython here
 
-        cmd = ['git', 'commit'] + (["-m", msg if msg else ""])
+        cmd = ['git', 'commit'] + (["--edit", "-m", msg if msg else ""])
         if options:
             cmd.extend(options)
         lgr.debug("Committing via direct call of git: %s" % cmd)
```

and running `GIT_EDITOR=gvim datalad save`.
Obviously if `-m` is provided to the outmost invocation (i.e. `save` here), I don't think `--edit` should be added...
