### ISSUE TITLE
New helper to deal with submodules in handles

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#324]
FTR: If a handle has submodules and git annex is used to get files in the submodule, a sub-sequent `git submodule deinit` will not work anymore. Instead the submodule and all its content will need to br `rm -rf`ed manually. We should have a helper that takes care of this.

**Comment by hanke** [comment]
As soon as I get to it I'll write up how I think submodules should be handled in a more comprehensive document.

**Comment by yarikoptic** [comment]
On Mon, 21 Dec 2015, Michael Hanke wrote:

> As soon as I get to it I'll write up how I think submodules should be handled
> in a more comprehensive document.

would be valuable indeed since I am still so far away from any
submodules handling in my battle ;)

**Comment by hanke** [comment]
This issues has further implications. We might night more comprehensive support for submodules. Issues:

- [ ] deinit submodules with annexes
- [ ] adjust URLs for submodules on publication. Typical scenario would be that a submodule is a handle in the same collection, so upon publication that should all get updated URLs to remain accessible

**Comment by bpoldrack** [comment]
This issue currently isn't one on its own anymore, right?

**Comment by hanke** [comment]
I will close this. We now have a dedicated helper for adjusting submodule URLs. The rest is the scope of uninstall().
