### ISSUE TITLE
--explicit prevents run from committing sidecar files

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#3253]
When `run` is called with an `--output` that is more specific than just `.`, using `--sidecar` as well as `--explicit` will result in an untracked sidecar file.
Since the sidecar file is determined by `run` itself, it doesn't make sense to me, to expect the user to specify it as an output (only a rather unspecific `.datalad/runinfo` would be possible to specify, which is running against the intention of `--explicit`).

I have a quick fix already, but will come up with a proper test and possibly a nicer solution. Filing just the issue for now, in case somebody else runs into it. Just too late tonight to finish it. ;-)

**Comment by kyleam** [comment]
> Since the sidecar file is determined by `run` itself, it doesn't make sense to me, to expect the user to specify it as an output (

No, just an oversight.

> I have a quick fix already, but will come up with a proper test and possibly a nicer solution.

Thanks.

**Comment by bpoldrack** [comment]
Fix failed to link the issue. However, this is not happening anymore.
