### ISSUE TITLE
FOI: profiling on make_studyforrest_mockup

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3261]
Following @adelavega 's recipe from https://github.com/bids-standard/pybids/pull/411#issuecomment-468948473 here is what I got for 
```python
from datalad.tests.utils_testdatasets import make_studyforrest_mockup
 
import cProfile
cProfile.run('make_studyforrest_mockup("/tmp/forrest")', "/tmp/forrest.gprof")

# gprof2dot -f pstats restats | dot -Tpng -o output.png
```
ran on 0.12.0rc2-76-g6ba6d53b
![forrest](https://user-images.githubusercontent.com/39889/54853454-4cf6f780-4cc6-11e9-9815-474dc05d7f14.png)

yet to digest it fully, but
- ~90% of time we are spending running external commands (which is good I guess, the more the better - ie. we do not waste cpu ourselves)
- use of `generator_func` complicates things up, e.g. from diagram alone it is not clear what eats up 25.84% of total time from 51.83% taken by `clone.__call__`.
- `git config` calls seems to take 17.72% (!) of the total run time.

**Comment by adelavega** [comment]
Nice graph ;)

**Comment by yarikoptic** [comment]
thanks ;)

**Comment by mih** [comment]
This is very useful! Trying this out now with status().

I think its ok to close this now.
