### ISSUE TITLE
OPT/RF Runner

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3262]
#3261 shows that in some use-cases we do spend a lot of time in Runner executing external commands. Unfortunately we do not have estimate how it relates to actual run time of those external commands, but observing low CPU and no `D` state for invoked git/git-annex commands I would suspect that the way we invoke those commands via Popen is suboptimal, probably blocking/waiting/sleeping somewhere.

Also Runner grew into a monster, as many of you have already stated.  I think it would be worth to
- identify scenarios where and how it is used (e.g. with or without requiring online processing of output, etc). May be by now some combinations of modes could be dropped, and a few more mode-specific implementations are provided instead
- [ ] see if at least for some (if not all) we could use/implement non-blocking mode of operation, see e.g. https://stackoverflow.com/questions/375427/non-blocking-read-on-a-subprocess-pipe-in-python

**Comment by mih** [comment]
This is also related to https://github.com/datalad/datalad/pull/3101 and https://github.com/datalad/datalad/pull/3101. The solution we decided to aim for in both cases is a dedicated, leaner mode of operation.

**Comment by yarikoptic** [comment]
I think we should just look into new features of python3 and implement a solution to look forward, e.g. demanding python >= 3.5 using asyncio et al. Something along the lines of https://stackoverflow.com/questions/17190221/subprocess-popen-cloning-stdout-and-stderr-both-to-terminal-and-variables/25960956#25960956 .  That example/implementation seems to be flexible to be able to still retain common "Runner" implementation while triggering specific behavior (process stdout or stderr or both) via options to the run.

**Comment by mih** [comment]
We should take a long hard look at http://docs.pyinvoke.org and see what we would need that it doesn't do already (came across it, because fabric uses it, https://github.com/datalad/datalad/issues/3609).

**Comment by yarikoptic** [comment]
looks neat. but isn't it more of a library for building cmdline interfaces (even hash shell completion output/support, nice)?  There is some `.run` (even with "parallel execution ") but that seems to be not really the main target functionality of pyinvoke.  I just wonder (didn't look inside yet) if it doesn't anything beyond just Popen there

**Comment by yarikoptic** [comment]
FWIW -- python-invoke in debian is really outdated (upstream is 1.3.0 in debian we have 0.11) - so online examples might not work.  Filed a bug report.

**Comment by mih** [comment]
#4125 has an alternative runner
