### ISSUE TITLE
Unify interface for "entity" based operations?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3276]
May be there is already an issue - didn't find it upon quick search.  But I bet we already discussed it at least in the context of `create-sibling` vs `siblings create`.  So ATM we have
- `subdatasets`

BUT for other entities we do not have similar "gate" command with sub-actions, while by default just listing the known entities of the kind.  E.g. we have following commands which list different entities
- `containters-list` (from `datalad-container` extension)
- `run-procedure --discover` - to list procedures
- `search --show-keys` - a bit of a stretch here, and if any RF might just need to migrate somehow into `metadata` command probably?

So I wonder if we should look into unifying interface across those, so whenever there is a clear entity which commands operate "on" (`containers`, `procedures`) - there should be a gateway command which would by default just list the known ones (like `siblings` and `subdatasets` do now)

**Comment by mih** [comment]
I will close this question-type issue, as the lack of responses seem to document that there is presently not enough juice to work on this.
