### ISSUE TITLE
Deal with "native" (link file)  submodule on remote sibling when reconfiguring

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3277]
ATM we e.g. just crash to reconfigure remote sibling if it is a submodule which was initiated by `submodule update --init`.

**Comment by mih** [comment]
This issue is describing one of many aspects that require a general overhaul of the `create-sibling` command. This overhaul effort is being tracked by the meta-issue #6149. I am closing this issue here, after having added it to that TODO list.
