### ISSUE TITLE
Code/semantics homogenization of dataset/path argument resolution

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3282]
This is connected to various issues (#3230, #2589, #3242), but is also focused on the flow with which command should process and resolve arguments. We should have a standard, documented way (if possible) to reduce the heterogeneity across commands that contributes to the issues listed above.

Here is a pattern proposal (not a description of the status quo):

### Dataset resolution

Determine which dataset to operate on (if needed). All relevant commands get a `dataset` argument, and we can use `require_dataset()` to get a `ds` Dataset instance. It is important to maintain the pristine `dataset` argument value for path resolution (below), or in case further commands need to be called, so that argument semantics stay constant.
Besides normal dataset path specification like absolute/relative paths, this **could** support special symbols like `^` and/or `^^` to indicate the root of the dataset immediately containing CWD, or the topmost dataset respectively.

### Path argument resolution

The goal is to turn all arguments into absolute paths. The challenge is to make the semantics sensible for both cmdline and Python API.
In the cmdline the CWD is an important and highly visible anchor. Interpretation of nifty things like `--dataset ^^ --path here/below` is relatively clear (the topmost dataset, and $PWD/here/below).

The same things in Python with bound methods: `topmost.cmd('here/below')` is not at all saying the same (rather path relative to the dataset).

We also support `cmd(dataset='^^', path='here/below')`, which could mean any of the those interpretations from my POV.

Proposal:

1. if the `dataset` argument (not the resolved `ds`) is a `Dataset` instance: any relative path argument is interpreted relative to that dataset (this covers the bound-method case).
2. If the `dataset` argument is anything else (`None`, or any path specification, including magic symbols): any relative path is interpreted relative to CWD
3. There is no difference in semantics between "explicit" relative paths (`./here/below`) and relative paths (`here/below`)

**Comment by yarikoptic** [comment]
interoperable agreement achieved despite the lack of the magical pepper liquid.

**Comment by mih** [comment]
Awesome!
