### ISSUE TITLE
Need inode minimizing special remote storage

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3284]
Situation: there is space for 5PB but a quota of only 25M inodes, hence any file smaller than 200MB comes with a (big) penalty. The provider recommends to use [SquashFS](https://en.wikipedia.org/wiki/SquashFS)  to navigate around this limitation. But that is a read-only, prepare once use often kind of thing.

The storage system is SSH-accessible, so theoretically there are large degrees of freedom. The layout at the storage end is not really relevant, so it does not need to be "exported", as access would always be through git-annex (but of course it doesn't hurt to have less assumptions on access patterns).

**Comment by yarikoptic** [comment]
"export"ed special remote, with versioning support (like S3) is probably the leanest it could be and with the best reuse (can be used as a regular file tree).  versioning though is only implemented for S3 ATM AFAIK.

**Comment by mih** [comment]
Replaced by #3327. Forgot that this exists.
