### ISSUE TITLE
unable to create new dataset with 'rev-create'

### ISSUE THREAD

**Issue by loj** [datalad/datalad#3305]
I was following the demo in the cbbs imaging docs for creating a new dataset and did the following:

% datalad rev-create my_raw_dataset
datalad: Unknown command 'rev-create'.

I created a virtual environment using virtualenv and installed datalad with pip.  I'm using datalad version 0.11.4 (`datalad wtf` output attached)

On the datalad website (https://www.datalad.org/for/lazy-folks) and the cbbs imaging docs (http://imaging-docs.cbbs.eu/datamanagement/study_setup/), 'datalad rev-create' is used to create a new dataset. However, docs.datalad.org says 'datalad create' is used to create a dataset, and indeed that allowed me to successfully create the dataset.

Perhaps this is just a matter of updating the information on the datalad website and cbbs imaging docs (or datalad docs), but I wanted to bring the conflicting information to your attention.

% datalad wtf
# WTF
- path: /home/loj/demo
- type: directory
## datalad 
  - full_version: 0.11.4
  - version: 0.11.4
## dependencies 
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:annex: 7.20190219+git191-g2d6a364d4-1~ndall+1
  - cmd:git: 2.20.1
  - cmd:system-git: 2.11.0
  - cmd:system-ssh: 7.4p1
  - git: 2.1.11
  - gitdb: 2.0.5
  - humanize: 0.5.1
  - iso8601: 0.1.12
  - keyring: 19.0.1
  - keyrings.alt: 3.1.1
  - msgpack: 0.6.1
  - requests: 2.21.0
  - six: 1.12.0
  - tqdm: 4.31.1
  - wrapt: 1.11.1
## environment 
  - GIT_PYTHON_GIT_EXECUTABLE: /usr/lib/git-annex.linux/git
  - LANG: en_US.UTF-8
  - LC_ALL: en_US.UTF-8
  - LC_CTYPE: en_US.UTF-8
  - PATH: /home/loj/.venvs/datalad/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/home/loj/.dotfiles/bin
## extentions 
  - container: 
    - description: Containerized environments
    - entrypoints: 
      - datalad_container.containers_add.ContainersAdd: 
        - class: ContainersAdd
        - load_error: None
        - module: datalad_container.containers_add
        - names: 
          - containers-add
          - containers_add
      - datalad_container.containers_list.ContainersList: 
        - class: ContainersList
        - load_error: None
        - module: datalad_container.containers_list
        - names: 
          - containers-list
          - containers_list
      - datalad_container.containers_remove.ContainersRemove: 
        - class: ContainersRemove
        - load_error: None
        - module: datalad_container.containers_remove
        - names: 
          - containers-remove
          - containers_remove
      - datalad_container.containers_run.ContainersRun: 
        - class: ContainersRun
        - load_error: None
        - module: datalad_container.containers_run
        - names: 
          - containers-run
          - containers_run
    - load_error: None
    - module: datalad_container
    - version: 0.3.1
  - hirni: 
    - load_error: The 'pyperclip; extra == "full"' distribution was not found and is required by datalad [__init__.py:resolve:849]
  - neuroimaging: 
    - load_error: The 'pyperclip; extra == "full"' distribution was not found and is required by datalad [__init__.py:resolve:849]
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3(multipartupload)(storageclasses)
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - hook
    - external
  - supported repository versions: 
    - 5
    - 7
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  - version: 7.20190219+git191-g2d6a364d4-1~ndall+1
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - bids: 
    - load_error: The 'pyperclip; extra == "full"' distribution was not found and is required by datalad [__init__.py:resolve:849]
    - module: datalad_neuroimaging.extractors.bids
    - version: None
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - dicom: 
    - load_error: The 'pyperclip; extra == "full"' distribution was not found and is required by datalad [__init__.py:resolve:849]
    - module: datalad_neuroimaging.extractors.dicom
    - version: None
  - exif: 
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: No module named 'PIL' [image.py:<module>:16]
    - module: datalad.metadata.extractors.image
  - nidm: 
    - load_error: The 'pyperclip; extra == "full"' distribution was not found and is required by datalad [__init__.py:resolve:849]
    - module: datalad_neuroimaging.extractors.nidm
    - version: None
  - nifti1: 
    - load_error: The 'pyperclip; extra == "full"' distribution was not found and is required by datalad [__init__.py:resolve:849]
    - module: datalad_neuroimaging.extractors.nifti1
    - version: None
  - xmp: 
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## system 
  - distribution: debian/9.4
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 270
  - name: Linux
  - release: 4.9.0
  - type: posix
  - version: BrandZ virtual linux

**Comment by mih** [comment]
Thanks for the report. This command will be part of the upcoming 0.12 release. This get it, either pip-install `datalad-revolution` or the 0.12 preview release:

```
pip install datalad==0.12.0rc2
```

In your case it may also make sense to git-clone this repository and install the sources themselves via `pip install -e <pathtoclone>`. This would make it straightforward to dive into the sources and also immediately try out modifications.

**Comment by mih** [comment]
There is no `rev-create` anymore (with #3383 merged). Documentation elsewhere needs to be adjusted, but as far as -core is concerned this issue is solved.
