### ISSUE TITLE
testrepo setup does not protect dotfiles against git-annex

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3306]
Older tests tend to use testrepo as if they were DataLad datasets. However, I keep forgetting that they are not, as they are generated without DataLad tooling and make no attempt to even look like actual datasets. Symptoms:

1. They do not have a dataset ID
2. They do not carry the default gitattriutes
    ```
    * annex.backend=MD5E
    **/.git* annex.largefiles=nothing
    ``` 

Now one could argue whether this is a bug or a feature, but in the concrete case of adding a subdataset to a non-dataset, `.gitmodules` ends up being annexed -- which is a problem.
GitRepo.add_submodule() is not committing this change so various places need a fix, but I am not yet sure which approach is best.

A symptom of this problem as the failing tests in                      https://github.com/datalad/datalad/pull/3304: e.g. https://travis-ci.org/datalad/datalad/jobs/517362633#L1781

**Comment by yarikoptic** [comment]
FWIW: Well, they are called "testrepos", not "testdatasets", so it is easy to remember that they lack fancy dataset attributes IMHO.
