### ISSUE TITLE
"Resolver" URL needed

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3308]
The IDs we assign in metadata should not only be unique, but also resolvable. It seems like a good idea to establish a URL under which a resolver for DataLad's IDs (of various kinds) can be reached. What about

`http://i.datalad.org` -- for "index"

alternatively: 'r' for resolve, or 'x' for Xtra-cool.

It should be short, as it will appear in all kinds of places. For comparison:

```
http://i.datalad.org
http://dx.doi.org
```

Once there is an implementation of such a resolver, it sure should also talk https...

**Comment by yarikoptic** [comment]
I found no clear description what `dx` in `dx.doi` standed for, but I guess "Digital indeX"... may be for consistency with `doi` we should have `http://dx.datalad.org` ?

Could you please provide here examples of what exactly would get resolved to what?

**Comment by mih** [comment]
I don't see why we need to be consistent with DOI, not we we would need to assert that this is a *digital* index ;-)

What to resolve:
- datasets (by UUID) to their landing pages
- files (by key) to their content (or rather information on where their content can be found)

The first is a near goal, the second a desirable stretch goal. For now the actual resolving part is irrelevant, I just need a URL prefix.

**Comment by yarikoptic** [comment]
ah, for what collection of datasets we are talking about? 
if the datasets.datalad.org then why not to have it as e.g. `datasets.datalad.org/index` or `datasets-index.datalad.org`?
or some future datasets registry?

**Comment by mih** [comment]
It cannot be bound to a specific dataset, as these URLs will be generated for metadata of any dataset.

**Comment by mih** [comment]
OK, `http://dx.datalad.org` it shall be.
