### ISSUE TITLE
status() needs better caching

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3311]
ATM caching is only done inside the command for the runtime of the command. That clearly does not give the performance gains that could be achieved. With `status()` being a common first step it is worth making this as fast as anyhow possible.

@kyleam do you have pointers on how `git status` caches its results?

 I think caches would be placed in the top-level dataset only and for any subdataset of any depth. Likely caches could *not* be put into each dataset in a hierachy, because doing so would invalidate the `mtime` of their root directory -- which is the only thing that I can think of that would help with status-speedup in the face of untracked/uncommitted changes.

**Comment by kyleam** [comment]
> @kyleam do you have pointers on how `git status` caches its results?

My understanding is that git compares the lstat information stored in
the index with the lstat information for the working tree file to decide
if the file is modified.  On top of that, there is the optional
untracked cache of the index (described in `man git-update-index`),
which can avoid traversing directories entirely.

**Comment by mih** [comment]
I pushed some sketch on how to easily hook persistent caching into the current runtime caching: https://github.com/mih/datalad/tree/enh-statusperf

However, cheap invalidation of such a cache (or parts thereof) is still an unsolved issues, hence that stuff is unusable at this point.

**Comment by mih** [comment]
Closing this issue of mine, acting on the apparent lack of motivation to work on it.
