### ISSUE TITLE
status (and rev-save) treatment of the path is "revolutionary": we need to unify

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3312]
This is largely a follow up to #3230 (the overall mixup of semantics) and complement to #3282 (treatment of relative paths, not the case of absolute path and `None` dataset). I found a peace of mind through us agreeing somewhat (in #3230) on the semantic that specifying a path to a datalad command, without dataset explicitly, switches the context of the operation to that dataset.  That is how I believe many, primarily old, commands still operate (`install`, `get`, `uninstall`, `drop`, `add/save`, ...).  But `status` assumes current dataset as the "context" of operation, and then fails whenever target path is outside:

```shell
$> datalad status /tmp/bmtemp/datalad_temp_bm_FQIGk4/testds10
[ERROR  ] dataset containing given paths is not underneath the reference dataset <Dataset path=/home/yoh/proj/datalad/datalad>: [] [status(/tmp/bmtemp/datalad_temp_bm_FQIGk4/testds10)] 
```
similarly (may be just because of use of `status` inside) for `rev-save`
```shell
$> datalad rev-save /tmp/bmtemp/datalad_temp_bm_FQIGk4/testds10 
[ERROR  ] dataset containing given paths is not underneath the reference dataset <Dataset path=/home/yoh/proj/datalad/datalad>: [] [status(/tmp/bmtemp/datalad_temp_bm_FQIGk4/testds10)] 
```

If we switch to such semantic it would become impossible to `install` a dataset or obtain (`get`) content without specifying on which dataset (i.e. providing `-d`) to operate.

**Comment by mih** [comment]
> If we switch to such semantic it would become impossible to install a dataset or obtain (get) content without specifying on which dataset (i.e. providing -d) to operate.

I cannot follow this conclusion. It is perfectly possible, but PWD needs to be in or above the dataset. Do you have use cases, where this is not the case?

The reason for this change is a massive reduction in complexity of the implementations (no need to to support operations on multiple disjoint trees anymore).

**Comment by mih** [comment]
I think we can close this. There is no general issue anymore, but very likely individual commands are still not in compliance. However, dedicated issue for these cases are more appropriate and this one has served its purpose.
