### ISSUE TITLE
Check coverage with AppVeyor only run

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3313]
As noted by @yarikoptic  in https://github.com/datalad/datalad/pull/3307#discussion_r273562474, the coverage reported by the AppVeyor run is looking wonky.  We should do a run with Travis disabled and see what coverage is reported.

**Comment by kyleam** [comment]
It looks like coverage for **test** files isn't reported for AppVeyor.  That explains the lack of coverage observed in gh-3307 to the degree I care to dig.  Of course it'd be good to know why this happens and how to fix it, but I'm not planning to look into that anytime soon, if ever.

--- 

My statement above is based on the following observations:

  * The AppVeyor-only codecov report for f802738 does report some amount of coverage, so coverage reporting from AppVeyor isn't failing entirely.

    https://codecov.io/gh/datalad/datalad/tree/f80273868482df1b00d8cfb5369eb3270ef233f6

  * The AppVeyor-only codecov report for f802738 doesn't list test files or test directories.  For example, the `datalad/interface/` directory [listing for f802738][0] (again, no contribution from Travis) lacks a test directory while the [listing for 73145b4][1] (a combination of Travis and AppVeyor) has a `tests/`.

  * Outside of tests, I can find code under `on_windows` that is covered.  Here's an [example in annexrepo.py][2].

[0]: https://codecov.io/gh/datalad/datalad/tree/f80273868482df1b00d8cfb5369eb3270ef233f6/datalad/interface
[1]: https://codecov.io/gh/datalad/datalad/tree/73145b49d55fa2fc24139a45df0432a02fa56909/datalad/interface
[2]: https://codecov.io/gh/datalad/datalad/src/f80273868482df1b00d8cfb5369eb3270ef233f6/datalad/support/annexrepo.py#L3293

**Comment by yarikoptic** [comment]
Or just hit me - isn't it because we have those separate runs of nose put collections of tests?

**Comment by kyleam** [comment]
>  isn't it because we have those separate runs of nose put collections of tests?

I don't know if the separate runs are contributing, but I decided that it wasn't the main issue because (1) there seems to be higher coverage elsewhere than I'd expect if the coverage was only reflecting the last run, `datalad.distribution.tests.test_install`, and (2) there is no coverage reported for the test_install.py.

**Comment by yarikoptic** [comment]
you are right!  

new hypothesis being tested - #3317

**Comment by kyleam** [comment]
Looks promising.  Thanks!
