### ISSUE TITLE
DataLad status command

### ISSUE THREAD

**Issue by leej3** [datalad/datalad#3323]
#### What is the problem?
This subcommand is not currently working for me on the command line
#### What steps will reproduce the problem?
In a DataLad repo: `datalad status`
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.11.4 on centos/7.6.1810/Core
(works with install from  master installed with `pip install git+https://github.com/datalad/datalad.git#egg-info=datalad` giving version 0.12.0rc2)

**Comment by kyleam** [comment]
> works with install from master installed with [...]

Right, the `status` subcommand isn't available in 0.11.4.  As mentioned in a [similar issue][0], the current documentation confusingly corresponds to what will be the 0.12 release. 

[0]: https://github.com/datalad/datalad/issues/3305#issuecomment-481230729

**Comment by leej3** [comment]
Aha, ok then. I thought I'd flag it just in case.

**Comment by kyleam** [comment]
> I thought I'd flag it just in case.

Absolutely.  Ideally we should fix this situation with our docs.  Until then (or until 0.12 is released), I think this issue is worth keeping open since others will very likely have the same confusion.

**Comment by mih** [comment]
Release of 0.12 is imminent. Closing.
