### ISSUE TITLE
tarball-base inode-minimizing special remote

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3327]
Use case: HPC-related storage system with inode quotas and the need to stage data on it for HPC/HTC computation (which would talk to the staged data via `git-annex get` requests). For datasets with many small files this quickly becomes prohibitive, even when not using a full repo with an annex, but just a type-directory special remote annex object tree.
In a concrete case, any file <200MB reduces the useable storage quota disproportionately.

Limitations: HPC system often run a really old/stable software stack. In my case Git is version 1.8, for example. So the approach should ideally not use any advanced/non-standard technology. The recommendation by the operators is to prepare a SquashFS image for each computation and stage that. However, SquashFS images are read-only filesystems, so this would imply a one time export, and expensive operations after updating a single file. Dataset size typically varies from several GB up to ~1TB -- connectivity to such systems is usually good, but not *that* good.

Idea: Use an uncompressed tarball on the receiving end as an archive using only a single inode. It seems `tar` is clever enough to not rewrite an archive when adding new content, or deleting references to obsolete content. Essentially, such a tarball would be an ever growing "file system" that contains an annex object tree, hence storage of multiple versions of a file is perfectly possible. The storage system in question is SSH-accessible, so a special-remote implementation would use SSH for transfer, and also to remote-execute `tar` command to test for, inject, or extract content.

@datalad/developers @joeyh Is there already an implementation of such a special-remote that you are aware of? Do you see any show-stoppers?

Thx.

**Comment by yarikoptic** [comment]
Pure tar would probably be really inefficient for addressing individual files later on. May be with some additional index to be able to position to a specific file it would work? If remote is Linux, may be could just be some fuse based overlay on top of something like that and then annex just using that location for regular special remote?

**Comment by mih** [comment]
All those are non-options. I will test read access latency with growing files again, didnt look to bad initially. Do you have suffered from that before?

**Comment by mih** [comment]
Relevant BSC thesis:

**Comment by yarikoptic** [comment]
Suffered from what? If abuse if inodes by for annex - yes, and  I kept advocating to @joeyh finding ways to reduce it since day one of datalad. Recent work on v7 thin and may be some extra (to avoid annexed copy altogether) might eliminate it, at least for consuming use case. But here you seems to be looking for something beyond it - to reduce it for a  remote/backup, not at the point of use, right?

**Comment by mih** [comment]
I am not even talking about the additional inodes used by git-annex. I am talking about having an git-annex accessible storage (container) that does not waste inodes on small files.

Stats example: A typical N=15, three-level GLM analysis of BOLD fMRI with FSL will come at about 35k files, but will only weigh 2.3GB in size (with standard resolution 3T BOLD data). When the storage provider calculates with ~200MB file size (as in my case), storing this result would cost the equivalent of 6.6GB (and this does not include any additional inode for the annex object tree, just actual files).

**Comment by mih** [comment]
Alright, my re-test of the timing confirmed my initial assessment: "not too bad". I tar'ed /usr on my laptop (17GB), and extract files from the start and end of the archive. Examples:

```
% time tar -O -xf usr.tar usr/bin/zlib-flate > /dev/null
tar -O -xf usr.tar usr/bin/zlib-flate > /dev/null  0.61s user 0.38s system 99% cpu 0.994 total

% time tar -O -xf usr.tar usr/share/khelpcenter/plugins/Manpages/man1.desktop > /dev/null
tar -O -xf usr.tar usr/share/khelpcenter/plugins/Manpages/man1.desktop >   0.60s user 0.40s system 99% cpu 1.000 total
```

So 1s access latency is not that bad, really. This should be read-only access of the file, hence parallel access should be doable.

It might be that my OS is doing some clever caching, although the tarfile does not fit in memory (8GB). But even if it is caching that gives this performance, the same caching would also happen on the storage system.

Do you consider that "really inefficient for addressing individual files"? Or am I missing the point?

**Comment by yarikoptic** [comment]
You could flush filesystem cache  and try again.
Even with 1 sec per file - 0.5 sec average, special remote works one key at a time. For 1000 files it is 8 minutes of just waiting access time scrolling through tar over and over again, which could be avoided if there was an index.

**Comment by mih** [comment]
`dar` files have an index and might be an alternative. No practical experience yet.

**Comment by mih** [comment]
Pointers for further research https://stackoverflow.com/questions/429987/compression-formats-with-good-support-for-random-access-within-archives

**Comment by mih** [comment]
Interim conclusion: SquashFS may be, disappointingly, the most suitable solution for a (read-only) access.
