### ISSUE TITLE
XMP metadata extractor needlessly slow

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3328]
ATM it tries to open any file in a dataset. However, the list of possible file types that  could potentially contain XMP metadata is relatively compact. I propose to introduce a configurable list of file extensions that is used to filter out matching file names and only try to open those. 

The same list can also be used to report which file content to obtain, a feature that becomes available with https://github.com/datalad/datalad-revolution/pull/84

Rational: the XMP extractor is a major source of slowness on large datasets that contain a few PDFs and a large number of other files.

**Comment by yarikoptic** [comment]
May be within xmp is some list of extensions?

**Comment by mih** [comment]
> May be within xmp is some list of extensions?

I could not find any comprehensive list of extensions, just lists of file formats. However, I doubt that more throughout checking is worth it. Should any metadata ever be found missing, the match expression could be easily adjusted.
