### ISSUE TITLE
datalad add  lost its progress bars?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3341]
I am running `datalad add -m msg subdirs*` on a heavy (fmriprep output) filetree.  I see that the size of `.git/annex/objects` grows and git-annex is busy, I see that it was invoked with `annex add --json`  but I see no updates of any kind on the screen from `datalad add`

DataLad 0.12.0rc2.dev268

**Comment by kyleam** [comment]
> datalad add  lost its progress bars?

Indeed, it used to have them.  It looks like they were lost in 097173f7f
(RF+ENH: Add generator functions for *Repo.add() as *Repo.add_(),
2018-08-07).

Interestingly, some progress, but no bar, was shown at the above commit.
Progress was lost completely when that series was merged in 2517f6146
(Merge pull request #2749 from mih/rf-generator, 2018-08-15).
2517f6146^ shows a progress bar.  2517f6146^2 shows progress but no bar.

The complete lack of progress is an interaction between #2749 and #2738,
as shown by rebasing 2517f6146^2 onto the first parent before the merge
of #2738, 7a3ead793.  Haven't dug further than that.

**Comment by mih** [comment]
I am closing this one, as 0.12 is coming out ~now, and `save()` (which replaces `add()`) has a nice progress bar.
