### ISSUE TITLE
Bring in metadata command stack from -revolution

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3344]
It fixes a whole slew of bugs, has 98%+ code coverage, works on windows, brings extractors that are cleaner and yield richer metadata. Aggregation is both faster, and more "automatic" due to consistent use of change detection, avoiding the need to keep in mind when to go "incremental" or not.

**Comment by mih** [comment]
As there seem to be no strong feelings, I propose this:

- replace `aggregate_metadata()` with variant from -revolution
- replace minor "plugin" `extract_metadata()` with full command from revolution
- add `query_metadata()` from revolution as a new command
- remove current `metadata()` command without replacement

**Comment by yarikoptic** [comment]
I guess I should finally get time to play with the new beast, but I wonder why `query_metadata` can't be the replacement for `metadata` which I typically used to query metadata ;-)

**Comment by mih** [comment]
> I wonder why query_metadata can't be the replacement for metadata which I typically used to query metadata ;-)

From my POV `query_metadata()` IS the replacement for `metadata()`. However, the two do different things

- `metadata()`: hard to give a comprehensive description of what exactly it does, but essentially it extracts metadata whenever it thinks it is the right thing to do, and queries for aggregated metadata of either the super or a leave or a particular intermediate subdataset, depending on moon phase, so it seems (and it won't tell you which one to emphasize its aura of mystery)
- `query_metadata()`: queries the one given (super)dataset (only) for aggregated metadata (only) 

If you are happy with this replacement, I am happy to. If not, we need to keep the old command implementation around, and additionally load it with required bits from the other old command to still make it perform whatever it did (and of course keep the old tests around too, for all those bits). All new code comes with its own tests.

**Comment by yarikoptic** [comment]
So `query_metadata` is like `clone` to `install` pretty much -- the plumbing command.
I am ok to remove `metadata` but IMHO it should come back from ashes later to provide `query` functionality (without auto extraction etc) with recursion.  Should be clear to describe and also annotate in the changelog, that `metadata` no longer extracts and just returns already aggregated metadata.

**Comment by mih** [comment]
We decided to delay this till after the 0.12 release. For the time being the new metadata stack and a new set of extractors for JSON-LD compliant metadata reports are available from https://github.com/datalad/datalad-metalad
