### ISSUE TITLE
Publish to github with specialremote for data access

### ISSUE THREAD

**Issue by mih** [datalad/datalad#335]
Here is the protocol of setting up a fairly convenient state to aid public data consumption. This protocol assumes that you only push to a server that shall host the data, and do not access the local machine from the server (as this will often not be possible).

Start with regular local annex repo.

```
git init
git annex init "thebeginning"
git annex add .
git commit
```

On the remote server create new Git repo. We use a non-bare repo. Using a bare repo is possible and makes some of the steps below unnecessary. However, having a work tree on the server allows for additional use cases (browsing, etc.)

```
# --shared all is likely what you want, but double-check before running
git init --shared=all
# with modern Git the next is unnecessary and can be replaced with the line afterwards
#git checkout -b ignore
git config receive.denyCurrentBranch updateInstead
mv .git/hooks/post-update.sample .git/hooks/post-update
git update-server-info
```

On the local machine add the new remote. Do it twice, once for push access via SSH, and once for anonymous pull access via HTTP. And push the content.

```
git remote add httpdata HTTPURL/.git
git remote add sshdata SSHURL
git push sshdata git-annex
git push sshdata master
```

Now go back to the remote, and init the annex.

```
# with the modern Git setup the following is not required
#git checkout master
git annex init "public data"
```

Now the remote repo can be enabled as a special remote on the client-side. Once done, sync the state with the remote.

```
git annex initremote datasrc type=git location=HTTPURL/.git autoenable=true
# at this point the http remote is no longer needed
git remote remove httpdata
git fetch sshdata
git annex merge
```

Now the whole thing can be pushed to github. Create a repo on github, and add it as a remote to the local repo. Then push

```
git push github master
git push github git-annex
```

At this point, anybody can clone from github and get a local annex repo with an automatically enabled special remote.

```
git clone https://github.com/SOMETHING mine
git annex init
```

At this point the `datasrc` did not receive any files yet, hence none can be annex-get.  The necessary workflow is as follows. In the original repo do:

```
git annex copy SOMEFILE --to sshdata
git push github git-annex
```

This is sufficient to make a file available and the availability known. In the anonymously cloned repo now do:

```
git pull
git annex get SOMEFILE
```

and it will be downloaded via HTTP from `datasrc`.

The above is verified and works. The rest is anticipation and extrapolation:

Further workflow for maintaining `sshdata`:

```
git annex sync sshdata
```

Further workflow for publishing to github

```
git push github git-annex
git push github master
```

In a collaborative scenario where the gihub repo can be modified from elsewhere, git annex sync would be a better fit.

Further workflow for any anonymous clone:

```
git pull
```

The latter cannot use annex sync, because it would want to push to github without sufficient permissions.

**Comment by yarikoptic** [comment]
yeap.  Thanks for detailing it

When we get to handles thought -- with all the rewrites for datalad's meta (thus no simple pushes of the master containing local urls, or pulls) it would be a bit more evolved ;-)  Without "global" urls it could've been indeed this straightforward

**Comment by hanke** [comment]
So let's think again, where we need which URLs exactly.

**Comment by hanke** [comment]
@bpoldrack @yarikoptic Amazingly, there is no need for an API key to use the github rest API. Here is how to create a repo via python-github:

````
import github as gh
g=gh.Github('myusername', 'mypasswd')
u=g.get_user()
u.create_repo('apitest', description='some fancy', homepage='example.com')
````

This should make `create_publication_target_github` quite a bit simpler than the sshwebserver one...

Cheers to the GitHub folks. Well done!

**Comment by hanke** [comment]
Moreover, it support the creation of oAuth tokens, so there is no need to store passwords....

**Comment by yarikoptic** [comment]
sweet! works even for organizations
```
*In [5]: g = gh.Github('yarikoptic-test', '....')

*In [7]: o = g.get_organization('yarikoptic-test-org')

In [8]: o.create_repo('apitest', description='some fancy', homepage='example.com')
Out[8]: <github.Repository.Repository at 0x7fd7880320d0>
```

as for credentials, indeed could go through oauth!  I guess we should provide some centralized helper for those, otherwise could use meanwhile the Credentials contraption
```
In [1]: from datalad.downloaders.providers import Credential

In [2]: cred = Credential('github', 'user_password', 'https://github.com/')

In [3]: creds = cred()
You need to authenticate with 'github' credentials. https://github.com/ provides information on how to gain access
user: 
You need to authenticate with 'github' credentials. https://github.com/ provides information on how to gain access
password: 

In [4]: print creds
{'password': '...', 'user': 'yarikoptic-test'}
```
which uses keyring module, and ATM with default backend which should theoretically match the system (in my case -- gnome's)

**Comment by Paolopost** [comment]
I tried the configuration reported above without success.

The main issue is that files on "mine" repository (the clone from github) appear to be available (with the 'whereis' command) only on [sshdata] and [public] both not accessible. The files are not indexes by [datasrc] remote. Following the example the files from local are copied on the server only to [sshdata].
Where am I wrong?

I have an additional question. 
It looks like the remote [httpdata] doesn't have any role.

P.S. Do you have a recommendation for a docker to config git server over http? 
        I tried "cirocosta/gitserver-http" but it supports only bare repos.

**Comment by Paolopost** [comment]
An additional detail. On the server the storage is mounted with sshfs.
When I init the annex "public" I received the following notification:

   init public 
  Detected a filesystem without fifo support.
  Disabling ssh connection caching.
  ok

I don't believe it is relevant to the issue mentioned above.

**Comment by mih** [comment]
Finally an update on this issue. With #1237 many things get changed (and hopefully improved). The is one more issue before this is fully resolved. Here is how the current flow is by means of a demo script. It does everything, except for the special remote setup -- which still needs some thought. Anyways, here it is:

````
#!/bin/bash -e

wdir="$(mktemp -d)"
cd $wdir

# fresh dataset
datalad create orig
cd orig
# remotes
# own webserver
datalad --dbg create-sibling \
	-s target1 \
	--existing replace \
	<serverhostname>:public_html/demoannex
# these two are TODO for special remote setup
#	--as-common-datasrc ownserver \
#	--target-url http://<serverhostname>/~user/demoannex/.git \
# github
datalad create-sibling-github \
	--github-login <githubuser> \
	--publish-depends target1 \
	--existing reconfigure \
	--access-protocol ssh \
	demoannex

# some new content
touch probe
datalad add probe

# publish to github, which involves transfer to own server too
datalad publish --to github

# random new user gets the new repo from from github
cd ..
datalad install -s git@github.com:<githubuser>/demoannex.git public
````

**Comment by mih** [comment]
OK, this is done (with the present state of #1237) -- just put back the two commented lines in the script above.
