### ISSUE TITLE
run-procedure does not report the changes

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3352]
```
(git-annex)hopa:~/doc/reviews[master]naturescidata/SDATA-19-00228
$> git show | head -n 1
commit ba6dd671b467cf156c499c9694a30a4c3e2cf077

$> datalad run-procedure cfg_text2git
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) ===== 

$> git diff --stat ba6dd671b467cf156c499c9694a30a4c3e2cf077
 .gitattributes | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

$> datalad --version
datalad 0.12.0rc2.dev288
```
I was expecting it to provide report on `.gitattributes` and `.` being saved, e.g. as `rev-save` does:
```
add(ok): .gitattributes (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
```

**Comment by kyleam** [comment]
[ Related to #2996, I think ]

As far as run-procedure is concerned,  cfg_text2git.py is any random python script.  It calls it as `python datalad/resources/procedures/cfg_text2git.py DATASET`, and cfg_text2git is free to output whatever it wants, which is currently nothing.

**Comment by yarikoptic** [comment]
indeed - just a script... indeed chose to be silent.
I wonder, if with the advance of `datalad status`, it might eventually make sense to e.g. return/render the "diff" record on difference before/after procedure in such cases. Sure thing I would hate to wait for too long if running some banal procedure (like the one here), so I guess it is infeasible, and if to be implemented could be implemented as a generic option to any datalad call (e.g. `datalad --diff CMD ...`).  So meanwhile probably will just close this one
