### ISSUE TITLE
Extractor for `run` provenance

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3359]
In response to #3358 we should use PROV-JSON (https://www.w3.org/Submission/2013/SUBM-prov-json-20130424/) to report on information encoded in `run` records.

Primarily this will be about "derivations" https://www.w3.org/TR/2013/REC-prov-dm-20130430/#term-Derivation and http://www.w3.org/TR/2013/REC-prov-dm-20130430/#term-Generation (we'll have to see how reliably we can distinguish the two).

Technically, we likely want to discover all run-records first, and then look for any file in the described state that was produced by any of the discovered run-records (as the last modification, ideally while ignoring plain renaming). I think this comes down to one `git-log` call per file in question.

The new extractor implementation coming via https://github.com/datalad/datalad-revolution/pull/84 also needs to be adjusted to report potentially annex run-record files as "content needed".

It seems sensible to split the provenance information into two components

1. A list of recorded "activities" that becomes part of the dataset metadata, where each activity is identified by the run-record's commit SHA
2. A "wasGeneratedBy" metadata property that is attached to each relevant file and references the respective activity by its commit SHA identifier.

**Comment by mih** [comment]
We can close this here.

**Comment by yarikoptic** [comment]
ping @kodiweera  on what we chatted about today.
