### ISSUE TITLE
`cfg_text2git` not functional on Windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3360]
This procedure is one of the central use cases behind https://github.com/datalad/datalad/pull/3353, but it is not working on windows, as the git-annex build lacks support of MIME types.

```
bad annex.largefile configuration: Parse failure: "mimetype" not supported; not built with MagicMime support
```

This looks as if any dataset configured in such way would not be operational on Windows.

**Comment by yarikoptic** [comment]
@joeyh I think we have touched briefly on the possibility to empower windows build with libmagic, or was there some showstopper?

**Comment by yarikoptic** [comment]
crap... I feel like we with @joeyh  had a brief "discussion" on why there is difficulty with libmagic for windows, but can't find a trace of it, damn. So I guess you @mih just drink "pure annex" for everything in your windows world?

**Comment by mih** [comment]
I think we should update the procedure to act differently on windows, or provide a different procedure that acts differently. @adswa has outlined a possible approach in https://github.com/datalad-handbook/book/pull/532

**Comment by adswa** [comment]
Windows requires file extensions, correct? Would it make sense to have ``text2git`` define a long list of text file file extensions as ``largefiles=nothing`` if we detect that we are on Windows?

**Comment by mih** [comment]
I don't think we should use the same procedure: While a dataset might be created on linux (and `text2git` working), it will still fail later when used on windows. And when `text2git` does something different on windows initially, it would impair all linux users. A separate procedure would make the separation clear. We might also consider stopping to ship `text2git` entirely, because it makes datasets less portable.

**Comment by yarikoptic** [comment]
I think the best investment of time would be to actually address the problem in the root of it, by providing libmagic build for windows in conda-forge, see https://github.com/conda-forge/file-feedstock/issues/3 (libmagic feedstock is archived but has no reference to migration over to file-feedstock, took time to find it).

**Comment by yarikoptic** [comment]
I would invite you to join fun on https://github.com/nscaife/file-windows/pull/9  where I am trying to cross-build libmagic... if we succeed, I think it it might pave the way to build it on conda-forge

**Comment by mih** [comment]
https://github.com/nscaife/file-windows/pull/9 was merged. Can you briefly summarize the state of the remaining effort, or link to a description? Thx!

**Comment by mih** [comment]
@adswa Maybe we should start a parallel effort to avoid expensive workarounds like the one you had to describe in http://handbook.datalad.org/usecases/ml-analysis.html

We can just implement an `if on_windows` in that procedure that adds an explicit file-extension-based configuration for some common file formats (txt, json, ... at minimum those used in the handbook). While this isn't as clean, it can be implemented without acquiring expertise in building conda packages, and we could ship it with 0.13.4.

**Comment by adswa** [comment]
I agree. I will take a look at it right now, unless you are at it already

**Comment by yarikoptic** [comment]
text2git should be functional with builds from http://datasets.datalad.org/datalad/packages/windows/

**Comment by adswa** [comment]
What would I need to do in order to get a build from there? Install it in addition to what comes together with conda-forge's datalad?

**Comment by adswa** [comment]
Wohoo! I just did a non-crashing text2git configuration :-) That's fantastic! (I installed git-annex on top of what came with conda-forge). Is there a plan to add this specific git-annex version as a dependency?
If so, I can delete all of those "Windows-workarounds" in the DataLad handbook :-) 
If not, I should boldly point to this annex version in the installation instructions.

**Comment by yarikoptic** [comment]
we are yet to establish proper "distribution" of those builds.  But even Joey points to them from https://git-annex.branchable.com/install/Windows/ already.  I am yet to finalize https://github.com/conda-forge/git-annex-feedstock/pull/107 which would provide that build in conda. BUT it them must be installed without `git` or `posix` or `m2-bash` there. Overall -- situation is still 'messy' and I would hold off on ultimate installation instructions for a bit longer, although pointing to http://datasets.datalad.org/datalad/packages/windows/ should be a safe bet since that is where we are planing to share them from (unless here are better ideas, chime in on https://github.com/datalad/git-annex/issues/2)

**Comment by adswa** [comment]
Thx! For now, I've included a note on where to find that build in the handbook.
