### ISSUE TITLE
we might need to reconsider approach for text2git

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3361]
Attn @joeyh 
ATM we are using 
```
* annex.largefiles=(not(mimetype=text/*))
```
but as we have recently discovered ([git-annex bug report](http://git-annex.branchable.com/bugs/manages_to_incorrectly_add_to_annex_instead_of_git_based_on___34__mimetype__34___-_we_cannot_figure_it_out_why/#comment-e0fec0da5dec5241db65324dcba2d3be)), it has stopped working for .json files since `file/libmagic` acquired additional powers to annotate them as `application/json`.

# Possible "proper" solutions

[Discussion on the `file` mailing list](https://mailman.astron.com/pipermail/file/2019-April/000106.html) brought following,
- We might want to consider using instead `encoding` not `type`. So we could then say:
```
* annex.largefiles=(mimeencoding=binary)
```
which is kinda neat IMHO!  But that would require adding support for that to git-annex
- We could (potentially, since there is [a bug in file/libmagic forbidding it](https://bugs.astron.com/view.php?id=77)) use `-k, --keep-going` flag and get all entries for each file to be matched.  But that would also require changes to git-annex and possibly more substantial since probably it was not coded to associate multiple mime types per file

There is also `-e json` which could be added to `file` call to exclude detection of json, but if anything (again, changed in annex) it would be a dirty hack/workaround, nothing really to rely upon.

# Temporary workaround
So I guess, in the short run, we should just add explicit 
```
*.json annex.largefiles=nothing
```
or alike (limit by size in addition).

Any other ideas?

**Comment by joeyh** [comment]
I like the mimeencoding=binary idea and have implemented it in
git-annex.

-- 
see shy jo

**Comment by yarikoptic** [comment]
Awesome, thank you @joeyh

**Comment by yarikoptic** [comment]
With git-annex-standalone=7.20190322+git133-g59922f1f4-1~ndall+1 in `debian-devel` of neurodebian `mimeencoding` is indeed available and seems to work for this use case:

first replicating prior erroneous behavior:
```shell
$> datalad create --text-no-annex /tmp/testds1
[INFO   ] Creating a new annex repo at /tmp/testds1 
create(ok): /tmp/testds1 (dataset)

$> cd /tmp/testds1

$> f=file.json; echo '{"a": 1}' >| $f; datalad add $f; ls -ld $f 
add(ok): /tmp/testds1/file.json (file)
save(ok): /tmp/testds1 (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
lrwxrwxrwx 1 yoh yoh 118 May  1 13:11 file.json -> .git/annex/objects/w5/f7/MD5E-s9--a01637863c1f9585c3e38cde6ce20940.json/MD5E-s9--a01637863c1f9585c3e38cde6ce20940.json
```
adjusting to use mimeencoding
```shell
$> echo -e '\n* annex.largefiles=(mimeencoding=binary)' >> .gitattributes; datalad save -m "Use mimeencoding"
save(ok): /tmp/testds1 (dataset)

$> f=file2.json; echo '{"a": 1}' >| $f; datalad add $f; ls -ld $f                                             
add(ok): /tmp/testds1/file2.json (file) [non-large file; adding content to git repository]
save(ok): /tmp/testds1 (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
-rw------- 1 yoh yoh 9 May  1 13:12 file2.json
```

so it works!

but there is a gotcha, that previous versions of annex would puke if encounter `mimeencoding`:
```shell
$> f=file2.json; echo '{"a": 1}' >| $f; datalad add $f; ls -ld $f                                             
CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'add', '--json', '--', '/tmp/testds1/file2.json']' failed with exitcode 1
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'add', '--json', '--', '/tmp/testds1/file2.json'] under '/tmp/testds1'. Exit code=1.
git-annex: bad annex.largefiles configuration: Parse failure: near "mimeencoding=binary"
git-annex: add: 1 failed
-rw------- 1 yoh yoh 9 May  1 13:08 file2.json
```
so we would need to boost git-annex version dependency!

FTR - empty zero sized files are added to annex as before and as expected (I think we might reconsider and make those added to git):
```shell
$> f=file3.json; touch  $f; datalad add $f; ls -ld $f             
add(ok): /tmp/testds1/file3.json (file)
save(ok): /tmp/testds1 (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
lrwxrwxrwx 1 yoh yoh 118 May  1 13:13 file3.json -> .git/annex/objects/fm/24/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e.json/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e.json

$> file -L --mime file3.json 
file3.json: inode/x-empty; charset=binary
```
if we are to reconsider, that is the rule to use
```shell
* annex.largefiles=((mimeencoding=binary)and(largerthan=0b))
```
NB file with a single empty line (of size 1) would still be considered binary

**Comment by yarikoptic** [comment]
eh, we should have handled this in #3667.  Now elderly me was whining again
https://git-annex.branchable.com/bugs/be_robust_to_additions_of_more_specific_mime_types_to_libmagic___40__e.g._application__47__json__41__/?updated#comment-04459bc7f99ebd74419f145e024e6830
before found this... Not sure what @joeyh would decide on this new issue, so I will submit a PR toward use of mimeencoding

**Comment by adswa** [comment]
Today in the Brainhack traintrack we got this bug report from a Windows 10 User in a dataset configured with ``text2git``

```
CommandError: '"git-annex" "add" "-c" "annex.dotfiles=true" "-c" "annex.retry=3" "--json" "--json-error-messages" "--" "books\SFTPGW-Manual.pdf" ".gitattributes"' failed with exitcode 1 under C:\Users\dorie\Documenten\Werk\_2019-03 - heden - Lab-datamanager Leiden\OHBM_OSSIG2020\DataLad-101 git-annex: bad annex.largefiles configuration in gitattributes: Parse failure: "mimeencoding" not supported; not built with MagicMime support
```

Has anyone seen this before?

**Comment by kyleam** [comment]
@adswa I don't think there's a solution for that issue yet:

* https://github.com/datalad/datalad/pull/3956#pullrequestreview-335604805
* https://git-annex.branchable.com/todo/provide_windows_build_with_MagicMime/

**Comment by kyleam** [comment]
This was marked as closed by gh-3956, but the auto-close wasn't triggered because the PR wasn't against master and the "Closes ..." bit was only in the PR's description.

**Comment by adswa** [comment]
Thank you @kyleam! I've opened https://github.com/datalad-handbook/book/issues/529 to provide a work-around
