### ISSUE TITLE
Why do run records contain `dsid`?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3369]
I cannot recall a reason, and I cannot find one in the docs. @kyleam ?

**Comment by mih** [comment]
I see it now. It is a marker for `rerun` to discover if a record was actually written for a superdataset. Such records should not actually end up in subdatasets, but our tooling is not yet capable enough (see e.g. #3244 for a technically related aspect and a linked PR that would enable tailoring of messages for subdatasets).

**Comment by kyleam** [comment]
Right.  For posterity: it was introduced by 85d54231a (ENH: run: Record dataset ID and check on rerun, 2018-05-25, gh-2560).
