### ISSUE TITLE
errors with git-worktree

### ISSUE THREAD

**Issue by notestaff** [datalad/datalad#3377]
Does datalad support linked worktrees created by git-worktree?  I'm getting an error, like so:

(master_env_v129_py36) 23:57  [is-import-powassan-04] $ datalad run -- dx find analyses --name 'assemble_denovo_with_deplete*' --state\
 done -n 200 --brief > benchmarks/powv/powv200.txt
[ERROR] /data/ilya-work/benchmarks/viral-ngs-benchmarks/tmp/is-import-powassan-04 [base.py:__init__:168] (InvalidGitRepositoryError)
(

**Comment by yarikoptic** [comment]
unfortunately "not yet" for years: https://github.com/datalad/datalad/issues/753 . [I was hoping](https://github.com/datalad/datalad/issues/2654#issuecomment-396610899) that the issue would be addressed in GitPython, but unfortunately not yet. From https://github.com/gitpython-developers/GitPython/issues/719#issuecomment-423775476 it sounds like a fix possibly quite easy.  Alternatively the issue might get resolved in 0.12 by eventually pruning any final use of GitPython (more and more we just invoke git commands directly)
