### ISSUE TITLE
Alternatives to progress bars

### ISSUE THREAD

**Issue by effigies** [datalad/datalad#3393]
#### What is the problem?

The current progress bar works well in a proper terminal, but if running in a less well-endowed environment, you can end up with something like:

```
    Total:   0%|                                         | 0.00/647M [00:00<?, ?B/s]
    sub-01/func .. bold.nii.gz:   0%|                    | 0.00/212M [00:00<?, ?B/s][A
    
    sub-01/func .. ressors.tsv:   0%|                   | 0.00/65.1k [00:00<?, ?B/s][A[A
    
    
    sub-02/func .. bold.nii.gz:   0%|                    | 0.00/212M [00:00<?, ?B/s][A[A[A
    
    
    
    Total:   0%|                              | 65.1k/647M [00:01<2:58:41, 60.3kB/s]
    
    Total (1 ok out of 6):   0%|              | 65.1k/647M [00:01<2:58:41, 60.3kB/s]
    
    Total (1 ok out of 6):   1%|▏             | 7.42M/647M [00:01<2:03:45, 86.1kB/s]
    sub-01/func .. bold.nii.gz:   3%|▍          | 7.35M/212M [00:00<00:14, 14.6MB/s][A
    
    sub-02/func .. bold.nii.gz:   5%|▌          | 9.70M/212M [00:00<00:10, 19.3MB/s][A[A
    
    
    Total (3 ok out of 6):   4%|▌              | 26.4M/647M [00:01<1:24:06, 123kB/s]
    sub-01/func .. bold.nii.gz:   4%|▍          | 7.80M/212M [00:01<02:26, 1.39MB/s][A
    
    sub-02/func .. bold.nii.gz:   5%|▌          | 10.5M/212M [00:01<01:24, 2.38MB/s][A[A
    
    
    Total (3 ok out of 6):   5%|▋              | 29.1M/647M [00:03<1:01:06, 168kB/s]
    sub-01/func .. bold.nii.gz:   4%|▍           | 8.31M/212M [00:03<04:43, 718kB/s][A
    
    sub-02/func .. bold.nii.gz:   5%|▌           | 11.0M/212M [00:03<03:43, 901kB/s][A[A
    
    
    sub-03/func .. bold.nii.gz:   5%|▌           | 10.2M/223M [00:03<04:31, 783kB/s][A[A[A
    sub-01/func .. bold.nii.gz:   4%|▍           | 8.57M/212M [00:03<05:16, 642kB/s][A
    
    
    sub-03/func .. bold.nii.gz:   5%|▌           | 10.5M/223M [00:03<04:50, 730kB/s][A[A[A
    sub-01/func .. bold.nii.gz:   4%|▍           | 8.77M/212M [00:04<06:09, 549kB/s][A
    
    Total (3 ok out of 6):   5%|▊                | 31.2M/647M [00:04<44:09, 232kB/s]
```

I've looked, and there doesn't seem to be any way to select an alternative display, or even no progress display.

It would be nice to be able to set a configuration option `datalad.progressbar = log` or similar to indicate that output should be treated as a serial stream, and `datalad.progressbar = none` to simply not try to display the information.

#### What steps will reproduce the problem?

In `jupyter-lab` with a Bash kernel:

```
datalad install -r ///labs/poldrack/ds003_fmriprep
datalad get ds003_fmriprep/sub-0{1,2,3}/func/*_space-MNI152NLin2009cAsym_desc-*.nii.gz \
            ds003_fmriprep/sub-0{1,2,3}/func/*_desc-confounds_*.tsv
```

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

datalad 0.11.4

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)

Yes

**Comment by yarikoptic** [comment]
Yeah -- I think we should add an explicit way to disable/alter progress bars (and only them).  At the moment the choice is tied into which "ui.backend" to be used.  E.g. you could disable all progress bars entirely by `datalad.ui.ui.set_backend("no-progress")` but that would also switch UI to "non interactive" mode so it would not even try to ask any questions/passwords if those become needed.

- I also do not think we exposed the choice for the backend via datalad's config... only for the tests (`datalad.tests.ui.backend`), so I think we should add `datalad.ui.backend` configuration variable so it could be set via config or env variable (`DATALAD_UI_BACKEND`)
- We should indeed add `datalad.ui.progressbar` config which could have e.g. 
   - `tqdm`,
   - `tqdm-ipython`,
   - `log` (to be implemented to probably logging.log the beginning + end of the progress or smth like that). 
`log` should be the one chosen if we detect being ran under some crippled terminal or CI

FWIW: We are trying to detect being in ipython/jupyter notebook and switching tqdm to use dedicated progress bars, that seems to work:
![image](https://user-images.githubusercontent.com/39889/57320655-5e0c9400-70cd-11e9-9baa-2de4e18b463f.png).  I didn't try yet in jupyter lab.
