### ISSUE TITLE
Request: Respect NO_COLOR environment variable

### ISSUE THREAD

**Issue by effigies** [datalad/datalad#3404]
#### What is the problem?

There is no obvious way to disable ANSI colors in the terminal outputs. There is an effort to have CLI tools uniformly respect a `NO_COLOR` environment variable, which seems like a good place to start. See https://no-color.org/.

The context this comes up in is in [this example notebook](https://fitlins.readthedocs.io/en/latest/examples/ds003_sample_analysis.html#install-data-and-fitlins), where Sphinx does not properly render ANSI colors. It would be useful to simply disable them at the datalad end, rather than play around on the parsing end.

[snipped other headers]

**Comment by mih** [comment]
I like that.

**Comment by kyleam** [comment]
Sounds good to me as well.  I think such a change should come along with a datalad.ui.color config variable with auto (default), off, and on values, where the explicit on overrides NO_COLOR.

**Comment by yarikoptic** [comment]
Sounds great to me too... Easy first contribution PR to do as well probably but could get down the rabbit hole ;-)

**Comment by yarikoptic** [comment]
Best would be done against 0.11.x branch
