### ISSUE TITLE
Unified specification of `--jobs`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3415]
This is closely related to https://github.com/datalad/datalad/issues/3246, but now also relevant in the `publish` rewrite https://github.com/datalad/datalad/projects/9

I don't have a good idea on how to approach this, but in both cases we complicate the high-level API only to be able to not act on this information at all, and merely pass it down to the low-level handlers.

**Comment by bpoldrack** [comment]
Should be a datalad option not a command option from my point of view. And yes, this would require a unified approach on how exactly to act upon it. However, moving this option accordingly and just let the command then pass it onto low-level would still be an improvement and a step in the right direction from my point of view.

**Comment by mih** [comment]
I think the pattern to implement support for individual commands is identified and is being applied on a case by case basis. The need to do so has been reduced with the introduction of the `foreach-dataset` command. Future work needs to explore in how far this paradigm (across dataset parallelization with `foreach-dataset` and within-dataset parallelization via individual `--jobs` parameters per command) is applicable and capable to a large-enough range of use cases. Depending on the results of such an exploration, concerted adjustment of the API needs to be planned.

For now, this issue cannot contribute to this effort any further.
