### ISSUE TITLE
Use cases for `publish --transfer-data`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3416]
I think this was originally added out of desperation. The question is whether it has a real purpose?

When any paths are given (at least when they are not datasets), I clearly want data transfer.

If I do not want data transfer, I can only act on the granularity of whole datasets anyways, so I can use `--dataset` instead of a `path`.

I would not be able to specify multiple individual datasets to publish at once in this scenario. However, there is not real requirement to support that, as multiple calls to `publish`, each for a single (root) dataset accomplish the job -- potentially much faster, as these operations are independent of each other.

All other scenarios I can think of would be covered by adding particular modes for `--force` #3414, including the case that if we want to transfer all data by default, without requiring `.` as path argument, we can have `--force nodatatransfer` as a way to prevent this. Although I am not at all saying we should transfer data by default.

**Comment by yarikoptic** [comment]
I think it again it might relate to our ongoing discussion on how we specify the "context" of operation.  Here you are saying that specifying path provides semantic "this data", but it could be a path to the (sub)dataset I want to publish.  Then how do we discriminate?  My wild guess for the intention for `--transfer-data` could have been to make it (more) explicit.
On that note -- I think I have rarely (if ever) used it.  Most often I rely on the default "auto" ;-)

**Comment by mih** [comment]
Closing "question"-type issue with a response, and no further activity.
