### ISSUE TITLE
New command: `create_sibling_gitlab`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3420]
Pretty straightforward exercise with https://github.com/python-gitlab/python-gitlab

**Comment by mih** [comment]
I have a working sketch and should get to an initial version over the next few days. Does anybody know of a public gitlab instance that we can test against?

**Comment by yarikoptic** [comment]
Us - Debian's salsa?

**Comment by yarikoptic** [comment]
tests will be an exercise too.  For github ones I used vcr with manual sanitization of the recorded tapes after. you can find in the codebase
