### ISSUE TITLE
run wishlist: expose its "specification" to the invoked process (RO or even RW)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3422]
With https://github.com/datalad/datalad-container/pull/84 we recently exposed container name, but greedy me now wants more!  Not unlikely in git hooks, exposing details of run I think could open a wider of possibilities for custom shims.  In my case (will be back-referenced later, yet to submit) I felt desire for
- knowing if it was an `--explicit` run. (could be exposed as `DATALAD_RUN_EXPLICIT`)
- in case of `--explicit` I felt I could benefit from knowin inputs/outputs.  Probably the best approach could be to store the entire `run` record in some temp file which would then be exposed via e.g. `DATALAD_RUN_RECORDFILE` variable

and then I wanted even ability to be able to alter the run record:
- shim might decide to alter run details, e.g. specify additional output files.  One way is to alter the run record file (above)

I guess the issue might get populated more later...

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
