### ISSUE TITLE
Avoid platform.dist (removed in py3.8) in wtf

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3431]
This is split off from gh-3417.  gh-3423 fixed the setup.py part, so this is a dedicated issue for wtf's use of platform.dist().

**Comment by yarikoptic** [comment]
d'oh -- sorry I've missed it

**Comment by kyleam** [comment]
> d'oh -- sorry I've missed it

No worries, I forget about it too until looking at the Travis failures for #3430.

**Comment by yarikoptic** [comment]
FWIW -- that `dist` package... seems all good but damn slow 

```shell
$> time python3.6 -c 'import platform as pl; print(pl.dist())' 
('debian', 'buster/sid', '')
python3.6 -c 'import platform as pl; print(pl.dist())'  0.04s user 0.01s system 99% cpu 0.051 total

$> time python3.6 -c 'import distro; print(distro.linux_distribution(full_distribution_name=False))' 
('debian', 'testing', 'buster')
python3.6 -c   2.41s user 0.36s system 81% cpu 3.406 total
```
so >3 sec! for what took `platform.dist` only 50 msec.

and it is not import time per se
```shell
$> time python3.6 -c 'import distro; '                                                                
python3.6 -c 'import distro; '  0.06s user 0.01s system 67% cpu 0.106 total
```
I know that it is just WTF but I do not think it is worth waiting for it .

Moreover RTFM for distro says "Distro currently supports Linux and BSD based systems but Windows and OS X support is also planned."  so -- no improvement on that end either...

**Comment by yarikoptic** [comment]
anyways, I think we should just make it not crash for now and fix it "properly" later. Actually I will even make it try `dist` as an alternative but will not demand it. I will submit a PR

**Comment by kyleam** [comment]
@yarikoptic:

> Actually I will even make it try `dist` as an alternative but will not demand it. I will submit a PR

Sounds good.  Thanks for looking into this.
