### ISSUE TITLE
local to subdatasets paths in action status report are misleading

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3442]
if before (0.11.x) it was suboptimal due to full paths:
```
(git-annex)hopa:/tmp/testds-remove[master]git-annex
$> echo 123 >> subds/subds12/subds/ingit 
(dev) 1 14595 [2].....................................:Mon 20 May 2019 06:38:30 PM EDT:.
(git-annex)hopa:/tmp/testds-remove[master]git-annex
$> datalad save -r -d . subds/subds12/subds/ingit
save(ok): /tmp/testds-remove/subds/subds12/subds (dataset)
save(ok): /tmp/testds-remove/subds/subds12 (dataset)
save(ok): /tmp/testds-remove/subds (dataset)
save(ok): /tmp/testds-remove (dataset)
action summary:
  save (ok: 4)
```
Now (0.12.0rc4.dev5) it is easier on eyes but without consideration of the "context" from which the command was called, reported paths within subdatasets could be confusing, wrong, or misleading:

```
(git-annex)hopa:/tmp/testds-remove[master]git-annex
$> echo 123 >> subds/subds12/subds/ingit
(dev) 1 14599 [2].....................................:Mon 20 May 2019 06:39:20 PM EDT:.
(git-annex)hopa:/tmp/testds-remove[master]git-annex
$> datalad save -r -d . subds/subds12/subds/ingit
add(ok): ingit (file)
save(ok): subds/subds12/subds (dataset)
add(ok): subds (file)
save(ok): subds/subds12 (dataset)
add(ok): subds12 (file)
save(ok): subds (dataset)
add(ok): subds (file)
save(ok): . (dataset)
action summary:
  add (ok: 4)
  save (ok: 4)
```
not to mention that I am not sure what "add(ok): subds (file)" means since I do not have `subds` file in this example.

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
