### ISSUE TITLE
run --explicit: seems to glob outputs only BEFORE but not AFTER

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3448]
glob can change as a result of running the command, and then result new output files should be saved as well.  It seems to be not the case and only files for the glob expanded before running the command are saved
```shell
$> ls  *.dat  
1.dat@  2.dat@

$> datalad --version
datalad 0.11.4.dev108

$> datalad run --output '*.dat' --explicit touch 3.dat
unlock(ok): 1.dat (file)                          
unlock(ok): 2.dat (file)
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) ===== 
add(ok): 1.dat (file)
add(ok): 2.dat (file)
action summary:
  add (ok: 2)
  save (notneeded: 1)
  unlock (ok: 2)

$> ls *.dat                                           
1.dat@  2.dat@  3.dat

$> git log 3.dat

$> datalad run --output '*.dat' --explicit touch 3.dat
unlock(ok): 1.dat (file)
unlock(ok): 2.dat (file)
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) ===== 
add(ok): 3.dat (file)
add(ok): 1.dat (file)
add(ok): 2.dat (file)
save(ok): /tmp/testds (dataset)
action summary:
  add (ok: 3)
  save (ok: 1)
  unlock (notneeded: 1, ok: 2)
```

FWIW -- without --explicit all is saved ok

```shell
$> datalad run --output '*.dat' touch 4.dat        
unlock(ok): 1.dat (file)               
unlock(ok): 2.dat (file)
unlock(ok): 3.dat (file)
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) ===== 
add(ok): 4.dat (file)
add(ok): 1.dat (file)
add(ok): 2.dat (file)
add(ok): 3.dat (file)
save(ok): /tmp/testds (dataset)
action summary:
  add (ok: 4)
  save (ok: 1)
  unlock (ok: 3)
```

**Comment by kyleam** [comment]
Doing the expansion on the filesystem only before the run but not after is certainly the intended behavior, but, yeah, the decision to expose --explicit complicates that.  I'll think more about doing a post-run expansion.

**Comment by pvavra** [comment]
I also ran into this unexpected behavior with `--explicit`. 

my use case (fwiw): 
run first-level fMRI analyses where I know into which folder files will be put, but not their name. 
I use `--explicit` to avoid issues with a dirty dataset (e.g. continuing writing code, while the computations run in the background)
Having changed the contrasts I want to have, (re-)running this will not save the additional files, only unlock the old ones.

Are there any workarounds/alternatives for my scenario?

**Comment by kyleam** [comment]
Thanks for your input.  I should revisit this, but a clean dataset approach to "continuing writing code, while the computations run in the background" would be to work in a clone of the dataset (perhaps making use of `clone/install`s `--reckless`).  Outside of the Datalad context, a related approach would be to use `git worktree`, but DataLad doesn't play well with worktrees.
