### ISSUE TITLE
SSH error message madness

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3450]
This report doesn't do the issue justice, because the colors are missing, but:
```
$ datalad publish --to inm7 --transfer-data all
Permission denied (publickey).
[WARNING] Failed to run cmd ['ssh', '-fN', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=15m', '-o', 'ControlPath="/home/homeGlobal/mih/.cache/datalad/sockets/6cfa41e2"', 'git@.....de']. Exit code=255
| stdout: None
| stderr: None 
[ERROR  ] Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)
|   cmdline: /usr/lib/git-annex.linux/git -c receive.autogc=0 -c gc.auto=0 fetch --progress -v inm7
|   stderr: 'fatal: Could not read from remote repository.
| 
| Please make sure you have the correct access rights
| and the repository exists.' [cmd.py:wait:415] (GitCommandError) 
```

What happens is that my SSH key was missing, so the connection attempt failed (pay attention to the first line of output). On the terminal this is easy to miss, because the next line starts with a bright yellow WARNING that informs me about the *consequence* not the initial problem, followed by a bright red ERROR that is even more detached from the issue.

**Comment by yarikoptic** [comment]
I don't have an idea how we could improve upon that besides doing initial sensing if we can login (I thought we actually did) and giving error even without trying to run git.

**Comment by mih** [comment]
Here is how to replicate this issue:

```
/tmp % datalad create lcl
/tmp % mkdir bareremote
/tmp % git -C bareremote init --bare
/tmp % cd lcl
% datalad siblings add -s bareremote --url datalad-test:/tmp/bareremote
% datalad publish --to bareremote --transfer-data all
mih@datalad-test: Permission denied (publickey,password).
[WARNING] Failed to run cmd ['ssh', '-fN', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=15m', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/c5820c82', 'datalad-test']. Exit code=255
| stdout: None
| stderr: None 
[ERROR  ] Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)
|   cmdline: /usr/lib/git-annex.linux/git fetch --progress -v bareremote
|   stderr: 'fatal: Could not read from remote repository.
| 
| Please make sure you have the correct access rights
| and the repository exists.' [cmd.py:wait:412] (GitCommandError) 
```

with:

```
% grep datalad-test /etc/hosts
127.0.0.1       datalad-test
% grep -A1 datalad-test ~/.ssh/config
Host datalad-test
  PreferredAuthentications publickey
```

and no private key listed in `~/.ssh/authorized_keys`

**Comment by mih** [comment]
Looking into this I cannot agree with @yarikoptic's assessment. Here is why:

1. `GitRepo._call_gitpy_with_progress()` does not eval `SSHConnection.open()`
  It returns a bool (or `None`) to indicates connection open success. This return value is ignored and datalad proceeds leading to the ultimate `error`. On failure, an early abort is possible.

2. `SSHConnection.open()` should not issue a warning.
  This method clearly documents if things worked out in its return value. There is no way for it to figure out, whether the caller has plans to deal with an error, and no way to disable the prominent warning in this case. In the spirit of https://github.com/datalad/datalad/issues/1769 it should relay all relevant information to the caller.

I propose to: RF `SSHConnection.open()` to:
   - return `True` on success, `False` on an already open connection (although I am not sure when this could be relevant)
   - raise `CommandError` when things go wrong in any way

ATM it is not meaningful to RF `GitRepo._call_gitpy_with_progress()`. With the above change, processing will stop before leading to subsequent errors (improves the status quo). There is no way to introduce meaningful result generation, because all its callers (`fetch`, `push`, `pull`) directly and immediately return internal GitPy data structures. Once this practice is discontinued, proper errors can be generated that feed into the result reporting infrastructure.
