### ISSUE TITLE
run: disable/avoid glob expansion?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3454]
#### What is the problem?

Sorry @kyleam - me again with the questions.  If one (or more) of my `input`s is a glob, which I need to use as a glob (or expanded, but only that one of inputs) in the command (`for` loop), how to do it?  here is a minimized (hopefully I didn't butcher it) example:
```
$ datalad run -m msg --explicit  --input some-config.cfg --input '*/preproc/sub-00*/ses-*/sub-*.nii.gz' --input "*/ev3/" bash -c 'for f in "{inputs[0]}" ; do scripts/run_1stlevel_analysis.sh "{inputs[1]}" $f; done'   
```
if ran currently, `{inputs[1]}` will not be a glob but first element after its expansion.

**Comment by kyleam** [comment]
The syntax is pretty limited here, and currently there's no way to do what you want (i.e. you have to repeat the input glob in the command).  

> or expanded, but only that one of inputs

In person, we've talked about supporting some sort of named inputs and outputs, along the lines of what [Snakemake does (second snippet)][0].  I'm not sure the added complexity is worth it, but it's of course worth discussing.

There's been no concrete proposal of how that would look on the command line (and in the run record).  Stealing git's pathspec signature just to have some sort of example:

```
datalad run -i '(:name=foo)*.a -i '(:name=bar)*.b' 'for f in {inputs.foo}; do thing {inputs.bar} $f; done'
```

[0]: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#rules

**Comment by yarikoptic** [comment]
Having ability to name inputs indeed would be great!  If we were to "adjust" our parsing of cmdline (possibly could come handy in other cases as well may be?) to allow something like

   datalad run --input-foo '*.a' --input config-file --input-bar '*.b' 'for f in {inputs.foo}; do thing -c {inputs[1]} {inputs.bar} $f; done'

thus allowing mixing named and just purely positional -- would have been great. But it would not have probably a clear analog in Python.  So may be restricting to either be strictly only positional (`list` in Python) or named (`dict` or `OrderedDict` in Python) - would be sensible.

**Comment by mih** [comment]
Closing "question"-type issue with a response, and no further activity.
