### ISSUE TITLE
Bring back git gc

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3457]
ATM we explicitly disable git's gc during calls to git/annex since GitPython's state might get outdated and we did experience problems in the past.  But that often, largely after a sweep of git annex actions, leaves **huge** .git/objects behind and then mandates either running some `git` commands manually to get gc triggered or an explicit run to `gc`.  Example after a one large `datalad save` call:
```shell
$ du -scm .git/objects
1978    .git/objects
1978    total

$ git gc --prune=now
Counting objects: 524428, done.
Delta compression using up to 40 threads.
Compressing objects: 100% (520901/520901), done.
Writing objects: 100% (524428/524428), done.
Total 524428 (delta 50448), reused 18895 (delta 1701)
Removing duplicate objects: 100% (256/256), done.
Checking connectivity: 524428, done.

$ du -scm .git/objects
71      .git/objects
71      total
```

Especially if GitPython would be gone, or may be even without it (could have been fixed up in GitPython to react upon gc?) we should consider dropping disabling of automatic gc.  I will submit a test PR to see if things still get crashing (unable to find objects etc) ;-)

**Comment by kyleam** [comment]
If gh-3458 shows that gitpython still has issues, another option would be to have a global boolean that indicates whether we trigger `git gc --auto` when exiting.  Commands that we think might create many loose objects could set that flag.

**Comment by kyleam** [comment]
Ah, but doing that globally is not a good idea because we don't know which dataset(s) to run it in.
