### ISSUE TITLE
create -d .  subds  stopped saving added subdataset within  .

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3463]
#### What is the problem?
We only discussed such possibility in https://github.com/datalad/datalad/issues/3316#issuecomment-493325455 but I was not expecting it to happen, but it seems on master 0.12.0rc4-90-ge83d571b0 it is the behavior ATM:
```shell
$> p=/tmp/testds; sudo rm -rf $p; datalad create $p; cd $p; datalad create -d . subm1 && git status
[INFO   ] Creating a new annex repo at /tmp/testds 
create(ok): /tmp/testds (dataset)                                                                                 
[INFO   ] Creating a new annex repo at /tmp/testds/subm1 
create(ok): subm1 (dataset)                                                                                       
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	subm1/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by kyleam** [comment]
The first commit I see this behavior with is fc25ac55d (BF: Do not duplicate/auto-convert dataset args to instances, 2019-05-20).  AFAICT it's an unintended regression.

**Comment by yarikoptic** [comment]
eh heh... and our "Python-API oriented" tests sure thing missed that!

**Comment by yarikoptic** [comment]
so I wonder if we are doomed to revert https://github.com/datalad/datalad/pull/3435 for now or there is a better resolution to avoid such unexpected drastic change in behavior, @mih?

**Comment by kyleam** [comment]
> so I wonder if we are doomed to revert #3435 for now or there is a better resolution to avoid such unexpected drastic change in behavior, @mih?

In my non-mih opinion, I think dealing with any other issues as they pop up is ok.
