### ISSUE TITLE
Uniformly record subdatasets's UUIDin .gitmodules

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3474]
In order to execute the plan in #1424, we need to have subdatasets' dataset UUID recorded in`.gitmodules` of the superdataset. The 0.12 `create` already does that, but `install` has yet to be modified.

Based on this UUID, `load()` would look for a stashed dataset, when recursively constructing a worktree. Likewise, `install` could use such a lookup.

**Comment by kyleam** [comment]
> In order to execute the plan in #1424, we need to have subdatasets' dataset UUID recorded in`.gitmodules` of the superdataset. The 0.12 `create` already does that, but `install` has yet to be modified.

That was done by adjusting `GitRepo.add_submodule`.  Won't that cover `install` too?

```sh
#!/bin/sh

set -eu

cd $(mktemp -dt dl-XXXXXXX)
datalad create toinstall
datalad create into
cd into
datalad install -d. -s ../toinstall subds
cat .gitmodules
```

```
[INFO   ] Creating a new annex repo at /tmp/dl-7couyn9/toinstall
create(ok): /tmp/dl-7couyn9/toinstall (dataset)
[INFO   ] Creating a new annex repo at /tmp/dl-7couyn9/into
create(ok): /tmp/dl-7couyn9/into (dataset)
[INFO   ] Cloning ../toinstall into '/tmp/dl-7couyn9/into/subds'
[INFO   ] warning: Not setting branch master as its own upstream.
install(ok): subds (dataset)
action summary:
  add (ok: 2)
  install (ok: 1)
  save (ok: 1)
[submodule "subds"]
	path = subds
	url = /tmp/dl-7couyn9/into/../toinstall
	datalad-id = be19cdf8-8a0f-11e9-a5e4-54e1ada290c0
```

**Comment by mih** [comment]
Ah, indeed. I tried it yesterday and it didn't work, but apparently the repo that I installed was just a repo and no dataset with an ID... Thx for double-checking!
