### ISSUE TITLE
Travis: py3.7 run segfaults

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3477]
First showed up in gh-3475 after push of 3e7963910 ([travis run][0]), but it shows up without that commit as well ([travis run][1]).

```
[...]
[INFO] Directory: /tmp/datalad_temp_tree_test_fs_traverser5ey6rfm/dir 
[INFO] Directory: /tmp/datalad_temp_tree_test_fs_traverser5ey6rfm 
/home/travis/.travis/functions: line 104:  8099 Segmentation fault      (core dumped) http_proxy= PATH=$PWD/../tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -A "$NOSE_SELECTION_OP($NOSE_SELECTION)" --with-doctest --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM
travis_time:end:0f10ce80:start=1560368950151875732,finish=1560369999894399306,duration=1049742523574
[0K[31;1mThe command "http_proxy= PATH=$PWD/../tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -A "$NOSE_SELECTION_OP($NOSE_SELECTION)" --with-doctest --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM" exited with 139.[0m
[...]
```

[0]: https://travis-ci.org/datalad/datalad/jobs/544787756#L1472
[1]: https://travis-ci.org/datalad/datalad/jobs/544897388#L1465

**Comment by yarikoptic** [comment]
Oh... May be wrapt? What if you revert that recent PR removing setting an env variable?

**Comment by kyleam** [comment]
Thanks for the suggestion.  Will try.

**Comment by kyleam** [comment]
It doesn't look like it was triggered by dropping `WRAPT_DISABLE_EXTENSIONS=1` ([travis run][0], 85c4df422).

[0]: https://travis-ci.org/datalad/datalad/builds/545239602#L1464

**Comment by kyleam** [comment]
The [last one][0] to _not_ segfault was when Travis still used Trusty as the default distribution.  The [first one][1] to segfault used Xenial.  That seems likely to have something to do with it.

[0]: https://travis-ci.org/datalad/datalad/jobs/544598177#L9
[1]: https://travis-ci.org/datalad/datalad/jobs/544787756#L9
