### ISSUE TITLE
Error creating sibling due to keyring

### ISSUE THREAD

**Issue by oesteban** [datalad/datalad#3478]
#### What is the problem?

I'm trying to create a sibling and repeatedly fall into this:

```Text
$ datalad create-sibling-github --github-organization "templateflow" --github-login oesteban --dataset tpl-MNIPediatricAsym tpl-MNIPediatricAsym
[WARNING] Failed to query keyring: a bytes-like object is required, not 'list' [ciphers.py:update_into:140]
[ERROR  ] a bytes-like object is required, not 'list' [ciphers.py:update_into:140] (TypeError) 
```

That happened with pip-installed datalad-0.10 & NeuroDebian's git-annex-standalone and also with conda installed datalad-0.11.5 & conda installed git-annex (2019X)

#### What steps will reproduce the problem?
Running the command line stated above

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
```
## datalad
  - full_version: 0.11.4
  - version: 0.11.4
## dependencies
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:annex: 7.20190219-g728228d5d
  - cmd:git: 2.17.1
  - cmd:system-git: 2.17.1
  - cmd:system-ssh: 7.6p1
  - exifread: 2.1.2
  - git: 2.1.11
  - gitdb: 2.0.5
  - humanize: 0.5.1
  - iso8601: 0.1.12
  - keyring: 16.0.2
  - keyrings.alt: 3.1
  - msgpack: 0.5.6
  - mutagen: 1.41.1
  - requests: 2.20.1
  - six: 1.11.0
  - tqdm: 4.32.1
  - wrapt: 1.10.11
## system
  - distribution: debian/buster/sid
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 291
  - name: Linux
  - release: 4.15.0-47-generic
  - type: posix
  - version: #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019
```

#### Is there anything else that would be useful to know in this context?
Writing the password with the ``--github-passwd`` command seemed to work out.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Yes, very successfully. Thanks for working this great piece of software.

**Comment by mih** [comment]
We have a new implementation now that interfaces with the keyring in a very different fashion. I think this can be closed now.
