### ISSUE TITLE
Q: Trajectory to make SSHConnection more useful

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3487]
I am using this functionality more and more, but it is rather clunky. For example, it is not easy to stream large outputs (think decompressing a remote archive and storing the output locally without making tmp copies, etc.

I see two paths forward:

1. Expose internal pieces, such as SSH command generation, so that could be used with an outside "runner".
2. Add a dedicated `.run()` that sits on top of `subprocess.run()` and takes the same args.

   https://docs.python.org/3/library/subprocess.html#subprocess.run

The later is PY3.5+ only, so we likely don't want to base internal functionality on it, but it would be very helpful in order to have the entire range of possibilities available via a standard interface, plus the connection handling functionality that we provide.

It also offers a cross-platform DEVNULL object (in addition to PIPE), which is really handy (PY 3.3+).

What do you think?

**Comment by bpoldrack** [comment]
Approach 2. looks much cleaner to me.
And ... well, I'll not mention the ticking clock. Not at all.

**Comment by mih** [comment]
Abusing this issue to leave a trace of a sneaking suspicion that something in this code is extremely suboptimal. I am running git-annex special remote test suite on two very similar implementations, one performing direct filesystem operations, one doing the closest analog through SSH connections to `localhost`. The difference in timing is extreme (80+ times slower via SSH). CPU utilization is <20%. Will have to dig into this...

**Comment by mih** [comment]
Closing "question"-type issue with a response, and no further activity.
