### ISSUE TITLE
Double-check permissions when publishing

### ISSUE THREAD

**Issue by mih** [datalad/datalad#349]
Not sure how general this issue is, but when I "git annex copy --to ..." a file that has 660 permissions locally, it seems to have them also on the target server. If the goal is to have a webserver access this file, this will likely cause a problem.

Need to investigate whether a git init --shared solves this issue.

**Comment by hanke** [comment]
`git init --shared=all` solves the issue.

@bpoldrack if this was obvious and already considered in the implementation of publish, please close this issue.

**Comment by yarikoptic** [comment]
I think this was solved... I do have very restrictive umask but keep publishing to datasets.datalad.org and things seems to work
