### ISSUE TITLE
Consider reworking the extension setup to use namespace packages

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3495]
https://stackoverflow.com/questions/8380381/the-way-to-make-namespace-packages-in-python#8380524

**Comment by yarikoptic** [comment]
I wondered if there is any real-life usage of that feature. https://codesearch.debian.net/search?q=namespace_packages seems to give > 200 package hits, so it seems to be in use.  Will be interesting to see if it provides startup performance benefit over current setup.

**Comment by mih** [comment]
Closing this now as there is/was no immediate uptake.
