### ISSUE TITLE
Fix up test_run.py tests for the glorious Windows

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3501]
ATM 19 tests within test_run carry `@known_failure_windows`.  Some do not and they do not rely on using POSIXy commands/constructs such as `touch` or  `echo ... >`  and instead use constructs like

```python
@with_tempfile(mkdir=True)
def test_py2_unicode_command(path):
    ...
    touch_cmd = "import sys; open(sys.argv[1], 'w').write('')"
    cmd_str = u"{} -c \"{}\" {}".format(sys.executable,
                                        touch_cmd,
                                        u"bβ0.dat")
    ds.run(cmd_str)
    ...
    ds.run([sys.executable, "-c", touch_cmd, u"bβ1.dat"])
```

so I wondered if we should come up with `get_touch_cmd(files)` and `get_append_cmd(content)`  etc helpers to construct the needed python invocation line to pass to `ds.run` or `run` in other tests to make them cross platform?

**Comment by kyleam** [comment]
On master, the run tests (now split into core/local/tests/test_run.py) are in much better shape wrt to Windows thanks to @mih.  With newer tests, I made some attempts (like above) to make it work, but @mih approach was to mostly just use carefully chosen commands, which is more readable than what I did above.

interface/tests/test_rerun.py is still in bad shape.  IIRC that's about more than the commands used; there are also issues with rerunning on adjusted branches.

**Comment by mih** [comment]
I will close this issue now, because the situation described isn't the case anymore. Feel free to retitle and/or reopen if you disagree.

**Comment by yarikoptic** [comment]
not sure how it "isn't the case" if https://github.com/datalad/datalad/pull/3982 failed when test was re-enabled.

**Comment by mih** [comment]
Because this failure is not about a run test (likely), but about more fundamental misbehavior on windows. But if you need this specific issue open, I am OK with that. Maybe it can provide additional insight ;-)

**Comment by mih** [comment]
FTR: The test quoted here also fails on crippled FS with non-windows systems. I still consider this issue worth closing, because it lumps together various issues and is like to stay open for a long period of time.

**Comment by mih** [comment]
Here is my 6-monthly attempt to close this issue, because the reason for test-failure in present code is absent unicode handling.
