### ISSUE TITLE
[wishlist] `datalad status`  "modes" or just `datalad -f stats`?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3502]
Unlike in typical use cases for git while developing code, dealing with  datasets  often results in many files being changed or untracked.  Both `git status` nor `datalad status` provide per file (changed or untracked) output which often just floods the screen making it impossible to actually comprehend current status (besides tree being dirty) without rerunning the command and piping it into `less` and then browsing it for a while.
I think it would be nice to have something like `git diff --stat` or summary rendering like we have in other commands just presenting overall summary **without** flooding the terminal, e.g.
```
untracked(file): 2000
modified(file): 1000
removed(file): 1000
```
and so on, may be even without `(file)` indicator although if we could provide information about subdatasets (e.g. `modified(subdataset): 2` and `dirty(subdataset): 1`) -- would be great.

And we have already something like that but for actions, since we do add `action summary:`  at the end in the default renderer.  But that is not in effect for `status` since there is no actual action taken, and in general it provides status for **all** the files, not only the ones of "interest" as reported by its renderer ATM (modified/untracked etc)

So I wondered if we should/could
-  add explicit `-f stats` which would suppress individual messages and only output summary at the end
- make it work also for `datalad status`
?

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
