### ISSUE TITLE
[wishlist] `--output-format smart`

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3503]
Relates to #3502 and other whinings from me before (feel welcome to find/link here). In many use cases datalad commands flood the screen with "per file" reports which aren't really of interest when manipulating large number of files, and then (some) commands  provide the actually useful in those use cases "action summary:" statements.  I think it would be nice if there was an output format (possibly eventually becoming the default one, with "oneline" being the current one) which
- after a configurable number of lines have been output (let's say 10) it would say something like
"... more than 10 records, only summary will be displayed, see /tmp/datalad-output-RANDOM.log for full list"
- that temporary file is not auto-removed
- in a TTY/interactive mode we could add some progress indicator for more records being received without flooding the screen
- at the end display "action summary:"

an alternative flavor is to store in that file not pre-formatted log lines, but actual records, and have a dedicated command (e.g. `datalad cmdlog`) being able to load and render them with an alternative `--output-format`, with `"oneline"` being the default one.

This way output from datalad will not flood terminals, all log messages will still be accessible if necessary, for programmable handling the other modes of `-f` would remain available

**Comment by yarikoptic** [comment]
ha, just discovered for myself that `git status` is also "smart".

<details>
<summary>  In the case of many untracked files, it doesn't show them and suggests to use `-u`.</summary> 

```shell
(git-annex)hopa:~pymvpa/papers[master]
$> git status   
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit (use -u to show untracked files)
1 25975.....................................:Wed 11 Sep 2019 09:40:41 AM EDT:.
(git-annex)hopa:~pymvpa/papers[master]
$> git status -u | nl | tail
  3264		talk-upenn2011_pymvpa/borrowed/vss_poster.ppt
  3265		talk-upenn2011_pymvpa/bu.txt
  3266		talk-upenn2011_pymvpa/out.png
  3267		talk-upenn2011_pymvpa/pdftoppm.ppm
  3268		talk-upenn2011_pymvpa/s-ack2.tex
  3269		talks-pymvpa_course2014/s-pymvpaecosystem.pdf.cache
  3270		talks-pymvpa_course2014/s-pymvpaecosystem.sh
  3271		workshop-dc2010/plan_slides.txt
       
  3272	no changes added to commit (use "git add" and/or "git commit -a")
```
</details>

**Comment by kyleam** [comment]
> ha, just discovered for myself that `git status` is also "smart".
>
> In the case of many untracked files, it doesn't show them and suggests to use `-u`.

The output you showed is also what you would see if you had configured `status.showUntrackedFiles=no` (along with the default `advice.statusHints=true`).  It's not clear to me that git is actually adjusting anything based on the number of files.  Can you show the values of config variables that might be relevant and the output if you have only a single untracked file?

I'm only able to trigger the output you show with a blanket `status.showUntrackedFiles=no`.

<details>
<summary>attempt to trigger</summary>

```sh
#!/bin/sh

set -ue

git --version
git -c core.pager=cat config -l

for i in $(seq 0 10000)
do echo $i >f-$i
done

echo "---"
echo "with vanilla configuration"
git status | nl | tail

echo "---"
echo "with -c status.showUntrackedFiles=no status"
git -c status.showUntrackedFiles=no status | nl | tail
```

```
git version 2.23.0
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.pager=cat
---
with vanilla configuration
  9997		f-9992
  9998		f-9993
  9999		f-9994
 10000		f-9995
 10001		f-9996
 10002		f-9997
 10003		f-9998
 10004		f-9999
       
 10005	nothing added to commit but untracked files present (use "git add" to track)
---
with -c status.showUntrackedFiles=no status
     1	On branch master
     2	nothing to commit (use -u to show untracked files)
```

</details>

**Comment by yarikoptic** [comment]
oh, you spoiled it @kyleam !!!!  indeed I had that setting for the repo set.  I guess at some point they annoyed me enough to act ;)

**Comment by yarikoptic** [comment]
ok, user got used to it one way or another, no need to linger on this topic
