### ISSUE TITLE
Docs: 3rd_party_analysis_workflow.sh fix is not updated in the docs

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#3507]
#### What is the problem?

Going through the documentation, I found 

```
datalad create myanalysis --description "my phd in a day" 
```
in the [data management use cases: A typical collaborative data management workflow](http://docs.datalad.org/en/latest/generated/examples/3rdparty_analysis_workflow.html). This example fails when executed with the latest datalad version (``datalad 0.12.0rc4.dev153``) because the arguments need to be specified prior to the path. 
It was already fixed in the [source .sh file](https://github.com/datalad/datalad/blob/b8ca6c9c8666057c13d0b5b89bb257f8552865e5/docs/examples/3rdparty_analysis_workflow.sh#L47) by @kyleam, but the latest version of the docs does not reflect the fix.

**Comment by kyleam** [comment]
Thanks for pointing that out.  The docs do need to be refreshed.

The current docs were built from 2020bd81 (0.12.0rc2-98), which doesn't include the commit you point to (0.12.0rc2-327-g81440485b) and are also stale in other ways compared to 0.12.0rc4.

**Comment by adswa** [comment]
Good to know, thanks!

**Comment by adswa** [comment]
Closing this, as it is now updated in the docs.
