### ISSUE TITLE
subdatasets -r does not recurse

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3509]
Discovered while messing with #3508 , thought it is my change but seems to be generic but could be result of me messing around with submodules there (was a mix of datalad versions and some screw ups while creating subsub2) but seems to be all good from checking .gitmodules. Tarball with this sample is at http://www.onerussian.com/tmp/datalad_temp_test_subds_pathyh6f2zwi.tgz

it seems that subdatasets discovery/listing is not recursing properly:
```shell
(git-annex)hopa:~/.tmp/datalad_temp_test_subds_pathyh6f2zwi[master]git
$> datalad ls -r .
.             [annex]  master  ✗ 2019-07-03/10:46:26  ✓
sub           [annex]  master  ✗ 2019-07-03/10:46:26  ✓
sub/subsub2   [annex]  master  ✗ 2019-07-03/10:46:25  ✓

$> git status
On branch master
nothing to commit, working tree clean

$> datalad subdatasets -r    
subdataset(ok): sub (dataset)

$> datalad subdatasets -r .
subdataset(ok): sub (dataset)

$> datalad subdatasets -r sub
subdataset(ok): sub (dataset)
subdataset(ok): sub/subsub2 (dataset)
action summary:
  subdataset (ok: 2)
```
current master:
```shell
$> datalad --version
datalad 0.12.0rc4.dev153

$> cd -
~datalad/datalad-master

$> git describe
0.12.0rc4-153-g2fccc29ef
```

it is ok with 0.11.x:

```shell
$> datalad subdatasets -r                        
subdataset(ok): sub (dataset)
subdataset(ok): sub/subsub2 (dataset)
action summary:
  subdataset (ok: 2)

$> datalad --version
datalad 0.11.5.dev18
```

**Comment by kyleam** [comment]
Yet to really look into it, but this bisects to 281e38c92 (BF+TST: Appropriately imitate cmdline, fix now obvious failure, 2019-05-20).  The related discussion for that change is at <https://github.com/datalad/datalad/pull/3429#discussion_r285623155>.

**Comment by kyleam** [comment]
I need to revisit gh-3429 a bit more and put together a range of different test scenarios, but I'm tempted to say that the recursive call to _get_submodules() should unconditionally use `paths=None`:

```diff
diff --git a/datalad/local/subdatasets.py b/datalad/local/subdatasets.py
index 73a75643c..0343a688f 100644
--- a/datalad/local/subdatasets.py
+++ b/datalad/local/subdatasets.py
@@ -421,7 +421,7 @@ def _get_submodules(ds, paths, fulfilled, recursive, recursion_limit,
                   recursion_limit > 1)):
             for r in _get_submodules(
                     Dataset(sm['path']),
-                    paths,
+                    None,
                     fulfilled, recursive,
                     (recursion_limit - 1)
                     if isinstance(recursion_limit, int)
```
