### ISSUE TITLE
Support IPFS special remote

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3510]
I've been playing around a bit with [git-annex's IPFS special remote][annex-ipfs].  The special remote implementation is documented as experimental and from 2015, but it still seems to work as advertised.

```
$ git annex whereis one
whereis one (1 copy) 
  	97de50fe-d40e-45e6-bd29-6c307ed4971b -- [ipfs]

  ipfs: ipfs:QmUB9Nr7RpqNYQpyh4W9r3RQNttiPQ6BQ9iQLkw9LztJFz
ok
$ git annex get one
get one (from ipfs...) 
Saving file(s) to .git/annex/tmp/SHA256E-s4--2c8b08da5ce60398e1f19af0e5dccc744df274b826abe585eaba68c525434806
 4 B / 4 B [================================================================] 100.00% 0s
(checksum...) ok
(recording state in git...)
```

But if I try to `datalad get` the a file from IPFS, DataLad doesn't think anything needs to be done.

```
$ git annex drop --force one
drop one ok
(recording state in git...)
$ datalad -f json_pp get one
{
  "action": "get",
  "path": "/tmp/gx-ipfs-HZmC5Wq/one",
  "status": "notneeded",
  "type": "file"
}
$ git annex whereis one
whereis one (1 copy)
  	97de50fe-d40e-45e6-bd29-6c307ed4971b -- [ipfs]

  ipfs: ipfs:QmUB9Nr7RpqNYQpyh4W9r3RQNttiPQ6BQ9iQLkw9LztJFz
ok
```

I think IPFS is a pretty neat option for people that want to share public data without setting up external hosting somewhere, so it'd be great to make DataLad work with the IPFS special remote.

[annex-ipfs]: https://git-annex.branchable.com/special_remotes/ipfs/

**Comment by yarikoptic** [comment]
+1 for making it work, @satra would be interested as well ;)

I am really surprised with `datalad get` failing somehow! there should be nothing remote specific.  Would you mind sharing/publishing that tiny sample repo somewhere?

**Comment by kyleam** [comment]
> +1 for making it work, @satra would be interested as well ;)

All right, more motivation for me to look into it :)

> I am really surprised with `datalad get` failing somehow! there should be nothing remote specific.

Yeah, I was too.

> Would you mind sharing/publishing that tiny sample repo somewhere?

I wouldn't mind, but I think the script to generate it is more useful, so I've included that below.  I've also dumped the resulting repo on smaug at /tmp/gx-ipfs-e8l3B8I.

<details>
<summary>script</summary>

```sh
#!/bin/sh

# Assumes you have git-annex-remote-ipfs on your path and the IPFS
# daemon running.

set -eux

cd $(mktemp -dt gx-ipfs-XXXXXXX)
git init
git annex init

git annex initremote ipfs type=external externaltype=ipfs encryption=none

echo one >one
git annex add one
git commit -mone

git annex copy --to ipfs one
git annex whereis one

git annex drop --force one
git annex whereis one

git annex get one
git annex whereis one

git annex drop --force one
git annex whereis one

datalad get one
git annex whereis one
```

</details>

**Comment by kyleam** [comment]
> > I am really surprised with `datalad get` failing somehow! there should be nothing remote specific.
> 
> Yeah, I was too.

Hmph looks like `datalad get` is may be behaving odd for me in general, and I incorrectly assumed it was related to the IPFS remote.  I'll need to debug more, but please don't waste any time troubleshooting on your end.

**Comment by kyleam** [comment]
> Hmph looks like `datalad get` is may be behaving odd for me in general, and I incorrectly assumed it was related to the IPFS remote. I'll need to debug more, but please don't waste any time troubleshooting on your end.

With my git-annex (7.20190626), `annex find --json` isn't giving the expected output:

```
$ git annex find --json --not --in=here -- one
one
```

and that is what leads to DataLad thinking the file is available.

If I use the annex from neurodebian, things look fine, including getting from the IPFS special remote:

```
$ git annex find --json --not --in=here -- one
{"bytesize":"4","mtime":"unknown","keyname":"2c8b08da5ce60398e1f19af0e5dccc744df274b826abe585eaba68c525434806","backend":"SHA256E","key":"SHA256E-s4--2c8b08da5ce60398e1f19af0e5dccc744df274b826abe585eaba68c525434806","humansize":"4 B","hashdirmixed":"0J/J1/","file":"one","hashdirlower":"171/8dc/"}
datalad get one
get(ok): /tmp/gx-ipfs-px8wztj/one (file) [from ipfs...]
```

So great, and sorry for the noise!

I'll debug `git annex find --json` a bit more on my end, and open an issue upstream if appropriate.

**Comment by yarikoptic** [comment]
lets keep it open may be for ipfs?

**Comment by kyleam** [comment]
> lets keep it open may be for ipfs?

What about it?  If you want something specific on DataLad's end (a pointer in the documentation?), I think a new, dedicated issue would be better.

**Comment by kyleam** [comment]
> I'll debug `git annex find --json` a bit more on my end, and open an issue upstream if appropriate.

For posterity: <https://git-annex.branchable.com/bugs/Regression_in___96__find_--json__96___output/>

**Comment by yarikoptic** [comment]
Heh heh heh -- thank you @kyleam !

**Comment by satra** [comment]
@kyleam - we may soon have a need for using ipfs via datalad. thanks for trying it out.
