### ISSUE TITLE
Policy on stalled PRs

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3533]
What about closing any open PR that hasn't seen any action (commit/comment/whatever) within the last, say, 6 months?

When closing a PR we could leave the origin branch as-is, so nothing would be lost. Moreover, we could file an issue for each PR closed this way which as a reminder for and pointer to the topic (unless there already is one).

ATM we have about two dozen open PRs. Quite a few have (subjectively) near-zero chance of ever being revived again, starting from the point where they are now.

**Comment by kyleam** [comment]
This was agreed on in the call.  In addition to the description above, there is now a stale-PR-closed-without-merge label.
