### ISSUE TITLE
subdatasets() slow with .get_content_info() (was much faster with custom parser)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3537]
according to http://datalad.github.io/datalad/#api.supers.time_subdatasets?machine=drogon-neurodebian10.20190322.1&branch=master

original PR #3435 if I localized it correctly

**Comment by yarikoptic** [comment]
actually looking closer it was https://github.com/datalad/datalad/pull/3429 
`distribution.subdatasets` -> `local.subdatasets`

**Comment by kyleam** [comment]
> actually looking closer it was #3429
> `distribution.subdatasets` -> `local.subdatasets`

To narrow this down to a particular commit, I think it is likely c89746c27 (RF: Rip out custom submodule parser, 2019-05-17), which replaced the custom parser from gh-2187 with `.get_content_info()`.

<details>
<summary>asv compare of `run -b api.supers.time_subdatasets`</summary>

```
All benchmarks:

       before           after         ratio
     [ba268edd]       [c89746c2]
+     11.0±0.04ms      12.5±0.03ms     1.14  api.supers.time_subdatasets [virtualenv-py2.7]
+     10.4±0.03ms      11.8±0.04ms     1.14  api.supers.time_subdatasets [virtualenv-py3.7]
+      34.6±0.2ms       63.6±0.3ms     1.84  api.supers.time_subdatasets_recursive [virtualenv-py2.7]
+     36.6±0.08ms       58.4±0.3ms     1.59  api.supers.time_subdatasets_recursive [virtualenv-py3.7]
      10.9±0.04ms      12.1±0.05ms    ~1.11  api.supers.time_subdatasets_recursive_first [virtualenv-py2.7]
+     10.3±0.03ms      11.5±0.02ms     1.11  api.supers.time_subdatasets_recursive_first [virtualenv-py3.7]
```

</details>

**Comment by mih** [comment]
Still the case as of 16ab284e80949d712da6d77ec3d58dfd17dea9f0

**Comment by mih** [comment]
Here is an uptodate comparison (with result renderer disabled, because it is irrelevant for any performance-use):

with ba268edd1
```
% python -m timeit -s "import datalad.api as dl; ds = dl.Dataset('.')" "ds.subdatasets(result_renderer='disabled')"

20 loops, best of 5: 10.6 msec per loop

```

with f7e89af1de175515f4b66bdc40ddcd0f5fdf7af3

```
% python -m timeit -s "import datalad.api as dl; ds = dl.Dataset('.')" "ds.subdatasets(result_renderer='disabled')"

10 loops, best of 5: 21.7 msec per loop

```

**Comment by mih** [comment]
Here is the state wrt today's master 8b4236cfc279ac49f5cc5fe7778780a2b22275d6

For a dataset with no subdatasets:

```
# was with ba268ed
% python -m timeit -s "import datalad.api as dl; ds = dl.Dataset('.')" "ds.subdatasets(result_renderer='disabled')"
500 loops, best of 5: 408 usec per loop

# is now
% python -m timeit -s "import datalad.api as dl; ds = dl.Dataset('.')" "ds.subdatasets(result_renderer='disabled')"
1000 loops, best of 5: 212 usec per loop
```

and for a dataset with ~1.2k subdatasets

```
# was with ba268ed
% python -m timeit -s "import datalad.api as dl; ds = dl.Dataset('.')" "ds.subdatasets(result_renderer='disabled')"
5 loops, best of 5: 73.3 msec per loop

# is now
% python -m timeit -s "import datalad.api as dl; ds = dl.Dataset('.')" "ds.subdatasets(result_renderer='disabled')"
2 loops, best of 5: 103 msec per loop
```

So depending on which end of the stick we are at, it is either twice as fast or 30% slower now.

Unless someone want to assign themselves to further exploration here, I think we can close this now. I will tag accordingly to aid future discovery.
