### ISSUE TITLE
Undesired submodule url

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3538]
Originally at https://github.com/datalad/datalad/pull/2601

`datalad install -d . -s ../raw sourcedata --reckless`

leads to

```diff
--- /dev/null
+++ b/.gitmodules
@@ -0,0 +1,3 @@
+[submodule "sourcedata"]
+       path = sourcedata
+       url = /home/data/psyinf/scratch/multires3t/bids/../raw
```

**Comment by kyleam** [comment]
Reverted in 0.12.1, but a new approach has been proposed in gh-4026.
