### ISSUE TITLE
Include benchmark comparison in dedicated travis run

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3539]
In the light of #3537 I wonder whether it wouldn't be sensible to have a dedicated travis run that performs whether is needed to enables @yarikoptic and @kyleam to compare benchmark performance. It should be sufficient to compare HEAD of a PR against whatever state of master, or even (in addition) the last release tag. If that is possible, this increasingly relevant information would be readily available for each PR -- whether or not one would expect a performance impact. It might additionally provide a great source of motivation to improve the validity and reliability of benchmark implementations.

It would probably be important to run pre and post assessment of performance within the same travis run and machine, to avoid unnecessary cross-machine differences.

**Comment by mih** [comment]
This is now available in 0.11, but hasn't made its way into master yet.

**Comment by kyleam** [comment]
Now in master.
