### ISSUE TITLE
compinit for zsh completions seems to ruin autoloading of other completions

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#354]
We use compinit but I have ran into situation that if in a new shell I haven't yet used completions for vim, but then do compinit, that is it -- no completions for vim (the same goes for git etc).  If I use vim completion before compinit, then doing compinit has no negative effect for that used already completion

```
$> autoload -U compinit && compinit
$> vim RE
_arguments:450: _vim_files: function definition file not found
_arguments:450: _vim_files: function definition file not found
```

so something to track down and address one way or another ;)

**Comment by mih** [comment]
I cannot reproduce this ancient report. I relief @yarikoptic from the burden to deal with it ;-)
