### ISSUE TITLE
0.12.0rc5 anyone?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3540]
Seems to be overdue
```shell
$> git describe origin/master
0.12.0rc4-213-g5233f3cc0
```
and I already lost track of what was added/fixed in it since May

**Comment by mih** [comment]
Yes, there should be one. Not sure when I can get to it, but it was on my list. Of course I'd cheer anyone taking the lead.

**Comment by kyleam** [comment]
I assume the most time-consuming thing is the changelog.  I can do that today.

@yarikoptic A 0.11.6 release would be good to resolve the tests that fail with the latest git (conda-forge/datalad-feedstock#14).  The 0.11.6 changelog should be complete.

**Comment by mih** [comment]
Related side note: How do you feel about a Debian package of the upcoming 0.12 series? Maybe named `datalad-0.12` and in conflict with datalad proper? I need to package the various extensions, and I cant start with that until I have a dependency that I can work with.

**Comment by yarikoptic** [comment]
@mih hmm, I guess. Or just datalad and upload to -devel of NeuroDebian? I guess the release is unavoidable

**Comment by yarikoptic** [comment]
@kyleam thanks!!
