### ISSUE TITLE
addurls: Consider supporting JSON lines

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3557]
At the moment URL-FILE can be a csv file or a JSON file with an array of records.  We could extend this to read a stream of JSON records from stdin if URL-FILE is "-".

Or alternatively we could read content from stdin as either a csv or JSON array, depending on --input-type.  Then a caller piping in a stream of JSON records could easily reformat it as an array with, say, `jq`.

The advantage of the second approach is that it doesn't limit stdin consumption to one file type and makes it clearer that addurls slurps all the records into memory rather than working with them as they come in.  The disadvantage, of course, is the need for another intermediate reformatting step.

Re: https://github.com/datalad/datalad/issues/3556#issuecomment-514604518

**Comment by yarikoptic** [comment]
+1 on the second approach.

**Comment by yarikoptic** [comment]
It would be nice if addurls supported reading from stdin (with or without json-lines support).  I have a script which combines and sanitizes multiple json files to be passed to addurls.  Now I need to save it first , and only then use for addurls.  Ideally I should be able to do it in one go without storing intermediate results
