### ISSUE TITLE
Automate update of Singularity images

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3559]
- our :fullmaster was almost a year old 
  - we didn't "touch" it for a while
  - pushed "touched" one (8e637af22f943d31d00dcc991facb7cdea55e10d) straight to master
  - [ ] TODO: we should automate (at least once a week) generation of full master (and ideally of 0.11.x) images so they live up to their promise!
- apparently singularity hook did not work at all also for the past two weeks
  - had to change webhook url from https://www.singularity-hub.org/hooks/build/push to https://singularity-hub.org/hooks/build/push
  - works now, new `:fullmaster` is built
- [x] push commit with `.0.11.5` one as soon as local test build finishes

**Comment by yarikoptic** [comment]
FWIW, "fullmaster" and new "maint" were updated yesterday: https://singularity-hub.org/collections/667.  I will adjust the title

**Comment by adswa** [comment]
With no singularity hub anymore, is this issue still possible? In light of #6298 would it make sense to build singularity and docker images with scheduled workflows and upload them somewhere?

**Comment by yarikoptic** [comment]
Correct, singularity hub is gone!
Most likely we should just concentrate on docker container and let `singularity` pull from docker.
Should we just remove `Singularity*` recipes and related stuff to close this issue?

**Comment by adswa** [comment]
> Should we just remove Singularity* recipes and related stuff to close this issue?

Unless there are other options for hosting, this sounds sensible to me.

**Comment by mih** [comment]
I also think this is the way forward. Will prep a PR.
