### ISSUE TITLE
Something fishy w/ `siblings add --as-common-datasrc` vs `siblings configure --as-c-d`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3560]
The former crashes. The underlying functionality seems untested in both cases.

@bpoldrack might add more details.

**Comment by bpoldrack** [comment]
Apparently `sibllings` maps both names to the same input variable. So, `--as-common-datasrc` takes a name that is supposed to be the name of the git-type special remote, while the name of the actual git remote is another parameter to `siblings add` and also needed when creating that kind of remote. Those two names need to be different. However, `siblings` crashes complaining about receiving parameter `name` twice.

**Comment by bpoldrack** [comment]
Also: manpage section about `--as-common-datasrc` makes little sense/is unclear. From that it's really hard to tell what that name is referring to. In addition it talks about a "created" sibling which is misleading, given that we are in none of the create-sibling-* commands.

**Comment by yarikoptic** [comment]
is this something still pertinent @mih?

**Comment by mih** [comment]
I think this has seen at least one round of fixes and tuning. Good to close. Thanks!
