### ISSUE TITLE
AppVeyor failing on master

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3572]
AppVeyor starting showing widespread failures in gh-3508, but it looks like it's actually a set of failures [that will hit master][0] starting with the next build.

The [last run for master][1] (five days ago) passed.  A [run today][2] that was based off of the same commit (with an empty commit on top) failed.  I'd guess the most likely culprit is the change in annex version: 7.20190627-g831e6746f vs 7.20190709-g15a972dd3.

[0]: https://github.com/datalad/datalad/pull/3508#issuecomment-516926981
[1]: https://ci.appveyor.com/project/mih/datalad/builds/26278166
[2]: https://ci.appveyor.com/project/mih/datalad/build/job/0ogacr7kj8ol05am

**Comment by kyleam** [comment]
This may be related to the recently reported failures of the git-annex test suite on Windows: https://git-annex.branchable.com/bugs/test_suite_fails_on_windows/

**Comment by yarikoptic** [comment]
yeap, most likely since we fail at `git annex init` with following 
```
datalad.support.exceptions.CommandError: CommandError: command '['git-annex', 'init']' failed with exitcode 1
1097Failed to run ['git-annex', 'init'] under 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_dd1758hd'. Exit code=1.
1098-------------------- >> begin captured logging << --------------------
1099datalad.distribution.clone: INFO: Cloning http://datasets-tests.datalad.org/repronim/containers [1 other candidates] into 'C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_dd1758hd'
1100datalad: INFO:  Cloning (counting objects) 100 objects done
1101datalad: INFO:  Cloning (compressing objects) 608 objects done in 0.0624974 sec at 9728 objects/sec
1102datalad: INFO:  Cloning (receiving objects) 1549 objects done in 0.0470643 sec at 32912 objects/sec
1103datalad: INFO:  Cloning (resolving stuff) 785 objects done in 0.093559 sec at 8390 objects/sec
1104datalad.annex: INFO:   Detected a filesystem without fifo support.
1105datalad.annex: INFO:   Disabling ssh connection caching.
1106datalad.annex: INFO:   Detected a crippled filesystem.
1107datalad.annex: INFO: git-annex: NUL: openFile: does not exist (No such file or directory)
1108datalad.annex: INFO: git-annex: init: 1 failed
1109--------------------- >> end captured logging << ---------------------
1110
1111
```

**Comment by kyleam** [comment]
The issues have been fixed upstream.  The [latest build][0], which used git-annex 7.20190731-gc131c0f0c, is green.

[0]: https://ci.appveyor.com/project/mih/datalad/builds/26831388
