### ISSUE TITLE
addurls blows in extract upon a csv with only the header

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3577]
Original issue: https://github.com/templateflow/datalad-osf/issues/1
which boils down to the code in addurls.py:extract
```python
    rows, colidx_to_name = _read(stream, input_type)
    ...
        metacols = (c for c in sorted(rows[0].keys()) if c != urlcol)
```
which assumes that there is at least a single data row in the stream

**Comment by kyleam** [comment]
No good :/
