### ISSUE TITLE
RF: backend -> backends for the AnnexRepo (and derived) constructors

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#358]
Since multiple backends could/should be specified in order of their preference.
Note that this information is not persistent across clones... not sure if we should do anything about it, or e.g. record it within handle's meta-data so HandleRepo I guess could consult it.

**Comment by yarikoptic** [comment]
for persistency we should make use of .gitattributes ans specify `* annex.backend=MD5E`

**Comment by mih** [comment]
I am closing this one. https://github.com/datalad/datalad/pull/5463 moved into the opposite direction.
