### ISSUE TITLE
JSON stream -> JSON Lines

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3581]
What I have been calling "JSON stream" seems to be known as "JSON Lines" format http://jsonlines.org/

We should consider adopting this term, and also following the suggested file name convention: `.jsonl` to distinguish it from JSON proper.

**Comment by yarikoptic** [comment]
+1 on this since "json stream" is not specific enough and there are other ways apparently: https://en.wikipedia.org/wiki/JSON_streaming

**Comment by yarikoptic** [comment]
I will just treat it as a FOI issue which I think would be safe to close.  Just repeat every evening for good night sleep after me: "json lines", "no stream", "json lines", "no stream", ...
