### ISSUE TITLE
datalad + openneuro integration

### ISSUE THREAD

**Issue by jasmainak** [datalad/datalad#3583]
#### What is the problem?
We're trying to use datalad in MNE with @sappelhoff and @agramfort to fetch some MEG and EEG datasets but we keep hitting roadblocks. I want to open an issue where we can list our complaints :) We were trying to update a dataset on Openneuro and [after some huff and puff](https://github.com/OpenNeuroOrg/openneuro/issues/1226) we did manage to update it. However, now we can't download the dataset using datalad.

#### What steps will reproduce the problem?
Do the following:

1. Update an openneuro dataset (ds000248 in our case)
2. Then run the following two commands:
```sh
$ datalad install https://github.com/OpenNeuroDatasets/ds000248
$ cd ds000248
$ datalad get sub-01
```
and I get

```py
Total (1 ok, 3 failed out of 4):   7%|███                                          | 10.6M/153M [00:07<01:06, 2.15MB/s][WARNING] Running get resulted in stderr output:   Remote is configured to use versioning, but no S3 version ID is recorded for this key
  Remote is configured to use versioning, but no S3 version ID is recorded for this key
  Remote is configured to use versioning, but no S3 version ID is recorded for this key
  Remote is configured to use versioning, but no S3 version ID is recorded for this key
  unknown export location
  unknown export location
  unknown export location
git-annex: get: 3 failed
 
                                                                                                                       [ERROR  ] from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 	82a4b182-753f-4d93-a59e-20cfdd4d4237 -- [s3-PUBLIC];  	e3612a8a-0c48-4374-9bfb-888f4010be54 -- root@1f69c4ed80cf:/datalad/ds000248; ; (Note that these git remotes have annex-ignore set: origin) [get(/home/mainak/data/ds000248/sub-01/anat/sub-01_T1w.nii.gz)] 
get(error): /home/mainak/data/ds000248/sub-01/anat/sub-01_T1w.nii.gz (file) [from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 	82a4b182-753f-4d93-a59e-20cfdd4d4237 -- [s3-PUBLIC];  	e3612a8a-0c48-4374-9bfb-888f4010be54 -- root@1f69c4ed80cf:/datalad/ds000248; ; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 	82a4b182-753f-4d93-a59e-20cfdd4d4237 -- [s3-PUBLIC];  	e3612a8a-0c48-4374-9bfb-888f4010be54 -- root@1f69c4ed80cf:/datalad/ds000248; ; (Note that these git remotes have annex-ignore set: origin) [get(/home/mainak/data/ds000248/sub-01/anat/sub-01_acq-flipangle05_run-01_MEFLASH.nii.gz)] 
get(error): /home/mainak/data/ds000248/sub-01/anat/sub-01_acq-flipangle05_run-01_MEFLASH.nii.gz (file) [from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 	82a4b182-753f-4d93-a59e-20cfdd4d4237 -- [s3-PUBLIC];  	e3612a8a-0c48-4374-9bfb-888f4010be54 -- root@1f69c4ed80cf:/datalad/ds000248; ; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 	82a4b182-753f-4d93-a59e-20cfdd4d4237 -- [s3-PUBLIC];  	e3612a8a-0c48-4374-9bfb-888f4010be54 -- root@1f69c4ed80cf:/datalad/ds000248; ; (Note that these git remotes have annex-ignore set: origin) [get(/home/mainak/data/ds000248/sub-01/meg/sub-01_task-audiovisual_run-01_meg.fif)] 
get(error): /home/mainak/data/ds000248/sub-01/meg/sub-01_task-audiovisual_run-01_meg.fif (file) [from s3-PUBLIC...; Unable to access these remotes: s3-PUBLIC; Try making some of these repositories available:; 	82a4b182-753f-4d93-a59e-20cfdd4d4237 -- [s3-PUBLIC];  	e3612a8a-0c48-4374-9bfb-888f4010be54 -- root@1f69c4ed80cf:/datalad/ds000248; ; (Note that these git remotes have annex-ignore set: origin)]
get(ok): /home/mainak/data/ds000248/sub-01/anat/sub-01_acq-flipangle30_run-01_MEFLASH.nii.gz (file) [from s3-PUBLIC...]
[WARNING] could not get some content in /home/mainak/data/ds000248/sub-01 ['/home/mainak/data/ds000248/sub-01/anat/sub-01_T1w.nii.gz', '/home/mainak/data/ds000248/sub-01/anat/sub-01_acq-flipangle05_run-01_MEFLASH.nii.gz', '/home/mainak/data/ds000248/sub-01/meg/sub-01_task-audiovisual_run-01_meg.fif'] [get(/home/mainak/data/ds000248/sub-01)] 
get(impossible): /home/mainak/data/ds000248/sub-01 (directory) [could not get some content in /home/mainak/data/ds000248/sub-01 ['/home/mainak/data/ds000248/sub-01/anat/sub-01_T1w.nii.gz', '/home/mainak/data/ds000248/sub-01/anat/sub-01_acq-flipangle05_run-01_MEFLASH.nii.gz', '/home/mainak/data/ds000248/sub-01/meg/sub-01_task-audiovisual_run-01_meg.fif']]
action summary:
  get (error: 3, impossible: 1, ok: 1)
```
@sappelhoff did some digging and found [this repo](https://github.com/OpenNeuroDatasets) which seems to indicate that there is some auto updating (?) being done. But it's not clear to us how long we have to wait till this has finished. I updated the dataset more than 6 hours ago and it's not more than a GB I think. Perhaps this is more an Openneuro question. _However_, even if the dataset has not been updated, I should be able to get the older version. So, I tried:

```sh
$ git checkout HEAD~1
$ ls
```
and it gave me an empty directory. I was expecting it to have the older version of the dataset, but maybe I don't understand fully here how datalad should behave.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

datalad 0.11.5

#### Is there anything else that would be useful to know in this context?

I want to know what's the easiest way to make it work in the shortest amount of time :)

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)

Would love to add a testimonial once we have it integrated in our CIs ;-)

**Comment by yarikoptic** [comment]
sorry about that 
re `get`: it seems that there might be some oddity with parallel `annex get` on a freshly cloned repo!  could be related to "Remote is configured to use versioning, but no S3 version ID is recorded for this key"  which was reported to openneuro folks almost a year ago, but apparently not yet fixed: https://github.com/OpenNeuroOrg/datalad-service/issues/79  (attn @effigies)

Filed an issue with git-annex: https://git-annex.branchable.com/bugs/fails_to___96__get__96___in_parallel_for_a_freshly_clone_from_public_s3_bucket_where_versioning_info_was_forgotten/?updated

if you do `datalad get -J 1` it should work fine, or if you let it first fail and then rerun `get` it should work too.

**Comment by yarikoptic** [comment]
re updates -- that sounds like an issue to report to https://github.com/OpenNeuroOrg/datalad-service 

re older versions -- even the openfmri version of that dataset seems to have only a single version (`//openfmri/ds000248`)

**Comment by jasmainak** [comment]
Thanks a lot for the workaround ! It works like a charm

> re older versions -- even the openfmri version of that dataset seems to have only a single version

okay I raised an issue here: https://github.com/OpenNeuroOrg/datalad-service/issues/96 :)

**Comment by jasmainak** [comment]
On second thoughts, perhaps this indicates that jobs = 1 is a better default than jobs = 'auto' ;-)

**Comment by yarikoptic** [comment]
> On second thoughts, perhaps this indicates that jobs = 1 is a better default than jobs = 'auto' ;-)

it would be a "safer" choice but not a "better" one IMHO ;)
- slower default gets
- we would discover such bugs late(r) in the game ;-)

**Comment by jasmainak** [comment]
alright, fair enough. I'm too used to the joblibs and scikit-learn world :-)

**Comment by soichih** [comment]
I found this thread by google searching for an error message that I am seeing.
> [ERROR  ] Remote is configured to use versioning, but no S3 version ID is recorded for this key


```
brlife@wrangler2:/mnt/datalad/OpenNeuroDatasets/ds000248/sub-emptyroom/meg$ datalad get sub-emptyroom_task-noise_run-01_meg.fif 
[WARNING] Running get resulted in stderr output: download failed: Not Found
download failed: Not Found
download failed: Not Found
git-annex: get: 1 failed
 
[ERROR  ] Remote is configured to use versioning, but no S3 version ID is recorded for this key
| Remote is configured to use versioning, but no S3 version ID is recorded for this key
| Remote is configured to use versioning, but no S3 version ID is recorded for this key [get(/mnt/datalad/OpenNeuroDatasets/ds000248/sub-emptyroom/meg/sub-emptyroom_task-noise_run-01_meg.fif)] 
get(error): sub-emptyroom/meg/sub-emptyroom_task-noise_run-01_meg.fif (file) [Remote is configured to use versioning, but no S3 version ID is recorded for this key
Remote is configured to use versioning, but no S3 version ID is recorded for this key
Remote is configured to use versioning, but no S3 version ID is recorded for this key]
```

I tried the `datalad get -J 1 <path>` option but it doesn't look like it has much effect..  I am guessing this is an OpenNeuro issue.. Should I file a report/complaints on their end?

**Comment by soichih** [comment]
@effigies pointed me to this thread > https://github.com/OpenNeuroOrg/openneuro/issues/1731 It looks like this is an issue with OpenNeuro and they are working on it.
