### ISSUE TITLE
[wishlist] diff --metadata "selector(s)" FILE1 FILE2

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3588]
One way or another it would be nice to provide an interface to diff metadata extracted for two files/paths.  Usecase: Could come handy to just compare DICOM header fields between two dicoms since we pre-select fields.

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
