### ISSUE TITLE
Dataset "update" procedure (convention)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3595]
I ran into this missing feature/convention before, and now I am hitting it again. The only convenient method to update a dataset from a non-DataLad resource is the crawler (i.e. `datalad crawl`). However, considering metadata composition it might be necessary (or convenient) to run code in addition to just filling up an annex, or even when no crawler is involved at all.

Here is the dataset where I hit this first: https://github.com/datalad-datasets/longnow-podcasts

At the time, I chose to write up a [few scripts ](https://github.com/datalad-datasets/longnow-podcasts/tree/master/.datalad/maint), put them in `.datalad/maint/`, and ran them through `datalad run` (https://github.com/datalad-datasets/longnow-podcasts/commit/36a30a1a1d8725658410b650d516d9d3c640427d and https://github.com/datalad-datasets/longnow-podcasts/commit/004e484d05a93c6ca46438ffe7878f8e3d53312e).

Working on https://github.com/datalad/datasets.datalad.org/issues/24 (which needs a bit more code to get scrapy to spit out the info in the table at https://openpsychometrics.org/_rawdata/ as JSON-LD) it occurred to me that such update scripts could be implemented in the form of a dataset procedure.

We would probably benefit from a naming convention for such a procedure, and potentially integrate its execution with a refurbished `update` command. https://github.com/datalad/datalad/issues/1199

Any thoughts?

**Comment by bpoldrack** [comment]
Seems to me like a per-remote config what to execute for an update (+ a possible post-processing)

**Comment by mih** [comment]
Closing "question"-type issue with a response, and no further activity.
