### ISSUE TITLE
Issues with latest release of GitPython

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3598]
With the release of GitPython v3.0.0, we have some [new test failures][0].  The main ones I spot are the flyweight_monitoring_inode tests:

```
# from https://travis-ci.org/datalad/datalad/jobs/570888123#L1125
======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_flyweight_monitoring_inode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/support/tests/test_annexrepo.py", line 2399, in test_AnnexRepo_flyweight_monitoring_inode
    check_repo_deals_with_inode_change(AnnexRepo, path, store)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/support/tests/utils.py", line 53, in check_repo_deals_with_inode_change
    hexsha = repo.repo.head.object.hexsha
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/git/refs/symbolic.py", line 193, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/git/objects/base.py", line 64, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/git/db.py", line 37, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(sha))
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/git/cmd.py", line 1077, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/git/cmd.py", line 1066, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/git/cmd.py", line 1030, in _parse_object_header
    raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
ValueError: SHA b'8097085c9fb022ad18cea2ff099fbcd13ae953be' could not be resolved, git returned: b'8097085c9fb022ad18cea2ff099fbcd13ae953be missing'
```

It looks like v3.0.0 drops support for Python 2, so I thought "we should set v3.0.0 as the ceiling in setup.py", but then I realized that the py3 builds are failing (and actually neither of the py2 ones are!).  So there's more going on here, but I haven't looked any deeper.

[0]: https://travis-ci.org/datalad/datalad/builds/570888119

**Comment by yarikoptic** [comment]
eh heh. and it is triggered by our not so trivial `check_repo_deals_with_inode_change` and only for py3.  The easiest might be just to bisect in GitPython to what change has lead to this change in its behavior?

**Comment by yarikoptic** [comment]
for some reason I feel like doing it, will try now to bisect

**Comment by yarikoptic** [comment]
<details>
<summary>eh, actually it doesn't replicate for me (ran in isolation) with 3.7 and GitPython 3.0.0 from its git repo :-/ </summary> 

```shell
$> python --version
Python 3.7.3rc1

$> python -m nose -s -v datalad/support/tests/test_annexrepo.py:test_AnnexRepo_flyweight_monitoring_inode
datalad.support.tests.test_annexrepo.test_AnnexRepo_flyweight_monitoring_inode ... ok
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=7.20190708+git36-g32d526164-1~ndall+1 cmd:bundled-git=2.20.1 cmd:git=2.20.1 cmd:system-git=2.22.0.455.g172b71a6c5 cmd:system-ssh=7.9p1 exifread=2.1.2 git=git gitdb=2.0.2 humanize=0.5.1 iso8601=0.1.11 keyring=17.1.1 keyrings.alt=3.1.1 msgpack=0.5.6 mutagen=1.40.0 requests=2.21.0 six=1.12.0 wrapt=1.10.11
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-master/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.utf8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git'

----------------------------------------------------------------------
Ran 1 test in 0.995s

OK

```
</details>

**Comment by yarikoptic** [comment]
ah -- seems to be 0.11.x specific ( I guess that code path was RFed away) -- reproduced locally and will try to bisect now

**Comment by yarikoptic** [comment]
ok, here is the (confirmed) origin: https://github.com/gitpython-developers/GitPython/commit/0b6b90f9f1e5310a6f39b75e17a04c1133269e8f

**Comment by yarikoptic** [comment]
reportbug upstream: https://github.com/gitpython-developers/GitPython/issues/907  although could still be some kind of our flyweight side effect / interaction with different behavior of GitPython.

**Comment by kyleam** [comment]
Thanks for digging.

> eh heh. and it is triggered by our not so trivial `check_repo_deals_with_inode_change` and only for py3.

I was initially confused that the failures weren't happening on py2.  That's due to the py2 builds are running with GitPython v2.1.13 because v3.0.0 dropped py2 support.

> ah -- seems to be 0.11.x specific ( I guess that code path was RFed away) -- reproduced locally and will try to bisect now

Sorry, this is my fault.  I removed GitPython usage from that test without realizing that the whole point of the test is to make sure we're not triggering a failure in GitPython.  I'll open a PR reverting that change.

> ok, here is the (confirmed) origin: [gitpython-developers/GitPython@0b6b90f](https://github.com/gitpython-developers/GitPython/commit/0b6b90f9f1e5310a6f39b75e17a04c1133269e8f)

Looking at that commit with `git show --color-moved=zebra --color-moved-ws=allow-indentation-change`, most of the changes around `.__del__()/.close()` are just code movement.  The main difference seems to be that, when `.close()` is called, the variable storing the `git.cmd.Git` object get set to None.  AFAICT the previous code retained this across `.close()` calls.  If I drop that part, `test_{Git,Annex}Repo_flyweight_monitoring_inode` pass for me.

```diff
diff --git a/git/repo/base.py b/git/repo/base.py
index 31b57a3..348474e 100644
--- a/git/repo/base.py
+++ b/git/repo/base.py
@@ -224,7 +224,6 @@ def _get_git(self):
     def _del_git(self):
         if self._git:
             self._git.clear_cache()
-            self._git = None
             # Tempfiles objects on Windows are holding references to
             # open files until they are collected by the garbage
             # collector, thus preventing deletion.
```

**Comment by yarikoptic** [comment]
> Looking at that commit with `git show --color-moved=zebra --color-moved-ws=allow-indentation-change`, most of the changes around `.__del__()/.close()` are just code movement. The main difference seems to be that, when `.close()` is called, the variable storing the `git.cmd.Git` object get set to None. AFAICT the previous code retained this across `.close()` calls. If I drop that part, `test_{Git,Annex}Repo_flyweight_monitoring_inode` pass for me.
> 
> ```diff
> diff --git a/git/repo/base.py b/git/repo/base.py
> index 31b57a3..348474e 100644
> --- a/git/repo/base.py
> +++ b/git/repo/base.py
> @@ -224,7 +224,6 @@ def _get_git(self):
>      def _del_git(self):
>          if self._git:
>              self._git.clear_cache()
> -            self._git = None
>              # Tempfiles objects on Windows are holding references to
>              # open files until they are collected by the garbage
>              # collector, thus preventing deletion.
> ```

nice catch!

**Comment by kyleam** [comment]
v3.0.1, which reverts the problematic commit with d5cc590, was released today.
