### ISSUE TITLE
should we have some default internal "git ignore"?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3607]
just spotted that I have saved a lock file:
```
$> git show --stat
commit 3ad259ea824b7737955496c2b7b22f200416ba20 (HEAD -> master)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Thu Aug 8 10:54:26 2019 -0400

    [DATALAD] Save updated subdatasets

 specs/.~lock.all_usable_data_with_covs.tsv# | 1 +
 1 file changed, 1 insertion(+)
```
so wondered if we should internally (not via .gitignore, but rather configuration setting) ignore some paths which are most likely the ones to ignore.  E.g. here `^\.~.*#$` pattern but also `^\..*\.swp` and others?

**Comment by mih** [comment]
I would want to veto such a move. It would mean that we would have to inspect each and every single path going into any git-related functionality, anticipating what might be done to/with it, break down coarse path specifications (a single directory), into fine-grained ones (all individual files, except this particular one). If we don't do that, but only watch a few places, we would be making a promise that we know we cannot keep. Moreover, only a user can known if the above claim that such a file is really undesired, is indeed true. I would not want to build more heuristics into the machine.

**Comment by kyleam** [comment]
@adswa I'm not sure if there's an appropriate spot in the handbook or if in general this is outside its scope, but perhaps it'd make sense to tell users about how they can set up global gitignore values and recommend some common patterns they might want to put there.

**Comment by adswa** [comment]
@kyleam I don't think it is out of scope at all - in fact, there is http://handbook.datalad.org/en/latest/basics/101-179-gitignore.html. So far it only shows how .gitignore files work in general, but I will add a "findoutmore" section on it. Thanks!
