### ISSUE TITLE
Adjusted unlock in Win10 WSL1 errors

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3608]
Just reporting an observation. Trying to `git annex adjust --unlock` results in :

```error: external filter 'git-annex smudge -- %f' failed 1
error: external filter 'git-annex smudge -- %f' failed
sqlite worker thread crashed: user error (SQLite3 returned ErrorProtocol while attempting to perform prepare "SELECT null from content limit 1": locking protocol(while opening database connection))
git-annex: thread blocked indefinitely in an MVar operation
```

**Comment by yarikoptic** [comment]
probably related: https://git-annex.branchable.com/bugs/__34__git_status__34___thread_blocked_indefinitely_in_an_MVar_operation/
attn: @joeyh

**Comment by yarikoptic** [comment]
actually probably this one is even closer: https://git-annex.branchable.com/bugs/WSL_adjusted_braches__58___smudge_fails_with_sqlite_thread_crashed_-_locking_protocol/

**Comment by mih** [comment]
I think we have moved on from WSL1, and are no exploring other ways that do not work ;-)
