### ISSUE TITLE
Helper to automate creation of Debian data packages for existing hybrid code/data software project repos

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#361]
This is not directly concerned with goals of the DataLad project but I think this issue tracker would be the most appropriate and most probably should be implemented within datalad (or as some kind of plugin...).  I want to outline the idea and seek your feedback on how to improve it or botcher it.

Our use-case example is http://github.com/neurodebian/freesurfer (atm ~64MB .git/objects after repacking) -- upstream provides multi-GB git/annex repo with data and some pre-built libraries intermixed with source code.  autotools used to 'install' data, which entails also extracting from archives and copying (so annex links are dereferenced) everything under installation path.

With the support of the content from archives, and eventual helpers for git-annex based debian packages, datalad can provide a really nice helper to facilitate creation of debian packages through following steps:
- Register original annex as 'git' special remote
- Given a "source" git-annex, go through it and in a dedicated branch (`incoming-processed`? ;) ) add content of all found annexed archives.  
- Publish 'enhanced' annex ANNEX somewhere (e.g. github) without data but now with datalad supported archive URLs so any installable data file could be fetched through annex from original upstream (or our clone somewhere) git/annex
- Do normal installation procedure for the project and then
  a. initiate in the installed "root" directory an annex which would either be new or a clone (without files checked out) of one from previous build and having ANNEX as a remote.  Actually may be just a branch (again checked out without files) within the same ANNEX thus we could easily reuse it and not breed git/annexes
  b.  traverse the installed tree, while under specified paths/filename patterns, based on the checksum matching the used annex backends find files which are available under annex and "annex add" them
  c.  move annexed files into a separate (e.g. -data) package

Concern with above is in the case when multiple packages are desired (-data, -data-nonfree, -doc) which then should ideally reuse the same git/annex.  May be then there could be an -data package which would provide the annex to overlay but without instruction to fetch any load (besides may be some common).  Then separate packages (-data-nonfree, ...) would depend on it and only do additional fetching of necessary files in their debhelper scripts, thus not really shipping any data.  This way we can provide any necessary level of granularity while keeping only a single git/annex to be installed and small debian packages

@hanke -- I would be really eager to hear your opinion on this ;)

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.

But also ping @aqw for awareness re upcoming Debian-related projects.
