### ISSUE TITLE
datalad addurls does not ask for credentials but gives an error

### ISSUE THREAD

**Issue by TobiasKadelka** [datalad/datalad#3610]
While trying to reproduce the addurl-command I get an error. This is probably caused by missing aws s3 credentials. I think, last time I got asked for the aws secret key and the aws access key, but this time just the error message comes up.

```
(hirni) tkadelka@brainbfast in ~/HCP/HCP on git:master
❱ datalad addurls  /data/BnB_USER/Kadelka/next.csv '{original_url}' '{subject}/{filename}'
                                                                                                                              addurls(error): /home/homeGlobal/tkadelka/HCP/HCP/123420/HCP_1200/123420/release-notes/Diffusion_unproc.txt (file) [AnnexBatchCommandError: command 'addurl'
Error, annex reported failure for addurl (url='s3://hcp-openaccess/HCP_1200/123420/release-notes/Diffusion_unproc.txt'): {'file': '123420/HCP_1200/123420/release-notes/Diffusion_unproc.txt', 'command': 'addurl', 'success': False} [annexrepo.py:add_url_to_file:1819]]
```

**Comment by kyleam** [comment]
[ transferred to DataLad repo ]

> While trying to reproduce the addurl-command I get an error. This is probably caused by missing aws s3 credentials. I think, last time I got asked for the aws secret key and the aws access key, but this time just the error message comes up.

`datlad addurls` maps directly to `git annex [options] --file FILE URL`.  That means that it only support URLs that `git annex addurl` understands, and [it doesn't know how to handle s3://][0].  This is in contrast to `datalad download-url`, which goes through DataLad's providers.  For public buckets, the URL can be reformatted as `https://s3.amazonaws.com/<bucket>/<object>`.  I guess to support private buckets we'd have to make it possible for `addurls` to go through DataLad providers.

[0]: https://git-annex.branchable.com/todo/Natively_support_s3__58____47____47___urls___40__for_addurl__44___get__44___etc__41__/

**Comment by yarikoptic** [comment]
yep.  Try enabling datalad special remote:
```
git annex initremote datalad type=external externaltype=datalad encryption=none
```
@mih - is that something `datalad siblings enable` already can do somehow?

to verify that it is not just credentials try
```
datalad ls s3://hcp-openaccess/HCP_1200/123420/release-notes/Diffusion_unproc.txt
```

**Comment by kyleam** [comment]
> yep. Try enabling datalad special remote (before running `addurls`):

Seems worth expanding on given that it contradicts what I wrote above.  How does the datalad special remote help when `datalad addurls` calls `git annex addurl` (via `GitRepo add_url_to_file`)?

**Comment by kyleam** [comment]
> > yep. Try enabling datalad special remote (before running `addurls`):
> 
> Seems worth expanding on given that it contradicts what I wrote above. How does the datalad special remote help when `datalad addurls` calls `git annex addurl` (via `GitRepo add_url_to_file`)?

And I should do the expanding, since it's my statement that's wrong.  To revise my comment from above:

> That means that it only support URLs that `git annex addurl` understands, and [it doesn't know how to handle s3://](https://git-annex.branchable.com/todo/Natively_support_s3__58____47____47___urls___40__for_addurl__44___get__44___etc__41__/).

... unless you enable the `datalad` remote, as @yarikoptic suggests.

> I guess to support private buckets we'd have to make it possible for `addurls` to go through DataLad providers.

... or enable the `datalad` remote, as @yarikoptic suggests

No contradiction now :]

**Comment by yarikoptic** [comment]
correct ;)

**Comment by TobiasKadelka** [comment]
Thanks.
`git annex initremote datalad type=external externaltype=datalad encryption=none`
worked totally fine. And know the datalad addurls works again.
