### ISSUE TITLE
AppVeyor: test_autoenabled_remote_msg intermittently hanging

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3617]
We've seen several cases across a few PRs where an AppVeyor run fails with `test_clone.test_autoenabled_remote_msg` as the last line.  This has occurred more than looking through the AppVeyor build history suggests because we've restarted some cases, but here are [two][0] [examples][1].

[0]: https://ci.appveyor.com/project/mih/datalad/builds/26865864/job/8fsb0oqbnyb9gvlm#L879
[1]: https://ci.appveyor.com/project/mih/datalad/builds/26901081/job/7by401uxrnl15q1w#L846

**Comment by kyleam** [comment]
Popped up again: https://ci.appveyor.com/project/mih/datalad/builds/27034823/job/8e7fsxl8pr5dpguf

**Comment by yarikoptic** [comment]
poped up again: https://ci.appveyor.com/project/mih/datalad/builds/29049064/job/gtoqg37p4tkh93n3 of  https://github.com/datalad/datalad/pull/3888 - restarting that build now

**Comment by mih** [comment]
Haven't seen this in quite a while.
