### ISSUE TITLE
run-procedure --discover report strange location

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3619]
I am in a subdir inside a dataset
```
% datalad run-procedure --discover
cfg_text2git (../git/datalad/resources/procedures/cfg_text2git.py) [python_script]
cfg_yoda (../git/datalad/resources/procedures/cfg_yoda.py) [python_script]
cfg_metadatatypes (../git/datalad/resources/procedures/cfg_metadatatypes.py) [python_script]
```

The relative paths do not  point to the scripts. Possibly the paths are reported relative to the dataset I am in, but they should be relative to the subdirectory IMHO.

**Comment by bpoldrack** [comment]
Minor comment: My guess is they are relative to datalad installation root dir.
