### ISSUE TITLE
include api command into NAME of the manpage

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#362]
ATM
```
NAME
       datalad - add content of an archive under git annex control

SYNOPSIS
       datalad  add-archive-content
```
ideally name should include add-archive-content somehow

**Comment by hanke** [comment]
Had a first look. This is insane. I tried to create new commands with a symlinked helper tool to that $0 would equal to "datalad-somecmd"... still NAME says "datalad" only. I modified the usage output with --help-np to say "datalad-somecmd", yet the NAME still remains "datalad".

At this point I don't know where help2man gets it from.

**Comment by yarikoptic** [comment]
Gotcha... I just thought it was under our immediate control. A little of sed could come for the rescue I guess
