### ISSUE TITLE
Shlex_quote() values instead of ""-ing placeholders in run-procedure

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#3625]
Noting down an issue @kyleam brought to attention in https://github.com/datalad/datalad/pull/3624#discussion_r317657539:

Within 
https://github.com/datalad/datalad/blob/c9abcb0b3c4e91bb3df1721c8bcd2d7d60371461/datalad/interface/run_procedure.py#L182-L193

placeholders should be stripped of the quotes, and values should be passed through shlex_quote().

**Comment by mih** [comment]
Merged into 0.11 now.
