### ISSUE TITLE
Missing ability to point to a custom/user git-annex installation on an SSH remote

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3641]
We do try to find `git` as bundled with `git-annex` , but we have no way to configure where a remote `git-annex` can be found. Problem related to https://git-annex.branchable.com/forum/not_finding_git-annex-shell_on_remote/

Workaround could be to define `remote.<name>.annex-shell` locally, as a config setting for an `install` command -- but it doesn't work.

Because the `enableremote` fails, the remote is set to `annex-ignore`. Once `annex-shell` is configured *afterwards*, and `annex-ignore` is removed manually, things start working.

So custom annex installs are possible, but are needlessly hard to configure. We could add some kind of convenience mechanism that fixes the config up as necessary.

Ping @dickscheid

**Comment by yarikoptic** [comment]
> but we have no way to configure where a remote `git-annex` can be found

but would we be able to "configure" remote environment anyhow but by modifying remote `~/.profile` to  include target desired installation of git-annex into the `PATH`?

PS I agree that the "jumpiness" of git-annex to declare a remote to be ignored is quite annoying at times.  With a single repo it is ok to manage but then I think I had cases installing superdatasets and getting it marking it all repos in the hierarchy.

**Comment by mih** [comment]
FTR: The original issue was addressed by https://github.com/datalad-handbook/book/issues/177
