### ISSUE TITLE
`download-url` vs `addurls`?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3643]
I would like to get feedback on the purpose of `download-url` now that we have `addurls`. There is a significant overlap. Additionally `download-url` needs an overhaul wrt path handling (e.g. use of `normpath` inside), i.e. transition it to use pathlib.

Q is now: is there anything that speaks against stripping any functionality from `download-url` that works with datasets (e.g. actually saving downloaded files in a dataset)?

#### Pros

- it would make the command do what the name suggests -- download and download only
- it would reduce the overlap with `addurls`

#### Cons

- it complicates adding a single/few files to a dataset from a set of URLs (but given there is `git annex addurl`, and `addurls` not much is lost)

**Comment by yarikoptic** [comment]
I agree that we have inconvenient and inconsistent in naming overlap between the two.
I would though prefer to avoid stripping "dataset related" functionality from download-url, which actually was added only recently.  Also it has unique functionality of doing download/addition of tarballs conent.
 It came out to be a frequent use case to be able to download and save to dataset (and register url within annex).
But I wonder if we should unify (more) with addurls.  May be
- `download-url` could be RFed to be just a specific interface to addurls (preparing all needed records and delegating everything else to addurls).    
- I think I would be ok to strip it of an ability to download multiple urls/files at once, then we could rename it into `addurl`, which might make things a bit more consistent at least in naming

**Comment by kyleam** [comment]
> Additionally `download-url` needs an overhaul wrt path handling

It has already seen a bit of attention in f38d72c68 (BF: download_url: Update for new path resolution logic, 2019-06-03), so it's probably in better shape than a fair number of commands.

> (e.g. use of `normpath` inside),

In the above commit I probably should have replaced the block that contains `normpath` with use of `rev_resolve_path`.

> i.e. transition it to use pathlib.

That doesn't seem necessary for following the new path handling conventions.

**Comment by kyleam** [comment]
> But I wonder if we should unify (more) with addurls. May be
> 
> * `download-url` could be RFed to be just a specific interface to addurls (preparing all needed records and delegating everything else to addurls).

This would come with a change in behavior.  download-url goes directly through the providers while addurls downloads the file with `git annex addurl ...`.

It's not clear to me that forcing download-url to use addurls buys us anything.  Assuming we want to keep download-url functionality like --archive, I would guess that it will make the code less readable and harder to reason about.

> * I think I would be ok to strip it of an ability to download multiple urls/files at once, then we could rename it into `addurl`, which might make things a bit more consistent at least in naming

IMO a one character difference (i.e. `datalad addurl{,s}`) makes the situation worse.

**Comment by mih** [comment]
> > Additionally `download-url` needs an overhaul wrt path handling
> 
> It has already seen a bit of attention in [f38d72c](https://github.com/datalad/datalad/commit/f38d72c68b6ae7c1af9d3e9ab32b9f10b2254c64) (BF: download_url: Update for new path resolution logic, 2019-06-03), so it's probably in better shape than a fair number of commands.

You are correct, sorry about that -- only had a brief look and the first impression was wrong.
> 
> > (e.g. use of `normpath` inside),
> 
> In the above commit I probably should have replaced the block that contains `normpath` with use of `rev_resolve_path`.

I agree.

> > i.e. transition it to use pathlib.
> 
> That doesn't seem necessary for following the new path handling conventions.

True, there are more important things to be done ;-)

**Comment by mih** [comment]
I think it is fine to close this issue at this point. Thx for the input.
