### ISSUE TITLE
FOI: fragility of some tests due to a good obscure name

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3645]
while building a perspective 0.11.7 package.  Many tests started (in comparison to 0.11.6 build) started to fail.   
```shell
root@smaug:/tmp/buildd/datalad-0.11.7# grep ERROR build.lo
datalad.distribution.tests.test_create.test_create_with_obscure_name ... ERROR
datalad.distribution.tests.test_dataset.test_require_dataset(' "\';a&b&cΔЙקم๗あ `| ',) ... ERROR
datalad.interface.tests.test_add_archive_content.test_add_archive_content ... ERROR: File /tmp/datalad_temp_test_providers_enter_newzlhr8gmp/providers/exists.cfg already exists, choose another name
ERROR: Provided regular expression doesn't match original url.  Please re-enter
datalad.interface.tests.test_run_procedure.test_quoting ... ERROR
datalad.plugin.tests.test_plugins.test_wtf ... ERROR
ERROR: datalad.distribution.tests.test_create.test_create_with_obscure_name
ERROR: datalad.distribution.tests.test_dataset.test_require_dataset(' "\';a&b&cΔЙקم๗あ `| ',)
ERROR: datalad.interface.tests.test_run_procedure.test_quoting
ERROR: datalad.plugin.tests.test_plugins.test_wtf
```

major cause/problem is within git-annex, not sure if I reported it before (I do have some feeling that I did) but here it is https://git-annex.branchable.com/bugs/fails_to_init_under_a_directory_with_a___34__tricky__34___name/ and I think it should be addressed properly .

why we didn't see them before -- those are either new tests or only started to use obscure filename after previous release.

for this release at least I might just make obscure filename (in debian package) less obscure (no unicode) for the purpose of testing.

**Comment by mih** [comment]
FTR: The same thing happens on Windows.

**Comment by yarikoptic** [comment]
FTR, @joeyh [fixed underlying issue](https://git-annex.branchable.com/bugs/fails_to_init_under_a_directory_with_a___34__tricky__34___name/#comment-0e85995f7a04cf79c2d951f590d8de82) in the likely to be released process-1.6.5.2 library. Ignorant in haskell me not sure what to look for among debian packages since there is no `process` mentioned in debian/control, and the only library package I find is libghc-process-extras-dev which is at 0.7.4-3+b3 .  May be it something bundled within ghc itself, @joeyh?

**Comment by joeyh** [comment]
Yes, process is bundled with ghc, although that does not prevent
installing a newer version.

-- 
see shy jo

**Comment by yarikoptic** [comment]
not sure if worth keeping it open here. still don't know which ghc would carry the fixed `process` but I guess time will heal the issue automagically
