### ISSUE TITLE
Take a look at and possibly adopt or better support OpenNeuro extensions

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3651]
Context and references at https://github.com/OpenNeuroOrg/datalad-service/issues/105#issuecomment-528017978

Key functionality:
- Full report on dataset content (related to `status` and its low-level helpers)
- "is dataset clean" check (again related to `status`)

Maybe we could start by benchmarking what we have and compare it to https://github.com/OpenNeuroOrg/datalad-service/blob/c9c8d8e970b168755f7b979b4bd4f1c07b8cc2b4/datalad_service/common/annex.py#L87

**Comment by kyleam** [comment]
> * Full report on dataset content (related to `status` and its low-level helpers)

It sounds like their starting point was GitRepo.get_files(), so I suspect GitRepo.get_content_info() would have been an improvement for them.  They landed on a similar `ls-tree, cat-file --batch` design.  Perhaps the processing approaches or just Runner overhead results in get_content_info() being noticeably slower, so as you suggest a benchmark would be very useful.

> * "is dataset clean" check (again related to `status`)

I might be missing some other spot where they use a custom is dirty check, but AFAICT [they use our GitRepo.is_dirty()][0].  In that case they [shouldn't see a slowdown][1] when switching the current .dirty that was introduced in 9d29d13bc (OPT: gitrepo.dirty: Use 'git status --porcelain', 2019-05-26).

[0]: https://github.com/OpenNeuroOrg/datalad-service/blob/c9c8d8e970b168755f7b979b4bd4f1c07b8cc2b4/datalad_service/tasks/draft.py#L6-L9
[1]: https://github.com/datalad/datalad/pull/3460#discussion_r288778925

**Comment by mih** [comment]
I am closing this now, due to its age and because we spent the past years moving into a direction that should make the identified functionality more accessible and also faster.

@nellh @effigies please let us know, if something is missing or still problematic. Thx!
