### ISSUE TITLE
Different names to refer to procedures with run-procedures and create -c

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#3652]
This is remotely related to  #2649.

I'm writing up a section on procedures, and found it confusing that ``datalad run-procedure`` uses the procedure name with a ``cfg`` prefix (e.g. ``datalad run-procedure cfg_yoda``) but when I apply the configuration template within ``create`` I need to call it without the prefix  (e.g. ``datalad create -c yoda someds``).
Would it be useful to call the procedures in a uniform manner, or am I missing an obvious reason for this?

**Comment by kyleam** [comment]
See #3353 for the PR that added this.

The idea with that `--cfg-proc` exposes all procedures that start with `cfg_`, so we can express things more succinctly letting it be referred to by the last bit.

**Comment by mih** [comment]
The connection is that `create -c` will only accept `cfg_*` procedures which, by pure convention, must not require any arguments to run. This was done to not complicate the `create` API too much. In general, procedures can have any number of (required) arguments.

**Comment by adswa** [comment]
thanks for the insights!
