### ISSUE TITLE
flaky test test_run_inputs_outputs 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3653]
ran into while building 0.11.7 package for neurodebian 16.04:

```
======================================================================
ERROR: datalad.interface.tests.test_run.test_run_inputs_outputs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.11.7/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 442, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/build/datalad-0.11.7/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.11.7/.pybuild/pythonX.Y_2.7/build/datalad/interface/tests/test_run.py", line 770, in test_run_inputs_outputs
    ds.run("touch dummy{}".format(idx), inputs=inputs_arg)
  File "/usr/lib/python2.7/dist-packages/wrapt/wrappers.py", line 557, in __call__
    args, kwargs)
  File "/build/datalad-0.11.7/.pybuild/pythonX.Y_2.7/build/datalad/distribution/dataset.py", line 527, in apply_func
    return f(**kwargs)
  File "/usr/lib/python2.7/dist-packages/wrapt/wrappers.py", line 518, in __call__
    args, kwargs)
  File "/build/datalad-0.11.7/.pybuild/pythonX.Y_2.7/build/datalad/interface/utils.py", line 499, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/wrapt/wrappers.py", line 518, in __call__
    args, kwargs)
  File "/build/datalad-0.11.7/.pybuild/pythonX.Y_2.7/build/datalad/interface/utils.py", line 487, in return_func
    results = list(results)
  File "/build/datalad-0.11.7/.pybuild/pythonX.Y_2.7/build/datalad/interface/utils.py", line 474, in generator_func
    msg="Command did not complete successfully")
IncompleteResultsError: Command did not complete successfully [{'status': u'error', 'message': u'transfer already in progress, or unable to take transfer lock; Unable to access these remotes: origin; Try making some of these repositories available:; \t395cdc5e-95fd-4153-b21d-464202175ae6 -- pbuilder@smaug:/tmp/datalad_temp_tree_test_run_inputs_outputs17DsJJ [origin]', 'annexkey': u'MD5E-s5--ab16016d9717ecbc869d549ac0ca18aa.dat', 'action': u'get', 'path': u'/tmp/datalad_temp_test_run_inputs_outputssTjSyw/b.dat', 'type': u'file', 'refds': u'/tmp/datalad_temp_test_run_inputs_outputssTjSyw'}]
```

**Comment by yarikoptic** [comment]
happened again on cron travis run:  https://travis-ci.org/datalad/datalad/jobs/583295860  so something special about that test ;-)

**Comment by yarikoptic** [comment]
@kyleam 1.5 years ago you annotated that test as `@slow  # ~10s`.  

<details>
<summary>For me locally ATM it takes ~60s! </summary> 

```shell
$> ( set -e; for s in {1..100}; do python -m nose -v datalad/interface/tests/test_run.py:test_run_inputs_outputs; done ) 
datalad.interface.tests.test_run.test_run_inputs_outputs ... ok

----------------------------------------------------------------------
Ran 1 test in 60.776s

OK
  39.20s user 25.29s system 103% cpu 1:02.22 total
datalad.interface.tests.test_run.test_run_inputs_outputs ... ok

----------------------------------------------------------------------
Ran 1 test in 68.931s
```
</details>

I wondered on what is the run time for you these days? ;)  The test has changed since then, so it might have just became "heavier"... or may be my laptop is that old???

**Comment by kyleam** [comment]
> @kyleam 1.5 years ago you annotated that test as `@slow # ~10s`.
> For me locally ATM it takes ~60s!
> 
> I wondered on what is the run time for you these days? ;)

I've just executed the test three times.  All runs came in around ~23s.

> The test has changed since then, so it might have just became "heavier"...

That test has certainly become larger (too large).  That slow annotation came when it was ~40 lines.  It's now ~140 lines.  (Not to mention the underlying code is more involved.)

**Comment by kyleam** [comment]
Regarding the flakiness: It's curious that it has popped up twice in a short interval, but AFAIK none of use has seen it before.  That test and the underlying code haven't been touched for a while.

**Comment by yarikoptic** [comment]
So it is likely then git annex to blame

**Comment by yarikoptic** [comment]
and again on cron https://travis-ci.org/datalad/datalad/jobs/609358155#L1869 , previously python 3.6 now 3.7

**Comment by kyleam** [comment]
It's continued to fail intermittently.  I gave an attempt at an ugly workaround in gh-3716, but I wasn't able to trigger the workaround with any of the builds for that PR.

It would of course be better to fix the underlying issue, but that's difficult when it doesn't reliably fail on Travis and I haven't been able to get it to fail even once locally.

**Comment by yarikoptic** [comment]
FWIW I also have failed to reproduce locally :-(  not yet sure what factor to introduce (tried to `nice` the process etc) to cause it... actually looking at the original report -- it triggered while building debian package.  May be I will put that one on loop until it fails so at least there is hope to get in the susceptible environment

**Comment by yarikoptic** [comment]
On some hundred whatever rerun I ended up triggering it:
```
datalad.interface.tests.test_run.test_run_inputs_outputs ... > /build/datalad-0.11.8/datalad/interface/utils.py(474)generator_func()
-> msg="Command did not complete successfully")
(Pdb) l
469                                     for act in sorted(action_summary))))
470     
471                 if incomplete_results:
472                     raise IncompleteResultsError(
473                         failed=incomplete_results,
474  ->                     msg="Command did not complete successfully")
475     
476             if return_type == 'generator':
477                 # hand over the generator
478                 lgr.log(2, "Returning generator_func from eval_func for %s", _func_class)
479                 return generator_func(*args, **kwargs)
(Pdb) p incomplete_results
[{'type': 'file', 'refds': '/tmp/datalad_temp_test_run_inputs_outputsqm9a569m', 'status': 'error', 'path': '/tmp/datalad_temp_test_run_inputs_outputsqm9a569m/c.txt', 'action': 'get', 'annexkey': 'MD5E-s5--d394994e9541622e8018542d886abaa8.txt', 'message': 'transfer already in progress, or unable to take transfer lock; Unable to access these remotes: origin; Try making some of these repositories available:; \t088cedcc-a08e-4ab4-8a64-d72785630c37 -- root@smaug:/tmp/datalad_temp_tree_test_run_inputs_outputsv3qpxcvo [origin]'}]
```
and of cause manual re-get worked out
```
root@smaug:/tmp/buildd/datalad-0.11.8# cd /tmp/datalad_temp_test_run_inputs_outputsqm9a569m
root@smaug:/tmp/datalad_temp_test_run_inputs_outputsqm9a569m# git annex get /tmp/datalad_temp_test_run_inputs_outputsqm9a569m/c.txt
get c.txt (from origin...) 
MD5E-s5--d394994e9541622e8018542d886abaa8.txt
              5 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/1)
(checksum...) ok
(recording state in git...)
root@smaug:/tmp/datalad_temp_test_run_inputs_outputsqm9a569m# cat .git/config 
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = /tmp/datalad_temp_tree_test_run_inputs_outputsv3qpxcvo
        fetch = +refs/heads/*:refs/remotes/origin/*
        annex-uuid = 088cedcc-a08e-4ab4-8a64-d72785630c37
...
```
so it does smell like some racing in git-annex (attn @joeyh )

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> [{'type': 'file', 'refds': '/tmp/datalad_temp_test_run_inputs_outputsqm9a569m', 'status': 'error', 'path': '/tmp/datalad_temp_test_run_inputs_outputsqm9a569m/c.txt', 'action': 'get', 'annexkey': 'MD5E-s5--d394994e9541622e8018542d886abaa8.txt', 'message': 'transfer already in progress, or unable to take transfer lock; Unable to access these remotes: origin; Try making some of these repositories available:; \t088cedcc-a08e-4ab4-8a64-d72785630c37 -- root@smaug:/tmp/datalad_temp_tree_test_run_inputs_outputsv3qpxcvo [origin]'}]

> so it does smell like some racing in git-annex (attn @joeyh )

Either multiple threads or multiple processes have tried to download the
same key concurrently. This is very easy to reproduce, just start a get
and run it again in another terminal.

-- 
see shy jo

**Comment by yarikoptic** [comment]
hm... I will try to dig out more, but :

- my initial hint on that it could be the same key was wrong (so there would be transfer from it from multiple threads) -- then seems to fail differently https://git-annex.branchable.com/bugs/parallel_get_to_the_files_for_the_same_key_would_fail_with__thread_blocked_indefinitely_in_an_STM_transaction/?updated
- it feels that it is something to be addressed at git annex level one way or another.   message is too ambiguous (is it about transfer? or unable to acquire a lock? or actually cannot access remote?) . If transfer is in progress -- annex imho should wait (with some time out) until transfer completes.  If lock is not available -- wait for it (with some timeout) to become available and verify if transfer is needed. Time out might be even very long if from lock information it knows that it is some other live git-annex process on the same box.  And it is not that `origin` was not available here (it was) so it shouldn't complain about that here.

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> hm... I will try to dig out more, but :
> 
>   • my initial hint on that it could be the same key was wrong (so there would
>     be transfer from it from multiple threads) -- then seems to fail
>     differently https://git-annex.branchable.com/bugs/
>     parallel_get_to_the_files_for_the_same_key_would_fail_with__thread_blocked_indefinitely_in_an_STM_transaction
>     /?updated

But that's a closed bug report from 2017. The current behavior if two threads
both try to transfer the same key would be the same as what you showed.

>   • it feels that it is something to be addressed at git annex level one way or
>     another. message is too ambiguous (is it about transfer? or unable to
>     acquire a lock? or actually cannot access remote?

The message is "transfer already in progress, or unable to take transfer
lock". There's a later, more general error message displayed at a higher
level. (I don't know what is making them be separated by "; " , it does not
seem to be done by git-annex.)

> If transfer is in
> progress -- annex imho should wait (with some time out) until transfer
> completes. If lock is not available -- wait for it (with some timeout)

This has been discussed before, I think even between us. Waiting will
cause git-annex to block if another git-annex, running a transfer, is
suspended, or has been blocked. A timeout gets right back to the current
behavior, so there's no guarantee that a failure can't happen due to
another process running the transfer.

-- 
see shy jo

**Comment by joeyh** [comment]
Joey Hess wrote:
> But that's a closed bug report from 2017. The current behavior if two threads
> both try to transfer the same key would be the same as what you showed.

Nm, I thought you meant a different bug report, not the one you just
opened.

-- 
see shy jo

**Comment by kyleam** [comment]
As far as a I know, we haven't seen this failure in a long time.
