### ISSUE TITLE
Performance observations with large subdataset numbers

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3655]
I created 1000 datasets (not particular content). That takes about 500ms per dataset on my laptop. I used this code (yeah, lazy, I know)

```python
 [dl.create('/'.join((str(uuid.uuid4())[:2], str(uuid.uuid4())))) for i in range(1000)]  
```

Adding them to a superdataset worked without issues. However the results have the wrong type (`file`).

A superdataset with 1000 empty subdatasets weighs 315 MB on the filesystem.

```
% datalad save 
...
add(ok): ff/b143ff42-85c4-4d6f-bcc7-c4d9c6fd50cc (file)
add(ok): ff/e4287631-3e94-4183-9a68-e7f84d87c99d (file)
add(ok): .gitmodules (file)
save(ok): . (dataset)
action summary:
  add (ok: 1001)
  save (ok: 1)
datalad save  132.18s user 59.01s system 100% cpu 3:11.04 total
```

Subdataset reporting seems to be speedy and working fine.

```
% datalad subdatasets
...
subdataset(ok): ff/e4287631-3e94-4183-9a68-e7f84d87c99d (dataset)
action summary:
  subdataset (ok: 1000)
datalad subdatasets  0.72s user 0.18s system 96% cpu 0.933 total
```

A save attempt on the (clean) superdataset is a bit sluggish though

```
% time dl save
datalad save  35.30s user 18.30s system 100% cpu 53.371 total
```

Uninstall is a problem:

```
% datalad uninstall -r --nocheck */*
uninstall(ok): /tmp/alot/ff/e4287631-3e94-4183-9a68-e7f84d87c99d (dataset)
uninstall(ok): /tmp/alot/ff/b143ff42-85c4-4d6f-bcc7-c4d9c6fd50cc (dataset)
...
action summary:
  uninstall (ok: 1000)
datalad uninstall -r --nocheck */*  301.58s user 131.57s system 99% cpu 7:15.19 total
```

The superdataset's `.git` weighs ~25MB, and it has

```
% git count-objects 
1002 objects, 23436 kilobytes
```

roughly 25KB per subdataset.

**Comment by yarikoptic** [comment]
Would be nice to have it as a benchmark if we don't have any. May be just use 100 datasets

**Comment by mih** [comment]
Ping @loj @bpoldrack this is the relevant starting point when we are going for 30k+ subdatasets.

**Comment by loj** [comment]
I did the same as @mih, except with 33,000 subdatasets. Creating the subdatasets took around 10 hours.

 `[dl.create('/'.join((str(uuid.uuid4())[:2], str(uuid.uuid4())))) for i in range(33000)] `

The datalad save took around 24 hours.

```
% datalad save 
...
add(ok): ff/f52908dc-6bd5-4bfb-93e2-1bf42be2042f (file)
add(ok): ff/f9173ecf-abc9-4d07-8bce-d18f38d22867 (file)
add(ok): .gitmodules (file)
save(ok): . (dataset)
action summary:
  add (ok: 33001)
  save (ok: 1)
```

```
% time datalad subdatasets
...
subdataset(ok): ff/f9173ecf-abc9-4d07-8bce-d18f38d22867 (dataset)
subdataset(ok): ff/fa856977-a2d8-4128-bf42-93755e6bff26 (dataset)
action summary:
  subdataset (ok: 33000)
datalad subdatasets  16.26s user 4.13s system 75% cpu 27.000 total
```
```
% time datalad status -t raw -e commit
datalad status -t raw -e commit  109.67s user 268.82s system 44% cpu 14:10.55 total
```
A save attempt on the (clean) superdataset:
```
% time datalad save
datalad save  345.73s user 1797.46s system 42% cpu 1:24:35.61 total
```
```
% datalad --version
datalad 0.12.0rc5
```

**Comment by bpoldrack** [comment]
FTR: I'll try the same thing as @loj  on faster drives and with rc6, since the FS "situation" on that machine may contribute quite a lot to those numbers.

**Comment by yarikoptic** [comment]
With rc6 I expect it to only become slower, ref: https://github.com/datalad/datalad/issues/3766 . I can be proven to be wrong
