### ISSUE TITLE
`uninstall --recursive *` does not recurse into subdatasets

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3661]
Here is what I see:

```
% datalad uninstall -r --nocheck *
uninstall(impossible): /tmp/alot/00 (directory) [can only uninstall datasets (consider the `drop` command)]
uninstall(impossible): /tmp/alot/01 (directory) [can only uninstall datasets (consider the `drop` command)]
...
```

The structure of the dataset is this (the uuid-like directories are the actual subdatasets)

```
.
├── 00
│   ├── 0ea832de-bec0-45a9-989f-c0376394d6e6
│   ├── 3790b8c2-1beb-494c-a5a5-189ccb9737b6
│   ├── 4255e451-d5d4-4829-8053-8c2e55c9a647
│   ├── f339565c-345f-42ce-a7ed-f83e1733a237
│   └── f617fc62-0b65-4471-97f4-f8d006f929a2
├── 01
│   ├── 1c9a767d-0b4c-4214-a8b3-403666191251
│   ├── 545dd1fc-b816-4725-a11f-1aafbb71a6bf
│   ├── 67d925e2-1bd9-4ec3-9e04-be15aa5f49e1
│   ├── 884cb78d-02ee-4762-86fc-4b02f96e0e7f
│   ├── 8b773663-eb54-4c7e-bfc2-06ddfb83c6d8
│   ├── ad1461b2-40d8-4983-bbb0-8d5b125045a7
│   ├── d92e1877-f2f2-403d-ac81-dd747c34a234
│   └── f673af13-1fe8-44c3-aa52-e382299c59e4

```

I somewhat expected the above command to uninstall any subdatasets that match the given path, everything underneath the given path (because `--recursive`).

Question is: what should we do, if we call `uninstall` with a path to a directory that has two subdatasets underneath, but **no** recursive is given?

**Comment by yarikoptic** [comment]
Without -r shouldn't uninstall them I guess unless path points direct it to them

**Comment by mih** [comment]
Q is: what does recursion mean in this case. I can never uninstall a top-level subdataset without recursively uninstalling all potential subdatasets. So in the best case, this is just a flag that, if absent, prevents any operation in the case of subsubdatasets.

**Comment by bpoldrack** [comment]
Hm. Absence of `--recursive` could cause the command to still try to uninstall datasets further down, but not passing `--nocheck`, `--if-dirty`.
However, I agree - it's a weird UI indeed.
Somewhat related: The default for `--if-dirty` is `save_before`. Doesn't seem to make a lot of sense for an `uninstall`, since you'd create a commit only to instantly loose it.
