### ISSUE TITLE
Reporting special remotes

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#3664]
As of now, we (still) don't properly report special remotes via `AnnexRepo.get_remotes()`. This can be solved by using `git-annex-info` via `AnnexRepo.repo_info()`, I think (I'll issue a PR right after writing this issue). 
However, `datalad-siblings` also fails to report them and I'm not quite sure whether or not that is what we want. To clarify: I'm talking about actual special remotes, that don't come with any `remote.<name>.something` in the config files like https://github.com/datalad/git-annex-ria-remote
Since `siblings` does rely on the same call, it does filter those results out (didn't look too deeply into how). That might well be intentional and if it isn't we may want to decide now, that it should indeed be that way. On the pro side, a key store isn't an actual sibling. It might not be a repository and it might even have no idea of a history at all. Also, if you want to act upon results of `datalad-siblings` the treatment could possibly be very different, which would complicate things.
On the other hand, there currently is no way to get a list of all remotes via CLI. (Via python there will be, assuming that my PR makes it into master.)

What do you think, @datalad/developers ?

**Comment by mih** [comment]
As the resulting PR was closed unmerged, I think enhancing `siblings()` is the more viable/useful approach (also enhances the cmdline API). As there is already an issue for this #2884, I am closing this one.
