### ISSUE TITLE
Web documentation points to nonexistent command datalad-containers-run

### ISSUE THREAD

**Issue by dnkennedy** [datalad/datalad#3671]
#### What is the problem?
http://docs.datalad.org/projects/container/en/latest/generated/man/datalad-containers-run.html?highlight=containers-run
there is no 'datalad-containers-run' command
there is 'datalad containers-run'
As a user this confused me for a bit.

![image](https://user-images.githubusercontent.com/1349212/64880526-68640f00-d626-11e9-84e1-d10388abc1e6.png)

**Comment by yarikoptic** [comment]
dashes of cause are present for all commands.

also look at the sidebar menu.  It mixes up cmdline interface help (man pages) and Python API docs in the same list which is confusing as well.  At least we could split them into "Command line" and "Python" sections there (if possible)

**Comment by mih** [comment]
This bug seems to be present in all extension docs, but *not* in the main docs. It would make sense to have clones of this issue in the respective github projects, and close this one here -- but keeping it for now.

**Comment by loj** [comment]
Based off the extensions listed in https://github.com/datalad/datalad-extensions, the docs for the following extensions have this problem:
* datalad-neuroimaging ([issue](https://github.com/datalad/datalad-neuroimaging/issues/89))
* datalad-container ([issue](https://github.com/datalad/datalad-container/issues/153))
* datalad-hirni ([issue](https://github.com/psychoinformatics-de/datalad-hirni/issues/199))

I've opened clones of this issue in those repos. I think this issue can be closed now.

**Comment by mih** [comment]
Thanks @loj not just for the more appropriate issue locations, but also for the respective PRs!
