### ISSUE TITLE
run wishlist: run record to record user-invoked command

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3673]
#### What is the problem?

Our run record ATM records the actual ran command, and not the actual original invocation of `datalad *run`: we place all the inputs outputs etc.  In the case of `datalad-containers-run` execution, we even add a prefix for invocation via container.
Although it makes it possible to `rerun` exactly that command, it is ATM not so easy to "re-execute" that command with some modifications, e.g. adding, removing or changing some command option, or in the case of `datalad container` possibly switching to use another container.

It would be nice if we recorded the original invocation (e.g. `"datalad containers-run -n containers/bids-mriqc  --input sourcedata --output . '{inputs}' '{outputs}' participant group"`), i.e. exact command line if ran from the command line or Python invocation signature somewhere in the record (or sidecar).  This would allow easy "human reexecution" with possible modification of the command.

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
