### ISSUE TITLE
[wishlist] copy/move command to support copying annex availability/metadata across repos

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3681]
ATM it is not trivial to copy an annexed file(s) from one dataset to another, while trying to preserve information about its availability via URLs (from web and other remotes).    Use cases are

- copying a subset of files from a large repo into a smaller / more targetted one
- moving files from one dataset into another (e.g. withing a hierarchy of datasets)

`move` is just a special case which would entail running `remove` after `copy`, although still desiring that `--no-drop` for remove for the majority of the use cases I see (https://github.com/datalad/datalad/issues/2673)

Following actions should be done when copying files from one repo to another:

- annex level metadata should be copied as well
- register those urls from the original repository in the target repository for annexed file
- If some URLs are handled via special remotes, we should also init/enable those remotes in the target repo.  If a remote with such a name already exists, we could verify if parameters are the same, and if not -- warning/crash/ignore (config var) and/or inform the parameters to the user

### http(s)
Usecase from @satra is to get/use a few files from freesurfer repo.  It is not pragmatic to just add that repo as a remote so annex could fetch files from it since that repo's .git/objects is already >600MB.  That usecase is a bit trickier:  files do not have URLs associated with them, but the remote is available via http (https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/repo/freesurfer.git) and the actual load is somewhere there under [annex/objects](https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/repo/freesurfer.git/annex/objects/) but because it is a bare repo special remote (ref: [annex docs](http://git-annex.branchable.com/internals/hashing/)), annex/objects cache paths use different layout from the one on a clone on a regular clone. 
```bash
> git annex examinekey --format='${hashdirlower}' SHA256E-s200057528--a4da07a728f5cfac9c20e600e0c2ca0417ebd4e92f89aca1faddb11793b12c7a.tar.gz
958/132/% 
```
<details>
<summary>so `examinekey` could be used to deduce the cache dir and compose the url :</summary> 

```shell
$> wget 'https://surfer.nmr.mgh.harvard.edu//pub/dist/freesurfer/repo/annex.git//annex/objects/958/132/SHA256E-s200057528--a4da07a728f5cfac9c20e600e0c2ca0417ebd4e92f89aca1faddb11793b12c7a.tar.gz/SHA256E-s200057528--a4da07a728f5cfac9c20e600e0c2ca0417ebd4e92f89aca1faddb11793b12c7a.tar.gz'
--2019-09-16 09:45:36--  https://surfer.nmr.mgh.harvard.edu//pub/dist/freesurfer/repo/annex.git//annex/objects/958/132/SHA256E-s200057528--a4da07a728f5cfac9c20e600e0c2ca0417ebd4e92f89aca1faddb11793b12c7a.tar.gz/SHA256E-s200057528--a4da07a728f5cfac9c20e600e0c2ca0417ebd4e92f89aca1faddb11793b12c7a.tar.gz
Resolving surfer.nmr.mgh.harvard.edu (surfer.nmr.mgh.harvard.edu)... 132.183.240.105
Connecting to surfer.nmr.mgh.harvard.edu (surfer.nmr.mgh.harvard.edu)|132.183.240.105|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 200057528 (191M) [application/x-gzip]
Saving to: ‘SHA256E-s200057528--a4da07a728f5cfac9c20e600e0c2ca0417ebd4e92f89aca1faddb11793b12c7a.tar.gz’

    SHA256E-s200057528--a4da07a728f5cfac9   4%[==>   
```
</details>

may be there is even more straightforward way to obtain such URLs directly from git-annex? (attn: @joeyh)  i.e. for every file to be `get`'ed to just report the urls from which it could be obtained (possibly including ssh, see below)

### ssh

In some cases (probably primarily for private repos without data being shared publicly), the only remotes carrying data would be clones over ssh. So instead of `http*` urls, `ssh://` urls should be created. git-annex ATM does not natively support them, but there is a TODO: https://git-annex.branchable.com/todo/support_ssh__58____47____47___or_sftp__58____47____47___urls_via___34__built-in__34___ssh_support/  so in principle/future it should be feasible.

**Comment by mih** [comment]
I am running into the same issue. In my context it is not the size of the source repo that is too big, it is that the number of source repos is way to large and constructing a tailored dataset with just the relevant pieces is a much leaner and more practical input data to serve as a dependency for an analysis.

It is unclear to me how we could comprehensively achieve this without breaking too many assumptions. I think registered URL could indeed be transplanted, but files in the regular network of distributed annexes would likely have to be "merged" -- maybe following the strategy outlines in https://github.com/datalad/datalad/issues/600, likely with some kind of post-merge cleanup running.

**Comment by yarikoptic** [comment]
I wonder if all those numerous source (ssh etc) repos could be added [as "cache" remotes](https://git-annex.branchable.com/tips/local_caching_of_annexed_files/) just may be with higher cost, but so that their availability is not merged in, but so that local git-annex knows that there is a remote (so there is uuid in .git/config) from which it could try getting that content.
