### ISSUE TITLE
save provides no details for an error (in case of permission issues)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3685]
```shell
(git)smaug:/mnt/btrfs/datasets/datalad/crawl/dicoms/salo/MEEPI[master]6ET_MB4
$> datalad save -m 'initially downloaded from gdrive .zip' complex_multiecho_phantom_data.zip
add(error): 6ET_MB4/complex_multiecho_phantom_data.zip (file)
action summary:
  add (error: 1)
  save (notneeded: 1)
```
the actual reason could be unveiled only by running with `-l debug`:
```shell
...
[DEBUG  ] Determined 1 datasets for saving from input arguments 
[DEBUG  ] 1 path(s) to add to <AnnexRepo path=/mnt/btrfs/datasets/datalad/crawl/dicoms/salo/MEEPI (<class 'datalad.support.annexrepo.AnnexRepo'>)> {'6ET_MB4/complex_multiecho_phantom_data.zip': {'state': 'untracked', 'type': 'file'}} 
[DEBUG  ] Running add resulted in stderr output:   6ET_MB4/complex_multiecho_phantom_data.zip: setFileMode: permission denied (Operation not permitted)
git-annex: add: 1 failed
 
add(error): 6ET_MB4/complex_multiecho_phantom_data.zip (file)
```
initially detected with datalad 0.12.0rc4.dev330 and tested then with current master 0.12.0rc5.dev60.
I expected some `ERROR` level log msg or some other indication in the results renderer. But  json record contains no message or stderr from the original invocation:
```
$> datalad -f json_pp save -m 'initially downloaded from gdrive .zip' complex_multiecho_phantom_data.zip
{
  "action": "add",
  "key": null,
  "path": "/mnt/btrfs/datasets/datalad/crawl/dicoms/salo/MEEPI/6ET_MB4/complex_multiecho_phantom_data.zip",
  "refds": "/mnt/btrfs/datasets/datalad/crawl/dicoms/salo/MEEPI",
  "status": "error",
  "type": "file"
}
{
  "action": "save",
  "path": "/mnt/btrfs/datasets/datalad/crawl/dicoms/salo/MEEPI",
  "refds": "/mnt/btrfs/datasets/datalad/crawl/dicoms/salo/MEEPI",
  "status": "notneeded",
  "type": "dataset"
}
```
so I guess the proper fix would be to somehow channel error/stderr within this record so it could be rendered?

**Comment by bpoldrack** [comment]
Actually, I think this needs a fix in annex.

```
$ git annex add more --json
  more: setFileMode: permission denied (Operation not permitted)
{"command":"add","success":false,"file":"more"}
git-annex: add: 1 failed
```
For consistency with other JSON results, that message should be included in the JSON in a field `'note'`.

**Comment by yarikoptic** [comment]
ok, channeled to git annex issues: https://git-annex.branchable.com/bugs/add_--json_should_provide_a___34__note__34___with_an_error_message_in_case_of_an_error/?updated

**Comment by yarikoptic** [comment]
should be closed with a version of git-annex which resolves it

**Comment by mih** [comment]
Turns out that this isn't `git annex` per se, but our use of it. We need to

1. Call git-annex with `--json-error-messages`
2. Adjust our result generation to extract the messages

I will look into this.
