### ISSUE TITLE
Reimplement branch querying helpers around `git for-each-ref`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3703]
Relevant for #2970 

Concrete targets are:

- `get_active_branch()`
- `get_branches()`
- `get_remote_branches()`

**Comment by kyleam** [comment]
This sounds good in general and I'll look at #3705 later today.

>     * get_active_branch()

For this one, I'd say `git symbolic-ref --short HEAD` would be better than for-each-ref.

**Comment by mih** [comment]
Oh perfect! I was hoping that posting this issue would reveal this knowledge. Thx!
