### ISSUE TITLE
known_failure_v6_or_later is in effect only when version forced via global datalad.repo.version

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3706]
In the light of #3648 and while troubleshooting https://github.com/datalad/datalad-crawler/issues/55 I saw that the test marked as `@known_failure_v6_or_later` was not skipped although default version for the repositories now should be 7... and looking at the code the reason is obvious:
```python
def known_failure_v6_or_later(func):
    """Test decorator marking a test as known to fail in a v6+ test run

    If datalad.repo.version is set to 6 or later behaves like `known_failure`.
    Otherwise the original (undecorated) function is returned.
    """

    from datalad import cfg

    version = cfg.obtain("datalad.repo.version")
    if version and version >= 6:

        @known_failure
        @wraps(func)
        @attr('known_failure_v6_or_later')
        @attr('v6_or_later')
        def v6_func(*args, **kwargs):
            return func(*args, **kwargs)

        return v6_func

    return func
```

so we would skip only when we force default repo version to be >= 6, so with annex having v7 as default we wouldn't skip those (for better or for worse).

I am not sure yet if we should treat it as a bug (and fix it by eg considering also a version of annex) or a feature (that actually virtually no tests blew up) and start deprecating this decorator ;)

**Comment by kyleam** [comment]
> I am not sure yet if we should treat it as a bug (and fix it by eg considering also a version of annex) or a feature (that actually virtually no tests blew up) and start deprecating this decorator ;)

5db9ee007 (TST: skip_v6_or_later: Consider whether v5 is supported by git-annex, 2019-09-03) in gh-3648 adjusts skip_v6_or_later, so I think we should give the same treatment to known_failure_v6_or_later.  (I'm guessing I didn't because no tests in datalad core use it.)  That should then resolve the crawler failure, but of course the crawler should really be updated to work with v7 repos given that the latest annex auto-upgrades to them.

**Comment by yarikoptic** [comment]
ah cool, I should have checked those others

yes, some TLC to the crawler would be the best way forward in the long(er) run. good news is that probably there is not that much to do? (since tests were not failing)

meanwhile I think it might be best if you indeed fix up `known_failure_v6_or_later` and we then just could close that https://github.com/datalad/datalad-crawler/pull/57 without merge.

**Comment by kyleam** [comment]
> meanwhile I think it might be best if you indeed fix up `known_failure_v6_or_later` and we then just could close that [datalad/datalad-crawler#57](https://github.com/datalad/datalad-crawler/pull/57) without merge.

OK, working on it now.
