### ISSUE TITLE
Dataset.repo access (within loops)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3711]
It just occurred to me that `Dataset.repo` makes a lot of tests when we already have a `Repo` instance attached to a `Dataset`. All these tests would and do happen everytime when the repo accessor is used in a (tight) loop. This may or may not have a significant performance impact in real life, but it is worth keeping it in mind and avoid going through this accessor repeatedly, if possible.

**Comment by yarikoptic** [comment]
would be nice to know/have pointers to the "tests" we are talking about here.  Some (e.g. annex version etc) IIRC should be lazy and run only once.

**Comment by mih** [comment]
I am specifically talking about `Dataset.repo`. I don't see it being very lean. The first conditional is block that always runs is:

```
       if self._repo is not None and realpath(self.path) == self._repo.path:
```

That alone needs to traverse the filesystem (`realpath`), if there is a repo instance present (standard case).

Next up is flyweight processing (unavoidable), and a bunch more filesystem poking (`is_valid_repo()`).

That is happening pretty much for every single access of a non-corner case Dataset instance.

Now if you look at `Dataset.config`, it has `if self.repo is None:` as its first line...

**Comment by mih** [comment]
I think we can close this now, because there is no single future time where this would be solved forever. We just need to keep it in mind.
