### ISSUE TITLE
Investigate fate of AnnexRepo.add()

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3714]
After a future removal of the obsolete old `save()` and `add()` `AnnexRepo.commit()` is completely bypassed by high-level API code. However, there are a bunch of tests specifically for this function. It needs to be investigated inhowfar those tests test something that is relevant for the `save()` code paths, and/or what parts of `save()` can or need to move into `AnnexRepo.commit()` to remain valid and useful.

Same issue for `AnnexRepo.add()`. It is not used by `save()`. Instead there is `AnnexRepo._save_add()`.

**Comment by mih** [comment]
General feeling during initial discussion in conference call was that the Repo classes are internal API. Hence those methods could be removed, when no longer needed internally.

The situation is complicated by the fact that old code (e.g. the crawler) still uses the Repo API as the primary API. So in practice we will have to carry this burden for a while -- knowing that bitrot will accumulate in them.

**Comment by yarikoptic** [comment]
> ... Repo classes are internal API.

As long as they are exposed as `Dataset.repo`, they are not.  
We have made a similar mistake to expose GitPython's `.repo` as `*Repo.repo` and now e.g. our prominent openneuro downstream uses them: https://github.com/OpenNeuroOrg/datalad-service/search?q=.repo&unscoped_q=.repo&type=Code (at times even `.repo.repo`). So pruning should be done with care or at least keeping openneuro folks aware (as was done in the past).

> The situation is complicated by the fact that old code (e.g. the crawler) still uses the Repo API as the primary API.

yeah, DataLad's grand-father crawler needs to be RFed to start using higher level API. Possibly we could avoid full "compatibility" RFing, but rather only RF main used crawling pipelines to use new interface/implementation.

**Comment by kyleam** [comment]
@yarikoptic:
>  our prominent openneuro downstream uses them: https://github.com/OpenNeuroOrg/datalad-service/search?q=.repo&unscoped_q=.repo&type=Code (at times even `.repo.repo`). So pruning should be done with care or at least keeping openneuro folks aware (as was done in the past).

No need to look too far into the past.  The same discussion that spurred the comment you're replying to led the following discussion on their side:

* https://github.com/OpenNeuroOrg/datalad-service/pull/114#issuecomment-540262800

  A comment where you say, "We are thinking to overhaul those classes which we primarily see as the internal interface."

* https://github.com/OpenNeuroOrg/datalad-service/issues/116

**Comment by mih** [comment]
#4168 removes `AnnexRepo.commit()`

**Comment by mih** [comment]
The `add()` methods in both Repo classes are obsolete now. I will propose a PR that replaces all remaining use of them in the tests and a few other places.

**Comment by mih** [comment]
After the stalled #4872 I am now preparing a new PR that will use the approach from https://github.com/datalad/datalad/pull/6010 to move these methods into -deprecated.

**Comment by mih** [comment]
I am closing this old issue of mine. There is clearly no interest in this.
