### ISSUE TITLE
Get file size before downloading?

### ISSUE THREAD

**Issue by joeyzhou98** [datalad/datalad#3717]
#### What is the problem?
Just a quick question: Is it possible to get a file size before downloading it?
#### What steps will reproduce the problem?
No steps
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.11.6
#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
A little bit

**Comment by kyleam** [comment]
>  Is it possible to get a file size before downloading it?

I'm assuming you're talking about a file that is already stored in annex but not present locally.  You can call `git annex info FILE` or, with 0.12.x series of datalad, call `datalad status --annex -- FILE`.

**Comment by joeyzhou98** [comment]
@kyleam How can we install datalad version 0.12.x? I can't seem to find it on pip

**Comment by kyleam** [comment]
@joeyzhou98:

> @kyleam How can we install datalad version 0.12.x? I can't seem to find it on pip

It's available as a release candidate, so you can `pip install datalad==0.12.0rcN`, where N is currently 5.

**Comment by joeyzhou98** [comment]
@kyleam is there a way to call `datalad status --annex -- FILE` through the python api?

**Comment by kyleam** [comment]
> @kyleam is there a way to call `datalad status --annex -- FILE` through the python api?

Yes, see `pydoc datalad.api.status`.  (In general you can replace `status` with whatever command you're interested in.)

So something like

```python
import datalad.api as dl

ds = dl.Dataset("/path/to/some/dataset")
results = ds.status(path=<path or list of paths>, annex="basic", result_renderer=None)
```

**Comment by mih** [comment]
Given that the answer is on record, I will close this now. Feel free to reopen, if there is a need.
