### ISSUE TITLE
datalad (singularity) run singularity image

### ISSUE THREAD

**Issue by bpinsard** [datalad/datalad#3745]
#### What is the problem?
On an HPC I use datalad in a singularity container (to have the required up-to-date git-annex), but if I want to datalad run a preprocessing pipeline that is a singularity image, of course it won't find singularity in the datalad container.

eg.
```
$ singularity run  datalad.sif run -i .... -i ...  'singularity run .... fmriprep.sif ......'
[INFO   ] Making sure inputs are available (this may take some time) 
[INFO   ] == Command start (output follows) ===== 
/bin/sh: 1: singularity: not found
[INFO   ] == Command exit (modification check follows) ===== 
```

Is there any smart way around that limitation?
Or do I necessarily need to manually compile git-annex in the home folder and install datalad in a virtualenv on the HPC instead of using singularity?

Thanks.

**Comment by kyleam** [comment]
I think someone will be able to give a better answer than I can, but a couple thoughts:

  * I have a vague memory that singularity doesn't let you run singularity from within.  I haven't bothered confirming that with searching or testing though.

  * Given the requirement to have git-annex/datalad in the container, the only workable approach that comes to mind is to build a custom container that has git-annex, datalad, and fmriprep, and then do `singularity run 'datalad run fmriprep ...'`.

**Comment by kyleam** [comment]
> Or do I necessarily need to manually compile git-annex in the home folder and install datalad in a virtualenv on the HPC instead of using singularity?

Another option would be to install git-annex/datalad via conda.

**Comment by yarikoptic** [comment]
I would recommend going conda way too. 
https://github.com/datalad-handbook/book/blob/473b337bba4663af9d157eb1a90bece7dfd4c40b/docs/intro/installation.rst#linux-neurodebian-ubuntu-and-similar-systems had a complete example using miniconda if there is no conda there yet

**Comment by bpinsard** [comment]
Thanks for the advises.
I will try again with conda, I remember it to be really slow on the HPC.

**Comment by mih** [comment]
This might be useful: https://github.com/datalad-handbook/book/issues/177
