### ISSUE TITLE
check_git_configured() performs inadequate check

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3750]
This function is called whenever the first repo instance is created, i.e. for any commandline execution once. It invokes `git config` twice to check for `user.name` and `user.email`.

I have two issues with that.

1. it is inadequate for figuring out what it wants to see (git configured to make proper commits with meaningful IDs), because it only checks the config, but ignores all other possibilities.

```
      user.email
           Your email address to be recorded in any newly created commits. Can be
           overridden by the GIT_AUTHOR_EMAIL, GIT_COMMITTER_EMAIL, and EMAIL environment
           variables. See git-commit-tree(1).

       user.name
           Your full name to be recorded in any newly created commits. Can be overridden
           by the GIT_AUTHOR_NAME and GIT_COMMITTER_NAME environment variables. See git-
           commit-tree(1).
```

2. Paying the price of two `git config` calls before there even is a repo seems inappropriate. It may be better to perform such a check whenever the first git config is loaded into the config manager, instead of handling this in `GitRepo`. Both `Repo` and `Dataset` have `ConfigManager` instances that engage `git config anyways.

**Comment by yarikoptic** [comment]
I am ok with delaying the check, but not sure how it would help 1, which is probably a separate issue (can't check ATM if git config call itself doesn't consult those env cars for sure)
