### ISSUE TITLE
Fate of logging of results

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3752]
At present, any result that passes through the core event loop and has a logger instance attached, get a corresponding log message. This leads to generally duplicate reporting. For example:

```
% datalad save
[ERROR  ]   that3: setFileMode: permission denied (Operation not permitted) [add(/tmp/perm/that3)] 
add(error): that3 (file) [  that3: setFileMode: permission denied (Operation not permitted)]
```

I propose to demote all log messages triggered like this to a level less than `info`, hence remove them from the default user experience.

Rational: "error/impossible"-type events can be caused by non-faulty probing behavior and those should not clutter the terminal with scary inconsequential messages. Still logging any of such events at a lower level keeps them accessible for debugging. In addition, any faulty behavior that only leads to an "error" log message, without a corresponding "error" result is likely a bug (e.g. not leading to non-zero exit code, on-failure handling not controllable, etc.).

If that is not acceptable, an alternative solution to a cleaner UX is to no longer add a logger to the result records -- but that is clearly inferior for a developer perspective.

**Comment by yarikoptic** [comment]
Duplication is indeed unpleasant but it is better than silent failing it just operating not as expected. It is not always possible to just rerun work a different log level.
I feel that there should either be explicit control (khe khe - option to the run, expect_error alike expect_stderr) or handling (alike swallow_logs)

**Comment by mih** [comment]
What is "run" in this context?

**Comment by yarikoptic** [comment]
Execution of any datalad command. They aren't atomic, so re- retuning might start from a different state.

**Comment by mih** [comment]
Hmm, dont get it then. You want to have a cmdline arg that enables users to disable the double logging of results?

Just to be clear, any result gets a log message, regardless where it is coming from, and what is the originating command. Do you also propose that any disabling arg must be handed of to any called command inside any other command?
