### ISSUE TITLE
FOI: notes on globus for possible future support via special remote

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3758]
globus.org says "Globus lets you share data on your storage systems with collaborators at other institutions. You specify what data. You specify which colleagues. Globus manages access simply and securely, so you can focus on your research."

I have got initial good experience (after installing their globus-connect-personal, and establishing authentication via orchid, my id is 0000-0003-3456-2493@orcid.org) with a download of a 800GB dataset.

Possible cons of globus:
- it is not entirely "not for profit"  endeavor. From https://www.globus.org/subscriptions it seems that we could only get "File transfer" for free. Which should be sufficient to satisfy the "consumer" need in our use case
- but many institutions seems to come onboard, so it might be that in some cases depositing to globus end points would also be feasible (even if not truly free of charge)
There was an interest to see such a remote from @gi114 in [the issue #3632](https://github.com/datalad/datalad/issues/3632#issuecomment-530899992) .

So here I have decided to collect some notes on what I find, since it seems the "globus ecosystem" is "too rich" to get an immediate idea on how to get it done.

For the basic data access it seems only 3 pieces should be needed:
- access token (looks like a UUID) -- seems to be needed even for access to public data
- endpoint UUID for the globus resource to download from (e.g. it is `558c54fe-cc41-11e8-8c6a-0a1d4c5c824a` for `NYU Langone Health DTN1 - Buzsakilab Public Datasets`; there is also some kind of a "legacy name" `nyulangonehealth#558c54fe-cc41-11e8-8c6a-0a1d4c5c824a`)
- path within the resource

It might be that also receiving side should have its own endpoint UUID.

So I think it should be feasible to distill minimal "client" invocation to be able to download content from/via globus. Underneath I believe it is GridFTP which does actual transfer, but there is need for establishing additional "layer" to establish those GridFTP transfers.

There might be multiple clients out there.  I have not looked yet into official `globus` cmdline interface (not avail in Debian).  So was searching for other lean implementations

# globus-url-copy

Available from globus-gass-copy-progs package in Debian with minimal set of dependencies.
Found via HOWTO on http://www.prace-ri.eu/data-transfer-with-gridftp/ . But it seems it requires explicit URLs, and doesn't operate at the basis of "endpoint UUID"

# Globus Python SDK

https://globus-sdk-python.readthedocs.io/en/latest/  
Seems to have lean dependencies and should provide all needed API. We would need 
- authenticate and obtain a token -- not yet clear which way, but https://globus-sdk-python.readthedocs.io/en/latest/examples/authorization/# should have example
- [create or update (if was created before for the repo?) local endpoint](https://globus-sdk-python.readthedocs.io/en/latest/clients/transfer/#globus_sdk.TransferClient.create_endpoint)
- initiate/carry out transfer (waiting for it to finish) -- something along the lines here https://globus-sdk-python.readthedocs.io/en/latest/examples/advanced_transfer/?highlight=transfer

ok, hopefully I will find more time to dig more later on, unless someone beats me to it  before then ;)

**Comment by yarikoptic** [comment]
ha ha -- I see @gi114 already taking a stab at establishing special remote: https://github.com/gi114/GLOBUSannex !

**Comment by mih** [comment]
Closing FOI
