### ISSUE TITLE
simplify access to benchmarks results (for PRs) + establish "failure" indication

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3771]
# Simplify

I will make tools/ci/benchmark-travis-pr.sh accept parameters for what to do -- `run` or `compare` and split then invocation in the action workflow into two, so we could easily jump to compare

# Failure

I think that benchmarks run should fail whenever ratio exceeds pre-specified amount (default is 1.1 as used to group benchmark results).  I do not immediately see any option in `asv compare` to indicate presence of regressions via exit code, so we might just use some grep etc.

edit wishlist item for asv: https://github.com/airspeed-velocity/asv/issues/884

**Comment by mih** [comment]
I think this is a reality for quite a while now.
