### ISSUE TITLE
Brainstorming for "git annex unlock" use

### ISSUE THREAD

**Issue by mih** [datalad/datalad#378]
We need to think about with which API we want to allow people to enable modification is annex'ed files.

**Comment by yarikoptic** [comment]
I guess something like a new "edit" interface function?  I guess I should also allow it in "AutomagicIO" mode, where for now I am just fetching new files upon request, BUT I could also unlock the ones which are attempted to be opened for writing

**Comment by bpoldrack** [comment]
I think we should stick to lock/unlock. These are proper terms regardless
of whether or not you know about annex.

2016-03-22 13:30 GMT+01:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by hanke** [comment]
Makes sense.

**Comment by hanke** [comment]
Please check #453. Going to v6 repos changes the picture quite a bit.
