### ISSUE TITLE
Adding return-type-based methods to GitRepo

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3789]
This is bringing up a topic that I mentioned on the call where we were talking about how we should handle changes to the GitRepo class (and is essentially elaborating on [this old comment of mine][0]).  I think trying to provide lots of methods that wrap different Git subcommands is a painful approach.  It leads to us adding a one-off methods that do the bare minimum for the use case we have at that time.  That is a good thing if the code is meant to be used internally because there's no point in trying to support and test knobs we don't need (and git commands sure do have lots of knobs).  But it doesn't make for a nice external interface, and it leads to churn and incompatibilities when we later need to extend the method for another use case.

My preference instead would be to move towards having a restricted set of methods where our wrapping is really adding something to the plain git calls (`get_content_info` and friends are perhaps the nicest examples of this).  For many other things, I don't think we need a dedicated method for the subcommand.  Instead we can have a few methods that wrap specific kinds of calls.  Here are some examples, ignore some arguments like `expect_stderr` that we'd probably need.  (I didn't give the names much thought, so just consider them placeholders; they mostly follow magit, which has a nice set of functions like this.)

  * `.call_git(args, files=None)` => None

    Call git for side effects, letting the CommandError through if it's raised.

    Example:
    `.tag("name", message="msg")` => `.call_git(["tag", "-m", "msg", "name"])`

  * `.git_success(args, files=None)` => boolean

    Call git for the exit code.  Return False for non-zero exits.

    Example:
    `is_ancestor("a", "b")` => `.git_success(["merge-base", "--is-ancestor", "a", "b"])`

  * `.git_lines(args, files=None)` => list of str

     Call git for newline-separated output, letting the CommandError through if it's raised.

  * `.git_str(args, files=None)` => str

     Call git for a single line of output, letting the CommandError through if it's raised.  Raise an error if output is more than a single line.

  * `.git_items(args, files=None)` => list of str

     Call git for null-separated output, letting the CommandError through if it's raised.

I think introducing these would have the following benefits:

  * It is a set of commands that we can offer to third-party callers if they need a command that we don't have but still want to call git through us.

  * Likewise, it is a set of commands we can use to avoid adding one-off methods.

  * We already use `_git_custom_command` in many spots outside of gitrepo.py to avoid adding more methods to GitRepo.  These new methods would simplify these calls.

  * If we decide to deprecate a method or change it in an incompatible way, we can point to these methods as an alternative.

I'm not suggesting that we rip out the old methods that we already have.  I'm suggesting that, by adding this return-value based methods, we could avoid needlessly adding methods in the future.  When we have a new case that calls for a method (e.g., we need special error handling or processing of the results), we should of course still add the method.

Thoughts?

[0]: https://github.com/datalad/datalad/issues/2879#issuecomment-426759137

**Comment by mih** [comment]
I am very much in favor of this!

It would be good to keep generator-style return values in the picture. This is the only thing that I would consider worthwhile adding.

**Comment by kyleam** [comment]
> It would be good to keep generator-style return values in the picture.

Good point.  There's no reason `.git_{lines,items}` shouldn't yield.

**Comment by mih** [comment]
OK, so how do we go about this? I have the impression that @kyleam has a good concept already, but maybe we can find a mode where not just one person alone has to carry the weight.

It seems that with function definitions like proposed above in place, we can implement them pretty much in-full with what we have scattered around the code base. Maybe not optimally performant, but functional.

**Comment by kyleam** [comment]
My plan was to put up a draft PR today as the base that implements (something like) the methods above and replaces some obvious `_git_custom_command` calls with them.  That'd give us something concrete to extend or iterate on.

**Comment by bpoldrack** [comment]
I also like that approach!

As for "how to proceed": I think that's a general issue. We don't have a clear place where to put a conceptual approach on a particular aspect of further developing the code base,  so that everybody can find and follow it. Same is true for new(er) command implementation styles, "the new path handling", etc. We need some reference place where to check how to go on.
