### ISSUE TITLE
Possible format for minimal dataset description

### ISSUE THREAD

**Issue by mih** [datalad/datalad#379]
Here is what R uses

https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file

quite simply, and (after R syntax is removed, and dependency information is dropped) quite usable IMHO.

**Comment by yarikoptic** [comment]
I would suggest we use Debian's https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/  short abbreviations for licenses where applicable.  Being good legal citizens we should ideally allow for Copyright specification may be? (as we know license without copyright is kinda insufficient, so we would encourage better practice)
Version: -- although we should have it in "aggregated" meta I wonder if it shouldn't be actually autogenerated (we use git underneath, aren't we?) and in actual packages we define Version-glob to be provided to `git describe`. Lazy/busy me as a maintainer hates adjusting versions in the files upon every release.  Relying on tags is much better but we might need to filter them out and propagate that info "up" (may be... or may be not even bother???)

**Comment by bpoldrack** [comment]
Re version: From my point of view, everything in there is optional, right?
So, we can autogenerate as long as there is no entry provided within such a
file, but allow for an entry (that overrides everything else).

2016-03-22 13:25 GMT+01:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by hanke** [comment]
We now have implementations for two, rather minimal, JSON-based meta data formats in #682
