### ISSUE TITLE
fetch complimentary materials for the PDF

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#38]
Reviewing paper for PLOS and annoying thing is that it has plenty of "Supplementary" files which are linked in PDF but even with acroread -- doesn't go to any of those URLs for some reason...  so here came ugly in implementation but beautiful in the result workaround

``` shell
git init; git annex init; strings ../PONE-D-XXXX.pdf | grep URI.*editorialmanager | sed -e 's,.*/URI(\(http://www.edit.*\))>>.*,\1,g' | while read link; do fn=$(~datalad/datalad/tools/urlinfo -f $link);   git annex addurl --pathdepth=1 --file=$fn $link; done 
```

urlinfo was necessary because of #37 .

So I thought it might provide an interesting useful use-case for the crawler, where "provider" is a PDF document (instead of e.g. a website) -- the rest goes the same.  Now I have fetched some tarballs to be extracted etc

**Comment by yarikoptic** [comment]
NB for some reason .tif files (such as Figure1.tif) were  annex'ed but at the end reverted to files and listed as not staged and as a "typechange: Figure1.tif" although downloaded -- may be there were duplicate urls I guess  (also just noted that I used --pathdepth=1 instead of -1)

```
$> ls -l Figure1.tif
-rw-r--r-- 1 yoh yoh 136056 Jan 21 13:38 Figure1.tif

$> git status Figure1.tif
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   Figure1.tif

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	typechange: Figure1.tif
```

I had to commit, and then 'git reset --hard' to bring the symlinks back

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
