### ISSUE TITLE
search: guard user from misspecification of search query

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3801]
E.g. we use `:` as a separate in the search query in `key:value`.  Since it is more conventional to specify `key=value` it is easy to make that "mistake" here and  simply obtain no results - not even a warning issued.

Example:
```
(git-annex)hopa:~/datalad[master]
$> datalad -c datalad.search.index-egrep-documenttype=all search bids.MagneticFieldStrength=3T           
[INFO   ] no hits 
datalad -c datalad.search.index-egrep-documenttype=all search   76.81s user 1.99s system 96% cpu 1:21.26 total
```
with the correct one being:
```
$> datalad -c datalad.search.index-egrep-documenttype=all search bids.MagneticFieldStrength:3T | head
search(ok): /home/yoh/datalad/openfmri/ds000217/derivatives/mriqc/reports/sub-Exp1s01_task-routelearning_run-01_bold.html (file)
search(ok): /home/yoh/datalad/openfmri/ds000217/derivatives/mriqc/reports/sub-Exp1s01_task-routelearning_run-02_bold.html (file)
search(ok): /home/yoh/datalad/openfmri/ds000217/derivatives/mriqc/reports/sub-Exp1s01_task-routelearning_run-03_bold.html (file)
search(ok): /home/yoh/datalad/openfmri/ds000217/derivatives/mriqc/reports/sub-Exp1s01_task-routelearning_run-04_bold.html (file)
search(ok): /home/yoh/datalad/openfmri/ds000217/derivatives/mriqc/reports/sub-Exp1s01_task-routelearning_run-05_bold.html (file)
...
```
in this particular case I would even expect `search` just error out since IMHO it was entirely incorrect specification.  If we were to look for hits where that field is present with any value, it should have been `field:.*`

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
