### ISSUE TITLE
`git status` broken in submodule with adjusted branch (on crippled FS)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3820]
I was trying to figure out, how we could properly save the state of a modified subdataset in a parent repository when both are using adjusted branches. However, I stumbled upon behavior that seems like a more fundamental bug. Here is a demo:

Prepare a repo with a submodule

```
/tmp % datalad create repo
/tmp % datalad create -d repo repo/sub
/tmp % echo 123 > repo/sub/file
/tmp % echo 234 > repo/file
/tmp % datalad save -d repo -r

# clean state
/tmp % git -C repo submodule
 fdb2afee57643a978494530b136a8ced7f6d5f34 sub (heads/master)

/tmp % git -C repo/sub log -n1 |cat
commit fdb2afee57643a978494530b136a8ced7f6d5f34
Author: Michael Hanke <michael.hanke@gmail.com>
Date:   Mon Oct 21 09:37:04 2019 +0200

    [DATALAD] Recorded changes
/tmp % git -C repo status
On branch master
nothing to commit, working tree clean
```

Clone onto a crippled FS and initial both repos

```
/tmp/crippled % git clone /tmp/repo
Cloning into 'repo'...
done.
/tmp/crippled % cd repo
/tmp/crippled/repo (git)-[master] % git annex init
init  
  Detected a filesystem without fifo support.

  Disabling ssh connection caching.

  Detected a crippled filesystem.
(merging origin/git-annex into git-annex...)
(recording state in git...)
(scanning for unlocked files...)

  Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.

Switched to branch 'adjusted/master(unlocked)'
ok
(recording state in git...)

/tmp/crippled/repo (git)-[adjusted/master(unlocked)] % git submodule init
Submodule 'sub' (/tmp/repo/sub) registered for path 'sub'

/tmp/crippled/repo (git)-[adjusted/master(unlocked)] % git status
On branch adjusted/master(unlocked)
nothing to commit, working tree clean

/tmp/crippled/repo (git)-[adjusted/master(unlocked)] % git -C sub annex init
init  
  Detected a filesystem without fifo support.

  Disabling ssh connection caching.

  Detected a crippled filesystem.
(scanning for unlocked files...)
ok
```

The repo is reported clean, despite the submodule checkout not being identical with the recorded commit:

```
/tmp/crippled/repo (git)-[adjusted/master(unlocked)] % git status
On branch adjusted/master(unlocked)
nothing to commit, working tree clean

/tmp/crippled/repo (git)-[adjusted/master(unlocked)] % git submodule
 fdb2afee57643a978494530b136a8ced7f6d5f34 sub
/tmp/crippled/repo (git)-[adjusted/master(unlocked)] % git -C sub log -n1 |cat
commit 3aac9c0887b2eb6e47f0da33e07656a70c32434e
Author: Michael Hanke <michael.hanke@gmail.com>
Date:   Mon Oct 21 09:37:04 2019 +0200

    git-annex adjusted branch
```

Initially I thought this is a nice feature, and it detects that there is nothing different other than the adjustment. However, no modifications to the submodule are being detected:

```
/tmp/crippled/repo (git)-[adjusted/master(unlocked)] % touch sub/this
/tmp/crippled/repo (git)-[adjusted/master(unlocked)] % git status
On branch adjusted/master(unlocked)
nothing to commit, working tree clean
```

But modifications to the parent are being detected:

```
(datalad3-dev) mih@meiner /tmp/crippled/repo (git)-[adjusted/master(unlocked)] % touch up
(datalad3-dev) mih@meiner /tmp/crippled/repo (git)-[adjusted/master(unlocked)] % git status
On branch adjusted/master(unlocked)
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        up

nothing added to commit but untracked files present (use "git add" to track)
```

It seems as if Git doesn't realize that it is in a submodule, as it reports the parent change from inside the submodule, but still not the original modification

```
/tmp/crippled/repo (git)-[adjusted/master(unlocked)] % git -C sub status
On branch adjusted/master(unlocked)
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../up

nothing added to commit but untracked files present (use "git add" to track)
```

When I apply the same modifications to the original repositories on the normal FS, everything behaves as expected:

```
/tmp/repo (git)-[master] % touch sub/this
/tmp/repo (git)-[master] % touch up
/tmp/repo (git)-[master] % git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   sub (untracked content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        up

no changes added to commit (use "git add" and/or "git commit -a")
/tmp/repo (git)-[master] % git -C sub status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        this

nothing added to commit but untracked files present (use "git add" to track)
```

@joeyh Could you please have a look and share your thoughts on what is happening here?

**Comment by joeyh** [comment]
I have not been able to reproduce this using git-annex on FAT w/o
datalad. I guess it has something to do with the .git file/symlink in
the submodule confusing git so it does not always treat it as a git
repository, or something like that.

I did find a bug in git-annex init in this situation, that prevented it
from entering an adjusted branch in the submodule if the submodule
was cloned from a repo with the same adjusted branch checked out.
Fixed in commit fc7c6a5a33df7c33274c79bbe635b8ad082d5436.
I don't think you encountered this bug though.

It seems that git status will always report a submodule to be modified
with "(new commits)" when a different commit is checked out; it does not
care that the submodule's master branch is unchanged. I don't see a way
around that, unfortunately.

-- 
see shy jo

**Comment by mih** [comment]
Thanks @joeyh 

> I have not been able to reproduce this using git-annex on FAT w/o datalad. I guess it has something to do with the .git file/symlink in the submodule confusing git so it does not always treat it as a git repository, or something like that.

Good point, it made me realize that this wasn't vfat, but exfat. Here are the respective excerpts for this device and a fat usb drive in comparison on the system in question:

```
% mount
...
/dev/sdb2 on /media/mih/playwithme type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)
/dev/sdc1 on /media/mih/7CE3-AFF6 type vfat (rw,nosuid,nodev,relatime,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,showexec,utf8,flush,errors=remount-ro,uhelper=udisks2)

% sudo blkid -o list
device                       fs_type     label        mount point                      UUID
----------------------------------------------------------------------------------------------------------------------------
/dev/sdb2                    exfat                   /media/mih/playwithme              545F-616E
/dev/sdc1                    vfat                     /media/mih/7CE3-AFF6             7CE3-AFF6
```

> I did find a bug in git-annex init in this situation, that prevented it from entering an adjusted branch in the submodule if the submodule was cloned from a repo with the same adjusted branch checked out. Fixed in commit fc7c6a5a33df7c33274c79bbe635b8ad082d5436. I don't think you encountered this bug though.

I agree, this sounds different. but thanks for fixing it before it hit me! ;-)

> It seems that git status will always report a submodule to be modified with "(new commits)" when a different commit is checked out; it does not care that the submodule's master branch is unchanged. I don't see a way around that, unfortunately.

I was expecting that. I think we can ultimately work around it in `datalad status`, but I don't see a way to make it compatible with `git status`.

**Comment by joeyh** [comment]
Michael Hanke wrote:
> Good point, it made me realize that this wasn't vfat, but exfat.

I'm seeing the same behavior with exfat as vfat.

git version 2.23.0
git-annex version: 7.20191018-gb94f2c18e

Must be something else I'm missing to replicate the problem.
Anyway, looking at the submodule's .git is the obvious thing to do to
get at why git status is not treating it as a git repo.

-- 
see shy jo

**Comment by mih** [comment]
Erm, grrr... `git submodule init` obviously must be followed by `git submodule update`, otherwise there will be not submodule cloned. No submodule makes `git status` not see a submodule, because there is none.

:man_facepalming: 

Sorry for the noise.
