### ISSUE TITLE
"run --naive --" mode

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3823]
Given a command line (after --) of anything user would run without datalad, run datalad get on anything which might look like a path, if it is (after get which might install subdataset), add it to inputs. Whatever changes after the run, add to outputs, save the state of the execution like any run would do

**Comment by yarikoptic** [comment]
ha -- I think it was a cute idea.  I will add some labels ;-)

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.

Also: added more labels ;-)
