### ISSUE TITLE
Add ability to generate submodule clone URLs based on submodule properties

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3827]
ATM DataLad already supports the generation of additional candidate clone URLs besides the one hardcoded in `.gitmodules` https://github.com/datalad/datalad/blob/004daa2216c8451a6ad84eec527123c1481242c9/datalad/distribution/get.py#L80

It can be instrumental to not have to record a URL, or at least be able to overwrite a URL record without having to actually modify a dataset -- especially when dealing with large numbers of datasets. Having a configurable mechanism would also aid longevity, as data**set** availability can be made more robust.

This somewhat relates to https://github.com/datalad/datalad/issues/947 where a global dataset catalog could be queried for the location of a particular dataset that is needed as a subdataset, even if the included submodule URL is no longer valid.

As of https://github.com/datalad/datalad/commit/16dc4937595542ebb2b8d26a1220eb93e5828bba we include the DataLad dataset ID in the submodule record. Consequently, while a submodule record of a locally created dataset hierarchy can be rather useless looking like this:

```
% cat .gitmodules
[submodule "sub"]
        path = sub
        url = ./sub
        branch = master
        datalad-id = 740aa162-f3d5-11e9-9625-f0d5bf7b5561
```

The dataset ID offers the possibility for further investigation.

### Proposal

I want to enhance the candidate URL generation with a configuration-based templating mechanism that can use any known submodule property to format a URL. Let's say I have a tree of bare repos on a server that are structured based on their datalad ID. I could have:

```
datalad.get.subdataset_url_candidate = 'store.example.com:/data/{id:.3}/{id[3]}{id[4]}{id[5]}{id[6]}{id[7]}{id[8]}{id[9]}{id[10]}{id[11]}{id[12]}{id[13]}{id[14]}{id[15]}{id[16]}{id[17]}{id[18]}{id[19]}{id[20]}{id[21]}{id[22]}{id[23]}{id[24]}{id[25]}{id[26]}{id[27]}{id[28]}{id[29]}{id[30]}{id[31]}{id[32]}{id[33]}{id[34]}{id[35]}
```

which resolves to `store.example.com:/data/740/aa162-f3d5-11e9-9625-f0d5bf7b5561` when sent through `templ.format(**submod_props)` (datalad id, broken into its first three bytes and the rest; admittely obscure, but what counts is that it is possible).

The same mechanism can later be used to enable query of a particular redirector, e.g.

```
datalad.get.subdataset_url_candidate = http://dx.datalad.org/{id}
```

and of course multiple queries can be configured:

```
# local name based catalog (stupid idea, but hey...)
datalad.get.subdataset_url_candidate = /data/{name}
# global redirector
datalad.get.subdataset_url_candidate = http://dx.datalad.org/{id}
```

As already the case, candidate URLs are tried in order and the first one to succeed terminates the process.

It would make sense to RF the current hard-coded behavior out, and also expose the currently tried URL variants `.../.git`, `....git` though this mechanism. This could be achieved by adding the configured remote URL of the superdataset to the list of submodule properties.

**Comment by bpoldrack** [comment]
I think I like that approach. There's another aspect to it: At some point such a configuration might become useful to even record something that is not a URL one could actually git-clone from, but that could point to kind of "special remote" to retrieve a repo from by some different method.

**Comment by kyleam** [comment]
That sounds good to me too.

The proposed functionality could also eventually be used to create a command that rewrites `.url` values.  This would be nice in cases where `datalad create -d. <subddataset>` generated a useless URL and at some later point the subdataset was made available at a proper URL.  By rewriting the stored `.url` value, the clone would work outside of datalad.

**Comment by yarikoptic** [comment]
Sounds great.
One possible additional aspect: I think that it would be valuable if any such alternative record/source was accompanied by a name, which would be used as a name for the corresponding remote/sibling, as opposed to default "origin". with our current alterative locations we do try to reach its copy on its original location so origin as a name makes semantic sense to me. Also that one is most likely to contain desired commit/version. Alternative locations might not be that reliable, and we might need to try a few. For that it would be best to have them available in separate remotes.

Also, if there were names, we could finally implement support for other than /// shortcuts.

**Comment by yarikoptic** [comment]
Sounds great.
One possible additional aspect: I think that it would be valuable if any such alternative record/source was accompanied by a name, which would be used as a name for the corresponding remote/sibling, as opposed to default "origin". with our current alterative locations we do try to reach its copy on its original location so origin as a name makes semantic sense to me. Also that one is most likely to contain desired commit/version. Alternative locations might not be that reliable, and we might need to try a few. For that it would be best to have them available in separate remotes.

Also, if there were names, we could finally implement support for other than /// shortcuts.

**Comment by mih** [comment]
@yarikoptic I had a similar thought re names. However, I currently think that such functionality (configuring multiple remotes) would fit better into a URL rewriting command that @kyleam mentioned. Otherwise we would needlessly slow subdataset installation for plain one-off consumption cases.

I will try to add the idea of named source candidate though, so we could have an easier time making the full feature set happen eventually.

**Comment by yarikoptic** [comment]
> Otherwise we would needlessly slow subdataset installation for plain one-off consumption cases.

I want suggesting to add all known possible remotes, so I don't expect any effect on performance

What I was thinking about is more of what should be instead of datalad.get.subdataset_url_candidate single variable, we might want to define sections similar to branches and remotes, and call them eg "datalad.origin" where each named section would have url field (for starters) but might later also define "priority" or cost fields so local configurations could be adjusted to reflect the situation etc

**Comment by mih** [comment]
Hmm, I don't get it yet then. I cannot see a way to first guess possibly existing remotes (and it is guessing, because it is happening based on a superdataset's knowledge, but needs to be applied to a subdataset), and then end up with valid configuration for actually existing remotes without a cost. At the very minimum it needs a fetch for each remote. For each subdataset we already create two candidates (in the future more), each of them would need to be tested for each subdataset in question -- even in the one-off throw-away install case.

I think we should decouple this from to ongoing PR.
