### ISSUE TITLE
get broke reporting on 'notneeded' subdatasets in 0.12.0rc6

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#3836]
Installing an already existing subdataset used to yield a "notneeded" result (as `get` does). With 0.12.0rc6 there's no result at all (which as a result breaks datalad-neuroimaging test helper for example dicom datasets:

```
❱ datalad create some
[INFO   ] Creating a new annex repo at /tmp/some
create(ok): /tmp/some (dataset)                                                                                              
(hirni-test-rc6) bpoldrack@brainbfast in /tmp
❱ cd some
(hirni-test-rc6) bpoldrack@brainbfast in /tmp/some on git:master
❱ datalad create -d . nested
[INFO   ] Creating a new annex repo at /tmp/some/nested
create(ok): nested (dataset)                                                                                                 
action summary:
  add (ok: 2)
  create (ok: 1)
  save (ok: 1)
(hirni-test-rc6) bpoldrack@brainbfast in /tmp/some on git:master
❱ datalad status
(hirni-test-rc6) bpoldrack@brainbfast in /tmp/some on git:master
❱ datalad -f json_pp get nested
{
  "action": "get",
  "path": "/tmp/some/nested",
  "refds": "/tmp/some",
  "status": "notneeded",
  "type": "directory"
}
(hirni-test-rc6) bpoldrack@brainbfast in /tmp/some on git:master
❱ datalad -f json_pp install nested
(hirni-test-rc6) bpoldrack@brainbfast in /tmp/some on git:master
❱
```

From the diff of `install` itself the change seems to be not in there, which suggests it's actually `get`. However, `get` does yield the correct result, so I'm not yet clear, where it goes wrong. Does that ring a bell, @mih?

**Comment by mih** [comment]
Yes. Install uses a very peculiar result filter that tries to only return datasets macthing actual input argument (grep for `is_result_matching_pathsource_argument`). As this is not doable in general, it makes guesses. Most likely the returned result does not match an assumption hard-coded in this function.

**Comment by bpoldrack** [comment]
Double-checked comparison to rc5.
There's a difference in `get` indeed. Compare to above:

❱ datalad -f json_pp get nested             
{
  "action": "get",
  "orig_request": "nested",
  "path": "/tmp/some/nested",
  "raw_input": true,
  "registered_subds": true,
  "status": "notneeded",
  "type": "dataset"
}
{
  "action": "get",
  "path": "/tmp/some/nested",
  "status": "notneeded",
  "type": "directory"
}
```

So, what I missed in the beginning: in rc6 `get` yields a `type=directory` result only, while in rc5 there's a dataset-type result in addition.

**Comment by bpoldrack** [comment]
So, no matter what `install` wants to do, `get` is wrong from my point of view. It should be a dataset type result, I think. Agree @mih ?

**Comment by mih** [comment]
From what is in this issue, I agree. But I haven't looked into it in detail.

**Comment by mih** [comment]
So this is the critical change:

```
(datalad3-dev) mih@meiner /tmp/some (git)-[master] % datalad -f json_pp get nested -n
(datalad3-dev) mih@meiner /tmp/some (git)-[master] % datalad -f json_pp get nested 
{
  "action": "get",
  "path": "/tmp/some/nested",
  "refds": "/tmp/some",
  "status": "notneeded",
  "type": "directory"
}
```

`get` is silent, when there is no attempt to fetch data. This looks broken to me.
