### ISSUE TITLE
and here comes github pricing model for the Actions to be in place from Nov 13

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3843]
Just received an email that from 13 of nov, Actions will not be in beta, so there will be less of free cheese (now it is all free as part of beta, no limits). https://github.com/features/actions:
2,000 minutes per month, extra is $0.008 per minute for Linux and $0.016 for Windows!  So if my algebra is right -- to double free on Linux only, we need to pay 16$/mo (or twice more if Windows only).

But the real question is how many minutes we consume typically, or how many we consumed so far?  I found no summary anywhere. Emailed support@github.

But also -- I see from https://github.com/pricing that "Team", which has 10,000 (so 5x) minutes per month allowance, would be 25$/mo (for 5 team members), BUT also it is "Free to academic faculty for teaching or non-profit research".  So at least we could inquire may be about getting core developers some Team privileges?
There is even a bigger carrot where one of us would need to sell someone's in administration soul to github -- https://education.github.com/schools which makes enterprise level github available for free, and that would be 50,000 minutes! ;)

**Comment by mih** [comment]
We currently need:

- extension tests: 15min
- windows: 83min
- benchmarks: 16min
- docs: 2min

Makes a total of ~120min per push to a PR. Which is 16 PR runs per month for 2000 free minutes. Pointless. Even with 50000min it is just 420 pushes per month.

Either we can keep using it for free, or we have to migrate -- or pay.

**Comment by bpoldrack** [comment]
> Additional hosted runner minutes
> 
>     Linux       $0.008 per minute
>     Windows     $0.016 per minute
>     macOS       $0.08 per minute
>     Self-hosted  Coming soon  Free

I think the only interesting option is "coming soon". Otherwise - migrate.

**Comment by mih** [comment]
Closing this issue, all relevant info seems to have been collected.
