### ISSUE TITLE
Recognize a `tmp/` subdir in a YODA setup

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3845]
Some people have the desire to have a place in a dataset where it is OK to be messy. Shall we add a `.gitignore` setting for a potentially existing `tmp/` subdirectory?

**Comment by yarikoptic** [comment]
I guess for Yoda it should be ok

**Comment by bpoldrack** [comment]
Hm. This can be quite surprising and it's unclear to me, what this name and purpose has to do with YODA.
Also: How is it more easy to know that this particular config procedure happens to recognize a particular name for such a place than to just add `tmp/*` to `.gitignore`?

**Comment by kyleam** [comment]
FWIW my reaction matched @bpoldrack's.

**Comment by mih** [comment]
Hmm, maybe we have different concepts of these config procedures. From my POV, this procedure does nothing but implement a set of conventions. My proposal was asking to add another convention to an existing set. YODA was invented to promote a particular dataset layout, having a place within the dataset that serves as scratch space seems like a good addition -- given that the existence of such a places (heterogeneously named for the lack of a convention) prompted this issue.

If the problem is "why not configure it yourself" then my question is: what is the point in configuring `code/` and arbitrarily naming it such?

If the problem is why YODA then it is fine with me to just copy the yoda procedure and have another one with a different name. In this case, I'd prefer to adjust to handbook to refer to this alternative procedure, as within its scope (and the associate course) people learn about useful conventions.

What am I missing?

**Comment by kyleam** [comment]
> having a place within the dataset that serves as scratch space seems like a good addition -- given that the existence of such a places (heterogeneously named for the lack of a convention) prompted this issue.

I don't see this heterogeneity as a problem that needs solving.  Why does using a common directory matter for content that is untracked?  I think that's the core of the issue for me.

That said, I don't think ignoring "/tmp/" or "tmp/" has much potential to cause harm.  The worst case scenario I can come up with is that an inexperienced git user puts content in "tmp/" for whatever reason and doesn't realize that this directory is being ignored and that these changes aren't being saved.  The more likely scenario is just that a user doesn't prefer the setting and modifies `.gitignore` to their liking or doesn't use `cfg_yoda`.  So I don't have a strong objection.

**Comment by mih** [comment]
> I don't see this heterogeneity as a problem that needs solving.

True, but it is not the heterogeneity that I am concerned with. I want to be able to promote an "always clean" workflow, where there is nothing untracked cluttering a dataset. At the same time, I want to promote making more smaller commits, because they tend to be more comprehensible and are also easier to squash into one, than it is to take a bulk commit apart. In such a scenario, one frequently needs a place to put things that need/must not be tracked. That implies that anyone, more or less immediately needs to create directory that can serve as a tmp folder, and gitignore it.
Of course this could be left to each user, but inexperienced users might move that tmp folder outside the dataset. This in turn increases the likelihood that code tracked in a dataset references locations outside the dataset -- which might impact portability.

So in general, I am looking for the optimal trade-off between setup complexity and 
novice users intuitively doing the right thing from the very start -- without requiring them to know all the tricks first.

> The worst case scenario I can come up with is that an inexperienced git user puts content in "tmp/" for whatever reason and doesn't realize that this directory is being ignored and that these changes aren't being saved.

That is an issue, I agree. What about going one step further, and not just adding gitignore configuration, but actually creating a tmp folder and putting an empty `NO_VERSION_CONTROL_HERE` file into it? Of course this wouldn't help later clones of such a dataset, but I'd argue that once you install a dataset from somewhere, you are less novice than after your first `create`.

It is not perfect, but I would be satisfied if the chances for harm are tiny and the potential for good is non-zero.

**Comment by kyleam** [comment]
> > I don't see this heterogeneity as a problem that needs solving.
> 
> True, but it is not the heterogeneity that I am concerned with. I want to be able to promote an "always clean" workflow, where there is nothing untracked cluttering a dataset. At the same time, I want to promote making more smaller commits, because they tend to be more comprehensible and are also easier to squash into one, than it is to take a bulk commit apart. In such a scenario, one frequently needs a place to put things that need/must not be tracked. That implies that anyone, more or less immediately needs to create directory that can serve as a tmp folder, and gitignore it.

Interesting.

Reading that I can't help but think that this problem is the reason that git's index exists, but the index is a concept that datalad hides away.  I think that points to the fact that my reaction really shouldn't count for much here.  I'm not the target audience, and, while I do try to look at things from that point of view, I'm clearly failing on this one.

> > The worst case scenario I can come up with is that an inexperienced git user puts content in "tmp/" for whatever reason and doesn't realize that this directory is being ignored and that these changes aren't being saved.
> 
> That is an issue, I agree. What about going one step further, and not just adding gitignore configuration, but actually creating a tmp folder and putting an empty `NO_VERSION_CONTROL_HERE` file into it?

Yeah, sounds fine.  Perhaps just a README.md that explains the purpose of the directory, like what's already done for `code/`, would be sufficient.

**Comment by yarikoptic** [comment]
I am with @mih on this. ;-)

Having said that, adding anything to .gitignore should be done indeed with the caution, since it could directly effect reproducibility of the runs. I even wonder if we could somehow inform user after `run` that X files changes were ignored because those were ignored. But that might be too costly. May be at least to alert that such ignored paths (as tmp/) exist

**Comment by mih** [comment]
If we want to issue a valid warning, the only way that I see is to have a dedicated `ls-files --exclude-standard --ignored` run (per dataset) before and after a `run` to check them for differences. Just looking at local `.gitignore` files won't give us the full picture, and IMHO issuing some warnings, but not reliable enough that they are actually trustworthy would be more problematic than not having any, and merely documenting that ignored files can be an issue for reproducibility.

**Comment by mih** [comment]
As evident, there is not sufficient interest in pushing this over the finish line. Closing.
