### ISSUE TITLE
download-url -O SUBDIR/ --archive  silently extracts in current (not SUB) dir if SUB not exists

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3848]
Took me a while to understand what is going on, since some times it was getting extracting under subdir (name was short -- easy to spot a typo), and some times into a current one (name was long, I had a typo in subdir name).

```shell
$> datalad create -c text2git testds; cd testds;
[INFO   ] Creating a new annex repo at /tmp/testds 
[INFO   ] Running procedure cfg_text2git                                                                                
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) ===== 
create(ok): /tmp/testds (dataset)

$> d=python-novice-inflammation; mkdir -p "$d"; datalad download-url -O "$d"typo --archive http://swcarpentry.github.io/python-novice-inflammation/data/python-novice-inflammation-data.zip
[INFO   ] Downloading 'http://swcarpentry.github.io/python-novice-inflammation/data/python-novice-inflammation-data.zip' into 'python-novice-inflammationtypo' 
http://swcarpentry.github.io/python-novice-inflammation/data/python-novice-inflammation-data.zip:   0%| | 0.00/22.6k [00                                                                                                                        download_url(ok): python-novice-inflammationtypo (file)
add(ok): python-novice-inflammationtypo (file)
save(ok): . (dataset)
[INFO   ] Adding content of the archive python-novice-inflammationtypo into annex <AnnexRepo path=/tmp/testds (<class 'datalad.support.annexrepo.AnnexRepo'>)> 
[INFO   ] Initiating special remote datalad-archives 
[INFO   ] Finished adding python-novice-inflammationtypo: Files processed: 15, +git: 15 
action summary:
  add (ok: 1)
  download_url (ok: 1)
  save (ok: 1)

$> ls  
data/  python-novice-inflammation/
```

but it is arguably not a bug per se but side-effect of a feature.  `-O` (as `--help` says) could be used to point to target file name to download to (and that is where the archive gets downloaded to first), and then it gets extracted from current directory:

```shell
$> git log --stat
commit 8a4c958836cc640a7cbff9b4ff2260447cde1776 (HEAD -> master)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Wed Oct 30 09:31:29 2019 -0400

    [DATALAD] Added content extracted from archive python-novice-inflammationtypo
    
    Files processed: 15
     +git: 15

 data/inflammation-01.csv       | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 data/inflammation-02.csv       | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 data/inflammation-03.csv       | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 data/inflammation-04.csv       | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 data/inflammation-05.csv       | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 data/inflammation-06.csv       | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 data/inflammation-07.csv       | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 data/inflammation-08.csv       | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 data/inflammation-09.csv       | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 data/inflammation-10.csv       | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 data/inflammation-11.csv       | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 data/inflammation-12.csv       | 60 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 data/small-01.csv              |  2 ++
 data/small-02.csv              |  2 ++
 data/small-03.csv              |  2 ++
 python-novice-inflammationtypo |  1 -
 16 files changed, 726 insertions(+), 1 deletion(-)

commit f747339165f8e30b0d22099e1e4552868d3e5b6a
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Wed Oct 30 09:31:26 2019 -0400

    [DATALAD] Download URLs
    
    URLs:
      http://swcarpentry.github.io/python-novice-inflammation/data/python-novice-inflammation-data.zip

 python-novice-inflammationtypo | 1 +
 1 file changed, 1 insertion(+)
```

so I thought to suggest to throw a warning if `-O` specified together with `--archive` (which would imply extraction), but I feel that could be a reasonable use case as well.

So not sure if we could/should do anything, or may be someone has an idea?  If not -- we should close this one in a few days. Just wanted to share since was confused for a bit with behavior

**Comment by kyleam** [comment]
I'm confused why the discussion has been focused on `--archive`.  The core issue seems to be that `-O` has special treatment for existing directories and if there's a typo, download-url of course isn't aware of that directory and goes with the non-directory treatment.  The download goes somewhere the user didn't intend; I don't see why conceptually it matters if later that download file is fed to `add_archive_content` or not (though I understand that in practice the resulting explosion of the archive's content in the wrong place may be more annoying).

I think a good option here is to go with rsync-like behavior and make a trailing separator necessary to trigger the directory treatment.  (Yes, I know when similar cases have come up before, some object to this as too magical, but the current behavior is already magical and in a way that is less familiar.)  The trailing slash behavior is easy to document and resolves the ambiguity of guessing what the user wants.  And because we know when they want a directory, we can even create directories that don't exist.

**Comment by bpoldrack** [comment]
But we could have a really complicated solution! ;-)

Somewhat embarrassing, but I think you're absolutely right, @kyleam .

**Comment by yarikoptic** [comment]
I thought to argue with `wget` as an argument (I thought its behavior was the inspiration for the flexibility) but
```shell
$> wget -O /tmp/out https://launchpad.net/libeatmydata
/tmp/out: Is a directory
```

trailing slash... I somewhat hate it (since generally we are trying to get away from such semantic), but it would indeed be the best solution here probably... and crash if there is no trailing slash and there is a directory in the path (similar to `wget`).  I would be ok with that breaking change.

**Comment by kyleam** [comment]
> I somewhat hate it (since generally we are trying to get away from such semantic)

I'd be interested to read past discussions on this (though of course not something you should waste much time searching for).  Off the top of my head, I can't think of many places in DataLad where we make the distinction.  The main one I know of is `status`, but I didn't think there was any proposal to get away from that behavior.

https://github.com/datalad/datalad/blob/afc32703d5cad054c95a249faa9dd2e6c5f41c11/datalad/core/local/status.py#L186-L191

**Comment by mih** [comment]
> I'd be interested to read past discussions on this

I don't have the references either, but some difficulty of working with such semantics comes from the fact that once a path arg is turned into a `Path` object, such properties can no longer be inferred. That being said, it is now relatively clear to me that any kind of argument normalization has to be carefully considered, and actually largely avoided when passing args to underlying (but also high-level) commands. Hence this is not so much of an issue than I thought it would be. And clearly, I considered it meaningful for `status`, so I am on board with this move.
