### ISSUE TITLE
Browser GUI for DataLad

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3849]
I have ran into https://github.com/ml-tooling/ml-workspace which is cool on its own, but looking through dependencies of it found https://github.com/FredrikNoren/ungit -- looks pretty cool as well! ;)

I wondered if (looking into the future) we are to provide some GUI - this might be a viable candidate to expand/contribute to git-annex/DataLad relevant functionality.
Rationale:  most likely GUI would be in a browser, and instead of redoing all the UI we better consider contributing to an existing solution.  In case of ungit -- (if our changes accepted upstream) we would immediately reach a wide audience

**Comment by bpoldrack** [comment]
Didn't look into details yet, but speaking of browser-based GUI want to remind ourselves of https://github.com/datalad/datalad-webapp

**Comment by yarikoptic** [comment]
Yeah, I know about it. But i feel that unless we get some web design expert and time to spare on redoing actual gui, better to integrate with some existing solution

**Comment by bpoldrack** [comment]
Sure. But integration could use that approach to actually talk to datalad, while the actual integration part is completely independent.

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
