### ISSUE TITLE
Error when creating a bare repository

### ISSUE THREAD

**Issue by dickscheid** [datalad/datalad#3855]
#### What is the problem?

When trying to create a new, bare  datalad  repository using

     datalad create testset --bare

the following error occurs:

     [INFO   ] Creating a new annex repo at /p/home/jusers/dickscheid1/judac/testset
     CommandError: command '['git', '-c', 'annex.largefiles=nothing', 'add', '--dry-run', '-N', '--ignore-missing', '--verbose', '--', '.gitattributes']' failed with exitcode 128
     Failed to run ['git', '-c', 'annex.largefiles=nothing', 'add', '--dry-run', '-N', '--ignore-missing', '--verbose', '--', '.gitattributes'] under '/p/home/jusers/dickscheid1/judac/testset'. Exit code=128.     out= err=fatal: this operation must be run in a work tree

     fatal: this operation must be run in a work tree

The bare git annex repo is successfully created, but datalad seems to try to run this post-configuration which only makes sense for non-bare repos.

#### What steps will reproduce the problem?

see above

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

datalad 0.12.0rc6
on Jülich's JUDAC system:

#### datalad
  - version: 0.12.0rc6
  - full_version: 0.12.0rc6
#### dependencies
  - cmd:annex: 7.20190912-gcd27683
  - cmd:git: 2.20.1
  - cmd:bundled-git: 2.20.1
  - cmd:system-git: 2.20.1
  - cmd:system-ssh: 7.4p1
  - appdirs: 1.4.3
  - boto: 2.49.0
  - exifread: 2.1.2
  - git: 3.0.2
  - gitdb: 2.0.5
  - humanize: 0.5.1
  - iso8601: 0.1.12
  - keyring: 19.2.0
  - keyrings.alt: 3.1
  - msgpack: 0.6.1
  - mutagen: 1.41.1
  - requests: 2.22.0
  - wrapt: 1.11.2
#### environment
  - PATH: /p/project/cjinm14/jinm1400/src/bftools:/p/project/cjinm14/jinm1400/src/miniconda3/bin:/p/project/cjinm14/jinm1400/src/miniconda3/condabin:/opt/lenovo/onecli:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/usr/lpp/mmfs/bin
  - LANG: en_US
  - GIT_PYTHON_GIT_EXECUTABLE: /p/project/cjinm14/jinm1400/src/miniconda3/bin/git
#### git-annex
  - version: 7.20190912-gcd27683
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions:
    - aws-0.21.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.1.0
    - ghc-8.6.5
    - http-client-0.5.14
    - persistent-sqlite-2.9.3
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - operating system: linux x86_64
  - supported repository versions:
    - 7
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
#### location
  - path: /p/home/jusers/dickscheid1/judac
  - type: directory
#### metadata_extractors
  - annex:
    - module: datalad.metadata.extractors.annex
    - version: None
    - load_error: None
  - audio:
    - module: datalad.metadata.extractors.audio
    - version: None
    - load_error: None
  - datacite:
    - module: datalad.metadata.extractors.datacite
    - version: None
    - load_error: None
  - datalad_core:
    - module: datalad.metadata.extractors.datalad_core
    - version: None
    - load_error: None
  - datalad_rfc822:
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
    - load_error: None
  - exif:
    - module: datalad.metadata.extractors.exif
    - version: None
    - load_error: None
  - frictionless_datapackage:
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
    - load_error: None
  - image:
    - module: datalad.metadata.extractors.image
    - version: None
    - load_error: None
  - xmp:
    - module: datalad.metadata.extractors.xmp
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
#### python
  - version: 3.7.3
  - implementation: CPython
#### system
  - type: posix
  - name: Linux
  - release: 3.10.0-1062.1.2.el7.x86_64
  - version: #1 SMP Mon Sep 30 14:19:46 UTC 2019
  - distribution: CentOS Linux/7.7.1908/Core
  - max_path_length: 288
  - encoding:
    - default: utf-8
    - filesystem: iso8859-1
    - locale.prefered: ISO-8859-1

**Comment by mih** [comment]
Thanks for the report! This is directly related to #2820, which should now be revisited, as the previous blocker "direct mode support" is not longer an issue.

**Comment by dickscheid** [comment]
Is there a workaround for the time being, to get a single bare repo running?

**Comment by mih** [comment]
That depends on the desired outcome. if you just need a bare repo, there is always `git init --bare`of course. If you need a datalad dataset in a bare repo you could do this:

```
datalad create baretmp
git --git-dir baretmp/.git config --replace-all core.bare true
```

and then move `baretmp/.git` to where you need it, while deleting all the rest.

Or you create a bare repo, and push a dataset into it via remote.
