### ISSUE TITLE
Add annex/git indicator to save() results

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3865]
ATM it just says

```
add(ok): grpmf (file)                                                                                                        
```

but I think it should say `add-to-git` or `add-to-annex` to give a better clue of what happened. I have accidentally done the opposite of what I wanted, and only figured out much later.

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.

**Comment by adswa** [comment]
uhhh this would be cool to have...

**Comment by loj** [comment]
I also think this would be nice to have.
