### ISSUE TITLE
Behavior with large N datasets

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3869]
Demo dataset with 100k tiny files. A size like this is often considered the upper sensible limit of numbers of files.  Each file is placed in a 4th-level subdirectory, because I find that is a frequent average depth in the datasets that I work with.

```sh
$ for i in $(seq 100000); do s=$(uuid | tr '-' '/'); mkdir -p ${s:5:19} && echo $s > ${s:5}; done
# [7min, total size <4MB]
```

Create a dataset

```sh
/tmp/big % time datalad create -f
[INFO   ] Creating a new annex repo at /tmp/big 
create(ok): /tmp/big (dataset)                                                               
datalad create -f  1.03s user 0.52s system 66% cpu 2.327 total
```

```sh
/tmp/big (git)-[master] % time datalad save
Total (100000 ok out of 100000): 100%|██████████████████| 3.70M/3.70M [12:50<00:00, 12.0kB/s]
<snip 99999 lines>
add(ok): ffe/07be/11ea/ba1c/1fdd75885bdc (file)
save(ok): . (dataset)
action summary:
  add (ok: 100000)
  save (ok: 1)
datalad save  781.46s user 189.75s system 109% cpu 14:46.91 total
```

First, it works! Second, every ~30k files, my machine took a break (desktop sluggish). It seems inside `git-annex-add` numerous `git ls-files` processes (among others) are started. I am attaching a `pstree` of a moment in such a phase that has ~100 such processes running.

[ptree.txt](https://github.com/datalad/datalad/files/3852232/ptree.txt)

NB: while we are calling `git-annex-add` in batches with long lists of filenames already, `git-annex` itself further splits to-be-processed files into (smaller) batches.

The result renderer output is completely useless (100k `add(ok)` lines), nobody knows if there was an important message on top.

It took 2x longer to save the files than to create them on the file system -- not too bad IMHO.

```sh
% time datalad status
datalad status  60.22s user 13.44s system 61% cpu 2:00.10 total
% time datalad status -t raw
datalad status -t raw  6.09s user 1.45s system 100% cpu 7.487 total

% time datalad save
datalad save  8.90s user 1.56s system 99% cpu 10.485 total
```

Sensible IMHO. With a hot cache `git status` does

```
% time git status
On branch master
nothing to commit, working tree clean
git status  0.42s user 0.94s system 127% cpu 1.064 total
```

and here some truths:

```
/tmp/big (git)-[master] % find . |wc -l
506736
/tmp/big (git)-[master] % find .git |wc -l
296571
 /tmp/big (git)-[master] % du -sh .git
1.3G    .git
/tmp/big (git)-[master] % git gc --aggressive
Enumerating objects: 425779, done.
Counting objects: 100% (425779/425779), done.
Delta compression using up to 4 threads
Compressing objects: 100% (321825/321825), done.
Writing objects: 100% (425779/425779), done.
Total 425779 (delta 11506), reused 414271 (delta 0)
git gc --aggressive  36.98s user 0.80s system 294% cpu 12.810 total
/tmp/big (git)-[master] % du -sh .git
1.3G    .git
/tmp/big (git)-[master] % du -sh .git/annex
1.2G    .git/annex
/tmp/big (git)-[master] % du -sh .git/annex/objects
1.2G    .git/annex/objects
/tmp/big (git)-[master] % du -hc *
<snip>
821M    total
```

I did another test run with 500k files, but my machine ooops'ed after almost exactly one hour.It started to throw `add(error)` results afterwards.On reboot it took 8min to empty `/tmp` ;-)

**Comment by yarikoptic** [comment]
would be interesting to see also the effect (if any ;)) of the choice of filesystem.  I might do that later.

**Comment by mih** [comment]
This was `ext4`

**Comment by mih** [comment]
Bunch of tests for ZFS with various configurations (to be updated)

### ZFS on HDD (raidz2, 3 vdevs, no compression)
### ZFS on HDD (raidz2, 3 vdevs, lz4 compression)
### ZFS on HDD (raidz2, 3 vdevs, gzip9 compression)

### ZFS on SSD (raidz2, 1 vdev, no compression)
### ZFS on SSD (raidz2, 1 vdev, lz4 compression)
### ZFS on SSD (raidz2, 1 vdev, gzip9 compression)

**Comment by yarikoptic** [comment]
If you are repartitioning here, I would appreciate if you compare against btrfs (on top of a software raid) here on the same hardware

**Comment by yarikoptic** [comment]
Fwiw, this is the setup I used years back when benchmarking filesystems https://github.com/datalad/benchmarking

**Comment by mih** [comment]
Same as above, but with a 500k-file dataset

`for i in $(seq 500000); do s=$(uuid | tr '-' '/'); mkdir -p ${s:5:19} && echo $s > ${s:5}; done;`

### ZFS on HDD (raidz2, 3 vdevs, no compression)
- generate: `01h53min`
- create: `datalad create -f  0.70s user 0.26s system 102% cpu 0.937 total`
- initial save: ``
- save on clean: ``
- status (full): ``
- status (no eval): ``
- git status (warm): ``

**Comment by aqw** [comment]
@yarikoptic Perhaps in the future, but right now we won't be testing btrfs. Focus right now is on migrating the INM7 cluster.

These tests are performed on differently configured ZFS datasets on the same pool.

But yes, it would be interesting in the future to throw an extra SSD in there and just scroll through a few different file systems.

**Comment by yarikoptic** [comment]
If you are ok making uninformed decisions, the call is yours. I might setup some benchmarking in some nearest future - the situation might have changed, and I didn't test on SSDs.
I just remember that in the past https://www.datalad.org/test_fs_analysis.html ZFS shown to be prohibitively slower, and in the future migration from ZFS to BTRFS might become infeasible.

**Comment by aqw** [comment]
@yarikoptic There are more considerations to system than a benchmark

**Comment by mih** [comment]
Check big datasets with Git's split index feature.

**Comment by mih** [comment]
Another round with a 539523-file dataset.

- initial save: `datalad save  6097.82s user 2334.69s system 209% cpu 1:07:11.11 total`
- save on clean: `datalad save  48.89s user 18.53s system 97% cpu 1:09.05 total`
- status (no eval): `datalad status -t raw  35.97s user 17.32s system 99% cpu 53.653 total`
- add single file w/o datalad: `bash -c   2.88s user 3.33s system 149% cpu 4.155 total`
- add single file w/ datalad: `bash -c   3.57s user 4.17s system 157% cpu 4.931 total`

PS:

Used code:

```
bash -c "mkdir -p deep/down && echo '123' > deep/down/below && git annex add deep/down/below && git commit -m 'add'"

bash -c "mkdir -p deep/down && echo '234' > deep/down/below2 && datalad save deep/down/below2"
```

**Comment by mih** [comment]
I started a `git annex unlock > /dev/null` in the v7 repo from above:

```
% git config -l
core.splitindex=true
annex.version=7
annex.thin=true

% find . -type f |wc -l
556878
```

It is going since more than 4h, and has inflated the repo size multiple times (at 13GB so far).

**Comment by joeyh** [comment]
This probably has to do with sqlite's performance with a million or so
INSERTs (with index updates) and probably twice as many SELECTs.

> 7.5G    .git/annex/keys

The size of that database seems suspicious to me. I see a linear growth
in the database size while unlocking files, of approx 1kb per file
(of course long filenames would make it larger). So with half a million
files the database size should be around half a gigabyte. Tested only up
to 15000 files, perhaps sqlite needs more at scale.

Of course, unlock also has to copy every annexed object to the work tree
file, so will double the size of the repo at least (maybe more if there
are duplicates). Setting annex.thin will help with that.

-- 
see shy jo

**Comment by joeyh** [comment]
unlock definitely gets slower as the total number of files increases:

joey@darkstar:/tmp/bigdb2>for n in $(seq 1 500); do for x in $(seq 1 1000); do echo $n-$x>$n-$x;done; git annex joey@darkstar:/tmp/bigdb2>for n in $(seq 1 500); do for x in $(seq 1 1000); do echo $n-$x>$n-$x;done; git annex add --quiet; git annex unlock --quiet; echo "pass $n"; ls -l .git/annex/keys/db; done | ts -i
00:00:20 pass 1
00:00:00 -rw-r--r-- 1 joey joey 860160 Nov 21 17:42 .git/annex/keys/db
00:00:57 pass 2
00:00:00 -rw-r--r-- 1 joey joey 1699840 Nov 21 17:43 .git/annex/keys/db
00:02:03 pass 3
00:00:00 -rw-r--r-- 1 joey joey 2527232 Nov 21 17:45 .git/annex/keys/db
00:01:51 pass 4
00:00:00 -rw-r--r-- 1 joey joey 3383296 Nov 21 17:47 .git/annex/keys/db
00:02:26 pass 5
00:00:00 -rw-r--r-- 1 joey joey 4186112 Nov 21 17:49 .git/annex/keys/db

Doesn't look exponential, at least with those relatively few 5k files...

I do wonder if the significantly larger than expected db size in
Michael's case indicates something beyond that.

-- 
see shy jo

**Comment by mih** [comment]
Thx @joeyh for the initial sanity check. The `unlock` process eventually finished after 16h. Other than the time, the state of the repo looks good:

```
~/big/.git/annex (git)-[master] % du -shc *
512     gitqueue.lck
27M     index
4.5K    index.lck
4.1M    journal
512     journal.lck
119M    keys
4.5K    keys.cache
512     keys.lck
3.6G    objects
512     othertmp.lck
512     precommit.lck
512     sentinal
4.5K    sentinal.cache
512     smudge.lck
3.7G    total

~/big (git)-[master] % du -sh
6.3G    .
1.7G    .git/objects

[after `git gc --aggressive`]
~/big (git)-[master] % du -sh
5.0G    .
243M    .git/objects
```

I have now started an initial `git status`
```
% git status
Refresh index: 0% (127/539528)
```
It does about two objects per second, so if the speed is maintained, it will run for 74 days. It is crunching through the smudge filters

```
mih@data1 ~ % pstree -p 162314 -la
git,162314 status
  ├─sh,33561 -c git-annex smudge --clean -- '01a/061e/11ea/950e/078d4d322ab0' git-annex smudge --clean -- '01a/061e/11ea/950e/078d4d322ab0'
  │   └─git-annex,33562 --library-path /usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/gconv:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/audit:/usr/lib/git-annex.linux//etc/ld.so.conf.d:/usr/lib/git-annex.linux//lib64:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu:/usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git-annex/git-annex smudge --clean -- 01a/061e/11ea/950e/078d4d322ab0
  │       ├─git,33582 --library-path /usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/gconv:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/audit:/usr/lib/git-annex.linux//etc/ld.so.conf.d:/usr/lib/git-annex.linux//lib64:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu:/usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git/git --git-dir=.git --work-tree=. --literal-pathspecs cat-file --batch
  │       ├─git,33583 --library-path /usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/gconv:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/audit:/usr/lib/git-annex.linux//etc/ld.so.conf.d:/usr/lib/git-annex.linux//lib64:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu:/usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git/git --git-dir=.git --work-tree=. --literal-pathspecs cat-file --batch-check=%(objectname) %(objecttype) %(objectsize)
  │       ├─git,33584 --library-path /usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/gconv:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/audit:/usr/lib/git-annex.linux//etc/ld.so.conf.d:/usr/lib/git-annex.linux//lib64:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu:/usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git/git --git-dir=.git --work-tree=. --literal-pathspecs check-attr -z --stdin annex.backend annex.numcopies annex.largefiles --
  │       ├─{git-annex},33577
  │       ├─{git-annex},33578
  │       ├─{git-annex},33579
  │       └─{git-annex},33581
  └─{git},33560
```

CPU load is negligible (~10%) , and the file system (ZFS on NVMe) is essentially idle. Do we see the cost of creating processes? But even then, two objects per second don't seem realistic.

**Comment by joeyh** [comment]
Michael Hanke wrote:
> Thx @joeyh for the initial sanity check. The unlock process eventually finished
> after 16h. Other than the time, the state of the repo looks good:
> 
> 119M    keys

Now I really wonder what was in the database when it was 7 gb in size,
must have been a lot of tmp files..

If I got the numbers right, it unlocked 10 files/second; I'd be curious
how fast unlock of 1000 files in a small repo runs there, to get a baseline
to compare with and see how it degrades at scale.

> I have now started an initial git status
> 
> % git status
> Refresh index: 0% (127/539528)
> 
> It does about two objects per second, so if the speed is maintained, it will
> run for 74 days. It is crunching through the smudge filters
> 
> CPU load is negligible (~10%) , and the file system (ZFS on NVMe) is
> essentially idle. Do we see the cost of creating processes? But even then, two
> objects per second don't seem realistic.

I saw in your ps that you're using the standalone git-annex build, so it
has to bootstrap itself with a shell script, find the libraries etc,
every time. That dominates the startup time. If that used a static C
shim, it would be faster, but faster yet is a native git-annex binary.

It will still be fairly slow, the smudge interface is not well suited
for so many files.
https://git-annex.branchable.com/todo/git_smudge_clean_interface_suboptiomal/

-- 
see shy jo

**Comment by mih** [comment]
Thanks @joeyh I will investigate the impact of standalone vs thepackage from Debian proper.

> It will still be fairly slow, the smudge interface is not well suited for so many files.

Unfortunately, the datasets this exploration is about, are both large in N files, and in size. Not using v7 would imply not having thin mode, and that would mean 2x on unlock -- which sadly is needed because .... Matlab :(

**Comment by mih** [comment]
There is no need to keep this open.

**Comment by mih** [comment]
I happened to create a dataset with 35k unique subdatasets (all mounted straight under root). 6.2MB .gitmodules file. `.git` weighed 18GB after a total of 6 incremental `save` runs. Shrank to 4.8MB after `git gc --prune=now`.

`datalad subdatasets` takes 10s to report on all of them.

`datalad status -e no` is a bit faster with 8.5s

`datalad status -e commit` takes 4min52s
