### ISSUE TITLE
`git --git-dir <dir> annex init` yields worktree with bare repos

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3878]
Demo:
```
git init origin
git -C origin annex init
echo '123' > origin/file1
git -C origin annex add
git -C origin commit -m 'some'

git clone --bare origin clone
git --git-dir clone annex init
```

this leads to

```
% ls -l
total 12
drwxrwxr-x 9 mih mih 4096 Nov 20 11:59 clone/
lrwxrwxrwx 1 mih mih  178 Nov 20 11:59 file1 -> .git/annex/objects/G6/qW/SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b/SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b
drwxrwxr-x 3 mih mih 4096 Nov 20 11:59 origin/
```

The file is checked out in the parent dir. When using `git -C clone annex init` this is not happening, and initialization is performed as expected, without a work tree/checkout being created.

Unsure if this is a bug or a feature. @joeyh

**Comment by bpoldrack** [comment]
Well, this seems reasonable to me as is. You told annex init at CWD pointing to a git-dir to use und `clone/`.

**Comment by bpoldrack** [comment]
Okay. So, the broken symlink *is* an issue. I agree.
However, the overall thing to create a worktree where you called annex-init on seems fine and inline with git behavior from my point of view. You still can have a worktree with a bare repo and git itself does that as I'd expect it to.

**Comment by joeyh** [comment]
Michael Hanke wrote:
> git clone --bare origin clone
> git --git-dir clone annex init

Fixed in 43f19ef00aa1e1044a00f7e12ff7f362d467bfc5

-- 
see shy jo

**Comment by mih** [comment]
@joeyh Thx much!

**Comment by joeyh** [comment]
Benjamin Poldrack wrote:
> Okay. So, the broken symlink is an issue. I agree.
> However, the overall thing to create a worktree where you called annex-init on
> seems fine and inline with git behavior from my point of view. You still can
> have a worktree with a bare repo and git itself does that as I'd expect it to.

The bug was that it assumes there's a worktree with the bare repo,
which is not the case here because core.bare is set and no worktree is
explicitly specified.

-- 
see shy jo
