### ISSUE TITLE
addurls: add option to drop added content

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3879]
In crawler (to be included in 0.4.4), s3_simple pipeline gained a new option `add_immediately` to `annex drop` files immediately after indexing them.  It is necessary for crawling large datasets which cannot fit to the local drive (e.g. neuropixels dataset from Allen institute provides >200GB files).
In the bright future of "addurs powers all the crawling" (https://github.com/datalad/datalad-crawler/issues/22) it would be nice to make it available within addurls. May be it could be an option `drop_after=("add", "save")` (with "save", dropping when entire run completes) or alike

**Comment by kyleam** [comment]
@yarikoptic added such an option in 7460519545 (ENH: addurls(..., drop_after=True) to drop content after adding, 2020-10-23, gh-5081).
