### ISSUE TITLE
normalize_paths() can be a major slowdown for large N datasets

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3881]
Whenever an absolute path is provided, it will result in a `realpath()` call. This can be slow, depending on FS performance and path complexity. When done 500k times, it will have an impact.

**Comment by bpoldrack** [comment]
FTR: Had a quick look at the code of `_normalize_path`. It does a realpath on `base_dir` in addition. This is superfluous IMO, since `base_dir` should always come from `*Repo.path` which is a realpath already. So it's probing that path over and over again, I guess.

**Comment by yarikoptic** [comment]
but is it really a "major slowdown"? was there a usecase where you have noted datalad being stuck in that place and then speedily accomplished whatever it was destined to do "useful"?  or it was just code exploration for a possible optimization?

**Comment by mih** [comment]
No need to keep this open.
