### ISSUE TITLE
ENH: Commit message for subdataset installation?

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#3882]
When writing a basic, exemplary YODA-compliant data analysis ([here](http://handbook.datalad.org/en/latest/basics/101-130-yodaproject.html)), I'm making a point of how easily comprehensible a YODA project log can be:

```
Let’s take a look at the history of the midterm_project analysis dataset:

$ git log --oneline
c73efce [DATALAD RUNCMD] analyze iris data with classification analysis
789e6b4 add script for kNN classification and plotting
9466bd3 [DATALAD] Recorded changes
ab62c74 Apply YODA dataset setup
8d3c887 [DATALAD] new dataset

“Wow, this is so clean an intuitive!” you congratulate yourself.
```

What is not easily comprehensible from the log however is ``9466bd3 [DATALAD] Recorded changes`` -- this is the installation of a subdataset.

What I would like to do is attaching a commit message when installing a subdataset:

```
datalad install -d . -s https://github.com/datalad-handbook/iris_data.git input/ -m "install input data"
```

Can you see any adverse effect this could have? I've quickly implemented this in a PR I'll submit shortly (at least locally the tests don't complain) to show what I mean codewise.

**Comment by kyleam** [comment]
Sounds like a good idea to me, and in general I'm in favor of anything that enables specifying more meaningful messages.  (To really encourage/facilitate good commit messages I think we'll eventually need to support something like datalad/datalad-revolution#71.)

> Can you see any adverse effect this could have?

Nothing comes to mind.

**Comment by yarikoptic** [comment]
Great to see this coming, thank you @adswa !  Larger scope/discussion for this issue is also at https://github.com/datalad/datalad/issues/3316
