### ISSUE TITLE
Provide bioimagesuite ppl with a json of URLs

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3895]
It would be cool to have datalad hosted and interfaced on http://datasets.datalad.org (actually they need https).  It would be nice to provide a complete exhaustive list of (https) urls we have in our datalad metadata.

**Comment by mih** [comment]
The `metalad_core` extractor from https://github.com/datalad/datalad-metalad already includes this info: https://github.com/datalad/datalad-metalad/blob/master/datalad_metalad/extractors/core.py#L237

**Comment by yarikoptic** [comment]
yeay!  I now remembered that  we had extracted some for someone at some point, I think we did for mriqc ppl: https://neurostars.org/t/return-hash-and-url-for-every-nifti-file-in-datalad-super-dataset/2733

So it is information we already have. So something like this (re relative paths, #2679 closed-due-to-inactivity):
```
datalad -f json metadata --reporton files -r \
| jq '{path: .path, urls: .metadata.datalad_core.url}' \
| sed -e "s,\"$PWD/,\",g"
```
seems to work quite nicely:
```
...
{
  "path": "abide/RawData/NYU/0050987/session_1/anat_1/mprage.nii.gz",
  "urls": [
    "http://fcp-indi.s3.amazonaws.com/data/Projects/ABIDE/RawData/NYU/0050987/session_1/anat_1/mprage.nii.gz?versionId=j8PZRSiZkfyS9EvrUhi.LamkUTRNGXwa"
  ]
}
...
```

@bioimagesuiteweb - would something like that work for you? Any additional information you would like to see in such metadata dump? (note that we are not in control over target urls, so those which are http:// -- might or might not be available also via https://; and some might even be behind password authentication or have `"urls": null`

**Comment by yarikoptic** [comment]
the issue is really of the datasets.datalad.org and thus webui which is ATM deprecated within datalad-deprecated but eventually would be moved into datalad-webui for which there is a related issue https://github.com/datalad/datalad-webui/issues/6 .
FWIW: For files which we host, we already have nice context menu which would provide urls for nii etc files to go to bisweb, so it would be an extension to that.
