### ISSUE TITLE
node: to fixup permissions of files

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#390]
in many cases extracted files, if coming e.g. from windows, would have execution bit set.  We should clear it out.  Sure thing it could be an option for add_archive_content but imho should be a separate node allowing for specification of file patterns, mime types, etc to reset those executable bits (or may be wider range, e.g. setting up groups stickiness etc)

**Comment by yarikoptic** [comment]
since git doesn't care about permissions besides setting the executable bit, we just need probably `fix_permissions(file_re, executable=True/False)` so a node, which would get the filename in the `data`, and check what is the permissions of that file and either it has executable bit set or not to the desired value.

**Comment by glalteva** [comment]
@yarikoptic should I consider for `data` having multiple matches for the key 'filename'?

**Comment by yarikoptic** [comment]
What do you mean?  there could be only a single 'filename' item in a single `data`
