### ISSUE TITLE
Establish top level behavior rules/principles of DataLad

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3905]
Moved from https://github.com/datalad/datalad/issues/3759#issuecomment-559908687 which concerns change in `get` and `install` behavior in pre-0.12 release.

I am proposing us to discuss a possible list of rules/principles we could document as to describe how DataLad operates given a specific CWD, optional --dataset, and provided paths.  ATM there is no  such description, introduced changes break previous behaviors (e.g. as in #3759) under the premise of removing ambiguity, but to me everything is ambiguous since we have no clear description of expected behaviors like below.  So we [ourselves even get confused](https://github.com/datalad/datalad/issues/3759#issuecomment-562631994) either such a list of steps corresponds to current or proposed behavior. 

Here is the list of rules/steps I proposed.  I would welcome someone to add a changed set which corresponds to current (as of sample commands X, Y, Z) behaviors:

1. If no working dataset is explicitly specified (via `dataset` argument), a dataset current directory belongs to is taken as the "working dataset".  (note: If there is no "working dataset", that is ok (rules `4., 5.` below have "if"))
2. Any given command first operates on the path(s) within the dataset where path(s) belong to (clarification: a (sub)dataset path causes operation within that (sub)dataset; even `datalad install .` is ok).
3. `--recursive` flag could be used (where applicable) to make command operate within subdatasets of the provided path(s). 
4. If there is a "working dataset", changes on the paths performed in the sub-datasets of the "working dataset" are also saved in any sub-dataset on the path from the "working dataset" to the dataset specified path(s) belongs to (old behavior I think)
5. For the paths outside of the "working dataset" (if any), changes to their datasets are not saved in their possible super-datasets (old behavior)
6. Merely a note: some commands (e.g. `get` and `install`) might require necessary sub-datasets first being `install`ed to act on the path(s) specified on the command line.  Such sub-datasets will be installed regardless of relation to the working directory dataset (old bevavior, nothing really special here). `create` might require to create a directory in the specified path to act on.

**Comment by mih** [comment]
This has failed to ignite the desired discussion. In the meantime the behavior of the joint set of commands has further developed. I think, at present, the most useful for to pick such a discussion up -- if desired -- is a PR with a design document.

Will close this issue for now.
