### ISSUE TITLE
Remove --proc-pre/post (replacement: result hooks)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3908]
This new feature is proposed in https://github.com/datalad/datalad/pull/3903

I propose to remove its predecessors, because their are (from my POV) completely unused, untested, and less capable (only dataset procedures, not any DataLad command).

**Comment by bpoldrack** [comment]
I can't come up with a use-case that one couldn't solve by reacting to a result and although it kinda seemed obvious to have I never encountered any for `pre`, despite a theoretical "save everything before I do X", that - in reality - seems like the wrong way of doing it anyway.

So - I'm fine with removing the command based hooks.

**Comment by kyleam** [comment]
I also doubt these gained traction anywhere and would be fine with dropping them.

**Comment by mih** [comment]
Result hooks are now a mainline feature.
