### ISSUE TITLE
Slow S3 download datalad vs s3cmd

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3910]
Working on https://github.com/datalad/datalad/issues/3901 I noticed that `download-url` seems relatively slow, and indeed it seems to take about 50-100% longer than a straight-up download via s3cmd -- with `--nosave`.

Here are same representative times for a 0.5M file and my current location in Europe:

```
% time s3cmd get s3://hcp-openaccess/HCP_1200/123420/T1w/ribbon.nii.gz d2
download: 's3://hcp-openaccess/HCP_1200/123420/T1w/ribbon.nii.gz' -> 'd2'  [1 of 1]
 586704 of 586704   100% in    1s   449.42 kB/s  done
s3cmd get s3://hcp-openaccess/HCP_1200/123420/T1w/ribbon.nii.gz d2  0.21s user 0.04s system 12% cpu 1.886 total
```

vs 

```
% time datalad download-url s3://hcp-openaccess/HCP_1200/123420/T1w/ribbon.nii.gz --nosave -O t4
[INFO   ] Downloading 's3://hcp-openaccess/HCP_1200/123420/T1w/ribbon.nii.gz' into '/tmp/s3test/t4' 
[INFO   ] S3 session: Connecting to the bucket hcp-openaccess with authentication 
<snip progressbar>
download_url(ok): /tmp/s3test/t4 (file)
datalad download-url s3://hcp-openaccess/HCP_1200/123420/T1w/ribbon.nii.gz  -  0.49s user 0.06s system 15% cpu 3.652 total
```

In both cases an untracked file is left in the worktree.

Is this to be expected? Does anyone have a clue on where to start looking for the cause?

Thx!

**Comment by yarikoptic** [comment]
for me difference is smaller 
```
$> time datalad download-url s3://hcp-openaccess/HCP_1200/123420/T1w/ribbon.nii.gz --nosave -O t4
[INFO   ] Downloading 's3://hcp-openaccess/HCP_1200/123420/T1w/ribbon.nii.gz' into 't4' 
[INFO   ] S3 session: Connecting to the bucket hcp-openaccess with authentication 
download_url(ok): t4 (file)                                                                                                      
datalad download-url s3://hcp-openaccess/HCP_1200/123420/T1w/ribbon.nii.gz  -  0.41s user 0.07s system 38% cpu 1.255 total

$> time s3cmd -c ~/.s3cfg-hcp500 get s3://hcp-openaccess/HCP_1200/123420/T1w/ribbon.nii.gz d2
download: 's3://hcp-openaccess/HCP_1200/123420/T1w/ribbon.nii.gz' -> 'd2'  [1 of 1]
 586704 of 586704   100% in    0s  1275.25 kB/s  done
s3cmd -c ~/.s3cfg-hcp500 get  d2  0.14s user 0.05s system 24% cpu 0.779 total
```
and that time is probably impacted with all the python imports... if you were to test speeds -- test on some larger file, e.g. s3://hcp-openaccess/HCP_1200/123420/unprocessed/3T/rfMRI_REST1_LR/123420_3T_rfMRI_REST1_LR.nii.gz ... not to say that we (boto) might be slower to download or to establish a new download

**Comment by yarikoptic** [comment]
and for a larger one, we only get "faster" ;)
```
$> datalad download-url s3://hcp-openaccess/HCP_1200/123420/unprocessed/3T/rfMRI_REST1_LR/123420_3T_rfMRI_REST1_LR.nii.gz
[INFO   ] Downloading 's3://hcp-openaccess/HCP_1200/123420/unprocessed/3T/rfMRI_REST1_LR/123420_3T_rfMRI_REST1_LR.nii.gz' into '.' 
...                                                                   
datalad download-url   9.11s user 3.29s system 37% cpu 33.249 total

$> rm 123420_3T_rfMRI_REST1_LR.nii.gz 

$> s3cmd -c ~/.s3cfg-hcp500 get s3://hcp-openaccess/HCP_1200/123420/unprocessed/3T/rfMRI_REST1_LR/123420_3T_rfMRI_REST1_LR.nii.gz
download: 's3://hcp-openaccess/HCP_1200/123420/unprocessed/3T/rfMRI_REST1_LR/123420_3T_rfMRI_REST1_LR.nii.gz' -> './123420_3T_rfMRI_REST1_LR.nii.gz'  [1 of 1]
download: 's3://hcp-openaccess/HCP_1200/123420/unprocessed/3T/rfMRI_REST1_LR/123420_3T_rfMRI_REST1_LR.nii.gz' -> './123420_3T_rfMRI_REST1_LR.nii.gz'  [1 of 1]
 1260735111 of 1260735111   100% in   34s    34.70 MB/s  done
s3cmd -c ~/.s3cfg-hcp500 get   9.13s user 4.02s system 37% cpu 34.846 total
```

**Comment by bpinsard** [comment]
I have observed the same thing, our private S3 (minio) is on the same network and it is way slower than what to expect from a 1Gbit/s connection.

A related question: from [datalad code](https://github.com/datalad/datalad/blob/master/datalad/downloaders/s3.py), it seems that S3 remotes (or at least the downloads) are managed by datalad rather than git-annex? 
However, when I wanted to set up a private S3 sibling/remote I couldn't find any documentation on how to do this with datalad (only ssh remote was documented), so I ended up adding the remote with git-annex, but maybe it was wrong?

Could it be the reason why the transfer speeds are different?

**Comment by yarikoptic** [comment]
> I have observed the same thing, our private S3 (minio) is on the same network and it is way slower than what to expect from a 1Gbit/s connection.

"Talk is cheap, show me the ~~code~~ numbers!" (~~Linus~~Yarik)

> S3 remotes (or at least the downloads)

we only provide download functionality from s3:// urls (not supported by git-annex), where git-annex does annex special remotes on S3. 

> so I ended up adding the remote with git-annex, but maybe it was wrong?

you have done it right!

> Could it be the reason why the transfer speeds are different?

reasons could be multitude!  Unfortunately @mih has provided no further information.  I have explained possible differences (imports), haven't observed inferior performance (see above), and no more factual information came in the previous comment ;)  please try again, ideally on some large(r) files, and if you still observe it, report back here and I will reopen this issue.
