### ISSUE TITLE
RF `import *` statements

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3912]
I consider any and all of these cases evil, except for the first one -- where this is just as intentional, but also unavoidable

```
% git grep 'import \*'
datalad/api.py:from datalad.coreapi import *
datalad/customremotes/tests/test_datalad.py:from ...tests.utils import *
datalad/interface/run.py:from datalad.core.local.run import *
datalad/interface/tests/test_base.py:from datalad.tests.utils import *
datalad/support/tests/utils.py:from datalad.tests.utils import *
datalad/tests/test_misc.py:from .utils import *
datalad/tests/test_strings.py:from .utils import *
datalad/tests/utils.py:from ..utils import *
datalad/tests/utils.py:from ..support.vcr_ import *
```

I know that there is no easy way out of this mess, as we could decide to assume that anyone could have imported anything from anywhere in some code. However, I say, the sooner we get rid of this, the better.

**Comment by kyleam** [comment]
> datalad/interface/run.py:from datalad.core.local.run import *

I'm against removing this one.

**Comment by mih** [comment]
True, that would defeat its purpose. Thx for pointing it out!

**Comment by yarikoptic** [comment]
may be add a directive to pylint to ignore that so next time we grep, we know that we consciously ok with it

```
from datalad.core.local.run import *  # pylint: disable=W0401
```

**Comment by mih** [comment]
To be fair, once approached, it would have been obvious that it should stay.

**Comment by yarikoptic** [comment]
> To be fair, once approached, it would have been obvious that it should stay.

ok, whatever, let's re-approach it then upon the next cycle of similar fixes

**Comment by mih** [comment]
This only places where this pattern remains used (for non backward-compatibility grease cases) are some ancient tests. All good now.
