### ISSUE TITLE
"datalad status" no terminal output for clean datasets

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#3916]
#### What is the problem?
`datalad status` shows no response on dataset without changes.

#### What steps will reproduce the problem?
`datalad save ; datalad status`

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
`datalad 0.12.0rc6`

#### Is there anything else that would be useful to know in this context?
This is no bug. If there is nothing to stage or commit, `datalad status` does not return anything, no message at all. This is a bit confusing, it would make sense to actually return something on the terminal, maybe "nothing to save" etc, similar to what `git status` returns when there is nothing to commit.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
N/A

**Comment by mih** [comment]
I am not convinced that rendering a message is needed or helpful. Being silent is a common behavior IMHO.

```
mih@meiner ~ % mkdir empty
mih@meiner ~ % ls empty
mih@meiner ~ %
```
It doesn't say "there is nothing here" ;-)

There are also other reasons for running `status`, besides an intention to `save` something. Also,  it is not entirely correct that there is no "return value". In fact status reports verbosely. You can enable that via something like: `datalad -f json_pp status`. It is just the behavior of the default result renderer to be silent, when everything is clean.

I hope that sheds some light on the situation.

**Comment by dorianps** [comment]
Mine was a suggestion, of course. But from a development perspective I can hardly think of any tool that implies the work is done by not printing anything on screen. In addition, the `ls` command return the prompt instantly if there are no files, while `datalad status` can sit for 10 minutes and then return nothing. The first is a linux command with a single well defined purpose, whereas `datalad status` is a full algorithm of checks on git, git-annex, symlinks, etc. It just looks weird that the user request to know the status of a dataset gives no response at all, even more so since the underlying tools produce a response for the same `status` call.

I checked `datalad -f json_pp status` and, honestly, I don't think is of any use for routine use. It just prints a huge list of information that is not informative for humans. One would need to check by eye if the two commits match. Even trying to filter the output with ` datalad -f json_pp status | grep status" prints a huge list that brings no information.

Just my view on interfacing tools with a user. Maybe it would be helpful to add a flag on the level of information, i.e., say something at the end, or show some verbosity on what steps are being performed during a, say 10 minute long, run.

This is what `datalad -f json_pp status` produces on the containers dataset.

```
{
  "action": "status",
  "bytesize": 10344,
  "gitshasum": "fc74657269fdde51a30036a90a034ee72b55983b",
  "parentds": "/DATA/FEDERATED_DATASETS/containers",
  "path": "/DATA/FEDERATED_DATASETS/containers/scripts/create_singularities",
  "prev_gitshasum": "fc74657269fdde51a30036a90a034ee72b55983b",
  "refds": "/DATA/FEDERATED_DATASETS/containers",
  "state": "clean",
  "status": "ok",
  "type": "file"
}
{
  "action": "status",
  "bytesize": 4026,
  "gitshasum": "f8c3632515b2138f6c1baddf848d85a54bab72e5",
  "parentds": "/DATA/FEDERATED_DATASETS/containers",
  "path": "/DATA/FEDERATED_DATASETS/containers/scripts/singularity_cmd",
  "prev_gitshasum": "f8c3632515b2138f6c1baddf848d85a54bab72e5",
  "refds": "/DATA/FEDERATED_DATASETS/containers",
  "state": "clean",
  "status": "ok",
  "type": "file"
}
{
  "action": "status",
  "bytesize": 259,
  "gitshasum": "b777ffeefca6bf11ee54d11e963c6342e33a8c8e",
  "parentds": "/DATA/FEDERATED_DATASETS/containers",
  "path": "/DATA/FEDERATED_DATASETS/containers/scripts/tests/Singularity.arg-test",
  "prev_gitshasum": "b777ffeefca6bf11ee54d11e963c6342e33a8c8e",
  "refds": "/DATA/FEDERATED_DATASETS/containers",
  "state": "clean",
  "status": "ok",
  "type": "file"
}
{
  "action": "status",
  "bytesize": 136,
  "gitshasum": "7c424e286581fda57624fb32d8c78f95c8c77cbe",
  "parentds": "/DATA/FEDERATED_DATASETS/containers",
  "path": "/DATA/FEDERATED_DATASETS/containers/scripts/tests/arg-test.simg",
  "prev_gitshasum": "7c424e286581fda57624fb32d8c78f95c8c77cbe",
  "refds": "/DATA/FEDERATED_DATASETS/containers",
  "state": "clean",
  "status": "ok",
  "type": "file"
}
{
  "action": "status",
  "bytesize": 1065,
  "gitshasum": "ab0b36cf21867d602d11ddaf925c30a19db8ce75",
  "parentds": "/DATA/FEDERATED_DATASETS/containers",
  "path": "/DATA/FEDERATED_DATASETS/containers/scripts/tests/test_helpers.bash",
  "prev_gitshasum": "ab0b36cf21867d602d11ddaf925c30a19db8ce75",
  "refds": "/DATA/FEDERATED_DATASETS/containers",
  "state": "clean",
  "status": "ok",
  "type": "file"
}
{
  "action": "status",
  "bytesize": 3019,
  "gitshasum": "c9f3e2178748ac82033428508394efe82aeb29f7",
  "parentds": "/DATA/FEDERATED_DATASETS/containers",
  "path": "/DATA/FEDERATED_DATASETS/containers/scripts/tests/test_singularity_cmd.bats",
  "prev_gitshasum": "c9f3e2178748ac82033428508394efe82aeb29f7",
  "refds": "/DATA/FEDERATED_DATASETS/containers",
  "state": "clean",
  "status": "ok",
  "type": "file"
}
{
  "action": "status",
  "bytesize": 1812,
  "gitshasum": "6f7ed8d244bfa1aa3e6e1ec55ebbfa4880cc352c",
  "parentds": "/DATA/FEDERATED_DATASETS/containers",
  "path": "/DATA/FEDERATED_DATASETS/containers/travis/dummy_docker",
  "prev_gitshasum": "6f7ed8d244bfa1aa3e6e1ec55ebbfa4880cc352c",
  "refds": "/DATA/FEDERATED_DATASETS/containers",
  "state": "clean",
  "status": "ok",
  "type": "file"
}
{
  "action": "status",
  "bytesize": 940,
  "gitshasum": "2f80ca0933f94bc20d17d4dd5b82bb5028ebe6dd",
  "parentds": "/DATA/FEDERATED_DATASETS/containers",
  "path": "/DATA/FEDERATED_DATASETS/containers/travis/install.sh",
  "prev_gitshasum": "2f80ca0933f94bc20d17d4dd5b82bb5028ebe6dd",
  "refds": "/DATA/FEDERATED_DATASETS/containers",
  "state": "clean",
  "status": "ok",
  "type": "file"
}
```

**Comment by mih** [comment]
> I checked `datalad -f json_pp status` and, honestly, I don't think is of any use for routine use. It just prints a huge list of information that is not informative for humans. One would need to check by eye if the two commits match. Even trying to filter the output with ` datalad -f json_pp status | grep status" prints a huge list that brings no information.

You are possibly interested in checking `datalad --help` for the ability specify custom reporting formats that better fit your needs. I routinely use `-f json` (`json_pp` is the same, but formatted for human consumption) for interfacing with tools like `jq` to get pretty much arbitrary reporting flexibility. I have limited understanding of your needs, but I am quite satisfied with what I can personally achieve with it.

Feel free to send a PR with alternative result rendering capabilities. It would be better to discuss a concrete proposal.

I will retitle the issue for clarity.

**Comment by dorianps** [comment]
Thanks for the tips. I have limited time and understanding to enhance it (maybe aliases git style for datalad could be helpful here). Closing the issue for now, anyone else can reopen if needed.
