### ISSUE TITLE
Datalad status null when there are changes to commit

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#3919]
#### What is the problem?
Running `datalad status` after `datalad remove` shows no output, but `git status` shows changes to be commited. Not sure if this is normal.

#### What steps will reproduce the problem?
Create a a testme subdataset. Save the superdataset. Remove the subdataset, and run `datalad status; git status`. My log:
```sh
[dorian@mri processed]$ datalad remove --nocheck testme
remove(ok): /DATA/FEDERATED_DATASETS/study1/data/processed/testme (dataset)
[dorian@mri processed]$
[dorian@mri processed]$ git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    testme

no changes added to commit (use "git add" and/or "git commit -a")
[dorian@mri processed]$ datalad status
[dorian@mri processed]$
```

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.12.0rc6 on CentOS 7

#### Is there anything else that would be useful to know in this context?
No.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
N/A

**Comment by kyleam** [comment]
> Running `datalad status` after `datalad remove` shows no output, but `git status` shows changes to be commited. Not sure if this is normal.

`datalad status` should report deleted subdatasets.

Trying with the script below, I'm not seeing the issue.  Could you provide a minimal script that triggers the issue on your end?

<details>
<summary>script</summary>

```sh
#!/bin/sh

set -eux

cd $(mktemp -d --tmpdir dl-XXXXXXX)
datalad create
datalad create -d. subds
datalad remove --nocheck subds
git status
datalad status
```

```
+ mktemp -d --tmpdir dl-XXXXXXX
+ cd /tmp/dl-Enh5w6v
+ datalad create
[INFO   ] Creating a new annex repo at /tmp/dl-Enh5w6v 
create(ok): /tmp/dl-Enh5w6v (dataset)
+ datalad create -d. subds
[INFO   ] Creating a new annex repo at /tmp/dl-Enh5w6v/subds 
add(ok): subds (file)
add(ok): .gitmodules (file)
save(ok): . (dataset)
create(ok): subds (dataset)
action summary:
  add (ok: 2)
  create (ok: 1)
  save (ok: 1)
+ datalad remove --nocheck subds
remove(ok): /tmp/dl-Enh5w6v/subds (dataset)
+ git status
On branch master
Changes not staged for commit:
	deleted:    subds

no changes added to commit
+ datalad status
  deleted: subds (dataset)
```

</details>

**Comment by mih** [comment]
I cannot replicate this behavior:

```
mih@meiner /tmp/rmtest % . ~/env/datalad3-dev/bin/activate
(datalad3-dev) mih@meiner /tmp/rmtest % datalad create super
[INFO   ] Creating a new annex repo at /tmp/rmtest/super 
create(ok): /tmp/rmtest/super (dataset)                                                                                      
(datalad3-dev) mih@meiner /tmp/rmtest % datalad create -d super super/sub
[INFO   ] Creating a new annex repo at /tmp/rmtest/super/sub 
add(ok): sub (file)                                                                                                          
add(ok): .gitmodules (file)
save(ok): . (dataset)
create(ok): sub (dataset)
action summary:
  add (ok: 2)
  create (ok: 1)
  save (ok: 1)
(datalad3-dev) mih@meiner /tmp/rmtest % datalad remove -d super super/sub
(datalad3-dev) 130 mih@meiner /tmp/rmtest % cd super
(datalad3-dev) mih@meiner /tmp/rmtest/super (git)-[master] % datalad remove --nocheck sub
remove(ok): /tmp/rmtest/super/sub (dataset)
(datalad3-dev) mih@meiner /tmp/rmtest/super (git)-[master] % git st
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    sub

no changes added to commit (use "git add" and/or "git commit -a")
(datalad3-dev) mih@meiner /tmp/rmtest/super (git)-[master] % datalad status
  deleted: sub (dataset)
```

Can you please post a full log of all commands. Thx!

**Comment by dorianps** [comment]
Can't replicate on a new dataset, but the mismatch is still there, and does not go away even after saving with datalad.

```bash
[dorian@mri processed]$ git log -n 4
commit 6679b875f516e3af3d886619496e1bbaab8c3565 (HEAD -> master)
Author: Dorian Pustina <dorian.pustina@foundation.org>
Date:   Wed Dec 11 08:47:13 2019 -0500

    [DATALAD RUNCMD] containers/scripts/singularity_cmd run c...

    === Do not change lines below ===
    {
     "chain": [],
     "cmd": "containers/scripts/singularity_cmd run containers/images/bids/bids-mriqc--0.15.1.sing '{inputs}' '{outputs}' participant --participant-label XXXXXXXXXX",
     "dsid": "f38080bc-1895-11ea-982d-ecebb88942b0",
     "exit": 0,
     "extra_inputs": [
      "containers/images/bids/bids-mriqc--0.15.1.sing"
     ],
     "inputs": [
      "study1/data/bids/"
     ],
     "outputs": [
      "study1/data/processed/testme/"
     ],
     "pwd": "."
    }
    ^^^ Do not change lines above ^^^

commit 7a3ef7687fdde48cdddf9cedc73f0f86de6f67dd
Author: Dorian Pustina <dorian.pustina@foundation.org>
Date:   Tue Dec 10 23:41:28 2019 -0500

    [DATALAD] Recorded changes

commit 090460bc4909291317240e1e492d3bbbe0d1e9ac
Author: Dorian Pustina <dorian.pustina@foundation.org>
Date:   Tue Dec 10 17:18:03 2019 -0500

    [DATALAD] Recorded changes
[dorian@mri processed]$ git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    testme

no changes added to commit (use "git add" and/or "git commit -a")
[dorian@mri processed]$ time datalad status

real    2m37.306s
user    1m8.085s
sys     1m30.919s
[dorian@mri processed]$ datalad save
[dorian@mri processed]$ git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    testme

no changes added to commit (use "git add" and/or "git commit -a")
[dorian@mri processed]$
```

Anything else I can check?

**Comment by dorianps** [comment]
In other words, looks like the `datalad remove --nocheck` did not result in a commit to update the removal of the subdataset (the last commit is the `container-run` call), and `datalad status` does not pick up the change either.

**Comment by dorianps** [comment]
One more info, installing the dataset in a separate folder also produces a failed copy for `testme`, all the other subdatasets seem to have cloned well.

```
[ERROR  ] Failed to clone from all attempted sources: ['/DATA/FEDERATED_DATASETS/study1/data/processed/testme'] [install(/DATA/mettes/FEDERATED_DATASETS/study1/data/processed/testme)]
```

**Comment by kyleam** [comment]
> looks like the `datalad remove --nocheck` did not result in a commit to update the removal of the subdataset

True.  I see that on both master and the 0.11.x.  I don't spot an existing issue for that, and it's a distinct issue from `status` not reporting the removed subdataset, so I'll open another report about that.

**Comment by dorianps** [comment]
Can I use `git commit` to proceed for now or does datalad need to keep track of things elsewhere and I risk to mess thigns up with git commit?

**Comment by kyleam** [comment]
Yes, it's safe to use `git commit`.

**Comment by kyleam** [comment]
> Anything else I can check?

I suspect the most effective way to troubleshoot this would be to step through the execution of `datalad.support.gitrepo.GitRepo._diffstatus` and look at how it handles that subdataset path.  (It is essentially deciding the state based on looking at the output of `ls-files --stage -d -m [...]`,  `ls-tree -lr [..] HEAD`, and `ls-tree -m [...]`.)  Perhaps the issue is elsewhere, but that's where I'd look first.  But since only you have a repo that triggers this (though perhaps not any longer if you've call `git commit` directly :/), that's a good amount of work on your end.

It might be helpful to look at verbose debug output (e.g., `export DATALAD_LOG_LEVEL=9`), but that's going to be a flood of information, and I don't think I personally would have much luck extracting the important details from it.

**Comment by dorianps** [comment]
I have already committed the change, but I've noticed on a couple of other
occasions that git status and datalad status were not matching.

If I encounter the issue again I will try to use the commands you mention
above to try troubleshooting. We can close this issue now.
