### ISSUE TITLE
remove does not commit removal of subdatset

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3920]
As reported in #3919, `remove` does not commit the removal of a subdataset on either master or 0.11.x.  That is inconsistent with how `remove` behaves with non-dataset items (unless `--nosave` is given).

`remove` still uses annotated paths, so perhaps the most feasible fix is to just couple this with the rewrite to drop annotated paths from `remove`.  With 0.12.x, we've talked about moving away from most subcommands saving things themselves, and requiring a follow-up call to `save`, so going that direction would of course resolve this issue as well.

---

Here's a script from #3919 that shows the issue:

<details>
<summary>script</summary>

```sh
#!/bin/sh

set -eux

cd $(mktemp -d --tmpdir dl-XXXXXXX)
datalad create
datalad create -d. subds
datalad remove --nocheck subds
git status
datalad status
```

</details>

**Comment by dorianps** [comment]
@kyleam  and others. I think what might have happened is this:

Before the problem emerged, I tried to delete git history because I thought the .git folder was keeping 9Gb of long history for nothing. I followed the solution found here:
https://stackoverflow.com/questions/13716658/how-to-delete-all-commit-history-in-github
```
git checkout --orphan latest_branch
git add -A
git commit -am "commit message"
git branch -D master
git branch -m master
```

This might have caused some sort of undetached HEAD state, which now I still see when running `datalad update --merge` on a sibling.
```
[INFO   ] Submodule HEAD got detached. Resetting branch master to point to c63c290a. Original location was f1431e2b
```

I will check online if there is a solution, but before doing that I wanted to ask if you know of a solution to resolve all the potential head deatched states in nested submodules easily.

**Comment by kyleam** [comment]
> I think what might have happened is this:

For clarity: I believe you're referring to is gh-3919, which is about `git status` reporting a deleted submodule while `datalad status` does not.  The misbehavior reported in this issue, which was spawned by that one, is that `datalad remove` does not commit the removal of a subdataset, which AFAICT is a consistent bug that's present on both the 0.11.x maintenance branch and the master branch.

> Before the problem emerged, I tried to delete git history because I thought the .git folder was keeping 9Gb of long history for nothing. [...]

Thanks for providing more details.  I'd very much like to figure out what was going on in gh-3919.

Hmm, at first glance, I don't see anything in the procedure above that seems like it'd make `git status` and `datalad status` disagree.  Quickly testing I was unable to trigger the issue from gh-3919 using the setup.

> ```
> [INFO   ] Submodule HEAD got detached. Resetting branch master to point to c63c290a. Original location was f1431e2b
> ```

This message typically isn't a cause for alarm.  When installing a subdataset, DataLad clones it down and then runs `git submodule update ...` to put the subdatset on the same commit that is registered in the superproject.  This often leads to a detached HEAD.  If DataLad notices that the detached HEAD is in the history of the branch it was on when it initially cloned the repo, it guesses that that's the desired branch and moves that branch to the registered commit.

**Comment by dorianps** [comment]
Thank you @kyleam . I just found a similar conclusion as yours online (post [here](https://stackoverflow.com/questions/18770545/why-is-my-git-submodule-head-detached-from-master/55570998)). This is good, we are now starting to implement the collaborative plan where each will have their own siblings and we will merge and update each other's siblings. Hopefully this will go smoothly.

**Comment by kyleam** [comment]
I said
> `remove` does not commit the removal of a subdataset on either master or 0.11.x. That is inconsistent with how `remove` behaves with non-dataset items (unless `--nosave` is given).

Oy, I should have considered that it was by design.  If you specify the current dataset with `-d.`, it is saved (and the code suggests that's a deliberate choice).

**Comment by kyleam** [comment]
I said
> If you specify the current dataset with `-d.`, it is saved (and the code suggests that's a deliberate choice).

And given that, I supose it's fine to close this and let inter-command consistency be handled as part of a larger push (e.g., #3905).
