### ISSUE TITLE
dataverse

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#393]
Might be cool to try.  There is an API (eg to fetch info for a dataset using persistent id https://dataverse.harvard.edu/api/datasets/:persistentId?persistentId=doi:10.7910/DVN/ARKOTI, https://github.com/IQSS/dataverse/issues/1837#issuecomment-197468164) and then we could use search mechanism (need API token) http://guides.dataverse.org/en/4.3/api/search.html to fetch listing of datasets (I guess eventually we could ask for an API cmd for that too ;)).
It is an interesting one since it is also distributed, hierarchical (we could use dataverse server as first level, two levels from doi) and would be a good check for scalability.  https://dataverse.harvard.edu/dataverse/harvard lists 60k datasets from 1000 dataverses.  Some data there is even neuroimaging related (a few MRI/DTI/... studies).
Should be an easy thing to setup IMHO... and would be somewhat an ideal case for scalability testing, especially whenever we start dealing with metadata

**Comment by yarikoptic** [comment]
more references:  another API to expose contents of dataverses:  http://guides.dataverse.org/en/4.3/api/native-api.html

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
