### ISSUE TITLE
install could be more clever with a single URL given

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#394]
````
% datalad install https://github.com/psychoinformatics-de/studyforrest-data-visualrois.git
1 installed item is available at
<Dataset path=/tmp/https:/github.com/psychoinformatics-de/studyforrest-data-visualrois.git>
````

The result (an empty repo) is most likely not intended. One solution would be to special case a single argument that looks like a URL and mimic the behavior of `git clone` in this case.

**Comment by hanke** [comment]
Follow-up:

````
% datalad install -s https://github.com/psychoinformatics-de/studyforrest-data-visualrois.git
Nothing was installed
````

This condition could be tested and a helpful "need to specify installation path" could be given.

**Comment by bpoldrack** [comment]
I think the first case should be mapped to the second one, which then installs according to git clone logic (not asking for a path, but let git clone do it). Objections?
