### ISSUE TITLE
Add sys.argv into WTF?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3941]
Originally was desired to be added to the "helpme" crash log reporting https://github.com/datalad/datalad/issues/3649, but I think it could be just added into `WTF` output, if any of the first 3 elements in `sys.argv` end with `datalad` (after `os.path.split`) or always (why not?).  The only concern could be -- couldn't it contain sensitive information? (e.g. `datalad create-sibling-github` invocation could have password or any `run` etc have some sensitive info).

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
