### ISSUE TITLE
What is our markup convention for variable references in the documention?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#395]
I can see

1. VARIABLE
2. `variable`
3. ``variable``

From the RST perspective the 3. is the appropriate choice (e.g. exercised by nibabel): [literal vs interpreted](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#interpreted-text)

I was personally lazy and used 2 -- it is conceptually wrong, but is usually rendered the same way. I don't know what the motivation for uppercasing is.

In any case, we should agree on one style and stop mixing.

**Comment by yarikoptic** [comment]
yeah -- 1 is wrong, unless referencing env variable?
actually I think that 2 (single back tick) is the closest one since theoretically it should be with description of its role, i.e. ``:var:`variable``` but we simply omit it.  Also makes reading docstrings easier, not too overloaded with backquotes.  So why is it conceptually wrong? ;)

**Comment by hanke** [comment]
With your interpretation it is not conceptually wrong ;-)

So single back ticks it is and everything else is a bug.

**Comment by hanke** [comment]
As I already talked to @bpoldrack I am closing this one as "settled".

**Comment by bpoldrack** [comment]
In general I agree, but reopen to mention, that there is a TODO regarding this topic:

The reason for the use of uppercase is, that this is the way, docs are rendered for command line output of --help. Therein the parameter names are referenced in uppercase and we currently don't render backticks in a way, that fits for help output in commandline. We still need a solution.

**Comment by mih** [comment]
I think we are good on this one.
