### ISSUE TITLE
Transition `clone()` to core.distributed

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3957]
Following up on #3192 I want to start moving `clone()` to the core API. This is also related to the ongoing discussion on scope and behavior of `install` and `get`.

At the moment, `clone` is pretty much taking all arguments defined by `install` as-is, and implements all non-get functionality of `install`. For a transition to the core API I think it mandatory to discuss the status quo of the `clone` API and identify issues that should be addressed beforehand.

### --reckless
One issue I personally have is the boolean nature of the `reckless` option. Similar to other commands, we should switch to a mode-style option with literal mode labels as expected values. This would already be useful in tailoring the "recklessness style" in scenarios such as throw-away clones that were mentioned in https://github.com/datalad/datalad/issues/3887 and where a related implementation is available in an extension https://github.com/datalad/git-annex-ria-remote/pull/31

### --alternative-sources
Moreover, I think we should discuss the need for `--alternative-sources` (`alt_sources`). This is a primarily (if not exclusively) internally used option. Its existence is probably due to me not properly reflecting on what is needed, and avoiding a larger RF.

Nowadays we have the `datalad.get.subdataset-source-candidate-<name>` (consider rename?) config mechanism that covers some of that in a more flexible way (templating support), and functionality such as "also look at URL + `/.git`" can be RF'ed to move inside `clone`.

### --message

Implicitly requested by https://github.com/datalad/datalad/issues/3882 and confirmed by https://github.com/datalad/datalad/issues/3896

### default return value

ATM the Python command gives a single-item list with a result dict for the installed dataset. IMHO it would be more useful to change the defaults to:

`clone(..., result_xfm='datasets', return_type='item-or-list')`

such that a single dataset instance is returned.

### behavior on clone into non-empty location

ATM clone would fail with

```
{'action': 'install',
 'path': '/tmp/~/forrest/collection/phase2',
 'type': 'dataset',
 'status': 'error',
 'message': 'target path already exists and not empty, refuse to clone into target path',
 ...}
```
I think it would be worth considering a check if the location actually contains a dataset from the source that was given, and issue a `notneeded` result in this case, instead of a failure. In combination with a change in the default return value, this would enable the same idempotent behavior that `install` is offering for already present subdatasets.

### related issues with potential implications for behavior changes

- configure origin of a clone *source* as a remote https://github.com/datalad/datalad/issues/3926
- throw-away clones https://github.com/datalad/datalad/issues/3887

What do you think @datalad/developers ?

**Comment by mih** [comment]
I would start along these lines. Please stop me, if you have concerns -- to avoid wasting time.

**Comment by yarikoptic** [comment]
Something ahead: install eventually would get super power to install a specific version (or a branch) of a dataset. We already do something along those lines during clone (I believe) for subdatasets, but may be (just may be) it could be considered during this RF.
Related to above, but unrelated to clone, would be ability to specify what to get. So in a single install command user could get not just all data, but some of interest. (https://github.com/datalad/datalad/issues/1810)

Re reckless: we would need something like auto mode - on file systems with cow, it might then do nothing special; on others - what it does now

**Comment by mih** [comment]
Done for a while already.
