### ISSUE TITLE
Minor issue: datalad get would fail for newly pulled subdatasets

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#3968]
#### What is the problem?
Suppose there two clones of a datalad superdataset in A and B, both having the subdatasets 1,2,3. If B adds a new subdataset 4, and A adds B's location as a sibling and runs `datalad update --merge --sibling B`, what happens is that A will now have subdataset 4, but cannot get the actual data. To get the data you normally run `datalad get --source B`, but this would fail because the new subdataset 4 does not have B as a remote in A. The workaround is to add manually the remote B on the newly pulled subdataset 4 inside A, then try `get` again. 

#### What steps will reproduce the problem?
Sorry, no code for now, above explanation should help create the situation.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.12.0rc6 from Github on Dec 2019

#### Is there anything else that would be useful to know in this context?
Though this is not a serious bug, it is confusing to the user. Moreover, it is problematic when there are hundreds of subdatasets. Running `sibling add` one by one is not reasonable, so I usually go for `sibling add --recursive` from the parent dataset. This in turn throws lots of errors for existing remotes in old subdatasets, but fixes the new ones too. The point is that the process is not smooth and shows errors. Maybe datalad can handle this situation automatically.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
NA

**Comment by kyleam** [comment]
> Sorry, no code for now, above explanation should help create the situation.

I believe the minimal example below matches the situation you're describing.  I've dropped the nonessential subdatasets 1-3 and renamed the subdataset of interest, 4, to "subds".

```sh
#!/bin/sh

set -eu

cd "$(mktemp -d --tmpdir dl-XXXXXXX)"

datalad create A
datalad clone A B
datalad -C A siblings add --name B --url ../B

datalad -C B create -d. subds
echo foo >B/subds/foo
datalad save -d B -r

cd A
datalad update --merge --sibling B
datalad get --source B subds
```

The final command fails with something like

```
[...]
Remote 'B' is not available. Command failed:
RemoteNotAvailableError: command 'annex get'

install(ok): /tmp/dl-hKgGNo1/A/subds (dataset) [Installed subdataset in order to get /tmp/dl-hKgGNo1/A/subds]
```

Note, however, that the crucial bit is `--source B`.  That subdataset was cloned with the default remote name of "origin".

```
A/subds$ git remote -v                                 
origin	/tmp/dl-hKgGNo1/A/../B/subds (fetch)
origin	/tmp/dl-hKgGNo1/A/../B/subds (push)

A/subds$ datalad get foo
get(ok): foo (file) [from origin...]
```

As far as I know, datalad doesn't provide a way to control the name of the remote that the repository was cloned from (i.e. it doesn't expose `git clone -o NAME ...`).

**Comment by dorianps** [comment]
I guess the challenge for datalad is to add the remote for each newly
pulled subdataset. If a dataset is being added by a pull it is obvious that
the location responsible for creating the subdatasets should be a remote.

**Comment by dorianps** [comment]
BTW, has the master for 0.12.0 switched from "install" to "clone"?

**Comment by yarikoptic** [comment]
Not really. Just in some use cases/ handbook it is used instead as the least common denominator for needed functionality

**Comment by kyleam** [comment]
> I guess the challenge for datalad is to add the remote for each newly pulled subdataset.

The url for the clone is being added as a remote.  It's just that it's named "origin".

> If a dataset is being added by a pull it is obvious that the location responsible for creating the subdatasets should be a remote.

Hmm, I think you're imagining a tighter link than there actually is between the sibling used in the `update` call and the clone url used when you call `get` on a subdataset.  Commits that register a new submodule may come from any remote that the user happens to fetch from, but that doesn't mean that the subdataset has a url that is based on the superdataset's remote.  `get` assembles a list of clone url candidates based on things like the configured remote for that branch, which remotes have the HEAD commit, and `get.subdataset-source-candidate-*` configuration values (see [get.py:_get_flexible_source_candidates_for_submodule][0] for more details).

We _could_ update `clone` to accept a name other than "origin" (i.e expose `git clone -o NAME ...`) and teach `get` to feed in the remote name to its clone call.  But I don't understand what the benefit of that would be, and a downside is that it would make the name of the added remote less predictable (it'd depend on the order in which remotes are tried, among other things).

[0]: https://github.com/datalad/datalad/blob/ea4a9f8aff38f4441c8c2c5fa95a51dbc256720d/datalad/distribution/get.py#L98-L136

**Comment by dorianps** [comment]
Sorry but I don't know what update uses in the background. What I meant is
that the newly pulled dataset should not have origin as remote but the
remote it is coming from. My master dataset, for example, does not have a
remote called origin, just ad hoc remotes/siblings that are added and
removed as needed.

If an update from custom remote creates new siblings with a remote origin,
it might be quite complicated to keep track of remotes. Particularly if
existing datasets already have an origin which points elsewhere, so origin
will be heterogeneous after the merge.

**Comment by kyleam** [comment]
As I mentioned at gh-4005, I think this issue is the same root issue as that one, so I'll close this (though please reopen if I'm mistaken).
