### ISSUE TITLE
Be robust/magical (i.e. crash with meaningful msg) if `install` is not possible

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#397]
ATM, if you clone some annex'ed repo, and then remove origin remote (I know -- noone must do that), `datalad install FILES` would crash with cryptic error msg (`AttributeError: 'GitRepo' object has no attribute 'annex_add'`) since repository wouldn't be considered 'annexed' (see below).  IMHO if "installation" fails for something which we (humans, and thus computers as well) can determine to belong to annex (symlink, empty file, tiny file with ref in it on windows) -- we should spit out some friendly informative message alike "Darling -- you have lost your annex somewhere, we can't find it among your remotes (x, y, z) and you have no git-annex branch".

```
(git)hopa:/tmp/ds000202[master]sub-1001/anat
$> datalad --dbg install * 
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venv-tests/bin/datalad", line 9, in <module>
    load_entry_point('datalad==0.1.dev0', 'console_scripts', 'datalad')()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 216, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/base.py", line 153, in call_from_parser
    return cls.__call__(**kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/install.py", line 120, in __call__
    recursive=recursive) for p in path]
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/install.py", line 273, in __call__
    added_files = vcs.annex_add(relativepath)
AttributeError: 'GitRepo' object has no attribute 'annex_add'
()
> /home/yoh/proj/datalad/datalad/datalad/distribution/install.py(273)__call__()
-> added_files = vcs.annex_add(relativepath)
(Pdb) p vcs
<GitRepo path=/tmp/ds000202 (<class 'datalad.support.gitrepo.GitRepo'>)>
(Pdb) 
```

**Comment by hanke** [comment]
I check for the was already implemented in https://github.com/datalad/datalad/commit/99051d0264d0d61a6549fe2950b19e9650d0e222

Closing.
