### ISSUE TITLE
create-publication-target-sshwebserver add-sibling broken

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#399]
````
% datalad create-publication-target-sshwebserver ssh://localhost testpublic --target-dir /tmp/remote -f
mih@localhost's password: 
 (cmd.py:351):47:43,228 [ERROR  ] stderr| Stop listening request sent.
2016-04-11 14:47:43,229 [ERROR  ] __call__() got an unexpected keyword argument 'sibling' [create_publication_target_sshwebserver.py:__call__:308] (TypeError) (main.py:223)
````

**Comment by hanke** [comment]
But:

````
/tmp/mine (git)-[master] % datalad add-sibling testpublic ssh://localhost/tmp/remote
Added sibling to one dataset:
mine
````

Nit-picking: Shouldn't the result rendering say `'.'` in this case?

**Comment by bpoldrack** [comment]
Not sure. I think 'mine' is okay. Especially since you no where explicitly stated to use '.'. But I don't know what's more intuitive to the user.

**Comment by hanke** [comment]
How would you then report the installation of a dataset at

`/tmp/mine/mine` while being in the same directory? `mine/mine`, or also `mine`? If this is a relative path, why should it be anchored one level up? A possible solution is to go for absolute paths all the time.

**Comment by bpoldrack** [comment]
Currently also mine, since this is the name of the toplevel thing, you are operating on. Reursivley called datasets would reported relative to this one. But yes, it's probably better to use absolute paths.

**Comment by hanke** [comment]
Original issue is no longer present.
