### ISSUE TITLE
Support `datalad -f '{relpath}'`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3994]
It would be convenient to be able get relative paths from the cmdline results for programatic post-processing. I.e. like this:

```
% datalad diff -f incoming^ -t incoming                 
    added: 1008788_20227_2_0.zip (file)
    added: 1008788_20249_2_0.zip (file)
    added: 1008788_20252_2_0.zip (file)
```

but just the relative path. Absolute is working already, relative not:

```
% datalad -f '{path}' diff -f incoming^ -t incoming                                                                                      
/data/project/rehab_biobank/datalad_trial/1008788/.datalad/.gitattributes
/data/project/rehab_biobank/datalad_trial/1008788/.datalad/config
/data/project/rehab_biobank/datalad_trial/1008788/.gitattributes
/data/project/rehab_biobank/datalad_trial/1008788/1008788_20227_2_0.zip
/data/project/rehab_biobank/datalad_trial/1008788/1008788_20249_2_0.zip
/data/project/rehab_biobank/datalad_trial/1008788/1008788_20252_2_0.zip

% datalad -f '{relpath}' diff -f incoming^ -t incoming
N/A
N/A
N/A
N/A
N/A
N/A
```

**Comment by mih** [comment]
I take that back. Adding this is less useful than I thought. The refds setting required for it is not very reliable, a `basename` is easy to produce on the cmdline, and it would still need result filtering in many places. I now believe that a `jq`-based solution is superior and already fully supported right now.

Example: Report the path of any dataset content that were added or modified by the last commit
```
datalad -f json diff -f HEAD^ -t HEAD | jq '. | select(.state == "added", .state == "modified") | .path'
```

**Comment by yarikoptic** [comment]
note that there was https://github.com/datalad/datalad/pull/2679 for this goal, didn't finish up, but could be a starting point
