### ISSUE TITLE
openfmri

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4]
https://openfmri.org is a popular NSF-funded project to federate a rich collection of neuroimaging data from cognitive experiments.

Pros:
- standardized layout
- redundant and heterogeneous data hosting -- XNAT, Amazon S3  (versioning was already enabled for S3)

Cons:
- redundant and heterogeneous data hosting -- care must be taken to establish proper "original data distribution" and make use of those additional data hosters

**Comment by hanke** [comment]
Note: OpenFMRI meta data will change and move towards the Brain Imaging Data Structure (BIDS) Specification -- at some point in the future.

**Comment by yarikoptic** [comment]
Well, since we are already providing some from http://datasets.datalad.org/openfmri  I will close this one for now
