### ISSUE TITLE
Composite (git submodules?) dataset handles with support for the views

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#40]
As HCP and NCANDA (via @nicholsn  with 10mil files)  shows, it might be in-feasible to aim supporting shipping the entire beast in a single git/git-annex repository, which suggests modularizing at least at the level of a single subject (or may be subject/modality or subject/visit) to be managed with e.g. git submodules or some "native" datalad distribution way.  But  then such  features as "views" of git-annex do not want to be lost since they provide really nice functionality to reexpose that data in an analysis specific convenient layout (given the meta-data is contained within annex). So this all requires additional thought on how to go about.

@joeyh  -- any ideas on how to go about growing large repositories partitioning/handling?

**Comment by yarikoptic** [comment]
related is probably the joeyh's sub-project to annex internet archive:  http://git-annex.branchable.com/design/iabackup/

**Comment by yarikoptic** [comment]
Since everything goes to having collections of multiple handles (e.g. per subject for HCP) it would be an issue of supporting passing those view commands to annex in each handle through the collection interface.

**Comment by mih** [comment]
Closing this. We have subdataset that do impose limits on their capabilities. We don't do anything with views, but that is another story.
