### ISSUE TITLE
idea: datalad/git-annex aware streaming/random access access to files content

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4003]
- ATM we have `AutomagicIO` which provide somewhat ad-hoc/ugly (relies on monkey patching "known" open calls) hack to automagically `datalad get` files being accessed
- there was another "idea" (desire) expressed to build atop some batched access to datasets (or files) content: https://github.com/datalad/datalad/issues/3121
- `git annex` contains information about where each file count be accessed from, often including URLs via standard protocols (http{,s}, ftp, etc)
- for many "remote" access mechanisms (http{,s} urls) 3rd party existing tools could be utilized to provide streaming or even random access using requests for specific bytes ranges (see https://github.com/dandi/infrastructure/issues/12 for pilot attempt using httpfs2 and a pointer to [astreamfs](https://gitlab.com/BylonAkila/astreamfs) tuned for streaming access).

Two modes could be envisioned

- "fetch and forget", with some optional cache for most recent/frequent requests -- would just fetch the content without anyhow affecting local `git-annex` store of the dataset
- "fetch and get" -- if user requests enough (e.g. `> 90%`) of the file content, we could as well fetch the rest, and make that annex key actually available in the local git-annex repository. Could be implemented by fetching initiating a sparse file, filling out its content as requests are coming in, and finalizing (fetching the rest and moving it under git-annex key) whenever file is closed.
- "sparse cache" -- cache requested/downloaded data (as [sparse files](https://en.wikipedia.org/wiki/Sparse_file) for original keys) in a local cache (with mtime/atime adjusted accordingly, so cache could be efficiently trimmed whenever needed)

I think it should be quite easy to achieve basic pilot (for "fetch and forget") implementation for Linux, by creating a datalad FUSE filesystem, which would 

- talk to git-annex to figure out where a key is available from
- initiating 3rd party tools (configurable -- httpfs2 or astreamfs for http, sshfs for ssh) to provide access to the content behind url
- functionality relying on random access of compressed files with indexes, such as .xz, could then seamlessly access specific files within those archives without requiring to download the entire archive  (see https://github.com/datalad/datalad/issues/373)

"user interface" to invoke it could be the same "datalad shell" we briefly discussed in the past (https://github.com/datalad/datalad/issues/2063), e.g. `datalad shell --mode=fs [COMMAND ...]` so that if there is no `[COMMAND ...]` - opens a shell, otherwise just executes the `COMMAND ...` under such "FUSE" control.  In Python could be a context manager, so ```with dl.shell(mode='fs'):``` (if possible to achieve in the same process ;) ).  Then, any (possibly domain specific) batching approaches desired in https://github.com/datalad/datalad/issues/3121 could be implemented on top.

**Comment by kyleam** [comment]
> creating a datalad FUSE filesystem

@notestaff has done some work on a FUSE file system for auto-getting git-annex content (mentioned [here][0]).  Perhaps that's worth looking into for inspiration.

[0]: https://git-annex.branchable.com/forum/How_to_prevent_copies_on_a_single_device_and_use_only_hardlinks/#comment-abd600260d934cef36884c08d8ccdacd

**Comment by yarikoptic** [comment]
adjusted description a bit -- added "sparse cache" -- I keep running into use cases which would benefit from having such FUSE file system.  In my case primary use case is "metadata extraction", which would also be needed for datalad-registry:  it would be infeasible/too expensive to download full data files, whenever likely on the header or some small amount of data spread out across the file (in case of hdf5 files) would be needed to extract metadata.  Primary use cases would be `http{,s}://` urls, often on S3 buckets (since we would not even be able to access data on ssh servers).

## rclone!

As additional tooling, I have just discovered that the mighty `rclone` has [rclone mount](https://rclone.org/commands/rclone_mount/) which seems to work magic

<details>
<summary>brief demo on datasets.datalad.org</summary> 

```shell
$> tail -4 ~/.config/rclone/rclone.conf
[http_datasets_datalad_org]
type = http
url = http://datasets.datalad.org/

$ mkdir /tmp/m-datalad ; rclone mount http_datasets_datalad_org:datalad /tmp/m-datalad

lena:/tmp/m-datalad/packages/neurodebian
$> time file git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb
git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb: Debian binary package (format 2.0), with control.tar.gz, data compression gz
file git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb  0.01s user 0.01s system 2% cpu 0.574 total

$> time md5sum git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb
0ea5994957513670410561a78f4f6f89  git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb
md5sum git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb  0.44s user 0.05s system 3% cpu 14.818 total
```

so it didn't fetch the full file to get access only to the header.

And when I remounted with a cache:
```
$> rclone mount  --vfs-cache-mode full http_datasets_datalad_org:datalad /tmp/m-datalad
```
it was indeed nicely cached !!!
```
$> time md5sum git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb
0ea5994957513670410561a78f4f6f89  git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb
md5sum git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb  0.35s user 0.05s system 2% cpu 18.354 total

$> time md5sum git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb
0ea5994957513670410561a78f4f6f89  git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb
md5sum git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb  0.10s user 0.04s system 92% cpu 0.155 total
```

```shell
(git)lena:~[master].cache/rclone
$> find -iname *deb -ls
 84353986  62632 -rw-------   1 yoh      yoh      64134894 Oct 25 10:56 ./vfs/http_datasets_datalad_org/datalad/packages/neurodebian/git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb
 84353987      4 -rw-------   1 yoh      yoh           251 Feb 24 10:51 ./vfsMeta/http_datasets_datalad_org/datalad/packages/neurodebian/git-annex-standalone_7.20190819+git2-g908476a9b-1~ndall+1_amd64.deb
```

and from the look of it those files in cache are sparse and get filled in as more data is requested.
</details>

<details>
<summary>and it did its magic for data (3TB file ;)) on S3 </summary> 

```shell
$> tail -8 ~/.config/rclone/rclone.conf

[s3_dandiarchive]
type = s3
provider = AWS
# region seems to be needed to be specified for anon access
# to work
region = us-east-2
storage_class = STANDARD
```

since no bucket is really specified, I should have just named it s3_us_east2 or alike.  It seems we would need first to figure out which region any given bucket in.

```shell
$ rclone mount --vfs-cache-mode full s3_dandiarchive:dandiarchive /tmp/m-dandiarchive
```

```shell
lena:/tmp/m-dandiarchive/largeuploads/blobs/f5d/aac
$> time ls -l 
total 3543836856
-rw------- 1 yoh yoh 3628888939868 Feb 18 20:57 79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2
LC_COLLATE=POSIX ls -bCF --color=auto --hyperlink=auto -l  0.00s user 0.01s system 71% cpu 0.008 total
1 60688.....................................:Wed 24 Feb 2021 11:09:29 AM EST:.
lena:/tmp/m-dandiarchive/largeuploads/blobs/f5d/aac
$> time file 79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2 
79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2: Hierarchical Data Format (version 5) data
file 79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2  0.01s user 0.01s system 1% cpu 0.971 total
1 60689.....................................:Wed 24 Feb 2021 11:09:39 AM EST:.
lena:/tmp/m-dandiarchive/largeuploads/blobs/f5d/aac
$> source ~/proj/dandi/dandi-cli/venvs/dev3/bin/activate
(dev3) 1 60690.....................................:Wed 24 Feb 2021 11:10:05 AM EST:.
lena:/tmp/m-dandiarchive/largeuploads/blobs/f5d/aac
$> dandi ls 79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2 
- nwb_version: null
  path: 79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2
  size: 3628888939868
2021-02-24 11:10:39,764 [ WARNING] Failed to operate on some paths (empty records were listed):
 ValueError: 1 paths
2021-02-24 11:10:39,764 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210224161018Z-1325592.log
(dev3) 1 60691.....................................:Wed 24 Feb 2021 11:10:39 AM EST:.
lena:/tmp/m-dandiarchive/largeuploads/blobs/f5d/aac
$> time h5ls 79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2
YO                       Group
h5ls 79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2  0.02s user 0.02s system 71% cpu 0.043 total
(dev3) 1 60692.....................................:Wed 24 Feb 2021 11:10:54 AM EST:.
lena:/tmp/m-dandiarchive/largeuploads/blobs/f5d/aac
$> time h5ls -r 79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2 > /tmp/h5ls.out
h5ls -r 79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2 >   0.01s user 0.02s system 72% cpu 0.042 total
(dev3) 1 60693.....................................:Wed 24 Feb 2021 11:11:29 AM EST:.
lena:/tmp/m-dandiarchive/largeuploads/blobs/f5d/aac
$> cat /tmp/h5ls.out
/                        Group
/YO                      Group
/YO/16_16_16             Dataset {128, 1622, 2759}
/YO/1_1_1                Dataset {2048, 25939, 44141}
/YO/2_2_2                Dataset {1024, 12970, 22071}
/YO/32_32_32             Dataset {64, 811, 1380}
/YO/4_4_4                Dataset {512, 6485, 11036}
/YO/64_64_64             Dataset {32, 406, 690}
/YO/8_8_8                Dataset {256, 3243, 5518}

```

`dandi ls` did take some seconds and traffic but completed reasonably fast. And now I have a 3TB file on my laptop's drive (which is having only a few GBs of free space):

```shell
(git)lena:~[master].cache/rclone
$> du -sch --apparent-size ./vfs/s3_dandiarchive/dandiarchive/largeuploads/blobs/f5d/aac/79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2
3.4T	

$> du -sch  ./vfs/s3_dandiarchive/dandiarchive/largeuploads/blobs/f5d/aac/79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2     
57M	
```
</details>

I have not tried yet to see if I could somehow access specific VersionId for S3'ed files... if we could do that -- `rclone` might be the ultimate tool (again)! (there is even `rclone mount` on windows!! crazy)

So, might be feasible to take @notestaff's existing [annex fuse](https://github.com/broadinstitute/viral-ngs/blob/is-dx-benchmarks/tools/git-annex-remotes/git-annex-on-demand.py) and just enhancing it with some `rclone`'ing of remote hosts/buckets, and proxying access to those FUSED up file systems... sounds crazy and inefficient, but may actually work damn well (in comparison to the necessity to fetch full datasets).

might also be of interest to @satra (although we are happily using ros3 hdf5 driver now for access to HDF5 files on S3 -- this more generic approach might come handy as well)

PS another tooling I found but didn't investigate is https://github.com/fangfufu/httpdirfs .

**Comment by satra** [comment]
nice! these are indeed good options to have. do you know if rclone mount relies on fuse or can be used completely in user space? if the latter, that would be fantastic.

**Comment by yarikoptic** [comment]
I don't see how more "user space" it could be without adding support in a specific IO library (e.g. like ros3 driver in hdf5) or overloading all low level system calls via some library you would `LD_PRELOAD` first, but even that might insufficient since e.g. [go does syscalls directly](https://github.com/rclone/rclone/issues/1637#issuecomment-326417145) apparently so even that would not be a full solution.

**Comment by bpoldrack** [comment]
> since we would not even be able to access data on ssh servers

FTR: While the approach needs some RF'ing and robustness improvement: We would - the way ORA remote does it.

**Comment by yarikoptic** [comment]
ORA does to access a file within the archive, not to a portion of the file within that file, right?  
but indeed, could also be worked out probably with smth like `sshfs` FUSE may be to provide transparent access to remote ORA-ed archives.  Could be quite cool
PS started to craft some ugly prototype... hopefully will find time to finalize it to some demo state working on at least S3, and at least without versioning support (https://github.com/rclone/rclone/issues/5064).

**Comment by bpoldrack** [comment]
> ORA does to access a file within the archive, not to a portion of the file within that file, right?

Not an addressable portion really, but ORA does actually read the file (whether or not in archive) in little chunks and "streams" it. It doesn't `scp` things, but has a subprocess with a persistent shell in which it executes something like `cat myfile && echo endmarker`. Stdout of that subprocess is read by the special remote and piped into local file.

Original reason was a huge latency for separate SSH calls (even w/ connection sharing) on some systems which was unbearable for something like an `git-annex fsck -f remote`. But we might want to utilize the approach for what you're thinking about here.

**Comment by yarikoptic** [comment]
Since `rclone` does not support yet access to "versions", I have continued my quest looking for more python solution. And I ran into [Introducing Remote Content Caching with FSSpec](https://www.anaconda.com/blog/fsspec-remote-caching) which leads us to [fsspec](https://filesystem-spec.readthedocs.io/en/latest/index.html) which
- [has implementation for access to https* urls and range requests](https://filesystem-spec.readthedocs.io/en/latest/_modules/fsspec/implementations/http.html?highlight=range)
- supports  [sparse files cache via blockcache](https://filesystem-spec.readthedocs.io/en/latest/features.html?highlight=sparse#caching-files-locally)
- [has some experimental FUSE](https://filesystem-spec.readthedocs.io/en/latest/features.html?highlight=fuse#mount-anything-with-fuse)
- supports [sparse files cache via blockcache](https://filesystem-spec.readthedocs.io/en/latest/features.html?highlight=sparse#caching-files-locally)
- [has some experimental FUSE](https://filesystem-spec.readthedocs.io/en/latest/features.html?highlight=fuse#mount-anything-with-fuse)
- [on github](https://github.com/intake/filesystem_spec), BSD-3 licensed, in Debian (although a bit outdated: 0.8.3 instead of 0.8.7 ATM; reported)

so I have created a very ugly and not yet exactly working right starting point (looks like it does but it seems to not work entirely right).  Those who are interested, have a look at https://github.com/datalad/datalad-fuse/commit/eb69598c66d5664841f9b61c04fa2bad1d7cdc77

**Comment by yarikoptic** [comment]
Echoing above, I think it is well worth to develop `datalad-fsspec` extension, which would provide 

- git-annex external special remote which would handle URLs supported by [fsspec](https://filesystem-spec.readthedocs.io/en/latest/) (e.g. `github://dask:fastparquet@main/test-data/nation.csv` from [this example](https://filesystem-spec.readthedocs.io/en/latest/usage.html#higher-level)).  
- an interface which would be a lean adapter around `fsspec.open` to `open` the annex'ed files, and thus providing a solution for for fetching portions of an archive (https://github.com/datalad/datalad/issues/373),  streaming (#3121), or "datalad shell" (#2063).
- become a base (and possibly a home) for the https://github.com/datalad/datalad-fuse, the sketch of which used fsspec.

**Comment by yarikoptic** [comment]
idea from @effigies 
![image](https://user-images.githubusercontent.com/39889/124822642-282df900-df3e-11eb-8b49-3c840f0507a4.png)
so might be worth adding some interfaces like that via some common entry point like `datalad fsspec CMD`.  I was wondering about smth like 

```head  `datalad open PATH` ```

where we would establish some "fake" temporary file and listen for the desired operations to channel to fsspec (fall into background task, finish it upon close etc), but I guess it would also need some kind of FUSE level for that.  So may be `head` on its own or `fsspec head` would still be worthwhile and cross-platform.

**Comment by effigies** [comment]
If I can suggest, `datalad stream` might be more meaningful than `datalad fsspec`. I'm not sure what all operations you would want to support, so maybe stream isn't the right subcommand...

Anyway, if it basically comes down to slicing, you could write: `datalad stream PATH [START_BYTE] STOP_BYTE`

If you have an index or are taking the first N bytes, you could slice the compressed contents: `datalad stream -z gzip [-i INDEX_FILE] PATH [START_BYTE] STOP_BYTE`

**Comment by thewtex** [comment]
Not sure how it would work in datalab, but possibly [fsspec-reference-maker](https://github.com/intake/fsspec-reference-maker) could be applied to nifti to index the header and  chunks.

**Comment by yarikoptic** [comment]
@effigies for now we did go with `fsspec-head` in https://github.com/datalad/datalad-fuse/pull/3 (possible renaming/move into a dedicated -fsspec is yet to discuss/do).  Works quite neat IMHO, welcome to try ;)

`fsspec-` prefix imho would be useful to even just disambiguate between possible extensions etc, and `stream` is a little too generic I think,  BUT I like the idea of  `datalad stream -z gzip [-i INDEX_FILE] PATH [START_BYTE] STOP_BYTE`


> `` head `datalad open PATH` ``
> 
> where we would establish some "fake" temporary file and listen for the desired operations to channel to fsspec (fall into background task, finish it upon close etc), but I guess it would also need some kind of FUSE level for that.

yes -- it would be nice, but indeed would need FUSE level -- so pretty much just a helper to mount FUSE filesystem somewhere and expose mounted there file location. So should be the dedicated command whenever we get (back) to FUSE implementation. Gave a bit of design formalization in https://github.com/datalad/datalad-fuse/issues/5 .

**Comment by yarikoptic** [comment]
I think any such functionality should be implemented within datalad-fuse which already provides some of the desired functionality (with or without FUSE), so I will just close this issue - file any new within that repo instead: https://github.com/datalad/datalad-fuse/
