### ISSUE TITLE
Add features to `clone`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4008]
These are left-over TODOs from #3966 

- [x] import 'ephemeral' reckless mode from `ria-install` https://github.com/datalad/git-annex-ria-remote for #3528 -> #4099 
- [x] support dedicated "URLs" for installing from a ria dataset store (like `store.datalad.org`) like `ria-install` does. The nature of that URL is to be determined, but likely consists of the store base url and the dataset ID. It should immediately foresee the need to obtain a specific version #2109

**Comment by yarikoptic** [comment]
if you are to extend "features" in general  -- might also have a look at https://github.com/datalad/datalad/issues/1347 .

**Comment by mih** [comment]
This has served its purpose.
