### ISSUE TITLE
Suggestions on how to use DataLad with very large datasets

### ISSUE THREAD

**Issue by satyaog** [datalad/datalad#4009]
#### What is the problem?
DataLad (git) with a large number of files (1.5M or 10-20M) is slow. I would like to have recommendations how to efficiently use DataLad with a large number of files or what should be my expectation in that context.
#### What steps will reproduce the problem?
1.5M files for 150GB takes more than 48h to index and almost the same time to move from one annex remote to another with annex.thin = true and annex.hardlink = true.

8M files for 1.3TB took more than 4 weeks to complete indexing and it unfortunately failed at the end (I actually have to check why). I have to say that there was a nice and ionice applied to the process but the machine was not under other heavy use for a long period of time.
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
DataLad 0.11.8, git-annex version: 7.20190819-ge4cecf8, git-annex local version 5
#### Is there anything else that would be useful to know in this context?
For the 1.5M files, I've tried to git-annex files per directories (1000 directories each containing 1500 files) without better results.
#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
I've successfully used DataLad to annex and track preprocessing steps on smaller datasets (10000s of files) using datalad run or annexed few big files (3 of 100GB).

Based on git limitation explained in #17, I'm tempted to use DataLad with archives of files instead of individual files and use datalad rerun to store the extraction commands. However, my current understanding is that I would have to write an empty commit myself (since datalad doesn't store empty commits) with the json needed for datalad rerun or maybe change the content of single file.

I haven't tested using annex.tune as mentioned in #32 but I'm not sure yet how to tune an existing repository (need to look deeper) or what should be my expectations in terms of performance gain.

**Comment by mih** [comment]
Here is an issue with info you might be interested in https://github.com/datalad/datalad/issues/3869

I'd recommend to start thinking about distributing files across multiple datasets once you go substantially beyond 100k files. DataLad makes working with dataset hierarchies fairly painless. Slowness with large N dataset is not just contributed by datalad, but also git-annex (see issue linked above), and Git itself have issue with such a large number of files.

**Comment by satyaog** [comment]
Thank you for the recommendation, I will start experimenting with this approach.

How is datalad handling conflicts across subdatasets? From my experience, it can be a pain to work with git submodules as the parent only sees different commit hashes when trying to merge two commits with changes inside sub-modules. Is it easier to handle with datalad update/publish maybe?

Second question would be regarding [git-annex caches](https://git-annex.branchable.com/tips/local_caching_of_annexed_files/). I suppose the benefits of having multiple subdatasets would not be compatible with caches?

**Comment by yarikoptic** [comment]
> How is datalad handling conflicts across subdatasets? From my experience, it can be a pain to work with git submodules as the parent only sees different commit hashes when trying to merge two commits with changes inside sub-modules. Is it easier to handle with datalad update/publish maybe?

I think it is indeed "easier" with `datalad` with default `update --merge` invocation since we would first merge (pretty much pull) within subdataset, and then (if no conflicts in that stage) just commit that updated state in the superdataset.    So, if you meant the case where superdataset got two different ideas (e.g. local one progressed, and remote one progressed) on what subdataset state should be - with explicit merge in subdataset we would (for better or for worse) avoid that.  Also note that current master (0.12.2-355-gc05783773) has extended `--merge` to allow for various strategies (`any`, `ff-only`). whichcould help

> Second question would be regarding [git-annex caches](https://git-annex.branchable.com/tips/local_caching_of_annexed_files/). I suppose the benefits of having multiple subdatasets would not be compatible with caches?

didn't play with caches much yet, but I think it would be working just fine.  You would just need to link ("manually") the same cache to multiple (sub)datasets ATM.

**Comment by yarikoptic** [comment]
since the original question (and follow ups ;)) were answered, I would close this issue.  Feel free to open new ones with other questions
