### ISSUE TITLE
datalad install should  output concise help

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#401]
ATM
```
$> datalad install                                       
2016-04-19 10:02:03,487 [ERROR  ] insufficient information for installation (needs at least a dataset or an installation path [install.py:__call__:114] (ValueError) (main.py:223)
```
It would be nicer and more homogeneous if it output the concise help information as other commands which do require some argument

**Comment by hanke** [comment]
That is easier said than done. Technically, "install" doesn't require an argument, but particular combinations are problematic, as you have shown.

One solution that I can see is a dedicated Exception type like `InsufficientArguments()` that we raise in this case and that we catch in the cmdline interface to trigger the help output.

Votes?

**Comment by yarikoptic** [comment]
exception approach sounds good to me -- "whatever makes it work" ;)  if "protocoled" by a unit-test we could later refactor with assurance not breaking previous behavior ;-P

**Comment by yarikoptic** [comment]
gr, khm  #418 should have closed this one automagically
