### ISSUE TITLE
update --merge: should invoke `git annex get --auto` at the end

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4010]
`datalad publish` (when no PATHs specified) already invokes `git annex copy --auto` to transfer preferred content if any is set for the remote.  `datalad get` doesn't have any interfacing to `git annex get --auto` AFAIK (https://github.com/datalad/datalad/issues/1347).  Besides `get` I think `update` should get  such capability.  
I think such operation should be default mode of operation for `datalad update --merge`, but it might be desired to disable this mode in some cases. So it might be worth RFing `--reobtain-data` into `--data={auto,reobtain,nothing}` . With `auto` (being default) it doing the `get --auto` if wanted is set for a local clone.

Actually probably it should also obtain an option similar to `--missing`of `publish` (e.g. `--new`) to specify what should be done to new subdatasets which didn't exist before.  With "inherit" value it should then inherit "wanted" settings (that is what `datalad publish --missing=inherit` would do).  The point is to make it address the most common usecase(s) which would require such functionality (currently e.g. @soichih 's attempt to keep a hierarchy of datalad datasets in sync and having all files he needs for ingestion).

**Comment by mih** [comment]
Ping #1313

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
