### ISSUE TITLE
Establish and use severity- labels to prioritize issues/PRs

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4011]
Inspired by https://github.com/datalad/datalad/issues/3808#issuecomment-573320479 .
I think we might want to establish a set of tags to mark "severity" or importance (may be mimicing [Debian](https://www.debian.org/Bugs/Developer) but melding top 3 together so we get):

- `severity-critical` - makes it unusable, causes data loss, introduces security vulnerability
- `severity-important` - major effect on the usability of a package, without rendering it completely unusable to everyone
- `severity-normal` - the default, majority of issues
- `severity-minor` - 
a problem which doesn't affect the package's usefulness, and is presumably trivial to fix
- `severity-wishlist` - feature request, and also for any bugs that are very difficult to fix due to major design considerations `FOI:` etc
- `severity-none` - for all the `FOI: ` and possibly some `Q: ` left unanswered

`critical` and `important` would be release blockers, and all issues should be categorized accordingly.  Then you could easily filter to not miss any important one.

**Comment by mih** [comment]
Given that this model works for Debian, my impulse response is in favor of such categorization.

**Comment by mih** [comment]
I have created the set of issues. I have renamed the existing 'wishlist' to 'severity-wishlist' in the process.
