### ISSUE TITLE
URL scheme for referencing datasets in a RIA store

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4017]
This is necessary to conveniently support installation from stores like `store.datalad.org`

I think something like this could work:

`ria://<label or host>#<dataset uuid[@<tag/branch/sha]`

The store label is used to look for potentially available local configuration on store access. The actual dataset location is generated or looked up based on a combination of store location and dataset uuid. Any version indicator is used to tune the cloned repository.

I think I prefer to use a dedicated url scheme (although I am not set on the "ria" name), because the datalad RIs have a different focus, and somewhat different semantics.

Some code to perform such location resolution is available at https://github.com/datalad/git-annex-ria-remote/blob/master/ria_remote/install.py but given that we have store.datalad.org it should rather be functionality provided by datalad-core.

**Comment by yarikoptic** [comment]
Should it like pip URLs include protocol, eg ria+ssh:// vs  ria+http:// ?

**Comment by yarikoptic** [comment]
Related on version: https://github.com/datalad/datalad/issues/2109

**Comment by mih** [comment]
@yarikoptic excellent point on encoding the protocol in the name. I like that.

**Comment by bpoldrack** [comment]
+1 for `ria+`
