### ISSUE TITLE
Replace patool with direct cmdline calls?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4019]
I wonder if there was a specific motivation to use patool for archive file management? Given issues like #3769 and #2555, and now #4018 I am thinking about reimplementing `compress_file` and `decompress_file` with direct calls to `7z` and `tar`. I think it would be relatively easy to do, and cut away an external dependency (even patool needs the underlying tools to be installed, it seems).

@yarikoptic

**Comment by yarikoptic** [comment]
the motivation was/is to not re-implement what was already implemented, and for many more archives than just .7z and .tar{,.xz,.gz}.  
We did have `.gz` and `.zip` at least as well.  I think I had some .rar and may be few others which I had "handled" with datalad at some point.

> I am thinking about reimplementing compress_file and decompress_file with direct calls to 7z and tar

Well, I guess nobody would stop you... (or you could fix patool to benefit not only datalad but other users of patool as well).  If you are to reimplement - just make it configurable (to be able to force use of patool) and use patool for other types of archives support for which you wouldn't reimplement.

**Comment by mih** [comment]
Point taken, but I am still not seeing the benefit of patool for our purposes. All of what you write above is possible with straight-up 7z cmdine alone. It supports all the formats you mentioned, including `tar.?` (so I wouldn't even bother with TAR). It might well be that the entire code to achieve the same results through 7z is less than the compatibility dance we are currently doing to pass information to patool.

**Comment by yarikoptic** [comment]
one of the issues I had with patool (and 7z for that matter) is handling large files: https://github.com/wummel/patool/issues/49

**Comment by mih** [comment]
I checked my recent work re archive file size. The largest archive I built has 1.9T, I can reliably extract arbitrary content from it:

```
$ ls -lh archive.7z
-rw-r--r-- 1 me users 1.9T Nov 16 22:54 archive.7z
$ 7z e archive.7z physio.json

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,32 CPUs Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz (50654),ASM,AES-NI)

Scanning the drive for archives:
1 file, 2063868614059 bytes (1923 GiB)

Extracting archive: archive.7z
--
Path = archive.7z
Type = 7z
Physical Size = 2063868614059
Headers Size = 391804
Method = Copy
Solid = -
Blocks = 42441

Everything is Ok                                                         

Size:       89
Compressed: 2063868614059
```

This particular archive uses no compression inside the container. I tested a 500G 7z with LZMA compression. It works equally fine.

```
$ 7z e archive2.7z IC_146_prob.png

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,32 CPUs Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz (50654),ASM,AES-NI)

Scanning the drive for archives:
1 file, 527731712730 bytes (492 GiB)

Extracting archive: archive2.7z
--
Path = archive2.7z
Type = 7z
Physical Size = 527731712730
Headers Size = 6660694
Method = LZMA2:24 BCJ
Solid = +
Blocks = 587

Everything is Ok                                                             

Files: 725
Size:       1604829618
Compressed: 527731712730
```

**Comment by yarikoptic** [comment]
The references issue was extracting from already existing .zip files, not .7z

**Comment by yarikoptic** [comment]
Anyway, implementing alternative handling of archives is ok with me, even making it to be default, but then falling to patool via config or automatically if eg unknown format or simply 7z is not available
