### ISSUE TITLE
.tar.gz of 0.12.0 on pypi is missing _datalad_build_support

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4021]
see #3808 for a "workaround" to e.g. assure having setuptools_scm present during release `setup.py sdist` call.

`pip install` goes fine since works with uploaded .whl , Debian package built fine since also we work from VCS branch on top of release, but any other distribution (like conda, see [sample build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=110250&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7)) would fail.

**Comment by kyleam** [comment]
Resolved with the just released 0.12.1. 

```
$ tar --list -f datalad-0.12.0.tar.gz | grep _datalad_build
$ tar --list -f datalad-0.12.1.tar.gz | grep _datalad_build
datalad-0.12.1/_datalad_build_support/
datalad-0.12.1/_datalad_build_support/__init__.py
datalad-0.12.1/_datalad_build_support/formatters.py
datalad-0.12.1/_datalad_build_support/setup.py
```
