### ISSUE TITLE
change in get behavior 

### ISSUE THREAD

**Issue by leej3** [datalad/datalad#4023]
#### What is the problem?
This worked pre 0.12.0. Now it does not. Just wanted to flag it in case the breakage was accidental...

#### What steps will reproduce the problem?
```
(Pdb++) Path.cwd()
PosixPath('/opt/afni/tests')
(Pdb++) test_data_dir
PosixPath('/opt/afni/tests/afni_ci_test_data')
(Pdb++) file_fetch_list
['mini_data/anat_3mm_no_skull.nii.gz']
```
Based on prior behavior I expect mini_data/anat_3mm_no_skull.nii.gz to resolve to  /opt/afni/tests/afni_ci_test_data/mini_data/anat_3mm_no_skull.nii.gz
```
(Pdb++) datalad.api.get(dataset=str(test_data_dir), path=file_fetch_list)
*** datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'action': 'get', 'path': '/build/afni_tests/mini_data/anat_3mm_no_skull.nii.gz', 'status': 'error', 'message': ('path not associated with dataset %s', <Dataset path=/opt/afni/tests/afni_ci_test_data>)}]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py", line 493, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py", line 481, in return_func
    results = list(results)
  File "/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py", line 468, in generator_func
    msg="Command did not complete successfully")
(Pdb++)
```
The file path is incorrectly resolved to `/build/afni_tests/mini_data/anat_3mm_no_skull.nii.gz`

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
[circleci](https://app.circleci.com/jobs/github/afni/afni/1486), v0.11 switching to v0.12

**Comment by kyleam** [comment]
There is an expected 0.12.0 change in behavior here.  Relative paths are only interpreted as relative to the dataset if a `Dataset` _instance_ is passed a the `dataset` argument.  Otherwise they are taken as relative to the current working directory.

> Based on prior behavior I expect mini_data/anat_3mm_no_skull.nii.gz to resolve to /opt/afni/tests/afni_ci_test_data/mini_data/anat_3mm_no_skull.nii.gz
> 
> ```
> (Pdb++) datalad.api.get(dataset=str(test_data_dir), path=file_fetch_list)

With that above change in mind, you either want pass the dataset as an instance (something like the long `datalad.api.get(dataset=datalad.api.Dataset(test_data_dir), path=file_fetch_list)`) or equivalently call `.get` as a dataset method (i.e. `datalad.api.Dataset(test_data_dir).get(...)`).

**But** there might still be a bug here.  Based on the `Path.cwd()`, it looks like your current working directory is `/opt/afni/tests`, so I would've expected the relative path to resolve to `/opt/afni/tests/mini_data/anat_3mm_no_skull.nii.gz`, not `/build/afni_tests/mini_data/anat_3mm_no_skull.nii.gz`.

**Comment by kyleam** [comment]
> There is an expected 0.12.0 change in behavior here. Relative paths are only interpreted as relative to the dataset if a `Dataset` _instance_ is passed the `dataset` argument. Otherwise they are taken as relative to the current working directory.

Here's a minimal script that shows this change in behavior:

<details>
<summary>script</summary>


```python
import pathlib
from pprint import pprint
import tempfile

import datalad.api as dl
from datalad.utils import chpwd

tdir = pathlib.Path(tempfile.mkdtemp(prefix="dl-"))
ds = dl.create(str(tdir / "ds"))

with chpwd(str(tdir)):
    for ds in [ds.path, ds]:  # str, instance
        pprint(dl.get(dataset=ds, path="not-there", on_failure="ignore"))
```

```
[INFO   ] Creating a new annex repo at /tmp/dl-b5jaca8y/ds 
[{'action': 'get',                                                                      
  'message': ('path not associated with dataset %s',
              <Dataset path=/tmp/dl-b5jaca8y/ds>),
  'path': '/tmp/dl-b5jaca8y/not-there',
  'status': 'error'}]
[{'action': 'get',
  'message': 'path does not exist',
  'path': '/tmp/dl-b5jaca8y/ds/not-there',
  'refds': '/tmp/dl-b5jaca8y/ds',
  'status': 'impossible'}]
```

</details>


> **But** there might still be a bug here. Based on the `Path.cwd()` output, it looks like your current working directory is `/opt/afni/tests`, so I would've expected the relative path to resolve to `/opt/afni/tests/mini_data/anat_3mm_no_skull.nii.gz`, not `/build/afni_tests/mini_data/anat_3mm_no_skull.nii.gz`.

If it's true that `/build/afni_tests/` isn't the current working directory, it'd be very helpful if you could try to wrap up the misbehavior you're seeing in a complete, minimal script.

**Comment by leej3** [comment]
Thanks @kyleam, making it a Dataset instance fixes my problem.

`/build/afni_tests` is a symlink to `/opt/afni/tests`. That is the cause of confusion there. Apologies, I should have gone for a more minimal example. I wasn't sure where my problem was and didn't want to deviate too far from my exact failure.

<details><summary>Path resolution works regardless of symlink status of cwd</summary>
<p>
    
     import datalad.api as datalad
     from pathlib import Path
     import os

     test_data_dir = Path('/opt/afni/tests/afni_ci_test_data')
     file_fetch_list = ['mini_data/anat_3mm_no_skull.nii.gz']
     Path.cwd()
    PosixPath('/build')
     datalad.get(dataset=test_data_dir,path=file_fetch_list)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py", line 493, in eval_func
        return return_func(generator_func)(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py", line 481, in return_func
        results = list(results)
      File "/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py", line 468, in generator_func
        msg="Command did not complete successfully")
    datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'action': 'get', 'path': '/build/mini_data/anat_3mm_no_skull.nii.gz', 'status': 'error', 'message': ('path not associated with dataset %s', <Dataset path=/opt/afni/tests/afni_ci_test_data>)}]


     os.chdir('afni_tests') # cwd will now be a symlink
     Path.cwd()
    PosixPath('/opt/afni/tests')
     datalad.get(dataset=test_data_dir,path=file_fetch_list)
    [WARNING] realpath of PWD=/build is /build whenever os.getcwd()=/opt/afni/tests. From now on will be returning os.getcwd(). Directory symlinks in the paths will be resolved
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py", line 493, in eval_func
        return return_func(generator_func)(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py", line 481, in return_func
        results = list(results)
      File "/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py", line 468, in generator_func
        msg="Command did not complete successfully")
    datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'action': 'get', 'path': '/opt/afni/tests/mini_data/anat_3mm_no_skull.nii.gz', 'status': 'error', 'message': ('path not associated with dataset %s', <Dataset path=/opt/afni/tests/afni_ci_test_data>)}]
</p>
</details>

**Comment by kyleam** [comment]
> `/build/afni_tests` is a symlink to `/opt/afni/tests`. That is the cause of confusion there.

Got it.  Thanks.

> Apologies, I should have gone for a more minimal example. I wasn't sure where my problem was and didn't want to deviate too far from my exact failure.

Ah, no worries at all.  Posting the exact failure as you did is great.  I just didn't have any ideas of where "/build/afni_tests" would be coming from, though if I were clever I would have guessed "symlink" :>

Closing, but please reopen if there's a remaining issue I'm missing.
