### ISSUE TITLE
GitHub actions support self-hosted runners!

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4029]
I didn't know... 
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-self-hosted-runners
so it smells like we could use our own infrastructure for runners which would be great for many use cases (custom file system setups etc), and may be also avoid hitting the free cpu allowance limits for github actions!  yet to try

**Comment by yarikoptic** [comment]
https://github.com/ci-for-research/self-hosted-runners provides nice detailed instructions and some ansible recipes for configuring self hosted runners for a number of scenarios (a docker image, virtualbox instance).
Also https://github.com/actions/virtual-environments/ provides packer recipes for the stock github actions environments and provides [instructions](https://github.com/actions/virtual-environments/blob/main/help/CreateImageAndAzureResources.md) on how to build them.  BUT it is all possibly too tight up into Azure, and the scripts which invoke packer are in powershell.

But I guess anyways this all should wait until github allows to provision some control (via "permitted users" or labels assignment on PRs from others) to avoid running potentially malicious code from PRs: see https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories , although if someone manages to configure some cloudy azure-like "start brand new VM" for every workflow run, could be done sooner.

**Comment by mih** [comment]
I believe @yarikoptic has such a setup running now
