### ISSUE TITLE
Need sphinx/docs solution to reference handbook content

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4034]
Instead of bloating the command docstrings it would often be helpful to add pointers to handbook content for background info or details.

If I want to do this now, I'd have to add something like this to a docstring

```
    .. seealso::

      http://handbook.datalad.org/en/latest/usecases/datastorage_for_institutions.html
        More information on Remote Indexed Archive (RIA) stores
 ```

It renders nicely in both manpage and HTML docs, but it still ugly, because it will unconditionally reference the latest version of the handbook, and not necessarily the version that corresponds to the running datalad.

@adswa has started maintaining release branches matching `MAJOR.MINOR` versions of DataLad in the handbook. So we have this URL available now:

http://handbook.datalad.org/en/0.12/usecases/datastorage_for_institutions.html

Now we could introduce a directive that enables us to place more readable handbook references, that point to the relevant version of the documentation.

**Comment by adswa** [comment]
I've started to look into defining custom roles that allow to reference the handbook, similar to the built-in ``:manpage:`` role of Sphinx. For the ``:manpage:`` directive, one defines the base url in ``conf.py``, e.g., ``manpages_url = 'http://docs.datalad.org/generated/man/{page}.html'``, and can subsequently link to the docs with ``:manpage:`datalad-create` ``.

From what the internet tells me, defining custom roles (e.g., a ``:handbook:`` role one can use with ``:handbook:`<version><section>` ``) seems to require writing a sphinx extension. Here is a tutorial that describes how a role similar to what we want is written:
https://doughellmann.com/blog/2010/05/09/defining-custom-roles-in-sphinx/

**Comment by mih** [comment]
I am on it -- half-working already.
