### ISSUE TITLE
Check if providers could provide an alternative url to point user to where to get credentials

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4044]
use case: http://github.com/conpdatasets/preventad-open

has
```
$> cat .datalad/providers/loris.cfg       
[provider:loris-prevent-ad]
url_re = https:\/\/openpreventad.loris.ca\/.*
credential = loris-prevent-ad
authentication_type = loris-token
loris-token_failure_re = "User not authenticated"}$

[credential:loris-prevent-ad]
url = https://openpreventad.loris.ca/api/v0.0.3-dev/login
type = loris-token
```
which leads to
```
$> git annex get preventad_5458966_NAPFU12_bold_002.mnc
get preventad_5458966_NAPFU12_bold_002.mnc (from datalad...) 
[INFO] Downloading 'https://openpreventad.loris.ca/api/v0.0.3-dev/candidates/5458966/NAPFU12/images/preventad_5458966_NAPFU12_bold_002.mnc' into '.git/annex/tmp/MD5E-s23636657--ed08ec2d2c5402baac5615f6a918096f.mnc' 
[INFO] http session: Authenticating into session for https://openpreventad.loris.ca/api/v0.0.3-dev/candidates/5458966/NAPFU12/images/preventad_5458966_NAPFU12_bold_002.mnc 
You need to authenticate with 'loris-prevent-ad' credentials. https://openpreventad.loris.ca/api/v0.0.3-dev/login provides information on how to gain access
user: 
```
but user needs to go to https://openpreventad.loris.ca not api/v0.0.3-dev/login of it to register. I guess `url` here is the programmable end-point

**Comment by yarikoptic** [comment]
probably for loris for now I will just overload this message to use top level url (`https://openpreventad.loris.ca`) of the url field.

**Comment by bpoldrack** [comment]
AFAICT, `credential.url` is used for nothing but this message. It's stated purpose is to point users to where to get credentials. Hence, there's nothing needed here, that could see. Simply change the url this config provides to the one that's actually useful for users and be done.

I'll close this for that reason. If I got something wrong - obviously feel free to reopen, @yarikoptic
