### ISSUE TITLE
datalad install of a subdataset into a dataset fails since provides None to git submodule call

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#405]
```
$> datalad install --dataset . d0/r0
2016-04-20 16:52:35,752 [ERROR  ] Failed to start ['git', 'submodule', 'add', None, 'd0/r0']" under '/tmp/123'": execv() arg 2 must contain only strings [subprocess.py:_execute_child:1335] (cmd.py:260)
2016-04-20 16:52:35,752 [ERROR  ] execv() arg 2 must contain only strings [subprocess.py:_execute_child:1335] (TypeError) (main.py:223)

$> ls -ld .git d0/r0/.git
drwx------ 8 yoh yoh 240 Apr 20 16:52 .git/
drwx------ 8 yoh yoh 240 Apr 20 16:51 d0/r0/.git/
```

I guess it wants me to provide a source... and I know we have discussed it but I see it as a common pattern so imho we should somehow support it (e.g. if provided path points to existing git repo and source is not provided, it is logical to assume that it is the source and craft corresponding source argument)

**Comment by bpoldrack** [comment]
Agree. Seems to make sense. But as far as I'm aware it's just about convenience, right? If you provide the source argument it works for you?

**Comment by bpoldrack** [comment]
Okay, found what's wrong with it. Just to check for the actual functionality to work, please use all three arguments: `datalad install --dataset . -s d0/r0 d0/r0`
That's a general issue with the API "definition". Therefore I think, we should currently use fully specified calls to make sure everything works and discuss API, whenever Michael is back.

**Comment by hanke** [comment]
We need to talk about this in the next meeting. I created a new issue label and used it for this issue to mark issue that should be discussed in the next conference call.

**Comment by yarikoptic** [comment]
Good idea... And I should bring back taking notes ;-)

**Comment by hanke** [comment]
Already fixed.
