### ISSUE TITLE
Manually copy large subdataset dataset folder instead of pulling files

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4051]
#### What is the problem?
As mentioned before, we have a master location of a superdataset and work on clones to fill and fix subdatasets which we pull in the master location. This time, I am processing some fmriprep data which will be about 6Tb in size, split into subdatasets. Trying to pull these changes into the master location will take another 6Tb and will take very long. Is there a way for me to copy the newly created subdataset folder called `fmriprep` in the master location, and just register it as subdataset in the parent dataset? In Linux command line this would be just the `mv` command, which is much faster than copying 6Tb of data.

A bonus question as well :) I am planning to create subdatasets for each subject, but data for each subject is split into multiple folders like this:

**./fmriprep/sub-11111111 (folder)**
./fmriprep/sub-22222222 (folder)
**./fmriprep/sub-11111111.html (file)**
./fmriprep/sub-22222222.html (file)
**./freesurfer/sub-11111111 (folder)**
./freesurfer/sub-22222222 (folder)

Is there a way for subdatasets to track specific folders in different places, like the bold items above?

#### What steps will reproduce the problem?
NA, my problem only.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.12.0rc6

#### Is there anything else that would be useful to know in this context?
NA

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
NA

**Comment by mih** [comment]
We are working on supporting "ephemeral" clones for such scenarios. The idea is that with datasets that are prohibitively large, such that any copying is not a good idea, one can setup clones that share the "master" annex. The feature is already implemented, it just needs a bit of polish to get fit for a PR into master. The ETA for a PR is very soon (days rather than weeks) -- it would be fantastic to have it be tested broadly.

PS: version 0.12.1 has been released. It would make sense to upgrade from rc6.

**Comment by dorianps** [comment]
Will upgrade in time. My data processing will finish in 15+ days, so I will update datalad with the new feature hopefully. This ephemeral idea though is new to me, and I would very much hope there is no mess-up of the master location. This is the reason why we use clones, i.e., researchers don't have access to write on the master location, and everything is vetted before being merged in the master location,

**Comment by yarikoptic** [comment]
Fwiw, if you use file system with cow (copy on write) support such as btrfs, copying data within filesystem could be done very efficiently and without wasting space. I would (will) have also checked if git annex move within clones on the same filesystem would just use mv command. 
BTW, for running fmriprep, do you use containers-run? We have ready to use containers etc in https://github.com/ReproNim/containers

**Comment by yarikoptic** [comment]
Fwiw, if you use file system with cow (copy on write) support such as btrfs, copying data within filesystem could be done very efficiently and without wasting space. I would (will) have also checked if git annex move within clones on the same filesystem would just use mv command. 
BTW, for running fmriprep, do you use containers-run? We have ready to use containers etc in https://github.com/ReproNim/containers

**Comment by dorianps** [comment]
@yarikoptic My storage array is, no btrfs unfortunately. I am using only datalad and not playing with git/annex just to be sure everything is done according to internal datalad procedures.

I am using a singularity container for fmriprep, with the latest v1.5.5 from a few days ago. But I am not using it through `datalad containers-run` for two reasons:
1. I need to run subjects in parallel with SGE job scheduler.
2. I plan to create subdatasets for each subject to optimize the hierarchical organization of datasets for easy save/status/etc.
So, for now, I am producing the data, then will run `datalad create --force` to make the subdatasets, and after that merge changes in the master location.

When posting the question here I was thinking that what I want to achieve can be done simply by
1. `mv` the entire folder at the master location.
2. Go to the parent dataset and add the entry in `.gitmodules` (I can even copy this entry from the clone location):
```
[submodule "fmriprep-1.5.5"]
        path = fmriprep-1.5.5
        url = ./fmriprep-1.5.5
        datalad-id = 3f433c48-1398-11ea-98da-ecebb88942b0
```
Wouldn't this be enough?

**Comment by dorianps** [comment]
A follow up on this procedure.
I copied my 6Tb subdataset from the location I was working at to the master location where I keep the data (within the same server). That was instant, so no headaches. I ran `datalad save` in the master location and now I can see the "imported" subdataset. However, when I check `.git/config` all subdmodules have the `url=/PATH/` pointing to the old location in absolute path. At the same time `.gitmodules` does not have this problem, it points to the relative path.

Question is, do I have to fix the URLs in `.git/config`? I can do this with a simple replace of the text in config, but other posts online [mention only using git commands](https://stackoverflow.com/questions/42028437/how-to-change-git-submodules-url-locally/42035018). But first things first, what problem might the wrong url in `.git/config` cause?

**Comment by dorianps** [comment]
Pinging this thread once more. Just want to make sure that, despite the "wrong" paths in .git/config, there is no problem and I can use the dataset without worries after moving the subdataset.

**Comment by yarikoptic** [comment]
sorry... I edit `.git/config` manually all the time ;)  yes -- replace paths with correct ones.  Not sure what problems might arise - I guess you would see if you don't change them ;)

**Comment by dorianps** [comment]
Got it, thanks. Closing issue.
