### ISSUE TITLE
Reenable github integration test

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4079]
A failing test of special-interest functionality was a blocker to an urgent global fix #4078

I disabled the test with cad795b0f73a952e38214c62fe1a35eef43d258a:

Please bring it back @yarikoptic

**Comment by yarikoptic** [comment]
the fact that it started to fail suggests that the interaction sequence with github has changed, and I wonder why it has changed (unless the #4078 fixed something which resulted e.g. in a new url or credentials being used)

**Comment by adswa** [comment]
It looks like this has been resolved by #5218?

**Comment by yarikoptic** [comment]
I think so, at least at that time. thank you @adswa ! left a relevant note on https://github.com/datalad/datalad/pull/5949#issuecomment-918164954 which provides a fresh generic reimplementation of github support.
