### ISSUE TITLE
How to rename subdataset folder?

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4084]
#### What is the problem?
I need to rename a subdataset folder. I don't need to move it, just rename the folder. The handbook says that one can just use the linux `mv` command and there will be no problem (I don't have siblings etc.):
http://handbook.datalad.org/en/latest/basics/101-136-filesystem.html#moving-renaming-a-superdataset

But since a git submodule is registered with a path, I don't see how this is not a problem. Can you please let me know what is the right way to do it. I.e., rename `data123` to `data12`.

#### What steps will reproduce the problem?
NA

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.12.1 (installed via github link few days ago)
By the way, `datalad wtf` does work efficiently anymore. It hangs there and took over 1 minute to respond, timing below:
```
real	1m28.283s
user	0m3.349s
sys	0m2.434s
```

#### Is there anything else that would be useful to know in this context?
No

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
NA

**Comment by yarikoptic** [comment]
The idea is that when you call `datalad save` it should do the right thing and do necessary adjustments. If it doesn't - it would be a bug. If it does - comment here and close this issue

Wtf - could you please run it with -l debug and file a separate issue with what you find

**Comment by mih** [comment]
Here is what it should do and does. Please reopen, if it doesn't do that for you, or if you find this to be problematic.

```
(datalad3-dev) mih@meiner /tmp % datalad create demo_super
[INFO   ] Creating a new annex repo at /tmp/demo_super 
create(ok): /tmp/demo_super (dataset)                                                                                                                                                        
(datalad3-dev) mih@meiner /tmp % cd demo_super
(datalad3-dev) mih@meiner /tmp/demo_super (git)-[master] % datalad clone -d . https://github.com/datalad/datalad.git path1
install(ok): path1 (dataset)                                                                                                                                                                 
add(ok): path1 (file)                                                                                                                                                                        
save(ok): . (dataset)
action summary:
  add (ok: 1)
  install (ok: 1)
  save (ok: 1)
datalad clone -d . https://github.com/datalad/datalad.git path1  5.18s user 0.75s system 68% cpu 8.685 total
(datalad3-dev) mih@meiner /tmp/demo_super (git)-[master] % git status
On branch master
nothing to commit, working tree clean
(datalad3-dev) mih@meiner /tmp/demo_super (git)-[master] % cat .gitmodules
[submodule "path1"]
        path = path1
        url = https://github.com/datalad/datalad.git
        branch = master
(datalad3-dev) mih@meiner /tmp/demo_super (git)-[master] % mv path1 path2
(datalad3-dev) mih@meiner /tmp/demo_super (git)-[master] % dl save
delete(ok): path1 (file)
add(ok): path2 (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  delete (ok: 1)
  save (ok: 1)
(datalad3-dev) mih@meiner /tmp/demo_super (git)-[master] % cat .gitmodules
[submodule "path2"]
        path = path2
        url = https://github.com/datalad/datalad.git
        branch = master
(datalad3-dev) mih@meiner /tmp/demo_super (git)-[master] % git st
On branch master
nothing to commit, working tree clean
```

**Comment by dorianps** [comment]
Got the answer. Thank you.
