### ISSUE TITLE
migrate to pytest or nose2

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4090]
#### What is the problem?

According to @effigies issue https://github.com/nipy/nibabel/issues/864 we might soon experience fallout of nose.  So, sooner or later we will need to migrate from it to pytest (or some other helper/runner if there is any, but unlikely pure unittest2 or alike). 

# pytest

I guess it will be our choice.  I personally have love/hate relationship with pytest.  IIRC major obstacles will be
- parametric tests.   pytest dropped support for nose-style generator-based parametric tests awhile back, so we will need to convert any parametric test like that to be implemented "pytest-way"
- decorators-vs-fixtures. Some of our decorators pass positional args into the tests. I would need to recall details on what we encountered in reproman, but I believe pytest would consider positional args as fixtures. So we would need to convert them to keyword args to avoid that or in some places convert our decorators into proper pytest fixtures.
- as we start using more of straight `assert` calls, instead of our (nose) helpers like `assert_smth`, we might need to provide pytest with ways to to be totally "pytest-ified" (later) we might like to provide our custom assertion failure handlers: https://docs.pytest.org/en/latest/assert.html#defining-your-own-explanation-for-failed-assertions  

# other alternatives mentioned by others

- nose2
   - cons: seems already not actively developed (last release 0.10.0 (2020-01-27) is almost 2 yo), on my attempts I did not see an easy pattern to migrate over to it
- https://packages.debian.org/python3-testrepository 
- https://packages.debian.org/python3-stestr

**Comment by effigies** [comment]
There is also nose2. I haven't really looked into it deeply.

**Comment by yarikoptic** [comment]
Indeed... Last time I had looked at it was years ago and it gave me feeling I had after trying to migrate from cfengine to cfengine2... But nose2 is indeed there, seems to be slowly but going forward, should provide easier transition than to pytest (haven't spotted any allow stoppers in description of differences from nose).

**Comment by djarecka** [comment]
@yarikoptic - let me know if you will need help. once `nibabel` is done, I can help with `datalad`

**Comment by yarikoptic** [comment]
Than you @djarecka ! I guess for us it might be worth first trying out nose2. And first starting with centralizing all testing support imports, so we don't import from nose but from datalad.tests.utils. that should simplify future switch

**Comment by djarecka** [comment]
@yarikoptic - ok, I know nothing about `nose2`, so don't have opinion.

If you decide to use pytest at the end - I was checking random tests files from `datalad`, and it looks to me that they will be easier to translate to pytest than the ones in `nibabel`, i.e. not as many classes and imports between tests (but I could be just lucky to chose the ones that don't have it).
Many of the `assert` statements (especially `assert_true`, `assert_false`, `assert_equal`) can be automatically translated using `nose2pytest`, but of course it's worth reviewing.

**Comment by effigies** [comment]
The main insight I have to offer from the nibabel experience is that vanilla `unittest` constructs work well with both nose and pytest. So if your goal is to never do this again and just switch to the most popular test-runner when it changes, I would try to do that as much as possible.

We don't use a ton of fancy features in tests, but:

1) `raise unittest.SkipTest` works in nose and pytest.
2) `@unittest.skip*` marks work in both nose and pytest. Except:
3) `@unittest.skip*` does not decorate non-`unittest.TestCase` classes, so you can choose whether to use pytest or patch `__init__`. This might only be an issue for nibabel's weird API validator classes.
4) `@unittest.expectedFailure` is underfeatured relative to `pytest.mark.xfail`. And it has the same class-decorating limitation. As above, it's a choice between pytest-specificity and verbosity.
5) pytest parameterization can't be run with nose. Nor can fixtures like `tmp_path`.

There is also a third-party package [parameterized](https://pypi.org/project/parameterized/), which works with nose, unittest, nose2, unittest2 and pytest. I didn't bother with it simply because we are using pytest, and there's no guarantee that parameterized won't also die at some point.

**Comment by yarikoptic** [comment]
thank you @effigies and @djarecka !  yes, one of the main "concerns" is parametrized tests of which we have a good bunch, and overall decorators on the tests (of which we also have a good number) -- I can't recall details but I have a feeling that some of them didn't play nicely with pytest.
I am not saying that it (migration to pytest) cannot be done though ;)

**Comment by djarecka** [comment]
@yarikoptic - perhaps, I can just try to do a couple of files this or next week, and we will see. Do you have any specific tests that you remember to have no-pytest-friendly parameterization or decorators?

**Comment by yarikoptic** [comment]
well, the files without decorators probably the easiest ones and could just work out of the box:
```
(git)lena:~datalad/datalad-master[master]git
$> grep -L '^@' datalad/**/test_*py
datalad/cmdline/tests/test_formatters.py
datalad/distribution/tests/test_dataset_binding.py
datalad/downloaders/tests/test_base.py
datalad/interface/tests/test_base.py
datalad/interface/tests/test_docs.py
datalad/support/tests/test_ansi_colors.py
datalad/support/tests/test_cache.py
datalad/support/tests/test_github_.py
datalad/support/tests/test_stats.py
datalad/support/tests/test_status.py
datalad/support/tests/test_vcr_.py
datalad/support/tests/test_versions.py
datalad/tests/test_api.py
datalad/tests/test_constraints.py
datalad/tests/test_dochelpers.py
datalad/tests/test_interface.py
datalad/tests/test_misc.py
datalad/tests/test_strings.py
datalad/tests/test_version.py
datalad/ui/tests/test_base.py
datalad/ui/tests/test_dialog.py
```

**Comment by djarecka** [comment]
my point for starting from the hard one was to see if your decorators will work nicely with pytest so you can decide whether to chose `node2` or `pytest`

**Comment by yarikoptic** [comment]
ah, sorry - I have misread the desire ;)  

https://github.com/datalad/datalad/blob/master/datalad/tests/test_tests_utils.py  would be the one to test many of those decorators, so would be quite heavy on them.  And then https://github.com/datalad/datalad/blob/master/datalad/support/tests/test_annexrepo.py as one of the representative heavy users of them

But let me try to centralize those imports as I have mentioned, it could be helpful regardless of the pytestification effort

**Comment by djarecka** [comment]
@yarikoptic - ok, no worries.  Just ping me whenever

**Comment by kyleam** [comment]
@djarecka:
> my point for starting from the hard one was to see if your decorators will work nicely with pytest

They won't work nicely, though in many cases the workaround is trivial but ugly.  Take `test_save_obscure_name` as an example (picked somewhat randomly among short examples that use `with_tree/with_tempfile`.  Trying to run that with `pytest` will fail with

```
$ python -m pytest -vs datalad/core/local/tests/test_save.py::test_save_obscure_name
[...]
datalad/core/local/tests/test_save.py::test_save_obscure_name ERROR

==================================== ERRORS ====================================
___________________ ERROR at setup of test_save_obscure_name ___________________
file /home/kyle/src/python/datalad/datalad/core/local/tests/test_save.py, line 746
  @with_tree(tree={OBSCURE_FILENAME: "abc"})
  def test_save_obscure_name(path):
E       fixture 'path' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/home/kyle/src/python/datalad/datalad/core/local/tests/test_save.py:746
[...]
```

We can work around this by adding a default:

```diff
diff --git a/datalad/core/local/tests/test_save.py b/datalad/core/local/tests/test_save.py
index 4c9f9ea93b..8e5efeddfb 100644
--- a/datalad/core/local/tests/test_save.py
+++ b/datalad/core/local/tests/test_save.py
@@ -744,7 +744,7 @@ def test_on_failure_continue(path):
 
 
 @with_tree(tree={OBSCURE_FILENAME: "abc"})
-def test_save_obscure_name(path):
+def test_save_obscure_name(path=None):
     ds = Dataset(path).create(force=True)
     fname = OBSCURE_FILENAME
     # Just check that we don't fail with a unicode error.
```

```
datalad/core/local/tests/test_save.py::test_save_obscure_name PASSED                              [100%]
```

But that won't play well if we try to use other pytest features (`.fixture`, `.mark.parametrize`).  As a stupid example:

```diff
diff --git a/datalad/core/local/tests/test_save.py b/datalad/core/local/tests/test_save.py
index 4c9f9ea93b..a185d444f3 100644
--- a/datalad/core/local/tests/test_save.py
+++ b/datalad/core/local/tests/test_save.py
@@ -743,8 +743,12 @@ def test_on_failure_continue(path):
     assert_repo_status(ds.path)
 
 
+import pytest
+
 @with_tree(tree={OBSCURE_FILENAME: "abc"})
-def test_save_obscure_name(path):
+@pytest.mark.parametrize("foo", [1, 2])
+def test_save_obscure_name(foo, path=None):
+    assert foo < 3
     ds = Dataset(path).create(force=True)
     fname = OBSCURE_FILENAME
     # Just check that we don't fail with a unicode error.
```

```
[...]
datalad/core/local/tests/test_save.py::test_save_obscure_name[1] FAILED  [ 50%]
datalad/core/local/tests/test_save.py::test_save_obscure_name[2] FAILED  [100%]

=================================== FAILURES ===================================
__________________________ test_save_obscure_name[1] ___________________________

arg = (), kw = {'foo': 1}
tkwargs_ = {'prefix': 'datalad_temp_tree_test_save_obscure_name'}
d = '/tmp/datalad_temp_tree_test_save_obscure_namem9oy1exv'

    @wraps(t)
    def newfunc(*arg, **kw):
        tkwargs_ = get_tempfile_kwargs(tkwargs, prefix="tree", wrapped=t)
        d = tempfile.mkdtemp(**tkwargs_)
        create_tree(d, tree, archives_leading_dir=archives_leading_dir)
        try:
>           return t(*(arg + (d,)), **kw)
E           TypeError: test_save_obscure_name() got multiple values for argument 'foo'

datalad/tests/utils.py:559: TypeError
__________________________ test_save_obscure_name[2] ___________________________
[...]
```
In my view (and assuming a switch to pytest), the best way to deal with the above is to just make `with_tree` and friends proper pytest fixtures.

**Comment by djarecka** [comment]
@kyleam - so maybe it's also worth checking `nose2`... but have no experience, so won't be guessing whether is much easier or not.

**Comment by yarikoptic** [comment]
FWIW, #4136 is centralizing the imports of test helpers.

**Comment by djarecka** [comment]
@kyleam @yarikoptic - started reading your tests - you really like decorators ;-)
As @kyleam mentioned many of your decorators do not work with pytest and probably moving to pytest fixtures is the best way (at least I don't know any other that makes sense). The good news is, that IMO some of your decorators could be replaced by pytest existing fixtures or at least can be based on them. 

I've started changing the code to see how it can look like, I only converted a few test, but will try to add more this week. For now I only worked with `with_tempfile`  - I believe in most cases it can be `pytest.tmpdir.join("file")`, but perhaps I'm missing something important. 
For the tests that need content I've created `with_tempfile_pyt` in a temporary file [datalad/tests/utils_pytest](https://github.com/datalad/datalad/compare/master...djarecka:pytest?expand=1#diff-428e442292eff5a6772afbe6e10771cbR102)

You can comment here: https://github.com/datalad/datalad/pull/4232

**Comment by mih** [comment]
#6211 makes it obvious that this time has come now.

I looked into `nose2` and it does not support package-level fixtures -- but our entire test setup critically depends on them. There is a `layers` plugin (https://docs.nose2.io/en/latest/plugins/layers.html) which provides something that is way more flexible, and can be used in scenarios that nobody can envision yet -- and as always the price for this seems to be rather high (each test needs to declare the layer it is in. This would require a large-scale reorganization of the tests. I am not up for that TBH.

This leaves pytest #6225

**Comment by mih** [comment]
I think the decision is made. Follow #6225 for updates on this topic.
