### ISSUE TITLE
Observations on inconsistent handling of relative paths across python commands

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#4098]
When I updated command examples to consistently include ``dataset=`` for the Python API following https://github.com/datalad/datalad/pull/4091#discussion_r371304348, I noticed inconsistent interpretations of ``path=<some/path/>`` between Python functions. Some interpret it as relative to ``dataset=<some/path>``, and some not.

I'm aware it is a known issue, but I wanted to write down  which commands treat paths in which way when the dataset specification is a path (and not a dataset instance).

I had an ipython instance in ``/tmp`` and used the Python API to work with a dataset `/tmp/super`, created like this in ``/tmp``:
```
from datalad.api import create, Dataset
# create dataset (with path)
create(path="super")
# also have a Dataset instance for it
ds = Dataset('super') 
```
I checked the commands `create`,`save`,`unlock`,`download_url`, `get`, `clone`, `run`, `rerun`, `uninstall`, `diff`,`run-procedure`, `remove`, `drop`, `publish`, `siblings` (the latter four are the odd ones out)

#### Behavior when dataset is a path (not dataset instance)

Paths are **not** interpreted as relative to the dataset root in the following commands :
- ``create`` (i.e., subdataset creation fails here: ``create(dataset='super', path='sub')``)
- ``save`` (i.e., saving a file `file1` in ``super`` fails here: ``save(dataset='super', path='file1'``)
- ``unlock`` (i.e, unlocking a file `file1` in `super` fails here: ``unlock(dataset='super', path='file1')``
- ``download_url`` (i.e, downloading a file and saving it as `downloadfile` in `super` fails here: ``download_url(dataset='super', urls='https://raw.githubusercontent.com/datalad/datalad.org/7e8e39b1f08d0a54ab521586f27ee918b4441d69/content/asciicast/seamless_nested_repos.sh', message="did yx", path='downloadfile')``
- ``get`` (i.e., reobtaining a downloaded file ``downloadfile`` from `super` fails here: ``get(dataset='super', path='downloadfile')``
- ``clone``, (i.e., installing a subdataset `podcasts` into super fails here: ``clone(dataset='super', source='https://github.com/datalad-datasets/longnow-podcasts.git', path='podcasts')``
- ``run``, (i.e, running `mv file1 file_1` fails here: `run(dataset='super', cmd='mv file1 file_1', outputs='file1')`
- ``rerun`` simply says ``No lines in history match specification`` after `rerun(dataset='super')` (see details at the end of this issue)
- `uninstall` (i.e., uninstalling ``podcasts`` fails here: ``uninstall(dataset='super', path='podcasts')``)
- ``diff`` (i.e., getting the diff on ``anotherfile`` in ``super`` fails here: `diff(dataset='super', path='anotherfile')`

- a bit unrelated, but ``run-procedure`` works regardless of how I specify the dataset: ``run_procedure(dataset='super', spec='cfg_text2git')``

Paths are interpreted as **relative** to the dataset root (specified as a string with ``dataset=``) in following commands:
- ``remove`` (i.e., removing a subdataset `podcasts` from `super` works here: ``remove(dataset='super', path='podcasts')``
- ``drop`` (i.e., dropping a file ``downloadfile`` from `super` works here: ``drop(dataset='super', path='downloadfile')``)
- ``siblings``. I created ``/tmp/super_sibling`` (my dataset is ``/tmp/super``, ipython runs in ``/tmp``). Adding a sibling with a relative path works here: 
```
siblings(action='add', dataset='super', name='sibling-local', url='../super_sibling')                                                                     
.: sibling-local(+) [../super_sibling (git)]
Out[95]: 
[{'action': 'add-sibling',
  'path': '/tmp/super',
  'type': 'sibling',
  'name': 'sibling-local',
  'url': '../super_sibling',
  'fetch': '+refs/heads/*:refs/remotes/sibling-local/*',
  'annex-uuid': '172fb4d5-9b59-4f9e-ac05-66d65d161ce2',
  'annex-ignore': 'false',
  'annex-description': 'sibling-local',
  'status': 'ok',
  'refds': '/tmp/super'}]

```
If I add a sibling with a path relative to the location my ipython instance runs from, it gets it wrong (sibling is wrongly under `super/super_sibling2` after this):
```
siblings(action='add', dataset='super', name='sibling-local2', url='super_sibling2')                                                                      
[INFO   ] Failed to enable annex remote sibling-local2, could be a pure git or not accessible 
[WARNING] Failed to determine if sibling-local2 carries annex. 
.: sibling-local2(-) [super_sibling2 (git)]
Out[97]: 
[{'action': 'add-sibling',
  'path': '/tmp/super',
  'type': 'sibling',
  'name': 'sibling-local2',
  'url': 'super_sibling2',
  'fetch': '+refs/heads/*:refs/remotes/sibling-local2/*',
  'annex-ignore': True,
  'status': 'ok',
  'refds': '/tmp/super'}]

```
- ``publish`` (i.e., this works: ``publish(dataset='super', path='file_1', to='sibling-local')``

________________________________________________________

<details><summary>Just for completeness: if dataset= gets a dataset instance or if the command is used as a dataset method, paths are interpreted as relative</summary>
_______________________________________________________

#### Behavior when dataset is dataset instance

Paths are interpreted as **relative** to the dataset root (specified as a dataset instance with ``dataset=``) in all commands I have tried:
- ``create(dataset=ds, path='sub')``
- ``save(dataset=ds, path='file1')``
- ``unlock(dataset=ds, path='file1')``
- ``download_url(dataset=ds, urls='https://raw.githubusercontent.com/datalad/datalad.org/7e8e39b1f08d0a54ab521586f27ee918b4441d69/content/asciicast/seamless_nested_repos.sh', message="did yx", path='downloadfile')``
- ``clone(dataset=ds, source='https://github.com/datalad-datasets/longnow-podcasts.git', path='podcasts')``
-  ``drop(dataset=ds, path='downloadfile')``
- ``remove(dataset=ds, path='sub')`` 
- ``get(dataset=ds, path='downloadfile')``
-`` run(dataset=ds, cmd='mv file1 file_1', outputs='file1') ``
- ``rerun`` simply says ``No lines in history match specification`` after `rerun(dataset=ds)` (see details at the end of this issue)
- ``uninstall(dataset=ds, path='podcasts')``
- ``siblings(action='add', dataset=ds, name='sibling-local', url='../super_sibling')``
- ``publish(dataset=ds', path='file_1', to='sibling-local')``
- `diff(dataset=ds, path='anotherfile') `

_______________________________________________________
#### Behavior when using a dataset method instead of function

Paths are interpreted as **relative** to the dataset root when used as a dataset method in all commands I have tried:
- ``ds.create(path='sub')``
- ``ds.save(path='file1')``
- ``ds.unlock(path='file1')``
- ``ds.download_url(urls='https://raw.githubusercontent.com/datalad/datalad.org/7e8e39b1f08d0a54ab521586f27ee918b4441d69/content/asciicast/seamless_nested_repos.sh', message="did yx", path='downloadfile')``
- ``drop(dataset=ds, path='downloadfile')``
- ``ds.clone(source='https://github.com/datalad-datasets/longnow-podcasts.git', path='podcasts')``
- `ds.remove(path='sub')`
- ``ds.get(path='downloadfile')``
- ``ds.run(cmd='mv file1 file_1', outputs='file1')``
- ``ds.siblings(action='add', name='sibling-local', url='../super_sibling')``
- ``ds.publish(path='file_1', to='sibling-local')``
- ``ds.diff(path='anotherfile') ``

a bit unrelated, but ``run-procedure`` works regardless of how I specify the dataset: ``run_procedure(dataset=ds, spec='cfg_text2git')`` / ``ds.run_procedure(spec='cfg_text2git')``
 
</details>

________________________________________________________

I think I found an unrelated bug when I wanted to rerun a previous ``run`` command. It does not work when I pass the dataset as a string or -- interestingly -- also a dataset instance, but works if I use the command as a dataset method. When it "fails", the it just returns  ``No lines in history match specification`` instead of (what I think should be) complaining about a non-existent dataset.

<details>

This "fails" with what I find a misleading message:
```
In [69]: rerun(dataset='super')                                                       
No lines in history match specification

In [70]: rerun(dataset=ds)                                                            
No lines in history match specification
```

works as dataset method:

```
ds.rerun()                                                                   
[INFO   ] == Command start (output follows) ===== 
[...]
```

</details>
Let me know whether this is a feature or if I should open a new issue about it.

**Comment by mih** [comment]
This is an absolutely crucial assessment. Thanks a lot for taking the time to do it!

**Comment by kyleam** [comment]
> Paths are interpreted as **relative** to the dataset root (specified as a string with `dataset=`) in following commands: [remove, drop, publish, siblings]

Nice to have a concrete list.  There are no real surprises here, and I'm glad none of the commands that have been updated for the new path handling (or rewritten entirely) show up here.

> I think I found an unrelated bug when I wanted to rerun a previous `run` command. It does not work when I pass the dataset as a string or -- interestingly -- also a dataset instance, but works if I use the command as a dataset method. When it "fails", the it just returns `No lines in history match specification`

I think you're invoking IPython's magic command `rerun`:

```
In [1]: pwd
Out[1]: '/tmp'

In [2]: rerun(dataset="blah")
No lines in history match specification

In [3]: rerun -gp
=== Executing: ===
pwd
=== Output: ===
Out[3]: '/tmp'
```

> instead of (what I think should be) complaining about a non-existent dataset.

Quickly checking, I think things are working as you'd expect:

<details>
<summary>rerun</summary>

```sh
#!/bin/sh

cd "$(mktemp -d --tmpdir dl-XXXXXXX)"

datalad create a
(
    cd a
    echo one >one
    datalad save
    datalad run -i one -o out "cat {inputs} >>out"
)
python -c "import datalad.api as dl; dl.rerun(since='')"
python -c "import datalad.api as dl; dl.rerun(dataset='a', since='')"
cat a/out
```

```
[INFO] Creating a new annex repo at /tmp/dl-onXk5po/a 
create(ok): /tmp/dl-onXk5po/a (dataset)
add(ok): one (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
[INFO] Making sure inputs are available (this may take some time) 
[INFO] == Command start (output follows) ===== 
[INFO] == Command exit (modification check follows) ===== 
add(ok): out (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  get (notneeded: 1)
  save (ok: 1)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kyle/src/python/datalad/datalad/interface/utils.py", line 492, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/kyle/src/python/datalad/datalad/interface/utils.py", line 480, in return_func
    results = list(results)
  File "/home/kyle/src/python/datalad/datalad/interface/utils.py", line 411, in generator_func
    allkwargs):
  File "/home/kyle/src/python/datalad/datalad/interface/utils.py", line 527, in _process_results
    for res in results:
  File "/home/kyle/src/python/datalad/datalad/interface/rerun.py", line 194, in __call__
    purpose='rerunning a command')
  File "/home/kyle/src/python/datalad/datalad/distribution/dataset.py", line 566, in require_dataset
    raise NoDatasetArgumentFound("No dataset found")
datalad.support.exceptions.NoDatasetArgumentFound: No dataset found
[INFO] Making sure inputs are available (this may take some time) 
[INFO] == Command start (output follows) ===== 
[INFO] == Command exit (modification check follows) ===== 
one
one
```

</details>

**Comment by adswa** [comment]
ha! thanks @kyleam and sorry for the noise! :)
