### ISSUE TITLE
wishlist: enhance AnnexRepo.get_urls() to "mint" URLs for files under git, git annex special remotes etc

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4109]
ATM `get_urls` returns list of urls as known to git-annex.
  
"Information" about locations of files under git (e.g. as also available from other clones), or under special remotes, even if they are known to be exposed publicly or via ssh would is not used.  But potentially we can "mint" (create/compile/construct) ssh:// s3:// http*:// etc URLs based on the information contained in git/git-annex and local .git/config.  That would allow establishing a list of urls for possible downloads by external tools, such as perspective jsdownloader (see https://github.com/con/jsdownloader/issues/1).

I am not sure if anything like that could/should be implemented in git-annex (attn @joeyh, I could be wrong), that is why filing this wishlist issue here for further discussion.

PS I took `get_urls` as a possible location for (optional) feature, but it might be implemented as another method, and should be interfaced at the level of a Dataset, so it would be sufficient to query paths to subdatasets without needing to "manually" resolve to a particular one first.

**Comment by joeyh** [comment]
git-annex has a knownUrls that returns a [(Key, URLString)] with
every url that is recorded in the git-annex branch (".log.web" files).
It would be easy to add a plumbing command that dumps out them all.

It's used by git-annex importfeed and is a little bit slow since it has
to traverse every file on the git-annex branch. I've thought before it
would be good to cache them in sqlite and have a fast incremental
update, but it's not been a priority.

-- 
see shy jo

**Comment by yarikoptic** [comment]
> git-annex has a knownUrls that returns a [(Key, URLString)] with every url that is recorded in the git-annex branch (".log.web" files). It would be easy to add a plumbing command that dumps out them all.

Just to make sure: `knownUrls` lists all urls regardless either any annex special remote is claiming them.  So knownUrls might result in more urls then what we now get via `git annex whereis` which first resolves the urls to be handled by specific special remotes. Correct @joeyh?

Original issue is is the desire to have **not only** urls from `.log.web` files, but to construct urls for regular and special remotes.  E.g. if I have an `origin` remote with `host:/path`, then for a file which is under annex KEY, it would then construct url `ssh://host/path/.git/annex/objects/..../KEY`, and if that remote is a bare one, it would be without `.git/` and if that remote url is an `http://` URL (might have `ssh` url for push), it would be immediately full url to that file via public http, not requiring git-annex.  If file is under s3 special remote, it could construct "non-standard" s3://bucket/xx/yy/KEY?versionId=ZZZ from the special remote information and s3 versionId info git-annex knows and so on.

NB files under "git" are actually tricky, since we could only provide urls for the current version, so first we would need to check if the remote's current HEAD tree contains desired version of the file. But nothing non-doable.

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
