### ISSUE TITLE
Needlessly required clone target specification?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4110]
```
% datalad clone -d analysis code
install(error): ../code (dataset) [clone target path '/tmp/modules/code' not in specified target dataset '<Dataset path=/tmp/modules/analysis>']
```

where both `analysis` and `code` are datasets in CWD. Works fine with an explicit target.

```
% datalad clone -d analysis code analysis/code
install(ok): code (dataset)                                                                  
add(ok): code (file)
add(ok): .gitmodules (file)
save(ok): . (dataset)
```

I think, without a given target, the default relpath target should be treated as relative to the target dataset (if any), and not relative to CWD.

**Comment by yarikoptic** [comment]
> I think, without a given target, the default relpath target should be treated as relative to the target dataset (if any), and not relative to CWD.

It feels like this here, but that would break consistency with how now either commands handle relative paths, so I would probably take it as a not so good idea as to cater this specific use case. There is always explicit way or -C , right? ;-)

**Comment by mih** [comment]
@yarikoptic's viewpoint makes sense to me after re-reading this with sufficient distance ;-)
