### ISSUE TITLE
FOI: JOSS paper repo is now at https://github.com/datalad/datalad-paper-joss/

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4114]
As we have discussed in the past, let's push out a basic JOSS paper on DataLad.  Its purpose would be merely to establish a DataLad paper which would provide a very high level description and pointers to the other components in the ecosystem (extensions etc), many of which could even obtain their own publications.  Also there could be "larger" and themed "DataLad publications".  I expect them to address some specific question(s), whenever JOSS paper is a mere overview of the DataLad as a whole.

Please comment, commit/push and submit issues/PRs in that other repository. 

Whenever we are ready we would submit it to JOSS.  May be moving its materials back into this repository (if small and/or reused elsewhere, e.g. in doc/) and retiring that one

**Comment by mih** [comment]
Tagged and closed FOI issue
