### ISSUE TITLE
Just a suggestion: datalad remove (make default --if-dirty fail)

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4115]
#### What is the problem?
http://docs.datalad.org/en/latest/generated/man/datalad-remove.html
Looks like `datald remove` will by default save a dataset before starting the process. I would suggest the default value of `--if-dirty` is switched to fail, this way the user by default is faced with the problem rather than the software making the decision. It would then make sense that a user faced with the problem selects either `--if-dirty save` or `--if-dirty ignore` to proceed. I know changes in default values are not easy decisions, but the defaults usually should (1) make selections for naive users which all of us are at the beginning, and (2) follow the most common use (which does not seem the right thing to do for most users; trigger saving all pending changes when removing a single file). Just a thought/suggestion. 

#### What steps will reproduce the problem?
NA

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.12.2 (github today)

#### Is there anything else that would be useful to know in this context?
Nope.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Sure, love is in the air :)

**Comment by dorianps** [comment]
Just echoing the same request for `datalad drop`. I wanted to get rid of some file content and I found myself with temporary files I was working on commited to the dataset. Yes, it is my fault for not using `--if-dirty ignore`, but in principle, saving a dataset when running other commands is a dangerous assumption. I.e., in my case, I had two files I wanted to save after dropping the file content; this was special editing for a subject to make fmriprep work. Instead of dropping all the default content and saving the two edited files, datalad commited the two edited files in history, so now retaining only the content of those two files and dropping everything else becomes more complicated.

I think saving a dirty dataset without the user asking for it is not intuitive or safe.

**Comment by mih** [comment]
With the upcoming rewrite of `remove` and `drop` in #6111 this will become reality. It will behave "save-by-default" -- although it will actually abandon the `if_dirty` parameter. If you have any feedback on #6111 and the new behavior, please chime in. Thx!
