### ISSUE TITLE
AnnexRepo.commit() investigate performance of test for untracked files

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4126]
Here is the code:

https://github.com/datalad/datalad/blob/7afff524f5b5ad36f1c2f204a7965407f7ac1055/datalad/support/annexrepo.py#L2569-L2572

This uses a dry-run commit to seemingly test for untracked files given to commit. This can be a fairly expensive test to make.

It is unclear to me why it is done, because a potential exception is not handled, hence will blow up in the same way that it would have with a real commit.

If it needs to be done, we should investigate whether a call to `GitRepo.get_content_info()` is able to perform this test faster.

**Comment by yarikoptic** [comment]
That call was added in e950799d87a60e10e04307d6cce442fe2c448222 which is `0.10.3~23^2~14`, so long before new `save` was added with a new behavior (save everything, including untracked files) and we operated on AnnotatedPaths and less of dataset level commands.  ATM with new `save` we would just add/commit untracked files AFAIK. So, if operating on dataset level commands to initiate commit, such check is probably not needed.  But if we use `AnnexRepo.commit` directly - we would just silently not commit that file

<details>
<summary>First invocation is with --dry-run check, 2nd one with it removed - silent "do nothing"</summary> 

```shell
/tmp > datalad create test1; cd test1
[INFO   ] Creating a new annex repo at /tmp/test1 
create(ok): /tmp/test1 (dataset)                                                                                                                                                                                                   

/tmp/test1 > touch 1

/tmp/test1 > python -c 'from datalad.support.annexrepo import AnnexRepo; r=AnnexRepo("."); r.commit(files=["1"])'
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 1694, in commit
    index_file=index_file)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 320, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 2102, in _git_custom_command
    expect_fail=expect_fail)
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 134, in run_gitcommand_on_file_list_chunks
    out_, err_ = func(cmd + ['--'] + file_chunk, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 975, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 808, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command '['git', 'commit', '-m', 'dryrun', '--dry-run', '--no-status', '--', '1']' failed with exitcode 1
Failed to run ['git', 'commit', '-m', 'dryrun', '--dry-run', '--no-status', '--', '1'] under '/tmp/test1'. Exit code=1. out= err=error: pathspec '1' did not match any file(s) known to git

stdout=
stderr=error: pathspec '1' did not match any file(s) known to git


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/annexrepo.py", line 2572, in commit
    files=files)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 1716, in commit
    [l for l in e.stderr.splitlines()
datalad.support.exceptions.FileNotInRepositoryError: FileNotInRepositoryError: command '['git', 'commit', '-m', 'dryrun', '--dry-run', '--no-status', '--', '1']' failed with exitcode 1
File(s) unknown to git
stdout=
stderr=
[Errno 1] ['git', 'commit', '-m', 'dryrun', '--dry-run', '--no-status', '--', '1']: File(s) unknown to git: ''

exit:1 /tmp/test1 > python -c 'from datalad.support.annexrepo import AnnexRepo; r=AnnexRepo("."); r.commit(files=["1"])'

/tmp/test1 > echo $?
0

/tmp/test1 > git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	1

nothing added to commit but untracked files present (use "git add" to track)

/tmp/test1 > python -c 'from datalad.support.annexrepo import AnnexRepo; r=AnnexRepo("."); print(r.commit(files=["1"]))'
None
```
</details>

<details>
<summary>
but that is only if we operate on `AnnexRepo.commit` and not `GitRepo.commit` which would fail with Command Error
</summary> 

```shell
/tmp/test1 > python -c 'from datalad.support.annexrepo import GitRepo; r=GitRepo("."); print(r.commit(files=["1"]))'       
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 1694, in commit
    index_file=index_file)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 320, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 2102, in _git_custom_command
    expect_fail=expect_fail)
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 134, in run_gitcommand_on_file_list_chunks
    out_, err_ = func(cmd + ['--'] + file_chunk, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 975, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 808, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command '['git', 'commit', '-m', '', '--allow-empty-message', '--', '1']' failed with exitcode 1
Failed to run ['git', 'commit', '-m', '', '--allow-empty-message', '--', '1'] under '/tmp/test1'. Exit code=1. out= err=error: pathspec '1' did not match any file(s) known to git

stdout=
stderr=error: pathspec '1' did not match any file(s) known to git


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/gitrepo.py", line 1716, in commit
    [l for l in e.stderr.splitlines()
datalad.support.exceptions.FileNotInRepositoryError: FileNotInRepositoryError: command '['git', 'commit', '-m', '', '--allow-empty-message', '--', '1']' failed with exitcode 1
File(s) unknown to git
stdout=
stderr=
[Errno 1] ['git', 'commit', '-m', '', '--allow-empty-message', '--', '1']: File(s) unknown to git: ''
```
</details>

So the question is "why we had it in AnnexRepo". Original commit  e950799d87a60e10e04307d6cce442fe2c448222 change suggests that it was only for special treatment of direct mode, since otherwise the exception was just ignored.

My summary:
1. I think it should be ok to just remove that `--dry-run` call
2. We should look (later?) either we still need any special treatment at `AnnexRepo.commit` level and probably unify its behavior with `GitRepo.commit` on such cases (file is not known to Git).

**Comment by yarikoptic** [comment]
FWIW, looking into 1+2 atm

**Comment by kyleam** [comment]
>   We should look (later?) either we still need any special treatment at `AnnexRepo.commit` level

The motivation for the temporary index workaround is explained in 1a609d4be (BF: annexrepo: Avoid typechange when using temporary index, 2019-04-30) and 1a609d4be (BF: annexrepo: Avoid typechange when using temporary index, 2019-04-30).

The second commit adds a test case that shows where the new `save()` behavior still fails.  Given that we've been okay with having that limitation for `save()`, I think it'd be fine to have it for `commit()` as well.

**Comment by kyleam** [comment]
> It is unclear to me why it is done, because a potential exception is not handled, hence will blow up in the same way that it would have with a real commit.

This is answered both in the comment right above, and by the `git-blame`-reported commit, which Yarik pointed to.

**Comment by yarikoptic** [comment]
> and [205b2ca](https://github.com/datalad/datalad/commit/205b2cac406911ab267e146c444c241c1b34a14e) (TST: rev-save: Demonstrate partial commit failure, 2019-04-30).
> 
> The second commit adds a test case that shows where the new `save()` behavior still fails...

FWIW, changes in #4127 seems to retain that tested behavior:
```shell
(git)lena:~datalad/datalad-master[opt-commit-no--dry-run]git
$> DATALAD_TESTS_SSH=1 python -m nose -s -v datalad/core/local/tests/test_save.py
...
datalad.core.local.tests.test_save.test_save_partial_commit_shrinking_annex ... ok
...
```

as for the review of the situation, filed separate #4128

**Comment by kyleam** [comment]
> FWIW, changes in #4127 seems to retain that tested behavior:

That PR changes `AnnexRepo.commit`, which the `save` command doesn't go through.

**Comment by yarikoptic** [comment]
> > FWIW, changes in #4127 seems to retain that tested behavior:
> 
> That PR changes `AnnexRepo.commit`, which the `save` command doesn't go through.

Oh. I wonder then how @mih identified this issue then ;-)

**Comment by mih** [comment]
Crystal ball!

**Comment by mih** [comment]
There is no `AnnexRepo.commit()` anymore.
