### ISSUE TITLE
Dissolve AnnexRepo.commit 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4128]
Initial attention to the issue was brought up by https://github.com/datalad/datalad/issues/4126 . Looking at all the logic and comments in the code: https://github.com/datalad/datalad/blob/master/datalad/support/annexrepo.py#L2578

and now that all bits for direct mode handling are gone, https://github.com/datalad/datalad/pull/4127 removes call to `--dry-run`, it seems that custom logic there is to provide "consistent" (according to our idea of consistency) behavior for git-annex while committing files which might jump between git/git-annex (depending on .gitattributes etc).  There were tons of changes in git-annex since then (which was in 2018), and our minimal "supported" git-annex version atm is 7.20190503 . So, I think it would be valuable to check if may be current git-annex already behaves "consistent" with our expectations in such cases, and thus completely deprecate `AnnexRepo.commit`

**Comment by kyleam** [comment]
> it seems that custom logic there is to provide "consistent" (according to our idea of consistency) behavior for git-annex while committing files which might jump between git/git-annex (depending on .gitattributes etc). There were tons of changes in git-annex since then (which was in 2018), and our minimal "supported" git-annex version atm is 7.20190503 . So, I think it would be valuable to check if may be current git-annex already behaves "consistent" with our expectations in such cases, and thus completely deprecate `AnnexRepo.commit`

`test_save_partial_commit_shrinking_annex` has remained passing on Travis (7.20190819+git2-g908476a9b-1~ndall+1), so it appears that the git-annex partial index error is still being triggered.  This issue goes away with v6+ repos, so whenever we depend on a git-annex version that auto-upgrades v5 repos (at least 7.20190912), there will be no problem for `.commit()` to work around.

**Comment by kyleam** [comment]
Can this be closed as a duplicated of gh-3714?
