### ISSUE TITLE
no progress bar during save with large files being added to annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4129]
https://github.com/datalad/datalad/issues/3341 was closed under the premise (no demonstration to support) of `save` of upcoming 0.12 providing the best progress bars.  I just did `datalad save` with datalad 0.12.1 and saw no progress bars.  So I guess the underlying issue was not actually fixed

**Comment by mih** [comment]
Did you intentionally test this version, instead of master or the latest release, or is this a typo?

**Comment by yarikoptic** [comment]
no... it was the version installed (and I forgot that we had .2), tested current master, indeed there is progress bars now with 0.12.2.dev116, sorry for the noise
