### ISSUE TITLE
reckless=ephemeral test fails on windows

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#4131]
For now disabled test `test_clone.py:test_ephemeral` in PR #4099 on windows. Failure depends on PR #4057 (proper path resolve) since "Github Windows" comes up with short paths.

**Comment by mih** [comment]
This test only makes sense in an environment that supports chained symlinks from the worktree of one repository into the annex of another. Even with symlinks the datasets on windows will still be in adjusted mode and have no such links.

I am closing this issue, because it cannot be rectified.
