### ISSUE TITLE
credentials are requested multiple times for a tricky ///crcns/aa-1

### ISSUE THREAD

**Issue by gi114** [datalad/datalad#4133]
```shell
(venv) giuly@giuly-ThinkPad-T480s:~/test/aa-1$ datalad get *
Total:   0%|                                                                                                                 | 0.00/10.3M [00:00<?, ?B/s]You need to authenticate with 'crcns' credentials. https://crcns.org/request-account/ provides information on how to gain access
[INFO   ] To obtain some keys we need to fetch an archive of size 7.0 MB                                                                                 
You need to authenticate with 'crcns' credentials. https://crcns.org/request-account/ provides information on how to gain access
user: You need to authenticate with 'crcns' credentials. https://crcns.org/request-account/ provides information on how to gain access
user: You need to authenticate with 'crcns' credentials. https://crcns.org/request-account/ provides information on how to gain access
user: You need to authenticate with 'crcns' credentials. https://crcns.org/request-account/ provides information on how to gain access
user: You need to authenticate with 'crcns' credentials. https://crcns.org/request-account/ provides information on how to gain access
user: You need to authenticate with 'crcns' credentials. https://crcns.org/request-account/ provides information on how to gain access
user: 
```
and to kill this thing -- it is really hard

<details><summary>DataLad 0.12.1 WTF (configuration, datalad, dataset, dependencies, environment, extensions, git-annex, location, metadata_extractors, python, system)</summary>

# WTF
## datalad 
  - full_version: 0.12.1
  - version: 0.12.1
## dataset 
  - id: e7f3d3a8-d4ce-11e9-9c3d-5076afd7427c
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /home/giuly/test/FRDR-multimodal
  - repo: AnnexRepo
## dependencies 
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:annex: 7.20190819+git2-g908476a9b-1~ndall+1
  - cmd:bundled-git: 2.20.1
  - cmd:git: 2.20.1
  - cmd:system-git: 2.17.1
  - cmd:system-ssh: 7.6p1
  - git: 3.0.5
  - gitdb: 2.0.6
  - humanize: 0.5.1
  - iso8601: 0.1.12
  - keyring: 21.1.0
  - keyrings.alt: 3.4.0
  - msgpack: 0.6.2
  - requests: 2.22.0
  - tqdm: 4.41.1
  - wrapt: 1.11.2
## environment 
  - GIT_PYTHON_GIT_EXECUTABLE: /usr/lib/git-annex.linux/git
  - LANG: en_CA.UTF-8
  - PATH: /home/giuly/test/venv/bin:/home/giuly/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - local repository version: 5
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions: 
    - 5
    - 7
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  - version: 7.20190819+git2-g908476a9b-1~ndall+1
## location 
  - path: /home/giuly/test/FRDR-multimodal
  - type: dataset
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: No module named 'PIL' [image.py:<module>:16]
    - module: datalad.metadata.extractors.image
  - xmp: 
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.6.8
## system 
  - distribution: Ubuntu/18.04/bionic
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 288
  - name: Linux
  - release: 4.15.0-74-generic
  - type: posix
  - version: #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019
</details>

**Comment by kyleam** [comment]
@gi114, sorry for the lack of a response.  I _think_ this issue is resolved by gh-4308.  Please reopen if I'm mistaken.
