### ISSUE TITLE
export-to-figshare would fail to cleanup for dataset with subdatasets

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4137]
Tried on some test dataset laying around:

```shell
(git-annex)lena:/tmp/testds[master]git
$> git status
On branch master
nothing to commit, working tree clean

$> datalad export-to-figshare
[INFO   ] Exporting current tree as an archive under /tmp/testds since figshare does not support directories 
[INFO   ] Uploading /tmp/testds/datalad_None.zip to figshare 
Article
Would you like to create a new article to upload to?  If not - we will list existing articles (choices: yes, no): yes

[INFO   ] Created a new (private) article 11845443 at https://figshare.com/account/articles/11845443. Please visit it, enter additional meta-data and make public 
[INFO   ] 'Registering' /tmp/testds/datalad_None.zip within annex                                                                                                                                                                  
[INFO   ] Adding URL https://ndownloader.figshare.com/files/21708819 for it 
[INFO   ] Registering links back for the content of the archive 
[INFO   ] Adding content of the archive /tmp/testds/datalad_None.zip into annex <AnnexRepo path=/tmp/testds (<class 'datalad.support.annexrepo.AnnexRepo'>)> 
[INFO   ] Initiating special remote datalad-archives 
[INFO   ] Finished adding /tmp/testds/datalad_None.zip: Files processed: 2, removed: 2, +annex: 2 
[WARNING] Removing temporary directory under which extracted files were annexed and should have been removed: /tmp/testds/.dataladw4a0msxt 
CommandError: command '['git', 'rm', '--force', '-r', '--', '.dataladw4a0msxt']' failed with exitcode 128
Failed to run ['git', 'rm', '--force', '-r', '--', '.dataladw4a0msxt'] under '/tmp/testds'. Exit code=128. out= err=fatal: pathspec '.dataladw4a0msxt' did not match any files

fatal: pathspec '.dataladw4a0msxt' did not match any files

$> datalad subdatasets
subdataset(ok): d0/d1/r0 (dataset)

```
That was with datalad 0.12.2 and then reproduced with 0.12.2.dev117

<details><summary>DataLad 0.12.2.dev117 WTF (configuration, datalad, dataset, dependencies, environment, extensions, git-annex, location, metadata_extractors, python, system)</summary>

# WTF
## datalad 
  - full_version: 0.12.2.dev117-g66da5-dirty
  - version: 0.12.2.dev117
## dataset 
  - id: None
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /tmp/testds
  - repo: AnnexRepo
## dependencies 
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 7.20200204+git1-gb2c529b88-1~ndall+1
  - cmd:bundled-git: 2.24.0
  - cmd:git: 2.24.0
  - cmd:system-git: 2.24.0
  - cmd:system-ssh: 8.1p1
  - exifread: 2.1.2
  - git: 3.0.5
  - gitdb: 2.0.6
  - humanize: 0.5.1
  - iso8601: 0.1.11
  - keyring: 18.0.1
  - keyrings.alt: 3.1.1
  - msgpack: 0.5.6
  - mutagen: 1.40.0
  - requests: 2.21.0
  - tqdm: 4.30.0
  - wrapt: 1.11.2
## environment 
  - GIT_PAGER: less --no-init --quit-if-one-screen
  - GIT_PYTHON_GIT_EXECUTABLE: /usr/lib/git-annex.linux/git
  - LANG: en_US.UTF-8
  - PATH: /home/yoh/proj/datalad/datalad-master/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - local repository version: 7
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions: 
    - 7
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  - version: 7.20200204+git1-gb2c529b88-1~ndall+1
## location 
  - path: /tmp/testds
  - type: dataset
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp: 
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.7.5
## system 
  - distribution: debian/bullseye/sid
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 267
  - name: Linux
  - release: 5.5.0-rc5-amd64
  - type: posix
  - version: #1 SMP Debian 5.5~rc5-1~exp1 (2020-01-06)
</details>

NB didn't check if actually export itself exported that subdataset properly

**Comment by adswa** [comment]
Pending a few band aids I will PR in a second, this issue doesn't reproduce anymore with DataLad ``0.17.9``:

```
(gooey) adina@muninn in /tmp/superds on git:master
❱ tree
.
├── file -> .git/annex/objects/5m/WZ/MD5E-s6--d577273ff885c3f84dadb8578bb41399/MD5E-s6--d577273ff885c3f84dadb8578bb41399
└── sub
    └── file -> .git/annex/objects/22/Gw/MD5E-s7--f447b20a7fcbf53a5d5be013ea0b15af/MD5E-s7--f447b20a7fcbf53a5d5be013ea0b15af

1 directory, 2 files
(gooey) adina@muninn in /tmp/superds on git:master
❱ datalad export-to-figshare
[INFO   ] Exporting current tree as an archive under /tmp/superds since figshare does not support directories 
export_archive(ok): /tmp/superds/datalad_303bf1fc-a01d-41fa-8473-30576cc71d0a.zip (file)
[INFO   ] Uploading /tmp/superds/datalad_303bf1fc-a01d-41fa-8473-30576cc71d0a.zip to figshare 
Article
Would you like to create a new article to upload to?  If not - we will list existing articles (choices: yes, no): yes

New article
Please enter the title (must be at least 3 characters long). [superds#303bf1fc-a01d-41fa-8473-30576cc71d0a]: safewf

[INFO   ] Created a new (private) article 21572166 at https://figshare.com/account/articles/21572166. Please visit it, enter additional meta-data and make public 
[INFO   ] 'Registering' /tmp/superds/datalad_303bf1fc-a01d-41fa-8473-30576cc71d0a.zip within annex 
[INFO   ] Adding URL https://ndownloader.figshare.com/files/38236380 for it     
[INFO   ] Registering links back for the content of the archive 
[INFO   ] Adding content of the archive /tmp/superds/datalad_303bf1fc-a01d-41fa-8473-30576cc71d0a.zip into annex AnnexRepo(/tmp/superds) 
[INFO   ] Initializing special remote datalad-archives 
[INFO   ] Finished adding /tmp/superds/datalad_303bf1fc-a01d-41fa-8473-30576cc71d0a.zip: Files processed: 5, removed: 5, +git: 3, +annex: 2 
add-archive-content(ok): /tmp/superds (dataset)                                 
[INFO   ] Removing generated and now registered in annex archive 
export_to_figshare(ok): Dataset(/tmp/superds) [Published archive https://ndownloader.figshare.com/files/38236380]
(gooey) adina@muninn in /tmp/superds on git:master
❱ git status
On branch master
nothing to commit, working tree clean
```

I checked whether the subdataset is exported; its content is not included in the upload. However, I wondered whether it should? There is no recursive option in `export-to-figshare`... If someone finds that to be a bug, please open a new issue about it - this one can be closed.
