### ISSUE TITLE
`create-sibling --existing replace` is dangerous

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4145]
It will perform a `rm -rf` on the remote end. No check if it would wipe out the last existing copy of a file, or whether there even is a dataset sibling.

I propose the complete removal of this functionality. It is totally unexpected that a command that is called `create...` destroys something remote:

```
/tmp % mkdir precious
/tmp % echo "all my secret keys" > precious/keys
/tmp % datalad create reckless
/tmp % cd reckless
/tmp/reckless (git)-[master] % datalad create-sibling localhost:/tmp/precious
[ERROR  ] Target path /tmp/precious already exists. And it fails to rmdir (rmdir: failed to remove '/tmp/precious': Directory not empty). [create_sibling.py:_create_dataset_sibling:161] (RuntimeError) 

# death
/tmp/reckless (git)-[master] % datalad create-sibling localhost:/tmp/precious --existing replace
create_sibling(ok): . (dataset)
% ls -l /tmp/precious
total 0

```

**Comment by bpoldrack** [comment]
Agree. Removal should be done very explicitly by the users themselves. I get that it might be quite convenient in the recursive case, but that's exactly where one might easily run into unintended consequences by relying merely on the notion that a directory exists. In case of a single dataset, one might be sure about that, but then one can easily rm it directly. When it's about thousands of datasets, it's convenient, but that's exactly the case where existence is a dangerous criterion since you likely don't have a complete overview of what's there and why and whether it's safe to remove.

**Comment by yarikoptic** [comment]
> Removal should be done very explicitly by the users themselves

It already is if the user **explicitly** provides `--existing replace`.  It would not really make it "safer"  by making it "more painful" .  To be on a safer side may be we should just issue a warning and seek confirmation (if ui is interactive, if not - fail or require yet another configuration setting or smth to confirm) that it is desired to remove it if actual removal is encountered.  May be even provide some information or even interactive shell to investigate.

**Comment by mih** [comment]
I tried:

```
datalad create-sibling localhost: --existing replace
```

Does it work for you? I'd say, we should have a one PR to wipe this "feature" out, and another one to make it safe. We merge them, whenever they get approved, in that order.

But honestly, given the command above you need magical powers to anticipate that it will wipe out everything, unconditionally. That is unacceptable.

**Comment by mih** [comment]
On top of this "feature" there is also:

`datalad create-sibling localhost:`

will happily drop a repository into $HOME -- no error, no warning.

**Comment by yarikoptic** [comment]
> I tried:
> 
> ```
> datalad create-sibling localhost: --existing replace
> ```
> 
> Does it work for you?

have you tried a `rm -rf ~/ crap`, does it work for you? ;)  I think I did manage to start killing my home once.


> `datalad create-sibling localhost:`
> 
> will happily drop a repository into $HOME -- no error, no warning.

hm... and default is 'error' but I guess we only check for having `.git/` there and not just any file.  Indeed yet another safety issue to fix, although this one is easier to later fix up for ;)

> I'd say, we should have a one PR to wipe this "feature" out, and another one to make it safe. We merge them, whenever they get approved, in that order.

I would say that it should be in a single PR - there is a feature, used feature, dangerous if misused (as many other commands). It could be made safer if desired.
you are suggesting to destroy all the hammers until a new manufacturer gets rubber boots on them.

**Comment by mih** [comment]
> you are suggesting to destroy all the hammers until a new manufacturer gets rubber boots on them

Absolutely not. But

```
ssh localhost rm -rf
```

sends a message that is much clearer than

```
datalad create-sibling localhost: --existing replace
```

the latter literally says "replace an existing sibling", not "delete all files in my homedir. Anyone interested in the latter can use the former command, at no additional cost.

But again, I am not opposed to someone making this feature safe, but the safe approach is to disable it, until it happens.
