### ISSUE TITLE
Q: how to update dataset hierarchy to the state of the remote hierarchy when some submodules go forward?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4148]
ATM we have only `update --merge -r` but that one would "pull" all submodules to the latest state present on remote.  That might result in progressing forward relative to the origin even if there is no local changes.  So the desired action to achieve is something along the lines of 

 `git pull --ff-only && git submodule update --recursive`

but that might detach heads due to `submodules`.

Here is a script (based on Kyle's way in #4118):
```
cd "$(mktemp -d --tmpdir dl-XXXXXXX)"

datalad create 3rd

datalad create rem
datalad -C rem clone -d . $PWD/3rd
datalad -C rem uninstall -d . 3rd

# Install hierarchy elsewhere
datalad install -r -s rem ds

# 3rd goes ahead
echo foo > 3rd/foo
datalad save -d 3rd

# rem goes ahead some other way
echo I read > rem/README.md
datalad save -d rem -r

# Intent is to update full hierarchy to reflect state of rem
# but we would then would be merging changes in 3rd not present in rem
datalad -C ds update -r --merge
git -C ds diff origin/master..
```
which would result at the end in smth like
```
diff --git a/3rd b/3rd
index 8fcac34..49003d6 160000
--- a/3rd
+++ b/3rd
@@ -1 +1 @@
-Subproject commit 8fcac346541f642a580478183dd7b007c4ca9683
+Subproject commit 49003d6324514140c4991c7a9aea6d877542f3fd
```
when the desire/intent to not have differences to the origin, i.e. `ds/3rd` staying in the same version as on original `rem`, not progressing forward as it did in its origin. 

How should we express it in `update` call?   

PS use case from https://github.com/CONP-PCNO/conp-dataset/ where actual subdatasets are of respective contributors, and shouldn't be progressed forward until curated.

**Comment by kyleam** [comment]
Thanks for the nice write-up.  I think it touches on some of the core issues behind gh-4118, and, while I think those changes move us in a better direction, it might be worth getting a handle on this before merging that in.

> ATM we have only `update --merge -r` but that one would "pull" all submodules to the latest state present on remote. That might result in progressing forward relative to the origin even if there is no local changes. So the desired action to achieve is something along the lines of
> 
> `git pull --ff-only && git submodule update --recursive`
> 
> but that might detach heads due to `submodules`.

And to continue with the `git submodule update` context, what `datalad update --merge -r` does can be seen as roughly

    git pull && git submodule update --remote --merge

I'm still not really sure what behaviors of `update` are intended, but I agree that in the situation you describe,  it doesn't seem desirable to advance to a commit that is not recorded in the up-to-date parent.  Ideally we'd have a way to say "try to put subdataset on the registered commit".  I'd even say that seems like it should be the default behavior, at least if we can do it in a fast-forward/no-op way (as in your example).

**Comment by yarikoptic** [comment]
Thanks for the thanks!  Your comment and `git pull && git submodule update --remote --merge` analogy gave me an idea on what "option" we are possibly missing:  `--follow=remote,superdataset`.  What we are doing now is pretty much `--follow=remote` -- we merge what is available from a remote without any regard to what dataset's "parent" superdataset expects.  With `--follow=superdatset` we would merge to "respect" the state which (remote) superdataset expects.  I am saying "respects", because subdataset could have its own changes, so action alike `git submodule update --recursive`, which would just reset to the state "parent" superdataset respect and discard local changes (AFAIK), wouldn't be desired.  So, in this (`--follow=superdataset`) case we just need to `git merge SUPERDATASET's-hexsha-for-the-submodule-on-the-remote` (instead of `git pull` which would progress forward, which would be what we do for `--follow=remote`).

Another use case I was often wanting, actually was already briefly discussed: #3079 "update: --fast-forward", and suggested there `--changes=merge,fast-forward`.  It feels that this option is orthogonal to `--follow` and pretty much should be just a safe-guard (similar to `git pull --ff-only`), to fail (without performing any actual merge, so we better do full analysis first) if pure fast-forward(s) are not possible somewhere in the hierarchy (if `-r`).

**Comment by kyleam** [comment]
> Your comment and `git pull && git submodule update --remote --merge` analogy gave me an idea on what "option" we are possibly missing: `--follow=remote,superdataset`. What we are doing now is pretty much `--follow=remote` -- we merge what is available from a remote without any regard to what dataset's "parent" superdataset expects. With `--follow=superdatset` we would merge to "respect" the state which (remote) superdataset expects.

I'm not sure the option name and values seem very clear to me.  Perhaps I'm just biased by the fact that I know the `git submodule`s spelling and any recasting is going to sound weird.  Anyway, I don't have any particular suggestions at this point, so let's go with those at least for now.

> I am saying "respects", because subdataset could have its own changes, so action alike `git submodule update --recursive`, which would just reset to the state "parent" superdataset respect and discard local changes (AFAIK), wouldn't be desired.

Sure, just as `git submodule update [--remote]` has the ability to merge (or rebase).

> So, in this (`--follow=superdataset`) case we just need to `git merge SUPERDATASET's-hexsha-for-the-submodule-on-the-remote` (instead of `git pull` which would progress forward, which would be what we do for `--follow=remote`).

Right.  This is why I'm uncertain about what to do with gh-4118.  That series works for the position that "it seems `update` is working as hoped and its definition of 'update' is fine overall for most users' needs".  (Coming from me, this is largely a guess.)  Given that, gh-4118 keeps the behavior the same (notice that no test changes were needed), except that it runs `git merge <recorded revision>` when the branch that would be merged in doesn't include the revision recorded in the parent.

So, this takes what was a `git submodule update --remote --merge` behavior and mixes in a bit of `git submodule update --merge` (no remote) behavior.  Merging that series makes me uneasy if we're going to follow up with options that provide a clear delineated these two behaviors.

I'll try to rework gh-4118 to introduce the `--follow=remote,superdataset` distinction that you propose, and let's see how things look.

**Comment by yarikoptic** [comment]
Thank you
