### ISSUE TITLE
half-initialized annex repo

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#4152]
Observed in PR #4124 :

In a fresh clone `git-annex-info` leads to a "half-initialized" annex. It does create `.git/annex` and its content and it does create the `annex.uuid` entry in `.git/config`. However, autoenabled special remotes were not enabled. At the same time, what it does prevents us from detecting that it wasn't properly initialized, since all the clues are there.
Actual call was : 'git-annex' 'info' '--debug' '--json' '--json-error-messages' '--bytes' '--fast'

Need to build a reproducible min. example and file issue with git-annex, I guess.

**Comment by yarikoptic** [comment]
so -- is there a human on the planet of earth who is capable to reproduce this issue? ;)

**Comment by bpoldrack** [comment]
Not reproduced w/ annex 8.20201127

Closing. Please reopen if it resurfaces.
