### ISSUE TITLE
temp. $HOME in test setup conflicts with datalad.cfg

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#4153]
Stumbeld upon this in PR #4124 :

We shoot our feet with the fake $HOME we set up for tests:
```
(Pdb) cfg.__dict__
{'_store': {'user.name': 'Benjamin Poldrack', 'user.email': 'benjaminpoldrack@gmail.com', 'url.ria+file:///tmp/datalad_temp__test_create_storele6bc8ij.insteadof': 'ria+ssh://test-store:', 'datalad.datasets.topurl': 'http://datasets-tests.datalad.org/', 'datalad.log.level': '100'}, '_cfgfiles': {'/home/ben/.gitconfig'}, '_cfgmtimes': {'/home/ben/.gitconfig': 1581683659.070651}, '_dataset_path': None, '_dataset_cfgfname': None, '_repo_cfgfname': None, '_config_cmd': ['git', '--git-dir=', 'config'], 'overrides': {}, '_src_mode': 'any', '_runner': <datalad.cmd.GitRunner object at 0x7f86b2795520>, '_gitconfig_has_showorgin': True}
```

Note, that it reads `/home/ben/.gitconfig`.
But:

```
(Pdb) os.environ['HOME']
'/tmp/datalad_temp_ft_s2hz0'
```

Since `datalad.cfg` is instantiated on import, it doesn't consider what `setup_package` does to $HOME and won't reconsider what global config to read from. This leads to inconsistencies in test configs.

I'd suggest to

```python
global cfg
cfg.reload(force=True)
```
in `setup_package` after changing home dir. What do you think, @datalad/developers ? Anything I miss here?

**Comment by yarikoptic** [comment]
good find!  adding reload in setup and teardown (after restoring HOME) sounds like the way to go.
