### ISSUE TITLE
separate out SSH test builds

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#4166]
Particularly with PR #4164, which uses `git-annex-testremote` SSH tests can take quite a while. At the same time, we have `@skip_ssh` to mark tests that require SSH and the respective `DATALAD_TESTS_SSH` to enable it.
I think we should have a dedicated build (matrix?), that would run the SSH tests *only* and have the other builds *not* run them. Otherwise we will exceed the time limit for Travis runs. Also: There are often paired tests - one for SSH one for local thing. An SSH build doesn't need to run the ones that a non-SSH build already ran. In `git-annex-ria-remote` (and therefore in PR #4164) I have an opposing decorator, that would skip a test if `DATALAD_TESTS_SSH` is *not* set. That way we could mark such pairs where it's sufficient to run either one of the tests.
Alternatively we might want to have a marking decorator, that could be discovered by nose (like `@usecase`)  - didn't look into that yet.

Either way - a separation in dedicated builds is needed, I guess. What do you think, @datalad/developers?

**Comment by mih** [comment]
FTR: we also have `@slow`

**Comment by bpoldrack** [comment]
True. Will try whether that's sufficient to delay the split. ;-)

**Comment by bpoldrack** [comment]
This was addressed by introducing the `turtle` attribute for tests and separate out the tests using `git annex testremote`, which can take a lot of time.
