### ISSUE TITLE
Development direction wrt to SSH usage

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#417]
We use SSH in a few places and we need SSH's controlmaster feature. Currently, SSH is treated as god-given shell binary. My question is: what is our general development direction in this regard.

1. Ignore. Currently implementation is unlikely to work on Windows (Mac OS I am not sure either) and we are OK with that.

2. Acknowledge partially and ignore for now. We create a minimall SSH wrapper class that we use in our code base to secure a better chance to support SSH better in the future with justifiable effort.

3. Switch to using a proper Wrapper like http://www.paramiko.org or https://github.com/mwilliamson/spur.py (both in Debian) hoping that they bring some improvement in cross platform support.

**Comment by yarikoptic** [comment]
I would say that 2.wrapper approach with later tuning it to either to go either 3. or just use bundled into distribution ssh (probably annex bundle installation already does that even for windows, so we could just use it)

**Comment by hanke** [comment]
Closing this: the outcome grows in #435

**Comment by yarikoptic** [comment]
another interesting related project is https://github.com/ronf/asyncssh (python3 only -- asyncio based implementation)
