### ISSUE TITLE
"datalad status -e commit" takes 2+ hours 

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4184]
#### What is the problem?
I am getting back to merging modifications to a master location. The data is 1.7Tb and is split in several subdatasets, total ~450 of which 440 are subject datasets in one of the bids folder. After merging some changes from another location, I am going back to the root superdataset to check if any subdataset is out of sync (i.e., the submodule registered in the parent dataset is not pointing to the last commit of the subdataset). I use `-e commit` to avoid thorough checks, but it takes almost 3 hours anyway:

```
[dorian@mri FEDERATED_DATASETS]$ time datalad status -e commit
nothing to save, working tree clean

real    0m0.272s
user    0m0.203s
sys     0m0.077s
[dorian@mri FEDERATED_DATASETS]$ time datalad status -e commit --recursive
nothing to save, working tree clean

real    169m26.862s
user    7m6.813s
sys     8m17.664s
```
Is this normal? Is my command correct for simply checking proper registration of latest commit of each subdataset into parent?

#### What steps will reproduce the problem?
Can't tell how to reproduce, try on a big superdataset.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.12.2 (installed from github yesterday)

#### Is there anything else that would be useful to know in this context?
No

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Yes.

**Comment by mih** [comment]
I think I mentioned it before, but with huge datasets and if you dont need type evaluation try `-t raw`

**Comment by dorianps** [comment]
Yes, I remember now the trick was to use both of them. Will try that shortly. But what I can't reconciliate is the description of those two flags:
`-e commit`: With ‘commit’ only a discrepancy of the HEAD commit shasum of a subdataset and the shasum recorded in the superdataset’s record is evaluated, and the ‘state’ result property only reflects this aspect. 
`-t raw`: With ‘raw’ no type inspection is performed, and symlinks representing annex’ed files are indistinguishable from other symlinks. 

Why would symlinks matter (`-t`) if `-e commit` should only check the shasum commit and no files or symlinks?

**Comment by mih** [comment]
Because in the second case you ask for recursion with no path contraints. That means a complete status report (all files, everything). Just in case of subdatasets it doesn't additionally recurse into them to figure out their state within a given dataset.

**Comment by dorianps** [comment]
Sorry @mih, maybe this is clearer from a developer view, but I still don't get it from a user side. I am asking datalad to recurse through subdataset and check `-e commit` (everywhere downstream). If it starts to check files and symlinks, then `-e commit` is not respected downstream. Not sure why going downstream should change the type of check on the subdataset. For example, I can have a dataset somewhere in a dirty state, but I am not asking to check that (`-e full`), I am asking only to know if its parent has properly registered the current commit. Why wouldn't this be the same with and without recursion?

**Comment by mih** [comment]
> I am asking datalad to recurse through subdataset and check -e commit (everywhere downstream)

This might be the misconception.That is not what status does.

You are asking for the status of the paths given to the `status` command. If no paths are given, the path is PWD, with `--recursive` you are asking for the status of anything underneath the path. That includes much more than just subdatasets. `-e commit` merely alters the behavior when encountering a subdataset in the status reporting. It does not exclude or disable any other reporting (compare `datalad -f json status--recursive`). If you have a suggestion on how to improve the docs in this regard, please let me know.

**Comment by dorianps** [comment]
Got it. Only suggestion is to put your explanation above in the book/docs, it is quite clear.

I also tried this which is much faster
`git submodule foreach --recursive 'git status -s'`: 42 seconds
whereas:
`datalad status -e commit -t raw --recursive`: 5m27s

Maybe I just need that first git command to get the information I need (which subdataset is out of sync with the parent registration). But then again what is datalad doing more in the command above that needs more time (dealing with files?).

Thank you for helping me understand the background process.

**Comment by mih** [comment]
Your're welcome.

That speed difference is likely caused by Git already having cached the status to some degree (datalad does not do any caching at the moment). But in general, we try to not be in Git's or Git-annex's way. If they provide a faster, better, more elegant way in some case, it is always a possibility to use them directly.

**Comment by dorianps** [comment]
Thanks. Closing.
