### ISSUE TITLE
siblings: should provide a way to list all known (to git-annex) remotes (siblings)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4193]
ATM seems to show only "enabled" siblings:
```shell
$> git clone http://datasets.datalad.org/crcns/aa-1/.git
Cloning into 'aa-1'...
remote: Counting objects: 22913, done.
remote: Compressing objects: 100% (11030/11030), done.
remote: Total 22913 (delta 9039), reused 22788 (delta 8988)
Receiving objects: 100% (22913/22913), 1.89 MiB | 2.44 MiB/s, done.
Resolving deltas: 100% (9039/9039), done.

$> cd aa-1

$> datalad siblings                                     
.: here(?) [git]
.: origin(?) [http://datasets.datalad.org/crcns/aa-1/.git (git)]
```
and I think it would be nice to list at least some from:

```shell
$> git annex info  
...
semitrusted repositories: 7
	00000000-0000-0000-0000-000000000001 -- web
 	00000000-0000-0000-0000-000000000002 -- bittorrent
 	1e41b9cf-4479-4ef1-8c66-e6cfbf861f2e -- datalad
 	3dee27a1-32f5-494c-b484-d3cbdcefa356 -- yoh@lena:/tmp/aa-1 [here]
 	79080a38-0e94-4a0a-bd89-9022eada547b -- yoh@smaug:/mnt/btrfs/datasets/datalad/crawl/crcns/aa-1
 	895b9a07-6613-4c8a-95ae-280d8119475c -- datalad-archives
 	fa2495e7-17ae-44de-9c6b-e737ee445d6e -- yoh@falkor:/srv/datasets.datalad.org/www/crcns/aa-1 [origin]
```

My guess would be to filter out those starting with `000000...` but report others, with information on either they are known git annex special remotes as listed in
```
$> git show git-annex:remote.log                                
1e41b9cf-4479-4ef1-8c66-e6cfbf861f2e autoenable=true encryption=none externaltype=datalad name=datalad type=external timestamp=1464124519.012356s
895b9a07-6613-4c8a-95ae-280d8119475c autoenable=true encryption=none externaltype=datalad-archives name=datalad-archives type=external timestamp=1464124520.081473s
```
showing which could be enabled.

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
