### ISSUE TITLE
FOI: v5 is no longer supported even

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4217]
may be I missed the news already stated, but wanted to share:
```shell
$> git annex get --debug 05+swi_acq-qsm_run-01/SWI+05+swi_acq-qsm_run-01_01+00001.dcm
git-annex: Repository /tmp/SWIdataset is at unsupported version 5. Automatic upgrade is disabled by annex.autoupgraderepository configuration. To upgrade this repository: git-annex upgrade

$> git annex version
git-annex version: 8.20200226+git16-ge156a2b74-1~ndall+1
```

**Comment by kyleam** [comment]
I'm not aware of a dedicated issue about it.  In gh-4000, I touch on the issue regarding Travis:

> And when neurodebian's git-annex (i.e. what we test with on Travis) is at least 7.20190912, v5 will also auto-upgrade to v7. I think this becomes a little tricky because, if our minimum git-annex version doesn't auto-upgrade, we'll want to still have a run that tests v5 repos. So we'd either need to add a run that gets an older git-annex from somewhere else or bump the minimum required version.

In addition to tests, we should probably do a tree-wide sweep the check what places assume a v5 default once our minimum git-annex version is at least 7.20190912.  (This should mostly be comments, unnecessary conditions, etc., because functionally we should already be okay with the v6+ default.)

**Comment by mih** [comment]
FTR: Since #4283 all windows tests use 8.20200309 and the subset tested on appveyor seem OK with it.

**Comment by kyleam** [comment]
>> In addition to tests, we should probably do a tree-wide sweep the check what places assume a v5 default once our minimum git-annex version is at least 7.20190912. (This should mostly be comments, unnecessary conditions, etc., because functionally we should already be okay with the v6+ default.)

> FTR: Since #4283 all windows tests use 8.20200309 and the subset tested on appveyor seem OK with it.

git-annex has been upgrading Windows/crippled file systems into v6+ well before 7.20190912, ever since direct mode removal on annex's end.

**Comment by yarikoptic** [comment]
I guess everyone absorbed this FOI
