### ISSUE TITLE
Be more clever wrt to "install from submodule checkout"

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#424]
Apologies for a possible duplication, but I couldn't find the original discussion anymore.

Synopsis: Git's submodule implementation is not as clever as it could be with respect to figuring out from which location to clone a submodule. Here is a demo of the core issue:

````
% datalad install -s http://psydata.ovgu.de/studyforrest/templatetransforms/.git tnt
% cd tnt
% grep -A2 '^\[submodule "raw/structural"\]' .gitmodules
[submodule "raw/structural"]
	path = raw/structural
	url = ../structural
````

The location of the respective submodule is this: http://psydata.ovgu.de/studyforrest/structural/

Given that it isn't a bare repository the actual source URL is: http://psydata.ovgu.de/studyforrest/structural/.git/

Current Git is not able to figure this out.

AFAICS we can work around this problem, by detecting a failure and make an educated second guess. First the failure:

````
% datalad install raw/structural
....
2016-05-05 09:22:07,575 [ERROR  ] CommandError: command '['git', 'submodule', 'update', '--init', 'raw/structural']' failed with exitcode 128.
| Failed to run ['git', 'submodule', 'update', '--init', 'raw/structural'] under '/tmp/tnt'. Exit code=128. out=Submodule 'raw/structural' (http://psydata.ovgu.de/studyforrest/templatetransforms/structural) registered for path 'raw/structural'
|  err=Cloning into 'raw/structural'...
| fatal: repository 'http://psydata.ovgu.de/studyforrest/templatetransforms/structural/' not found
| fatal: clone of 'http://psydata.ovgu.de/studyforrest/templatetransforms/structural' into submodule path 'raw/structural' failed
|  [cmd.py:run:296] (CommandError) (main.py:235)
````

This leaves us without an initialized submodule, but a misconfigured submodule URL remains:

````
% git submodule status raw/structural
-54e555acea857acdb2a8b713cc4c7c7b09607b3d raw/structural
% git config submodule.raw/structural.url
http://psydata.ovgu.de/studyforrest/templatetransforms/structural
````

We can fix this by looking at 

````
% git config remote.origin.url
http://psydata.ovgu.de/studyforrest/templatetransforms/.git
% grep -A2 '^\[submodule "raw/structural"\]' .gitmodules |grep url | cut -d '=' -f 2
 ../structural
````

Remove `.git` from the origin URL, and resolve the relative path from the submodule URL. For increased flexibility we could try first with the resulting http://psydata.ovgu.de/studyforrest/structural and fail again in this case, and subsequently append `/.git/` and try one last time. However, it seems unlikely that git repositories at a close-by location mix different setup (bare, non-bare, ...).

Anyway, after fixing up the git config setting things start working:

````
% git config submodule.raw/structural.url http://psydata.ovgu.de/studyforrest/structural/.git/
% mkdir raw/structural
% datalad install raw/structural
2016-05-05 09:40:47,548 [ERROR  ] stderr| Cloning into 'raw/structural'... (cmd.py:351)
1 installed item is available at
<Dataset path=/tmp/tnt/raw/structural>
% git -C raw/structural status
HEAD detached at 54e555a
nothing to commit, working directory clean
````

Few notes:

- this workaround doesn't require a modification of any content checked into Git, hence no useless cruft is generated in the history
- appart from an initial failing clone attempt it doesn't waste bandwidth or storage with useless intermediate results
- the `mkdir` above is required as the initial install attempt kills the submodule mount point for some reason. If datalad doesn't find this mountpoint the second install attempt will happily create a new empty submodule -- this is likely a bug on its own
- for reasons not 100% clear to me the trailing `/` of the fixed submodule URL is critical

**Comment by hanke** [comment]
Quick follow up:

This workaround could be extended to also address a similar issue, namely when the submodule is actually checked out at its configured mountpoint inside the parent repository. In this case, we could attempt to clone from a URL that we derive from the origin URL and the `path` setting in `.gitmodules` using the same logic.

It could be argued that checking such a URL first would be better than going to the configured source URL for the submodule. Rational: if the parent repo actually contains an accessible checkout of its submodule, it is more likely to actually contain the desired commit.

If we want to do this, the workaround presented above would need to be modified to skip the initial "blind" clone attempt and pre-configure a candidate submodule URL. Here are the steps for the same URL as above (other initial candidate URLs are possible, obviously):

````
% datalad install -s http://psydata.ovgu.de/studyforrest/templatetransforms/.git tnt
1 installed item is available at
<Dataset path=/tmp/tnt>
% cd tnt
% git config submodule.raw/structural.url http://psydata.ovgu.de/studyforrest/structural/.git/
% datalad install raw/structural
2016-05-05 10:01:39,107 [ERROR  ] stderr| Cloning into 'raw/structural'... (cmd.py:351)
1 installed item is available at
<Dataset path=/tmp/tnt/raw/structural>
% git -C raw/structural status
HEAD detached at 54e555a
nothing to commit, working directory clean
````

**Comment by yarikoptic** [comment]
There was some discussion with git upstream: http://thread.gmane.org/gmane.comp.version-control.git/292032 . So indeed rewrites of urls in failed to initialize submodules is a workaround, and indeed might "scale" then to similar manual labor for cloning from non-bare clones (i.e. our installations).  I am still not sure though, if there would be any benefit, since such manual url derivation is to be done anyways, to imho more straightforward "derive url; git clone url submodule/path; git submodule update --init submodule/path" as I have suggested on the datalad-team ml.
Meanwhile I think that git should address upstream the issue that it auto-detects/senses .git/ for ssh and local file targets but not http:// repos. I will raise the discussion on git upstream ml

**Comment by hanke** [comment]
Good point. I agree that treating submodule installation like regular cloning (plus subsequent init) has potential to uniformize procedures und we could factor out the relevant bits.

**Comment by yarikoptic** [comment]
FWIW:  http://thread.gmane.org/gmane.comp.version-control.git/293777  post to git upstream about possibility to sense for /.git over http

**Comment by yarikoptic** [comment]
For now I have crafted apache2 rewrite rule which I have deployed on datasets.datalad.org, so we could approach this workaround path and/or use it for demos if by then no proper resolution is done:
```
 RewriteEngine On
 RewriteCond "!.*/\.git/.*"
 RewriteRule "(.*?/)((?<!\.git/)(HEAD|config|annex/objects/.*|objects/(info/[^/]+|[0-9a-f]{2}/[0-9a-f]{38}|pack/pack-[0-9a-f]{40}.(pack|idx))|git-(upload|receive)-pack)|info/refs)$" "$1.git/$2" [PT]
```
NB ds00005 is indeed not there yet  or smth, so ignore
```
$> git clone --recursive http://datasets.datalad.org/openfmri
Cloning into 'openfmri'...
Checking connectivity... done.
Submodule 'ds000001' (http://datasets.datalad.org/openfmri/ds000001) registered for path 'ds000001'
Submodule 'ds000002' (http://datasets.datalad.org/openfmri/ds000002) registered for path 'ds000002'
Submodule 'ds000003' (http://datasets.datalad.org/openfmri/ds000003) registered for path 'ds000003'
Submodule 'ds000005' (http://datasets.datalad.org/openfmri/ds000005) registered for path 'ds000005'
...
Checking connectivity... done.
Submodule path 'ds000003': checked out '6785d552f8949afed4417ed50edf40e5b11fae70'
Cloning into 'ds000005'...
fatal: repository 'http://datasets.datalad.org/openfmri/ds000005/' not found
fatal: clone of 'http://datasets.datalad.org/openfmri/ds000005' into submodule path 'ds000005' failed

$> git clone http://datasets.datalad.org/test                
Cloning into 'test'...
Checking connectivity... done.

$> cd test
123@  sub1/

$> git annex get 123                         
(merging origin/git-annex into git-annex...)
(recording state in git...)
/tmp/test/.git/annex/tmp/SHA256E-s4--181210f8f9c779c26da1d9b2075b 100%[============================================================================================================================================================>]       4  --.-KB/s    in 0s      
(checksum...) ok
(recording state in git...)
```

**Comment by hanke** [comment]
FTR: PR 427 fully implements a solution to this issue.

**Comment by hanke** [comment]
All merged now, closing....
