### ISSUE TITLE
rerun: add `--file` mode

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4242]
ATM `rerun` requires to specify (range of) commits to be reran.  My most frequent use case is to rerun some script to regenerate a particular FILE.  For that I need to first `git log FILE`, copy paste commit HEXSHA which changed file, and then compose `datalad rerun HEXSHA`.  
I think having a `--file FILE` option to identify the commit to rerun would have been great.

In "git fashion", we could even allow for `datalad rerun FILE|REVISION`, with disambiguation via `datalad rerun -- FILE` whenever mysteriously there is a FILE and REVISION with the same "name".

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
