### ISSUE TITLE
Fate of AnnexRepo.sync()

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4244]
`sync()` is used twice in the entire code base (one usage is in `merge_annex()`. This method is a trivial frontend to a `git-annex sync` call that is easily done with `call_git` -- and is done in this fashion in `AnnexRepo._save_post()`. `AnnexRepo.merge_annex()` is actively being avoid (e.g. in `update()`), because it leaves behind the `synced/...` branches.

I propose to dissolve both methods and replace them with `call_git()` calls, or a local sync helper from #4243 that also handles the removed of the `synced/...`branches.

**Comment by yarikoptic** [comment]
I am ok to stop using `annex sync` (to avoid `synced/` branches proliferation), but it is not clear to me why in general `call_git` is preferable over having a `sync` method possibly just calling out to `call_git` if that is all it does.

**Comment by mih** [comment]
The existing `AnnexRepo.sync()` method offers access to only a subset of the functionality of `annex sync` and merely converts Python kwargs into a command arg list. It is untested, and barely used. As such it can be considered "dead weight", and consequently should be removed.

**Comment by mih** [comment]
https://github.com/datalad/datalad/pull/4243 replaces all usage of `merge_annex()`

**Comment by mih** [comment]
Retitled after #4243 was merged.
