### ISSUE TITLE
Test repo setup (additionally) broken with adjusted branches

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4248]
While working on #4227 I came to realize that any annex test repo will only ever manipulate the adjusted branch, and never ever sync the corresponding branch. All sensible assumptions on how a dataset would be set up using datalad's own procedures are invalid for the test repos. If things work with test repos that has no predictive value on real operations, and if things don't work also not.

At some point I will find the courage to delete them.

**Comment by mih** [comment]
A workaround could invoke `AnnexRepo.localsync()` at the end of `BasicAnnexTestRepo.populate()`, which is coming in https://github.com/datalad/datalad/pull/4243

**Comment by yarikoptic** [comment]
> All sensible assumptions on how a dataset would be set up using datalad's own procedures are invalid for the test repos.

They are "repos" not "datasets", so I do not see why dataset procedures should be applied.
Having said that I am not against having them overhauled (trimmed, etc) -- they are one of the oldest code pieces.  Attempts were made though.

> At some point I will find the courage to delete them.

as long as there is a reasonable substitute which would allow to retain using them tests - why not.

**Comment by mih** [comment]
> as long as there is a reasonable substitute which would allow to retain using them tests - why not. 

That is why I am not doing it. But it is a matter of fact that less and less tests are using them, so the issue will go away over time.

**Comment by mih** [comment]
This issue can be closed, the ultimately solution presents itself in https://github.com/datalad/datalad/issues/6144
