### ISSUE TITLE
Unable to create a dataset, git annex issue

### ISSUE THREAD

**Issue by alicebizeul** [datalad/datalad#4251]
Hi, 

I am unable to create a dataset due to the following error. Following issue #3932, I initialised the git annex (git-annex init) and tried to create the dataset once again, this did not resolve the issue.
 
### What is the problem ?

CommandError: command '['git-annex', 'add', '--json', '--json-error-messages', '--include-dotfiles', '-c', 'annex.largefiles=nothing', '--', '.datalad']' failed with exitcode 1
Failed to run ['git-annex', 'add', '--json', '--json-error-messages', '--include-dotfiles', '-c', 'annex.largefiles=nothing', '--', '.datalad'] under '/home/abizeul'. Exit code=1.
Invalid option `--include-dotfiles'

#### What steps will reproduce the problem?
datalad create --force

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.12.2

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
First time using Datalad ! 

Thank you !

**Comment by kyleam** [comment]
Thanks for the report.  This failure is due `--include-dotfiles` being removed in the latest git-annex release (8.20200226).  It is addressed by gh-4214 (merged), but there hasn't been a DataLad release yet.

**Comment by kyleam** [comment]
v0.12.3, with compatibility fixes for the latest git-annex, has been released and uploaded to PyPI.
