### ISSUE TITLE
Add osx to travis

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#426]
see example from non-python world: https://github.com/Psychtoolbox-3/Psychtoolbox-3/pull/333/files . Canonical doc: https://docs.travis-ci.com/user/multi-os/

**Comment by mih** [comment]
Uh, ah -- I wasn't even aware of this being a possibility. Was there any show stopper? Why are we not doing this?

**Comment by yarikoptic** [comment]
I think just because noone did it ;)   I am not aware of any showstoppers, just possible a mild annoyance of probably needing to pull in miniconda and deal with installing git-annex there somehow

**Comment by driusan** [comment]
For what it's worth, in my experience the osx build queue on Travis tends to have backlogs more often than the linux queue, but is otherwise pretty reliable.

**Comment by yarikoptic** [comment]
we added osx to git actions here and also in https://github.com/datalad/git-annex
