### ISSUE TITLE
How to check all file content is present?

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4281]
#### What is the problem?
How should I check if all the files in all datasets/subdatasets have file contents locally available? I noticed there is something like `git annex fsck` but not sure how to apply it recursively and print only missing content (it prints a huge list of `ok` files).

To clarify, I need the content to be within the dataset, I don't care if a copy is available elsewhere. I am trying to check if the master location has all the files and I did not miss anything when merging updates from other locations.

#### What steps will reproduce the problem?
NA

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.12.2 (installed from github, how do I find the installed hash?)

#### Is there anything else that would be useful to know in this context?
NA

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Yes

**Comment by mih** [comment]
Check out

`datalad -f json status --annex availability`

**Comment by kyleam** [comment]
> I noticed there is something like `git annex fsck` but not sure how to apply it recursively and print only missing content (it prints a huge list of `ok` files).

If you want to stick to using git-annex directly, I think the command you're looking for is `git annex find`, in particular `git annex find --not --in=here`.  Assuming your entire hierarchy is annex repos, you could do something like this from the top repository:

```sh
git annex find --not --in=here
git submodule foreach --quiet --recursive \
    'git annex find --not --in=here --format=$displaypath/$\\{file\\}\\n'
```

**Comment by mih** [comment]
I think this can be closed. If there is need for further info, please reopen.

**Comment by dorianps** [comment]
Thank you both for the tips.
Just a quick report. Tried both, Kyle's code does not produce any outcome which I take it as no missing files. Michael's methods produced the json outputs, but I guess I need to filter through those to find missing content. Kyle's method ended up taking longer, below are the times 

```
[dorian@mri freesurfer]$ time git annex find --not --in=here

real    0m0.108s
user    0m0.069s
sys     0m0.048s
[dorian@mri freesurfer]$ time git submodule foreach --quiet --recursive \
>     'git annex find --not --in=here --format=$displaypath/$\\{file\\}\\n'

real    99m37.249s
user    3m11.808s
sys     3m0.294s

[dorian@mri freesurfer]$ time datalad -f json status --annex availability --recursive
real    73m10.572s
user    51m54.640s
sys     10m46.091s
```

**Comment by dorianps** [comment]
Just a suggestion, it might be helpful to place  the code suggested above in the book FAQ.

**Comment by adswa** [comment]
good idea, @dorianps, will do.

**Comment by yarikoptic** [comment]
if it is not a crippled filesystem and no unlocked files, I wonder how such check
```
du -sbL PATH 2>&1 | grep -v '\.git/'| grep 'cannot access'
```
to detect the missing ones would compare? ;)

**Comment by mih** [comment]
> Michael's methods produced the json outputs, but I guess I need to filter through those to find missing content.

`-f json` output is made to be processed with `jq`. Here is a full example:

```
datalad -f json status --annex all | jq '. | select(.has_content == true) | .path'
```

which translates to:

1. for any record...
2. select those which have `has_content=true`
3. print the `path` property

`jq` is a mighty beast. In combination with the richness of reported result properties (not just for `status`) many relatively sophisticated queries are possible.

**Comment by dorianps** [comment]
An update here. Both the git-based and datalad-based solution work well to find missing annex files. But there is a difference in performance. Here are the commands that work for me (6Tb dataset).

Via datalad:
(122mins first time, 78mins second time I ran it)
```bash
echo "Searching for missing files" ; \
datalad -f json status --recursive --annex all | \
jq '. | select(.has_content == false).path'
```


Solution via git:
(88mins \first time, 2.5mins second time I ran it) 
```bash
git annex find --not --in=here --format=$displaypath/$\\{file\\}\\n; \
git submodule foreach --quiet --recursive     'git annex find --not --in=here --format=$displaypath/$\\{file\\}\\n'
```
