### ISSUE TITLE
radical: Enable "consumer" functionality without needing git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4286]
In many use cases, datalad is used solely as a tool to get data.  Installation of git-annex across platforms remains an issue - with conda packaging efforts things improved, but not solved across platforms.
So I think through an idea to at least consider providing a GitAnnex class "implementation" providing only a few interfaces (e.g. `get` and `drop`) which we would implement for the most typical types of data access -- from a proper git remote via ssh or http (we can do it) or from URLs.  We will not bother with `annex init` or even being "considerate" about problems with adjusted branches/smudge filtering and what git would start thinking about having a large file appearing inplace of a symlink - we would just `get` file content into the `.git/annex/objects/...` if file is a real symlink, or inplace if file is on a crippled file system.

Sure thing a big fat warning would be issued such as  

**WARNING!!! No git-annex found installed.  DataLad is operating in minimalistic "consumer" mode and only basic commands (clone, install, get, drop, remove, uninstall) are available on git-annex repositories.  You are strongly encouraged to install git-annex for proper functioning.  You might need to reinstall datasets which you installed in this minimalistic mode**

Sure thing warning could be made suppressed with some datalad config setting.
If we find no way to `get` a file without requiring `git-annex` we would also issue an informative error message for that file.

But otherwise -- it should make it possible to just `pip install datalad` on any system and `install/get` data from the majority of datasets we share or care about.

**Comment by mih** [comment]
It would make sense to me to have a minimal Python-based surrogate. However, I would not be thrilled to see the complexity for working with different flavors of git-annex implementations folded into the already complex base classes. I'd say, if it can be done as a `git-annex` replacement binary that supports a minimal subset of the functionality of the original I am all for it, and it should have minimal impact on datalad itself.

**Comment by yarikoptic** [comment]
to some limited degree https://github.com/datalad/datalad-fuse/ would achieve that I guess... but in general sounds potentially too much to implement etc. unlikely anyone would embark on this endevor in near future, thus will just close
