### ISSUE TITLE
wishlist: run --adjusted=otherbranch (and sure thing rerun knowing how to handle it ;-))

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4310]
ha -- couldn't come up with a better name ;-)
This use case is actually really tightly relates to good old `datalad-crawler` setup of working with archives.  We have `incoming` branch which has pristine content from the web, and `incoming-processed` which "merges" from incoming, but where content is extracted and possibly cleaned up.  So merge strategy is not really a merge - but rather "take content of incoming tree, dump it here, perform operation, commit merge (so we know where we came from in incoming-processed and incoming).

And now I came to the exact same situation in another case.  Consider e.g. one branch containing ".mnc" files whenever we want another branch with "nii.gz" files, so we want to run `conversion` command.  Running once is all ok, but how to do it repeatedly if original branch would get changes to those .mnc files?
In my use case -- it is simply different naming of the files between two branches (`dandi organize` command).  In each of those cases it is just a matter of running a command on the content of another commit, and committing it as a merge based on the previous state of this other branch (could be the same if it is initial commit where such run is performed).
If we have this, future possible RFing of datalad-crawler could have taken advantage of it as well.

So it does remind "adjusted" branches of git-annex! but with `datalad run` flavor to it ;-)

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
