### ISSUE TITLE
clone() docs do not mention ability to clone specific version/branch

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4313]
Which is possible when cloning from a RIA store like:

`datalad clone ria+http://store.datalad.org#76b6ca66-36b1-11ea-a2e6-f0d5bf7b5561@<shasum|branchname|tag>`

**Comment by adswa** [comment]
Not that I want to brag, but the handbook does :stuck_out_tongue:

**Comment by mih** [comment]
That not-brag earns you a: "Would you mind adding an example record to clone via a PR?"

:stuck_out_tongue_closed_eyes:

**Comment by adswa** [comment]
Sure :stuck_out_tongue_winking_eye:

**Comment by adswa** [comment]
:tongue:
