### ISSUE TITLE
Does not install main entrypoint on windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4315]
Can be seen here https://ci.appveyor.com/project/mih/datalad-metalad/builds/31523205

and has also been reported by a user: https://github.com/datalad-handbook/book/issues/409

Affects the 0.12.3 release too.

**Comment by mih** [comment]
@yarikoptic figured out that it does install entrypoints, but our custom unix version and not the required native ones. Fix is coming.

**Comment by adswa** [comment]
Thank you!

**Comment by yarikoptic** [comment]
All wheels for recent releases were removed.  Just in case if some cached by CDN ones are used,
https://stackoverflow.com/a/38263887/1265472 gives an answer to use
```shell
pip install datalad --no-binary :all:
```
but it could lead to our dependencies also not been installed from wheels, which could give many kinds of pains.  So I just hope that eventually (within a day?) pypi would simply stop providing our removed wheel and things should clear up.

**Comment by mih** [comment]
No success yet. I guess we have to make a new release to fix it. https://ci.appveyor.com/project/mih/datalad-metalad/builds/31526178

**Comment by mih** [comment]
The 0.12.4 release enables installation on windows (due to no wheel being available from PyPi). Evidence: https://ci.appveyor.com/project/mih/datalad-metalad/builds/31569411
