### ISSUE TITLE
siblings(add) reporting confuses

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4322]
Here is the original report: https://neurostars.org/t/using-bitbucket-with-datalad/6226/3

A pure git remote is configured (presumably successful). However, the particular phrasing and classification of the messages makes that user conclude that it failed.

Ping @adswa for awareness

**Comment by adswa** [comment]
Thanks for the ping!
I think it would be good to improve the warning (I can take a whack at this), and I will also add an explanation of what this is in this PR https://github.com/datalad-handbook/book/pull/418.
