### ISSUE TITLE
Refactor GitRepo/AnnexRepo

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#434]
The `git_*` and `annex_*` methods should go and be replaced by implementations that do the right thing depending on the class type.

This will also make it more feasible to integrate some helpers that were/are scattered around the codebase, e.g. `get_remotes()` that could filter out annex remotes, but was removed in 23ce4b213be3485be2d8e6ce80d526452fd835dc because nothing used it.

**Comment by yarikoptic** [comment]
I thought we had an issue for this but I guess I was wrong.  also related #299 (`__repr__`s)

**Comment by hanke** [comment]
Conclusion from discussion: Do plain old, no fancy, inheritance.
