### ISSUE TITLE
Abandon default result summary renderer?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4343]
When #4337 is merged, we no longer need this, IMHO. It is the piece of code that adds info like this this the end of a command:

```
action summary:
  add (ok: 1001)
  save (ok: 2)
```

Commands like `status` have dedicated summary renderers that remain useful (and other commands could-should get some as well), but the default one is of little use with #4337 active.

**Comment by kyleam** [comment]
I think it makes sense to drop it.  I guess the main case it could still be useful is where the main truncated result listing wouldn't fit on the screen but the summary would.  I doubt that is common enough to make the default result summary renderer worth keeping around.

**Comment by mih** [comment]
I have now witnessed a few cases where the rhythm of reporting included a result `action` switch often enough to still yield dozens of pages of output.
