### ISSUE TITLE
Dependency on gitlab package is missing

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4344]
ATM needs to be manually installed to make `create_sibling_gitlab()` work.

**Comment by jsheunis** [comment]
Ok, so from what I can derive: `python-gitlab` should be added to the `requires` dict in [setup.py](https://github.com/datalad/datalad/blob/master/setup.py). Should it be under a specific key? `publish`?

**Comment by mih** [comment]
I think it makes sense to treat it exactly like the github-related software components. So yes, under `publish`, I think. Thx!

**Comment by yarikoptic** [comment]
#5776 fixed it but merged into maint so didn't auto close
