### ISSUE TITLE
idea: store trimmed (or all?) outputs by default renderer?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4351]
just a follow up to https://github.com/datalad/datalad/pull/4337 which would please many I bet ;)  Thank you again.  An idea: I forgot in which tool I saw it, but in cases of trimmed output, it might be worthwhile to just save all of them (trimmed or not) into a file and then instead of
```
[XXX similar messages have been suppressed]
```
report smth like
```
[XXX similar messages have been suppressed. See /path/to/<datetime>-<pid>.outputs for full list]
```
`/path/to` could be `/tmp` or some `~/.cache/datalad/outputs` .

File could even have all the ANSI decorations, `less -R` could be used to view "in color".
I guess it could even be a setting to tune to either do that for only trimmed, or for all runs, or never.

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
