### ISSUE TITLE
datalad: Unknown command 'push'

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4356]
#### What is the problem?
http://docs.datalad.org/en/latest/generated/man/datalad-push.html
```
$ datalad push --to origin --force datatransfer
datalad: Unknown command 'push'.  See 'datalad --help'.

Did you mean any of these?
        publish
```
Is `push` deprecated?

#### What steps will reproduce the problem?
Try `datalad push` on the command line.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
```
datalad 0.12.4
```

#### Is there anything else that would be useful to know in this context?
No.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Yes.

**Comment by dorianps** [comment]
Here is another one:
```
$ datalad create-sibling-ria -s origin ria+ssh://dorian@xx.xx.xx.xx/DATA/dorian/testremote
datalad: Unknown command 'create-sibling-ria'.  See 'datalad --help'.

Did you mean any of these?
        create-sibling
        create-sibling-gitlab
        create-sibling-github
```
This is simply following the book example: http://handbook.datalad.org/en/latest/usecases/datastorage_for_institutions.html#step-by-step

To clarify, all I am trying to do is pull (i.e., install) a dataset from ssh, make a change, and push back the changes (including file content) to the original ssh location. Can you help me with how to do this? A simple example would be great, can't seem to figure it out from book examples. So far, `publish` is giving me this error:
```
$ datalad publish .
[INFO   ] Publishing <Dataset path=/home/dp/testremote> to origin
[ERROR  ] failed to push to origin: master -> origin/master [remote rejected] (branch is currently checked out); pushed: ['[up to date]'] [publish(/home/dp/testremote)]
publish(error): /home/dp/testremote (dataset) [failed to push to origin: master -> origin/master [remote rejected] (branch is currently checked out); pushed: ['[up to date]']]
```

**Comment by kyleam** [comment]
> http://docs.datalad.org/en/latest/generated/man/datalad-push.html

"latest" appears to point to the tip of master, based on the revision reported at the bottom of the page (right now, 8ed1f5d6).  That commit is not contained in a release.

s/latest/stable/ in the URL, and you get the current release, 0.12.4.  That will 404 because ...

> Is `push` deprecated?

`push` is a new commit in master.  See #4206.

---

I'm not very familiar with our docs.datalad.org setup, but I think a few things are worth considering to make things clearer:

  * visiting a bare docs.datalad.org should land on the last release, not the development version

  * The "latest" label is unclear.  I would have guessed it was the latest release, but it's some point along the master branch.  So perhaps we should come up with a clearer label ("master" or "dev"?).

**Comment by kyleam** [comment]
> `publish(error): /home/dp/testremote (dataset) [failed to push to origin: master -> origin/master [remote rejected] (branch is currently checked out); pushed: ['[up to date]']]`

By default, Git will refuse a push into a non-bare repo that updates the checked out branch.  See the "receive.denyCurrentBranch" entry in `man git-config`.  Running `git config receive.denyCurrentBranch updateInstead` in the repo you are pushing to should resolve the issue.  (`datalad create-sibling` uses this value for the repos that it creates.)

**Comment by dorianps** [comment]
Thank you @kyleam, works now. Here is a quick example for anyone that wants to try this out (maybe this is something else for the FAQ/book (pinging @adswa , I can do more later, but need to get used to how to update the book).

```
### Server
datalad create -D 'testing for QC purpose' testremote
echo 'server file content' > serverfile.txt
datalad save
git config receive.denyCurrentBranch updateInstead

### Local
datalad install ssh://user@xx.xx.xx.xx:/PATH/TO/DATASET
cd testremote/
echo 'local file content' > desktopfile.txt
datalad save -m 'Saving new local file'
datalad publish --to origin  --transfer-data all
```

You should see `desktopfile.txt` in the server now.

**Comment by adswa** [comment]
Thanks @dorianps, any contribution would be very appreciated! Let me know if there is something I can assist you with, or if the Contributing page is unclear in some way.
I will probably put this into the [help section where this error message is mentioned already](http://handbook.datalad.org/en/latest/basics/101-135-help.html#output-produced-by-git). Thanks!
