### ISSUE TITLE
Add a way to query Datalad config parameters via CLI 

### ISSUE THREAD

**Issue by yfyf** [datalad/datalad#4359]
Either I couldn't find it, or at the moment there doesn't seem to be a way to query for datalad configuration parameters via the CLI?

E.g. I have a small bash script that installs plugins to the user's plugin dir. To resolve the dir I'm currently doing:

```
get_plugin_dir() {
    python3 -c "from datalad import cfg; print(cfg.obtain('datalad.locations.user-plugins'), end='')"
}

DATALAD_PLUGIN_DIR=$(get_plugin_dir)
```

It would be ideal to have something like

```
datalad cfg query datalad.locations.user-plugins
```

`datalad wtf` is somewhat helpful here, but it only prints config params which are actually set.

**Comment by kyleam** [comment]
This sounds like a nice addition.  Given that datalad looks at `.datalad/config` on top of the regular git config files, it's not trivial for a CLI caller to get the value with a `git config` call.

On top of querying, such a command may also be a nice spot to expose information/documentation about options that is stored in `datalad.interface.common_cfg`.

**Comment by kyleam** [comment]
gh-5370 reverted the addition of the new command.  Reopening.

**Comment by mih** [comment]
For the time being, there is an `x-configuration` command available from https://github.com/mih/datalad-mihextras (pip installable).

**Comment by mih** [comment]
I am closing this now. We have a command for this in an extension for almost a year now. At some point it will get into -core, but the bar is high, so there is no ETA. However, this issue has served its purpose. Thx for reporting it!
