### ISSUE TITLE
dataset.config fails to detect changed config file (seems to be master specific)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4363]
Origin: https://github.com/datalad/datalad-extensions/pull/7#issuecomment-606725942
```
(git)lena:~datalad/datalad-master[master]git
$> python -m nose -s -v datalad/metadata/tests/test_base.py:test_get_metadata_type
datalad.metadata.tests.test_base.test_get_metadata_type ... HERE0
HERE1:  /home/yoh/.tmp/datalad_temp_test_get_metadata_typet6b5ptfh
FAIL
Versions: appdirs=1.4.3 boto=2.49.0 cmd:7z=16.02 cmd:annex=7.20190819+git2-g908476a9b-1~ndall+1 cmd:bundled-git=2.20.1 cmd:git=2.20.1 cmd:system-git=2.25.1 cmd:system-ssh=8.1p1 exifread=2.1.2 git=3.0.7 gitdb=2.0.6 humanize=0.5.1 iso8601=0.1.12 keyring=18.0.1 keyrings.alt=3.2.0 msgpack=0.5.6 mutagen=1.40.0 requests=2.22.0 tqdm=4.30.0 wrapt=1.11.2
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-master/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git'

======================================================================
FAIL: datalad.metadata.tests.test_base.test_get_metadata_type
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 691, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/metadata/tests/test_base.py", line 92, in test_get_metadata_type
    assert_equal(get_metadata_type(ds), 'mamboschwambo')
AssertionError: [] != 'mamboschwambo'
```

Happens in `test_get_metadata_type` where  we append explicitly to `.datalad/config` file,

It actually seems to be not git/git-annex version specific -- happens with our stock neurodebian git annex 7.20190819+git2-g908476a9b-1~ndall+1, not sure how was not spotted...

somehow does not happen on maint - there config seems to be nicely reread... I have not spotted any relevant diff in `datalad/metadata/tests/test_base.py` or `datalad/config.py`...

May be some recent changes give ideas @kyleam @mih ? before we try to bisect or figure it out otherwise

**Comment by yarikoptic** [comment]
CS and binary search rule -- within a few seconds, bisect gave

a256a03b16b3f96ceb68f5fc635917b6a5d55309 is the first bad commit
... :

    RF: Rip out GitRepo.repo
    
    Defer import of GitPython and instantiation to the few pieces in
    DataLad's tests that need a GitPython repo instance to work.

**Comment by kyleam** [comment]
> bisect gave
> 
> a256a03 is the first bad commit

Hmm, I went off that commit and tried to figure out what could be going on, but didn't get anywhere yet.

Checking out the parent of that commit, I still see the failure.  Running the bisect on my end with `test_get_metadata_type` points to a different commit, upstream of yours: f635ace895 (RF: GitRepo.commit() based on WitlessRunner, 2020-02-07).  The `test_get_metadata_type` results I'm seeing locally appear consistent, though answer of your bisect does seem a bit more plausible.  I'll see if I can make sense of it with a closer look.

**Comment by yarikoptic** [comment]
I think generally it is an interaction of flyweight Repos and Datasets and our collection of decision making on "when to reload config" with continuous OPTs to trim some of those ;)
In particular in this test, it smells like we relied that calling `Dataset(...)` would trigger some kind of `reload`.  But it stopped happening (didn't check if by a256a03 or later, but that is the difference in logs between maint and master). #4364 goes most liberal way to resolve it -- I didn't want to make it at the Dataset() level because it is Repo.config which is a "common denominator" here - I do  not see `Dataset()` been special here.  I think it is just that in the code where we need to do a sequence of interactions with `.config`, similarly to `.repo` we should just bind to a local instance and work with it to avoid this constant `.reload()` which would trigger decision making based on time stamps.

**Comment by kyleam** [comment]
> I think generally it is an interaction of flyweight Repos and Datasets and our collection of decision making on "when to reload config" with continuous OPTs to trim some of those

That's almost too vague to be wrong :>  It's really unsatisfying to not actually be able to pinpoint a commit (at least on my end) that is causing it :/

**Comment by kyleam** [comment]
> It actually seems to be not git/git-annex version specific -- happens with our stock neurodebian git annex 7.20190819+git2-g908476a9b-1~ndall+1, not sure how was not spotted...

This mystery is also really unsatisfying.  Our master has been green, and I don't recall any one mentioning seeing this intermittently.  Really odd...

**Comment by yarikoptic** [comment]
> This mystery is also really unsatisfying. Our master has been green, and I don't recall any one mentioning seeing this intermittently. Really odd...

yeah -- that is what I also do not quite get really since it feels that we just lost some (deterministically invoked) `.reload()` but reality suggests that it is more like of some kind timing and/or race condition issue. dunno

**Comment by yarikoptic** [comment]
> That's almost too vague to be wrong :> It's really unsatisfying to not actually be able to pinpoint a commit (at least on my end) that is causing it :/

damn you -- I just thought that I am special

<details>
<summary>but I am not</summary> 

```shell
$> git co a256a03
HEAD is now at a256a03b1 RF: Rip out GitRepo.repo
(dev3) 1 12859.....................................:Tue 31 Mar 2020 09:28:39 PM EDT:.
(git)lena:~datalad/datalad-master[pull/origin/4172/head~9]git
$> for s in {1..10}; do python -m nose datalad/metadata/tests/test_base.py:test_get_metadata_type &>/dev/null && echo -n "$s ok, " || echo -n "$s fail, "; done
1 fail, 2 fail, 3 fail, 4 fail, 5 fail, 6 fail, 7 fail, 8 fail, 9 fail, 10 fail, %                               (dev3) 1 12860.....................................:Tue 31 Mar 2020 09:28:55 PM EDT:.
(git)lena:~datalad/datalad-master[pull/origin/4172/head~9]git
$> git co a256a03^
Previous HEAD position was a256a03b1 RF: Rip out GitRepo.repo
HEAD is now at 8a174f5cf Merge pull request #4237 from mih/bf-annexjson
(dev3) 1 12861.....................................:Tue 31 Mar 2020 09:28:59 PM EDT:.
(git)lena:~datalad/datalad-master[pull/origin/4245/head~1]git
$> for s in {1..10}; do python -m nose datalad/metadata/tests/test_base.py:test_get_metadata_type &>/dev/null && echo -n "$s ok, " || echo -n "$s fail, "; done
1 fail, 2 fail, 3 fail, 4 fail, 5 fail, 6 fail, 7 fail, 8 fail, 9 fail, 10 fail, %      
```
</details>
i.e. it does fail for me even in 8a174f5cf67c8917392de7001cc0e412d93a0b0f ... so I reran bisect on something more stringent: `git bisect run bash -c '( set -e; for s in {1..3}; do python -m nose datalad/metadata/tests/test_base.py:test_get_metadata_type &>/dev/null && echo -n "$s, "; done; )'` and ended up with a new candidate: f635ace895856b75b2d057e7884e71fa9460b8ff  which also makes little to no immediate sense... rerunning with doing 10 runs but I am afraid it is all useless, and  also got stuck on 
```
Bisecting: 35 revisions left to test after this (roughly 5 steps)
[373fe1ae3b947bbf5b273cabb17b0a272368ee85] ENH: assert_in_results: Make failure message more readable
running bash -c ( set -e; for s in {1..10}; do python -m nose datalad/metadata/tests/test_base.py:test_get_metadata_type &>/dev/null && echo -n "$s, "; done; )
1, 
```
heh heh

**Comment by yarikoptic** [comment]
btw -- `bisect` seems to screw up workdir setup somehow, can't get back to master -- says that already checked out... heh heh

**Comment by yarikoptic** [comment]
forgot to remove "Fixes" from that PR. although indeed #4365 is fixing up the test, I think this issue is more general, thus better stay open until resolved more definitely (some more discussion is ATM in #4364)

**Comment by yarikoptic** [comment]
I think at large this is a duplicate of unclear "promise" we have over config life cycle.  So let's consider it a duplicate  of https://github.com/datalad/datalad/issues/5824 and let this particular one RiP
