### ISSUE TITLE
Should we harmonize our (perspective) config with git or with Python?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#437]
So far I have plugged SafeConfigParserWithIncludes which is based on stock Python's ConfigParser and originally hacked (by me) for fail2ban a decade ago to allow explicitly including other files using `[INCLUDES]` section.  I have also started to use ':' in section names to define some kind of hierarchical (atm just `section:subsection`) relation to group some sections together.  We also allow for option keys within those sections to have spaces in them.  As such, although visually very similar, it is different from ad-hoc git's config which I think doesn't bother allowing spaces in the option key names, and allows for subsections specification via `[section "subsection"]`.  That is how we get usually used `[branch "master"]` or `[remote "origin"]` (sub)sections.  Python's parser can't handle such section names with spaces btw.

Q1:  So I wondered -- should we go Python + ad-hoc or Git ad-hoc way?  If git way -- we could use I guess GitPython for reading (and may be even for writing):
```ipython
In [1]: from git.config import GitConfigParser
In [3]: config = GitConfigParser('.git/config')
In [4]: config.read()
In [6]: config.get_value('branch "master"', 'remote')
Out[6]: u'origin'
*In [7]: config.get_value('branch', 'remote')
---------------------------------------------------------------------------
NoSectionError 
```

Q2: I don't think git does it that way, but I think we should (as we already do) enable overrides for those variables defined in config files, via environment variables.  ATM, since there were no notion of 'subsection', we just split out section name right after leading `DATALAD_`, and use the rest for the key (also we magically assume section GENERAL if there is no other `_` in the suffix).  So depending on the choice of the config format, how could we uniformly point to subsections assuming that some sections?
In case of git format, it might be actually simple -- since it seems to not allow having `_` as well anywhere in the names.  So we could easily judge by number of underscores, having syntax like `DATALAD_[<SECTION>[_<SUBSECTION>]]_KEY`.

Q3: eventually I guess the ConfigManager should also be interfaced into 'cmdline interface' so we could, similar to git/annex specify those arbitrary options in the command line (e.g. -c datalad.section.subsection=value) while even possibly allowing for passing 'annex.' and 'git.' options into Git/AnnexRepo classes set of default options.  Or...?

What do you think @datalad/developers ? ;)

**Comment by bpoldrack** [comment]
I think it is a good idea to allow for a similar way of a config command as git has and address items the same way. Therefore I'd vote for the same config file format as well. As a tool on top of git/annex, datalad should be usable and configurable the same way. So: 
Q1: git way (probably using gitpython config reader/writer)
Q3: Yes, think so to. `-c` option like git, also allowing for passing git and annex options. And probably a `datalad config` command similar to git.
Q2: I'm fine with your approach in case of git format.

**Comment by hanke** [comment]
Q1: Git
Q2: Let's stay close to git also. Semantic units in a variable name separated by dots, and '_' used to replace them for envvars.
Q3: what Ben said. ;-)

**Comment by hanke** [comment]
In terms of files to read: We should do the same as git-annex:

1. .git/config for repo- and clone-specific config, not intended to be propagated
2. .gitattributes for per-path config stuff that should go with the dataset when published.

Even for a user-config the main git config files makes most sense.

We may need to add a .datalad/config file in a dataset for other publishable configuration items -- if we can come up with necessary ones.

Prefix would be `datalad`.

**Comment by yarikoptic** [comment]
>    In terms of files to read: We should do the same as git-annex:
>     1. .git/config for repo- and clone-specific config, not intended to be
>        propagated
>     2. .gitattributes for per-path config stuff that should go with the
>        dataset when published.
>    Even for a user-config the main git config files makes most sense.
>    We may need to add a .datalad/config file in a dataset for other
>    publishable configuration items -- if we can come up with necessary ones.

yes -- we would need some custom location as well, outside of .git/,
since some configuration/settings might not be appropriate for
.gitattributes but need to be committed.  E.g. configuration or entire
pipelines for crawling, and status files.  See e.g. how it is now

http://datasets.datalad.org/openfmri/ds000001/.datalad/crawl/

**Comment by yarikoptic** [comment]
and https://github.com/datalad/ratholeradio-archive/tree/master/.datalad/crawl/pipelines  where entire .py crawling pipeline is provided  (crawl assumes path `.datalad/crawl/pipelines`) to look for a pipeline ATM.

**Comment by yarikoptic** [comment]
Just a note TODO:  check if git config format allows multiline entries as we use already somewhat in some config files.... might be somewhat of a blow

**Comment by hanke** [comment]
@yarikoptic git config format does not allow for multiline values.

**Comment by hanke** [comment]
@yarikoptic However, escaped newlines (`\n`) are supported and are correctly expanded via `git config` calls.

**Comment by hanke** [comment]
@yarikoptic git config files support inclusion of other files. Quote from manpage:

````
      You can include one config file from another by setting the
       special include.path variable to the name of the file to be
       included. The included file is expanded immediately, as if its
       contents had been found at the location of the include directive.
       If the value of the include.path variable is a relative path, the
       path is considered to be relative to the configuration file in
       which the include directive was found. The value of include.path
       is subject to tilde expansion: ~/ is expanded to the value of
       $HOME, and ~user/ to the specified user’s home directory. See
       below for examples.

           [include]
                   path = /path/to/foo.inc ; include by absolute path
                   path = foo ; expand "foo" relative to the current file
                   path = ~/foo ; expand "foo" in your $HOME directory

````

**Comment by yarikoptic** [comment]
On Tue, 02 Aug 2016, Michael Hanke wrote:
>    @yarikoptic git config files support inclusion of other files. Quote from
>    manpage:

nice... one feature in python configs I have used before but no longer (I
think) is the string interpolations.  but once again I don't think we would
need it.  as for new lines -- I rely on that feature e.g. to separate fields
specification for authentication forms, and multiple regexes for urls see e.g.
https://github.com/datalad/datalad/blob/master/datalad/downloaders/configs/crcns.cfg
sure thing could be worked around somehow with git config, but not yet sure
what could be the best way (dedicated uniqely named section with all the fields
or what)

**Comment by hanke** [comment]
Using `\n` as field separator would work, just not without escapes. It would be
````
html_form_fields = username={user}\n\
                   password={password}\n\
                   submit=Login\n\
                   fn=alm-1/filelist.txt
````

**Comment by joeyh** [comment]
Michael Hanke wrote:
> @yarikoptic git config format does not allow for multiline values.

Actually...

	joey@darkstar:~/tmp/r>git config foo.bar line1
	joey@darkstar:~/tmp/r>git config --add foo.bar line2
	joey@darkstar:~/tmp/r>git config --get-all foo.bar
	line1
	line2

-- 
see shy jo

**Comment by hanke** [comment]
@joeyh Indeed, thanks!

````
git config -f sometest.cfg --add datalad.creds username=some
git config -f sometest.cfg --add datalad.creds passwd=password1
cat sometest.cfg
[datalad]
	creds = username=some
	creds = passwd=password1
````

**Comment by mih** [comment]
We went for Git's config and the implementation is now in master (from #744)
