### ISSUE TITLE
heads down: test_binary_data_local (or git annex get) fails

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4371]
spotted in datalad-externals master run https://github.com/datalad/datalad-extensions/runs/552489412?check_suite_focus=true#step:9:2510:
```
Versions: appdirs=1.4.3 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20200330+git11-gad483f5e2-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.26.0 cmd:system-ssh=7.6p1 humanize=2.2.0 iso8601=0.1.12 keyring=21.2.0 keyrings.alt=3.4.0 msgpack=1.0.0 patoolib=1.12 requests=2.23.0 tqdm=4.44.1 wrapt=1.12.1
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: LANG='C' PATH='/opt/hostedtoolcache/Python/3.7.6/x64/bin:/opt/hostedtoolcache/Python/3.7.6/x64:/usr/share/rust/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/runner/.dotnet/tools:/home/runner/.config/composer/vendor/bin' LC_CTYPE='C.UTF-8' GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git'
ERROR: datalad.distributed.tests.test_ria_data_transfer.test_binary_data_local
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/distributed/tests/ria_utils.py", line 95, in newfunc
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 186, in newfunc
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 691, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 691, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/distributed/tests/test_ria_data_transfer.py", line 41, in test_binary_data_local
    ds.get(file)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/distribution/dataset.py", line 498, in apply_func
    return f(**kwargs)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 494, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 482, in return_func
    results = list(results)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 469, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'type': 'file', 'refds': '/tmp/datalad_temp_test_binary_data_localf24b3bak', 'status': 'error', 'path': '/tmp/datalad_temp_test_binary_data_localf24b3bak/code/stimulus/visualarea_localizer/img/body01.png', 'action': 'get', 'annexkey': 'MD5E-s40207--86c5c063acf1dd9d7c9101d451a63334.png', 'message': 'not available; Try making some of these repositories available:; \t2f51364e-815a-4ad9-b380-617c682b1680 -- mddatasrc;  \t40809380-c618-4801-bb8d-81320474c9da -- studyforrest phase2 original source repository; ; (Note that these git remotes have annex-ignore set: mddatasrc origin)'}]
```

but build which followed a few hours later succeeded.

**Comment by kyleam** [comment]
@yarikoptic The -extensions error and your local one look like different errors.

The local error you posted matches the one I see due to the git-annex `GETCONFIG` change repo Michael described at gh-4259.  However, that change was introduced (7.20200202.7) and reverted (8.20200309, 6a9147192) _after_ the 7.20190819+git2-g908476a9b, so I guess that's not it.

`test_binary_data_local` passes for me locally (with datalad's 507353d34) when I use a git-annex built from 908476a9b (your local version) and built from ad483f5e2 (the version reported in the -extensions log).

Anyway, I suppose none of that is very helpful, but it seems worth pointing out that (1) the errors aren't the same and (2) the test isn't unconditionally failing with the git-annex versions in question.

**Comment by yarikoptic** [comment]
> The local error you posted matches the one I see ...

oh right -- I got misguided seeing the same "IncompleteResultError" I guess.  So locally it is due to " Cannot run git-annex-remote-ora -- It is not installed in PATH..."  So it was my fault -- now that I reran `pip install -e .` that error is gone!

**Comment by yarikoptic** [comment]
and I have failed to reproduce on 100 runs using git annex we have in neurodebian devel  (8.20200309+git133-gc29943f40-1~ndall+1) :-/  using 8.20200330+git28-g7ebc11877-1~ndall+1 (from that failed datalad-extensions run) reproduced on 52nd attempt.  So it is indeed just a very flaky case

**Comment by bpoldrack** [comment]
Well, in the opening post `git-annex-get` fails with "make some of these repositories available", suggesting just the kind of currently usual connection issues to me.

**Comment by kyleam** [comment]
Perhaps this is the same underlying issue as gh-3653, though the exact message is slightly different (in particular, this one includes a bit about annex-ignore).

**Comment by bpoldrack** [comment]
I suspect it's the same issue as https://github.com/psychoinformatics-de/datalad-hirni/issues/158 (see also https://github.com/psychoinformatics-de/datalad-hirni/pull/159, where the same data source sometimes seems to not work leading to a `get` failing with `Authentication failed`, while there shouldn't be any authentication required and the very same get on the very same data with the very same test code succeeded just a minute before. Seems to me there's something flaky about that server on our site (Jülich).

However, for that `test_binary_data` test it doesn't matter at all what data it's using. So I will just change it to get something from github instead.
