### ISSUE TITLE
datalad clone uncoditionally set submodule.*.branch when adding submodules

### ISSUE THREAD

**Issue by yfyf** [datalad/datalad#4373]
#### What is the problem?

It seems that when you `datalad clone` a submodule, it always sets the `submodule.*.branch` to the parent (or specified) dataset's currently checked out branch.

This is not always desired, for example if you are on a feature/experiment branch in the parent project, then you probably don't want to set it. Is this intended? It would be amazing to have a flag to disable this in `clone`.

#### What steps will reproduce the problem?

```
datalad create parent
cd parent
git checkout -b feature-branch
datalad clone -d . some-other-dataset
cat .gitmodules
```

`.gitmodules` will now contain `branch = feature-branch` for the `some-other-dataset` dataset and there is no flag to disable this functionality.

#### What version of DataLad are you using (run `datalad --version`)?

0.12.4

**Comment by kyleam** [comment]
Thanks for the report.

I think this can be viewed as a regression introduced by 0.12.0, specifically by 2fda83e2ca (ENH: Record the active branch of a subdataset in the parent, 2019-10-20).  It has [come up tangentially][0] in a pending PR.  As I mentioned there, I think the intent was to record the current branch _of the sub-repository_ when saving in the parent.

[0]: https://github.com/datalad/datalad/pull/4275#discussion_r390596089

**Comment by yfyf** [comment]
Thanks, it all makes sense then.
