### ISSUE TITLE
Using headers with download_url

### ISSUE THREAD

**Issue by joeyzhou98** [datalad/datalad#4376]
#### What is the problem?
I am using the Datalad Python API to script a crawler which downloads files from different platforms. I am trying to download private datasets/files using `datalad.api.download_url`, however, the [server](https://developer.osf.io/#tag/Authentication) serving the private files only allows downloads when authenticated by passing the token via the header of the REST call. Is there a way to pass a token via header using Datalad when using `download_url`?
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.12.2
Ubuntu/18.04/bionic

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Yes I am using Datalad regularly to modulate/maintain different repositories containing datasets

**Comment by yarikoptic** [comment]
BTW, you might like to use `datalad addurls` or https://github.com/datalad/datalad-crawler/ extension for crawling.

Re "token authentication" - we support authentication using "Bearer" token.  you would just need to configure a new downloader provider/credentials... if service returned 403 when trying to access without proper token, I think datalad should have given you a dialog to enter a new provider.
Unfortunately we have not exposed that interface yet via convenient API call, but here is how you could trigger that "manually":
```
(git)lena:~datalad/datalad[tags/0.12.2^0]git
$> python -c 'from datalad.downloaders.providers import Providers; Providers().enter_new(url="http://my.domain.com/api/blah")'
New provider name
Unique name to identify 'provider' for http://my.domain.com/api/blah [my.domain.com]: 

New provider regular expression
A (Python) regular expression to specify for which URLs this provider should be used [http://my\.domain\.com/api/blah]: http://my\.domain\.com/api/.*

Authentication type
What authentication type to use (choices: aws-s3, bearer_token, html_form, http_auth, http_basic_auth, http_digest_auth, loris-token, nda-s3, none, xnat): bearer_token

Credential
What type of credential should be used? (choices: aws-s3, loris-token, nda-s3, [token], user_password): 

Save provider configuration file
Following configuration will be written to /home/yoh/.config/datalad/providers/my.domain.com.cfg:
# Provider configuration file created to initially access
# http://my.domain.com/api/blah

[provider:my.domain.com]
url_re = http://my\.domain\.com/api/.*
authentication_type = bearer_token
# Note that you might need to specify additional fields specific to the
# authenticator.  Fow now "look into the docs/source" of <class 'datalad.downloaders.http.HTTPBearerTokenAuthenticator'>
# bearer_token_
credential = my.domain.com

[credential:my.domain.com]
# If known, specify URL or email to how/where to request credentials
# url = ???
type = token
 (choices: [yes], no): yes
```
and indeed that file was created:

```
$> cat /home/yoh/.config/datalad/providers/my.domain.com.cfg                                                                  
# Provider configuration file created to initially access
# http://my.domain.com/api/blah

[provider:my.domain.com]
url_re = http://my\.domain\.com/api/.*
authentication_type = bearer_token
# Note that you might need to specify additional fields specific to the
# authenticator.  Fow now "look into the docs/source" of <class 'datalad.downloaders.http.HTTPBearerTokenAuthenticator'>
# bearer_token_
credential = my.domain.com

[credential:my.domain.com]
# If known, specify URL or email to how/where to request credentials
# url = ???
type = token
```
so you could improve it further.

**Comment by mih** [comment]
There is a good chance that this issue has served its purpose. Feel free to reopen, if that assessment is wrong.
