### ISSUE TITLE
promote `-c datalad.search.index-MODE-documenttype` into `search --type [datasets|files|all]`

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4381]
#### What is the problem?

- this is an often to use "switch", but config variable name is not trivial to remember/type
- there is a `--mode` switch already, switching the mode requires adjusting this config name

e.g., compare
```
datalad -c datalad.search.index-egrep-documenttype=all search path:.*T1w.*
```
to
```
datalad search --type=all path:.*T1w.*
```
?

So  I think it would be great to have an easy to find/use option to `search` to specify what to search among.  It would override `index-MODE-documenttype` if specified.

How should be named? I feel that `documenttype` is too "whoosh-inspired" (`document` generally is an alien term to datalad, and I would not really call "dataset" a "document") and unnecessarily long.  I do not quite like `--type` since too generic.  Other possible choices: `--what`, `--target`, `--level`, ...?

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
