### ISSUE TITLE
FOI: flaky azure on github actions

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4384]
issues filed within github (not by me) in the past week:
- https://github.community/t5/GitHub-Actions/Install-dependencies-in-Ubuntu-flakes-several-times-a-wekk/td-p/51785
- https://github.com/actions/virtual-environments/issues/675

one message there recommends

As a workaround, you can probably use [apt-spy2](https://github.com/lagged/apt-spy2) to use the closest *available* mirror before running apt-get update. 

I personally never used it, but it could be neat.

another quick workaround (but might brake in the future):

```
sudo sed -i 's/azure\.//' /etc/apt/sources.list
sudo apt-get update
```

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
