### ISSUE TITLE
random crashes on datalad.create and datalad.save in Python3

### ISSUE THREAD

**Issue by jonamfischer** [datalad/datalad#4385]
#### What is the problem?
When performing multiple datalad commands in python within a specific timeframe (until now it seems to be 3-4 hours) the first one of each would result in an error stopping the datalad command
#### What steps will reproduce the problem?
We reproduced this by sending data to our service from different clients which then would each first start a datalad dataset creation and then a 'datalad save' whenever a request has been handled. The first request of each client would always fail at the respective datalad command.
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.12.1 for Python3
#### Is there anything else that would be useful to know in this context?
Log-Output:
File "/usr/lib/python3.7/pathlib.py", line 1251, in mkdir
self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/.cache/datalad/sockets'
raceback (most recent call last):
File "/usr/lib/python3.7/pathlib.py", line 1251, in mkdir
self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/.cache/datalad'
...
PermissionError: [Errno 13] Permission denied: '/var/www/.cache'

BTW: Using just the command line for all datalad-related tasks works.

**Comment by yarikoptic** [comment]
User's HOME is read only `/var/www/`?

**Comment by jonamfischer** [comment]
No, this directory shouldn't even be accessed. And given the fact that all following, identical operations, succeed I can't see a pattern there. I tried using a shell script to handle those datalad operations and it works perfectly fine. So using the command line works, but using the python api would cause described error.

**Comment by bpoldrack** [comment]
>  No, this directory shouldn't even be accessed.

This is suggesting to me that something goes wrong with config variable `datalad.locations.cache`, which defaults to `appdirs.AppDirs("datalad", "datalad.org").user_cache_dir`. So, if you didn't set this somewhere, we need to look into what might cause `appdirs` to report `/var/www/.cache/` for it and how this can possibly differ from CLI and python API.

Could you try to confirm that this actually differs by running
`python -c "import appdirs; print(appdirs.AppDirs('datalad', 'datalad.org').user_cache_dir)"` from command line and then have that same output from the very python context you are using, @jonamfischer ?

**Comment by jonamfischer** [comment]
@bpoldrack since the service is a WSGI script run by the user www-data, which is standard for apache configurations, /var/www/.cache is what I get when the service executes this command. So this is causing the error, but weirdly only for the first execution of a datalad command. If I retry my request, it works no matter whether I do it 2, 5 or 10 times. That's why I switched to a cron job using a zsh-Script. At the same time I now only have one place for datalad ops and not multiple python-files, so all in all a win. But still, this error bugs me (pardon the pun) ;-)

**Comment by bpoldrack** [comment]
> But still, this error bugs me (pardon the pun) ;-)

Pardened. ;-)
Me as well, although merely academically for now. Would be good to figure it out.

One other idea: Can you check what are the actual permissions for `/var/www/.cache` at the point where it then works? That is because we try setting it to 700. Maybe that is what fails, but the directory is created and once it's there we never check again.

**Comment by yarikoptic** [comment]
> datalad 0.12.1 for Python3

world was square back then -- we are all rounded up now and there should be no "random crashes" -- everything is very well planned in datalad land now.  But if still happens, feel welcome to reopen @jonamfischer
