### ISSUE TITLE
[WARNING] ... Directory symlinks in the paths will be resolved 

### ISSUE THREAD

**Issue by soichih** [datalad/datalad#4387]
This is not a problem, but I am seeing the following warning message when I run `datalad get`.

```
[WARNING] realpath of PWD=/mnt/wrangler/dev1/5e8e84ae5b188b245b4d34c9/5e8e84ae5b188b245b4d34ca is /mnt/wrangler/dev1/5e8e84ae5b188b245b4d34c9/5e8e84ae5b188b245b4d34ca whenever os.getcwd()=/mnt/datalad/datasets.datalad.org/adhd200. From now on will be returning os.getcwd(). Directory symlinks in the paths will be resolved 
```

I don't really know what this message means, and I was wondering if someone could tell me what it means and if I am doing something wrong, how to fix it.

I am using the following version of datalad

```
brlife@wrangler2:~/.ssh$ datalad --version
datalad 0.12.4
brlife@wrangler2:~/.ssh$ python3 --version
Python 3.6.9
```

I am running something like following to run datalad get - the script is located in  `/mnt/wrangler/dev1/5e8e84ae5b188b245b4d34c9/5e8e84ae5b188b245b4d34ca`

```
import subprocess
cwd="/mnt/datalad/datasets.datalad.org/adhd200"
src="RawDataBIDS/Brown/sub-0026001/ses-1/anat/sub-0026001_ses-1_run-1_T1w.nii.gz"
subprocess.call(["datalad", "get", src], cwd=cwd)
```

I am setting cwd to the root of the datalad dataset, then requesting datalad to get the T1w.nii.gz located under `src` path. This script that I am running is in another location (under /mnt/wrangler/dev1..), and I am guessing datalad doesnt' like that the PWD environment parameter is set differently from what I am passing to cwd?

**Comment by yarikoptic** [comment]
short answer: you are safe! ;)
In datalad we often report full path.  In case if a current directory has a symlink somewhere in its path, it is only the PWD environment variable (AFAIK) which would reflect such path. `getcwd()` would return resolved.  So in datalad, if we detect that PWD and getcwd() diverge - we announce that we no longer care about PWD -- and that is what that message does.

In your cases it happens before your child process is ran in another directory, while PWD is still inherited from outside shell.
