### ISSUE TITLE
search: provide a better error when regex is incorrect

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4393]
Although it is quite easy to grasp what went wrong familiar with python 

```shell
$> datalad search path:*T1w.nii.gz
[ERROR  ] nothing to repeat at position 0 [sre_parse.py:_parse:651] (error)
```
I think a better error would be
```
[ERROR ] regular expression '*T1w.nii.gz' is incorrect:  nothing to repeat at position 0 [search.py:...] (error)
```
which would become especially useful in case of multiple regular expressions and more tricky ones

**Comment by adswa** [comment]
I think your merged PR that fixed this for some reason did not automatically close this issue? I will close it, please reopen if I'm mistaken here. PS: I like the improved error message :)

**Comment by kyleam** [comment]
Thanks @adswa 

> I think your merged PR that fixed this for some reason did not automatically close this issue?

When a PR is based off of a branch other than the default branch of the repo, the closes/fixes cookie needs to be in a commit message, not just the PR description.

**Comment by adswa** [comment]
Thank you for sharing, I did not know this :)
