### ISSUE TITLE
get_local_file_url() broken

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#440]
````
In [1]: from datalad.utils import get_local_file_url
In [3]: import urlparse
In [4]: urlparse.urlparse(get_local_file_url('some'))
Out[4]: ParseResult(scheme='file', netloc='some', path='', params='', query='', fragment='')
````

This should likely call abspath() first. Or it is the special handling of non-Windows platforms that is wrong by using `file://` and not `file:///` as I assume it should be.

Anyway, we are not using this function anywhere in the code. Best fix seems to be removal!?

**Comment by bpoldrack** [comment]
We use it for tests.

What do you think is broken here? The file:// is correct as far as I'm
aware. So, urlparse gets the scheme right. But may be you are right and it
should always use an absolutepath, which then gives the third slash on
non-windows.

2016-05-20 17:23 GMT+02:00 Michael Hanke <notifications@github.com>:

**Comment by bpoldrack** [comment]
Probably nobody used it with a relative path before ;)

2016-05-20 17:37 GMT+02:00 Benjamin Poldrack <benjaminpoldrack@gmail.com>:

**Comment by hanke** [comment]
URL is

file://HOST/PATH

this is not a platform thing.

**Comment by bpoldrack** [comment]
Theoretically, yes. There is no HOST in case of the file scheme, but the
path should start with a slash, since it should indeed be an absolute path.
BUT: get an absolute path on windows and will not start with a slash. So,
if we want a  file:// - URL on windows, we need to add the third slash and
append the path.

2016-05-20 17:39 GMT+02:00 Michael Hanke <notifications@github.com>:

**Comment by bpoldrack** [comment]
In other words: within file://HOST/PATH, HOST is empty. Everything else is
platform dependent converting of the path.

2016-05-20 17:43 GMT+02:00 Benjamin Poldrack <benjaminpoldrack@gmail.com>:

**Comment by hanke** [comment]
No, you got it backwards. There is always a HOST. On Linux it also needs three slashes, if there is no HOST.

**Comment by bpoldrack** [comment]
Yes, if you remove HOST from your pattern, then there are always three
slashes. The differnece is, that on linux an absolute path already starts
with a slash. On windows it doesn't. So the difference is not, what the URL
looks like, but how to build it from what you have.

2016-05-20 17:47 GMT+02:00 Michael Hanke <notifications@github.com>:

**Comment by hanke** [comment]
Well, the function is broken. It yields invalid URLs on Linux, unless I make sure the path is absolute. That was the sole point.

**Comment by hanke** [comment]
And in order to avoid this, we should use urlparse to build URLs.

**Comment by bpoldrack** [comment]
Agree. Needs to be fixed.

**Comment by hanke** [comment]
Relevant info (also for Windows): https://en.wikipedia.org/wiki/File_URI_scheme

**Comment by yarikoptic** [comment]
for now I think it would be sufficient just to use absfile if non-abs path provided... later above url could be of good use while prepping urls for windows.  Since @bpoldrack is already assigned, I will not touch this issue for a quick PR
