### ISSUE TITLE
Concurrency handling, even a little

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4401]
When multiple datalad activities target a single dataset things can fail quickly and seemingly at random. I think we should invest (minimal) effort to not impose this on users completely. Example of a creating a subdataset while something else is modifying a dataset:

```
[INFO   ] Creating a new annex repo at /tmp/top/a36 
[INFO   ] Scanning for unlocked files (this may take some time) 
CommandError: 'git commit -m '[DATALAD] Recorded changes' --' failed with exitcode 128 under /tmp/top
fatal: Unable to create '/tmp/top/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

There is no reason to fail at the commit stage. Either fail at the very beginning, or place our own lock for write operations that coordinate some level of concurrent access. E.g. when `save()` starts and sees a lock it could simply wait until it can acquire the lock and only then perform its dataset state assessment.

I believe that if we implement a meaningful concurrency protection for the core commands `save()` (first and foremost), `create()`, and `run()`, we would already get a long way.

**Comment by yarikoptic** [comment]
IMHO we should implement cross-process/hosts locking at the level of a repo, so write operations (see discussion in #5070 ) would wait (and possibly time out after some configurable) to acquire the lock to proceed

**Comment by mih** [comment]
Replaced by #6593
