### ISSUE TITLE
Investigate call_git*(["annex", ...]) use

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#4406]
It occurred to me while working on gh-4405 that any place where we call git-annex via one of the `call_git*` methods, rather than going through `_run_annex_command`, is likely problematic because that won't set the options (inlcuding `annex.alwayscommit`) that `_run_annex_command` takes care of setting.  Quickly grepping, there are a few spots.

**Comment by kyleam** [comment]
Here's a list of cases I've found in master (66c3a1df6) that might need to be considered.  Most of these are `call_git` calls, but I looked for anything that didn't go through `_run_annex_command`.  This list almost certainly both misses some and has false positives.  Plus, many of these instances, especially in tests, may not really matter, though if we're going to do a tree-wide cleanup, it seems worth trying to get everything.

With @mih's gh-5163 (`call_annex`) underway, it might make sense to cover many of those in that PR (or at least right after it lands).

- [ ] datalad/core/distributed/push.py
      `cmd = ['git', 'annex', 'copy', '--batch', '-z', '--to', target,`
- [ ] datalad/core/distributed/tests/test_clone.py
      `Runner(cwd=d.path).run(['git', 'annex', 'enableremote',`
      `runner.run(['git', 'annex', 'init'], cwd=bare_path)`
- [ ] datalad/core/distributed/tests/test_push.py
      `target.call_git(['annex', 'init'])`
      `ds.repo.call_git(['annex', 'sync'])`
      `ds.repo.call_git(['annex', 'sync', '--cleanup'])`
      `target_subnoannex.call_git(['annex', 'init'])`
- [ ] datalad/core/local/tests/test_create.py
      `cmd = ['git', 'annex', 'info']`
- [ ] datalad/customremotes/archives.py
      `["git", "annex", "get", "--json", "--json-progress", "--key", akey],`
- [ ] datalad/customremotes/base.py
      `out = self.repo.call_git(['git', 'annex', 'contentlocation', key])`
- [ ] datalad/customremotes/tests/test_archives.py
      `['git', 'annex', 'drop', '--', fn_in_archive_obscure],`
      `['git', 'annex', 'get', '--', fn_in_archive_obscure],`
- [ ] datalad/distributed/create_sibling_ria.py
      `'annex',`
      `ds.repo.call_git(['annex', trust_level, srname])`
- [ ] datalad/distributed/tests/test_ria_basics.py
      `['annex', 'enableremote', 'ria-remote'] + common_init_opts +`
      `ds.repo.call_git(['annex', 'enableremote', 'ria-remote'] +`
      `['git', 'annex', 'testremote', 'store']`
      `ds.repo.call_git(['annex', 'move', str(file), '--to', 'store'])`
      `ds.repo.call_git(['annex', 'get', str(file), '--from', 'store'])`
      `ds.repo.call_git(['annex', 'move', '--all', '--from=bare-git'])`
- [ ] datalad/distributed/tests/test_ria_git_remote.py
      `ds.repo.call_git(['annex', 'move', 'one.txt', '--from', 'bare-git'])`
      `ds.repo.call_git(['annex', 'move', 'one.txt', '--to', 'bare-git'])`
- [ ] datalad/distribution/tests/test_update.py
      `repo.call_git(["annex", "upgrade"])`
- [ ] datalad/distribution/update.py
      `repo.call_git(["annex", "merge"])`
- [ ] datalad/interface/tests/test_add_archive_content.py
      `repo._annex_custom_command([], ["git", "annex", "drop", "--all"])`
- [ ] datalad/interface/tests/test_unlock.py
      `ds.repo.call_git(['annex', 'lock'], files=['test-annex.dat'])`
      `ds.repo.call_git(['annex', 'lock'], files=['test-annex.dat'])`
- [ ] datalad/local/copy_file.py
      `dest_key = dest_repo.call_git_oneline(['annex', 'calckey', str_src])`
- [ ] datalad/plugin/wtf.py
      `['git', 'annex', 'version'], protocol=StdOutErrCapture)`
- [ ] datalad/support/annexrepo.py
      `["git", "annex", "version"],`
      `return self._annex_custom_command([], ["git", "annex", "dead", name])`
      `cmd = ['annex', 'sync']`
- [ ] datalad/support/external_versions.py
      `['git', 'annex', 'version'],`
- [ ] datalad/support/tests/test_annexrepo.py
      `['git', 'annex', 'find', '.', '--json'],`
      `['git', 'annex', 'find', '.', 'error', '--json'],`
- [ ] datalad/tests/test_cmd.py
      `failing_cmd = ['git', 'annex', 'add', 'notexistent.dat']`

**Comment by mih** [comment]
Wonderful! Thx @kyleam

**Comment by mih** [comment]
#5163 should now address all true-positives.
