### ISSUE TITLE
create-sibling-ria crashes

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4415]
On the HCP dataset (full checkout)
```
% datalad create-sibling-ria \
  -d . \
  --no-storage-sibling \
  -s some \
  --shared group \
  --group BnB \
  --trust-level trust \
  ria+file:///ds/hcp/srv --existing skip -r  
```

fails with

```
[ERROR  ] CommandError: 'git init --bare '--shared= --shared='"'"'group'"'"''' failed with exitcode 128 under /ds/hcp/srv/2b9/8f794-2b98-11ea-b613-002590496000 [err: 'fatal: bad numeric config value ' --shared='group'' for 'arg': invalid unit'] [cmd.py:run:930] 
CommandError: 'git init --bare '--shared= --shared='"'"'group'"'"''' failed with exitcode 128 under /ds/hcp/srv/2b9/8f794-2b98-11ea-b613-002590496000
fatal: bad numeric config value ' --shared='group'' for 'arg': invalid unit
```

this looks all wrong.

On a rerun with `--dbg` it crashes with

```
FileExistsError: [Errno 17] File exists: '/ds/hcp/srv/2b9/8f794-2b98-11ea-b613-002590496000'
> /home/mih/code/datalad/datalad/distributed/create_sibling_ria.py(520)_create_sibling_ria()
-> repo_path.mkdir(parents=True)
(Pdb) l
515             #       special remote's RemoteIO classes without
516             #       talking via annex
517             if ssh_host:
518                 ssh('mkdir -p {}'.format(quote_cmdlinearg(str(repo_path))))
519             else:
520  ->             repo_path.mkdir(parents=True)
521  
522         # 2. create a bare repository in-store:
523  
524         lgr.debug("init bare repository")
525         # TODO: we should prob. check whether it's there already. How?
```

Maybe this is a separate bug.

Edit: Indeed confirmed to be a separate issue. The original issue replicates, once the store is wipe out.

**Comment by bpoldrack** [comment]
The first one looks to me like `GitRepo`'s init call is buggy rather than anything being wrong with `create-sibling-ria`. The quoting of `group` looks suspicious.

Second one: Note to myself: Call uses `--existing skip`. We shouldn't get there.

**Comment by bpoldrack** [comment]
Another note: `'--shared= --shared='"'"'group'"'"'''` ... we might have some kind of double use of `to_options` or something like that. Double creating the command line option.

**Comment by mih** [comment]
Correct. The command that is actually issued is:
```
(Pdb) print(cmd)
['git', 'init', '--bare', "--shared= --shared='group'"]
```

but in `_create_empty_repo`

```
(Pdb) kwargs
{'bare': True, 'shared': " --shared='group'"}
```

which comes from

```
> /home/mih/code/datalad/datalad/distributed/create_sibling_ria.py(563)_create_sibling_ria()
-> if shared else None)
(Pdb) l
558                 # provided with the same chgrp
559                 ssh(chgrp_cmd)
560         else:
561             gr = GitRepo(repo_path, create=True, bare=True,
562                          shared=" --shared='{}'".format(quote_cmdlinearg(shared))
563  ->                      if shared else None)
```

which is simply a bug, and not in `GitRepo`

**Comment by bpoldrack** [comment]
What idiot wrote that line? (Assuming it was me)

**Comment by mih** [comment]
`b6157ec862 (Benjamin Poldrack 2020-02-25 09:11:17 +0100 561)` :clinking_glasses:

**Comment by bpoldrack** [comment]
Re `exists`:
@mih, does only the directory exist already or is there a repo? What we test for is a `config` at the target dir. Now, if there's only an empty dir, the question is how do we want to interprete `--existing skip` vs. `--existing reconfigure`. In other words: If we didn't find a (bare) repo (as indicate by `config`), do we still want to skip or just call `mkdir` with `exist_ok`?

**Comment by bpoldrack** [comment]
I think `exist_ok` is the way to go. An empty directory shouldn't be considered an "existing target" that would require to specify `skip`, `error`, `reconfigure` from my point of view. There's no conflict to deal with. However, that still means, that we might want to refine our detection of whether or not a target "exists" in the sense of that switch.

**Comment by mih** [comment]
I think it is not a problem to use `exist_ok=True`, as it will do no damage. I am not convinced that more detection sophistication is needed.

**Comment by bpoldrack** [comment]
- `shared` issue fixed in https://github.com/bpoldrack/datalad/commit/6b204dc8276267caf7fb8480654e36cbfbcdb133

- "existing issue" implicitly fixed in https://github.com/datalad/datalad/pull/4203/commits/18e45e49586ae54b2ef484094296734be031fb09 since the entire `mkdir` call isn't needed anymore (at this location). Call moved to creation helpers using ORA remote's IO classes, which call mkdir with `-p` or `parents=True, exists_ok=True` respectively.
