### ISSUE TITLE
should output suppression be disabled if stdout is not tty?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4416]
#### What is the problem?

Currently suppression of similar messages in default renderer is unconditional, so even when I want to see full list e.g. for the purpose of grepping for lines of interest -- it would be suppressed:
```shell
$> datalad subdatasets | grep 101
subdataset(ok): HCP1200/101006 (dataset)
subdataset(ok): HCP1200/101107 (dataset)
subdataset(ok): HCP1200/101309 (dataset)
subdataset(ok): HCP1200/101410 (dataset)
subdataset(ok): HCP1200/101915 (dataset)

$> datalad subdatasets | grep supp
  [1103 similar messages have been suppressed]
```
I wonder if suppression should happen only if stdout is not redirected somewhere and thus a tty?

**Comment by kyleam** [comment]
I agree we should not suppress messages when not attached to a tty.
