### ISSUE TITLE
config option to disable suppression?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4417]
Message
```
  [XXX similar messages have been suppressed]
```
provides no information on how to disable suppression and I didn't find any config variable like `datalad.renderer.suppress-similar` so in cases of dire need (when I actually care to see all output) I could still use default renderer but see all output

**Comment by mih** [comment]
There is no config option (yet).

**Comment by mih** [comment]
> I think suppression should be the non-standard behavior, which can be enabled by a config option or switch.
> 
> If it still is standard behavior, the "suppressed" message has to be really prominent and should contain instructions how to switch it off.

This is a valid viewpoint. With #5681 one can now configure such behavior, and the requested hint is given.

**Comment by mih** [comment]
A change of the default behavior (if desired) should become it own issue IMHO.
