### ISSUE TITLE
Support convenience aliases in RIA stores

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4424]
It would be nice, if some datasets in a RIA store could be addressable via non-UUID convenience aliases. Those could be symlinks on the file system, but the resolving code would also need a change to accept them.

Use case: All 4.5k HCP subdatasets live in a store. It would be nice to not have to post the superdataset on another platform, only to give it a non-UUID URL. Doing the initial clone from the same store also get's all the subdataset resolving features readily configured, such that no tuning of the superdataset for a specific publication location would be needed.

**Comment by bpoldrack** [comment]
Nice to have, but not completely clear to me how to approach it. We would need to accept sth like `ria+http://mystore.org/base#<some label>`. So we would need to recognize whether or not or how to resolve such a URL. Generally the URL resolution should prob. not require a look up at the remote end as long as this is avoidable.
Therefore might be easiest to just use a different URL form to distinguish from ID based resolution. Different marker than `#` or an additional one. Say `ria+http://mystore.org/base##<label>`. This could then resolve to `http://mystore.org/base/label` which needs to point to such a symlink. Note, that we can't just use a not-to-be resolved URL, while simultanously making sure to recognize it's a RIA store and not just pointing to the base path of it. This approach would also allow to have different ways to resolve those later on based on the store itself (lookup resolution rule or sth).

**Comment by mih** [comment]
`##` is one way to deal with it. Another would be to simply check if the suffix is a UUID or not (already done at some point). Anything that is not, could be taken literally.

**Comment by bpoldrack** [comment]
Sure. That's simpler. Just potentially less flexible re future additions in how to interprete what comes after `#` or how to deal with a label.
However, I'd consider this pretty much the same approach.

What would be really different is some kind of lookup at the remote end (dedicated file w/ lookup table for labels?), so that we actually resolve to the real ID on our end. In a way that's more "beautiful", because it sticks to the ID based approach. But it would mean to not be able to resolve it without a connection to the store.

Wonder whether there's a clever third way.

**Comment by bpoldrack** [comment]
One more argument for a lookup like thing: Inodes. We can have thousands of labels in a table.

**Comment by mih** [comment]
I thought about this for a while now. I could not come up with a reason why we would *want* to "actually resolve to the real ID on our end" **before** a clone. Anything prior to a clone doesn't need a UUID, and anything after a clone has trivial access to it. Do you have something concrete in mind?

Moreover, any sort of "fancy" resolver should be done by a service, and not by a client that (potentially) needs to obtain a lot of information in order to provide this convenience.

**Comment by yarikoptic** [comment]
Fwiw - Initial single use case was : It would be nice to not have to post the superdataset on another platform, only to give it a non-UUID URL.

A symlink was suggested, and IMHO a viable solution without requiring any client changes probably. Number of symlinks even if established for many Datasets would still be much smaller than number of files in those datasets. Or what am I missing? More use cases?

**Comment by mih** [comment]
Or you saying that you need more usecases? Or that this is not a good solution?

**Comment by bpoldrack** [comment]
He's arguing in your favor, I think ;-)

>  Moreover, any sort of "fancy" resolver should be done by a service, and not by a client that (potentially) needs to obtain a lot of information in order to provide this convenience.

Yeah, can see that. No strong opinion on my end. Was just thinking out loud.

There's only the point of number of inodes that is a really concrete concern. In that regard I consider this 

> Number of symlinks [...] would still be much smaller than number of files in those datasets

not the point. ;-) We build those stores in a way that an actual dataset could go in there with just 20 inodes (ORA with archive). Number of files in a checkout is irrelevant comparison in that case.
