### ISSUE TITLE
Need for housekeeping command?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#444]
Datalad downloads tarballs in the background and caches them. This could lead to situations where a user want to know how much storage is needednfor the cache and maybe empty it.

Should we have a housekeeping command that can provide this info and perform cleanups?

Maybe even can kill cached files that are no longer needed (determined by some measure)?

**Comment by yarikoptic** [comment]
There are even multiple levels of what could be considered a cache here..  we should indeed discuss, please tag. Meanwhile, there is clean command already iirc.
-- 
Sent from a phone which beats iPhone.

**Comment by hanke** [comment]
Yes, there is `clean`, but nothing beyond that.

**Comment by mih** [comment]
Superseded by #1371.
