### ISSUE TITLE
fresh git annex build trips ria remote tests

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4445]
ok in maint and release, trips in master

there is a flood of errors from annex testremote, see https://github.com/datalad/datalad-extensions/runs/620907424

PS reminder -- you can download that build of git annex from 'artifacts' on top of that page

**Comment by kyleam** [comment]
When checking this out locally, I start seeing the `test_ria_gitannex:test_gitannex_localio_url` failure with aeca7c220 (Sped up query commands that read the git-annex branch by around 5%, 2020-04-09).  That's not that recent in the context of the datalad-extensions test, I suppose, so there might be something else at play.

**Comment by kyleam** [comment]
I can trigger this with the built-in directory remote.  I'll file a bug on git-annex's end.

**Comment by kyleam** [comment]
Filed at <https://git-annex.branchable.com/bugs/testremote_failures_starting_with_aeca7c220/>.

**Comment by kyleam** [comment]
Joey very quickly fixed this with fa98025de (fix testremote to not throw away annex state, 2020-04-28).  Looks like the issue was with `testremote` itself rather than some issue with special remote functionality caught be `testremote`.
