### ISSUE TITLE
Support query for computational reproducibility

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4449]
We can already determine which file versions have been produced by a computation of some kind (see the metadata extractor for this https://github.com/datalad/datalad-metalad/blob/master/datalad_metalad/extractors/runprov.py). We can take this a step further and add functionality that can verify the computational reproducibility. Recipe:

- Find at all the files that look as if they could be computed
- Execute the computation
- Verify identical results
- Mark file version as `reproducible`

This can be done on a different machine to improve validity of the assessment

With that information we can enhance other commands:

- `get`: compute a file, if no external sources have it available for download
- `push`: exclude computable files, useful to minimize resource consumption (e.g. backups https://github.com/datalad/datalad/issues/16)
- `drop`: trim local clone by stripping computable files

**Comment by yarikoptic** [comment]
re 
- `get`: initial discussion in https://github.com/datalad/datalad/issues/2850
- `push` and `drop`: "exclude computable file" -- I think it should be done by annotating computable files with annex metadata so special remotes could have their `wanted` expression set e.g. to `not metadata=computable`

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
