### ISSUE TITLE
Decide on the nature of --recursive

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#445]
With 0.2 release:

```shell
$> datalad install http://datasets.datalad.org/openfmri
1 installed item is available at
<Dataset path=/tmp/http:/datasets.datalad.org/openfmri>

$> datalad install -r http://datasets.datalad.org/openfmri
usage: datalad install [--version] [-h]
                       [-l {critical,error,warning,info,debug,1,2,3,4,5,6,7,8,9}]
                       [-p {condor}] [--dataset DATASET] [-s [SOURCE]]
                       [--recursive RECURSIVE]
                       [--add-data-to-git ADD_DATA_TO_GIT]
                       [path [path ...]]
datalad install: error: argument --recursive/-r: invalid <datalad.support.constraints.AltConstraints object at 0x7f319a08b910> value: 'http://datasets.datalad.org/openfmri'

$> lst
total 744
drwx------ 3 yoh         yoh           4096 May 20 18:10 http:/
...
$> ls -l http:/datasets.datalad.org/openfmri/

```

for the first install, I expected it to create local openfmri/ repo, for -r -- install also all submodules

**Comment by yarikoptic** [comment]
apparently '-r/--recursive' (not that help doesn't even list -r as a option there) wants me to say 'true'.

anyways -- I think it is all due to the fact that it treats the argument as the path and if not exists, magicial says "sim sim appear", and initialized a new repo.  Not sure if that is a natural thing.  I know that we diverged from classical git `src [dest]` here but imho analyzing arguments and checking if provided arg is a url and using it as source (with deduced target location) would be better...

**Comment by hanke** [comment]
The path -> source issue was addressed in #443 and is waiting for a merge.

**Comment by hanke** [comment]
Re recursive:

There is no simple "just recursive". Is it recursive with all the data? Or just the handles?

I see two possibilities:

1. Ignore this difference and imply "just handles" when no dataset exists at the beginning, and subsequently imply "with data".
2. have recursive have a mandatory value that is "handles" or "data" to make things explicit.

IMHO the first option is convoluted and impractical.

**Comment by yarikoptic** [comment]
Ah!  Interestingly that I believe it did swallow "true" to it... btw that error msg above should be made more informative (what are the expected values?) and less scary  (no python stock rear)

I will rtfm  ( the code) first and give it a try again. May be then -r could be for handles only and recursive take a parameter or smth like that. I just want us to find some usability point when options could be deducted by anyone familiar with other tools, and not too ad-hoc unexpectedly

**Comment by hanke** [comment]
Well, we need recursive to distinguish between this cases. I am not sure what ad-hoc means in this context. I stand by the my second proposal.

**Comment by hanke** [comment]
Split into several option. Have recursive just indicate recursion -- leave everything else to annex options.

**Comment by yarikoptic** [comment]
Do you foresee how argument(s) for 'annex options' should look like @hanke?

We could have explicit `--install-data` interim, which later would be enhanced with e.g. `--git-annex-get-opts` to provide arbitrarily options for annex and/or `--files-re`/`--files-glob` for simple regexps/globs to match (e.g. I could just --files-glob=*.nii.gz)... or then not worth having `--install-data` at all?

Should/could I or @bpoldrack  meanwhile RF so we have `-r|--recursive` just as  a flag to close this issue for now?

**Comment by yarikoptic** [comment]
Had a user expressing confusion of what "bool" means for recurse... moreover since -r data doesn't quite work (yet at least), I can only repeat that it might be better to have -r dealing with datasets alone, and installing data not being added into the soup and controlled with dedicated option(s).

**Comment by mih** [comment]
I think we have decided:

- within dataset is always recursive (like git annex)
- across datasets needs a `--recursive` flag
- `--recursive-limit` defines how far down to go
