### ISSUE TITLE
create-sibling doesn't run with local path

### ISSUE THREAD

**Issue by pvavra** [datalad/datalad#4450]
For `create-sibling` the [docs say](http://docs.datalad.org/en/latest/generated/man/datalad-create-sibling.html) that siblings can be created locally by setting `SSHURL` to a local path (tested on 0.12.6). 

I also noticed that the command line-help (`datalad create-sibling --help`) does *not* mention the local-path option, unlike the docs. 

Still, I expected the following to create a local sibling under `/tmp`
```
datalad create demo_siblings
datalad create-sibling -d demo_siblings -s "tmpsibling" /tmp/tmpsibling
```
Instead, if fails with 
```
[ERROR  ] Unsupported SSH URL: '/tmp/tmpsibling', use ssh://host/path or host:path syntax [create_sibling.py:__call__:499] (ValueError) 
```

I tried setting `--target-url`, `--target-path`, and `--target-pushurl` to the local path, but it gave similar errors.

However, the following works:
```
datalad clone demo_siblings /tmp/tmpsiblings
datalad siblings add -d demo_siblings --url /tmp/tmpsiblings
datalad siblings -d demo_siblings
# gives: 
# .: here(+) [git]
#  .: tmpsibling(+) [/tmp/tmpsibling (git)]
```

Am I misunderstanding the syntax of `datalad create-siblings` or has it lost the `local/path` part and the docs still reflect the old capabilities?

if the latter, any particular reason it was dropped?

**Comment by kyleam** [comment]
Sorry for the confusion.  That feature hasn't yet made it into a release (it will be a part of 0.13.0), and those docs are for an unreleased DataLad.

Not surprisingly, this doc/functionality mismatch has come up before.  If there's not a dedicated issue for this, I'll file one.

**Comment by kyleam** [comment]
Here the behavior of (a slightly modified variant of) you snippet:

```sh
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"
datalad --version
datalad create demo_siblings
datalad create-sibling -d demo_siblings -s "tmpsibling" tmpsibling
```

```
datalad 0.12.6.dev612
[INFO] Creating a new annex repo at /tmp/dl-JDOwiGH/demo_siblings 
[INFO] Scanning for unlocked files (this may take some time) 
create(ok): /tmp/dl-JDOwiGH/demo_siblings (dataset)
[INFO] Considering to create a target dataset /tmp/dl-JDOwiGH/demo_siblings at /tmp/dl-JDOwiGH/tmpsibling of localhost 
[INFO] Fetching updates for Dataset(/tmp/dl-JDOwiGH/demo_siblings) 
[INFO] Start enumerating objects 
[INFO] Start counting objects 
[INFO] Start compressing objects 
[INFO] Adjusting remote git configuration 
[INFO] Running post-update hooks in all created siblings 
create_sibling(ok): . (dataset)
```

**Comment by kyleam** [comment]
> Not surprisingly, this doc/functionality mismatch has come up before. If there's not a dedicated issue for this, I'll file one.

I've created gh-4451.
