### ISSUE TITLE
multiple issues with get output (in master)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4455]
Wanted to check effects of #4454 on other commands and ran into a  surprising  new behavior:

```shell
$> datalad --version ; datalad get openneuro/ds000017/sub-1/ses-timepoint1/anat/sub-1_ses-timepoint1_inplaneT2.nii.gz
datalad 0.12.6.dev611
Tried to get 1 file that had no content yet. 1 (failed).
/home/yoh/datalad/openneuro/ds000017 [dataset] ... notneeded
/home/yoh/datalad/openneuro/ds000017/sub-1/ses-timepoint1/anat/sub-1_ses-timepoint1_inplaneT2.nii.gz [file] ... notneeded
```

whenever released version is more succinct:

```shell
$> datalad --version ; datalad get openneuro/ds000017/sub-1/ses-timepoint1/anat/sub-1_ses-timepoint1_inplaneT2.nii.gz
datalad 0.12.6.dev1
action summary:
  get (notneeded: 2)
```
so it is strange that
- reports "Tried to get 1 file that had no content yet. 1 (failed)." although there is no such file and nothing really failed -- file does have content:
```
$> ls -Ll openneuro/ds000017/sub-1/ses-timepoint1/anat/sub-1_ses-timepoint1_inplaneT2.nii.gz
-r-------- 1 yoh yoh 661198 Apr 28 19:23 openneuro/ds000017/sub-1/ses-timepoint1/anat/sub-1_ses-timepoint1_inplaneT2.nii.gz
```
- spits out full paths.  I thought we went away from displaying those. (depending on destiny of #4454 we might want to centralize paths reporting logic)

**Comment by mih** [comment]
Closing #4429 assuming that a the new issue is better.

**Comment by kyleam** [comment]
I've started looking into this.
