### ISSUE TITLE
providing incorrect option to a datalad command gives summary for datalad not the command

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#446]
```
$> datalad install --src http://datasets.datalad.org/openfmri         
usage: datalad [-h] [-l {critical,error,warning,info,debug,1,2,3,4,5,6,7,8,9}]
               [-p {condor}] [--version] [--dbg] [-C PATH]
               {install,publish,uninstall,move,update,create-publication-target-sshwebserver,add-sibling,modify-subhandle-urls,test,crawl,pull,push,ls,clean,add-archive-content,download-url,create-test-dataset}
               ...
datalad: error: unrecognized arguments: --src
```

**Comment by hanke** [comment]
Unless we want to replace argparse there is nothing we could do. It determines that neither the main parser nor the subparser no anything about `--src` and returns the main help.

I will remove my assignment.

**Comment by yarikoptic** [comment]
Absolutely sure there is no easyish way @hanke?

**Comment by hanke** [comment]
I am absolutely sure that **I** see no way. I am also absolutely sure that there is a non-zero chance that I could be done somehow -- Python is Turing-complete after all ;-)

**Comment by yarikoptic** [comment]
ok, let's keep this one lingering around open then

**Comment by yarikoptic** [comment]
FWIW didn't look in detail, but atm playing with http://github.com/ViDA-NYU/reprozip (very nice and well done), and it seems to pick up/report correct --help (as for a subcommand) when I mystype the option for the command:
```shell
$> reprounzip graph --helalskdjfp      
error: too few arguments
usage: reprounzip graph [-h] [--version] [-F] [--packages PACKAGES]
                        [--processes PROCESSES] [--otherfiles OTHERFILES]
                        [--aggregate AGGREGATE] [--regex-filter REGEX_FILTER]
                        [--regex-replace REGEX_REPLACE REGEX_REPLACE] [--dot]
                        [--json] [-d DIR]
                        target [pack]

Generates a provenance graph from the trace data
...
```
although still giving a generic --help if mystyping also argument for the subcommand:
```shell
$> reprounzip graph asjdf --helalskdjfp 
error: unrecognized arguments: --helalskdjfp
usage: reprounzip [-h] [--version] [-v]  ...

reprounzip is the ReproZip component responsible for unpacking and reproducing
an experiment previously packed with reprozip
...
```
so may be provide a hint on how

**Comment by mih** [comment]
There you go!

**Comment by yarikoptic** [comment]
Sweet!!!

**Comment by yarikoptic** [comment]
I don't see a little test to accompany the fix though... Fix might evaporate and we wouldn't even note :-(
