### ISSUE TITLE
Replace `publish` by `push` for 0.13?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4461]
As it keeps coming up, e.g. in #4453, `push` is there to provide a cleaner (no `create-sibling` "integration")  `publish` .  As `create-sibling` got `--since`, I think all use cases possible with current `publish` should be addressed by a tandem of `create-sibling` and `push`. 
Please correct me if I am wrong.
So why to release 0.13 with new `push` instead of replacing with it `publish`?

**Comment by kyleam** [comment]
> So why to release 0.13 with new `push` instead of replacing with it `publish`?

At the very least, to give people a deprecation window.

**Comment by yarikoptic** [comment]
and then deprecation window for `push` to be gone (well -- mutate into `publish`)?  or we would just kill `publish` while keeping `push`? (then #4453 is still pertinent)

**Comment by mih** [comment]
Additionally, lots of tests need to be RF'ed. `publish` could start recommending `push`. And through actual usage we could figure out if `push` does what it should.

**Comment by mih** [comment]
I will close this. It is unlikely that any such move will happen for 0.13.

**Comment by yarikoptic** [comment]
My [question above](https://github.com/datalad/datalad/issues/4461#issuecomment-621389099) did not receive an explicit answer, but from the above ("recommend `push`) and our conversation during hangout, if I got it right, the strategy would be to introduce `push` and eventually remove `publish` after a proper deprecation cycle.  So, `push` would not become `publish`, thus #4453 remains pertinent.
