### ISSUE TITLE
`datalad push`-friendly remote config from `clone/create-sibling`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4467]
My desire was to push all relevant branches of a dataset to github (master, git-annex), but `push` wouldn't do it.

```
% datalad push --to origin --force no-datatransfer                                                                      
```

That is, because `push` does what Git would do:

```
% git push origin          
fatal: The current branch master has no upstream branch.    
To push the current branch and set the remote as upstream, use
                                                                                             
    git push --set-upstream origin master                                                   
```

so I was left with

```
% git push origin git-annex
Enumerating objects: 5070, done.
Counting objects: 100% (5070/5070), done.
Delta compression using up to 16 threads
Compressing objects: 100% (2985/2985), done.
Writing objects: 100% (3265/3265), 275.68 KiB | 5.74 MiB/s, done.
Total 3265 (delta 1190), reused 0 (delta 0)
remote: Resolving deltas: 100% (1190/1190), completed with 1165 local objects.
To github.com:datalad-datasets/hcp-structural-preprocessed.git
   4853f6be..7a81424f  git-annex -> git-annex
```

In contrast to `push` trusty old `publish` does not follow Git config (and therefore would have done "the right thing"), but in other scenarios users might suffer from the ignorance/deviant ideas of `publish`.

So, I wonder if `clone` and `create-sibling-*` (or rather `siblings add`) should pay more attention and configure proper `remote.*.push` settings, such that `publish` can keep being close to Git? And a plain `git push` would also "do the right thing".

FTR:
```
# config as a result of `datalad clone`
[remote "origin"]
        url = git@github.com:datalad-datasets/hcp-structural-preprocessed.git
        fetch = +refs/heads/*:refs/remotes/origin/*
        annex-ignore = true
# config as a result of `create-sibling-ria`
[remote "inm7"]
        annex-ignore = true
        url = /ds/hcp/srv/aef/339ec-889f-11ea-9d9c-a0369f287950
        fetch = +refs/heads/*:refs/remotes/inm7/*
```

Is there any scenario, where we want to clone an annex dataset, and do not want to be able to push the `git-annex` branch back **by default**? Likewise, is there any scenario, where we want to create a sibling, and not push an annex-branch **by default**?

If that is not desirable, we have to change the way `push` makes decisions.

**Comment by kyleam** [comment]
> My desire was to push all relevant branches of a dataset to github (master, git-annex), but `push` wouldn't do it.
> 
> ```
> % datalad push --to origin --force no-datatransfer                                                                      
> ```

Testing on my end with the default value for `push.default`, `datalad push` will push master with the above command, so I think "wouldn't do it" refers to push the git-annex branch in addition to master?

<details>
<summary>ex0</summary>

```sh
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"
git init --bare a

mkdir b
(
    cd b
    datalad create
    git config push.default simple
    git remote add origin ../a
    git remote add other ../a
    echo one >one
    datalad save
    datalad push --to origin --force no-datatransfer
)
```

```
[...]
publish(ok): . (dataset) [refs/heads/master->origin:refs/heads/master [new branch]]
```

</details>

If I remove `--force no-datatransfer`, then git-annex gets pushed as well.

<details>
<summary>ex1</summary>

```sh
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"
git init --bare a

mkdir b
(
    cd b
    datalad create
    git config push.default simple
    git remote add origin ../a
    git remote add other ../a
    echo one >one
    datalad save
    datalad push --to origin
)
```

```
[...]
publish(ok): . (dataset) [refs/heads/master->origin:refs/heads/master [new branch]]     
publish(ok): . (dataset) [refs/heads/git-annex->origin:refs/heads/git-annex [new branch]]
```

</details>

> That is, because `push` does what Git would do:
> 
> ```
> % git push origin          
> fatal: The current branch master has no upstream branch.    
> To push the current branch and set the remote as upstream, use
>                                                                                              
>     git push --set-upstream origin master                                                   
> ```

That doesn't seem accurate given the examples above.  `datalad push` tries to do what `git push` would do (testing the waters with `--dry-run`), but it doesn't stop there.  It fall backs to pushing `<current branch>:<current branch>` and, by default, `git-annex:git-annex`.

> so I was left with
> 
> ```
> % git push origin git-annex
> ```

Given the use of `--force no-datatransfer`.  Perhaps the git-annex branch should still be pushed in that case?

> So, I wonder if `clone` and `create-sibling-*` (or rather `siblings add`) should pay more attention and configure proper `remote.*.push` settings, such that `publish` can keep being close to Git? And a plain `git push` would also "do the right thing".

Hmm, I'm not sure it's a good idea for datalad to configure the push refspec for users.  It risks surprising users that call git directly and can result in them pushing things they didn't intend to.

> Is there any scenario, where we want to clone an annex dataset, and do not want to be able to push the `git-annex` branch back **by default**? Likewise, is there any scenario, where we want to create a sibling, and not push an annex-branch **by default**?

Based on the examples above, it seems `push` already does this...

> If that is not desirable, we have to change the way `push` makes decisions.

... though perhaps the behavior when `--force no-datatransfer` is given should be reconsidered.

**Comment by yarikoptic** [comment]
> > So, I wonder if `clone` and `create-sibling-*` (or rather `siblings add`) should pay more attention and configure proper `remote.*.push` settings, such that `publish` can keep being close to Git? And a plain `git push` would also "do the right thing".
> 
> Hmm, I'm not sure it's a good idea for datalad to configure the push refspec for users. It risks surprising users that call git directly and can result in them pushing things they didn't intend to.

I would vote too to stick closer to `git` behavior somewhat and not do something (push or annex copy) something not asked to be done explicitly by the command or configuration. As a solution to facilitate easy configuration we might want to establish common scenarios and have an explicit option to `create-sibling` (and `siblings` to adjust post-fact) to instruct on what that sibling is expected to be used for. See e.g. [previous issue/discussion](https://github.com/datalad/datalad/issues/925#issuecomment-252344069) .  Then `publish`/`push`, if explicitly asked to push to some sibling which has no explicit rule setup might as well just fail loud and clear instructing to provide desired configuration (via `siblings`).  Even `git` has similarish (although sure thing more simplified since no data is involved, and you cannot push at the same time to multiple remotes):
```
$> git remote add --help
...
    --mirror[=(push|fetch)]
                          set up remote as a mirror to push to or fetch from
```

I would also like us to allow (may be through explicit `--interactive` option) to be able to ask user in case if we would fail otherwise, see https://github.com/datalad/datalad/pull/3756 . If we could also do analysis first and only then proceed when all is clear, and otherwise interact with the user -- could be useful as well.

**Comment by mih** [comment]
Verdict after discussion in dev call: It could be tricky to find the right configuration to set -- which doesn't interfere with other (known to be used  configuration, e.g. `pushDefault`). It looks as if the current approach is near-optimal (minus the bugs).
