### ISSUE TITLE
ORA remote fails on windows

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#4469]
https://ci.appveyor.com/project/mih/datalad/builds/32554163/job/m95vob7met6w4a60

Need to investigate what's going on.

**Comment by bpoldrack** [comment]
This might be closely related to #4278

**Comment by mih** [comment]
There is no need to keep this open. The entire ORA code doesn't work on windows, and all tests are disabled. No need to "track" individual issues of the past, IMHO.
