### ISSUE TITLE
Make exc_str() silent by default

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4478]
We are trying to use this function to make it easier to debug exceptions. However, debugging isn't always necessary and certainly not a desire of most users. The function has (at least) this kind of impact on (error) messages:

```
w/o:  [Errno 39] Directory not empty: 'dir'
with: [Errno 39] Directory not empty: 'dir' [pathlib.py:rmdir:1302]
```

If we want to use this function unconditionally, and we acknowledge that, in the general case, we cannot decide whether an exception is indeed an indication of an error (in the original context of the example above, it was not #4430), then this function should be silent by default and not add additional information.

Output that is unconditionally tuned for debugging is only suitable for code that is so fragile that it isn't really expected to work INMO. This may be true from some pieces, but certainly should not be true for DataLad as a whole.

The above example is actually not representative of the real impact. In many cases, DataLad error messages flood the terminal with tons of info already, and the additions by `exc_str()` just add the icing to the cake.

**Comment by mih** [comment]
I looked into this now, and I think I see a possibility to change the concept of `exc_str()` to make it easier to work with (and faster).

My issue with this function is that it calls `str(exc)`, unconditionally and at the time of log message composition (not when it is eventually emitted, if at all). It is unforeseeable how much that costs, because it depends on the exception itself. Moreover, it moves all decision making on how the most appropriate formatting looks like into the log message composition, where it is cumbersome to make things conditional on whether a message will actually be seen.

I think we should stop turning exceptions into strings with amended information, and instead amend the exception objects, while leaving the formatting to the `Logger`, where it already happens, and at the latest possible stage.

Proposal:

- stop using `exc_str()` and replace with `exc_add_tb()`
- `exc_add_tb()` adds an attribute `datalad_tb_entries` to an exception object that matches the filtered selection `entries[-limit:]` that is presently used for str formatting in `exc_str()`.
- the actual exception str formatting moves into `datalad.log.ColorFormatter.format()` that receives the log message args as a tuple (`record.args`), that can be easily transformed by looping over all args and formatting the ones that are of type `Exception` and have our custom traceback information. The rest is left untouched.

IMHO this is a better fit for the design of `logging`. The user-facing behavior is unchanged, information collection is now longer conflated with information display.

**Comment by bpoldrack** [comment]
I like that idea.

**Comment by yarikoptic** [comment]
Do you know any estimate of the % of execution time such refactoring would shave off? I would agree to pay 1% slow down to avoid nether conflicts etc at this point of maint and master.

What if exc_str just mutate into a class with __str__ doing what needs to be done on that instance if called. I wonder if much of course should then be changed.

**Comment by yarikoptic** [comment]
as for silencing -- I am ok with it if it is so important to you.  I thought in general you did not care about log messages and wanted to relay all important to the user via result records and their rendering.  That is how many of errors and warnings were silenced (went to the lower log level) in the logs already and then brought in some shape of form up in results records' message.  So may be in this particular case something similar to be done anyways?

**Comment by mih** [comment]
re silencing: The case the brought us here was a `warning` about a directory that could not be removed. It had no immediately relationship with any result of a command, hence could not or should not become a result (IMHO). However, it also wasn't any indication that something was wrong in DataLad. It merely reflected a situation on the system our code was running on. If the desire is to always add debugging info to any exception, I'd say that it should be possible to turn this off, if a message is generated that warns about a condition DataLad is facing (and cannot resolve), rather than alerting a user to a condition within DataLad, where DataLad itself goes off the rails. How this is done is less important to me, but we should have the ability to communicate non-debug info that is gathered from exceptions. Most log messages we generate do not render any debug info by default, I don't know why a warning about a non-empty dir that can happen for all kinds of reasons must come with debug info.

That being said, maybe this whole debate is an indication that this warning shouldn't be there to begin with.

**Comment by yarikoptic** [comment]
BTW regarding formatting exception info, if we were to RF the code notably, we should look into passing exception via exc_info argument and providing custom formatter.

**Comment by yarikoptic** [comment]
a somewhat alternative was implemented in https://github.com/datalad/datalad/pull/4843 (yet to be finalized) to include a full stack in the returned error record

**Comment by bpoldrack** [comment]
Looking into this again.

FTR: Also trying to figure how to capture the relevant infos best, in order to avoid keeping the exception (or its traceback object) around (remember: circular references). Seems like the `traceback` module provides `TracebackException ` objects for that.
