### ISSUE TITLE
push: does not respect wanted git-annex wanted expression

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4483]
As discovered during meeting, following script:
```
#!/bin/bash

datalad --version
set -eu
export PS4='> '
set -x
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"

datalad create src

(
cd src
# now modify subds without saving updated state in superdataset
echo "precious content" > file
datalad save -m "added a file"
datalad create-sibling --annex-wanted nothing  -r -s target ../target
datalad push -d . --to target
)
ls -ld target/file
cat target/file
```

produces

```
> ls -ld target/file
lrwxrwxrwx 1 yoh yoh 110 May  5 10:51 target/file -> .git/annex/objects/63/PP/MD5E-s17--94887fe09c10ca3340603e9a7ec9efdf/MD5E-s17--94887fe09c10ca3340603e9a7ec9efdf
> cat target/file
precious content
```

so "nothing" was not respected

**Comment by yarikoptic** [comment]
FWIW FTR, `git annex copy --auto PATHs` just restricts `--auto` operation to keys found under `PATHs` which would be in agreement with `datalad push` description for having `PATH`s specified.

**Comment by yarikoptic** [comment]
note: make sure to add `--auto` only if wanted is set, since otherwise it would not cause any transfer.

**Comment by kyleam** [comment]
> note: make sure to add `--auto` only if wanted is set

numcopies configuration is also considered.
