### ISSUE TITLE
Update list of DataLad extensions (or bits that extend Datalad otherwise)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4490]
We have a lists at:

- http://docs.datalad.org/en/stable/#extension-packages
- https://github.com/datalad/datalad#extensions

ATM this lists crawler, neuroimaging, container, webapp (or IOW a mixture of premature code bits, plus trusty workhorses). We should update these lists with other pieces that are of interest to datalad users. I keep forgetting that we have them myself, I can only imagine how not obvious it has to be for everybody else:

#### Extensions of various maturity levels
- https://github.com/datalad/datalad-xnat
- https://github.com/datalad/datalad-ukbiobank
- https://github.com/datalad/datalad-metalad
- https://github.com/datalad/datalad-htcondor
- https://github.com/psychoinformatics-de/datalad-hirni

#### Git remote helper
- https://github.com/datalad/git-remote-rclone

Are there some `Repro*` projects that would fit here too?

Edit: Added hirni after @adswa  pointed it out.

**Comment by adswa** [comment]
I have put up a PR to update [the list I keep in the handbook](http://handbook.datalad.org/en/latest/beyond_basics/101-144-intro_extensions.html). What is missing in the list above is [datalad-hirni](https://github.com/psychoinformatics-de/datalad-hirni/), I believe.

**Comment by mih** [comment]
Ah, cool! Even that I had forgotten. Maybe we should then stop maintaining any other list than your's"

**Comment by yarikoptic** [comment]
Note: ideally any extension we reference should be added to https://github.com/datalad/datalad-extensions "dashboard" which should also be referenced in README/docs

**Comment by yarikoptic** [comment]
FWIW may be https://github.com/datalad/datalad-extensions/blob/master/extensions.yaml should be extended/used to programmatically establish necessary lists in docs?

**Comment by mih** [comment]
The list in the handbook is now uptodate. I will remove the 0.13.0 milestone. This is not really blocking a release.
