### ISSUE TITLE
Remove `publish` command

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4494]
Following the deprecation in 0.13 https://github.com/datalad/datalad/issues/4493

Candidate issues to close:
- https://github.com/datalad/datalad/issues/5176
- https://github.com/datalad/datalad/issues/4446
- https://github.com/datalad/datalad/issues/4397
- https://github.com/datalad/datalad/issues/4396
- https://github.com/datalad/datalad/issues/3068
- https://github.com/datalad/datalad/issues/2186
- https://github.com/datalad/datalad/issues/1673
- https://github.com/datalad/datalad/issues/1494
- https://github.com/datalad/datalad/issues/1491
- https://github.com/datalad/datalad/issues/1344
- https://github.com/datalad/datalad/issues/1331

**Comment by dorianps** [comment]
I didn't want to open a separate issue, since this is related to `publish`. The documentation needs some more detailed explanation for `--transfer-data` options. I am not sure what `auto` does, or if there is a way to transfer only files that were changed between in the commits that will advance the remote to the local status. Pinging @adswa .

![image](https://user-images.githubusercontent.com/9083517/81366726-5a816380-90b9-11ea-83ed-5f4681450940.png)

**Comment by yarikoptic** [comment]
--auto would cause adding --auto to git annex copy if there's is a wanted expression set for the remote in annex: https://git-annex.branchable.com/git-annex-wanted/ which would cause transfer only if the files satisfying that expression. We indeed should extend documentation there

**Comment by yarikoptic** [comment]
Re original issue - some of those listed issues might be pertinent to push as well. Requires checking them all out

**Comment by adswa** [comment]
thanks for pinging me, @dorianps. I agree. FWIW, I tried to create a [better overview for ``datalad push``](http://handbook.datalad.org/en/latest/basics/101-141-push.html) in the handbook.

**Comment by ljchang** [comment]
I was trying to follow the handbook, but my version of datalad doesn't appear to have push yet, is this from a forthcoming release?

I'm using datalad 0.12.6

**Comment by kyleam** [comment]
> I was trying to follow the handbook, but my version of datalad doesn't appear to have push yet, is this from a forthcoming release?

Yes, `push` will be part of the 0.13.0 release (which should happen next week).  `publish` will still be there too, until at least 0.14.0.  There is an rc out right now that you can pull down with `pip install datalad==0.13.0rc1` if you're interested.

**Comment by ljchang** [comment]
Ah, that makes sense. Thanks the heads up! Handbook looks great so far!

**Comment by yarikoptic** [comment]
removing it from 0.14.0 release since I do not think this ended up being our plan

**Comment by adswa** [comment]
Another candidate issue that could be closed if ``publish`` is removed is https://github.com/datalad/datalad/issues/1331

**Comment by mih** [comment]
I added this to the 0.15.0 milestone. Primarily to make sure we actively decide on a removal, as 0.15 would be the first time point that is compatible with the original announcement.

**Comment by yarikoptic** [comment]
eh,  let's at least move it to deprecated may be? I am still wary of using `push` whenever I am working with public remotes due to its different default behavior, but I guess I should "hardcode" my brain to just use `--data auto` always with the `push`.

**Comment by mih** [comment]
> eh, let's at least move it to deprecated may be?

Will make an attempt now

**Comment by mih** [comment]
There is still usage of `publish` in the tests of `clone`, RIA, `create-sibling`, `install`, `update`, and metadata aggregation.

I will approach those, motivated be the renewed realization that this deprecation cuts more ties to `annotate_paths()` in -core.
