### ISSUE TITLE
sudo -E cron run on travis fails on master -- demands authenticaiton

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4497]
AFAIK is ok on maint, but fails on master: https://travis-ci.org/github/datalad/datalad/jobs/682067831

```shell
$ http_proxy= PATH=$PWD/../tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -A "$NOSE_SELECTION_OP($NOSE_SELECTION) and not(turtle)" --with-doctest --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM
...............
........................................................S....enableremote datastore-storage ok
(recording state in git...)
enableremote datastore-storage ok
(recording state in git...)
enableremote datastore-storage ok
(recording state in git...)
enableremote datastore-storage ok
(recording state in git...)
.S.The authenticity of host 'datalad-test (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256:8ff0Hk2I7/JeM6B0VLliG30VgWMVboBej6mp8MhP/Ug.
Are you sure you want to continue connecting (yes/no)? 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by kyleam** [comment]
SSH should be skipped on the `sudo -E` runs:

https://github.com/datalad/datalad/blob/8ccc341249dd5f522ebad0128315000eed23288f/.travis.yml#L135-L142

That makes me think this may have been resolved by b1a917f57 (TST: ria_utils: Delay instantiation of IO class to allow SSH skip, 2020-05-06).  Looking at the [last cron run for master][0], it doesn't look like it got stuck, so I hope that's so.

Note though that there is another failing test that should be fixed.  I'll open an issue or PR for that.

[0]: https://travis-ci.org/github/datalad/datalad/jobs/684799579

**Comment by kyleam** [comment]
> Note though that there is another failing test that should be fixed. I'll open an issue or PR for that.

PR #4534

**Comment by kyleam** [comment]
As hoped, the [latest cron for master][0] didn't hit into this authentication failure.  It did fail due to the issue that is resolved by the now merged gh-4534.

[0]: https://travis-ci.org/github/datalad/datalad/jobs/687559718#L1677
