### ISSUE TITLE
provide decorator to swallow log messages to get them ignored or analyzed

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#45]
now if we run
```
$> nosetests -s -v datalad/tests/                 
datalad.tests.test_annexrepo.test_AnnexRepo_instance_brand_new ... ok
datalad.tests.test_annexrepo.test_AnnexRepo_instance_from_clone ... 2015-02-25 13:19:13,261 [ERROR  ] 'git clone -v /home/yoh/proj/datalad/datalad/datalad/tests/testrepos/basic/r1 /home/yoh/.tmp/tmptoMerM' returned with exit code 128
| stderr: 'fatal: destination path '/home/yoh/.tmp/tmptoMerM' already exists and is not an empty directory.
| ' (gitrepo.py:59)
ok
...
```
we get them spit out to the screen, which is not proper since they are intended to error out at that point (right @bpoldrack ?).  so we need to swallow them.
In fail2ban we have a derived TestCase class for that purpose: https://github.com/fail2ban/fail2ban/blob/HEAD/fail2ban/tests/utils.py#L200  which also allows to analyze those logs for testing (which we would need to).  But here we better come up with a decorator which captures and exposes within the test the logs.  Any takers? ;)

**Comment by bpoldrack** [comment]
Can't we just make the logger directing ERROR to stderr instead of stdout?

2015-02-25 19:24 GMT+01:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by bpoldrack** [comment]
And what about this brand new idea of having a logger write it's output to a logfile, what you can browse/analyze afterwards?

**Comment by yarikoptic** [comment]
1. Regarding "directing ERROR to stderr instead of stdout" -- good idea in case of stdout (not file) output but not sure if I know/used straight solution for that with the python logger -- we might would need to provide a shim around the two.  If interested -- figure it out BUT this is far from being a priority ATM.  Just file a new issue so we don't forget

2. logging to a file will happen and very simple todo, but also not a priority ATM.  We will do it whenever we start working on a datalad config facility probably.  But just to make you happy I will do it in a PR shortly

swallowing/suppressing logs is a bit more important atm since they pollute output of running tests

**Comment by yarikoptic** [comment]
for 2.  just accept #46 pull request

**Comment by yarikoptic** [comment]
was implemented with ```swallow_logs``` context manager in 43e2d72b4c531e3f2a04c78cfd0576ef7c03cdc1
