### ISSUE TITLE
`push` warns to early and too dramatically

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4508]
Case:

```
datalad push --to inm7 -r
...
[WARNING] Slated for transport, but no content present [copy(....nii.gz)] 
...
```
The local dataset doesn't have the content, but the remote has it already. There are now three angles:

#### UX

All these files should be tested, whether the remote has the content already, and if so, the logging should happen on DEBUG instead.

#### Performance

No further testing should be done. No path was given, if content isn't there locally, it can never be copied. That is "obvious" and not worth a warning even.

#### Trust

I might be under the impression that after this command, the remote is guaranteed to have a content that is *tracked* (not just available). Without a warning, I can easily maintain this false impression.

**Comment by mih** [comment]
https://github.com/datalad/datalad/issues/4530 is another case where this is massively annoying. 60k+ warning log messages after

`datalad push --to origin`

**Comment by kyleam** [comment]
> There are now three angles:

Reading over these, I have a hard time landing on any angle other than the second.

**Comment by mih** [comment]
Thx for the feedback @kyleam ! This is also my current attitude.
