### ISSUE TITLE
RF ssh CI setup to use a dedicated docker image 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4514]

**Comment by kyleam** [comment]
I worked on this yesterday.  I got to a point where (I think) all the SSH tests were passing for me locally: [origin/scratch/docker-ssh](https://github.com/datalad/datalad/compare/master...scratch/docker-ssh).

There are some wip/temp commits at the end of that branch to try this out on Travis.  One of them pulls in the docker build file for the container so it can be built locally, though of course in the final state our test runs would just download the image from somewhere.

However, when I try that on Travis, there are [widespread failures]( https://travis-ci.org/github/datalad/datalad/builds/686364795).  It looks like all of these come down to permission errors when ssh commands are trying to work with things in the temp directory.

**Comment by yarikoptic** [comment]
can't leave comments in the diff view.  Re permissions: I think some (if not majority) of tests rely on being able to manipulate the "remote" paths locally. There is no user mapping in docker by default so I guess whatever used it logs in into has UID which is different.  `--user` option to docker run could be used to map local one to the remote one IIRC. But may be it is a wrong idea since you say that they all pass locally and I do not see how that could be.

**Comment by kyleam** [comment]
> can't leave comments in the diff view.

That seems acceptable given that I wasn't requesting comments there.

> Re permissions: I think some (if not majority) of tests rely on being able to manipulate the "remote" paths locally. [...]

Yes, and the setup accounts for that in that exposes the paths.  But the state that was good enough locally (probably by chance of uid match) isn't good enough on Travis.  Hopefully none of this here should be too hard to solve.  The above was just a comment about where things are at the moment, especially because I'm not sure when I'll return to this next.

**Comment by kyleam** [comment]
With a workaround for the permission issues, the tests passed with the neurodebian git-annex, but [still stalled][0] (or at least had 10 minutes of no output) with -devel.  Bah, so it doesn't seem there is much hope of ignoring these as a peculiarity of the Travis setup.  Sadly, it still doesn't stall for me when I run it locally.

[0]: https://travis-ci.org/github/datalad/datalad/jobs/686723312#L2028
