### ISSUE TITLE
Dissolve plugins (and supporting functionality)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4519]
We have interfaces, plugins, procedures, and extensions now.
IIRC plugin mechanism was introduced before procedures and pretty much morphed into an interfaces:
```
$> grep Interface datalad/plugin/*py   
datalad/plugin/add_readme.py:from datalad.interface.base import Interface
datalad/plugin/add_readme.py:class AddReadme(Interface):
datalad/plugin/addurls.py:from datalad.interface.base import Interface
datalad/plugin/addurls.py:class Addurls(Interface):
datalad/plugin/check_dates.py:from datalad.interface.base import Interface
datalad/plugin/check_dates.py:class CheckDates(Interface):
datalad/plugin/export_archive.py:from datalad.interface.base import Interface
datalad/plugin/export_archive.py:class ExportArchive(Interface):
datalad/plugin/export_to_figshare.py:from datalad.interface.base import Interface
datalad/plugin/export_to_figshare.py:class ExportToFigshare(Interface):
datalad/plugin/__init__.py:    # TODO check all symbols whether they are derived from Interface
datalad/plugin/no_annex.py:from datalad.interface.base import Interface
datalad/plugin/no_annex.py:class NoAnnex(Interface):
datalad/plugin/wtf.py:from datalad.interface.base import Interface
datalad/plugin/wtf.py:class WTF(Interface):
```

should we just remove the notion of plugins (e.g. in 0.14) and move existing ones around into corresponding spots?  

or am I missing some unique feature of plugins ?

**Comment by mih** [comment]
Plugins are obsolete from my POV. I would appreciate if someone takes care of the transition that you proposed.

**Comment by mih** [comment]
Before we can remove the supporting code, the following plugins must be registered as proper commands, or they would disappear:

- [ ] datalad/plugin/add_readme.py
- [ ] datalad/plugin/addurls.py
- [ ] datalad/plugin/check_dates.py (missing @datasetmethod decorator)
- [ ] datalad/plugin/export_archive.py
- [ ] datalad/plugin/export_to_figshare.py
- [ ] datalad/plugin/no_annex.py

They are all already standard command, just not registered.
