### ISSUE TITLE
git annex direct mode vs. submodule -> dead end? Doesn't look like it!

### ISSUE THREAD

**Issue by mih** [datalad/datalad#453]
Demo:

```
% mkdir testsuper
% cd testsuper
% git init
Initialized empty Git repository in /media/mih/USB DISK/testsuper/.git/
% git annex init
init  
  Detected a filesystem without fifo support.

  Disabling ssh connection caching.

  Detected a crippled filesystem.

  Enabling direct mode.
ok
(recording state in git...)
% mkdir testsub
% cd testsub
% git init
Initialized empty Git repository in /media/mih/USB DISK/testsuper/testsub/.git/
% touch test
% git add test
% git commit -m commit
[master (root-commit) 3fcd25e] commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test
% cd ..
% git submodule add testsub testsub
fatal: /usr/lib/git-core/git-submodule cannot be used without a working tree.
% git annex proxy -- git submodule add testsub testsub
fatal: /usr/lib/git-annex.linux/git-core/git-submodule cannot be used without a working tree.
% git annex proxy -- git status
On branch annex/direct/master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    testsub/

nothing added to commit but untracked files present (use "git add" to track)
```

`git annex proxy` generates a temporary working tree from commited and staged changes, hence it doesn't see the to-be-added submodule/directory. At this point, I don't see a workaround.

This issue should be limited to adding a fresh submodule to a dataset, and should not affect the consumption of subdatasets in installed datasets on crippled file systems.

**Comment by hanke** [comment]
Makes it harder to debug #258...

**Comment by hanke** [comment]
Captain's log: GitPython may be more clever than the cmdline:

````
% datalad install -s http://psydata.ovgu.de/studyforrest/templatetransforms                   
% cd templatetransforms
# in the crippled beast
% git submodule status
fatal: /usr/lib/git-core/git-submodule cannot be used without a working tree.
% ipython
Python 2.7.11+ (default, Mar 23 2016, 11:35:56) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import datalad.api as da

In [2]: ds=da.Dataset('.')

In [3]: ds.get_dataset_handles()
Out[3]: [u'raw/phase2', u'code/ofhelpers', u'raw/structural', u'raw/phase1']
````

**Comment by hanke** [comment]
Sadly, not:

````
In [6]: sm
Out[6]: git.Submodule(name=raw/structural, path=raw/structural, url=../structural, branch_path=refs/heads/master)
In [13]: sm.add(ds.repo.repo, 'raw/structural', 'raw/structural')
---------------------------------------------------------------------------
InvalidGitRepositoryError                 Traceback (most recent call last)
<ipython-input-13-563f802eb6fe> in <module>()
----> 1 sm.add(ds.repo.repo, 'raw/structural', 'raw/structural')

/usr/lib/python2.7/dist-packages/git/objects/submodule/base.pyc in add(cls, repo, name, path, url, branch, no_checkout)
    331             update fails for instance"""
    332         if repo.bare:
--> 333             raise InvalidGitRepositoryError("Cannot add submodules to bare repositories")
    334         # END handle bare repos
    335 

InvalidGitRepositoryError: Cannot add submodules to bare repositories
````

Looks like some soul searching is required.

**Comment by hanke** [comment]
Captian's log:

`git --git-dir=.git --work-tree=. status` is a muuuch faster in a direct mode repo than `git annex proxy -- git status` and seems to accomplish the same.

**Comment by hanke** [comment]
Lovely:

````
% git --git-dir=.git --work-tree=. submodule update  raw/structural
Cloning into 'raw/structural'...
Checking connectivity... done.
Submodule path 'raw/structural': checked out '54e555acea857acdb2a8b713cc4c7c7b09607b3d'
% git --git-dir=.git --work-tree=. status
On branch annex/direct/master
nothing to commit, working directory clean
% git --git-dir=.git --work-tree=. submodule status             
-bb29cf28a5e25b9e97a0bb0a97a2eddef46d8a7f code/ofhelpers
-b2b9d3e73712def6600c5980bdc52535ca613169 raw/phase1
-ddf2eae956fb782e127321fd913e8a951349e1d3 raw/phase2
 54e555acea857acdb2a8b713cc4c7c7b09607b3d raw/structural (heads/master)
````

Worth noting that `.git` in the annex-initted submodule looks like this:

````
gitdir: /media/mih/USB DISK/templatetransforms/.git/modules/raw/structural
````

and that annex operations seem to work as expected.

**Comment by hanke** [comment]
And here comes the relief:

````
% git clone http://psydata.ovgu.de/studyforrest/templatetransforms/.git
Cloning into 'templatetransforms'...
Checking connectivity... done.
Checking out files: 100% (924/924), done.
% cd templatetransforms
% git annex init
init  
  Detected a filesystem without fifo support.

  Disabling ssh connection caching.

  Detected a crippled filesystem.
(merging origin/git-annex into git-annex...)
(recording state in git...)

  Enabling direct mode.
ok
(recording state in git...)
% cd raw/structural
% git clone http://psydata.ovgu.de/studyforrest/structural/.git .   
Cloning into '.'...
Checking connectivity... done.
% git annex init
init  
  Detected a filesystem without fifo support.

  Disabling ssh connection caching.

  Detected a crippled filesystem.
(merging origin/git-annex into git-annex...)
(recording state in git...)

  Enabling direct mode.
ok
(recording state in git...)
% cd ../..
% git --git-dir=.git --work-tree=. submodule                                    
-bb29cf28a5e25b9e97a0bb0a97a2eddef46d8a7f code/ofhelpers
-b2b9d3e73712def6600c5980bdc52535ca613169 raw/phase1
-ddf2eae956fb782e127321fd913e8a951349e1d3 raw/phase2
-54e555acea857acdb2a8b713cc4c7c7b09607b3d raw/structural
% git --git-dir=.git --work-tree=. submodule update --init raw/structural 
Submodule 'raw/structural' (http://psydata.ovgu.de/studyforrest/templatetransforms/structural) registered for path 'raw/structural'
% git --git-dir=.git --work-tree=. submodule status                             
-bb29cf28a5e25b9e97a0bb0a97a2eddef46d8a7f code/ofhelpers
-b2b9d3e73712def6600c5980bdc52535ca613169 raw/phase1
-ddf2eae956fb782e127321fd913e8a951349e1d3 raw/phase2
 54e555acea857acdb2a8b713cc4c7c7b09607b3d raw/structural (heads/annex/direct/master)
````

Noteably, `raw/structural/.git` is not moved, and not replaced by a file, but is the usual .git directory.

Bottom line: all good.

We should probably adjust the code so that all Git calls and GitPython operations are explicitly configured with the `--git-dir=` and `--work-tree=` equivalent -- regardless of whether we operate on direct or indirect mode repositories.

Question: Should we standardize our setup so that submodule `.git` stays in the submodule? Or would there be any negative effects?

**Comment by yarikoptic** [comment]
@joeyh please pardon my ignorant question, but why https://github.com/datalad/datalad/issues/453#issuecomment-220769439 ?

**Comment by joeyh** [comment]
I don't think it's safe at all to use --work-tree in direct mode repositories. Any git command that actually manipulates the work tree could overwrite/delete the annex files with the symlinks from the git repository. 

That is basically the same as removing the direct mode guard (configuring the repo to not be considered to be a bare repo), which is there to prevent such foot-shooting deletion of potentially the only copy of a file in a direct mode repository.

v6 mode is a much better solution to this probem.

**Comment by hanke** [comment]
Thanks @joeyh !

I will start playing with v6 repos and see how they play alongside submodules.

**Comment by hanke** [comment]
I spent some time manually trying out the most essential bits from the datalad PoV with V6 repos. I agree with @joeyh that this is a much better solution. Not just to the handling of submodules, but also to  some of the issues we are still ignoring (AFNI dereferencing files, ...).

I'd suggest that you also take a look, if you haven't yet. We should really consider doing v6 right from the start for datalad's datasets.

During the next meeting we should discuss, whether we want to go v6 and whether we want to present "unlocked" files by default.

**Comment by joeyh** [comment]
Note that git annex adjust --unlock makes it easy to switch a repository
to presenting unlocked files locally while keeping them locked in other
clones. I could very easily add the --lock to go the other way if there
is a use case for it.

v6 mode still has some warts though, including speed problems that will
need patches to git to resolve. Drop or get some files with git annex
and run git status to see one of the problems..

(And a big thank you to DataLad/Dartmouth for making v6 development possible!
It's rare to be in a position to be able to try out big speculative
changes like this.)

-- 
see shy jo

**Comment by hanke** [comment]
@joeyh Thanks for the information, and thanks for everything else, too!

**Comment by yarikoptic** [comment]
for reference: annex page describing outstanding issues with v6/smudge filters: https://git-annex.branchable.com/todo/smudge/

**Comment by mih** [comment]
We are doing much better on this topic in current master. Closing.
