### ISSUE TITLE
download-url stalls while downloading a simple URL

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4532]
Triggered by trying to reproduce #4525 , but resulted in a different discovery I believe: for me it just stalled!

<details>
<summary>With this simple reproduction script:</summary> 

```shell
$> cat test-ziprchive.sh                        
#!/bin/bash
#
#

export PS4="> "
set -eu
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"

which datalad
datalad --version

set -x
datalad create ds
(
cd ds
datalad download-url --archive http://www.onerussian.com/tmp/testzip.zip
)
```
</details>

if ran with DATALAD_LOG_LEVEL=1 the last lines I see are
```
[DEBUG  ] Reading files: ['/home/yoh/proj/datalad/datalad-0.12.x/datalad/downloaders/configs/crawdad.cfg', '/home/yoh/proj/datalad/datalad-0.12.x/datalad/downloaders/configs/crcns.cfg', '/home/yoh/proj/datalad/datalad-0.12.x/datalad/downloaders/configs/figshare.cfg', '/home/yoh/proj/datalad/datalad-0.12.x/datalad/downloaders/configs/hcp.cfg', '/home/yoh/proj/datalad/datalad-0.12.x/datalad/downloaders/configs/indi.cfg', '/home/yoh/proj/datalad/datalad-0.12.x/datalad/downloaders/configs/kaggle.cfg', '/home/yoh/proj/datalad/datalad-0.12.x/datalad/downloaders/configs/loris.cfg', '/home/yoh/proj/datalad/datalad-0.12.x/datalad/downloaders/configs/nda.cfg', '/home/yoh/proj/datalad/datalad-0.12.x/datalad/downloaders/configs/nitrc.cfg', '/home/yoh/proj/datalad/datalad-0.12.x/datalad/downloaders/configs/openfmri.cfg', '/home/yoh/proj/datalad/datalad-0.12.x/datalad/downloaders/configs/providers.cfg', '/home/yoh/.config/datalad/providers/www.onerussian.com.cfg', '/home/yoh/.config/datalad/providers/jigsaw.w3.org.cfg', '/home/yoh/.config/datalad/providers/w3-digest.cfg', '/home/yoh/.config/datalad/providers/jigsaw-digest.cfg', '/home/yoh/.config/datalad/providers/my.domain.com.cfg', '/home/yoh/.config/datalad/providers/yarik.cfg'] 
[DEBUG  ] Assigning credentials into 25 providers 
[DEBUG  ] Initializing default provider for http 
[DEBUG  ] No dedicated provider, returning default one for http: Provider(authenticator=None, credential=None, name='', url_res=['http://.*']) 
[Level 5] Requested to provide version for requests 
[INFO   ] Downloading 'http://www.onerussian.com/tmp/testzip.zip' into '/home/yoh/.tmp/dl-xoRowDy/ds/' 
```
and there it stays!  requests library is at 2.23.0

<details><summary>DataLad 0.12.6 WTF (configuration, datalad, dataset, dependencies, environment, extensions, git-annex, location, metadata_extractors, python, system)</summary>

# WTF
## datalad 
  - full_version: 0.12.6
  - version: 0.12.6
## dataset 
  - id: None
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /home/yoh/proj/datalad/trash
  - repo: GitRepo
## dependencies 
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20200501+git61-g64e081d58-1~ndall+1
  - cmd:bundled-git: 2.24.0
  - cmd:git: 2.24.0
  - cmd:system-git: 2.26.2
  - cmd:system-ssh: 8.1p1
  - exifread: 2.1.2
  - git: 3.1.0
  - gitdb: 4.0.2
  - humanize: 2.3.0
  - iso8601: 0.1.12
  - keyring: 18.0.1
  - keyrings.alt: 3.4.0
  - msgpack: 0.6.2
  - mutagen: 1.40.0
  - requests: 2.23.0
  - tqdm: 4.43.0
  - wrapt: 1.11.2
## environment 
  - GIT_PAGER: less --no-init --quit-if-one-screen
  - GIT_PYTHON_GIT_EXECUTABLE: /usr/lib/git-annex.linux/git
  - LANG: en_US.UTF-8
  - PATH: /home/yoh/proj/datalad/datalad-0.12.x/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200501+git61-g64e081d58-1~ndall+1
## location 
  - path: /home/yoh/proj/datalad/trash
  - type: dataset
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp: 
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.8.3rc1
## system 
  - distribution: debian/testing/bullseye
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 284
  - name: Linux
  - release: 5.6.0-1-amd64
  - type: posix
  - version: #1 SMP Debian 5.6.7-1 (2020-04-29)
</details>

**Comment by kyleam** [comment]
Hmm I tried with maint and master and didn't see a stall.  (That was with requests 2.22.0, but if I upgrade to 2.23.0, it still doesn't stall.)

<details>
<summary>output</summary>

```
/home/kyle/src/python/venvs/datalad/bin/datalad
datalad 0.12.6.dev20
> datalad create ds
[INFO] Creating a new annex repo at /tmp/dl-uCq9c8n/ds 
create(ok): /tmp/dl-uCq9c8n/ds (dataset)
> cd ds
> datalad download-url --archive http://www.onerussian.com/tmp/testzip.zip
[INFO] Downloading 'http://www.onerussian.com/tmp/testzip.zip' into '/tmp/dl-uCq9c8n/ds/' 
[INFO] Adding content of the archive /tmp/dl-uCq9c8n/ds/testzip.zip into annex <AnnexRepo path=/tmp/dl-uCq9c8n/ds (<class 'datalad.support.annexrepo.AnnexRepo'>)> 
[INFO] Initiating special remote datalad-archives 
[INFO] Finished adding /tmp/dl-uCq9c8n/ds/testzip.zip: Files processed: 2, +annex: 2 
download_url(ok): /tmp/dl-uCq9c8n/ds/testzip.zip (file)
add(ok): testzip.zip (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  download_url (ok: 1)
  save (ok: 1)
```

```
/home/kyle/src/python/venvs/datalad/bin/datalad
datalad 0.13.0rc1.dev25
> datalad create ds
[INFO] Creating a new annex repo at /tmp/dl-Japxi1f/ds 
[INFO] Scanning for unlocked files (this may take some time) 
create(ok): /tmp/dl-Japxi1f/ds (dataset)
> cd ds
> datalad download-url --archive http://www.onerussian.com/tmp/testzip.zip
[INFO] Downloading 'http://www.onerussian.com/tmp/testzip.zip' into '/tmp/dl-Japxi1f/ds/' 
[INFO] Adding content of the archive /tmp/dl-Japxi1f/ds/testzip.zip into annex AnnexRepo(/tmp/dl-Japxi1f/ds) 
[INFO] Initiating special remote datalad-archives 
[INFO] Finished adding /tmp/dl-Japxi1f/ds/testzip.zip: Files processed: 2, +annex: 2 
download_url(ok): /tmp/dl-Japxi1f/ds/testzip.zip (file)
add(ok): testzip.zip (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  download_url (ok: 1)
  save (ok: 1)
```

</details>

**Comment by kyleam** [comment]
`version: #1 SMP Debian 5.6.7-1 (2020-04-29)`

As an unrelated and unimportant note, the first issue in this repository has a lot of references thanks to wtf output.

**Comment by yarikoptic** [comment]
thank you @kyleam for trying!  I dug out the silent reason -- locking!

<details>
<summary>apparently I have a process in the background somewhere </summary> 

```shell
$> ls -ld /home/yoh/.cache/datalad/locks/downloader-auth.lck
-rw------- 1 yoh yoh 0 Mar 15 21:36 /home/yoh/.cache/datalad/locks/downloader-auth.lck
cached/staged changes:                                                                                         
 submodules.txt | 104 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
(dev3) 1 28049.....................................:Thu 14 May 2020 12:41:22 PM EDT:.
(git)lena:~datalad/trash[master]git
$> fuser /home/yoh/.cache/datalad/locks/downloader-auth.lck
/home/yoh/.cache/datalad/locks/downloader-auth.lck: 3973259
cached/staged changes:                                                                                         
 submodules.txt | 104 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
(dev3) 1 28050.....................................:Thu 14 May 2020 12:41:24 PM EDT:.
(git)lena:~datalad/trash[master]git
$> px | grep 3973259
yoh      3973259  0.0  0.1  60148 47588 pts/16   S+   10:58   0:02  |   |   \_ /home/yoh/proj/datalad/datalad-master/venvs/dev3/bin/python3 /home/yoh/proj/datalad/datalad-master/venvs/dev3/bin/datalad -l 2 download-url https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/2424540/NAPEN00/images/preventad_2424540_NAPEN00_fieldmap-phasediff_002.mnc/bids/sub-2424540_ses-NAPEN00_run-002_phasediff.json
yoh      4010475  0.0  0.0   6168   908 pts/17   S+   12:41   0:00  |   |   \_ grep --color=auto -d skip 3973259
```
</details>
I guess I am still "debugging it"... I think we need to 
- at least inform that there is a lock and we will wait for it to be released
- But also I am not sure why we (probably I) made that lock global, and not at least per repository and why lock at all -- need to investigating and making locking at least not that wide or may be even avoided where not really necessary.

**Comment by yarikoptic** [comment]
here is the commit which introduced that locking:

commit dbf3aa3afee10562080102c73033e82c644a244c
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Sun Mar 15 21:42:52 2020 -0400

    BF: downloaders - lock upon establishing connection and handling (re)authentication
    
    That would prevent multiple "login" prompts whenever git-annex requests downloads
    by our special remote in parallel.
    
    It might incure slight slow down to initiate the connection(s) since only one
    at a time would try, but IMHO it should not show any real impact since
    typically time should be spent in transfers since ware to wrangle large
    files primarily

**Comment by kyleam** [comment]
gh-4533 marked this as closed.  That PR was against maint has already made its way to master.  However, in order to trigger a close on merge to master, the commit message itself needs the closes/fixes cookie.

**Comment by yarikoptic** [comment]
thanks @kyleam .  I was trying to keep those to PR messages, but indeed probably for `maint` targetted commits, will do directly in commit messages (or may be it would propagate if it would be in PR title?)

**Comment by kyleam** [comment]
>  I was trying to keep those to PR messages

Just out of curiosity, why is that?

**Comment by yarikoptic** [comment]
I think because in the past it used to happen that the initial commit/attempt wasn't the final one which actually fixed the issue in the course of the pr development, and somehow I thought that it was our agreement to place those into pr description instead... With all the more frequent rebases etc I think I should stop doing that and indeed just about commits (and then possibly duplicate in a pr description for references?)

**Comment by kyleam** [comment]
> I think because in the past it used to happen that the initial commit/attempt wasn't the final one which actually fixed the issue in the course of the pr development

I see.

> and somehow I thought that it was our agreement to place those into pr description instead...

Ah, okay.  I wasn't aware.  I hope everyone doesn't mind if I continue to put the "closes/fixes" in the relevant commit.

> With all the more frequent rebases etc I think I should stop doing that and indeed just about commits (and then possibly duplicate in a pr description for references?)

I really was just asking out of curiosity.  Whatever you prefer is fine with me.
