### ISSUE TITLE
unittest for #452

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#454]
for PR #452

**Comment by hanke** [comment]
Not sure what could be tested here other than swallow_logs and logger. I'd prefer to have them unit-tested and not for each and every invocation. This PR doesn't add a new code path.

**Comment by yarikoptic** [comment]
Test needs to test that issue was solved -that there is no scary error msgs upon success, that there is a scary msg upon failure.

**Comment by yarikoptic** [comment]
ok -- screw it for now then... that code was RF'ed a bit more and at least there is a test now for no complaints about uuid -- would be tricky to generate a test whenever nothing is noisy now
