### ISSUE TITLE
When should `push` (NOT) add `--auto` to `git-annex copy`?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4550]
In https://github.com/datalad/datalad/pull/4541#issuecomment-629589141 I proposed that `--auto` should always be used, unless there is counter-evidence. This is a departure from what `publish` does (add `--auto` if `wanted` is set; https://github.com/datalad/datalad/pull/4541#issuecomment-629479069), and what `push` currently does (`not to_transfer and force not in ('all', 'datatransfer')`, which is problematic #4483, and doesn't make much sense in general).

@kyleam pointed out that `numcopies=1` has the potential to shoot us in the foot, if we do say `--auto` by default (https://github.com/datalad/datalad/pull/4541#issuecomment-629689667). `numcopies=1` is actually the default, and worse, it could be set on a per-file level. For this reason, it is not advisable to adopt the behavior of `publish`.

It felt attractive to me to say that a precondition for adding `--auto` internally is the absence of a `path` argument (a way of saying "you go figure it out"), but that would imply that any subselection of subdatasets to publish would not be possible. For my workflows this has negligible impact (if any), because hierarchies are typically shallow and homogeneous (subdatasets are either technical means of splitting a bigger monorepo, or all subdatasets are "data dependencies"/input). However, @yarikoptic's workflows might be completely different and may involve deep heterogeneous dataset hierarchies.

The more I think about it, the more attractive https://github.com/datalad/datalad/pull/4541 becomes, which made adding `--auto` explicit (ignoring the implementation details for now).

I am also still pondering the idea set add `--auto` unconditionally, and combine it with `numcopies=2` for the runtime of `push`. If one calls `push` they clearly want to transfer information. However, that may cause undesired interactions with tailored wanted expressions where file content might be copied without a desire to have that done. But this part is still too fuzzy to me.

In any case the test included in #4541 should be salvaged (thx @kyleam )

**Comment by yarikoptic** [comment]
I (or someone else) yet to double check interaction between numcopies and wanted - if I set wanted to exclude some files, would they still be copied over if numcopies>1? That would undermine effort to avoid distribution of sensitive data

**Comment by yarikoptic** [comment]
I was not sure if I should create another issue or it is just manifestation of absence of `--auto` treatment which is discussed here, but 

<details>
<summary>here is a test script (ATM wouldn't even complete running since `push` would somewhat rightfully exit with non-0 ATM due to wrong IMHO behavior)</summary> 

```shell
$> cat check-push-content.sh                                                               
#!/bin/bash

set -eu
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"

datalad create src

(
cd src
# Produce and annotate some data
echo -e '\x00' > data.0
echo -e '\x01' > data.1
echo -e '\x02' > data.2
datalad save -m "added some files"

# Dropping a file to mimic a case of simply not having it locally (thus not to be "pushed")
git annex drop --force data.2

# Annotate sensitive content, actual value "verysecure" does not matter in this example
git annex metadata --set distribution-restrictions=verysecure data.0

datalad save -m "added a file"
datalad create-sibling --annex-wanted "not metadata=distribution-restrictions=*"  -r -s target ../target
datalad push --to target
)

(
cd target
git annex list
)
```
</details>

 which visualizes the main issue of `wanted` to be completely ignored
- all files are "Slated" to be transfered
- the `secure.2` which is not really intended to be transferred (if `wanted` was consulted), and which lacks content locally -- causes a WARNING to be issued.

The only way to avoid the warning probably would be to resort to calling `annex find` (as we do in `AnnexRepo.copy`) as to see what files are not intended to be transferred to start with

**Comment by kyleam** [comment]
> I (or someone else) yet to double check interaction between numcopies and wanted

My understanding is the transfer happens if either numcopies or preferred content says "do it".  Quickly, that seems to be the case.

> if I set wanted to exclude some files, would they still be copied over if numcopies>1?

Yes.

**Comment by yarikoptic** [comment]
Than you! I better never use it then ;-) for completeness: there is `copies` I could probably use in preferred content to accomplish the mission where needed in consideration with metadata based restrictions

**Comment by kyleam** [comment]
Resolving what the default data transfer behavior is (gh-4551) seems crucial for deciding what to do with `--auto`.  If the decision is to follow `publish` and lean towards not transferring data by default, then adding `--auto` unless data transfer is explicitly requested or disabled via `force` would give behavior that is pretty close to `publish`s default behavior, I think.

On the other hand, if we stay with transferring data by default, adding `--auto` would essentially go against that desire, for the reasons @mih gives.  Of the proposed solutions, I think adding `--auto` (or some way to explicitly request it) is the simplest conceptually, though it is a bit ugly in that giving it would be incompatible with several values of `force`.  For the `numcopies=2`/`--auto` solution, I think the interaction mentioned is indeed a big problem; if the user has crafted their preferred content expressions to avoid transfer, `numcopies=2` would surprisingly force it.

**Comment by mih** [comment]
Given that I opened this issue, I will close it now. We have an open PR #4581 and the discussion continues in #4483 #4602 #4603 #4604
