### ISSUE TITLE
OpenNeuro unindex datasets

### ISSUE THREAD

**Issue by franklin-feingold** [datalad/datalad#4564]
Hey Datalad team!

Flagging over here that there are several datasets that have been removed from OpenNeuro and I wasn't sure if they needed to be manually unindexed on Datalad or if deleting the GitHub repository is all that is needed. The associated GitHub repositories have been removed.

Thank you!

**Comment by yarikoptic** [comment]
ATM it would be manual.  Do you have a list of them? ;-) (ok if not -- just would need to code for that; if there is a list could quickly prune)

**Comment by franklin-feingold** [comment]
yep! here it is - some may have already been unindexed but wanted to ensure so! thank you @yarikoptic !

```
ds001165
ds001219
ds001393
ds001493
ds001505
ds001512
ds001544
ds001568
ds001611
ds001650
ds001750
ds001782
ds001851
ds001900
ds001934
ds001985
ds001996
ds002036
ds002068
ds002070
ds002078
ds002171
ds002222
ds002245
ds002317
ds002319
ds002337
ds002509
ds002572
ds002653
```

**Comment by yarikoptic** [comment]
done, and while at it also fetched newer ones, see http://datasets.datalad.org/?dir=/openneuro

**Comment by franklin-feingold** [comment]
woo! looking great!! thank you @yarikoptic !
