### ISSUE TITLE
Standardize handling of .git for submodules.

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#457]
Currently, `.git` of a submodule can end up in various shapes and forms depending on the particular procedure used. It can be:

1. a .git file
2. a symlink to ...../.git/modules/...
3. an actual .git directory

A symlink sometimes leads to a problem: http://git-annex.branchable.com/bugs/git-annex_confuses_Git_with_nested_submodules

but in general all three scenarios seems to work. However, we should discuss which option we are standardizing on (if anyhow possible). Current `install()` implements platform assumptions for `.git` handling that are invalid and ignore direct mode peculiarities.

A solution to this issue would help identify the proper fix.

**Comment by hanke** [comment]
Resolution from conference: have .git be a standalone directory in the submodule.

**Comment by debanjum** [comment]
yarik : it was addressed already afaik
