### ISSUE TITLE
[INFO] Clear progress bars [INFO] Refresh progress bars on 0.13.0rc2

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4570]
#### What is the problem?
Just a quick report. I run the following code to search for missing local annex files:
```bash
echo "Searching for missing files" ; \
datalad -f json status --recursive --annex all | \
jq '. | select(.has_content == false).path'
```
Works as before on 0.12.7, but shows the following messages in 0.13.0.rc2
```bash
[INFO] Clear progress bars
[INFO] Refresh progress bars
[INFO] Clear progress bars
[INFO] Refresh progress bars
[INFO] Clear progress bars
[INFO] Refresh progress bars
[INFO] Clear progress bars
```
Not sure if this is just temporary code you put to debug stuff, but just wanted to report it for now.

#### What steps will reproduce the problem?
See above.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
See above.

#### Is there anything else that would be useful to know in this context?
No

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Yes

**Comment by mih** [comment]
Thx for the report. This is an undesired and unexpected side effect of #4555. And now that you reported it, it is completely obvious :(

**Comment by kyleam** [comment]
The `noninteractive_level` parameter of `log_progress` could be used here.

**Comment by mih** [comment]
Thx @kyleam!
