### ISSUE TITLE
`SQLite3 returned Error`

### ISSUE THREAD

**Issue by soichih** [datalad/datalad#4571]
On datalad 0.12.6 running on Ubuntu 18.04, I sometimes ran into an error message that looks like the following.

```
[WARNING] realpath of PWD=/mnt/wrangler/dev1/5ec9e6767a9c5c28447d7f05/5ec9e6767a9c5c28447d7f06 is /mnt/wrangler/dev1/5ec9e6767a9c5c28447d7f05/5ec9e6767a9c5c28447d7f06 whenever os.getcwd()=/mnt/datalad/OpenNeuroDatasets/ds000253. From now on will be returning os.getcwd(). Directory symlinks in the paths will be resolved 
[WARNING] Running get resulted in stderr output: git-annex: get: 1 failed
 
[ERROR] Remote is configured to use versioning, but no S3 version ID is recorded for this key
| SQLite3 returned ErrorBusy while attempting to perform close: unable to close due to unfinalized statements or unfinished backups [get(/mnt/datalad/OpenNeuroDatasets/ds000253/sub-02/anat/sub-02_T1w.nii.gz)] 
```

Normally, when I just rerun the datalad get, it completes successfully so I believe this is just a transient problem.

**Comment by kyleam** [comment]
What version of git-annex are you using?

git-annex v7.20191009 contained 9628ae2e6 (Close sqlite databases more robustly, 2019-09-26), which I think should mitigate these `ErrorBusy` exceptions.  Although that version is above datalad's minimum git-annex version, it's pretty old, so I'd guess your version is more recent.

The only git-annex issue that I see that contains `ErrorBusy` is the one that led to the commit above: <https://git-annex.branchable.com/bugs/crippled_filesystem__58___SQLite3_returned_ErrorBusy/>.

**Comment by yarikoptic** [comment]
re SQLite3: what version of git-annex?

Re "S3 version ID": see https://github.com/OpenNeuroOrg/datalad-service/issues/79#issuecomment-444347357 -- I guess still was not resolved for  some datasets. `ds000253` indeed still has no .rmet files in git-annex branch
```
(git-annex)lena:/tmp/ds000253[master]git-annex
$> git ls-tree -r --name-only git-annex | grep rmet
```

**Comment by yarikoptic** [comment]
@soichih I will close this one, most likely it is an issue with git-annex, and most likely addressed since then.  Feel welcome to reopen if some recentish git-annex gives you the same trouble
