### ISSUE TITLE
Slides and info on long term plans for Datalad?

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4576]
#### What is the problem?
I need to present my work on data federation in a few days. Among other things, I plan to introduce Datalad and show why this is the winning bet for now and the future. Besides the technical approach which is clear to me, I need to give a layout of the future. So far, I only know Datalad comes from a USA-German collaboration, but not much else. Where can I find some more details on 
how many people work on it (full time, part time?), how much funding it currently has, and how long there is funding to keep going on. That is, I am trying to get a long term view of where datalad is going with some concrete details to back up my personal enthusiasm.

Also, is there any set of slides from past presentations I can borrow? I found some slides from @adswa [here](https://github.com/datalad-handbook/course/tree/master/talks), not sure if there is something else.

Another question:
Are HCP and UK Biobank datasets fully up for retrieval via datalad now?

#### What steps will reproduce the problem?
N/A

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
N/A

#### Is there anything else that would be useful to know in this context?
N/A

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
This is it :)

**Comment by mih** [comment]
Few details from my POV: I think DataLad is pretty well positioned at this point. On the German end funding is solid for the next 3 years (the core US-German collab grant, and two large EU consortia that fund work on DataLad as an infrastructural components). Another consortium is forming with a 5-10y lifespan. In my group 5 people's funded work is closely related to DataLad (3 of which have software development as their key task). This will likely increase over the next months. We do not track usage, but DataLad is part is 2 collaborative research center grants that I am aware of (~100 people each, which is also roughly the size of our institute), plus the usage within the consortia.

**Comment by dorianps** [comment]
Thank you @mih

How long have datalad been in the making?
Is there a timeline to end the development stage and release v1?
Where can I find info on the consortium that is behind datalad development, i.e., is it this NIH-DFG funded or some other agency/foundation?
What about the HCP, UKbiobank datalad datasets, are they already up?

Dorian

P.s. I am not concerned about usage. The only minor concern for me was to see git-annex being dropped by gitlab and likes in favor of lfs. But I am not of the field and assume git-annex keeps chugging as long as you actively rely on it and Joey keeps working on it. As I said, minor concern only.

**Comment by mih** [comment]
> How long have datalad been in the making?

First funding come in 2014. Prototype existed before.

> Is there a timeline to end the development stage and release v1?

Absolutely! But @yarikoptic keep this info secret ;-)

> Where can I find info on the consortium that is behind datalad development, i.e., is this NIH-DFG funded or some other agency/foundation?

The collab between @yarikoptic and me within the CRCNS program is the seed (see bottom of https://www.datalad.org/about.html), but on top of that funding is versatile from different sources....which is a good thing ;-)

> What about the HCP, UKbiobank datalad datasets, are they already up?

Yes, kinda...

HCP (full): https://github.com/datalad-datasets/human-connectome-project-openaccess (needs 0.13 to work with properly)

Thx to @adswa there are tailored subsets available (need 0.13 to build, but any recentish datalad is good enough to consume):

- https://github.com/datalad-datasets/hcp-structural-preprocessed
- https://github.com/datalad-datasets/hcp-functional-connectivity
- https://github.com/datalad-datasets/hcp-structural-connectivity

UKB datasets cannot be published (terms forbid), but there is an extension to roll your own: https://github.com/datalad/datalad-ukbiobank

> P.s. I am not concerned about usage. The only minor concern for me was to see git-annex being dropped by gitlab and likes in favor of lfs. But I am not of the field and assume git-annex keeps chugging as long as you actively rely on it and Joey keeps working on it. As I said, minor concern only.

Let's say that we are very much aware that git-annex is something that must be well maintained ;-)

**Comment by yarikoptic** [comment]
> > Is there a timeline to end the development stage and release v1?
> 
> Absolutely! But @yarikoptic keep this info secret ;-)

Following our PyMVPA legacy - might never happen and we would just jump to v2 ;)  Do you have any specific expectations from v1 @dorianps ?

Re slides: checkout https://github.com/datalad/artwork and linked there submodules.  Since github would not really show html slides shows, you could instead browse http://datasets.datalad.org/datalad/artwork so some talks would immediately have visible slide shows e.g. http://datasets.datalad.org/datalad/artwork/talks/2019-mila

**Comment by yarikoptic** [comment]
Re scales of development/adoption in Americas: our team at Dartmouth is smaller ([we are hiring - consider joining!](https://searchjobs.dartmouth.edu/postings/54423)), about 2 FTE ATM between me and @kyleam directly on DataLad and related to ReproNim parts of the project.  Necessary git-annex developments and maintenance by Joey are also funded. It is also a backend tech for OpenNeuro and Canadian Open Neuroscience Platform (https://github.com/CONP-PCNO); and is integrated with BrainLife.io.  DataLad is already used in many ReproNim devleopments (heudiconv, reproman, repronim/containers, etc) and there will only be more integrations in the future.

**Comment by yarikoptic** [comment]
> The only minor concern for me was to see git-annex being dropped by gitlab and likes in favor of lfs.

The unique features of LFS (inability to remove content from the remote; centralized server) are too seductive for businesses ;-) Meanwhile -- we can still use git-annex with LFS, see e.g. http://handbook.datalad.org/en/latest/basics/101-138-sharethirdparty.html?highlight=LFS#use-github-for-sharing-content

**Comment by dorianps** [comment]
> Do you have any specific expectations from v1 @dorianps?

Not really, it's usually a good sign when the software gets out of alpha/beta stage. But I know a lot of reliable software that are used a lot which keep staying in dev status (including my R packages). And I know you are still deciding what to keep and what to throw (i.e. publish/push). But on the other hand, I have been thinking that for long term data archiving, one should keep a singularity version of datalad, just to make sure the handling of the data is reproducible the same way I store the containers of fmriprep, etc.

Thanks for all the tips. Will close the issue in 1-2 days.
