### ISSUE TITLE
Let's establish a roadmap toward 1.0 release?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4585]
I think it would benefit us if we kick out 1.0 some time soon (e.g. this year) with some guarantees (so truly follow semver upon those components API changes) of API.  As touched upon in recent call, I would say we could restrict guarantees to the `datalad.core` and `datalad.coreapi` (and only at the top level, i.e. not propagating to `.repo` etc which comes from `.support`). 
ATM I think `coreapi` is too "bloated"

```shell
$> python -c 'import datalad.coreapi as dlcore; print([x for x in dir(dlcore) if not x.startswith("_")])'
['Dataset', 'add_archive_content', 'aggregate_metadata', 'annotate_paths', 'clean', 'clone', 'copy_file', 'create', 'create_sibling', 'create_sibling_github', 'create_sibling_gitlab', 'create_sibling_ria', 'create_test_dataset', 'diff', 'download_url', 'drop', 'export_archive_ora', 'extract_metadata', 'get', 'install', 'ls', 'metadata', 'publish', 'push', 'remove', 'rerun', 'run', 'run_procedure', 'save', 'search', 'siblings', 'sshrun', 'status', 'subdatasets', 'test', 'uninstall', 'unlock', 'update', 'wtf']
```
e.g. all the metadata related functionality (`search` included) should not be there since I expect it to be sooner than later superseded by metalad (approach). Also depending on `publish/push` interactions etc, `publish` might be gone (or not), and similarly `install`.  I still think that we by 1.0 might come up with a solution to avoid breeding `_flavor` commands (i.e. of `create_sibling` family). 

By then we also establish a policy that no new modules/interfaces are added directly  to `.core` while being developed, unless they are released in some MAJOR.MINOR release for a while; and only then moved to `.core` to announce that indeed their API stabilized.

To orchestrate 1.0 release effort I have initiated ["Release 1.0"](https://github.com/datalad/datalad/projects/11#card-39084742) project, while milestones could still be used to annotate any specific issue/pr for "minor" `0.` releases they would actually appear in.

**Comment by mih** [comment]
I am skeptical re "this year", but I think having a roadmap would be instrumental. Thank you for the initiative!

I would prefer, if we start engaging in the process with an expectation to draft and than repeatedly refine a roadmap, rather than with the idea to sit down once and set something in stone. Also there are a bunch of TODOs with quite some uncertainties re timing and nature of their resolutions (drop/uninstall/remove, commands that use pre-AnnotatePath interface conventions, AnnotatePath). for me, a major theme of 1.0 needs to be "fewer corpses in the basement" ;-)

**Comment by yarikoptic** [comment]
> a major theme of 1.0 needs to be "fewer corpses in the basement" ;-)

if the basement `.core` -- totally agree ;)  I also agree it would be a good thing in general, but I would not make it an ultimate goal for 1.0 -- would delay it etc.  I think providing a release with at least limited promise such that `.core` and `.coreapi` are stable and have no corpses would already be very valuable. It would be ok with me to have some corpses outside (in `.support` etc) if that would minimize breakage of externals etc.  The laudable goal of killing all corpses could be stretched through a number of major releases. Having said that if someone sees a way to kill them all at once without major pain and suffering - great.

**Comment by yarikoptic** [comment]
> Also there are a bunch of TODOs with quite some uncertainties re timing and nature of their resolutions (drop/uninstall/remove, commands that use pre-AnnotatePath interface conventions, AnnotatePath)

IMHO, if we would like to establish some baseline of 1.0 release, we could just move those out of the `core` and proceed.  IMHO it is better to provide some, even if not fulfilling all "core" use cases, baseline `core` than wait for the "ultimate" one.

**Comment by yarikoptic** [comment]
Thank you @kyleam , that clarifies `coreapi` history/purpose. Let's continue in https://github.com/datalad/datalad/issues/4590 on that

**Comment by mih** [comment]
Someone has introduced an issue label that seems relevant here: https://github.com/datalad/datalad/labels/corpse-in-basement

**Comment by yarikoptic** [comment]
See above https://github.com/datalad/datalad/issues/4585#issuecomment-636069620

**Comment by adswa** [comment]
Can we integrate the any points that are still relevant from this issue into #6247 and close this one?

**Comment by adswa** [comment]
I believe I have distilled the main points from this issue into #6247 (which is a more recent revival of the same question). I'll close this issue in favor of the newer discussion.
