### ISSUE TITLE
[helpme] add integration into interactive UI

### ISSUE THREAD

**Issue by vsoch** [datalad/datalad#4588]
After #4586 is merged, we would want to also add this functionality into the Datalad Interactive UI (which I have not seen / tested yet!) Details here: https://github.com/datalad/datalad/pull/4586#pullrequestreview-420576966

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
