### ISSUE TITLE
Decide on destiny of .repo (and *Repos)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4589]
Before we discuss details I see two major possible options to try to decide on for 1.0 under assumption that `.core` will be providing a stable API:

- :+1: make `Dataset` s `.repo` protected (`._repo`) to hide the corpse and do not worry much about *Repos
- :smile: keep `.repo` "public" but make it use only `core.**repo.py` classes
- :-1: I don't care

I am not considering following option(s) as viable:
- Document that `.repo` is supposed to be considered "protected" and not used outside of the DataLad code base

Please vote. If there is another high level approach I have missed, please add

**Comment by mih** [comment]
Related re core Repo classes: https://github.com/datalad/datalad/issues/3988

**Comment by yarikoptic** [comment]
well, decision was kinda made ;-)
