### ISSUE TITLE
WTF: must not fail entirely whenever somehow incompatible extension is installed 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4599]
See https://github.com/datalad/datalad/pull/4583/checks?check_run_id=717057520 for https://github.com/datalad/datalad/pull/4583/files .

**Comment by adswa** [comment]
Sadly, the logs for this are expired :(

**Comment by mih** [comment]
I have tried this by intentionally breaking an extension I had installed locally. This results in:

```
% datalad wtf
...
  - mihextras: 
    - load_error: name 'broken' is not defined [__init__.py:<module>:1]
...
```

`wtf` performs otherwise normally under these circumstances, and also other installed extensions are reported properly.

Given that the original logs are lost, I'd say we can close this issue.
