### ISSUE TITLE
Connection with NeurotechX Community

### ISSUE THREAD

**Issue by xloem** [datalad/datalad#4601]
Hey,

I noticed you guys maintain a huge dataset of open brain data.  I went on your website looking for a community and found this github.

I wanted to make sure you knew about the NeuroTechX community of brain hackers, researchers, and hobbyists.  There are literally thousands of people across the world on their slack; the form to join is at https://docs.google.com/forms/d/e/1FAIpQLSfZyzhVdOLU8_oQ4NylHL8EFoKLIVmryGXA4u7HDsZpkTryvg/viewform and their website is at 
https://neurotechx.com/ .

I hung out on neurotechx some years ago and there was no mention of datalad.  People were actually starting their own, smaller projects to open source their brain research data, at that time.  I was just thinking of this and wanted to make sure I addressed the situation.

**Comment by yarikoptic** [comment]
Thanks for reaching out! There is indeed many specialized "brainy" communities out there! Virtually impossible to become an active member in all of them, but it would be great if existing active members established the bridges between ;-)  If you are still part of it, we would highly appreciate if you disseminate information about datalad to NeurotechX - then it also would not look like self promotion if it was done by us. We will be happy to hear about use cases and possibly features still needed in the scope of interests to NeurotechX.

Cheers

**Comment by xloem** [comment]
Thanks.  I don't really have any presence in that community but I can throw a link into the chat.  What other communities are there?
