### ISSUE TITLE
push: --force=onlywanteddatatransfer

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4602]
I still wonder how I could use new place in my workflow without major changes to existing Datasets. Could such (or is there a better name?) force mode be considered, which would mimic current publish behavior (no data transfer unless there is a wanted setting, and then --auto) in case of no paths provided?

**Comment by mih** [comment]
With the exploding number of issue it gets harder and harder to keep track of the discussion for me. It would help to outline why this new proposal should be preferred over the implementation of our discussion results included in https://github.com/datalad/datalad/pull/4581

It looks to me as if the major difference is that `onlywanteddatatransfer` cannot be combined with `gitpush`.

It seems as if with #4602 the desired behavior is achievable with:

`datalad datalad.push.copy-auto-if-wanted=true push ...`

The only difference being that this behavior is only desired here when no paths are provided. However, I thought that we have established that providing paths or not has no undesired effect on `--auto`. So why is the complication necessary?

If it is necessary, should giving `--force=onlywanteddatatransfer` _and_ one or more paths result in a `ValueError`?

**Comment by yarikoptic** [comment]
I don't care about paths. I care that I cannot use `push` to "mimic current publish behavior (no data transfer unless there is a wanted setting, and then --auto) in case of no paths provided?" with any combination of options and "forces" ATM afaik, because I can only force nodatatransfer, but because it means no annex copy call, that added config would have no effect on that case of I get it right. I will check on example when wake up
