### ISSUE TITLE
push: yet another round on the interface, but with a new twist

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4604]
Decided to not pollute #4581 or any other prior discussion thus filed separately

Current `--force` options are already non orthogonal (impossible to use `no-datatransfer` and `datatransfer` together).  I think it would be great to reserve `--force` for tune ups to specific git or annex actions (like `gitpush` already and possibly `no-annexfast`  #4603)  while making a dedicated option to define the data transfer mode, and just change the default to follow @mih's desire for the new "right thing" behavior (#4551) to copy annexed data by default.  Moreover, while going through such RFing - we gain a chance to align it with git-annex a bit more.

What if we add the same option as `publish` has -- `--transfer-data` with following possible values:

- (default) "anything" -- transfer any file not available on remote
- (previous `publish` behavior) "nothing" -- transfer nothing
- "auto" -- pass `--auto` to `annex copy` to satisfy "wanted" expression for the remote if any, and otherwise transfer nothing (note: it would also respect a possible `numcopies` setting).

"anything" and "nothing" from above - are wanted expressions of annex.  Further documentation could point to `--annex-wanted` of `create-siblings` (and may be `siblings` if exposed there) to hint on how it could be tuned to automate.

`--fast` will be used, and could be removed via `--force` option.

I do  like an idea of configurable default `push` data transfer behavior discussed in #4581 .

Later we could expand the list if any additional specific desire, but specific for data transfer, not fusing it into the list of `forces`.

**Alternative** to `--transfer-data MODE` is to align with current `get` and its `-n|--no-data`, and also introduce `-a|--auto-data`.

edit1: "annex-auto" -> "auto", and added `get` inspired alternative

**Comment by mih** [comment]
I am mentally dead right now, so only briefly: the reason that we do not have transter-data anymore is the cumulative effect of all issues fixed by push.

Also there is no desire for all force modes to be orthogonal, they are no more than mutually exclusive.

**Comment by yarikoptic** [comment]
I am not suggesting to adopt transferdata implementation from `publish`.  I merely suggest to RF interface - implementation should stay the same (just use `data_transfer` option instead of force modes).  Would a PR help to illustrate? (could try on weekend or so)

**Comment by bpoldrack** [comment]
I currently lean towards agreeing with @yarikoptic. I do see value in having modes rather than a number of switches whose combinations can lead to nonsense, but I have a hard time imagining invalid combinations in that case. If we have `--force [gitpush|no-annexfast|all]` and `--datatransfer [anything|nothing|auto]`, I can't see actually invalid combinations, apart from `--force no-annexfast --datatransfer nothing` looking strange (I'd still think it's clear that `nothing` is the decisive thing in that case, therefore no ambiguity to me). Plus: I'm not sure `no-annexfast` is a good name, but `--force datatransfer --datatransfer none` would be worse.

The main point, however, is that the question what (if any) data to consider is indeed orthogonal to whether or not use `git push --force` and `git annex copy --fast`. The alternatives would be to have a lot more combinations as force-modes or to declare that datalad-push can be used to force-push or to not transfer data and that those things are different layers, but if you want both you need to use git and git-annex directly and you cannot make use of `publish-depends` or `--since` or sth like that.
The latter doesn't sound convincing to me and the former is possible, but I suspect I would not be able to remember the meaning of any of those modes if their number grows significantly.

**Comment by yarikoptic** [comment]
> is indeed orthogonal to whether or not use `git push --force` and `git annex copy --fast`

I had not thought about this one BTW, we might want a slight doc tune up to state to what  `--force gitpush`  applies to - only current branch being pushed or also push of `git-annex`. But I think `--fast` or not is orthogonal here - `--fast` just avoids check on the remote but still should make a record in local `git-annex` branch information about availability (before our `push`, which could be forced or not)

**Comment by bpoldrack** [comment]
> But I think --fast or not is orthogonal here - 

Yes, but that's covered within the existing `force` modes (you can have both or one of them or none). However, those kinds of switches that propagate to underlying `git/git-annex` commands tend to quickly lead to ambiguous combinations if exposed independently. So, I agree with @mih, that it's better to support specific combinations by means of such modes. My point is, that even for non particularly git-(annex)-aware users, the distinction between history considerations and data considerations does make sense for push. We try to make clear that those are two different things anyway (how else to explain `get` and `-n`, `drop`, etc.).

**Comment by yarikoptic** [comment]
>  So, I agree with @mih, that it's better to support specific combinations by means of such modes

As long as it is possible with a clear inambigous association -- sure.  But insofar the "clear" ones are only "nodatatransfer" (== "do not call `annex copy`) and "gitpush" (note -- it is 1-to-1 mapping to git option). "datatransfer" - is not really that, it is just == "do not add --fast" (#4603), and does not necessarily force datatransfer. 
Overall, IMHO, it is just another reflection of a desire to make "datalad" to pretend to be "self-sufficient", without exposing any git/git-annex. And again, I think it is too utopian of an idea to achieve, and that is reflected through the evolution of development, and a wide variety of use cases etc which require direct calls to `git` and `git-annex`. IMHO DataLad should strive to be what  we often claim - a "thin layer" on top of git/git-annex (and singularity/docker in -container) to facilitate their use to address (meta)data management use cases. I do not mind "modes" where a clear combination of options to pass to git/git-annex, but here it seems to be not the case. Also when modes are orthogonal ("gitpush" vs "*datatransfer") IMHO it is better to keep them separate. Note that `--force` in my perception is a flag/option as a measure of the last resort, not something I should get accustomed to call to "do the right thing" .

**Comment by bpoldrack** [comment]
As I said earlier, I agree with your original post. Last comment was just about not splitting up current `force` even further. We can argue about the name - doesn't have to be `force` as far as I'm concerned. So, I stick to:

| If we have --force [gitpush|no-annexfast|all] and --datatransfer [anything|nothing|auto] ...

being my currently favored solution with no strong opinion on whether the former should be called `force`. :)

**Comment by yarikoptic** [comment]
BTW, reflecting on my comment -- "annex-auto" mode cannot even be named "wanted" since `annex copy --auto` is effected by both `wanted` and `numcopies` setting (#4605) - another demonstration that coming up with "our" modes is tricky... I guess it could be "wanted" if then we also add `--numcopies 1` to `copy --auto` as @kyleam suggested in #4605 though; but it would be fragile in case if annex decides to add some additional parameter handling to `--auto` mode, thus we better not.

Another related aspect which I forgot is `datalad get`.  ATM it has two modes: by default get data, and then do not call `annex get` with `-n|--no-data`.  Ideally we should aim to make `push` and `get` consistent in their options on data transfer.  If I was not demanding some support for `annex copy --auto`, `push` should have just got `-n|--no-data` (instead of `--force nodatatransfer`, while retaining the force option to avoid `--fast`). But note that `datalad get` does not yet expose possibility for `annex get --auto` ATM - I believe nobody of us needed that functionality so far, but it is available, and might be desired: I just forgot about it, but could set the same wanted for local clones where I do not even want to obtain unwanted sensitive data.

**Comment by yarikoptic** [comment]
> --datatransfer [anything|nothing|auto]

Just noted that you used "auto" not "annex-auto" as I originally mentioned.  I was afraid that with pure "auto" we might suggest some of "our" auto mode like we do now in `publish`.  But indeed, if it is just a translation 1-to-1 to adding `--auto` to `annex copy` -- makes total sense and shorter, so I would go with it ;)

**Comment by kyleam** [comment]
> I guess it could be "wanted" if then we also add `--numcopies 1` to `copy --auto` as @kyleam suggested in #4605 though

To be clear: I only suggested it in the sense that it was included in my "here are some possibilities for ways to deal with this" section.  I don't think it's a good idea for a few reasons, including the required content that I mentioned in the same post.  As I've said, I think it's a mistake that `publish` inspects `wanted`.  I think there should simply be a flag or some other way for the caller to say "pass --auto to annex".

**Comment by yarikoptic** [comment]
> ... aim to make push and get consistent... `push` should have just got `-n|--no-data`

and `-a|--auto-data` of cause ;)  but that is where the hit for multiple options for the same "mode", and thus desire for a "mode" option to make it more consistent and expandable.  Short options though are too convenient to let go off them...

**Comment by bpoldrack** [comment]
> but that is where the hit for multiple options for the same "mode", and thus desire for a "mode" option to make it more consistent and expandable.

Exactly. Let it go ;-)

**Comment by mih** [comment]
Trying to catch up with the discussion. @yarikoptic Is it correct that this one supersedes #4602 and #4603?

**Comment by yarikoptic** [comment]
It is a better alternative to #4602.  #4603 is orthogonal (force applicable to any possible annex copy invocation )

**Comment by kyleam** [comment]
I think we can consider this closed with the merge of #4620.  Please reopen if I'm mistaken.
