### ISSUE TITLE
Support reading config variable definitions from extensions

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4611]
There is a plan to be able to generate documentation and query information from `common_cfg.py`. This will be of limited utility unless corresponding info is obtained from installed extensions as well.

We would only need to support reading the same structured information from a predefined location in an extension.

**Comment by yarikoptic** [comment]
Why extension didn't just expand/alter the dict I place?

**Comment by mih** [comment]
I am closing this one in favor of the slightly more elaborate https://github.com/datalad/datalad/issues/5769
