### ISSUE TITLE
Callout Regarding Police Brutality Archival

### ISSUE THREAD

**Issue by xloem** [datalad/datalad#4612]
There is a lot of ongoing police brutality and people are archiving video evidence of it at places like https://github.com/pb-files/pb-videos .  Evidence like this is unfortunately often lost.

Is anybody familiar with datalad able to help coordinate starting to consolidate the mirror systems together into one updatable git repository that is easy to mirror?  It seems it can take some time to learn datalad for the first time, and current events are developing.

**Comment by yarikoptic** [comment]
!!! Brilliant idea! I was wondering if how we could help... We could indeed establish such a dataset with supporting materials, having at least a local backup to guarantee availability etc. If we publish videos files as well eg on datasets.datalad.org, although without a convenient viewer, they should be viewable without any datalad knowledge.
Is there may be already a page which collected relevant references/URLs?

**Comment by yarikoptic** [comment]
Found your https://github.com/xloem/police-brutality . Didn't grep yet, but if you make it into a git annex repo with all relevant YouTube videos added etc, I could mirror its on datasets.datalad.org

**Comment by yarikoptic** [comment]
Twitter posts with screenshots could go straight into git but might be worth to add to annex for metadata annotation, and keeping repo more lightweight.

**Comment by xloem** [comment]
The tech friends of the moderators of the subreddit linked from https://github.com/2020PB/police-brutality are coordinating the face of that stuff since their reddit is so active.  Here's a reference to some ongoing work: https://github.com/2020PB/police-brutality/issues/315#issuecomment-640163911 .  Does datalad support any kind of web publishing itself?

The repo of mine you found was just a fork for a PR but I may have some time to work on this in upcoming days.

**Comment by yarikoptic** [comment]
https://github.com/2020PB/police-brutality seems to be doing well even without DataLad, not clear what changes in DataLad are needed to assist, so I will close this.  If any particular new feature desired, please let us know

**Comment by xloem** [comment]
Thanks for looking at this.

The assistance wasn't changes in datalad: it was somebody experienced with using it.

Most of the hosts for the police brutality repository are on servers that could mutate data, links, or served content if given police order to do so.  In my opinion, Datalad's functionalities could have really aided in reducing that concern, but I'm not familiar with using it.  That's all.
