### ISSUE TITLE
RIA subdataset install "broken" by early success

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4613]
Demo:

```
% datalad clone ria+http://rs.ds.inm7.de#~super all_rs_data
% cd all_rs_data
% datalad get eNKI/sub-A00008399
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore                        
[INFO   ] Configured RIA store not found at ria+file:///ds/rs/srv                            
install(ok): /tmp/all_rs_data/eNKI (dataset) [Installed subdataset in order to get /tmp/all_rs_data/eNKI/sub-A00008399]
Total (0 ok, 4 failed out of 4):   0%|                            | 0.00/207M [00:00<?, ?B/s][WARNING] Running get resulted in stderr output: git-annex: get: 4 failed
 
                                                                                             [ERROR  ] not available; Try making some of these repositories available:;      019b3420-fc32-4984-93c6-b79a705511a2 -- mih@bulk1:/ds/rs/incoming/eNKI;      38cb587d-c7ec-4228-a8a2-a1abec89331a -- inm7-storage; ; (Note that these git remotes have annex-ignore set: origin) [get(/tmp/all_rs_data/eNKI/sub-A00008399/ses-DS2/Confounds_sub-A00008399_ses-DS2.mat)] 
...
```

The ora special remote config doesn't work `ria+file:///ds/rs/srv` so a reconfiguration should have been triggered, but wasn't. The reason is this:

```
% git grep -A 3 'submodule.*eNKI' -- .gitmodules |cat
.gitmodules:[submodule "eNKI"]
.gitmodules-    path = eNKI
.gitmodules-    url = http://rs.ds.inm7.de/23e/45ab0-a588-11ea-8ccf-a0369f287950
.gitmodules-    datalad-id = 23e45ab0-a588-11ea-8ccf-a0369f287950
```
The URL recorded in `.gitmodules` is actually functional and is tried before the configured RIA lookup:

```
% git config datalad.get.subdataset-source-candidate-origin
ria+http://rs.ds.inm7.de#{id}
```

Not sure which way would be best here. The problem is caused by the facts that I used

```
datalad clone -d^ ria+http://rs.ds.inm7.de#23e45ab0-a588-11ea-8ccf-a0369f287950 eNKI
```

when adding the subdataset originally -- which get's resolved to the working http URL above. I could simply not do that and use a local clone path. or we change the lookup order to prefer datalad config sources over `.gitmodules`.

Please let me know what you think @datalad/developers so we can fix this for 0.13 (either by changing code or documenting the issue and leaving written advice on how to avoid this, probably in the handbook).

**Comment by bpoldrack** [comment]
Generally agree - it's somewhat weird as well as somewhat correct. :)

Solution is certainly not to change order from my point of view. We want stay aligned with git. If we start considering different URLs then git itself does *first*, we kinda break the paradigm that things git and annex consider valid, stay valid for datalad.

There could be a different solution by code change, though:
We only check for ORA special-remotes, when we clone from a `ria+` URL (which `datalad get` didn't do in your case). We could change that and make the post-clone-special-remote-check more universal. IIRC there already is another code block (not in `postclonecfg_ria`) that discovers special remotes that weren't autoenabled (or sth like that). We could RF and do the ORA reconfiguring there. We would still be able to detect, that there's an ORA remote with `autoenable=true`, that wasn't sucessfully enabled by `git-annex-init` and then not only check the URL we cloned from to be a `ria+` URL, but also `subdataset-source-candidate-origin` if it wasn't.

**Comment by mih** [comment]
> Solution is certainly not to change order from my point of view. We want stay aligned with git. If we start considering different URLs then git itself does _first_, we kinda break the paradigm that things git and annex consider valid, stay valid for datalad.

I am not convinced that considering datalad-specific functionality first breaks anything that git or git-annex would do.

> We only check for ORA special-remotes, when we clone from a `ria+` URL (which `datalad get` didn't do in your case). We could change that and make the post-clone-special-remote-check more universal. IIRC there already is another code block (not in `postclonecfg_ria`) that discovers special remotes that weren't autoenabled (or sth like that). We could RF and do the ORA reconfiguring there. We would still be able to detect, that there's an ORA remote with `autoenable=true`, that wasn't sucessfully enabled by `git-annex-init` and then not only check the URL we cloned from to be a `ria+` URL, but also `subdataset-source-candidate-origin` if it wasn't.

This would possibly help in some cases (although note that the source-candidate config is not in the dataset that is being processed, but in its superdataset). However, there is no guarantee that the URL a subdataset was cloned from actually has an ORA remote, while the location that would have been cloned from, when the superdataset config would have been considered, may still have one. In general, this proposal would mean that, when a subdataset was successully cloned, we check any other possible clone candidate whether it has the remote we are still looking for. This sounds very expensive, as there is no guarantee that such a location exists.

Maybe, we should make the order in which candidates are tried configurable, and include .`gitmodules` as an explicit item. 

`subdataset-source-candidate-origin` could become `subdataset-source-candidate-20origin` and there would be an explicit `subdataset-source-candidate-100gitmodules`. Candidates would be considered in alphanum order -- following an approach that is also used for stuff like drop-in config in `/etc/environment.d` and similar UNIXy mechanisms.

This would also make it possible to avoid the current penalties, where users have to endure datalad guessing which URL to clone from more than once. Frequently the cloning is now the slowest part of obtaining data via datalad. I suspect that we could shave off quite a bit of time when installing complex datasets like the HCP one.

**Comment by bpoldrack** [comment]
>  I am not convinced that considering datalad-specific functionality first breaks anything that git or git-annex would do.

Well, the "promise" was, that datasets remain usable/accessible even when datalad disappears. If we favor setups, where the committed in git URLs are not the ones being considered, then this promise becomes quite shaky, since a mere `git submodule update --init --recursive` would now potentially result in very different thing then what was set up to work with datalad via `datalad get --recursive`. Will be more difficult to even get the same repo as w/o datalad. And requires datalad knowledge.

>  (although note that the source-candidate config is not in the dataset that is being processed, but in its superdataset)

True. But: We would still be in (post-)clone that read the URL (-candidates) from this very superdataset.

> However, there is no guarantee that the URL a subdataset was cloned from actually has an ORA remote, while the location that would have been cloned from, when the superdataset config would have been considered, may still have one.

We would only need to consider `ria+` URLs in source-candidates, that resolve to the same location as the URL we cloned from. Otherwise reconfiguration of a particular special remote (UUID) would potentially mess up things thoroughly indeed.

> In general, this proposal would mean that, when a subdataset was successully cloned, we check any other possible clone candidate whether it has the remote we are still looking for. This sounds very expensive, as there is no guarantee that such a location exists.

Well, *if* autoenabling fails, we first check the clone-URL and then the candidates for whether they are `ria+` URLs (that match the clone-URL in case of the candidates) until enabling succeeds or we have no more candidates.
Theoretically this can be expensive, yes. But nothing speaks against documenting how to avoid that in addition to a code change, except that now it wouldn't document how to avoid such a failure but a potentially slow cloning.

> Maybe, we should make the order in which candidates are tried configurable, and include .gitmodules as an explicit item.

Doesn't exactly solve my first point, but sounds like a not too bad compromise. :)

**Comment by mih** [comment]
> Well, the "promise" was, that datasets remain usable/accessible even when datalad disappears.

I agree.

> If we favor setups, where the committed in git URLs are not the ones being considered, then this promise becomes quite shaky, since a mere `git submodule update --init --recursive` would now potentially result in very different thing then what was set up to work with datalad via `datalad get --recursive`. Will be more difficult to even get the same repo as w/o datalad. And requires datalad knowledge.

I do not agree. If the dataset maintainer cares for the url, things will just work fine. If they don't then it won't. That is no change from what is true with Git alone.

The "very different thing" is a potentially different origin URL nothing else. And only if there happens to be a candidate config.

If I remember the current behavior correctly, installing the full HCP dataset with 4500 subdatasets (which takes 5.5h) will cause 9000 clone attempts that we already know will fail (gitmodule url (which is a path), that path + '.git'), and then the 4500 attempts that are configured to work. Those attempts are a significant source of slow-down.

Avoiding those failed attempts with the present setup would mean to configure a working URL in all `.gitmodules`. If we do that then all clone attempts on our local cluster would now start talking to a server in the US, instead of a local store, making things even slower. If I want to fix that, I would have to carry a permanent diff in all 4500 datasets, and also fix them again and at each site, whenever anything moves.

So in an ideal world everything is nice, but in reality things are slow and expensive.

**Comment by bpoldrack** [comment]
> And ironically, when I want to have the dataset behave intelligently right now, all I have to do is to break the .gitmodules URL config and put something there that doesn't work -- thereby intentionally making sure that DataLad is required under all circumstances, and no Git fallback will work.

Good point :-D

I'm kind of  fine with that config proposal, but I don't really like it. There's nothing wrong w/ that `.gitmodules` URL (if didn't miss sth important). The problem doesn't actually arise from us using the wrong URL for cloning, but from us not considering it for reconfiguring the special remote since it's not a RIA URL. It's weird to solve that on the end that actually works perfectly right w/ and w/o datalad.

Thinking about it, there's actually a third option: Why not just change what URLs to consider if autoenabling failed? Even without the `ria+` prefix we can actually see that this URL fits the pattern of a resolved RIA URL and try it. That doesn't seem expensive and makes perfect sense in my mind. Ultimately the point of reconfig is that it needs to be the same location the git remote points to. If we have a valid URL we can derive the special remote config from - all is good actually.

**Comment by mih** [comment]
> I'm kind of fine with that config proposal, but I don't really like it. There's nothing wrong w/ that `.gitmodules` URL (if didn't miss sth important).

The important thing is that I have _zero_ possibilities to prevent datalad from using that URL, if a clone succeeds. In my case I built the dataset, so the URL is still kinda OK, but that is just coincidence. If that URL resolves to a server that is only accessible via TCP-over-smoke-signals, any user would hate to see the local RIA store (from which the superdataset was just cloned) be completely ignored and given no ability to change that -- other than manually modifying all superdatasets (at any level).

Moreover, any modification of any subdataset in a local store will automatically break that URL, because the change is not available upstream, leading to an unsuccessful clone attempt, leading to a consideration of the alternatives, leading to the .gitmodules URL be effectively ignored -- in an expensive way.

**Comment by bpoldrack** [comment]
>  any user would hate to see the local RIA store (from which the superdataset was just cloned) be completely ignored

Right. I missed that the URL the superdataset was cloned from should have a say indeed. That's convincing to me. Would then indeed defy the purpose of source-candidates if they were ignored.
Okay - let's go for the priority configs. :)

**Comment by bpoldrack** [comment]
Still worth considering non-`ria+` URLs for reconfiguration (given those configs) of the special remote if we can match them as described above. So, if in your example `.gitmodules` would have highest priority we would not need to fail on enabling that remote.

**Comment by mih** [comment]
Started looking into this. It is even worse than expected. Here is the code https://github.com/datalad/datalad/blob/1ddfd3651fe47ffdcaf195d6c926cb22862266b3/datalad/distribution/get.py#L99

Even before trying the (wrong) URL from `.gitmodules` yet another set of URLs is tested. The URL of any configured remote that has the desired submodule commit + the submodule mount path. This is pointless for any dataset coming from a RIA store, but is guaranteed to be attempted.

If the URL is an `http*` one then each clone from a RIA store will have two clone attempts to a location in the store than can never exist (flat list), one for the plain URL, and one with `/.git` appended.

**Comment by mih** [comment]
There seems to be more variability. Here is a concrete public demo:

```
% datalad clone ria+http://store.datalad.org#~hcp-openaccess
% cd hcp-openaccess
% datalad get HCP1200/172029
```

`.gitmodules` has

```
[submodule "172029"]
        path = HCP1200/172029
        url = ./HCP1200/172029
        branch = master
        datalad-id = 632dc798-2869-11ea-8afa-002590496000
```

4 candidate URLs are being generated:

- http://store.datalad.org/alias/hcp-openaccess/HCP1200/172029
- http://store.datalad.org/alias/hcp-openaccess/HCP1200/172029/.git
- http://store.datalad.org/632/dc798-2869-11ea-8afa-002590496000
- http://store.datalad.org/632/dc798-2869-11ea-8afa-002590496000/.git

The first two must fail, the third succeeds.

There are only 4 candidates, because the gitmodules and the hierarchy prediction give the same result and a `unique` operation is performed inside. Changing gitmodules URL to `./someotherplace`, cause 7 candidates to be generated, success on the 5th:

- http://store.datalad.org/alias/hcp-openaccess/HCP1200/172029
- http://store.datalad.org/alias/hcp-openaccess/HCP1200/172029/.git
- http://store.datalad.org/alias/hcp-openaccess/someotherplace
- http://store.datalad.org/alias/hcp-openaccess/someotherplace/.git
- http://store.datalad.org/632/dc798-2869-11ea-8afa-002590496000

Each clone attempt takes about 0.5s in this case, so 1.5s wasted per subdataset, or almost two hours for the entire HCP dataset.

**Comment by mih** [comment]
I am starting to think that even without any change in the concept, the order in which attempts should be made is this:

- http://store.datalad.org/alias/hcp-openaccess/HCP1200/172029
- http://store.datalad.org/alias/hcp-openaccess/someotherplace
- http://store.datalad.org/632/dc798-2869-11ea-8afa-002590496000
- http://store.datalad.org/alias/hcp-openaccess/HCP1200/172029/.git
- http://store.datalad.org/alias/hcp-openaccess/someotherplace/.git
- http://store.datalad.org/632/dc798-2869-11ea-8afa-002590496000/.git

Rational: all those `/.git` variants are blind attempts to mitigate deliberately or mistakenly misspecified URLs. In cases where it gets to this, a little wait is more justifiable, then causing this wait in cases where all URLs are proper.

**Comment by mih** [comment]
Here is more wrong: This is the list of candidate URLs (stripping the `.git` variants for clarity this time) after another remote of the superdataset was configured:

```
% git remote add gh git@github.com:datalad-datasets/human-connectome-project-openaccess.git 
% git fetch gh
```

Now two remotes have the desired submodule commit. This gives:

```
[('origin', 'http://store.datalad.org/alias/hcp-openaccess/HCP1200/172029'),
 ('origin', 'http://store.datalad.org/alias/hcp-openaccess/someotherplace'),
 ('subdataset-source-candidate-origin',
  'ria+http://store.datalad.org#632dc798-2869-11ea-8afa-002590496000'),
 ('gh',
  'git@github.com:datalad-datasets/human-connectome-project-openaccess.git/HCP1200/172029'),
 ('gh',
  'git@github.com:datalad-datasets/human-connectome-project-openaccess.git/someotherplace'),
 ('subdataset-source-candidate-origin',
  'ria+http://store.datalad.org#632dc798-2869-11ea-8afa-002590496000'),
 ('local', '/tmp/hcp-openaccess/someotherplace')]
```

the subdataset candidate config is in there twice (an indentation error in the code), but gets stripped later on for proving an identical URL. Most of these candidates are invalid, thankfully the right one is  in 5th position and not 11th ;-)

**Comment by mih** [comment]
I took off the milestone. The proposed change to a sortable order can be done without breaking existing config (I think). The core of the suboptimal behavior was already present in 0.12, so no reason to make it a block now.

**Comment by bpoldrack** [comment]
After reading this again, I'm not sure, there's anything left to be done after PR #4619. Do I miss something or can we close, @mih?

**Comment by mih** [comment]
I trust your judgement
