### ISSUE TITLE
EnsureChoice doc rendering suboptimal

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4616]
When a parameter has:

`EnsureChoice(None, 'extracted', 'archives')`

the short help looks nice:

```
Usage: ... [-h] [-k PATH] [--merge] [-f]
                [--drop {extracted|archives}] [-d DATASET]
```

but long help doesn't (cmdline):

```
--drop {extracted|archives}
                        ... Constraints: value must be one of (None,
                        'extracted', 'archives')
```

with `EnsureChoice('extracted', 'archives') | EnsureNone())` long help looks nice

```
  --drop DROP  ... Constraints: value must be one of ('extracted', 'archives')
```

but short help doesn't

```
Usage: ... [-h] [-k PATH] [--merge] [-f] [--drop DROP]
                [-d DATASET]
```

I think the preferred form should be `EnsureChoice(None, 'extracted', 'archives')` and the long-help rendering should be fixed to exclude `None` on the commandline.

**Comment by mih** [comment]
Although related https://github.com/datalad/datalad/issues/5653

**Comment by christian-monch** [comment]
> I think the preferred form should be `EnsureChoice(None, 'extracted', 'archives')` [...]

It seems cleaner to me to write `EnsureChoice('extracted', 'archives') | EnsureNone()`. The other form conflates IMO parameter values and parameter-requirement status.

**Comment by adswa** [comment]
> It seems cleaner to me to write EnsureChoice('extracted', 'archives') | EnsureNone(). The other form conflates IMO parameter values and parameter-requirement status.

That sounds sensible to me. But how can we improve the short-rendering of this version? In the example that @mih gave above, the short-help is not helpful at all about the possible choices.
