### ISSUE TITLE
Something is flaky in crippled FS workflow

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#4621]
Stumbled upon this in PR #4608 :

Crippled FS workflow passed. After squashing the PR and pushing again it suddenly failed, because a `ds.config.get("annex.uuid")` returned `None`. After restarting the job it passed again. I have no idea ATM, but want to take a note here. However, this also lead me to discover, that some tests are using it like `assert_equal(uuid_before, uuid_after)`, which wouldn't raise in such a case.

**Comment by mih** [comment]
I have seen multiple spurious failures over the past days, never the same one, though. :(

**Comment by bpoldrack** [comment]
"Fixed" the spots I could find where we wouldn't notice that we got no `uuid`. I think this is the only thing coming out of this issue.
The actual thing can't be addressed for now w/o more information and reproducibility.
