### ISSUE TITLE
Q: Short(er) option for --transfer-data?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4622]
Decided to bring to discussion outside of #4620 to not pollute it.

`publish` was never blessed with a short version for `--transfer-data` option. `--force` had `-f` which made it possible to say `-f datatransfer`.
- `install` has `-g|--get-data`
- `get` has `-n|--no-data`

I wonder if we could/should decide on a short option for `--transfer-data` going forward. May be eventually it could even become common (there is no reason for `get` to not support `auto*` modes) and listed among common options of the [cheat sheet](http://handbook.datalad.org/en/latest/basics/101-136-cheatsheet.html).

- Candidates such as `-D`, `-d` are already taken.
- `-t` is also used in a wide variety of contexts without any consistency.
- The only one relating to "transfer" left seems to be `-T` but I think it is more about "data" than "transfer" so I do not like it either.

Altogether - I do not see any short option :-/

## `--data`

Orthogonal alternative compromise is to introduce `--data` instead of `--transfer-data` in #4620 , which would at least be shorter and easier to remember, e.g. `datalad push --data anything --to myremote`.
  
While at it also deprecate `--transfer-data` in `publish` (in favor of `--data`) if that one to survive.  That would also "assist" with conscious migration from `publish --transfer-data all` to `publish --data anything`.

Later we could RF/enhance `get` to make it default to `get --data=auto-if-wanted` and use `get --data=nothing` instead(?) of `get -n`, making interfaces more consistent.

**Comment by bpoldrack** [comment]
I'm not generally concerned with short options tbh, but I'm fine with `--data` and like aligning how to specify it in `get` and `push`.

**Comment by yarikoptic** [comment]
Added 7dd99fd271cb30211e8a01f55ca6092c3aec3500 to #4620 renaming into `--data`.  If we decide to go with it, will then RF `publish` to align.

**Comment by kyleam** [comment]
gh-4620 has been merged.
