### ISSUE TITLE
save: record committer's orcid id (if available)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4624]
I don't remember why I had done it in the past but I have
```shell
$> git config user.orcid
0000-0003-3456-2493
```

I wondered how we could make orcid recorded for any particular commit by those who have e.g. similar setup.

- trailer of git commit message?
- git notes?
- I could just come up with a `user.email` to be smth like `0000-0003-3456-2493@orcid.org` which wouldn't be valid, BUT it would provide ready to be used solution!  I am a little worrying about making it e.g. `orcid:0000-0003-3456-2493` - not sure if there would be no side effects from tools etc which expects it to be a proper email. May be then `orcid:0000-0003-3456-2493@orcid.org`?

**Comment by bpoldrack** [comment]
I would not record that per commit. Metadata is the right layer for this, I think. And requires only one record that makes the connection between committer's email and and orcid. The latter could then be extracted from a config like the one you used or from a zenodo file or whatever else.

**Comment by adswa** [comment]
I've taken the liberty to add the ``metadata`` label to this one

**Comment by yarikoptic** [comment]
the rationale to request such a feature was not clear, and was not met with extreme enthusiasm and PRs, thus let's let it RiP.
