### ISSUE TITLE
create-publication-target* should "initiate" that remote to be known for annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#463]
otherwise later invocation of annex commands might lead to undesired network interactions
see http://git-annex.branchable.com/bugs/addurl_--batch_decides_to_talk_to_ssh_remotes_for_some_reason/

**Comment by yarikoptic** [comment]
actually may be it should be done during publish, if source repository is an annex.  blank freshly created remote repo is not "respected" by annex, so it would be too early during `create-publication-target*`.  After publish it seems to be the right time ;)

**Comment by yarikoptic** [comment]
ah, and relates to #432 about which I have forgotten now and already burnt myself again... I guess fix will entail fix for #432 and then for this one (not sure yet what is optimal way to kick annex to add uuid for the remote, but calling `annex info` would do) ....   But then keep in mind that it would also then be followed by  a call to "git annex merge" so it would merge (well -- just ff) to the updated git-annex on the remote end.

**Comment by yarikoptic** [comment]
just uploaded fresh annex snapshot to neurodebian and will upgrade all the buildbot dockers now -- with annex 6.20160524+gitg2b7b2c4-1~ndall+1  you can now use reliably `git annex enableremote REMOTENAME` to make annex query/assign uuid.  For more info see http://git-annex.branchable.com/devblog/day_394__implicit_vs_explicit/

**Comment by yarikoptic** [comment]
@hanke, @bpoldrack this one and #432 -- would be nice to have them addressed by 0.2.1

**Comment by yarikoptic** [comment]
so could it be done @hanke, @bpoldrack ?

**Comment by bpoldrack** [comment]
Yes, will do.

**Comment by yarikoptic** [comment]
I think this is still not resolved... need to do manually "git annex info" to initiate annex uuid on the remotes atm

**Comment by yarikoptic** [comment]
this issue hunts me around... this time I think it appeared while crawling, since I guess archives backend asked for info from annex and that one again tried to reach out to datalad-public

```
2016-08-02 22:07:42,635 [Level 5] Command: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'addurl', '-c', 'annex.largefiles=exclude=README*', '--with-files', '--json', '--batch'] (annexrepo.py:1390)
2016-08-02 22:07:42,641 [Level 5] Sending 'dl+archive:MD5E-s23309790--bc52eae1f927ad23e924b2c4d293c660.tar.gz#path=additional_whl_files/00-README.txt&size=1415 additional_whl_files/00-README.txt\n' to batched annex BatchedAnnex(annex_cmd=['addurl'], annex_options=<<['-c', 'annex.largefil...>>, git_options=[], output_proc=<function>, path=<<'/mnt/datasets/datalad...>>) (annexrepo.py:1445)
2016-08-02 22:07:42,641 [Level 5] Done sending. (annexrepo.py:1453)
yoh@datasets.datalad.org's password: 
packet_write_wait: Connection to 129.170.233.11 port 11110: Broken pipe
muxclient: master hello exchange failed
Failed to connect to new control master
yoh@datasets.datalad.org's password: 
  Remote datalad-public does not have git-annex installed; setting annex-ignore
  This could be a problem with the git-annex installation on the remote. Please make sure that git-annex-shell is available in PATH when you ssh into the remote. Once you have fixed the git-annex installation, run: git annex enableremote datalad-public
2016-08-02 22:10:32,758 [Level 5] Received output: {u'note': u'from datalad-archives', u'success': True, u'command': u'addurl', u'key': u'MD5E-s1415--8dabadc47561b48faef7d5e2f0c9f65f.txt', u'file': u'additional_whl_files/00-README.txt'} (annexrepo.py:1463)
```

**Comment by yarikoptic** [comment]
I said:
>  blank freshly created remote repo is not "respected" by annex
and I am not sure if I was silly or just meant something else since sure thing we could run git annex init after git init.  And thus I think create publication target is the right place to do it.  It should do it though only if original one is annex, and not git.  I or @debanjum will fix it since noone else has done it yet
