### ISSUE TITLE
FOI: pydantic enforces type hints at runtime...

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4631]
https://pydantic-docs.helpmanual.io/

Feels like it could find some nice uses in DataLad.  E.g. (if there is no performance hits etc) - could provide formalization for return records etc, whenever we start to use type declarations (#4513)

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
