### ISSUE TITLE
We need to establish a minimal supported git version and puke informatively

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4636]
relates: #4535 

See https://github.com/CONP-PCNO/conp-portal/issues/318 where @tashrifbillah gets

```shell
(base) [tb571@pnl-z840-2 tmp]$ datalad install https://github.com/CONP-PCNO/conp-dataset.git

CommandError: command '['git', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes']' failed with exitcode 128
Failed to run ['git', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] under '/tmp/conp-dataset'. Exit code=128. out= err=fatal: unknown refname: format strip=2

fatal: unknown refname: format strip=2
```
so we use unsupported by his version `--format`.

Ideally we should run a sweep of our tests with that minimal version, similarly to how we do with minimalish git-annex now on cron job.

**Comment by yarikoptic** [comment]
Since you know git best of all of us, I had assigned this one to you @kyleam  ;-)

**Comment by kyleam** [comment]
Thanks for bringing this up again.  I [very much agree][0] we should have an explicit minimum version.  But it has very little to do with knowledge of git.  It's coming to an agreement on what the minimum should be, which depends on where people rely on running datalad (and perhaps what git-annex depends on, though I'd have to check).

So, can you and others weigh in with what a suitable minimum version would be for your purposes?

[0]: https://github.com/datalad/datalad/pull/3705#discussion_r327905090questreview-292794681

**Comment by kyleam** [comment]
> and perhaps what git-annex depends on, though I'd have to check

I see [a comment on git-annex's bug tracker][0] that the minimum git version for git-annex is 2.22, but that might just be in the context of upgrades.  Grepping the code base, it seems the hard minimum might be either 2.1 or 2.2.

[0]: https://git-annex.branchable.com/bugs/git-annex_upgrade_fails/#comment-c4dbd2f22516bc1172b285838d2a2038

**Comment by yarikoptic** [comment]
I guess we could test with `max(2.2, version_which_introduced_--format=%(refname:strip=2)_support)`

**Comment by kyleam** [comment]
> I guess we could test with `max(2.2, version_which_introduced_--format=%(refname:strip=2)_support)`

`:strip` came in v2.7 according to my comment I linked to.  I guess your test comment means you want to test with that, and see if that reveals anything else from a newer version that we depend on, and then use that version.

Setting it to that value would certainly be better than what we do now, but if we're going to set a minimum version, I'd think in the process it'd be good to get opinions about what a reasonable floor is and consider bumping it more aggressively.  v2.7 is from Jan 2016.  Should we spend effort worrying about compatibility with that old of a version?

**Comment by yarikoptic** [comment]
Worrying about compatibility -- not. Just knowing what version we are compatible with.  As for establishing minimal one to require - I think 2.19.1, if confirmed to work, could be the one to require.  It is 32bit git version in https://anaconda.org/anaconda/git . It is below the 2.20.1 in Debian stable (happen someone backports native build of git-annex for it).
