### ISSUE TITLE
More intelligent "datalad update --recursive"?

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4642]
#### What is the problem?
I have a dataset with 400+ subdatasets. A collaborator works to change a couple of subdatasets, then I pull the changes on the parent dataset. To do this properly, I do `datalad update --merge --recursive`. The problem is that with `--recursive` datalad goes into every subdataset, fetches changes, and applies them, which takes a long time for just a couple of subdatasets that need to be updated. May I suggest the creation of a more intelligent recursive approach, where only new or changed subdatasets are updated. This could be something like `--recursive [all | modified]`.

I don't think this can be done with the current version, but if it's possible, please give me some tips on how to.

#### What steps will reproduce the problem?
NA

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
`datalad 0.12.6`

#### Is there anything else that would be useful to know in this context?
NA

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Yes, using routinely.

**Comment by yarikoptic** [comment]
I think this is another vote for having https://github.com/datalad/datalad/issues/4452  resolved ;)?

**Comment by yarikoptic** [comment]
> May I suggest the creation of a more intelligent recursive approach, where only new or changed subdatasets are updated

For that, if not only in `--follow parentds`, you would need to go through all subdatasets since it might be that subdatasets were changed on remote side without modifications within their superdataset. But also it highlights use-case which I am not sure (@kyleam could correct me) we accounted/tested for -- when your local (super)dataset does have some changes not present on remote and you still want to merge only changes which happened in datasets on remote -- not sure if `--follow parentds` would work or not.

**Comment by dorianps** [comment]
Ah, I see the problem. You can't rely on parentds alone in case the subdataset has advanced in remote without being registered in parent. But for that case scenario the standard `--recursive` is fine. The trick is to find a solution to save time when all you need is a quick work on a dataset. For all we know, the co-worker might be still working on subdataset A and B and does not want to register them in parentds, while there is something in subdataset C that is more urgent and needs to be saved and worked on immediately. This is not exactly my use scenario, but I guess having a smarter recursive merge allows for this scenario too.

**Comment by yarikoptic** [comment]
I think we should approach it for `--follow parentds` first then: there is indeed no need to even consider a subdataset if it is to follow its state as known to the parent, and parent says "no changes".
