### ISSUE TITLE
Error `up-to-date` on datalad publish?

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4646]
#### What is the problem?
I am pushing some changes to a remote server. Had to try this a few times because some subdatasets weren't in the remote initially. Now the local and remote seem to be in sync when I check git log, but the publish call ends with this error:
```
[ERROR  ] failed to push to pushsibling: master -> pushsibling/master [rejected] (non-fast-forward); pushed: ['[up to date]'] [publish(/home/dp/datasets/apr26/freesurfer)]
publish(error): . (dataset) [failed to push to pushsibling: master -> pushsibling/master [rejected] (non-fast-forward); pushed: ['[up to date]']]
action summary:
  publish (error: 1, notneeded: 447)
```
Should I ignore this error since both repositories seem in sync from a git perspective?

#### What steps will reproduce the problem?
Not 100% sure of whether this is reproducible, I had to run publish multiple times while fixing some of the missing subdatasets in the remote.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.12.6

#### Is there anything else that would be useful to know in this context?
NA

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
All good.

**Comment by dorianps** [comment]
A follow-up question. Isn't the publish command supposed to create the missing subdatasets in the remote instead of failing (my original issue with this process). Am I missing something in the publish command? Here is my call to datalad
```
datalad publish --to pushsibling  --transfer-data all --recursive
```

**Comment by dorianps** [comment]
Fixed the first issue. Had accidentally advanced the remote by one commit, which prevented fast-forwarding. Sorry for flooding with messages.

The second questions still stands. Shouldn't the publish command take care of creating/installing/updating all the subdatasets that are being pushed to the remote?

**Comment by kyleam** [comment]
> Isn't the publish command supposed to create the missing subdatasets in the remote instead of failing (my original issue with this process). Am I missing something in the publish command?

Have you tried use `--missing`?

<details>
<summary>demo</summary>

```sh
set -eu

cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-XXXXXXX)"

datalad create a

(
    cd a
    datalad create-sibling --name=b ../b
    datalad publish --to=b
    datalad create -d. sub
    echo 0 >sub/f0
    datalad save --recursive
    datalad publish --to=b --recursive --transfer-data all --missing inherit
)

tree --charset=ascii b
```

```
[...]
b
`-- sub
    `-- f0 -> .git/annex/objects/zJ/p1/MD5E-s2--897316929176464ebc9ad085f31e7284/MD5E-s2--897316929176464ebc9ad085f31e7284
```

</details>

**Comment by yarikoptic** [comment]
Thank you @kyleam ! I think that answer addresses the question, I will close. @dorianps , feel welcome to reopen if I am wrong
