### ISSUE TITLE
"No such file or directory" for good folders.

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4647]
#### What is the problem?
Anyone knows why sometimes datalad/python does not seem to recognize perfectly good path?
```
datalad siblings add --recursive --name mandy --url /DATA/sdas/FEDERATED_DATASETS/study1/data/processed/freesurfer: No such file or directory
```
I upgraded to 0.13.0rc2 but that did not resolve the problem, so I am still stuck. I have seen this in the past and don't remember how it goes away, but maybe someone has an idea. The path is definitely there, I can see the content with `ls`.

#### What steps will reproduce the problem?
Can't find a way to reproduce easily. I am on Centos 7, installed datalad via pip3.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.12.7 and 0.13.0rc2

#### Is there anything else that would be useful to know in this context?
Maybe restarting the server helps, but can't do that often.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
All ok.

**Comment by bpoldrack** [comment]
It is not obvious to me that the path it's missing is the one you passed to `--url`.
Is this

> datalad siblings add --recursive --name mandy --url /DATA/sdas/FEDERATED_DATASETS/study1/data/processed/freesurfer: No such file or directory

the actual output, or did you cut out something between entering the command and the error message? The thing is: If that error happend during execution it should look different, I think.
However, debug level output would be interesting ( `datalad -l debug siblings add ...` ).
I'd suspect that `--recursive` might look for a path that's not there.

**Comment by dorianps** [comment]
Found the problem. I am pasting from other sources and there are invisible characters (i.e., color codes) being pasted. That's what is causing troubles all over the place. Writing the command manually make it work. The strange thing is that I can't see those codes even when I paste the text in Notepad++. So, will need to be more careful or enable some setting in bash to strip the non-character codes automatically, not sure if this has to do with ANSI. 

Closing the issue.
