### ISSUE TITLE
'Unable to access these remotes' error on server.

### ISSUE THREAD

**Issue by jacobsanz97** [datalad/datalad#4651]
#### What is the problem?

I've been trying to download the Prevent-AD (both the BIDS and non-BIDS versions) and the Multicenter Single Subject Human MRI Phantom datasets from the CONP ( [https://github.com/CONP-PCNO/conp-dataset] ) on a Compute Canada headnode using DataLad, but I run into the following error when I run 'datalad get' on their files:

```
[ERROR  ] from datalad...; Unable to access these remotes: datalad; Try making some of these repositories available:; 	cf13d535-b47c-5df6-8590-0793cb08a90a -- [datalad]; ; (Note that these git remotes have annex-ignore set: origin) [get(/home/$user$/$projects$/$name$/conp-dataset/projects/preventad-open/1004359/PREBL00/images/preventad_1004359_PREBL00_asl_001.mnc)] 
get(error): projects/preventad-open/1004359/PREBL00/images/preventad_1004359_PREBL00_asl_001.mnc (file) [from datalad...; Unable to access these remotes: datalad; Try making some of these repositories available:; 	cf13d535-b47c-5df6-8590-0793cb08a90a -- [datalad]; ; (Note that these git remotes have annex-ignore set: origin)]
action summary:
  get (error: 1, notneeded: 1)
```
I am able to get the other CONP datasets on the server with no issues, but these three datasets sourced from LORIS all result in the same error. 
Locally, on my personal laptop, however, I am able to successfully 'get' files from the datasets in question with no errors, so the issue is only present on the server.

#### What steps will reproduce the problem?

On the server I am running the commands:
datalad install -r http://github.com/CONP-PCNO/conp-dataset
datalad get projects/preventad-open/1004359/PREBL00/images/preventad_1004359_PREBL00_asl_001.mnc

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

Currently I am using DataLad version 0.12.6, and git-annex version 8.20200330. I have tried a number of different versions of DataLad (including 0.13.0rc2) and git-annex, and they resulted in the same error. The server is CentOS 7.7.1908.

#### Is there anything else that would be useful to know in this context?

`git annex whereis preventad_1004359_PREBL00_bold_001.mnc`
Running 'git-annex whereis' and 'git-annex get' on the file there is no output (even using verbose mode). It's as if I'd hit enter on the terminal without writing any commands. Running either of these commands on debug mode prints various "process done ExitSuccess" and no errors.

I have also tried installing the dataset in a different directory to no avail.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
I have had success getting the other CONP datasets on the server, and getting the files in question locally.

Thank you very much for your help!

**Comment by yarikoptic** [comment]
I think it is just that `datalad` special remote which is needed to access data from those repositories did not get enabled for some reason (may be you just `git clone`'ed this repo?)... try

`git annex enableremote datalad`

and report back if it works/blows and either if it works - would `annex whereis` and/or `get` work

**Comment by yarikoptic** [comment]
here is the full protocol of an attempt with that datalad version -- I do arrive at "authentication" phase, so `datalad` special remote is working:
```
/tmp > datalad --version
datalad 0.12.6

/tmp > git annex version | head -n 1
git-annex version: 8.20200501+git61-g64e081d58-1~ndall+1

/tmp > datalad install -r http://github.com/CONP-PCNO/conp-dataset
[INFO   ]   Remote origin not usable by git-annex; setting annex-ignore                                          
install(ok): /tmp/conp-dataset (dataset)                                                                         
[INFO   ] Installing <Dataset path=/tmp/conp-dataset> underneath /tmp/conp-dataset recursively 
[INFO   ]   Remote origin not usable by git-annex; setting annex-ignore                                          
install(ok): /tmp/conp-dataset/projects/1000GenomesProject (dataset)                                             
[INFO   ]   Remote origin not usable by git-annex; setting annex-ignore                                          
install(ok): /tmp/conp-dataset/projects/BigBrain (dataset)                                                       
[INFO   ]   Remote origin not usable by git-annex; setting annex-ignore                                          
install(ok): /tmp/conp-dataset/projects/BigBrain_3DClassifiedVolumes (dataset)                                   
[INFO   ]   Remote origin not usable by git-annex; setting annex-ignore                                          
^CERROR:                                                                                                         
Interrupted by user while doing magic: KeyboardInterrupt() [selectors.py:select:415]
datalad install -r http://github.com/CONP-PCNO/conp-dataset  6.71s user 2.90s system 60% cpu 15.850 total

exit:1 /tmp > cd conp-dataset 

/tmp/conp-dataset > datalad get projects/preventad-open/1004359/PREBL00/images/preventad_1004359_PREBL00_asl_001.mnc
[INFO   ]   Remote origin not usable by git-annex; setting annex-ignore                                          
install(ok): /tmp/conp-dataset/projects/preventad-open (dataset) [Installed subdataset in order to get /tmp/conp-dataset/projects/preventad-open/1004359/PREBL00/images/preventad_1004359_PREBL00_asl_001.mnc]
Authenticated access to https://openpreventad.loris.ca/api/v0.0.3-dev/candidates/1004359/PREBL00/images/preventad_1004359_PREBL00_asl_001.mnc has failed.
Do you want to enter other credentials in case they were updated? (choices: yes, no): 

```

**Comment by jacobsanz97** [comment]
> I think it is just that `datalad` special remote which is needed to access data from those repositories did not get enabled for some reason (may be you just `git clone`'ed this repo?)... try
> 
> `git annex enableremote datalad`
> 
> and report back if it works/blows and either if it works - would `annex whereis` and/or `get` work

I ran the command from the Prevent-AD folder and got this error output:
```
enableremote datalad [ERROR] No annex repository found in /lustre03/project/6049200/jacobsr/conp-dataset/projects/preventad-open (RuntimeError) 
[ERROR] No annex repository found in /lustre03/project/6049200/jacobsr/conp-dataset/projects/preventad-open (RuntimeError) 

git-annex: external special remote protocol error, unexpectedly received "" (unable to parse command)
failed
git-annex: enableremote: 1 failed
```
The files/links were obtained through the 'datalad install' command, I didn't explicitly clone the repo.

Thank you for replying!

**Comment by jacobsanz97** [comment]
> I think it is just that `datalad` special remote which is needed to access data from those repositories did not get enabled for some reason (may be you just `git clone`'ed this repo?)... try
> 
> `git annex enableremote datalad`
> 
> and report back if it works/blows and either if it works - would `annex whereis` and/or `get` work

I ran the command from the Prevent-AD folder and got this error output:

```
enableremote datalad [ERROR] No annex repository found in /lustre03/project/6049200/$user/conp-dataset/projects/preventad-open (RuntimeError) 
[ERROR] No annex repository found in /lustre03/project/6049200/$user/conp-dataset/projects/preventad-open (RuntimeError) 

git-annex: external special remote protocol error, unexpectedly received "" (unable to parse command)
failed
git-annex: enableremote: 1 failed
```
The files/links were obtained through the 'datalad install' command, I didn't explicitly clone the repo.

Thank you for replying!

**Comment by bpoldrack** [comment]
> ... /lustre03/project/6049200/$user/conp-dataset/projects/preventad-open ...

Hm. That seems to point to the issue. How did `$user` end up *literally* in there? Suggests, that git-annex/datalad assume this to be the path to the current working directory. Something is not properly replacing this `$user`.

**Comment by jacobsanz97** [comment]
> > ... /lustre03/project/6049200/$user/conp-dataset/projects/preventad-open ...
> 
> Hm. That seems to point to the issue. How did `$user` end up _literally_ in there? Suggests, that git-annex/datalad assume this to be the path to the current working directory. Something is not properly replacing this `$user`.

I manually replaced my username with $user manually when copy and pasting the error for the internet to see! It's just a placeholder for my actual username on the server. I did the same in the initial post for the directory names. Sorry for any confusion.
Thanks for the reply.

**Comment by glatard** [comment]
Hi @jacobsanz97, I replicated your issue on beluga.computecanada.ca. Using `git-annex` options `-v` and `-d` gives the following error message:
```
[2020-06-24 21:02:22.807554726] Failed to download url https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1004359/PREBL00/images/preventad_1004359_PREBL00_t1w_001_t1w-defaced_001.mnc/bids/sub-1004359_ses-PREBL00_run-001_T1w.json for key MD5E-s2038--973f5272ebf9fff92660b4f53f2d3615.json: Failed to establish a new session 1 times. Last exception was: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/pki/tls/certs/ca-bundle.crt [adapters.py:cert_verify:227] [http.py:get_downloader_session:510]
[2020-06-24 21:02:22.807594084] git-annex-remote-datalad[1] --> TRANSFER-FAILURE RETRIEVE MD5E-s2038--973f5272ebf9fff92660b4f53f2d3615.json Failed to download from any of 1 locations [datalad.py:_transfer:169]
```
Unsetting env variable `CURL_CA_BUNDLE` solved the issue for me:
```
> unset CURL_CA_BUNDLE
> datalad get BIDS_dataset/sub-1004359/ses-PREBL00/anat/sub-1004359_ses-PREBL00_run-001_T1w.nii.gz 
get(ok): BIDS_dataset/sub-1004359/ses-PREBL00/anat/sub-1004359_ses-PREBL00_run-001_T1w.nii.gz (file) [from datalad...] 
```
Does it also work for you?

**Comment by jacobsanz97** [comment]
> Hi @jacobsanz97, I think I replicated your issue on `beluga.computecanada.ca`. Using `git-annex` options `-v` and `-d` gives the following error message:
> 
> ```
> [2020-06-24 21:02:22.807554726] Failed to download url https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1004359/PREBL00/images/preventad_1004359_PREBL00_t1w_001_t1w-defaced_001.mnc/bids/sub-1004359_ses-PREBL00_run-001_T1w.json for key MD5E-s2038--973f5272ebf9fff92660b4f53f2d3615.json: Failed to establish a new session 1 times. Last exception was: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/pki/tls/certs/ca-bundle.crt [adapters.py:cert_verify:227] [http.py:get_downloader_session:510]
> [2020-06-24 21:02:22.807594084] git-annex-remote-datalad[1] --> TRANSFER-FAILURE RETRIEVE MD5E-s2038--973f5272ebf9fff92660b4f53f2d3615.json Failed to download from any of 1 locations [datalad.py:_transfer:169]
> ```
> 
> Unsetting env variable `CURL_CA_BUNDLE` solved the issue for me:
> 
> ```
> > unset CURL_CA_BUNDLE
> > datalad get BIDS_dataset/sub-1004359/ses-PREBL00/anat/sub-1004359_ses-PREBL00_run-001_T1w.nii.gz 
> get(ok): BIDS_dataset/sub-1004359/ses-PREBL00/anat/sub-1004359_ses-PREBL00_run-001_T1w.nii.gz (file) [from datalad...] 
> ```
> 
> Does it also work for you?

This works perfectly, thank you very much!!!

**Comment by glatard** [comment]
@yarikoptic, is there a "troubleshooting" section of the DataLad handbook somewhere, and if not, shall we create one? I feel like we could consolidate a few debugging tips there.

**Comment by jbpoline** [comment]
:+1:  on this :) (and :tophat: to @glatard for the debugging, reminds me how much I hate certificate issues in airports when these were in use ...)

**Comment by mih** [comment]
> @yarikoptic, is there a "troubleshooting" section of the DataLad handbook somewhere, and if not, shall we create one? I feel like we could consolidate a few debugging tips there.

We have http://handbook.datalad.org/en/latest/basics/basics-help.html 

There is no dedicated collection for troubleshooting, but @adswa might consider starting one?

**Comment by adswa** [comment]
Thanks for the idea. Started in https://github.com/datalad-handbook/book/pull/538
