### ISSUE TITLE
ENH?: make test_utils_cached_dataset tests use local (not networked) dataset

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4653]
ATM relies on reuse of https://github.com/datalad/testrepo--minimalds and thus relies on stable network connection to it etc. We have  `@serve_path_via_http()`, so it might be better to just (re)create such dataset in a global fixture and then serve it.

Meanwhile, will mark all those tests with `@skip_if_no_network`

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
