### ISSUE TITLE
clone --reckless ephemeral does not inherit

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4655]
```
% datalad clone --reckless ephemeral /data/project/enki/processed ds
% cd ds
% datalad get -n code/pipelines fmriprep
% git config -l |grep reckless
datalad.clone.reckless=ephemeral
% git -C fmriprep config -l |grep reckless
```

and the subdataset annex is also not linked. This is with 0.13

**Comment by kyleam** [comment]
Confirmed on my end.  I didn't spot a test that checks that `datalad get` on a subdataset inherits the reckless config.  The closest I see is a test_clone check that cloning underneath a dataset inherits from the dataset:

https://github.com/datalad/datalad/blob/e730298044c36c8418d8c927ee6abd0a32e3a496/datalad/core/distributed/tests/test_clone.py#L335-L339

Something like this addresses the issue (at least for the demo below):

```diff
diff --git a/datalad/distribution/get.py b/datalad/distribution/get.py
index 014105768..ae1f539b6 100644
--- a/datalad/distribution/get.py
+++ b/datalad/distribution/get.py
@@ -785,6 +785,7 @@ def __call__(
                          if sdsres.get('state', None) == 'absent'
                          else sdsres['path'])
             assert 'contains' in sdsres
+            reck = reckless or ds.config.get('datalad.clone.reckless', None)
             # explore the unknown
             for target_path in sdsres.get('contains', []):
                 # essentially the same as done above for paths in the root
@@ -795,7 +796,7 @@ def __call__(
                         Path(target_path),
                         recursive,
                         recursion_limit,
-                        reckless,
+                        reck,
                         refds_path,
                         description):
                     known_ds = res['path'] in content_by_ds
```

I'll look into turning that into a proper patch later today.

<details>
<summary>demo</summary>

```sh
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"
datalad create a
datalad create -d a a/sub
echo d >a/sub/dat
datalad save -d a -r

datalad clone --reckless=ephemeral a b
(
    cd b
    datalad get -n sub
    ls -al sub/.git/annex
    git config --list | grep reckless
    git -C sub config --list | grep reckless
)
```

</details>

**Comment by bpoldrack** [comment]
IIRC the idea was, that `get` uses `clone` internally. So, it's either `clone` that's buggy, or the assumption about `get` is/became invalid.

**Comment by bpoldrack** [comment]
That's why the value is supposed to be stored in `datalad.clone.reckless` and considered by `clone` itself.

**Comment by kyleam** [comment]
@bpoldrack Yeah, I haven't taken a closer look yet, but that all sounds right.  Don't read too much into the quick and dirty patch.  It came with no investigation.
