### ISSUE TITLE
Tentative setup for HTC computing via containers

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4662]
This is not a issue. I am just using it to put a draft out here for people to find and comment.

What is described here is a DataLad dataset holding and documenting the fmriprep processing of the eNKI dataset (or another big one). It utilizes several DataLad features (such as containerized execution, dataset nesting, provenance capture) in order to enabled FAIR-compliant results and computational reproducibility.

The whole dataset comprises five DataLad dataset. This superdataset and four subdatasets with the following purpose:

- superdataset: code and documentation, versioned links to all subdatasets
code/pipelines: toolbox dataset, providing a preconfigured fmriprep equipped with a freesurfer license (not to be shared)
- `sourcedata`: BIDS-formatted eNKI dataset
- `fmriprep`: fmriprep output tree
- `freesurfer`: dedicated Freesurfer output tree produced by fmriprep

All code is located in the `code/` directory. There are two essential pieces that make up an HTCondor-based parallelized fmriprep of eNKI.

- `code/fmriprep_all_participants.submit` is an HTCondor submit file that submits on job per participant to HTCondor. Here the resource requirements of individual jobs are specified, and the execution environment for each and all jobs is defined.
- `code/fmriprep_participant_job`

In order for the submission to work correctly, the `sourcedata/` subdataset needs to be installed. Its top-level subdirectories are used to discover the participant IDs (run `datalad get -n sourcedata` in the root of the superdataset).

Log files for jobs will be placed outside the superdataset at `../logs`

The outputs for each job will be recorded in a dedicated branch in each of the output subdatasets. Branch names will be `condor-<cluster>-<process>`, where `cluster` and `process` are the HTCcondor job identifiers, and enable matching to the generated log files, in case something went wrong. All output branch have to be merged in a dedicated subsequent step, after computations are completed.

The submit file:

```
universe       = vanilla
# this is currently necessary, because otherwise the
# bundles git in git-annex-standalone breaks
# but it should be removed eventually
get_env        = True
# resource requirements for each job
request_cpus   = 1
request_memory = 8G
request_disk   = 90G
executable     = $ENV(PWD)/code/fmriprep_participant_job
# the job expects to environment variables for labeling and synchronization
environment = "CONDOR_JOBID=$(Cluster).$(Process) DSLOCKFILE=$ENV(PWD)/.git/datalad_lock"
log    = $ENV(PWD)/../logs/$(Cluster).$(Process).log
output = $ENV(PWD)/../logs/$(Cluster).$(Process).out
error  = $ENV(PWD)/../logs/$(Cluster).$(Process).err
arguments = $(subid)
# find all participants, based on the subdirectory names in the source dataset
# each relative path to such a subdirectory with become the value of `subid`
# and another job is queued. Will queue a total number of jobs matching the
# number of matching subdirectories
queue subid matching dirs sourcedata/sub-*
```

The job "payload"

```sh
#!/bin/bash
# fail whenever something is fishy, use -x to get verbose logfiles
set -e -u -x
# we pass in "sourcedata/sub-...", extract subject id from it
subid=$(basename $1)
# this is all running under /tmp inside a condor job, /tmp is a performant
# local filesystem
cd /tmp
# get the output dataset, which inclues the inputs as well
# flock makes sure that this does not interfere with another job
# finishing at the same time, and pushing its results back
flock --verbose $DSLOCKFILE \
	datalad clone --reckless ephemeral URL_OF_ROOT_DATASET ds
# all following actions are performed in the context of the superdataset
cd ds
# obtain dataset with fmriprep singularity container and pre-configured
# pipeline call; also get the output dataset to prep them for output
# consumption, we need to tune them for this particular job
datalad get -n code/pipelines fmriprep freesurfer
# checkout new branches in both subdatasets
# this enables us to store the results of this job, and push them back
# without interference from other jobs
git -C fmriprep checkout -b "condor-$CONDOR_JOBID"
git -C freesurfer checkout -b "condor-$CONDOR_JOBID"
# create workdir for fmriprep inside to simplify singularity call
# PWD will be available in the container
mkdir -p .git/tmp/wdir
# pybids (inside fmriprep) gets angry when it sees dangling symlinks
# of .json files -- wipe them out, spare only those that belong to
# the participant we want to process in this job
find sourcedata -mindepth 2 -name '*.json' -a ! -wholename '*'/"$1"/'*' -delete
# the meat of the matter, add actual parameterization after --participant-label
datalad containers-run \
  --explicit \
  -o freesurfer -o fmriprep \
  -i "$1" \
  -n code/pipelines/fmriprep \
  sourcedata . participant \
  --n_cpus 1 \
  --skull-strip-fixed-seed \
  -w .git/tmp/wdir \
  --skip-bids-validation \
  --participant-label "$subid"
# selectively push outputs only
# ignore root dataset, despite recorded changes, needs coordinated
# merge at receiving end
flock --verbose $DSLOCKFILE datalad push -d fmriprep --
```

**Comment by yarikoptic** [comment]
FWIW, in reproman we stepped away from `datalad *run` for actual execution in such scenarios to avoid racing across participants etc.  Basic invocation was presented recently in https://www.youtube.com/watch?v=ix3lC6HGo-Q&t=448s

**Comment by mih** [comment]
Do you see issues with the locking approach above? It seems to work nicely and not impose too much of overhead. When the job does almost nothing I see waiting times of ~10s with >1000 concurrent jobs. Which is pretty good, I think. I found no issues re clone or push with this implementation.

**Comment by adswa** [comment]
I think it is okay to close this issue. The approach above is documented in the handbook, and its successor will be a preprint soon.
