### ISSUE TITLE
Merge utilities for git-remote-helpers into -core

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4671]
We have two now:

- https://github.com/datalad/datalad-osf/pull/106
- https://github.com/datalad/git-remote-rclone

Both work with the same principle and share most code. Only the actual file transfer/auth is different. It would make sense to centralize the common code.

I wonder, whether time has come to split off an actual datalad-core package that is lean and can serve this purpose. This aspect came up multiple times before in different contexts (core repo classes, core API, ...).
A complication: While `git-remote-rclone` is really standalone, `datalad-osf` is much more integrated. Having both depend on datalad proper will force a whole slew of pointless dependencies.

**Comment by yarikoptic** [comment]
I wonder if that common (useful without datalad) code in `git-remote-rclone` (and possibly osf) should just get a life in `git-remote` (similar to `git-annex-remote`) or something more specific like `git-tarball-remote` (or any other better suited name)?

**Comment by mih** [comment]
I am closing this old issue of mine. There is clearly no interest in this.
