### ISSUE TITLE
Efficient procedure to obtain an entire annex

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4677]
Again the topic of large N datasets (say 400k file range). The datasets tend to be static, i.e. few versions per file (if any).

git-annex operations are essentially per file, and the smaller the files the more impact per-file overhead gets. That overhead is not necessarily caused by datalad or git-annex but is essentially inherent in the nature of things (e.g. one HTTP request per file).

I think it would be beneficial for such cases, to have a method that can "give me the entire thing" or at least "give me the entire annex" of a particular remote. In some case it will be possible to implement much faster ways to obtain the content, by e.g. streaming a large file based on a single request. I suspect that cloud-storage applications would also benefit from few requests to big files, rather then many small ones (speedwise alone, not even talking about API usage constraints).

**Comment by yarikoptic** [comment]
Re request per file - someone needs to send that request one way or another, unless files are bundled together (eg a tarball, and datalad-archive remote is enabled) and we prioritize transfers of the bundles could individual files (such idea to decide on that generally was expressed before eg in https://github.com/datalad/datalad/issues/1082 ). 
Re separate files - speeding up handling of those requests could be done via async downloads implementation. https://git-annex.branchable.com/todo/idea__58___external_special_remote___34__async__34___protocol_for_transfers/ is discussion about support for that in external special remotes.

**Comment by yarikoptic** [comment]
And I think majority of overhead is coming from datalad which does analysis on its side and giving list of keys/files to annex, instead of just providing eg `.` as the target to download.

**Comment by yarikoptic** [comment]
I could be proven wrong, but my guess is that older versions, which just provide AnnexRepo.get https://github.com/datalad/datalad/blob/master/datalad/support/annexrepo.py#L1275
with the target user specified path, instead of expanded list, and only ask annex about what to be transferred to gain ability to report total transfer size, are more "efficient". (When trying/comparing, don't forget that we stopped paralleling get by default now)

**Comment by mih** [comment]
In the concrete case there are 3 zips with a total 140GB and 380k files inside. All indexed via the `datalad` special remote (i.e. `add-archive-content`). I did `datalad get .`. The download of the three zips that happened implicitly was done in ~8min. Datalad was then entertaining the machine with purely local processing for another >90min(!). The ZIPs where uncompressed so there is no CPU bottleneck, just IO, and the drives in question can handle  0.5GB/s. Even after the `get` progress bars where done, it took ~10min to count up the `get` results. At the end it took:

```
datalad -C somename get .  4855.81s user 4035.77s system 116% cpu 2:07:44.51 total
```

which is overall `18MB/s` -- not stellar. You are correct that the download didn't start immediately. There were a few seconds of delay during which DataLad did some analysis. But those where few seconds and def. less than a minute. Leave 126 minutes for alternative optimizations. ;-)

**Comment by yarikoptic** [comment]
> Datalad was then entertaining the machine with purely local processing for another >90min(!). The ZIPs where uncompressed so there is no CPU bottleneck, just IO, and the drives in question can handle 0.5GB/s. 

So what was it doing during those 90 minutes? Was bottleneck in read io, write io, communication between git annex and special remote, or annex doing checksumming? Async implantation could provide boost in some communication if it provisions "per job" not per per file, "done" status reporting, this minimizing needed communication (@joeyh ).
Related: https://git-annex.branchable.com/todo/OPT__58_____34__bundle__34___get_+_check___40__of_checksum__41___in_a_single_operation/ - since annex would first download zip, then reread it to compute checksum - adds to consumed time.

**Comment by yarikoptic** [comment]
How does it also compare to direct get of those 380k files of served separately?

**Comment by mih** [comment]
I do not know why it was slow. I just know that it was slow. Unpacking the uncompressed ZIPs onto the NVMe drives takes <5min.

**Comment by mih** [comment]
Unpacking the 3 ZIPs next to the dataset on the same FS:

```
unzip -o $i > /dev/null  57.61s user 16.82s system 94% cpu 1:19.16 total
unzip -o $i > /dev/null  522.85s user 133.89s system 96% cpu 11:20.53 total
unzip -o $i > /dev/null  195.43s user 51.86s system 96% cpu 4:15.52 total
```

That accounts for ~17min.

md5sum'ing all 380k unpacked files:

```
find . -type f -exec md5sum {} \; > /dev/null  638.59s user 441.61s system 84% cpu 21:20.29 total
```

**Comment by yarikoptic** [comment]
I do not think we have anything actionable to discuss here.  Some optimizations might have improved performance somewhat already, but if something specific to be done - a new issue might revive this discussion
