### ISSUE TITLE
ENH: A helper (command? procedure?) to redo dataset with fake dates

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4701]
The use case -- if fake dates were not initially enabled, it might be desired to rewrite the dataset history retaining all changes and only changing dates of the commits.

For `git-annex` branch I guess it might be more or less sufficient to just `git annex forget` to start with. Ideally - availability information from reachable remotes updated, and time stamps for each key updated to current date and then `forget` -- should be sufficient to destroy sensitive dates from the stored info when they were added to a remote.

For the other branches, I wondered 
- if may be `git fast-export/fast-import` could be used while altering dates in the commits metadata... but since it would be changing commits checksums, not sure if that would work.
- could we use `git filter-branch` and adjust date information there?

What do you think?

**Comment by adswa** [comment]
+1 for having this feature!
Not sure on how to handle other branches, but [using filter-branch](https://stackoverflow.com/a/454750/12792496) will also modify checksums as far as I know. It looks like it is even easier  with ``filter-repo`` (but I assume this will also change checksums): https://blog.kawzeg.com/2019/12/19/git-filter-repo.html

**Comment by yarikoptic** [comment]
Checksums indeed will change in any of those cases. filter-repo looks great and might indeed provide the best workhorse for this! I forgot about it, thanks for the pointer @adswa

**Comment by yarikoptic** [comment]
possible another solution we briefly discussed with @kyleam during a call: to establish a "clone" of the dataset with a "view" of the tree in a completely detached commit (so no commits history is shared) with fake dates and then link to the original repo state via "git grafts" mechanism.

<details>
<summary>not sure if that is indication that git annex uses git grafts or just calls smth a graft:</summary> 

```shell
$> git grep graft | grep -v doc/
Annex/AutoMerge.hs:			graftin them file LsFiles.valThem LsFiles.valThem LsFiles.valUs
Annex/AutoMerge.hs:			graftin us file LsFiles.valUs LsFiles.valUs LsFiles.valThem
Annex/AutoMerge.hs:	{- Stage a graft of a directory or file from a branch
Annex/AutoMerge.hs:	graftin b item selectwant selectwant' selectunwant = do
Annex/AutoMerge.hs:		-- Update the work tree to reflect the graft.
Annex/AutoMerge.hs:			-- So, when grafting in a symlink, we must create it:
Annex/AutoMerge.hs:			-- And when grafting in anything else vs a symlink,
Annex/AutoMerge.hs:				-- in the work tree; replace with grafted
Annex/Branch.hs:rememberTreeish treeish graftpoint = lockJournal $ \jl -> do
Annex/Branch.hs:	addedt <- inRepo $ Git.Tree.graftTree treeish graftpoint origtree
Annex/Branch.hs:		"graft" [branchref] addedt
Annex/Branch.hs:		"graft cleanup" [c] origtree
Annex/Import.hs:	-- ^ Import a tree from the remote and graft it into a subdirectory
Annex/Import.hs: - When a subdir is provided, imported tree is grafted into the basetree at
Annex/Import.hs:				graftTree' importtree subdir basetree repo hdl
Annex/RemoteTrackingBranch.hs: - RemoteTrackingBranch, while grafting new git history into it.
Git/Tree.hs:	graftTree,
Git/Tree.hs:	graftTree',
Git/Tree.hs: - down to the graft location. It does not buffer the whole tree in memory.
Git/Tree.hs:graftTree
Git/Tree.hs:graftTree subtree graftloc basetree repo =
Git/Tree.hs:	withMkTreeHandle repo $ graftTree' subtree graftloc basetree repo
Git/Tree.hs:graftTree'
Git/Tree.hs:graftTree' subtree graftloc basetree repo hdl = go basetree graftdirs
Git/Tree.hs:		t' <- case partition isabovegraft t of
Git/Tree.hs:				graft <- graftin (topmostgraphdir:restgraphdirs)
Git/Tree.hs:				return (graft:t)
Git/Tree.hs:					_ -> graftin (topmostgraphdir:restgraphdirs)
Git/Tree.hs:	isabovegraft i = beneathSubTree i graftloc || gitPath i == gitPath graftloc
Git/Tree.hs:	graftin t = recordSubTree hdl $ graftin' t
Git/Tree.hs:	graftin' [] = RecordedSubTree graftloc subtree []
Git/Tree.hs:	graftin' (d:rest) 
Git/Tree.hs:		| d == graftloc = graftin' []
Git/Tree.hs:		| otherwise = NewSubTree d [graftin' rest]
Git/Tree.hs:	-- For a graftloc of "foo/bar/baz", this generates
Git/Tree.hs:	graftdirs = map (asTopFilePath . toInternalGitPath . encodeBS) $
Git/Tree.hs:		mkpaths [] $ splitDirectories $ gitPath graftloc
Logs/Export.hs:-- Also, the newTreeish is grafted into the git-annex branch. This is done

```
</details>

**Comment by yarikoptic** [comment]
filter-branch (filter-repo) approach would also be useful to "redo" pure `git` , or suboptimal `git-annex` (too much committed into git) repository. The overall workflow generally is
- go to some old commit which is still ok.  If the entire history needs to be redone gets trickier since more likely would cause some conflicts due to the next step.
- adjust `.datalad/config` (for fakedates) and/or `.gitattributes` (for adjusted git-vs-git-annex allocations etc)
- redo history

**Comment by yarikoptic** [comment]
it is 2 year old wishlist issue, no comments from outside of the core team, so unlikely there is big demand etc. Let's let it RiP
