### ISSUE TITLE
push: -J seems to be of no "effect"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4704]
Trying to push a dataset

```
$ datalad push --to=datalad-public -r -J4
```
with `wanted` setting.  I see only a single progress bar appearing per each file, and `dstat` shows intermissions between transfers, suggesting that there is no parallel transfer of multiple files and reflecting on the fact that data transfer will be slow. Process table looks like:
```
yoh      2165602  0.0  0.0  11064  2412 pts/6    S+   12:15   0:00  |               \_ /usr/lib/git-annex.linux/exe/git --library-path /usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/gconv:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/audit:/usr/lib/git-annex.linux//etc/ld.so.conf.d:/usr/lib/git-annex.linux//lib64:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu:/usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git/git annex copy --batch -z --to datalad-public --json --json-error-messages --json-progress --jobs 4 --auto --fast
yoh      2165617 40.6  0.0 1074523132 58660 pts/6 Sl+ 12:15   1:24  |                   \_ /usr/lib/git-annex.linux/exe/git-annex --library-path /usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/gconv:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu/audit:/usr/lib/git-annex.linux//etc/ld.so.conf.d:/usr/lib/git-annex.linux//lib64:/usr/lib/git-annex.linux//usr/lib/x86_64-linux-gnu:/usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-annex.linux/shimmed/git-annex/git-annex copy --batch -z --to datalad-public --json --json-error-messages --json-progress --jobs 4 --auto --fast
```
which is `--batch` suggesting that we are feeding paths to be copied (I guess here it should be none).  Didn't look inside but I suspect that may be `push` feeding annex with some single path at a time and waits for response before proceeding to the next one, which completely annihilates any benefit from `-J` specification. Of cause it could also be some limitation of `git-annex` in batch mode that -J is not in effect then.  But in either case -- seems to be a broken promise from datalad.

DX note: running with `-l debug` or even with `-l 2` provided no additional clues whatsoever what is fed into git-annex in batch mode there

datalad 0.13.0.dev44 , git-annex 7.20190819+git2-g908476a9b-1~ndall+1 .

**Comment by mih** [comment]
I tried this on current master. It works:

![image](https://user-images.githubusercontent.com/136479/143576916-bbee389d-534a-4bfe-8464-9018ed426ea9.png)

This is the process tree for `datalad push -J 2 --to juseless` using a RIA/ORA combo via SSH`. As expected, there are two simultaneous `scp` processes.

I am closing this now, it seems it was resolved since the original report.
