### ISSUE TITLE
FOI: reusing the same ssh control path creates ssh bottleneck in transfer

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4705]
There is a single `sshd` process started per socket on the server side.  Transferring data through a single socket leads to it 100% CPU and thus limits transfer speeds.
In my case it was two separate `annex copy` processes in different subdatasets.  Running with the same `-c remote.datalad-public.annex-ssh-options='-o ControlMaster=auto -S /home/yoh/.cache/datalad/sockets/b0da704a'` bottlenecked at CPU as mentioned above.  Starting 2nd one without `-c remote.datalad-public.annex-ssh-options` resulted in two `sshd` processes and throughput pretty much doubling.

I have no good ideas ATM on how to mitigate.
Attn @joeyh

**Comment by joeyh** [comment]
Positive the bottleneck was server side?

This seems surpsising enough it could be considered a bug in ssh.
Perhaps we could find a way around it in git-annex using multiple
ssh sockets, although that risks ssh multiple password prompts.

-- 
see shy jo

**Comment by yarikoptic** [comment]
> Positive the bottleneck was server side?

99% confident ;) I should have screenshotted -- I saw a single sshd at 100% when two processes went through a single socket, and then I saw two sshd at under 100% whenever I had 2nd one not using the same socket.

FTR: on client side I had openssh-client (1:7.9p1-10) and on server openssh-server (1:7.4p1-10+deb9u7)

I think the situation would be pertinent only to high throughput networks (here I had 10Gbit) and/or less powerful boxes, so I guess we shouldn't rush into "resolving" it if there is a sacrifice to make (like multiple password prompts).

**Comment by mih** [comment]
Is there anything we can and would want to do about this in the near future? If not, I'd vote for closing this.

**Comment by yarikoptic** [comment]
I think we indeed could do something about it, although what exactly -- "not sure". Plan of action could be
- confirm my observation (may be I was wrong as @joeyh suspected and that ssh should have bottlenecked even while reusing the same socket)
- see how we could decide to have a "pool" of sockets for the same host

either it would be looked at in the "near future" -- who knows. At least with #5042 there is a way to disable multiplexing and in case of using keys try out if would give some remedy.

Anyways -- in the ongoing "issues witch hunt" fashion, I guess I will close it, so it could come like a phoenix from ashes if someone hits this limitation too.
