### ISSUE TITLE
helper to automate commits for the datasets (including super-datasets and its "children")

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#472]

**Comment by hanke** [comment]
#682 does something along those lines for meta data aggregation. I think `save()` could be enhanced to implement `--recursive`.

**Comment by mih** [comment]
`save` has help for some time now. Closing.

**Comment by yarikoptic** [comment]
Well, it still does nothing for the superdatasets, so only partially addressed... And using -d^ would still be different solution since then might save some other modified subdatasets of the superdataset. I wonder what option be the option to add (--include-supers, -s), or should we obscure --recursionl-evel to be able to specify eg "sublimit:superlimit" reserving -1 for unlimited?

**Comment by yarikoptic** [comment]
ok -- assigned to myself.  Will implement by adding '--supers,-S' (`-s` conflicts with `--source,-s`) to `save` call. For now -- all of them, without limit, but stopping at the upmost dataset (if it is just a repo, without our .datalad/config -- not a dataset)
