### ISSUE TITLE
What filenames are (il)legal?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4728]
Digging into test failures on crippled filesystems I found that we still use random collections of characters as test filenames in some places. We cannot expect them to work on windows.

Here is a helpful link: https://kb.acronis.com/content/39790

Summary: no `/ ? < > \ : * | "` and any character you can type with the Ctrl key, also no `^` on FAT and no space or `.` at the end of the filename

**Comment by yarikoptic** [comment]
And we take the most obscure over which file system supports: https://github.com/datalad/datalad/blob/master/datalad/tests/utils.py#L1444

**Comment by bpoldrack** [comment]
We didn't, @yarikoptic . See PR #4733.

**Comment by yarikoptic** [comment]
Was may be the actual reason - absence of that `TMPDIR` directory? see
https://github.com/datalad/datalad/pull/4708#issuecomment-658795652

**Comment by bpoldrack** [comment]
Not only, but that's certainly part of it. There's more we did wrong and for the particular issue here, there's hardcoded obscurity in addtion as Michael shows in #4730

**Comment by mih** [comment]
I think this can go on record now.
