### ISSUE TITLE
ENH: add [RUNID] option to `install-annex.sh datalad-extensions-build`

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4740]
inspired by https://github.com/datalad/datalad-extensions/issues/22, relates to https://github.com/datalad/datalad-extensions/pull/23 (to always have .deb even if git annex tests fail)

ATM `install-annex.sh datalad-extensions-build` downloads the most recent successful (AFAIK) build done in master on cron.  Whenever git-annex fails datalad tests we do have a .deb we could install from artifacts even though the overall build fails.
If would be nice to streamline those build artifacts installations

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
