### ISSUE TITLE
(Re)move automagic IO functionality?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4742]
It has issues and future plans:

- https://github.com/datalad/datalad/issues/4724
- https://github.com/datalad/datalad/issues/2062

Looking at https://github.com/datalad/datalad/blame/master/datalad/auto.py the code has not been touch in 3-5 years (minus small fixes motivated by outside changes). This either means it is perfect, or unused.

I have personally not used this functionality and I am not aware that it is being used. Given the nature of it, I feel it is more suitably placed in a dedicated package, rather than at the core of datalad.

How do you feel about this?

**Comment by bpoldrack** [comment]
I feel similarly - an extension package seems more appropriate to me given how the ecosystem evolved since this was written.

**Comment by mih** [comment]
I am preparing a move of code and tests to -deprecated -- analog to the webUI transition.
