### ISSUE TITLE
rerun: add ability to rerun into a "new" dataset to facilitate rerun on dataset hierarchies

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4765]
As @kyleam has reminded during the call, one of the outstanding issues with `rerun` is inability to do anything about changing the state of subdatasets upon rerun.  The major stumbling point is inability to record/recall states (https://github.com/datalad/datalad/issues/1424) of dataset(s) hierarchy: the issue was identified awhile back, discussed a number of times, but its implementation IIRC wasn't even attempted since logistics would be quite complicated, especially since (unlike `git`) we install submodules `.git/` (instead of establishing a link to some centralized `.git/modules` in some super-dataset). 

**The overall idea**: add an option to `rerun`, such as `--sibling-path PATH`, which would in a nutshell be:

- install "reran" dataset at the `since` version into that new PATH (original dataset would become origin, all commits are accessible)
  - the only TODO is to implement generic "install at version X"  (see #1810) which is currently supported only for RIA remotes  (implemented in #4022)
- carry out rerun in that "new" dataset 
  - the only TODO as far as I see is the ability to implement recursive `rerun` where changes in the submodule hexsha within its parent repository should be tracked as well regarding the diff etc`*`, `**`.  In a nutshell it should just translate to the series of recursive `rerun` calls within subdatasets.

`*` I feel like we had mentioning of this in some issue/PR but failed to search it up

`**` Needed only if subdataset had a diff for a commit in its super dataset which had no RUNCMD record, and contained some commits with RUNCMD record (so needs independent rerun) or it had participated in some `rerun` before.  So in some cases we don't even need to rerun recursively, but just `update` subdataset to the new state.

Unless I am not seeing some additional steps/aspects, implementing those two "steps" should be sufficient to make `rerun` usable with YODA style dataset hierarchies, while avoiding need for a more complicated "in-place" #1424. Resultant "new" dataset (hierarchy) could then be interrogated with `datalad diff [-r]` regarding differences to the state of its "origin" to verify reproducibility etc.   Regular `rerun` invocation could just error out with a message to use this new mode of operation if it detects any change within subdataset as part of the protocol to rerun.

Sugarings to add on top:

- `--wreckless=mode` option to be applied for any (sub)dataset found installed in the original location  (some subdatasets might need to be installed from the original location, thus would require non-wreckless handling) (this could be really useful! we could introduce it first as a configuration item and if there is  demand - add an option)
- option to add "new" dataset as a sibling to the current dataset or relevant (the ones "touched" by `rerun`) hierarchy of subdatasets (although largely not necessary IMHO)

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
