### ISSUE TITLE
Idea (failing so far): Do all necessary for ssh tests hostnames setup within our `setup_package` fixture

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4771]
continuation from https://github.com/datalad/datalad/pull/4762#issuecomment-664504230

#### What is the problem?

To run ssh tests we need to tune `/etc/hosts` to setup the `datalad-test` hostname... With #4762 it would become required for all ssh tests.  In some cases I will not have such ability even if ssh is installed and I can `ssh localhost`.

With this apsect (local boxes and all CIs with /etc/hosts and/or `.ssh/config` tune ups) in mind it hit me: did we ever try to just establish `~/.ssh/config` within our custom `$HOME` we use for testing? 
 If we didn't and there is no show stopper (although looks like there is - see below), then an ultimate solution, which would avoid any box/CI "manual" configuration (of /etc/hosts and ssh) would be:
- add datalad configuration items `datalad.tests.ssh_hosts.datalad_test` and `datalad.tests.ssh_hosts.datalad_test2` which would both default to `localhost:22` 
- in https://github.com/datalad/datalad/blob/master/datalad/__init__.py#L128 establish `~/.ssh/config` with `Host` entries for each of those `datalad-test`s (there is some `if` where we reuse GIT_HOME but I think it is purely for debian pkg building where we do not run any ssh tests anyways)
- in those few tests were exact knowledge of the port is desired, it could be parsed out from config (e.g. via SSHRI) if use of `ssh -G` seems like a heavier thing to do.

Then it should work as is for any local testing (even if we add more named hosts there) and for CI we would need to just provide that CIs custom configuration through the exports of two environment variables without additional helpers. 

But then I decided to give it a quick try to fail.

<details>
<summary>Q&D patch for the fixture</summary> 

```shell
$> git diff
diff --git a/datalad/__init__.py b/datalad/__init__.py
index 4504aace0..da15dc41d 100644
--- a/datalad/__init__.py
+++ b/datalad/__init__.py
@@ -120,11 +120,19 @@ def setup_package():
             os.environ['HOME'] = new_home
         if not os.path.exists(new_home):
             os.makedirs(new_home)
+            os.makedirs(os.path.join(new_home, '.ssh'))
         with open(os.path.join(new_home, '.gitconfig'), 'w') as f:
             f.write("""\
 [user]
        name = DataLad Tester
        email = test@example.com
+""")
+        with open(os.path.join(new_home, '.ssh', 'config'), 'w') as f:
+                f.write("""\
+Host datalad-test
+    Port 22
+    Hostname localhost
+    StrictHostKeyChecking no
 """)
         _TEMP_PATHS_GENERATED.append(new_home)
 ```
</details>

failure `#1`: for some reason `ssh` simply ignores `HOME` and still tries to go for `/home/yoh/.ssh/`:

```ssh
$> SSH_TTY= SSH_AUTH_SOCK= SSH_CLIENT= SSH_CONNECTION= SSH_AGENT_PID= USER=blah HOME=/home/yoh/.tmp/datalad_temp_zj4pfl0z ssh -v -v datalad-test
OpenSSH_8.1p1 Debian-5, OpenSSL 1.1.1g  21 Apr 2020
debug1: Reading configuration data /home/yoh/.ssh/config
debug1: /home/yoh/.ssh/config line 337: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Control socket "/home/yoh/.ssh/controls/yoh@datalad-test:22" does not exist
debug2: resolving "datalad-test" port 22
ssh: Could not resolve hostname datalad-test: Name or service not known

$> cat /home/yoh/.tmp/datalad_temp_zj4pfl0z/.ssh/config
Host datalad-test
    Port 222
    Hostname localhost
    StrictHostKeyChecking no
```
so it seems that internally `ssh` does not care about `$HOME` at all! (note: `$HOME` is *nix specific for ssh, according to https://github.com/PowerShell/Win32-OpenSSH/issues/1146 on windows there is `%userprofile%` but that one might be readonly, heh heh -- failure `#2`)

So may be this idea is no go, unless someone sees some way

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
