### ISSUE TITLE
"Argument list too long: 'git-annex' " error while using datalad save

### ISSUE THREAD

**Issue by Hoda1394** [datalad/datalad#4778]
I added some files to a dataset and I want to save them with one commit. datalad save ./  raises this error:
Argument list too long: 'git-annex' [subprocess.py:_execute_child:1551]
the files are 27 folders but each one has subfolder and files. I can do separate datalad save <folder_path>/ but it is time consuming while making the history unnecessarily crowded. So, Is there another way of saving those files?
I saw [#1865](https://github.com/datalad/datalad/issues/1865), and it seems I am having the same problem again.

datalad version: 0.13.1 and I am using it on a Linux based HPC system.

**Comment by kyleam** [comment]
Hmm, we try to determine a maximum argument length here:

https://github.com/datalad/datalad/blob/5eaec0f08ee66e204d0adce03e51d028beb6444a/datalad/utils.py#L110-L137

And then the `git annex add` call should be split into multiple calls as needed.

It seems that's not coming up with anything useful for the machine you're on.  What does

```
python -c "import os; print(os.sysconf('SC_ARG_MAX'))"
```

report on that system?

Running with `datalad -l debug ...` might also give a hint at what's going on.

**Comment by Hoda1394** [comment]
`os.sysconf('SC_ARG_MAX')` is 768000000 on the system.
and `datalad -l debug save` returns:
```
[DEBUG  ] 74064 path(s) to add to AnnexRepo(<repo_path>)  
Total:   0%|              | 0.00/874G [00:00<?, ?B/s]
[DEBUG  ] Process file list chunk 0 (length 74064) 
[Level 11] Failed to start ['git-annex', 'add', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', '--json', '--json-error-messages', '--',                                                      

```
followed by list of files.

**Comment by yarikoptic** [comment]
Wow, so it is ~360 times larger than on mine.  Would you mind sharing output of `datalad wtf` so we could see details of the system?  most likely #3150 needs a better investigation and a proper fix.

Meanwhile we could remove 
```
if sys.version_info[:2] == (3, 4): 
```
and just always limit to a sensible value, or at least do it on Linux (the other OSs sensible values are so "tiny").

**Comment by kyleam** [comment]
> `os.sysconf('SC_ARG_MAX')` is 768000000 on the system

Does `getconf ARG_MAX` in the shell agree with that value?  If so, it seems likely that the system is reporting an inappropriately large value.

**Comment by Hoda1394** [comment]
@kyleam `getconf ARG_MAX` returns the same amount. 
@yarikoptic attached info
[datalad_wtf.txt](https://github.com/datalad/datalad/files/4990695/datalad_wtf.txt)

**Comment by yarikoptic** [comment]
THANK YOU.  The excerpt in relation to the code mentioned above:

```
## python
  - implementation: CPython
  - version: 3.7.7
## system
  - distribution: CentOS Linux/7.7.1908/Core
```

**Comment by Hoda1394** [comment]
> THANK YOU. The excerpt in relation to the code mentioned above:
> 
> ```
> ## python
>   - implementation: CPython
>   - version: 3.7.7
> ## system
>   - distribution: CentOS Linux/7.7.1908/Core
> ```

@yarikoptic can I remove the attached config file now?

**Comment by yarikoptic** [comment]
If you need to, we typically just cut/paste them here

**Comment by yarikoptic** [comment]
BTW, would you be able to patch (edit) that code above mentioned in https://github.com/datalad/datalad/issues/4778#issuecomment-665171865 (make it always take the min, even with python 3.7)  to get you going?

**Comment by yarikoptic** [comment]
We haven't observed this in the wild in a while, and many things were changed. But feel welcome to reopen @Hoda1394 if you still encounter this issue

**Comment by Hoda1394** [comment]
Thanks, actually, many things are also changed on our side either. So we may not want to do the same thing anymore. But I will reopen if I encounter it again.
