### ISSUE TITLE
RFC: how to organize our UI/logging 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#478]
ATM our UI, in particular any "real-time" feedback from downloads, is pretty much non-existent. `download-url` reports nicely with a progress bar but generally that functionality is not used because of all the sandwiching of calls from datalad into git-annex , which  in turn might call to wget/quvi/... to download its content, or git-annex-remote-datalad\* remotes, which in turn might call git-annex again to fetch e.g. the "mother" tarball, which in turn might also go to wget OR back to git-annex-remote-datalad*...  Few points:
1. I think we can't allow for all output from git-annex (and its calls to wget/...) to simply be dumped on the screen, and in some cases, there is no output if we use annex in batched mode
2. At least for all use-cases we care about we could make annex use our git-annex-remote-datalad to download content from `http://` (we do already for all `s3://`)

So I am wondering, if our UI, which probably should also handle logging output (currently "independently dumped"), should be a little parallel process within datalad which would then communicate via some socket, we define some `DATALAD_UI_SOCKET` env variable so that any child process which would be started directly by us, or by annex, could reach out to the master UI process and report its logs/progress in downloads, or request some info interactively (so such commands should be atomic, so that UI is pretty much 'stateless' but deals with e.g. UI object IDs... more on that later if overall idea would be sound)

I foresee cmdline UI (in TTY mode where we have better control allowing rewrite previous lines, etc) then which would be comprised from 
1. (on top) log msgs if any at current level
2. and what is handled by UI ATM:
- active "updatable" progress indicators, e.g. progress bars for the processes which are currently running:
  
  ```
   - Downloaded (...%) X out of Y files (... failed), (...%) ...MB out of ...MB  (in words or as a progressbar)
   - ongoing per file downloads (progress bars)
  ```
- high level messages  (may be should be melded into logging at INFO or even some higher (INFO + 5) level?)
- Interactive UI element (e.g. requests for user/passw information, which might come from deep inside the guts of the sandwich), which then would disappear (only some log line might refect in 1 that it happened) after it is "done".

In non-interactive mode interactive UI wouldn't be allowed, and downloads progress indicators could also be gone just relying on the log msgs.  Standardizing such an interface might later allow for easy custom other views: we might want to provide some custom mode for "within Python or IPython" operation, or in web ui happen we get there some time.

Related references for git-annex discussion:  annex does support concurrent output now https://git-annex.branchable.com/todo/parallel_get/
@joeyh - do you think it would be possible to somehow make annex calls report progress on downloads back to parent process somehow, now that you are tracking/reporting progress yourself while in -J mode? (note that even -J1 makes annex report progress on its own shushing wget )
Even though we do report back from our custom downloaders back to annex about progress, I am afraid it wouldn't be sufficient due to 
- possible necessity for interactive UI (although the easiest could still be just crash and demand specifying credentials prior, but that ruins interactivity since credentials might be entered incorrectly)
- annex not reporting progress during batch mode of addurl
- probably our desire for somewhat customized display, to e.g. hide per item downloads progress indicators/reports after those downloads are complete, aiming for leaner reporting that annex does.

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> Related references for git-annex discussion: annex does support concurrent
> output now https://git-annex.branchable.com/todo/parallel_get/
> @joeyh - do you think it would be possible to somehow make annex calls report
> progress on downloads back to parent process somehow, now that you are tracking
> /reporting progress yourself while in -J mode? (note that even -J1 makes annex
> report progress on its own shushing wget )
> Even though we do report back from our custom downloaders back to annex about
> progress, I am afraid it wouldn't be sufficient due to

The --json output could include progress info in it somehow, possibly.

Or, a flag could enable some other progress reporting, perhaps to a
separate FD. I'm clearer on how this would work, and it could use the
same format as the special remote protocol does, so it like it a bit
more.

I think that datalad would have to be responsible for propigating that
progress info from the subsidiary git-annex to the parent git-annex when
it's doing that kind of nested download.

Note that git-annex updates .git/annex/transfer/ files for keys
being downloaded with progress info. This is used by some things
including the webapp.

-- 
see shy jo

**Comment by yarikoptic** [comment]
Just an interesting (to me) note that apparently that is how also apt-get interacts with dpkg, where dpkg reports status updates to an fd (passed on cmdline):
```
$> grep -r status.*fd -A2 .
./main.c:"  --status-fd <n>            Send status change updates to file descriptor <n>.\n"
--
./main.c:  { "status-fd",         0,   1, NULL,          NULL,      set_pipe, 0 },
--
./help.c:  statusfd_send("processing: %s: %s", action,
./help.c-                pkgbin_name(pkg, pkgbin, pnaw_nonambig));
./help.c-}
--
./configure.c:	statusfd_send("status: %s : %s : '%s' '%s' %i %i ",
./configure.c-	              cfgfile, "conffile-prompt",
./configure.c-	              realold, realnew, useredited, distedited);
--
./errors.c:  statusfd_send("status: %s : %s : %s", pkgname, "error", emsg);
--
./errors.c:  statusfd_send("status: %s : %s : %s", filename, "error", emsg);
```

**Comment by yarikoptic** [comment]
TODO within annex:  http://git-annex.branchable.com/todo/interface_to_the___34__progress__34___of_annex_operations/

**Comment by yarikoptic** [comment]
note that @joeyh joey has done it already! ;)

```shell
$> git annex version
git-annex version: 6.20160923+gitgd1dabb3-1~ndall+1

$> git annex get -J3 --json --json-progress 10*
{"command":"get","note":"checksum...","success":true,"key":"SHA256E-s15530--fd99a77abcb4bbb7242123b43ba9784ba76af33f06d3c30300a69fd9541670eb.nii.gz","file":"1003/13874.nii.gz"}
{"command":"get","note":"checksum...","success":true,"key":"SHA256E-s18347--767e77208e4e5c9e8739e17e99be963528cdb58876d93d6da58fbb41c1627b34.nii.gz","file":"1003/13876.nii.gz"}
{"command":"get","note":"checksum...","success":true,"key":"SHA256E-s19701--32a50d75acca0518dc21aacc9bae62c8ae6d5a586a2f4bf1e0dd4e6007982132.nii.gz","file":"1003/13877.nii.gz"}
...
```

so we can support parallel downloads of git-annex, just need to track downloads per each key.

**Comment by yarikoptic** [comment]
this issue is largely solved. The only thing we are 'hiding' ATM is downloads of big tarballs when a file from a tarball is asked for.  The other aspects of UI/Logging are discussed in freshier #1476
