### ISSUE TITLE
datalad push --data nothing doesn't push the annex branch

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#4780]
We're pushing a dataset into a RIA store without a storage sibling (``bulk1``). We try to be explicit about not pushing data in the script, and hence add ``--data nothing`` to ``datalad push``.
However, a `datalad push --to bulk1 --data nothing` only pushes ``master``:

```
$ datalad push --to bulk1 --data nothing
# refs in RIA store only have master, not git annex:
$ ls /data/project/ukb_vbm/dsstore/156/28c7a-d1af-11ea-bbf2-ac1f6b8b1606/refs/heads 
master

# git-annex branch is only pushed without --data nothing
$ datalad push --to bulk1
$ ls /data/project/ukb_vbm/dsstore/65d/fd6d4-d1b0-11ea-9471-b4969146869c/refs/heads
git-annex  master
```

Given the documentation,

```
       --data {anything|nothing|auto|auto-if-wanted}
              what to do with (annex'ed) data. 'anything' would cause transfer of all annexed content, 'nothing'
              would avoid call to `git annex copy` altogether. 'auto' would use 'git annex copy'  with  '--auto'
              thus  transferring  only  data which would satisfy "wanted" or "numcopies" settings for the remote
              (thus "nothing" otherwise). 'auto-if-wanted' would enable '--auto' mode only if there is a  "want‐
              ed"  setting  for the remote, and transfer 'anything' otherwise. Constraints: value must be one of
              ('anything', 'nothing', 'auto', 'auto-if-wanted') [Default: 'auto-if-wanted']
```

I would expect that the annex branch should be pushed nevertheless.

**Comment by yarikoptic** [comment]
> I would expect that the annex branch should be pushed nevertheless.

I would have expected so too!  It kinda takes "--data nothing" really literally ;)  There might even be a use case where it is really desired to push neither data nor its availability (git-annex branch), but I do not think that is what we had in mind here.  When (if) such use case comes up we could add "absolutely-nothing" and meanwhile fixup "nothing" to still push git-annex branch ;)  I guess we just return somewhere too prematurely in `push`.

BTW, I think with `--data auto` you should achieve desired effect (unless you did set 'wanted' for that sibling)

**Comment by kyleam** [comment]
> However, a `datalad push --to bulk1 --data nothing` only pushes `master`:

The git-annex is branch is pushed as of 17541fa6c1 (OPT: Consolidate on a single `git-push` call in `push()`, 2020-07-12).  That was done for performance reasons and involved a fair amount of restructuring, so it made sense for that to go to master.

But it applies cleanly to maint and, given the issue you raise, I think it'd be good to cherry pick it, along with a commit that adds a test for the "git-annex branch is pushed" expectation.

<details>
<summary>demo</summary>

```sh
set -ue

cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-push-XXXXXXX)"
ria_path="$(pwd)"/ria
datalad create a
(
    cd a
    datalad create-sibling-ria --no-storage-sibling -s ria \
            ria+file:"$ria_path"
    echo 0 >f0
    datalad save
    datalad push --to=ria --data=nothing
)
find ./ria | grep refs/heads/
```

</details>

**Comment by kyleam** [comment]
> But it applies cleanly to maint and, given the issue you raise, I think it'd be good to cherry pick it, along with a commit that adds a test for the "git-annex branch is pushed" expectation.

I'll open a PR doing that at some point later today.
