### ISSUE TITLE
test_annex_ssh failure due to non-existent socket (again)

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#4781]
In the most recent Travis build on master, [one job][0] had a failure in `test_annex_ssh`:

```
======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_annex_ssh
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 271, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 731, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/support/tests/test_annexrepo.py", line 1202, in test_annex_ssh
    ok_(exists(socket_2))
AssertionError: None
```

That failure has come up before in an earlier iteration of gh-4762. I thought I worked around it with b46b4cbbcd (TST: test_annex_ssh: Avoid syncing unrelated histories, 2020-07-21). A similar (but not identical) failure popped up in gh-4768 (which was before the Docker ssh switch), and that failure didn't show up after the changes from the above commit were cherry picked.

So, despite b46b4cbbcd appearing to clear up the failures in those PRs, it seems it's still an issue.

[0]: https://travis-ci.org/github/datalad/datalad/jobs/712974813#L2001

**Comment by kyleam** [comment]
This `test_annex_ssh` failure was triggered in a Travis run restricted to the `test_annexrepo` module where I was trying to trigger the `test_AnnexRepo_commit` failure from gh-4773.  The run was with `DATALAD_LOG_OUTPUTS=1` and `DATALAD_LOG_LEVEL=5`, so perhaps if provides some clue about what's going on here.

https://travis-ci.org/github/datalad/datalad/builds/715171614

That is on top of maint (7ff697da2), with only changes to the ci files.

**Comment by yarikoptic** [comment]
FWIW: Looking at the test code -- I think this particular test might be racy although I do not see how:

- we test that the socket still exists (`ok_(exists(socket_2))`) (according to line 1202 in master) it is 
```python
    # copy to the new remote:
    ar.copy_to(["foo"], remote="ssh-remote-2")

    ok_(exists(socket_2))
```
which is not the test above that which tests depending on either it existed or not before.
- that means that if some other test started it some time before it might have existed to start with
- but we start those sockets with time out -- from sshconnector.py
```python
        # set control options
        ctrl_options = ["-fN",
                        "-o", "ControlMaster=auto",
                        "-o", "ControlPersist=15m"] + self._ssh_args
```
- so if by chance we arrive into this part of the test when some prior test started it about 15m ago, and then times out while we go through the test, we end up without socket being available upon completion of copy

I did not spot though any other test which could have started that socket "before" (so I am not sure why we still have those `if` existed before besides may be interference on local runs) and this particular test is not taking 15m...

for further troubleshooting it might be worthwhile to at least provide a custom message for that test which would announce either socket existed or not before starting the copy and act accordingly, e.g.

```diff
diff --git a/datalad/support/tests/test_annexrepo.py b/datalad/support/tests/test_annexrepo.py
index 5b1249ba8..a2f3bf43d 100644
--- a/datalad/support/tests/test_annexrepo.py
+++ b/datalad/support/tests/test_annexrepo.py
@@ -1196,10 +1196,16 @@ def test_annex_ssh(topdir):
     else:
         ok_(not exists(socket_2))
 
+    # reset our knowledge about socket existence or not since above check
+    # is skipped on V6 in some cases
+    datalad_test2_was_open = exists(socket_2)
     # copy to the new remote:
     ar.copy_to(["foo"], remote="ssh-remote-2")
-
-    ok_(exists(socket_2))
+    if not datalad_test2_was_open:
+        ok_(exists(socket_2))
+    else:
+        ok_(exists(socket_2))
+    # To be decided to close unconditionally?
     ssh_manager.close(ctrl_path=[socket_1, socket_2])
 
 
```

**Comment by kyleam** [comment]
> * so if by chance we arrive into this part of the test when some prior test started it about 15m ago, and then times out while we go through the test, we end up without socket being available upon completion of copy

A point against that idea: the [test][1] I linked to above was with just the `test_annexrepo` module and the entire thing only ran for 7 minutes.

[1]: https://travis-ci.org/github/datalad/datalad/builds/715171614

**Comment by yarikoptic** [comment]
Hm, indeed... I would say - f.ck it ;-) something closes the socket or doesn't even create it (?! Btw, is it even getting created as part of that copy call? I will check later in the logs of anything on that) - at least we aren't keeping unexpected sockets around ;-)

**Comment by kyleam** [comment]
> Btw, is it even getting created as part of that copy call?

Yes, it is for me locally and in a Xenial VM.

**Comment by yarikoptic** [comment]
And in the logs of jobs were don't explicitly close it? If not - f.ck it - some ssh bug ;-)

**Comment by yarikoptic** [comment]
Or is it git-annex which does that?!

**Comment by kyleam** [comment]
> And in the logs of failed jobs we don't explicitly close it?
> Or is it git-annex which does that?!

I think I'm missing the point, but a perhaps related note: Even for successful runs, our calls to `SSHManager.close` do not close the sockets created by `test_annex_ssh`.  The reason is that the test avoids doing anything that triggers our `SSHConnection.open`, instead testing that the git-annex operations opens them.  So, at closing time [*] the sockets are left as is because they were not opened by the `SSHConnection` instance itself.

[*] ... the explicit `.close` in that test, but the same would be true if we removed it and let it be handled by the `SSHManager.close` that we register atexit.

**Comment by kyleam** [comment]
I haven't seen this in quite a while.  Without the ability to trigger it, I guess the best we can hope for is that it stays away.
