### ISSUE TITLE
git-annex/ora-remote SSH session handling broken/odd/suboptimal

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4797]
Scenario: `git annex copy -J 5` via an `ora special remote via SSH. Lots of smallish files (330k with a total of 250GB).

What I think should happen is that git-annex starts 5 ora-remote processes. Each of them opens a connection (possibly through a single ControlMaster), each connection leads to a single persistent shell session on the remote. So unless something goes wrong, I should see 5 stable SSH sessions on the remote.

However, that is not what happens:

```Aug  4 18:29:00 bulk1 systemd[1]: Started Session 173366 of user mih.
Aug  4 18:29:00 bulk1 systemd[1]: session-173366.scope: Succeeded.
Aug  4 18:29:00 bulk1 systemd[1]: Started Session 173367 of user mih.
Aug  4 18:29:00 bulk1 systemd[1]: Started Session 173368 of user mih.
Aug  4 18:29:00 bulk1 systemd[1]: session-173367.scope: Succeeded.
Aug  4 18:29:00 bulk1 systemd[1]: session-173368.scope: Succeeded.
Aug  4 18:29:00 bulk1 systemd[1]: Started Session 173369 of user mih.
Aug  4 18:29:00 bulk1 systemd[1]: session-173369.scope: Succeeded.
Aug  4 18:29:00 bulk1 systemd[1]: Started Session 173370 of user mih.
Aug  4 18:29:00 bulk1 systemd[1]: Started Session 173371 of user mih.
Aug  4 18:29:00 bulk1 systemd[1]: session-173370.scope: Succeeded.
Aug  4 18:29:00 bulk1 systemd[1]: session-173371.scope: Succeeded.
Aug  4 18:29:01 bulk1 systemd[1]: Started Session 173372 of user mih.
Aug  4 18:29:01 bulk1 systemd[1]: Started Session 173373 of user mih.
Aug  4 18:29:01 bulk1 systemd[1]: Started Session 173374 of user mih.
Aug  4 18:29:01 bulk1 systemd[1]: session-173373.scope: Succeeded.
Aug  4 18:29:01 bulk1 systemd[1]: session-173372.scope: Succeeded.
Aug  4 18:29:01 bulk1 systemd[1]: session-173374.scope: Succeeded.
...
```
There are tons of sessions being started.

I stumbled upon this, because the overall data transfer was slow. Then I noticed CPU load on my laptop that looked as if it would be providing auth credentials all the time (the git-annex transfer was not from my laptop, but I use SSH agent forwarding). And indeed, when I disconnected from the tmux session the transfer eventually stalled, asking for a password.

This is with ora-remote from datalad 0.13.1 and `git-annex version: 8.20200330`

```
% git cat-file -p git-annex:remote.log
1eedf1f0-0da4-416d-a7e9-9eb8b3d8125d archive-id=7322bb7c-b617-11ea-aad3-b4969157768c autoenable=true encryption=none externaltype=ora name=inm7-storage type=external url=ria+ssh://enki.ds.inm7.de/ds/enki/srv timestamp=1596554753.792935681s
```

Ping @bpoldrack

**Comment by mih** [comment]
Looked through the code. I forgot that uploads are not (yet?) using the persistent shell session on the remote machine, but are handled via individual `scp` calls that use the connection manager. That means that many sessions are needed (keep in mind 300k mostly tiny files). The server has `MaxSessions` set to 10. With connection sharing we would have one persistent shell session per special remote process, plus any `scp` shells. This caused the server to drop sessions (and likely connections). Leading to re-auth and overall slowdown.

Setting `MaxSessions` to 100 mitigates the issue and give a stellar throughput in comparison.

I am closing this issue now. A related issue is #4563.

A "fix" would be to implement the `put` operation also via the persistent remote shell. But for now this is mostly FOI.

**Comment by aqw** [comment]
Additional info: `MaxSessions 10` is `sshd`'s default. So the "problematic" behavior will be seen on most systems.
