### ISSUE TITLE
Download-url doesn't forwards bearer token authentication on redirects

### ISSUE THREAD

**Issue by joeyzhou98** [datalad/datalad#4805]
#### What is the problem?

I use [OSF](https://osf.io/) to store and retrieve datasets, clients will use their web interface to upload private datasets and my goal is to grab those datasets files into a local datalad dataset. I setup a new provider using the steps [here](https://github.com/datalad/datalad/issues/4376) and input my OSF token when prompted. Problem is that OSF redirects download links about 3 times: from their API to another internal API link to finally a Google drive link containing the private file and each redirect requires a `{"Authorization": "Bearer <token>"}` header in order to proceed except the last google drive link. It doesn't seem like `datalad download-url` adds that header after the first redirect, causing the authentication to fail even though the bearer token is perfectly good. So it would be great if the Bearer token authentication adds the token to subsequent redirect requests so cases like this won't cause problems

![image](https://user-images.githubusercontent.com/35869923/89483265-9d5ee000-d769-11ea-9fbd-6f9d4842b24f.png)

#### What steps will reproduce the problem?

- Setup a new provider by running `python -c 'from datalad.downloaders.providers import Providers; Providers().enter_new(url="https://api.osf.io/v2/")'
- Hit enter
- Enter regex `.*` to match all links
- Enter `bearer_token`
- Enter `token`
- Hit enter
- `datalad download-url https://osf.io/download/5e8524691ab24301dae037a9/`
- Enter `yes`
- Enter this throwaway token: `KysP9I5gIBKVWLLIMK8wZDc5xlkqawJ5wnzncKWOtORGi4jMhsyjGzYemMtd3dEbQsD7Xq`
- Enter this token again
- See that the command failed to authenticate

![image](https://user-images.githubusercontent.com/35869923/89482935-f11cf980-d768-11ea-9666-ae092bb28468.png)

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.12.6

**Comment by yarikoptic** [comment]
I would (or will, when wake up) check first how https://github.com/datalad/datalad-osf does it (directly or in osf client module it might be using)

**Comment by yarikoptic** [comment]
Also I don't remember if there were any related fix , but you might have better luck with more recent datalad release

**Comment by joeyzhou98** [comment]
Unfortunately the most recent release (0.13.1) also has the same error and datalad-osf currently does not support the behaviour wanted which is to create a local datalad dataset repo from an existing private osf dataset
