### ISSUE TITLE
publish should push also tags and branches

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#481]
realized today that while publishing we didn't push any tags or branches.
Not sure what default behavior should be but may be 'publish' command should allow to specify the list of `push` targets to set in the config for that remote in every dataset it works on?  or may be just to allow to pass `--all --tags` to push call BUT that would not persist for other calls

**Comment by yarikoptic** [comment]
probably should be done in 'prepare' stage.
Could be set per branch within .git/config, e.g. I have in pymvpa git:
```
[remote "gh-pymvpa-hyper"]
	url = https://github.com/PyMVPA/PyMVPA-hyper
	push = refs/tags/upstream/*
	push = refs/heads/master
	push = refs/heads/conhyp
```

**Comment by yarikoptic** [comment]
yeap... I think it should be done in prepare stage, BUT then publish code should either use native 'git push' command or load and pass those references to be pushed to GitPython's push. Currently just hard codes master and git-annex for annex repos

**Comment by yarikoptic** [comment]
For now I manually had to do to repositories on smaug to be published
```
git config --add remote.datalad-public.push 'refs/tags/*'; git config --add remote.datalad-public.push 'refs/heads/*'
```
so I would say that `create_pub...` should do that by default, and either allow to tune the list of those refs to be pushed, or just have an option such as `--do-not-add-push-refs` which would instruct to not do it.
It must be careful though in `--existing=reconfigure` mode to not change those settings if already defined... or may be would be safer to not change those at all in `reconfigure` mode -- I will just fix up manually those lacking them for now

**Comment by yarikoptic** [comment]
Anybody is working on this one @mih or @bpoldrack ?

**Comment by mih** [comment]
Looking into this now. I agree that this needs to be configurable. I agree that this needs to be done in a git-native way.

Looking at `publish` it seems a precondition for this is to stop calling 'push' with specific refspecs.

When we are doing that, we could consider offloading more duties to git annex by making more use of `sync`. this could take care of all kinds of conflicts, and data transfer in one go. We still would want to perform uni-directional updates, but `--no-pull` should do that. All that for annex repos only, of course.

After annex-sync is done (or for any other non-annex repo), we can run a simple `git push <remote>` to push the remaining configured 
items to send.

Any comments @bpoldrack

**Comment by bpoldrack** [comment]
Not ATM. I agree.

**Comment by mih** [comment]
#1275 is where we are in the discussion right now.
