### ISSUE TITLE
eval_func() leads to one `git-config` call per cmd call

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4813]
This is not a proper analysis, just recording a realization.

In order to figure out whether there are any result hooks, `eval_func()` consults a `ConfigManager` instance. That in itself would not be an issue. What is an issue is that this instance is create anew for each call to `eval_func()`. That means its `reload()` is called with `force=True` leading to an unconditional `git-config` call, regardless of whether the last one was milliseconds ago. There is no mtime checking, no caching.

Two directions to mitigate come to my mind:

1. ConfigManager singletons
2. Have two instances as dataset members. One  for the full config, and one for non-committed config only.

**Comment by yarikoptic** [comment]
Didn't look into the code so FWIW - how does it even load correct config if not through the dataset, which is a Singleton?

**Comment by mih** [comment]
A dataset's ConfigManager also loads the committed config. In `eval_func()` as standalone ConfigManager is created that only load the standard Git config. This avoid datasets being able to bring in remote execution configuration via a dataset update.

**Comment by mih** [comment]
Looked into this further, and I think it is doable and might even make things faster. A plan could be to RF the code to keep standard Git config sources and the committed datalad one strictly separate and not merge them on load. Instead they would be "merged" on query (by default), but all query methods would get a keyword arg to limit reporting to a particular source.

When this is done, we can also split the tracking of config file mtimes into git and datalad sources. At present we do a full reload whenever anything changes. After the RF we would only execute the git-config calls that are actually necessary (so in many case only do a single one, where we did two unconditionally before). This might change the assessment of how effective #4794 will be, but at least for an initial load it should be just as effective.

With these new capabilities it would be possible to completely avoid the construction of a dedicated ConfigManager for pure-local queries.

This is likely going to be changing more than a few lines, but it should speed up processing in the config manager in general, and also in `eval_func()`, hence I think it would be worth it.

Given the necessary changes, it would make sense to incorporate #4794 at the same time and in the same PR.
