### ISSUE TITLE
clone/install: introduce url mapping convenience?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4822]
#### What is the problem?

ATM for a user visiting some datalad-osf published dataset on osf.io it would require either user knowledge or every dataset having a description such as "this component can be git or datalad cloned from a 'osf://ID' URL, where 'ID' is the OSF node ID that shown in the OSF HTTP URL, e.g. https://osf.io/q8xnk/ can be cloned from osf://q8xnk", and then do all url tune up manually to get `datalad` `clone` or `install` working.

### Suggested solution:

I think datalad should make it easier and allow for a simple "copy paste URL I see in the browser bar", thus making `datalad clone https://osf.io/q8xnk/` work as well, while internally mapping it into `osf://q8xnk` for `git clone` operation.

Possible cons:
- if OSF changes their url schema -- would break our mapping.  But given historical stability and presence of those URLs in the wild already, it is very unlikely to happen

Possible implementation:
- datalad internally and also allowing extensions to register new "URL mappers"
- such "mappers" possibly should allow for different/absent context/purpose behavior
  - e.g. for OSF it would only matter for `clone`
  - in a somewhat related (waiting for merge) #4816, where within datalad itself we introduce "mapping" of `shub://` URLs into (minted by singularity hub with timeouts) http urls so that those images could be downloaded from the singularity hub; context would be `download`
- we already hardcode `///` to be a mapping to `http://datasets.datalad.org` -- implementation could generalize it
- some mappers could be as simple as regex based transformation (like in the case of OSF, `///`)

**Comment by mih** [comment]
I think anything that is specific to a particular system should stay in the code that interfaces that system. I would consider it suboptimal, if datalad-core start accumulating mappings for all kinds of 3rd-party services, given that there is an extension to deal with OSF. Whatever mechanism will be implemented, it should be extensible/updatable without having to modify datalad-core.

Another use case for this is the RIA URL decoding that is presently implemented in `clone`.

**Comment by yarikoptic** [comment]
Another usecase might be -- docker registries/hubs, see #5129

**Comment by mih** [comment]
I am toying around with the idea to implement this through a config setting (and possibly some entrypoint that extensions can provide, in addition). It seems as if this could be as simple as

```
[datalad "url"]
	substitute = (.*)github.com/([^/]*)$\n\\1gitlab.com/\\2
	substitute = mike\nsue
```

so a multiply defined setting that separates match and substitution by a newline char (which should be rare in  a URL).

Our config manager seems fine with this:

```py
>>> print(ds.config['datalad.url.substitute'])
('(.*)github.com/([^/]*)$\n\\1gitlab.com/\\2', 'mike\nsue')
```

Extensions could provide entrypoint with lists of 2-tuples directly.

**Comment by yarikoptic** [comment]
FWIW, we have (an elderly) https://github.com/yarikoptic/datalad/blob/HEAD/datalad/support/strings.py#L37 , used in the crawler for similar specifications in the crawler configuration, and inspired by `sed` syntax for substitutions specification in a string: 
first character defines the splitting character between "from" and "to", so would be smth like `/mike/sue` (or `,mike,sue` etc) in the above example.
