### ISSUE TITLE
Need test helper to take down pending git-annex processes

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4827]
We continue to have issues on windows with test cases that fail due to the `rmtree` call in the testbed take down code, because a git-annex process is still running. The latest installment is described here 
https://github.com/datalad/datalad/pull/4808#issuecomment-674381095 and an error log is  https://ci.appveyor.com/project/mih/datalad/builds/34672374/job/0og7edl8hw0nsbwl#L1073

In that particular case, our typical mitigation strategy (add `del repo` to the end of the test code) isn't working here -- presumably because multiple variables reference the same repo singleton. @bpoldrack had some spontaneous thought on the reasons elsewhere.

I think we would benefit from a test helper that reliably takes down all related processes.

**Comment by bpoldrack** [comment]
FTR: I'm on it. Goal is to build a test decorator, that would kill any flyweight (`Dataset`or `*Repo`) that was created during the test (and ideally any subprocess, `BatchedAnnex`, whatever attached to it).
While at it, I'm looking into using `weakref.finalize` instead of `__del__` for clean up.
