### ISSUE TITLE
Concurrent datalad get -n of submodules runs into locking issues

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4852]
```
CommandError: 'git submodule update --checkout --init -- sub-1313122' failed with exitcode 128 under /data/project/ukb_vbm/bidsclone
error: could not lock config file .git/config: File exists
fatal: Failed to register url for submodule path 'sub-1313122'
```

An analog approach to https://github.com/datalad/datalad/pull/4793 could help (i.e. bypass `git-submodule` completely).

**Comment by mih** [comment]
#4853 should deal with that. Running test on UKB dataset to confirm.

**Comment by yarikoptic** [comment]
I will just guess that #4853 resolved this one.  Please reopen if I am wrong.
