### ISSUE TITLE
Make a dedicated "create" command (instead of having it as a magic in "install")

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#487]
Have burnt myself multiple times already -- install creates a new repo instead of just failing if mistyping a path.

**Comment by hanke** [comment]
I'd prefer a --create flag for install, which would refuse to create an
empty repo, unless this is given.

**Comment by yarikoptic** [comment]
And then possible options to augment creation options, e.g. I foresee
- --register-with-superdataset -- to register  as a submodule
- --annex-id -- to provide custom identifier/description for annex init (see #27 )
- --git-description -- to provide git's .git/description
? 
How "datalad install --create" is better than explicit "datalad create"? 
I really see no advantage of blowing up 'install' for 'create' functionality anyways - does it help to solve any use-case?

**Comment by hanke** [comment]
OK, fine with separate.

**Comment by hanke** [comment]
Now presumably addressed by #499
