### ISSUE TITLE
Remove submodule functionality in GitRepo

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4873]
https://github.com/datalad/datalad/pull/4853#pullrequestreview-482873372 identified the duplication of some aspects of this functionality as a problem. In line with the ongoing slimming of the Repo API in order to improve maintainability, I propose to remove the (now) largely unused submodule-related functionality from `GitRepo`.

Specially:

- `deinit_submodule()`: replaceable by a config adjustment call at its only use in `remove()`
- `update_submodule()`: not used in -core outside tests of its functionality
- `add_submodule()`: only used in test helpers and test code. Replaceable for `Dataset.create()` calls

Given there is practically no usage, I propose to remove this code without a deprecation cycle. If you do not consider this acceptable, please give feedback on how a deprecation should look like (other than a changelog entry).

**Comment by yarikoptic** [comment]
Is it not used by any extension? Open neuro? Anything in Canadians code?
I don't see why there shouldn't be a deprecation cycle just in case

**Comment by mih** [comment]
All these were deprecated and will be removed some time in the future. No need for this dedicated tracking issue.
