### ISSUE TITLE
Failures on crippled FS

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4881]
I went through 11 of the CrippledFS workflow failures of the past days, trying to find a pattern. I failed to achieve that. I leave a list of failing tests as a starting point for subsequent research.

- 2x `datalad.core.distributed.tests.test_clone.test_expanduser`
- 1x `datalad.core.distributed.tests.test_clone.test_local_url_with_fetch`
- 1x `datalad.core.distributed.tests.test_push.test_push(True,)`
- 1x `datalad.core.distributed.tests.test_push.test_push_subds_no_recursion`
- 2x `datalad.core.local.tests.test_resulthooks.test_basics`
- 1x `datalad.distributed.tests.test_ria_git_remote.test_bare_git_version_2(None,)`
- 1x `datalad.distributed.tests.test_create_sibling_gitlab.test_fake_gitlab`
- 2x `datalad.local.tests.test_subdataset.test_get_subdatasets`

I also failed to replicate any of them with a fast (exfat, SSD) local crippled FS setup (10 attempts each), and had no luck with an ancient USB stick (fat32) either (speculating that FS speed could trigger a race condition).

No idea how to proceed. In any case, the constant unreliable failures that cannot be replicated reduce the value of these tests dramatically. Unfortunately, it is not a solution to just use appveyor, as it would promote `if on_windows` workaround that actually should be based on FS capabilities.

**Comment by bpoldrack** [comment]
I have yet another push-related one: `datalad.core.distributed.tests.test_push.test_ria_push` and don't believe it's related to the PR I saw it in (That would be #4899).

**Comment by mih** [comment]
Close due to age and spurious nature. Lots has change.
