### ISSUE TITLE
install --reckless ephemeral creates invalid link to remote annex if source is a bare repo

### ISSUE THREAD

**Issue by dickscheid** [datalad/datalad#4893]
- please see my latest post below, problem now clearly understood but it needs a fix -  

#### What is the problem?

I want to clone a repo with some Tiff images as an input-subdataset, from a RIA store that sits on the same filesystem. Since the tiff images are very large, I want to do a reckless-ephemeral install that points to the original data blobs in the RIA store. This works well.

Since my tiff library  doesn't like the hardlinks, I want to unlock files first. If I run "datalad unlock file.tif" however, I receive an error:

```
CommandError: 'git-annex find -c annex.dotfiles=true -c annex.retry=3 --json --json-error-messages --copies 0 -- <my filename>.tif' failed with exitcode 1 under <my directory>
git-annex: .git/annex: createDirectory: already exists (File exists)
```

If I do the exact same procedure on the same system, but install the same subdataset from a non-RIA store, it works. 

If I do not use --reckless ephemeral, the "datalad get" + "datalad unlock" is much slower than the ephemeral variant.

#### What steps will reproduce the problem?

1. Create a repository A with some files.
2. Create a RIA sibling of A, A-RIA on the same filesystem.
3. Install a clone of A-RIA as a subdataset in a new repository on the same filesysetm, using --reckless ephemeral.
4. Try to `dataset unlock` a file - the error occurs.
5. Repeat 3, but use A as the origina (not A-RIA).
6. Try to `dataset unlock` a file - works.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

0.13.3

**Comment by dickscheid** [comment]
Update on this issue: The problem with my tiff library were not hardlinks, but rather the way that `--reckless ephemeral` symlinks the annex. I will dig deeper into the problem, but the different behavior for unlocking described above ist still an open question to me.

**Comment by dickscheid** [comment]
I think I figured the problem myself: 

The `datalad install --reckless ephemeral` models the new clone's `.git/annex` as a symlink to the origin's / remote's annex. When I clone from a RIA store, thsi remote is a bare repo. The install command however creates a symlink to the remote's `.git/annex`, which does not exist.

Suggested solution is that `datalad install --reckless ephemeral` should detect wether the source repo is a bare repo, and in that case craete the symbolic link to `annex/` instead `.git/annex`.

**Comment by mih** [comment]
Holy cow! I need to replicate that and if your assessment holds, this is something we can never talk about, ever again ... 🤦

**Comment by bpoldrack** [comment]
I'm afraid I don't need a replication to believe we forgot that. Luckily the fix isn't hard.

**Comment by bpoldrack** [comment]
Oh, and I'll take the blame ;-)

**Comment by bpoldrack** [comment]
I think I have fix. Am writing a proper test for it.

**Comment by dickscheid** [comment]
Forgiven regarding all the fun I have with datalad :-)

**Comment by bpoldrack** [comment]
@dickscheid : The fix is merged into the `maint` branch in case you want to try instantly. Otherwise will be included in next minor release.
