### ISSUE TITLE
Redefine prototype.

### ISSUE THREAD

**Issue by sje30** [datalad/datalad#49]
Not really an issue, just a comment on your top-level readme:

    It is currently in a "prototype" state, i.e. a mess.

that's classic!

**Comment by hanke** [comment]
;-)

**Comment by yarikoptic** [comment]
I guess now we are doomed now to keep this issue open until we could remove this statement ;-)

**Comment by yarikoptic** [comment]
damn -- just now mentioned -- why "wontfix" @hanke?  I hope we will get from that state eventually ;)
