### ISSUE TITLE
Extension-provided configuration?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4905]
Thinking about #4903, we would benefit from a way in which extensions can provide (default) configuration.

I can think of:

- config.d directory-type mechanism -- might be a pain to maintain
- ConfigManager inspecting extension entrypoints and adding a file each to the list of files to monitor -- could be source of slow-down

Key point here is that an extension can inform -core that something is supposed to happen, and that we have the ability to alter the way an entire installation works (rather than just a user). I believe that we should not consider starting to mess with `/etc/gitconfig`.

**Comment by yarikoptic** [comment]
I am a bit lost -- why extension doesn't just place its configuration in a section of "stock" config file (well, as we do already for datalad-container etc)?
