### ISSUE TITLE
addurls: add ability to just pass a list of records

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4906]
ATM `addurls` API is oriented toward command line invocation where records would be either passed via external file or piped through `stdin`.  When using `addurls` within Python scripts (and later within crawler) it would be easier to just provide a list with records, thus avoiding necessary in addurls to load/parse external file.

I guess it could be done by renaming first positional argument from `urlfile` to `records` or alike, and allowing the argument to be not just a string (for filename) but also another iterable (e.g. a list, tuple, generator) in which case it would just iterate over that structure.

**Comment by kyleam** [comment]
Works underway for this.  It's based off of gh-5184 (to avoid conflicts), so I'll probably wait until that lands.
