### ISSUE TITLE
rudimentary tests for interface/{push,pull}.py

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#492]
if we are to keep them at all.  push is kinda useful, but someone could argue that some kind of a `publish` could do it.  But if we are to keep them, we need to test them

**Comment by bpoldrack** [comment]
Kind of agree. But I'd not keep them at all. That's what we have publish and update for. If you want a pure git push/pull, you should call it directly, I think.

**Comment by hanke** [comment]
+1 for removal
