### ISSUE TITLE
FOI: Travis migration by end of 2020

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#4922]
Tonight I received an email that travis-ci.org shuts down at the end of the year and that all users should migrate to travis-ci.com.

> Hi there!  As  you’ll no doubt have noticed, Travis CI has, for some time, been split  between travis-ci.com and travis-ci.org. This was initially planned to  enable open-source and commercial/private projects to be distinctly  separate, but back  in May 2018, we announced that open source builders would have the  opportunity to build and test their projects under travis-ci.com,  meaning your public and private repositories could be managed under one  domain with a consistent interface and build environment.   In an effort to ensure that all of our users - whether you build  open-source, public or private repositories - receive regular feature  updates, security patches and UX/UI enhancements, we are announcing that  travis-ci.org will be officially closed down completely on December  31st, 2020, allowing us to focus all our efforts on bringing new  features and fixes to travis-ci.com and all of our awesome users like  yourself on the travis-ci.com domain.     
> What this means for you  
> The  main thing to expect is that your projects will be built and tested  with the same speed and robustness as you’ve come to expect from Travis  CI - but also with great new features such as support for AWS Graviton2  which is only available on travis-ci.com. Open-source projects will be  free as they always have, with lighting fast builds provided by partners  like Packet.   We encourage you to migrate your existing repositories that are  currently on travis-ci.org over to travis-ci.com as soon as possible,  enabling you to identify any additional changes required to your code or  configuration well in advance of the December 31st deadline. We’ve documented everything you need to know in order to migrate your repositories, and of course, you can reach out on the community forum for any additional help.   If you have any questions or concerns, please feel free to contact our support team who will be happy to talk through any migration queries you may have!    
> Happy building on travis-ci.com!

I migrated my repositories and the datalad-handbook's repository over to test it.

Information on how to migrate is [here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration). In order to migrate private repositories, I needed to sign up for their "beta" with my account, grant access to the travis-ci.com GitHub app, and migrate the repository via button click in the web interface. I had to repeat this for the datalad-handbook organization.
After migration, testing happens via travis-ci.com, but I still have read access to previous test logs. So overall, it worked fine for me, with no unexpected problems.

**Comment by mih** [comment]
I will close this. It became the disaster we were afraid of ;-)
