### ISSUE TITLE
addurls: ignores on_failure="stop" setting due to use of  `with_result_progress`

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4929]
My usecase: I have following invocation 
```python
        out = ds.addurls(
            submission_file, '{associated_file}', '{path}',
            exclude_autometa='*',
            fast=fast,
            save=False,
            ifexists="overwrite",
            cfg_proc='nda',
            on_failure="stop",
            # result_renderer='default'
        )
```
which I run on thousands of files.  I do want it to stop as soon as an error encountered since it would make no sense to proceed forward (I want to get from clean state to clean state to save) but after a few minutes I get a first failed reported in progress bar (not sure which one) and it still has hours to go.  The only way is to interrupt but I would not even know what has failed.

The reason is: `@with_result_progress` is "accumulating" all returned or yielded values into the list first and then returns it.  That is what completely prevents correct treatment of `on_failure` in `_process_results`.

I think ideally `@with_result_progress` should keep generator functions to be generator functions **but**, depending on the use case immediate yields could cause `_process_result` rendering of the results thus possibly interfering with the progress bars of `@with_result_progress`.  And `on_failure` is not passed into underlying functions (like `addurls` itself) so they cannot decide one way or another (fail or continue if error).  So I do not see an easy solution here yet.

apparently `@with_result_progress` is used only in addurls ATM within datalad-core:

```shell
$> git grep with_result_progress
datalad/log.py:def with_result_progress(fn, label="Total", unit=" Files"):
datalad/plugin/addurls.py:from datalad.log import log_progress, with_result_progress
datalad/plugin/addurls.py:@with_result_progress("Adding URLs")
datalad/plugin/addurls.py:@with_result_progress("Adding metadata")
```

**Comment by kyleam** [comment]
Thanks for the analysis.  I definitely overlooked this issue when writing `with_result_progress`.
