### ISSUE TITLE
URL handling

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#493]
Since we had several issues and discussions about how to deal with different kind of URLs and how to detect them and how `urlparse` isn't sufficient for our needs, we need to centralize the URL handling.

Connected (but not restricted) to #440 , #441 , #442

**Comment by hanke** [comment]
Could you remind me how urlparse is failing?

**Comment by bpoldrack** [comment]
Not exactly failing, but not sufficient for our needs. For example, as Yarik mentioned in PR #435, we want to accept `[user@]host:path` as an SSH URL. `urlparse` will not only detect no scheme but also fail to correctly assign the other parts. All of it will go into `path`.

**Comment by bpoldrack** [comment]
A centralization of URL handling will also provide a place, where to add some "detection magic".

**Comment by bpoldrack** [comment]
And: Even `ssh://user@host:path` will not work with `urlparse` only, since it does not deal with the colon.

**Comment by hanke** [comment]
If we want to support that, please let's not call that a URL! This will only create confusion. SSH doesn't call it a URL either.

**Comment by bpoldrack** [comment]
Yes, actually it's not an URL and I'm fine with calling it "address" or sth.
But: Git kind of calls it "URL". You can add a remote that way and therefore will find this kind of things in .git/config as "url" for that remote.

**Comment by yarikoptic** [comment]
note: related is `is_url` function we have already

**Comment by yarikoptic** [comment]
hm... and probably there is no easy reliable way to say either 'xxx:yyy' stands for 

- url `xxx` schema and `yyy` path (`ParseResult(scheme='xxx', netloc='', path='yyy', params='', query='', fragment=''))
- or host `xxx` and path `yyy`

:-/  so are we doomed to use `ssh://` prefix or otherwise grow some magical assumptions about legit schemes etc?  

as for `ssh://user@host:PATH` we indeed would need to add a posthandling of netloc to extract `PATH` and prefix the extracted `path` with it

**Comment by bpoldrack** [comment]
Well, atm I think we should have a "magic layer", that detects things, we want to accept, and translates it into something, that either urlparse can deal with, or that is a ParseResult itself. Any other code else then just gets the ParseResult instead of the original string (could be done via `constraint` for example)

**Comment by bpoldrack** [comment]
`user@host:path` would then lead to

**Comment by yarikoptic** [comment]
I hope to work on #441 atm, so may be I will take a chance to provide some ultimate magical handling

**Comment by hanke** [comment]
Looks like we can close this as the merge has happended.
