### ISSUE TITLE
Problematic AnnexRepo.get() usage in get_cached_dataset()

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4938]
My context is #4595 and #4887 

Only very recently introduced by @bpoldrack in https://github.com/datalad/datalad/commit/0399eda71c841570dc8c68a76fa0b5dfddd74b10 `get_cached_dataset()` passes one or more keys to `AnnexRepo.get()` if so desired.

If this works (haven't tested it), this is magic made possible by `normalize_paths()` and I would prefer that we do not introduce new usage of this kind.

It could also just be a bug, given https://github.com/datalad/datalad/blob/454baaac1392dd7b6a4b6fe2711d08d11a94ab8a/datalad/support/annexrepo.py#L1200 

In any case a change needs to be made.

I would prefer to replace the current `get()` with a method that works without `normalize_paths` (ie. a generate-style `get_()`), and either accepts any number of keys (not just one), or have a dedicated sibling method `get_keys_()` that does.

**Comment by mih** [comment]
It would be good to get your response to this @bpoldrack

**Comment by bpoldrack** [comment]
@mih 
Not a bug, given the docstring

https://github.com/datalad/datalad/blob/454baaac1392dd7b6a4b6fe2711d08d11a94ab8a/datalad/support/annexrepo.py#L1171

However, I'm fine with a change in interface, as long as we can `get` keys. IIRC the only thing that a change would break is datalad-hirni.

**Comment by mih** [comment]
I am closing this old issue of mine. There is clearly no interest in this. This is a tests-only, special feature that is not used elsewhere.
