### ISSUE TITLE
Keep track of GitPython

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#494]
Just a reminder to keep track of https://github.com/gitpython-developers/GitPython/issues/462 and https://github.com/gitpython-developers/GitPython/issues/461

**Comment by yarikoptic** [comment]
both issues were addressed in GitPython upstream, I believe part of 2.0.6 release (thanks Vincent Driessen for a quick release), so I guess it would be ok to close this particular issue.  i will update debian packages etc some time later
