### ISSUE TITLE
Add github workflow to test on OSX

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4942]
In the light of #4941 I think it would be very useful to get at least some (`datalad.support` and `datalad.core` at least or all which are not `slow` or `turtle`?) unittests being tested on OSX on github actions.  Then PRs addressing failures listed in #4941 could expand coverage to cover what is fixed up.

For now git-annex could be installed from the officially distributed .dmg, but eventually I hope that we could provide some builds straight from https://github.com/datalad/datalad-extensions/ .

**Comment by jwodder** [comment]
@yarikoptic What permissions do I have on this repository as a collaborator?  When I try to push my branch for this issue, I get permission denied.  Do I still need to submit my PR via a fork?

**Comment by yarikoptic** [comment]
yes, for this repo we all submit PRs from "personal" forks. Thank you in advance!

**Comment by yarikoptic** [comment]
we have it now
