### ISSUE TITLE
Separate extractor results from internal structures

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad#4962]
Datalad uses an internal structure, i.e. a dictionary to pass information about metadata, for example in the _meta2doc and _mk_schema-methods of Search-classes. This dictionary contains a number of administrative keys, which are used by the datalad core code, i.e. code in datalad.metadata. These keys are:

- path
- type
- datalad_unique_content_properties
- parentds

In addition this dictionary will contains keys with the name of installed metadata extractors. The way to discriminate between them is to either:
- Know all names that are administrative (needs to be updated, when the set of administrative names changes)
- Identify all keys with a dictionary value as metadata format names, unless the key is `datalad_unique_content_properties` (needs to be updated when this configuration changes)

It is easy to see, that this logic is brittle. The code has to be updated when the names change, the metadata extractors names should not be the same as the keys of the administrative entries.

To mitigate this problem and reduce the number of possible errors, we should create an administrative entry in said structure that contains all extracted metadata, for example, an entry with the name "extracted_metadata", which contains a dictionary where the keys are the extractor names and the values are the extracted metadata.

(And with python >= 3.7, we might use dataclasses instead of dictionaries for said structure)

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
