### ISSUE TITLE
install-annex.sh: Add OSX installation for "autobuild", "snapshot", and "datalad-extensions-build" options

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4971]
ATM https://github.com/datalad/datalad/blob/master/tools/ci/install-annex.sh is Linux specific, but now that we even have datalad-extensions built .dbg it could also support OSX.  I think it would be nice if it would internally (no dedicated new option) download appropriate file (.dmg for OSX) and install it accordingly.

Ideally `--help` could either be limited only to the options supported on current OS (but then a bit painful since some are Debian specific), or at least annotate, e.g.

```
    "autobuild  # Linux, OS X"
    "conda-forge [version]  # Linux"
    "conda-forge-last [version]  # Linux"
    "datalad-extensions-build  # Debian-based Linux, OS X"
    "deb-url URL  # Debian-based Linux"
    "neurodebian  # NeuroDebian-based Linux"
    "neurodebian-devel # NeuroDebian-based Linux"" 
    "snapshot   # Linux, OS X"
```

NB "snapshot" is somewhat a bad name.  It corresponds to "current" (release?) for both Linux and OSX

**Comment by jwodder** [comment]
Where should the .dmg file be downloaded from for "autobuild" and "snapshot"?  Should it be downloaded from <https://downloads.kitenet.net/git-annex/OSX/current/$MACOS_VERSION/git-annex.dmg>?  If so, this suggests that "autobuild" can't be supported, as there's only a "current" directory under `/git-annex/OSX`.  Also, assuming this script is primarily meant to be run on GitHub Actions, a directory for a macOS 10.15 build of git-annex will need to be added.  (It would also be helpful if paths like `/git-annex/OSX/current/10.10` existed and redirected to `/git-annex/OSX/current/10.10_Yosemite`, as there's no clean way to get the macOS codename that doesn't require an update for every new version.)

**Comment by yarikoptic** [comment]
From https://git-annex.branchable.com/install/OSX/ I see

- autobuild: https://downloads.kitenet.net/git-annex/autobuild/x86_64-apple-yosemite/git-annex.dmg and description says "10.11 El Capitan / 10.10 Yosemite / 10.9 Mavericks". I do see separate directories per MACOS_VERSION but they all seems to lead to the same .dmg binary (compared 10.11 and 10.9) so most likely symlinks
- snapshot/current: https://downloads.kitenet.net/git-annex/OSX/current/10.10_Yosemite/git-annex.dmg

so I guess the same build should work on any recent OSX.  So for now I would not worry about MACOS_VERSION at all, and just download from those URLs regardless of OSX version. Whenever we see that it doesn't work and/or new build or "per-MACOS_VERSION" builds start to appear -- we will ask @joeyh to harmonize paths to reach binaries a bit and tune the script.

**Comment by yarikoptic** [comment]
done by https://github.com/datalad/datalad/pull/4974
