### ISSUE TITLE
download_url --archive slow

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4975]
[sorry no proper triage yet]

I am testing https://github.com/datalad-handbook/book/pull/581, specifically running

```
datalad -c datalad.runtime.use-patool=1 download-url --archive --message "Download Imagenette dataset" 'https://s3.amazonaws.com/fast-ai-imageclas/imagenette2-160.tgz'
```

It took me 1min to download the archive, but an additional 2.5min for the `addurl` processes to finish. This seems long.

The results look fine though:

```
% datalad status --annex
13394 annex'd files (101.6 MB recorded total size)
nothing to save, working tree clean
```

**Comment by yarikoptic** [comment]
`13394` files -- so I would say it might be "expected" (not that we shouldn't improve -- async and all) to take time to annex this number.  A useful comparison could be to a pure `git annex add && git commit` tandem on already downloaded archive.

**Comment by mih** [comment]
```
( git annex add -q && git commit -m some; )  63.38s user 22.75s system 103% cpu 1:22.84 total
```

so it seems to double the time, roughly.

**Comment by yarikoptic** [comment]
In my experience 2x overhead from datalad on top of pure git/annex commands while working with large number of small files is actually quite "ok".  Again, we could and should strive to reduce it, or even make default operation of datalad faster (through default -J and async interaction with annex) than plain git/annex invocations.  But I do not see his particular issue needing a dedicated attention - although I could be proven wrong, but most likely overhead comes from additional calls to git to get `status` etc,

**Comment by mih** [comment]
Closing this issue of mine. The conclusion here is "good enough"
