### ISSUE TITLE
have an easy way to set/change default backend for annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4978]
6f8c54f4b9eb4f7ea533d67869da64517f790e81 (0.12.0rc3) retired old `create` which had a dedicated option to set backend.
ATM there is no easy way to set backend to another one... jitsi discussion pointed to (not part of common_opts) annex.backends which we could use to pass it via `-c`.

**Comment by yarikoptic** [comment]
my most concise recipe ATM to create a dataset with alternative backend (ignore setup code)
```python
import datalad.api as dl

ds = dl.Dataset('/tmp/dssss')
if not ds.is_installed():
   ds.create()

attr = ds.pathobj / ".gitattributes"
attr.write_text(attr.read_text().replace("MD5E", "SHA256E"))
```

**Comment by kyleam** [comment]
How about `datalad -c datalad.repo.backend=SHA256E create`?

**Comment by kyleam** [comment]
Related discussion starting at https://github.com/datalad/datalad/pull/3383#issuecomment-489287916

**Comment by yarikoptic** [comment]
> How about `datalad -c datalad.repo.backend=SHA256E create`?

ah, right, thanks! so in Python would be smth like
```
import datalad
import datalad.api as dl
datalad.cfg.set('datalad.repo.backend', 'SHA256E', where='override')
ds = dl.Dataset('/tmp/dssss').create()
```

**Comment by mih** [comment]
A few approaches have been pointed out. I will close this issue.
