### ISSUE TITLE
Broken location reporting for ORA remote

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4979]
```
git annex whereis archives/BnB1__Raw_Data__ADNI.7z
whereis archives/BnB1__Raw_Data__ADNI.7z (2 copies) 
        47710ef6-eef8-4617-ae01-291794c10a71 -- mih@brainbfast:/data/BnB2/monster
        fd775661-3a2e-4382-a0fc-b54ab9d50177 -- [inm7-storage]

  inm7-storage: http://archive.ds.inm7.de/annex/objectspV/14//MD5E-s315728551051--3a1a3e5e7fe6f6125122fe3b23922869.7z/MD5E-s315728551051--3a1a3e5e7fe6f6125122fe3b23922869.7z
```

This path in the last line is broken. Double-slash (not critical), but missing slash after `objects`.

The correct URL would be `http://archive.ds.inm7.de/736/bcb04-7dea-4346-9bb8-a12cd2749b3f/annex/objects/pV/14/MD5E-s315728551051--3a1a3e5e7fe6f6125122fe3b23922869.7z/MD5E-s315728551051--3a1a3e5e7fe6f6125122fe3b23922869.7z`

Ping @bpoldrack

**Comment by adswa** [comment]
I tried to check if this is still true. I tried in ``/data/group/psyinf/processing-workflow-tutorial`` (@bpoldrack you have access to it), but it reports it as a relative path now it seems?

```
(magma) adina@cpu12 in /data/group/psyinf/processing-workflow-tutorial on git:master
❱ git annex whereis fmriprep/sub-01/anat/sub-01_desc-brain_mask.nii.gz 
whereis fmriprep/sub-01/anat/sub-01_desc-brain_mask.nii.gz (3 copies) 
  	c034a599-5db4-4212-8c2f-5d1bfaa0af5c -- adina@juseless:/data/group/psyinf/processing-workflow-tutorial [here]
   	c564c916-629f-4bb8-8113-01a3b04d7a51 -- gin [gnode]
   	d8807e1f-25ef-4267-a5b9-698eae068b4c -- [output-storage]

  output-storage: Pv/77/MD5E-s422015--f1db473b0ef4bde6cd9bd1b6db9069ff.nii.gz/MD5E-s422015--f1db473b0ef4bde6cd9bd1b6db9069ff.nii.gz
```

I guess that approach solves the issues @mih raised above :P But I also think it makes it impossible to find out where the file actually is.

**Comment by adswa** [comment]
I don't have a good understanding of ORA remotes, and my debugging is more or less blind. If @bpoldrack has tips I would be happy to hear them. I guess that the code in question is 

https://github.com/datalad/datalad/blob/66bea22482a900a9ea8676e50558fec4fddea24f/datalad/distributed/ora_remote.py#L1305-L1320

The ``key_path`` is being returned ("``Pv/77/MD5E-s422015--f1db473b0ef4bde6cd9bd1b6db9069ff.nii.gz/MD5E-s422015--f1db473b0ef4bde6cd9bd1b6db9069ff.nii.gz``"), but the ``remote_git_dir`` somehow isn't, even though I think it carries at least a part of the correct value ("``/data/group/psyinf/outputstore/47a/9ef9e-9fa0-49cd-873f-c51cc501da96``")

**Comment by bpoldrack** [comment]
@adswa : Yes, that's right. Correct place.

However, it looks like that ORA remote actually is local, so the output is actually "correct": `return str(key_path)` is what we see ;-)
Meaning: the `if self._local_io()` part needs to be prefixed with `dsobj_dir`, I think

**Comment by adswa** [comment]
Ahh cool, thanks :) I'll try a PR. But then this actually isn't related to the original issue here (damnit)

**Comment by adswa** [comment]
oh, that's easier than I thought! Thanks. :) I'll add a commit to that PR!
