### ISSUE TITLE
Approach to streamline credential handling

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4981]
Credential handling is a bit of dark magic in DataLad, although the foundations are very flexible and should be capable of dealing with any scenario that I can come up with. Previous plans to replace it have not led to any results (e.g. #1783). However, there are long-standing limitations like the lack of a modification API (#396), and priorities (#322).

The biggest issue right now (from my POV) is the specification of credentials in non-interactive environments without a credential store being easily available (HPC/HTC). The only practical approach is to supply them via ENV variables. How these must be named is undocumented and knowledge that is only discoverable by the initiated.

The last attempt to do something in that direction was #4135 (stalled).

I propose to adjust credential handling to:

- use `ConfigManager` instead of direct environment variable inspection (this will open up many standard ways to supply credentials that are all better documented then the present one) -- such a PR should replace #4135
- document a predictable credential (variable) naming scheme
- keep using python-keyring whenever the environment doesn't have what is needed
- address #396 by implementing a datalad command that can at least list, and delete credentials

**Comment by yarikoptic** [comment]
I agree, we need to overhaul. Just a quick note for now: I use https://github.com/datalad/datalad/wiki/FAQ#how-to-configure-insecure-local-credentials-store on hpc etc

**Comment by mih** [comment]
> * address #396 by implementing a datalad command that can at least list, and delete credentials

So this turns out to be a major issue. `keyring` has no support for listing known secrets. We would need to interface with individual backends for that. Simple for `SecretService`, more or less a reimplementation for `PlaintextKeyring` (to name just two).

Without being able to list secrets it is near-impossible to delete secrets (#3126), because their naming is completely hidden from users. In order to filter relevant secrets from `SecretStorage` I have to know that good candidates are ones with this property

`'application': 'Python keyring library'`

and have a `service` property, and it starts with `datalad-`. On my system that yields:

```
 'datalad-https://nmrxnat....de:443/xnat',
 'datalad-datalad-test-s3',
 'datalad-https://nmrxnat....de:443/xnats',
 'datalad-hcp-s3',
 'datalad-github',
 'datalad-crcns',
 'datalad-https://nmrxnat.....de:443/xnat',
 'datalad-nmrxnat.ime....de:443/xnat',
 'datalad-gitadshub',
 'datalad-hcp-s3',
 'datalad-nmrxnat.....de:443/xnat',
 'datalad-github',
 'datalad-datalad-test-s3',
 'datalad-https://nmrxnat.....de:443/xnats',
 'datalad-gitadshub',
```

I have no evidence that this is indeed an exhaustive list.

**Comment by mih** [comment]
Exploring further. Git has built-in handling of credentials. It ships a credential store on windows. It supports a flexible architecture to plug in other systems (I use it with `pass` for example). It considers config variables already. Worth considering to switch to a system that appears to be equally flexible, but already comes with the one key dependency of datalad.

**Comment by yarikoptic** [comment]
Sounds good!  Re "listing known secrets" -- I guess it could be done by going through known/loaded providers: each one would know which credential it needs, and we could query keyring about it (either known or not).  So even though we would not know ALL possibly stored "datalad" credentials, we would know the "relevant" ones

**Comment by mih** [comment]
But there is no uniform API across backends...

**Comment by yarikoptic** [comment]
do not talk to "credential storage backend" at all (which would be nice to interface properly too at datalad level), talk to providers:

```python
from datalad.downloaders.providers import Providers
providers = Providers.from_config_files()
for provider in providers:
    cred = provider.credential
    if cred:
        print(f"{provider.name}: {cred.name} of type {type(cred).__name__}  known: {cred.is_known}")
```
results in
```
crawdad: crawdad of type UserPassword  known: True
crcns: crcns of type UserPassword  known: True
crcns-nersc: crcns of type UserPassword  known: True
figshare: figshare of type Token  known: True
hcp-web: hcp-db of type UserPassword  known: True
hcp-http: hcp-db of type UserPassword  known: True
hcp-xnat: hcp-db of type UserPassword  known: True
hcp-s3: hcp-s3 of type AWS_S3  known: True
balsa: hcp-db of type UserPassword  known: True
indi-s3: datalad-test-s3 of type AWS_S3  known: True
kaggle: kaggle of type UserPassword  known: True
loris-demo: loris-demo of type LORIS_Token  known: False
NDA: NDA of type NDA_S3  known: True
miNDAR: miNDAR of type UserPassword  known: False
nitrc-frs: nitrc of type UserPassword  known: True
nitrc-ir: nitrc of type UserPassword  known: True
openfmri-s3: datalad-test-s3 of type AWS_S3  known: True
datalad-test-s3: datalad-test-s3 of type AWS_S3  known: True
www.onerussian.com: www.onerussian.com of type UserPassword  known: True
jigsaw.w3.org: jigsaw.w3.org of type UserPassword  known: True
w3-digest: w3-digest of type UserPassword  known: True
jigsaw-digest: jigsaw-digest of type UserPassword  known: True
my.domain.com: my.domain.com of type Token  known: False
yarik: yarik of type Token  known: True
```
for me while in "nowhere".  If I am in some dataset which has a dedicated provider -- it would get a new entry listed
```shell
/home/yoh/proj/datalad/trash > datalad install https://github.com/conpdatasets/preventad-open ; cd preventad-open; python .././show_creds.py | grep -i prevent
[INFO   ] Scanning for unlocked files (this may take some time)                                                  
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore                                            
install(ok): /home/yoh/proj/datalad/trash/preventad-open (dataset)
datalad install https://github.com/conpdatasets/preventad-open  9.08s user 2.01s system 75% cpu 14.760 total
loris-prevent-ad: loris-prevent-ad of type LORIS_Token  known: True
```
```

**Comment by adswa** [comment]
> @adswa this would not look pretty in the handbook, but ATM I see no other way to improve the status quo than to describe the complexity of the situation. What do you think?

Sorry, I must have missed this. In the meantime, Michael Joseph has started: https://github.com/datalad-handbook/book/pull/622. I can compliment this with a section on the current complex status of credential handling for now. But I'm hoping that the Git credential helper can be useful - only for the HCP data alone I discovered a good handful of different ways to fix up or query credentials on different operating systems.

**Comment by mih** [comment]
I am closing this in favor of https://github.com/datalad/datalad/issues/396, because it is the only remaining open issue from the original list.
