### ISSUE TITLE
datalad get failing after datalad drop

### ISSUE THREAD

**Issue by HendrikBoehmer** [datalad/datalad#4986]
#### What is the problem?
I currently try to follow the Handbook article which is comparing DataLad to DVC
https://handbook.datalad.org/en/latest/beyond_basics/101-168-dvc.html

#### What steps will reproduce the problem?
Everything works fine until this paragraph
https://handbook.datalad.org/en/latest/beyond_basics/101-168-dvc.html#id10

After dropping the data with ``datalad drop`` I cannot get the data back again with ``datalad get``:
$ datalad get data/raw/val
Total (0 ok, 13 failed out of 3925):   0%|                 | 0.00/31.2M [00:39<?, ?B/s]

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

Datalad 0.13.3 on Windows Subsystem Linux 2 (Ubuntu 20.04)

## datalad
  - full_version: 0.13.3
  - version: 0.13.3
## dataset
  - id: db2027f4-4771-4698-a790-116a49255975
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /home/hendrik/Code/dvc_datalad_comparison/datalad
  - repo: AnnexRepo
## dependencies
  - annexremote: 1.4.3
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20200226
  - cmd:bundled-git: 2.25.1
  - cmd:git: 2.25.1
  - cmd:system-git: 2.25.1
  - cmd:system-ssh: 8.2p1
  - git: 3.1.9
  - gitdb: 4.0.5
  - humanize: 2.6.0
  - iso8601: 0.1.12
  - keyring: 21.3.1
  - keyrings.alt: 3.4.0
  - msgpack: 1.0.0
  - requests: 2.24.0
  - tqdm: 4.48.2
  - wrapt: 1.12.1
## environment
  - LANG: C.UTF-8
  - PATH: /home/hendrik/python_envs/general/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
  #### EDITED ####

## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions:
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.1.0
    - ghc-8.6.5
    - http-client-0.5.14
    - persistent-sqlite-2.9.3
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - local repository version: 8
  - operating system: linux x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions:
    - 8
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200226
## location
  - path: /home/hendrik/Code/dvc_datalad_comparison/datalad
  - type: dataset
## metadata_extractors
  - annex:
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio:
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite:
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif:
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage:
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image:
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp:
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python
  - implementation: CPython
  - version: 3.8.2
## system
  - distribution: ubuntu/20.04/focal
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 305
  - name: Linux
  - release: 4.19.128-microsoft-standard
  - type: posix
  - version: #1 SMP Tue Jun 23 12:58:10 UTC 2020

**Comment by adswa** [comment]
Thanks for reporting - I will try to trigger this on a Windows machine with WSL2 hopefully later today, I can't see an immediate reason why this would fail, but I also don't have much experience with how WSL2 behaves. It may be the special remote...

**Comment by adswa** [comment]
Sorry, my bad. The most recent release of DataLad (0.13.3) doesn't handle ``.tgz`` archives yet.

I didn't realize that I was demoing a workflow that relies on a bug fix that isn't yet released.
We stumbled across it while we were creating the demo you are working through. The missing fix was introduced in https://github.com/datalad/datalad/pull/4877 (support for ``.tgz`` archives), and that will only be a part of 0.13.4 (:facepalm:) . I will add a note to this example in the handbook.

If you rely on this feature, you could install datalad with an editable install by cloning this repository, and within its root, run ``pip install -e .`` - this will get you the fix.
The work around for the time being to use the datalad-archives special remote is a bit lengthy:

```
# download the archive, unzip it
curl -s https://s3.amazonaws.com/fast-ai-imageclas/imagenette2-160.tgz -O imagenette2-160.tgz ; gunzip imagenette2-160.tgz 
# save it
datalad save imagenette2-160.tar
# call add-archive-content --delete by hand - this would have been done by the --archive flag
datalad add-archive-content --delete imagenette2-160.tar
```
Then you should be able to drop and re-obtain the files.

**Comment by HendrikBoehmer** [comment]
Alright, thanks for your help.

**Comment by adswa** [comment]
FTR: 0.13.4 was released yesterday evening
