### ISSUE TITLE
Windows support conceptual problems

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4987]
I was told that @mih might be compiling the ultimate list, here is some collection of large conceptual issues we observed:

- indirect mode: absent support by git-annex on Windows
  - symlinks are claimed to be supported across all recent windows releases, see [e.g. ](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) for workthrough
    - always needs admin? @bpoldrack suggests that some devel release has support for 
  - there might be need for alternative locking (pidlock?), and permissions restrictions (making read-only)
- adjusted branches: difficulty of working with in general, in particular with submodules, not really tested thoroughly in DataLad
- short-vs-long paths returned, in particular while working with `os.path` not `libpath`
  - we have `.support.path` which shims already some `os.path` -- we should just use it instead of `os.path` and shim where needed for windows ("slow is better than not working" -- @mih)
- ssh stalling issues

**Comment by mih** [comment]
https://github.com/datalad/datalad/issues?q=is%3Aissue+is%3Aopen+label%3Awindows is also always worth a look

**Comment by mih** [comment]
FTR: Proper adjusted branch support is required even when using datalad within WSL2, in order to access any annexed files from regular windows apps.

**Comment by mih** [comment]
Of all these issues only subdataset handling with adjusted branches remains a problem, but that is not windows specific.
