### ISSUE TITLE
addurls: information + progress indication when creating subdatasets

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4989]
Now in my case where there is a `cfg_` procedure is also running to initiate a good number of subdatasets my screen just fills up with 
```
...
(recording state in git...)
initremote datalad ok
(recording state in git...)
initremote datalad ok
...
```
without any indication on what is going on, which subdataset is created, and how long it is left to tolerate this ;)

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
