### ISSUE TITLE
copy-file: add a mode to provide a full copy of annex information for key(s) not not url "transfer"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4995]
`copy-file` operates by reading out urls for a key and populating a file in the new dataset using those url(s).  

Pros:
- backend (and other possible custom settings of the new clone) migration happens if it is needed

Cons:
- works only for keys with urls from remotes, all other remotes availability information is not transfererd
- (probably, didn't check) would "serialize" s3 availability of exported to S3 files as "urls" instead of copying .rmet (like openneuro ones)

During initial discussion of `copy-file` implementation (TODO: find issue/PR) an alternative implementation with a full copy of information from annex seemed more evolved and was not needed for the usecase at hands (hcp) so was not attempted. But I think in many scenarios (in particular for e.g. `mv` #1193) it would beneficial to support a "full transfer" which also probably could be faster and not even require data to be present locally to instantiate keys in destination (git files should be copied)

- key (symlink) is copied to the destination dataset (possibly under a different name/path)
- information from `git-annex` branch for the key is copied into `git-annex` branch of destination
  - need to look out for [the `annex.tune` options](https://git-annex.branchable.com/tuning/) which AFAIK we have not used but could be defined
- (special) remotes information should also be copied (if not yet known at destination) based on the UUIDs found in the key annex .lo
- backend of the key doesn't need to match the default really, just need to be supported

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
