### ISSUE TITLE
Address "non-finishing" batched processes properly

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4998]
"Introduced" within https://github.com/datalad/datalad/pull/4829/files#diff-9f14d6f5afddd497b06677e855a05d9eR1333

- our "waiting time" might be insufficient in legit cases, so we should not just abandon git-annex processes and proceed (e.g. with a commit) since it could lead to inconsistent commits (yet to be seen, but I saw batched processes exiting peacefully after 1 or 2 loops)
- reported to @joeyh : https://git-annex.branchable.com/bugs/some_annex_addurl_--fast_--with-files_--json_--json-error-messages_--batch__do_not_quit/ . More investigation is needed, may be bisection of git-annex (yet to double check that older versions aren't the subject to this) and more careful analysis of changes in #4829 on what has introduced that effect
- the way I  reproduce it mimics original stall on CI
```shell
(dev3) test@smaug:~/proj/datalad/datalad$ git diff
diff --git a/datalad/cmd.py b/datalad/cmd.py
index d4d54eb46..c8a666e24 100644
--- a/datalad/cmd.py
+++ b/datalad/cmd.py
@@ -1353,6 +1353,7 @@ class BatchedCommand(SafeDelCloseMixin):
                     timeout=3.0,
                 )
             except subprocess.TimeoutExpired:
+                import pdb; pdb.set_trace()
                 lgr.warning(
                     "Batched process %s did not finish, abandoning it without killing it",
                     process)
...
(dev3) test@smaug:~/proj/datalad/datalad-crawler/__testhome__$ PATH=~/git-annex/20201005-snapshot/ DATALAD_LOG_LEVEL=WARNING DATALAD_TESTS_TEMP_KEEP=1 python -m nose -s -v --with-cov --cover-package datalad ../datalad_crawler/dbs/tests/test_files.py ../datalad_crawler/nodes/tests/test_annex.py
```
and end up in pdb upon timeout

**Comment by yarikoptic** [comment]
grrr this bug... as soon as became brave to bisect sh.t out of it -- cannot reproduce locally or on smaug in **exactly** the same env I prepared for joey and reproduced it reliably in the past.  May be it is the fact that more starlink satellites in the orbit, I am out of ideas.... But I know that if I remove this kludge, travis will stall!  I bet it will!

**Comment by yarikoptic** [comment]
oh, at least  some of those, on windows in particular, and when involving some external git annex remote, were addressed on git-annex side. Some other, were coming from "leakage" of instances across tests and some circular dependencies in flighweights, we have not seen those for a while, even if #5013 was merged... oh crap -- it was merged past 0.13.5 -- may be that would explain fresh https://github.com/datalad/datalad/issues/5145 (but I think we had good green runs since then under datalad-extensions... need to be double-checked that it is not it and if not -- close this one)

**Comment by adswa** [comment]
Has this surfaced again in the past 9 months? I personally haven't seen it, but I was not paying too much attention...

**Comment by yarikoptic** [comment]
oh well -- hard to remember now ;) thanks for the buzz
- there was quite  a saga for fixing it at windows, which likely resulted in overall changes across OSes
- I think I have not observed any leaks recently, so let's just indeed let it RiP and bring from the dead in a new life form if someone spots any
