### ISSUE TITLE
automate "releases"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4999]
even if I've heard about it, didn't "register", but it seems to be quite powerful and flexible: https://github.com/intuit/auto

(was mentioned in https://github.com/physiopy/phys2bids/issues/311)

**Comment by smoia** [comment]
We're trying to set it up - since OHBM. We had some bumps on the road (see physiopy/phys2bids#181 and physiopy/phys2bids#239). If you manage to implement it, let us know - equally, if we figure it out we can help you set it up!

**Comment by jwodder** [comment]
@yarikoptic How exactly do you want this to work?  Should all PRs to master cause a new version to be tagged and a GitHub release to be created, or should it only be certain PRs (and, if so, should it be PRs that have a certain label or lack a certain label that cause new releases to be made)?

**Comment by yarikoptic** [comment]
I think upon a PR with a `release` label added.  It might be going against `maint` branch (not necessarily `master`).  I think we better try setup out on `dandi-cli` - it is an easier target and see how we like it.

**Comment by jwodder** [comment]
@yarikoptic Rather than jumping immediately to implementing this in dandi-cli, I've created a test repo https://github.com/jwodder/auto-test for testing auto out in.  I've made you a collaborator so you can test it out as well.

Note the following:

- When applying this to dandi-cli, I believe we'll have to get rid of the header section in CHANGELOG.md and decrease the subsequent headers by one level.  Otherwise, there will be formatting issues.
- Because `onlyPublishWithReleaseLabel` is set, I *think* it's OK to push commits directly to master, and doing so won't cause a release, but I haven't tested that.

**Comment by yarikoptic** [comment]
re sectioning -- I think that is just fine

re pushes to master -- generally they are discouraged anyways.  As long as release PR/branches are merged in, I think that releasing from a PR is just as fine

**Comment by yarikoptic** [comment]
note: We should do this as soon as we release 0.14.0

**Comment by yarikoptic** [comment]
Given the unfortunate upcoming departure of @kyleam, and since nobody voiced their desire to take over release management which @kyleam took care about in the past years, I think we should go `auto`. Insofar we used auto-based releasing for a good number of projects, including `datalad-container` and it worked out quite well. 
So, I am giving @jwodder a green light to prepare a PR for this repo against `maint` branch.  While at it I guess we should also switch to using versioneer since we are using it in majority of extensions already and https://github.com/datalad/datalad-extension-template also uses it.  So wouldn't hurt to harmonize IMHO.

**Comment by bpoldrack** [comment]
> since nobody voiced their desire to take over release management which @kyleam took care about in the past years, I think we should go auto. Insofar we used auto-based releasing for a good number of projects, including datalad-container and it worked out quite well.

While I generally agree - I still have no idea what exactly it picks up how and what we should therefore pay attention to in PRs, so it would be able to assemble a decent changelog, instead of a bunch of remarks that may be useful for other core developers but meaningless for users.

> While at it I guess we should also switch to using versioneer

+1

**Comment by jwodder** [comment]
@bpoldrack By default, `auto` only uses PR names and labels.

**Comment by smoia** [comment]
If I can help - It's true that the changelog is less intelligible than a human-based changelog, and that it might require interested users to _open_ some issues to properly understand them, but if the title of the PR is self-explanatory enough, it's not that bad. See [phys2bids changelog](https://github.com/physiopy/phys2bids/releases) or even better [auto changelog](https://github.com/intuit/auto/releases). The categories can be tweaked and adapted to your needs in the file configuration (they mainly require a label for each category). Also Adam is welcoming towards external PRs, so you might be able to slip in an enhancement to have the first part of the PR message in the log?

**Comment by yarikoptic** [comment]
well, `maint` is `auto`mated or better or for worse, let's consider this particular one done
