### ISSUE TITLE
aspera support

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5]
Aspera is a company (http://asperasoft.com , apparently belonging to IBM now) developing products for the high-performance transfer -- it intends to fill up the pipe even while going through the WAN .  Currently used by NIH (for NCBI) and HCP.

Pros:
- efficient transfer

Cons:
- closed source proprietary patented technology
- even clients are closed source
- freely available client might be difficult to "drive" due to a rich variety of settings/options etc

Theoretically nothing forbids supporting it, but logistically it might be very messy (see cons).

**Comment by yarikoptic** [comment]
Dan Marcus shared that there would be a webinar about Aspera extension for git server(s) : http://asperasoft.com/company/webinars/  might be worth checking out if interested @datalad/developers

**Comment by mih** [comment]
Six years after the last post here, and three years after the last mention of this issue, I will close it, because it never became critical enough to actually work on it. Its wisdom will be preserved even in its new state.
