### ISSUE TITLE
Windows 10 `git-annex` installation fails

### ISSUE THREAD

**Issue by nrosjat** [datalad/datalad#5000]
I have tried to install Datalad on a Windows 10 system (Win 10 Enterprise, v1909). For this I followed _3.16 Windows 10 from the Datalad Handbook_, that is:

- Step 1: Install conda
- Step 2: Install git `conda install -c conda-forge git`
- Step 3: Install git-annex

At the last step I used `C:\Users\me\Miniconda3\Library` as installation path as recommended. But when restarting Windows I got an error message from the Windows Script Host that the file could not be found. It seems like in autostart a file with a (probably hardcoded) default path to Git `C:\Program Files\Git\cmd\git-annex-autostart.vbs` was created automatically. I replaced this link with the filepath to Anaconda. After that I get the next error message

```
Script: git-annex-autostart.vsb
Line: 2
Error: Subscript out of range
code: 800A0009
```

So there seems to be an error with `WScript.Arguments(0)` to determine the current directory. Probably the input of another path is expected here, but where should it point to?

**Comment by adswa** [comment]
Thanks for the bug report! I got my hands on a fresh Windows computer and will take a look at installations methods and potential problems

**Comment by yarikoptic** [comment]
instructions in the handbook were adjusted.  Having `git` installed inside conda is not "advisable" ATM. You could also try our fresh(iest) build of git-annex from http://datasets.datalad.org/datalad/packages/windows/ . Please re-open if issue persists
