### ISSUE TITLE
Poll: Primary API for documentation?

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#501]
It is time to compose some tutorial-style documentation for datalad targeting the upcoming workshops. Question is now: What is the primary API to present for this purpose?

From my POV this can only be the cmdline API, but I want to reassure myself...

This is obviously a question that is independent of the need to document both APIs.

Moreover, we surely want to be able to test the cmdline tutorials too.

**Comment by yarikoptic** [comment]
I guess indeed primary short-term target should be the cmdline API for those common commands: `create`, `install`, `update`, `uninstall` I guess.  But wouldn't it be trickier to get it "doctested"? I feel like there is smth in sphinx but I haven't used it for so long that I have forgotten.

In the long term, we could see if we could have both APIs somehow exhibited within the same tutorial, where just a switch would allow to go from one to another.  I think I saw it somewhere but forgot where... will dig out.

There is one feature which I would like to demonstrate but it is a bit Python specific -- that AutomagicIO, but it is also usable via `python -m datalad` in cmdline.  Also, eventually we will come to tutorials on crawling.  Those are primarily in Python, so cmdline examples will not be the main target.

**Comment by bpoldrack** [comment]
+1 for cmdline API as the primary target for now.
But for these basic things, the python API will look very similar anyway (and will equally well work at any point, the cmdline API does). So, maybe it's not a significant extra effort to provide it simultanously ...

**Comment by yarikoptic** [comment]
if only there was an answer to [Is there a way to use doctest and sphinx to test and document command line applications?](https://stackoverflow.com/questions/22843529/is-there-a-way-to-use-doctest-and-sphinx-to-test-and-document-command-line-appli)

**Comment by hanke** [comment]
I think we are all on the same page.
