### ISSUE TITLE
python api create: cfg_proc results in exception

### ISSUE THREAD

**Issue by SteffenBrinckmann** [datalad/datalad#5018]
#### What is the problem?
If I run in python  datalad.api.create(path='mydataset', cfg_proc='text2git')
I get an exception
UnsupportedOperation: fileno

#### What steps will reproduce the problem?
import datalad
datalad.api.create(path='mydataset', cfg_proc='text2git')
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.13.4
# WTF
## datalad 
  - full_version: 0.13.4
  - version: 0.13.4
## dataset 
  - id: 11382775-849a-4f4d-a52d-925952941270
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /home/sbrinckm/temporary_test0/NewProject
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.4.3
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 7.20190819+git2-g908476a9b-1~ndall+1
  - cmd:bundled-git: 2.20.1
  - cmd:git: 2.20.1
  - cmd:system-git: 2.17.1
  - cmd:system-ssh: 7.6p1
  - exifread: 2.1.2
  - git: 3.0.5
  - gitdb: 2.0.6
  - humanize: 3.0.1
  - iso8601: 0.1.13
  - keyring: 10.6.0
  - keyrings.alt: 3.0
  - msgpack: 1.0.0
  - mutagen: 1.38
  - requests: 2.18.4
  - tqdm: 4.50.0
  - wrapt: 1.12.1
## environment 
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US
  - LC_ADDRESS: en_US.UTF-8
  - LC_IDENTIFICATION: en_US.UTF-8
  - LC_MEASUREMENT: en_US.UTF-8
  - LC_MONETARY: en_US.UTF-8
  - LC_NAME: en_US.UTF-8
  - LC_NUMERIC: en_US.UTF-8
  - LC_PAPER: en_US.UTF-8
  - LC_TELEPHONE: en_US.UTF-8
  - LC_TIME: en_US.UTF-8
  - PATH: /home/sbrinckm/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/sbrinckm/FZJ/JamDB/Python:/home/sbrinckm/Android/Sdk/emulator:/home/sbrinckm/Android/Sdk/tools:/home/sbrinckm/Android/Sdk/tools/bin:/home/sbrinckm/Android/Sdk/platform-tools
  - PYTHONPATH: :/home/sbrinckm/MPIE/zz_Code/FEM_Abaqus/:/home/sbrinckm/FZJ/SourceCode/EBSD:/home/sbrinckm/FZJ/SourceCode/Nanotribology:/home/sbrinckm/FZJ/SourceCode/Micromechanics/src:/home/sbrinckm/FZJ/SourceCode/orix
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - local repository version: 5
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions: 
    - 5
    - 7
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  - version: 7.20190819+git2-g908476a9b-1~ndall+1
## location 
  - path: /home/sbrinckm/temporary_test0/NewProject
  - type: dataset
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp: 
    - load_error: None
    - module: datalad.metadata.extractors.xmp
    - version: None
## python 
  - implementation: CPython
  - version: 3.6.9
## system 
  - distribution: Ubuntu/18.04/bionic
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 297
  - name: Linux
  - release: 5.4.0-42-generic
  - type: posix
  - version: #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020

#### Is there anything else that would be useful to know in this context?
The exception log:
[INFO] Creating a new annex repo at /home/sbrinckm/temporary_test0/mydataset 
[INFO] Running procedure cfg_text2git 
[INFO] == Command start (output follows) ===== 
---------------------------------------------------------------------------
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-9-88a66abe531b> in <module>
----> 1 datalad.api.create(path='mydataset', cfg_proc='text2git')

/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py in eval_func(wrapped, instance, args, kwargs)
    492                     return results
    493             lgr.log(2, "Returning return_func from eval_func for %s", wrapped_class)
--> 494             return return_func(generator_func)(*args, **kwargs)
    495 
    496     return eval_func(func)

/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py in return_func(wrapped_, instance_, args_, kwargs_)
    480                     # unwind generator if there is one, this actually runs
    481                     # any processing
--> 482                     results = list(results)
    483                 # render summaries
    484                 if not result_xfm and result_renderer in ('tailored', 'default'):

/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py in generator_func(*_args, **_kwargs)
    411                     result_log_level,
    412                     # let renderers get to see how a command was called
--> 413                     allkwargs):
    414                 for hook, spec in hooks.items():
    415                     # run the hooks before we yield the result

/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py in _process_results(results, cmd_class, on_failure, action_summary, incomplete_results, result_renderer, result_log_level, allkwargs)
    550     render_n_repetitions = 10 if sys.stdout.isatty() else float("inf")
    551 
--> 552     for res in results:
    553         if not res or 'action' not in res:
    554             # XXX Yarik has to no clue on how to track the origin of the

/usr/local/lib/python3.6/dist-packages/datalad/core/local/create.py in __call__(path, initopts, force, description, dataset, no_annex, annex, fake_dates, cfg_proc)
    501 
    502         for cfg_proc_ in cfg_proc:
--> 503             for r in tbds.run_procedure('cfg_' + cfg_proc_):
    504                 yield r
    505 

/usr/local/lib/python3.6/dist-packages/datalad/distribution/dataset.py in apply_func(wrapped, instance, args, kwargs)
    501             elif i >= ds_index:
    502                 kwargs[orig_pos[i+1]] = args[i]
--> 503         return f(**kwargs)
    504 
    505     setattr(Dataset, name, apply_func(f))

/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py in eval_func(wrapped, instance, args, kwargs)
    492                     return results
    493             lgr.log(2, "Returning return_func from eval_func for %s", wrapped_class)
--> 494             return return_func(generator_func)(*args, **kwargs)
    495 
    496     return eval_func(func)

/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py in return_func(wrapped_, instance_, args_, kwargs_)
    480                     # unwind generator if there is one, this actually runs
    481                     # any processing
--> 482                     results = list(results)
    483                 # render summaries
    484                 if not result_xfm and result_renderer in ('tailored', 'default'):

/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py in generator_func(*_args, **_kwargs)
    411                     result_log_level,
    412                     # let renderers get to see how a command was called
--> 413                     allkwargs):
    414                 for hook, spec in hooks.items():
    415                     # run the hooks before we yield the result

/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py in _process_results(results, cmd_class, on_failure, action_summary, incomplete_results, result_renderer, result_log_level, allkwargs)
    550     render_n_repetitions = 10 if sys.stdout.isatty() else float("inf")
    551 
--> 552     for res in results:
    553         if not res or 'action' not in res:
    554             # XXX Yarik has to no clue on how to track the origin of the

/usr/local/lib/python3.6/dist-packages/datalad/interface/run_procedure.py in __call__(spec, dataset, discover, help_proc)
    450                 # pass through here
    451                 on_failure='ignore',
--> 452                 return_type='generator'
    453         ):
    454             yield r

/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py in generator_func(*_args, **_kwargs)
    411                     result_log_level,
    412                     # let renderers get to see how a command was called
--> 413                     allkwargs):
    414                 for hook, spec in hooks.items():
    415                     # run the hooks before we yield the result

/usr/local/lib/python3.6/dist-packages/datalad/interface/utils.py in _process_results(results, cmd_class, on_failure, action_summary, incomplete_results, result_renderer, result_log_level, allkwargs)
    550     render_n_repetitions = 10 if sys.stdout.isatty() else float("inf")
    551 
--> 552     for res in results:
    553         if not res or 'action' not in res:
    554             # XXX Yarik has to no clue on how to track the origin of the

/usr/local/lib/python3.6/dist-packages/datalad/core/local/run.py in __call__(cmd, dataset, inputs, outputs, expand, explicit, message, sidecar)
    237                              explicit=explicit,
    238                              message=message,
--> 239                              sidecar=sidecar):
    240             yield r
    241 

/usr/local/lib/python3.6/dist-packages/datalad/core/local/run.py in run_command(cmd, dataset, inputs, outputs, expand, explicit, message, sidecar, extra_info, rerun_info, extra_inputs, rerun_outputs, inject, saver)
    626         cmd_exitcode, exc = _execute_command(
    627             cmd_expanded, pwd,
--> 628             expected_exit=rerun_info.get("exit", 0) if rerun_info else None)
    629 
    630 

/usr/local/lib/python3.6/dist-packages/datalad/core/local/run.py in _execute_command(command, pwd, expected_exit)
    468             log_stderr=False,
    469             expect_stderr=True,
--> 470             expect_fail=True,
    471             # TODO stdin
    472         )

/usr/local/lib/python3.6/dist-packages/datalad/cmd.py in run(self, cmd, log_stdout, log_stderr, log_online, expect_stderr, expect_fail, cwd, env, shell, stdin)
    913                                         cwd=popen_cwd,
    914                                         env=popen_env,
--> 915                                         stdin=stdin)
    916 
    917             except Exception as e:

/usr/lib/python3.6/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    685         (p2cread, p2cwrite,
    686          c2pread, c2pwrite,
--> 687          errread, errwrite) = self._get_handles(stdin, stdout, stderr)
    688 
    689         # We wrap OS handles *before* launching the child, otherwise a

/usr/lib/python3.6/subprocess.py in _get_handles(self, stdin, stdout, stderr)
   1202             else:
   1203                 # Assuming file-like object
-> 1204                 c2pwrite = stdout.fileno()
   1205 
   1206             if stderr is None:

UnsupportedOperation: fileno

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Non python-api version works fine

**Comment by bpoldrack** [comment]
> import datalad
> datalad.api.create(path='mydataset', cfg_proc='text2git')

Minor comment: Should likely be `import datalad.api` otherwise it should fail before execution.

At a first trial, this create call works for me in python 3.6, 3.7 and 3.8. So, it's not the python API per se leading to that issue. However, the error suggests that something goes wrong with the output capturing.

**Comment by bpoldrack** [comment]
@SteffenBrinckmann : Apart from the need to get to the core of the problem, just want to point out, that

```
import datalad.api
dataset = datalad.api.create('mydataset')
dataset.run_procedure('cfg_text2git')
```

Is supposed to do the same thing. Would be good to see, whether that works for you (and is a workaround in case it does).

**Comment by SteffenBrinckmann** [comment]
Sorry, it is an ipython/jupyter issue. If I run in native python it works fine.
