### ISSUE TITLE
save: does not add subdataset(s) to .gitmodules if nested

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5021]
<details>
<summary>reproducer with 2 parts -- 1) create/save 1 direct; 2) create/save 1 direct and nested within </summary> 

```shell
#!/bin/bash

export PS4='> '
set -x
set -eu
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"

: "=================== 1 -- ok"
datalad create testgh1; 
(
cd testgh1
datalad create subds
datalad save -d . subds
git status
datalad subdatasets -r
)

: "=================== 2 - nested -- not ok"
datalad create testgh2; 
(
cd testgh2
datalad create subds
datalad create subds/subsubds
datalad save -d . subds subds/subsubds
git status
datalad subdatasets -r
)
```
</details>

<details>
<summary>output</summary> 

```shell
> set -eu
>> mktemp -d /home/yoh/.tmp/dl-XXXXXXX
> cd /home/yoh/.tmp/dl-kskmghy
> : '=================== 1 -- ok'
> datalad create testgh1
[INFO] Creating a new annex repo at /home/yoh/.tmp/dl-kskmghy/testgh1 
create(ok): /home/yoh/.tmp/dl-kskmghy/testgh1 (dataset)
> cd testgh1
> datalad create subds
[INFO] Creating a new annex repo at /home/yoh/.tmp/dl-kskmghy/testgh1/subds 
create(ok): /home/yoh/.tmp/dl-kskmghy/testgh1/subds (dataset)
> datalad save -d . subds
add(ok): /home/yoh/.tmp/dl-kskmghy/testgh1/subds (file)
add(ok): /home/yoh/.tmp/dl-kskmghy/testgh1/.gitmodules (file)
save(ok): /home/yoh/.tmp/dl-kskmghy/testgh1 (dataset)
action summary:
  add (ok: 2)
  save (ok: 1)
> git status
On branch master
nothing to commit, working tree clean
> datalad subdatasets -r
subdataset(ok): /home/yoh/.tmp/dl-kskmghy/testgh1/subds (dataset)
> : '=================== 2 - nested -- not ok'
> datalad create testgh2
[INFO] Creating a new annex repo at /home/yoh/.tmp/dl-kskmghy/testgh2 
create(ok): /home/yoh/.tmp/dl-kskmghy/testgh2 (dataset)
> cd testgh2
> datalad create subds
[INFO] Creating a new annex repo at /home/yoh/.tmp/dl-kskmghy/testgh2/subds 
create(ok): /home/yoh/.tmp/dl-kskmghy/testgh2/subds (dataset)
> datalad create subds/subsubds
[INFO] Creating a new annex repo at /home/yoh/.tmp/dl-kskmghy/testgh2/subds/subsubds 
create(ok): /home/yoh/.tmp/dl-kskmghy/testgh2/subds/subsubds (dataset)
> datalad save -d . subds subds/subsubds
add(ok):../ /home/yoh/.tmp/dl-kskmghy/testgh2/subds/subsubds (file)
add(ok):../ /home/yoh/.tmp/dl-kskmghy/testgh2/subds/.gitmodules (file)
save(ok): /home/yoh/.tmp/dl-kskmghy/testgh2/subds (dataset)
add(ok): /home/yoh/.tmp/dl-kskmghy/testgh2/subds (file)
save(ok): /home/yoh/.tmp/dl-kskmghy/testgh2 (dataset)
action summary:
  add (ok: 3)
  save (ok: 2)
> git status
On branch master
nothing to commit, working tree clean
> datalad subdatasets -r

```
</details>

so the end of above log looks like
```
> datalad save -d . subds subds/subsubds
add(ok):../ /home/yoh/.tmp/dl-kskmghy/testgh2/subds/subsubds (file)
add(ok):../ /home/yoh/.tmp/dl-kskmghy/testgh2/subds/.gitmodules (file)
save(ok): /home/yoh/.tmp/dl-kskmghy/testgh2/subds (dataset)
add(ok): /home/yoh/.tmp/dl-kskmghy/testgh2/subds (file)
save(ok): /home/yoh/.tmp/dl-kskmghy/testgh2 (dataset)
action summary:
  add (ok: 3)
  save (ok: 2)
> git status
On branch master
nothing to commit, working tree clean
> datalad subdatasets -r
```

not to mention confusing `../` (hopefully #4454 would get revived some time), what is interesting is that top level dataset got no `.gitmodules` record for `subds` (although there is `add(ok)` for it.  the nested one seems got its record added ok

```shell
(git-annex)lena:~/.tmp/dl-kskmghy/testgh2[master]git
$> cat subds/.gitmodules 
[submodule "subsubds"]
	path = subsubds
	url = ./subsubds
	datalad-id = 32fd57b8-b343-442b-b332-937707dad644
```

IMHO it is of an important severity
tested also with `maint` - the same

**Comment by bpoldrack** [comment]
I agree that `save` doesn't seem to behave intuitively in that situation. However, at least part of the problem is: While I know what you want the result to be, it's not actually clear from the point of view of a `save` implementation. If you specify `subds` explicitly, it's not clear per se whether or not you want subds itself being modified first. Maybe you just want to add the subdataset in the state it's currently in (without `subds/subds`). This would involve some magic inspecting all given paths first at draw conclusions as to what the user actually meant. There's still another issue resulting in `subds` not being added at all, but it's not easily clear what to ultimately do with such a call, I think. I wouldn't call it a bug if you end up with `subds` being an actual subdataset (result of first path given), but already modified (result of second path). However, I'd expect `save` to result in what you probably want when calling `datalad save -r`. And this doesn't happen either.

**Comment by yarikoptic** [comment]
> I agree that save doesn't seem to behave intuitively in that situation

IMHO it behaves inconsistent with any semantic :

- having `sub` properly added to .gitmodules when alone but not when accompanied with `sub/sub` has no "logical explanation" to me since AFAIK we do not have "paths composition/order dependent semantic" AFAIK here.
- having `save` saving Subproject for `sub` but not adding it to `.gitmodules` is also something we do not have as a "feature"

Since I do specify `-d dataset`, I am saying "save provided paths state within hierarchy of this `dataset`" (I am not adding `-r` to say "also inspect subdatasets on specified paths and save their internal changes first"). And it seems to do what I intended, BUT adding that `sub` to `.gitmodules`.  So IMHO it is just a bug ;-)

**Comment by kyleam** [comment]
I think the fix likely will be somewhere in here:

https://github.com/datalad/datalad/blob/4b6606cb4e71cf031d906df2f6b5b61a693bab1a/datalad/core/local/save.py#L240-L255

If you drop that logic entirely, the second case in your script adds the subdataset to the top-level dataset's .gitmodules.  Unsurprisingly, that also results in several `datalad.core.local.tests.test_save` failures (haven't tried any tests outside that).

I'll try to understand what that logic is doing and see if we can adjust it.

**Comment by yarikoptic** [comment]
THANK YOU @kyleam !  I have tried to get to look into fixing up this #5022-blocker but haven't yet, so your help will be much appreciated!
