### ISSUE TITLE
datalad ignores virtualenvs

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#5030]
Stumbled upon this in context of #5024 :

In that case it's `datalad get` behaving differently than `git-annex-get` because it's calling `git-annex` in a different environment leading to a different implementation of a special remote being used.
Ultimately it boils down to the `Runner` prefixing `PATH` with `/usr/bin`. This is because `GitRunnerBase` looks for `git-annex` and then prepending `PATH` with its location. This does not only make sure we know what annex installation we are using. It also overrules anything in a virtualenv that is also installed system-wide.

**Comment by mih** [comment]
I agree, this is not desirable.

**Comment by mih** [comment]
Maybe we should make `DATALAD_USE_DEFAULT_GIT` a config switch and enable that system-wide for us.

**Comment by bpoldrack** [comment]
I'm not convinced yet. This would need to be set by anyone using any kind of virtualenv (incl. conda?). Plus, it ultimately is backwards. The issue is about using other executables from whatever is set in `PATH` rather than about what `git/git-annex` to use (which is detected correctly in a way).

What `DATALAD_USE_DEFAULT_GIT` is meant for AFAICT, is to declare that we want to use system's `git` rather than a bundled with annex `git` in a bundled annex installation. This seems orthogonal to the question where to use other executables from.

**Comment by bpoldrack** [comment]
May be just check whether the "bundled" `git` as found in line 1102 is actually different from `find_executables('git')`. And if not there's nothing to do.

**Comment by yarikoptic** [comment]
@bpoldrack FWIW - I do not immediately see a problem with such approach, so might work!
