### ISSUE TITLE
FOI: Windows(?): Nose requires --traverse-namespace under Python 3.8

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#5036]
On Windows 10 with nose 1.3.7 and Python 3.8 I struggled to get nose to discover any tests. 
Any nose call basically resulted in 

```
-----------------------------------------------
Ran 0 tests in 0.043s

OK
```

I stumbled across https://stackoverflow.com/questions/58556183/nose-unittest-discovery-broken-on-python-3-8, and, indeed, using ``python -m nose --traverse-namespace`` works.
Posting as an FYI in case this behavior shows up in our CI at some point.

**Comment by yarikoptic** [comment]
AWESOME, thank you @adswa and thanks @mih for referral to this FOI notification of which I had missed. Might be useful for @jwodder as well. 

I will submit a PR to add to CONTRIBUTING.md.

**Comment by adswa** [comment]
Glad it helped! Since this is in CONTRIBUTING.md now, I will close this.
