### ISSUE TITLE
default credentials configured for `indi-s3` prevent anonymous connect

### ISSUE THREAD

**Issue by loj** [datalad/datalad#5038]
#### What is the problem?

`datalad-test-s3` credentials are configured as the default for `fcp-indi` (`datalad/downloaders/configs/indi.cfg`). 

#### What steps will reproduce the problem?

If I don't have my own credentials configured and want to connect to `s3://fcp-indi/data/Projects/INDI/SALD/RawData_BIDS/` anonymously, I am not able to do so unless I comment out the credentials configured in `datalad/downloaders/configs/indi.cfg`.

```
❱ datalad ls -Lr 's3://fcp-indi/data/Projects/INDI/SALD/RawData_BIDS/'
Connecting to bucket: fcp-indi
You need to authenticate with 'datalad-test-s3' credentials. team@datalad.org provides information on how to gain access
key_id: 

ERROR: 
Interrupted by user while doing magic: KeyboardInterrupt() [dialog.py:question:262]
```

#### What version of DataLad are you using?

datalad 0.13.4.dev239

**Comment by yarikoptic** [comment]
Thank you for the report!  I think that configuration just comes from times whenever we had no anonymous access "implemented".  Care to submit a PR against `maint` removing that line ?
