### ISSUE TITLE
our special remotes inherit GIT_DIR etc from git-annex but start annex commands from repo topdir

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#506]
This leads to such obscure failures as 

```
(git)smaug:/mnt/btrfs/scrap/datalad/ds000001[master]sub001/BOLD/task001_run002/QA
$> git annex drop fd.png                            
drop fd.png git-annex: git: createProcess: runInteractiveProcess: chdir: does not exist (No such file or directory)
(unsafe) 
  Could only verify the existence of 0 out of 1 necessary copies

  Unable to access these remotes: datalad-archives

  Try making some of these repositories available:
  	899f0347-0888-48ef-91b6-bac213ca8cef -- [datalad-archives]
   	c8bd3d05-33d4-4b59-9d53-ca7efbdcdd13 -- yoh@smaug:/mnt/btrfs/datasets/datalad/crawl/openfmri/ds000001

  (Use --force to override this check, or adjust numcopies.)
```
which is due to our custom remote starting contentlocation batch process as we usually do from the top dir of the repository, while inheriting GIT_DIR=../../.., which then leads to

```
$> echo -e 'MD5E-s2526804721--b29a61c20f974c5e75e7783500ebe8ed.tgz' | GIT_WORK_TREE=../../../.. GIT_DIR=../../../../.git git annex contentlocation --batch
git-annex: git: createProcess: runInteractiveProcess: chdir: does not exist (No such file or directory)
```

@joeyh -- what do you think would be the best resolution?

1. start batch process within current directory
   cons: then I think it might interfer with our "start all git/annex from top directory" which does paths normalization etc, and might become defunct if that directory gets removed in the process while batch process is still running

2. sanitize the environment (GIT_DIR GIT_WORK_TREE, anything else?) before invoking git/annex from top directory

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> @joeyh -- what do you think would be the best resolution?

It's worth considering whether git-annex should be passing these 
GIT_DIR etc environments to the special remote process. 

Well, if git-annex didn't set these, and git was run with --git-dir or
--work-tree, it would not communicate those overrides on to the special
remote process, and so if the special remote then ran a git command
(including re-running git-annex), it would run with the wrong values.

Also, git --git-dir annex ... sets GIT_DIR to communicate it to
git-annex, so it's consistent for git-annex to pass these environment
variables on to its children as well. (git-annex goes ahead and always
sets GIT_DIR and GIT_WORK_TREE even when --git-dir and --work-tree are
not set, for reasons of consistency/simplicity.)

Perhaps git-annex should set GIT_DIR etc to absolute paths in case
the special remote process chdir's. However, the relative paths are
useful especially on Windows with its very short limits on the length of
paths.

>  2. sanitize the environment (GIT_DIR GIT_WORK_TREE, anything else?) before
>     invoking git/annex from top directory

If you mean sanitize by clearing then no; it would break --git-dir and
--work-tree setting propigation.

If you're going to chdir, it makes sense to adjust these relative paths
to be absolute or relative to the new CWD.

-- 
see shy jo
