### ISSUE TITLE
`subdatasets -r` listing: should be fast(er) 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5075]
haven't look in detail yet but IMHO `subdatasets` seems to be doing something `avoidable`.  if `subdatasets -r` supposed to list only "known" subdatasets, should it even "consult" `.config` of leaf datasets if there is no `.gitmodules` in the top directory of that leaf dataset? 

Here is the flame graph of running process where it was slowly listing leaf subdatasets: http://www.onerussian.com/tmp/busy-datalad-subdatasets-1.svg . So it seems (didn't look in detail) that .config is consulted by AnnexRepo in `__init__`, which I guess we instantiate to verify that subdataset is installed...  May be could be "avoided"?  (didn't look in detail yet)

Also,  If it is collecting all kinds of "useful information" which is otherwise disregarded at the end (e.g. whenever I just need to list subdatasets), we might look into making such "additional lookup" lazy (i.e. triggered only when some key is requested from the yielded record).

**Comment by mih** [comment]
Can you please share which datalad version you were using, and whether it had #4868?

**Comment by mih** [comment]
I have adjusted the title of the issue to make clear that this is about recursive processing.

**Comment by yarikoptic** [comment]
FWIW, I think it had no #4868 merged , but I guess irrelevant since confirmed etc.  Thanks again!
