### ISSUE TITLE
log_progress_stage "progressbars" helper

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5079]
#### What is the problem?

ATM we just rely on `lgr.info` but we do and should use it sparsely. So we would not use it if in some cases operations could complete fast and be many to run.

If we could have something like
```python
with log_process_stage(f"Processing dataset {ds}", steps=["fetch", "process", "save"]) as lps:
  lps.next()
  fetch()
  lps.next()
  process()
  lps.next()
  ds.save()
```
which would display progress bar with `3` total and then adjust label as it goes from "Processing dataset XXX: fetch" to "Processing dataset XXX: save" (on top of any other progressbar which might come from log_progress etc) and then as any other progressbar disappear -- would be awesome and informative to the user. (changes in https://github.com/datalad/datalad/pull/5022/ would also ensure that logging would just be "streaming" above the progressbars)

It can already be done with log_progress, but IMHO a helper would be of "help" (unless I am mistaken).  Notes:

- if there are conditional steps, we could have `next(step=None)` so it would find the step in the list and know that some were skipped, and thus adjust the label to also say `"skipped: process"` (e.g. if we had `lps.next("save")` but not the one for "process".

- edit: a "smart" one could may be not show ETA based on current steps progression, but (optionally?) just collect statistics for a given code placement (or some explicitly provided `id`) and guestimate duration based on the prior runs - I expect that in typical usecases it would already be "in the right ballpark"

WDYT?

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
