### ISSUE TITLE
Windows revelation not so obvious to me - may be for someone else?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5082]
might be something very obvious to  Windows gurus but here you go:

```shell
(Pdb) event_loop.run_until_complete(run_async_cmd(event_loop, 'git annex version --raw' , protocol, stdin, protocol_kwargs=kwargs, cwd=cwd, env=env))
{'stdout': '8.20201008-g577af1b', 'stderr': '', 'code': 0}
(Pdb) event_loop.run_until_complete(run_async_cmd(event_loop, ['git', 'annex', 'version', '--raw'], protocol, stdin, protocol_kwargs=kwargs, cwd=cwd, env=env))
{'stdout': '', 'stderr': "git: 'annex' is not a git command. See 'git --help'.\n", 'code': 1}
```

the same with old `Runner` (directly here):
```
(Pdb) Runner().run('git annex version', env=env2)
('git-annex version: 8.20201008-g577af1b\r\nbuild flags:.....', '')
(Pdb) Runner().run(['git', 'annex', 'version'], env=env2)
*** datalad.support.exceptions.CommandError: CommandError: '"git" "annex" "version"' failed with exitcode 1 [err: 'git: 'annex' is not a git command. See 'git --help'.']
```

so `env` (so PATH) is the same, but when it is explicitly ran through shell of some kind on windows - something happens to PATH as it gets to git, or may be a different git is ran, dunno

In my "explorations" I apparently did not follow http://handbook.datalad.org/en/latest/intro/installation.html#windows-10 "to the word", which do not tell to install git natively systemwide, but rather within conda, and then git-annex INTO conda env.
I followed git-annex installation instructions (install git, then git-annex into git) and then created a new conda environment into which I `conda install -c conda-forge --only-deps datalad` and then `pip install -e .` within datalad git .  But if `git` does see `git-annex` whenever I run in a normal windows shell, or in conda shell outside of `datalad` environment; it does not see it inside `datalad` environment and that seems to relate to PATH overloads done by conda (if I prepend `C:\Program Files\Git\cmd` to PATH - it finds it in that anaconda shell).  So I was exploring us tuning up PATH for running git so it sees git-annex. But it somehow "was not in effect" - until I dug deep enough into this particular difference which makes little sense to me.

Now, I guess, I need to uninstall git, git-annex, and miniconda altogether and try from start with sticking git-annex into miniconda environment/installation to get into "common denominator" of how annex should be installed for datalad on windows ;-)  Let's see what that brings me

**Comment by mih** [comment]
After following https://github.com/datalad-handbook/book/pull/588 (no conda for git, git-annex) I see this:

```
>>> event_loop.run_until_complete(run_async_cmd(event_loop, 'git annex version --raw', NoCapture, None))
8.20200227-gebd0447dc{'stdout': '', 'stderr': '', 'code': 0}

>>> event_loop.run_until_complete(run_async_cmd(event_loop, ['git', 'annex', 'version', '--raw'], NoCapture, None))
8.20200227-gebd0447dc{'stdout': '', 'stderr': '', 'code': 0}
```

which I would hope to be universally true. I could not deduce a datalad version from your post, but I guess your `run_async_cmd` has

```py
    if isinstance(cmd, str):
        proc = loop.subprocess_shell(factory, cmd, **kwargs)
    else:
        proc = loop.subprocess_exec(factory, *cmd, **kwargs)
```

**Comment by yarikoptic** [comment]
It is master so yes, that code is there

I think I followed that Pr instructions more than you, since you choose msys for your git terminal which seems to effect also which tools are installed etc. I went with defaults.

The difference though is that I use our own git annex build (with magic) so may be that is related. Will check

**Comment by yarikoptic** [comment]
Oh and it might relate to the fact that I am in custom conda env, not they main one

Combinatorics on possible installation schemes on windows are a disaster. We need https://github.com/datalad/datalad/issues/5078

**Comment by yarikoptic** [comment]
Ok -- `conda remove git` resolved the "problem", although without obvious reason since AFAIK 

PATH was the same in both cases

```shell
(datalad) C:\Users\DataLad>python -c "from datalad.cmd import GitRunner as R; print([l for l in R().run(['env'])[0].splitlines() if l.startswith('PATH')])"
['PATH=/c/Program Files/Git/cmd:/c/Users/DataLad/miniconda3/envs/datalad:/mingw-w64/bin:/usr/bin:/bin:/c/Users/DataLad/miniconda3/envs/datalad/Scripts:/c/Users/DataLad/miniconda3/envs/datalad/bin:/c/Users/DataLad/miniconda3/condabin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/Git/cmd:/c/Users/DataLad/AppData/Local/Microsoft/WindowsApps:.', 'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC']

(datalad) C:\Users\DataLad>python -c "from datalad.cmd import GitRunner as R; print([l for l in R().run('env')[0].splitlines() if l.startswith('PATH')])"
['PATH=/c/Program Files/Git/cmd:/c/Users/DataLad/miniconda3/envs/datalad:/mingw-w64/bin:/usr/bin:/bin:/c/Users/DataLad/miniconda3/envs/datalad/Scripts:/c/Users/DataLad/miniconda3/envs/datalad/bin:/c/Users/DataLad/miniconda3/condabin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/Git/cmd:/c/Users/DataLad/AppData/Local/Microsoft/WindowsApps:.', 'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC']
```

and even `which` reported the same system wide git to be used (I believe -- can't find in terminals available atm), which was strange to me btw... So, if, without proper conda build of git-annex, we seems to be doomed to instruct people to uninstall `git` in their conda env, and so far I found no easy/quick way to check if we are not running conda's git (`git --version` reported was identical iirc too)

**Comment by yarikoptic** [comment]
and damn -- forgot to check if may be `git-annex` (not `git annex`) would have worked reliably with the proper PATH adjustment ... may be later

**Comment by yarikoptic** [comment]
or may be never... clearly installation was "suboptimal".  The problems caused by having `git` installed within conda are known, so not worth keeping around ATM AFAIK
