### ISSUE TITLE
unable to git clone /// on windows

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5097]
Tried in git bash and conda (conda installed `git`), getting the same
```
(base) C:\tmp>git clone http://datasets.datalad.org/.git
Cloning into 'datasets.datalad.org'...
Fetching objects: 11320, done.
error: invalid path 'con'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

anyone saw such one, has a clue on WTF, or why `con` is so special?

<details><summary>WTF within conda env</summary>

# WTF
## credentials 
  - keyring: 
    - active_backends: 
      - Windows WinVaultKeyring
      - Windows RegistryKeyring
      - EncryptedKeyring with not defined v.1.0 at C:\Users\DataLad\AppData\Local\Python Keyring\wincrypto_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at C:\Users\DataLad\AppData\Local\Python Keyring\keyring_pass.cfg
    - config_file: C:\Users\DataLad\.config\python_keyring\keyringrc.cfg
    - data_root: C:\Users\DataLad\AppData\Local\Python Keyring
## datalad 
  - full_version: 0.13.4.dev374-g635b6
  - version: 0.13.4.dev374
## dependencies 
  - annexremote: 1.2.1
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 19.00
  - cmd:annex: 8.20201008-g3be4731
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.29.1.windows.1
  - cmd:system-git: 2.29.1.windows.1
  - cmd:system-ssh: 7.1p2
  - exifread: 2.1.2
  - humanize: 3.1.0
  - iso8601: 0.1.13
  - keyring: 21.4.0
  - keyrings.alt: 3.1
  - msgpack: 1.0.0
  - mutagen: 1.41.1
  - requests: 2.24.0
  - tqdm: 4.51.0
  - wrapt: 1.12.1
## environment 
  - PATH: C:\Users\DataLad\miniconda3\envs\datalad-2;C:\Users\DataLad\miniconda3\envs\datalad-2\Library\mingw-w64\bin;C:\Users\DataLad\miniconda3\envs\datalad-2\Library\usr\bin;C:\Users\DataLad\miniconda3\envs\datalad-2\Library\bin;C:\Users\DataLad\miniconda3\envs\datalad-2\Scripts;C:\Users\DataLad\miniconda3\envs\datalad-2\bin;C:\Users\DataLad\miniconda3\condabin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Users\DataLad\AppData\Local\Microsoft\WindowsApps;.
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: mingw32 x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20201008-g3be4731
## location 
  - path: C:\tmp
  - type: directory
## metadata_extractors 
  - annex (datalad 0.13.4): 
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.13.4): 
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite (datalad 0.13.4): 
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.13.4): 
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.13.4): 
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.13.4): 
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage (datalad 0.13.4): 
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.13.4): 
    - distribution: datalad 0.13.4
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp (datalad 0.13.4): 
    - distribution: datalad 0.13.4
    - load_error: Exempi library not found. [exempi.py:_load_exempi:60]
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.8.6
## system 
  - distribution: msys_nt-10.0/2.5.0  10/10.0.18362/SP0/Multiprocessor Free
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp1252
  - max_path_length: 262
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.18362

</details>

**Comment by yarikoptic** [comment]
oh guacamole
```
(datalad-2) C:\tmp>mkdir con
The directory name is invalid.
```

**Comment by mih** [comment]
I don't see how you'd talk to serial devices and printers while being backwards compatible with 1980 and forward compatible with 5G networking and still fit in 640kb. Its not fucked up. It is pure magic that they get a mouse pointer to move with this beast.

**Comment by mih** [comment]
Given that this is caused by the *content* of a specific dataset, rather than anything that datalad does or has added to a dataset automatically, I think this is better move to https://github.com/datalad/datasets.datalad.org

In the context of the datalad code base, we should disable all tests that use `///` until it has been addressed.

**Comment by yarikoptic** [comment]
rright, issue is addressed.

On the larger note -- I would not mind having  `///` moved to some other hosting where multiple people could manage it than just myself.  But it is not just `///` -- it is subdatasets as well, so we would need probably to flatten them within https://github.com/datalad-datasets (or may be should we get some gitlab "directory" somewhere to avoid flattening etc) and also establish workflow for updates/management   etc.  But I do not see myself doing this ATM.  If someone interested to make this happen - let's do it in some other issue/PR etc
