### ISSUE TITLE
Nesting ProducerConsumers

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5103]
Possible use cases:
- parallelize subdatasets (which would be used as a producer) - while also parallelizing operation on them (not sure if worth it really, but could be a use case)
- #5102 - parallelize independently operation across multiple paths, while each path handling would also be parallelized

possible implementation 0 (safe one): disable any nested parallelization.  Define some "watch" class level variable, so any nested ProducerConsumer would just fall to `jobs=0` (pure serial) in the nested one.

possible implementation 1: RF to have `ProducerConsumer` to become/use some central/shared "engine", which would be 'multiplexing' all the tasks and feed individual `ProducerConsumer` with results only relevant to it.  But it might become too quickly too tricky to not cause a deadlock.

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
