### ISSUE TITLE
Issue warning when encountering windows-unfriendly filenames?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5123]
I think it could annoy and also be appreciated by some users if `save` (since the one introducing such names) would warn if names which cause windows indigestion, e.g. `con`, `prn` and others, would be alerted about.

**Comment by adswa** [comment]
FTR: I found a [list of filenames](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) that can't be used (regardless of whether they include an extension):
CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9.

However, I wonder if datalad should be dealing with this. 
For one, I actually found very few ways in which I could create such a file on Windows. I was only able to do it in a Git Bash, it fails silently in CMD and with an error message in a file explorer. So a Windows user would need to try hard to get such a file into existence.

Git also doesn't handle adding those files gracefully, either:

```
datalad@latitude-e7440 MINGW64 ~/ux-5123 (adjusted/master(unlocked))
$ git add COM1
error: open("COM1"): No such file or directory
error: unable to index file 'COM1'
fatal: adding files failed
```

And I suspect that if we start to do it, we would need to do it across operating systems - cloning a repo created on Linux with a file that's incompatible with Windows results in a failure to checkout head:
```
$ git clone git@github.com:adswa/ux-5123.git ux-5123clone
Cloning into 'ux-5123clone'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 19 (delta 2), reused 19 (delta 2), pack-reused 0
Receiving objects: 100% (19/19), done.
Resolving deltas: 100% (2/2), done.
error: invalid path 'NUL.txt'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
now
```

**Comment by yarikoptic** [comment]
yeap.  I think we should issue a warning whenever a "new" file is added/committed.  Ideally, if we had some "interactivity" we could even inquire.  Might even have some config parameter like `datalad.runtime.windows-forbidden-paths={ask-if-interactive-warn-otherwise,warn,nothing}`?

**Comment by adswa** [comment]
I'm still thinking about whether it should be us that emits a warning or failure or checks against forbidden names. As far as I know, WSL happily lets you create those files, even if the Windows part of your computer can't deal with them. The Git bash on Windows, too. Git-for-Windows, judging from https://github.com/git-for-windows/git/pull/2440, should apparently refuse to create a reserved file, and even files with illegal characters or those ending in a dot or space. But I can create those files just fine, and an attempt to ``git add`` them just fails in the typical "No such file or directory; unable to index file" way.... That commit is in Git itself it seems (https://github.com/git/git/commit/4dc42c6c1867a52e22f1f04a1a247b5a7538b8af), but only affecting stuff that runs on Windows (I think - its in ``compat/mingw.{c,h}``, which doesn't sound like its used elsewhere, but I'm just guessing).
Not even Windows itself emits a helpful message were I to create a file like this, it just responds with "No such file or directory". So I'm not sure whether we should warn about something that even Windows itself isn't warning about. On the other hand, stuff like the Rust package manager *does* warn when reserved files are included in a package: https://github.com/rust-lang/cargo/pull/8136/files...

Unrelated to the thoughts above, I have started to document that those names shouldn't be used in https://github.com/datalad-handbook/book/pull/794

**Comment by yarikoptic** [comment]
I would play on safe side and make it configurable (error, warning, none) so in https://github.com/datalad/datalad/pull/6291/files make it `datalad.save.windows-compat-check` (instead of bool `datalad.save.windows-compat-warning`) and default to `error`.  That check should run regardless of the platform.
