### ISSUE TITLE
Describe in CONTRIBUTING.md our env variables we use ATM useful for development

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#513]
`git grep os.environ` and see which one you find, and if you could figure out their purpose in life.  Document in CONT... file

**Comment by hanke** [comment]
FTR: `DATALAD_HELP2MAN` is no longer relevant. But there is now a `DATALAD_RUN_CMDLINE_TESTS` used as anticipated trigger for executing cmdline test scripts.

**Comment by debanjum** [comment]
fixed with #539
