### ISSUE TITLE
failed dl drop results in unhelpful git-annex hint

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#5135]
Its usually nice to not swallow errors or hints from git-annex, but in the case of ``datalad drop``, a failed ``git annex drop`` results in the misleading hint to "use --force":

```
$ datalad drop .easteregg.png
[WARNING] Running drop resulted in stderr output: git-annex: drop: 1 failed

[ERROR] unsafe; Could only verify the existence of 0 out of 1 necessary copies; (Use --force to override this check, or adjust numcopies.) [drop(C:\Users\datalad\testing\myanalysis\.easteregg.png)]
drop(error): C:\Users\datalad\testing\myanalysis\.easteregg.png (file) [unsafe; Could only verify the existence of 0 out of 1 necessary copies; (Use --force to override this check, or adjust numcopies.)]
```

Would someone read the error message and retry with ``--force``, datalad rightfully complains:

```
$ datalad drop .easteregg.png --force
[ERROR] unknown argument: --force
usage: datalad drop [-h] [-d DATASET] [-r] [-R LEVELS] [--nocheck]
                    [--if-dirty {fail,save-before,ignore}]
                    [PATH [PATH ...]]

```

It would be nice to be more user-friendly here. At the very least, DataLad's log or error message should include a hint about ``--nocheck``, so that users have a chance to find out what they need to do.

**Comment by kyleam** [comment]
> It would be nice to be more user-friendly here. At the very least, DataLad's log or error message should include a hint about `--nocheck`

I've gone with the very least in gh-5194, though of course any further tweaks are welcome.
