### ISSUE TITLE
FOI: msys sh on windows ignores real user home

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#5140]
Demo: clone via SSH, real windows user has a key setup, but

```
sh-4.3$ git clone git@github.com:psychoinformatics-de/paper-remodnav.git tmp2
Cloning into 'tmp2'...
Warning: Permanently added the RSA host key for IP address '140.82.121.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Running the same command in `cmd.exe` works.

The reason for that is that the msys shell "maintains a different HOME:

```
sh-4.3$ set |grep HOME
HOME=/home/datalad
HOMEDRIVE=C:
HOMEPATH='\Users\datalad'
```

which has nothing to do with the actual windows user home, hence also doesn't know about the SSH key.

This can be "fixed":

```
sh-4.3$ HOME=C:\\Users\\datalad git clone git@github.com:psychoinformatics-de/paper-
remodnav.git tmp2
Cloning into 'tmp2'...
remote: Enumerating objects: 238, done.
remote: Counting objects: 100% (238/238), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 1546 (delta 140), reused 175 (delta 90), pack-reused 1308
Receiving objects: 100% (1546/1546), 11.01 MiB | 5.22 MiB/s, done.
Resolving deltas: 100% (928/928), done.
```

This also explains the strange difference in the [behavior of `git config`](https://github.com/datalad/datalad/pull/5002#discussion_r520853020).

This is likely to affect any usage of real windows programs within an msys environment. Whether to HOME readjustment is a real fix is uncertain.

**Comment by mih** [comment]
Closing FOI after a long time.
