### ISSUE TITLE
Both master and maint hang while testing bleeding edge annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5145]
https://github.com/datalad/git-annex/runs/1383197387?check_suite_focus=true

There is also flood of

```
removeKey when not present:                      OK (0.37s)
    present False:                                   OK
channel 22: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
channel 22: open failed: connect failed: open failed
...
```
and it seems not happen for released version? https://github.com/datalad/git-annex/runs/1383197395?check_suite_focus=true

Unfortunately it all confounded with a steak of annex build failures, so we had no real testing run for a week or so, and move of git annex building/testing into a dedicated repository from datalad-extensions. So now we need to figure out what actually broke.

**Comment by kyleam** [comment]
I can trigger a stall locally with `datalad.distributed.tests.test_ria_basics.test_initremote_basic('datalad-test',)`.  In the process of bisecting... not sure if it will turn up anything.

**Comment by yarikoptic** [comment]
@kyleam would you be so kind to run with `datalad.runtime.stalled-external=abandon` (`DATALAD_RUNTIME_STALLED__EXTERNAL=abandon`) to see if that is not somehow the #5013

**Comment by kyleam** [comment]
> In the process of bisecting... not sure if it will turn up anything.

`test_initremote_basic('datalad-test',)` stalls for me (Debian buster) with git-annex's master branch 6911d27d4 and with the latest release (8.20201103).  It does not stall with the release before that (8.20201007).  I was hoping I could skip around build failures, but there are a bit too many to make that viable.

Just based on area, I suspected that 7245a9ed5 (Improve shutdown process for external special remotes and external backends, 2020-11-02) may be the culprit.  If I revert that commit, `test_initremote_basic('datalad-test',)` no longer stalls.  I'll try to reduce/rework that test into something to report to Joey.

<details>
<summary>diff</summary>

```diff
diff --git a/Annex/ExternalAddonProcess.hs b/Annex/ExternalAddonProcess.hs
index 8a6c6c32f..94983160a 100644
--- a/Annex/ExternalAddonProcess.hs
+++ b/Annex/ExternalAddonProcess.hs
@@ -55,20 +55,14 @@ startExternalAddonProcess basecmd pid = do
 	started cmd errrelayer pall@(Just hin, Just hout, Just herr, ph) = do
 		stderrelay <- async $ errrelayer herr
 		let shutdown forcestop = do
-			-- Close the process's stdin, to let it know there
-			-- are no more requests, so it will exit.
-			hClose hout
-			-- Close the procces's stdout as we're not going to
-			-- process any more output from it.
-			hClose hin
+			cancel stderrelay
 			if forcestop
 				then cleanupProcess pall
-				else void (waitForProcess ph)
-					`onException` cleanupProcess pall
-			-- This thread will exit after consuming any
-			-- remaining stderr from the process.
-			() <- wait stderrelay
-			hClose herr
+				else flip onException (cleanupProcess pall) $ do
+					hClose herr
+					hClose hin
+					hClose hout
+					void $ waitForProcess ph
 		return $ ExternalAddonProcess
 			{ externalSend = hin
 			, externalReceive = hout
```

</details>

**Comment by kyleam** [comment]
> would you be so kind to run with `datalad.runtime.stalled-external=abandon` (`DATALAD_RUNTIME_STALLED__EXTERNAL=abandon`) to see if that is not somehow the #5013

Why do you think it's that?  maint is hanging too, and that commit (02f6729294) and the series it reverts are only in master.

**Comment by yarikoptic** [comment]
AH, right -- indeed I forgot that it was master-specific (:relieved:) ... FWIW: that git-annex commit (or may be inc) [8.20201007-144-g7245a9ed5 AKA 8.20201103~15](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=7245a9ed5) is what resolved stalling git-annex/our external remotes on windows

**Comment by yarikoptic** [comment]
ok -- on why it doesn't stall for our released (0.13.5) version?
we carried over
```
      - name: Set up SSH target
        shell: bash
        # TODO: Drop the release condition once 0.13.2 is released.
        run: |
          if [ "${{ matrix.version }}" != "release" ]; then
            curl -fSsL \
              https://raw.githubusercontent.com/datalad/datalad/master/tools/ci/prep-travis-forssh.sh \
              | bash
            echo DATALAD_TESTS_SSH=1 >> "$GITHUB_ENV"
          fi
```
so we should disable that (but will not do that now since the stall)

what confuses me abit (although probably unrelated) is that on released one
```
2020-11-11T02:59:30.7124157Z datalad.distributed.tests.test_ria_basics.test_remote_layout('datalad-test',) ... SKIP: Run this test by setting DATALAD_TESTS_SSH
2020-11-11T02:59:34.4177312Z 
2020-11-11T02:59:34.4178953Z 7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
2020-11-11T02:59:34.4180166Z p7zip Version 16.02 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (306F2),ASM,AES-NI)
2020-11-11T02:59:34.4180843Z 
2020-11-11T02:59:34.4181263Z Scanning the drive:
2020-11-11T02:59:34.4181734Z 6 folders, 2 files, 16 bytes (1 KiB)
2020-11-11T02:59:34.4182511Z 
2020-11-11T02:59:34.4183680Z Creating archive: /tmp/datalad_temp__test_remote_layoutmibpyf78/21e/0c279-be9e-4a91-a410-ec6c8d82de44/archives/archive.7z
2020-11-11T02:59:34.4184454Z 
2020-11-11T02:59:34.4184823Z Items to compress: 8
2020-11-11T02:59:34.4185156Z 
2020-11-11T02:59:34.4185410Z 
2020-11-11T02:59:34.4185783Z Files read from disk: 2
2020-11-11T02:59:34.4186223Z Archive size: 297 bytes (1 KiB)
2020-11-11T02:59:34.4186743Z Everything is Ok
2020-11-11T02:59:36.2110331Z datalad.distributed.tests.test_ria_basics.test_remote_layout(None,) ... ok
```
so where that 7zip output dump comes from and what it spent 4 seconds on before it got to the next `test_remote_layout(None,) ` if that test was skipped?

**Comment by yarikoptic** [comment]
May be this patch (Joey crafted it while we were debugging) if you decide to troubleshoot on what it stalls could be of help
```diff
diff --git a/Annex/ExternalAddonProcess.hs b/Annex/ExternalAddonProcess.hs
index 94983160a..06ce4466e 100644
--- a/Annex/ExternalAddonProcess.hs
+++ b/Annex/ExternalAddonProcess.hs
@@ -11,6 +11,7 @@ import qualified Annex
 import Annex.Common
 import Git.Env
 import Utility.Shell
+import Utility.ThreadScheduler
 import Messages.Progress
 
 import Control.Concurrent.Async
@@ -55,14 +56,18 @@ startExternalAddonProcess basecmd pid = do
 	started cmd errrelayer pall@(Just hin, Just hout, Just herr, ph) = do
 		stderrelay <- async $ errrelayer herr
 		let shutdown forcestop = do
-			cancel stderrelay
+			let trace m a = do
+				debugM "shutdown" ("shutdown external trace: " ++ m ++ " in 10s")
+				threadDelaySeconds (Seconds 10)
+				a
+			trace "stopping stderr relay" $ cancel stderrelay
 			if forcestop
-				then cleanupProcess pall
-				else flip onException (cleanupProcess pall) $ do
-					hClose herr
-					hClose hin
-					hClose hout
-					void $ waitForProcess ph
+				then trace "called with forcestop, cleanupProcess" $ cleanupProcess pall
+				else flip onException (trace "caught exception! cleanupProcess" $ cleanupProcess pall) $ do
+					trace "closing stderr" $ hClose herr
+					trace "closing stdin" $ hClose hin
+					trace "closing stdout" $ hClose hout
+					trace "waiting for process" $ void $ waitForProcess ph
 		return $ ExternalAddonProcess
 			{ externalSend = hin
 			, externalReceive = hout
```

related whining of yours truly: https://git-annex.branchable.com/todo/--debug-level___40__and__47__or_-c_annex.debug-level__41___+_more_debug_information_from_git-annex/

**Comment by yarikoptic** [comment]
hm, our daily tests/builds still stall, e.g. ee
https://github.com/datalad/git-annex/runs/1404305092?check_suite_focus=true canceled 6 hours ago, whenever the fix in datalad was merged 3 days ago.... so there might be more to it?

**Comment by kyleam** [comment]
Yes, it seems so. The issue is resolved for me locally and I don't have any other ideas, but I'll add a comment to the related git-annex issue saying that it is still a stall on the CI builds.  (It seems likely to be related to the same commit, but of course who knows.)

**Comment by kyleam** [comment]
The demo script that I gave in the git-annex thread is now resolved on git-annex's end by d8b7f6721 (Merge branch 'ssh-hates-me', 2020-11-18).

Fingers crossed that those changes clear up the hanging of the CI builds.  Hard to say, I guess, given that the ORA changes in gh-5151 already resolved the hang in `test_initremote_basic` and in the demo script for me locally.

**Comment by kyleam** [comment]
> Fingers crossed that those changes clear up the hanging of the CI builds. Hard to say, I guess, given that the ORA changes in [gh-5151](https://github.com/datalad/datalad/pull/5151) already resolved the hang in `test_initremote_basic` and in the demo script for me locally.

Current one is still running, but I think it's good! (I can't really scroll up in that UI, but I'm not spotting the currently running test in the logs of the stalled jobs.)

https://github.com/datalad/git-annex/runs/1421906286?check_suite_focus=true

**Comment by yarikoptic** [comment]
It seems to be all green again, woohoo https://github.com/datalad/git-annex/actions/runs/371469598

Cheers and thanks!
