### ISSUE TITLE
addurls: `--mode offline` to populate solely using metadata

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5150]
If input data structure has all necessary information to "mint" a key (related question for git-annex is how to do that: https://git-annex.branchable.com/todo/calckey___91__--path__93___given_a_checksum_and_filename__63__/?updated) -- filename (for extension), size, and checksum (corresponding to the default/desired/some backend) we could populate proper (not `--fast` or `--relaxed`) annex'ed files without even talking to the server.
If there is needed for 'minting' interface in git-annex, the question left would be how to express that in `addurls` "API" (pretty much just instruct which field to take checksum from, safe-guard making it sure that looks correct given a backend - e.g. by length across MD5/SHA.../etc)

That would be a blessing for some use cases making it possible to really quickly (instead of multi-TB download and/or multi-thousand request to the server asking about size) to establish datalad datasets from provided metadata.

attn: @satra

**Comment by yarikoptic** [comment]
duplicating my sample 'recipe' from https://git-annex.branchable.com/todo/calckey___91__--path__93___given_a_checksum_and_filename__63__/#comment-1c12b3ed7e2c3f260266cc8bff54fc4a which should now be possible with git-annex
```shell
$> cat ./addurl-uberfast.sh
#!/bin/bash

export PS4='> '
set -x
set -eu
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"

md5=f92bbc617f8c8714a251f1f208af37a0
size=6605
filename=GLwDrawA.h
url=http://www.onerussian.com/tmp/$filename

git init
git annex init

echo MD5-s$size--$md5 $filename | \
 git-annex examinekey --batch --format='${key} ${objectpath}\n' --migrate-to-backend=MD5E | \
 while read key objectpath; do
    git-annex registerurl "$key" "$url"
    # examinekey does not know ${filename} in its format so such looping isn't exactly
    # possible easily in bash ATM
    ln -s "$objectpath" "$filename"
    git add "$filename"
    git annex get "$filename"
    git annex drop "$filename"
 done
```

used while hoping to try on multiple but then realized that no filename can be passed through there so just left as is.  For datalad batched processes wouldn't matter anyways.
So it still exposes a bit of annex internal structure of the key, but imho that is ok - we already rely on parsing it in few spots.  But it avoids hardcoding objectpath and extensions parsing done by git-annex -- so as close to is as we could get.

**Comment by satra** [comment]
nice work @yarikoptic

**Comment by yarikoptic** [comment]
ha ha -- thank you, but do you mean "nice work of pestering Joey"? ;) work is actually now to be done on datalad end .  FWIW, forgot to mention the state where it was implemented in git-annex so we could provide proper conditioning: [8.20201103-87-g7566aa6bc](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=7566aa6bc59093f94ab8af0d326ab71b0b9ed8f9)

**Comment by kyleam** [comment]
Implemented in gh-5184 (which I should have hooked up to automatically close this).
