### ISSUE TITLE
Why do we have `AnnexRepo.add_urls()`?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5153]
This is what it advertises:

```
    def add_urls(self, urls, options=None, backend=None, cwd=None,
                 jobs=None,
                 git_options=None, annex_options=None):
        """Downloads each url to its own file, which is added to the annex.

        Parameters
        ----------
        urls: list of str
        options: list, optional
            options to the annex command
        cwd: string, optional
            working directory from within which to invoke git-annex
        """
```

but we do have `add_url_to_file()` too:

```
    def add_url_to_file(self, file_, url, options=None, backend=None,
                        batch=False, git_options=None, annex_options=None,
                        unlink_existing=False):
        """Add file from url to the annex.

        Downloads `file` from `url` and add it to the annex.
        If annex knows `file` already,
        records that it can be downloaded from `url`.

        Note: Consider using the higher-level `download_url` instead.

        Parameters
        ----------
        file_: str
        url: str
        options: list
            options to the annex command
        batch: bool, optional
            initiate or continue with a batched run of annex addurl, instead of just
            calling a single git annex addurl command
        unlink_existing: bool, optional
            by default crashes if file already exists and is under git.
            With this flag set to True would first remove it.

        Returns
        -------
        dict
          In batch mode only ATM returns dict representation of json output returned
          by annex
        """
```

which seems to be a superset of `add_urls()`. Also `add_urls()` is not used outside the tests. ``add_url_to_file()` is used in:

- `add_archive_content`
- `download_url`
- `addurls`

Both functions score equal on advertising options that are not implemented and just lead to warnings.

I'd say we should get rid of `AnnexRepo.add_urls()`.

This was prompted by the discovery in #5152 that this is pretty much the last annex run function to go through a non-witless execution path.

**Comment by yarikoptic** [comment]
re "why": `add_url_to_file` requires to know the filename where url would be added. `add_urls` would rely on git-annex to "mint" the filename based on url or content-disposition.  `add_urls` is indeed an "older" interface, and we were never "satisfied" with filenames established by annex (would carry portion of a url etc), thus it was used only in the tests where we do not really care how the file is named.

so it feels that indeed it might make sense to deprecate `add_urls`, and we might not even need to extend `add_url_to_file` to support e.g. empty `file_` name (although we could by using e.g. `get_url_disposition_filename` we have)
