### ISSUE TITLE
FOI: asyncssh

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5158]
It was mentioned awhile back in https://github.com/datalad/datalad/issues/417 but time wasn't as ripe.
https://github.com/ronf/asyncssh : AsyncSSH is a Python package which provides an asynchronous client and server implementation of the SSHv2 protocol on top of the Python 3.6+ asyncio framework. 

IMHO worth keeping it mind although given that it is re-implementation (although seems to list all needed features), might have have some rough compatibility corners for our use cases.

**Comment by mih** [comment]
Tagging and closing this FOI
