### ISSUE TITLE
Refactor `run_annex*` API in AnnexRepo

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5161]
In the context of #5003 and specifically #5152 the git-annex execution helper in `AnnexRepo` are probably the last major connection of old `Runner` functionality with the rest of the code base. There are

- `_run_simple_annex_command()`
- `_run_annex_command_json()`

that both sit on top of `_run_annex_command()`. The latter already has some support with witless-execution, but in particular `_run_annex_command_json` does not use it, and implements a different progress handling than `AnnexJsonProtocol`.

There are numerous ways in which these three methods are called. It is unclear to me what an RF strategy would be or should be. However, from a design perspective it would be nice to have `call_annex()` to parallel `call_git()`.

It would also make sense to me to have `call_annex_items_()` to do the work of reporting JSON records. I do not see why the fact that JSON is used to receive information from git-annex should be reflected in the API.

So roughly speaking, I could see the following analogs:

- `GitRepo._call_git`: `AnnexRepo._run_annex_command` -> `AnnexRepo._call_annex`
- `GitRepo.call_git`: `AnnexRepo._run_simple_annex_command` -> `AnnexRepo.call_annex`
- `GitRepo.call_git_items_`: `AnnexRepo._run_annex_command_json` -> `AnnexRepo.call_annex_items_`

Here is a comprehensive list of `_run_annex_command()` usage in the code base of datalad proper. First the two main wrappers:

```
...(*args, **kwargs) [by _run_simple_annex_command]
...(command, files=files,  annex_options=annex_options, **kwargs)
```

where `args` and `kwargs` are exposed, hence could be anything, but contain legacy `log_*` options in any call via `_run_annex_command_json()`.

Remaining usage:

```
...('addurl', annex_options=options + urls, backend=backend, log_online=True,log_stderr=False, cwd=cwd)
...('adjust', annex_options=options, runner="gitwitless")
...('checkpresentkey',annex_options=list(annex_input),expect_fail=True,runner="gitwitless")
...('contentlocation',annex_options=[key],expect_fail=True,runner="gitwitless")
...('describe', annex_options=[name, description])
...('enableremote',annex_options=[name] + ensure_list(options),runner="gitwitless",env=env)
...('find', files=[f],annex_options=["--print0"], expect_fail=True,merge_annex_branches=False,runner="gitwitless")
...('find', annex_options=args, merge_annex_branches=False,  runner="gitwitless")
...('init', runner="gitwitless", protocol=AnnexInitOutput, annex_options=opts)
...('initremote', annex_options=[as_common_datasrc, 'type=git', 'location={}'.format(url), 'autoenable=true'])
...('initremote', annex_options=[name] + options, runner="gitwitless")
...('lookupkey', files=[files], expect_fail=True,runner="gitwitless")
...('metadata', '.', '-g', 'lastchanged')
...('migrate',annex_options=files,backend=backend,runner="gitwitless")
...('registerurl', annex_options=[dest_key, url])
...('reinject', annex_options=[str(tmploc), str_dest])
...('rmurl', files=[file_, url], runner="gitwitless")
...('setpresentkey', annex_options=[dest_key, dest_rid, '1'])
...('sync', annex_options=args, runner="gitwitless")
...('unannex', annex_options=options, files=files, runner="gitwitless")
...('untrust', annex_options=['here'])
```

and in the tests:
```
...('dead', annex_options=['here'])
...('direct' if enable_direct_mode else 'indirect', expect_stderr=True, runner="gitwitless")
`..("initremote", annex_options=["special", "type=git", "autoenable=true", "location=" + clone_url])
...('log')
...('unannex', annex_options=[op.join(lvl2relpath, 'file')])
...('upgrade')
```

Now same for `_run_simple_annex_command()`:

```
...("group", annex_options=[remote or '.'])
...("groupwanted", annex_options=[remote or '.'])
...("required", annex_options=[remote or '.'])
...("wanted", annex_options=[remote or '.'])
```

and for `_run_annex_command_json()`:

```
...('add',opts=options,files=files,backend=backend,expect_fail=True,jobs=jobs,expected_entries=expected_additions,expect_stderr=True)
...('add',opts=options,files=list(files.keys()),backend=None,expect_fail=True,jobs=None,expected_entries=expected_additions,expect_stderr=True)
...('addurl',opts=options + [files_opt] + [url],progress=True,expected_entries={file_: None},**kwargs)
...('copy',opts=annex_options,files=files,jobs=jobs,expected_entries=expected_copys,progress=True)
...('drop',opts=options + [k],jobs=jobs)
...('drop',opts=options,files=files,jobs=jobs)
...('dropkey', opts=options, files=keys, expect_stderr=True)
...('find', opts=expr, files=files, merge_annex_branches=merge_annex_branches)
...('fromkey',opts=[dest_key, str_dest, '--force'], expect_fail=True,)
...('fsck',iles=paths,git_options=git_options,opts=args,expect_stderr=True,expect_fail=True,)
...('get',jobs=jobs,expected_entries=expected_downloads,progress=True,**kwargs)
...('info', opts=options, files=files, merge_annex_branches=False)
...('info', opts=options, merge_annex_branches=merge_annex_branches)
...('ls-files', opts=opts, files=files)
...('ls-tree', opts=opts, files=files)
...('metadata', opts=['--json'], files=files)
...('metadata',args, files=files)
...("unlock", files=files)
...('whereis', **kwargs)
```

and in tests:

```
...('add', files='gl\\orious BS')
...('add', ['non-existing'], expect_fail=True)
...('add', ['non-existing'], expect_fail=False)
...("info",log_stdout=log_stdout,log_stderr=log_stderr,runner="gitwitless")
```

**Comment by bpoldrack** [comment]
Makes sense to me. While at it, we should make it clear how to run annex with `--debug`. This used to be implicit by log level <= 8, but it might be better to have a dedicated config.

**Comment by yarikoptic** [comment]
on one hand I did "enjoy" having a single option to regiment adding `--debug` but indeed, in many cases I wanted it explicit eg to have it while the rest is at INFO level to not overfill the screen... Also note that its usefulness is IIRC "dependent" on having `DATALAD_LOG_OUTPUTS` set (since if not -- no --debug output would be logged) but that one in turn is also log level dependent IIRC. So, yet not sure 100% if decoupling into a separate config would provide any advantage besides many be minimizing logging verbosity at `<=8` whenever `--debug` output from annex is not really of interest.

**Comment by mih** [comment]
Also see the list of annex-call that do not go through these helpers: https://github.com/datalad/datalad/issues/4406#issuecomment-728288468
