### ISSUE TITLE
ORA remote config contains unused `archive-id`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5166]
```
% git cat-file -p git-annex:remote.log
2c9f30a6-a85e-4e45-ab7b-92c8fdfbb801 archive-id=e1694650-7cee-4d7f-a2f7-18825230a090 autoenable=true encryption=none externaltype=ora name=mike2-storage type=external url=ria+file:///tmp/bummer2 timestamp=1605595341.140622368s
```

Its presence is tested for and operation is refused if it is missing, but it seems to be unused otherwise.

**Comment by bpoldrack** [comment]
Looking into it, I think we probably want to keep it. The name is an unfortunate legacy - it really is the dataset's ID, which is needed to resolve the actual locations from the `ria+` URL to the store. Now, we can always read that from `.datalad/config`. But: Not associating a particular special remote with a particular dataset would mean, that the same special remote with the same uuid would be valid across datasets (with the potential to mess up availability info). An alternative would be to not store the RIA URL to the store, but to the dataset in store (appending `#ID`). Switching to this model would invalidate existing datasets.
So, we are either stuck with it or go for a transition that requires to update existing datasets or just make it easier for users to deal with it (if that's the point really) by not requiring it as an input to `git-annex-initremote`/`git-annex-enableremote` and auto-create that config during INITREMOTE instead.

What do you think, @mih?

**Comment by mih** [comment]
I cannot follow the part with

> Not associating a particular special remote with a particular dataset would mean, that the same special remote with the same uuid would be valid across datasets (with the potential to mess up availability info)

This UUID is random (I double-checked that `create-sibling-ria` does not change that). Special remote setups are not shared or transferable across repositories.

That being said, at present this information is used in the code. Hence the point of the issue is invalid. Closing.
