### ISSUE TITLE
Remove from annex

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#517]
I just unified the behaviour of `remove` in `AnnexRepo` and `GitRepo` class. Currently this is just a `git rm` in both cases (just an override to respect direct mode in case of `AnnexRepo`). I wonder whether this is what we want. For the "opposing" operation `add`, we execute an `annex add`or a `git add` respectively. Shouldn't we therefore have a `remove`, that in the same way distinguishes between `git annex unannex` and `git rm` as the complementary operation to `add`? What do you think, @yarikoptic @hanke ?

**Comment by mih** [comment]
Hard to say. I guess once we have a functional uninstall at the toplevel API, things should become clearer.

**Comment by mih** [comment]
In #796 I am only using `drop` (if there is an annex) and remove. The use case of `unannex` (i.e. undo of `annex add` is not considered in that implementation of `uninstall`. While I find it logical to have that be possible, I consider it secondary, given that we decided to focus on clean repositories by default. In other words, the next `save` would automatically re-annex the result of any `unannex`.

**Comment by mih** [comment]
Nobody seems to care.
