### ISSUE TITLE
MacOS: unable to import unlock from datalad.api

### ISSUE THREAD

**Issue by jadecci** [datalad/datalad#5171]
#### What is the problem?

The following error was raised when trying to import the `unlock` function from `datalad.api`:

```python
>>> from datalad.api import unnlock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/datalad/api.py", line 92, in <module>
    _generate_extension_api()
  File "/usr/local/lib/python3.8/site-packages/datalad/api.py", line 81, in _generate_extension_api
    mod = import_module(intfspec[0])
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/site-packages/ria_remote/install.py", line 39, in <module>
    class Install(Clone):
  File "/usr/local/lib/python3.8/site-packages/datalad/interface/base.py", line 533, in build_doc
    update_docstring_with_parameters(
  File "/usr/local/lib/python3.8/site-packages/datalad/interface/base.py", line 374, in update_docstring_with_parameters
    raise ValueError("function has argument '%s' not described as a parameter" % arg)
ValueError: function has argument 'alt_sources' not described as a parameter
```

#### What steps will reproduce the problem?

Simply runnning `from datalad.api run import` will generate the error.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

The DataLad version is 0.13.0. I was not able to run `datalad wtf` either. The following error was produced

```bash
[ERROR  ] function has argument 'alt_sources' not described as a parameter [base.py:update_docstring_with_parameters:374] (ValueError)
```

#### Is there anything else that would be useful to know in this context?

I have recently updated the MacOS to BigSur, which has broken something else for me too. As I don't recall having this issue previously, I suspect the system update might have caused the problem.

**Comment by mih** [comment]
This looks like the installation is/was broken, and is currently a mix of more than one version. I would suggest to reinstall datalad the same way you had installed it before. Does that work?

**Comment by jadecci** [comment]
I tried `python3 -m pip uninstall datalad` followed by `python3 -m pip install --user datalad`, but still getting the same error.

**Comment by kyleam** [comment]
> `python3 -m pip uninstall datalad` followed by `python3 -m pip install --user datalad`, but still getting the same error.

@jadecci I think that probably means your uninstall isn't removing the stale files.  Your traceback looks like a mix between `/usr/local/lib/python3.8/` and `/usr/local/Cellar/...`.  I don't use macOS, but isn't `/usr/local/Cellar/...` a homebrew-related path?

**Comment by kyleam** [comment]
@jadecci, were you able to resolve your installation issues?

**Comment by mih** [comment]
I will close this issue now due to the absent response. But feel free to reopen with new information, should the problem persist.
