### ISSUE TITLE
datalad clone with singularity does not honour working directory

### ISSUE THREAD

**Issue by gdevenyi** [datalad/datalad#5173]
#### What is the problem?
datalad clone with singularity does not honour working directory

#### What steps will reproduce the problem?
Create and navigate to a directory, use singularity container to perform `datalad clone`

Example
```
$ mkdir /scratch/savepath
$ cd /scratch/savepath
$ singularity pull shub://datalad/datalad:fullmaster
$ ./datalad-datalad-master-fullmaster.simg clone git@host:user/datasetname
Clone attempt:   0%|                                                                         | 0.00/1.00 [00:00<?, ? Candidate locations/s]
install(ok): /home/cic/devgab/datasetname (dataset)
```

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
```
./datalad-datalad-master-fullmaster.simg --version
datalad 0.13.0rc2
```

**Comment by yarikoptic** [comment]
I feel that we should just kill those singularity images.  As singularity is linux only, it means that it must be possible to install datalad "properly" via conda: see/follow http://handbook.datalad.org/en/latest/intro/installation.html?highlight=HPC%20conda#linux-machines-with-no-root-access-e-g-hpc-systems or you could use https://github.com/datalad/datalad/blob/master/datalad/install.py script to instruct to install git-annex in a (new) conda environment.  We are yet to make it install datalad as well.

**Comment by yarikoptic** [comment]
I will close this issue, let us know if anything else to be done
