### ISSUE TITLE
install.py: implement more flexible/modular but also easy on user parsing schema

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5181]
initial `install.py` (and shell prototype it was based on) was targeting 1 component (git-annex) and then miniconda was added as an individual component but overall parsing was not yet refactored, and now looks like

```
schema:
  Type of git-annex installation (default "conda-forge")

  {autobuild,brew,conda-forge,conda-forge-last,datalad-extensions-build,deb-url,neurodebian,neurodebian-devel,snapshot,miniconda}
```

It think we are at a good point to RF it along the lines proposed in https://github.com/datalad/datalad/issues/5078 (and somewhat inspired by neurodocker , check it out)

``` [--options-applied-to-all] COMPONENT1[=version] [--options] COMPONENT2[=version] [--options] ...```

or more specifically

``` [--options-applied-to-all] COMPONENT1[=version] [--options] [--schema X] [--schemaoptions] COMPONENT2[=version]...```

where current target components should be (adding `venv`, I think it is time -- could come handy for testing PRs etc)

- miniconda
- venv
- git-annex
- datalad

among `--options`, both datalad and git-annex should get `--schema` option (thus I listed it explicitly above), which would be "auto" by default, and otherwise allow for following "schemas":

- datalad
  - apt
  - conda
  - deb-url
  - neurodebian
  - neurodebian-devel
  - pip
- git-annex
  - apt
  - autobuild
  - brew
  - conda
  - ~~conda-last  # or let's drop it as not used ATM anyways and not to be sourced?~~
  - datalad/annex  # from datalad-extensions-build since we moved
  - deb-url
  - neurodebian
  - neurodebian-devel
  - snapshot

some of those (conda-forge, pip, apt) should use specific `[=VERSION]` if specified, the others should raise some exception.

we can decouple installation of git-annex from installation of miniconda, i.e. if it is `install.py git-annex --schema conda-forge` and prior `miniconda` component which would install miniconda and make `conda` available, and there is no `conda` in the PATH  -- it is ok to just exit with an exception if conda is not available.  Ideally it should be a dedicated common exception like `IncompatibleEnvrionmentError(ValueError) ` (similar exception for e.g trying neurodebian install on OSX etc). 

Installation of a component could lead to 
- tune up of PATH (or other env vars) so whenever we get to the next one, it might be operating in the environment reflecting prior actions. Implementation -- may be there could/should be a persistent shell session or otherwise could use approach I coded in reproman (I can point to if we see it needed), or do some other way (composite command which would first `source` some env vars file produced by `install` to accumulate those chages)
- some components (miniconda ATM, later may be `venv`) would prepend to the "auto_schema" internal list (which is initiated with "native")

as a result, after `miniconda` component installation, `PATH` in subsequent invocations should have corresponding conda environment in there, and `auto_schema` should become `['conda', 'native']`

if `schema == "auto"` when considering a COMPONENT, it should consults auto_schema in that order.  If 'native' -- check for the first known to that component order from user to system level conda/apt/neurodebian/brew/standalone and for which there is no `IncompatibleEnvironmentError` raised.

`conda` schema should probably just pass all `--schemaoptions`  (all subsequent with start with `-` until it hits something without `-`) to underlying `conda install -c conda-forge ... COMPONENT` call, so I could just add `--only-deps`, `--update-all,` or alike.

An additional COMPONENT (was thinking to make it an option for miniconda, but would make it not flexible):
- `conda-env` with `-n|--name NAME` and `-p|--package_spec SPEC` so it would create a conda environment as well (providing package_specs to `conda create -n NAME` ), and adjust env etc, so all subsequent installations would just be done in that environment (i do not see when we might need git-annex and datalad installed in different, so not worth per package), or could be a separate component.

So a few ultimate examples
- `install.py datalad` (or git-annex) on my laptop whenever I am not in any venv conda should just end up running `sudo apt-get install datalad` (or git-annex), and it would install it in `conda` if I am in conda, or using `brew` if I am on OSX with brew, 

- `install.py miniconda --path-miniconda /tmp/mini conda-env -n datalad-dev datalad` - would install datalad (and thus git-annex and what not) in a new miniconda within datalad-dev environment

- `install.py miniconda -p python=3.9 datalad --only-dep` - would install datalad dependencies only (and thus git-annex and what not) in a new miniconda with python 3.9 for which it would tell me the PATH, so I could enter that env and do `pip install -e .` on the code base

- `install.py venv datalad=0.13.2` - create a new temp venv with pip installed old datalad

WDYT, sounds sensible or too complicated? ;-)

**Comment by jwodder** [comment]
This seems doable, though it'll take a few days or so of work.

The first issue I see is with implementing the custom versioned subcommand parsing.  I can see a way to get the basics working using argparse (though the `--help` outputs might be suboptimal) through what should be an appropriate use of `argparse.REMAINDER`, which was [so intractably buggy](https://bugs.python.org/issue17050) that it was removed from the docs in Python 3.9.  However, passing arbitrary unknown options through to `conda install` as described won't work (unless we hardcode/duplicate all known options) for the following reasons:

* The bug in `argparse.REMAINDER` means it can't handle argument sequences that start with an option-like string.
* Trying to implement this via an `--extra-opts "--opt1 --opt2"` option would be unreliable, as [a separate ill-conceived heuristic in argparse](https://bugs.python.org/issue9334) causes it to reject options whose arguments look like other options.
* If any of the `conda install` options take arguments, there would be situations where the parser can't tell whether an argument is a conda option argument or the name of the next component.

One way that would work would be to require the conda install options to come after all of the conda component's "real" options and for the install options to be preceded by either `--` or some option like `--extra-opts` (Note to self: This one is implemented via `parser.add_argument("--extra-opts", nargs=argparse.REMAINDER)`) — but this would still have to deal with the option argument ambiguity issue, unless we go with hardcoding all `conda install` options.

---

I don't like the idea of one invocation of `install.py` modifying the PATH in such a way that the modifications are available to another invocation run immediately afterwards in the same shell.

---

> if schema == "auto" when considering a COMPONENT, it should consults auto_schema in that order. If 'native' -- check for the first known to that component order from user to system level conda/apt/neurodebian/brew/standalone and for which there is no IncompatibleEnvironmentError raised.

I'm not entirely sure what you're trying to say here.  Do you mean that "native" should try all schemata in a certain order and use the first one that works?

**Comment by yarikoptic** [comment]
> I don't like the idea of one invocation of `install.py` modifying the PATH in such a way that the modifications are available to another invocation run immediately afterwards in the same shell.

why? isn't it pretty much natively following how we would in the shell (install miniconda, enter its env, create an env, activate it, etc)

> > if schema == "auto" when considering a COMPONENT, it should consults auto_schema in that order. If 'native' -- check for the first known to that component order from user to system level conda/apt/neurodebian/brew/standalone and for which there is no IncompatibleEnvironmentError raised.
> 
> I'm not entirely sure what you're trying to say here. Do you mean that "native" should try all schemata in a certain order and use the first one that works?

pretty much, as appropriate to the underlying OS (e.g. no need to try brew on linux, or neurodebian on windows).  Again, the ultimate idea is to loosely mimic what is done by a human operator:  if miniconda is instructed to be installed prior to git-annex, we would assume that `conda` becomes the preferable schema for subsequent installations (since otherwise -- why was it installed?).  If there were no conda installed, but it is available -- also makes sense to try it first, and then continue with "OS-specific" installers, and end up with "ad-hoc" standalone as the measure of the last resort.

> ...  through what should be an appropriate use of argparse.REMAINDER, which was so intractably buggy that it was removed from the docs in Python 3.9

thanks for the info, filed #5192 and can proudly state that or "core" cmdline parsing code (not sure if there is a live human being which can understand it without significant time involvement ATM) in https://github.com/datalad/datalad/blob/HEAD/datalad/cmdline/main.py isn't relying on it!  It is so much better -- it is using `._parse_known_args` (well, in addition to `parse_known_args` in higher level spot) ;-)

But on that thought -- wouldn't it be possible to first establish main parser which would just be aware of the top level options and only one positional argument (the component) which it would parse, establish the corresponding subparser and feed the rest to its `.parse_known_args`, and so on to the next one on the remainder etc.  This way no argparse.REMAINDER should be needed.  Then for `conda-create` (formerly I named it `conda-env` but why not to make it more obvious) we just take the remaining args as is (all the way until the end of the end of the list or until we hit `--`) and run `['conda', 'create'] + args`?  so in other words there would be no parser (besides "consume till the `--` or the end") pretty much for `conda-create`.

**Comment by jwodder** [comment]
> why? isn't it pretty much natively following how we would in the shell (install miniconda, enter its env, create an env, activate it, etc)

Activating an environment (assuming it's like virtualenv) is done through sourcing a shell script or running a shell function, which are some of the few command-like things that should ever modify the shell's environment.  I'm not sure how exactly you're proposing our script modify the calling shell's state, but I'd be wary of violating the expectations people have about subprocesses' environments not affecting parents' environments.

> But on that thought -- wouldn't it be possible to first establish main parser which would just be aware of the top level options and only one positional argument (the component) which it would parse, establish the corresponding subparser and feed the rest to its .parse_known_args, and so on to the next one on the remainder etc. This way no argparse.REMAINDER should be needed.

In order to "feed the rest" to the next parser, you have to capture all the options after the positional argument; that's where `argparse.REMAINDER` is required.  Using a regular argument with `nargs='*'` won't prevent argparse from trying to treat options after the positional arguments as options to the main parser, resulting in errors.  I vaguely recall I found a similar problem with using `parse_known_args()` instead, but the only issue with that approach I can determine at the moment is that it would prevent two different parsers from having separate options with the same name (which I suppose is a dealbreaker, if we want multiple components to have their own `--schema` option).

**Comment by yarikoptic** [comment]
> > why? isn't it pretty much natively following how we would in the shell (install miniconda, enter its env, create an env, activate it, etc)
> 
> Activating an environment (assuming it's like virtualenv) is done through sourcing a shell script or running a shell function, which are some of the few command-like things that should ever modify the shell's environment. I'm not sure how exactly you're proposing our script modify the calling shell's state, but I'd be wary of violating the expectations people have about subprocesses' environments not affecting parents' environments.

(let's forget about windows for now since there I am not entire sure what should be happening unless there is `sh`, as e.g. under git bash) just prepend e.g. `source {conda_path}/etc/profile.d/conda.sh; ` (and any number of them as needed, could be directly modifying `PATH` where applicable) to the target command string you are to execute next.  No parent environment would be harmed

**Comment by yarikoptic** [comment]
> > But on that thought -- wouldn't it be possible to first establish main parser which would just be aware of the top level options and only one positional argument (the component) which it would parse, establish the corresponding subparser and feed the rest to its .parse_known_args, and so on to the next one on the remainder etc. This way no argparse.REMAINDER should be needed.
> 
> In order to "feed the rest" to the next parser, you have to capture all the options after the positional argument; that's where `argparse.REMAINDER` is required. Using a regular argument with `nargs='*'` won't prevent argparse from trying to treat options after the positional arguments as options to the main parser, resulting in errors. I vaguely recall I found a similar problem with using `parse_known_args()` instead, but the only issue with that approach I can determine at the moment is that it would prevent two different parsers from having separate options with the same name (which I suppose is a dealbreaker, if we want multiple components to have their own `--schema` option).

toyed abit with some ideas (without resoring to REMAINDER) but insofar `argparser` assumptions are too ... restrictive.  There are new (since 3.7) `parse_known_intermixed_args` and `parse_intermixed_args` but they do not really make it easier.  What do you suggest @jwodder we should do? ;)

**Comment by jwodder** [comment]
@yarikoptic I'm fine with using `REMAINDER`, but if you're not, we'd have to fall back to either [optparse](https://docs.python.org/3/library/optparse.html) or [getopt](https://docs.python.org/3/library/getopt.html) for option-parsing.

**Comment by yarikoptic** [comment]
I am fine with REMAINDER, even if no longer documented, it is used internally and we still use it, etc -- so as long as it does what we need, I think it is ok to use it. `optparse` has been deprecated for too long. I have no objections against getopt if you feel that it would provide a more sustainable (albeit a bit more coding now) solution

**Comment by jwodder** [comment]
@yarikoptic To start, I am going to need a list of the following desired features:

* all of the global options
* all of the components
* all of the per-component options
* all of the schemata allowed for each component
* all of the schema-specific options

**Comment by yarikoptic** [comment]
this grew too long, so starting afresh in #5240
