### ISSUE TITLE
Can't find corresponding branch after fmriPrep Preprocessing

### ISSUE THREAD

**Issue by jkroell** [datalad/datalad#5183]
I preprocessed files from a subject, similar as in (http://handbook.datalad.org/en/latest/beyond_basics/101-171-enki.html). After finishing, I wanted to merge the branch but couldn't find it. 

Previously it worked with the same set-up for several subjects, I just had to repeat this single sub because fmriPrep crashed on this one before. This time, though, the log file suggests that fmriprep ran successfully. "Git branch" lists all previous branches, but not the one I am looking for.

**Comment by kyleam** [comment]
I'm not very familiar with the setup in that section, but, looking through the `code/fmriprep_participant_job` script, I'm trying to guess what spot seems like the most likely to be the reason for not seeing a branch for that job ID in the original dataset.  Assuming your variant of the script also runs with `set -e`, the job-id-named branch should have been checked out if it got through a successful fmriPrep run, so perhaps the most likely spot to have failed is the `datalad push` call to `origin`.

**Comment by adswa** [comment]
We resolved the issue yesterday via zoom call (hopefully). There indeed was no branch because a failure prior to push prevented the branch from being pushed. I'm closing this, but please reopen or get in touch if it fails again.
