### ISSUE TITLE
FOI: buggy argparse.REMAINDER is no longer documented in 3.9

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5192]
alerted to the https://bugs.python.org/issue17050 by @jwodder in https://github.com/datalad/datalad/issues/5181#issuecomment-732344347 and it seems we do use it in a few spots:
```
$> git describe
0.13.5-504-g0b8b8ad8c

$> git grep REMAINDER
datalad/core/local/create.py:    REMAINDER,
datalad/core/local/create.py:            nargs=REMAINDER,
datalad/core/local/run.py:from argparse import REMAINDER
datalad/core/local/run.py:            nargs=REMAINDER,
datalad/distributed/export_archive_ora.py:from argparse import REMAINDER
datalad/distributed/export_archive_ora.py:            nargs=REMAINDER,
datalad/interface/run_procedure.py:from argparse import REMAINDER
datalad/interface/run_procedure.py:            nargs=REMAINDER,
```
so might need some RFing eventually

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon. 

FTR: 4 spot remain at this point:

```
datalad/core/local/create.py
datalad/core/local/run.py
datalad/distributed/export_archive_ora.py
datalad/interface/run_procedure.py
```
