### ISSUE TITLE
Google Cloud Source Support

### ISSUE THREAD

**Issue by konkodi210** [datalad/datalad#5198]
#### Does the datalad support creating sibling with [Google Cloud Source](https://cloud.google.com/source-repositories) ?

If it is not supported as of now, I am happy to contribute. Please let me know if any work done on this.

**Comment by yarikoptic** [comment]
rclone seems to support it https://rclone.org/googlecloudstorage/ so to the extent of support by rclone special remote (no exports of the tree), this would be a solution for now.  See http://handbook.datalad.org/en/latest/basics/101-138-sharethirdparty.html?highlight=rclone#from-the-perspective-of-whom-you-share-your-dataset-with for more on how to setup rclone special remote
