### ISSUE TITLE
Not able to create Google Cloud Storage remote for the subdatasets.

### ISSUE THREAD

**Issue by xarvshar** [datalad/datalad#5224]
Hi,

I am trying to create a GCS remote to my current nested dataset. 

I am using S3 API's to do so. The command that I execute is mentioned below 

git annex initremote gcsremote type=S3 encryption=none host=storage.googleapis.com storageclass=STANDARD  bucket=<My-Bucket-Name>

This command Only creates a datalad siblings to the root datalad dataset(Mainly it creates a GCS sibling to the dataset in which is got executed). When I try to execute the same command with the same bucket (or with a fileprefix flag) it fails to create siblings with the same bucket. 

Is there a way to recurse the creation of the GCS remote to its nested sub-datasets.

**Comment by kyleam** [comment]
I've never used google cloud storage, so sorry if I'm missing something obvious but...

> git annex initremote gcsremote type=S3 encryption=none host=storage.googleapis.com storageclass=STANDARD bucket=
> [...]
> When I try to execute the same command with the same bucket (or with a fileprefix flag) it fails to create siblings with the same bucket.

... what's the actual failure here?  Can you show the output?

If the `git annex initremote` call worked in subdatasets, then you should be able to use `git submodule foreach ...`.

**Comment by xarvshar** [comment]
Hi Kyle,

Thanks for your fast response.

Here is my nested datalad dataset structure.

![image](https://user-images.githubusercontent.com/16451564/101728840-1cc83b80-3add-11eb-9b41-46d53af7863f.png)

Once I execute the git annex initremote command on the root folder. I can see a datalad sibling created for the root dataset 

![image](https://user-images.githubusercontent.com/16451564/101729134-aaa42680-3add-11eb-9a1c-f615230d7c6c.png)


I want the remote for the subdataset to have, but once I execute the above command in the subdataset directory I get the below error

**initremote gcsremote (checking bucket...) (creating bucket in US...) 
git-annex: S3Error {s3StatusCode = Status {statusCode = 403, statusMessage = "Forbidden"}, s3ErrorCode = "AccessDenied", s3ErrorMessage = "Access denied.", s3ErrorResource = Nothing, s3ErrorHostId = Nothing, s3ErrorAccessKeyId = Nothing, s3ErrorStringToSign = Nothing, s3ErrorBucket = Nothing, s3ErrorEndpointRaw = Nothing, s3ErrorEndpoint = Nothing}
failed
git-annex: initremote: 1 failed**

The reason why I am doing this is when I do a publish command on the root folder to a GCS it also pushes the subdatsets data to the same GCS bucket which is not happening currently. 

Please let me know if you require any additional information.

**Comment by kyleam** [comment]
You mentioned in the initial post that you tried with `fileprefix` (presumably a unique one for each dataset?).  Reading through <https://git-annex.branchable.com/special_remotes/S3/> and glancing at the use of `getFilePrefix` in Remote/S3.hs, my impression is that using a different `fileprefix` for disjoint repos should allow them to use the same bucket, but I don't have any experience with doing that.

You may get more clues about what's going on by running `initremote` with `--debug` (be careful about posting that output here though, because it can include sensitive information).  If you can't get `initremote` working with different `fileprefix` values, it might be worth reporting the problem on the git-annex bug tracker.

**Comment by xarvshar** [comment]
Yeah, It is actually not working I will report it on the git-annex bug tracker.

What I want to understand from you is, In can of the nested dataset if I initialize a remote on GCS(or any storage service) for the root dataset is there a way(like -r flag or --recursion flag )which automatically creates the remote to its sub-datasets.

The reason behind this question is once if install/clone the published data from a GitLab/GitHub, I want to use datalad get command on the sub-datasets to retrieve the contents from these storage services(like GCS).

I hope I am able to explain my query.

**Comment by adswa** [comment]
> What I want to understand from you is, In can of the nested dataset if I initialize a remote on GCS(or any storage service) for the root dataset is there a way(like -r flag or --recursion flag )which automatically creates the remote to its sub-datasets.

As far as I know, there is no DataLad command that can do this. But as Kyle mentioned in his first comments, you could pass the ``git annex initremote`` (once it works) command to each subdataset by using Git's ``git submodule foreach`` command: https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-foreach--recursiveltcommandgt

**Comment by xarvshar** [comment]
Okay, I tried the **git submodule foreach** command but again it only allows to create a sibling to one dataset. Let me raise it as a bug to git-annex bug tracker.

Thanks for your fast responses :))
