### ISSUE TITLE
Publish the softlink to one remote and data to another remote

### ISSUE THREAD

**Issue by xarvshar** [datalad/datalad#5225]
I have created two remotes for my datalad dataset. While creating the second remote I am mentioning a flag --publish-depends and mentioning the first remote name.

When I try to publish the data to my second remote, it actually pushes only the softlink data to the second remote and actual data to my first remote. Why?

**Comment by kyleam** [comment]
I think it will be tricky to say without more details (e.g., output from the commands or a reproducer script).  My guess is that git-annex is detecting that the second remote doesn't support plain git-annex operations (this is the case for github remotes).  The demo below sets `annex-ignore=true` explicitly to show that behavior.  Compare the `git annex whereis` results with and without the `git config remote.r-wo-annex.annex-ignore true` line.

<details>
<summary>demo</summary>

```sh
#!/bin/sh

set -eu

cd "$(mktemp -d "${TMPDIR:-/tmp}"/-XXXXXXX)"

git init --bare noannex.git
datalad create -D local loc
(
    cd loc

    datalad create-sibling -s r-with-annex ../with-annex
    datalad publish --to r-with-annex

    datalad siblings add -s r-wo-annex --publish-depends r-with-annex \
            --url ../noannex.git
    git config remote.r-wo-annex.annex-ignore true
    datalad publish --to r-wo-annex

    echo foo >foo
    datalad save
    datalad publish --transfer-data=all --to=r-wo-annex

    git annex whereis
)
```

</details>

**Comment by xarvshar** [comment]
Yes that is true. My first remote is Google Cloud Storage, whereas my second remote is gitlab (which does not support git annex operations). When I run the **git annex whereis** it tells the git annex data is present at local as well as on GCS bucket. 

My question is I have not explicitly defining this, Where it is configured? Is this a normal Functionality? If I Publish the other way around (i.e. If i create gitlab remote first and GCS remote as second with the --publish-depends flag on gitlab remote) Will it work the same way (that is all the soft link to gitlab remote and git annex object on GCS) or it will move everything to GCS bucket (that is .datalad, .gitmodules, .gitattributes folder and files)?

**Comment by adswa** [comment]
>  Is this a normal Functionality? 

Yes. But it doesn't have anything to do with the order in which you create siblings or publication dependencies, but rather with the capabilities (and configurations) of the sibling.
From what you describe you have a sibling without annex capabilities on a repository hosting site (Gitlab), and a sibling without repository hosting support (the GCS special remote sibling). Publishing to a sibling can only publish what the sibling supports (irrespective of the publication dependency). So if you publish, your annex objects would not show up on Gitlab, and the Git aspect of your repository will not show up on GCS.
In other words: Publishing to a repository hosting site without annex support will publish everything stored in Git. Publishing to a special remote will publish annex objects (if you don't want to publish all annex objects you could specify the files manually, or provide configurations for git-annex - I think its https://git-annex.branchable.com/preferred_content/ but I haven't yet done this myself).

> If I Publish the other way around (i.e. If i create gitlab remote first and GCS remote as second with the --publish-depends flag on gitlab remote) Will it work the same way (that is all the soft link to gitlab remote and git annex object on GCS) 

Yes, it will work the same way. The publication dependency only determines the order of publication.
This walkthrough through dataset publications from a recent workshop may also be useful: https://www.youtube.com/watch?v=3ePgH-kK8h8&t=553s

**Comment by xarvshar** [comment]
Thanks @adswa. This is really helpful :)). Thanks for pointing to the workshop as well.

Can you please take a look at below two issues 

https://github.com/datalad/datalad/issues/5224
https://github.com/datalad/datalad/issues/5228

**Comment by xarvshar** [comment]
Closing the issue
