### ISSUE TITLE
FOI: recipe for uploading (exporting) (super)dataset fully to S3

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5227]
I thought it (after we finalize it to our satisfaction) could at least be an addition to the handbook somewhere (hence attn @adswa), but ideally we should look into :

- establish support for `annex initremote` of arbitrary type (or can we do it already?), smth like `create-sibling-annex` if we follow current approach of `create-sibling*`
- add support for using `annex export` instead of `annex copy` for those with `exporttree=yes` (#3127)

Here is our quick&dirty script we came up with @snastase while preparing upload to fcp-indi which you point to superdataset, bucket, and prefix and it exports (or re-exports if any updates) to S3:

<details>
<summary>the script</summary> 

```bash
#!/bin/bash

set -eu

export PS4='> '
set -x

topds="$1"
bucket="$2"
prefix="$3"

# TEMP
srname="${bucket}5"

topdsfull=$PWD/$topds/

if ! git annex version | grep 8.20201 ; then
	echo "E: need recent git annex. check what you have"
	exit 1
fi

{ echo "$topdsfull"; datalad -f '{path}' subdatasets -r -d "$topds"; } | \
while read ds; do
	relds=$(relpath "$ds" "$topdsfull")
	fileprefix="$prefix/$relds/"
	fileprefix=$(python -c "import os,sys; print(os.path.normpath(sys.argv[1]))" "$fileprefix")
	echo $relds;
	(
		cd "$ds";
		# TODO: make sure that there is no ./ or // in fileprefix
		if ! git remote | grep -q "$srname"; then
			git annex initremote --debug "$srname" \
				type=S3 \
				autoenable=true \
				bucket=$bucket \
				encryption=none \
				exporttree=yes \
				"fileprefix=$fileprefix/" \
				host=s3.amazonaws.com \
				partsize=1GiB \
				port=80 \
				"publicurl=https://s3.amazonaws.com/$bucket" \
				public=yes \
				versioning=yes
		fi
		git annex export --to "$srname" --jobs 6 master

	)
done

```
</details>

**Comment by adswa** [comment]
Ah, I seem to have been busy in December ... I get the looming ABCD deadline made me forget this one. But this script could be a Findoutmore in @jsheunis' [awesome chapter on S3 as a special remote](http://handbook.datalad.org/en/latest/basics/101-139-s3.html)!

**Comment by adswa** [comment]
> if ! git annex version | grep 8.20201 ; then
	echo "E: need recent git annex. check what you have"
	exit 1
fi

I assume this can/should become 8.2021, or something more clever?

**Comment by yarikoptic** [comment]
> > if ! git annex version | grep 8.20201 ; then
> > echo "E: need recent git annex. check what you have"
> > exit 1
> > fi
> 
> I assume this can/should become 8.2021, or something more clever?

yes, it was just a doorstop measure to not manage to run an outdated git annex

**Comment by adswa** [comment]
I have added this in to a PR that improves the chapter on publishing. :+1:

**Comment by mih** [comment]
It seems this can be closed. Thx!
