### ISSUE TITLE
way too many "open failed: connect failed: open failed" in datalad/git-annex testing

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5250]
it seems that we see such error messages from ssh in some number in our normal CI setup on travis , see e.g.

https://api.travis-ci.com/v3/job/459752523/log.txt

```
..................................................S  CHECKURL failed with no reason given
git-annex: addurl: 1 failed
.........channel 22: open failed: connect failed: open failed

channel 22: open failed: connect failed: open failed

channel 22: open failed: connect failed: open failed
```

but when we test in datalad/git-annex, see e.g. https://github.com/datalad/git-annex/runs/1547701875 -- there are **THOUSANDS** of those, although largely from `git annex fsck` during `datalad.distributed.tests.test_ria_basics.test_gitannex_ssh` .  It seems that tests still pass, but it really floods the logs etc.

We had those appearing [here and there](https://github.com/datalad/datalad/search?q=open+failed%3A+connect+failed%3A+open+failed&type=issues) before but nobody really cared to figure out the reason behind that, although may be to some degree some time back in https://github.com/datalad/datalad/issues/4643 .  

It seems we should again look into the reason why they are happening :-/ !  Any trobleshooting/ideas would be most welcome @kyleam @bpoldrack @mih @jwodder !

**Comment by kyleam** [comment]
c96c677 (Dockerfile: Increase value of MaxSessions) in the docker-ssh-target repo is sufficient to get rid of these messages on my end (tested with three runs of `test_gitannex_ssh`).  Please reopen if you spot these messages again.
