### ISSUE TITLE
`get` of a subdataset originally clones from ria+ url is differently configured than originally

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5256]
Desired behavior is shown in initial clone
```sh
% datalad clone -d . ria+http://ukb.ds.inm7.de#~bids inputs/ukb3
% git -C inputs/ukb3 config --list | grep subdataset
datalad.get.subdataset-source-candidate-200origin=ria+http://ukb.ds.inm7.de#{id}
```

This makes sure that subdatasets of ukb3 are also pulled from the same store.

But once that original clone is gone, and later retrieved via `get` it is no longer there, and the superdataset isn't as functional anymore:

```
% datalad uninstall inputs/ukb3 && datalad get -n inputs/ukb3
% git -C inputs/ukb3 config --list | grep subdataset
-> exit 1
```

A workaround is to put the vanishing config into `.datalad/config` of the super. A proper solution might be to annotate the respective `.gitmodules` entry in the superdataset.

**Comment by bpoldrack** [comment]
Just to be more explicit: This config is set when we clone from a `ria+...` URL. However, the resolved URL is stored for the submodule, so that upon the `get` w/o `ria+` the configuration isn't triggered.

So, I agree - that information should go into `.gitmodules`. Just not sure yet in what shape.

**Comment by bpoldrack** [comment]
May be just save

```
[submodule XXX]
    datalad-unresolved-url = ria+http://ukb.ds.inm7.de#~bids
```

in addition, so plain git operation is still fine as is, but datalad can consider it.

**Comment by mih** [comment]
Agreement from devcall: Make it so! But call it `datalad-url`
