### ISSUE TITLE
Parameters in docstrings -- unify indentation?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#526]
Should we unify indentation in the parameter docstrings?  some times we use 2 spaces, some times 4.  [NumPy standard](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#docstring-standard) seems to use 4, so should we have it 4 all around?

oh -- and there they capital case beginnings of their descriptions ... heh

**Comment by bpoldrack** [comment]
Well, we should not just pretend to follow a standard,but actually do it. Or not even say we do it ;)
So, yes, let's use 4. And I don't get why to not use capitals anyway. But I don't really care.

**Comment by mih** [comment]
I am one year late to "like" this, but hey ... still made it... ;-)

**Comment by mih** [comment]
This well matured issue will be closed now, it can perfectly serve as a reference in that state too. Sorry if I am shutting done this hot debate ;-)
