### ISSUE TITLE
a number of failing OSX tests

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5270]
In  #5269 I pushed some quick fixes for fails/errors detected on a run of released version on OSX https://github.com/datalad/git-annex/runs/1638321268?check_suite_focus=true#step:12:2515  but some failed tests seems to suggest other issues, including some paths dereferencing etc

https://github.com/datalad/git-annex/runs/1638321268?check_suite_focus=true#step:12:2515

**Comment by mih** [comment]
These failures are all variants of #5291. Closing in favor of that issue collection.
