### ISSUE TITLE
`clone` must support optimization arguments

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5286]
I have a case where the source dataset contains MANY branches. Cloning it takes forever. With `git clone` I can to `--singlebranch` or `--depth 1`. With DataLad I am forced to wait.

**Comment by yarikoptic** [comment]
I guess could be some config option (e.g. `datalad.runtime.clone-git-opts`) to not clutter cmdline options and provide most flexibility. Note that `--singlebranch` is likely not desired in case of `git-annex` repos... 

I think having something like a `--lean` options to clone/install which would fetch only default branch (and git-annex if available, is that possible?) and run with `--depth 1` would be useful for **any** YODA style analysis where we install `sourcedata/` only briefly for the duration of analysis.  Most likely such clone should get that reflected in `.git/config` so possible subsequent `get` would also `clone` accordingly. I feel like we had already some discussion (failed to find, may be I dreamed  it up) on having such "optimized" short-lived installations

**Comment by mih** [comment]
Ah, right. Sadly `--depth 1` implies `--singlebranch`.

**Comment by yarikoptic** [comment]
so in `--lean` we could may be just do two calls (clone and fetch), e.g.

```
$> git clone --depth 1 http://datasets.datalad.org/openneuro/ds000001/.git ; cd ds000001; git fetch --depth 1 origin +refs/heads/git-annex:refs/remotes/origin/git-annex
Cloning into 'ds000001'...
remote: Enumerating objects: 187, done.
remote: Counting objects: 100% (187/187), done.
remote: Compressing objects: 100% (141/141), done.
remote: Total 187 (delta 46), reused 185 (delta 46)
Receiving objects: 100% (187/187), 98.39 KiB | 3.39 MiB/s, done.
Resolving deltas: 100% (46/46), done.
CHANGES                   participants.tsv  sub-03/  sub-06/  sub-09/  sub-12/  sub-15/
README                    sub-01/           sub-04/  sub-07/  sub-10/  sub-13/  sub-16/
dataset_description.json  sub-02/           sub-05/  sub-08/  sub-11/  sub-14/  task-balloonanalogrisktask_bold.json
remote: Enumerating objects: 571, done.
remote: Counting objects: 100% (571/571), done.
remote: Compressing objects: 100% (407/407), done.
remote: Total 570 (delta 89), reused 424 (delta 28)
Receiving objects: 100% (570/570), 64.69 KiB | 2.70 MiB/s, done.
Resolving deltas: 100% (89/89), done.
From http://datasets.datalad.org/openneuro/ds000001/
 * [new branch]      git-annex  -> origin/git-annex
1 48371.....................................:Thu 07 Jan 2021 11:06:37 AM EST:.
(git)lena:/tmp/ds000001[master]
$> git annex init
init  (merging origin/git-annex into git-annex...)
(recording state in git...)
(scanning for unlocked files...)
(Auto enabling special remote s3-PUBLIC...)
ok
(recording state in git...)
```
