### ISSUE TITLE
RunnerAdapter quoting of paths is broken on windows

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5287]
A test ( no code changes ) introduced in https://github.com/datalad/datalad/pull/5117  points to an issue with paths quoting on Windows:

```
======================================================================
ERROR: datalad.distribution.tests.test_create_sibling.test_preserve_attrs
----------------------------------------------------------------------
....
  File "C:\Miniconda37\lib\site-packages\datalad\distribution\create_sibling.py", line 109, in __call__
    out = self.run(cmd, protocol=StdOutErrCapture)
  File "C:\Miniconda37\lib\site-packages\datalad\cmd.py", line 404, in run
    **results,
datalad.support.exceptions.CommandError: CommandError: '"cp" "-R" "-p" """C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_39z3yyrw\src""" """C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_vg79t529"""' failed with exitcode 1 [err: 'cp: missing destination file operand after '\C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_39z3yyrw\src" "C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_vg79t529"'
Try 'cp --help' for more information.']
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using proactor: IocpProactor
```

Initial attempt to mitigate (https://github.com/datalad/datalad/pull/5196) was not successful so the issue remains.  Meanwhile I will merge #5117 with a skip on windows due to this issue

**Comment by mih** [comment]
From the pattern you posted it looks like quotes are being escaped, which is supposed to happen whenever an argument has quotes. The behavior is likely triggered by:

```
                cmd = ["cp", "-R"]
                if preserve_attrs:
                    cmd.append("-p")
                self(cmd + [quote_cmdlinearg(a) for a in args])
 ```

I wonder why quoting is done? `WitlessRunner` receives the command as a list, hence there will be no shell-based execution and no parsing.

**Comment by mih** [comment]
I have adjusted the title to make clear that it is not windows argument quoting in general that is broken.

**Comment by yarikoptic** [comment]
indeed, I see no reason, so will send a quick PR to remove
