### ISSUE TITLE
address rate limiting on "docker pull" of our ssh image

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5288]
here and there we now keep getting following errors:

```
latest: Pulling from dataladtester/docker-ssh-target
anyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
The command "tools/ci/prep-travis-forssh.sh" failed and exited with 1 during .
Your build has been stopped.
```

which is due to 

    The rate limits of 100 container image requests per six hours for anonymous usage, 
    and 200 container image requests per six hours for free Docker accounts are now in effect

I guess possible ways to mitigate:
- :dollar: pay
- :rocket: retry a few times with some delays.  our CI runs long enough that we would likely "escape" the exceeding the limit 
- :-1: setup to use free account to double the limit 
- :heart: add images to https://github.com/datalad-tester/dev-containers , host those images ourselves (e.g. within github LFS, OSF, and/or datasets.datalad.org)  and use datalad-container
  -  my main concern is that to achieve that we need to have datalad and datalad-container installed first and it might "taint" our testing :-/ possible mitigation: lean helper which would just use git-annex directly to `get` that container files, and run the same `docker import` etc as datalad-container does.
- :eyes: : there is also caching, which boils down to the same docker save/load: https://stackoverflow.com/questions/32866599/can-travis-ci-cache-docker-images but travis advises against caching them: https://docs.travis-ci.com/user/caching/#things-not-to-cache 

WDYT (can vote, sorry -- no votes for :dollar: ;)) -- may be there is some better way I do not see?

**Comment by kyleam** [comment]
My vote would be to host the docker-save output somewhere on datalad.org.

```
docker build -t datalad-tests-ssh-base .
docker save datalad-tests-ssh-base | gzip >datalad-tests-ssh-base.tar.gz
```

The .gz is 197M on my end.


```
... download ...
zcat datalad-tests-ssh-base.tar.gz | docker load
sh setup-docker-ssh [...] --from=datalad-tests-ssh-base
```

tools/ci/prep-travis-forssh.sh could either always take that route or fall back to download/load approach when the `--from=dataladtester/docker-ssh-target:latest` variant fails.
