### ISSUE TITLE
Test setup requires short base path on Windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5294]
Demo test:

```
@with_tempfile
@with_tempfile
def test_annex_drop(src, dst):
    s = AnnexRepo(src)
    (s.pathobj / 'test-annex.dat').write_text("content")
    s.save('some')

    ar = AnnexRepo.clone(src, dst)
    testfile = 'test-annex.dat'
    assert_false(ar.file_has_content(testfile))
    ar.get(testfile)
 ```

It passes on linux, it works on windows if the principle equivalent command order (just plain git and git-annex) is typed into a `cmd.exe`, it works when using the high-level datalad commands on windows, it works when this code is executed in a standalone python session on windows.

It does not work when executed as part of the datalad test suite.

In this last case it throws:

```
datalad.support.exceptions.CommandError: CommandError: '"git" "annex" "get" "--json" "--json-error-messages" "--json-progress" "-c" "annex.dotfiles=true" "-c" "annex.retry=3" "--" "test-annex.dat"' failed with exitcode 1 under C:\Users\datalad\AppData\Local\Temp\datalad_temp_8oyv2y7c [err: 'git-annex: get: 1 failed'] [errors from JSON records: [[]]] [info keys: stdout_json]
```

That does say much, but going into that repo and running the `get` again reveals

```
C:\Users\datalad\AppData\Local\Temp\datalad_temp_6mdgp88e>git annex get test-annex.dat
get test-annex.dat
  Unable to access these remotes: origin

  Try making some of these remotes available:
        8c5fdf62-ddc8-47ae-ae7a-8d2295821901 -- datalad@latitude-e7440:~/AppData\Local\Temp\datalad_temp__u8s9_s6 [origin]
failed
git-annex: get: 1 failed
```

But origin exists, has the key, and `git-annex sync` interacts with it just fine. And, again, the analog `get` in a repo that was not prepared as part of a test run, but with identical code, works just fine.

**Comment by mih** [comment]
If I modify the test (create a full dataset instead of just a repo)

```
@with_tempfile
@with_tempfile
def test_annex_drop(src, dst):
    from datalad.api import Dataset
    s = Dataset(src).create()
    (s.pathobj / 'test-annex.dat').write_text("content")
    s.save()

    ar = AnnexRepo.clone(src, dst)
    testfile = 'test-annex.dat'
    assert_false(ar.file_has_content(testfile))
    ar.get(testfile)
```

It works.

**Comment by yarikoptic** [comment]
> And, again, the analog `get` in a repo that was not prepared as part of a test run, but with identical code, works just fine.

any `diff` of .git/config between such two?

**Comment by mih** [comment]
> any `diff` of .git/config between such two?

Only the annex uuid (expected), and the backend (MD5 is working; SHA256 is broken).

Ha! Path length!

And indeed, using `backend='MD5'` in the `AnnexRepo` constructor fixes it!

The annex error is maximally non-informative in this case (ok, I take that back: datalad's variant is even worse). but it points to the fact that we should somehow verify that git-annex can even access the keys that it creates.

And we should like alter the CI runs to use `C:\TMP` as base path to have some wiggle room.

**Comment by mih** [comment]
#5303 acknowledges this now. Closing.
