### ISSUE TITLE
Deprecate `publish`?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5295]
`push` came in 0.13. `publish` was no deprecated at that time. For a smooth and eventually completed transition it would be good to make a deprecation official (in the docs). Shall we do this for 0.14?

I am in favor of that.

**Comment by yarikoptic** [comment]
related prior discussions: https://github.com/datalad/datalad/issues/4494 (I believe there were more).

I must confess I am still using `publish` more often than `push` to not leak (`annex copy`) data unexpectedly.

**Comment by mih** [comment]
It would be good to have a clear statement. We are all still using `AnnotatePath` too -- but that doesnt make it a strategy, or even a good idea.

**Comment by mih** [comment]
If a deprecation is not desired, than at least the tests should be fixed, or the command labeled as unfit for windows, if it is not a pure test issue #5087

**Comment by yarikoptic** [comment]
> If a deprecation is not desired, than at least the tests should be fixed, or the command labeled as unfit for windows, if it is not a pure test issue #5087

FWIW that test is already marked for skipping on windows

```shell
$> git grep -B5 test_publish_fetch_do_not_recurse_submodules
datalad/distribution/tests/test_publish.py-
datalad/distribution/tests/test_publish.py-@known_failure_windows
datalad/distribution/tests/test_publish.py-@slow  # 14sec on Yarik's laptop
datalad/distribution/tests/test_publish.py-@skip_ssh
datalad/distribution/tests/test_publish.py-@with_tempfile(mkdir=True)
datalad/distribution/tests/test_publish.py:def test_publish_fetch_do_not_recurse_submodules(path):
```
similarly to other tests (including in `test_push`) which require create_sibling etc

**Comment by yarikoptic** [comment]
ok, let's add deprecation announcement for it to be gone in 0.15.0.  See #5343
