### ISSUE TITLE
asyncio is not fully reset

### ISSUE THREAD

**Issue by djarecka** [datalad/datalad#5313]
#### What is the problem?
I'm not sure if you consider this as a problem, but after running datalad command in my python code, I'm not able the run `asyncio.get_event_loop()`.
I've changed my code, so it works again, but this perhaps can be an issue...?

#### What steps will reproduce the problem?
```
import asyncio
asyncio.get_event_loop()
import datalad.api as datalad
datalad.clone(source="https://github.com/afni/afni_data.git")
asyncio.get_event_loop()
```
The second call of `get_event_loop` returns an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dorota/miniconda3/envs/testkraken_pydra/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.
```

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.13.6, python 3.7, OSX

**Comment by mih** [comment]
Hmm, PY3.7 is causing general pain with `asyncio`. The current setup in master arrived at a local pain minimum. Can you give that a try?

But given that you are running in miniconda, maybe using 3.8 (or later) is an option for you?

**Comment by djarecka** [comment]
@mih - thanks for suggestion, but I don't see any difference with py3.8 or py3.9. Still can't run `get_event_loop()` after using datalad.

For me the best option seems to be using `asyncio.SelectorEventLoop` instead of `get_event_loop()`: https://github.com/nipype/pydra/pull/401/files

**Comment by djarecka** [comment]
I've also checked that removing ` asyncio.set_event_loop(None)` from you code solves the issue with `get_event_loop()` for all pythons I tried: py3.7, py3.8 and py3.9

**Comment by mih** [comment]
> For me the best option seems to be using `asyncio.SelectorEventLoop` instead of `get_event_loop()`: https://github.com/nipype/pydra/pull/401/files

But that one is not available on Windows, right?

**Comment by djarecka** [comment]
yes, for windows we use `asyncio.ProactorEventLoop()`.  At the end I actually came back to `get_event_loop` but catch an error and call `new_event_loop` if needed.

It looks like `asyncio` will use `asyncio.ProactorEventLoop()` for windows automatically starting from python 3.9 https://docs.python.org/3/library/asyncio-eventloop.html#event-loop-implementations

**Comment by djarecka** [comment]
@mih - so if you don't want to touch it now in datalad, feel free to close the issue

**Comment by kyleam** [comment]
I think this can be closed with the merge of gh-5350, but please reopen if I'm mistaken.
