### ISSUE TITLE
install/clone: add -s/--name

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5320]
re option name: we are yet to unify, e.g. see https://github.com/datalad/datalad/issues/3832

I guess it is not a frequent use case but I did run into it before and again now: we have no way to specify the name of the sibling (other than default "origin") while clone/installing a dataset.  `git clone` has `-o|--origin <name>`

**Comment by adswa** [comment]
With Git version 2.30 Git learned to respect a default remote name configuration: https://patchwork.kernel.org/project/git/patch/5c519376c29a28bd89a712cf0b8125fc1c2c81be.1599848727.git.gitgitgadget@gmail.com/

Setting ``clone.defaultRemoteName`` to any value other than ``origin`` will chose this value as a sibling/remote name.
