### ISSUE TITLE
create-sibling-github fails for enterprise base URL

### ISSUE THREAD

**Issue by m-hess** [datalad/datalad#5324]
#### What is the problem?
`datalad create-sibling-github` can only send requests to `github.com` not enterprise URLs like `git.mycompany.edu`. 

#### What steps will reproduce the problem?
Enabling an optional parameter like `--enterprise-url` with the `datalad create-sibling-github` command for custom URL input would fix this issue. I believe this approach would require modifying `datalad/datalad/distribution/create_sibling_github.py` and `datalad/datalad/support/github.py` to accept and utilize an additional parameter.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
Datalad version 0.13.7 on Mac OS Catalina 10.15.7.

#### Is there anything else that would be useful to know in this context?
Nothing else to note.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
I love Datalad! To make sure that this issue was not user error on my part, I tried `datalad create-sibling-github` on my personal account, which worked perfectly, so I am pretty certain the issue is with the requesting URL to github.

**Comment by kyleam** [comment]
> Enabling an optional parameter like `--enterprise-url` [...]

A similar approach would be adding a configuration variable (which could also be passed on the command line via `-c`).  I don't have an enterprise instance to test against, but, if you're interested in taking a stab at it, perhaps something like the patch below would be a good start.  (It's just based on grepping around the PyGithub code base, so it could be completely wrong)

<details>
<summary>diff</summary>


```diff
diff --git a/datalad/interface/common_cfg.py b/datalad/interface/common_cfg.py
index 7b5a55c0dd..8d411215f9 100644
--- a/datalad/interface/common_cfg.py
+++ b/datalad/interface/common_cfg.py
@@ -131,6 +131,14 @@
             'text': 'Description for a Personal access token to generate.'}),
         'default': 'DataLad',
     },
+    'datalad.github.base_url': {
+        'ui': ('question', {
+            'title': 'URL to use with PyGithub',
+            'text': 'Use this value as `base_url` rather than the default '
+            'when instantiating pygithub.Github. '
+            'This is enterprise instances.'}),
+        'default': None,
+    },
     'datalad.tests.nonetwork': {
         'ui': ('yesno', {
                'title': 'Skips network tests completely if this flag is set Examples include test for s3, git_repositories, openfmri etc'}),
diff --git a/datalad/support/github_.py b/datalad/support/github_.py
index 6848a67851..226a7b9fea 100644
--- a/datalad/support/github_.py
+++ b/datalad/support/github_.py
@@ -33,6 +33,7 @@
     raise MissingExternalDependency(
         'PyGitHub',
         msg='GitHub-related functionality is unavailable without this package')
+from github.MainClass import DEFAULT_BASE_URL
 
 
 def get_repo_url(repo, access_protocol, github_login):
@@ -60,11 +61,11 @@ def _token_str(token):
     return token[:3] + '...'
 
 
-def _get_tokens_for_login(login, tokens):
+def _get_tokens_for_login(login, tokens, base_url):
     selected_tokens = []
     for t in tokens:
         try:
-            g = gh.Github(t)
+            g = gh.Github(login_or_token=t, base_url=base_url)
             gu = g.get_user()
             if gu.login == login:
                 selected_tokens.append(t)
@@ -104,17 +105,18 @@ def _gen_github_ses(github_login):
         reverse=True
     )
 
+    url = cfg.get("datalad.github.base_url", DEFAULT_BASE_URL)
     # Check the tokens.  If login is provided, only the token(s) for the
     # login are considered. We consider oauth tokens as stored/used by
     # https://github.com/sociomantic/git-hub
 
     if github_login and tokens:
         # Take only the tokens which are Ok and correspond to that login
-        tokens = _get_tokens_for_login(github_login, tokens)
+        tokens = _get_tokens_for_login(github_login, tokens, url)
 
     for token in tokens:
         try:
-            yield gh.Github(token), _token_str(token)
+            yield gh.Github(login_or_token=token, base_url=url), _token_str(token)
         except gh.BadCredentialsException as exc:
             lgr.debug("Failed to obtain Github session for token %s: %s",
                       _token_str(token), exc_str(exc))
@@ -126,7 +128,7 @@ def _gen_github_ses(github_login):
         try:
             # ??? there was a comment   # None for cred so does not get killed
             # while returning None as cred.  Effect was not fully investigated from changing to return _token_str
-            yield gh.Github(token), _token_str(token)
+            yield gh.Github(login_or_token=token, base_url=url), _token_str(token)
         except gh.BadCredentialsException as exc:
             lgr.debug("Failed to obtain Github session for token %s: %s",
                       _token_str(token), exc_str(exc))
```

</details>

**Comment by m-hess** [comment]
@kyleam thanks for the info, i'll take a crack at it sometime soon!

**Comment by mih** [comment]
I spent a bit of time on this command (https://github.com/datalad/datalad/pull/5551), and also took a look re this issue. We have three locations where we create a `Github()` instance. Those would need to get a `base_url` parameter https://pygithub.readthedocs.io/en/latest/github.html#github.MainClass.Github 

It seems quite doable, in particular to config approach suggested by @kyleam
