### ISSUE TITLE
Debian pkgs for 14.04

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#533]

**Comment by yarikoptic** [comment]
So could run in Windows Linux subsystem which seems to come with 14.04 but installation of pkg from 15.04 showed some problems

**Comment by hanke** [comment]
@yarikoptic did you try runing something on windows this way?

**Comment by yarikoptic** [comment]
Yeap, but not me personally. I will look also either we could upgrade or VM so we have it as well

**Comment by yarikoptic** [comment]
debian/0.2.1-2 was uploaded .  crawling wouldn't work since we need scrapy > 1 for some pieces, but it should install fine and run other functionality just fine... seems to 'datalad install' things
