### ISSUE TITLE
async-based BatchedCommand

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5336]
The old runners are gone, which leaves `BatchedCommand` as a non-async execution helper. This should become uniform, I think.

**Comment by yarikoptic** [comment]
and insofar one working reliably given [growing number of async-related problems](https://github.com/datalad/datalad/issues?q=is%3Aopen+is%3Aissue+label%3Aasync), so I think no async'ification of it should happen before we address those one way or another which might determine destiny of this RF.

**Comment by mih** [comment]
No async, indeed! Instead #6125
