### ISSUE TITLE
remotes have annex-ignore set with python api, but work in cli

### ISSUE THREAD

**Issue by Saksham20** [datalad/datalad#5353]
There is a dataset that I have created in GIN: https://gin.g-node.org/SakshamSharda/ophys_testing1
Followd with the usual commands:

1. Create a local repo with the required data (binary and text files)

Ran commands:
```shell
datalad create -c text2git -f .
datalad save -m "messg"
git gc --prune=now
datalad siblings add -d . --name gin --url https://gin.g-node.org/SakshamSharda/ophys_testing1.git
datalad push --to gin
```
 3. All uploaded and looks good on the repo on GIN.
4. For round trip, I clone that using datalad clone https://gin.g-node.org/SakshamSharda/ophys_testing1.git
5. All symlinks downloaded, good. Then datalad get "add of symlink" . Got the actual dataset, good.

**PROBLEM:**

If i do the same procedure using the python api using dataset = 
```
datalad.api.install('https://gin.g-node.org/SakshamSharda/ophys_testing1.git') 
dataset.get(dataset_path)
```
 i get an error like:
```
[ERROR] not available; (Note that these git remotes have annex-ignore set: origin) [get(~\ophys_testing1\segmentation_datasets\extract\2014_04_01_p203_m19_check01_extractAnalysis.mat)] 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~\venv\lib\site-packages\wrapt\wrappers.py", line 605, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "~\venv\lib\site-packages\datalad\distribution\dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "~\venv\lib\site-packages\wrapt\wrappers.py", line 566, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "~\venv\lib\site-packages\datalad\interface\utils.py", line 495, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "~\venv\lib\site-packages\wrapt\wrappers.py", line 566, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "~\venv\lib\site-packages\datalad\interface\utils.py", line 483, in return_func
    results = list(results)
  File "C:\Users\Saksham\Documents\NWB\roiextractors\venv\lib\site-packages\datalad\interface\utils.py", line 468, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'get',
  'annexkey': 'MD5E-s1183261--22827ea35bda2a7d678e5f86e875fc5b.mat',
  'message': 'not available; (Note that these git remotes have annex-ignore '
             'set: origin)',
  'path': '~\\ophys_testing1\\segmentation_datasets\\extract\\2014_04_01_p203_m19_check01_extractAnalysis.mat',
  'refds': '~\\ophys_testing1',
  'status': 'error',
  'type': 'file'}]
```
**datalad version: 0.13.7**

**Comment by yarikoptic** [comment]
I will lookup for more references etc, but I believe that for private repos (on gin or in general, don't remember) you would need to go through ssh not http so that `git-annex` would be able to talk to them.  With my ssh key present in the agent and known to gin, following code works for me (on linux, didn't try on windows yet), please try
```
import datalad.api
dataset = datalad.api.install('git@gin.g-node.org:/SakshamSharda/ophys_testing1.git', get_data=True)
```

**Comment by yarikoptic** [comment]
ok -- provided more information/references and initiated dialog with gin folks: https://github.com/G-Node/gogs/issues/111 . I do not think we could do anything extra here...

although, to make it sure.  You said "but work in cli" -- are you sure that `datalad install -g` works in the command line for you? doesn't (and shouldn't as far as see due to above) for me ;)

**Comment by Saksham20** [comment]
yes, you're right, its the ssh issue.
In case of CLI, I had initially cloned using the ssh so it set the origin to the ssh url. When I change the origin to the https and then do `datalad get` it gives the same error of `annex-ignore set:origin`. 
With the python api, when I use the SSH url, it works!

**Comment by yarikoptic** [comment]
Thanks! Since I don't see anything we could do, and issues are filled for gin and git annex, I will close this one here
