### ISSUE TITLE
Discontinue or RF `ls` command

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5359]
This code has not seen any work in 3-4 years. It is either perfect or not used. Several open issues are associated with it (most for several years):

- https://github.com/datalad/datalad/issues/2875
- https://github.com/datalad/datalad/issues/2780
- https://github.com/datalad/datalad/issues/2217
- https://github.com/datalad/datalad/issues/2061
- https://github.com/datalad/datalad/issues/1145
- https://github.com/datalad/datalad/issues/858

The aspect of `ls` functionality that is focused on local datasets could be cheaply reimplemented (and with it almost automatically addressing some of the issues above) using the tooling that fuels `status()`. However, `ls` also aims to be a frontend for S3 (and in the future other platforms -- although we now live in the future and it did not happen ;-), and for that uses an abstraction that is unique to `ls` and not used elsewhere. This special nature makes it unattractive to work on `ls`.

Personally, I think we should:

- discontinue the S3-related functionality in datalad-core -- and maybe move it to the crawler (where it makes kinda sense as an intro/inspection tool
- either discontinue `ls` entirely (what feature does it provide without S3?) or reimplement it using more standard building blocks

**Comment by yarikoptic** [comment]
it is indeed a corpse (needs work for sure), but kinda a "loved one" -- I use it all the time for listing datasets and s3 urls. It is not perfect but quite convenient.  Also, obscurely, it is used for producing listings for the web ui such as http://datasets.datalad.org/.  That code probably should be RFed away though.

**Comment by mih** [comment]
Now that we have https://github.com/datalad/datalad-deprecated there is an easy path to get this stale code out of -core, while maintaining usability and all opportunities for an overhaul.

**Comment by bpoldrack** [comment]
I think `ls` should indeed move to `datalad-deprecated`. The local features (that I kinda like, too) could either be rewritten in a lean replacement in core or simply integrated in `subdatasets`.

**Comment by yarikoptic** [comment]
although I do actively use it, and it is a "core" for metadata extraction for the web UI, but since web ui is in `-deprecated`, I guess this move would be logical and might provide a possible motivation to properly RF the beast into two separate components etc.  As long as it remains functional I should be ok, just shouldn't forget to install `-deprecated` on datasets.datalad.org so post-update hooks still work

**Comment by yarikoptic** [comment]
note: when moving, please move those issues into `-deprecated` instead of just closing them

**Comment by mih** [comment]
Issues above have been moved
