### ISSUE TITLE
`run` <- `save` torpedos working with individually unlocked files

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5360]
Scenario: I have a tool that relies on database files to operate (Berkeley DB). These files are opened `rw`, even for query operations. These DB files are essential for operation (cannot be ignored or regenerated). I want to capture the output of this tool with `datalad run`, hence `datalad save` will be used internally.

Problem: The DB files are big enough, and change frequently enough to warrant annexing. But when files are locked, I would need to go through a `datalad run` for any command execution (to get the DB files to open `rw`), even for trivial reporting. This makes things inconvenient and slow.

Potential solution 1: Send the dataset into adjusted-unlocked mode, and require it to be used in this way. However, that seems heavy handed, as there are just a handful of these files in a single directory that needs special handling, not the entire repo.

Potential solution 2: Commit the unlocked state of these individual files.

This second solution is directly supported by git-annex (and works fine, as far as I can tell):

> `# git annex unlock my_cool_big_file`
> That changes what's stored in git between a git-annex symlink (locked) and a git-annex pointer file (unlocked). You can commit the change, if you want that file to be unlocked in other clones of the repository.

But it does not work with `datalad`, because `datalad save` will forcibly revert the state of an annexed file to "locked" with seemingly no way to prevent it.

```sh
# produce a dataset with a single locked file
% datalad create demo
% echo 123 > testfile
% datalad save

# unlock file "permanently"
% git annex unlock testfile
unlock testfile ok
(recording state in git...)
% git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        typechange: testfile
% git commit -m "keep unlocked"
[master 3450867] keep unlocked
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite testfile (100%)
 mode change 120000 => 100644

# modify
% echo 345 >> testfile
# works without additional explicit unlock
% cat testfile
123
345
# and is automatically recorded as an annex key update
% git diff | cat
diff --git a/testfile b/testfile
index 5b353e4..31f9f36 100644
--- a/testfile
+++ b/testfile
@@ -1 +1 @@
-/annex/objects/MD5E-s4--ba1f2511fc30423bdbb183fe33f3dd0f
+/annex/objects/MD5E-s8--bf4d9751c6249d31a5ab1983661ddfa6
# proper "save" works like this
% git add testfile && git commit -m update

# further modification possible at any time
% echo 789 >> testfile

# but a dataset save ruins it
% datalad save
% echo "boom" >> testfile
zsh: permission denied: testfile
```

Summary:

- I want to use `run`
- These DB (must-be-unlocked) files need saving when something actually changes, but I do not want to pay the unlock penalty on each query-style call (each script using the original tool read-only would need to be adjusted to use it through a properly parametrized `datalad run` call.
- But each use of `datalad run` resets the necessary state of the DB files (re-locks them), and needs to be followed with a dedicated fix-up intervention

**Comment by kyleam** [comment]
> But it does not work with `datalad`, because `datalad save` will forcibly revert the state of an annexed file to "locked" with seemingly no way to prevent it.

I do think that at some point datalad (and thus `save`) needs to embrace v6+ and persistent unlocked files rather than using them in a v5-way.  I don't have any well-formulated ideas on this, but it's hard to imagine an approach that wouldn't add a good amount of complexity to both the code and interface.

**Comment by kyleam** [comment]
> Potential solution 2: Commit the unlocked state of these individual files.

IIRC it was reported in another channel that using `annex.addunlocked` worked here.  So, aside from perhaps documenting that somewhere, is there anything left to do here?

**Comment by mih** [comment]
Yes, I agree -- there is nothing to be done here. I will leave a pointer to the upcoming https://github.com/psychoinformatics-de/datalad-debian where this will play a role and get an implementation in the context of wrapping `reprepro`.

Thx for the support @kyleam !
