### ISSUE TITLE
Support 'git-annex config' in ConfigManager/`configuration`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5361]
As means to supply branch-independent config across clones.

Simultaneously, we should rename `--scope dataset` to `--scope branch` in `configuration` immediately. And later (or even at the same time) introduce the `git-annex` configuration as the actual scope `dataset` (or for authenticity reasons maybe indeed as `git-annex`, which would avoid future confusion.)

**Comment by bpoldrack** [comment]
Despite the potential confusion with the former notion of `dataset`, I'm pretty much in favor of `branch`+`dataset`. While `git-annex` is technically correct, it's less telling if you didn't grasp a lot about how git-annex works yet. If you're using datalad looking at it as a kind of abstraction layer, you can do a lot w/o ever getting what that `git-annex` branch is about and what storing something there would imply. I don't think there's a whole lot of multi-branch usage of datalad datasets with branch specific configs out there yet.

An alternative could be something like `branch`+`all-branches`.

**Comment by kyleam** [comment]
My knee-jerk reaction is that this may not be worth exposing.  DataLad's config situation is already pretty complicated to reason about (e.g., gh-5217), and this adds another layer for readers/users to digest.  On top of that, there's the complication that git-annex won't look at the git-annex branch for most options, only these:
  
  * `annex.addunlocked`
  * `annex.autocommit`
  * `annex.dotfiles`
  * `annex.largefiles`
  * `annex.resolvemerge`
  * `annex.securehashesonly`
  * `annex.synccontent`
  * `annex.synconlyannex`

Grepping around, I wasn't able to find any spots in the code base where we need inspect the git-annex branch for these.

**Comment by mih** [comment]
I confirmed that git-annex prevents setting any non-whitelisted configuration. This makes it pointless to support this mechanism. Thx @kyleam

**Comment by bpoldrack** [comment]
I'm not entirely convinced. This only makes the point to not expose the functionality of `git-annex-config`. Agree on that aspect. But: At a quick test it doesn't seem like annex is confused by adding non-whitelisted configs to `git-annex:config.log`. So, if we are interested in branch-independent configs it still is a place we could use instead of coming up with yet another mechanism. We would just not use `git--annex-config` to read/write those configs.
