### ISSUE TITLE
Strip `configuration` command from the release

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5365]
It comes with a `--scope` parameter that uses the label `dataset` to identify a branch-specific configuration. This precludes the introduction of a non-branch-specific scope that is nevertheless committed to the dataset in the future, without leading to additional confusion.

https://github.com/datalad/datalad/pull/5363#issuecomment-765814422 demands https://github.com/datalad/datalad/issues/5364 as a precondition for this a change in the scope label. Given the magnitude of the implied change, it seems most appropriate to strip `configuration` from master and the upcoming release to avoid complicating the situation further by exposing the problematic label via a command.

I cannot do it momentarily, but I will put up a PR shortly to facilitate the 0.14 release.

**Comment by yarikoptic** [comment]
> This precludes the introduction of a non-branch-specific scope that is nevertheless committed to the dataset in the future, without leading to additional confusion.

Opportunistic statement, since it doesn't. It just would need to be another scope, such as datalad-any-branch or alike

**Comment by yarikoptic** [comment]
Or dataset-detached or dataset-latest if implemented so that it has no association with specific commits
