### ISSUE TITLE
provide API command "credentials"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#537]
and then use it within .travis.yml to set credentials for `datalad-test-s3` credential so we could test s3 code while on travis

unfortunately originally when approached the API command haven't found the way in Keyring to list already registered entries

**Comment by mih** [comment]
Closing in favor of original #396

**Comment by yarikoptic** [comment]
thanks

**Comment by mih** [comment]
FTR: I made a credential entry helper for OSF specifically https://github.com/datalad/datalad-osf/pull/105

Maybe it could be useful for building a more general helper later.
