### ISSUE TITLE
export-archive-ora : how to then add the 7z archive as remote

### ISSUE THREAD

**Issue by bpinsard** [datalad/datalad#5374]
#### What is the problem?
I cannot find documentation on registering the exported 7z file as a special remote for the dataset.
I think it is a relatively recent feature, but it is of great interest for our lab to reduce inode usage on HPC as well as archiving dormant datasets.
Maybe I am misunderstanding the process.

#### What steps will reproduce the problem?
I created a RIA sibling on the same system as the dataset (not ssh), and then ran `export-archive-ora`  storing the file in  `<path/to/ria>/<dataset_2folders>/archive/`. 
From the code of that command it seems to only proceed to the archive creation and that no remote is added.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

0.13.7

Thanks for your help!

**Comment by kyleam** [comment]
> I cannot find documentation on registering the exported 7z file as a special remote for the dataset.

Hmm, yeah, I wasn't able to find any in this code base or the handbook.

> I created a RIA sibling on the same system as the dataset (not ssh), and then ran `export-archive-ora` storing the file in `<path/to/ria>/<dataset_2folders>/archive/`.
> From the code of that command it seems to only proceed to the archive creation and that no remote is added.

I know very little about RIA/ORA things and may be getting turned around (I'm sure others will chime in), but I think setting up a 7z archive with `export-archive-ora` is independent of initiating the special remote.  The remote can added by `create-sibling-ria` or more directly via a `git annex initremote type=external externaltype=ora ...`, which is what `create-sibling-ria` runs underneath, in cases where you already have a store but no special remote.

Here's a working demo that registers a 7z archive (which appears to be functional):

<details>
<summary>demo</summary>

```python
from pathlib import Path
import tempfile
import subprocess as sp

import datalad.api as dl

tdir = Path(tempfile.mkdtemp(prefix="dl-"))

ds = dl.create(tdir / "ds")
(ds.pathobj / "f1").write_text("a")
(ds.pathobj / "f2").write_text("b")
ds.save()

ria_path = tdir / "ria"
ds.create_sibling_ria(name="ria",
                      url="ria+file:{}".format(str(ria_path)))
ds.export_archive_ora(
    ria_path / ds.id[:3] / ds.id[3:] / "archives")
# Update availability information.
ds.repo.fsck(remote="ria-storage", fast=True)

ds.drop(["f1", "f2"])

# sp.run(["tree", ria_path])
sp.run(["git", "annex", "info"], cwd=ds.path)
sp.run(["git", "annex", "whereis"], cwd=ds.path)

ds.get(["f1", "f2"])

sp.run(["git", "annex", "whereis"], cwd=ds.path)
```

</details>

**Comment by bpinsard** [comment]
Thanks a lot for your reply! 

So if I get it, running the fsck on the ria-storage will index the content of `archives/archive.7z` (and only that file, or all 7z files in the archive folder?) and update the annex branch for file location (only in the current dataset git and not in the RIA bare-git, I guess, requiring to push to `ria`).
Would that also work through ssh? I think that would be possible with remote execution of 7z. 

I will try what you suggested tomorrow.

**Comment by mih** [comment]
In addition to the procedure that @kyleam has described, you can also push individual annex keys into the ria sibling as you would normally do. Afterwards you can put them into a 7z archive serverside, and place the archive into the same location that is used above. Because git-annex already knows that you pushed the files to this remote, there is no need to run `fsck` manually. The ora special remote will look for a 7z archive automatically, if it cannot find an annex key file in the usual spot. You can also keep pushing new keys to the remote. They will not automatically enter the 7z archive (because that is expensive), but the special remote will offer the union of all keys (archive + normal) transparently. When you think the time is ripe, you could update the archive serverside again.

**Comment by bpoldrack** [comment]
> So if I get it, running the fsck on the ria-storage will index the content of archives/archive.7z (and only that file, or all 7z files in the archive folder?) and update the annex branch for file location (only in the current dataset git and not in the RIA bare-git, I guess, requiring to push to ria).

Yes, you got that right and as of now `archive.7z` is the only one the special remote is looking at. We are, however, aware that there might be a need for several archives, so this is likely to change in the future. No promise re timeline, though ;-)

> Would that also work through ssh?

Yes.

**Comment by bpinsard** [comment]
Thanks for all your answers, it is clearer now. This is a very nice feature!
In git-annex doc, fsck with --fast option "avoids slow operation", so I guess it will only check that the keys are present on the remote and not perform checksum. 
Regarding updating of the archive, it should be possible to append files to an existing archive, though it wouldn't be with an existing datalad command.

On the HPC we have nearline tapes. I will try to set the `archives` folder as a symlink to the nearline for large dormant datasets, this way we can host large datasets and retrieve them only with datalad commands (with added delays to retrieve and position the tape).

**Comment by bpoldrack** [comment]
> fsck with --fast option "avoids slow operation", so I guess it will only check that the keys are present on the remote and not perform checksum.

Exactly. Without `--fast` it would download and checksum those keys.

> I will try to set the archives folder as a symlink to the nearline for large dormant datasets, this way we can host large datasets and retrieve them only with datalad commands (with added delays to retrieve and position the tape).

Let us know how this works out for you. We may need to introduce configurable timeouts for the special remote or some other feature to better deal with such a setup.

**Comment by bpinsard** [comment]
What do you think of instead using squashfs archives so that archives can be used directly as overlays in singularity images (with binding to `.git/annex/objects`). Multiple archives could be overlaid and union with non-archived files.

**Comment by mih** [comment]
As far as I can see, nothing speaks against using that serverside. Do you see a specific need for dedicated support for this from the datalad end?

**Comment by bpinsard** [comment]
The main advantage is avoiding data duplication when only needing read access. However with the use of a ria-store and the way to preprocess data suggested in datalad-handbook (cloning and pulling data from single subject, branch, preprocessing, pushing then deleting and merging) is simpler and less hacky.
