### ISSUE TITLE
How to deal with the javascript blobs in the code base

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5376]
Github tells that 20% of the codebase are javascript https://github.com/datalad/datalad/search?l=javascript These are largely static, sometimes extremely outdated versions of javascript libraries:

- https://github.com/datalad/datalad/blob/7c1219d17036d5b22cc69d0185ab0a03609467db/datalad/resources/website/tests/qunit/sinon-1.17.5.js (version not even listed on upstream website anymore, current is 9.2.4!)
- https://github.com/datalad/datalad/blob/7c1219d17036d5b22cc69d0185ab0a03609467db/datalad/resources/website/assets/js/jquery-2.2.4.js (2.x branch is no longer supported upstream, 3.5.1 is current)
- https://github.com/datalad/datalad/blob/7c1219d17036d5b22cc69d0185ab0a03609467db/datalad/resources/website/assets/js/md5-2.3.0.js (uptodate)
- https://github.com/datalad/datalad/blob/7c1219d17036d5b22cc69d0185ab0a03609467db/datalad/resources/website/tests/qunit/qunit-2.0.1.js (~4 years old, 2.14.0 is current)
-  https://github.com/datalad/datalad/blob/7c1219d17036d5b22cc69d0185ab0a03609467db/datalad/resources/website/assets/js/jquery.dataTables-1.10.12.js (1.10.23 is current, unclear if it could be even made to work with jquery 2x)
- https://github.com/datalad/datalad/blob/7c1219d17036d5b22cc69d0185ab0a03609467db/datalad/resources/website/assets/js/showdown-1.8.5-33-g0c6ce94.js (~3 years old, 1.9.1 is current)
- https://github.com/datalad/datalad/blob/7c1219d17036d5b22cc69d0185ab0a03609467db/datalad/resources/website/tests/qunit/sinon-qunit-1.0.0.js (~10 years old, 2.0 is newer and already 6 years old)

So with few exceptions these are very outdated. Moreover, they just sit in the source repo and have received no maintenance after 2018 (some no a single change after the initial inclusion).

We should discuss how to handle this code in the future.

An initial step could be to pull the (large) static js library blobs from the repo, and replace them with adhoc downloads from an alternative source.

**Comment by yarikoptic** [comment]
Given that they are just to support web UI interface such as of http://datasets.datalad.org, and I am not sure if anyone else besides me is using it, it might be worth looking into just moving this ability to create a sibling with this particular web interface into an extension (e.g. `datalad-webui-classic` or alike ;) ).

**Comment by mih** [comment]
Extensions are an option. But in general, do you benefit from these libs being in the source tree in editable form vs just pulling them in minified to the client via html?

**Comment by mih** [comment]
It seems the space and also site-performance savings potential is substantial. For example:

`jquery.dataTables-1.10.12.js` as stored in our repo, and uploaded to a silbling is 400kb. If I pull down (what I assume to be the same flavor from https://cdn.datatables.net/v/dt/jq-2.2.4/dt-1.10.12/datatables.min.js I see 170kb.

However, in looking through the libs I saw that this one in particular is a fork with a small change:
cb3d8d932ab3f38fcc129db671809e5f3aceb0d5

So just switching the assets to be pulled from a CDN can be ruled out.
