### ISSUE TITLE
Proxy datalad_installer __main__ in datalad.install?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5378]
With #5243 we will remove `datalad.install` introduced for 0.14.0rc1 , and it would be the right thing to do to avoid code duplication and resolve "chicken/egg" issue for a use of datalad-installer to actually install datalad itself.

But I wondered if we should may be still "have" it as a core dependency and add that `datalad.install`?  That should simplify at least installation of datalad on osx and windows, where we could do "install datalad" (conda, pip, etc; conda would need to have it packaged) + `python -m datalad.install git-annex`.  That could also be accomplished via "install datalad-installer" + `python -m datalad_installer git-annex datalad` and that is why I am a bit luke warm about it...

WDYT @datalad/developers ?

**Comment by mih** [comment]
I'd say 10 months of silence is enough ;-)

Maybe we should revisit the topic when the installer is actually used across all platforms. The current windows CI setup is still a custum implementation due to #5767 and #5871
