### ISSUE TITLE
DATALAD_SSH_IDENTITYFILE is not in effect for git-annex !?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5382]
NB sorry if not totally descriptive but spent too much time digging all the way down from reproman and trying to figure out.  Want to just record what I found, pardon my mistakes in the following claim, if there is any:

For remote hosts reachable only via a dedicated ssh key, we have come up with DATALAD_SSH_IDENTITYFILE (config) to point to such ssh key.   I believe it worked nicely for both git and git-annex, but I believe we do not have (or was it somehow gone?) a nice dedicated test for that and it stopped working!

Here is demonstration on the laptop (watchout -- removes authorized_keys):

```
#!/bin/bash

export PS4='> '

set -eu

cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-ssh-XXXXXXX)"

ssh-add -D || :
rm -f ~/.ssh/authorized_keys

ssh-keygen -f identity -N ''
cat identity.pub >| ~/.ssh/authorized_keys

datalad create test1; touch test1/data; datalad save -d test1

# this will go ok
DATALAD_SSH_IDENTITYFILE=$PWD/identity datalad clone localhost:$PWD/test1 test1-clone

# but get would demand password!
# in my specific use case password is not allowed auth method, so it just fails
DATALAD_SSH_IDENTITYFILE=$PWD/identity datalad get -d test1-clone
```

Some observations:

- `sshconnector` makes use of that variable to include in minting the socket filename
- `sshconnector` does not start socket
- `git-annex` seems to not care about us setting `GIT_SSH_COMMAND="datalad sshrun" GIT_SSH_VARIANT=ssh`
  - I have tried with git-annex `7.20190819+git2-g908476a9b-1~ndall+1` and `8.20201127+git54-ga1b227171-1~ndall+1` with the same "success"
- as a result - annex cannot `get` anything :-/

To me smells like a bug in git-annex, but I bet I have tried before with that elderly 7.20190819 ... may be datalad also behaved differently (always started a socket?) back then and that is why it worked (but I have tried even 0.11.7 to the same effect).

So am I dreaming that it ever worked for git-annex?  or there is a long standing regression which we have missed?

**Comment by bpoldrack** [comment]
> So am I dreaming that it ever worked for git-annex?

No, at least `GIT_SSH_COMMAND` is supposed to be supported by annex for a long time.

**Comment by yarikoptic** [comment]
then it is something to troubleshoot more and fix since seems to be not working (although was "long time" ago ;-))

**Comment by kyleam** [comment]
It looks like support for `GIT_SSH` and `GIT_SSH_COMMAND` was added in 6.20170321, but, shortly after that
(6.20170510), `GIT_ANNEX_USE_GIT_SSH` needed to be set in order to use them.  `GIT_ANNEX_USE_GIT_SSH` has never been in this code base, so it seems that that is the window where this would have worked.

I think the main thing to try is set `GIT_ANNEX_USE_GIT_SSH=1` (telling git-annex that sshrun can handle `-n`) and drop the use of `.annex-ssh-options` in the code base, which isn't in effect when `GIT_SSH{,_COMMAND}` is set.

<details>
<summary>relevant section from git-annex manpage</summary>

```
       GIT_SSH, GIT_SSH_COMMAND
              Handled similarly to the same as described in git(1).   The  one
              difference  is  that git-annex will sometimes pass an additional
              "-n" parameter to these, as the first parameter, to prevent  ssh
              from  reading  from stdin. Since that can break existing uses of
              these environment variables that don't expect the extra  parame‐
              ter,  you  will need to set GIT_ANNEX_USE_GIT_SSH=1 to make git-
              annex support these.

              Note that setting either of these environment variables prevents
              git-annex  from  automatically  enabling  ssh connection caching
              (see annex.sshcaching), so it will  slow  down  some  operations
              with  remotes  over ssh. It's up to you to enable ssh connection
              caching if you need it; see ssh's documentation.

              Also,  annex.ssh-options   and   remote.<name>.annex-ssh-options
              won't have any effect when these envionment variables are set.

              Usually  it's  better  to  configure any desired options through
              your ~/.ssh/config file, or by setting annex.ssh-options.
```

</details>

**Comment by kyleam** [comment]
> I think the main thing to try is set `GIT_ANNEX_USE_GIT_SSH=1`[...]

Working on it, though I'm getting bested by `tests_annex_ssh` at the moment.  However...

> `GIT_ANNEX_USE_GIT_SSH` needed to be set in order to use them

... all of this seems to be operating as expected on git-annex's end when I use `GIT_SSH_COMMAND=datalad sshrun` and friends and then use git-annex directly.

<details>
<summary>example</summary>

```sh
## .ssh/config entry for the Docker ssh target used in datalad's tests
#
# Host datalad-test
# HostName localhost
# User dl
# ControlMaster no
# StrictHostKeyChecking no
# Port 42241

set -eu

socket_dir="$HOME"/.cache/datalad/sockets
rm -rfv "$socket_dir"

cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-sshrun-XXXXXXX)"
git init a
(
    cd a
    git annex init
    git commit --allow-empty -mc0
)

git clone datalad-test:"$(pwd)/a" b

export GIT_SSH_COMMAND='datalad sshrun'
export GIT_SSH_VARIANT=ssh
export GIT_ANNEX_USE_GIT_SSH=1
find "$socket_dir" -type s || :
(
    cd b
    git annex init
    echo a >f1
    git annex add f1
    git commit -mf1
    test -z "$(find "$socket_dir" -type s)" || exit 1
    git remote -v
    git annex copy --to origin f1

)

find "$socket_dir" -type s || :
echo "sleeping for atexit()..."
sleep 1
find "$socket_dir" -type s || :

datalad --version
git annex version --raw
```

```
[...]
origin	datalad-test:/tmp/dl-sshrun-ZcYbZaH/a (fetch)
origin	datalad-test:/tmp/dl-sshrun-ZcYbZaH/a (push)
copy f1 (to origin...) 

100%  2 B               2 KiB/s 0s
                                  
ok
(recording state in git...)
/home/kyle/.cache/datalad/sockets/bddf1a95
sleeping for atexit()...
datalad 0.13.7.dev25
8.20210127
```

</details>
