### ISSUE TITLE
idea: sense remote before clone for having a desired commit?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5392]
this is a somewhat complimentary to https://github.com/datalad/datalad/pull/5391 (remove failed clone).  We could minimize such cases if we had an easy way to test if remote has the desired commit.  One command which comes to mind is `git ls-remote` which would give hexshas for all current heads.  But it might be insufficient (i.e. if head has progressed, but commit is still there).
@datalad/developers and other git gurus -- do you see a way (may be through some `--dry-run` of some hypothetical `git-fetch-object` command) to achieve that?

**Comment by bpoldrack** [comment]
I don't get that with respect to `clone` / #5391. What remote? Before cloning there's no repo with a remote we could run such a command on. And after cloning we test it anyway. Don't see the point really, but may be I'm missing something.

**Comment by yarikoptic** [comment]
;-) there is none, but clone is at large `mkdir; git init; git fetch`, so we could do smth like
```
$> time bash -c 'mkdir -p repo; git init; git remote add origin http://github.com/datalad/datalad ; cd repo; git ls-remote | grep 08786195f7fc891017205f61132d184509b2b61d'
Reinitialized existing Git repository in /tmp/.git/
fatal: remote origin already exists.
warning: redirecting to https://github.com/datalad/datalad/
From http://github.com/datalad/datalad
08786195f7fc891017205f61132d184509b2b61d	refs/heads/debian
08786195f7fc891017205f61132d184509b2b61d	refs/tags/debian/0.14.0_rc1+git10-g1b22107ac-1^{}
bash -c   0.09s user 0.04s system 23% cpu 0.567 total
```
and then if commit is found, do a full fetch (or alternatively just remove this temporary thing, and do a full clone)

**Comment by bpoldrack** [comment]
Hmmm

> or alternatively just remove this temporary thing, and do a full clone

Given lots of options, special cases and postclone routines for `clone`, I think this is the only option. 
Adding overhead for all cases instead of the (probably rare) cases, where we actually can clone from a URL candidate but don't find the commit overall seems more expensive to me, though.

**Comment by yarikoptic** [comment]
> postclone routines for `clone`

unrelated really since those would be handled outside of `git clone` and we could just handle that part "alternatively". But you also making me worry... can such routines reside in the dataset or its super dataset?  then it is a huge security hazard -- malicious user could provide a dataset with malicious routine... I feel we had this discussion before, so hopefully the answer is "not".

re overhead etc.  Overall I think it might be worth a configuration item which would instruct to either "fail" (current), "remove" (#5391), "sense" (this idea).  I would see "fail" useful in cases where I would like to ensure that I do have my original "source" url to contain reachable hierarchy.  "sense" would be of great benefit as we get registry going and be able to provide more of "alternative sources" -- it would make sense to sense them first without trying to clone each and every one.

But question stands: is there some `git` plumbing command which could let us sense the remote. if not - the whole point is moot (although may be could relate to https://github.com/datalad/datalad/issues/5286 as a possible implementation (fetch lean top level, and then fetch the rest if all is ok).

**Comment by kyleam** [comment]
> One command which comes to mind is `git ls-remote` which would give hexshas for all current heads. But it might be insufficient (i.e. if head has progressed, but commit is still there).

I think that's a pretty big limitation.

You could check the status of `git fetch [--depth=1] <remote> <hexsha>`, but 1) that's still pretty expensive and 2) depends on the server being configured to allow it.  Since it's not a reliable answer, at best you could use it to re-prioritize URLs, which seems likely to be too expensive to be worth it.

> 'mkdir -p repo; cd repo; git init; git remote add origin http://github.com/datalad/datalad ; git ls-remote | grep 08786195f7fc891017205f61132d184509b2b61d'

FWIW you could do

```
$ git ls-remote https://github.com/datalad/datalad | grep 08786195f7fc891017205f61132d184509b2b61d           
08786195f7fc891017205f61132d184509b2b61d	refs/heads/debian
08786195f7fc891017205f61132d184509b2b61d	refs/tags/debian/0.14.0_rc1+git10-g1b22107ac-1^{}
```

**Comment by bpoldrack** [comment]
> can such routines reside in the dataset or its super dataset?

No.

> unrelated really since those would be handled outside of git clone and we could just handle clone "alternatively"

Yes, all of that (not just post clone routines) can be handled if we'd go for `git init`, `git fetch`, etc., but all of that implies a lot of refactoring, I think.

**Comment by yarikoptic** [comment]
ok, verdict -- idea was good but there is no way to implement it due to absent `git` support for such an act
