### ISSUE TITLE
Thoughts on scalable computing bottleneck

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5395]
The computing setup that eventually led to #5393 made me think about bootlenecks and ways to avoid them. Here is a brief summary of that setup:

- there is a RIA store with a (single) dataset that will receive the output of each of 40k compute jobs
- all compute jobs are in-principle independent of each other (each consumes different data and writes different output files than any other job
- a job does
  1) clone from RIA store
  2) create job-specific branch
  3) pull inputs from subdataset
  4) compute via `containers-run` and capture outputs
  5) push results (new branch, and git-annex) back to `origin` in the RIA store, and push file content to an ORA special remote (pointing to the same store)

Problem

- steps 1 and 5 operate on a single git repo (in the RIA store), and must be protected by a global lock (across all jobs)
- due to #5393 (and possibly other effects) step 1 takes longer and longer with an increasing number of job results pushed back to `origin` in the RIA store (started at 5s, approached 3min after 30k jobs, with daily `git gc` runs at origin)
- because of the global lock, job start and completion quickly consume more time that the net compute time of a job (steps 2-4, ~1h)

Possible alternative

Things should be much faster when jobs do not produce output that needs to be sync'ed across jobs (which needs to happen in step 5 with the git-annex branch, it always implies a merge of the latest state, and as #5393 illustrates there is useful and not useful information accumulating in that branch with each job).

So maybe it could go like this -- only changing step 5:

Instead of pushing file content to the store, and two branches (job output branch and git-annex), we only

- push the file content (no need to sync/lock across jobs as there are no concurrency problems)
- push the job output branch only (to capture which annex keys belong to the output)

We do not push (hence also avoid syncing with `origin`'s `git-annex` branch). This will prevent adequate file availability records accumulating at `origin`. However, that accumulation is the problem. And we can easily create uptodate records by running a `git annex fsck -f ora-remote-in-store --fast` at the very end of computation.

Now we can do one more change and should maximize speed. We can have two store locations:

- one for the starting point of the computation -- each job clones from here
- one for the output, where the job specific output branches accumulate

With this setup, the same (tiny) starting state is cloned (<2s), and there is no cumulative slowdown with increasing number of output branches. NB: We cannot use optimizations such as `--singlebranch`, because they will not give us functional datasets (see #5286). The initial clone likely still needs a global lock, but it can be different than the one for pushing results.

Pushing results will not need a global lock for the file content transfer, only the branch push needs to go through a lock. But as there is nothing to merge and each job pushes a unique branch, it should work even without any prior fetch (just configure a remote), hence should be quick (in my concrete case <1s).

So there is hope that this change would increase parallelization from an effective 50x to a >1800x (assuming the initial global clone lock is the limiter with 2s) for ~1h jobs.

**Comment by bpoldrack** [comment]
> We can have two store locations:
> 
>     one for the starting point of the computation -- each job clones from here
>     one for the output, where the job specific output branches accumulate

Not sure whether you meant it that way, so this is either clarifying or proposing fine tuning:

- clone from input location
- do stuff
- push annex keys back to input location (even same keys can be uploaded simultaneuously via ORA, so if lock would be needed in such a case, it would be limited to the duration of a `mv` from within ORA)
- push git-branch to collecting repo (not input location)
- when everything is done, collecting repo can merge (if needed), run annex-fsck on input location and push all branches back to input location
   -> neither ephemeral clones nor the collecting repo pollute the git-annex branch.

**Comment by yarikoptic** [comment]
> We do not push (hence also avoid syncing with `origin`'s `git-annex` branch). This will prevent adequate file availability records accumulating at `origin`. However, that accumulation is the problem. And we can easily create uptodate records by running a `git annex fsck -f ora-remote-in-store --fast` at the very end of computation.

FWIW: I was thinking about something like that as well (just in a different, likely less performant way - some staging repository in which to do the merge, announcing those remotes dead etc, and then annex forget), since it is of no use to blow up git-annex branch with all the branches/information about life of files on the individual job clones.

**Comment by mih** [comment]
I will close this now. We have a manuscript coming on that touches on such aspects. The most relevant technical issue for datalad is the use of private annex repos, see https://github.com/datalad/datalad/issues/5835
