### ISSUE TITLE
using datalad for provenance tracking in nipype - how to?

### ISSUE THREAD

**Issue by pvavra** [datalad/datalad#5397]
I am interested in using nipype to set up my analysis pipeline and datalad, especially `datalad run` for provenance tracking (and version control). However, I’m not sure about how to go about this and I would appreciate your opinion on this.
 
I wasn't sure where to post this. Since this not a bug per se, but a rather large feature-request involving datalad too, I created a [neurostars.org thread on this](https://neurostars.org/t/using-datalad-for-provenance-tracking-in-nipype-how-to/18132). Feel free to close this issue, and reply your thoughts on neurostars instead. To get the nipype devs to see the post too, I'm posting a similar issue over at the nipype repo as well.

**Comment by yarikoptic** [comment]
For completeness here is the satellite issue you filed in nipype: https://github.com/nipy/nipype/issues/3294 .
I followed up there -- I do not think there is anything todo about this on datalad side

**Comment by adswa** [comment]
I think this question has been answered in the linked issue, and is thus hopefully good to close. Please reopen if you disagree, and feel more than welcome to ask additional questions
