### ISSUE TITLE
datalad crawl adds multiple wrong URLs to certain files

### ISSUE THREAD

**Issue by cmadjar** [datalad/datalad#5429]
#### What is the problem?

When running `datalad crawl`, all `*scans.json` files get added to the list of URLs of all scans.json files in git-annex:

```
(datalad_v0.14.0_python3.8.5) preventad-open-bids $ git annex whereis BIDS_dataset/sub-5458966/ses-NAPBL00/sub-5458966_ses-NAPBL00_scans.json
whereis BIDS_dataset/sub-5458966/ses-NAPBL00/sub-5458966_ses-NAPBL00_scans.json (4 copies) 
  	2930065c-0d6e-4f44-bb37-5e3bd38c670c -- cmadjar@Ceciles-Mac-mini.local:~/tmp_pad/preventad-open-bids [here]
   	c1310042-0393-48a1-9b0f-886f0353c93d -- cecile@cecile-dev.loris.ca:/data/CONP/preventad-open-bids
   	c6a15a49-4e7f-4cf7-8d63-7b70b5376bb0 -- cecile@cecile-dev.loris.ca:/data/CONP/preventad-open-bids
   	cf13d535-b47c-5df6-8590-0793cb08a90a -- [datalad]

  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1000173/NAPBL00/bidsfiles/sub-1000173_ses-NAPBL00_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1000173/NAPEN00/bidsfiles/sub-1000173_ses-NAPEN00_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1000173/NAPFU03/bidsfiles/sub-1000173_ses-NAPFU03_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1000173/NAPFU12/bidsfiles/sub-1000173_ses-NAPFU12_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1004359/PREBL00/bidsfiles/sub-1004359_ses-PREBL00_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1004359/PREFU12/bidsfiles/sub-1004359_ses-PREFU12_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1004359/PREFU24/bidsfiles/sub-1004359_ses-PREFU24_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1016072/PREFU24/bidsfiles/sub-1016072_ses-PREFU24_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1072774/PREEN00/bidsfiles/sub-1072774_ses-PREEN00_scans.json
  datalad: https://openpreventad.loris.ca/api/v0.0.3-dev//candidates/1072774/PREFU12/bidsfiles/sub-1072774_ses-PREFU12_scans.json
 .... for over 1300 files...
```

This is consistent for all the `*scans.json` files and `*bval` files crawled. All the other crawled files are fine and only have one URL attached to them. I keep looking at the pipelines code and cannot figure out why this is happening. Any idea?

I checked the LORIS API and there is indeed only one entry for each scans.json file returned so that does not seem to come from the LORIS API.

#### What steps will reproduce the problem?

1) install latest release of datalad (v0.14.0)
2) checkout the following branch from my fork of datalad-crawler (note, branch based on tag 0.8.0 of datalad-crawler): https://github.com/cmadjar/datalad-crawler/tree/0.8.0_preventad_bids_test
3) run the following statements to install preventad-open-bids, remove all *scans.json files and run the crawler

```
datalad install https://github.com/conpdatasets/preventad-open-bids.git
cd preventad-open-bids/
datalad remove BIDS_dataset/*/*/*scans.json
datalad crawl
```

Notes: 
- `datalad crawl` will ask for credentials on openpreventad.loris.ca. If you do not have already an account, you can request one and it will be quickly approved.
- on my fork, I commented out most of the code and added a break in the for loop to just download the first `scans.json` file for testing purposes instead of waiting for all the files to be downloaded... I am not that patient ;).

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

Was confirmed on a fresh install of `datalad` tag `v0.14.0` and `datalad-crawler` tag `0.8.0` but has been present on older versions as well.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)

The error mentioned here seems consistent across all the crawled `*scans.json` and `*.bvals` files. For every other files crawled by that crawler, there is only one URL added in git annex.

**Comment by cmadjar** [comment]
FYI - result of `datalad wtf`

```
(datalad_v0.14.0_python3.8.5) preventad-open-bids $ datalad wtf
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - macOS Keyring
      - PlaintextKeyring with no encyption v.1.0 at /Users/cmadjar/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /Users/cmadjar/.config/python_keyring/keyringrc.cfg
    - data_root: /Users/cmadjar/.local/share/python_keyring
## datalad 
  - full_version: 0.14.0
  - version: 0.14.0
## dataset 
  - id: 2c186076-9acc-11ea-99d2-525400a81410
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /Users/cmadjar/tmp_pad/preventad-open-bids
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.5.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:annex: 8.20200501
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.24.3
  - cmd:system-git: 2.24.3
  - cmd:system-ssh: 8.1p1
  - humanize: 3.2.0
  - iso8601: 0.1.14
  - keyring: 22.0.1
  - keyrings.alt: 4.0.2
  - msgpack: 1.0.2
  - requests: 2.25.1
  - scrapy: 2.4.1
  - wrapt: 1.12.1
## environment 
  - LANG: en_CA.UTF-8
  - PATH: /Users/cmadjar/python_virtualenv/datalad_v0.14.0_python3.8.5/bin:/usr/local/opt/grep/libexec/gnubin:/usr/local/opt/php@7.2/bin:/usr/local/fsl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/local/bin:/opt/local/sbin
## extensions 
  - crawler: 
    - description: Crawl web resources
    - entrypoints: 
      - datalad_crawler.crawl.Crawl: 
        - class: Crawl
        - load_error: None
        - module: datalad_crawler.crawl
        - names: 
          - crawl
      - datalad_crawler.crawl_init.CrawlInit: 
        - class: CrawlInit
        - load_error: None
        - module: datalad_crawler.crawl_init
        - names: 
          - crawl-init
          - crawl_init
    - load_error: None
    - module: datalad_crawler
    - version: 0.8.0
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - FsEvents
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.6.5
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0.1
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - local repository version: 8
  - operating system: darwin x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200501
## location 
  - path: /Users/cmadjar/tmp_pad/preventad-open-bids
  - type: dataset
## metadata_extractors 
  - annex (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: No module named 'PIL' [image.py:<module>:16]
    - module: datalad.metadata.extractors.image
  - xmp (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## metadata_indexers 
## python 
  - implementation: CPython
  - version: 3.8.5
## system 
  - distribution: darwin/19.6.0 10.15.7/x86_64
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 298
  - name: Darwin
  - release: 19.6.0
  - type: posix
  - version: Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64
```

**Comment by yarikoptic** [comment]
could you check if those files anyhow different or they all are the same checksum?

**Comment by cmadjar** [comment]
aaaaaaaah, yes... Now that you mention it I just realized that indeed, all scans.json and all bval files are identical for that BIDS dataset... I guess this is why all the URLs pile up in each file. 

Is there a way to avoid that and have only one URL per file by any chance?

Thank you :-)

**Comment by yarikoptic** [comment]
Why bother? The more the merrier since you do have them there. You could have even added them directly to git to not bother annex for them.
 I will consider issue resolved. Cheers

**Comment by yarikoptic** [comment]
BTW, the fact that all `_scans.json` are the same says that most likely they are degenerate -- i.e. do not actually have proper data in them.  So you might like to fix that in your bids dataset if viable

**Comment by cmadjar** [comment]
the `_scans.json` files describe the content of the `scans.tsv` files. That content is alway the same across all subjects/sessions, therefore they are identical. I just re-checked the BIDS specs in case I missed something about the generation of that file but as far as I understand, this is correct.

We also have the same issue for all .bval files which are identical as the same DWI protocol has been applied to all MRI sessions.

Do you have any advice on how we could fix the issue of the multiple URLs added to those files when we crawl?

**Comment by cmadjar** [comment]
oh, somehow I missed your comment from 3 days ago and only receive a notification for your comment of today.

> Why bother? The more the merrier since you do have them there. You could have even added them directly to git to not bother annex for them.

Because of the large amount of URLs, it looks like it slows down significantly the download of scans.json files which systematically fails the test download that we have running on Circle CI. 

![Screen Shot 2021-02-22 at 10 33 08 AM](https://user-images.githubusercontent.com/1402456/108730455-8c08d580-74f9-11eb-8d01-c9a324a491f0.png)

We could increase the timeout of the test but that does not resolve the issue that users have to download over 1300 small json files that would take a significant amount of time to download. 

If you have any suggestion, let me know. 

Thank you for your help and quick replies :-)

**Comment by yarikoptic** [comment]
> the `_scans.json` files describe the content of the `scans.tsv` files. That content is always the same across all subjects/sessions, therefore they are identical.

d'oh -- right, mixed up with `.tsv` files themselves... I wonder if inheritance principle could be applied to just carry a single .json on top of the dataset.

> Because of the large amount of URLs, it looks like it slows down significantly the download of scans.json files which systematically fails the test download that we have running on Circle CI.

that is odd and should not happen one way or another.  This dataset is not public right?  might need to 'simulate' or smth like that.  not yet convinced it is due to large number of urls -- it is probably a "large files in annex which point to the same key"...

> If you have any suggestion, let me know.

as I have mentioned above -- IMHO the best would be to keep them directly in git not in git-annex.  I doubt they contain any sensitive data

**Comment by cmadjar** [comment]
oh boy, Monday morning is hard on me I think ;-). I missed your git suggestion earlier... I might do that actually. Since they do not contain any PII, just description of the protocol, it will definitely be fine to add them directly to git.


FYI - The dataset PREVENT-AD dataset is open but behind a LORIS login/password (openpreventad.loris.ca). All requested accounts are granted. I think you already have an account if I remember correctly. It is part of the [DataLad conp-dataset ](https://github.com/CONP-PCNO/conp-dataset) or its BIDS derived dataset can be found directly at: https://github.com/conpdatasets/preventad-open-bids

**Comment by cmadjar** [comment]
Thank you for the suggestion and help :-).
