### ISSUE TITLE
NDA -- access to meta-data

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#543]
ATM access to meta-data associated with data provided from S3
- miNDAR package needs to be generated
- per package credentials specified
  So, even having NDAR credentials sufficient to access the meta-data, it is impossible to access it without going through miNDAR

@obenshaindw is the NDAR guru who might work to provide a service to access meta-data associated with GUIDs/datasets etc, so it might come out in the future.

For now, within #527 we will just (ultimately) provide a super-dataset with access to Image datasets from NDAR without associated meta-data being provided (although possibly accessed initially to create the datasets via miNDAR package)

References:
- https://github.com/BANDA-connect/NDA-sprint/wiki/NDA-Entity-Relationship-Diagrams

Notes
- 1-to-many Collection -> Submission -> Dataset  .
-  "res-subsmissions" result in previous submission being archived (not accessible unless referenced by some other collection(?)), new submission is created to replace previous one (in a collection(?))

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
