### ISSUE TITLE
git-annex will instantaneously and silently upgrade the repo to a new version of git-annex 

### ISSUE THREAD

**Issue by jbpoline** [datalad/datalad#5439]
Described by @prioux ; possibly linked to #5399

@yarikoptic : this may be a @joey question

#### What is the problem?

The 'git-annex' command and its different versions is the tricky point here.

The problem is that when git-annex version N is run on a repo created with an
earlier version of git-annex (e.g. A, where A < N), then git-annex will instantaneously
and silently upgrade the repo to git-annex version N.

This is a problem when the datalad command, for some reason, invokes an old version A of git-annex
while the system or the user's shell has access to a newer version N. This sequence of operation then
causes problems:

1) You can install a datalad dataset with the datalad command, which uses old git-annex A
2) You manually run some git-annex commands, which uses new git-annex N, and which upgrades the
dataset to git-annex N structure.
3) You attempt to run further datalad commands, but now it is trying to run git-annex A again
and these will crash, because version A doesn't know how to access git-annex version N files.

#### What steps will reproduce the problem?

A very specific example of that is when using the datalad singularity container:
Fetch the container with

singularity pull datalad.sif shub://datalad/datalad:fullmaster

This creates the file 'datalad.sif' which is a self-contained, self-running container with
datalad 0.13 and git-annex 7.20:

unix> ./datalad.sif --version
datalad 0.13.0rc2
unix> singularity exec datalad.sif git-annex version | head -1
git-annex version: 7.20190819+git2-g908476a9b-1~ndall+1

If on that system I also have a more recent git-annex:

unix> git-annex version | head -1
git-annex version: 8.20200909-g2d5036e44

Then it's easy to demonstrate the problem:

unix> export SINGUALRITY_BINDPATH=$PWD # only needed if you run datalad on any path outside of the default bind path of singularity

Install a dataset:

unix> ./datalad.sif install ///conp-dataset/projects/BigBrain_3DSurfaces
unix> cd BigBrain_3DSurfaces

Query with the build-in git-annex, v7 :

unix> singularity exec ../datalad.sif git-annex whereis bigbrain.loris.ca_BigBrainRelease.2015_3D_Surfaces_CerebralCortex_MNI_obj_white_right_327680.obj                                                                                  
whereis bigbrain.loris.ca_BigBrainRelease.2015_3D_Surfaces_CerebralCortex_MNI_obj_white_right_327680.obj (2 copies)                                                                                                                  
       00000000-0000-0000-0000-000000000001 -- web                                                                
       4850dd3d-9f7c-4e2f-8b43-27f1a0111376 -- emmet@emmet-VirtualBox:~/conp-dataset/projects/BigBrain_3DSurfaces

 web: ftp://bigbrain.loris.ca/BigBrainRelease.2015/3D_Surfaces/CerebralCortex/MNI-obj/white_right_327680.obj      
ok                      

Query now with the system git-annex, v8 :

unix> git-annex whereis bigbrain.loris.ca_BigBrainRelease.2015_3D_Surfaces_CerebralCortex_MNI_obj_white_right_327680.obj                                                                                                                  
whereis bigbrain.loris.ca_BigBrainRelease.2015_3D_Surfaces_CerebralCortex_MNI_obj_white_right_327680.obj (2 copies)                                                                                                                  
       00000000-0000-0000-0000-000000000001 -- web                                                                
       4850dd3d-9f7c-4e2f-8b43-27f1a0111376 -- emmet@emmet-VirtualBox:~/conp-dataset/projects/BigBrain_3DSurfaces

 web: ftp://bigbrain.loris.ca/BigBrainRelease.2015/3D_Surfaces/CerebralCortex/MNI-obj/white_right_327680.obj      
ok                                                                                                             

Even though I get the same result, now the repo has been silently upgraded to version 8. Future datalad commands will fail:

unix> singularity exec ../datalad.sif git-annex whereis bigbrain.loris.ca_BigBrainRelease.2015_3D_Surfaces_CerebralCortex_MNI_obj_white_right_327680.obj                                         
git-annex: Repository version 8 is not supported. Upgrade git-annex.

unix> ../datalad.sif get bigbrain.loris.ca_BigBrainRelease.2015_3D_Surfaces_CerebralCortex_MNI_obj_white_right_327680.obj
CommandError: 'git -c annex.merge-annex-branches=false annex find -c annex.dotfiles=true -c annex.retry=3 --json --json-error-messages --not --in . -- bigbrain.loris.ca_BigBrainRelease.2015_3D_Surfaces_CerebralCortex_MNI_obj_white_right_327680.obj' failed with exitcode 1 under /tmp/X/BigBrain_3DSurfaces
git-annex: Repository version 8 is not supported. Upgrade git-annex.

**Comment by yarikoptic** [comment]
```
singularity pull datalad.sif shub://datalad/datalad:fullmaster

This creates the file 'datalad.sif' which is a self-contained, self-running container with
datalad 0.13 and git-annex 7.20:

unix> ./datalad.sif --version
datalad 0.13.0rc2
```
we should really kill that singularity image or make it build/update automagically ... I remember trying to resurrect that but forgot why I stopped.  Better use some proper distribution of datalad (although yeah -- we still have that older version in neurodebian -- will be uploading fresh release shortly).  https://github.com/datalad/datalad-installer/ could be of help if you do not have some conda already installed.

Re auto-upgrades: you can disable those with 
```
[annex]
    autoupgraderepository = false
```
in your `~/.gitconfig` or for specific repos.

Not sure what we could otherwise do here.

**Comment by yarikoptic** [comment]
well -- besides
- [ ] uploading new git-annex-standalone to neurodebian
- [ ] updating all those singularity images "just in case"

I will close this issue whenever both are "done"

**Comment by jbpoline** [comment]
Many thanks - super useful - I alerted @prioux of this

**Comment by prioux** [comment]
The .gitconfig setting is nice for interactive users, but not that much useful when datalad is invoked as part of an automated system that doesn't even have a proper $HOME (e.g. when $HOME is mount-binded to something else for the durection of the process). I'd really prefer to have datalad work all by itself properly just with whatever it can reach through its system $PATH.

**Comment by yarikoptic** [comment]
I am still not sure what would you like datalad to do or not to do, e.g. "forbid annex to auto-upgrade repositories from older to newer version"?  

this particular problem does not manifest itself if you do not use older git annex after having used a newer one which automigrated the dataset.

**Comment by prioux** [comment]
I've not asked anything to be solved; it's not a DataLad problem that needs to be fixed. It's just a configuration/installation issue to be aware of. I created the description of the issue just to let people know about it (because it can be mysterious as to why things start to fail if you're not aware of it) and sent this by email to a select set of colleagues because I was asked to document it. That email ended up here on github as an issue, indirectly. Feel free to close it if like me you think it shouldn't be here, @yarikoptic .

**Comment by yarikoptic** [comment]
I think it is good indeed to have it here so others could find.  We have a number of similar `FOI` (for our information) or labeled `question` issues, which we open and then close if there is nothing to be done for them on datalad side.  I guess I will indeed close this one now on this note ;)

Cheers,
