### ISSUE TITLE
Publish doesn't use ssh connection manager properly (at all)

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#544]

**Comment by bpoldrack** [comment]
Did you experience something, that led to the conclusion there are no shared connections or do you conclude from the fact, that there is nothing explicitly called within the code for `publish`?
The latter should not be necessary. That's what the approach on shared connections is about. ;)

**Comment by hanke** [comment]
I had to enter a password four times ;-)

**Comment by bpoldrack** [comment]
Okay, figured it out. The new RIs were simply not introduced to GitRepo yet. So it didn't know, that `localhost:/path` is considered to be a SSH URL. Fixing it.

**Comment by hanke** [comment]
Also fixed in #550
