### ISSUE TITLE
FOI: rich library to build terminal UIs

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5443]
Saw a tweet pointing to this article
https://www.willmcgugan.com/blog/tech/post/building-rich-terminal-dashboards/
about https://github.com/willmcgugan/rich

Could come handy for datalad fuse based shell or an alternative display of logs + results (could build hierarchy across datasets etc)

**Comment by bpoldrack** [comment]
That looks really nice indeed.

**Comment by yarikoptic** [comment]
ok, announced etc
