### ISSUE TITLE
branches in nested dataset

### ISSUE THREAD

**Issue by bpinsard** [datalad/datalad#5449]
#### What is the problem?

This is not specifically a datalad problem, but I think that the nesting introduced by datalad and git-annex specificities make my question more pertinent here.
I am trying to setup branches to track an evolving super-dataset with multiple sub-datasets.
My goal is that when switching branch in the super-dataset, it recurses in the submodules to checkout a branch with the same name.
I set akk the submodule to track branch `.` which is to have submodule track the branch of the parent git.
`git submodule foreach --recursive 'git config -f $toplevel/.gitmodules submodule.$sm_path.branch .'`
I then created a branch `main` in each subdataset recursively.
I then tried:
`git checkout --recurse-submodules main `
but then only the parent dataset has changed branch, not the submodules.
I tried :
```$ git checkout --recurse-submodules --force  main
Migrating git directory of 'anat' from
'/home/basile/data/tests/cneuromod2/anat/.git' to
'/home/basile/data/tests/cneuromod2/.git/modules/anat'
Already on 'main'
Your branch is up to date with 'origin/main'.
``` 
Which effectively switched the submodule to a detached head (not ideal), but, as you can see, triggered an `absorbgitdirs` (not sure why), which of course breaks the git-annex symlinks.
This took me again to git-submodule man page to discover that "absorbed" .git dirs is the normal git behavior !?:
> A repository that was cloned independently and later added as a submodule or old setups have the submodules git directory inside the submodule instead of embedded into the superprojects git directory.
I am concerned that git will blindly decide to absorb git-dirs when running basic commands and that users will "loose" access to their annexed data. 
 
Do you have any experience or advice on how to cleanly set the branch tracking?
Thanks!

**Comment by kyleam** [comment]
> This is not specifically a datalad problem, but I think that the nesting introduced by datalad and git-annex specificities make my question more pertinent here.

I think this is a good place to discuss this.  Both git-annex and datalad override git's default behavior in different ways, and it's all fairly confusing.

> My goal is that when switching branch in the super-dataset, it recurses in the submodules to checkout a branch with the same name.
> I set akk the submodule to track branch `.` which is to have submodule track the branch of the parent git.

Git only cares about `submodule.<name>.branch` when updating the submodule from the remote (`update --remote`), not for switching branches or checking out the registered commit.

> `git checkout --recurse-submodules main `
> but then only the parent dataset has changed branch, not the submodules.
[...]
> Which effectively switched the submodule to a detached head (not ideal),

Right, `checkout --recurse-submodules` checks out the commit for each submodule that's registered in the parent dataset.  It doesn't concern itself with the submodule's branch.

> but, as you can see, triggered an `absorbgitdirs` (not sure why), which of course breaks the git-annex symlinks.
> This took me again to git-submodule man page to discover that "absorbed" .git dirs is the normal git behavior !?:

Yep, plain git-annex handles this by converting the .git file into a symbolic link pointing to the same `modules/` directory that the .git file did.  DataLad, on the other hand, will move the `modules/` directory so that it is a regular `.git/` directory for the submodule when adding a new subdataset or installing one.

> I am concerned that git will blindly decide to absorb git-dirs when running basic commands and that users will "loose" access to their annexed data.

AFAICT, aside from a direct call to `git submodule absorbgitdirs`, the main path that can trigger `absorbgitdirs` is any code path that ends up calling `submodule_move_head`, which I think is (at least at the moment) limited to using `--recurse-submodules` with commands.  If you `git checkout x && git submodule update` (with the default `submodule.<name>.update` value), you'll still have the detached HEAD state you described, but the submodules' .git/ directories shouldn't be absorbed.

And, while of course not ideal, if a directory does get absorbed, git-annex should replace it with a symbolic link.  After that, `git submodule absorbgitdirs` shouldn't touch it.

**Comment by bpinsard** [comment]
Thanks so much for the detailed explanation!
I will try with the checkout + submodule update.

> And, while of course not ideal, if a directory does get absorbed, git-annex should replace it with a symbolic link. After that, git submodule absorbgitdirs shouldn't touch it.

```
$ cat  anat/.git
gitdir: ../.git/modules/anat
```

It seems like the absorption already produce a text file that point to the absorbed module but in a git way?, and git-annex symlinks won't work with that text file. Does git-annex fix-it afterward when calling any datalad command?
Anyway, I will avoid having the module absorbed by not calling `--recurse-submodules`.

Thanks for your help.

**Comment by kyleam** [comment]
> It seems like the absorption already produce a text file that point to the absorbed module but in a git way?

Right, that's the "git file" that's used with absorbed submodules as well worktrees (as in those produced by `git worktree`).

> and git-annex symlinks won't work with that text file. Does git-annex fix-it afterward when calling any datalad command?

Not sure about "any", but I think most git-annex commands that datalad invokes would trigger the fixup.

<details>
<summary>example with datalad-get</summary>

```sh
set -eu

cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-XXXXXXX)"

datalad create a
(
    cd a
    echo one >one
    datalad save
)

datalad create b

(
    cd b
    datalad clone -d. ../a sub

    git checkout -b other
    echo two >sub/two
    datalad save -r

    git checkout --recurse-submodules -

    cat sub/.git
    datalad get sub/one
    readlink sub/.git
)
```

```
[...]
Migrating git directory of 'sub' from
'/tmp/dl-CTygTNx/b/sub/.git' to
'/tmp/dl-CTygTNx/b/.git/modules/sub'
Switched to branch 'master'
gitdir: ../.git/modules/sub
get(ok): sub/one (file) [from origin...]
action summary:
  get (notneeded: 1, ok: 1)
../.git/modules/sub
```

</details>

**Comment by bpinsard** [comment]
Ok perfect! Thanks!

**Comment by kyleam** [comment]
I said:

> Not sure about "any", [...]

Just to follow up on this, I think invoking any git-annex command in a repo that already has git-annex initialized should trigger the fixup.  From git-annex's Annex/Fixup.hs:

```haskell
{- Submodules have their gitdir containing ".git/modules/", and
 - have core.worktree set, and also have a .git file in the top
 - of the repo. We need to unset core.worktree, and change the .git
 - file into a symlink to the git directory. This way, annex symlinks will be
 - of the usual .git/annex/object form, and will consistently work
 - whether a repo is used as a submodule or not, and wheverever the
 - submodule is mounted.
 -
 - git-worktree directories have a .git file.
 - That needs to be converted to a symlink, and .git/annex made a symlink
 - to the main repository's git-annex directory.
 - The worktree shares git config with the main repository, so the same
 - annex uuid and other configuration will be used in the worktree as in
 - the main repository.
 -
 - git clone or init with --separate-git-dir similarly makes a .git file,
 - which in that case points to a different git directory. It's
 - also converted to a symlink so links to .git/annex will work. 
 - 
 - When the filesystem doesn't support symlinks, we cannot make .git
 - into a symlink. But we don't need too, since the repo will use adjusted
 - unlocked branches.
 -
 - Don't do any of this if the repo has not been initialized for git-annex
 - use yet.
 -}
fixupUnusualRepos :: Repo -> GitConfig -> IO Repo
```

**Comment by yarikoptic** [comment]
eh, datalad is yet to establish convenience(s) to checkout/reset to different states of the entire dataset hierarchy.  Just establishing a connection: #1424 is one of still open issues
