### ISSUE TITLE
save() auto-adds untracked files -- is that what we want?

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#546]
So far I had conceptualized the addition of content to a dataset as the job of `install()` -- which it does fine. However, now `save()` can do it too: it runs `git annex add .` followed by `git add .` (based on my recommendation). The only use case that I can see where `install` is still required for adding content to a dataset is when file should be added to Git directly.

Now the question: Really?

This implies that we cannot have untracked content by default with `save` (see --auto-add-changes=True). More general, it seems to communicate that we can have two ways of dealing with dataset changes:

1. I don't give a fuck: `save -a`
2. I am picky: `install <path>`, `save --no-a`

Now that I have written that it seems less disturbing than before, but we should still be on the same page prior setting it in stone @bpoldrack @yarikoptic

**Comment by yarikoptic** [comment]
"not sure"
all the magic is heavily alienating git-savvy users.  'install' command in general doesn't need to commit. install in sense of 'git annex get' doesn't even change anything in the index, and just causes git-annex branch progression.   so for a git-savvy user having no automagic commit upon install could be beneficial may be?  
automagically adding untracked content -- I can only imagine how many folks could scream after bunch of intermediate results get automagically added.  May be default could be the `--no-a` and `-a` option could be the one to add everything, including untracked (but hopefully still warranting .gitignore) into repo?

**Comment by hanke** [comment]
1st: I am strongly in favor of "never automatic commits" in any case.

2nd: not clear what you mean.

Sure thing .gitignore is tracked. Git savvy users know `git add`. But what shall the normal users do? How do they get to say what to commit and what not?

**Comment by yarikoptic** [comment]
logically "save [files]" could be the the interface specifying which files to "save"

**Comment by hanke** [comment]
Sounds sensible.

**Comment by hanke** [comment]
As this was a "question" and the answer is now available in code I am closing this one.
