### ISSUE TITLE
appveyor needs "assistance"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5467]
recently the number of failed to even start OSX workers increased.  see e.g. https://ci.appveyor.com/project/mih/datalad/builds/38069462 where even ubuntu freaked out.  IMHO it needs to be troubleshooted.  Since a paid plan, @mih - could you please reach out to appveyor support?

**Comment by mih** [comment]
https://help.appveyor.com/discussions/problems/29047-cannot-assign-job-to-cloudsgroups-macos-pro

**Comment by mih** [comment]
I think we can close this. The story is behind the support forum link. The issue still shows sporadicly, but there is nothing else TODO.
