### ISSUE TITLE
Creating own metadata for datasets - Is there any doc?

### ISSUE THREAD

**Issue by k-sap** [datalad/datalad#5470]
#### What is the problem?
In the docs there is a description of git-annex file-level metadata and other domain specific metadata formats which are then extracted by datalad.
I'd like to use my own metadata schema (it could  be a simple json) file with basic info about all datasets I create, e.g. for filtering my subdatasets by some criteria, share metadata while cloning datasets.

I couldn't find enough information for that use case in documentation. Is there something I've missed? Is there some format/support for that? Should I just use git-annex metadata?

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
My work is under development.

**Comment by yarikoptic** [comment]
http://docs.datalad.org/en/stable/metadata.html and see sample provided with datalad extractors at https://github.com/datalad/datalad/tree/master/datalad/metadata/extractors .
RFing of metadata storage and handling is ongoing as part of the https://github.com/datalad/datalad-metalad/ but I believe you will be able to reuse extractor(s) you create for current "good old" metadata handling in datalad.
To make your extractor seamlessly available to datalad, you might want to consider developing your project as a datalad extension (create new from https://github.com/datalad/datalad-extension-template) see e.g. https://github.com/datalad/datalad-neuroimaging/tree/master/datalad_neuroimaging/extractors extension providing its own extractors.

**Comment by k-sap** [comment]
Thank you for your response. I can write my own extractor. But can I just use one of the sample ones you mentioned? (https://github.com/datalad/datalad/tree/master/datalad/metadata/extractors) 

I just need a simple dataset-level solution.

**Comment by k-sap** [comment]
Analysing more in depth the list of extractors... I suppose that RFC822-compliant metadata or Friction-less data packages could be a simple solution?

**Comment by yarikoptic** [comment]
Sure thing you could just try use of the existing extractors if you have metadata in any of those formats, and our extractors cover the needed metadata fields you have.
