### ISSUE TITLE
Uninstall/remove: drop only local keys

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5472]
I am not sure how `annex drop <path>` is implemented, but I recently uninstalled a few datasets that had no local keys whatsoever (`git annex whereis --in here` had no output), but uninstall without `--nocheck` was kinda slow.

Possibly, things could be faster when calling `git annex drop --in here <paths>` instead.

Also, with an `ephemeral` clone the availability check is pointless, and maybe counterproductive. We should think about making `--nocheck` standard behavior for such clones.

**Comment by bpoldrack** [comment]
> Also, with an ephemeral clone the availability check is pointless, and maybe counterproductive. We should think about making --nocheck standard behavior for such clones.

Not sure about this part. `--ephemeral` doesn't suggest you don't want to push new keys elsewhere first anymore than any another clone, IMO. I think we would still want to check whether or not there's more than the local copy we are about to kill.

**Comment by mih** [comment]
As noted above, `drop` has an improved implementation for all this and was released with 0.16. Given that `uninstall` is now only a deprecated shim, there is little desire to change anything here specifically for `uninstall`. Closing.
