### ISSUE TITLE
create-sibling-ria changes ssh username

### ISSUE THREAD

**Issue by mattcieslak** [datalad/datalad#5475]
#### What is the problem?
When trying to create a ria sibling the user name gets switched from the name in the ssh url to the current user name

#### What steps will reproduce the problem?

```
[rbc@cubic-login1 bidsdatasets]$ datalad create-sibling-ria \
    --name pmacs-ria ria+ssh://user2@scisub.pmacs.upenn.edu:/project/RBC/BIDS/CCNP
rbc@scisub.pmacs.upenn.edu's password:   
```

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.14.0
#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
No luck on create-sibling-ria :(

Is there some place I need to specify the user name for the remote server? It's replacing the user in the connection string with the name of the current user that's running the commands.

**Comment by bpoldrack** [comment]
> Is there some place I need to specify the user name for the remote server?

Yes and no. I do consider this a bug, so in that sense you're doing it right and datalad is at fault. However, while I fix it there's a workaround for you that should work: You could specify the user for that host in your ssh config instead, so ssh figures that out when called by datalad with a URL w/o a specified user. That's how I do it (and probably why we failed to run into it).

**Comment by bpoldrack** [comment]
In case that's not entirely clear to you, @mattcieslak :

Your `~/.ssh/config` should have a section like that:

```
Host scisub.pmacs.upenn.edu
    User user2
```

With that, you should be able to run: `datalad create-sibling-ria --name pmacs-ria ria+ssh://scisub.pmacs.upenn.edu:/project/RBC/BIDS/CCNP` instead of the call you mentioned.

**Comment by mattcieslak** [comment]
Confirmed- this works. Thanks for your help @bpoldrack!

**Comment by apirogov** [comment]
I've also run into this error and came up with this workaround, but would be happy if it is actually fixed!

**Comment by mih** [comment]
@apirogov @mattcieslak I am looking into this now. Sorry for the delay.

**Comment by mih** [comment]
The particular use of `datalad.customremotes.ria_utils.verify_ria_url()` is at fault here. This function (among other stuff) returns the hostname, which is used for further SSH calls. However, it strips the username. Technically it does what it promises in its docs, but what it does is undesirable.

Will look into a fix. It is used in `create-sibling-ria`, but also in the ORA special remote implementation.
