### ISSUE TITLE
Call to datalad.api.save() stall forever in a Django app

### ISSUE THREAD

**Issue by 20** [datalad/datalad#5482]
#### What is the problem?
Call to datalad.api.save() stall forever
I'm using python datalad.api in a simple new django (3.1) app .. When I call save() the process stall..
Trying to debug I saw that git process dies while reading buffer.  
If I try saving the same dataset using same repository with bash shell and ipython, it works normally.

#### What steps will reproduce the problem?

```python
from datalad.api import Dataset
import pdb
from datalad import lgr

from . import utils

from django.utils.translation import ugettext_lazy as _

import os
import shutil
import logging 

logger = logging.getLogger(__name__)

def dataset_update(content):
    try:
        content_new_path = utils.get_content_path(content)
        os.makedirs(os.path.dirname(content_new_path), exist_ok=True)
        shutil.move(content.artefact.path, os.path.join(
                content_new_path, content.get_human_id))
    except Exception as e:
        logger.info(_("Something wrong during file move execution: "
                      + e.__doc__))        
    try:
        lgr.setLevel(2)
        pdb.set_trace()
        ds = Dataset(path=content.repository.path)    
        os.environ['GIT_COMMITTER_NAME'] = content.mocambola.username
        os.environ['GIT_COMMITTER_EMAIL'] = content.mocambola.email
        logger.info(os.environ['GIT_COMMITTER_NAME']+'and'+os.environ['GIT_COMMITTER_EMAIL'])
        ds.save()
    except Exception as e:
        logger.info(_("Something happened during datalad execution: "
                      + e.__doc__))   
```

**Full code and installation:**
- git clone https://labmocambos.taina.net.br/npdd/baobaxiaa
- cd baobaxiaa/baobaxia
- docker-compose up --build
- docker exec -it baobaxiaa_baobaxia_1 /bin/bash python3 manage.py loaddata apps/bbx/fixtures/dados_iniciais.json
- You can login in django admin with user:livre pass:livre 
- Uncomment call to dataset_update() on baobaxia/apps/bbx/models.py at the end of BaseContent save()

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

<details>
<summary>datalad wtf -D html_details</summary> 

DataLad 0.14.0 WTF (configuration, credentials, datalad, dataset, dependencies, environment, extensions, git-annex, location, metadata_extractors, metadata_indexers, python, system)</summary>

# WTF
## credentials 
  - keyring: 
    - active_backends: 
      - SecretService Keyring
      - EncryptedKeyring with [PBKDF2] AES256.CFB v.1.0 at /home/befree/.local/share/python_keyring/crypted_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at /home/befree/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/befree/.local/share/python_keyring/keyringrc.cfg
    - data_root: /home/befree/.local/share/python_keyring
## datalad 
  - full_version: 0.14.0
  - version: 0.14.0
## dataset 
  - id: c936b3b0-1a66-478e-be8f-81440bd7a22d
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /data/bbx/repositories/rede-mocambos-123456
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.4.3
  - appdirs: 1.4.3
  - boto: 2.44.0
  - cmd:7z: 16.02
  - cmd:annex: 7.20190819+git2-g908476a9b-1~ndall+1
  - cmd:bundled-git: 2.20.1
  - cmd:git: 2.20.1
  - cmd:system-git: 2.24.0
  - cmd:system-ssh: 7.9p1
  - exifread: 2.1.2
  - humanize: 0.5.1
  - iso8601: 0.1.11
  - keyring: 17.1.1
  - keyrings.alt: 3.1.1
  - msgpack: 0.5.6
  - mutagen: 1.40.0
  - requests: 2.21.0
  - wrapt: 1.10.11
## environment 
  - LANG: it_IT.UTF-8
  - PATH: /home/befree/.yarn/bin:/home/befree/.config/yarn/global/node_modules/.bin:/home/befree/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/sbin
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - local repository version: 5
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions: 
    - 5
    - 7
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  - version: 7.20190819+git2-g908476a9b-1~ndall+1
## location 
  - path: /data/bbx/repositories/rede-mocambos-123456
  - type: dataset
## metadata_extractors 
  - annex (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp (datalad 0.14.0): 
    - distribution: datalad 0.14.0
    - load_error: None
    - module: datalad.metadata.extractors.xmp
    - version: None
## python 
  - implementation: CPython
  - version: 3.7.3
## system 
  - distribution: LinuxMint/4/debbie
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 320
  - name: Linux
  - release: 4.19.0-14-amd64
  - type: posix
  - version: #1 SMP Debian 4.19.171-2 (2021-01-30)
</details>

#### Is there anything else that would be useful to know in this context?

That's the python log:

```
[Level 2] Entered eval_func for <function Save.__call__ at 0x7fd18b6bc7b8> 
Entered eval_func for <function Save.__call__ at 0x7fd18b6bc7b8>
[DEBUG  ] Determined class of decorated function: <class 'datalad.core.local.save.Save'> 
Determined class of decorated function: <class 'datalad.core.local.save.Save'>
[Level 5] Detected <class 'datalad.support.annexrepo.AnnexRepo'> at /data/bbx/repositories/rede-mocambos-123456 
Detected <class 'datalad.support.annexrepo.AnnexRepo'> at /data/bbx/repositories/rede-mocambos-123456
[Level 5] Requested to provide version for cmd:git 
Requested to provide version for cmd:git
[Level 5] Requested to provide version for cmd:git 
Requested to provide version for cmd:git
[Level 5] Found 0 previous connections 
Found 0 previous connections
[DEBUG  ] Async run ['git', 'config', '-z', '-l', '--show-origin'] 
Async run ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG  ] Launching process ['git', 'config', '-z', '-l', '--show-origin'] 
Launching process ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG  ] Process 31813 started 
Process 31813 started
[DEBUG  ] Waiting for process 31813 to complete 
Waiting for process 31813 to complete
[Level 5] Read 400 bytes from 31813[stdout] 
Read 400 bytes from 31813[stdout]
```

with process 31813 beeing:
`[git] <defunct>`

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
I've been experiencing a bit. I already use git-annex and we made a software, Baobáxia, based on it. 
We would like to use datalad in a new version/implementation of Baobáxia.

Thanks!

**Comment by yarikoptic** [comment]
<details>
<summary>docker-compose up --build isn't happy with me</summary> 

```shell
Attaching to baobaxiaa_baobaxia_1
baobaxia_1  | Make migrations...
baobaxia_1  | Traceback (most recent call last):
baobaxia_1  |   File "./manage.py", line 15, in <module>
baobaxia_1  |     execute_from_command_line(sys.argv)
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
baobaxia_1  |     utility.execute()
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 377, in execute
baobaxia_1  |     django.setup()
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 24, in setup
baobaxia_1  |     apps.populate(settings.INSTALLED_APPS)
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 114, in populate
baobaxia_1  |     app_config.import_models()
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/apps/config.py", line 211, in import_models
baobaxia_1  |     self.models_module = import_module(models_module_name)
baobaxia_1  |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
baobaxia_1  |     return _bootstrap._gcd_import(name[level:], package, level)
baobaxia_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
baobaxia_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
baobaxia_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
baobaxia_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
baobaxia_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
baobaxia_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/models.py", line 2, in <module>
baobaxia_1  |     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/base_user.py", line 48, in <module>
baobaxia_1  |     class AbstractBaseUser(models.Model):
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 122, in __new__
baobaxia_1  |     new_class.add_to_class('_meta', Options(meta, app_label))
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 326, in add_to_class
baobaxia_1  |     value.contribute_to_class(cls, name)
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/db/models/options.py", line 206, in contribute_to_class
baobaxia_1  |     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/db/__init__.py", line 28, in __getattr__
baobaxia_1  |     return getattr(connections[DEFAULT_DB_ALIAS], item)
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 214, in __getitem__
baobaxia_1  |     backend = load_backend(db['ENGINE'])
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 111, in load_backend
baobaxia_1  |     return import_module('%s.base' % backend_name)
baobaxia_1  |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
baobaxia_1  |     return _bootstrap._gcd_import(name[level:], package, level)
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/db/backends/spatialite/base.py", line 10, in <module>
baobaxia_1  |     from .features import DatabaseFeatures
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/db/backends/spatialite/features.py", line 1, in <module>
baobaxia_1  |     from django.contrib.gis.db.backends.base.features import BaseSpatialFeatures
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/db/backends/base/features.py", line 3, in <module>
baobaxia_1  |     from django.contrib.gis.db import models
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/db/models/__init__.py", line 3, in <module>
baobaxia_1  |     import django.contrib.gis.db.models.functions  # NOQA
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/db/models/functions.py", line 3, in <module>
baobaxia_1  |     from django.contrib.gis.db.models.fields import BaseSpatialField, GeometryField
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/db/models/fields.py", line 3, in <module>
baobaxia_1  |     from django.contrib.gis import forms, gdal
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/forms/__init__.py", line 3, in <module>
baobaxia_1  |     from .fields import (  # NOQA
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/forms/fields.py", line 2, in <module>
baobaxia_1  |     from django.contrib.gis.gdal import GDALException
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
baobaxia_1  |     from django.contrib.gis.gdal.datasource import DataSource
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
baobaxia_1  |     from django.contrib.gis.gdal.driver import Driver
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
baobaxia_1  |     from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
baobaxia_1  |     from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
baobaxia_1  |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/gis/gdal/libgdal.py", line 46, in <module>
baobaxia_1  |     % '", "'.join(lib_names)
baobaxia_1  | django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal3.1.0", "gdal3.0.0", "gdal2.4.0", "gdal2.3.0", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.

```
</details>

**Comment by 20** [comment]
Sorry.. I updated some package dependency on dockerfile.. 
It should work now!

**Comment by yarikoptic** [comment]
<details>
<summary>going to django admin interface leads to another</summary> 

```shell

```
</details>

<details>
<summary>trying to run command provided (fixing it up a bit) leads to another</summary> 

```shell
$> docker exec -it baobaxiaa_baobaxia_1 /bin/bash -c 'python3 manage.py loaddata apps/bbx/fixtures/dados_iniciais.json'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: main.bbx_mocambola

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/loaddata.py", line 181, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python3.7/dist-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 792, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 873, in _save_table
    forced_update)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 926, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 803, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1522, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: Problem installing fixture '/var/www/baobaxia/apps/bbx/fixtures/dados_iniciais.json': Could not load admin.LogEntry(pk=1): no such table: main.bbx_mocambola

```
</details>

**Comment by 20** [comment]
Thanks @yarikoptic .. 

I'm resolving my own Docker / Django issues and investigate more this problem.

Closing the issue at moment, if it needs I'll reopen later.. 
Thanks for your time!
