### ISSUE TITLE
rerun: do not delete parent directories of outputs if those are otherwise empty

### ISSUE THREAD

**Issue by matrss** [datalad/datalad#5486]
#### What is the problem?
`datalad rerun` deletes parent directories of outputs if those are otherwise empty, resulting in failing scripts if a parent directory is not explicitly created.

#### What steps will reproduce the problem?
Create a script that produces some output, e.g. `code/produce-output.sh`:
```
#!/bin/sh

echo "test" > outputs/output1.txt
echo "test2" > outputs/output2.txt
```
Create the `outputs` directory, then run the script:
```
datalad run --output "outputs/*.txt" "code/produce-output.sh"
```
At this point a rerun works fine.

If we now clone the repository so that the outputs are not in the local annex, a rerun deletes the `*.txt` symlinks as well as the parent directory `outputs/`, which leads to a failing script as it does not create the directory itself. As soon as at least one of the outputs is in the local annex, so e.g. after a `datalad get outputs/output1.txt`, the rerun works again.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
Version 0.14.0 on Linux (NixOS) installed through conda

#### Is there anything else that would be useful to know in this context?
I am not sure if this might even be intended behaviour, but as a naive user I would assume prior `datalad get`'s to not have an influence on the outcome of reruns.

**Comment by kyleam** [comment]
Thanks for the report and the reproducer.

> I am not sure if this might even be intended behaviour, [...]

Removing outputs that aren't present is intended, but this interaction with the container directory is not.  The output is removed with `git rm`, and that will wipe out empty directories.

I think this should be addressed, though I haven't started thinking about the best approach yet.

**Comment by matrss** [comment]
> Removing outputs that aren't present is intended, but this interaction with the containing directory is not.
That's what I thought as well.

A fairly straight forward approach would be to make it a two step process and first `git rm --cached` the files, then `rm`'ing
them. This would leave the git repo in the same state as after the current `git rm`, but keeps the `outputs` directory in the working directory. Haven't thought about every corner case of possible outputs though.

At it's root, the problem seems to be that git does not track directories by themselves. The "standard" solution to keep a directory in git afaict is using a `.gitkeep` hidden file. Maybe that's also an option here.

**Comment by kyleam** [comment]
> A fairly straight forward approach would be to make it a two step process and first `git rm --cached` the files, then `rm`'ing them.

It looks like we can get away with just a plain `rm`.  Proposed in gh-5492.

> At it's root, the problem seems to be that git does not track directories by themselves.

Hmm, even still, `git rm` doesn't _have_ to remove empty directories (and, as mentioned in [this thread][1] discussing the `git rm` behavior, there was a time long ago when it left empty leading directories around).  But, yeah, conceptually I think it's rooted in that, and the behavior is consistent with how other commands treat empty directories.

Also, note that `rerun --onto` checks out a different tree, which as expected drops a directory in the current tree that doesn't have any tracked files in the target tree.  But unlike what you report, the tree-switching case is probably not surprising, and I don't view it as something to be addressed.

> The "standard" solution to keep a directory in git afaict is using a .gitkeep hidden file. Maybe that's also an option here.

That's good to mention.  If someone wanted to do that in their dataset, they of course can, but I don't see that as something datalad itself would manage.

[1]: https://lore.kernel.org/git/20180606200137.GJ3094@zaya.teonanacatl.net/T/#u
