### ISSUE TITLE
python api call datalad.config.set - cannot add quoted string

### ISSUE THREAD

**Issue by pvavra** [datalad/datalad#5493]
Using the `datalad.config.ConfigManager` api, I would like to register a custom procedure to the dataset config. As per [Handbook](https://handbook.datalad.org/en/latest/basics/101-124-procedures.html), this should include both a `format-call` and `help`, both of which should be quoted strings. The example in the handbook is:
```
[datalad "procedures.<NAME>"]
   help = "This is a string to describe what the procedure does"
   call-format = "python {script} {ds} {somearg1} {somearg2}"
```

However, I don't know how to make the quotes to be passed on by the api, without them getting escaped in the process.
I can think of potentially 2 ways, but none work as intended:
```
from datalad.distribution.dataset import require_dataset
dataset = require_dataset(
      'testdataset',
      check_installed=True)
cfg = dataset.config
cfg.set('datalad.hirni.procedures.my-new-procedure.help',
        "simply pass a string with spaces")
cfg.set('datalad.hirni.procedures.my-new-procedure2.help',
        '"wrap the string in single quotes to include double quotes"')
cfg.set('datalad.hirni.procedures.my-new-procedure3.help',
        "\"or using escaped double-quotes..\"")
```
will produce 
```
[datalad "hirni.procedures.my-new-procedure"]
	help = simply pass a string with spaces
[datalad "hirni.procedures.my-new-procedure2"]
	help = \"wrap the string in single quotes to include double quotes\"
[datalad "hirni.procedures.my-new-procedure3"]
	help = \"or using escaped double-quotes..\"
```

So none are simply quoted with out the escaping backslash.

If there is a way to get this done, I guess it would be handy to include it in the docs of `datalad.config.ConfigHandler.set` and `datalad.config.ConfigHandler.add` ([docs](http://docs.datalad.org/en/stable/generated/datalad.config.html) do not mention anything, as far as I can tell).

tested with datalad version 0.14.0 on centOS.

**Comment by bpoldrack** [comment]
While it is an interesting observation, that we can't achieve the quotes via `ConfigManager`, I think this is mostly a misunderstanding from the respective handbook section. The quotes should not be needed. When reading such configs, the quotes make no difference. So, simply passing a string should do the job, @pvavra.

However, the handbook section is confusing in this regard. It does not seem to explicitly say the quotes are necessary, but it does show a config file with the quotes, while the later shown call `git-config` call to set the config would NOT result in those quotes.

I'll open an issue with the handbook.

**Comment by bpoldrack** [comment]
Note, that when you really need quotes within the value, the resulting `\"` in the config file, that you achieved in two ways, actually is what you'd want:

```
[dummy]
    first = some not actually "quoted" value
    second = some \"quoted\" value
```
=>

```
$> git config dummy.first
some not actually quoted value
$> git config dummy.second
some "quoted" value
```
So, you did it right - it's just needless in that case, @pvavra!
