### ISSUE TITLE
`Credential` (or elsewhere) should sanitize names

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5495]
A credential name is presently described as:

```
name : str
            Name of the credential, as it would be identified by in the centralized
            storage of credentials
 ```

However, since https://github.com/datalad/datalad/pull/5491 it is now more obvious that the provided name needs to be chosen carefully. The keyring wrapper will perform a lookup of an environment variable that could provide credentials. FOr that lookup to work, the name must be a valid environment variable name(part). Using hostnames, which are not too far fetched for a name will not work, because they contain a dot (or two), which most shells are not happy with. Given that these implications are all but obvious, DataLad should take care of this, IMHO.

**Comment by mih** [comment]
Working on #5796 and #5028 I came to the realization that naming a credential is a major obstacle in the design of our system. These names are not exposed, (supposed to be) internally generated, but simultaneously crucial for lookup and maintenance of credentials in a store. FTR: Git does not name credentials, but credentials are defined by the URLs they shall be used for (by default host-specific, on-demand host+path specific).

**Comment by bpoldrack** [comment]
While I agree, that current datalad credential system is sort of an "overfit" to keyring and needs redesign, I want to leave a trace here re credential labels + URLs:

The current implementation isn't meant for credentials to work w/o providers. Hence, the connection between a label and a UR/host is to be made by a provider config. This is relevant as the datalad git-credential helper approach in #5796 ATM uses the URL as the label in order to map git's approach to datalad's. Lookup/mapping could make the detour via providers, though.

**Comment by mih** [comment]
Cross-linking with #4981 that confirms the statement

> The current implementation isn't meant for credentials to work w/o providers.

**Comment by mih** [comment]
With #6555 credential names are actually no longer restricted (practically) -- only nullbyte and newline are illegal.

Different story for credential property names, such as `key_id`, which were not expressible via ENV overrides before. SUch names must no be valid git config variables (only alphanum and dashes). As a consequence, these are automatically compliant with ENV overrides.

**Comment by mih** [comment]
I am closing this issue. The credential system provided by https://github.com/datalad/datalad-next does not have this issue and I am not aware of any plans to address this for the system in core.
