### ISSUE TITLE
update: `--merge reset-hard`? (to be used with `--follow parentds`)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5498]
#### What is the problem?

While trying to "mirror" existing super-datasets (such as http://github.com/CONP-PCNO/conp-dataset) it is often a case that sub-dataset state cannot be "fast-forwarded" - may be commit was amended or entire state hard-reset to some other point, I don't know.  So it makes `update --merge ff-only --follow parentds` insufficient - it just would error out and I need to do `reset --hard` manually and rerun update.  That forbids automation via CRON job since occasionally fails (marking as severity-important since it is a use case at hand with this issue affecting daily operations).

I think `--follow parentds` (and/or `--follow parentds-lazy` whenever #5474 merged) describe semantic for `follow` quite well, and the notion of "hard resetting" should not be melded into `--follow`.  Rather I feel that `--merge` is the option to add an additional mode to, although `reset-hard` is not really a merge.  So even though `--merge reset-hard` looks odd, I am not sure if it is worth migrating `--merge` into some more descriptive `--changes=(merge|ff|reset-hard)`.

WDYT?

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

0.14.0

**Comment by kyleam** [comment]
> While trying to "mirror" existing super-datasets (such as [http://github.com/CONP-PCNO/conp-dataset](https://github.com/CONP-PCNO/conp-dataset)) it is often a case that sub-dataset state cannot be "fast-forwarded" [...]

For an automated mirroring use case, I'm surprised you don't just embrace the detached heads and go with the standard `git submodule update` (no custom `submodule.<name>.update`).

Anyway, adding a way to "follow by reset rather than merge" sounds fine to me.  For adjusted branches, I think it should just bail, like some other incompatible parts of `update` already do.

> Rather I feel that `--merge` is the option to add an additional mode to, although `reset-hard` is not really a merge. So even though `--merge reset-hard` looks odd, I am not sure if it is worth migrating `--merge` into some more descriptive `--changes=(merge|ff|reset-hard)`.

While I agree with viewing `reset` as an alternative to the current `--merge`, my guess is that `--merge reset-hard` would be pretty confusing to most users, to the point where I think migrating would be worth it.  I'm not sure "changes" is a good name.  Ignoring that `update` also handles the top-level dataset, I think `--how` would be okay, since it's a question of how the subdataset update is done.

**Comment by yarikoptic** [comment]
> ... since it's a question of how the subdataset update is done.

Not really. If to be in --merge (or renamed) it would apply also to super dataset - reset to that sibling state (since --follow is applicable to figure out only subdatasets state, for ultimate super it is the state of remote which we merge, ff-only, or hard reset to)

**Comment by yarikoptic** [comment]
If --how, then I would see possible modes `annex-and-remotes-only` (the default since current default as in absense of --merge), `merge`, `ff-only`,`hard-reset` with all later ones implying to include updates to annex and remotes.

**Comment by kyleam** [comment]
> Not really. If to be in --merge (or renamed) it would apply also to super dataset - reset to that sibling state (since --follow is applicable to figure out only subdatasets state, for ultimate super it is the state of remote which we merge, ff-only, or hard reset to)

Thanks for pointing out the my description was too narrow.  Yes, updating subdataset is one of two aspects `--merge` controls.

As I think is laid out pretty well in 94efa8637a (NF: update: Add option to merge in recorded submodule commit, 2020-02-17), `update` is conceptually covering a

```
git pull --no-recurse-submodules [...]
git submodule update --recursive [...]
```

I find the decision to make `--merge` control both these steps confusing/problematic.  I don't think how the current dataset is updated and how subdatasets are updated is inherently coupled.  In the context of a reset action, I think it'd be even more problematic.

**Comment by yarikoptic** [comment]
> I'm surprised you don't just embrace the detached heads and go with the standard git submodule update (no custom submodule.<name>.update).

detached heads would create a problem for re-publishing those datasets to datasets.datalad.org and have them in installable shape which would give branches as if installed from the original superdataset on github.

I thought about it more, and I think even `reset --hard` would not provide a full ultimate solution: for my use case, ideally some mode of `update` should provide behavior which would result in the same outcome as 

    datalad uninstall -r . && git pull --ff-only && datalad install -r .

where `install` would take care about getting the correct current branch for each subdataset and then possibly roll it back to some prior commit (whenever subdataset progressed beyond what its superdataset needs).  But pragmatically aforementioned command would be wasteful and most likely trigger some rate limiting by github sooner or later (especially with some `--jobs`).
