### ISSUE TITLE
Creating RIA sibling fail - Cannot determine special remote name

### ISSUE THREAD

**Issue by MartinGrignard** [datalad/datalad#5500]
#### What is the problem?

Hi :slightly_smiling_face:
After asking about the best Datalad practice [on neurostars](https://neurostars.org/t/datalad-beginner-compressed-sibling-yoda-and-singularity/18467/4), I've tried to setup a RIA store on our storage server through SSH.

Since neither Git nor Git Annex are installed on the remote, I use the `--storage-sibling=only` configuration.

To do so, I tried to use the following command:
```shell
datalad create-sibling-ria \
    --name=ceci \
    --storage-sibling=only \
    ria+ssh://martin@[HOST]:/home/ulg/crc/martin/riastore
```
The result is this error message:
```
[ERROR  ] initremote failed.
| stdout: initremote ceci 
| failed
| 
| stderr: git-annex: Cannot determine special remote name, got: ''
| git-annex: initremote: 1 failed
|  [create-sibling-ria(/media/martin/hdd/scratch/ria_test)] 
create-sibling-ria(error): /media/martin/hdd/scratch/ria_test (dataset) [initremote failed.
stdout: initremote ceci 
failed

stderr: git-annex: Cannot determine special remote name, got: ''
git-annex: initremote: 1 failed
]
```
And on the remote, it produced this folder structure:
```
riastore
├── b1a
│   └── a4d59-a304-47a1-9835-bf6aa79f5458
│       ├── annex
│       │   └── objects
│       ├── archives
│       └── ria-layout-version
├── error_logs
└── ria-layout-version
```

Do you have any clue about what is causing this error?

#### What steps will reproduce the problem?

```shell
datalad create my_dataset
cd my_dataset
datalad create-sibling-ria \
    --name=ceci \
    --storage-sibling=only \
    ria+ssh://[USER]@[HOST]:[PATH]
```

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

- OS: Ubuntu 20.04
- Python: 3.8.5
- Datalad: 0.14.0

#### Have you had any success using DataLad before?

Creating Gitlab siblings and the basic local usage of Datalad work smoothly on the same machine/with the same config.

**Comment by kyleam** [comment]
What git-annex version do you have installed?  Just based on `Cannot determine special remote name, got: ''`, perhaps this is the same issue as gh-4509.

**Comment by MartinGrignard** [comment]
Indeed, I didn't not come across this issue but it looks like the same issue...
My version is `8.20200226-1` and is the default one available in Ubuntu 20.04 as mentioned in gh-4509:
> FTR: I see this bug using the stock git-annex available from Ubuntu 20.04 (see https://ci.appveyor.com/project/mih/appveyor-datalad/build/job/i7hqqmtve72k4myc), so it will be with us for the next 4-5 years.

I'll try upgrading to another version and see if it fixes the problem.
thanks for your answer @kyleam :pray:

**Comment by MartinGrignard** [comment]
I installed the [standalone](https://git-annex.branchable.com/install/Linux_standalone/) in version `8.20210224` and it works now.
Sorry for the non-Datalad related issue.

**Comment by kyleam** [comment]
> I installed the [standalone](https://git-annex.branchable.com/install/Linux_standalone/) in version `8.20210224` and it works now.

Thanks for confirming.

> Sorry for the non-Datalad related issue.

No need to be.  Whether the root of an issue is in datalad, git-annex, or git isn't always very clear, and even if it's not in datalad, we'll often try to work around it when feasible.  As mentioned in gh-4509, I don't think there's much we can do here, but this issue is worth keeping in mind when bumping the minimum git-annex version (gh-5399), and there are also other ideas about failing more helpfully in cases like this (e.g., gh-4272).
