### ISSUE TITLE
git-config produces output that _parse_gitconfig_dump cannot handle

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5502]
This is still a mystery, but this issue is about some aspect that might trigger a `get` failure that was reported to me. The environment is an HPC system with GPFS. Correction: the dataset is located in `/dev/shm/...` (tmpfs), while the user HOME is on GPFS.

```
$ datalad get -n inputs/ukb/sub-3192110
[WARNING] Skip unrecognized .gitmodule specification: rm: cannot remove '/p/home/users/.../.cache/git-annex/locales/97d8e8e226139eee06ab02ccdf2f4c84': Directory not empty=submodule.code/pipeline.path 
[WARNING] Failed to get 'code/pipeline.path', skipping this submodule
```

The specific composition of this warning message makes me suspect that 

```
        out = self.call_git(
            ['config', '-z', '-l', '--file', '.gitmodules'],
            read_only=True)
 ```

in `get.py:_parse_gitmodules()` produces output 

```
rm: cannot remove '/p/home/users/.../.cache/git-annex/locales/97d8e8e226139eee06ab02ccdf2f4c84': Directory not empty
```

That `_parse_gitconfig_dump()` cannot handle, as a result gets mistaken for a misconfiguration, subsequently leading to critical submodule information being ignores, and ultimately failing the entire operation.

**Comment by bpoldrack** [comment]
> in get.py:_parse_gitmodules() produces output

FTR: That's in `gitrepo.py`, not `get.py`.

Looking a bit closer into that one, the issue seems to be that `_parse_gitconfig_dump` conflates the to be skipped output with a part of the output that's actually valid:

`rm: cannot remove '/p/home/users/.../.cache/git-annex/locales/97d8e8e226139eee06ab02ccdf2f4c84': Directory not empty` ends up being a key, which is correctly skipped (as the warning reads). But then `submodule.code/pipeline.path` is the associated value, which really should be part of the next entry, I guess.

**Comment by bpoldrack** [comment]
I don't think there's a really clean and obvious solution, but considering that we aren't parsing some arbitrary config file, but specifically `.gitmodules` we may simply want to switch to omit the `-z` from the `git-config` call in `_parse_gitmodules` (and adjust `_parse_gitconfig_dump` accordingly, of course). I wouldn't know what entries in `.gitmodules` may be problematic in that regard.

**Comment by bpoldrack** [comment]
As for the question why that call would trigger some git-annex cache to be deleted in the first place ... no idea ATM.

**Comment by mih** [comment]
Sooo, the story continues (@bpoldrack I am not following up on anything you wrote, I think until the cause is not clear, the solution is not clear either).

The behavior is dependent on the git-annex version. I just worked with today's autobuild and I can see it: It removed user write permissions to `~/.cache/git-annex/locales` to provoke an error.

```
$ python -c 'import datalad'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mih/hacking/datalad/git/datalad/__init__.py", line 47, in <module>
    cfg = ConfigManager()
  File "/home/mih/hacking/datalad/git/datalad/config.py", line 274, in __init__
    self.reload(force=True)
  File "/home/mih/hacking/datalad/git/datalad/config.py", line 327, in reload
    self._stores[store_id] = self._reload(runargs)
  File "/home/mih/hacking/datalad/git/datalad/config.py", line 355, in _reload
    stdout, stderr = self._run(
  File "/home/mih/hacking/datalad/git/datalad/config.py", line 717, in _run
    out = self._runner.run(self._config_cmd + args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 409, in run
    raise CommandError(
datalad.support.exceptions.CommandError: CommandError: 'git --git-dir= config -z -l --show-origin' failed with exitcode 1 [err: 'mv: cannot move '/home/mih/.cache/git-annex/locales.tmp/9377285ab5c230a9c56378c628224cf6.442845' to '/home/mih/.cache/git-annex/locales/9377285ab5c230a9c56378c628224cf6': Permission denied']
```

```
$ git-annex version        
mv: cannot move '/home/mih/.cache/git-annex/locales.tmp/9377285ab5c230a9c56378c628224cf6.443003' to '/home/mih/.cache/git-annex/locales/9377285ab5c230a9c56378c628224cf6': Permission denied
```

whereas I can run all this fine with `git-annex version: 8.20210223`.

Now, running the autobuild also means running the git that comes with.

```
$ git config
mv: cannot move '/home/mih/.cache/git-annex/locales.tmp/9377285ab5c230a9c56378c628224cf6.443132' to '/home/mih/.cache/git-annex/locales/9377285ab5c230a9c56378c628224cf6': Permission denied
```

which points squarely at the `runshell` script in the git/git-annex bundle.

Given the original report happens on an HPC system with numerous simultaneous invocations, I think we are looking at a concurrency issue in that wrapper script. The installation of datalad/git-annex on that machine is conda-based.

**Comment by bpoldrack** [comment]
> @bpoldrack I am not following up on anything you wrote, I think until the cause is not clear, the solution is not clear either

Agree. However, making output parsing more robust against unexpected parts in it, seems worthwhile anyway (if only to provide a better way of failing). After all, it looks like the output would have been usable despite the error from rm.

**Comment by mih** [comment]
I am onto this. The git config parsing is broken in more ways than I wanted to learn about...
