### ISSUE TITLE
make_tempfile() uses deprecated mktemp with potential security implications

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5507]
`mktemp` is deprecated since version 2.3.

https://docs.python.org/3/library/tempfile.html#tempfile.mktemp

**Comment by mih** [comment]
This problematic usage pattern is more widespread:

```
datalad/interface/add_archive_content.py:            prefix_dir = basename(tempfile.mktemp(prefix=".datalad", dir=annex_path)) \
datalad/plugin/tests/test_addurls.py:        cls.json_file = tempfile.mktemp(suffix=".json", **mktmp_kws)
datalad/support/archives.py:            path = tempfile.mktemp(**get_tempfile_kwargs())
datalad/support/archives.py:            path = tempfile.mktemp(**get_tempfile_kwargs(prefix=_get_cached_filename(archive)))
datalad/tests/utils_testrepos.py:                tempfile.mktemp(**get_tempfile_kwargs(
datalad/utils.py:            self._out = open(tempfile.mktemp(**kw), 'w')
datalad/utils.py:            self._err = open(tempfile.mktemp(**kw), 'w')
datalad/utils.py:                out_file = tempfile.mktemp(**kw)
datalad/utils.py:    filename = {False: tempfile.mktemp,
```

**Comment by mih** [comment]
In the specific case of `make_tempfile()` the situation seems rather hopeless. It explicitly aims to provide a temporary filename only -- unless, of course, `mkdir` is given, or `content` -- in both cases something will actually exist on the filesystem on return. Just having a name *is* the security issue.

Unfortunately, this particular pattern is standard in the unittests.

It is probably best to relabel (and move) this function as a test helper, and provide a saner variant for use in the main codebase.

**Comment by adswa** [comment]
Looking at the Python docs, ``mkstemp`` could maybe be an alternative? https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp

**Comment by mih** [comment]
I am closing this old issue of mine. There is clearly no interest in this.
