### ISSUE TITLE
download_url: should auto initiate and autoenable datalad remote if download requires authentication

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5510]
follow up to https://github.com/datalad/datalad/issues/5508 : it is possible to `download-url` into a dataset but then nobody else would be able to fetch it since URL will be associated with the generic `web` remote.  To work correctly, we should first 
```
git annex initremote datalad externaltype=datalad type=external encryption=none autoenable=true
```
**before** registering a URL for the downloaded file if authentication was required and we succeeded with our downloader. If `initremote` is done after addurl/registerurl - it will be associated with web remote, i.e. lack `:` prefix as in this example having both after readding after enabeling the remote:

```shell
(git-annex)lena:/tmp/osf-test-private[git-annex]git-annex
$> cat 39d/3e1/MD5E-s4--098f6bcd4621d373cade4e832627b4f6.txt.log.web
1616071779.260903179s 1 :https://files.osf.io/v1/resources/37emg/providers/osfstorage/5e8524691ab24301dae037a9
1616039251.897745s 1 https://files.osf.io/v1/resources/37emg/providers/osfstorage/5e8524691ab24301dae037a9
```

**Comment by yarikoptic** [comment]
Wdyt @kyleam ?

**Comment by satra** [comment]
i ran into a bit of this where download-url works fine and i add the provider credentials, but the following command fails:

```
datalad addurls -d BANDA --fast test.csv '{url}' '{subj}//{folder}/{path}'
```

in the above command i was hoping to create the main dataset and the subdataset automatically, but it fails to access the http url, which i think is because git-annex doesn't know about the provider credentials.

**Comment by satra** [comment]
more fyi:

```
datalad create BANDA
mkdir BANDA/.datalad/procedures
cp cfg_init.sh BANDA/.datalad/procedures/
```
runs into 
```
datalad addurls -d BANDA --fast test-nomd5.csv '{url}' '{subj}//{folder}/{path}' -c init.sh 
[INFO   ] Creating a new annex repo at /om2/scratch/Mon/satra/BANDA/BANDA174 
[INFO   ] Scanning for unlocked files (this may take some time) 
[WARNING] Cannot find procedure with name 'cfg_init.sh' [run_procedure(cfg_init.sh)] 
[WARNING] Received an exception Command did not complete successfully. 1 failed:
[{'action': 'run_procedure',
  'message': "Cannot find procedure with name 'cfg_init.sh'",
  'path': 'cfg_init.sh',
  'refds': '/om2/scratch/Mon/satra/BANDA/BANDA174',
  'status': 'impossible'}] [utils.py:generator_func:459].
| Canceling not-yet running jobs and waiting for completion of running.
| You can force earlier forceful exit by Ctrl-C. 
[INFO   ] Canceled 0 out of 0 jobs. 0 left running. 
```

so the procedure doesn't apply to subdatasets.

**Comment by kyleam** [comment]
> Wdyt @kyleam ?

Sounds like a good idea.
