### ISSUE TITLE
datalad-archive leaves temp. files behind by default

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#5519]
Problem is: Build a dataset with `add-archive-content` to annex the archive as well as the extracted content using the datalad-archive special remote for extraction.
Now, in a fresh clone that only knows a source for the archive (as opposed to knowing a remote with the extracted content) run a `datalad get .`. This effectively leaves that clone requiring up-to 3 times the space of the content we wanted to get:
- the archive
- the extracted content in `.git/annex/objects`
- an extraction cache in `.git/datalad/tmp`

I think at least the cache shouldn't be persistent by default. The demand on space seems too surprising for a default. Arguably the same is true for keeping the archive around, when the `get` was called on the extracted content. In any case, the special remote should communicate how to drop the archive and how to use `datalad clean` to remove the cache, if any of those was kept (INFO message to annex).

Stumbled upon this in https://github.com/psychoinformatics-de/datalad-hirni/issues/183

Ping @yarikoptic 

Ping @pvavra, so you know where to follow ...

**Comment by yarikoptic** [comment]
I think we should
1. add config variables
    - `datalad.remote.archives.autoclean=false|true`: clean up established cache(s) upon exit
    - `datalad.remote.archives.autodrop=false|true`: `annex drop` obtained archives 
2. at the (graceful) exit of the special remote handle `true` settings for those
3. for `false` - at the point of the corresponding action (extraction of an archive, or obtaining archive) send annex `MESSAGE`  informing user that either cache or key would be left behind, and giving commands to clean them (`datalad clean --what cached-archives`, `git annex drop --key KEY`)

**Comment by bpoldrack** [comment]
FTR:

Tried looking into this in PR #5730, but actual cleaning turns out more complicated. There might be parallel annex jobs using the extraction cache, nested archives leading to nested calls of `datalad get` -> `annex get` -> `special remote` -> `annex get` -> `special remote` -> ... where it's not easily clear when and where to decide for (or against) removal. Also, an `atexit`-based approach would have the additional complication that even in a simple case it would work for command line invocation only, not when datalad is used via its python interface.

**Comment by bpoldrack** [comment]
Given the discussion here and in PR #5738, an `autoclean` turns out to be a severe problem. Therefore created #5834 to separate out part of the UX aspect. I will remove this issue from the UX project and add the other one instead.

**Comment by mih** [comment]
Attempts have been made, and partially succeeded. I am not aware of any plans to pick such effort up again. Closing.
