### ISSUE TITLE
`datalad extension-command --version` to provide version of the extension, not of datalad

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5527]
inspired by #5526  on multiple occasions I needed that. `datalad wtf` is a bit too much overhead to get that very "bite" of information.

**Comment by bpoldrack** [comment]
While I like a simple ay of querying an extension's version, I dont think `extension-command` is the way. I'd go the other way around:

- possibly deprecate `--version`
- have simple `version` subcommand instead (like annex), that can take an extension name as arguments

**Comment by yarikoptic** [comment]
> * possibly deprecate `--version`

I would strongly object that ;) 

> * have simple `version` subcommand instead (like annex) ...

lack of a regularly provided `--version` (like `git` does too) kept annoying me in annex as well.  And we have `datalad wtf` which pretty much provides what `git annex version` does.

> , I dont think `extension-command` is the way.

I might have not been clear, by  `extension-command` I meant commands provided by extensions, such as `containers-run` not really adding an `extension-command` entry point. And thinking about it more I love it -- I see smth like
```
$ datalad --version
0.14.0
$ datalad install --version
datalad 0.14.0
$ datalad containers-run --version
datalad-container 1.0.1
```
so we can conveniently provide not only a version of the extension which provided that command but disambiguate where that command/entry point comes from!

**Comment by bpoldrack** [comment]
> I would strongly object that ;)
> lack of a regularly provided --version (like git does too) kept annoying me in annex as well. And we have datalad wtf which pretty much provides what git annex version does.

Not mutually exclusive. `datalad version` can just do the same thing as `datalad --version`.

>    $ datalad install --version
>    datalad 0.14.0

Yes, that's already the case. 

> $ datalad containers-run --version

I see. And agree - that would be nicer than it is right now.
The "problem" I have with that is: You need to know which commands are coming from what extension in order to find out what version of the extension you have. To find out, you run `datalad wtf`. So - no need for a further `--version`, you already have it right there. It's only faster/easier than `wtf` if you don't need to think about what commands belong where. If that is not the case, nothing is gained over `datalad wtf`.

**Comment by bpoldrack** [comment]
Plus: There might not even be a command.
Say: A hirni user runs into a problem, posts an issue and I ask "What version of datalad-neuroimaging (a dependency of hirni) do you have installed?"
Now:
1. There's no command
2. The user installed hirni and might be aware of its commands, but that doesn't imply he knows anything about datalad-neuroimaging and its (non-existent) commands.

With your approach remains the same: `datalad wtf`.
With my approach: `datalad version datalad-neuroimaging`.

Similarly to the doc discussion there's of course always the python way of looking it up. Valid but not particularly nice for non python users.

**Comment by yarikoptic** [comment]
> > $ datalad install --version
> > datalad 0.14.0
> 
> Yes, that's already the case.

indeed I missed that we add `datalad ` prefix even for `datalad --version`.  I think it is a shortcut in our argparse-logic to report datalad's version for any `datalad COMMAND --version` thus they all show the same

**Comment by yarikoptic** [comment]
> "What version of datalad-neuroimaging (a dependency of hirni) do you have installed?"

so it would need to be a voice from above to inform the user for which extension to ask version of ... for anything like that full output of `datalad wtf` would still be preferable anyways.  `datalad COMMAND --version` is a convenience to avoid needing the discovery from which extension command comes and current behavior is IMHO just a little bit wrong since `datalad containers-run  --version` reports datalad's version which is not really the version of the `containers-run` implementation

**Comment by bpoldrack** [comment]
> datalad COMMAND --version is a convenience to avoid needing the discovery from which extension command comes and current behavior is IMHO just a little bit wrong since datalad containers-run --version reports datalad's version which is not really the version of the containers-run implementation

Agree. In case that's not clear: I have no objection to doing that.
