### ISSUE TITLE
datalad download-url --path does not work without backslash

### ISSUE THREAD

**Issue by manuelakuhn** [datalad/datalad#5528]
When following this documentation <http://docs.datalad.org/projects/hirni/en/latest/demos/demo_reproducibility.html#a-reproducible-glm-demo-analysis>, the step `download-url` does not work when using `--path` without a backslash.

```console
$ datalad create glm_analysis
[INFO   ] Creating a new annex repo at /tmp/datalad-tests/glm_analysis
[INFO   ] Scanning for unlocked files (this may take some time)
create(ok): /tmp/datalad-tests/glm_analysis (dataset)
$ cd glm_analysis
$ datalad run-procedure cfg_yoda
[INFO   ] Running procedure cfg_yoda
[INFO   ] == Command start (output follows) =====
[INFO   ] == Command exit (modification check follows) =====
$ datalad download-url --path code https://raw.githubusercontent.com/myyoda/ohbm2018-training/master/section23/scripts/events2ev3.sh
download_url(error): /tmp/datalad-tests/glm_analysis/code (file) [Non-directory path given (no trailing separator) but a directory with that name (after adding archive suffix) exists]
```
But with backslash it works:
```console
$ datalad download-url --path code/ https://raw.githubusercontent.com/myyoda/ohbm2018-training/master/section23/scripts/events2ev3.sh
[INFO   ] Downloading 'https://raw.githubusercontent.com/myyoda/ohbm2018-training/master/section23/scripts/events2ev3.sh' into '/tmp/datalad-tests/glm_analysis/code/'
download_url(ok): /tmp/datalad-tests/glm_analysis/code/events2ev3.sh (file)
add(ok): code/events2ev3.sh (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  download_url (ok: 1)
  save (ok: 1)
```

Besides that the documentation is wrong, from a user's perspective this is confusing because it behaves differently than standard commands, e.g. `cp`:

datalad behaviour:

|| `--path code/` | `--path code` |
|:--|:--|:--|
| code dir exists | download `events2ev3.sh` into code | error |
| code dir does not exist | error | download `events2ev3.sh` and name it code |

cp behaviour:
|| `cp events2ev3.sh code/` | `cp events2ev3.sh code` |
| :-- | :-- | :-- |
| code dir exists | copy `events2ev3.sh` into code | copy `events2ev3.sh` into code |
| code dir does not exist | error | copy `events2ev3.sh` and name it code|

I am using datalad version 0.14.0 with python 3.8.7

**Comment by kyleam** [comment]
Thanks for noting the documentation issue and for feedback on the behavior.

> from a user's perspective this is confusing because it behaves differently than standard commands, e.g. `cp`:

Yeah, I'm sympathetic to that; the rsync-like behavior was introduced as a lesser evil to avoid another confusing behavior:
https://github.com/datalad/datalad/issues/3848#issuecomment-548436256

**Comment by manuelakuhn** [comment]
Thank you very much for clarifying! This makes the behaviour much more understandable.

I just checked `datalad download-url --help` but there is nothing mentioned about this as well. Maybe it would help to also extend the documentation there. The man page of rsync does a pretty good job in this regard and perhaps could be used as reference.

**Comment by kyleam** [comment]
> I just checked `datalad download-url --help` but there is nothing mentioned about this as well. Maybe it would help to also extend the documentation there.

Hmm, the description for `--path` has a bit on this:

```
  -O PATH, --path PATH  target for download. If the path has a trailing
                        separator, it is treated as a directory, and each
                        specified URL is downloaded under that directory to a
                        base name taken from the URL. Without a trailing
                        separator, the value specifies the name of the
                        downloaded file (file name extensions inferred from
                        the URL may be added to it, if they are not yet
                        present) and only a single URL should be given.
                        [...]

```

Any suggestions for how that should be extended/reworded?

**Comment by manuelakuhn** [comment]
Sorry, my comment was misleading. What I meant was having that distinction more prominent so that you can see at first glance that you have to be cautious. In the rsync documentation they do this for example:
```
              For  example,  the  following creates a copy of file foo as bar in the sub/dir directory, creating dirs
              "sub" and "sub/dir" if either do not yet exist:

                  rsync -ai --mkpath foo sub/dir/bar

              If you instead ran the following, it would have created file foo in the sub/dir/bar directory:

                  rsync -ai --mkpath foo sub/dir/bar/
```
The example lines with and without trailing backslash help and make it easier to spot that there is something going and read the text more thoroughly.
