### ISSUE TITLE
Repository defaults to git-annex branch

### ISSUE THREAD

**Issue by adelavega** [datalad/datalad#5541]
#### What is the problem?
The datalad dataset defaults to the `git-annex` branch, not the `master` branch
See: https://github.com/neuroscout-datasets/ds002837

When I do `datalad install` on this dataset, it also is set to `git-annex` branch instead of `master`

#### What steps will reproduce the problem?

`datalad create-sibling-github --github-organization neuroscout-datasets --github-login adelavega --publish-depends mddatasrc --access-protocol ssh ds002247`

In the machine I ran this command, it is on `master` branch

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.11.6

If this is a known bug that was already fixed, do you know of an easy way to fix this problem? The datasets are fine otherwise and I rather not have to re-create and publish them.

Thanks!

**Comment by yarikoptic** [comment]
Fixed recently by https://github.com/datalad/datalad/pull/5010
I guess we need a maint release, @kyleam would you be so kind?

**Comment by adelavega** [comment]
Great. @yarikoptic do you know how to fix a current datalad dataset so it defaults to master branch?

**Comment by yarikoptic** [comment]
Yes, go to settings if repository, branches (iirc) and close master there.
Can also change at the level of user/organization so would work even for new ones. See https://github.com/datalad/datalad/issues/4997#issuecomment-712454841 for more info

**Comment by adelavega** [comment]
ahh so its at the level of github that is the issue. gotcha. thanks!

**Comment by kyleam** [comment]
> I guess we need a maint release, @kyleam would you be so kind?

Sure, 0.14.1 is out.
