### ISSUE TITLE
Consolidate signature of former plugins

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#5556]
As seen in https://github.com/datalad/datalad/pull/5554, the signatures of a bunch of commands are such, that the way to call them via CLI, bound `Dataset` methods and unbound functions isn't quite consistent. This should be ironed out.

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
