### ISSUE TITLE
Clarify consistent API test

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#5557]
As discussed in https://github.com/datalad/datalad/pull/5554, it's not obvious what the test really tries to ensure and why.
This needs to be documented in that test. Related: #5556

**Comment by mih** [comment]
From discussion in call: for a 1.0 release, we might want to consistently apply the rule "no positional arguments in any command".

**Comment by yarikoptic** [comment]
we might... meanwhile might be worth introducing use of [`*`](https://python-3-for-scientists.readthedocs.io/en/latest/python3_advanced.html) to explicitly annotate such in the "non-API" functions (and may be new API "constructs"), in particular in the new ones we add (I believe it is present in all relevant versions of python3, so we are "ready" to use it).

**Comment by adswa** [comment]
Looking at this test on ``master``, there still is no clarification or docstring - however, @yarikoptic touched up its internal helper in b8701490648d33a0a4b7afa572b12195f51c77da which has a few comments, and there now is a design doc in http://docs.datalad.org/en/latest/design/pos_vs_kw_parameters.html. Is this test clarified? And if not, what is missing?

**Comment by yarikoptic** [comment]
Thank you @adswa for digging this out. IMHO that test code is sufficiently commented out, we indeed now use `*` to separate out few pos args from kwargs, that test ensures that, and design doc exists.  Let's close and if still more clarification is desired, reopen as a new issue with more specific desires listed.
