### ISSUE TITLE
Saving subdataset requires `-d .` ?

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#5567]
#### What is the problem?
Maybe I am missing something. I thought `datalad save SUBDATASET` would save the latest commit of the subdataset located in folder `SUBDATASET`. But here is what happens:
```
[dorian@mri fmriprep-20.2.x]$ datalad save -m 'Update fmriprep reference' fmriprep
[dorian@mri fmriprep-20.2.x]$ datalad save -m 'Update fmriprep reference' fmriprep/
[dorian@mri fmriprep-20.2.x]$ datalad save -d . -m 'Update fmriprep reference' fmriprep
add(ok): fmriprep (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
[dorian@mri fmriprep-20.2.x]$ datalad status -r
nothing to save, working tree clean
```
I was running `datalad status -r` to make sure the entire subdataset tree was clean. It showed that the subdataset `fmriprep` was modified. I tried to save it normally, and the prompt just returns, nothing was done. Running `datalad status -r` still showed it as modified. After placing `-d .` in the command, it actually saved it. Did I miss something on how it should work?

#### What steps will reproduce the problem?
NA

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.14.0

#### Is there anything else that would be useful to know in this context?
These subdatasets were folders, thus I created the dataset with `--force`.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Yup.

**Comment by kyleam** [comment]
> After placing `-d .` in the command, it actually saved it. Did I miss something on how it should work?

No, you're not missing anything.  If you pass a subdataset as a path, using `--dataset` is needed to record the corresponding change in the parent dataset.

This was discussed a bit in <https://github.com/datalad/datalad/issues/3550>.

It'd be good to describe this behavior in `save`s help output (e.g., in the examples section).

**Comment by dorianps** [comment]
But if I am in dataset A and attempt to save the subfolder/subdataset B, what else can it save except the reference of the subdataset? It is  not saving B itself, and is not saving anything in the parent A. Practically it is a command hole with no outcome and no return message. It might be useful to at least inform the user that nothing was saved, unless the approach of datalad is always to mean that a return prompt with no message = nothing was performed.

**Comment by kyleam** [comment]
> what else can it save except the reference of the subdataset? It is not saving B itself

Hmm, it should save within the subdataset itself:

```sh
cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-XXXXXXX)" || exit 1
datalad create
datalad create -d. subds
touch subds/foo
echo "----------------------------------------------------------------------"
datalad --version
set -x
datalad status -r
datalad save subds
datalad status -r
```

```
[...]
datalad 0.14.2
+ datalad status -r
 modified: subds (dataset)
untracked: subds/foo (file)
+ datalad save subds
add(ok): foo (file)                                                                     
save(ok): subds (dataset)                                                               
action summary:                                                                         
  add (ok: 1)
  save (ok: 1)
+ datalad status -r
 modified: subds (dataset)
```

**Comment by adswa** [comment]
If I am seeing it correctly, this issue looks like a "question"-type issue with an answer, and hence I am inclined to close it. Please reopen if I have missed something, or if undesired behavior is still occurring. Thanks!
