### ISSUE TITLE
openBinaryFile: resource busy git-annex: export: 2 failed

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5588]
Working on backporting git-annex (8.20210331, not standalone) to Debian buster. The following test fails reliably, for git 2.24 and 2.29.

 ```
      ./Test/Framework.hs:57:
      export to dir failed (transcript follows)
      export foo bar.c okexport foo foo   /tmp/.t/tmprepo4/dir/foo29555-4.tmp: openBinaryFile: resource busy (file is locked)failedexport foo sha1foo   /tmp/.t/tmprepo4/dir/sha1foo29555-7.tmp: openBinaryFile: resource busy (file is locked)failed(recording state in git...)git-annex: export: 2 failed
```

Nothing to be done here necessarily, but worth making a record of.

Update: There is no test failure for 8.20210223 or 8.20210310 (tested with git 2.29 or 2.24) -- so this is a recent breakage

**Comment by yarikoptic** [comment]
eh, I think it might relate to https://git-annex.branchable.com/bugs/fresh_3_tests_fails-_openBinaryFile__58___resource_busy/ I have reported to @joeyh recently.

**Comment by adswa** [comment]
From the git-annex issue it seems that this has been fixed last April on git-annex's side - thus, I'm closing this issue. Please reopen if I am mistaken.
