### ISSUE TITLE
Repo method cache

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5598]
I am planning to implement a replacement for manual caching of `Repo` method result caching. The type of caching I am talking about can be seen in the `copy_file()` code, but is also prevalent elsewhere.

The "cache" that I am aiming for is a class that:

- wraps a `Repo` instance
- implements any method call (in a generic fashion)
- keeps a record of any output in a dict with a key that combines (method name, and arguments)
- returns the cached result on a repeated request

In essence this creates a static variant of a `Repo` (not really static, because time is only frozen from the time of the first request with a particular parameterization). It needs to be used with care, but it has its use, I think.

Returned generators will need special handling, such that they can be unrolled multiple times.

**Comment by yarikoptic** [comment]
wouldn't it work only
- in case of no external changes to the repository
- until any non-read-only invocation of external command is made
unless analysis of file stats is done on `.git/` directory files content as we do in fscacher?

if there were no aforementioned concerns, I guess a simple `@lru_cache` could have been just used for such methods?

**Comment by mih** [comment]
Yes, that is what I wanted to say by calling it "static". That doesn't cover all use cases, but some, where we assume static already and have custom caching implemented:

- `diffstatus()` caches `get_content_info()` (which is actually coordinated from `diff()` and `status()`)
- `copy_file()` caches `get_dataset_root()`, `get_special_remotes()`

What these implementations do is to assume a static situation on disk in order to perform some kind of query or assessment to inform subsequent processing. And they do it for performance reasons.

I think it would be instrumental if we could establish some generic machinery for that: treat all repos as static and behave `lru_cache`-like.

I don't think `lru_cache` per se does what is needed. I think it is only meant to be used for functions that are always behaving in ways that keeps their previous return values valid for a later call. Here we have the situation that this should only ever happen in some specific context. To me this requires either a switch within `*Rep` (ugly), or a dedicated class.

I don't have a solid understanding yet, but I think such a tool would offer a good opportunity to decomplicate code.

**Comment by bpoldrack** [comment]
If I understand the idea correctly, and instance of such a thing would be explicitly created for use in a context where we assume the repo to be "static" already and throw it away when that context is left.

Sounds to me like something that could be more generic (not specific to `*Repo`). 
A `CachedObject` class that:
 - defines a decorator function, that would deal with the cache dict
 - has a constructor that takes any object
 - implements `__getattr__` to wrap any method call with that decorator
 
 Something like that, @mih?

**Comment by yarikoptic** [comment]
> ... should only ever happen in some specific context.

so do you mean smth like

```
with ds.repo.get_content_info.cached:
   res1 = ds.repo.diffstatus()
   res2 = dl.blah()
   ...
```
where `.cached` would then force usage of e.g. `@lru_cache`'ed version of `ds.repo.get_content_info` for the duration of the context manager?

**Comment by mih** [comment]
My demo implementation for `copy_file` was met with complete neglect for two months. Nobody seems to care for this type of optimization. No need to keep this open.
