### ISSUE TITLE
create slim version of gump dataset used by testkraut test

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#56]
takes a while on each clone etc.

as I have hinted in the mail should just provide minimalistic view of that repository with only files necessary for the (unit)test

**Comment by yarikoptic** [comment]
please let me know if you need help with this one @bpoldrack -- its slowness really gets on my nerves

**Comment by bpoldrack** [comment]
See PR 65. Since the use of actual forrest data for this test is pointless, I changed the testkraut test to make use of basic/r1 testrepo.

**Comment by yarikoptic** [comment]
also let's consider resolved by #65
