### ISSUE TITLE
--init  for crawl  to provide easy means to initiate crawling configuration based on some template

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#561]
So eventually we would get a set of generic templates. So it would be nice if I could, in a repository, say

```
datalad crawl --init basic \
  url=http://example.com \
  a_href_match=.*\.(tar.*|dat)) \
  extract_tarballs=.*\.tar.*. 
```
or 

```
datalad crawl --init --interactive basic
```

 which would give me a list of arguments that template expects to user could specify them  and as a result `.datalad/crawl/crawl.cfg` would be initiated, and crawling started.    I will describe more in person ;)

**Comment by glalteva** [comment]
Closed by #638
