### ISSUE TITLE
Begging for consistent API: provide -d DATASET for create to register it within super-dataset right away

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#563]
As you saw in #562, I, empowered by knowledge, that -d generally probably corresponds to a dataset to specify for e.g. registering a newly installed/created module, I have used it also for create -- very logical to me.  But then discovered that -d is actually for "description" when called for `create`.  I raise my vote as a user and as a developer to do introduce ability to register a newly created dataset within super dataset but providing consistent with 'install' -d/--dataset option.  

For description we could make it -D   or make it inline with git-annex by providing as positional optional 2nd arg (although not sure if I like that one)

**Comment by hanke** [comment]
This will come automatically once create is reimplemented via install. I can remove create entirely until this happens, if this causes more trouble than it helps.

**Comment by yarikoptic** [comment]
On Fri, 17 Jun 2016, Michael Hanke wrote:

>    This will come automatically once create is reimplemented via install. I
>    can remove create entirely until this happens, if this causes more trouble
>    than it helps.

please don't.... a super-magical all-in-1 install is still confusing for
simple minded like me.  Having create at least in some shape is already
helpful... I will for now just quickly change -d to -D to avoid confusion

**Comment by bpoldrack** [comment]
Since `create` is redesigned now including an option to register to the superdataset, I think this is obsolet.
