### ISSUE TITLE
[doc, minor]: "datalad create --help" references "run_procedure" cmd, but only "run-procedure" exists

### ISSUE THREAD

**Issue by sappelhoff** [datalad/datalad#5634]
Hi all and thanks for datalad.

I was playing a bit with `datalad create` and wanted to check the different configurations. `datalad create --help` tells me:

> Use run_procedure --discover to get a list
                        of available procedures, such as cfg_text2git.

Then running `datalad run_procedure --discover` tells me:

>datalad: Unknown command 'run_procedure'.  See 'datalad --help'.
>
>Did you mean any of these?
        run-procedure

And finally, that suggestion (`datalad run-procedure --discover`) works fine.

Perhaps the issue a typo here?

https://github.com/datalad/datalad/blob/a36f1c1c0e133b3f6535c4aefdf24d694fedc4d7/datalad/core/local/create.py#L196

recent install of `git-annex` using `conda-forge` (8.20210428....) and `datalad` using `pip` (0.14.3)

**Comment by yarikoptic** [comment]
Yes, for CMD should have -

**Comment by yarikoptic** [comment]
addressed by #5635 which merged to maint, no need to keep it open
