### ISSUE TITLE
datalad annex remote: Provide configurable (or just "smart") weighting/ordering of URLs

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5638]
See https://git-annex.branchable.com/todo/assign_costs_per_URL_or_better_repo-wide___40__regexes__41__/ for more context etc.  `datalad` special remote could be used instead of "built-in" `web` remote if such prioritization is desired.

We could may be weight different download providers first, and/or just URLs based on regexes.  Then datasets could carry desired weighting within their `.datalad/config`.

Or, we could be "smarty pants" and just (via historical collection in cache, e.g. of the recent X size: time pairs per each `protocol://servername` we encountered) figure out which of the domains (URLs) is expected to be the "fastest" one.  I feel like we had some issue about that but failed to find it.  Such automagical decision making would be nice, but would be hard to "inherit"/propagate across different CI runs (one of the use cases e.g. `annex fsck` for https://github.com/dandi/dandisets/issues/11#issuecomment-831993490) and might need some clever design to not derail into choosing the suboptimal/slowest one.

May be that logic could even be reused for `clone` operation while going through candidates with the same priority.

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
