### ISSUE TITLE
create with description but --no-annex must not create an annex -- it must blow

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#564]
As #562 and #563 have demonstrated -- create tries to make a new dataset an annex even though I have said to not do that.  So it would be nice to just blow if incompatible options are provided (e.g. -- description and --no-annex)

**Comment by hanke** [comment]
If you feel it takes longer to write the issue than change the code, just
go ahead ;-)

**Comment by hanke** [comment]
Again, as with #563, any work on `create` that doesn't reimplement it as a plain proxy to install seems pointless.

**Comment by yarikoptic** [comment]
https://github.com/datalad/datalad/pull/576 closed it
