### ISSUE TITLE
`git annex info`: misleading suggestion

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5665]
```
% git annex info

  remote input:This repository is not initialized for use by git-annex, but ./../inputstore/893/8de76-0302-45b5-9825-3c6ce3f3fffe/annex/objects/ exists, which indicates this repository was used by git-annex before, and may have lost its annex.uuid and annex.version configs. Either set back missing configs, or run git-annex init to initialize with a new uuid.
```

`input` and `input-storage` are a RIA remote combo, therefore they have `annex/objects` but should not have an `annex.version` and `annex.uuid` configs.

**Comment by bpoldrack** [comment]
This looks a whole lot like running annex on the repo in-store. Is that true, @mih ?

**Comment by bpoldrack** [comment]
Or is it just, that the store is local?

**Comment by mih** [comment]
This is running in an ephemeral clone, not a store. `input` existed before the clone was made, hence `create-sibling-ria` was never executed in that clone.

**Comment by bpoldrack** [comment]
I don't know what it means, that `input` existed before cloning. It's a git remote, isn't it? And how is it not `origin` during cloning (in which case `clone` is supposed to set annex ignore)? Something is special and I don't quite get it yet.

**Comment by mih** [comment]
I can  no longer reproduce this with current master

**Comment by yarikoptic** [comment]
I wonder if this could be related to https://github.com/datalad/datalad/issues/6708 - as if @mih ran `git annex info` in a repository of another user.  I am tracking down that "new" behavior in that issue but still with older git-annex but newer (from Apr 13 15:21:34 2022) git so I am observing exactly such response in a case where repo is owned by `root`:

```
(datalad-dev) yoh@datalads-imac2 clone % ls -lta
total 0
drwxr-xr-x  14 root  staff  448 May 27 18:37 .git
drwxr-xr-x   4 root  staff  128 May 27 18:37 .
lrwxr-xr-x   1 root  staff  178 May 27 18:37 file1 -> .git/annex/objects/Xk/Vz/SHA256E-s5--c147efcfc2d7ea666a9e4f5187b115c90903f0fc896a56df9a6ef5d8f3fc9f31/SHA256E-s5--c147efcfc2d7ea666a9e4f5187b115c90903f0fc896a56df9a6ef5d8f3fc9f31
drwx------   4 yoh   staff  128 May 27 18:37 ..
(datalad-dev) yoh@datalads-imac2 clone % git annex info
git-annex: This repository is not initialized for use by git-annex, but .git/annex/objects/ exists, which indicates this repository was used by git-annex before, and may have lost its annex.uuid and annex.version configs. Either set back missing configs, or run git-annex init to initialize with a new uuid.
(datalad-dev) yoh@datalads-imac2 clone % git --version; git annex version | head -n 1
git version 2.35.3
git-annex version: 8.20210310
```

and that all is due to the fact that `git` returns no annex.uuid in this case:

```
(datalad-dev) yoh@datalads-imac2 clone % git config annex.uuid
(datalad-dev) yoh@datalads-imac2 clone % echo $?
1
(datalad-dev) yoh@datalads-imac2 clone % git --git-dir=. config annex.uuid
(datalad-dev) yoh@datalads-imac2 clone % git --git-dir=.git config annex.uuid
f45b8a85-7c58-4add-aa9a-5b64f2c72466
(datalad-dev) yoh@datalads-imac2 clone % echo $?
0
```

and indeed setting safe.directory globally (only!) helps
```
(datalad-dev) yoh@datalads-imac2 clone % git -c safe.directory=$PWD config annex.uuid
(datalad-dev) yoh@datalads-imac2 clone % git -c safe.directory=$PWD/.git config annex.uuid
(datalad-dev) yoh@datalads-imac2 clone % git config --global safe.directory $PWD
(datalad-dev) yoh@datalads-imac2 clone % git config annex.uuid                         
f45b8a85-7c58-4add-aa9a-5b64f2c72466
```

given that `safe.directory` handling in git was added only recently
```
commit 8959555cee7ec045958f9b6dd62e541affb7e7d9
Author: Johannes Schindelin <Johannes.Schindelin@gmx.de>
Date:   Wed Mar 2 12:23:04 2022 +0100
```
unlikely it is the original issue @mih observed in 2021 -- but here you have it FWIW ;)
