### ISSUE TITLE
Technology update for datalad.org webpage

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#567]
Current version was a more-or-less hackish copy of the studyforrest.org setup. The latter site has received a major overhaul with a much cleaner implementation. I propose to redo the copy-over and benefit from the cleaner foundation.

Objections?

**Comment by yarikoptic** [comment]
Eventually the whole website should be redone anyways to support browsing etc of datasets and being datalad published, so I don't see urgency in face lifting ATM, but if someone is eager to do it, I wouldn't mind

**Comment by hanke** [comment]
This sounds like we don't have the same concept of that webpage. So let's not touch anything until this is clarified.

**Comment by yarikoptic** [comment]
Could well be. Mine is close to what we proposed originally in the proposal :-)

**Comment by hanke** [comment]
In this case, I strongly propose an amendment. I want to keep the pictures on the website, despite the fact that the founding fathers didn't put that explicitly in the proposal.

**Comment by yarikoptic** [comment]
;-)  And I "slept on it", and decided that whatever we would "publish" should be really concerned only with presentation/exploration of the datasets.  It should just be pluggable easily into main (lab, consortium, etc) websites either through an ugly subframe or some other, more contemporary technique.  So, in general I do not oppose any face lifting to the main website.  BUT I wonder if it shouldn't be fully sphinx produced?  I find myself quite lost often among multitude of "faces" of projects' websites.  As we already know we could do everything, including blog pots etc, with sphinx.  And then later we would just embed the "datasets.datalad.org" component into it.
