### ISSUE TITLE
FOI: there is now git annex filter-branch

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5670]
as of   [8.20210428-157-g7d57866c3](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=7d57866c3e1cddea2ce8b74c457a46416b6704d4)

More info https://git-annex.branchable.com/todo/copy-key___40__--batch__41___to_copy__47__merge_availability_info/ and original motivation was to allow for `annex copy-key`. I guess (since didn't try yet) this filter-branch could be used for needed `copy-file` functionality but would be most efficient whenever files are operated on in "bulk", not one by one.

Attn #5599

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
