### ISSUE TITLE
Initializing S3 special remote with `versioning=yes` and `exporttree=yes` results in datalad push error

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad#5684]
#### What is the problem?
I'm not sure which options are best for configuring S3 as a special remote.

If I include `versioning=yes` and `exporttree=yes` when running the `git annex initremote` command to initialize the special remote (which is also set as a publication dependency for a GitHub sibling), running `datalad push --to github` results in the following error:

```
CommandError: 'git -c diff.ignoreSubmodules=none annex copy --batch -z --to public-s3 --fast --json --json-error-messages --json-progress -c annex.dotfiles=true -c annex.retry=3' failed with exitcode 1 under /Users/jsheunis/Documents/neuro_data_s3
git-annex: copy: 6 failed
```

If I exclude these options, the data gets pushed to the special remote as expected.

#### What steps will reproduce the problem?
I'm running DataLad v0.14.2 on macOS Big Sur 11.2.3. I have a DataLad dataset (with `nii.gz`, `json`, and `tsv content`) with an S3 bucket configured as a git-annex special remote which is also a publication dependency for a GitHub sibling.

Initializing the special remote:
```
git annex initremote public-s3 type=S3 encryption=none bucket=$BUCKET public=yes versioning=yes exporttree=yes datacenter=EU autoenable=true
```

Running `datalad push --to github` leads to the error.

I'm guessing there's some git-annex and special remote context that I'm missing here?

**Comment by yarikoptic** [comment]
eh -- sorry about that.  I forgot to realize that we never added support for `annex export` AFAIK.  Relevant issue from `publish` times is https://github.com/datalad/datalad/issues/3127 . I adjusted title now and added labels there.

for now it would be needed to manually call `git annex export` for such cases :-/

**Comment by jsheunis** [comment]
Thanks for the info!

**Comment by mih** [comment]
I will close this issue now, I have assigned myself to #3127 to finally sort it out.
