### ISSUE TITLE
Mandatory initial content/commit for new datasets?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#569]
We are back in meta data land....

Git cannot deal with empty (no commits) repositories as submodules properly. Actually, it does it properly, and ignores them largely -- just like empty directories. However, in our context this causes pain and complications (see #558, but we have been there before already).

The "easy" way out is to never have empty repositories by making an initial commit. The naive choice for the content of such commit is an initial set of meta data (remember?). At this point I don't want to repeat the "what could the minimal meta data set be?" question.

Fortunately, we have a concrete case this time: "description". Unlike the suggestion in #564, I propose to store a given description for a new dataset in our own meta data file in `.datalad` (or whereever we agreed that thing to be). Let's ignore the linked data topic for now and go simple with this one. I'd prefer YAML as a format, but I don't feel strongly about it.

I do not see this meta data file as exclusive. We should continue to set a description via git-annex (although this rather has to be seen as a description for an annex clone, and not so much a description of the dataset itself).

Yes, no, maybe?

**Comment by yarikoptic** [comment]
We could also force generate an empty commit ;-) And I agree on general for 'create -d ...' invocation to force a nonempty repository. In general case though, we could just fail to 'install -d ...' wherever installed subdataset is still an empty repo
-- 
Sent from a phone which beats iPhone.

**Comment by hanke** [comment]
So you are proposing: "no meta data, just an empty commit"?

**Comment by yarikoptic** [comment]
yes, we could use 'git commit --allow-empty -m "Initiating empty datalad dataset"' if we need to force initiate git history and no meta data was provided ;)

**Comment by bpoldrack** [comment]
I agree. Initializing with some metadata will lead to even more additional options and functionality in `install` and `create`, in order to "configure" that initial commit. Once we have a again a concept for metadata, this can still be changed, if there is a reasonable initial commit involving metadata. For now, let's go with an empty commit

**Comment by mih** [comment]
We are now always having default content (since the merged #682).
