### ISSUE TITLE
cant push data to ria-sibling

### ISSUE THREAD

**Issue by OleBialas** [datalad/datalad#5694]
I have created a ria sibling (called backup) on an external disk following the guide from the handbook (http://handbook.datalad.org/en/latest/beyond_basics/101-147-riastores.html)

pushing to the sibling whilst not transferring any data seems to work fine:
 ` datalad push --to backup --data nothing`

however when I omit the `--data` flag I always get the error message:

`Push to 'backup':  25%|██████████████████████████▊                                                                                | 1.00/4.00 [00:00<00:00, 7.15k Steps/sCommandError: 'git -c diff.ignoreSubmodules=none annex copy --batch -z --to backup-storage --fast --json --json-error-messages --json-progress -c annex.dotfiles=true -c annex.retry=3' failed with exitcode 1`

I am using Ubuntu 20.04 and Datalad 0.14.4 (installed via conda)
I did some research but couldn't find a solution for my problem, I'm hoping you can help me out (this is my first datalad project)

**Comment by adswa** [comment]
Hey @OleBialas, thanks for getting in touch. I wonder if the problem may be related to the file system on your external disk. Could you check what you use? 
Could you also run the ``push`` command in debug mode (``datalad -l debug push --to backup``) and paste the output here?

**Comment by OleBialas** [comment]
[DEBUG  ] Command line args 1st pass for DataLad 0.14.4. Parsed: Namespace() Unparsed: ['push', '--to', 'backup'] 
[DEBUG  ] Discovering plugins 
[DEBUG  ] Building doc for <class 'datalad.core.local.status.Status'> 
[DEBUG  ] Building doc for <class 'datalad.core.local.diff.Diff'> 
[DEBUG  ] Building doc for <class 'datalad.core.distributed.push.Push'> 
[DEBUG  ] Parsing known args among ['/home/ole/anaconda3/envs/elevation_encoding/bin/datalad', '-l', 'debug', 'push', '--to', 'backup'] 
[DEBUG  ] Async run:
|  cwd=None
|  cmd=['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] 
[DEBUG  ] Launching process ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] 
[DEBUG  ] Process 127682 started 
[DEBUG  ] Waiting for process 127682 to complete 
[DEBUG  ] Process 127682 exited with return code 0 
[DEBUG  ] Determined class of decorated function: <class 'datalad.core.distributed.push.Push'> 
[DEBUG  ] Resolved dataset for pushing: /home/ole/projects/elevation_encoding 
[DEBUG  ] Async run:
|  cwd=/home/ole/projects/elevation_encoding
|  cmd=['git', 'config', '-z', '-l', '--show-origin'] 
[DEBUG  ] Launching process ['git', 'config', '-z', '-l', '--show-origin'] 
[DEBUG  ] Process 127684 started 
[DEBUG  ] Waiting for process 127684 to complete 
[DEBUG  ] Process 127684 exited with return code 0 
[DEBUG  ] Async run:
|  cwd=/home/ole/projects/elevation_encoding
|  cmd=['git', 'config', '-z', '-l', '--show-origin', '--file', '/home/ole/projects/elevation_encoding/.datalad/config'] 
[DEBUG  ] Launching process ['git', 'config', '-z', '-l', '--show-origin', '--file', '/home/ole/projects/elevation_encoding/.datalad/config'] 
[DEBUG  ] Process 127686 started 
[DEBUG  ] Waiting for process 127686 to complete 
[DEBUG  ] Process 127686 exited with return code 0 
[DEBUG  ] Resolved dataset for difference reporting: /home/ole/projects/elevation_encoding 
[DEBUG  ] Diff Dataset(/home/ole/projects/elevation_encoding) from 'None' to 'HEAD' 
[DEBUG  ] AnnexRepo(/home/ole/projects/elevation_encoding).get_content_info(...) 
[DEBUG  ] Query repo: ['ls-tree', 'HEAD', '-z', '-r', '--full-tree', '-l'] 
[DEBUG  ] Async run:
|  cwd=/home/ole/projects/elevation_encoding
|  cmd=['git', '-c', 'diff.ignoreSubmodules=none', 'ls-tree', 'HEAD', '-z', '-r', '--full-tree', '-l'] 
[DEBUG  ] Launching process ['git', '-c', 'diff.ignoreSubmodules=none', 'ls-tree', 'HEAD', '-z', '-r', '--full-tree', '-l'] 
[DEBUG  ] Process 127688 started 
[DEBUG  ] Waiting for process 127688 to complete 
[DEBUG  ] Process 127688 exited with return code 0 
[DEBUG  ] Done query repo: ['ls-tree', 'HEAD', '-z', '-r', '--full-tree', '-l'] 
[DEBUG  ] Done AnnexRepo(/home/ole/projects/elevation_encoding).get_content_info(...) 
[DEBUG  ] Attempt push of Dataset at /home/ole/projects/elevation_encoding 
[DEBUG  ] Discovered publication dependencies for 'backup': ['backup-storage']'                                                                                           
[DEBUG  ] Async run:                                                                                                                                                      
|  cwd=/home/ole/projects/elevation_encoding
|  cmd=['git', '-c', 'diff.ignoreSubmodules=none', 'push', '--progress', '--porcelain', '--dry-run', 'backup'] 
[DEBUG  ] Launching process ['git', '-c', 'diff.ignoreSubmodules=none', 'push', '--progress', '--porcelain', '--dry-run', 'backup']                                       
[DEBUG  ] Process 127691 started                                                                                                                                          
[DEBUG  ] Waiting for process 127691 to complete                                                                                                                          
[DEBUG  ] Non-progress stderr: b'fatal: The current branch master has no upstream branch.\n'                                                                              
[DEBUG  ] Non-progress stderr: b'To push the current branch and set the remote as upstream, use\n'                                                                        
[DEBUG  ] Non-progress stderr: b'\n'                                                                                                                                      
[DEBUG  ] Non-progress stderr: b'    git push --set-upstream backup master\n'                                                                                             
[DEBUG  ] Non-progress stderr: b'\n'                                                                                                                                      
[DEBUG  ] Process 127691 exited with return code 128                                                                                                                      
[DEBUG  ] Dry-run push to check push configuration failed, assume no configuration: CommandError: 'git -c diff.ignoreSubmodules=none push --progress --porcelain --dry-run backup' failed with exitcode 128 under /home/ole/projects/elevation_encoding [err: 'fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream backup master'] 
[DEBUG  ] Async run:                                                                                                                                                      
|  cwd=/home/ole/projects/elevation_encoding
|  cmd=['git', '-c', 'diff.ignoreSubmodules=none', 'symbolic-ref', 'HEAD'] 
[DEBUG  ] Launching process ['git', '-c', 'diff.ignoreSubmodules=none', 'symbolic-ref', 'HEAD']                                                                           
[DEBUG  ] Process 127693 started                                                                                                                                          
[DEBUG  ] Waiting for process 127693 to complete                                                                                                                          
[DEBUG  ] Process 127693 exited with return code 0                                                                                                                        
[DEBUG  ] Async run:                                                                                                                                                      
|  cwd=/home/ole/projects/elevation_encoding
|  cmd=['git', '-c', 'diff.ignoreSubmodules=none', 'symbolic-ref', 'HEAD'] 
[DEBUG  ] Launching process ['git', '-c', 'diff.ignoreSubmodules=none', 'symbolic-ref', 'HEAD']                                                                           
[DEBUG  ] Process 127695 started                                                                                                                                          
[DEBUG  ] Waiting for process 127695 to complete                                                                                                                          
[DEBUG  ] Process 127695 exited with return code 0                                                                                                                        
[DEBUG  ] No sync necessary, no corresponding branch detected                                                                                                             
[DEBUG  ] Async run:                                                                                                                                                      
|  cwd=/home/ole/projects/elevation_encoding                                                                                                                              
|  cmd=['git', '-c', 'diff.ignoreSubmodules=none', 'push', '--progress', '--porcelain', '--dry-run', 'backup-storage'] 
[DEBUG  ] Launching process ['git', '-c', 'diff.ignoreSubmodules=none', 'push', '--progress', '--porcelain', '--dry-run', 'backup-storage']                               
[DEBUG  ] Process 127697 started                                                                                                                                          
[DEBUG  ] Waiting for process 127697 to complete                                                                                                                          
[DEBUG  ] Non-progress stderr: b'fatal: The current branch master has no upstream branch.\n'                                                                              
[DEBUG  ] Non-progress stderr: b'To push the current branch and set the remote as upstream, use\n'                                                                        
[DEBUG  ] Non-progress stderr: b'\n'                                                                                                                                      
[DEBUG  ] Non-progress stderr: b'    git push --set-upstream backup-storage master\n'                                                                                     
[DEBUG  ] Non-progress stderr: b'\n'                                                                                                                                      
[DEBUG  ] Process 127697 exited with return code 128                                                                                                                      
[DEBUG  ] Dry-run push to check push configuration failed, assume no configuration: CommandError: 'git -c diff.ignoreSubmodules=none push --progress --porcelain --dry-run backup-storage' failed with exitcode 128 under /home/ole/projects/elevation_encoding [err: 'fatal: The current branch master has no upstream branch.                     
To push the current branch and set the remote as upstream, use

    git push --set-upstream backup-storage master'] 
[DEBUG  ] Async run:                                                                                                                                                      
|  cwd=/home/ole/projects/elevation_encoding                                                                                                                              
|  cmd=['git', '-c', 'diff.ignoreSubmodules=none', 'symbolic-ref', 'HEAD'] 
[DEBUG  ] Launching process ['git', '-c', 'diff.ignoreSubmodules=none', 'symbolic-ref', 'HEAD']                                                                           
[DEBUG  ] Process 127699 started                                                                                                                                          
[DEBUG  ] Waiting for process 127699 to complete                                                                                                                          
[DEBUG  ] Process 127699 exited with return code 0                                                                                                                        
[DEBUG  ] Async run:                                                                                                                                                      
|  cwd=/home/ole/projects/elevation_encoding                                                                                                                              
|  cmd=['git', '-c', 'diff.ignoreSubmodules=none', 'symbolic-ref', 'HEAD'] 
[DEBUG  ] Launching process ['git', '-c', 'diff.ignoreSubmodules=none', 'symbolic-ref', 'HEAD']                                                                           
[DEBUG  ] Process 127701 started                                                                                                                                          
[DEBUG  ] Waiting for process 127701 to complete                                                                                                                          
[DEBUG  ] Process 127701 exited with return code 0                                                                                                                        
[DEBUG  ] No sync necessary, no corresponding branch detected                                                                                                             
[DEBUG  ] Launching process ['/home/ole/anaconda3/envs/elevation_encoding/bin/python', '--version']                                                                       
[DEBUG  ] Process 127703 started                                                                                                                                          
[DEBUG  ] Waiting for process 127703 to complete                                                                                                                          
[DEBUG  ] Process 127703 exited with return code 0                                                                                                                        
[DEBUG  ] Async run:                                                                                                                                                      
|  cwd=None                                                                                                                                                               
|  cmd=['git', 'annex', 'version', '--raw'] 
[DEBUG  ] Launching process ['git', 'annex', 'version', '--raw']                                                                                                          
[DEBUG  ] Process 127705 started                                                                                                                                          
[DEBUG  ] Waiting for process 127705 to complete                                                                                                                          
[DEBUG  ] Process 127705 exited with return code 0                                                                                                                        
[DEBUG  ] Async run:                                                                                                                                                      
|  cwd=/home/ole/projects/elevation_encoding                                                                                                                              
|  cmd=['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'findref', '--copies', '0', 'HEAD', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3'] 
[DEBUG  ] Launching process ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'findref', '--copies', '0', 'HEAD', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3']                                                                                                                                         
[DEBUG  ] Process 127713 started                                                                                                                                          
[DEBUG  ] Waiting for process 127713 to complete                                                                                                                          
[DEBUG  ] Process 127713 exited with return code 0                                                                                                                        
[DEBUG  ] Async run:                                                                                                                                                      
|  cwd=/home/ole/projects/elevation_encoding                                                                                                                              
|  cmd=['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'wanted', 'backup-storage', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3'] 
[DEBUG  ] Launching process ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'wanted', 'backup-storage', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3']          
[DEBUG  ] Process 127732 started                                                                                                                                          
[DEBUG  ] Waiting for process 127732 to complete                                                                                                                          
[DEBUG  ] Process 127732 exited with return code 0                                                                                                                        
[DEBUG  ] Push data from Dataset(/home/ole/projects/elevation_encoding) to 'backup-storage'                                                                               
[DEBUG  ] Counted 37970744416 bytes of annex data to transfer                                                                                                             
[DEBUG  ] Async run:                                                                                                                                                      
|  cwd=/home/ole/projects/elevation_encoding                                                                                                                              
|  cmd=['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'copy', '--batch', '-z', '--to', 'backup-storage', '--fast', '--json', '--json-error-messages', '--json-progress', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3'] 
[DEBUG  ] Launching process ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'copy', '--batch', '-z', '--to', 'backup-storage', '--fast', '--json', '--json-error-messages', '--json-progress', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3']                                                                                             
[DEBUG  ] Process 127746 started                                                                                                                                          
[DEBUG  ] Waiting for process 127746 to complete                                                                                                                          
[DEBUG  ] Process 127746 exited with return code 1                                                                                                                        
Push to 'backup':  25%|███████████████████████████                                                                                 | 1.00/4.00 [00:08<00:26, 8.87s/ StepsCommandError: 'git -c diff.ignoreSubmodules=none annex copy --batch -z --to backup-storage --fast --json --json-error-messages --json-progress -c annex.dotfiles=true -c annex.retry=3' failed with exitcode 1 under /home/ole/projects/elevation_encoding
git-annex: copy: 2 failed

**Comment by OleBialas** [comment]
The drive uses ext4

**Comment by OleBialas** [comment]
Ok so it seems the problem is not specific for pushing to the sibling but more general for version 0.14.4. (I just upgraded from version 0.12.4 to use ria siblings). I get the same error when executing the `datalad run` command. Now I went back to 0.12.4 and everything is back to normal but unfortunately i can't make ria siblings on this version

**Comment by mih** [comment]
Hey @OleBialas, could you please report whether this is still an issue for you? We are at 0.15.3 now, with lots of fixes in the vicinity of the functionality that did not work for you. Thx!

**Comment by OleBialas** [comment]
Hey @mih, sorry for the late reply - I went on using the normal sibling instead of the ria one and it is working fine for me. If the info is somehow useful for you I can go ahead and try creating a ria sibling again (would be just for testing purposes), otherwise you can close the thread

**Comment by mslw** [comment]
I've now stumbled upon this issue. I don't see anything that would be actionable now, and the comments suggest that this has been most likely resolved in 0.15 - we are on 0.18. Looks like this can be safely closed.
