### ISSUE TITLE
Test if it is possible to put a virtualenv into a dedicated subdataset and (re-)use it

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5700]
@loj claims that @mih is done it before. Ping @FeHoff

**Comment by mih** [comment]
Yes, it is possible and works just like without being in a datalad dataset.

The number of files is large, so there is some slowness in the `clone/get` operation. But tolerable.

**Comment by yarikoptic** [comment]
if you are talking about python virtualenvs : might be not that straightforward and require committing executable files in unlocked mode so git preserves (if it does for those -- it doesn't for symlinks) executability.  Without preserving excitability -- utility of such virtualenv would be "hindered".
