### ISSUE TITLE
`lock_if_check_fails` overhaul for PY3?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5703]
Docs say:

> Unfortunately yoh did not find any way in Python 2 to have a context manager which just skips the entire block if some condition is met (in Python3 there is ExitStack which could potentially be used).  So we would need still to check in the block body if the context manager return value is not None.

Maybe it could be done simpler now that we are all PY3-only

**Comment by mih** [comment]
@yarikoptic worth keeping this open?

**Comment by yarikoptic** [comment]
Unlikely anyone would bother to rf this helper with a single use iirc
