### ISSUE TITLE
Question: best way to back up an RIA store to another server

### ISSUE THREAD

**Issue by mattcieslak** [datalad/datalad#5707]
Hi! I have a scenario where there is an RIA store on a local file system and we'd like to back it up to another server. I was thinking I could do something like 

```
datalad clone ria+file:///path/to/local/ria tmp_ds
cd tmp_ds
datalad create-sibling-ria -s backup ria+ssh://remote:/path/to/remote/ria
datalad push --to backup
git annex dead here
```

but when I do this there isn't any data transferred to the ria+ssh destination. Is the best option to just `rsync /path/to/local/ria tmp_ds remote:/path/to/remote/ria`?

**Comment by mattcieslak** [comment]
using `--data anything` did not copy any data either. Is there something I'm missing? I'd like to avoid copying all the annexed data into `tmp_ds` before pushing it to the backup RIA store.

**Comment by mih** [comment]
`push` will only _push_ data you have in the clone (not pull from somewhere implicitly, and then push).

That being said, RIA stores are actually specifically made to be self-contained. It is perfectly fine to rsync them. We do it all the time. Moreover, we do it not just for backups, but also to have one and the same RIA store (defined as the joint set of git-annex 's annex UUIDs) be in two physically distinct locations, while fulfilling the same "logical  role" in the git-annex network.

This allows us to have something like a `institute-storage` remote for a dataset, and it get's resolved to different locations, depending on the execution environments, while any dataset only "knows" about data to be available in a single `institute-storage` store.

And for the sake of completeness, it is not just `rsync` that could be used here, but any syncing or sending tool.

I will close this issue now, but feel free to reopen, if you have further Q.
