### ISSUE TITLE
Plans for `exc_str` replacement

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#5716]
Putting the idea for follow ups for PR #5691 here to have the discussion separated.
In that PR I leave `exc_str` as simple "proxy" shim, instead of replacing its calls.

IMO replacing this (its calls) should be taken as an occasion to go through the places where we log exceptions and make sure we don't double log (log where an exception is "handled", not where it occurs (that's why we have partially both)- we have a traceback and don't need the original place for a dedicated log message.
Furthermore I think `CapturedException` should get method `log(logger, level, msg)`, that actually does *two* things:

- log the actual exception at a dedicated level (may be configurable) - probably below DEBUG
- use `level` and `msg` for a second log message after the above that should not include the exception itself. That is for two reasons:
    1. A message containing the exception will often look weird (at least ATM) with something like "Bad thing happened:" where nothing follows the colon with exception logging disabled.
    2. From my POV a log message - particularly since logging is to some degree user output in our case - should focus on a humanly readable and understandable problem description, not a technical one. This is for people actually debugging and it's telling only, if one is somewhat fanilar with datalad's code base.

There are a few other spots, where `exc_str` is used with result dicts. I think, there should be a similar approach. Have a dedicated method for adding a result entry for the exception to a dict. This can be several key value pairs with different formats. It's then up to the result renderer to decide what to make use of.

Last but not least: In both cases (results and logging) the ultimate formatting decision should be moved from the spots where we currently use `exc_str` to log formatter(s) and result renderer(s). I'm not a fan of yet another intermediate step ATM, so I wanted to keep the use of `exc_str` as a marker for what to go through.

**Comment by adswa** [comment]
I didn't follow the issue and associated PRs, but just stumbled across a PR of mine, where when I merged ``master`` the log message with ``exc_str(e)`` came back empty. I saw in #5691 that there is now ``CapturedException`` as an alternative, but I haven't found an example how to use it, and I can't infer it from the issue description here... How can I replace my and other uses of ``exc_str`` exactly?

**Comment by bpoldrack** [comment]
@adswa 
> How can I replace my and other uses of exc_str exactly?

Although not entirely finished, this can be seen in #5883. I'd recommend waiting for me to finish description and link pointers to different cases in there, though.

**Comment by mih** [comment]
With https://github.com/datalad/datalad/issues/5975 being in progress now, this can be closed.

More info: http://docs.datalad.org/en/stable/design/exception_handling.html
