### ISSUE TITLE
test_gracefull_death: Assertion error

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5746]
continuation to #5742 found while testing #5735 with , while cmd:annex: 8.20201127 but not sure if related to having -J5 there or not

https://ci.appveyor.com/project/mih/datalad/builds/39550675/job/ns726sivdltwl9tu

```

======================================================================
FAIL: datalad.support.tests.test_parallel.test_gracefull_death
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py", line 266, in _wrap_skip_if
    return func(*args, **kwargs)
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/support/tests/test_parallel.py", line 197, in test_gracefull_death
    assert_greater_equal(len(results), 2)
AssertionError: 0 not greater than or equal to 2
```

most likely just fragility of that test

**Comment by bpoldrack** [comment]
> most likely just fragility of that test

Indeed. I encounter that constantly. However, I don't really know what to do about it which kinda questions the utility of that test. If all we actually do about it is restarting the job, then it's pointless. Suggestions?

**Comment by yarikoptic** [comment]
> Indeed. I encounter that constantly.

oh -- locally too?

that particular failure is due to producer having produced 10 "items" for consumer to munch on before it raised an exception, but consumer and code around it didn't manage to "handle" a single one.  I guess could happen if python didn't even give a chance to consumer threads and "held to" the producer thread despite it having that tiny sleep inside its loop.

but then looking at the test code
```python
    def consumer(i):
        sleep(0.001)
        yield i
...
    def producer():
        for i in range(10):
            sleep(0.0001)
            yield i
        raise ValueError()
```
it might happen that producer produces all and raises, and consumer would have no chance to even get one done in that time (sleep is 10x longer).  sending out #5747 .  If it was failing for you locally and you could try that one -- would be great.  If issue resurfaces again -- we might just disable that portion of the test I guess :-/
