### ISSUE TITLE
datalad-installer pulls outdated git-annex on windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5767]
Appveyor reports

```
  - cmd:annex: 8.20201127-ge25d2c445
```

but git-annex offers `8.20210429-gc5149cfe9`

The reason seems that the datalad-contributed autobuilds have stopped and git-annex's own installer releases are more recent.

This is a concern, because these later releases fix issues I am seeing on windows with #5749

Also, running the datalad-installer unconditionally will revert a more recent git-annex to an old one.

Trying to use `datalad-installer git-annex -m datalad/git-annex` seems to require a Github OAuth token...

**Comment by yarikoptic** [comment]
ATM windows installation is still picked up from the https://datasets.datalad.org/?dir=/datalad/packages/windows which is not automated... I will add some freshier version but wonder which one given the https://github.com/datalad/datalad/issues/5759 .  Would 8.20210621 be ok you think @mih ?

Eventually, that automated tinuous setup should replace it, and we will likely to provide only releases (we can always mint our own release I guess if really needed) there

```shell
(git)smaug:/mnt/datasets/datalad/ci/git-annex[master]git
$> ls releases/8.20210621/
git-annex-build.log                                   git-annex_8.20210621-1.ndall+1.dsc              git-annex_8.20210621-1.ndall+1_amd64.changes     git-annex_8.20210621_x64.dmg@
git-annex-installer_8.20210621_x64.exe@               git-annex_8.20210621-1.ndall+1.tar.gz@          git-annex_8.20210621-1.ndall+1_source.buildinfo
git-annex-standalone_8.20210621-1.ndall+1_amd64.deb@  git-annex_8.20210621-1.ndall+1_amd64.buildinfo  git-annex_8.20210621-1.ndall+1_source.changes
```

**Comment by mih** [comment]
Ah, thx. I forgot how this works. Besides updating our pick, I think it would make sense to make git-annex's choice of windows version accessible via the installer too. WDYT?

**Comment by yarikoptic** [comment]
Version picking should work for methods where it is possible (multiple available) indeed. Please file an issue against installer if doesn't work

**Comment by mih** [comment]
We can close this in favor of #5871. `datalad-installer` should not be used on windows.
