### ISSUE TITLE
1000FCP project 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#578]
This is the source page
http://fcon_1000.projects.nitrc.org/fcpClassic/FcpTable.html
which points to archives of different kinds.  Per each one of them we would need to generate a subdataset (e.g. Baltimor, Bangor, ...) so scraping of the cells would be needed (see xpath_match and css_match nodes to match corresponding TDs), and then submodules would need to contain tarballs, so similar pipeline to openfmri with incoming/incoming-processed/master.  First try to workout scraping of the top page -- can already be tricky.  
To learn/practice selection via css or xpath, see scrapy tutorials and use scrapy shell (`scrapy shell http://fcon_1000.projects.nitrc.org/fcpClassic/FcpTable.html`).  Although I don't expect this page to change, so we could just "hardcode" everything, I think it would be best to make it automated so everything should be scraped.

Note that Cleveland CCF  leads to another page since was incorporated to INDI (we will deal with those after), but you can easily grab tarball from there...

**Comment by glalteva** [comment]
Closed with #627
