### ISSUE TITLE
Enhance auto CHANGELOG generation

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5782]
During last weekly meeting we discussed the desire to see auto entries in changelog to be improved. Two main questions aspects came to mind

- Ability to provide custom summary for the release.  Something like what we did (sometimes) before:  e.g. https://github.com/datalad/datalad/blob/master/CHANGELOG.md#0130-june-23-2020---- . So would be nice to somehow be able to modify some perspective entry within CHANGELOG which would get plugged in into next release on top.  If not possible with auto "natively", we might need to hackup some auto extension.
- Ability to provide custom changelog entry for each PR in the PR.  ATM it is a PR title (if I get right), but that one is a bit restrictive since should be short. For some changes it is desired to provide a more elaborate description beyond title.  Is that possible?

**Comment by jwodder** [comment]
@yarikoptic 

> Ability to provide custom summary for the release.

`auto shipit` has a `--title` option that can be used to set the changelog section title.  Unfortunately, I am not aware of a way to include the version number in that title without knowing it in advance.  The simplest workaround would be to write a script for modifying the default title in the changelog in-place and invoking it as a `beforeCommitChangelog` exec hook.

> Ability to provide custom changelog entry for each PR in the PR.

`auto` supports including release notes in a PR that get added to the changelog: https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes

**Comment by adswa** [comment]
I think this wasn't autoclosed because the PR went to ``maint``, please reopen if I am mistaken.
