### ISSUE TITLE
Design flaw using downloaders in ORA special remote?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5790]
I have a dataset with a configured ORA remoted that points to a password-protected HTTP server.

```
% git annex get Simulation2GenerateRun.m
get Simulation2GenerateRun.m (from inm7-storage...) 
[INFO] Downloading 'https://archive.ds.inm7.de/c27/71672-96c4-11ea-be6a-a0369f287950/annex/objects/GX/88/MD5E-s1749--847057de59b55cf34e98757525ba7809.m/MD5E-s1749--847057de59b55cf34e98757525ba7809.m' into '.git/annex/tmp/MD5E-s1749--847057de59b55cf34e98757525ba7809.m' 
[INFO] http session: Authenticating into session for https://archive.ds.inm7.de/c27/71672-96c4-11ea-be6a-a0369f287950/annex/objects/GX/88/MD5E-s1749--847057de59b55cf34e98757525ba7809.m/MD5E-s1749--847057de59b55cf34e98757525ba7809.m 

  A non-interactive silent UI was asked for a response to a question: user. Title: You need to authenticate with 'ds.inm7.de' credentials..
```

There is no way for me to enter these credentials interactively, because interactivity is not possible at this stage (git-annex talks to the special remote binary).

I have

```
[provider:ds.inm7.de]
url_re = https.*://.*ds\.inm7\.de
authentication_type = http_basic_auth
credential = ds.inm7.de

[credential:ds.inm7.de]
type = user_password
```

but I do not think this matters or is suboptimal. I believe this is a design flaw. The only way out would be to prime the credential store prior to the first `get`. The necessary credentials are known to git (git clone works fine), but #5028 is not implemented. This only leaves #5680

**Comment by yarikoptic** [comment]
there is datalad special remote involved here, right? I remember that credentials querying was working fine even whenever nested very deep... 

e.g. here is an example on ///crcns/aa-2 where it would need credentials

<details>
<summary>prompt seems to work fine</summary> 

```shell
test3@lena:/tmp
*$> datalad install ///crcns/aa-2
install(ok): /tmp/aa-2 (dataset)                                                                          
                                                                                                          
#8 !59 [0].....................................:Thu Jul 15 13:25:58:.
test3@lena:/tmp
$> cd aa-2
total 52
20 all_cells/   4 cell_regions.csv@        4 crcns-aa2-README.txt@        4 stim_data.csv@
12 all_stims/   4 cell_stim_classes.csv@   4 download-instructions.txt@
(git)/tmp/aa-2:[master]
#9 !60 [0].....................................:Thu Jul 15 13:26:00:.
test3@lena:/tmp/aa-2
$> git annex info
trusted repositories: 0
semitrusted repositories: 7
	00000000-0000-0000-0000-000000000001 -- web
 	00000000-0000-0000-0000-000000000002 -- bittorrent
 	43c73899-037b-4cdb-8254-3ff14a20cf19 -- [datalad]
 	a14294a1-cb00-4b42-ae0d-00ca058b5065 -- test3@lena:/tmp/aa-2 [here]
 	b9de6395-acf6-431b-9a11-066155ddf6cd -- [datalad-archives]
 	da0ab986-dc70-4190-95f0-407377c64430 -- yoh@falkor:/srv/datasets.datalad.org/www/crcns/aa-2 [origin]
 	eda7ba26-724d-4b6d-924a-53217d74c890 -- yoh@smaug:/mnt/btrfs/datasets/datalad/crawl/crcns/aa-2
untrusted repositories: 0
transfers in progress: none
available local disk space: 241.77 gigabytes (+1 megabyte reserved)
local annex keys: 0
local annex size: 0 bytes
annexed files in working tree: 38118
size of annexed files in working tree: 62.92 megabytes
bloom filter size: 32 mebibytes (0% full)
backend usage: 
	MD5E: 38118
(git)/tmp/aa-2:[master]
#10 !61 [0].....................................:Thu Jul 15 13:26:06:.
test3@lena:/tmp/aa-2
$> git annex get cell_regions.csv 
get cell_regions.csv (from datalad-archives...) 
[INFO] To obtain some keys we need to fetch an archive of size 10.0 kB 

  To obtain some keys we need to fetch an archive of size 10.0 kB
You need to authenticate with 'crcns' credentials. https://crcns.org/request-account/ provides information on how to gain access
user: datalad

Please set a password for your new keyring: 

```
</details>

<details>
<summary>ps tree showing the sandwich</summary> 

```shell

test3    2821640  0.0  0.0   7168  3712 pts/13   S+   13:26   0:00  |   |                   \_ git annex get cell_regions.csv
test3    2821641  0.6  0.1 1074159180 44528 pts/13 Sl+ 13:26   0:00  |   |                       \_ /usr/lib/git-annex.linux/exe/git-annex --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/gi
test3    2821663  0.0  0.0      0     0 pts/13   Z+   13:26   0:00  |   |                           \_ [git] <defunct>
test3    2821664  0.0  0.0      0     0 pts/13   Z+   13:26   0:00  |   |                           \_ [git] <defunct>
test3    2821665  0.0  0.0      0     0 pts/13   Z+   13:26   0:00  |   |                           \_ [git] <defunct>
test3    2821666  0.0  0.0      0     0 pts/13   Z+   13:26   0:00  |   |                           \_ [git] <defunct>
test3    2821671  0.0  0.0  23740  4944 pts/13   S+   13:26   0:00  |   |                           \_ /usr/lib/git-annex.linux/exe/git --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-a
test3    2821672  0.0  0.0   8964  3420 pts/13   S+   13:26   0:00  |   |                           \_ /usr/lib/git-annex.linux/exe/git --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/git-a
test3    2821673  1.2  0.1 111328 32996 pts/13   Sl+  13:26   0:00  |   |                           \_ /usr/bin/python3 /usr/bin/git-annex-remote-datalad-archives
test3    2821689  0.0  0.0   8828  3568 pts/13   S+   13:26   0:00  |   |                               \_ /usr/lib/git-annex.linux/exe/git --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/g
test3    2821690  0.0  0.0 1074085448 26600 pts/13 Sl+ 13:26   0:00  |   |                               |   \_ /usr/lib/git-annex.linux/exe/git-annex --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu:
test3    2821704  0.0  0.0   8828  3468 pts/13   S+   13:26   0:00  |   |                               \_ /usr/lib/git-annex.linux/exe/git --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /usr/lib/g
test3    2821706  0.5  0.1 1074159180 44440 pts/13 Sl+ 13:26   0:00  |   |                                   \_ /usr/lib/git-annex.linux/exe/git-annex --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu:
test3    2821718  0.0  0.0      0     0 pts/13   Z+   13:26   0:00  |   |                                       \_ [git] <defunct>
test3    2821719  0.0  0.0      0     0 pts/13   Z+   13:26   0:00  |   |                                       \_ [git] <defunct>
test3    2821720  1.8  0.1 146212 50824 pts/13   S+   13:26   0:00  |   |                                       \_ /usr/bin/python3 /usr/bin/git-annex-remote-datalad
test3    2821732  0.0  0.0  23728  4844 pts/13   S+   13:26   0:00  |   |                                       \_ /usr/lib/git-annex.linux/exe/git --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /u
test3    2821733  0.0  0.0   8960  3524 pts/13   S+   13:26   0:00  |   |                                       \_ /usr/lib/git-annex.linux/exe/git --library-path /usr/lib/git-annex.linux//lib/x86_64-linux-gnu: /
```
</details>

<details><summary>DataLad 0.14.0 WTF (datalad, dependencies)</summary>

# WTF
- datalad: version=0.14.0 full_version=0.14.0
- dependencies: cmd:git=2.24.0 cmd:annex=8.20210630-1~ndall+1 cmd:bundled-git=2.24.0 cmd:system-git=2.32.0 cmd:system-ssh=8.4p1 cmd:7z=16.02 annexremote=1.4.3 appdirs=1.4.4 boto=2.49.0 exifread=2.3.2 git=3.1.14 gitdb=4.0.5 humanize=0.0.0 iso8601=0.1.13 keyring=22.0.1 keyrings.alt=UNKNOWN msgpack=1.0.0 mutagen=1.45.1 requests=2.25.1 scrapy=2.4.1 wrapt=1.12.1

</details>

so the question might be why it "A non-interactive silent UI was asked for a response to a question"? (also note that I tried under a different user and system wide datalad was old 0.14.0 -- so if doesn't work with newer -- then some regression)

**Comment by mih** [comment]
This was done with: 

```
% datalad --version
datalad 0.14.3
```

from the Debian package.

> there is datalad special remote involved here, right?

It is the ORA git-annex special remote that comes with datalad. Not the `datalad` special remote that comes with DataLad. Not sure which one you were referring to. Ping @bpoldrack

**Comment by bpoldrack** [comment]
The remote ORA simply calls `download_url`. I don't see how this could interact with the user while the ORA remote's stdin/stdout is connected to git-annex. However, if that works with the datalad special remote, I need to check how that one does achieve it.

**Comment by yarikoptic** [comment]
FWIW -- exactly for that purpose of being possible to talk to user from deep within nested special remote, we do not use stdin/stdout ;-)  we cruely (ab)use `getpass` https://github.com/datalad/datalad/blob/master/datalad/ui/dialog.py#L163 which IIRC uses tty directly.

**Comment by yarikoptic** [comment]
I can only repeat that IMHO the problem lies in why "A non-interactive silent UI was asked for a response to a question"? i.e. why `SilentConsoleLog` is used and not `DialogUI`?

**Comment by mih** [comment]
Connecting to our discussion on why things could turn non-interactive. Here is a related issue on windows https://github.com/datalad/datalad/issues/5124

**Comment by yarikoptic** [comment]
may be would be of help, or at least would resolve some mystery on how `datalad` built-in special remotes manage to get a prompt:

- in https://github.com/yarikoptic/datalad/blob/HEAD/datalad/customremotes/main.py#L122 (main process of special remote) we `ui.set_backend('annex')` 
- that one handled here: https://github.com/yarikoptic/datalad/blob/HEAD/datalad/ui/__init__.py#L51
- which is a dedicated `UnderAnnexUI` https://github.com/yarikoptic/datalad/blob/HEAD/datalad/ui/dialog.py#L216:7 which subclasses from `DialogUI` and thus an `InteractiveUI`. 

So even though special remote runtime is (probably) not treated as interactive, its UI is "forcefully" interactive, while not pestering stdin/stdout (AFAIK) and anything displayed, is displayed to stderr (i guess, due to https://github.com/yarikoptic/datalad/blob/HEAD/datalad/ui/dialog.py#L223) .  This way we still can display (stderr) and `input` (uses `input` tty directly iirc), even if deeply nested.

I guess any other helper/special remote which is using an alternative special remote base class, would need to do the same if expects any interaction.

**Comment by yarikoptic** [comment]
will send a quick&dirty PR shortly ;-)
