### ISSUE TITLE
INDI 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#580]
Is a heterogeneous collection of datasets, some of which, such as HCP1000 ( #578) will be crawled separately.  Otherwise it should be quite straightforward -- primarily tarballs -- after we figure out what/how is versioned and how to harmonize appearance, and probably after we do support meta-data

**Comment by mih** [comment]
Available on datasets.datalad.org now.

**Comment by yarikoptic** [comment]
to be fair -- we have only a subset of indi datasets... and majority of them are published as 'independent' from indi (per Cameron's suggestion).  There is more datasets from indi which should come to datasets.datalad.org
