### ISSUE TITLE
Unconditional use of `annex.retry` turns error reporting into a mess

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5808]
Example:

```
git annex copy --to expdir --fast --json --json-error-messages -c annex.retry=3
{"command":"copy","note":"to expdir...","success":false,"input":["123"],"key":"MD5E-s4--ba1f2511fc30423bdbb183fe33f3dd0f","error-messages":["  remote is configured with exporttree=yes; use `git-annex export` to store content on it","  remote is configured with exporttree=yes; use `git-annex export` to store content on it","  remote is configured with exporttree=yes; use `git-annex export` to store content on it","  This could have failed because --fast is enabled."],"file":"123"}
git-annex: copy: 1 failed
```

The command execution fails due to a setup issue (#3127). However, we unconditionally configure any call to `git-annex` to have `annex.retry` set (and we have 3 by default). From the documentation one can guess that this was only meant to be used for data transfer:

```
On transfer failure, annex.retry (sans "datalad.") controls the number of times that git-annex retries. DataLad will call git-annex with annex.retry set to the value here unless the annex.retry is explicitly configured
```

But is presently used for ANY `git-annex` call, unless `annex.retry` is set directly already.

This is not only a UX issue due to error message inflation. Trying 3 times for non data transport related errors is likely also having a performance impact.

This needs to be RF'ed to take `annex.retry` out of `_annex_common_options` and turn into targeted usage for calls where this is actually meaningful.

**Comment by adswa** [comment]
I feel like I don't have enough background information to tackle this. Can we established for which command a retry would be meaningful? The only one I can think of is ``get``, but I am sure there are more to be considered.

**Comment by mih** [comment]
I think `get` is the primary one. `copy` and `move` maybe make sense. Doing it for `sync` is already nightmare-ish. I am not sure if git-annex even considers it for anything else.

In general I would just vote to turn it off by default. If people want to protect against flaky behavior, they can turn it on for their use cases. Masking a wide range of errors like this has no net benefit IMHO, and can have actual negative impact (think: hammering services DDOS style because of parallelization times retries).

From my POV adding it to the `get` docs as a supported tuning option and switching the default to off would be the best change.

**Comment by yarikoptic** [comment]
3x of attempts wouldn't cause DoS (if does -- something else needs to be fixed IMHO).  Those retries were introduced to make git-annex (and thus datalad) use robust on CIs and in some user use-cases -- timed out/dropped connections aren't that rare, and it is painful to see some CI runs fail randomly because some flaky connection in some run. Having just those few retries pretty much made that issue disappear from encounter.  I would strongly vote to keep annex retrying those few times.

`sync` is also a data transfer command AFAIK, but I do not recall if I ever encountered explicit desire for needing `retry` on it.

If it is just a UX aspect where we would like to not report multiple duplicate errors from git-annex, may be that is what we should do -- not report multiple failed commands from git-annex and just report unique ones?

**Comment by mih** [comment]
re CI use: I agree, but my point is that it is a specific use case and set of requirements. It is trivial to put `git config --system annex.retry 3` in the CI setup.

It is not just a UX aspect, because we unconditionally send this setting to any `git annex` invocation. We have no idea what it would do in cases we did not think of (now or in the future). At minimum it should be limited to the intended scenarios.

Moreover, git-annex reports the failure output as a single command execution, so what you suggest needs parsing, de-duplication, and failing to do it properly in unforeseen corner cases IMHO.

Given your viewes, I think it is uncontroversial to separate the two issues: passing the switch unconditionally and uniformly to any git annex command, and specific value to use for `get`.
