### ISSUE TITLE
FOI: pyfakefs

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5827]
probably largely not really applicable since majority of tests need git/git-annex interactions with the filesystem, but spotted it being used while backporting for debian for `importlib_version`: http://github.com/jmcgeheeiv/pyfakefs

pyfakefs implements a fake file system that mocks the Python file system modules. Using pyfakefs, your tests operate on a fake file system in memory without touching the real disk. The software under test requires no modification to work with pyfakefs.

so - not sure if of an immediate use, but might come handy I guess (e.g. may be while producing fake tarballs etc) to speed up at least some testing

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
