### ISSUE TITLE
(Re)design of `drop`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5832]
Companion of #5842 (to be discussed in conjunction)

Context: This is about approaching an improved implementation of the `drop` command, not in isolation, but in the context of a reconsideration of the `drop/uninstall/remove` combo, with the partial goal to replace the old `remove` entirely, and with that make progress towards #3368

This is an opportunity to reconsider the role of `drop` in the API, and amend it with the missing functionality we have identified (issues are linked below). This draft description is not about making a contrast to what the present `drop` is doing (there are massive overlaps), but about a comprehensible concept of what `drop` does, and does not. The initial design draft is the result of a discussion of @adswa and @mih.

### Basic concept

`drop` is the antagonist of `get`. Whatever a `drop` can do, should be undoable by a subsequent `get` (given unchanged remote availability).

Like `get`, `drop` primarily operates on a mandatory path specification (to discover relevant files and sudatasets to operate on).

`drop` has `--type` parameter that serves as an extensible "mode-switch" to cover all relevant scenarios, like 'drop all file content in the work-tree' (e.g. `--type files`, default, #5858), 'drop all keys from any branch' (i.e. `--type allkeys`, #2328), but also '"drop" AKA uninstall entire subdataset hierarchies' (e.g. `--type all`), or drop preferred content (`--type preferred-content`, #3122).

`drop` prevents data loss by default (#4750). Like `get` it features a `--reckless` "mode-switch" to disable some or all potentially slow safety mechnism, i.e. 'key available in sufficient number of other remotes', 'main or all branches pushed to remote(s)' (#1142), 'only check availability of keys associated with the worktree, but not other branches'. "Reckless operation" can be automatic, when following a reckless `get` (#4744).

`drop` properly manages annex lifetime information, e.g. by announcing an annex as `dead` on removal of a repository (#3887).

Like `get`, drop supports parallization #1953 

`datalad drop` is not intended to be a comprehensive frontend to `git annex drop` (e.g. limited support for e.g. #1482 outside standard use cases like #2328).

Note: It is understood that the current `uninstall` command is largely or completely made obsolete by this `drop` concept.

Given the development in #5842  towards the complete obsolescence of `remove` it becomes necessary to import one of its proposed features:

`drop` should be able to recognize a botched attempt to delete a dataset with a plain rm -rf, and act on it in a meaningful way, even if it is just hinting at chmod + rm -rf.

### Use cases

The following use cases operate in the dataset hierarchy depicted below.

```
super
├── dir
│   ├── fileD1
│   └── fileD2
├── fileS1
├── fileS2
├── subA
│   ├── fileA
│   ├── subsubC
│   │   ├── fileC
│   └── subsubD
└── subB
    └── fileB
```

Unless explicitly stated, all command are assumed to be executed in the root of `super`.

- `datalad drop fileS1`
   Drops the file content of `file1` (as currently done by `drop`)
- `datalad drop dir`
   Drop all file content in the directory (``fileD{1,2}``; as currently done by `drop`
- `datalad drop subB`
   Drop all file content from the entire `subB` (`fileB`)
- `datalad drop subB --type all`
   Same as above (default `--type files`), because it is not operating in the context of a superdataset (no automatic upward lookups). Possibly hint at next usage pattern).
- `datalad drop -d . subB --type all`
  Drop all from the superdataset under this path. I.e. drop all from the subdataset and drop the subdataset itself (AKA uninstall)
- `datalad drop subA --type all`
  Error: "``subA`` contains subdatasets, forgot --recursive?"
- `datalad drop -d . subA -r --type all`
  Drop all content from the subdataset (``fileA``) and its subdatasets (``fileC``), uninstall the subdataset (``subA``) and its subdatasets (``subsubC``, ``subsubD``)
- `datalad drop subA -r --type all`
  Same as above, but keep ``subA`` installed
- `datalad drop sub-A -r`
   Drop all content from the subdataset and its subdatasets (``fileA``, ``fileC``)
- `datalad drop . -r --type all`
  Drops all file content and subdatasets, but leaves the superdataset repository behind
- `datalad drop -d . subB`
  Does nothing and hints at alternative usage, see https://github.com/datalad/datalad/issues/5832#issuecomment-889656335
- `cd .. && datalad drop super/dir` 
  Like `get`, errors because the execution is not associated with a dataset. This avoids complexities, when the given `path`'s point to multiple (disjoint) datasets. It is understood that it could be done, but it is intentionally not done. `datalad -C super drop dir` or `datalad drop -d super super/dir` would work.

**Comment by aqw** [comment]
> `drop` is the antagonist of `get`. Whatever a drop can do, should be undoable by a subsequent get (given unchanged remote availability).

I think this is a step in the right direction when it comes to the path of least surprise and DataLad being consistent with itself. This is _good_.

I often explain to *nix newcomers that the options for `ls` and `rm` are very similar (they're not identical, but it's a good enough approximation for beginners). When they're first learning globbing and flags, people have (understandable) anxiety with using `rm`. I explain that they can run that same thing with `ls` first. Once they're convinced that it only lists the files they want to remove, then swap the `ls` for `rm`.

+1 for steps in this direction.

**Comment by loj** [comment]
I like this direction. It covers all instances that I currently use `uninstall` and `drop`.

I especially like the ability to distinguish between `files` vs `all` with `--type` for dropping subdataset content vs the full subdataset itself. This is more intuitive to me than the current situation.

Quick clarification, given that `--type files` is the default, if I run `datalad drop -d . subB`, it would only drop the files in `subB` and not the `subB` dataset itself, correct?

**Comment by bpoldrack** [comment]
> Quick clarification, given that --type files is the default, if I run datalad drop -d . subB, it would only drop the files in subB and not the subB dataset itself, correct?

That would be my question, too and ultimately is a matter of making the `-d` option consistent and understandable across commands (touching a broader conceptual issue). I'm undecided what such a call should result in. On the one hand it's most convenient (and somewhat intuitive) to do what @loj suggests. On the other: In a way this result contributes to the vagueness of the notion of `-d` and thereby overall confusion, I think. If it is supposed to mean "operate on THIS dataset", then those files can't be dropped w/o `-r` (they are not part of THIS dataset). So, not sure. I lean towards the suggestion, but I we should use this occasion to get very clear about the meaning and implications of `-d`. In some cases it's very clear (particularly when thinking about it in an object oriented way), but in others not so much.

Other than that: I, too, like it very much.

**Comment by mih** [comment]
> Quick clarification, given that `--type files` is the default, if I run `datalad drop -d . subB`, it would only drop the files in `subB` and not the `subB` dataset itself, correct?

Good question! I believe it should do nothing, but provide a hint on alternative usage.

`drop -d .` means drop from `.` (which is `super`), so drop `subB` from `super`. Given that the default for `--type` would be `files` in this draft concept, there is no file that matches `subB` in `super`, hence nothing is done. Dropping all files from `subB` would be `drop -d subB` or `drop -d . subB -r -R 1` (again keep in mind the implicit `--type files`.

One might argue whether `--type files` is the optimal default. However, given that we reuse the `drop` command slot for this redesign, we also have to keep a transition in mind, and keeping this default seems to be the easiest angle.

**Comment by mih** [comment]
I extended the list of use cases further.

**Comment by loj** [comment]
> I believe it should do nothing, but provide a hint on alternative usage.

This makes sense. Thanks for clarifying. :-)

> However, given that we reuse the drop command slot for this redesign, we also have to keep a transition in mind, and keeping this [`--type files`] default seems to be the easiest angle.

I agree with this as well.

**Comment by yarikoptic** [comment]
+1 on making `drop` parallel `get` better!  But then might be worth right away looking into `get` interface to harmonize its `-n, --no-data` into `--type` as well, after all `preferred-content` support might even be more interesting/appropriate for `get` than for `drop`.  Also note that it might need to be `non-preferred-content` to signal that most likely what will be dropped is content which is **not** preferred (actual desire behind #3122 if I read it right), and actually there could still be `preferred-content` setting to drop exactly that -- preferred content. Note that we refer to such content as `wanted` (not `preferred`) mirroring actual annex command.  

Similarly to our past discussion on `push --data` I feel that we are mixing dimensions here (files/directories vs "filter" for files) which might eventually show limitation, asking for separating out `--type` from some `--filter` or alike.

I wonder if there could be a better choice instead of (too generic, might be confused with a "type of `get`" not the "type of stuff `get` works on",  etc) `--type`: if we should follow the course set by `update --how` and have `drop --what` .  FWIW, we already have `datalad clean --what` so makes sensible parallel.

> Note: It is understood that the current `uninstall` command is largely or completely made obsolete by this `drop` concept.

I think it would be ok to keep higher level, "porcelain" commands as far as they are just interfaces to other, possibly more lower-level commands.  E.g. I might find it much more user friendly to use `datalad uninstall -r subA` in favor of `datalad drop -d . subA -r --type all` . Similarly `install` is also largely obsolete with `datalad clone ... && datalad -C ... get` tandem (both of which it uses AFAIK), but I find a singular `install` command invocation handy.

**Comment by yarikoptic** [comment]
Also, in redesign of `drop`, I would like to bring attention to a recently added capability in git-annex in response to [original todo: option to `drop path` to not drop "all copies"](https://git-annex.branchable.com/todo/option_to___96__drop_path__96___to_not_drop___34__all_copies__34__/) where @joeyh added `--excludesamecontent=glob` and `--includesamecontent=glob` ... haven't yet tried it or looked how to apply to original "todo" case (not sure if globbing everything else is an easy approach).  But it might be something to foresee for `drop` interface/(re)implementation

**Comment by mih** [comment]
@yarikoptic seems to be asking for a rename of `--type` to `--what`. As in the discussion in the `push` context before, I cannot get behind the rational, but I see no problem using this name instead.

re #5858: I think this is sensible default behavior.

re `uninstall`: I have no expectation that `uninstall` would be removed from the API (at least any time soon). We have a history of keeping things around until there is no user is left alive. I do, however, have no plans to invest time into `uninstall`. Which also means that the old drop and associated functionality like `if_dirty` will need to be kept around. They are already alien and partially broken, and lettig them rot further will not make things worse. It is worth mentioning that this is different for `remove` -- which keeps `annotate_paths` a necessity. If the desire to preserve extends to `remove`, I think it would be better to keep the status quo, and develop alternatives elsewhere.

To keep `uninstall` around, the old `drop` code needs to move into it to free up the slot in the namespace. Even more work.

**Comment by mih** [comment]
Edited the feature list to include the ability to help cleaning up a botched removal of a dataset.

**Comment by mih** [comment]
I will close this in favor of trying an improved discussion process within a PR, as suggested by @yarikoptic 

Please head over to #5867
