### ISSUE TITLE
Do we want auto-adjust version in CITATION.cff ?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5843]
added in https://github.com/datalad/datalad/commit/b02c4306edc20186bd8bfea83c55c77de09f0f66 since required.  But it is hardcoded ATM.  If we would like to have it updated, I guess should be done by `auto` triggered within `.github/workflows/release.yml`

On the other related hand - that CITATION.cff then also should be adjusted by tributors workflow in case new contributors are added etc.  FWIW, filed https://github.com/con/tributors/issues/58 .

**Comment by mih** [comment]
I think I would be fine either way. I used that version, because it is the one referred to in the JOSS paper, so it kinda made sense to connect the too. Always fresh is also fine.
