### ISSUE TITLE
export-archive-ora filter files based on git-annex matching options.

### ISSUE THREAD

**Issue by bpinsard** [datalad/datalad#5845]
#### What is the problem?

More a feature request / feasibility question: 
Currently, when exporting an archive for ORA, it will add all keys present in the current repo to the archive, while one might want to filter the archive content (eg. based on distribution-restriction metadata) similar to the `wanted` option for special-remotes.

Do you think it would be possible to replace the following glob:
https://github.com/datalad/datalad/blob/master/datalad/distributed/export_archive_ora.py#L139
with a call to `git-annex find --format='.git/annex/objects/${hashdirmixed}${key}/${key} '` with optional [git-annex-matching-options](https://git-annex.branchable.com/git-annex-matching-options/) passed as an option to the `export-archive-ora` command line?
If you think this is of interest, I could work on a PR.

Thanks!

**Comment by mih** [comment]
I think that is a great idea!

**Comment by bpoldrack** [comment]
I like that, too.

Since you are pointing to it, @bpinsard : Considering `wanted`/preferred content could be considered as a filter, too. Thinking of an option to name a particular ORA remote to make that export for. If that remote is already configured in such ways, this could then be used to filter the to be included keys.

**Comment by mih** [comment]
Being able to do an export for a specifically configured remote would be very convenient, indeed!

**Comment by bpinsard** [comment]
Great, so the changes should add:
- `--for` option specifying the special remote from which to get the wanted/preferred content : runs `git-annex find --want-get <remote>`
- either take all other options to pass as  git-annex-matching-options to `git-annex find` (if that is possible for the parser to have a sort of wildcard.) 
- or have `--wanted/filter` to which we give a string of git-annex arguments from git-annex-matching-options or `--branch=ref` 

Should it raise an error/warning if the wanted content is missing? ( or add a `--missing [ignore,error]` )

Should it call: http://docs.datalad.org/en/stable/generated/datalad.support.annexrepo.html#datalad.support.annexrepo.AnnexRepo.find (in which case, it needs to be extended to allow passing more options) or make a custom call to http://docs.datalad.org/en/stable/generated/datalad.support.annexrepo.html#datalad.support.annexrepo.AnnexRepo.call_annex_items_ ?

**Comment by mih** [comment]
Done with #6234
