### ISSUE TITLE
TST: wrong invocation of "echo" on Windows?

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#5870]
I ran tests under Windows and noticed a few failures where ``subprocess.Popen()`` would complain with a WinError2 ("Can't find the specified file"), such as

```
======================================================================
ERROR: datalad.tests.test_nonasyncrunner.test_inside_async
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\datalads\AppData\Local\Programs\Python\Python39\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\datalads\repos\datalad\datalad\tests\test_nonasyncrunner.py", line 141, in test_inside_async
    result = loop.run_until_complete(main())
  File "C:\Users\datalads\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\datalads\repos\datalad\datalad\tests\test_nonasyncrunner.py", line 138, in main
    return runner.run(["echo", "abc"], StdOutCapture)
  File "C:\Users\datalads\repos\datalad\datalad\cmd.py", line 149, in run
    results = run_command(
  File "C:\Users\datalads\repos\datalad\datalad\nonasyncrunner.py", line 194, in run_command
    process = subprocess.Popen(cmd, **kwargs)
  File "C:\Users\datalads\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\datalads\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

```
======================================================================
ERROR: datalad.tests.test_witless_runner.test_runner_no_stdin_no_capture
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\datalads\AppData\Local\Programs\Python\Python39\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\datalads\AppData\Local\Programs\Python\Python39\lib\site-packages\nose\tools\nontrivial.py", line 97, in newfunc
    result = func(*arg, **kw)
  File "C:\Users\datalads\repos\datalad\datalad\tests\test_witless_runner.py", line 170, in test_runner_no_stdin_no_capture
    runner.run(
  File "C:\Users\datalads\repos\datalad\datalad\cmd.py", line 149, in run
    results = run_command(
  File "C:\Users\datalads\repos\datalad\datalad\nonasyncrunner.py", line 194, in run_command
    process = subprocess.Popen(cmd, **kwargs)
  File "C:\Users\datalads\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\datalads\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

In these cases, the test would call ``echo`` with some arguments, e.g.,  ``runner.run(["echo", "abc"]``. On Windows, [``echo`` is a command within ``cmd.exe``](https://stackoverflow.com/questions/44371876/why-is-popencmd-exe-echo-a-shell-true-not-running-echo). When I replace ``echo`` with ``"C:\\WINDOWS\\system32\\cmd.exe", "/c", "echo"``, ``subprocess.Popen()`` can execute the command. 

I know that via some magic, some things replace the Unixy call with a Windows equivalent. E.g., during start-up of datalad, I see a ``'C:\\WINDOWS\\system32\\cmd.exe /c "ver"'`` call being executed via ``Subprocess.Popen()``. But I am not sure how that works, or if this is intended for the tests at hand, or even anyhow useful

**Comment by bpoldrack** [comment]
> But I am not sure how that works

Would need to try, but I guess that happens, when the `Popen` call gets `shell=True` (which isn't always what we'd want, but for something like this seems better than detecting `cmd.exe` ourselves (Don't know to what extend location may vary across Windows systems).

**Comment by adswa** [comment]
I read through the [[docs](http://omz-software.com/editorial/docs/library/subprocess.html), and ``shell=True`` behaves slightly different between Unix and Windows. 

> On Unix with shell=True, the shell defaults to /bin/sh. If args is a string, the string specifies the command to execute through the shell. This means that the string must be formatted exactly as it would be when typed at the shell prompt. This includes, for example, quoting or backslash escaping filenames with spaces in them. If args is a sequence, the first item specifies the command string, and any additional items will be treated as additional arguments to the shell itself. That is to say, Popen does the equivalent of:

> ``Popen(['/bin/sh', '-c', args[0], args[1], ...])``

I think we set ``shell=True``  independently of OS, just whenever the command is a string, following the Unix logic:

https://github.com/datalad/datalad/blob/c9a3f713c7e3db0c8d366af036913f7e53de9a2f/datalad/nonasyncrunner.py#L181-L190


> (Don't know to what extend location may vary across Windows systems).

Appearently, there is an env variable for this: ``ComSpec=C:\WINDOWS\system32\cmd.exe``. The docs say

> On Windows with shell=True, the COMSPEC environment variable specifies the default shell. The only time you need to specify shell=True on Windows is when the command you wish to execute is built into the shell (e.g. dir or copy). You do not need shell=True to run a batch file or console-based executable.

> Warning
Passing shell=True can be a security hazard if combined with untrusted input. See the warning under Frequently Used Arguments for details. 

So maybe it would be worthwhile to ensure that ``shell`` is never True under Windows unless a built-in command ([only a handful exist](https://renenyffenegger.ch/notes/Windows/dirs/Windows/System32/cmd_exe/commands/index)) is run? But then again, I'm not sure how useful this, at the moment this would "only" be a fix for failing tests

**Comment by bpoldrack** [comment]
> So maybe it would be worthwhile to ensure that shell is never True under Windows unless

Just to be clear: That security hazard warning is not specific to Windows. We shouldn't do it on Unix either from my POV.
But: For shell-builtins, we need a shell, obv. We just should make extra sure, that there's no way user input or possibly manipulated repository content is leaking into such invocations.

> But then again, I'm not sure how useful this, at the moment this would "only" be a fix for failing tests

Yes, only makes sense for things like `create-sibling` or the ORA special remote where we need to internally invoke such commands. A test that is simply executed something completely arbitrary to see it executed, should simply use another command instead.

**Comment by mih** [comment]
I will push a fix for this shortly. Thx for the report.
