### ISSUE TITLE
Cannot save datalad subdataset - "index file smaller than expected"

### ISSUE THREAD

**Issue by m-petersen** [datalad/datalad#5872]
#### What is the problem?

I am using datalad in a setup with multiple nested subdatasets within a superdataset for the processing of neuroimaging data on a HPC. In doing so, I try to adhere to the datalad handbook (http://handbook.datalad.org/en/latest/beyond_basics/101-171-enki.html) and some posts on neurostars.

Essentially the directory hierarchy looks like

root
|-code
|-envs
|-data* |-smriprep |-sub-XYZ

\* only data/ is a pure directory the rest are datalad datasets

It's the second time I am facing an error. This time it occured during executing "datalad save" within the smriprep subdataset preventing me from saving it. Last time it occured while trying to merge results to a subdataset for freesurfer outputs.

´
Total:   0%|    | 0.00/1.00 [00:39<?, ? datasets/sCommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -c annex.retry=3 -- .datalad/.gitattributes .datalad/config .gitattributes .gitmodules' failed with exitcode 1 under /work/fatx405/projects/CSI_XYZ/data/smriprep
fatal: /work/fatx405/projects/CSI_XYZ/data/smriprep/.git/annex/index: index file smaller than expected
fatal: /work/fatx405/projects/CSI_XYZ/data/smriprep/.git/annex/index: index file smaller than expected
fatal: /work/fatx405/projects/CSI_XYZ/data/smriprep/.git/annex/index: index file smaller than expected
git-annex: fd:22: hPutBuf: resource vanished (Broken pipe)
´

#### What steps will reproduce the problem?
Not sure about that. I realized the type of error with some delay to the last time working with the subdataset so I wasn't able to precisely relate it back to my behaviour. I think the last thing I have done in smriprep/ is deleting some branches containing faulty computation results. 

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.14.4

<details>
<summary>datalad wtf</summary>
<br>
# WTF
## credentials 
  - keyring: 
    - active_backends: 
      - PlaintextKeyring with no encyption v.1.0 at /home/fatx405/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/fatx405/.config/python_keyring/keyringrc.cfg
    - data_root: /home/fatx405/.local/share/python_keyring
## datalad 
  - full_version: 0.14.4
  - version: 0.14.4
## dataset 
  - id: 90cec49a-ae22-4d5f-ae05-98b7d852de70
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /work/fatx405/projects/CSI_POSTCOVID/data/smriprep
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.5.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20201104-g13bab4f2c
  - cmd:bundled-git: 2.29.2
  - cmd:git: 2.29.2
  - cmd:system-git: 2.29.2
  - cmd:system-ssh: 7.4p1
  - exifread: 2.1.2
  - humanize: 3.2.0
  - iso8601: 0.1.14
  - keyring: 22.0.1
  - keyrings.alt: 4.0.2
  - msgpack: 1.0.2
  - mutagen: 1.41.1
  - requests: 2.25.1
  - wrapt: 1.12.1
## environment 
  - LANG: en_US.UTF-8
  - PATH: /sw/env/system-gcc/parallel/20180322/bin:/work/fatx405/miniconda3/bin:/sw/link/git/2.32.0/bin:/sw/env/system-gcc/singularity/3.5.2-overlayfix/bin:/sw/batch/slurm/19.05.6/bin:/sw/rrz/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
## extensions 
  - container: 
    - description: Containerized environments
    - entrypoints: 
      - datalad_container.containers_add.ContainersAdd: 
        - class: ContainersAdd
        - load_error: None
        - module: datalad_container.containers_add
        - names: 
          - containers-add
          - containers_add
      - datalad_container.containers_list.ContainersList: 
        - class: ContainersList
        - load_error: None
        - module: datalad_container.containers_list
        - names: 
          - containers-list
          - containers_list
      - datalad_container.containers_remove.ContainersRemove: 
        - class: ContainersRemove
        - load_error: None
        - module: datalad_container.containers_remove
        - names: 
          - containers-remove
          - containers_remove
      - datalad_container.containers_run.ContainersRun: 
        - class: ContainersRun
        - load_error: None
        - module: datalad_container.containers_run
        - names: 
          - containers-run
          - containers_run
    - load_error: None
    - module: datalad_container
    - version: 1.1.4
  - hirni: 
    - description: HIRNI workflows
    - entrypoints: 
      - datalad_hirni.commands.dicom2spec.Dicom2Spec: 
        - class: Dicom2Spec
        - load_error: None
        - module: datalad_hirni.commands.dicom2spec
        - names: 
          - hirni-dicom2spec
          - hirni_dicom2spec
      - datalad_hirni.commands.import_dicoms.ImportDicoms: 
        - class: ImportDicoms
        - load_error: None
        - module: datalad_hirni.commands.import_dicoms
        - names: 
          - hirni-import-dcm
          - hirni_import_dcm
      - datalad_hirni.commands.spec2bids.Spec2Bids: 
        - class: Spec2Bids
        - load_error: None
        - module: datalad_hirni.commands.spec2bids
        - names: 
          - hirni-spec2bids
          - hirni_spec2bids
      - datalad_hirni.commands.spec4anything.Spec4Anything: 
        - class: Spec4Anything
        - load_error: None
        - module: datalad_hirni.commands.spec4anything
        - names: 
          - hirni-spec4anything
          - hirni_spec4anything
    - load_error: None
    - module: datalad_hirni
    - version: 0.0.8
  - metalad: 
    - description: DataLad semantic metadata command suite
    - entrypoints: 
      - datalad_metalad.aggregate.Aggregate: 
        - class: Aggregate
        - load_error: None
        - module: datalad_metalad.aggregate
        - names: 
          - meta-aggregate
          - meta_aggregate
      - datalad_metalad.dump.Dump: 
        - class: Dump
        - load_error: None
        - module: datalad_metalad.dump
        - names: 
          - meta-dump
          - meta_dump
      - datalad_metalad.extract.Extract: 
        - class: Extract
        - load_error: None
        - module: datalad_metalad.extract
        - names: 
          - meta-extract
          - meta_extract
    - load_error: None
    - module: datalad_metalad
    - version: 0.2.1
  - neuroimaging: 
    - description: Neuroimaging tools
    - entrypoints: 
      - datalad_neuroimaging.bids2scidata.BIDS2Scidata: 
        - class: BIDS2Scidata
        - load_error: None
        - module: datalad_neuroimaging.bids2scidata
        - names: 
          - bids2scidata
    - load_error: None
    - module: datalad_neuroimaging
    - version: 0.3.1
  - ukbiobank: 
    - description: UKBiobank dataset support
    - entrypoints: 
      - datalad_ukbiobank.init.Init: 
        - class: Init
        - load_error: None
        - module: datalad_ukbiobank.init
        - names: 
          - ukb-init
          - ukb_init
      - datalad_ukbiobank.update.Update: 
        - class: Update
        - load_error: None
        - module: datalad_ukbiobank.update
        - names: 
          - ukb-update
          - ukb_update
    - load_error: None
    - module: datalad_ukbiobank
    - version: 0.3.2
  - webapp: 
    - description: Generic web app support
    - entrypoints: 
      - datalad_webapp.WebApp: 
        - class: WebApp
        - load_error: None
        - module: datalad_webapp
        - names: 
          - webapp
          - webapp
    - load_error: None
    - module: datalad_webapp
    - version: 0.3
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 8
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20201104-g13bab4f2c
## location 
  - path: /work/fatx405/projects/CSI_POSTCOVID/data/smriprep
  - type: dataset
## metadata_extractors 
  - annex (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - bids (datalad-neuroimaging 0.3.1): 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.bids
    - version: None
  - datacite (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - dicom (datalad-neuroimaging 0.3.1): 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.dicom
    - version: None
  - exif (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - metalad_annex (datalad-metalad 0.2.1): 
    - distribution: datalad-metalad 0.2.1
    - load_error: None
    - module: datalad_metalad.extractors.annex
    - version: None
  - metalad_core (datalad-metalad 0.2.1): 
    - distribution: datalad-metalad 0.2.1
    - load_error: None
    - module: datalad_metalad.extractors.core
    - version: None
  - metalad_custom (datalad-metalad 0.2.1): 
    - distribution: datalad-metalad 0.2.1
    - load_error: None
    - module: datalad_metalad.extractors.custom
    - version: None
  - metalad_runprov (datalad-metalad 0.2.1): 
    - distribution: datalad-metalad 0.2.1
    - load_error: None
    - module: datalad_metalad.extractors.runprov
    - version: None
  - nidm (datalad-neuroimaging 0.3.1): 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.nidm
    - version: None
  - nifti1 (datalad-neuroimaging 0.3.1): 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.nifti1
    - version: None
  - xmp (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: Exempi library not found. [exempi.py:_load_exempi:60]
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.7.9
## system 
  - distribution: CentOS Linux/7.9.2009/Core
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 306
  - name: Linux
  - release: 4.14.240-1.0.33.el7.rrz.x86_64
  - type: posix
  - version: #1 SMP Thu Jul 22 18:29:43 CEST 2021
</details>

**Comment by m-petersen** [comment]
Well, removing .git/annex/index solved the issue.

**Comment by m-petersen** [comment]
So this type of error remains to be a problem. I tried to execute smriprep over 600 subjects in parallel. Trying to push the branch containing successfully produced smriprep/freesurfer outputs the error again (see below). Although saving the datasets with datalad before execution was flawless. 

`
0: ++ flock /work/fatx405/tmp/pipeline.lock datalad push -d /scratch/fatx405.1449403/sub-0424f0cc/clone/data/freesurfer --to origin
0: [INFO] Determine push target 
0: [INFO] Push refspecs 
0: [INFO] Transfer data 
0: CommandError: 'git -c diff.ignoreSubmodules=none annex copy --batch -z --to origin --fast --json --json-error-messages --json-progress -c annex.dotfiles=true -c annex.retry=3' failed with exitcode 1 under /scratch/fatx405.1449403/sub-0424f0cc/clone/data/freesurfer
0: fatal: /work/fatx405/projects/CSI_POSTCOVID/data/freesurfer/.git/annex/index: index file smaller than expected
0: git-annex: fd:23: hPutBuf: resource vanished (Broken pipe)
0: ++ flock /work/fatx405/tmp/pipeline.lock datalad push -d /scratch/fatx405.1449403/sub-0424f0cc/clone/data/smriprep/sub-0424f0cc --to origin
0: [INFO] Determine push target 
0: [INFO] Push refspecs 
0: [INFO] Transfer data 
0: [INFO] Update availability information 
0: [INFO] Start enumerating objects 
0: [INFO] Start counting objects 
0: [INFO] Start compressing objects 
0: [INFO] Start writing objects 
0: [INFO] Start resolving deltas 
0: [INFO] Finished push of Dataset(/scratch/fatx405.1449403/sub-0424f0cc/clone/data/smriprep/sub-0424f0cc) 
0: ++ flock /work/fatx405/tmp/pipeline.lock datalad push -d /scratch/fatx405.1449403/sub-0424f0cc/clone/data/smriprep --to origin
0: [INFO] Determine push target 
0: [INFO] Push refspecs 
0: [INFO] Transfer data 
0: CommandError: 'git -c diff.ignoreSubmodules=none annex copy --batch -z --to origin --fast --json --json-error-messages --json-progress -c annex.dotfiles=true -c annex.retry=3' failed with exitcode 1 under /scratch/fatx405.1449403/sub-0424f0cc/clone/data/smriprep
0: fatal: /work/fatx405/projects/CSI_POSTCOVID/data/smriprep/.git/annex/index: index file smaller than expected
0: git-annex: fd:23: hPutBuf: resource vanished (Broken pipe)`
`

Not sure whether something corrupts the index file during computations.

Grateful for any help!

**Comment by m-petersen** [comment]
That is the script concerned I run after creating an ephemeral clone of the original dataset.

`
#!/bin/bash

# Get input and output dataset directory trees
datalad get -n -J $SLURM_CPUS_PER_TASK $CLONE_BIDS_DIR/$1
datalad get -n -J $SLURM_CPUS_PER_TASK $CLONE_DATA_DIR/freesurfer
datalad get -n -J $SLURM_CPUS_PER_TASK $CLONE_DATA_DIR/smriprep
datalad get -n -J $SLURM_CPUS_PER_TASK $CLONE_DATA_DIR/smriprep/$1

# Checkout unique branches (names derived from jobIDs) of result subdatasets
# to enable pushing the results without interference from other jobs.
# In a setup with no subdatasets, "-C <subds-name>" would be stripped,
# and a new branch would be checked out in the superdataset instead.
git -C $CLONE_DATA_DIR/freesurfer checkout -b "job-$SLURM_JOBID-freesurfer-$1"
#git -C $CLONE_DATA_DIR/freesurfer/$1 checkout -b "job-$SLURM_JOBID-freesurfer-$1"
git -C $CLONE_DATA_DIR/smriprep checkout -b "job-$SLURM_JOBID-smriprep-$1"
git -C $CLONE_DATA_DIR/smriprep/$1 checkout -b "job-$SLURM_JOBID-smriprep-$1"

# Remove job outputs in dataset clone to prevent issues when rerunning
# Freesurfer requires removal of output subject directory before processing, hence no subdataset structure only directories in data/freesurfer
(cd $CLONE_DATA_DIR/freesurfer && rm -rf fsaverage $1 .bidsignore)
(cd $CLONE_DATA_DIR/smriprep && rm -rf logs $1/* "${1}.html" dataset_description.json desc-aparcaseg_dseg.tsv desc-aseg_dseg.tsv .bidsignore)

CMD="
   singularity run --cleanenv --userns -B . -B $PROJ_DIR -B $SCRATCH_DIR/:/tmp \
   $ENV_DIR/smriprep-0.8.0rc2
    data/raw_bids data participant \
    -w .git/tmp/wdir \
    --participant-label $1 \
    --output-spaces fsnative fsaverage MNI152NLin6Asym T1w T2w \
    --nthreads $SLURM_CPUS_PER_TASK \
    --fs-subjects-dir data/freesurfer \
    --stop-on-first-crash \
    --fs-license-file envs/freesurfer_license.txt
"

datalad run \
   -m "$PIPE_ID" \
   --explicit \
   --output $CLONE_DATA_DIR/freesurfer -o $CLONE_DATA_DIR/smriprep -o $CLONE_DATA_DIR/smriprep/$1 \
   --input "$CLONE_BIDS_DIR/$1"\
    $CMD


#flock $DSLOCKFILE datalad push -d $CLONE_DATA_DIR/freesurfer/$1 --to origin
flock $DSLOCKFILE datalad push -d $CLONE_DATA_DIR/freesurfer --to origin
flock $DSLOCKFILE datalad push -d $CLONE_DATA_DIR/smriprep/$1 --to origin
flock $DSLOCKFILE datalad push -d $CLONE_DATA_DIR/smriprep --to origin
`

**Comment by bpoldrack** [comment]
While I haven't seen this particular error message before, looking at your last comment, @m-petersen, the issue seems to be the `ephemeral` clone and how it works. With that you symlink the clone's `.git/annex` to `origin`, resulting in the fact that `origin` already has the data after a `save` in in the clone (implicit `save` in your case via `run`) - only it doesn't know yet.

One solution could be to run `git annex fsck -f origin --fast` in order to have annex record the availability of the data from `origin` and only then run `datalad push` (which should find that there's no data only git history to push, so you could specify `--data nothing` to not even let push try).

Does that work for you? If so - I'd still leave that issue open, since `push` could be smart enough to detect that situation and be more informative/instructive.

**Comment by m-petersen** [comment]
Thanks a lot for your reply, @bpoldrack. 

>With that you symlink the clone's .git/annex to origin, resulting in the fact that origin already has the data after a save in in the clone (implicit save in your case via run) - only it doesn't know yet.

Ah, the fact that newly producing and saving the data in the clone's `freesurfer/` results in `origin's freesurfer/` having the outputs as well is new to me. Maybe this explains why getting `freesurfer/` with `datalad get -n` at the beginning of the script takes an increasing amount of time with every failed run. Does that also mean the outputs produced during jobs terminating with the error above aren't lost and somehow recoverable? 

> One solution could be to run git annex fsck -f origin --fast in order to have annex record the availability of the data from origin and only then run datalad push (which should find that there's no data only git history to push, so you could specify --data nothing to not even let push try).

Just to make sure I understand the fix: I run `git annex fsck -f origin --fast` from within `freesurfer/` before `datalad push --to origin --data nothing`?

**Comment by bpoldrack** [comment]
@m-petersen 
> Just to make sure I understand the fix: I run git annex fsck -f origin --fast from within freesurfer/ before datalad push --to origin --data nothing?

Yes, exactly. This should lead to annex realizing that the data is already in `origin`, recording that availability in the `git-annex`. Then the `push` will make sure that your git branch and the `git-annex` branch are pushed back to origin.

**Comment by bpoldrack** [comment]
@m-petersen 
> Does that also mean the outputs produced during jobs terminating with the error above aren't lost and somehow recoverable?

The data is "recoverable" in principle, yes. But in reality that depends. What is/was secured is the data objects identified by their content hash. Now two potential problems may or may not render those data objects unusable: 

1. You do need the git branch that would refer to those data objects, otherwise you don't know what file they belong to. It may well be, that the respective branch was pushed before the failure to push data. If you can recover the commit with the results from `origin`, you'll find your data as well.

Somewhat related is:
2. Depending on what/how you run your pipeline, a second run may not yield bit-identical files. That would then tie into the above problem: With a result branch from a later run you may not be able to reference the right data objects although in some sense the right ones are there.

So, ultimately depends on whether or not you can figure out the exact commit (by brach name, tag whatever) that was yielding your results, because that commit ties the hashes to files. Otherwise you'd have the data, but all you know about the objects would be their content hash and probably the filename extension. With the commit, you can the correct filenames and can use it.

**Comment by m-petersen** [comment]
Okay. Thanks again for your help

**Comment by bpoldrack** [comment]
@m-petersen 

One more thing re recovery: Say `origin` has your result branches, since `datalad push` only failed when trying to push the data (don't know from the top of my head). Because with earlier runs you didn't have the `fsck` integrated, `origin` still doesn't know it has the data for that branch. So, you could clone origin elswhere, `git fetch origin` to get all the branches, `git checkout YOUR-RESULT-BRANCH`, `git annex fsck -f origin --fast`. Then a `datalad get` / `git annex get` should hopefully get you the old data.

This may be a little more complicated in case `origin` isn't a regular dataset, but part of a RIA store. I haven't noticed you mentioning that, so assume it's a no. If that's actually a yes and you do want to recover, then just ping me. Same principle, but different commands required.

**Comment by m-petersen** [comment]
Indeed, `origin` is a regular dataset, but unfortunately there are no result branches in it.

**Comment by bpoldrack** [comment]
> but unfortunately there are no result branches in it.

In that case I need to check `push`. Your log read

> [INFO] Push refspecs 

before the failure. So, either there's some misleading messaging or something else is wrong with `push`.

**Comment by m-petersen** [comment]
I really appreciate your time and support, @bpoldrack. 

> So, from the POV of the superdataset, it's all remaining in its master branch (or whatever your default is). Meaning: You would see those branches only, if check git branch from within the subdatasets.

I checked within the subdataset `freesurfer/` and there were no results branches `job-$SLURM_JOBID-smriprep-$1`. As it took >8 hours to `datalad get -n freesurfer/` (because by now there was half a terabyte in the .git) and I have to get the results quickly I removed the subdataset, created a new on and started from scratch. Now, it is operable/gettable again. 

On a sidenote, before deleting the whole subdataset I executed `git annex dropunused` resulting in file deletion until `freesurfer/.git` contained only 24gb but still right after that `datalad get freesurfer/` wasn't finishing until I manually stopped the job (after 8 hours again). Was I missing something when cleaning .git up? I wasn't executing `git gc --aggressive` as recommended in the handbook (http://handbook.datalad.org/en/latest/beyond_basics/101-162-springcleaning.html) could that be the reason?

**Comment by m-petersen** [comment]
> I run git annex fsck -f origin --fast from within freesurfer/ before datalad push --to origin --data nothing?

A new round of computations is currently running.

Adding `pushd $CLONE_DATA_DIR/freesurfer; git annex fsck -f origin --fast; pop` before pushing solved the primary issue with result branches of finished jobs now being available in `freesurfer\` of `origin`

**Comment by mattcieslak** [comment]
We started off using the ENKI instructions too and switched over to [this](https://github.com/psychoinformatics-de/fairly-big-processing-workflow), which solved everything.

**Comment by m-petersen** [comment]
Hi Matt,
thanks for the recommendation. Can you elaborate on the problems it addressed in your case? Before I try to implement it I'd like to know the benefits which aren't too obvious to me after a first glimpse.

**Comment by mattcieslak** [comment]
It uses a separate ria store for the compute jobs to clone from. This prevents a lot of issues that arise when many jobs are trying to push to and clone from the same source

**Comment by m-petersen** [comment]
I see thanks.

**Comment by mih** [comment]
It seems that the discussion here has ended. My reading is that the situation has been clarified and this issues can be closed.
