### ISSUE TITLE
File hierarchy for defined subset

### ISSUE THREAD

**Issue by TheChymera** [datalad/datalad#588]
It wold be cool if one had the option to copy only the directory structure leading up to the branch for which one needs to install the data:

e.g from this structure, of which one only needs the subdirectory `files`:

sci-biology/
├── abacas
│   ├── abacas-1.3.1.ebuild
│   ├── Manifest
│   └── metadata.xml
├── act-bin
│   ├── act-bin-13.0.0.ebuild
│   ├── Manifest
│   └── metadata.xml
├── afni
│   ├── afni-0_pre20130927.ebuild
│   ├── afni-0_pre20141212.ebuild
│   ├── afni-9999.ebuild
│   ├── ChangeLog
│   ├── Manifest
│   └── metadata.xml
...
├── fsa
│   ├── fsa-1.15.7.ebuild
│   ├── Manifest
│   └── metadata.xml
├── fsl
│   ├── files
│   │   ├── 99fsl
│   │   ├── fsl-5.0.4-headers.patch
│   │   ├── fsl-5.0.4-setup.patch
│   │   ├── fsl-5.0.6-fsldir_redux.patch
│   │   ├── fsl-5.0.8-fsldir_redux.patch
│   │   ├── fsl-5.0.8-headers.patch
│   │   └── fsl-5.0.8-setup.patch
│   ├── fsl-5.0.8.ebuild
│   ├── Manifest
│   └── metadata.xml 
...

you would only get the following paths:

**sci-biology**/
├── abacas
│   ├── abacas-1.3.1.ebuild
│   ├── Manifest
│   └── metadata.xml
├── act-bin
│   ├── act-bin-13.0.0.ebuild
│   ├── Manifest
│   └── metadata.xml
├── afni
│   ├── afni-0_pre20130927.ebuild
│   ├── afni-0_pre20141212.ebuild
│   ├── afni-9999.ebuild
│   ├── ChangeLog
│   ├── Manifest
│   └── metadata.xml
...
├── fsa
│   ├── fsa-1.15.7.ebuild
│   ├── Manifest
│   └── metadata.xml
├── **fsl**
│   ├── **files**
│   │   ├── 99fsl
│   │   ├── fsl-5.0.4-headers.patch
│   │   ├── fsl-5.0.4-setup.patch
│   │   ├── fsl-5.0.6-fsldir_redux.patch
│   │   ├── fsl-5.0.8-fsldir_redux.patch
│   │   ├── fsl-5.0.8-headers.patch
│   │   └── fsl-5.0.8-setup.patch
│   ├── fsl-5.0.8.ebuild
│   ├── Manifest
│   └── metadata.xml 
...

this can already be done wth two commands:

`datalad install http://myhost/sci-biology ; datalad install sci-biology/fsl/files`

But this seems a common enough use case, to warrant an own command :-/ for me in fact it would be the main use case.
It is important I think to keep the directory structure when installing a submodue so that people can rely on the same path structures.

**Comment by hanke** [comment]
I think I have the same desire, but let me ask a question to get a better sense of what you want.

Do you want to be able to save the state of "data availability" (ie. fulfilled file handles at some point in time), and be able to re call that? Or do you rather want to trim the dataset content to a particular subset of file/directories such that only those are visible on the filesystem?

**Comment by yarikoptic** [comment]
I don't think it was going that deep ;-)  just literally that two separate commands usecase

**Comment by TheChymera** [comment]
@hanke among the two, I would be more concerned about trimmimg the dataset content to a particular subset of file/directories such that only those are visible on the filesystem.

I think this is important for distribution. While I might want to have symlinks à la git-annex for files I do not actually have on one particular repo - for anybody trying to get my data for reproduction purposesthat, would just be plain confusing.

**Comment by bpoldrack** [comment]
So, if I got it right, what you want is basically a more fine grained `recursive` option for install?
`datalad install http://myhost/sci-biology --recursive` would install `sci-biology` as well as all its subdatasets , whereas you want to specify a (list of) certain subdataset(s), right?

**Comment by yarikoptic** [comment]
not exactly @bpoldrack  -- it was litterally what you would get if you run two commands
```
datalad install http://myhost/sci-biology ; datalad install sci-biology/fsl/files
```
i.e. it would install top super-dataset, and then the subdataset(s) all the way to fsl/files

**Comment by yarikoptic** [comment]
Since we have not come to this for years, and there is a 2-command workaround, I think it is good enough... the solution would be to add some sugaring annotation to the URLs  to define the boundary from which to start installing super-datasets etc... not sure if worth complication, but some interested soul might come back to it later if manages to search this up (open or closed - does not really matter with current number of open issues ;))  But I minted a new issue label now ;)
