### ISSUE TITLE
DataLadRIs

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#589]
A follow up to #582 and dump of ideas echoing our discussion during my visit to MD.  I think we can support following format `/[locality]/[remote]/[path]`
- `[locality]` is to signal 
  - `~` -- that it is a local user-wide centralized installation which we need to work with (e.g. `~/.datalad` or some other...)
  - empty value -- remote locations registered within a given dataset we are in.  I.e. without `locality`=`~` prefix, and empty `remote`, we are referring to our canonical remote location http://datasets.datalad.org.

By default we could also make `/~//` behave as `/~/origin/` where origin would point again to our canonical super-dataset as a remote (note that `/~//` by itself is not a clone of it, just gets populated with the datasets from it)
- `[remote]` would point to a possibly registered as a git remote some other (super)dataset.

So `datalad install /~//openfmri/ds000001` would result in "installation" of ~/.datalad/openfmri/ds000001.  In turn `datalad install ///openfmri/ds000001` would install `ds000001` under a local directory.

We should then allow to register additional 'remotes' for any of those -- some local (super-)dataset or the centralized one (`/~/`), e.g. 
`datalad register-dataset /~/studyforrest http://psydata.ovgu.de/studyforrest/` and then be able to  `datalad install /~/studyforrest/phase1` or just `datalad install -r /~/studyforrest`.  Similarly it would work for non-~ local deployments: `datalad register-dataset studyforrest http://psydata.ovgu.de/studyforrest` while being inside a dataset (or respect `-d ds` otherwise).

Then we could provide support of those in `datalad ls` so I could e.g. do  `datalad ls //` to list all known remote datasets registered in the local ds.  `datalad ls //studyforrest` to list sub-datasets within studyforrest remote dataset.  Similar for all those `/~/` just within the centralized.

smth like that... I think it should scale, and it doesn't conflict (as far as I see) with shell handling of `~`  so we should be safe to use all those examples I have given

**Comment by yarikoptic** [comment]
and should be able to do something like `datalad install --source /~//openfmri/ds000001` which would install from already installed in central location or `datalad install --source /~/openfmri/ds000001` which would install from url known to openfmri remote dataset registered within centralized user super dataset

**Comment by yarikoptic** [comment]
to make it clear -- there indeed theoretically be `/~` directory which would "ruin" my logic and conflict with "paths" BUT it is VERY unlikely and even if happens, probably just by mistake of the admin ;)  and even though duplicate `//` constitute a legal path pointing to '/', I think it should be ok to "overload" it.  I would prefer such non-standard and theoretically conflicting paths, to some "proper" uris suchas `datalad://[remote] `

**Comment by mih** [comment]
Do we need to keep this open?

**Comment by yarikoptic** [comment]
I think so -- support for those (with `locality`) isn't yet implemented and not even discussed really

**Comment by mih** [comment]
Still keeping this open!

**Comment by mih** [comment]
My annual ping if this still needs to be kept open after three years and no apparent interest in the topic?

**Comment by yarikoptic** [comment]
yeah, let's close it -- we know where to find it if interest comes back
