### ISSUE TITLE
Documentation for special remote types datalad and datalad-archives

### ISSUE THREAD

**Issue by matrss** [datalad/datalad#5891]
#### What is the problem?

Not a traditional issue. I was researching the different types of special remotes that are available and stumbled over `externaltype=datalad` and `externaltype=datalad-archives`. Together with `ora` those seem to be the ones explicitly implemented for datalad. Unfortunately, I could not find much information on the first two and am still not sure what they do, how they work and how all three relate to each other.

I primarily found `externaltype=datalad{-archives}` used for datasets hosted on http://datasets.datalad.org/ but from my understanding it is not specific for that location. I am not sure in which cases these special remote types might be relevant and used.

I guess this issue could be considered as a request for more documentation for those special remote types.

Thanks in advance! I am sorry if I overlooked an obvious part of documentation.

**Comment by yarikoptic** [comment]
indeed documentation on those seems to be scarce to say the least, or hard to find. e.g. for archives one from --help:

```
(git-annex)lena:~/proj/dandi/dandisets[rf-dates]tools
$> git-annex-remote-datalad-archives --help-np | grep archives
Usage: git-annex-remote-datalad-archives [-h] [-l LEVEL] [--version] [--dbg]
git-annex-remote-datalad-archive is a git-annex custom special remote to extract content from archives (.tar{,.gz}, .zip, etc) which are in turn managed by git-annex.  See `datalad add-archive-content` command

$> datalad add-archive-content --help-np | head -n 30         
Usage: datalad add-archive-content [-h] [--annex ANNEX]
...
Add content of an archive under git annex control.

This results in the files within archive (which must be already under annex
control itself) added under annex referencing original archive via
custom special remotes mechanism

Example:

    annex-repo$ datalad add-archive-content my_big_tarball.tar.gz

```

 I guess we should extend notebook, filed https://github.com/datalad-handbook/book/issues/748 

meanwhile let me provide brief explanation here:  Those were created to fulfill very old original use cases needed for DataLad -- 

- `git-annex-remote-datalad` -- access data available from websites with (often some ad-hoc) authentication or just through protocols not directly supported by git-annex (e.g. `s3://` urls)
- `git-annex-remote-datalad-archives` -- to be able to transparently to the user obtain individual files whenever originally provided only in zip/tarballs on remote portals (e.g. how it was for openfmri, and remains for many others like CRCNS)

Both of those are "transparently" enabled by e.g. `download-url`, `add-archive-content` , datalad-crawler extension pipelines where needed, and indeed we (or - contributions are always welcome!) should document better when/how people should enable them manually.

**Comment by matrss** [comment]
Alright, thanks a lot!

So essentially, the `datalad` special remote was created to address authentication and the shortcomings of the git annex `web` special remote and `datalad-archives` transparently reads archives. I assume in that case both are meant as "read-only remotes", right?

**Comment by yarikoptic** [comment]
> and `datalad-archives` transparently reads archives.

I wouldn't praise it that high, just "transparently downloads entire archive to extract a dedicated file(s)" since the issue of "transparent reading" of some kind is still in the air ;)

> I assume in that case both are meant as "read-only remotes", right?

ATM 100% correct!

**Comment by mih** [comment]
@matrss Please check out my attempt of an explanation at #6181
