### ISSUE TITLE
Is it possible to use an already-in-use s3 bucket as a remote?

### ISSUE THREAD

**Issue by mattcieslak** [datalad/datalad#5900]
Hi!

We are hoping to follow the instructions [here](https://handbook.datalad.org/en/latest/basics/101-139-s3.html) to create a sibling of a dataset on s3. Unfortunately, we don't own the bucket that we need to upload the data to: we only have write access to a subdirectory of someone else's bucket.

Is it possible to use a subdirectory of a bucket as a git annex remote? Suppose I've only been granted permission to write to the `s3://someone-elses-bucket/data/Projects/HBN/DATALAD_BIDS` address.

**Comment by yarikoptic** [comment]
Yes, add `fileprefix=data/Projects/HBN/DATALAD_BIDS` to your initremote invocation . More options etc at https://git-annex.branchable.com/special_remotes/S3/
