### ISSUE TITLE
AnnexRepo.copy_to() cannot accept options

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5903]
If given `options` must be a list, due to this handling:

```
options = options[:] if options else []
```

however, if it is a list, it will crash due to this follow-up handling:

```
annex_options.extend(split_cmdline(options))
```

This is a minor issue, because this method is only used in tests, and was deprecatsed in Apr 2021 already. Waiting for removal is likely the best option.

**Comment by adswa** [comment]
> This is a minor issue, because this method is only used in tests, and was deprecatsed in Apr 2021 already. Waiting for removal is likely the best option.

@mih, with this being deprecated in the ``0.14`` series, can this function be removed in ``0.16``?  The commit 62c01cce1ba7fb12f8c576c0a51fdab091a4beba that deprecated this function says in the commit message that it can be removed together with ``publish``, which has been moved to ``datalad-deprecated`` with ``0.15``

**Comment by mih** [comment]
Yes! Thx for spotting that!

**Comment by adswa** [comment]
In ripping it out and adjusting the tests that use it, I think I found a missing piece in ``push``. Some tests rely on ``copy_to`` to only transfer annexed contents to a remote. I couldn't find a parametrization for ``push`` that would allow for this (i.e., only transfer data and not push Git branches). Maybe ``push`` needs a ``--data only`` mode or a ``--what`` parameter similar to the new ``drop``?

**Comment by mih** [comment]
I agree with the assessment of @adswa . Given that https://github.com/datalad/datalad/issues/6417 exists as a dedicated issue, and there rest is documented (but simply not acted on), I think we can close this.
