### ISSUE TITLE
Discontinue double-reporting of error results

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5910]
Demo:

```
% datalad create-sibling-gitlab --site gitlab.com 
[ERROR  ] No project path specified, and no configuration to derive one [create_sibling_gitlab(/tmp/some)] 
create_sibling_gitlab(error): . (dataset) [No project path specified, and no configuration to derive one]
```

The reasons for this have been described in https://github.com/datalad/datalad/issues/3752.

https://github.com/datalad/datalad/pull/3754 was introduced to provide means for preventing it.

I have used `datalad.log.result-level=debug` since that time (Oct 2019), I have not had a single case, where I missed that duplicate log message.

I think it is time to stop issuing log messages from results.

**Comment by bpoldrack** [comment]
It may be worth making it conditional on whether or not the log target is a file, since a log file wouldn't have any indication of an error otherwise. But apart from that aspect, absolutely agree.

**Comment by mih** [comment]
I should have been more precise: I want to change the log level from "match the result status" to `datalad.log.result-level` and make `datalad.log.result-level=debug` by default. If anyone configures the log target to be a file, they can also change that default to `datalad.log.result-level=None`.
