### ISSUE TITLE
Inaccessible action choices for `siblings`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5912]
Besides #5147 making `siblings` awkward to use, it is also too hard to see the list of supported `ACTION`s.

```
% datalad siblings -h
Usage: datalad siblings [-h] [-d DATASET] [-s NAME] [--url [URL]] [--pushurl PUSHURL] [-D DESCRIPTION] [--fetch]
                        [--as-common-datasrc NAME] [--publish-depends SIBLINGNAME] [--publish-by-default REFSPEC]
                        [--annex-wanted EXPR] [--annex-required EXPR] [--annex-group EXPR] [--annex-groupwanted EXPR]
                        [--inherit] [--no-annex-info] [-r] [-R LEVELS] [--version]
                        [ACTION]
```

it is necessary to parse the long help. It should be possible to list them in the synopsis. If necessary even "by hand".

**Comment by mih** [comment]
Erm, so what prevents the simple automatic listing of choices is just the `| Ensure(None)`

```
constraints=EnsureChoice('query', 'add', 'remove', 'configure', 'enable') | EnsureNone()),
```

**Comment by mih** [comment]
Grrr, turns even further out that `None` is not actually a supported argument :roll_eyes: 

```
In [1]: import datalad.api as dl
In [2]: dl.siblings(action=None)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
...
```

**Comment by yarikoptic** [comment]
FWIW #5913 did the right thing and have improved the `--help` but it seems that `None` given as an argument is still causing a non-informative crash

```
(git-annex)lena:~/datalad/crcns/aa-1[master]git
$> python -c 'from datalad.api import siblings; siblings(action=None)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-maint/datalad/interface/utils.py", line 481, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/interface/utils.py", line 474, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/interface/utils.py", line 393, in generator_func
    for r in _process_results(
  File "/home/yoh/proj/datalad/datalad-maint/datalad/interface/utils.py", line 556, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-maint/datalad/distribution/siblings.py", line 239, in __call__
    worker = action_worker_map[action]
KeyError: None

$> datalad --version
datalad 0.14.7+27.gd2b8026ba

$> git -C ~/proj/datalad/datalad show d2b8026ba   
commit d2b8026ba7ae2d96c2e4aba53e09d07d8f127850 (origin/maint, maint)
Merge: c6e0e4df6 95ac8ad94
Author: Benjamin Poldrack <bpoldrack@users.noreply.github.com>
Date:   Wed Aug 18 16:00:37 2021 +0200

    Merge pull request #5913 from mih/bf-5912
    
    Fix argument-spec for `siblings` and improve usage synopsis
```

I guess  we don't do any checking for the `Arguments` in Python API and for UX need to "manually" do such checks in the code and raise ValueError (which IIRC we do in some spots)

**Comment by mih** [comment]
Sadly, there is no comprehensive checking. I would prefer not to make a dedicated issue out of this particular behavior (we would need to have thousands). I spent the day on `siblings()` and I am still torn whether just replacing it (rather than fixing) would be the better approach...

**Comment by yarikoptic** [comment]
> I spent the day on `siblings()` and I am still torn whether just replacing it (rather than fixing) would be the better approach...

FWIW, in my really "baby step" first approach toward allowing for subcommand interfaces (#4539), `siblings` was the candidate I used -- https://github.com/yarikoptic/datalad/commit/14607f54e84aedc32edd1112ae8f7937163780a7
