### ISSUE TITLE
`create-sibling-github --existing skip` configures a sibling

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5941]
Not sure how I feel about this behavior. I have a dataset that I want to create a github sibling for. I (accidentally) chose a repo name that conflicts with an already existing repo on github. So this behavior is good:

```
% datalad create-sibling-github funkydummy3
create_sibling_github(error): . (dataset) [repository "funkydummy3" already exists on Github]
```

but this one, I cannot easily get behind:

```
% datalad create-sibling-github funkydummy3 --existing skip
configure-sibling(ok): . (sibling)
action summary:
  configure-sibling (ok: 1)
  create_sibling_github (notneeded: 1)
```

I does skip the creation of the repo (to avoid the conflict), but it also proceeds to configure the (totally unrelated repo, in my case) as a sibling.

I would have expected the `existing='skip'` to mean "if there already is a sibling configured, skip", not "if there already is a repo, skip creation, but configure a sibling".

I think I would expect such a behavior with `existing='reconfigure'`, but not with `skip`.

**Comment by bpoldrack** [comment]
> I think I would expect such a behavior with existing='reconfigure', but not with skip.

I agree. Same is likely true for `create-sibling`. I guess the intention was to apply `reconfigure` only when there's an already configured sibling with that name.
