### ISSUE TITLE
Prepare a binder demo

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5953]
https://mybinder.readthedocs.io/en/latest/examples/sample_repos.html#data-and-reproducibility

a whole category of examples, with no DataLad to be found.

@jsheunis could we use your work for that?

**Comment by jsheunis** [comment]
Good idea 👍

**Comment by mih** [comment]
Once done, we should put a binder launcher button on the datalad.org frontpage, and an APNG to demo-click on the terminal "notebook" starter and show a functional datalad installation.

**Comment by jsheunis** [comment]
Do you have a specific level in mind for the content to be covered in such a demo? As in "walk through installation", or "basics of DataLad" (e.g. clone, save, get, drop, etc), longer walk-through tutorial (such as the [OHBM workshop](https://github.com/mih/datalad-tutorial-binder)) or just a general overview using a specific dataset (e.g. [StudyForrest](https://github.com/psychoinformatics-de/studyforrest-data-binder))? Or should it be something that relates more directly to the specific section of the binder docs, i.e. "Data and Reproducibility"?

**Comment by mih** [comment]
I was thinking to do none of that, actually. Sorry for having be too vague. Here is what I have in mind:

- prepare a minimal, but "comprehensive" setup to use datalad, but with no materials preloaded (no data, no notebooks, nothing), and no dependencies for functionality that makes no sense running on binder.
- following https://discourse.jupyter.org/t/tip-speed-up-binder-launches-by-pulling-github-content-in-a-binder-link-with-nbgitpuller/922 this should be an environment that could be flexibly used from other contexts (e.g. a workshop notebook repository, the handbook). Reusing the same env will be maximally efficient, but also maximally available, because its usage ideally remains too frequent for the image to be culled
- this minimal binder will have no notebooks (see above why it is better to separate binder env from content), instead it is meant to be used via the built-in terminal (only)
```

**Comment by jsheunis** [comment]
Here it is: https://github.com/jsheunis/datalad-binder

I'll send a transfer request to transfer it to the `datalad` organisation (I don't have permissions to create new repos there), and then I'll update the links afterwards (currently pointing to my personal github account).

**Comment by jsheunis** [comment]
Oh lol I need permission on the destination organisation in order to "request" a transfer. @mih I'll give you admin access to the repo, can you transfer it to wherever you think is best?

**Comment by mih** [comment]
Sure. But I do not seem to have access yet

**Comment by jsheunis** [comment]
I sent you an invite.

**Comment by mih** [comment]
Maybe not enough power? I still don't see the settings.

**Comment by jsheunis** [comment]
Ugh, looks like I can't grant you access to that level on a user account repository. I've transferred it to the datalad-handbook organization: https://github.com/datalad-handbook/datalad-binder

**Comment by mih** [comment]
I completed the roundtrip ;-)

**Comment by mih** [comment]
This is done, the demo is here: https://github.com/datalad/datalad-binder

It will also be on the new website. Closing.
