### ISSUE TITLE
Announce deprecation of `datalad.version` in 0.15

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5957]
TODO recorded by @yarikoptic 
 in https://github.com/datalad/datalad/commit/7bbccef6a7d9ddab402ab505dba2deed5d11e1f8

**Comment by yarikoptic** [comment]
eh, should have thought more about that comment as for "0.15.0". since added in 0.14.x, not 0.14.0  - we should  add a deprecation warning within that `.version` within 0.15.0,  and thus AIM to remove in 0.16.0. Will submit a PR

**Comment by yarikoptic** [comment]
oh - comment was actually correct, adjusted issue title

> TODO: announce in 0.15 to be deprecated for 0.16
