### ISSUE TITLE
new (?) blow on lustre FS

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#596]
would be useful to verify that current datalad works on it with recent annex, which had locking for such FS refined already

**Comment by yarikoptic** [comment]
verified -- drop/fsck blow: http://git-annex.branchable.com/bugs/drop_blows_on_lustre__58___SQLite3_returned_ErrorIO/

**Comment by mih** [comment]
Still an issue? Surely no longer "new".

**Comment by yarikoptic** [comment]
Have no means to check ATM, but issue against annex seems to be still open, added a label though

**Comment by mih** [comment]
Pretty much everything has changed in the past four years. I don't think it is useful to have an issue that tracks an issue of a problem that nobody can or does work on. Documenting that this has ever happened is perfectly done in a closed issue too.
