### ISSUE TITLE
Publish doesn't do much

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#597]
I created a remote repo on a server with `git init` and added it as a remote with `add-sibling`. When I `datalad publish` a dataset to that sibling, it pushed the git-annex branch, but nothing else. If I add `.` as a positional arg, it pushed the annex content, but still not the master branch.

**Comment by bpoldrack** [comment]
At a first try I thought you were right. But I made a mistake myself. So:
Did you do `git config receive.denyCurrentBranch updateInstead` on the remote repo? Or checkout something else than master? Or is it bare?

**Comment by bpoldrack** [comment]
Of course if not so, this would still mean to care for a proper message to be printed out ...

**Comment by hanke** [comment]
Yes, this was a publish to a system running Debian stable, with a rather old Git installation that doesnt support denyUpdateInstead.

**Comment by bpoldrack** [comment]
Ok. So if I got it right, it was a repo with checked out `master branch, which we simply cannot push to. Therefore not a bug, but just a matter of UI. Right?

**Comment by hanke** [comment]
Yes, I agree.
