### ISSUE TITLE
Release workflow failed

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5972]
https://github.com/datalad/datalad/runs/3568118676?check_suite_focus=true

error     Received E2BIG from execSync.

I guess we could now just cut paste that changelog and retry to release with that PR, right @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic If you mean manually adding the changelog to `CHANGELOG.md` and rerunning the release workflow, expecting the `--no-changelog` provision to reduce the exec plugin payload size, that won't work, as the exec plugin will still be passing a giant JSON object full of PR info through the environment.

The root problem is that auto's exec plugin (used by datalad for updating the rST changelog and releasing to PyPI) is too poorly designed to handle releases with too much PR data.  While the long-term solution would be to ~harass~ engage with the auto developers until they redesign the plugin (or, at the very least, get back to me on [this issue](https://github.com/intuit/auto/issues/2019) regarding a supposed alternative to exec), continuing to use auto for now would require rewriting the release workflow in manner akin to the reverse of [this dandi-cli commit](https://github.com/dandi/dandi-cli/commit/76f4ab40ceeb98326645ca27f05ac5916d8f5de0#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34).  However, getting the rST changelog command to run at the appropriate point is not something I am entirely certain how to do.

**Comment by yarikoptic** [comment]
half-ass workaround which might (?) work to allow for the workaround of manual copy/pasting: 
- if we are to provide `opts=--no-changelog`:
  - `sed -i -e '/afterChangelog/d' .autorc && make update-changelog && git add docs/source/changelog.rst && git commit -m '[skip ci] Update RST changelog'`
  before calling `auto`
- if we are not to provide opts, make sure that that afterChangelog line is possibly re-populated and committed before running the `auto`

**Comment by mih** [comment]
I am not following this closely, but I got the impression that changelog generation (prevention) is no longer an issue. Can we close this @jwodder @yarikoptic ?

**Comment by yarikoptic** [comment]
E2BIG remains the issue, but nothing we can really do about ATM without redoing the entire release process without `auto`.  As such, "release often" would avoid this issue. And let's let this issue RiP.
