### ISSUE TITLE
HTTPDownloader not yet working with redirected http-auth

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#5995]
While working on providing http-auth testing via enhanced docker image from https://github.com/datalad-tester/docker-ssh-target, I looked into `download_url` in order to combine the test setup with an actually meaningful test (and possibly necessary first fix).

The setup in the docker I have reflects the setup for RIA stores we use at INM-7: HTTP is redirected to HTTPS. Against that setup `download_url` works fine if pointed to the HTTPS address. It fails with the redirected HTTP address, though. That made me stumble upon several questionable aspects:

The downloader actually sends two requests to the same URL: A POST request to establish authentication and a subsequent GET request to actually download. Since with simple default apache serving files the response to the POST request already contains the content of the file, the GET request seems superfluous (or the other way around depending on how you look at it).

- Leading to the first question in this regard: Under what circumstances is a dedicated authentication request actually needed? We use `requests.Session` object and it seems to me, that the authenticator should be assigned to the `Session` (instead of being passed to the request call) and we can simply go for an authenticated GET. Why is there a POST to begin with? Was that written with some kind of webservice in mind, that would actually require that? May be in context of the crawler? @yarikoptic any recollection? It doesn't seem to make sense to me, since this is happening within the http downloader processing a single URL.

- That the redirected download fails is due to the fact, that we auto-follow a redirect for the initial POST request (which in this case is all we need and that succeeds), but we do not do that for the subsequent GET (which then therefore is what fails). `requests` does strip the credentials from redirected request, since it's considered a security hazard to auto-send credentials to a redirect. Now, this raises two questions: Should we really do that automatically for the POST (as we do right now)? If so, why not do it with the GET then? It's the exact same URL. If we trust the one request we can trust the other one, I think. If we shouldn't do it at all, then what could be our strategy to deal with such server setups? Asking for confirmation on every redirect? Would users even know whether or not that's fine? What could a config look like, that allows to authenticate against the redirected URL? Just the target URL that is whitelisted for being the target of such a redirect? Or does it make a difference where we are redirected from? (I don't think so).

- Finally, when we follow the redirect for the initial POST, what we send to the new target suddenly becomes a GET. Why is that? It makes it even more weird to send this as mere authentication establishing request, only to now have the intended download request to be *completely* identical (with POST/GET being the only difference to begin with - that's now gone, too).

It seems to me, what we should do is:
    - rip out the authentication request, just have an authenticated GET. If the `Session` object persists, we'd still have the same effect for subsequent downloads from the same host
    - make following redirects conditional on config/user interaction if authentication is required (to be decided: What does the config look like?)

**Comment by mih** [comment]
We may also want to consider a redirect that is essentially `http://specificurl` to `https://specificurl` to be treated differently from random-http-url to random-other-but-also-https-url. However, I am not sure what a "standard behavior" would be.

**Comment by bpoldrack** [comment]
Yes, that's certainly an option. Another one, that would also cover that kind of redirect is to not necessarily associate credentials with the URL that was originally given, but the one that actually requires authentication. We don't really need to send credentials to the HTTP address to begin with. Then, by storing credentials associated with the redirect target, the user would implicitly "allow" that. Seems a little cleaner to me, but may be a heavier surgery to the code base than one would wish for.

**Comment by yarikoptic** [comment]
> * Rip out the dedicated authentication request and see what may break

ping me whenever -- there is a number of tests which conditionally (if credential available) test against some portals for which all this mess was initially created.  As recently discussed while troubleshooting NASA Earthdata (https://github.com/datalad/datalad/issues/5846) -- all that "POST sending" is indeed not quite proper, and probably should not be done at all.  Instead of "ripping out" it might be worth just looking into creating a more "proper" authenticator which would follow all the "standard"/desired logic.  I have distilled some information into https://github.com/datalad/datalad/issues/5878 for that .
And if that other one shown to work reliably and may be against those which needed that odd POST, we could even replace then.  Not yet sure if it might or not require some change in the "downloader"s logic to support possible needed following of redirects and reauth.

**Comment by mih** [comment]
What is the status here @bpoldrack?

**Comment by bpoldrack** [comment]
I am re.thinking the entire approach. Having looked at that part of the code base more closely, the structure of how providers, downloaders and authenticators are being used strikes me as wrong altogether. Which makes everything related to redirects a mess. That's mostly because providers are treated as the toplevel thing from within which everything else is determined. However, a provider is created from the respective config  based on matching a URL that was given. Meaning, that the entire context (credentials and whether we need/have any, type of authentication and downloaders) is determined before we even had a chance to discover a redirect (or the actual need to authenticate anything).

I am looking into how to restructure or possibly just introduce helpers that use existing code in a "different order" as a first step that allows a bunch of fixes for issues like this one.

**Comment by yarikoptic** [comment]
@bpoldrack  yeah, downloaders setup/logic has lots of "history" to it, and design was largely driven to fulfill our immediate use cases  for portals which do not quite follow standard procedures for authentication (e.g. CRCNS).
You desire of the "the way around" seems to go along with what I outlined (and referenced above) in https://github.com/datalad/datalad/issues/5878 .  Have you had a look at it?  May be we could actually accomplish the mission without major RF, although I would not mind that one either if code/design would become more straightforward.

**Comment by bpoldrack** [comment]
@yarikoptic I'm aware of that issue, yes. Going through the code taking notes currently to get this ironed out.

**Comment by mih** [comment]
https://github.com/datalad/datalad-next/pull/124 has an implementation that supports this. Unless someone aims to make a second implementation here, I'd say this can be closed with this pointer.

**Comment by bpoldrack** [comment]
> Unless someone aims to make a second implementation here, I'd say this can be closed with this pointer.

I agree. Don't think I'll ever make another attempt w/o at the very least starting with this very pointer (more likely just taking it from next)
