### ISSUE TITLE
Datalad publish to gin.g-node.org fails repeatedly

### ISSUE THREAD

**Issue by ozika** [datalad/datalad#6001]
#### What is the problem?
- I am uploading a large (~630 GB) data set on `gin.g-node.org` and while about 90% of files gets uploaded, the rest fails
- The command I run: `datalad publish -f --to gin --transfer-data all` 
- I re-run the same command but the same files keep failing. 
- Strangely, when trying to re-upload I noticed that for all of them the upload reaches 100% and keeps going. One clue is that it eventually reaches the size of twice the amount of the original file before marking it as failed. I initially thought it's something to do with internet stability or permissions, but I think I have eliminated those two now. I made [**a video**](https://drive.google.com/file/d/1jENvUH44E_QgSuSv1R0QP5VedDUusEt-/view?usp=sharing) showing this behaviour. The full size of the file is reached at ~3:15 (when upload size is 1.37 GB in this case) and the eventual fail occurs at cca ~7:05 (when the upload size is 2.74 GB, exactly double). 

#### What steps will reproduce the problem?
Tbh not sure, just uploading large files to gin from ubuntu, maybe?  I tried uploading to an alternative gin server (internal) and I made sure the internet connection is fast and stable. 

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

In short `0.12.6`, `ubuntu 18.04.`. 
In long below line: 
--- 
# WTF
## datalad 
  - full_version: 0.12.6
  - version: 0.12.6
## dataset 
  - id: 63a423d0-1894-11ec-8975-4889e7d51f56
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /data/pl1_data
  - repo: AnnexRepo
## dependencies 
  - appdirs: 1.4.3
  - boto: 2.44.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20210223-1~ndall+1
  - cmd:bundled-git: 2.24.0
  - cmd:git: 2.24.0
  - cmd:system-git: 2.24.0
  - cmd:system-ssh: 7.6p1
  - exifread: 2.1.2
  - git: 3.0.5
  - gitdb: 2.0.6
  - humanize: 0.5.1
  - iso8601: 0.1.11
  - keyring: 10.6.0
  - keyrings.alt: 3.0
  - msgpack: 0.5.6
  - mutagen: 1.38
  - requests: 2.18.4
  - tqdm: 4.19.5
  - wrapt: 1.9.0
## environment 
  - GIT_PYTHON_GIT_EXECUTABLE: /usr/lib/git-annex.linux/git
  - LANG: en_US.UTF-8
  - LC_ADDRESS: en_GB.UTF-8
  - LC_IDENTIFICATION: en_GB.UTF-8
  - LC_MEASUREMENT: en_GB.UTF-8
  - LC_MONETARY: en_GB.UTF-8
  - LC_NAME: en_GB.UTF-8
  - LC_NUMERIC: en_GB.UTF-8
  - LC_PAPER: en_GB.UTF-8
  - LC_TELEPHONE: en_GB.UTF-8
  - LC_TIME: en_GB.UTF-8
  - PATH: /home/ondrej/.conda/envs/python3.7/bin:/home/ondrej/anaconda3/condabin:/usr/lib/fsl/5.0:/home/ondrej/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 8
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20210223-1~ndall+1
## location 
  - path: /data/pl1_data
  - type: dataset
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp: 
    - load_error: None
    - module: datalad.metadata.extractors.xmp
    - version: None
## python 
  - implementation: CPython
  - version: 3.6.9
## system 
  - distribution: Ubuntu/18.04/bionic
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 270
  - name: Linux
  - release: 5.4.0-81-generic
  - type: posix
  - version: #91~18.04.1-Ubuntu SMP Fri Jul 23 13:36:29 UTC 2021

**Comment by mih** [comment]
Thanks for your report. Can I ask you to try this again with a recent datalad version (current is 0.15.0). The reason is that we have fully replaced the `publish` command with a new `push` command, because the former caused too many problems.

Thanks! I do let me know if you have issues with the upgrade.

**Comment by ozika** [comment]
Thanks @mih ! 

I have done that and it seems that the issue has disappeared - I will try to re-upload the missing parts and update here if all worked. 

Did I get it right that the `push` equivalent command to the above (`datalad publish -f --to gin --transfer-data all`) is 
`datalad push -f all --to gin`

**Comment by mih** [comment]
Yes, that is correct. In most cases there should be no need to force anything anymore. A `datalad push --to gin` should generally do the right thing (TM) ;-)

I am closing this issue now, given that `publish` is not longer part of the latest release. Thx again!
