### ISSUE TITLE
Collision with content in parent dataset when trying to create subdataset

### ISSUE THREAD

**Issue by tjhendrickson** [datalad/datalad#6021]
#### What is the problem?
I have a very large datalad dataset (10,000 subjects in BIDS format). Currently each subject folder (sub-*) is a separate subdataset, but I would like to take this one step further. I would like to create additional subdatasets underneath each subject subdataset corresponding to the session folder (ses-*). Once I try this, however, I get the error `[ERROR  ] collision with content in parent dataset`. What I would ultimately like to do is to retain the subject subdataset, but additionally create a session subdataset based on the subject superdataset. 
#### What steps will reproduce the problem?
mkdir -p superdataset/subdataset
echo hello world >> superdataset/subdataset/hello_world.txt
datalad create --force -d superdataset 
datalad save superdataset
cd superdataset/
datalad create --force -d subdataset
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
version: 0.14.6+60.g3cddd7c4a
OS: centos/7/Core
#### Is there anything else that would be useful to know in this context?
Maybe this is a simple thing to do, I just could not find anything within the datalad handbook nor within the github issues. I'm not sure if this changes anything, but all of the subject folders are backed up to S3 using `git annex initremote`.

**Comment by yarikoptic** [comment]
> datalad create --force -d superdataset
> datalad save superdataset

at this point you saved your `subdataset/hello_world.txt` into the `superdataset` hence any operation like you tried below:

```
cd superdataset/
datalad create --force -d subdataset
```
would inform you that you already have that path known to belong to `superdataset`.  

<details>
<summary>with a slight tune up of delaying save and creating subdataset belonging to superdataset</summary> 

```shell
mkdir -p superdataset/subdataset
echo hello world >> superdataset/subdataset/hello_world.txt
datalad create --force -d superdataset
cd superdataset/
datalad create --force -d . subdataset
datalad save -r .
```
</details>

<details>
<summary>your would have it working</summary> 

```shell
$> bash /home/yoh/proj/datalad/trash/superdatasetsave.sh
[INFO   ] Creating a new annex repo at /tmp/superdataset 
create(ok): . (dataset)
[INFO   ] Creating a new annex repo at /tmp/superdataset/subdataset 
add(ok): subdataset (file)                                                                                                                                                                                           
add(ok): .gitmodules (file)                                                                                                                                                                                          
save(ok): . (dataset)
create(ok): subdataset (dataset)
action summary:
  add (ok: 2)
  create (ok: 1)
  save (ok: 1)
add(ok): hello_world.txt (file)                                                                                                                                                                                      
save(ok): subdataset (dataset)                                                                                                                                                                                       
add(ok): subdataset (file)                                                                                                                                                                                           
save(ok): . (dataset)                                                                                                                                                                                                
action summary:                                                                                                                                                                                                      
  add (ok: 2)
  save (ok: 2)
bash /home/yoh/proj/datalad/trash/superdatasetsave.sh  3.69s user 2.09s system 99% cpu 5.827 total
(dev3) 1 17282 [1].....................................:Tue 28 Sep 2021 04:09:41 PM EDT:.
lena:/tmp
$> datalad status -d superdataset 
nothing to save, working tree clean

```
</details>

please reopen if this doesn't answer your question

**Comment by tjhendrickson** [comment]
Hi Yarik,

Thanks for your reply. I get that if I were to do it over again I would have done it differently, but part of my problem is that my datalad dataset is already gigantic (again 10,000 subjects) and it took a lot of work to get it set up. My hope is that I could avoid having to regenerate the datalad dataset to make this happen. If that is not possible I will start over, but I first want to explore every avenue to avoid starting over. 

Best,


-Tim
