### ISSUE TITLE
Lots of `server certificate verification failed. CAfile: none CRLfile` errors on ubuntu CI

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6026]
Sample https://ci.appveyor.com/project/mih/datalad/build/job/begrlqetcsw4f3ra

Seems unspecific to this PR.

Reported for

- https://datasets-tests.datalad.org
- https://gin.g-node.org

and possibly CRCNS.org, but hidden in a more complex download failure.

Given that it is only the linux workers, and that it is not a single host for which it fails, I blame the certificate setup in the worker.

**Comment by jwodder** [comment]
This may be relevant: https://superuser.com/questions/1679204/curl-on-ubuntu-14-all-lets-encrypt-certificates-are-expired-error-60

**Comment by yarikoptic** [comment]
Thank you @jwodder, let's see if https://github.com/datalad/datalad/pull/6027 would fix that and not break anything else ;)
