### ISSUE TITLE
Adjust docstring for arguments with 'nargs=*'

### ISSUE THREAD

**Issue by hanke** [datalad/datalad#603]
Due to the way argparse works we cannot use EnsureListOf(sometype) in such cases. Hence the Python API documentation doesn't reveal that sequences must be be passed into the functions.

**Comment by yarikoptic** [comment]
Since all of the argparse use is dark magic to me,  can neither really suggest anything without have a class look nor comprehend what is of the "the way the argparser works" we are talking about or could it be somehow mitigated through argparser fixes or monkey patching

**Comment by hanke** [comment]
argparse evaluate the `type` for each input and only afterwards collates all into a list. The fix is easy, and does not require any change to argparse. This is just a note to not forget about the issue.
