### ISSUE TITLE
`readline_rstripped()` should be un-deprecated

### ISSUE THREAD

**Issue by jwodder** [datalad/datalad#6030]
In [this exchange](https://github.com/datalad/datalad/pull/5667#discussion_r635214578) on #5667, it was decided to add a deprecation warning to `datalad.cmd.readline_rstripped()` on the assumption that it was no longer used.  However, it *is* used: [it's the default `output_proc` for `BatchedCommand`](https://github.com/datalad/datalad/blob/91ed701ddc36a97d76c2f976f996157959f73606/datalad/cmd.py#L96), and so, with the release of 0.15.0, using `BatchedCommand`, `BatchedAnnex`, `BatchedAnnexes`, etc. produces a deprecation warning.

**Comment by yarikoptic** [comment]
oops -- I was the one who stated it is not used, my bad.  It is a trivial tiny function but probably not worth being "exported" a part of the `cmd` API.  But also given that we do not really bother "sanitizing" API at our modules level, I think the easiest way out is just to undeprecate it.  Will send a quick PR for consideration

**Comment by mih** [comment]
Fixed via #6032
