### ISSUE TITLE
Clarify `get --reckless` docstring, only affects subdataset clones

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6039]
User reported confusion that `get --reckless auto` does not do hardlinks for files, after `clone` was done without `--reckless`.

While at it, the patronizing statements in the `--reckless` docstring should be removed.

**Comment by adswa** [comment]
I have made an attempt to fix this in #6043, please take a look. I'm not well-versed in the --reckless parameter, I'd appreciate a second opinion.

**Comment by adswa** [comment]
> mih moved this from Needs triage to Easy in Tackle user experience issues 4 hours ago

I very much get this move, and I was inclined to label this issue as "easy"/"good-first-issue" and leave it for someone else to tackle, but I think for this issue to have become truly easy (like, first-contributor-easy), it needed more information. Its difficult to find where this docstring is actually defined (neither in ``get`` nor ``clone``), it would benefit from a note that the wording must work for both of these commands, and a concrete pointer to the patronizing language would have helped to be more sure in what is to be deleted :-)

**Comment by mih** [comment]
Yeah, all true. The category was also since renamed "Maybe easy" ;-)
