### ISSUE TITLE
content change of annexed file not recognized

### ISSUE THREAD

**Issue by cni-md** [datalad/datalad#6046]
#### What is the problem?
After converting Philips data with heudiconv (repronim-reproin), the slice timing and PE dir is missing in the json files. Therefore, I run a script to add the missing parameters. This manipulation is not detected by dl and therefore not logged.
The json files are in git annex

#### What steps will reproduce the problem?
call repronim-reproin on Philips data. Modify json files with:

`#!/usr/bin/env python3

from bids import BIDSLayout
import json
import os
import stat
import glob
import nibabel as nib

layout = BIDSLayout('./nifti')
bold_files=layout.get( suffix='bold', task='lernmulti3', extension='nii.gz')
subjects = layout.get(return_type='id', target='subject' )

# add missing fields
for epi_file in bold_files:
    epi = nib.load(epi_file)
    slices = epi.header['dim'][3]
    myjson=json.loads(json.dumps(epi_file.get_metadata()))
    myjson.update({'SliceTiming': [slicescantime * 2./slices for slicescantime in range(slices//2)]*2 })
    myjson.update({'PhaseEncodingDirection':'j-'})
    myjson.update({'EffectiveEchoSpacing':epi_file.tags['EstimatedEffectiveEchoSpacing'].value})
    os.chmod(epi_file.path.replace('.nii.gz', '.json'), stat.S_IWRITE | stat.S_IREAD | stat.S_IRGRP | stat.S_IROTH )
    with open (epi_file.path.replace('.nii.gz', '.json'),'w') as jf:
      jf.write(json.dumps(myjson, indent=4))
`

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.15.1

**Comment by yarikoptic** [comment]
> the slice timing and PE dir is missing in the json files.

yes, Philips doesn't store slice timing or even order really of slices... order though could be figured out based on UIDs IIRC, but timing is a "guess work" under assumption of even spread etc.

in above example I do not see any `datalad save` invocation -- datalad is not a service which would monitor your directory. you need to `save` the changes

**Comment by cni-md** [comment]
Sorry. I used datalad run myscript.py and also datalad save after the script without datalad run. datalad status reports no change, all fine.

**Comment by yarikoptic** [comment]
so let's close, if I misunderstood "all fine" and there is an issue -- feel welcome to reopen.

**Comment by cni-md** [comment]
It is reproduceable

datalad create dummy
copy nifti dataset to dummy
remove all slicetimings from json file
datalad save
run update script -> json file contains slicetimings
datalad status -> nothing to save
git log -> no additional entry. only my nifti files and script from dl save before.

**Comment by yarikoptic** [comment]
what `git status` say? if that one is also silent -- files are not modified from what is known to git.

**Comment by adswa** [comment]
Sounds weird, but hard to investigate like this. Do you have time tomorrow at 4pm Berlin time? We could take a look during office hour.

**Comment by adswa** [comment]
> Do you have time tomorrow at 4pm Berlin time? We could take a look during office hour.

More info in this matrix chat room: https://matrix.to/#/!NaMjKIhMXhSicFdxAj:matrix.org?via=matrix.waite.eu&via=matrix.org&via=inm7.de

**Comment by cni-md** [comment]
It was my old non dl code, to modify the heudiconv output. Problem solved
