### ISSUE TITLE
Application vs library use distinction (also Python vs Cmdline)

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#6081]
Seeing https://github.com/datalad/datalad/pull/6078#issuecomment-944040232 reminded me, that we had several cases already where the information whether datalad was called via CLI or python would be desirable.
Currently that is not assessible from within most of the code base. However, the outer layer in `interface`, the arg parsing, etc. do actually have that information. We could simply set a module attribute in `datalad`, `datalad.api` or may be `datalad.interface` to store a flag, that can then be used by code deeper down.

WDYT, @datalad/developers ?

**Comment by yarikoptic** [comment]
another benefit from knowing that we are working from CLI might be to not bother rendering python docstrings for the interfaces:

```shell
$> datalad clone /// out
...
  /home/yoh/proj/datalad/datalad-master/datalad/core/distributed/clone.py(95)<module>()
-> class Clone(Interface):
  /home/yoh/proj/datalad/datalad-master/datalad/interface/base.py(521)build_doc()
-> update_docstring_with_parameters(
  /home/yoh/proj/datalad/datalad-master/datalad/interface/base.py(342)update_docstring_with_parameters()
```

**Comment by mih** [comment]
This is going all the way back to #2986
