### ISSUE TITLE
Compose a document on dataset content naming best-practices

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6083]
A great starting point is https://datatracker.ietf.org/doc/html/rfc8493#section-6.1

This can be pretty much taken 1:1, and possibly amended with specific additions -- but it goes a long way already. it also matches a kaleidoscope of little gotchas that we discovered ourselves along the way.

**Comment by adswa** [comment]
I have started in https://github.com/datalad-handbook/book/pull/794

**Comment by adswa** [comment]
I consider this done in the handbook and will close - but feel free to reopen, or suggest a place in core where we can link this.
