### ISSUE TITLE
Witless-based BatchedCommand (but generally generator-style command execution)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6085]
We need this dearly. It is the primary reason for datalad's slowness (especially on big datasets). Basically what we need is a way to execute a command, and start yielding outputs as quickly as possible, *not* waiting for the command to finish. When we have that, we also have batched command -- without the need for a dedicated implementation, because we also want to start yielding as quickly as possible for non-batched commands.

My under-performing brain thinks:

- if we want to start acting on outputs, while we are still in a `run()` method, we need multithreading (at least)
- we need to receive process output in the thread, turn it into a desirable structure (maybe JSON decode), and hand it over to the main thread for acting on it while more process output is received
- it seems https://docs.python.org/3/library/queue.html is the standard exchange paradigm for this stuff

It would be ideal, if we could wrap this entire construct into something that acts as an iterable, is parameterized with a runner instance, and exposes the signature of `Runner.run()`

**Comment by adswa** [comment]
Has #6244 fixed this issue?

**Comment by christian-monch** [comment]
> Has https://github.com/datalad/datalad/pull/6244 fixed this issue?

I would say it did, closing this issue
