### ISSUE TITLE
FOI: OpenMined for federated data analysis

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#6099]
@jsheunis and me had a pleasant chat with  @iamtrask on OpenMined (www.openmined.org), an open source toolkit for privacy preserving machine learning. Some pointers are https://github.com/OpenMined/PySyft, https://www.youtube.com/watch?v=DppXfA6C8L8, or https://www.youtube.com/watch?v=9qYDtt2XM2o.
I've shared pointers to our docs and chatrooms - maybe we can find intersections for interoperability in the future.

**Comment by mih** [comment]
Thx! Tagging and closing.
