### ISSUE TITLE
[Suggestion] add --jobs/-J option to `datalad run`

### ISSUE THREAD

**Issue by AKSoo** [datalad/datalad#6118]
`run` involves `get` on the inputs. However, `run` cannot make use of parallel jobs for `get` because there is no option for it.

**Comment by bpinsard** [comment]
I third that! ;)  And also for `datalad-containers-run`.
It would be critical when using datalad for parallel computing on HPC to maximize the usage of requested resources when cloning and getting input data and repushing results to a central repo (or ria-store).
I think for now the only way to achieve that is by setting the 2 following config values either globally or at a dataset level (which is not super convenient for nested ones), though I have not tested that yet. 

> datalad.runtime.max-annex-jobs
> Maximum number of git-annex jobs to request when “jobs” option set to “auto” (default): Set this value to enable parallel annex jobs that may speed up certain operations (e.g. get file content). The effective number of jobs will not exceed the number of available CPU cores (or 3 if there is less than 3 cores). Default: 1
> [value must be convertible to type ‘int’]

> datalad.runtime.max-jobs
> Maximum number of jobs DataLad can run in “parallel”: Set this value to enable parallel multi-threaded DataLad jobs that may speed up certain operations, in particular operation across multiple datasets (e.g., install multiple subdatasets, etc). Default: 1
> [value must be convertible to type ‘int’]
