### ISSUE TITLE
No warning / error when incorrect config procedure is given to datalad create -c

### ISSUE THREAD

**Issue by mslw** [datalad/datalad#6129]
### What is the problem?

When datalad create is used with an incorrect run procedure name, it generates no warnings or errors. The exit status reported by zsh is not zero, but there is no explicit information why (no `create(ok)` message either). The dataset gets created, just without applying the configuration.

### What steps will reproduce the problem?

Verify expected operation when a correct name is given:
```
$ datalad create -c text2git my-dataset
[INFO   ] Creating a new annex repo at /home/mszczepanik/Documents/rdm-warmup/example/my-dataset 
[INFO   ] Running procedure cfg_text2git 
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) =====                    
create(ok): /home/mszczepanik/Documents/rdm-warmup/example/my-dataset (dataset)
```
Reproduce by using an incorrect name:
```
datalad create -c texttogit my-other-dataset
[INFO   ] Creating a new annex repo at /home/mszczepanik/Documents/rdm-warmup/example/my-other-dataset 
```

### Datalad information

Datalad 0.15.0 on Debian 11 (bullseye)

### Additional context

This message is shown when `--log-level debug` is used 
```
$ datalad --log-level debug create -c texttogit my-other-dataset
(...)
[DEBUG  ] Cannot find procedure with name 'cfg_texttogit' [run_procedure(cfg_texttogit)] 
[DEBUG  ] could not perform all requested actions: IncompleteResultsError(Command did not complete successfully. 1 failed:
[{'action': 'run_procedure',
  'message': "Cannot find procedure with name 'cfg_texttogit'",
  'path': 'cfg_texttogit',
  'refds': '/home/mszczepanik/Documents/rdm-warmup/example/my-other-dataset',
  'status': 'impossible'}]) 
```

The message comes from `datalad/interface/run_procedure.py` [here](https://github.com/datalad/datalad/blob/3478fefef9f20a665108a74e2ab16aca48eb5495/datalad/interface/run_procedure.py#L398). If there's agreement that  this situation should be elevated to error/warning, I think I could try submitting a PR.

### Have you had any success using DataLad before?

Yes, though mostly tutorial-level stuff.

**Comment by adswa** [comment]
> If there's agreement that this situation should be elevated to error/warning, I think I could try submitting a PR.

I think there is. To copy some comments from the lab chat:

@adswa: I agree that it should at least issue a warning!

@bpoldrack: I would agree. Invalid argument (procedure doesn't exist) -> error. One may disagree when the error should occur, though. It could occur upfront and prevent even the creation of the dataset. Not sure. I can see both being useful under different circumstances. It may not be easy to apply the correct procedure to the correct datasets afterwards to a complex structure created by script - hence you'd want to fail upfront. Single execution -> likely preference for creating anyway and give an error afterwards. So, I'd lean to: yield error right away and allow dealing with it in the standard way (on-failure=ignore)

@mih: such conditions should ideally be detected early they should not be reported as error results, if they can be detected immediately at the start of a command, but rather raise an exception. A warning is not enough. If we know that something is an error, we should not run with it (ValueError!)

It would be great if you could submit a PR. Let me know if I can help you in any way.

**Comment by yarikoptic** [comment]
FWIW I would vote for an error! Warning is indeed not enough!

**Comment by mih** [comment]
Sounds like a plan!

**Comment by mslw** [comment]
Thanks! Since this is the first time I am touching something inside DataLad, I'd like to ask questions first. The current block of code looks like this:

```
        try:
            # get the first match an run with it
            procedure_file, cmd_name, cmd_tmpl, cmd_help = \
                next(_get_procedure_implementation(name, ds=ds))
        except StopIteration:
            res = get_status_dict(
                    action='run_procedure',
                    # TODO: Default renderer requires a key "path" to exist.
                    # Doesn't make a lot of sense in this case
                    path=name,
                    logger=lgr,
                    refds=ds.path if ds else None,
                    status='impossible',
                    message="Cannot find procedure with name '%s'" % name)
            yield res
            return
```

1. What is the proper way to raise an exception here? I suppose I could replace `return` with `raise ValueError(...)` (possibly raising from the stop iteration), but what should be done with `res = get_status_dict(...)`? Should I change status to "error" and leave the rest as it is, or find a way of putting the new exception inside (I tried, but it accepts `CapturedException`s and a plain `ValueError` won't work)? Or should this part go out because `raise` makes it redundant?
2. There is currently a test for this situation [here](https://github.com/datalad/datalad/blob/3478fefef9f20a665108a74e2ab16aca48eb5495/datalad/interface/tests/test_run_procedure.py#L56) which asserts that the status is set to "impossible". The test fails if an error is raised. Can I change this test to use `assert_raises` instead?
3. The run procedure is applied after dataset creation, so even if the error is raised, the dataset gets created (i.e. directory exists and first commit is made). Is this ok?

**Comment by adswa** [comment]
> What is the proper way to raise an exception here? I suppose I could replace return with raise ValueError(...) (possibly raising from the stop iteration), but what should be done with res = get_status_dict(...)? Should I change status to "error" and leave the rest as it is, or find a way of putting the new exception inside (I tried, but it accepts CapturedExceptions and a plain ValueError won't work)? Or should this part go out because raise makes it redundant?

I'm quoting @mih from above:
> such conditions should ideally be detected early they should not be reported as error results, if they can be detected immediately at the start of a command, but rather raise an exception.

i.e., he's in favor of not returning any result, and you could replace the complete ``res= [...]`` part with ``raise ValueError(...)``

> There is currently a test for this situation here which asserts that the status is set to "impossible". The test fails if an error is raised. Can I change this test to use assert_raises instead?

This sounds like a good idea to me :) 

> The run procedure is applied after dataset creation, so even if the error is raised, the dataset gets created (i.e. directory exists and first commit is made). Is this ok?

In line with the quote from @mih, you could maybe move the check whether the procedure exists up, before dataset creation, and error out early. Then, dataset creation only takes place when the procedure has been verified to exist.
