### ISSUE TITLE
Error when getting file with datalad "not available"

### ISSUE THREAD

**Issue by itepifanio** [datalad/datalad#6131]
### What is the problem?

I'm trying to use datalad to recovery a file, but when I tried using ` datalad get datalab-data/some-file.zip ` at first throws me:

```
[ERROR  ] Unable to parse git config from origin
| Remote origin does not have git-annex installed; setting annex-ignore
| This could be a problem with the git-annex installation on the remote. Please make sure that git-annex-shell is available in PATH when you ssh into the remote. Once you have fixed the git-annex installation, run: git annex enableremote origin
```

Then, if I run it again throws me:

```
[ERROR  ] not available; Try making some of these repositories available: <some-hash-here> -- backblaze; (Note that these git remotes have annex-ignore set: origin) 
```

### What steps will reproduce the problem?

Kind hard to reproduce because I'm using a private repository to clone and recovery the data.

### Datalad information

I'm using the PopOs 20.04 distro. 

I downloaded git-annex and exported to my PATH using ` wget -c https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz && export PATH="~/.git-annex.linux`. The git-annex version is 8.20211012.

Then I downloaded datalad using poetry install (the datalad dependency is locked as `datalad = "^0.14"`).

When I run ` datalad get datalab-data/some-file.zip ` it throws me that error above.

### Have you had any success using DataLad before?

It's my first time using DataLad

**Comment by yarikoptic** [comment]
what is the `origin` remote you have?  (e.g. `git remote show origin`)

output of `git annex whereis datalab-data/some-file.zip` ?

> It's my first time using DataLad

but you are familiar with git-annex since (I assume) you are trying to access some files  which were backed up using it?

**Comment by itepifanio** [comment]
So my origin point to a gitlab project.

```
> git remote show origin
* remote origin
  Fetch URL: ssh://git@gitlab.company.io:12345/organization/repository.git
```

And this project has a .noannex, so to run ` git-annex whereis datalab-data/some-file.zip ` I removed the .noannex, inited the project and it throws me:

```
> git-annex init
  Unable to parse git config from origin

  Remote origin does not have git-annex installed; setting annex-ignore

  This could be a problem with the git-annex installation on the remote. Please make sure that git-annex-shell is available in PATH when you ssh into the remote
```

I'll talk with the admin to check the remote origin configuration. Thanks for your help @yarikoptic o/

**Comment by mih** [comment]
If the dataset has a `.noannex` file. Are you confident that this is an orderly git-annex repository?

**Comment by itepifanio** [comment]
@mih you're right. I was trying to get the data from the root of the directory and didn't work :man_facepalming:. On the right folder I was able to download using only `git-annex init && git-annex get ...`

**Comment by mih** [comment]
Ok, cool! Sounds like we can close this issue. Feel free to reopen, if needed.
