### ISSUE TITLE
datalad get fails on subdataset with different ria URL than superdataset

### ISSUE THREAD

**Issue by FeHoff** [datalad/datalad#6159]
### What is the problem?

I created a Datalad dataset with subdatasets for every subject for a BIG neuroimaging dataset: Ds - manyDs 
Then I add this dataset with many subdataset as input dataset to another superdataset: SDs -> Ds - manyDs
When I push this setup to a RIA URL with another ria url than the first Ds containing all subdatasets, I cannot datalad get the subdatasets form the supersubdataset, while it works with the identical ria url for SDs & Ds.  
When I check the git remote in the subdataset the RIA does not resolve to the hash in the case of different URLs for SDs and manyDs.
```
RIA superdataset:    /data/project/inputstore
RIA subdataset:	 /data/project/dataladstore/alias/3T_data
```
```
RIA superdataset:  /data/project/dataladstore
RIA subdataset:     /data/project//dataladstore/5e7/1a5e6-95c7-4b38-9099-5c46f2379007
```

### What steps will reproduce the problem?

Should be rather clear from above:
Add (clone by alias link) a dataset with subdatasets to a superdataset. Then create a sibling with another URL than the added dataset. Uninstall the added dataset. Push the superdataset to the URL (different than the added one). Clone the Superdataset and datalad get the dataset and subdatasets failed then for me. 

### Datalad information

datalad 0.15.0

## python 
  - implementation: CPython
  - version: 3.7.3
## system 
  - distribution: debian/10.11
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 297
  - name: Linux
  - release: 4.19.0-18-amd64
  - type: posix
  - version: #1 SMP Debian 4.19.208-1 (2021-09-29)

### Additional context

I am using our workflow:  
https://github.com/psychoinformatics-de/fairly-big-processing-workflow

### Have you had any success using DataLad before?

Yes, absolutely, great things 💯 
🏄🏼

**Comment by bpoldrack** [comment]
I reproduced the behavior. Cloning the superdataset and trying to get all its subdatasets recursively resulted in successful `get` for the intermediate dataset, but not its subdatasets.

The issue appears to be the consideration of subdataset candidate urls. In the final clone I get this for the intermediate dataset's `.git/config`:

```
❱ cat intermediate/.git/config    
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = /tmp/firststore/alias/intermediate
	fetch = +refs/heads/*:refs/remotes/origin/*
	annex-ignore = true
	datalad-publish-depends = first-store-storage
[branch "master"]
	remote = origin
	merge = refs/heads/master
[annex]
	uuid = 05446ca1-5496-4b2a-b693-49b0916a20b0
	version = 8
[filter "annex"]
	smudge = git-annex smudge -- %f
	clean = git-annex smudge --clean -- %f
[remote "first-store-storage"]
	annex-externaltype = ora
	annex-uuid = 72236cc6-091f-4d32-98e4-5cc75f4f7abb
	annex-cost = 100.0
	annex-availability = GloballyAvailable
[datalad "get"]
	subdataset-source-candidate-200origin = "ria+file:///tmp/secondstore#{id}"
```

Note, that this dataset itself (in opposition to its superdataset) was *correctly* cloned from `first-store`, but suggests its subdatasets to be looked up in `second-store`.

**Comment by bpoldrack** [comment]
Additional observation:

When debugging `get/clone` what I see is, that we first do the right thing when adding this config from within `postclonecfg_ria`. But somewhere down the line we change it to the wrong thing.

**Comment by bpoldrack** [comment]
Ok, so: It's `get` that is at fault here. `clone` (internally called by `get`) sets that config correctly, but is then overruled by `get` that changes it again.

This is, where it goes wrong:
https://github.com/datalad/datalad/blob/981aa95ba2a6fcc6db5631dd11a1086ec1aecfcb/datalad/distribution/get.py#L379
