### ISSUE TITLE
Decision needed: ORA/RIA using datalad's providers or not

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6162]
Right now HTTPIO is a hot mess in ORA. It aims to integrate with datalad's credential/provider handling, but fails to do so completely (#6160 #6161). I see only two paths forward:

1. Stop using datalad's provider feature, and go plain requests.
2. Improve the downloader facility to cover more HTTP requests than just downloads.

Given that I don't understand (2), I would personally go for (1).

**Comment by bpoldrack** [comment]
I went through the provider/credential system recently and am doing so again in context of #6409.
I think, approach 2) is what it should ultimately be. That part of the code base needs attention and has implications throughout a lot of usecases that don't involve ORA. It's just our usage of RIA stores that exposes those issue via ORA. The `datalad` special remote shares most of the issues. 

1.) Would imply to either not deal with authentication at all or build a parallel system from scratch. If we do the later we better do it not as an ORA special case, but as replacement/RF'ing of the provider system
