### ISSUE TITLE
Stop using Appdirs

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#6164]
We rely on [appdirs](https://github.com/ActiveState/appdirs) to figure out appropriate config, data, and cache dirs for any given platform. However, the implementation in appdirs for Windows is for Windows 7 at latest. It relies on [Windows special folders CSIDL IDs](https://www.nirsoft.net/articles/find_special_folder_location.html) and retrieves them for example like this:

```
path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
```
where ``CSIDL_LOCAL_APPDATA`` is an identifier for a special folder. This is necessary because Windows versions change the location and name of these special folders.
However, since Windows Vista, these IDs have been replaced by [``KNOWNFOLDERID`` values](https://docs.microsoft.com/en-us/windows/win32/shell/csidl), and Windows advises to use them instead.

I believe this is the underlying cause for the test failure observed in #6160. 

I filed [an issue with appdirs](https://github.com/ActiveState/appdirs/issues/167) this summer because certain CSIDL ID's simply don't exist (they return an empty string on the windows 10/11 test boxes) but did not receive a reply, and it doesn't look like there is much development anymore. 

I think, at least for Windows-related things, we should switch away from appdirs.

**Comment by jwodder** [comment]
For the record, the modern, maintained replacement for appdirs is [platformdirs](https://github.com/platformdirs/platformdirs).

**Comment by adswa** [comment]
> For the record, the modern, maintained replacement for appdirs is [platformdirs](https://github.com/platformdirs/platformdirs).

Thanks a lot! I guess we should at least switch to that one. They also seem to use CSIDL values instead of KNOWNFOLDER IDs under Windows, sadly. I have a rather lengthy alternative that I might PR as a draft later...
