### ISSUE TITLE
`get_status_dict()` can no longer handle any exception, requires `CapturedException` now

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6171]
Story in https://github.com/datalad/datalad/pull/6167#discussion_r746504495

**Comment by bpoldrack** [comment]
I'd argue, that with the exception handling guideline there shouldn't be any need to be able to deal with any `Exception` and hence nothing needed but documentation.

However, I'm fine with making `get_status_dict` able to deal with any exception again and will do so, if desired.

**Comment by mih** [comment]
I think it would have been sufficient to add documentation, which I now did in https://github.com/datalad/datalad/pull/6167
