### ISSUE TITLE
Can a RIA store track datasets at their original location?

### ISSUE THREAD

**Issue by mslw** [datalad/datalad#6184]
Alternative title: can I have a RIA store which communicates what files I have and where, but does not store their contents.

## Problem statement

Suppose that I have one or several DataLad datasets in some locations that are accessible to me. I would like to push them (datasets, not contents) all to one, local, "central" RIA store. I would then like to have the ability to clone from the RIA store, without having to know the exact original location (that knowledge would be embedded in the RIA store). In the dataset cloned from the store, I would expect the get operation to work (DataLad would reach for the original location). Can I do that, and if so, how?

Imagine: several datasets with images in Pictures folder, and a RIA store in Documents that "indexes" them.

Or, less of a toy example: several datasets on a NAS server (home or lab storage) and a GitLab repository which indexes them all. So the GitLab is my way to communicate to you the dataset content / data location, but you'd have to come to my home / lab to actually obtain these files. In principle, this should be equivalent to the previous.

So this is, in a way, a question about propagation of origin through push / clone operations.

It might be lengthy, but I'll describe my reasoning and attempted steps below. If you decide the question makes sense and we find a solution, this can be then turned into a walkthrough. If that's not a good place for this issue, feel free to close it and suggest another place it should go. Datalad 0.15.0 on Debian GNU/Linux 11 (bullseye).

## Practical example

I will use a single dataset, though normally there would be more, and I'd want to push them to the same RIA store. Assume there is a dataset with some annexed files in `~/Documents/issue/original/ds01` and I see this as an original location.

### Naive approach
What certainly works is cloning from the original location:
```
mkdir /home/mszczepanik/Documents/issue/location1
cd /home/mszczepanik/Documents/issue/location1
datalad clone /home/mszczepanik/Documents/issue/original/ds01
cd ds01
datalad get file01.jpg
```
```
get(ok): file01.jpg (file) [from origin...]
```

Let's try going through a RIA store (without storage sibling - this sounds like a good idea for a potential "index" of datasets):
```
# create RIA & push
mkdir -p /home/mszczepanik/Documents/issue/central/ria-storeusing another mechanism 
cd /home/mszczepanik/Documents/issue/original/ds01
datalad create-sibling-ria --name ria --dataset . --alias ds01 --storage-sibling off \ 
    ria+file:///home/mszczepanik/Documents/issue/central/ria-store
datalad push --to ria

# clone to a new location
mkdir /home/mszczepanik/Documents/issue/location2/
cd /home/mszczepanik/Documents/issue/location2/
datalad clone "ria+file:///home/mszczepanik/Documents/issue/central/ria-store#~ds01"
datalad get file01.jpg
```
```
get(error): file01.jpg (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
```
Should I have expected it to work? Perhaps not (either because it doesn't work this way for regular git repository, or because revealing local path may not always be desired) - but my thinking initially went this way.

### Naive approach 2
Same as above, except the original dataset gets cloned into another dataset (which serves as a superdataset) and that one is pushed to RIA. The effect is the same as above. Of course, I could be using this superdataset directly as my "central storage" or "index", but my point is specifically about creating something through a publish mechanism.

### Git annex special remotes

I was then pointed to [git-annex special remotes](https://git-annex.branchable.com/special_remotes/git/). 

The dataset cloned from a original location has a remote called `origin`. 
```
cd /home/mszczepanik/Documents/issue/location1/ds01
datalad siblings
```
```
.: here(+) [git]
.: origin(+) [/home/mszczepanik/Documents/issue/original/ds01 (git)]
```
But, evidently, this is a standard git remote and it would not propagate through push

However, some *special remotes* can propagate through the push operation, as is the case for [S3 special remotes](https://handbook.datalad.org/en/latest/basics/101-139-s3.html) for example. Hence my expectation that a similar thing can be done here.

I'm working with the first clone, because (probably) the original dataset can't be a remote for itself. However, I wasn't able to create a special remote in origin's location:
```
git annex initremote original-source type=git \
    location=/home/mszczepanik/Documents/test-call/raw-dataset \
    autoenable=true
```
```
initremote original-source 
git-annex: could not find existing git remote with specified location
failed
initremote: 1 failed

```
Neither with prepending `file://` to the location:
```
git annex initremote original-source type=git \
    location=file:///home/mszczepanik/Documents/test-call/raw-dataset \ 
    autoenable=true
```
```
initremote original-source 
git-annex: could not find existing git remote with specified location
failed
initremote: 1 failed
```

## Questions
- How can I propagate a local origin to a RIA store (or some other repository)
- Does the presented problem pose a valid question? Am I misunderstending things completely? Should I be looking at different mechanisms?
- Why doesn't `git annex initremote` work in the example above?

**Comment by mih** [comment]
I think you are on the right track. The `type=git` special remote is the best way forward in your case (accept that the use of `file://` URLs will cause pain down the road, because particular security implications apply to them).

I would recommend to take a look at `datalad siblings --as-common-datasrc` for a helper to set things up properly.

**Comment by adswa** [comment]
> Suppose that I have one or several DataLad datasets in some locations that are accessible to me. I would like to push them (datasets, not contents) all to one, local, "central" RIA store. I would then like to have the ability to clone from the RIA store, without having to know the exact original location (that knowledge would be embedded in the RIA store). In the dataset cloned from the store, I would expect the get operation to work (DataLad would reach for the original location). Can I do that, and if so, how?

Its a completely valid usecase. This is, for example, how the [human-connectome-project-openaccess dataset](github.com/datalad-datasets/human-connectome-project-openaccess) is set up. Some information on how it was build is here: http://handbook.datalad.org/en/latest/usecases/HCP_dataset.html

But I think where it gets tricky is that you're all doing this locally. I checked in ``siblings`` source code, and we (and I thus assume also git-annex) only act on ``http`` or ``https`` urls:

https://github.com/datalad/datalad/blob/d8270f693c51854b6e1694bdeb5fdd46cd2e03e1/datalad/distribution/siblings.py#L580-L605

**Comment by mih** [comment]
Ah, true! I forgot that we changed this -- I think because git-annex will ultimately refuse to work with any other protocol. Moreover, `file://` URLs are a security risk, because a plain `git annex get somefile` could extract information from anywhere else on a machine, without making this obvious in code or command execution. A subsequent `push` could then ship this extracted info to a remote machine.

Check the documentation on `annex.security.allowed-url-schemes` and `annex.security.allowed-http-addresses` for related info, and other gotchas that you will likely run into with this setup.

**Comment by mslw** [comment]
Thank you both for your answers! Let me try and follow up on them.

### HCP example & addurls

The HCP example is a great one, and indeed very fitting for the situation that I had in mind. One fundamental thing I noticed is that the datasets there are built, fundamentally, upon `datalad addurls`. Since the source location for `addurls` is stored in a dataset, it gets sent to storage-less RIA without any additional steps.

I tried applying it to my local example. After adding the following to the `.git/config` of *both* my source dataset and its clone made from RIA:
```
[annex "security"]
	allowed-url-schemes = http https ftp file
```
I was able to complete my "round-trip" (addurls, push to RIA, clone from RIA, get). However, I needed to use `git annex addurl file://...` followed by `datalad save`, because `datalad download-url` refuses to work with protocols other than http(s), shub, ftp & s3, regardless of this setting*. I didn't try `datalad addurls`.

While it differs from my initial idea (making it work through push/pull alone), I see that using `download-url` with `file://` could be a good idea a) wanted to index files which aren't necessarily in DataLad datasets b) was willing to have an additional level of trust in dataset users.

### Special remotes

As pointed out, `datalad siblings --as-common-datasrc` is limited to http(s). My ability to add a special remote (pointing to a file location) through `git annex initremote` remains unaffected by `annex.security.allowed-url-schemes`, and results in the same error as in my original message. So at this moment I din't know if and how can I make it work.

I also noticed that git annex has other special remotes, such as [directory](https://git-annex.branchable.com/special_remotes/directory/) and maybe I should look into these, but its description suggests it's not quite what I want.

### Local vs remote locations

So it would seem that the mechanisms we talked about (addurls, special remotes) are specifically made for remote content, and by trying to come up with "simple" local examples I am actually making things harder. Going back to my initial example, if my "original" dataset was on some other server accessible through http(s), ssh, s3, probably also ftp or even smb, I imagine that I would be able to set up the special remote (and propagate it through push) without issues.

But for the local-only, perhaps the answer is to stick with `datalad clone`, and build a superdataset without involving `push` and RIA at all?

### Side notes
The error produced by `datalad download-url file://...` regardless of config
```
ValueError(Do not know how to handle url file:///home/mszczepanik/Downloads/file.jpg for scheme file. Known: dict_keys(['http', 'https', 'shub', 'ftp', 's3']))
```
The error produced by `git annex addurl file://...` if `allowed-url-schemes` doesn't include `file`:
```
Configuration of annex.security.allowed-url-schemes does not allow accessing file:///home/mszczepanik/Downloads/file.jpg
```

**Comment by bpoldrack** [comment]
> I also noticed that git annex has other special remotes, such as directory and maybe I should look into these, but its description suggests it's not quite what I want.

Yes, that's not want you want. Such directories would reflect the respective annex object tree, not the desired checkout. Hence - unuseable w/o git-annex.

> But for the local-only, perhaps the answer is to stick with datalad clone, and build a superdataset without involving push and RIA at all?

Arguably that would be the simpler setup. However, if we can figure out why exactly the type-git special remote refuses to initialize that way, the RIA approach (with those special remotes and w/o content) would scale better, I think.

**Comment by mslw** [comment]
This was more of a question than an issue, so with the answers I think it can be now closed. Thank you for the explanations!
