### ISSUE TITLE
git credential hangs in tests on mac

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#6185]
I'm investigating a hanging test on mac in https://github.com/datalad/datalad/pull/5796.
I reproduced the issue on @yarikoptic 's mac (Thx!) and also on the actual appveyor build (SSH'ing into that build).
In both cases I see the command working just fine when executing it in the shell on the same repository as the test. The command in question is `git credential approve` being fed a description via stdin (`b'url=https://example.datalad.org/somepath\nusername=mike\npassword=s3cr3t\n'`).

There are a couple of aspects to this:
The repository has a git config `credential.helper=store` set. That's what we want to use in the test and when invoking the command in that repo that works just fine (I can also get those credentials back via `git credential fill`). However, there's a system-level `credential.helper=osxkeychain` in addition (seems to be default for a git installation on mac). When running the command manually with `GIT_TRACE` and `GIT_TRACE2` being set, I see that git seems to first invoke the `osxkeychain` credential helper and then `store`. From within the test, the child process for `osxkeychain` doesn't exit, though (hence the second one is never invoked). While it isn't clear to me why both are considered rather than the one specified locally only, that in itself doesn't appear to be the actual problem since this is working outside the test the same way.

I also checked whether a bundled with annex git is used, since I thought that may be the `git` wrapper script may screw things up, but that doesn't appear to be the case.

What is the case, though, is that it seems to be somehow related to the test setting `HOME` to a temp dir. In fact, if I set a breakpoint right before the call into the runner and change `os.environ['HOME']` back to the actual user's home dir, it works. I currenty have no idea why, though. The `.gitconfig` in both homes only defines the git user and a `datalad.log.exc` in addition in case of the "fake-home". Since this is only invoking git itself, that entry shouldn't matter whatsoever. The only other thing the fake home is containing is an empty `Library/Caches/datalad/sockets` directory. So, either something is missing in that fake home that's not obvious to me, or this some more indirect consequence of using that.

I am bit on a loss ATM. Any ideas, @datalad/developers ?

Edit:
Now, that I wrote it down, I realize I shoud check whether osxkeychain expects something in `HOME` ... on it, will update on that

**Comment by bpoldrack** [comment]
Ok, so I figured it right after writing it down.

1. The fact that `osxkeychain` is invoked in the first pace is correct, documented behavior actually. I can probably stop that from happening as it's somewhat pointless for the test, but there's no issue hiding in that observation.

2. `osxkeychain` credential helper expects the keychain in `HOME` and evidently can't deal with absence. Copying `~/Library/Keychains` to the fake home makes it work as expected.

3. For the tests I will probably disable `osxkeychain` altogether - it's irrelevant for what is to be tested.

4. Nevertheless, this isn't exactly the first issue emerging from the fact that we change `HOME` for the tests and fail to account for al consequences. As mentioned here https://github.com/datalad/datalad/issues/6160#issuecomment-964884349, I think we need a different approach altogether.

**Comment by mih** [comment]
@bpoldrack what is the status here, now that the credential helper is merged? Can this be closed?

**Comment by bpoldrack** [comment]
Yes. Solved.
