### ISSUE TITLE
not pick up system-wide installed manpages if running local copy of datalad

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#619]
already confused myself few times staring into outdated manpages when having previous release of datalad installed system-wide

**Comment by hanke** [comment]
I would recommend to use `--help-np` instead, which should do exactly that.

**Comment by yarikoptic** [comment]
so I would need to remember when to use `--help-np` and when `--help`? mneh... too old

So let's fix it by 
- introducing datalad's version into generated manpages (which is a common thing to do to have version of the tool or enclosing it suite listed . See e.g. random selection from 
```shell
$> zgrep '\.TH' /usr/share/man/man1/*.1.gz | head
/usr/share/man/man1/0desktop.1.gz:.TH 0DESKTOP 1 "2013" "Thomas Leonard" ""
/usr/share/man/man1/0install.1.gz:.TH 0INSTALL 1 "2013" "Thomas Leonard" ""
/usr/share/man/man1/0launch.1.gz:.TH 0LAUNCH 1 "2011" "Thomas Leonard" ""
/usr/share/man/man1/0store.1.gz:.TH 0STORE 1 "2010" "Thomas Leonard" ""
/usr/share/man/man1/0store-secure-add.1.gz:.TH 0STORE\-SECURE\-ADD 1 "2010" "Thomas Leonard" ""
/usr/share/man/man1/[.1.gz:.TH TEST "1" "January 2016" "GNU coreutils 8.25" "User Commands"
/usr/share/man/man1/2to3.1.gz:.TH 2TO3-2.7 "1" "January 2012" "2to3-2.7 2.7" "User Commands"
/usr/share/man/man1/2to3-2.7.1.gz:.TH 2TO3-2.7 "1" "January 2012" "2to3-2.7 2.7" "User Commands"
/usr/share/man/man1/2to3-3.4.1.gz:.TH 2TO3-3.3 "1" "January 2012" "2to3-3.3 3.3" "User Commands"
/usr/share/man/man1/2to3-3.5.1.gz:.TH 2TO3-3.3 "1" "January 2012" "2to3-3.3 3.3" "User Commands"
...
```
so usually 3rd (index from 0) entry in `.TH` is "name version"

- before showing manpage, quickly load it up, parse out version available there.  only if found and identical to `datalad.__version__` show the manpage. Otherwise -- do `--help-np`

Since all Germans are vacating seems to me, @debanjum -- give it a try? ;)

**Comment by hanke** [comment]
Looks like this is done.
