### ISSUE TITLE
Rebalance runtime of windows CI runs on appveyor

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6193]
![image](https://user-images.githubusercontent.com/136479/141691940-edbfff03-c97f-4261-b534-0bdeb0d6184e.png)

Almost 20min difference between the fastest and the slowest. This is the result of running more tests, and moving tests the other locations in this codebase.

**Comment by adswa** [comment]
It looks like the only possible point of improvement lies in redistributing tests between ``WinP39a1`` (35mins) and ``WinP39a2`` (53 mins). Other redistributions would either be across operating systems (impossible), or placing non-core tests into core tests such as ``MacP38core`` (not so helpful classification)
