### ISSUE TITLE
Auto GC/closing of batched annex processes

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6197]
The need is "inspired" by https://github.com/datalad/datalad-fuse/pull/19#issuecomment-964408821 but I think it would be good for any other use case which works with a "rich" hierarchy datasets while not committing anything, e.g. using batched `get` or `whereis`.
ATM batched annexes are created and then closed in [`AnnexRepo.precommit`](https://github.com/datalad/datalad/blob/master/datalad/support/annexrepo.py#L2554) which is triggered before git mutating functions (remove, commit, etc). So if only read-only operations are invoked, we would keep those batched annexes running "indefinitely" (well, as long as AnnexRepo instance is available).

I think we should limit number of active annex batched processes, and close the oldest unused.  My thinking is

- Should be done at the level of `BatchedCommand`. Although it is a base class only for BatchedAnnex ATM, I think it could be considered to be generally applicable, and that is where the logic should go:
- Define some class attribute `_active_instances` with loose refs to all instances created
- We must avoid closing "active" (think - multithreading, already in place for many operations and even more with `foreach` #5517 ) batched commands 
  -  the ones which are in `yield_` or `__call__` -- although `__call__` uses `yield_` we must add some re-entrable tracking so we do not `close` while it is post-processing output from `yield_` in `__call__`
  - for that there should be e.g. `_active: int = 0` and context manager so `@track_active` to decorate both methods which would increment `self._active` upon entry, decrement when leaving (regardless if exception or not). 
  - `_active_last: datetime` would be "touched" upon every yield from `yield_`
- `datalad.runtime.max-batched: int = 20` and `datalad.runtime.max-inactive-age: int = 60` (in seconds) in common_cfg.py be added so users could configure number (and age) to decide which batched processes to trim
- `@classmethod` `clean_inactive()` would then 
  - `if len(cls._active_instances) > max_batched` loop through `_active_instances`
    - remove from `_active_instances` all for which weak refs are gone
    - add inactive (`_active = 0`, possibility for a race condition here :-/ not yet sure if we should guard) to a list of repos to consider
    - sort all by their `_active_last`, and start removing from the oldest unused until hitting `max-batched` number of processes left or `max-inactive-age` number of processes left.  Add 2nd check - if still not `_active` (see above note on race condition -- this would minimize possibility) `.close` them. 
    - if `max-batched` was not hit - issue a "warning" at lgr.debug level (unless was already issued e.g. `max-inactive-age` ago) stating the summary of processes -- how many active (not even considered), how many inactive were not cleaned up due to "small age".
 - call `clean_inactive` within `BatchedCommand.__init__` so a birth of any new batched process would potentially cleanup some old/stale one if needed.

**Comment by jwodder** [comment]
@yarikoptic When adding the new options to `common_cfg.py`, should I fill out the "ui" field for them?  That seems to be intended for asking the user for input, which seems like the wrong thing to do in the middle of a process cleanup.  In a similar vein, should I fetch the values of the config options using `cfg.getint()` or something else?

**Comment by yarikoptic** [comment]
> @yarikoptic When adding the new options to `common_cfg.py`, should I fill out the "ui" field for them?

yes

> That seems to be intended for asking the user for input, which seems like the wrong thing to do in the middle of a process cleanup.

IIRC there will be no question if a new value or (a default is set and we do not request a value to be saved).  So it is safe to `.obtain` it.

> In a similar vein, should I fetch the values of the config options using `cfg.getint()` or something else?

just use `.obtain` and since you would set `'type': EnsureInt(),` I believe it would do the proper casting
