### ISSUE TITLE
Improve and extend the code of conduct

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#6226]
Our [Code of Conduct](https://github.com/datalad/datalad/blob/master/CODE_OF_CONDUCT.md) is a bit old, and almost meaningless in its current form. The project is seeing more and more external contributions, and while we've improved on the technical documentation for these things, I think there is room for improvement in the social space. I'm not aware of any form of interaction that would violate common COC norms, but I'd say its better to have rules in place we can refer before we need them.

I propose to adopt the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/) in its current version 2.1. The text is [here](https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md).

I propose that we include several people as points of contact (I'm volunteering to be one, but we should have at least one more person).
GitHub provides the means to also actually enforce the COC in the hopefully unlikely case of violations, for example by [blocking comments or users](https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization).
WDYT, @datalad/developers?

**Comment by mih** [comment]
I think this is reasonable. It is much more verbose than what we have, but it also actually contains meaningful information. I consider the declaration of standards we want to hold ourselves accountable to the key advancement over the status quo.

I propose to go straight to a vote.

:+1: Adopt the Contributor Covenant Code of Conduct in its current version 2.1
:-1: Reject the particular wording of the Contributor Covenant Code of Conduct, and discuss further
:eyes: Abstention

**Comment by christian-monch** [comment]
A few things in the proposed COC feel too broadly phrased, e.g. "pledge", "community". In addition, it seems to have a very broad reach. Maybe we should limit its applicability to datalad-development?

How about a shorter code of conduct, along the lines of:


> While participating in the development of datalad we would like you to:

> * Demonstrate empathy and kindness toward other people
> * Be respectful of differing opinions, viewpoints, and experiences
> * Give and gracefully accept constructive feedback
> * Accept responsibility and apologe to those affected by your/our mistakes,
>   and learn from the experience
> * Focus on what is best not just for us as individuals, for the progress of datalad
>
>
> We will not tolerate the following behavior when communication in the datalad development-space
>
> * The use of sexualized language or imagery, and sexual attention or advances of
>  any kind
> * Derogatory comments, and personal or political attacks
> * Public or private harassment
> * Publishing others' private information, such as a physical or email address,
>  without their explicit permission
> * Other conduct which could reasonably be considered inappropriate in a
>  professional setting


> Enforcement responsibilities
> [,,,]

**Comment by mih** [comment]
I think this would cripple the CoC without a definition of "datalad development-space". IMHO a workable definition could easily turn out as broad as the full CoC wording implements it.

**Comment by mih** [comment]
Verdict from dev call: let's adopt it as suggested.

**Comment by adswa** [comment]
Thanks for all input on this. Will prepare a PR, adding me and @mih as points of contacts.
