### ISSUE TITLE
ORA require more relaxed permissions than a local annex

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6254]
Here is the situation:

I want to drop from an ORA remote

```
% git annex drop -f joc-storage sub-...
  [Errno 13] Permission denied: '/data/project/ukb_vbm/outputstore/893/8de76-0302-45b5-9825-3c6ce3f3fffe/annex/objects/w4/2V/MD5E-s5303257--d2dd1136a5770958323d713b131c85e7.tar.gz/MD5E-s5303257--d2dd1136a5770958323d713b131c85e7.tar.gz'\nNote: Write permissions for a key's parentdirectory are also required to drop content.
```

It literally means that. `w4` and `w4/2V` have write permissions, but `w4/2V/MD5E-s5303257--d2dd1136a5770958323d713b131c85e7.tar.gz` does not.

And indeed, a key pushed via ORA remote has a writable parent directory. But why?

```
% ls -l 21f/b481c-5e02-40ab-a036-1d4d62cc3385/annex/objects/pF/Zf                                                                                  
total 1
drwxrws--- 2 mih ukb 3 Nov 26 13:42 MD5E-s4--ba1f2511fc30423bdbb183fe33f3dd0f/
```

With an ephemeral clone, a direct non-ORA access would go directly to this key-dir and be able to delete the key, bypassing git-annex protections.

Is this justifiable?

PS: ORA access via `file://` URL.

**Comment by bpoldrack** [comment]
1. AFAIR ORA doesn't set the permissions at all, hence there's no specific reasoning.
2. ephemeral clones are a good argument to do exactly that!

**Comment by mih** [comment]
But aren't these two in conflict? If it sets the permissions right, it would always run into the condition that it claims is wrong.

**Comment by mih** [comment]
This is how the misleading message came to be https://github.com/datalad/datalad/pull/5683

**Comment by bpoldrack** [comment]
I think we should go for that fix. The `ephemeral` arguments changes the previous conclusion from my POV.
