### ISSUE TITLE
Standardize cmdline short help argument selection

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6255]
Only the first argument of all alternative names (long and short) will go into the usage synopsis.

Presently, these are mostly short options.

Should it be like this? Or should it be more expressive:

Demo:

```
datalad drop [-r]

vs.

datalad drop [--recursive]
```

**Comment by adswa** [comment]
I don't have a strong preference, I would be fine with both short or long. Sometimes short options are also understandable because their metavar has an insightful name, e.g.

```
Usage: datalad save [-h] [-m MESSAGE] [-d DATASET] [-t ID] [-r] [-R LEVELS]
                    [-u] [-F MESSAGE_FILE] [--to-git] [-J NJOBS] [--amend]
                    [--version]
                    [PATH ...]
```

**Comment by mslw** [comment]
Personally? I like the long options (especially the first few times I'm checking a command, but often will keep using them). They are more explanatory, and sometimes help create a mental image of where the short option comes from (e.g. : `-s NAME` vs `--sibling NAME`). And many options have only the long option, so some may consider consistent use of long forms aesthetically pleasing.

That being said, I agree that metavars are often enough. And showing short options makes the entire message shorter, which might actually help readability. So I wouldn't mind at all if the short options keep being the norm.

All in all this is very much down to personal preferences.

**Comment by mih** [comment]
OK, popular opinion seems to be "it depends" ;-)
