### ISSUE TITLE
Report errors which happen during git push of datalad publish

### ISSUE THREAD

**Issue by debanjum** [datalad/datalad#628]
Our mess didn't work at all and it was because of the hook that didn't work but git didn't crash because of that either.

**Comment by bpoldrack** [comment]
I'm afraid I neither get what went wrong nor what the issue suggests to change.
`publish` should already report errors when pushing somehow fails. What kind of failure it didn't report?

**Comment by mih** [comment]
So what is up with this one? Unless new info is coming, I'd close this.

**Comment by mih** [comment]
Closing, unclear what this is about.

**Comment by mih** [comment]
FTR: #1544 now reports anything that happens during push via status and messages of results.
