### ISSUE TITLE
WTF: add information about the filesystem of CWD etc.

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6294]
Many issues we run into (e.g. freshish https://github.com/ReproNim/containers/issues/62) with git-annex stem from "exotic" filesystems, often used on HPC, and which could be proprietary and cannot be setup within our CI to be tested against.  When users report problems, and even share WTF information, it requires inquiring more to discover specific of the filesystem in question and possibly relevant details (e.g. mount options).

I think it would be great if we added information about file systems (of $HOME, $TMPDIR, and $CWD) into WTF. Not sure how it could be done in reliable/consistent way, but it could be done quite "easily" in ad-hoc fashion at least for Linux and OSX by parsing output of `mount` command which provides consistent'ish output AFAIK. E.g.  on Linux looks like

```
$> mount | grep /home
/dev/md16 on /home type btrfs (rw,noatime,compress=lzo,space_cache=v2,subvolid=257,subvol=/home)
```
and on OSX
```
yoh@datalads-imac2 ~ % mount
/dev/disk1s5s1 on / (apfs, sealed, local, read-only, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk1s4 on /System/Volumes/VM (apfs, local, noexec, journaled, noatime, nobrowse)
/dev/disk1s2 on /System/Volumes/Preboot (apfs, local, journaled, nobrowse)
/dev/disk1s6 on /System/Volumes/Update (apfs, local, journaled, nobrowse)
/dev/disk1s1 on /System/Volumes/Data (apfs, local, journaled, nobrowse)
map auto_home on /System/Volumes/Data/home (autofs, automounted, nobrowse)
/dev/disk1s5 on /System/Volumes/Update/mnt1 (apfs, sealed, local, journaled, nobrowse)
```
which is the very similar (noted absence of leading `/` in device path, but that is unrelated as to information we care about) format as on FreeBSD, e.g.

```
$ mount | grep BIDS
inbox/BIDS on /inbox/BIDS (zfs, NFS exported, local, nfsv4acls)
```

So they are different "formats" and would require different regexes/parsers to parse. We can even just go through a set of regexes we know, and thus possibly make it just work even if `mount` comes from different implementations (i.e. not make it platform specific in deciding which parser to use).

**Comment by adswa** [comment]
It looks like ``psutil``'s ``disk_partitions`` is a more cross-platform compatible solution? https://psutil.readthedocs.io/en/latest/index.html?highlight=disk%20usage#disks

**Comment by yarikoptic** [comment]
nice find @adswa !
