### ISSUE TITLE
GitRepo pre-init sanity checks invalid

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6296]
`GitRepo.init()` uses `ls-files` to check for conflicting content in a parent repo whenever the target dir already exists. However, that check is invalid, because this does the equivalent of the following:

```
/tmp/grh (git)-[master] % mkdir -p /tmp/grh/subgit
/tmp/grh (git)-[master] % git -C /tmp/grh/subgit ls-files
.datalad/.gitattributes
.datalad/config
.gitattributes
/tmp/grh (git)-[master] % ls -la /tmp/grh/subgit
total 8
drwxrwxr-x 2 mih mih 4096 Dec 10 09:26 ./
drwxrwxr-x 6 mih mih 4096 Dec 10 09:26 ../
```

`ls-files` reports conflicting content, seemlingly in the target dir `subgit`, but there is none. These files are in the parent directory/repo.

**Comment by christian-monch** [comment]
I cannot reproduce the described behavior locally with an empty datalad dataset at `/tmp/grh` and the described commands

**Comment by yarikoptic** [comment]
so likely to be `git` version dependent?  FWIW

<details>
<summary>copy pasteable script</summary> 

```bash
#!/bin/bash

cd "$(mktemp -d ${TMPDIR:-/tmp}/fuse-XXXXXXX)"
set -eu

datalad -l error create . 1>/dev/null

mkdir subgit

git -C $PWD/subgit ls-files
git --version

```
</details>

produces only

```
git version 2.34.1
```
so can't reproduce either

**Comment by bpoldrack** [comment]
Same here. 

@mih, what git version does give you that outcome?

**Comment by mih** [comment]
It is fine with 2.30 and 2.34, but not with 2.33, for example.

```
(datalad-dev) mih@meiner /tmp % cd grh
(datalad-dev) mih@meiner /tmp/grh (git)-[master] % git ls-files
.datalad/.gitattributes
.datalad/config
.gitattributes
(datalad-dev) mih@meiner /tmp/grh (git)-[master] % git --version
git version 2.33.0
```

**Comment by adswa** [comment]
can't reproduce this either with 2.35.2. I skimmed the release notes of Git in the 2.30-ish series briefly and did not see anything that could explain this behavior
