### ISSUE TITLE
Experince with Datalad as a backend lib

### ISSUE THREAD

**Issue by SteffenBrinckmann** [datalad/datalad#6300]
### What is the problem?

Hey, over the past 2 years I wrote a ELN framework (Pasta) that uses datalad for file-system interaction and a document database (couchDB) for metadata (I know datalad can also metadata). It uses ReactJS and many other libs for the GUI. I had a great talk with Michael H. and he suggested I report on my experience using datalad as a lib.
It was *generally great* and is now one of the more stable parts of the code (every lib has issues when first-use/installing (which function call is best?, How to make it work on Windows/Linux/macOS), but that is always the case and part of the learning of the lib)

A few mentions:
- datalad.create(path,description=description): produces some progress bars and output which might not fit to the layout of the app. But I tried to hide it.
- hashing function: sometimes one needs to determine the hash of a file or sym-link to find things. An exposed function that gives a git-like hash would be great. (I found a possibility, but a generic function would simplify the code)
- locking of files is one of the great features of datalad. But it makes the file handling a little more troublesome (if file locked, then     ..) and complicates the file removal [as intended]. Perhaps one can lock/unlock entire datasets?
- dataset save works as intended and great, no need to change
- datalad.support.annexrepo.status is for my feeling the most helpful status (If I remember correctly, datalad.status gives output to the terminal)
- .gitignore & .gitattributes are working great, each dataset needs them. Is it possible to define a global set of .git* and those are used?

P.S. since I am so satisfied with datalad, I run an older version 0.13, so some of my comments might not be applicable anymore. I am in the process of evaluating the most recent version.

**Comment by mih** [comment]
Thank you @SteffenBrinckmann -- this is really helpful! I will try to provide a few hints re the points you brought up. I guess all of them are evidence for the need to improve documentation in these areas:

> datalad.create(path,description=description): produces some progress bars and output which might not fit to the layout of the app. But I tried to hide it.

There is a config switch `datalad.ui.progressbar` that can be used to turn any progress bars off. If you install the https://github.com/mih/datalad-mihextras it provides a n `x-configuration` command that lists all such switches. Setting `datalad.ui.progressbar=none` should turn them off (any switch can also be set with a corresponding env var. `DATALAD_UI_PROGRESSBAR=none` in this case.

> hashing function: sometimes one needs to determine the hash of a file or sym-link to find things. An exposed function that gives a git-like hash would be great. (I found a possibility, but a generic function would simplify the code)

It sounds as if `datalad.support.digests` could be what you are looking for.

> Perhaps one can lock/unlock entire datasets?

There is *adjusted mode*. It is pretty much a full dataset in unlocked mode. `git annex adjust --unlock`. This is the default mode on all special-needs file systems, such as NTFS, FAT, ...

> datalad.support.annexrepo.status is for my feeling the most helpful status (If I remember correctly, datalad.status gives output to the terminal)

Both are actually calling the same code. However, the top-level commands, are meant to be used primarily, and aspecially the core commands (save, run, status, diff, create) are given special considerations re long-term API stability. For your case it is worth mentioning that all commands can turn any result rendering off by giving the `result_renderer='disabled'` argument to their calls.

> .gitignore & .gitattributes are working great, each dataset needs them. Is it possible to define a global set of .git* and those are used?

Are you referring to some kind of template to be used for new datasets? In that case, it is worth looking into `git init --template ...`. Any such `git-init` argument can be directly given to `datalad create` too, so could be used in the same fashion as with `git-init`. However, I am not aware of any such usage with datalad. I would be interested in exploring this option, in case this is what you were thinking of.

**Comment by SteffenBrinckmann** [comment]
MUCH THANKS, really beneficial

**Comment by yarikoptic** [comment]
Congrats @SteffenBrinckmann - this issue is on the top of the ["most popular"](https://github.com/datalad/datalad/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) ones  in DataLad ATM.  Since it was filed lots of changes were introduced some like https://github.com/datalad/datalad/pull/6213  to improve use of DataLad as a library. @mih has provided some responses above, and I thus would consider original concerns addressed, and will close this issue.  If you feel like some aspects are yet to be addressed -- feel free to file new dedicated issues.
