### ISSUE TITLE
datalad 0.15.4 `setup_package()` broken on windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6335]
This is with the current release of datalad, observed in the mihextras tests.

```
Traceback (most recent call last):
527  File "<string>", line 1, in <module>
528  File "C:\Python39-x64\lib\multiprocessing\spawn.py", line 116, in spawn_main
529    exitcode = _main(fd, parent_sentinel)
530  File "C:\Python39-x64\lib\multiprocessing\spawn.py", line 126, in _main
531    self = reduction.pickle.load(from_parent)
532  File "C:\Python39-x64\lib\site-packages\datalad\__init__.py", line 50, in <module>
533    from .log import lgr
534  File "C:\Python39-x64\lib\site-packages\datalad\log.py", line 579, in <module>
535    lgr = LoggerHelper().get_initialized_logger()
536  File "C:\Python39-x64\lib\site-packages\datalad\log.py", line 560, in get_initialized_logger
537    ColorFormatter(use_color=use_color,
538  File "C:\Python39-x64\lib\site-packages\datalad\log.py", line 154, in __init__
539    msg = colors.format_msg(self._get_format(log_name, log_pid),
540  File "C:\Python39-x64\lib\site-packages\datalad\support\ansi_colors.py", line 64, in format_msg
541    if color_enabled() and use_color:
542  File "C:\Python39-x64\lib\site-packages\datalad\support\ansi_colors.py", line 57, in color_enabled
543    ui_color = cfg.obtain('datalad.ui.color')
544  File "C:\Python39-x64\lib\site-packages\datalad\config.py", line 488, in obtain
545    from datalad.interface.common_cfg import definitions as cfg_defs
546  File "C:\Python39-x64\lib\site-packages\datalad\interface\common_cfg.py", line 519, in <module>
547    compute_cfg_defaults()
548  File "C:\Python39-x64\lib\site-packages\datalad\interface\common_cfg.py", line 516, in compute_cfg_defaults
549    value['default'] = def_fn()
550  File "C:\Python39-x64\lib\site-packages\datalad\interface\common_cfg.py", line 105, in <lambda>
551    'default_fn': lambda: dirs.user_cache_dir,
552  File "C:\Python39-x64\lib\site-packages\appdirs.py", line 439, in user_cache_dir
553    return user_cache_dir(self.appname, self.appauthor,
554  File "C:\Python39-x64\lib\site-packages\appdirs.py", line 293, in user_cache_dir
555    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
556  File "C:\Python39-x64\lib\site-packages\appdirs.py", line 481, in _get_win_folder_with_pywin32
557    dir = shell.SHGetFolderPath(0, getattr(shellcon, csidl_name), 0, 0)
558pywintypes.com_error: (-2147024893, 'The system cannot find the path specified.', None, None)
```

**Comment by adswa** [comment]
With `appdirs` still being used, this is before #6198 and also #6260, right?
Its a weird behavior change, because that state should be the default mode of operation that datalad has been running tests under Windows on for the longest time. When I previously debugged this in https://github.com/datalad/datalad/issues/6160, I found that the query for a ``CSIDL`` would return "none" instead of raising an Error. This "none" would be interpreted as ``.`` by ``normpath``. However, I can't remember anymore which of the many ways possible (ctypes, pywintypes, environment, ..., each in their own ``_get_win_folder_with_xyz`` method) it used to detect the path.

I also found that pywin32 and ``_get_win_folder_with_pywin32`` that is used in the traceback above has been removed from the most recent version of appdirs (May 2020, v1.4.4): https://github.com/ActiveState/appdirs/commit/d1828cf05ac6243c12036f7fa0132992b86d8c83 - I wonder why it wouldn't install the most recent version on Appveyor? At least in the main datalad repo, there was no appdirs version requirement when we still had it in setup.py

**Comment by adswa** [comment]
actually, it might be similar to https://github.com/datalad/datalad/issues/5806 - an issue with an undetermined root cause that resolved itself after a reinstall

**Comment by mih** [comment]
Debugging on appveyor... This is only happening within `nose` nowhere else -- a plain `import datalad` works just fine.

Moreoever, the traceback output is not coincidental with an immediate crash. That happens later .... about 5min later, which made me really read the rest of the output:

```
...
  File "C:\Python39-x64\lib\site-packages\datalad\__init__.py", line 232, in setup_package
569    test_http_server.start()
570  File "C:\Python39-x64\lib\site-packages\datalad\tests\utils.py", line 636, in start
571    port = queue.get(timeout=300)
572  File "C:\Python39-x64\lib\multiprocessing\queues.py", line 114, in get
573    raise Empty
574
```

and indeed, when I comment out the starting of the HTTP server, the tests run. So the error output was completely misleading. 

Trying this part manually, a normal:

```py
>>> from datalad.tests.utils import HTTPPath
>>> from datalad import cfg
>>> import tempfile
>>> serve_path = tempfile.mkdtemp(dir=cfg.get("datalad.tests.temp.dir"), prefix='httpserve')
>>> test_http_server = HTTPPath(serve_path)
>>> test_http_server.start()
```

works fine -- which is the code that runs in `setup_package()`. So the problem must come from the general environment inside `setup_package()`. And indeed:

```py
C:\projects\datalad-mihextras>python
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import datalad
>>> datalad.setup_package()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python39-x64\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
...
```

When I upgrade datalad to the current mainline snapshot `datalad 0.15.4+520.gf3cbb0cc7` the issue goes away.

I suspect this might be related to the olden ways of setting up a fake HOME. It is unclear to me, though, why this behavior would show only now.

**Comment by yarikoptic** [comment]
bisect to what fixed it in master?

**Comment by mih** [comment]
We changed the entire HOMEDIR setup, in part because of issues on windows.

**Comment by mih** [comment]
Given that this issue only affects 0.15, and nobody is likely to address it with the upcoming 0.16 release, I will close it now.
