### ISSUE TITLE
BatchedCommand might stall under certain conditions

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad#6340]
### What is the problem?

This is related to issue https://github.com/datalad/datalad-metalad/issues/196, in datalad-metalad. During the test of batched-add, BatchedCommand stalls on Linux and MacOS in certain configurations

This has to be investigated and resolved before the release.

### Datalad information

master-branch, commit: 2b92a764fdc64b750dad68eb51c817218a1ec153

**Comment by yarikoptic** [comment]
any detail on "certain conditions"?

**Comment by christian-monch** [comment]
Sorry, not yet. It works in a number of scenarios and does not work in some others. The same code works when executed from pycharm, but does not work when executed via `python -m nose ...`. I don't know why that is the case yet.

**Comment by christian-monch** [comment]
On some Linux systems, e.g. my dev-system, I don't see the problem at all. Maybe it is related to the behavior of an externally called process (which is done a lot on some imports) and re-used of an improper cleaned-up object. But that is wild speculation

**Comment by christian-monch** [comment]
Stalling was caused by missing flush()-calls in meta-add. Fixed in datalad-metalad commit cf9b5f1aa6913c9acc49ed719ff69e34e487e25e.

The error was hidden in environments that automatically flushed stdout streams. So BatchedCommand is no suspect anymore.

**Comment by christian-monch** [comment]
Fixed by PR [datalad/datalad-metalad #197](https://github.com/datalad/datalad-metalad/pull/197)
