### ISSUE TITLE
Maintenance teams coordination

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6365]
DataLad has an old, large, and complex code base. Maintaining "all of it" is not a simple task. In order to achieve a more sustainable maintenance model, we attempt to split this hard problem into smaller more manageable task.

We chose to distinguish particular aspects of DataLad's functionality, each corresponding to parts of the code base in this repository. The aim is to have a minimum of two developers take on the responsibility to maintain the respective implementations, process and fix issues, and aim to improve overall code quality and performance. Pairing of developers with different levels of prior experience is highly encouraged, in order to facilitate expertise transfer.

This sign-up is not exclusive -- everyone is of course welcome to work on any aspects at all times. However, the maintenance team of an area is expected to respond to any issue, review any PR that falls into their area, and pro-actively improve robustness, user experience, documentation, and performance of the code. There is no expectation that the association of developers and areas remains constant over time.

- `core`: core API/commands
  - @mih
  - @adswa
  - @christian-monch  
  - @yarikoptic 
  - ...
- `git`: Git interface (e.g. `GitRepo`, protocols, helpers, compatibility)
  - @mih
  - @bpoldrack
  -  @christian-monch 
  - @yarikoptic  
  - ...
- `gitannex`: git-annex interface (e.g. `AnnexRepo`, protocols, helpers, compatibility)
  - @mih
  - @bpoldrack 
  - @yarikoptic 
  - ...
- `remotes`: (special) remote implementations
  - @bpoldrack  
  - @yarikoptic 
  - ...
- `runner`: sub-process execution and IO
  - @christian-monch 
  - ...
- `services`: interaction with 3rd-party services (`create-sibling*`, downloaders, credentials, etc.)
  - @adswa 
  - @mslw 
  - @jsheunis 
  - @yarikoptic 
  - ...

Each area has a corresponding `team-<area>` tag that can be used to associate individual issues/PRs with an area.

(please edit the top comment, rather than posting responses to this issue)

**Comment by adswa** [comment]
@yarikoptic which teams are you in? ;-)

**Comment by yarikoptic** [comment]
FWIW, embedded myself ;-)

**Comment by adswa** [comment]
I believe that the information in this document could migrate into either ``CONTRIBUTING`` or ``README``. This issue is quite buried and not easily findable, but served the purpose of creating teams. Exposing the information here in other files might make the practice of label assignments or tagging responsible teams less hidden insider knowledge.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.0`](https://github.com/datalad/datalad/releases/tag/0.18.0)
