### ISSUE TITLE
Getting coverage records from subprocesses

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6367]
This is a big hole in our current setup, I think. Stuff like the CLI, special remotes, and remote helpers fly under the radar.

But it seems this does not have to be the case: https://coverage.readthedocs.io/en/coverage-3.5.3/subprocess.html

**Comment by yarikoptic** [comment]
we have (or had) coverage for datalad git-annex special remotes in https://github.com/datalad/datalad/blob/HEAD/.travis.yml#L239 which adjusts PATH to point to our shims https://github.com/datalad/datalad/tree/HEAD/tools/coverage-bin and then we merge all coverage reports https://github.com/datalad/datalad/blob/HEAD/.travis.yml#L253 before submitting.
