### ISSUE TITLE
get_subdatasets (or to say GitPython's get_submodules) bails too early

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#637]
one of our datasets has a subdataset which doesn't yet have any data. git submodules just happily lists everyone but the problematic one.  our get_subdatasets **quietly** returns an empty list, because inside it catches exception thrown  by GitPython (as even the comment there says).  This makes it really fragile and any logic dependent on knowing the list of subdatasets perform incorrectly.  Needs to be addressed one way or another

**Comment by bpoldrack** [comment]
What exactly do you mean by "doesn't yet have any data"? There is no commit at all or just no checkout? Are you calling `get_subdatasets` with parameter `fullfilled=False`? What about `recursive`?

**Comment by yarikoptic** [comment]
Actually situation was more ad hoc and I would need to try to reproduce it first exactly

**Comment by mih** [comment]
Let's close this for now.
