### ISSUE TITLE
Revert #6381 after CLI is merged.

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6384]
It is only necessary to estimate any runtime impact of the new CLI setup. Its quality has been questioned, so let's remove it afterwards.

https://github.com/datalad/datalad/pull/6381

**Comment by mih** [comment]
@yarikoptic please let me know whether you would prefer to keep the extended set of CLI benchmarks, or if I shall post a PR to trim back to their previous collection.

If such a PR comes, I'll also use the opportunity to kill all the other benchmarks that continue to fail on every run.

**Comment by yarikoptic** [comment]
I love seeing more benchmarks, so I do not see the need to trim.  I would keep the original `--help-np` in `core` (IIRC) so if we get to reestablish historical benchmarking we have continuity.

As for killing failing ones -- those indeed need to be either fixed, disabled (if possible conditioning on version), or killed. IMHO it is a separate issue.

**Comment by mih** [comment]
Ok, closing then. Thx
