### ISSUE TITLE
Weird [INFO][WARNING] messages emitted by clone

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#6395]
I've recently started to see weird ` [INFO][WARNING]`` messages like this during cloning:

```
(handbook2) adina@muninn in /tmp
❱ datalad clone git@github.com:adswa/windowstesting.git mimimi
[INFO   ] Unable to parse git config from origin                                                                  
[INFO   ] [WARNING] Unknown instance class: <class '_io.BufferedRandom'>, assuming file-like input: <_io.BufferedRandom name=3> 
[INFO   ] [WARNING] Unknown instance class: <class '_io.TextIOWrapper'>, assuming file-like input: <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'> 
[INFO   ] Remote origin does not have git-annex installed; setting annex-ignore 
[INFO   ] This could be a problem with the git-annex installation on the remote. Please make sure that git-annex-shell is available in PATH when you ssh into the remote. Once you have fixed the git-annex installation, run: git annex enableremote origin 
install(ok): /tmp/mimimi (dataset)
```

``debug`` says that they originate from the stderr of a git clone call:

```
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'clone', '--progress', 'git@github.com:adswa/windowstesting.git', '/tmp/mimimimi'] (cwd=None) 
[DEBUG  ] Non-progress stderr: b"Cloning into '/tmp/mimimimi'...\n"                                               
[DEBUG  ] Non-progress stderr: b"[WARNING] Unknown instance class: <class '_io.BufferedRandom'>, assuming file-like input: <_io.BufferedRandom name=3> \n" 
[DEBUG  ] Non-progress stderr: b"[WARNING] Unknown instance class: <class '_io.TextIOWrapper'>, assuming file-like input: <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'> \n" 
[DEBUG  ] Non-progress stderr: b' \r'                                                                             
[DEBUG  ] Non-progress stderr: b'remote: Total 43 (delta 8), reused 42 (delta 7), pack-reused 0        \n'        
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'clone', '--progress', 'git@github.com:adswa/windowstesting.git', '/tmp/mimimimi'] with status 0                                                                     
[DEBUG  ] Git clone completed                                         
```

I suspect whatever runs this clone call has gotten suboptimal inputs/parameters.

**Comment by adswa** [comment]
More data: It seems to be specific to DataLads SSH run
```
(handbook2) adina@muninn in /tmp
❱ GIT_SSH_COMMAND="datalad sshrun" git clone git@github.com:adswa/windowstesting.git d    
Cloning into 'd'...
[WARNING] Unknown instance class: <class '_io.BufferedRandom'>, assuming file-like input: <_io.BufferedRandom name=3> 
[WARNING] Unknown instance class: <class '_io.TextIOWrapper'>, assuming file-like input: <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'> 
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 43 (delta 8), reused 42 (delta 7), pack-reused 0
Receiving objects: 100% (43/43), 4.95 KiB | 1.65 MiB/s, done.
Resolving deltas: 100% (8/8), done.
```

**Comment by adswa** [comment]
and more debug output:

```
[DEBUG] MultiplexSSHConnection(ctrl_path=<<PosixPath('/ho++38 chars++de')>>, sshri=<<SSHRI(hostname++26 chars++it')>>) is used to run ['ssh', '-o', 'ControlPath=/home/adina/.cache/datalad/sockets/56827dde', 'git@github.com', "git-upload-pack 'adswa/windowstesting.git'"] 
[DEBUG] Run ['ssh', '-o', 'ControlPath=/home/adina/.cache/datalad/sockets/56827dde', 'git@github.com', "git-upload-pack 'adswa/windowstesting.git'"] (cwd=None) 
[WARNING] Unknown instance class: <class '_io.TextIOWrapper'>, assuming file-like input: <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'> 
[Level 8] Process 910057 started 
[Level 5] process_waiter (Thread<process_waiter>) started 
```

**Comment by adswa** [comment]
maybe @christian-monch has an idea here?

**Comment by yarikoptic** [comment]
is that on `master`, what version of `ssh`? (`datalad wtf -D html_details`?)

**Comment by adswa** [comment]
> is that on `master`, what version of `ssh`? (`datalad wtf -D html_details`?)

today's ``master``. 
<details><summary>DataLad 0.15.4+575.g5193deb86.dirty WTF (configuration, credentials, datalad, dependencies, environment, extensions, git-annex, location, metadata_extractors, metadata_indexers, python, system)</summary>

# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - SecretService Keyring
      - PlaintextKeyring with no encyption v.1.0 at /home/adina/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/adina/.config/python_keyring/keyringrc.cfg
    - data_root: /home/adina/.local/share/python_keyring
## datalad 
  - version: 0.15.4+575.g5193deb86.dirty
## dependencies 
  - annexremote: 1.4.5
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20211123
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.34.1
  - cmd:system-git: 2.34.1
  - cmd:system-ssh: 8.7p1
  - exifread: 2.3.2
  - git: 3.1.12
  - gitdb: 4.0.5
  - humanize: 3.2.0
  - iso8601: 0.1.13
  - keyring: 21.8.0
  - keyrings.alt: 4.0.2
  - msgpack: 1.0.2
  - mutagen: 1.45.1
  - platformdirs: 2.4.0
  - requests: 2.25.1
  - scrapy: 2.5.1
## environment 
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US.UTF-8
  - LC_ALL: en_US.UTF-8
  - LC_CTYPE: en_US.UTF-8
  - PATH: /home/adina/env/handbook2/bin:/home/adina/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/local/games:/usr/games:/home/adina/.local/bin:/home/adina/bin:/snap/bin:/home/adina/repos/latexrun/:/home/adina/node_modules/.bin
## extensions 
  - container: 
    - description: Containerized environments
    - entrypoints: 
      - datalad_container.containers_add.ContainersAdd: 
        - class: ContainersAdd
        - load_error: None
        - module: datalad_container.containers_add
        - names: 
          - containers-add
          - containers_add
      - datalad_container.containers_list.ContainersList: 
        - class: ContainersList
        - load_error: None
        - module: datalad_container.containers_list
        - names: 
          - containers-list
          - containers_list
      - datalad_container.containers_remove.ContainersRemove: 
        - class: ContainersRemove
        - load_error: None
        - module: datalad_container.containers_remove
        - names: 
          - containers-remove
          - containers_remove
      - datalad_container.containers_run.ContainersRun: 
        - class: ContainersRun
        - load_error: None
        - module: datalad_container.containers_run
        - names: 
          - containers-run
          - containers_run
    - load_error: None
    - module: datalad_container
    - version: 1.1.2
  - deprecated: 
    - description: Deprecated functionality
    - entrypoints: 
      - datalad_deprecated.annotate_paths.AnnotatePaths: 
        - class: AnnotatePaths
        - load_error: None
        - module: datalad_deprecated.annotate_paths
        - names: 
      - datalad_deprecated.ls.Ls: 
        - class: Ls
        - load_error: None
        - module: datalad_deprecated.ls
        - names: 
      - datalad_deprecated.publish.Publish: 
        - class: Publish
        - load_error: None
        - module: datalad_deprecated.publish
        - names: 
    - load_error: None
    - module: datalad_deprecated
    - version: 0.1+47.g03f8b11
  - metalad: 
    - description: DataLad semantic metadata command suite
    - entrypoints: 
      - datalad_metalad.aggregate.Aggregate: 
        - class: Aggregate
        - load_error: None
        - module: datalad_metalad.aggregate
        - names: 
          - meta-aggregate
          - meta_aggregate
      - datalad_metalad.dump.Dump: 
        - class: Dump
        - load_error: None
        - module: datalad_metalad.dump
        - names: 
          - meta-dump
          - meta_dump
      - datalad_metalad.extract.Extract: 
        - class: Extract
        - load_error: None
        - module: datalad_metalad.extract
        - names: 
          - meta-extract
          - meta_extract
    - load_error: None
    - module: datalad_metalad
    - version: 0.2.1
  - mihextras: 
    - description: MIH's DataLad extras
    - entrypoints: 
      - datalad_mihextras.configuration.Configuration: 
        - class: Configuration
        - load_error: None
        - module: datalad_mihextras.configuration
        - names: 
          - x-configuration
          - x_configuration
      - datalad_mihextras.export_to_webdav.ExportToWEBDAV: 
        - class: ExportToWEBDAV
        - load_error: None
        - module: datalad_mihextras.export_to_webdav
        - names: 
          - x-export-to-webdav
          - x_export_to_webdav
      - datalad_mihextras.snakemake.SnakeMake: 
        - class: SnakeMake
        - load_error: None
        - module: datalad_mihextras.snakemake
        - names: 
          - x-snakemake
          - x_snakemake
    - load_error: None
    - module: datalad_mihextras
    - version: 0.4.1
  - neuroimaging: 
    - description: Neuroimaging tools
    - entrypoints: 
      - datalad_neuroimaging.bids2scidata.BIDS2Scidata: 
        - class: BIDS2Scidata
        - load_error: None
        - module: datalad_neuroimaging.bids2scidata
        - names: 
          - bids2scidata
    - load_error: None
    - module: datalad_neuroimaging
    - version: 0.3.1
  - osf: 
    - description: DataLad extension for OSF support
    - entrypoints: 
      - datalad_osf.create_sibling_osf.CreateSiblingOSF: 
        - class: CreateSiblingOSF
        - load_error: None
        - module: datalad_osf.create_sibling_osf
        - names: 
          - create-sibling-osf
          - create_sibling_osf
      - datalad_osf.credentials.OSFCredentials: 
        - class: OSFCredentials
        - load_error: None
        - module: datalad_osf.credentials
        - names: 
          - osf-credentials
          - osf_credentials
    - load_error: None
    - module: datalad_osf
    - version: 0.2.3.1+10.g38a4375
  - webapp: 
    - description: Generic web app support
    - entrypoints: 
      - datalad_webapp.WebApp: 
        - class: WebApp
        - load_error: None
        - module: datalad_webapp
        - names: 
          - webapp
          - webapp
    - load_error: None
    - module: datalad_webapp
    - version: 0.3
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20211123
## location 
  - path: /home/adina
  - type: directory
## metadata_extractors 
  - annex (datalad 0.15.4+575.g5193deb86): 
    - distribution: datalad 0.15.4+575.g5193deb86
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.4+575.g5193deb86): 
    - distribution: datalad 0.15.4+575.g5193deb86
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - bids (datalad-neuroimaging 0.3.1): 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.bids
    - version: None
  - datacite (datalad 0.15.4+575.g5193deb86): 
    - distribution: datalad 0.15.4+575.g5193deb86
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.4+575.g5193deb86): 
    - distribution: datalad 0.15.4+575.g5193deb86
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.4+575.g5193deb86): 
    - distribution: datalad 0.15.4+575.g5193deb86
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - dicom (datalad-neuroimaging 0.3.1): 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.dicom
    - version: None
  - exif (datalad 0.15.4+575.g5193deb86): 
    - distribution: datalad 0.15.4+575.g5193deb86
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage (datalad 0.15.4+575.g5193deb86): 
    - distribution: datalad 0.15.4+575.g5193deb86
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.4+575.g5193deb86): 
    - distribution: datalad 0.15.4+575.g5193deb86
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - metalad_annex (datalad-metalad 0.2.1): 
    - distribution: datalad-metalad 0.2.1
    - load_error: None
    - module: datalad_metalad.extractors.annex
    - version: None
  - metalad_core (datalad-metalad 0.2.1): 
    - distribution: datalad-metalad 0.2.1
    - load_error: None
    - module: datalad_metalad.extractors.core
    - version: None
  - metalad_custom (datalad-metalad 0.2.1): 
    - distribution: datalad-metalad 0.2.1
    - load_error: None
    - module: datalad_metalad.extractors.custom
    - version: None
  - metalad_runprov (datalad-metalad 0.2.1): 
    - distribution: datalad-metalad 0.2.1
    - load_error: None
    - module: datalad_metalad.extractors.runprov
    - version: None
  - nidm (datalad-neuroimaging 0.3.1): 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.nidm
    - version: None
  - nifti1 (datalad-neuroimaging 0.3.1): 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.nifti1
    - version: None
  - xmp (datalad 0.15.4+575.g5193deb86): 
    - distribution: datalad 0.15.4+575.g5193deb86
    - load_error: None
    - module: datalad.metadata.extractors.xmp
    - version: None
## metadata_indexers 
## python 
  - implementation: CPython
  - version: 3.9.9
## system 
  - distribution: debian/11-updates/n/a
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 267
  - name: Linux
  - release: 5.15.0-2-amd64
  - type: posix
  - version: #1 SMP Debian 5.15.5-2 (2021-12-18)
</details>
        
> hint: you could run with DATALAD_LOG_TRACEBACK=10 and get traceback for each log message -- might be of help to identify location/reason for those WARNINGs

```
❱ DATALAD_LOG_TRACEBACK=10 GIT_SSH_COMMAND="datalad sshrun" git clone git@github.com:adswa/windowstesting.git h                                                                                                                  128 !
Cloning into 'h'...
[WARNING] ...>exec:105>sshrun:119>sshconnector:468,160,151,277,468,175>runner:184>nonasyncrunner:315  Unknown instance class: <class '_io.BufferedRandom'>, assuming file-like input: <_io.BufferedRandom name=3> 
[WARNING] datalad:33>main:131,151>exec:105>sshrun:119>sshconnector:468,175>runner:184>nonasyncrunner:315  Unknown instance class: <class '_io.TextIOWrapper'>, assuming file-like input: <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'> 
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 43 (delta 8), reused 42 (delta 7), pack-reused 0
Receiving objects: 100% (43/43), 4.95 KiB | 1.65 MiB/s, done.
Resolving deltas: 100% (8/8), done.
```

**Comment by adswa** [comment]
ping @christian-monch for ideas?

**Comment by christian-monch** [comment]
> ping @christian-monch for ideas?

thanks for the ping. On it

**Comment by christian-monch** [comment]
Thanks for the catch. The warning is unnecessary, I removed it. It indicated that the `stdin` argument to the runner was not an instance of the classes that are specially treated, e.g. `string` or `queue.Queue`. PR is on its way
