### ISSUE TITLE
Website/docs: add github star banner?

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#6423]
The handbook has a GitHub stars banner in the sidebar, rendering 
[the number of GitHub stars](https://ghbtns.com/github-btn.html?repo=datalad&user=datalad&type=star&count=true&size=large) of the project and allowing to add a star via a click. Maybe nice to have for the docs or the website as well?

**Comment by jsheunis** [comment]
Tracked here for the website: https://github.com/datalad/datalad.org/issues/110

**Comment by mih** [comment]
![image](https://user-images.githubusercontent.com/136479/154953816-8208a11e-a7b4-432b-b8e6-0947f2c02d5e.png)

Thx!
