### ISSUE TITLE
`run` ignores its own input spec error and proceeds

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6427]
```
% datalad run -i bogus "echo 123 > mike2"
[INFO   ] Making sure inputs are available (this may take some time) 
run(error): /tmp/runny (dataset) [Input did not match existing file: bogus]
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) ===== 
add(ok): mike2 (file)                                                                                                       
save(ok): . (dataset)  
-> exit 1                                                                                                     
```

I would argue that if I explicitly specify an input, I rely on `run` to actually deliver the file content. From the docs:

> A dependency for the run. Before running the command, the content of this file will be retrieved.

Complaining about it, but then still executing the command, and modifying the dataset is unlikely to be desired in the use cases that I can come up with.

A possible resolution of #6426 would allow `run` to declare `on_failure=stop` as its default behavior. But until that is possible, it might be the best to stop processing unconditionally.

This issue is not an unresolvable thread to reliability, because the command does eventually fail, but it is easy to go unnoticed. Even with `--explicit` the input declaration has no impact on the command execution.

`rerun` behaves in a similar fashion when operating on such an invalid run-record. It shows an error message, proceeds, and eventually exits non-zero.

For the analog situation of an invalid `--output` declaration there is https://github.com/datalad/datalad/issues/3449 -- calling for a warning.

Taken together, the current implementation conceptualizes `--input` as a nice-to-have and hope-your-script has `set -e` "dependency". It seems a previous report concluded in a similar fashion https://github.com/datalad/datalad/issues/5583

Critical input from @kyleam is at https://github.com/datalad/datalad/commit/91d63ef455f8a7457224e57215b35e847cc5ccf9 thx! Seem to point into a similar direction.

**Comment by bpoldrack** [comment]
All cases I can think of where it's desirable to have something specified in the record that may or may not be there, seem covered by being able to specify (and not expand in the record) globs.

So - just yielding `impossible` seems reasonable to me.

**Comment by mih** [comment]
I have implemented a fix for this issue.
