### ISSUE TITLE
Re #541 web face:  make directories proper <A> links

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#644]
now they seems to be handled within javascript, instead of being just a url to a subdirectory.  This prohibits efficient navigation in extensions (e.g. vimium) relying on observing the links, etc.
Imho pretty much entire row could be the "link" to the subdirectory/file/whatever

**Comment by debanjum** [comment]
Interesting, it works fine with VimFX on Firefox.

**Comment by debanjum** [comment]
fixed in 4e1c300
