### ISSUE TITLE
Something introduced widespread double reporting of results

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#6445]
I noticed in #6258 that some commands result rendering contains duplicate entries. For example, this is the output of ``clone`` to clone a subdataset on current ``master``:

```
(handbook2) adina@muninn in /tmp/ab on git:master
❱ datalad clone -d . https://gin.g-node.org/adswa/bids-data input15             
install(ok): input15 (dataset)                                                  
add(ok): input15 (file)                                                         
add(ok): input15 (file)                                                         
add(ok): .gitmodules (file)                                                     
add(ok): .gitmodules (file)                                                     
save(ok): . (dataset)                                                           
save(ok): . (dataset)                                                           
add(ok): .gitmodules (file)                                                     
save(ok): . (dataset)                                                           
add(ok): .gitmodules (file)                                                     
save(ok): . (dataset)
```

This specific flood of results seems to be due to ``save`` -  a previous not set ``result_renderer='disabled'`` became necessary. 
#6421, for example, already added one to fix up the duplicate result rendering of ``run`` a few days ago. While its not confusing that ``result_renderer='disabled'`` would need to be set, its confusing to me why it only now showed the double-reporting and this was not observed before.

I tried to bisect this change, but due to the changes in CLI this proved to be quite difficult - I couldn't evaluate good or bad bisection states for some commits because at one point, result rendering was completely turned off, or because in one state result rendering led to internal errors. The outcome of this bisection is thus not really trustworthy in my opinion:

```
(handbook2) adina@muninn in ~/repos/datalad on bisect/bad~1 (bisect)
❱ git bisect bad 
83c9270305778884b6a480ef7c0875811d44948d is the first bad commit
commit 83c9270305778884b6a480ef7c0875811d44948d
Author: Michael Hanke <michael.hanke@gmail.com>
Date:   Sat Jan 29 13:24:36 2022 +0100

    Deprecate datalad.interface.common_opts.eval_defaults
    
    The default are more productively put into the Interface class directly.
    The makes the documentation more accessible, makes more obvious where
    overrides need to go, reduces the number of places that need to be
    queried in order to determine the effective value.

 datalad/cli/common_args.py       | 7 ++-----
 datalad/cli/tests/test_exec.py   | 2 +-
 datalad/interface/base.py        | 5 +++--
 datalad/interface/common_opts.py | 6 ++++++
 datalad/interface/utils.py       | 7 +------
 5 files changed, 13 insertions(+), 14 deletions(-)
```

Likely independent of ``save``, ``datalad install`` also does double reporting:

```
(handbook2) adina@muninn in /tmp/ab on git:master
❱ datalad uninstall input15
uninstall(ok): input15 (dataset)                                                
(handbook2) adina@muninn in /tmp/ab on git:master
❱ datalad install input15 
install(ok): /tmp/ab/input15 (dataset) [Installed subdataset in order to get /tmp/ab/input15]                                                                   
install(ok): /tmp/ab/input15 (dataset) [Installed subdataset in order to get /tmp/ab/input15]
```

**Comment by adswa** [comment]
Oh. This only happens on ``master`` and not on ``maint``

**Comment by mih** [comment]
There were a series of changes that could all have impacted this

- #6394
- #6391

and possibly more. It is hard to tell what it was specifically, and there is no desire to undo it it also. The effective behavior of the result rendering before these changes, and to some degree even now, is a complex interaction of side-effects of switches that should rather be independent of each other. Further simplifying, documenting and testing is the only sensible way forward IMHO.
