### ISSUE TITLE
(Special remote) authentication wrapper for specification and provisioning (of temporary) credentials

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6451]
Some special remotes require authentication and git-annex presently requires the credential provisioning to happen via an external mechanism. Some special remote implementations have such a mechanism built-in (rclone, some of our's). However, all implementations that I am aware of consider a credential to be "permanent", i.e. something that can be put into a credential store or config file.

My use case is a scenario where an auth-token is required in order to perform IO (download mostly, but could also be other types of requests). These tokens are temporary (only valid for a few hours), and have to be requested via a different set of credentials from a web-service. "Tokens" need not be normal token strings, but could also another set of login/passwd credentials -- of a similar temporary nature.

It would be instrumental, if we could provide a solution that could wrap any special remote that can be parameterized with authentication, and obtains the necessary credentials from another source. Such sources could be a credential store, or really an arbitrary process that yields whatever is necessary.

Such a mechanism could provide a generic solution to the various heterogeneous approached to credential selection and provisioning that continue to accumulate across the core package and extensions.

**Comment by yarikoptic** [comment]
yet to grasp fully, but FWIW we are already dealing (in ad-hoc fashion since they are ad-hoc AFAIK) with some "temporary tokens obtained based on auth credentials" for NDA (and probably LORIS), as could be seen setup/followed from https://github.com/datalad/datalad/blob/9bee7ee08305ab0fa13136c96884df7f4a1327fa/datalad/downloaders/credentials.py#L422:7 .

**Comment by mih** [comment]
I don't see how the credential provider alone, without integration with a special remote can be enough. How could a datalad-provided credential be put in effect for an rclone-remote based download from google cloud storage?

The last time we would see any evidence of such a request is the `git annex get` call made in `datalad get`. At that point we know little about which special remote will actually serve a download request, and we have no guarantee that we could even get any decisive information from parsing the special remote configurations (e.g., there could be multiple rclone, or webdav-type special remotes, which would all need different credentials).

**Comment by mih** [comment]
OK, then let's stick to the `webdav` special remote that git annex provides for discussion.

I have a file, it is available from two different special webdav remotes. Which layer of the code should set the *correct* `WEBDAV_USERNAME/PASSWORD` env variables, before `git-annex get` attempts obtain file content from any of them?

To me this is the exact same problem, only the means of provisioning the credential are different. Without dedicated support for remote-specific credential provisioning, a user either has to know in advance which special remote will be utilized,or a user has to provision *all* credentials for all special remotes for any request. The latter case is made easier by the approach implemented in rclone, but ultimately there is little difference conceptually -- git-annex also allows for embedding remote credentials in repository.

**Comment by mih** [comment]
https://github.com/datalad/datalad-next patches `siblings enable` to auto-deploy credentials. Support is currently limited to `webdav` special remotes, but nothing prevents (other extensions) implementing similar approaches of discovering credentials based on whichever identifying criteria.

Bottom line, there is no need or desire to implement the idea proposed here, anymore.
