### ISSUE TITLE
redo cookies storage etc

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#647]
currently implemented in https://github.com/datalad/datalad/blob/master/datalad/support/cookies.py  via shelve etc.  Kinda works but doesn't work across even python versions (Python3 can't read the one created by Python 2), so should be redone without such side effects may be through a simple cookiejar (see https://docs.python.org/2.7/library/cookielib.html)

**Comment by yarikoptic** [comment]
please submit a WiP PR so I could assess and recommend/push if necessary.  When testing, test using tox, which would run for both 2.7 and 3.4 so you could see if the same cookies storage (downloaders tests do not mock it away ATM) could be loaded/used by both

**Comment by yarikoptic** [comment]
keep in mind that it is quite likely that cookies db could possibly be opened by multiple processes...

**Comment by yarikoptic** [comment]
any progress on this one @debanjum ?  #689 had already to workaround some nasty issue opening those bloody cookies, so we better resolve it sooner than later now

**Comment by mih** [comment]
With #6506 posted, we can close this finally.
