### ISSUE TITLE
`auto` release produced 0.16.0 CHANGELOG but 0.15.5 tag

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6491]
got confused by failing test in https://github.com/datalad/datalad/pull/6459#issuecomment-1043942825 to discover that 0.16.0 changelog entry was added in

```shell
(git)lena:~datalad/datalad-master[maint]git
$> git describe ced1faf31e512efe6d2d1fc1112fe6dbb9ef9a31
0.15.4-26-gced1faf31

$> git describe --contains ced1faf31e512efe6d2d1fc1112fe6dbb9ef9a31
0.15.5~1

$> git show ced1faf31e512efe6d2d1fc1112fe6dbb9ef9a31 | grep '0\.'
+# 0.16.0 (Wed Feb 09 2022)
```

I have not done analysis of PRs on either any had some `semver-minor`  but given that tag was proper (0.15.5) I guess it is something else and possibly in our release workflow.  Meanwhile I will mitigate by manually fixing version in changelogs in `maint` and pushing directly

**Comment by jwodder** [comment]
@yarikoptic [Here's the run that did it.] (https://github.com/datalad/datalad/runs/5129711059?check_suite_focus=true)  The string "0.16.0" appears nowhere in the logs, but "0.15.5" does, many times.

**Comment by yarikoptic** [comment]
yeap, but then somehow actual CHANGELOG committed (before 6de38916b which can be found in the log) still got 0.16.0.  The only place it could be done is `/home/runner/auto shipit` I guess even though prior `/home/runner/auto shipit --dry-run --quiet` gave 0.15.5? then it must be an intuit's auto bug somehow...?

**Comment by jwodder** [comment]
@yarikoptic

> then it must be an intuit's auto bug somehow...?

Apparently, though I don't know if the developers would be able to do much since we don't have very verbose logs enabled for `auto shipit`.

**Comment by yarikoptic** [comment]
would `-v` be enough or should we go for `-vv` right away -- I would like to add it to calls to `auto` so we do end up with some logs if troubleshooting would be needed

**Comment by jwodder** [comment]
@yarikoptic [The last time the auto developers got back to me about a bug](https://github.com/intuit/auto/issues/1860), they recommended `-vv`, so we should probably go with that.

**Comment by yarikoptic** [comment]
0.15.6 was released ok.  Let's just beware to keep an eye on CHANGELOG to possibly spot another case
