### ISSUE TITLE
FOI: custom freeze/thaw'ing helpers

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6497]
decided to test those out as https://git-annex.branchable.com/todo/lockdown_hooks/ says they are already there and messing with adjusted branches is ... messy, especially whenever you are presumably on a performant file system on HPC and do not want to duplicate content etc.

Here is the reference for my initial attempt and hurdle: https://git-annex.branchable.com/bugs/can__39__t_make_annex_happy_in_freeze__47__thaw/ .  But I still hope to see the light in the end of the tunnel there.

The problem with that solution overall would be that it then would need to be configured per user (every user??) or system wide (on every system in HPC??), but then also would need to sense file system on either it actually needs that or not (some mount points might be pure POSIX and some not).  So I still don't know the best/cleanest UX to provide on those systems, but first want to make sure that freeze/thawing shims workaround works.  At worst, it just could be some "post-clone" procedure to run to configure that dataset right after `git clone` but before `git annex init`.  @mih @bpoldrack -- do we have a way to hook at that point?

edit1: I went back to more fragile "edit ACL" approach and it seems to work -- https://git-annex.branchable.com/bugs/can__39__t_make_annex_happy_in_freeze__47__thaw/#comment-02e2c8a0e65109d3fdc6bff220b4815d  .  So the question now is how to "bolt" it to DataLad's `clone`/`create` etc!?

**Comment by mih** [comment]
Here is the issue was the current state of things:

- #4903

**Comment by yarikoptic** [comment]
during week call @christian-monch suggested and I nodded in agreement that may be it is time to add "path specific" config settings, e.g.

```
[datalad "path.path-{uuid}"]
  path = /mnt/dartfs/
  pre-git-annex-init-hook = nfs4_acl
```
which would set some settings which would be path specific.  Then `ConfigManager`, for per-dataset invocation, should consult those and add them.  The overload order might be tricky to define though :-/

**Comment by mih** [comment]
Closing FOI now. Story continue in #6538
