### ISSUE TITLE
Understanding datalad save behavior and reliance on .gitattributes

### ISSUE THREAD

**Issue by lucasgautheron** [datalad/datalad#6512]
### What is the problem?

I have a `.gitattributes` file at the root of my repository, which looks like this:

```bash
* annex.backend=MD5E
**/.git* annex.largefiles=nothing
scripts/* annex.largefiles=nothing
```

A user put a bunch of files into a directory named `scripts/tt-report/`. She did `datalad save scripts/tt-report` and `datalad push`. For some reason, despite the rule in `.gitattributes`, all the files in that directory were annexed.

My two questions are: 

1. How does `datalad save` rely on `.gitattributes`? I guess the rules were incorrectly stated (anything inside of scripts/ should not be annexed, recursively). What would be the correct rule? `scripts annex.largefiles=nothing` ? `scripts/** annex.largefiles=nothing` ? or maybe `scripts/ annex.largefiles=nothing` ? What is the correct way to do this?

2. When it happens that a file is unintentionally annexed and we'd like to unannex is an version it with git instead, what is the most straightforward way to accomplish that?

Thanks for your help,

### What steps will reproduce the problem?

The steps previously described.

### Have you had any success using DataLad before?

Yes

**Comment by adswa** [comment]
Hey, sorry for leaving you waiting for a reply for so long :/ \*waves at the state of the world\*

> How does datalad save rely on .gitattributes? I guess the rules were incorrectly stated (anything inside of scripts/ should not be annexed, recursively). What would be the correct rule? scripts annex.largefiles=nothing ? scripts/** annex.largefiles=nothing ? or maybe scripts/ annex.largefiles=nothing ? What is the correct way to do this?

The notation in ``.gitattributes`` should follow Git's pattern format for `.gitignore` files: https://git-scm.com/docs/gitignore#_pattern_format
In your particular case, it would need ``scripts/**`` in order to match anything inside of scripts:
> A trailing "/**" matches everything inside. For example, "abc/**" matches all files inside directory "abc", relative to the location of the .gitignore file, with infinite depth.

Here is a quick demo:
```bash
adina@muninn in /tmp
❱ datalad create myds && cd myds
[INFO   ] Creating a new annex repo at /tmp/myds 
create(ok): /tmp/myds (dataset)
adina@muninn in /tmp/myds on git:master
❱ mkdir -p scripts/andmore
adina@muninn in /tmp/myds on git:master
❱ echo 12456 > scripts/andmore/gotogit
adina@muninn in /tmp/myds on git:master
❱ echo 'scripts/** annex.largefiles=nothing\n' >> .gitattributes       
adina@muninn in /tmp/myds on git:master!
❱ git diff
diff --git a/.gitattributes b/.gitattributes
index af926ef..ae0c2d6 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -1,2 +1,4 @@
 * annex.backend=MD5E
 **/.git* annex.largefiles=nothing
+scripts/** annex.largefiles=nothing
+
adina@muninn in /tmp/myds on git:master!
❱ datalad save   
add(ok): scripts/andmore/gotogit (file)                                         
add(ok): .gitattributes (file)                                                  
save(ok): . (dataset)                                                           
action summary:                                                                 
  add (ok: 2)
  save (ok: 1)
adina@muninn in /tmp/myds on git:master
❱ tree
.
└── scripts
    └── andmore
        └── gotogit

2 directories, 1 file
```

As for the question how to get it out of the annex I'd like to ping @yarikoptic for fact-checking, but I believe the most straight-forward way is to ``git annex unannex`` the file in question, alter the ``.gitattributes`` file, and ``save``:

```
adina@muninn in /tmp
❱ datalad create myds2 && cd myds2
[INFO   ] Creating a new annex repo at /tmp/myds2 
create(ok): /tmp/myds2 (dataset)
adina@muninn in /tmp/myds2 on git:master
❱ mkdir -p scripts/andmore
adina@muninn in /tmp/myds2 on git:master
❱ echo 12456 > scripts/andmore/gotogit                          
adina@muninn in /tmp/myds2 on git:master
❱ datalad save -m "ooops"
add(ok): scripts/andmore/gotogit (file)                                         
save(ok): . (dataset)                                                           
action summary:                                                                 
  add (ok: 1)
  save (ok: 1)
adina@muninn in /tmp/myds2 on git:master
❱ echo 'scripts/** annex.largefiles=nothing\n' >> .gitattributes
adina@muninn in /tmp/myds2 on git:master!
❱ git annex unannex scripts/andmore/gotogit 
unannex scripts/andmore/gotogit ok
(recording state in git...)
adina@muninn in /tmp/myds2 on git:master+!
❱ datalad save
add(ok): scripts/andmore/gotogit (file)                                         
add(ok): .gitattributes (file)                                                  
save(ok): . (dataset)                                                           
action summary:                                                                 
  add (ok: 2)
  save (ok: 1)
adina@muninn in /tmp/myds2 on git:master
❱ tree
.
└── scripts
    └── andmore
        └── gotogit

2 directories, 1 file
```

This is also how we documented it at http://handbook.datalad.org/en/latest/basics/101-136-filesystem.html#getting-contents-out-of-git-annex, so if @yarikoptic has something more efficient, I'd like to know to update the documentation, too. Hope this helps!

**Comment by adswa** [comment]
An alternative to ``.gitattributes`` is also a git-annex [largefiles configuration](https://git-annex.branchable.com/tips/largefiles/). Its path pattern rules are identical to those of ``.gitattributes`` above, but it supports additional criteria, such as size or filetype. In your case a configuration call would be like in this demo:

```
adina@muninn in /tmp
❱ datalad create myds3 && cd myds3
[INFO   ] Creating a new annex repo at /tmp/myds3 
create(ok): /tmp/myds3 (dataset)
adina@muninn in /tmp/myds3 on git:master
❱ mkdir -p scripts/andmore
adina@muninn in /tmp/myds3 on git:master
❱ echo 12456 > scripts/andmore/gotogit
adina@muninn in /tmp/myds3 on git:master
❱ git config annex.largefiles 'exclude=scripts/**'

adina@muninn in /tmp/myds3 on git:master
❱ datalad save
add(ok): scripts/andmore/gotogit (file)                                         
save(ok): . (dataset)                                                           
action summary:                                                                 
  add (ok: 1)
  save (ok: 1)
adina@muninn in /tmp/myds3 on git:master
❱ tree
.
└── scripts
    └── andmore
        └── gotogit

2 directories, 1 file
```

**Comment by bpoldrack** [comment]
Somewhat related: https://github.com/datalad/datalad/issues/6400. Linking here, since we may want to use the issue to come up with some better doc about `save`'s behavior.

**Comment by adswa** [comment]
I will tag this issue as "answered" and close it, but please reopen if you disagree, if there is more to clarify, or if you see the need for more documentation somewhere that goes beyond #6400. Thanks!
