### ISSUE TITLE
Determine fate of `datalad.ssh_manager`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6524]
This SSH-related code in DataLad is not cross-platform ready. Following up in https://github.com/datalad/datalad/issues/5829#issuecomment-1060640263 this is an exploration where it is actually used, to determine possible migration strategies and (hidden) failures.

In the core package, `datalad.support.sshconnector` is unused, except for an import of `SSHManager` in the top-level package in order to instantiate `ssh_manager = SSHManager()`.

The `ssh_manager` instance is used in the following four places to open SSH connections, which are subsequently used to execute remote commands.

```
datalad/distributed/create_sibling_ria.py:        ssh = ssh_manager.get_connection(
datalad/distributed/ora_remote.py:        self.ssh = ssh_manager.get_connection(
datalad/distribution/create_sibling.py:            shell = ssh_manager.get_connection(sshurl)
datalad/support/sshrun.py:        ssh = ssh_manager.get_connection(sshurl, force_ip=force_ip)
```

The only other usage is in `GitRepo`, where it is anticipating the opening of SSH connections by underlying commands, and enables connection sharing to minimize re-authentication and enable parallelization.

In particular the latter use case is broken, because this code does not allow for any interactivity in its present form (i.e. typing in ssh (key) passwords).

I wonder if any of these use cases is actually needed, and could not be replaced by calling `Dataset.sshrun()`?

No `Repo` method makes any use of `SSHManager` functionality.

`create_sibling_ria()` only makes straightup calls to `ssh`, which is exactly what `sshrun` is for.

`ora_remote` used it to open a connection and read out the parameters how it was done, in order to bypass it subsequently with a dedicated `ssh` process that it manages on its own. The exception is the execution of `scp` for `.get()` and `.put()`.

`create_sibling()` uses an opened SSH connection interchangeably with a local shell via a proxy class, again primarily for remote command execution, but also `put`.

#### Thoughts

Superficially it seems to make sense to consolidate all SSH-related functionality into dedicated commands, rather than having them fused into the core. I think two developments are needed:

- provide a slim wrapper around `scp` in a similar manner as `sshrun` wraps `ssh`
- implement a strategy to have multiple simultaneous `sshrun` command reliably create and use the same authenticated connection, likely via some kind of inter-process lock

Moreover, the present unconditional inspection of remote hosts for git-annex executables must stop and be done in layer of code that actually expect git-annex to be around.

**Comment by yarikoptic** [comment]
> I wonder if any of these use cases is actually needed, and could not be replaced by calling `Dataset.sshrun()`?

that latter of "anticipating the opening of SSH connections by underlying commands, and enables connection sharing to minimize re-authentication and enable parallelization." I thought was the main use-case that `datalad sshrun` was created for.  As it is anticipatory for any invocation of `git` which might invoke interaction with `git-annex` and where either of the two (git or git-annex) might trigger interaction with the remote -- we decided that we should preemptively establish the "ssh mux socket" IIRC.

> * provide a slim wrapper around `scp` in a similar manner as `sshrun` wraps `ssh`

we are defining `GIT_SSH_COMMAND` to point to our `datalad sshrun`, we aren't providing an `ssh` "wrapper" so I am not clear what wrapper around `scp` you have in mind, besides "overloading" `scp` and possibly `ssh` within `PATH`.  But may be that it what we should do actually? (i.e. to provide `ssh` and `scp` etc wrappers in some "private" path which we overload in PATH... so that we do not even bother establishing any socket until really asked for) 

> * implement a strategy to have multiple simultaneous `sshrun` command reliably create and use the same authenticated connection, likely via some kind of inter-process lock

We already have inter-process locking there AFAIK (both interprocess and threading):

```shell
$> git grep -n -A4 @.*locked
datalad/support/sshconnector.py:426:        # used by @fasteners.locked
datalad/support/sshconnector.py-427-        self._lock = [
datalad/support/sshconnector.py-428-            threading.Lock(),
datalad/support/sshconnector.py-429-            fasteners.process_lock.InterProcessLock(self.ctrl_path.with_suffix('.lck'))
datalad/support/sshconnector.py-430-        ]
--
datalad/support/sshconnector.py:510:    @fasteners.locked
datalad/support/sshconnector.py-511-    def open(self):
datalad/support/sshconnector.py-512-        """Opens the connection.
datalad/support/sshconnector.py-513-
datalad/support/sshconnector.py-514-        In other words: Creates the SSH ControlMaster to be used by this
```

**Comment by mih** [comment]
> > I wonder if any of these use cases is actually needed, and could not be replaced by calling `Dataset.sshrun()`?
> 
> that latter of "anticipating the opening of SSH connections by underlying commands, and enables connection sharing to minimize re-authentication and enable parallelization." I thought was the main use-case that `datalad sshrun` was created for. As it is anticipatory for any invocation of `git` which might invoke interaction with `git-annex` and where either of the two (git or git-annex) might trigger interaction with the remote -- we decided that we should preemptively establish the "ssh mux socket" IIRC.

Yes, I think so too. But if this is the case, there should be no `get_connection().open()` calls in `GitRepo`, because ultimately all SSH-based processing git and git-annex will go through `sshrun`. yet, there are a number of such calls. So they were either forgotten and complicate things needlessly, or the concept is not working.

> > * provide a slim wrapper around `scp` in a similar manner as `sshrun` wraps `ssh`
> 
> we are defining `GIT_SSH_COMMAND` to point to our `datalad sshrun`, we aren't providing an `ssh` "wrapper" so I am not clear what wrapper around `scp` you have in mind, besides "overloading" `scp` and possibly `ssh` within `PATH`. But may be that it what we should do actually? (i.e. to provide `ssh` and `scp` etc wrappers in some "private" path which we overload in PATH... so that we do not even bother establishing any socket until really asked for)

`sshrun` is a wrapper, because it presents the `ssh` API (subset) and calls `ssh`. Likewise, a similaar wrapper is needed for `scp`, because this is what `SSHConnection` does and provides internally.

> > * implement a strategy to have multiple simultaneous `sshrun` command reliably create and use the same authenticated connection, likely via some kind of inter-process lock
> 
> We already have inter-process locking there AFAIK (both interprocess and threading):
> 
> ```shell
> $> git grep -n -A4 @.*locked
> datalad/support/sshconnector.py:426:        # used by @fasteners.locked
...
> ```

Yes, my point is that is needs to move into `sshrun`. I am aware that it is being used by `sshrun` already. But it is unclear to which degree this whole business relies on `get_connection().open()` calls that *preceed* any `sshrun` call.

You seems to be suggesting that it is enough to call `sshrun`, which would be wonderful, and all residual code in elsewhere can simply be removed.

**Comment by bpoldrack** [comment]
> The only other usage is in GitRepo, where it is anticipating the opening of SSH connections by underlying commands, and enables connection sharing to minimize re-authentication and enable parallelization.

> In particular the latter use case is broken, because this code does not allow for any interactivity in its present form (i.e. typing in ssh (key) passwords).

>  there should be no get_connection().open() calls in GitRepo, because ultimately all SSH-based processing git and git-annex will go through sshrun. yet, there are a number of such calls. So they were either forgotten and complicate things needlessly, or the concept is not working.

On this aspect: I think they were forgotten. Some RF'ing was incomplete. Another indication for that is `GitRepo.__init__`, where we have:

```
        # So that we "share" control paths with git/git-annex
        if ssh_manager:
            ssh_manager.ensure_initialized()
```

I think that comment is misleading and inherited from an earlier approach where we set a config in annex repos, to tell annex what socket paths to use. But this has changed completely, and `ensure_initialized` doesn't do any of that.

**Comment by bpoldrack** [comment]
Overall it's not completely clear to me, whether we shouldn't use a central `SSHManager` instance at all (what seems to me you are suggesting, @mih). I think consistent use of `sshrun` is the correct path, but if a `sshrun`-process would use its own instance, than we'd currently loose the ability to share connections across those calls. That's because `SSHManager` would clean up behind itself and it wouldn't be able to realize that there's an ongoing datalad parent process that may want to reuse the connection.

**Comment by mih** [comment]
I think the solution for the "who shall close the connection" problem could be the following:

- Opening/closing a connection via a ControlMaster is protected by an inter-process lock
- If an `sshrun` process starts, and connection multiplexing is enable, a ControlMaster process is started, if there is none yet
- The test for an existing connection is an existing socket with a deterministic name, generated based on the local and remote connection details
- When an `sshrun` process ends, it ends the ControlMaster if the other processes use that socket. This is determined via `psutil`'s ability to report open files (works cross-platform, albeit with substantial performance differences)

Following this approach, any number of `sshrun` processes act like a swarm without the need for a central controller. This removes the need for any code in datalad that anticipates the opening of an SSH connection (of which there are plenty cases right now).

**Comment by mih** [comment]
Another realization I had when parsing the code: Rarely is an SSH connection actually closed. This implies that connections are only ever opened and not closed until process exit. Long running processes accumulate sockets with open connections. Switching to a swarm-like implementation as sketched above changes the pattern from "open-as-long-as-possible" to "as-short-as-necessary".

This is a substantial change. However, it also seems that the previous pattern is not implemented consistently either. For example, `maybe_open_ssh_connection()` is used for `get()` and `copy_to()`, but no other annex functionality that could be talking to `ssh` (init/enableremote, sync).

In other places, connections are opened in unexpected places in the code. `GitRepo.clone()` opens a connection, although one would argue that the `clone` dataset command should do that.

GitRepo.fetch/push() open a connection, although in a recursive fetch/push scenario connection management should happen in an outer layer.

Overall, the idea that connections are frivolously opened, and never closed is deeply backed into the code. Changing this pattern will need to have one of the following two consequences:

- increasing the number of times connections are (re-)opened, because we would actually close connections whenever there is no evidence for continued necessity to keep them open anymore
- the introduction of a true connection management that is aware of what compound-operations a connection is being used for (think a recursive `datalad push` that exercises `git-push`, `git annex copy` across a range of repositories all to the same target host)

The key problem with the current pattern is that we critically rely on `ssh_manager.get_connection().open()` to work non-interactively under all circumstances, because it is being called all over the place in the innermost code layers, possibly within processes that are not connected to any terminal.

**Comment by yarikoptic** [comment]
Some thoughts on some aspects.  Overall I feel like multiple, largely orthogonal issues are brought to surface: interactive entry of secrets, life-cycle of sockets in particular in case of parallel or fast sequential execution of commands, "support of `scp`".

- use-case of `scp` is specific to ORA remote.  Not clear to me either it could be just "with ssh manager: invoke `scp`" within ORA code and thus not require any `scp` specific wrapper etc
- interactivity (for secrets entry) -- doesn't work on Windows

I am not sure on this statement:

> In particular the latter use case is broken, because this code does not allow for any interactivity in its present form (i.e. typing in ssh (key) passwords).

<details>
<summary>since seems to work fine for password entry for me</summary> 

```shell
$> python -c 'from datalad import ssh_manager; c=ssh_manager.get_connection("smaug.datalad.org"); c.open(); print(c.get_git_version())'
sign_and_send_pubkey: signing failed for RSA "/home/yoh/.ssh/id_rsa" from agent: agent refused operation
yoh@smaug.datalad.org's password: 
2.30.2

$> datalad  sshrun smaug.datalad.org -- "git --version"      
sign_and_send_pubkey: signing failed for RSA "/home/yoh/.ssh/id_rsa" from agent: agent refused operation
yoh@smaug.datalad.org's password: 
git version 2.30.2
```
</details>
- sockets persistence.  Indeed we have the policy "the one who opens it - closes it", which is deficient and might need to be replaced with some re-entrable lock so that the last process closes it.  But I think we generally do not leave them hanging to just time out.

>  Strangely, it does not make an attempt to verify that the connection is not actually still in use.

Without any accountability (like re-entrable lock mentioned above) - we should not just leave it behind, and verification might be expensive.

**Comment by mih** [comment]
> * use-case of `scp` is specific to ORA remote.  Not clear to me either it could be just "with ssh manager: invoke `scp`" within ORA code and thus not require any `scp` specific wrapper etc

As stated in the top-comment, it is not just ORA. (search for `put()`, this is executing `scp`)

> I am not sure on this statement:
> 
> > In particular the latter use case is broken, because this code does not allow for any interactivity in its present form (i.e. typing 
in ssh (key) passwords).
> 
> since seems to work fine for password entry for me

It is broken, because it is specifically disabled in the constructor of `NoMultiplexSSHConnection`. This is used on windows, but not only on windows.

> - sockets persistence. Indeed we have the policy "the one who opens it - closes it", which is deficient and might need to be replaced with some re-entrable lock so that the last process closes it. But I think we generally do not leave them hanging to just time out.

> > Strangely, it does not make an attempt to verify that the connection is not actually still in use.
> Without any accountability (like re-entrable lock mentioned above) - we should not just leave it behind, and verification might be expensive.

Yes, we forcefully kill them, regardless of whether they are in use or not.

In the scenario where datalad code would be executed by a swarm of workers started by git-annex, the worker that happened to create the connection will take it down whenever it is done (because it assumes itself to be some kind of a master process), and requires the others to recover from this sabotage.

My current thinking for a fix is this:

- in addition to a socket, which is presently the only indicator for "need to have a connection open", we introduce "claim" files
- such files live in the same place as the socket (and the associated interprocess locks), same name as the socket, plus `.claim` extention
- code that "knows" that a connection is needed for a sustained period of time (across some potential idle period) can "claim" a connection, which creates the file (if needed) and opens it (always)
- the actual opening of connections is only done at the point where it is actually needed, and only then would a socket be created
- any code that believes a connection might be OK to close inspects whether there are processes still have the "claim" file open (if there is any, which is entirely optional)), and will *not* close a connection, if that is the case

The setup should allow a swarm of processes to reliably clean up without a central coordinator. In case of crashes the OS should close the file descriptors reliably, avoiding the pile-up of cruft. When a socket is to be created, and there is a "claim" file that is not opened currently, it can be reliably detected as stale and removed (this cleanup does not have to happen on startup to avoid delays), but can be done at shutdown.

It may be possible to avoid "claim" files to be different from the actual sockets, but I have not tested how SSH reacts to this. I don't think that having another file would be a significant issue.

I am aware that determining the number of processes that have a file open on windows is slow. However, SSH does not support sockets on windows, hence this is a non-issue -- claiming a connection on windows or rather for a `NoMultiplexSSHConnection` can simply be a noop.

**Comment by mih** [comment]
I don't know, but I am confident that I did not disable it for no reason.

**Comment by yarikoptic** [comment]
right -- it is in that comment @mih pointed to https://github.com/datalad/datalad/pull/5042#discussion_r505702974 in the PR which added it -- because we are likely nested and thus stdout is redirected.   But does ssh use stdout?

```
$> ssh smaug -- 'git annex version >&2' >/dev/null
sign_and_send_pubkey: signing failed for RSA "/home/yoh/.ssh/id_rsa" from agent: agent refused operation
yoh@smaug's password: 
Permission denied, please try again.
yoh@smaug's password: 
git-annex version: 8.20211123+git12-g02e3756bd-1~ndall+1
...

$> ssh smaug -- 'git annex version >&2' >/dev/null 2>&1
yoh@smaug's password: 
``` 

so -- for password prompt std* aren't used really -- those prompts are at the level of tty-whatever. That is what we rely on as well in our UI entry -- on using and lobotomizing for visibility `getpass` -- https://github.com/datalad/datalad/blob/HEAD/datalad/ui/dialog.py#L163 . That is how we can still ask for credentials within datalad special remote process . So, I wouldn't be surprised if prompting for password would just work if we disable disabling it

**Comment by mih** [comment]
Does `cmd.exe` qualify as a TTY?

**Comment by yarikoptic** [comment]
it is for someone with `cmd.exe` to find an answer, but there is `getpass.getpass` on windows -- could give the hypothesis a test I guess, e.g. `datalad install -g ///crcns/aa-1` or alike -- should give you  a prompt to enter a CRCNS password... don't have windows booted up ATM to try myself in the `cmd.exe` in question (always get lost among all the possible ways you could "do datalad" on window$)

**Comment by bpoldrack** [comment]
@mih 

> My current thinking for a fix is this:
> 
> - in addition to a socket, which is presently the only indicator for "need to have a connection open", we introduce "claim" files
> - such files live in the same place as the socket (and the associated interprocess locks), same name as the socket, plus `.claim` extention
> - code that "knows" that a connection is needed for a sustained period of time (across some potential idle period) can "claim" a connection, which creates the file (if needed) and opens it (always)
> - the actual opening of connections is only done at the point where it is actually needed, and only then would a socket be created
> - any code that believes a connection might be OK to close inspects whether there are processes still have the "claim" file open (if there is any, which is entirely optional)), and will *not* close a connection, if that is the case

I don't quite get the `claim` idea yet. How could a process decide to delete a `claim` file? In other words: How can I remove "my claim" w/o interferring with "someone else's claim"? Some sort of process id (not sure about win) would need to be included in the file name, no?

**Comment by mih** [comment]
> it is for someone with `cmd.exe` to find an answer, but there is `getpass.getpass` on windows -- could give the hypothesis a test I guess, e.g. `datalad install -g ///crcns/aa-1` or alike -- should give you a prompt to enter a CRCNS password... don't have windows booted up ATM to try myself in the `cmd.exe` in question (always get lost among all the possible ways you could "do datalad" on window$)

Here is the result of my attempt, bypassing any kind of datalad-layers

```
C:\Users\mih>ssh xxx@some.host.de 2>&1 > funky.txt
xxx@some.host.de's password:

C:\Users\mih>ssh xxx@some.host.de uname 2>&1 > funky.txt
ssh: connect to host some.host.de port 22: Connection timed out

C:\Users\mih>ssh xxx@some.host.de uname
ssh: connect to host some.host.de port 22: Connection timed out
```

So SSH itself is incapable of asking, or unwilling to ask, as soon as a remote command enters the picture.

**Comment by bpoldrack** [comment]
@mih Can't reproduce

```
❱ ssh juseless.inm7.de uname
no such identity: /home/ben/.ssh/id_rsa: No such file or directory
bpoldrack@juseless.inm7.de's password: 
```

**Comment by yarikoptic** [comment]
> ```
> C:\Users\mih>ssh xxx@some.host.de uname
> ssh: connect to host some.host.de port 22: Connection timed out
> ```
> 
> So SSH itself is incapable of asking, or unwilling to ask in the terminal, as soon as a remote command enters the picture.

hm, FWIW -- me is confused... I thought that `git` needs to run `git-shell` to clone/fetch from a remote over ssh, i.e. how would that work if it wouldn't ask for credentials if name is provided...

**Comment by yarikoptic** [comment]
FWIW -- couldn't reproduce
![image](https://user-images.githubusercontent.com/39889/157709513-b921a53b-e194-4746-8db7-e537ebc24013.png)

**Comment by mih** [comment]
So indeed, with

```diff
diff --git a/datalad/support/sshconnector.py b/datalad/support/sshconnector.py
index dfe290ca6..f578493bf 100644
--- a/datalad/support/sshconnector.py
+++ b/datalad/support/sshconnector.py
@@ -340,12 +340,6 @@ class NoMultiplexSSHConnection(BaseSSHConnection):
           Pass on to BaseSSHConnection
         """
         super().__init__(sshri, **kwargs)
-        self._ssh_open_args += [
-            # we presently do not support any interactive authentication
-            # at the time of process execution
-            '-o', 'PasswordAuthentication=no',
-            '-o', 'KbdInteractiveAuthentication=no',
-        ]

     def __call__(self, cmd, options=None, stdin=None, log_output=True):
         """Executes a command on the remote.
```

things are just working fine:

```
C:\Users\mih\code\datalad>datalad sshrun xxx@some.host.de uname
xxx@some.host.de's password:
xxx@some.host.de's password:
Linux
```

But why password-entry twice?

Ah, that is another side of https://github.com/datalad/datalad/issues/6530 -- without connection multiplexing, each call to ´sshrun´ results in two calls to ´ssh´.

**Comment by mih** [comment]
It seems this issue has served its purpose.
