### ISSUE TITLE
FOI: shortcoming of identifying just by checksums -- no executable bit considered

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#653]
just realized that if we start populating with urls pointing to other sources, and some of them would nohow carry information about the executable bit (e.g. a url, unlike a RI pointing to the tarball content, where executable bit is set)... and git doesn't carry an executable bit of the dereferenced content of a symlink, so we e.g. can't add an executable binary under annex, and having a url associated with it hope that somehow annex or git would set an executable bit on it whenever we 'annex get' it.  Correct @joeyh?

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> just realized that if we start populating with urls pointing to other sources,
> and some of them would nohow carry information about the executable bit (e.g. a
> url, unlike a RI pointing to the tarball content, where executable bit is
> set)... and git doesn't carry an executable bit of the dereferenced content of
> a symlink, so we e.g. can't add an executable binary under annex, and having a
> url associated with it hope that somehow annex or git would set an executable
> bit on it whenever we 'annex get' it. Correct @joeyh?

Yes, nothing tracks that.

In v6 mode, the execute bit of unlocked files is tracked.

-- 
see shy jo

**Comment by yarikoptic** [comment]
On Wed, 20 Jul 2016, Joey Hess wrote:

>    Yaroslav Halchenko wrote:
>    > just realized that if we start populating with urls pointing to other
>    sources,
>    > and some of them would nohow carry information about the executable bit
>    (e.g. a
>    > url, unlike a RI pointing to the tarball content, where executable bit
>    is
>    > set)... and git doesn't carry an executable bit of the dereferenced
>    content of
>    > a symlink, so we e.g. can't add an executable binary under annex, and
>    having a
>    > url associated with it hope that somehow annex or git would set an
>    executable
>    > bit on it whenever we 'annex get' it. Correct @joeyh?

>    Yes, nothing tracks that.

>    In v6 mode, the execute bit of unlocked files is tracked.

is it tracked persistently?  i.e. in a clean clone, with content
fetched from some special remote which doesn't care about executable
bits, I would get the executable bit set correctly if I unlock the
file??

or just while unlocking (set file exec bit as the key's), locking (set
key's exec bit as of the file)?

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> is it tracked persistently? i.e. in a clean clone, with content
> fetched from some special remote which doesn't care about executable
> bits, I would get the executable bit set correctly if I unlock the
> file??

It's persistent, and v6 mode unlocked files get committed as such, so
are unlocked in all clones.

See commit b7c8bf5274a64389ac87d6ce0388b8708c261971

-- 
see shy jo

**Comment by yarikoptic** [comment]
On Wed, 20 Jul 2016, Joey Hess wrote:

>    Yaroslav Halchenko wrote:
>    > is it tracked persistently? i.e. in a clean clone, with content
>    > fetched from some special remote which doesn't care about executable
>    > bits, I would get the executable bit set correctly if I unlock the
>    > file??

>    It's persistent, and v6 mode unlocked files get committed as such, so
>    are unlocked in all clones.

>    See commit b7c8bf5274a64389ac87d6ce0388b8708c261971

Great!  thank you for the explanation/pointer!

**Comment by mih** [comment]
As this was FOI, closing after two years.
