### ISSUE TITLE
Relevance of SSH `use_remote_annex_bundle`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6530]
When opening an SSH connection this is done by default. Its docs say:

```
        use_remote_annex_bundle : bool
          If set, look for a git-annex installation on the remote and
          prefer its binaries in the search path (i.e. prefer a bundled
          Git over a system package).
```

So this is really about the Git version to use and not so much about git-annex. It has an impact whenever there a git-annex in the default PATH at the remote end, but on the same host the Git version in the PATH is not the same, or for some reason undesirable.

While it is not completely clear to me what common scenario this is helping with, the cost for this cannot be ignored.

For each command line call to `sshrun` this is causing an additional remote command execution (of a compound command that determines the git-annex installation dir) -- on the system that I noticed this behavior with, this means an additional 600ms per call.

We are using `sshrun` as an SSH drop-in for all Git operations and all git-annex operations.

Unless someone convinces me otherwise, I think the default should change to not perform this adjustment attempt by default, and to add to the ability to enable it via a config switch, instead of a constructor parameter exclusively (which is inaccessible when used inside Git and git-annex).

**Comment by yarikoptic** [comment]
it is quite often that system wide installation of `git`, which is what would get used, is too old (e.g. on HPC).  standalone installation of git-annex on remote would likely come with a newer version of  `git`.  Some history on the issue:
- use of bundled git added in 133063887cb244556bd8ee8dff22d90f5f873812 part of https://github.com/datalad/datalad/pull/1237, fixing https://github.com/datalad/datalad/issues/1240 
- it was made "configurable" in 3dbacff9fc40bf952052e5abd54eb98a763b1a7d as part of https://github.com/datalad/datalad/pull/3402

I think, ideally, it might be worth making it configurable per remote (`remote.{name}.datalad-git-path` or alike), with initial sensing (done once if such variable is not present at all) so there would be singular invocation overhead.

**Comment by mih** [comment]
Just to clarify, with `sshrun` being GIT_SSH_COMMAND, there is one singular overhead per each call to `ssh`.

If I get you right, the scenario that calls for the unconditional cost is that on some systems, somebody bothered to install a standalone git-annex, but did not want a recent enough git to be default -- which can be done without admin intervention.

If that is correct, I'd say the default should change to off. It might well be that the Git shipped with that standalone install is actually older, or less security fixed. This should be an opt-in, not an opt-out.

**Comment by yarikoptic** [comment]
IMHO the default should be such which makes it a better fit for larger portion of the use cases.  Insofar I have not heard on disadvantages of current behavior (besides performance impact stated in this issue). We could do a quick experiment -- would any CI configuration need to be changed **if** you change the default to "opt-in"?

**Comment by bpoldrack** [comment]
I think, sensing `standalone` is a convenience thing that's fine if it's cheap. In principal (even in the local case) it just "fixes" something automatically, that - we think - should have been set up this way to begin with (not using different Git versions depending on whether you call git or git-annex). It can be solved by the user in both cases (remote and local). Hence, when it comes with a significant cost, it's expendable. Moreover: There's not a lot of git/git-annex calls in any remote operation I'm aware of anyway. `create-sibling` and SSH special remote(s) do barely anything other than `git init` and some `mkdir`, `scp`, etc. In other words: Off by default it is from my POV. 

I don't think that our CI builds are indicative of what's "normal". Especially not by proportion. That's not their purpose except that they should ideally include something that can be considered normal. Hence how many we'd need to change doesn't matter - if anything which ones would matter.

**Comment by yarikoptic** [comment]
> I don't think that our CI builds are indicative of what's "normal".

generally, those setups would be quite prevalent among potential users since such setups "shared" -- many CI users use them!  We already dealt with the fallout of needing everyone using datalad in CI to run all the `git config` commands to set the user, and requires every affected CI configuration tune up to just get tests going -- not fun and waste of typing IMHO, and thus should be avoided when possible  (what I am hinting -- that if needed, should be sensed/setup in the tests fixture).  So, even though for this particular SSH setting it is largely "unrelated" (since people wouldn't ssh from one CI to another), overall "I agree to disagree" with such a statement.  In particular, because we have no other idea of what is "normal" if there could be any.
