### ISSUE TITLE
Sharing data on OSF using datalad

### ISSUE THREAD

**Issue by ozika** [datalad/datalad#6534]
### What is the problem?

Following your [v. nice tutorial ](http://docs.datalad.org/projects/osf/en/stable/tutorial/exportdatacode.html) I have a data set successfully shared on OSF - this is great!  
However, sometimes, people who want to get the data set will not want to use datalad or they will just want to preview the data, let's say when there is an output PDF.  For now, when accessing the repo vis OSF's web interface it only sows the `.git` folder (as expected).  

I guess what I am asking is whether there is a way to unpack the data when they reach OSF. If I remember correctly, on GIN one can see the content. I totally understand if this isn't possible atm. If this is something that is more on OSF's side, I can try to request this feature.  

All in all, it would just make data sharing more accessible.

**Comment by yarikoptic** [comment]
Probably the best way would be to configure special remote to "exporttree" mode. tutorial for that is yet TODO: https://github.com/datalad/datalad-osf/issues/150 . Implementation PR https://github.com/datalad/datalad-osf/pull/59 has an example

**Comment by mih** [comment]
Hey, I think what you are asking for is explained [here](http://docs.datalad.org/projects/osf/en/latest/tutorial/exporthumandata.html). If you feel like this is missing some information, let's create a new issue about that at https://github.com/datalad/datalad-osf/issues
