### ISSUE TITLE
Downloaders not suitable for internal usage

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#6545]
The current implementation of downloaders wasn't aimed at providing download capabilities for somewhat internal operations. An example for the need for that would be the ORA special remote (HTTP case). Instead the error handling as well as the logging of downloaders clearly aim to provide user-facing messaging rather than provide higher-level code with an assessment of what went wrong.
Examples for that include:

- an INFO level log message "Fetching <URL> ...": that level is only useful if that download was something the user would be aware or intended to download of to begin with. For internal usage within ORA or `clone` (checking `origin`'s config when trying to enable special remote(s)) INFO level seems inappropriate
- `check_response_status` in `http.py` does not make use of `raise_from_status`. Hence, we don't, for example, get an `HTTPError` when encountering a 404. For higher-level code to know what's going on we'd currently need to parse the string of a generic `DownloadError` instead.

**Comment by yarikoptic** [comment]
yes, downloaders were written before any notion of ORA and possibly of return result records existed. They are used internally (thus issue title is a bit misleading) IIRC but indeed might need a face lift (or completely redo) to fit better into current internal design paradigm.

**Comment by bpoldrack** [comment]
Yes, I know this is old.
But apart from any legacy, the way exceptions and logging is shaped/worded seems clearly intended for user-messaging. This is only valid if that layer "knows" how and where it is used. That's what I mean by "not suitable". Internal use makes the downloaders a too low level layer to decide about user messaging.

**Comment by mih** [comment]
From my POV this can be closed. The logging issue is gone. The error behavior is just one aspect, why using `download_url` with the context of a special remote is undesirable. The inability to report progress to git-annex is another https://github.com/datalad/datalad/issues/4500#issuecomment-1074241474

**Comment by bpoldrack** [comment]
I don't think the logging issue is gone really. Just that one spot is lowered to DEBUG. But downloaders in general have a bunch of them and if they are used for any internal purpose that can result in the same problem in similar situations.

The use of `download_url` can be replaced (or that function adjusted, since replacement would be near identical), but this would likely reveal more such spots (like `BaseDownloader.download` emitting ` lgr.info("Downloading %r into %r", url, path)`). However, lowering to DEBUG should probably include to double-check where higher-level code may need to emit an INFO instead to not lose the message entirely (or confirm that it is OK to lose it, obv.)

**Comment by mih** [comment]
https://github.com/datalad/datalad-next/pull/124 provides an alternative without these issues. I don't think this will be addressed in the old code base. I am tagging and closing accordingly.
