### ISSUE TITLE
Keyring field deletion crashes with unknown field

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6552]
In https://github.com/datalad/datalad/blob/b23174877533ffac3c552f92412ef5398aa20c59/datalad/support/keyring_.py#L88 the code tries to specifically protect against attempting to delete a field that doesn't exist, but it is looking for an exception message (`not found`) that is not part of the actual exception:

`PasswordDeleteError(No such password!)`

**Comment by yarikoptic** [comment]
I guess something to fix in `maint` (if `master` is to get a new cred manager)... will send a quick PR

**Comment by mih** [comment]
Fixed by #6557
