### ISSUE TITLE
ADHD200 dataset

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#656]
Another part toward INDI (#580) collection coverage

http://fcon_1000.projects.nitrc.org/indi/adhd200/

For download and to see the download links, you need to be logged in into NITRC.  I will take care about making that happen

Otherwise, I think every site should be the sub-dataset.
Ideally, in preparation for handling meta information we should scrape all details about super and each particular dataset, so we could later populate the meta information

ok -- that page is javascript populated, based on information from
http://fcon_1000.projects.nitrc.org/indi/adhd200/json/intro.json
and
http://fcon_1000.projects.nitrc.org/indi/adhd200/json/sites.json

so we should just use those jsons, and generate datasets based on them

**Comment by mih** [comment]
I assume it is here: http://datasets.datalad.org/?dir=/adhd200
