### ISSUE TITLE
Consider passing shallow copy of result record to renderer

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6560]
Right now a custom result renderer can do in-place result record modifications, which will affect subsequent result processing in the central loop. I think this is undesirable and we should consider preventing it. Not sure if making an unconditional shallow copy is the best approach, but it certainly fixes this issue.

**Comment by yarikoptic** [comment]
yikes -- what has triggered the desire to file this issue I wonder?
"shallow" copy might address some particular abuse but can't provide a generic solution (my evil result rendered can go as deep as it cares)

if we are to start protecting one part of code from another, and in particular at the level of the result records, may be time to look into refactoring passing around a `dict` to formalizing into some `dataclass` and making created instances "immutable"?

**Comment by mih** [comment]
Sounds like the proposal was not a good idea, and result renderers should be careful until the results concept has been replaced.
