### ISSUE TITLE
nonasyncrunner - KeyError: 6 in threaded test_foreach_dataset.test_basic_resilience

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6595]
An extract from https://github.com/datalad/datalad/issues/6482#issuecomment-1076484326 which was resolved by a workaround.

was observed while testing the workaround #6587 on windows (although most likely a generic one, but was observed only on windows for now, marking as such).  Brief extract

```
> c:\users\datalad\pycharmprojects\datalad\datalad\runner\nonasyncrunner.py(592)remove_file_number()
-> self.fileno_mapping[file_number],
(Pdb) l
587             """
588
589             # TODO: check exception
590             # Let the protocol know that the connection was lost.
591             self.protocol.pipe_connection_lost(
592  ->             self.fileno_mapping[file_number],
593                 None)
594
595             if file_number in self.active_file_numbers:
596                 # Remove the file number from the set of active numbers.
597                 self.active_file_numbers.remove(file_number)
(Pdb) p https://uchealth.zoom.us/j/514490116
*** SyntaxError: invalid syntax
(Pdb) p self.fileno_mapping[file_number],
*** KeyError: 6
(Pdb) p self.fileno_mapping[file_number]
*** KeyError: 6
(Pdb) p self.fileno_mapping
{3: 1, 4: 2, None: 0}
```

we troubleshooted a bit with @christian-monch  but have not arrived to a conclusion.  So far the idea for the cause is that base process gets threaded so that `ThreadedRunner` instance gets used both in main and thread, causing the `run` to be called twice with different settings which causes this `6` to appear in fileno_mapping but not listed in other places

**Comment by yarikoptic** [comment]
me is failing to reproduce it even on the 100s of runs now :-( damn bug hided away.  @christian-monch what was that python library which you mentioned to introduce random delays into execution?

**Comment by christian-monch** [comment]
The problem is that `ThreadedRunner.run()` is not reentrant. Multiple entries into this method can easily be triggered by using a `GeneratorMixIn`-protocol and threads. But the error also occurs within a single thread. 

This is a small reproducer:

```
from datalad.runner.nonasyncrunner import ThreadedRunner
from datalad.runner.tests.utils import py2cmd
from datalad.runner.protocol import GeneratorMixIn
from datalad.runner.coreprotocols import StdOutCapture


class TestProtocol(GeneratorMixIn, StdOutCapture):
    pass

runner = ThreadedRunner(
    cmd=py2cmd("for i in range(10): print(i)"),
    protocol_class=TestProtocol,
    stdin=None)

generator_1 = runner.run()
generator_2 = runner.run()

generator_1.send(None)
generator_2.send(None)
```

Will add code to prevent re-entry.
