### ISSUE TITLE
allow for attempting connection/download without authentication and only if fail - demand one

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#661]
Eg. with nitrc frs `https?://www\.nitrc\.org/frs/downloadlink\.php/` urs. Some of those do not require any authentication, and some do (and also an explicit agreement by user!), e.g. https://www.nitrc.org/frs/?group_id=404 which if not authenticated forwards to https://www.nitrc.org/account/login.php?return_to=%2Ffrs%2F%3Fgroup_id%3D404 .  Note that return_to provided is a part of the form submission so upon succesfull authentication page/file gets provided.

Then, there could also be "Data Collection Agreement", which provides a page where user must agree or cancel.  We might want to channel it through datalad or just refer users to the page in the browser

**Comment by mih** [comment]
I think we can close the ancient issue, with #1069 and  #5878 tracking the two individual aspects also.
