### ISSUE TITLE
Datalad on WSL2. datalad save not working

### ISSUE THREAD

**Issue by jhpb7** [datalad/datalad#6614]
### What is the problem?

I reported the issue at the datalad-handbook repo, here:
https://github.com/datalad-handbook/book/issues/819#issue-1191599264

but I was advised to repost it here. In addition I updated datalad from 0.12 to 0.15, thus a more insightful error message occurred.

I’m currently working my way through the handbook and while most of it works, there is one error occurring.
When trying to save the books (pdfs in folder books) in section 1.2, using
datalad save -m "add books on Python and Unix to read later"

the following error occurs:

[WARNING] Received an exception CommandError(CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- books/TLCL.pdf books/byte-of-python.pdf .gitmodules' failed with exitcode 1 under /mnt/c/Users/++USRNAME++/Documents/datalab/test/DataLad-101 [info keys: stdout_json]    
\>git-annex: .git/annex/othertmp/TLCL.pdf.0/TLCL.pdf: rename: permission denied (Permission denied)
\> git-annex: .git/annex/othertmp/byte-of-python.pdf.0/byte-of-python.pdf: rename: permission denied (Permission denied) [err: 'add: 2 failed']). Canceling not-yet running jobs and waiting for completion of running. You can force earlier forceful exit by Ctrl-C.
[INFO   ] Canceled 0 out of 0 jobs. 0 left running.
Total:   0%|                                                                                                                   | 0.00/1.00 [00:00<?, ? datasets/s]
CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- books/TLCL.pdf books/byte-of-python.pdf .gitmodules' failed with exitcode 1 under /mnt/c/Users/++USRNAME++/Documents/datalab/test/DataLad-101 [info keys: stdout_json]
\>git-annex: .git/annex/othertmp/TLCL.pdf.0/TLCL.pdf: rename: permission denied (Permission denied)
\> git-annex: .git/annex/othertmp/byte-of-python.pdf.0/byte-of-python.pdf: rename: permission denied (Permission denied)
add: 2 failed

After that everything works fine until at section 5.3, I tried to use the “write your own procedures” and then again saving the python code yields this permission denied error. Between all this, saving (e.g. to the notes.txt) works fine.

### What steps will reproduce the problem?

use WSL Ubuntu and work on the windows file system. Work through Datalad Handbook Section 1.2, try to save the pdf in the books dataset

### Datalad information

# WTF
## credentials
  - keyring:
    - active_backends:
      - EncryptedKeyring with [PBKDF2] AES256.CFB v.1.0 at /home/++USRNAME++/.local/share/python_keyring/crypted_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at /home/++USRNAME++/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/++USRNAME++/.local/share/python_keyring/keyringrc.cfg
    - data_root: /home/++USRNAME++/.local/share/python_keyring
## datalad
  - version: 0.15.5
## dataset
  - branches:
    - git-annex@9c5ea6c
    - master@331a579
    - synced/master@6b0e828
  - id: bb5c7e98-b0c3-11ec-95ce-00155d1fbe46
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /mnt/c/Users/++USRNAME++/Documents/datalab/test/DataLad-101
  - repo: AnnexRepo
## dependencies
  - annexremote: 1.4.3
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20211123+git12-g02e3756bd-1~ndall+1
  - cmd:bundled-git: 2.30.2
  - cmd:git: 2.30.2
  - cmd:system-git: 2.25.1
  - cmd:system-ssh: 8.2p1
  - exifread: 2.1.2
  - git: 3.0.7
  - gitdb: 2.0.6
  - humanize: 1.0.0
  - iso8601: 0.1.12
  - keyring: 18.0.1
  - keyrings.alt: 3.4.0
  - msgpack: 0.6.2
  - mutagen: 1.44.0
  - requests: 2.22.0
  - wrapt: 1.11.2
## environment
  - LANG: C.UTF-8
  - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Users/++USRNAME++/Anaconda3/envs/opt:/mnt/c/Users/++USRNAME++/Anaconda3/envs/opt/Library/mingw-w64/bin:/mnt/c/Users/++USRNAME++/Anaconda3/envs/opt/Library/usr/bin:/mnt/c/Users/++USRNAME++/Anaconda3/envs/opt/Library/bin:/mnt/c/Users/++USRNAME++/Anaconda3/envs/opt/Scripts:/mnt/c/Users/++USRNAME++/Anaconda3/envs/opt/bin:/mnt/c/Users/++USRNAME++/Anaconda3/condabin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/mnt/c/Program Files/SCIPOptSuite 8.0.0/bin:/mnt/c/Users/++USRNAME++/Anaconda3:/mnt/c/Users/++USRNAME++/Anaconda3/Library/mingw-w64/bin:/mnt/c/Users/++USRNAME++/Anaconda3/Library/usr/bin:/mnt/c/Users/++USRNAME++/Anaconda3/Library/bin:/mnt/c/Users/++USRNAME++/Anaconda3/Scripts:/mnt/c/Users/++USRNAME++/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/++USRNAME++/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/++USRNAME++/AppData/Local/Programs/Git/cmd:/snap/bin
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 8
  - operating system: linux x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20211123+git12-g02e3756bd-1~ndall+1
## location
  - path: /mnt/c/Users/++USRNAME++/Documents/datalab/test/DataLad-101
  - type: dataset
## metadata_extractors
  - annex (datalad 0.15.5):
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.5):
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite (datalad 0.15.5):
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.5):
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.5):
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.15.5):
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage (datalad 0.15.5):
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.5):
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp (datalad 0.15.5):
    - distribution: datalad 0.15.5
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## python
  - implementation: CPython
  - version: 3.8.10
## system
  - distribution: ubuntu/20.04/focal
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 310
  - name: Linux
  - release: 5.10.102.1-microsoft-standard-WSL2
  - type: posix
  - version: #1 SMP Wed Mar 2 00:30:59 UTC 2022

### Additional context

- using VS Code and starting WSL in cmd line (wsl.exe)
- WSL 2 with Ubuntu 20.04 LTS
- working on a Windows folder, thus "/mnt/c/Users/++USERNAME++/Documents/datalab"

**Comment by bpoldrack** [comment]
Thanks for reporting, @jhpb7!

I have no immediate idea what is causing this - will need to reproduce.

**Comment by mih** [comment]
I do not know whether @bpoldrack has succeeded in reproducing this behavior, so please let me know if this issue is still valid. In order to get to the bottom of this it would be nice to get a small reproducer, ie. a minimal set of steps to show the problem. It would be good to check with the latest datalad version (0.16.1) and with a more recent git-annex (which is the failing component here). Thx!

**Comment by jhpb7** [comment]
Hello @mih, the issue is still valid.

I updated datalad to 0.16.1 and git-annex still to 10.20220322-g7b64dea.
What I just did to reproduce the error is
 `
        datalad create -c text2git DataLad-102
        cd DataLad-102/
        mkdir books 
        cd books
        wget -q https://sourceforge.net/projects/linuxcommand/files/TLCL/19.01/TLCL-19.01.pdf/download -O TLCL.pdf
        wget -q https://homepages.uc.edu/~becktl/byte_of_python.pdf -O byte-of-python.pdf
        cd ..
        datalad save -m "add books on Python and Unix to read later"
`
(sorry I can't seem to find how to add line breaks in md code)

More or less the same error occurs:
[WARNING] Received an exception CommandError(CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- books/TLCL.pdf books/byte-of-python.pdf' failed with exitcode 1 under /mnt/c/Users/USRNAME/Documents/datalab/DataLad-102 [info keys: stdout_json]
\>git-annex: .git/annex/othertmp/TLCL.pdf.0/TLCL.pdf: rename: permission denied (Permission denied)
\> git-annex: .git/annex/othertmp/byte-of-python.pdf.0/byte-of-python.pdf: rename: permission denied (Permission denied) [err: 'add: 2 failed']). Canceling not-yet running jobs and waiting for completion of running. You can force earlier forceful exit by Ctrl-C.
[INFO   ] Canceled 0 out of 0 jobs. 0 left running.
Total: 0.00 datasets [00:01, ? datasets/s]CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- books/TLCL.pdf books/byte-of-python.pdf' failed with exitcode 1 under /mnt/c/Users/USRNAME/Documents/datalab/DataLad-102 [info keys: stdout_json]
\>git-annex: .git/annex/othertmp/TLCL.pdf.0/TLCL.pdf: rename: permission denied (Permission denied)
\> git-annex: .git/annex/othertmp/byte-of-python.pdf.0/byte-of-python.pdf: rename: permission denied (Permission denied)
add: 2 failed

I'm not sure whether this is helpful but I just found a difference when creating the dataset on windows filesystem other than the linux wsl filesystem:
[INFO   ] Creating a new annex repo at /mnt/c/Users/Breuer/Documents/datalab/DataLad-102 
**[INFO   ] Detected a filesystem without fifo support. 
[INFO   ] Disabling ssh connection caching.**
[INFO   ] Running procedure cfg_text2git 
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) ===== 

The two bold lines only occur when creating in the windows filesystem.

Thanks for your time!

**Comment by adswa** [comment]
Sorry it took so long to get back to this. I've finally gotten around to installing WSL2. I tried to reproduce this, and I didn't yet succeed - the commands you provided in your reproducer worked both under ``/mnt/c/Users/<user>/...`` and ``/home/<user>``.
But what's interesting to me is indeed 

> I'm not sure whether this is helpful but I just found a difference when creating the dataset on windows filesystem other than the linux wsl filesystem:
[INFO ] Creating a new annex repo at /mnt/c/Users/Breuer/Documents/datalab/DataLad-102
[INFO ] Detected a filesystem without fifo support.
[INFO ] Disabling ssh connection caching.
[INFO ] Running procedure cfg_text2git
[INFO ] == Command start (output follows) =====
[INFO ] == Command exit (modification check follows) =====

Its something that actually isn't supposed to happen, and seems to suggest that its a file system or mounting issue inside of WSL2. I will read around a bit online to find out what might be causing this, I haven't seen this before...
Is your drive on Windows by any chance something that's not the ``:\C`` drive?

**Comment by adswa** [comment]
I managed to somehow make this reproduce, and I also managed to somehow fix/workaround this with some aspects of this [workaround on WSL1](https://git-annex.branchable.com/tips/Using_git-annex_on_NTFS_with_WSL1/) - though it is unclear to me how precisely. I need to come back to this with a bit more time. 

Here is a list of things I did, for me to remember:

I enabled developer mode in the Windows settings. 

I remounted the Windows filesystem with the metadata option
```
# from linux fs
sudo umount /mnt/c
sudo mount -t drvfs C: /mnt/c -o metadata
```

I then opened the affected dataset in a file explorer. Clicked "Properties" -> "Properties" -> "Security" -> "Advanced" -> "Add"

I then clicked "Select a principal" and wrote "Authenticated Users" in the free text field > "Check Names" -> "OK"
![signal-2022-04-21-173452_002](https://user-images.githubusercontent.com/29738718/164497587-afab1071-e741-43c2-b8d0-6e529f75d87e.png)

In the permissions overview I clicked "Show advanced permissions" and enabled “Write attributes”, “Create files”, “Create folders” and “Delete subfolders and files”, and then applied those properties.

In the Permission entries this added "Authenticated Users" with "Special" Access.
![signal-2022-04-21-173452_001](https://user-images.githubusercontent.com/29738718/164497952-2ceed1b1-500b-41e2-80b9-2e7bc21342e4.png)


I then ran "git config annex.crippledfilesystem true" (because I still could not get git-annex to detect a crippled filesystem as it did on your system, and some of the error report in git-annex seems to suggest that the bug might result from an attempt to hardlink files - but this was a shot in the dark). Afterwards, a file that I previously failed to save/git annex add was successfully saved/added.

```
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/bugtests/buggy$ datalad save file
[WARNING] Received an exception CommandError(CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- file' failed with exitcode 1 under /mnt/c/Users/adina/Documents/bugtests/bedo [info keys: stdout_json]
>git-annex: .git/annex/othertmp/file.0/file: rename: permission denied (Permission denied) [err: 'add: 1 failed']). Canceling not-yet running jobs and waiting for completion of running. You can force earlier forceful exit by Ctrl-C.
[INFO   ] Canceled 0 out of 0 jobs. 0 left running.
Total: 0.00 datasets [00:01, ? datasets/s]CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- file' failed with exitcode 1 under /mnt/c/Users/adina/Documents/bugtests/bedo [info keys: stdout_json]
>git-annex: .git/annex/othertmp/file.0/file: rename: permission denied (Permission denied)
add: 1 failed
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/bugtests/buggy$ git config annex.crippledfilesystem true
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/bugtests/buggy$ datalad save file
add(ok): file (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
```


It feels pretty nasty. I hope I can figure how the bug was triggered, because the first datasets I created were fine, and something I must have done in my attempts to reproduce this must have reconfigured something in a bad way.

**Comment by adswa** [comment]
Also just notes to myself, looking back at my terminal output, there really wasn't much I have done between ``git annex add`` working and not working anymore. I pretty much only switched from the Windows fs to Linux and back.
```
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102$ cd ~
adina@LAPTOP-7OK837FF:~$ sudo umount /mnt/c/
adina@LAPTOP-7OK837FF:~$ sudo mount -t drvfs C: /mnt/c -o metadata
adina@LAPTOP-7OK837FF:~$ cd /mnt/c/Users/adina/Do
Documents/ Downloads/
adina@LAPTOP-7OK837FF:~$ cd /mnt/c/Users/adina/Documents/
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents$ cd DataLad-102/
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102$ git init
Reinitialized existing Git repository in /mnt/c/Users/adina/Documents/DataLad-102/.git/
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102$ datalad status
untracked: byte-of-python.pdf (file)
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102$ datalad save -m "Add a file"
add(ok): byte-of-python.pdf (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102$ mkdir books
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102$ cd books/
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102/books$ ls
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102/books$ wget -q https://homepages.uc.edu/~becktl/byte_of_python.pdf -O byte-of-python.pdf
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102/books$ wget -q https://sourceforge.net/projects/linuxcommand/files/TLCL/19.01/TLCL-19.01.pdf/download  -O TLCL.pdf
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102/books$ cd ..
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102$ datalad status
untracked: books (directory)
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102$ datalad save -m "add books"
add(ok): books/TLCL.pdf (file)
add(ok): books/byte-of-python.pdf (file)
save(ok): . (dataset)
action summary:
  add (ok: 2)
  save (ok: 1)
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/DataLad-102$ cd ~
adina@LAPTOP-7OK837FF:~$ cd /mnt/c/Users/adina/
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina$ mkdir bugs
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina$ cd bugs/
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/bugs$ datalad create DataLad-101
[INFO   ] Creating a new annex repo at /mnt/c/Users/adina/bugs/DataLad-101
create(ok): /mnt/c/Users/adina/bugs/DataLad-101 (dataset)
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/bugs$ cd DataLad-101/
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/bugs/DataLad-101$ ls
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/bugs/DataLad-101$ ls -a
.  ..  .datalad  .git  .gitattributes
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/bugs/DataLad-101$ echo "1234" > file
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/bugs/DataLad-101$ datalad save
[WARNING] Received an exception CommandError(CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- file' failed with exitcode 1 under /mnt/c/Users/adina/bugs/DataLad-101 [info keys: stdout_json]
>git-annex: .git/annex/othertmp/file.0/file: rename: permission denied (Permission denied) [err: 'add: 1 failed']). Canceling not-yet running jobs and waiting for completion of running. You can force earlier forceful exit by Ctrl-C.
[INFO   ] Canceled 0 out of 0 jobs. 0 left running.
Total: 0.00 datasets [00:01, ? datasets/s]CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- file' failed with exitcode 1 under /mnt/c/Users/adina/bugs/DataLad-101 [info keys: stdout_json]
>git-annex: .git/annex/othertmp/file.0/file: rename: permission denied (Permission denied)
add: 1 failed
```

**Comment by adswa** [comment]
@jhpb7, just for shits and giggles, would you mind doing two things and check if they make a difference:

Could you enable "Developer mode" in the Windows settings? You should find it by typing "developer mode" into the explorer, its a toggleable switch. 

Could you then run ``git config annex.crippledfilesystem true`` inside of the repository where you see the errors, and try to re-save the files? 

After restarting my system, these things seem to at least make it work for now.

```
adina@LAPTOP-7OK837FF:~/bugtests/new$ cd /mnt/c/Users/adina/Documents/bugtests/
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/bugtests$ datalad create new
c[INFO   ] Creating a new annex repo at /mnt/c/Users/adina/Documents/bugtests/new
d new[INFO   ] Detected a filesystem without fifo support.
[INFO   ] Disabling ssh connection caching.

create(ok): /mnt/c/Users/adina/Documents/bugtests/new (dataset)
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/bugtests$ cd new
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/bugtests/new$ ls
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/bugtests/new$ echo 12345 > file
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/bugtests/new$ datalad save
[WARNING] Received an exception CommandError(CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- file' failed with exitcode 1 under /mnt/c/Users/adina/Documents/bugtests/new [info keys: stdout_json]
>git-annex: .git/annex/othertmp/file.0/file: rename: permission denied (Permission denied) [err: 'add: 1 failed']). Canceling not-yet running jobs and waiting for completion of running. You can force earlier forceful exit by Ctrl-C.
[INFO   ] Canceled 0 out of 0 jobs. 0 left running.
Total: 0.00 datasets [00:01, ? datasets/s]CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- file' failed with exitcode 1 under /mnt/c/Users/adina/Documents/bugtests/new [info keys: stdout_json]
>git-annex: .git/annex/othertmp/file.0/file: rename: permission denied (Permission denied)
add: 1 failed
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/bugtests/new$ git config annex.crippledfilesystem true
adina@LAPTOP-7OK837FF:/mnt/c/Users/adina/Documents/bugtests/new$ datalad save
add(ok): file (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
```

**Comment by jhpb7** [comment]
Hi @adswa thank you so much! Even though I do not understand it, it works!

**Comment by jhpb7** [comment]
Shall I close this issue or will you be able to fix it (and I leave it open)?

**Comment by mih** [comment]
Hey @jhpb7, it would be great, if you could leave a final note what exactly you did to get it working. Some of the steps @adswa suggested, or all of them? In the exact order?

Thx!

**Comment by jhpb7** [comment]
These two steps helped to fix the issue for me:
> Could you enable "Developer mode" in the Windows settings? You should find it by typing "developer mode" into the explorer, its a toggleable switch.
> 
> Could you then run `git config annex.crippledfilesystem true` inside of the repository where you see the errors, and try to re-save the files?

Note that the second step needs to be done inside every repository in the windows filesystem.
