### ISSUE TITLE
Design docs: `error_message` vs `error-messages` in result records

### ISSUE THREAD

**Issue by mslw** [datalad/datalad#6620]
The [design docs on Result records ](https://docs.datalad.org/en/latest/design/result_records.html) specify `error-messages` as one of the optional fields in a result record. They also say that the `get_status_dict()` function can be used to simplify creation of result records. Yet, this function has `error_message` instead:

https://github.com/datalad/datalad/blob/6b4280dcb3e31a2efc6b8d8be544655c08992982/datalad/interface/results.py#L101-L102

I think that design docs should be saying `error_message` instead.

However, I'm not 100% sure, so I wanted to confirm with @datalad/developers before making a one-liner PR.

---
For context:
- Git-annex uses `error-messages` in its JSON outputs (at least for get & drop that I checked - [git annex docs](https://git-annex.branchable.com/tips/using_git-annex_from_your_program/) only say "The format of git-annex's JSON output is not documented in full, because it varies from command to command. The shape is typically the same, but a few commands have a more custom JSON. Try a command and see what JSON it outputs and go from there" - so I tried and went from there)
- I searched DataLad codebase with `git grep` and it is *my impression* that `error_message` is preferred by us:
  - `error_message` (variable / key) and `get_status_dict` are used in several places
  - `error-messages` (variable / key) is also used in several places, but for most of them the context is clearly dealing with raw-ish git annex output, either directly (e.g. checking output of `repo._call_annex_records`) or to join error messages and place them in the `error_message` field for result records down the line
  - other possible combinations luckily don't exist:
    - `error-message` (hyphen, singular) is not present anywhere
    - `error_messages` is present once but probably as a typo #6577

**Comment by bpoldrack** [comment]
Hm. In my view it's not exactly a contradiction to say `error_messages` is allowed in result record and `get_status_dict` taking a single `error_message`. Both (a single str and a list of them) can be useful, I think and there's no fixed set of valid keys in a result dict. The meaningful aspect of listing keys in a doc is: What does a (default) result renderer understand? And: What are conventions for naming of things that are meaningful across commands? (like `path`)

However, reducing complexity (mental load required) certainly is beneficial.
I think we ultimately should have a dedicated class for results and make `get_status_dict` obsolete. With that we could settle for the singular case `error_message` and make the class deal with a plain `str` as well as a list of `str` (like `annexjson2result` does)

**Comment by bpoldrack** [comment]
> So IMO error_message should be documented.

Agree.

> In principle that's true, but - case in point - error_messages is a third alternative to error_message and error-messages that my issue was about ;-)

Phew - I once again missed that `-` in the first sentence of you original post. So yes - that should be corrected to document the things that actual code (renderer, `get_status_dict`) does in fact understand.
