### ISSUE TITLE
Annexrepo: `error_message` vs `error-messages` in `get_content_info`

### ISSUE THREAD

**Issue by mslw** [datalad/datalad#6621]
While grepping for `error_message` to investigate #6620 I came upon this recently merged piece, and I'm not sure if there isn't a misnomer:

https://github.com/datalad/datalad/blob/6b4280dcb3e31a2efc6b8d8be544655c08992982/datalad/support/annexrepo.py#L3397-L3402

In this case, `j` comes from `self.call_annex_records(cmd, files=files)` I'm not sure about the context, but it looks like:
- all key/value pairs, except `error_messages` get copied from git-annex record to `rec`
- accordingly, comment then says "change annex' `error_messages` into singular to match result records
- then the content of `error-messages` is pieced together and written to `error_message`

AFAIK git-annex returns `error-messages`, and I'm not sure if `error_messages` can be present at all. and if I'm reading the code correctly, then the `error-messages` field (containing a list) will pass the initial check, and will be included alongside the `error_message` field (containing a string). The intention may have been to do so, but it looks to me like the conditional and comment were meant to say `error-messages`.

@bpoldrack sorry to bring this comment a week after the PR was merged, but since you worked with this code recently, could you verify what was the intention? In case I misunderstood, sorry for the buzz.

**Comment by bpoldrack** [comment]
@mslw :

Looks like you are right. There's a confusion about `-` vs `_`. Intention is to do the same as `get_status_dict`, while what this is producing are not yet proper result dicts (those records here are further processed before anything becomes an actual result).

In short:

> but it looks to me like the conditional and comment were meant to say error-messages.

That's correct.

**Comment by adswa** [comment]
With #6624 merged I think this is fixed.
