### ISSUE TITLE
allow to specify/handle redirects to login pages so connection is re-established and then go back to original url

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#663]
e.g. NITRC if I guess cookie is no longer good, fails the session and redirects to e.g. 
https://www.nitrc.org/account/login.php?return_to=%2Ffrs%2F%3Fgroup_id%3D404&feedback=Please%20log%20in%20to%20download%20file

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
