### ISSUE TITLE
`create` is too noisy

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6633]
Every invocation produces this INFO-level message:

```
% datalad create myds
[INFO   ] Creating a new annex repo at /tmp/myds
create(ok): /tmp/myds (dataset)
```

This is not a long-running operation. In most cases, the INFO log and the result arrive near-simultaneously.

I would have argued that this should be a DEBUG message, but at DEBUG level we already have this

```
[INFO   ] Creating a new annex repo at /tmp/demo12 
[DEBUG  ] Initialize empty Git repository at '/tmp/demo12' 
[DEBUG  ] Initializing annex repository at /tmp/demo12... 
```

I think this is noise and should be removed.

**Comment by adswa** [comment]
With  #6638 merged I think this can be closed
