### ISSUE TITLE
Confusion between inputs and outputs with datalad run: inputs should be unlocks and info message should be consistent

### ISSUE THREAD

**Issue by arovai** [datalad/datalad#6643]
### What is the problem?

As far as I understand, datalad run with --input and --output options doesn't work as I (naively?) expected. I have a workflow in which some files are only needed with ro permissions (my inputs) and some new stuff will be written in some other empty folder.
Hence I naively set my input files using the --input option, but this doesn't work as my workflow is unable to find the files. (Here `datalad get` is not the issue, everything is already locally present by the way).
To be more explicit: when using datalad run without the --output option clearly doesn't unlock the input files, which is what I would expect (to avoid the clutter I simplified the commands quite a lot, see additional info below for the complete commands)
Command:
```
datalad run --input somefile.gz "myworkflowcmd somefile.gz output_dir"
```
Output:
```
[INFO   ] Making sure inputs are available (this may take some time) 
[INFO   ] == Command start (output follows) ===== 
```
Now I run the same command with the addition of the --output option, in which I pass my actual input files, and there datalad unlock my files:
Command:
```
datalad run --input somefile.gz --output somefile.gz "myworkflowcmd somefile.gz output_dir"
```
```
[INFO   ] Making sure inputs are available (this may take some time) 
unlock(ok): somefile.gz (file)
[INFO   ] == Command start (output follows) ===== 
```
So:
1. my inputs are not unlocked by using the mere --input option, which is counter-intuitive
2. the arguments given in the --output options are unlocked, which is fine, but they are listed as "input files" in the datalad run INFO prints

### What steps will reproduce the problem?

SEE ABOVE

### Datalad information

Using Datalad 0.15.5

### Additional context

neuroimaging
Commands (with some cleaning to that has nothing to do with datalad):
Without --output option:
```
datalad run  --input "rawdata/sub-001"  "singularity run -B rawdata:/data:ro -B derivatives:/derivatives:rw  --cleanenv fmriprep.sif /data /derivatives participant --participant-label 001"
```
With the --output option:
```
datalad run  --input "rawdata/sub-001" --output "rawdata/sub-001" "singularity run -B rawdata:/data:ro -B derivatives:/derivatives:rw  --cleanenv fmriprep.sif /data /derivatives participant --participant-label 001"
```

### Have you had any success using DataLad before?

oh yes

**Comment by mih** [comment]
Hey, thx for the report. Would you mind including the actual commands in your post, it is not clear to me how they differ exactly. Thx!

**Comment by arovai** [comment]
> Hey, thx for the report. Would you mind including the actual commands in your post, it is not clear to me how they differ exactly. Thx!

OP updated!

**Comment by mih** [comment]
Thx. I think the key statement is

> To be more explicit: when using datalad run without the --output option clearly doesn't unlock the input files, which is what I would expect

Why would you expect the *input* files to be unlocked -- which is to ready them for being written to?

Maybe this is the reason:

> but this doesn't work as my workflow is unable to find the files

Why is that? Is the workflow unable to deal with symlink?

**Comment by arovai** [comment]
I think the issue is that I work with a singularity image. Mounting the volumes as I did only mounts the directories with the symblinks, so they are effectively broken once inside the container. So yes you are right, my workflow is unable to deal with symlinks for now...
I guess another solution would be to mount the whole dataset in my container, including git-annex hidden stuff. For some reason I feel this is a bit too hacky but I see no other way, do you? In my dreams I never have to think about all those hidden files when working within datalad framework.

**Comment by arovai** [comment]
> 

`datalad-container` sounds like what I need, thanks for pointing this to me!
I am pretty sure the issue has nothing to do with json files as those are not in the git-annex and unlocking/symlinks resolution really is the core of the difficulty I encountered.

**Comment by adswa** [comment]
I believe this issue can be closed. From re-reading the discussion, it seems it was rather related to bindmounts in containers than the --input and --output option of run. I hope the containers extension was able to fix this problem for you, @arovai - if not, or if I am mistaken in closing this, please feel free to open a new issue or re-open this one.
