### ISSUE TITLE
remove  eval_file_type  from "internal" interfaces? -- deprecated at AnnexRepo level, unused

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6652]
became annoying in #6273

**Comment by adswa** [comment]
I believe it was deprecated in the wake of https://github.com/datalad/datalad/issues/6084, i.e., within the 15.x series. Can it be removed completely for ``0.17``? I would propose a PR if so

I only found usage of it in one extension:
```grep
datalad-ukbiobank: datalad_ukbiobank/update.py:201:                eval_file_type=False):
```
