### ISSUE TITLE
a small unittest to verify entry of credentials if none known but authentication is needed

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#666]
this part of the PR which I will merge https://github.com/datalad/datalad/pull/665/files#diff-94c99be6f1de0ca7ce49cee9457ced82R82  

you can e.g. use `@with_testsui` to provide responses.

it is a really small test to do (straight on an instance) but would allow you to get hands dirty into all this downloaders/authentication business ;)

**Comment by debanjum** [comment]
#669 closes this

**Comment by yarikoptic** [comment]
Then let's have it closed since that PR was merged
