### ISSUE TITLE
follow redirect for Cleveland

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#668]
ok -- merged #658 but now we need to improve that pipeline so we do follow redirect for Cleveland dataset.  You could e.g. create a subpipeline right before annex call, which should return its all outputs (do you remember there is a way to configure subpipelines with dictionary in first entry of the pipeline), and then continue_if dataset name is Cleveland, then crawl that url and match tarball url(s)

**Comment by glalteva** [comment]
closed by #670
