### ISSUE TITLE
datalad clone from RIA yields empty dataset

### ISSUE THREAD

**Issue by mgamble** [datalad/datalad#6686]
### What is the problem?

Even in the case of the simplest non-empty dataset put into an RIA, datalad will only clone an empty repo out of it. It's entirely possible that this is my error, but if so I have no idea what it could be. I feel like I followed the DataLad Handbook to the letter. 

All reports working prior to cloning the dataset where I get this message:
```
[WARNING] You appear to have cloned an empty repository.
[WARNING] Cloned /home/mgamble/clonedDS/test but could not find a branch with commits
install(ok): /home/mgamble/clonedDS/test (dataset)
```

It was not empty to start. And it certainly had a master branch as can be seen here:
```
(base) ~/datasets/test$ ls -la
total 24
drwxr-xr-x 4 mgamble mgamble 4096 May  6 22:31 .
drwxr-xr-x 3 mgamble mgamble 4096 May  6 22:31 ..
drwxr-xr-x 2 mgamble mgamble 4096 May  6 22:31 .datalad
drwxr-xr-x 9 mgamble mgamble 4096 May  6 22:32 .git
-rw-r--r-- 1 mgamble mgamble  115 May  6 22:31 .gitattributes
-rw-r--r-- 1 mgamble mgamble   21 May  6 22:31 notes.txt


(base) ~/datasets/test$ git log --oneline
2ce541c (HEAD -> master) add test note
6070648 Instruct annex to add text files to Git
451655c [DATALAD] new dataset
```

### What steps will reproduce the problem?

```
mkdir datasets
mkdir riaTest
mkdir clonedDS
cd datasets
datalad create -c text2git -D "test in datasets" test
cd test
cat << EOT > notes.txt
This is a test note.
EOT
datalad save -m "add test note"
datalad create-sibling-ria -s riaTest --alias test --new-store-ok "ria+file:///home/mgamble/riaTest"
cd ../../clonedDS
datalad clone "ria+file:///home/mgamble/riaTest#~test"
```

### Datalad information

datalad --version
datalad 0.16.2

datalad wtf
# WTF
## credentials
  - keyring:
    - active_backends:
      - libsecret Keyring
      - EncryptedKeyring with [PBKDF2] AES256.CFB v.1.0 at /home/mgamble/.local/share/python_keyring/crypted_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at /home/mgamble/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/mgamble/.config/python_keyring/keyringrc.cfg
    - data_root: /home/mgamble/.local/share/python_keyring
## datalad
  - version: 0.16.2
## dependencies
  - annexremote: 1.6.0
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 10.20220322-1~ndall+1
  - cmd:bundled-git: 2.30.2
  - cmd:git: 2.30.2
  - cmd:system-git: 2.25.1
  - cmd:system-ssh: 8.2p1
  - exifread: 2.1.2
  - git: 3.0.7
  - gitdb: 2.0.6
  - humanize: 1.0.0
  - iso8601: 0.1.12
  - keyring: 23.5.0
  - keyrings.alt: 3.4.0
  - msgpack: 0.6.2
  - mutagen: 1.44.0
  - platformdirs: 2.5.2
  - requests: 2.22.0
## environment
  - LANG: C.UTF-8
  - PATH: /home/mgamble/.local/bin:/home/mgamble/miniconda3/bin:/home/mgamble/miniconda3/condabin:/home/mgamble/.local/bin:/home/mgamble/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Perl64/bin:/mnt/c/Users/matth/AppData/Roaming/ActiveState/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program Files (x86)/Wolfram Research/WolframScript:/mnt/c/D/dmd2/windows/bin:/mnt/c/Program Files/PuTTY:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Pandoc:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program Files/dotnet:/mnt/c/Users/matth/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/matth/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/texlive/2021/bin/win32:/mnt/c/Program Files/Onivim2:/snap/bin
## extensions
  - container:
    - description: Containerized environments
    - entrypoints:
      - datalad_container.containers_add.ContainersAdd:
        - class: ContainersAdd
        - load_error: None
        - module: datalad_container.containers_add
        - names:
          - containers-add
          - containers_add
      - datalad_container.containers_list.ContainersList:
        - class: ContainersList
        - load_error: None
        - module: datalad_container.containers_list
        - names:
          - containers-list
          - containers_list
      - datalad_container.containers_remove.ContainersRemove:
        - class: ContainersRemove
        - load_error: None
        - module: datalad_container.containers_remove
        - names:
          - containers-remove
          - containers_remove
      - datalad_container.containers_run.ContainersRun:
        - class: ContainersRun
        - load_error: None
        - module: datalad_container.containers_run
        - names:
          - containers-run
          - containers_run
    - load_error: None
    - module: datalad_container
    - version: 1.1.6
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
    - 9
    - 10
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20220322-1~ndall+1
## location
  - path: /home/mgamble/clonedDS
  - type: directory
## metadata_extractors
  - annex:
    - distribution: datalad 0.16.2
    - load_error: None
    - module: datalad.metadata.extractors.annex
  - audio:
    - distribution: datalad 0.16.2
    - load_error: None
    - module: datalad.metadata.extractors.audio
  - datacite:
    - distribution: datalad 0.16.2
    - load_error: None
    - module: datalad.metadata.extractors.datacite
  - datalad_core:
    - distribution: datalad 0.16.2
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
  - datalad_rfc822:
    - distribution: datalad 0.16.2
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
  - exif:
    - distribution: datalad 0.16.2
    - load_error: None
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage:
    - distribution: datalad 0.16.2
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
  - image:
    - distribution: datalad 0.16.2
    - load_error: None
    - module: datalad.metadata.extractors.image
  - xmp:
    - distribution: datalad 0.16.2
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## python
  - implementation: CPython
  - version: 3.8.10
## system
  - distribution: ubuntu/20.04/focal
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 278
  - name: Linux
  - release: 5.10.102.1-microsoft-standard-WSL2
  - type: posix
  - version: #1 SMP Wed Mar 2 00:30:59 UTC 2022

### Additional context

I have gotten this error under two versions of Ubuntu (focal) running in WSL2 on Windows 11 (as shown above) on two separate computers, as well as on an HPC running Red Hat - rhel (Ootpa) with a "crippled filesystem" (apparently the HPC doesn't support locked files, even though its Linux). All give exactly the same "warning" and clone an empty repo.

### Have you had any success using DataLad before?

Normal cloning from one dataset to another works just fine. This seems only to be a problem when using an RIA. 

I'm new to datalad and this may very well be my error. I really loved reading the datalad handbook. It really made me want to implement this system in my lab and introduce it to my institution. I hope there is a quick fix, so I can continue on the journey.

**Comment by adswa** [comment]
Hey, thanks for the issue. I think the dataset in the store is empty because you didn't yet push dataset contents. Try `datalad push --to riaTest` before cloning.

**Comment by mgamble** [comment]
@adswa Thank you so much. That did the trick! I had assumed that the create-sibling-ria command would push the first round of data. Stupid mistake on my part. This was so helpful. Thank you for being so responsive and reaching out so quickly. I'll have the whole lab using datalad before long. Have a great weekend!
