### ISSUE TITLE
Failing doctests 

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#6715]
The doctests started failing today with

```
Warning, treated as error:
Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
make: *** [Makefile:50: html] Error 2
make: Leaving directory '/home/runner/work/datalad/datalad/docs'
Error: Process completed with exit code 2.
```

This is due to [today's release of Sphinx 5.0](https://www.sphinx-doc.org/en/master/changes.html#release-5-0-0-released-may-30-2022) which comes with https://github.com/sphinx-doc/sphinx/issues/10474 that disallows the
``language = None`` configuration we currently still use.

**Comment by adswa** [comment]
I have plastered all extensions I could find with PRs about this.

**Comment by yarikoptic** [comment]
Thank you @adswa for all the fixes and digging the sphinx issue up! 

FTR: sphinx developers seems have addressed the issue as well by making it into a warning (more legit way to handle IMHO): https://github.com/sphinx-doc/sphinx/issues/10474#issuecomment-1140389657 .
