### ISSUE TITLE
add a mode where publish doesn't even try to publish if local information says that current state was already published

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#674]
now it tries to do that anyways... which takes time.  In the simplest usecase it should see that remote/master is the same as local master and shouldn't even try.  May be there is some way to make 'git push' do that

**Comment by yarikoptic** [comment]
didn't find anything in git push, and probably we shouldn't do it manually but may be GitPython could provide us information on what branches, given refspecs for pushing in .git/config, would be pushed and then compare if anyhow different

**Comment by mih** [comment]
This is now the default (and only) behavior in #1203

**Comment by mih** [comment]
Merged.
