### ISSUE TITLE
`export-archive` fails on dataset with subdatasets, only if run from a subdirectory

### ISSUE THREAD

**Issue by catetrai** [datalad/datalad#6741]
### What is the problem?

When running `datalad export-archive` on a dataset that has subdatasets, the command works if run from the dataset root, but fails if run from a subdirectory:

```shell
cd subdir && datalad export-archive export.tar.gz
[ERROR  ] expected str, bytes or os.PathLike object, not NoneType (TypeError) 
```

### What steps will reproduce the problem?

```shell
(
# Create dataset with a subdirectory
datalad create test-export-bug
cd test-export-bug
mkdir subdir
echo test > subdir/test-file.txt && datalad save -m "add file to subdir"

# Works if no subdatasets exists
tar_no_subds="/tmp/datalad-export-no-subds.tar.gz"
(cd subdir && datalad export-archive $tar_no_subds)

# Fails (creates empty tar file) if a subdataset exists
datalad create -d . subds
tar_with_subds="/tmp/datalad-export-with-subds.tar.gz"
(cd subdir && datalad export-archive $tar_with_subds)
[[ -z "$(tar -tf $tar_with_subds)" ]] && echo "$tar_with_subds: empty tar file"
)
```

### Datalad information

<details><summary>datalad wtf</summary>
<p>

# WTF
## credentials 
  - keyring: 
    - active_backends: 
      - PlaintextKeyring with no encyption v.1.0 at /home/ct/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/ct/.config/python_keyring/keyringrc.cfg
    - data_root: /home/ct/.local/share/python_keyring
## datalad 
  - version: 0.16.3
## dependencies 
  - annexremote: 1.5.0
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 10.20220525-gf1fdc90
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.35.3
  - cmd:system-git: 2.35.3
  - cmd:system-ssh: 9.0p1
  - exifread: 3.0.0
  - humanize: 4.1.0
  - iso8601: 1.0.2
  - keyring: 23.5.1
  - keyrings.alt: 4.0.2
  - msgpack: 1.0.3
  - mutagen: 1.45.1
  - platformdirs: 2.5.1
  - requests: 2.27.1
## environment 
  - LANG: en_US.utf-8
  - LC_ALL: en_US.utf-8
  - LC_CTYPE: UTF-8
  - PATH: /home/ct/conda/yes/envs/datalad/bin:/home/ct/conda/yes/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ct/.local/bin:/home/ct/bin
## extensions 
  - container: 
    - description: Containerized environments
    - entrypoints: 
      - datalad_container.containers_add.ContainersAdd: 
        - class: ContainersAdd
        - load_error: None
        - module: datalad_container.containers_add
        - names: 
          - containers-add
          - containers_add
      - datalad_container.containers_list.ContainersList: 
        - class: ContainersList
        - load_error: None
        - module: datalad_container.containers_list
        - names: 
          - containers-list
          - containers_list
      - datalad_container.containers_remove.ContainersRemove: 
        - class: ContainersRemove
        - load_error: None
        - module: datalad_container.containers_remove
        - names: 
          - containers-remove
          - containers_remove
      - datalad_container.containers_run.ContainersRun: 
        - class: ContainersRun
        - load_error: None
        - module: datalad_container.containers_run
        - names: 
          - containers-run
          - containers_run
    - load_error: None
    - module: datalad_container
    - version: 1.1.4
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.29
    - DAV-1.3.4
    - feed-1.3.2.0
    - ghc-8.10.7
    - http-client-0.7.9
    - persistent-sqlite-2.13.0.3
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.1.2
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
    - 9
    - 10
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20220525-gf1fdc90
## location 
  - path: /home/ct/mri/sdn/datalad-datasets
  - type: directory
## metadata_extractors 
  - annex: 
    - distribution: datalad 0.16.3
    - load_error: None
    - module: datalad.metadata.extractors.annex
  - audio: 
    - distribution: datalad 0.16.3
    - load_error: None
    - module: datalad.metadata.extractors.audio
  - datacite: 
    - distribution: datalad 0.16.3
    - load_error: None
    - module: datalad.metadata.extractors.datacite
  - datalad_core: 
    - distribution: datalad 0.16.3
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
  - datalad_rfc822: 
    - distribution: datalad 0.16.3
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
  - exif: 
    - distribution: datalad 0.16.3
    - load_error: None
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - distribution: datalad 0.16.3
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
  - image: 
    - distribution: datalad 0.16.3
    - load_error: None
    - module: datalad.metadata.extractors.image
  - xmp: 
    - distribution: datalad 0.16.3
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.9.13
## system 
  - distribution: centos/7/Core
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 289
  - name: Linux
  - release: 3.10.0-1160.66.1.el7.x86_64
  - type: posix
  - version: #1 SMP Wed May 18 16:02:34 UTC 2022

</p>
</details>

### Have you had any success using DataLad before?

Novice but having a lot of fun with it!

**Comment by adswa** [comment]
Thanks much for the issue and the reproducer! I think this part of the code base has quite a few corpses in the basement, and I think at least one that has risen from the dead in this issue might have been introduced in 8476b08. I have only looked at it briefly - a change to a more modern approach with ``pathlib`` to that piece of code makes it work, but I will dedicate some time tomorrow for a closer look, I feel like quite a bit in there can be improved. Ping https://github.com/datalad/datalad/issues/4595 - I believe the code in question was on a list to be replaced for a while.

**Comment by catetrai** [comment]
Thank you for the quick fixing. Keep up the great work!
