### ISSUE TITLE
Documentation and behavior of datalad.log.traceback misleading

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6744]
It says

> Runs TraceBack function with collide set to True, if this flag is set to "collide". This replaces any common prefix between current traceback log and previous invocation with "..."

First issue is that setting this as a config item has no impact. It is only considered as an environment variable `DATALAD_LOG_TRACEBACK`

Next issue:

```
% DATALAD_LOG_TRACEBACK=1 dl -l debug status
[DEBUG  ] ...>log:223  Command line args 1st pass for DataLad 0.16.2+190.gd657c17fe. Parsed: Namespace() Unparsed: ['status'] 
[DEBUG  ] ...>log:223  Parsing known args among ['/home/mih/env/datalad-dev/bin/datalad', '-l', 'debug', 'status'] 
```

Running with `DATALAD_LOG_TRACEBACK=1` seem not very useful, although the docs do not promise that either ... "with collide=True". The traceback always and exclusively points to the logging code.

Changing this to `DATALAD_LOG_TRACEBACK=collide` still includes the meaningless log stack level, but also informative bits.

```
% DATALAD_LOG_TRACEBACK=collide dl -l debug status
[DEBUG  ] datalad:33>main:86>parser:119,369>log:223  Command line args 1st pass for DataLad 0.16.2+190.gd657c17fe. Parsed: Namespace() Unparsed: ['status'] 
[DEBUG  ] ...>main:94>log:223  Parsing known args among ['/home/mih/env/datalad-dev/bin/datalad', '-l', 'debug', 'status'] 
```

Looking at the first message, it seems that the name `datalad` should be added to the exceptions in `mbasename()`. It is not clear that this is the cmdline entrypoint script.

**Comment by yarikoptic** [comment]
We already filter out the parts of the traceback which comes from `logging` and even `unittest` at https://github.com/datalad/datalad/blob/HEAD/datalad/log.py#L74 . That `log` is our https://github.com/datalad/datalad/blob/HEAD/datalad/log.py#L223  `emit` function. I guess we could filter it out too if so desired... I agree it would be better -- will submit a PR shortly.

NB unrelated, according to hightlighting of coverage in the browser that entire code block for when we do encounter `dlm_progress` is not covered at all... that is odd.
