### ISSUE TITLE
Ensure semantics of `gitrepo.call_git_items_()` did not change from 0.15.6 to 0.16.0

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad#6766]
`GitRepo.call_git_items_()` yields git-command output that is split on line-ends or custom-separators. PR #6754 highlighted the potential for semantic divergence between the new generator-based implementation of `GitRepo.call_git_items_()` and the old version of `GitRepo.call_git_items_()`.

We have to ensure that the new implementation yields a result that is compatible with the old implementation. Only then can we be sure that the caller of the function will exhibit the same semantics.

**Comment by christian-monch** [comment]
There is a difference between the old and new implementation that was consciously introduced. The new implementation will treat line-end-separators and custom-separators identically. More precisely, if the output of a git command ends with a custom-separator, the old implementation returned an additional empty line. The new implementation will not return the additional empty line, and therefore unify the splitting behavior with line-endings and custom-separators.

The only custom separator that is used in datalad code 0.16.6 is "\0", i.e. a zero-byte. All usage of the "\0" separator will ignore a missing additional empty line.

**Comment by yarikoptic** [comment]
I assume it was fixed in `maint` and not auto-closed
