### ISSUE TITLE
Fix a race condition in ssh copy test

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad#6798]
The test `datalad.support.tests.test_sshconnector.test_ssh_copy` introduces a race condition by copying a file onto itself. This sometimes leads to an empty file and a failing test.

**Comment by yarikoptic** [comment]
Part of https://github.com/datalad/datalad/issues/6655 . Emptying is a behavior of new versions of ssh

**Comment by bpoldrack** [comment]
I think this aspect is actually addressed in #6799
