### ISSUE TITLE
DOC: document RIA URL format and versioning options

### ISSUE THREAD

**Issue by bpinsard** [datalad/datalad#6800]
### What is the problem?

http://docs.datalad.org/en/stable/generated/datalad.api.install.html mentions the possibility to install from RIA store with checkout of a specific version.

> branch (str or None, optional) – Clone source at this branch or tag. This option applies only to the top-level dataset not any subdatasets that may be cloned when installing recursively. **Note that if the source is a RIA URL with a version, it takes precedence over this option**

I couldn't find the full syntax for RIA url anywhere (handbook, doc, google, ...). Adding `@something` to a working URL seems to look for a branch with that name, seems not to work for other tree-ish (commit, tag). 
It might be worth improving documentation on these options.
Thanks! 

### What steps will reproduce the problem?

NA

### Datalad information

0.16.1

### Have you had any success using DataLad before?

Yes, a lot :)

**Comment by adswa** [comment]
I agree that this needs documentation. I'll check where I can put it in the handbook when I get a chance. I think it should be somewhere in docs.datalad.org, too, though. @bpoldrack, what do you think could be the best place for that? ``install`` or  ``clone`` now work with more and more protocols and can't possibly document all of them, but maybe the docstring of ``create-sibling-ria``?

**Comment by adswa** [comment]
quick ping for @bpoldrack - any thoughts on this?

**Comment by adswa** [comment]
this was done in https://github.com/datalad/datalad/pull/6861
