### ISSUE TITLE
Is there a way to manually change the repo description via create-sibling-github?

### ISSUE THREAD

**Issue by jbwexler** [datalad/datalad#6816]
https://github.com/datalad/datalad/blob/9cec945af3acebd319825ef9570e74e187596ace/datalad/distributed/create_sibling_ghlike.py#L454

Currently it's set to 'some default' by default. I plan to use gh to edit this after pushing to github, but it would be nice to be able to do this with a flag in create-sibling-github.

**Comment by yarikoptic** [comment]
nice find. BTW -- feel welcome to submit a PR to add that functionality.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.0`](https://github.com/datalad/datalad/releases/tag/0.18.0)
