### ISSUE TITLE
"Fusion" approach to changelog generation

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6856]
Had to look how bids-specification deals with [src/CHANGES.md](https://github.com/bids-standard/bids-specification/blob/HEAD/src/CHANGES.md) generation: coded in https://github.com/bids-standard/bids-specification/blob/HEAD/.circleci/config.yml#L176 . In a nutshell critical difference is that workflow produces/commits/pushes changelog entry as soon as PR is merged.  This way I think it should be feasible to satisfy everyone 

- we can have autogenerated changelog and quick releasing from PRs as we do now
- we can tool it so it could pickup optionally present in the PR description changelog entry (instead of a title) if so desired
- those who strive for better worded changelog can submit PR/change it while it is all still for `Unreleased` version

Cons: 
- extra commit in target branch for every changelog entry addition (since automated -- I do not really care, FWIW could even be a fancy `datalad run` record)
- we might need/want to agree to keep merge record default as the `Merge pull request #PR` so it could be parsed.  Gotcha can happen if someone pushes some merge from another repo.   But since it is ok to change/modify then before release -- could be fixed.

Notes:
- a typical problem with "manual" changelog modifications in PRs is conflicts (two PRs modify conflicting lines in the same CHANGELOG.md). This approach avoids the conflicts since done by bot.
- *race condition*, in case of rapid merges of two PRs , two runs could compete for pushing new record... smart tool, upon forbidden push, would instead of `reset --hard HEAD^ `, `git pull --ff-only`, and redo addition for that PR it was working on, and then try to push again.  I think this way we can make it "race proof"

We would just need a tool to help adding changelog entries with similar to `auto` sectioning awareness.  There might already be one.  Can research more later into this but first thought to check what @datalad/developers think about this.

edit: may be could be a happy marriage with the `scriv` which @mih at all test-driving for https://github.com/datalad/datalad-next but `scriv` entries auto-produced from PR upon merge/pushed unless PR did provide a scriv entry!?  Then `release` workflow would call `scriv` to compile actual CHANGELOG record.

**Comment by yarikoptic** [comment]
question to @jwodder : if we pre generate CHANGELOG for a release, `auto shipit` still can be used to do the rest (upload to pypi/github releases).

**Comment by jwodder** [comment]
@yarikoptic Yes, `auto shipit` has a `--no-changelog` option to skip creating the changelog.

**Comment by yarikoptic** [comment]
Does it then take version from changelog or it still mints new version based on PR labels, and we would need to update/make sure that version in ChangeLog matches the one which `auto` expects it to be?

**Comment by jwodder** [comment]
@yarikoptic auto only ever calculates the version based on PR labels.

**Comment by adswa** [comment]
I'm flexible to adapt, it sounds good. I think scriv produces sections in the way we typically structure them. It would be cool if we can teach it to append PR author and  # as done in BIDS. One question that came to my mind: how would we annotate PRs that don't need a CHANGELOG entry?

**Comment by mih** [comment]
In `-next` I use the following template

```
### {{ cat }}

- Describe change, possibly reference closed/related issue/PR.
  Fixes https://github.com/datalad/datalad-next/issues/XXX via
  https://github.com/datalad/datalad-next/pull/XXX (by @GITHUBHANDLE)
```

Any PR that needs a changelog, will have a changelog item in `changelog.d`. Some automation could fill in the last line

```
https://github.com/datalad/datalad-next/pull/XXX (by @GITHUBHANDLE)
```

possibly by replacing a placeholder, and only when that placeholder exists.

The important thing for a changelog is not which PR claimed to fix an issue, but which issue was fixed. There are cases where it needs multiple PRs to actually fix a single issue, there should not be multiple changelog entries in this case. Subsequent PRs can also modify the changelog items for all changes that have not yet been released -- by simply editing the files in `changelog.d/`.

For `next` I am considering to stop adding the PR links entirely. Github is clever enough to make them discoverable via the respective issues. Likewise for the authorship info: statistics are nice, but I am not convinced that the changelog is the place for that. Adding a list of people who contributed to a release is more easily done with a dedicated query at release time. It would additionally also include people who contributed to a PR, but did not open it.

**Comment by yarikoptic** [comment]
just a clarification that we do not need a "bot" per se -- it is just to be a github action reacting on change of labels (like we already have for `semver-` labels presence check) and generating that snippet with/for `scriv`

**Comment by mih** [comment]
When this is done, a patch similar to this one should be applied to the appveyor config (maybe there is something similar for travis):

```diff
diff --git a/.appveyor.yml b/.appveyor.yml
index 6aa19c4..64f9e7f 100644
--- a/.appveyor.yml
+++ b/.appveyor.yml
@@ -157,6 +157,7 @@ matrix:
 skip_commits:
   files:
     - docs/
+    - changelog.d/
 
 
 # it is OK to specify paths that may not exist for a particular test run
```

**Comment by bpoldrack** [comment]
> maybe there is something similar for travis

Closest I could find is an approach like this (so, nothing built-in): https://github.com/google/EarlGrey/pull/383/files/3b38a5dea36a88aba42a42931e77a7c5429a1837

However, I've pushed the suggestion for appveyor in PR #7208.
I think this issue can be closed then or do you think there's further discussion needed ATM, @yarikoptic?

**Comment by bpoldrack** [comment]
Skipping changelog commits rejected (see https://github.com/datalad/datalad/pull/7208).

Otherwise I think we've settled on a procedure for now. Let's see how the 0.18 series goes.
