### ISSUE TITLE
DOC: create-sibling-ria lacks examples

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#6860]
Related to #6800, I noticed that the typical ``examples`` that commands have is lacking in ``create-sibling-ria``. We should add a few, maybe even copy a few from [handbook.datalad.org/en/latest/r.html?RIA](http://handbook.datalad.org/en/latest/beyond_basics/101-147-riastores.html#riastore).

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.0`](https://github.com/datalad/datalad/releases/tag/0.18.0)
