### ISSUE TITLE
Implement support for unsetting a config item via `datalad -c ...`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6863]
https://github.com/datalad/datalad/issues/5653#issuecomment-1190069481 illustrates how this feature is missing for homogeneous support. It also points to the syntax used by `datalad credentials` for property unsetting, which could be adopted for this purpose.

A possible patch to add this feature would be

```diff
diff --git a/datalad/cli/helpers.py b/datalad/cli/helpers.py
index b657b6558..b20c467a4 100644
--- a/datalad/cli/helpers.py
+++ b/datalad/cli/helpers.py
@@ -255,17 +255,23 @@ def _parse_overrides_from_cmdline(cmdlineargs):
     # errors: we need a section, a variable, and a value at minimum
     # otherwise we break our own config parsing helpers
     # https://github.com/datalad/datalad/issues/3451
-    noassign_expr = re.compile(r'[^\s]+\.[^\s]+=[\S]+')
+    assign_expr = re.compile(r'[^\s]+\.[^\s]+=[\S]+')
+    unset_expr = re.compile(r':[^\s]+\.[^\s=]+')
     noassign = [
         o
         for o in cmdlineargs.cfg_overrides
-        if not noassign_expr.match(o)
+        if not (assign_expr.match(o) or unset_expr.match(o))
     ]
     if noassign:
         lgr.error(
             "Configuration override without section/variable "
-            "or value assignment (must be 'section.variable=value'): %s",
+            "or unset marker or value assignment "
+            "(must be '[:]section.variable[=value]'): %s",
             noassign)
         sys.exit(3)
-    overrides = dict(o.split('=', 1) for o in cmdlineargs.cfg_overrides)
+    overrides = dict(
+        [o[1:], None] if o.startswith(':')
+        else o.split('=', 1)
+        for o in cmdlineargs.cfg_overrides
+    )
     return overrides

```

**Comment by yarikoptic** [comment]
FWIW my few cents: a quick summary for myself from https://github.com/datalad/datalad/issues/5653#issuecomment-1190069481 and patch above: unsetting could be done via appending `:` to the config variable name i.e. `-c :user.name`.  
Sounds good and even inline semantically with `git push remote :delete-this-ref` . 

Looking at how we override via env vars, I thought also to suggest something like `--config-overrides-json JSON` support to parallel/expose `DATALAD_CONFIG_OVERRIDES_JSON` as CLI option, but I guess it is largely not needed.

**Comment by mih** [comment]
OK, I will propose a PR with a fix for this issue. 

With respect to the overrides JSON specification, this could also be done without a dedicated option (again following `datalad credentials`). I may or may not attempt an implementation in the coming PR.
