### ISSUE TITLE
when multiple publish-depends remotes, only one is used

### ISSUE THREAD

**Issue by LoannPeurey** [datalad/datalad#6867]
### What is the problem?

`datalad push --to origin` with origin having multiple 'remote.origin.datalad-publish-depends' only takes into consideration one of the sibling it should push to when I try to push

The push is done correctly on one of the 'publish-depends' remote and on the origin remote but nothing is pushed to the other 'publish-depends' remote.

After looking up what could have gone wrong :
https://github.com/datalad/datalad/blob/4f7735f7937c36da37b1c5fa2b8fc24b599cca5f/datalad/core/distributed/push.py#L499-L501
To me, it looks like the `ds.config.get(depvar, [])` only returns one value.

So I think replacing the line with:
```python
publish_depends = ensure_list(ds.config.get(depvar, [], get_all=True))
```
would solve the problem

### What steps will reproduce the problem?

```bash
#create a new dataset
datalad create dataset
cd dataset

# link to origin , public and confidential remotes (I used only GIN repositories)
datalad siblings add -s origin --url git@gin.g-node.org:/Loann_Peurey/test.git
datalad siblings add -s public --url git@gin.g-node.org:/Loann_Peurey/test-public.git
datalad siblings add -s confidential --url git@gin.g-node.org:/Loann_Peurey/test-confidential.git

# set publish-depends for origin to push to public and confidential
datalad siblings configure -s origin --publish-depends public --publish-depends confidential

# push to origin
datalad push --to origin
# => this only pushed to origin and public in my case.
```

## datalad
  - datalad 0.15.6
## git annex
  - git-annex version: 10.20220222-g8b42e3e
## python 
  - implementation: CPython
  - version: 3.7.12
## system 
  - distribution: debian/bullseye/sid
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 288
  - name: Linux
  - release: 5.15.0-41-generic
  - type: posix
  - version: #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022

### Additional context

content of `git/config`
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[annex]
        uuid = 5efda5a7-c095-4ada-8b39-0230e22b126f
        version = 8
[filter "annex"]
        smudge = git-annex smudge -- %f
        clean = git-annex smudge --clean -- %f
[remote "origin"]
        url = git@gin.g-node.org:/Loann_Peurey/test.git
        fetch = +refs/heads/*:refs/remotes/origin/*
        annex-ignore = false
        annex-uuid = 30cf6df3-8145-431b-aeb5-a157ffb32237
        datalad-publish-depends = confidential
        datalad-publish-depends = public
[branch "main"]
        remote = origin
        merge = refs/heads/main
[remote "confidential"]
        url = git@gin.g-node.org:/Loann_Peurey/test-confidential.git
        fetch = +refs/heads/*:refs/remotes/confidential/*
        annex-ignore = false
        annex-uuid = ab8b01c8-2de8-4551-b31b-419fa56b446d
[remote "public"]
        url = git@gin.g-node.org:/Loann_Peurey/test-public.git
        fetch = +refs/heads/*:refs/remotes/public/*
        annex-ignore = false
        annex-uuid = 5e1760fc-0023-425e-b276-8f738820e872
```
output of `git config`
```bash
~/dataset$ git config --get-all remote.origin.datalad-publish-depends
public
confidential
```

### Have you had any success using DataLad before?

Have been using datalad for 6 months, managing datasets for a research lab.

**Comment by mih** [comment]
It seems that the code in `push` was written with the expectation that users would configure a single config item `remote.<name>.datalad-publish-depends`.

This is a reasonable expectation given the documentation in the Python docstring:

```
Multiple dependencies can be given as a list of sibling names
```

However, on the CLI help for `siblings` it says:

```
This option can be given more than once to configure multiple dependencies
```

and when done in this fashion, the unhandled condition is reached:

```
[remote "origin"]
        ...
        datalad-publish-depends = r1
        datalad-publish-depends = r2
```

In order to maintain behavior and fix the issue at hand, it seems we should `get_all=True` (as suggested by OP) and also consider each value to be a possible white space separated list (as before).

**Comment by LoannPeurey** [comment]
Thank you for looking into it and for the quick fix :+1:  !
