### ISSUE TITLE
Introduce type hints through-out + mypy testing.

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6884]
We have quite complex typing in places, and I think we would greatly benefit from type hints (instead of just documenting them in the docstrings in numpy notation) + adding mypy testing.

TODOs
- [ ] mypy on some files which are already annotated and/or clean (no errors) in mypy
- [ ] add to `CONTRIBUTING.md` instructions on "how" (since we support >= 3.7, some `__future__` imports etc could be needed etc).  Good example PRs:
    - https://github.com/datalad/datalad/pull/7317
    - https://github.com/datalad/datalad/pull/7318 
- [ ] type hints throughout the project
  - [x] #6889
  - [x] `datalad/utils.py`
  - [ ] `datalad/support` , in particular `*repo.py` classes since they are "the next core" in terms of importance IMHO
      - [x] `datalad/support/gitrepo.py`
      - [ ] `datalad/support/annexrepo.py`
  - [ ] `datalad/core` - the "core"
  - [ ] .... add yours ...
  - [ ] mypy plugin to support our dynamic "API interfaces" . [mypy docs](https://mypy.readthedocs.io/en/stable/extending_mypy.html)
- [ ] mypy entire `datalad`

Could be done slowly growing amount of type hints annotations. Probably should be done through commits to `maint` so we reduce possible conflicts in the long-to-release `master`. Alternatively/complimentary we could have a short "hinting hackathon".

WDYT @datalad/developers ?

**Comment by jwodder** [comment]
Note that datalad's dynamic loading of methods will not play nice with mypy.  At a certain point (I'm not sure what triggers type-checking of method calls; it may or may not be automatic for all classes), calling any dynamically-loaded method on a Dataset object in an annotated function will produce an error in mypy unless a `# type: ignore[attr]` comment is added to the line.  The proper way to deal with this is to write a dedicated mypy plugin for datalad, which is something I do not know how to do and for which the official documentation is rather lacking.

**Comment by yarikoptic** [comment]
Thank you @jwodder for the valuable feedback.  Added an item to the list. If you ever feel like discovering "how to" accomplish the mission on that, it would be awesome!

**Comment by yarikoptic** [comment]
> The proper way to deal with this is to write a dedicated mypy plugin for datalad, which is something I do not know how to do and for which the official documentation is rather lacking.

indeed https://mypy.readthedocs.io/en/stable/extending_mypy.html isn't very easy to "adopt" and didn't have any changes since last time we talked (so didn't improve).  Upon quick search through github https://github.com/search?p=5&q=%22from+mypy.plugin+import+Plugin%22&type=Code didn't find (well -- github bugs out on page 4 showing it blank) good possible examples to follow.  I think we can postpone that but good to know that there should be a way.

Meanwhile let's proceed with smaller pieces in lower level codes -- eg. `utils.py` and entirety of `support/`.  If we ignore the need for `mypy` plugin, the type annotation is relatively easy, and individual PRs could be submitted for individual components as we are amassing type annotations.

**Comment by jwodder** [comment]
Manually adding type annotations is time-consuming and mind-numbing.  Instead, I'm going to refer to <https://stackoverflow.com/a/50416746/744178>, which lists several tools for automatically adding type annotations to Python source, along with <https://github.com/google/pytype>, another tool for the same not listed in the first post.  I have not tried out any of these tools.

**Comment by mih** [comment]
I believe this can be closed now. Right?

**Comment by yarikoptic** [comment]
I guess let's close and let it evolve naturally
