### ISSUE TITLE
Check git annex' error  reporting

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#69]
By now this intended to be a reminder to figure things out.
Just stumbled upon a case where I git annex init a repo and then got "init ok" on stdout, "fatal: ref HEAD is not a symbolic ref" on stderr and exitcode 0 (or at least None).
So, datalad didn't notice something went wrong. Needs further investigation.

**Comment by yarikoptic** [comment]
do you have a minimal example to replicate? what version of annex/git?

**Comment by bpoldrack** [comment]
The error itself may be due to the use of the submodule and not bleeding-edge git annex. My point is the exitcode!

cd wherever-youhave-datalad-repo/datalad/tests/testrepos/basic/r1
git annex init

results in:
init  fatal: ref HEAD is not a symbolic ref
ok
(Recording state in git...)

Exitcode: 0

git annex version
git-annex version: 5.20141125
build flags: Assistant Webapp Webapp-secure Pairing Testsuite S3 WebDAV Inotify DBus DesktopNotify XMPP DNS Feeds Quvi TDFA CryptoHash
key/value backends: SHA256E SHA1E SHA512E SHA224E SHA384E SKEIN256E SKEIN512E SHA256 SHA1 SHA512 SHA224 SHA384 SKEIN256 SKEIN512 WORM URL
remote types: git gcrypt S3 bup directory rsync web webdav tahoe glacier ddar hook external
local repository version: 5
supported repository version: 5
upgrade supported from repository versions: 0 1 2 4

**Comment by yarikoptic** [comment]
what systems it that on?  there is now more relevant moving gears in annex than before, so it would be worth checking first with recent annex before we inquire help from joey

**Comment by bpoldrack** [comment]
It's jessie.
By now, I don't want joey to fix something. We should have a closer look
(or just ask joey), whether or not catching the exitcode is supposed to be
sufficient for our needs.

2015-03-19 4:01 GMT+01:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by yarikoptic** [comment]
Joey said that it is most  probably due to that submodule handling in 
Windows, which was recently fixed up.  So I will close this issue, but 
if it reappears with the new version of annex -- feel free to reopen. 

Otherwise, git annex must spit out the error code if operation didn't 
succeed as a result.  There might be intermediate failures which could 
cause it to fall back to alternative way to accomplish the same thing.
