### ISSUE TITLE
Symbolic links in a dataset that was copied to a windows-based file system work fine from Linux but not from Windows

### ISSUE THREAD

**Issue by JohannesWiesner** [datalad/datalad#6910]
### What is the problem?

After copying over a (sucessfully downloaded) datalad dataset to a filesystem without fifo-support (windows server), the symbolic links work when accessed via a linux based OS but not via a Windows based OS.

### What steps will reproduce the problem?

I am using datalad on Linux Mint to download data from the Human Connectome Project. The mounted file server (where the data should be stored) is windows based and does not support fifo. Therefore, when I try to use the `datalad.api.get` command I run into issues. My current workaround is to first execute the following script in my home directory, which works like a charm:

```python
import os
from datalad.api import install
from datalad.api import Dataset
from datalad.api import get
from datalad.api import create
from datalad.api import copy_file

###############################################################################
## User Settings ##############################################################
###############################################################################

# specify the path (where the source dataset should be place) 
# and url (where the dataset is obtained from) of the source dataset
src_dataset_path = './hcp'
src_url = 'https://github.com/datalad-datasets/human-connectome-project-openaccess.git'

# specify the target dataset that will be created and where the final files
# will be downloaded
tgt_dataset_path = './rest'

###############################################################################
## Get/Set source and target datasets #########################################
###############################################################################

# install and obtain the source dataset as a dataset object and create target dataset
# using dataset objects instead of paths will guarantee that datalad uses
# full paths behind the scenes without the user to specificy them

if not os.path.isdir(src_dataset_path):
    install(source=src_url,path=src_dataset_path)

if not os.path.isdir(tgt_dataset_path):
    create(path=tgt_dataset_path)

src_dataset = Dataset(src_dataset_path)
tgt_dataset = Dataset(tgt_dataset_path)

###############################################################################
## Install subdatasets ########################################################
###############################################################################

get(path="HCP1200/100610/MNINonLinear/Results/",dataset=src_dataset,get_data=False,recursive=True)
    
###############################################################################
## Download the data ##########################################################
###############################################################################

# specify source and target directories
path = f"{src_dataset.path}/HCP1200/100610/MNINonLinear/Results/rfMRI_REST1_LR/Movement_Regressors.txt"
tgt_dir = f"{tgt_dataset.path}/100610/rfMRI_REST1_LR"
copy_file(path=path,target_dir=tgt_dir,dataset=tgt_dataset)
get(dataset=tgt_dataset,recursive=True,get_data=True)
```

After this, I copy the dataset over to the file server (`cp -r rest /path/to/windows/based/file/server`). When inspecting this dataset copy on the windows fileserver ("Movement_Regressors.txt") from Linux Mint, everything works fine. But when inspecting it from Windows (my personal machine that also has access to the file server) the symbolic links do not seem to be interpretable for Windows and look like this:

```
XSym
0132
172b6916d029c03a49454d1ef57792c9
../../.git/annex/objects/Zx/qG/MD5E-s159600--15f45160217dafd2ac3a9185d8b8e9b9.txt/MD5E-s159600--15f45160217dafd2ac3a9185d8b8e9b9.txt
                                                                                                                                       
```

Is there anything that I can do from preventing this to happen?

### Datalad information

Windows OS: Windows 10 Education
Linux OS is: Linux Mint 19.3 "Tricia"
Datalad version is: 0.16.3

### Additional context

Executing this script using my personal machine and WSL-2 is not an option because my institution does not allow the installation of WSL-2.

**Comment by yarikoptic** [comment]
> After this, I copy the dataset over to the file server (`cp -r rest /path/to/windows/based/file/server`).

you must never just `copy` the git-annex repositories:
- every repository must have a unique git-annex UUID. obviously `copy` makes it non-unique and possibly later 
- filesystems might have no support for symlinks (like in your case) and git-annex must then use an alternative mode (adjusted branch for files in unlocked mode) to provide support for such annexed content.  For such a reason I would close the issue with this note - IMHO there is nothing we or git-annex could do for such cases to "fix" the issue

Instead of just "copying" you should `clone` or `install` from old location into a new one.  Then git-annex should switch to adjusted unlocked branch mode on windows/crippled filesystem. Of cause you could also try to "move" but I would expect that move would fail one way or another on those symlinks.

Please reopen if you do not agree with closing and see something to be done (but then it might warrant a dedicated issue with a description of what to be done exactly)
