### ISSUE TITLE
datalad diff dataset(s)  to show a summary of changes within sub-datasets

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#692]
now it is hard/impossible to assess how submodule/subdataset is different from what it was before:

``` shell
$> git diff am-1                                                                                             
diff --git a/am-1 b/am-1
index f8d77ac..ecfced7 160000
--- a/am-1
+++ b/am-1
@@ -1 +1 @@
-Subproject commit f8d77ac430597b4ef5affc3545ab37ae2bef3687
+Subproject commit ecfced74ef227ff906bf445689286678fe298a80
```

I would like to see

``` shell
> datalad diff am-1
master branch: fast forwarded from f8d77ac (Tue Aug 2 17:31:01 2016) to ecfced (Tue Aug 2 17:31:01 2016)
stats: 6124 files changed, 6446 insertions(+)
log:
* ecfced7 - (HEAD, master) Merge branch 'incoming-processed' (7 days ago) [Yaroslav Halchenko]
* c801627 - (incoming-processed) Added files from extracted archives (9 weeks ago) [Yaroslav Halchenko]
* f4c4f4c - (incoming) Updated git/annex from a remote location (9 weeks ago) [Yaroslav Halchenko]
```

or may be that all should be a part of some extended `datalad ls`... e.g. with option `--diff`, but the point is that needed to get a quick understanding how current state is different from before to decide to commit or not

**Comment by mih** [comment]
Also see #992

**Comment by mih** [comment]
With #1506 there is a general diff now. The feature requested above could be achieved by merely adding a bit of nice rendering code. The required info should already be available in the results.

**Comment by mih** [comment]
We have `diff` in master, the specifics of the rendering a subjective topic. Closing.
