### ISSUE TITLE
`GitRepo.get_submodules_()` slow with many directories/files and few subdatasets

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6941]
`GitRepo.get_content_info()` is called by `GitRepo.get_submodules_()` and also calls `GitRepo.get_submodules_()` in order to ensure compatibility with recent Git versions. "Introduced" by https://github.com/datalad/datalad/commit/8ff86134405dcd125e41fe3a2544ebc7454efc32

This is a grave performance issue: Any performance-conscious command would call `GitRepo.get_content_info()` with `paths` constraints. On any modern system with Git > 2.29.0 a call with `ref=None` (part of any `status()`) will trigger a call to `GitRepo.get_submodules_()`, which will in turn trigger an unconstrained call to `GitRepo.get_content_info()` https://github.com/datalad/datalad/issues/6940 Performance on any sizable dataset, in terms of numbers of files, with a least one subdataset will be severely impacted proportional to the number of files, regardless of whether the calling code uses path-contraints.

**Comment by yarikoptic** [comment]
> `GitRepo.get_content_info()` is called by `GitRepo.get_submodules_()` and also calls `GitRepo.get_submodules_()` in order to ensure compatibility with recent Git versions. This can lead to
> 
> ```
> RecursionError: maximum recursion depth exceeded
> ```

I wish there was an example which demonstrated that. I thought to add a unittest to ensure that we do not get it but looking at the code I do not see how infinite recursion could happen since inside `get_content_info` we call back `get_modules_` only if `paths` were provided, but without providing `paths` into that recursive call, so not clean how this could happen to me :-/

**Comment by mih** [comment]
I retitled and edited the top post to remove this aspect from this issue. It is not relevant. The performance is.

**Comment by yarikoptic** [comment]
then duplicate of https://github.com/datalad/datalad/issues/6940 ?

**Comment by mih** [comment]
Yes. closing
