### ISSUE TITLE
A DataLad GUI

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6972]
Prompted by several circumstances I had to think about a GUI again.

FTR: I the past the attitude has mostly been "Can we find a way to add some kind of context-menu with datalad actions to a native file manager?", which has never played out. One main source of hesitance came from the need to implement support for individual platform's file managers.

The situation has changed a bit, since the early days of GUI considerations. Today:

- all datalad commands report structured data that can be serialized and rendered in different ways
- the API of all datalad commands is inspectable (ie. parameters can be inferred, their documentation read, and more and more programmatic input validation can be done)
- with https://github.com/datalad/datalad-next/pull/92 a fast filesystem inspection utility becomes available

I believe with these pieces, we could make an attempt at a lean GUI implementation that would yield meaningful functionality with manageable additional effort.

Here is my first rough attempt on how this could look visually:

![image](https://user-images.githubusercontent.com/136479/185896974-d87fcd6b-88d4-41f2-9af2-fa8d4f6769c7.png)

The centerpiece would be (A), a clickable, collapsible/expandable tree widget that is populated with `datalad-tree` and shows directories, datasets, regular files, and annexed files and indicate their local availability.

Depending on the selection in (A), the tabs in (B) are populated with buttons and inputs to trigger certain actions for particular item-types. Easily supportable actions are the key core API actions:

- create a dataset
- save a dataset with a commit message
- run a command on a dataset
- retrieve content/subdatasets
- drop content/subdatasets
- push to a remote

Later, with API inspection, we could also auto-detect sibling-types that could be created, and generated dialogs for such command calls programatically.

(C) would be the place to render incoming results from dataset, or turn intercepted progress log messages into a visual progress bar.

The menubar can provide access to the handbook and other docs, systeminfo, but could also interface `credentials` and `configuration`.

A GUI like this would be fairly extensible, and would not have to wait for a comprehensive implementation of everything one could think of.

My personal, current (and likely volatile) preference re GUI toolkit would be pyside(6). Having looked at a bunch of others, this would click best with me right now.

**Comment by adswa** [comment]
> The menubar can provide access to the handbook and other docs, systeminfo, but could also interface credentials and configuration.

I think those are also great additions to a GUI. I wonder if it would also be feasible to read out the config manager to give an indication on which extensions are active, given that patches to core from extensions are becoming more common.

**Comment by adswa** [comment]
the lab chat came up with a better name and logo suggestion: ``datalad-gooey``
![Uploading gooey.png…]()

**Comment by mih** [comment]
> I wonder if it would also be feasible to read out the config manager to give an indication on which extensions are active, given that patches to core from extensions are becoming more common.

Yes, that is what I meant to summarize with "systeminfo"

**Comment by jsheunis** [comment]
FWIW, some alternative GUI frameworks and links:
- [PyQt5](https://riverbankcomputing.com/software/pyqt/intro)
- [TkInter](https://wiki.python.org/moin/TkInter)
- [Kivy](https://kivy.org/)
- [wxPython](https://www.wxpython.org/)
- [PySide6](https://doc.qt.io/qtforpython)

**Comment by yarikoptic** [comment]
Consider some web UI framework , may be https://www.electronjs.org/ - then could become part of larger web UIs / may be jupyterlab instances etc

**Comment by mlell** [comment]
> Consider some web UI framework , may be https://www.electronjs.org/ - then could become part of larger web UIs / may be jupyterlab instances etc

That would make a lot of sense in my setup where all my analysis is running on a cluster which I only operate via browser. That is so much faster than a VNC connection, especially because it can tolerate a shaky internet connection (work from train)

**Comment by yarikoptic** [comment]
may be if Qt, https://www.qt.io/qt-examples-for-webassembly could be used?

**Comment by mih** [comment]
First lines of a tech demo are here: https://github.com/datalad/datalad-gooey

I agree that a web UI would be lovely.

However, I do think it makes sense to exercise this with any UI toolkit, just to get the pieces figured out. (Re)implementing in a different way should be substantially easier after having sorted out the conceptual units. Consequently, the goal of the above project is to get a GUI working with the least amount of Qt-specificity, and the least possible glue code between datalad and Qt.

If that works out, webassembly could be an option (more likely with less fancy Qt features being needed).

**Comment by yarikoptic** [comment]
I believe that https://github.com/datalad/datalad-gooey is **the** GUI DataLad will be getting, so I will just close this issue since IMHO it has been handled and anything more specific should be filed as issues against that repo.
