### ISSUE TITLE
Where does metadata get stored?

### ISSUE THREAD

**Issue by ddeepwel** [datalad/datalad#6975]
### What is the problem?

It is unclear where the metadata from running `datalad extract-metadata [...]` gets stored. The command runs and seems to indicate that metadata was extracted, but I do not know where it has been placed.

### What steps will reproduce the problem?

Once the datalad_neuroimaging module is installed, run the following

```
datalad create -c text2git dicom-extract
cd dicom-extract
git clone https://github.com/ShahinSHH/COVID-CT-MD.git
datalad save -m "new data" 
git config --file .datalad/config --add datalad.metadata.nativetype dicom
cd COVID-CT-MD/
datalad extract-metadata --type dicom -d .
```

### DataLad information

datalad 0.17.2
metalad 0.4.2
OS: linux x86_64

**Comment by christian-monch** [comment]
Hi @ddeepwel. As outlined [here](https://github.com/datalad/datalad/issues/6903#issuecomment-1225354287), there are two generations of `metalad`.

Generation 1 is built into `datalad` and updated in the `datalad-metalad` extension with version <= 0.2.

Generation 2 is contained in `datalad-metalad` extension with version >=0.3

The generations have different commands. The generation 1-code is still in `datalad`. So your configuration will provide both sets of commands to you.

You have used a generation 1-command. The resulting metadata should be stored under `.datalad/metadata`. The command `datalad search` would use this metadata to retrieve content. 

In generation 2 the resulting metadata is stored in an internal "branch" in the git repository. The generation 2-command to extract metadata would be `meta-extract` (generally, generation 2 metalad-commands start with `meta-`).  The syntax and semantics are different. An example can be found [here](https://gist.github.com/christian-monch/63c52f20a5c24b04146db0a8f2750d0c). In generation 2 the metadata is available via `datalad meta-dump`, and can also be searched via `datalad search`.

Let me know, how I can help you further.

**Comment by yarikoptic** [comment]
@ddeepwel feel free to reopen if further information is needed.
