### ISSUE TITLE
Make testrepo names contain non-ascii (maybe French) and unicode (maybe Chinese) chars

### ISSUE THREAD

**Issue by mih** [datalad/datalad#698]
See #697 for a related effort.

**Comment by hanke** [comment]
Tried. Failed. Big time....

**Comment by hanke** [comment]
Also see f991c7a8c1683ea09875ef90d577385270b15e9d

**Comment by yarikoptic** [comment]
See https://travis-ci.org/gitpython-developers/GitPython/jobs/156924625  ;-)

**Comment by mih** [comment]
We have failure obscure names for a long time now.
