### ISSUE TITLE
API documentation issue?

### ISSUE THREAD

**Issue by TimmWetzel** [datalad/datalad#6993]
### What is the problem?

Using the Python API I get the error `TypeError: apply_func() missing 1 required positional argument: 'instance'` when calling save or push as given in the documentation (with a `dataset=` keyword).

### What steps will reproduce the problem?

```
import datalad.api as dlapi
ds = dlapi.Dataset("some/path")

dlapi.Dataset.save(dataset=ds, ...)
dlapi.Dataset.push(dataset=ds, ...)

```

### DataLad information

```
datalad 0.17.3
Python 3.9.10
```

### Additional context

Using an instance method works fine
`ds.save(...)`,
as does simply omitting the `dataset=` keyword:
`dlapi.Dataset.save(ds, ...)`.

If the behavior is intended, the DataLad API documentation should probably change to match.

**Comment by mih** [comment]
Hey, if you want to call the commands without going through a dataset class _instance_, you can do

```py
dlapi.save(dataset=ds)
```

in contrast,

```py
dlapi.Dataset.save(...)
```

calls a class method, which requires a `self` Python-style instance pointer to be provided as the first non-keyword argument. So this would be something like:

```py
dlapi.Dataset.save(ds, ...)
```

as you pointed out, but I would not recommend doing that, as it feel rather unintuitive and may lead to confusion.

If we have that in the docs, please point me to it. We should indeed change it.

**Comment by TimmWetzel** [comment]
> ```python
> dlapi.save(dataset=ds)
> ```

I obviously manged to completely overlook the distinction between the `dlapi.*` and `dlapi.Dataset.*` forms. Ooops.

> ```python
> dlapi.Dataset.save(ds, ...)
> ```
> If we have that in the docs, please point me to it. We should indeed change it.

Interesting. The docs at docs.datalad.org actually do document both forms quite correctly. It was probably the integrated Python help (`>>> help(dlapi.Dataset.save)`) that confused me.

**Comment by yarikoptic** [comment]
I consider it answered, please reopen if that is not the case
