### ISSUE TITLE
Support `textblob`- and `autofield`-modes in `datalad search` with `gen4` metadata

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad#6999]
Currently `datalad search` on `gen4` metadata, i.e. metadata that is generated by Metalad version 0.3.0 and higher, only supports the search mode `egrep`.

The modes `textblob` and `autofield` should also be supported. This includes:

- [ ] handle indices for `gen4` metadata
- [ ] add support for `gen4`-metadata in `textblob` mode
- [ ] add support for `gen4`-metadata in `autofield` mode

### What is the problem?

The command `datalad search` with parameters `--mode autofield` and `--metadata-source gen4` fails in a dataset that actually contains `gen4` metadata with the following result dictionary:

```python
{
  'action': 'metadata',
  'message': 'metadata aggregation has never been performed in this dataset',
  'path': '<path to dataset>',
  'status': 'impossible',
  'type': 'dataset'
}
```

### What steps will reproduce the problem?

Execute the following command in a directory that contains a dataset with `gen4` metadata:

```shell
> datalad create t3
> cd t3
> datalad meta-extract metalad_example_dataset | datalad meta-add -
> git config -f .datalad/config --add datalad.search.index-autofield-documenttype all
> datalad search --mode autofield --metadata-source gen4 executed
> echo $?
1
```

The search shows zero hits and exits with status 1, although there should be one hit. If the search is executed with mode set to "egrep", it returns a match and exits with status 0

```shell
> git config -f .datalad/config --add datalad.search.index-egrep-documenttype all
> datalad search --mode egrep --metadata-source gen4 executed
search(ok): t3 (dataset)
> echo $?
0
```

### DataLad information

datalad version 0.17.4
datalad-metalad version 0.4.5

### Additional context

It seems that index building is not performed for gen4-metadata if mode is either "autofield" or "textblob" and that search is terminated early.

**Comment by mih** [comment]
This issues refers to functionality that has been removed in https://github.com/datalad/datalad/pull/7014
