### ISSUE TITLE
Make nipype more conscious about dead symlinks

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7]
I am not exactly sure what the right solution would be. If nipype's DataGrabber/Finder discovers a dead symlink it should at least complain/warn. But apart from that I am not certain whether it should refuse to run if in the matched set is a dead symlink, or whether it should exclude them, because they are practically not present.

**Comment by yarikoptic** [comment]
@hanke: Please bring discussion on nipype issues board and reference it back here

**Comment by mih** [comment]
Closing this issue of mine, acting on the apparent lack of motivation to work on it.
