### ISSUE TITLE
AnnexRepo.uuid (lazy) property

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#701]
any annexrepo should have a uuid, which also should should not change (other than from None) in its lifespan.  So we could lazily load it e.g. from config
```python
if not self._uuid:
   repocfg = vcs.repo.config_reader() 
   self._uuid = repocfg.get_value('annex', 'uuid')
```
but in case of fresh git clones of annex repos we might need to run e.g. `git annex info --fast` first so annex generates a UUID for this particular instance

```shell
hopa:/tmp
$> git clone d1 d2
Cloning into 'd2'...
done.
(venv-tests) 2 12409 [2].....................................:Thu 11 Aug 2016 10:25:43 AM EDT:.
hopa:/tmp
$> cd d2
(venv-tests) 2 12410 [2].....................................:Thu 11 Aug 2016 10:25:45 AM EDT:.
(git)hopa:/tmp/d2[master]
$> cat .git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = /tmp/d1
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
(venv-tests) 2 12411 [2].....................................:Thu 11 Aug 2016 10:25:47 AM EDT:.
(git)hopa:/tmp/d2[master]
$> git annex info --fast --json
(merging origin/git-annex into git-annex...)
(recording state in git...)
{"command":"info","key":null,"file":null,"repository mode":"indirect","trusted repositories":[],"semitrusted repositories":[{"here":false,"uuid":"00000000-0000-0000-0000-000000000001","description":"web"},{"here":false,"uuid":"00000000-0000-0000-0000-000000000002","description":"bittorrent"},{"here":false,"uuid":"25a7c4e5-4bf5-4d2f-9c42-322438bda875","description":"yoh@hopa:/tmp/d1 [origin]"},{"here":true,"uuid":"2f09ab75-e369-42e4-b852-47946933d260","description":"yoh@hopa:/tmp/d2"}],"untrusted repositories":[],"transfers in progress":[],"available local disk space":"773.75 megabytes (+1 megabyte reserved)","success":true}
(venv-tests) 2 12412 [2].....................................:Thu 11 Aug 2016 10:25:51 AM EDT:.
(git)hopa:/tmp/d2[master]
$> cat .git/config             
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = /tmp/d1
	fetch = +refs/heads/*:refs/remotes/origin/*
	annex-uuid = 25a7c4e5-4bf5-4d2f-9c42-322438bda875
[branch "master"]
	remote = origin
	merge = refs/heads/master
[annex]
	uuid = 2f09ab75-e369-42e4-b852-47946933d260
	version = 5
```

**Comment by hanke** [comment]
Few questions and pointers:

You write "should not change (other than from None) in its lifespan": "lifespan" of a Dataset object, the dataset on disk?

Please check out this implementation: https://github.com/hanke/datalad/blob/nf-metaparser/datalad/metadata/__init__.py#L60

It uses a UUID (if it finds any), the hexsha of the current branch HEAD (if any), or the local path as the last resort. This is done, because for meta data we need identifiers regardless of whether a UUID is available now, or will be in the future.

These two concepts could be merged to some degree. But it depends on what we want. If we want any ID, we should not call this method/property `UUID`, if we really want a UUID only, we still need a separate ID mechanism for all non-annex things.

**Comment by yarikoptic** [comment]
I meant in the life time of that python object, that is why lazy loading once should work fine... But if we allow checksum/path, and then it gets uuid (after annex command runs and inits it), it might change that way i guess

**Comment by bpoldrack** [comment]
I think, we can (and may be should) have both. The ID, @hanke is talking about, is mainly for identifying a dataset in a way, that is satisfying regarding metadata. Whereas UUID is a property of an annex repository. So, `AnnexRepo` could still have the lazy `uuid` property as proposed by @yarikoptic , while `Dataset` provides a more general ID mechanism, which uses the `uuid` of its underlying `AnnexRepo` instance, if there is any. These are two different things and while we need these dataset identifiers, the uuid is an independently essential property of an annex, represented by an `AnnexRepo` instance.

This also means, I agree to @hanke 's implementation in #720, with the exception, that it should be enhanced to use `AnnexRepo.uuid` and let this be the one, that lazily loads it from config.

**Comment by hanke** [comment]
@bpoldrack #720 now implements that.
