### ISSUE TITLE
Move old-style metadata facilities to `deprecated`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7012]
Protocol of plan made in devcall:

Move remaining metadata commands to `-deprecated`

- `metadata`
- `aggregate:-metadata`
- `search`

Announce this plan now (informally), and release the move with the next major release.

With that announcement, we announce that `metalad` provides the next generation metadata handling for datalad.

There is no requirement for `metalad` to provide an API-compatible replacement for these commands. Rather, it is appreciated for them to stay intact and usable in parallel with `-deprecated` installed.

**Comment by mih** [comment]
https://twitter.com/datalad/status/1567222620570927105?t=GJ9r-VL9ll-BQ-8nzk8sJQ&s=19

**Comment by christian-monch** [comment]
I will take this one. Plan:

1. extend datalad-deprecated with the metadata-commands
2. test with datalad branch https://github.com/mih/datalad/tree/mnt-metadata-mv

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.0`](https://github.com/datalad/datalad/releases/tag/0.18.0)
