### ISSUE TITLE
Replace `simplejson` with `json` to reduce dependencies

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad#7034]
Datalad uses `simplejson` instead of `json`, which introduces additional dependencies. Since the functionality is identical, `simplejson` should be replaced with `json`.

This change should also be done in the following extensions:

- [x] datalad-metalad: https://github.com/datalad/datalad-metalad/issues/285
- [ ] datalad-neuroimaging: https://github.com/datalad/datalad-neuroimaging/issues/107
- [ ] datalad-container: https://github.com/datalad/datalad-container/issues/181

**Comment by bpoldrack** [comment]
@christian-monch: Do you have plans to finish this?

**Comment by bpoldrack** [comment]
I think this is done as far as the core package is concerned and datalad-container has its own issue about it.
