### ISSUE TITLE
Runner cannot handle `run(cwd=Path)`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7040]
Docs say: `cwd : path-like, optional`

Made me assume that a `Path` instance would work, but it does not. At least not when passed to `run()`. It does work, when passed to the constructor (same docs of the argument there).

On Windows, such a path obj ends up in the environment, leading to unexpected results.

**Comment by christian-monch** [comment]
There is old code in the runner that puts a modified path into the alternative environment if an alternative environment is provided. This code did not account for the possibility of Path-objects in `cwd`. This should be fixed by #7107

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.17.8`](https://github.com/datalad/datalad/releases/tag/0.17.8)
