### ISSUE TITLE
Move release workflow from `pull_request` to `push`?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#7048]
ok, I did more investigation on why workflow switching from use of `auto` in  https://github.com/datalad/datalad/pull/7024  doesn't have credentials -- neither default GITHUB_TOKEN works nor the GITMATE_GITHUB_TOKEN works. The last summary was in https://github.com/datalad/datalad/pull/7046#issuecomment-1252539797 followed by https://github.com/datalad/datalad/pull/7047 which confirmed that we do not have a value for GITMATE_GITHUB_TOKEN available.

I have noted in the log for the action run that `Secret source: None` and logically got that we get them set only for `push` and not `pr`s:

```shell
(git)smaug:/mnt/datasets/datalad/ci/logs/2022/09[master]git
$> git grep 'Secret source: ' | sed -e 's,^[^/]*/\(pr\|push\).*[0-9]Z Secret source:,\1,g' | sort | uniq -c
   2162 pr None
    580 push Actions
```
and in #7024 we switched from `push` to `pull_request`.  Thus now we do not have any secrets available since it seems to be treated as a PR, just on merge:

```yaml
name: Auto-release on PR merge

on:
  pull_request:
    branches:
      - maint
    types:
      - closed
```

I do not remember exact reason and 597572ef3d2454b26dedc0883aa2a014d1513913 commit message provides none either.  @jwodder -- do you recall why is that and either we can may be get back to reacting on `push` somehow?  Or what other way you see to mitigate it and make releases work agian?

PS It might be that for PRs based off branches in the repo it would work, but it would be unfortunate to need to limit being able to release and remember about that only for PRs from branches from this repo.

**Comment by jwodder** [comment]
@yarikoptic We need to use a `pull_request` trigger in order to have access to information about the PR that was just merged (specifically, whether it had the "release" label).  It's possible that using `pull_request_target` instead of `pull_request` will fix the situation.

**Comment by yarikoptic** [comment]
How did we work it out in case of `auto`-powered on simple `push` -- we did the same reaction to merged PR with `release` label, right? so I guess it might be just a matter of taking the most recent merge commit and deducing which PR they correspond to?

**Comment by jwodder** [comment]
@yarikoptic `auto` did the determination itself.  I think it parses commit messages looking for GitHub-generated merge commits and deduces the PRs from those.

**Comment by yarikoptic** [comment]
can't we use pull requests listing for `state=closed&sort=updated&base={target_branch}&direction=desc` (direction might need to be `asc` if I mix up the two) to get 

Let's pull listing of most recently updated PRs: https://api.github.com/repos/datalad/datalad/pulls?state=closed&sort=updated&base=maint&direction=desc  -- there you can get `merge_commit_sha` for the most recent one, see if that is the HEAD of the branch, and if so -- consider its labels.

**Comment by jwodder** [comment]
@yarikoptic I think we should try using `pull_request_target` first.

**Comment by yarikoptic** [comment]
> @yarikoptic I think we should try using `pull_request_target` first.

ok, please give it a shot. I am not familiar much with it, can't judge.

**Comment by yarikoptic** [comment]
IIRC #7051 did address it for us back then
