### ISSUE TITLE
`ui.message()` cannot handle disconnected `stdin`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7053]
I wanted to use `datalad credential` inside an `SSH_ASKPASS` still tool. These are called by SSH or Git to retrieve credentials. However, `credentials` uses `ui.message()`. Inside such an environment, a "Silent UI" is set up by datalad, which will not prompt for anything, but rather

```
[ERROR] A non-interactive silent UI was asked for a response to a question: username. (RuntimeError)
```

I wonder if this avoidable?

Of course the main usecase for `SSH_ASKPASS` is to prompt via a GUI.

**Comment by bpoldrack** [comment]
I'm a bit confused here. The error message should only come from `ui.question` not `ui.message`.

However, I suppose ultimately this is hinting at the need to change the `UI_Switcher` approach, which assumes that it knows all relevant backends. That's not flexible enough to reliably provide another backend from an extension.

WDYT, @yarikoptic?

**Comment by bpoldrack** [comment]
Right now, it seems to me the only way would be to use `UI_Switcher`'s `set_backend`, which in turn would require to patch `ui.KNOWN_BACKENDS` dict and enhance it with the new backend. That way, one could circumvent the call path setting `SilientConsoleLog` based on interactivity detection, @mih.

**Comment by mih** [comment]
Yes. This is pretty much how I ended up doing it in datalad-gooey. I think we can close this. It is possible, by providing a largely independent implementation.
