### ISSUE TITLE
Consider adopting datalad-next constraints

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7054]
They are growing here and aim to offer a much finer control on type definitions and validation. They aim is to keep the API, and only extend it if absolutely necessary, e.g. in order to allow validation at other stages than argparse.

https://github.com/datalad/datalad-gooey/blob/main/datalad_gooey/constraints.py

**Comment by yarikoptic** [comment]
those two make sense to me. 
Only loosely related -- if there is some "completion" mechanism in gooey, e.g. give siblings for a dataset, might be worth adding such interfaces to constraints and using them in gooey and argcomplete in CLI.

**Comment by mih** [comment]
Would be nice, but I do not know, how I could make one Constraint aware of another parameter. In gooey this is done, for argparse, I know too little. I think it would need an API extension for that.

**Comment by mih** [comment]
I could not come up with a generic concept of validating a constraint with respect to an arbitrary number of other constraints. This would be necessary in order to have any parameter value, in principle, influence or determine another parameter.

Right now the essential `Constraint` API is:

```py
def __call__(self, value):
        # do any necessary checks or conversions, potentially catch exceptions
        # and generate a meaningful error message

def long_description(self):
        # return meaningful docs or None
        # used as a comprehensive description in the parameter list

def short_description(self):
        # return meaningful docs or None
        # used as a condensed primer for the parameter lists
```

`__call__` does context-free validation and type conversion. The other two doc-helpers sound generic, but are geared towards the two CLI APIs implementation-wise.

From my POV it makes sense extend this API with a context-dependent validation mechanism. The primary context we care about in DataLad is a `dataset`. This would enable a whole range of useful checks

- siblings
- gitshas
- paths
- branches
- ...

... **in a particular dataset**.

From a procedural POV, there would likely be a helper that is used at the start of a command implementation, and runs validation on all command parameters as soon as a dataset instance is known.

I propose to enhance `Constraint` with

```py
def for_dataset(self, dataset: Dataset, value: Any) -> Any:
    ...
```

**Comment by bpoldrack** [comment]
> I am considering the idea that a context based validation might just lead to a different constraint altogether.

I like that idea.

**Comment by mih** [comment]
Here is another batch of constraints: https://github.com/datalad/datalad-gooey/pull/297

- `EnsureMapping`
- `EnsureStr(regex)`
- `EnsureGitRefName`
- `EnsurePath` #6139

**Comment by mih** [comment]
I think we can close this issue here. Joint parameter set validation has been available in datalad-next for some time now. The next push is likely being triggered by https://hub.datalad.org/ui/dlcmd
