### ISSUE TITLE
`EnsureDataset` cannot handle `Path` values

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7069]
`datalad-gooey` does full parameter validation not, and because of that fails on any parameter that has an `EnsureDataset` constraint, because it does not use string paths internally, but `Path` objects.

This is a bit ironic, because `EnsureDataset` does not actually do anything other than rejecting anything that is not a `str` or `Dataset` instance.

I will replace this constraint in `Gooey` with something more useful, because the rational in the code doesnot apply there:

```
            # we cannot convert to a Dataset class right here
            # - duplicates require_dataset() later on
            # - we need to be able to distinguish between a bound
            #   dataset method call and a standalone call for
            #   relative path argument disambiguation
            #return Dataset(path=value)
 ```

Ultimately, datalad-core will need to do something about it, when it would start validating Python command arguments.

https://github.com/datalad/datalad-gooey/issues/298

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.0`](https://github.com/datalad/datalad/releases/tag/0.18.0)
