### ISSUE TITLE
make logger optionally log the traceback in the log msgs

### ISSUE THREAD

**Issue by glalteva** [datalad/datalad#707]
Currently we rely on builtin facility of logger to log the file:linenumber for the location where the log line was called.  For the `exc_str` we already have a convenient DATALAD_EXC_STR_TBLIMIT which places entire traceback (up to that limit) to exc_str.  We need something like (may be even unifying the env var name to be used by both) for logging, otherwise it is hard to see what situation lead to that log line at times

**Comment by yarikoptic** [comment]
was done already -- `DATALAD_LOG_TRACEBACK=`
