### ISSUE TITLE
fatal: path 'remote.log' does not exist in 'git-annex'

### ISSUE THREAD

**Issue by Kfarls** [datalad/datalad#7099]
### What is the problem?

datalad clone, create-sibling and siblings have begun producing the below error:

CommandError: 'git -c diff.ignoreSubmodules=none cat-file blob git-annex:remote.log' failed with exitcode 128 under /Users/kfarley/Main/Work/test
fatal: path 'remote.log' does not exist in 'git-annex'

### What steps will reproduce the problem?

This appears to just be an issue specific to my mac, I've tried using datalad on our remote server and it works without issue. This isn't limited to a single repo, if I datalad create a new repo, I am unable to clone it etc. Updating datalad and git-annex haven't fixed the error. Any help pointing out what I'm doing wrong would be greatly appreciated

### DataLad information

# WTF
## credentials 
  - keyring: 
    - active_backends: 
      - macOS Keyring
      - PlaintextKeyring with no encyption v.1.0 at /Users/kfarley/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /Users/kfarley/.config/python_keyring/keyringrc.cfg
    - data_root: /Users/kfarley/.local/share/python_keyring
## datalad 
  - version: 0.15.6
## dataset 
  - branches: 
    - git-annex@fc9782b
    - main@070213d
  - id: 02e31b58-ddde-4c2a-8c76-0148d5deb488
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /Users/kfarley/Main/Work/test
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.6.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 17.04
  - cmd:annex: 10.20221003
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.36.1
  - cmd:system-git: 2.36.1
  - cmd:system-ssh: 8.6p1
  - humanize: 4.0.0
  - iso8601: 1.0.2
  - keyring: 23.5.0
  - keyrings.alt: 4.1.0
  - msgpack: 1.0.3
  - requests: 2.27.1
  - wrapt: 1.14.0
## environment 
  - LANG: en_AU.UTF-8
  - PATH: /Users/kfarley/.emacs.d/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kfarley/Library/Python/3.7/bin:/Library/Apple/usr/bin:/Users/kfarley/bin
## extensions 
  - container: 
    - description: Containerized environments
    - entrypoints: 
      - datalad_container.containers_add.ContainersAdd: 
        - class: ContainersAdd
        - load_error: None
        - module: datalad_container.containers_add
        - names: 
          - containers-add
          - containers_add
      - datalad_container.containers_list.ContainersList: 
        - class: ContainersList
        - load_error: None
        - module: datalad_container.containers_list
        - names: 
          - containers-list
          - containers_list
      - datalad_container.containers_remove.ContainersRemove: 
        - class: ContainersRemove
        - load_error: None
        - module: datalad_container.containers_remove
        - names: 
          - containers-remove
          - containers_remove
      - datalad_container.containers_run.ContainersRun: 
        - class: ContainersRun
        - load_error: None
        - module: datalad_container.containers_run
        - names: 
          - containers-run
          - containers_run
    - load_error: None
    - module: datalad_container
    - version: 1.1.6
  - neuroimaging: 
    - description: Neuroimaging tools
    - entrypoints: 
      - datalad_neuroimaging.bids2scidata.BIDS2Scidata: 
        - class: BIDS2Scidata
        - load_error: None
        - module: datalad_neuroimaging.bids2scidata
        - names: 
          - bids2scidata
    - load_error: None
    - module: datalad_neuroimaging
    - version: 0.3.1
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - FsEvents
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.30
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-9.2.4
    - http-client-0.7.13.1
    - persistent-sqlite-2.13.1.0
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.2.1
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 10
  - operating system: darwin aarch64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
    - 9
    - 10
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20221003
## location 
  - path: /Users/kfarley/Main/Work/test
  - type: dataset
## metadata_extractors 
  - annex (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'mutagen')
    - module: datalad.metadata.extractors.audio
  - bids (datalad-neuroimaging 0.3.1): 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.bids
    - version: None
  - datacite (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - dicom (datalad-neuroimaging 0.3.1): 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.dicom
    - version: None
  - exif (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'exifread')
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - nidm (datalad-neuroimaging 0.3.1): 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.nidm
    - version: None
  - nifti1 (datalad-neuroimaging 0.3.1): 
    - distribution: datalad-neuroimaging 0.3.1
    - load_error: None
    - module: datalad_neuroimaging.extractors.nifti1
    - version: None
  - xmp (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.10.4
## system 
  - distribution: darwin/21.6.0 12.6/arm64
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 285
  - name: Darwin
  - release: 21.6.0
  - type: posix
  - version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101

### Additional context

After some encouragement I recently downloaded emacs ,though all I've done is the install and configuration per https://github.com/doomemacs/doomemacs and the emacs tutorial. I did notice .emacs.d in my environment path though so unsure if that's related?

example of the debug script in case it's useful:
datalad --log-level debug siblings
[DEBUG  ] Command line args 1st pass for DataLad 0.15.6. Parsed: Namespace() Unparsed: ['siblings'] 
[DEBUG  ] Building doc for <class 'datalad.distribution.update.Update'> 
[DEBUG  ] Building doc for <class 'datalad.distribution.siblings.Siblings'> 
[DEBUG  ] Parsing known args among ['/Library/Frameworks/Python.framework/Versions/3.10/bin/datalad', '--log-level', 'debug', 'siblings'] 
[DEBUG  ] Run ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] (cwd=None) 
[DEBUG  ] Finished ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] with status 0 
[DEBUG  ] Determined class of decorated function: <class 'datalad.distribution.siblings.Siblings'> 
[DEBUG  ] Resolved dataset to configure sibling: /Users/kfarley/Main/Work/test 
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin'] (cwd=/Users/kfarley/Main/Work/test) 
[DEBUG  ] Finished ['git', 'config', '-z', '-l', '--show-origin'] with status 0 
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin', '--file', '/Users/kfarley/Main/Work/test/.datalad/config'] (cwd=/Users/kfarley/Main/Work/test) 
[DEBUG  ] Finished ['git', 'config', '-z', '-l', '--show-origin', '--file', '/Users/kfarley/Main/Work/test/.datalad/config'] with status 0 
[DEBUG  ] Run ['git', 'annex', 'version', '--raw'] (cwd=None) 
[DEBUG  ] Finished ['git', 'annex', 'version', '--raw'] with status 0 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'info', '--bytes', '--fast', '--json', '--JSON-error-messages', '-c', 'annex.dotfiles=true'] (cwd=/Users/kfarley/Main/Work/test) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'info', '--bytes', '--fast', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true'] with status 0 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'cat-file', 'blob', 'git-annex:remote.log'] (cwd=/Users/kfarley/Main/Work/test) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'cat-file', 'blob', 'git-annex:remote.log'] with status 128 
[Level 11] CommandError: 'git -c diff.ignoreSubmodules=none cat-file blob git-annex:remote.log' failed with exitcode 128 under /Users/kfarley/Main/Work/test [err: 'fatal: path 'remote.log' does not exist in 'git-annex''] 
CommandError: 'git -c diff.ignoreSubmodules=none cat-file blob git-annex:remote.log' failed with exitcode 128 under /Users/kfarley/Main/Work/test
fatal: path 'remote.log' does not exist in 'git-annex'

### Have you had any success using DataLad before?

Yes! I'm a big fan of datalad. It's SO useful, especially when I'm working on something on the remote server and locally

**Comment by adswa** [comment]
Thanks for opening this issue! I have never seen such an error before, but @bpoldrack (who currently sits next to me) mentioned that he vaguely recalls a fix for something that sounded familiar. While I skim the CHANGELOG, could you try to upgrade DataLad? I see version 0.15.6 in your post, but depending on your installation method you could go up to 0.17.7 (available on PyPi or brew) or 0.17.6 (available on conda-forge).

**Comment by adswa** [comment]
I found it: Original fix was done in https://github.com/datalad/datalad/pull/6569, this changeset has been released on April 8th this year in 0.16.0. I strongly suspect that a update should fix this - please report back :)

**Comment by Kfarls** [comment]
Aha! Yeah that fixed it, thank you! I had updated it with brew but must have initially installed with pip3
