### ISSUE TITLE
Server certificate verification failed when installing 

### ISSUE THREAD

**Issue by alexisthual** [datalad/datalad#7108]
### What is the problem?

I can't install `datalad` datasets (I only tried installing `narratives`) because some certificates have expired.

### What steps will reproduce the problem?

`datalad install ///labs/hasson/narratives -r` yields

```bash
install(error): /storage/store2/data/narratives (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:                                                                    
- https://datasets.datalad.org/labs/hasson/narratives
  CommandError: 'git -c diff.ignoreSubmodules=none clone --progress https://datasets.datalad.org/labs/hasson/narratives /storage/store2/data/narratives' failed with exitcode 128 [err: 'Cloning into '/storage/store2/data/narratives'...
fatal: unable to access 'https://datasets.datalad.org/labs/hasson/narratives/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none']
- https://datasets.datalad.org/labs/hasson/narratives/.git
  CommandError: 'git -c diff.ignoreSubmodules=none clone --progress https://datasets.datalad.org/labs/hasson/narratives/.git /storage/store2/data/narratives' failed with exitcode 128 [err: 'Cloning into '/storage/store2/data/narratives'...
fatal: unable to access 'https://datasets.datalad.org/labs/hasson/narratives/.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none']]
[ERROR  ] NoDatasetFound(No installed dataset found at /storage/store2/data/narratives) (NoDatasetFound) 
usage: datalad install [-h] [-s SOURCE] [-d DATASET] [-g] [-D DESCRIPTION] [-r] [-R LEVELS] [--reckless [auto|ephemeral|shared-...]] [-J NJOBS] [--branch BRANCH] [--version] [PATH ...]
(singbrain) 
```

### DataLad information

```bash
〉 datalad --version
datalad 0.17.7
```

**Comment by adswa** [comment]
Hey, thanks for the issue -  I'm not very knowledgeable about certificates, so I'll just tag @yarikoptic. 
However, I just tried cloning these datasets, and can't reproduce this. The output of ``openssl s_client -showcerts -servername -connect datasets.datalad.org:443 `` looks like the certificate is valid. My suspicion is that my system has certificates that your system lacks. Could you check if your systems certificates (``/etc/ssl/certs/ca-certificates.crt ``) need an update (or if your systems clock is off)?

**Comment by alexisthual** [comment]
Hey, you were right @adswa, there was an issue on my side.
I could find [many answers](https://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c) on stackoverflow and eventually was able to circumvent my machine not trusting this certificate.
Thanks!

**Comment by adswa** [comment]
great to hear, thanks for reporting back!
