### ISSUE TITLE
Migrate release workflow to use datalad/release-action@v0

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#7110]
Most of https://github.com/datalad/datalad/issues/7052 are addressed there so we better migrate.  Also would be useful so other developers start to get used to it and file issues there if any detected.

Needs
- [ ] https://github.com/datalad/release-action/issues/8 to get changelog in github release formatted ok
- [x] https://github.com/datalad/release-action/issues/27 to gain @v0 (or v1?) to be used in the workflow here

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.17.9`](https://github.com/datalad/datalad/releases/tag/0.17.9)

**Comment by yarikoptic** [comment]
it was addressed but not closed since PR was AFAIK merged when `maint` was not a default branch
