### ISSUE TITLE
try-finally broken in `add-archive-content`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7113]
It needs `pbar_id` when `earchive.get_extracted_files()` (second line in the `try` block), but it is only define later on.

This patches fixes it

```diff
diff --git a/datalad/local/add_archive_content.py b/datalad/local/add_archive_content.py
index 362eb44df..4baf869df 100644
--- a/datalad/local/add_archive_content.py
+++ b/datalad/local/add_archive_content.py
@@ -423,13 +423,13 @@ class AddArchiveContent(Interface):
         outside_stats = stats
         stats = ActivityStats()
 
+        # start a progress bar for extraction
+        pbar_id = f'add-archive-{archive_path}'
         try:
             # keep track of extracted files for progress bar logging
             file_counter = 0
             # iterative over all files in the archive
             extracted_files = list(earchive.get_extracted_files())
-            # start a progress bar for extraction
-            pbar_id = f'add-archive-{archive_path}'
             log_progress(
                 lgr.info, pbar_id, 'Extracting archive',
                 label="Extracting archive",
```

Observed with datalad 0.17.8

**Comment by mih** [comment]
Sidenote: I noticed this issue, because add-content-archive depends on the extracted archive to have sane permissions. In my case, an extracted archive had no X permissions for a subdirectory, which prevented the extraction itself from completing. Not sure to which degree such situations can be prevented in general. But given that such permissions make no sense, and also cannot be represented in a Git repo, it might make sense to attempt a mitigation.

**Comment by yarikoptic** [comment]
- any reason why it is just an issue instead of a PR? (from the diff alone it is not even clear why this patch works)
- I am ok to have datalad mitigate subdirectories incorrect permissions while also issuing some warning about that

**Comment by mih** [comment]
I have no idea whether this works, or to what degree.
