### ISSUE TITLE
Add changelog.d snippet / add (pull_request_target)  errorred out

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#7127]
### What is the problem?

Happened in https://github.com/datalad/datalad/pull/7118 

```
Notice:  To update, run: pip install --upgrade pip
+ PYTHONPATH=:/home/runner/work/_actions/datalad/release-action/v1/add-changelog-snippet/..
+ python -m datalad_release_action -c .datalad-release-action.yaml datalad/datalad add-changelog-snippet 7118
Usage: python -m datalad_release_action [OPTIONS] REPO COMMAND [ARGS]...
Try 'python -m datalad_release_action --help' for help.

Error: Invalid value for '-c' / '--config': '.datalad-release-action.yaml': No such file or directory
Error: Process completed with exit code 2.
```

### What steps will reproduce the problem?

File a PR against `maint` and ask to add changelog entry

**Comment by yarikoptic** [comment]
may be just a matter of rebasing that PR? worked out just fine in https://github.com/datalad/datalad/pull/7126

**Comment by jwodder** [comment]
@yarikoptic Yes, I believe you simply need to rebase the PR to pick up the `.datalad-release-action.yaml` file added in #7111.

**Comment by yarikoptic** [comment]
rebased and it did add ok, thanks
