### ISSUE TITLE
Make 'maint' to be the default branch (instead of master)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#7131]
- main motivation is https://github.com/datalad/release-action/issues/32 so we would get PRs against `maint` to
  - close issues for which fixes already got not only got merged but likely released (ATM I believe they might still linger around)
  - be associated with PRs
  - issues get annotated with releases of datalad in which they were addressed (ATM we do release more often from `maint` branch, and may be next major release "from master" would also just go through `maint`)

additional benefits:
- external contributors submitting bug fixes would submit them against `maint` "by default".  We already had a number of PRs which had to be rebased against `maint` since defaulted to `master`, even though were not coming from new contributors

WDYT?  I do not feel strongly about it, I see both pros and cons.

**Comment by mih** [comment]
It makes sense. `maint` is the defacto development branch for many months now. The is hardly anything happening in `master`. There is no point in optimizing for workflows that are not exercised.

**Comment by bpoldrack** [comment]
No strong feelings here. The release annotation is useful, but the "solved but not auto-closed" problem exists either way.
However, we do have the `fix-implemented` label that could be used with issues addressed in `master`.

> may be next major release "from master" would also just go through maint

Sounds right.

**Comment by jwodder** [comment]
@yarikoptic I don't see any problems, though if future releases are going to be made on maint instead of master, you'll probably want to do that by merging a PR to maint with `semver-minor` and `release` labels.

**Comment by yarikoptic** [comment]
done -- `maint` is default now, let's see what happens

**Comment by adswa** [comment]
I will also change the default branch on readthedocs to maint accordingly.
