### ISSUE TITLE
release version went completely off -- 0.9.4 instead of 0.17.9

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#7146]
see https://github.com/datalad/datalad/releases/

- [ ] do manually the fix - re-release as 0.17.9
- [ ] fix the release-action
    - [ ] add a check that next version is greater than any of the prior known ones

edit: since 0.9.3 was last release before 0.10.0 -- I guess somewhere there is a literal sorting instead of numeric/version sorting used

**Comment by bpoldrack** [comment]
Re TODOs:

We probably also want to fix/redo the "released in ..." annotation of issues.

**Comment by jwodder** [comment]
Observations on what happened:

* The logs under "Checkout source" show that all tags were cloned.
* The action reported "Previous released tag: 0.9.3".  This version is determined by [this code](https://github.com/datalad/release-action/blob/302ea58785fc4fc7d1aff8f0aa335d557373a37d/datalad_release_action/versions.py#L80-L100) (here, `tag_prefix` equals the empty string).

**Comment by jwodder** [comment]
@yarikoptic I think I've figured out what went wrong; see [this PR to release-action](https://github.com/datalad/release-action/pull/35) and note that, based on the "Checkout source" logs, 0.9.3 was the last tag cloned.

**Comment by jwodder** [comment]
Possible strategy for fixing the release:

* Push a commit directly to `maint` that fixes the CHANGELOG
* Tag this new commit as 0.17.9 and push the tag
* Edit the 0.9.4 GitHub release to point to the 0.17.9 tag, and adjust the title as well
* Delete the 0.9.4 tag
* Yank the 0.9.4 release on PyPI
* Manually make a new PyPI release

**Comment by jwodder** [comment]
@yarikoptic That should work.

**Comment by yarikoptic** [comment]
@jwodder please proceed that way then to resolve this issue. Thank you in advance! (note that benchmarks testing might error out, "known": #7149 )

**Comment by jwodder** [comment]
@yarikoptic I can't delete the release on PyPI, as I'm not associated with the project there.

**Comment by yarikoptic** [comment]
> @yarikoptic I can't delete the release on PyPI, as I'm not associated with the project there.

thanks for the ping! I deleted 0.9.4 (not just yanked) and invited you as a collaborator.

**Comment by bpoldrack** [comment]
Thank you, @jwodder!
