### ISSUE TITLE
Make `EnsureDataset` functional

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7168]
Right now this is a dummy constraint:

```
    """Despite its name, this constraint does not actually ensure that the
    argument is a valid dataset, because for procedural reasons this would
    typically duplicate subsequent checks and processing. However, it can
    be used to achieve uniform documentation of `dataset` arguments."""
```

I believe we could avoid this dilemma (and make `required_dataset` handling within each command obsolete) with the following changes

1. When `EnsureDataset` creates an instance from a a path (of any kind), i.e. received a non-instance input, it sets an attribute in the resulting instance. Maybe `.auto_instance_from_path=<original path specification>`
2. When `resolve_path()` gets such an instance via `ds=`, it uses it as its `ds_resolved=` and this new attribute as `ds=`, hence resolves paths as if a path would be given to it directly.

With these minimal changes, path resolution would stay as-is, but pretty much all use of `require_dataset()` can be removed in favor of an `EnsureDataset` constraint that actually create a dataset instance.

Of course the latter implies that uniform parameter validation is done (not just for the CLI). See #7106 and #7167 for pointers on this effort.

**Comment by mih** [comment]
Sadly, this interferes with the flyweight setup. A dataset instances passed to an underlying command will always have the attribute, because one and the same dataset instance will be retrieved.

**Comment by bpoldrack** [comment]
> Sadly, this interferes with the flyweight setup.

FTR: I think we found a solution. Currently next is about to use a `DatasetParameter` class to address this. (so, this is what core should look at)

**Comment by mih** [comment]
I am closing this issue of mine as "fixed". `datalad-next` provides a fully functional `EnsureDataset`
