### ISSUE TITLE
Erroneous git url construction with relative Windows paths for subdatasets

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#7180]
I found a Windows issue while looking into fixing #3538.
If we clone a local relative Windows path into another dataset on Windows, the remote git url of the resulting subdataset will be butchered - also with git on its own:

```
C:\Users\adina\AppData\Local\Temp\datalad_temp_1szhiauj\ds>git clone ..\origin dummy
Cloning into 'dummy'...
done.

C:\Users\adina\AppData\Local\Temp\datalad_temp_1szhiauj\ds>git -C dummy config --list
[...]
remote.origin.url=C:/Users/adina/AppData/Local/Temp/datalad_temp_1szhiauj/ds/..\origin
```

[Consulting git clone's manpage confirms that the desired format for clone urls are forward slashes only](https://git-scm.com/docs/git-clone#_git_urls).
Because we pass urls consisting of relative paths as Windows paths (with escaped backslashes) on Windows, the result of a DataLad clone is even more messed up:

```
'C:/Users/adina/AppData/Local/Temp/datalad_temp_frvczceh/ds/..\\origin'
```

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.17.10`](https://github.com/datalad/datalad/releases/tag/0.17.10)
