### ISSUE TITLE
Butchered datalad_urls on Windows when cloning subdatasets from local paths

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#7182]
On Windows, the source of a clone call is passed as is into the ```.gitmodules``` file of the superdataset as the value for ```datalad_url```. If this source is a local path, the resulting value can be something like

```
datalad_url = ..\\origin
````

(which makes sense on no platform at all). It should rather be a posix like URL, as any URL in Git's configuration files is.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.17.10`](https://github.com/datalad/datalad/releases/tag/0.17.10)
