### ISSUE TITLE
`PathRI` behavior incorrect/not helpful on Windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7186]
Demo:

```py
>>> pathlib.PureWindowsPath("C:\\Windows").as_uri()
'file:///C:/Windows'

>>> RI("file:///c:/Windows").localpath
'/c:/Windows'

>>> pathlib.PureWindowsPath('/c:/Windows')
PureWindowsPath('/c:/Windows')
```

Ergo, it get's transformed into an unusable string.

A better approach would be:

```
>>> nturl2path.url2pathname(urlparse("file:///c:/Windows").path)
'C:\\Windows'
```

`nturl2path.url2pathname` is called by `urllib.request.url2pathname` on windows.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.17.10`](https://github.com/datalad/datalad/releases/tag/0.17.10)
