### ISSUE TITLE
CRCNS meta-data

### ISSUE THREAD

**Issue by glalteva** [datalad/datalad#719]
CRCNS pipeline needs extract_meta in pipeline. JSON descriptor should include: title, description, authors, citation, license per each dataset.

**Comment by yarikoptic** [comment]
I am clearing up on how we would fetch that meta data straight from
crcns or datacite... so don't worry about this one

On Mon, 22 Aug 2016, Gergana Alteva wrote:

>    CRCNS pipeline needs extract_meta in pipeline. JSON descriptor should
>    include: title, description, authors, citation, license per each dataset.

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by mih** [comment]
I am closing this in favor of keeping #983
