### ISSUE TITLE
Tune ThreadedRunner buffer size for better performance

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7190]
Here is the patch: https://github.com/datalad/datalad-next/pull/135

When reading from SSH with the runner I can boost the performance from 30-50MB/s to ~650MB/s with the new default behavior.

**Comment by yarikoptic** [comment]
Cool! Why not just a PR here?

**Comment by mih** [comment]
We'll soon know how that works out in practice.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.1`](https://github.com/datalad/datalad/releases/tag/0.18.1)
