### ISSUE TITLE
Can we annex copy before git push when publishing ?

### ISSUE THREAD

**Issue by debanjum** [datalad/datalad#722]
On running publish it seems we do an `annex copy` after `git push`.
Currently a metadata refresh is triggered post a git push
But the traverser isn't aware of annex installed files in the dataset as the soft-links are broken atm.
Need to figure if can `annex copy` before `git push` or atleast before the post-update hook
gets triggered for the metadata refresh to be aware of annex installed files

**Comment by bpoldrack** [comment]
I don't entirely get, what this is about, but want to note, that as far as I'm aware for `annex copy`'ing before the `git push` we need an annex at the target already. So, when republishing a dataset this could be done, but at least at the first time we publish an annex, the annex brunch needs to be pushed before `annex copy`.
Need to test, whether annex triggers the post-update hook, if we try to do it without explicitly pushing the annex brunch first, but let annex do whatever it takes.

**Comment by yarikoptic** [comment]
On Thu, 25 Aug 2016, Benjamin Poldrack wrote:

>    I don't entirely get, what this is about, but want to note, that as far as
>    I'm aware for annex copy'ing before the git push we need an annex at the
>    target already. So, when republishing a dataset this could be done, but at
>    least at the first time we publish an annex, the annex brunch needs to be
>    pushed before annex copy.

remote should be initialized as annex by then... so might all be kosher

>    Need to test, whether annex triggers the post-update hook, if we try to do
>    it without explicitly pushing the annex brunch first, but let annex do
>    whatever it takes.

actually it better doesn't trigger it (and I think it doesn't since
nothing is pushed I believe and it is annex shell which should trigger
update of the git-annex branch locally, do necessary changes etc). We
might need though to invoke 'git annex merge' before doing git push...
yeah -- needs testing and playing around with it

**Comment by yarikoptic** [comment]
@debanjum so did you try copying before pushing, or for now we should do "double run"?

**Comment by debanjum** [comment]
no not till now. The current publish was with the annex copy before the git push

**Comment by mih** [comment]
Same as #1480. Closing.
