### ISSUE TITLE
dochelpers `[PY: PY]` macro handling cannot deal with `[]` in the conditional docs

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7225]
The datalad-next `credentials` command shows it in the CLI for its `spec` parameter. It fails to find the macro and leaves it in

**Comment by bpoldrack** [comment]
Looking into it.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.17.10`](https://github.com/datalad/datalad/releases/tag/0.17.10)
