### ISSUE TITLE
install --recursive is not doing that for directories.

### ISSUE THREAD

**Issue by mih** [datalad/datalad#724]
Tried to install everything under a directory in a subdataset. Install reported lots of progress, but actually installed nothing. Tried various arguments to recursive, same result.

I guess this might not need a dedicated fix, as the reimplementation of `install` should do something about it, but reporting nevertheless to keep track of this.

**Comment by yarikoptic** [comment]
I find it useful to provide sample cut paste of the command and output...

On August 25, 2016 6:46:34 AM EDT, Michael Hanke <notifications@github.com> wrote:
>Tried to install everything under a directory in a subdataset. Install
>reported lots of progress, but actually installed nothing. Tried
>various arguments to recursive, same result.
>
>I guess this might not need a dedicated fix, as the reimplementation of
>`install` should do something about it, but reporting nevertheless to
>keep track of this.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/724

-- 
Sent from a phone which beats iPhone.

**Comment by hanke** [comment]
Me too!

**Comment by bpoldrack** [comment]
Are we talking about "installing" data here? In that case, this is deprecated, since with new API, `datalad install` is about datasets and you would need to use `datalad get`. (with the exception to provide `--get-data` to `ìnstall`in order to get all the data when installing a dataset)

**Comment by yarikoptic** [comment]
ok with me -- we could bring back 'install datafiles' later if we see a demand/use cases.

**Comment by bpoldrack** [comment]
Since with `datalad get` this works as far as I'm aware, I mark this for closing by PR #613 .
