### ISSUE TITLE
Loosen chardet upper version limit

### ISSUE THREAD

**Issue by sanjayankur31** [datalad/datalad#7256]
I see that chardet was set to `<5` because requests didn't support it before:

https://github.com/datalad/datalad/commit/0c88872a043db4970bcdd248cb1e5a00801e24d2

however, the latest versions of requests pins chardet to `<6`, implying that it does support version 5. So the chardet dep can also be bumped here.

https://github.com/psf/requests/commit/73793ce43e3d940a0f8d6b9b8ff125617828d8a1

**Comment by kimsin98** [comment]
Addressed with https://github.com/datalad/datalad/pull/7263!

**Comment by adswa** [comment]
thx all!
