### ISSUE TITLE
Nose tests action fails

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#7259]
The "old nose tests" Github action currently fails due to installation issues (reported version confllicts). Example here: https://github.com/datalad/datalad/actions/runs/3925056499/jobs/6709718821

We need to either fix it or consider disabling (do we still need this?)

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.2`](https://github.com/datalad/datalad/releases/tag/0.18.2)
