### ISSUE TITLE
create-sibling fails with non-english language setting on the server

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#7264]
`create-sibling` fails with non-existing target directories, when the language setting on the server isn't english. That's because we catch the respective failure of `ls` by matching its output to `No such file or directory`. If we need to rely on such output to figure out what went wrong, we should explicitly run `LC_ALL=C ls ..` instead.

Thanks, @nobodyinperson, for reporting.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.2`](https://github.com/datalad/datalad/releases/tag/0.18.2)
