### ISSUE TITLE
Provide `datalad.commands` as an alternative to `datalad.api`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7269]
The term API is ambiguous, because the actual Python API is comprised of several suits already. With the ongoing RF to streamline "the API" it would be good to make it easy to communicate what is changing and what is not. This would also translate into advice to consumers of the respective APIs.

From my POV it would make sense to take the command-level API (plus the `Dataset` class) and label it accordingly. This is essentially identical to the current `datalad.api`, but would/could be more appropriately named -- for examples `datalad.commands`.

Alternatively, we could very clearly document that nothing outside `datalad.api` is anyhow considered to be "an API" (which would be a stronger, and likely needlessly so, statement).

**Comment by adswa** [comment]
+1 from me. I would also consider it more user-friendly, as the term ``commands`` is less technical than ``api`` and sounds more user-facing

**Comment by yarikoptic** [comment]
my 1c:  `api` vs `commands` -- potato potato to me...   All those "commands" are "bound methods of `Interface`, not `Command` classes. And we also expose `Dataset` within `.api` which is not a command of any kind, and makes little sense on CLI.

Historical factor -- IIRC `datalad.api` came from `mvpa2.api` which was collated for the same reason of having various constructs spread out through `mvpa2.` hierarchy.  Indeed the entire surface of a python package is an API, and we are not particular with hiding via `_protected` or `__private` python tricks. But to some degree `.api` is the "public interface" we expose/support explicitly. 

As such rename IMHO would not solve any problem really and rather just cause bad UX of needing to adjust the scripts etc, inline with the last paragraph,  I would have just preferred some documentation which would advise to use `datalad.api` as the interfaces we provide/support but also aggregate from extensions (thus not visible anywhere else within `datalad.` name space).
