### ISSUE TITLE
Purpose of config.dataladlock

### ISSUE THREAD

**Issue by ins0mniac2** [datalad/datalad#7276]
I tried to look but didn't find much documentation. What does this file do ?

**Comment by yarikoptic** [comment]
it is indeed not documented anywhere. Where would you recommend to do so?

as for purpose - just search for it to find being used in https://github.com/datalad/datalad/blob/HEAD/datalad/config.py#L894 for `InterProcessLock(lockfile, logger=lgr):` . So we use it to guarantee that no two processes try to modify the same file at the same time by calling `git config ...` at the same time.

**Comment by adswa** [comment]
I'm closing this question-type issue as answered. If there are more questions, or if you know a place where this could be added to the documentation, please feel free to reopen this and comment further. :)
