### ISSUE TITLE
OPT: fast=False for info and repo_info of AnnexRepo

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#728]
add "fast=False" kwarg to 'def info' and 'def repo_info' of AnnexRepo   and if True, add '--fast' flag to annex call.  I think for the 'ls' use  we have, we don't need any network-related etc stuff annex info might be  doing, so --fast should be that -- faster ;)  would be interesting also  to time it (if there is actually any benefit).

**Comment by debanjum** [comment]
I think I tried testing `ls` with `info --fast` but it wasn't faster, though I can't seem to find my notes on it so not sure.

**Comment by debanjum** [comment]
Also `repo_info` in fast mode doesn't give much info. The size info required by `ls_json` isn't returned by repo_info in fast mode so it wouldn't be very useful for ls_json.

**Comment by yarikoptic** [comment]
On Fri, 26 Aug 2016, Debanjum wrote:

>    Also repo_info in fast mode doesn't give much info. The size info required
>    by ls_json isn't returned by repo_info in fast mode so it wouldn't be very
>    useful for ls_json.

got it
-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik
