### ISSUE TITLE
[question] Does datalad push transfer all annex data?

### ISSUE THREAD

**Issue by mattcieslak** [datalad/datalad#7282]
Hi! A quick question - does `datalad push` transfer the annexed data for all files that have ever been annexed? Or only files that currently exist in the repository?

Suppose I deleted a bunch of data and committed the change. If I have an s3 special remote named `s3remote`

```
datalad push --to s3remote
```

will the deleted files be transferred to the remote? This would be the first push to `s3remote`

Thanks in advance!

**Comment by yarikoptic** [comment]
only current tree, so if files were deleted in prior commits, and thus not present in current tree -- they will not be transferred.  You can transfer them using git-annex directly, e.g. `git annex push --all` would push all keys present locally.  
Note: If you set `wanted` expression for the remote, then only those which match that `wanted` expression would be pushed. Eg. I typically set

```
git annex wanted REMOTE "not metadata=distribution-restrictions=*"
```

and then use `git annex metadata` to annotate files which have any distribution restrictions. Then `datalad push` does the right thing by default

**Comment by mattcieslak** [comment]
Thank you @yarikoptic!!
