### ISSUE TITLE
`whereis` my whole folder

### ISSUE THREAD

**Issue by mlell** [datalad/datalad#7285]
### What is the problem?

I have difficulty being sure that all my data is uploaded to a sibling repo and that I can remove my local folders. But I do not want to push (annexed data of) all, but only specific revisions, because I would waste space with uploading all outdated big results. `git annex whereis` gives me detailed information where my individual files are, but if I have a lot of them I would need a way to do a `git annex whereis`  for a whole folder. If datalad (or `git  annex`?) would provide such a feature it would create additional security as one can check whether previous pushing commands were done correctly 

The same problem could also be tackled from another angle: Something like `git log --oneline` but for each revision report whether all annexed files are available in this repository.

### What steps will reproduce the problem?

1. Create a dataset
2. Create a sibling
3. Create a folder `data/` and in there create and commit 100 annexed files 
4. Push to sibling
5. Execute `git annex whereis data/`

## Actual result

You get for each file a pretty-printed summary in which repositories the files is: 

Number of output lines ≈ (number of files) * 2 [b/c empty lines] * (number of siblings + 1)

So for 100 annex'ed files and one sibling that is about 100 * 2 * 2 = 400 lines to check 

## Wished-for result
For example

     $ datalad whereis data/ 
     # All files in this folder are found in the following siblings:
     here
     origin

### Additional context

I use the following 3-tier setup for my research project, which reflect longer and longer iterations. Not all versions but only mature ones (for a different definition of "mature" per tier) get uploaded to the higher tier.

1. `/home/me/bench/`   --> "working bench": I clone a dataset from `datasets/` to here to fiddle around
2. `/home/me/datasets/`  --> "private repo" of my data sets. In "bench" datasets, subdatasets are cloned from here
3. `/groupfiler/datasets` --> "group repo": Dataset versions that are shared with others are uploaded here. 

I need a way to quickly see e.g. for a dataset in `/home/me/bench/...` whether the `results/` folder of the current revision is completely uploaded to e.g. `/home/me/datasets` so that I can delete the dataset (with all non-uploaded obsolete versions) from `bench`

**Comment by yarikoptic** [comment]
are you looking for `git annex find` command - https://git-annex.branchable.com/git-annex-find/ ?

**Comment by yarikoptic** [comment]
let's consider answered, can reopen if more to be cleared up. Cheers

**Comment by mlell** [comment]
Yes, (for the record), I can list files that are in a specific sibling using `git annex find --in=SIBLING` (for RIA stores, I need to append `-storage` to avoid the error: 

    git-annex: cannot determine uuid for origin (perhaps you need to run "git annex sync"?)

So if my RIA-storage is called "origin", I need to say `git annex find --in=origin-storage`. 

If I want to check if my whole directory `(FOLDER)` is uploaded, I can do `git annex find (FOLDER) --not --in=origin-storage`

So that is not quite straightforward for newcomers, but possible. Thanks! 

One question remains: The help page `git-annex-matching-options` says:

`--in=` Matches only when git-annex believes that the content is present in a repository

What does "believes" mean? How can I make `git annex` *know* instead of *believing* ?
