### ISSUE TITLE
A few commands, including `create_sibling_ria` and `foreach_dataset`, are missing from python module reference

### ISSUE THREAD

**Issue by mslw** [datalad/datalad#7288]
I noticed that these commands are not listed in the [Python module reference](https://docs.datalad.org/en/stable/modref.html) of our online docs:

- `create_sibling_ria`
- `export_archive_ora`
- `foreach_dataset`
- `shell_completion`
- `uninstall`

`uninstall` has been removed in 85b9edf5c due to deprecation, and `shell_completion` has questionable value in Python API usage, but I feel that the first three (or even four) should be included - and aren't probably due to simple omission from the listing. The first three are listed under the methods of `datalad.api.Dataset`, but that table has no links to the method description.

I'll make a PR with the small change.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.3`](https://github.com/datalad/datalad/releases/tag/0.18.3)
