### ISSUE TITLE
pytest keyring setup causes writes to user HOME

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7295]
The pytest `conftest.py` provided by this package sets the keyring backend to `plaintext`. This was implemented in https://github.com/datalad/datalad/commit/d8d538ae77ee8740ee2ca44e2b33f99b73a4ec3c by @bpoldrack to address an issue of (non)interactivity.

This has created a complex situation that made (and continues to make) my investigation of https://github.com/datalad/datalad-next/issues/249 difficult.

The location of this plain text file that will receive the secrets is `$HOME/.local/share/python_keyring/keyring_pass.cfg`. This would be fine. However, the effective value of `$HOME` is not the fake HOME set up for pytest, but the actual HOME of the user running pytest. The plaintext file is also not removed at the end of a test run.

This means that a user inspecting their regular keystore for "why do I have this credential?" will not find anything (because the backend is different). A developer inspecting the test HOME will not find anything. However, the credential updates are persistent across pytest runs -- which is a non issue for github actions or appveyor, but is an issue for a developer trying to debug locally or on an appveyor worker what is happening. The latter because running pytest twice on that worker (inside and outside the standard runs) will place/reuse credentials that the respective other run does not know (yet).

I think there should be a fixture that kills the plaintext file on after each test execution.

I also think that the plaintext backend should not live in a user's HOME dir and potentially interfere with legitimate real-world usage by that user.

**Comment by mih** [comment]
I came to the conclusion that it would be best to do:

- implement a `MemoryKeyring`, in the same spirit as `atalad.support.keyring_.MemoryKeyring`, but as an actual backend for python-keyring.
- implement a pytest fixture `memory_keyring` that can be used by particular tests, which set the keyring backend temporarily. This should be simple, the sketch is here https://github.com/jaraco/keyring#runtime-configuration
- annotate any test that requires credentials (either to be read, or written to a secret store) with this fixture.

It would be possible to make this fixture "auto-use". However, a conclusion of my exercise here is that I would have really liked to know which test _knowingly_ manipulates credentials. Having an explicit fixture would communicate that intuitively.

**Comment by mih** [comment]
I have implemented such a fixture and will test drive it now in datalad-next.

**Comment by yarikoptic** [comment]
> However, a conclusion of my exercise here is that I would have really liked to know which test _knowingly_ manipulates credentials

may be useless to @mih who already figured it all out, but just to share a tip of trade for others who might be reading -- in such cases I either
- if one/first test which matters -- I just make such file owned by root so user cannot write, run tests until they error out 
- if all -- strace execution tracking `open` syscall and interleaving output with tests runs output. Then see during what test(s) that file was opened.
