### ISSUE TITLE
Non-installed `Dataset` instance is using a separate, but non-global config manager

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7299]
Chasing https://github.com/datalad/datalad-next/issues/249 led me to realize that calling `Dataset().config` for any Dataset that does not actually exist yet locally, the returned instance is NOT the same as `datalad.cfg`.

It is a dedicated instance for a `Dataset` instance, which is parameterized like the global one, but still a separate instance.

I think this does not make sense, and the docs provide no counter arguments.

They say:

> Get an instance of the parser for the persistent dataset configuration.

There is a lot that is not persistent about this. For example, I can add overrides to this "persistent" configuration, but these overrides evaporate, as soon as a repo materializes for this `Dataset`.

Moreover, calling `set()` on this separate `ConfigManager` instance will not trigger the update routines in the global manager. Even worse, the `ConfigManager` instance is bound to a `Dataset` instance and will persist, as long as that parent instance persists. Given that DataLad implements a Flyweight pattern for datasets, this means that such configuration containers will survive for a surprisingly long time. Commands would "rediscover" a dataset instance for a particular path, and if there continues to be no repo, manipulations done via the global config manager will NOT be reflected in this separate instance -- even if the config items come from `system` or `global` scope!

I think this is rather undesirable complexity. I cannot come up with a reason why `Dataset().config` for an uninstalled dataset should not simply return `datalad.cfg`.

**Comment by mih** [comment]
Here is another side to the same problem. I now think I understood that the situation that triggered this issue led to two different config managers to be used by two different commands. The problem could be paved over by making these two particular commands behavior more uniformly, and thereby end up using the exact same instance.

However, as a general setup, this seems undesirable as a minimum requirement.

What I sketched about still makes sense to me to do. However, it does not address a related problem:

Presume a GLOBAL config is modified via a DATASET-bound `ConfigManager`. This change would be in-effect immediately via all `Dataset` and `Repo` instances. However, it would not trigger an update of the central instance `datalad.cfg`.

However, there is only one global instance. When any `ConfigManager` instance performs a `reload()`, it can know whether it is the global instance. If it is NOT, it can also trigger a `reload()` in the global instance.

Such an operation can be triggered bluntly in `reload()` itself, or more targeted (based on the manipulated scope) in any of the setters.

**Comment by yarikoptic** [comment]
Forcing reload of global makes sense to me as a workaround. Workaround because in principle global, when queried, should detect global config file modification and reload automagically. But our magic overall is a bit flawed here AFAIK, and https://github.com/datalad/datalad/issues/5824 was previous general concern on that.

**Comment by mih** [comment]
> Forcing reload of global makes sense to me as a workaround. Workaround because in principle global, when queried, should detect global config file modification and reload automagically. But our magic overall is a bit flawed here AFAIK, and #5824 was previous general concern on that.

My my concern with update-on-read is that reads are FAR more frequent than writes. Updates are also expensive. When there is an updated-on-read expectation, it would be sensible to have that expectation cover any sources of configuration. Hence a modification check of the global config file is insufficient.

The original reason for not doing that to start with was that it would require per filesystem implementation to get that right, and it might still be limited to the time resolution supported by each particular file system.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.3`](https://github.com/datalad/datalad/releases/tag/0.18.3)
