### ISSUE TITLE
[question] How to transfer from a ria store to an AWS sibling

### ISSUE THREAD

**Issue by mattcieslak** [datalad/datalad#7311]
Hi! I have a RIA store created by running a FAIRly big workflow. I'd like to create an AWS special remote and send all the data there. I have tried these steps:

 1. clone from the ria+file location
 2. create an AWS sibling in the clone
 3. datalad push to the aws sibling

However, when the push executes I see
```
$ datalad push --to AWS -J 2 -f all
action summary:
  copy (notneeded: 69161)
```

Is this because there is no data in the local annex? If so, would it be safe to create a reckless ephemeral clone and add the sibling to that?

Thanks in advance!

**Comment by mattcieslak** [comment]
Following up, I tried the --reckless ephemeral and the data was indeed pushed to AWS. However, it looks like the AWS availability was not saved in the original RIA store. Do you have a recommendation for this use case?

**Comment by yarikoptic** [comment]
this indeed would only work to transfer everything present in local remote.  Recently (so install most recent release) git annex got ability to `copy --from REMOTE1 --to REMOTE2` so you don't need to `get --all` first explicitly. We are about to start using that e.g. in https://github.com/dandi/dandisets/pull/336/files . So you could try that I guess, smth like `git copy --from ria --to AWS -J5 --all` and see how that goes ;-)  if need to do across hierarchy -- `datalad foreach-dataset` is there to help ;)

**Comment by mattcieslak** [comment]
Works beautifully, thank you as always @yarikoptic
