### ISSUE TITLE
published index.html (and other files) have 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#733]
my umask is too restrictive generally (077) so I guess stored/generated locally files would have read permissions wiped out for group/other.  But I am creating publication target with `--shared all` so I guess we should manually assure that permissions are good enough for that mode
```
$> ls -l .git/datalad/web/assets/
total 12
4 drwx------ 2 yoh yoh 4096 Aug 28 16:04 css/
4 drwx------ 2 yoh yoh 4096 Aug 28 16:04 images/
4 drwx------ 2 yoh yoh 4096 Aug 28 16:04 js/
```

**Comment by yarikoptic** [comment]
How is it going @debanjum?

**Comment by debanjum** [comment]
not that well, given that smaug is still unreachable for me and i need to debug/see_logs of the failed travis builds on smaug :/

**Comment by debanjum** [comment]
the docker build on travis/smaug is failing across multiple (seemingly) unrelated pr's

**Comment by yarikoptic** [comment]
If you are talking about nd90 that was fixed yesterday evening - #742. Just merge master and you will be good

**Comment by yarikoptic** [comment]
So figure out what is up with Smaug for you... Try to hop through another box. Recall what you have changed with your laptop setup from before.

**Comment by debanjum** [comment]
Yeah solved my smaug issues

**Comment by yarikoptic** [comment]
Which was...?
