### ISSUE TITLE
datalad special remote's reporting on error causes is suboptimal

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#7332]
Just observed a user getting `Failed to download from any of 2 locations [None]`.
This gives no idea what the `None` would be about. It's actual purpose is to record the `__cause__` of the original exception raised by the download call within the special remote's `transfer_retrieve`.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.3`](https://github.com/datalad/datalad/releases/tag/0.18.3)
