### ISSUE TITLE
make it display some meaningful msg if there were no datalad on remote and no jsons were generated

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#734]
1. when create-for-publication -- if no `datalad --version` good enough available -- issue a warning (that hook wouldn't work out etc, ask to install datalad on the server of at least version X ;) )
2. make web (index.html) display some meaningful msg, not just a blank page with the logo as on http://www.onerussian.com/video/OHBM2015/

**Comment by mih** [comment]
What is the status of this one? Is this about the web UI?

**Comment by yarikoptic** [comment]
I think we have some error message displayed ;-) either it is very meaningful is for your judgement:
http://www.onerussian.com/tmp/testds/
```
ERROR: Could not find any metadata directory. Sorry. Most probably cause is that 'publish' didn't run the post-update hook
```
I think I will close with this, thanks for reminding @mih
