### ISSUE TITLE
Cloning datasets from a hard-drive and copying the content produces weird behaviour

### ISSUE THREAD

**Issue by just-meng** [datalad/datalad#7348]
## 1. A dataset created on the Linux system

```
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/03_combined_data/01_Preliminary_Psychedelics_pandas$ datalad siblings
.: here(+) [git]
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/03_combined_data/01_Preliminary_Psychedelics_pandas$ git log -5 --oneline
ca9de8f (HEAD -> master) save the most updated state of the ds from before remaking the superds
de58885 Instruct annex to add text files to Git
84116a3 [DATALAD] new dataset
```
I'm on the master branch.

## 2. A dataset cloned from the hard-drive with annexed content got from the drive
```
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/02_Psychedelics_L5b_bpod$ datalad siblings
.: here(+) [git]
.: origin(+) [/media/meng/Seagate Expansion Drive/datalad_datasets/02_Psychedelics_L5b_bpod/ (git)]
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/02_Psychedelics_L5b_bpod$ git log -5 --oneline
195b6a8 (HEAD -> adjusted/master(unlocked), origin/adjusted/master(unlocked), origin/HEAD) git-annex adjusted branch
6b0546e (origin/master, master, refs/basis/adjusted/master(unlocked)) add all data until now for the l5b exp.
00f8822 Instruct annex to add text files to Git
48c5112 [DATALAD] new dataset
b0e42aa commit before entering adjusted branch
```
I see two more branches listed in the first line. 

## 3. A dataset cloned from the drive, content copied onto not unlocked files, git reset to the state after cloning

```
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/01_Preliminary_Psychedelics_2p$ git log -5 --oneline
a3e94412 (HEAD -> adjusted/master(unlocked), origin/master) save recorded data
9617b3d1 Instruct annex to add text files to Git
a7307eab [DATALAD] new dataset
```
The master branch has "vanished". Commiting a new file to the dataset leads to the following:
```
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/01_Preliminary_Psychedelics_2p$ datalad status
untracked: test.md (file)
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/01_Preliminary_Psychedelics_2p$ datalad save -m "add text.md to see what happens with the git log outputs" test.md 
add(ok): test.md (file)                                                                                                                
save(ok): . (dataset)                                                                                                                  
action summary:                                                                                                                        
  add (ok: 1)
  save (ok: 1)
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/01_Preliminary_Psychedelics_2p$ git log -5 --oneline
82b497be (HEAD -> adjusted/master(unlocked)) git-annex adjusted branch
cc6fd0c7 (master, refs/basis/adjusted/master(unlocked)) copy content onto unlocked files
a3e94412 (origin/master) save recorded data
9617b3d1 Instruct annex to add text files to Git
a7307eab [DATALAD] new dataset
```
HEAD points at the adjusted branch that perhaps exists on the hard-drive. What is this "refs/basis/adjusted/master(unlocked)"?
The commit is is not listed in git log. 

## 4. A dataset cloned from the drive, content copied onto unlocked files, saved after locking

```
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/02_preprocessed_data/01_Preliminary_Psychedelics_suite2p$ git log -5 --oneline
57e0958 (HEAD -> adjusted/master(unlocked)) git-annex adjusted branch
7ffcfce (master, refs/basis/adjusted/master(unlocked)) copy files onto place-holder
615a318 (origin/master) refine cell selection
8d0e9d2 add neuropil decontaminated traces, output of fissa
0e12a9e add layers rois
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/02_preprocessed_data/01_Preliminary_Psychedelics_suite2p$ datalad siblings
.: here(+) [git]
.: origin(+) [/media/meng/Seagate Expansion Drive/datalad_datasets/01_Preliminary_Psychedelics_suite2p/ (git)]
```

Adding a new file to the dataset leads to:
```
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/02_preprocessed_data/01_Preliminary_Psychedelics_suite2p$ git log -5 --oneline
3225325 (HEAD -> adjusted/master(unlocked)) git-annex adjusted branch
e489338 (master, refs/basis/adjusted/master(unlocked)) save a test file
7ffcfce copy files onto place-holder
615a318 (origin/master) refine cell selection
8d0e9d2 add neuropil decontaminated traces, output of fissa
```
The commit has worked as expected. But we still have those branches. 

### What steps will reproduce the problem?

- clone a dataset with annex'd files from a Windows system to a external harddrive
- clone the same dataset to a Linux system
- copy & paste the files from the Windows system to the Linux system
- now copy the files onto the annex'd files without unlocking the files
- git annex lock the files
- datalad save the modification, it should say ok, but datalad status will still report that those files are modified
- git reset --hard to the state after cloning
- datalad status --annex all should show all files present and nothing to save
- git log should show that the master branch has vanished
- commit a new file and see that git log would change, undo the reset, but the new commit does not show up

### DataLad information

# WTF
## credentials 
  - keyring: 
    - active_backends: 
      - SecretService Keyring
      - libsecret Keyring
      - EncryptedKeyring with [PBKDF2] AES256.CFB v.1.0 at /home/meng/.local/share/python_keyring/crypted_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at /home/meng/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/meng/.config/python_keyring/keyringrc.cfg
    - data_root: /home/meng/.local/share/python_keyring
## datalad 
  - version: 0.15.5
## dataset 
  - branches: 
    - adjusted/master(unlocked)@195b6a8
    - git-annex@ee37f1d
    - master@6b0546e
  - id: 18972008-4baa-4943-803d-3f86b8cc9738
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/02_Psychedelics_L5b_bpod
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.6.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20210223
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.34.1
  - cmd:system-git: 2.34.1
  - cmd:system-ssh: 8.9p1
  - exifread: 2.3.2
  - humanize: 0.0.0
  - iso8601: 1.0.2
  - keyring: 23.5.0
  - keyrings.alt: 4.1.0
  - msgpack: 1.0.3
  - mutagen: 1.45.1
  - requests: 2.25.1
  - wrapt: 1.13.3
## environment 
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US
  - LC_ADDRESS: de_DE.UTF-8
  - LC_IDENTIFICATION: de_DE.UTF-8
  - LC_MEASUREMENT: de_DE.UTF-8
  - LC_MONETARY: de_DE.UTF-8
  - LC_NAME: de_DE.UTF-8
  - LC_NUMERIC: de_DE.UTF-8
  - LC_PAPER: de_DE.UTF-8
  - LC_TELEPHONE: de_DE.UTF-8
  - LC_TIME: de_DE.UTF-8
  - PATH: /home/meng/anaconda3/bin:/home/meng/anaconda3/condabin:/home/meng/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/meng/gin
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 8
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20210223
## location 
  - path: /media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/02_Psychedelics_L5b_bpod
  - type: dataset
## metadata_extractors 
  - annex (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp (datalad 0.15.5): 
    - distribution: datalad 0.15.5
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.10.6
## system 
  - distribution: linuxmint/21.1/Vera
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 335
  - name: Linux
  - release: 5.15.0-67-generic
  - type: posix
  - version: #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023

### Additional context

on-going discussion in datalad office hour

**Comment by just-meng** [comment]
In the 3. case, deleting the test file again did produce a commit in the repo history! So only one commit is swallowed: 
```
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/02_Psychedelics_L5b_2p$ rm test 
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/02_Psychedelics_L5b_2p$ datalad save -m "delete test file" test
delete(ok): test (file)                                                                                                                
save(ok): . (dataset)                                                                                                                  
action summary:                                                                                                                        
  delete (ok: 1)
  save (ok: 1)
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/02_Psychedelics_L5b_2p$ git log -5 --oneline
a4fa6357 (HEAD -> adjusted/master(unlocked)) git-annex adjusted branch
dbf0bc4f (master, refs/basis/adjusted/master(unlocked)) delete test file
3f42cbed copy content unto annexed files without unlocking
be9df6b2 (origin/master) add missed fils of 230130A of last commit
982d8fff add mouse 230123A_Sim-Cre with quality check only no data
```
Strange, but it now seems to behave just as the 4. dataset.

Also adding a commit to the 2. dataset made the two branches go away
`origin/adjusted/master(unlocked)`, `origin/HEAD`. 
```
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/02_Psychedelics_L5b_bpod$ git log -5 --oneline
195b6a8 (HEAD -> adjusted/master(unlocked), origin/adjusted/master(unlocked), origin/HEAD) git-annex adjusted branch
6b0546e (origin/master, master, refs/basis/adjusted/master(unlocked)) add all data until now for the l5b exp.
00f8822 Instruct annex to add text files to Git
48c5112 [DATALAD] new dataset
b0e42aa commit before entering adjusted branch
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/02_Psychedelics_L5b_bpod$ vim test
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/02_Psychedelics_L5b_bpod$ datalad save -m "add test file" test 
add(ok): test (file)                                                                                                                   
save(ok): . (dataset)                                                                                                                  
action summary:                                                                                                                        
  add (ok: 1)
  save (ok: 1)
(base) meng@meng-MS-7D06:/media/meng/Data/Meng_Psychedelics/01_data/01_raw_data/02_Psychedelics_L5b_bpod$ git log -5 --oneline
f2abb36 (HEAD -> adjusted/master(unlocked)) git-annex adjusted branch
67ac9b6 (master, refs/basis/adjusted/master(unlocked)) add test file
6b0546e (origin/master) add all data until now for the l5b exp.
00f8822 Instruct annex to add text files to Git
48c5112 [DATALAD] new dataset
```
Now basically all datasets 2., 3., and 4. behave the same way. I'm less worried that something is completely off, but I still would like to understand why I'm still on an adjusted branch. Is this due to the import from a Windows file system? Will it have any consequences for me?

**Comment by bpoldrack** [comment]
So, I'm not completely clear what's going on, yet, @just-meng, but first things first:

The presence of adjusted branches does come from the original dataset on windows (and/or the externa drive) and is not a problem per se. See https://git-annex.branchable.com/git-annex-adjust/. That feature is used on Windows and filesystems that have issues with symlinks. 

What's a bit strange is, that you appear to be on an adjusted branch on your clone on linux. What I also don't instantly get is, why your commit disappeared. Trying to reproduce that situation.

Can check `git branch -a` from within the clone on the drive as well as the original one (if that's accessible to you)?

**Comment by mih** [comment]
I think this is known breakage. See https://github.com/psychoinformatics-de/knowledge-base/issues/12#issuecomment-1508225312
