### ISSUE TITLE
Original user cannot save data owned by other user

### ISSUE THREAD

**Issue by anikfal** [datalad/datalad#7356]
May be related to #3685 or #2683

1. The dataset and sub-dataset are created by `user1`.
2. Inside the sub-dataset some data have been stored by `user2`.
3. `user1` has been given full 777 permission to the data inside sub-dataset (stored by `user2`).

Now inside `sub-dataset`, after running `datalad save -m "save data stored by user2"` by `user1`, the error below happens:

> [WARNING] Received an exception CommandError(CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- isen_ECT_00020112.nc' failed with exitcode 1 under /p/largedata2/detectdata/DataLad_user1/colabsub [info keys: stdout_json]
> \>  isen_ECT_00020112.nc: setFileMode: permission denied (Operation not permitted) [err: 'add: 1 failed']). Canceling not-yet running jobs and waiting for completion of running. You can force earlier forceful exit by Ctrl-C.                                                           
> [INFO   ] Canceled 0 out of 0 jobs. 0 left running. 
> Total: 0.00 datasets [00:00, ? datasets/s]CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- isen_ECT_00020112.nc' failed with exitcode 1 under /p/largedata2/detectdata/DataLad_user1/colabsub [info keys: stdout_json]
> \>  isen_ECT_00020112.nc: setFileMode: permission denied (Operation not permitted)
> add: 1 failed

**Comment by yarikoptic** [comment]
> 3\. `user1` has been given full 777 permission

it is more of an "entire world" is given full permission.
Just try manually `git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- isen_ECT_00020112.nc` to possibly see more detail.  But overall -- I would not be surprised if anyways it would not work.  If you want to have repository managed by multiple users, add them all to some joint group, make directory group writeable and `git init` (or `datalad create` if starting from total scratch) with `--shared=group` first.

**Comment by yarikoptic** [comment]
well, may be your `chmod` was actually not effective or smth like that -- can also try without `--json` but I bet you will just see that `isen_ECT_00020112.nc: setFileMode: permission denied (Operation not permitted)` .  Might get better idea if you do smth like

```
echo $USER
ls -ld . sen_ECT_00020112.nc
```

**Comment by anikfal** [comment]
`echo $USER`
> nikfal1

`ls -ld . isen_ECT_00020112.nc`
> drwxrwsr-x+ 4 nikfal1 detectdata      4096 Mar 27 13:23 .
> -rwxrwxrwx+ 1 colab   detectdata 164214220 Mar 27 11:32 isen_ECT_00020112.nc

**Comment by anikfal** [comment]
Well actually that `--shared=group` option totally solved the issue. However, it seems i have to recreate all the sub-datasets.

**Comment by yarikoptic** [comment]
yeap, [I remain of an opinion](https://github.com/datalad/datalad/issues/7356#issuecomment-1485055290) that it would be the best way forward since permissions can be tricky to get them right ;)
I would consider this issue/question answered. Follow up if more

**Comment by anikfal** [comment]
There are also some simple Git configurations that worked for me:

After navigating to the sub-dataset:
```
git config --local core.sharedRepository true
git config --local receive.denyNonFastForwards true
```
Now `datalad save` works.

**Comment by yarikoptic** [comment]
well, *works* would have a stretch of meaning here since simply changing config does nohow changes permissions for already fetched keys, so group might not be able to access (if your umask was too restrictive) or drop already fetched keys.
AFAIK `git config --local receive.denyNonFastForwards true` should have nothing to do with shared aspect.

**Comment by anikfal** [comment]
First I did `datalad create` a new sub-dataset with `--shared=group`. Inside the newly created subdataset:
`git config --list --show-origin`

> ...
> file:.git/config        core.sharedrepository=1
> file:.git/config        receive.denynonfastforwards=true
> ...

So that `receive.denynonfastforwards` had been added to the git configurations by applying `--shared=group`. I didn't know the role of `receive.denynonfastforwards`. Just wanted to re-configure the old dataset to be identical to that of the newly created sub-dataset with `--shared=group`.

**Comment by yarikoptic** [comment]
`receive.denynonfastforwards` is just that -- to deny non-fast-forward pushes... it is good to have and default setting AFAIK.   My comment was just that it does have nothing to do with shared vs not.

**Comment by anikfal** [comment]
If another user makes a **subdirectory with some contents inside it**, even by applying the settings discussed above, they cannot be saved by `datalad save`.
Whereas, datalad can save other user's data, if the data-files are **not stored in a directory owned by that user**.

So it seems `datalad save` cannot be applied on a (not empty) directory created by another user. This issue makes it challenging to manage other user's data.
