### ISSUE TITLE
datalad save with -d^ has no effect

### ISSUE THREAD

**Issue by ddeepwell** [datalad/datalad#7364]
### What is the problem?

Running `datalad save` with the flag `-d^` within a subdataset has no effect. The existing untracked files remain untracked and there are no new commits listed in the git log.

The `-d^` flag is a valid input when used with `datalad run` where the commit is recorded in both the parent and subdataset. Extending from this example, I assumed that `-d^` with `datalad save` would update both the parent and subdatasets. Furthermore, the documentation has no information on using `-d^`.

### What steps will reproduce the problem?

```
datalad create /tmp/test_sub
cd /tmp/test_sub
datalad create -d . sub1
cd sub1
head -c 1000 /dev/urandom > file.bin
datalad save -d^ -m "Add file to subdataset"
```

No warning message or errors are displayed for the last command and the file remains untracked.

### DataLad information

datalad version 0.18.3

Portions of `datalad wtf`:
## git-annex
  - version: 10.20230329
## python 
  - implementation: CPython
  - version: 3.10.8
## system 
  - distribution: darwin/22.3.0 13.2.1/arm64
  - name: Darwin
  - release: 22.3.0
  - type: posix
  - version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103

### Additional context

Running the same steps but using datalad run instead works as expected
```
datalad create /tmp/test_sub_run
cd /tmp/test_sub_run
datalad create -d . sub1
cd sub1
datalad run -d^ -m "creating file" -o file.bin "head -c 1000 /dev/urandom > {outputs}"
```

**Comment by yarikoptic** [comment]
`-d^` doesn't assume `-r` since `-d^` might as well be this very superdataset.  So, to save within subdatasets, add `-r`.  I am 99% confident that it is the source of the issue here so will close, but feel welcome to follow up and reopen.
