### ISSUE TITLE
How to deal with configuration?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#737]
Assuming the following is true:

- we need a configuration storage/retrieval system
- we want to stay syntax compatible with Git's own, to...
- ...be able to stack configuration from system, to user, to dataset

we have a problem.

GitPython's config parser is incapable of producing the same behavior as git-config. The issue is multi-value options:

````
[some]
    mess = one
    mess = two
````

will always yield `mess = two`, i.e. the first values is ignored. `git-config` on the other hand provides `--get-all` which returns both settings. There does not seem to be an equivalent for that in GitPython's implementation.

Moreover, it seems there cannot be one, as GitPython bases its parser on Python's RawConfigParser, which seems to plainly overwrite the first value with the latter.

Two options:

- extend GitPython's parser (which is a monster)
- wrap `git-config`
- write a parser from scratch

All three options look like a waste of time. But I am leaning towards wrapping `git-config`. Reading the full config is a single call (`git config -l`), plus some line parsing. Writing config is either a git-config call per setting (need to check, if multiple at the same time are possible), or we simply write a syntax compatible file ourselves.

@yarikoptic @bpoldrack Your input is appreciated!

**Comment by yarikoptic** [comment]
I would at least file a bug report with gitpython folks, may be they would get excited to get it addressed. If not, indeed wrapping the call would be the least effort solution probably, unless we discover some show stopper along the way

We still have an alternative to stay with python config...

**Comment by bpoldrack** [comment]
I agree. But let's build the wrapper in a way, that behaves like such a `ConfigParser`. So we can easily change implementation later (switching back to a fixed gitpython ConfigParser or building our own, or whatever else ...)

**Comment by hanke** [comment]
Yes, I will add one more and make it behave:

1. totally different
2. somewhat like ConfigParser 
3. somewhat like GitPythonConfigParser

**Comment by hanke** [comment]
See #744 (but better do a bit later)

**Comment by hanke** [comment]
There is now a complete implementation with amazing tests in #744

**Comment by mih** [comment]
#744 was merged.
