### ISSUE TITLE
Searching function in Developer Docs hangs

### ISSUE THREAD

**Issue by candleindark** [datalad/datalad#7374]
### What is the problem?

The searching function in [Developer Docs](http://docs.datalad.org/en/stable/) hangs whenever one tries to do a search.

### What steps will reproduce the problem?

Do a search of any term at https://docs.datalad.org/en/stable/.

### Have you had any success using DataLad before?

Yes, definitely.

**Comment by adswa** [comment]
Might be related this this: https://github.com/readthedocs/readthedocs.org/issues/10263

**Comment by mslw** [comment]
Oki, I was wrong - we already declare an up-to-date dependency on Sphinx and sphinx-rtd-theme, and this is a bug in the latter, where jQuery is not loaded automatically (F12 when viewing docs shows an error, "jQuery is not defined").

The readthedocs issue you mentioned links to a workaround, i.e., adding this to the docs conf file:
``` python
extensions = [
    "sphinxcontrib.jquery",
]
```

I will add a PR with the change. Looking at the theme's issue tracker, it seems that a fix might be done in their next release (1.3.0), so we could also probably wait it out.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.4`](https://github.com/datalad/datalad/releases/tag/0.18.4)
