### ISSUE TITLE
boost DATALAD_INSTALLER_VERSION on appveyor!

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#7380]
we have been experiencing a broken .deb installation https://github.com/datalad/datalad-installer/issues/154 and recently added even a check for content-size header but "nothing helped". Looking at the recent run https://ci.appveyor.com/project/mih/datalad/builds/46925948/job/o17iv83h4laedpk6 logs with magnifying glass I saw

```
python -m pip install datalad-installer${DATALAD_INSTALLER_VERSION:-}
Collecting datalad-installer==0.2.0
  Using cached datalad_installer-0.2.0-py3-none-any.whl (19 kB)
Installing collected packages: datalad-installer
Successfully installed datalad-installer-0.2.0
```
so we are installing a fixed very old version of it!!! Currently we have 0.11.2 !  I guess it is some env var defined at appveyor level since I dont see it in codebase. Please adjust or remove it (AFAIK installer is quite stable, and we just keep getting downloads more robust etc) @mih

**Comment by adswa** [comment]
I found the environment variable:
![image](https://user-images.githubusercontent.com/29738718/235590315-462ef233-8399-49e8-b1a5-8223db1e614d.png)


I removed it.
