### ISSUE TITLE
Ought-to behavior of special remote implementations to enable progress logging

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7382]
Prompted by https://github.com/datalad/datalad-next/issues/328

There is no information (that I am aware of) that describes what a special remote implementation is supposed to do in order to enable proper progress reporting. In the linked case, progress logging is done as described in http://docs.datalad.org/en/stable/design/progress_reporting.html but does not translate to progress logging via `datalad get`.

The Python process running the datalad special remote likely needs to *not* render a tqdm progress bar, but output git-annex special remote protocol `PROGRESS Int` message for git-annex to receive and communicate back to the parent (datalad) process.

The necessary steps to make this happen are *not* performed by `datalad.customremotes.main`.

What is missing? And should `datalad.customremotes.main` be adjusted to establish the necessary conditions?

It seems that in order to have datalad send progress reports to git-annex:

- `AnnexSpecialRemoteProgressBar` must be used, and be initialized with the instance of the special remote class in action (via an undocumented `remote` constructor argument
- the registered remote instance must support `send_progress()`
- `send_progress()` is defined in `SpecialRemote`, which is the base class of (all?) remotes, incl. the ones from `datalad-next`
- `send_progress` simply calls `self.annex.progress(progress)`, but provides insightful comments:

        # This method is called by AnnexSpecialRemoteProgressBar through an
        # obscure process that involves multiple layers of abstractions for
        # UIs, providers, downloaders, progressbars, which is only happening
        # within the environment of a running special remote process though
        # a combination of circumstances.
        #
        # The main purpose of this method is to have a place to leave this
        # comment within the code base of the special remotes, in order to
        # aid future souls having to sort this out.
        # (and to avoid having complex code make direct calls to internals
        # of this class, making things even more complex)

- `AnnexSpecialRemoteProgressBar` is registered in the `progressbars` dict (registry?) under the name `annex-remote`
- this class is retrieved and instantiated in `UnderAnnexUI.get_progressbar()`
- `UnderAnnexUI` is in `KNOWN_BACKENDS` under the (not easily searchable) name `annex`, which can only be enabled via the `set_backend()` method and this explicit label
- the associated enabling seems to be done in `datalad.customremotes.main` -- which contradicts the finding above that this function is not successfully establishing all needed conditions

Speculations:

- the return value of `ui.get_progressbar()` in `ProgressHandler.emit()` should be an instance of `AnnexSpecialRemoteProgressBar`
- if that is true, its `update()` should be called, which should call `send_progress(), if `remote` is set
- `remote` is set when `UnderAnnexUI` is initialized with `specialremote=`
- but `UnderAnnexUI` is not created directly, only indirectly via `set_backend('annex')` in the annexremote supermain function.

I am not sure where the `UnderAnnexUI` is supposed to learn about the special remote instance.

That all being said, the `ProgressHandler` that is taking care of any progress logs, it set up in `LoggerHelper.get_initialized_logger()`, and only when `is_interactive()` evaluated to true. The behavior of this helper is to be changed in https://github.com/datalad/datalad/pull/7344

In my test case of a plain `git annex get`, `is_interactive()` is not true, hence the ProgressHandler is never set up. Hence there could not be git-annex progress reporting from progress log messages.

**Comment by yarikoptic** [comment]
ref: https://github.com/datalad/datalad/issues/7373

**Comment by yarikoptic** [comment]
FWIW, with #7388 patch I see

```
❯ DATALAD_LOG_TRACEBACK=100 DATALAD_LOG_LEVEL=debug git annex addurl --debug --json --json-progress https://dandiarchive.s3.amazonaws.com/blobs/082/8f8/0828f847-62e9-443f-8241-3960985ddab3 2>&1 | grep -e UI -e progress -e CLAIM
[DEBUG] git-annex-remote-uncurl:8>uncurl:526>main:68>ui.__init__:86  UI set to UnderAnnexUI(out=<TextIOWrapper>, specialremote=None) 
[DEBUG] git-annex-remote-uncurl:8>uncurl:526>main:78,53>uncurl:233>customremotes.__init__:60>dialog:349  Setting specialremote of UI UnderAnnexUI(out=<TextIOWrapper>, specialremote=None) to <datalad_next.annexremotes.uncurl.UncurlRemote object at 0x7f59f5528e10> 
[2023-05-02 10:40:00.137660362] (Annex.ExternalAddonProcess) /home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin/git-annex-remote-uncurl[1] --> GETUUID
[2023-05-02 10:40:00.141842442] (Annex.ExternalAddonProcess) /home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin/git-annex-remote-uncurl[1] <-- CLAIMURL https://dandiarchive.s3.amazonaws.com/blobs/082/8f8/0828f847-62e9-443f-8241-3960985ddab3
[2023-05-02 10:40:00.141922898] (Annex.ExternalAddonProcess) /home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin/git-annex-remote-uncurl[1] --> CLAIMURL-SUCCESS
```

and indeed no progress reports by uncurl despite all needed prior initialization AFAIK being done, and similar initialization is done in datalad remote as shown in #7383 .

**Comment by mih** [comment]
https://github.com/datalad/datalad-next/pull/329 provides an implementation that attaches any use of `log_progress()` directly to a special remote's `send_progress()` method. It bypasses any `datalad.ui` abstractions, hence is not concerned with the complexity outlined above. Its limitations are detailed in the docs and a test is included.

With such an approach the "Ought-to behavior of special remote implementations to enable progress logging" is:

- derive from `SpecialRemote`
- use `datalad.customremote.main.main()` as process entry point
- rely on `log_progress()` as detailed in http://docs.datalad.org/en/stable/design/progress_reporting.html#reporting-progress-with-log-progress either directly in special remote implementations, or indirectly by IO helpers using `log_progress()` by themselves.
