### ISSUE TITLE
Raise GIT_MIN_VERSION to 2.25?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7389]
Presently the minimum Git version is set to `2.19.1`. Raising it to 2.25 would allow for removing the kludges that need to workaround `ls-file -o` breakage in 2.24 (traversing into submodules and reporting content under `.git/`)

The current minimum 2.19. already excludes really old versions, such as the 1.8 branch still used in things like ScientificLinux 7.

Looking at the various systems and package managers, I see this:

- Fedora (36): 2.40.1
- Fink: 2.34.0-1
- NetBSD: 2.40.1
- Slackware: 2.40.1
- Ubuntu (focal, 20.04): 2.25.1
- Debian (buster/oldstable): 2.20.1
- Debian (bullseye/stable): 2.30.2

Within a few weeks Debian bullseye will become `oldstable`.

It seems Ubuntu focal (the base image for appveyor) is presently the oldest environment of concern. It supports 2.25.

**Comment by mih** [comment]
Discussed in dev-call: No objections have been expressed for a raise to Git v2.25.

It should be done in `master`, and it should involve removing the kludges. The idea was that `master` could be released "any time".

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`1.0.0`](https://github.com/datalad/datalad/releases/tag/1.0.0)
