### ISSUE TITLE
Investigate/use sphinx-autodoc-typehints 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#7404]
Relates to #6884 .
From https://github.com/numpy/numpydoc/issues/196 it follows that https://pypi.org/project/sphinx-autodoc-typehints/ might be the one to provide type annotations into documentation from type hints so we can avoid duplicating them in docstrings, which are of numpy style in our code base.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.18.5`](https://github.com/datalad/datalad/releases/tag/0.18.5)
