### ISSUE TITLE
Fix `hierarchy` layout in `create-sibling-gitlab`

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad#7409]
### Summary

This problem has been around and known about for a long time. See relevant issues and discussion:

- https://github.com/datalad/datalad/issues/5242
- https://github.com/datalad/datalad/issues/3467
- https://github.com/datalad/datalad/pull/3447#pullrequestreview-241875329

What it comes down to is that there seems to be a discrepancy between the implementation in the code of `create-sibling-gitlab` and what the docs describe for the `hierarchy` layout.

### Problem description

These are the docs for the layouts:

> **“hierarchy”**
> Each dataset is placed into its own group, and the actual GitLab project for a dataset is put in a project named “_repo_” inside this group. Using this layout, arbitrarily deep hierarchies of nested datasets can be represented, while the hierarchical structure is reflected in the project path. This is the default layout, if no project path is specified.
> **“flat”**
> All datasets are placed in the same group. The name of a project is its relative path within the root dataset, with all path separator characters replaced by ‘–‘.
> **“collection”**
> This is a hybrid layout, where the root dataset is placed in a “_repo_” project inside a group, and all nested subdatasets are represented inside the group using a “flat” layout.

The docs say that "Each dataset is placed into its own group, and the actual GitLab project for a dataset is put in a project named `_repo_` inside this group", but this is not how the top-level dataset is handled in the code, which is created as a gitlab project. 

For a subdataset, the process should be to create a gitlab subgroup in (inside the parent aka superdataset group) with the name of the subdataset, while the subdataset itself goes into the _repo_ project inside the subgroup. An example of such a url:
`gitlab.com/maingroup/superdataset/subdataset/_repo_`.

Currently, this recursive process fails because the program logic does not create the subgroup `subdataset` before attempting to create the `_repo_` project.

Another point to note is that one cannot create top-level groups via the latest Gitlab API. A suggestion is to tell users to create a top-level group themselves, and then pass that top-level group as the base part of the path provided in the `--project` argument to the `create-sibling-gitlab` call.

### Example

A demo of what a working process would look like:

1. User creates top-level `mydatalad` group on their gitlab acount
2. User sets project argument via config:
```
> datalad configuration set datalad.gitlab-mygitlab-project=mydatalad/midterm_hierarchy
set_configuration(ok): . [datalad.gitlab-mygitlab-project=mydatalad/midterm_hierarchy]
```
3. User created sibling recursively:
```
> datalad create-sibling-gitlab -d . -r -s gitlab-hier --layout hierarchy
create_sibling_gitlab(ok): . (dataset) [sibling repository 'gitlab-hier' created at https://gitlab.com/mydatalad/midterm_hierarchy/repo]
configure-sibling(ok): . (sibling)
create_sibling_gitlab(ok): input (dataset) [sibling repository 'gitlab-hier' created at https://gitlab.com/mydatalad/midterm_hierarchy/input/repo]
configure-sibling(ok): . (sibling)
action summary:
  configure-sibling (ok: 2)
  create_sibling_gitlab (ok: 2)
```
4. User pushes sibling:
```
> datalad push -r --to gitlab-hier
publish(ok): input (dataset) [refs/heads/master->gitlab-hier:refs/heads/master [new branch]]
publish(ok): input (dataset) [refs/heads/git-annex->gitlab-hier:refs/heads/git-annex [new branch]]
publish(ok): . (dataset) [refs/heads/master->gitlab-hier:refs/heads/master [new branch]]
publish(ok): . (dataset) [refs/heads/git-annex->gitlab-hier:refs/heads/git-annex [new branch]]
action summary:
  publish (ok: 4)
```
5. Demo: https://gitlab.com/mydatalad/midterm_hierarchy

### TODO

- Fix discrepancy between docs and code
- Update tests
- Test for recursion level larger than 2

**Comment by jsheunis** [comment]
The following diff allows the above example to work (long with changing `_repo_` and `--` as temporary fixes for the special character issue):

```diff
diff --git a/datalad/distributed/create_sibling_gitlab.py b/datalad/distributed/create_sibling_gitlab.py
index 2c8e7db18..6504627ac 100644
--- a/datalad/distributed/create_sibling_gitlab.py
+++ b/datalad/distributed/create_sibling_gitlab.py
@@ -401,7 +401,7 @@ def _proc_dataset(refds, ds, site, project, remotename, layout, existing,
         # look for a specific config in the dataset
         project = ds.config.get(project_var, None)

-    if project and process_root and layout == 'collection':
+    if project and process_root and layout != 'flat':
         # the root of a collection
         project = '{}/repo'.format(project)
     elif project is None and not process_root:
```

**Comment by adswa** [comment]
done and released in https://github.com/datalad/datalad/pull/7410
