### ISSUE TITLE
Q: can we avoid needing 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#7419]
In https://github.com/datalad/datalad/commit/ddffd174b6fff7bc10b02f46f4062cffe00f878c#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R38 we had gone

from

        'typing_extensions>=3.10.0.0; python_version < "3.10"',

to

        'typing_extensions>=4.0.0; python_version < "3.11"',

for what feature?  I wonder if we could stick to 3.10... would simplify building of packages for older debian releases

**Comment by jwodder** [comment]
@yarikoptic It's for the `Self` symbol.

**Comment by jwodder** [comment]
@yarikoptic I can see two ways to deal with this:

1. (recommended) Don't depend on newer `typing_extensions` versions at runtime, but do make use of them when type-checking (as `typing_extensions` is a dependency of mypy and thus available when type-checking).  We can do this by changing the import of `Self` in `datalad/typing.py` to:

    ```python
    from typing import TYPE_CHECKING

    if TYPE_CHECKING:
        from typing_extensions import Self
    ```

    We will then be able to revert the `typing_extensions` requirement change, and datalad will work at runtime in pre-3.11 Pythons as long as the relevant files have `from __future__ import annotations` at the top.

    However, in files that use `Self`, we would also have to either change the `from datalad.typing import ...` line to `from datalad.typing import *` (which I don't think mypy will like) or else move the above snippet from `datalad/typing.py` to each & every file that uses `Self`.

2. Do things how they used to be done before `Self` was introduced: For each class `Klass` with a method that returns `Self`, define a `TypeVar` like this:

    ```python
    from typing import TypeVar

    KlassType = TypeVar("KlassType", bound="Klass")
    ```

    and then change this:

    ```python
    @classmethod
    def close(cls, ...) -> Self:
    ```

    to this:

    ```python
    @classmethod
    def close(cls: type[KlassType], ...) -> KlassType:
    ```
