### ISSUE TITLE
CommandError when creating initial gin sibling

### ISSUE THREAD

**Issue by asmacdo** [datalad/datalad#7426]
### What is the problem?

When adding a gin sibling, I get the following log and CommandError

```
[INFO   ] Could not enable annex remote gin. This is expected if gin is a pure Git remote, or happens if it is not accessible. 
CommandError: 'git -c diff.ignoreSubmodules=none cat-file blob git-annex:remote.log' failed with exitcode 128 under /home/austin/datasets/opfvta-singularity
fatal: path 'remote.log' does not exist in 'git-annex'
```

### What steps will reproduce the problem?

1. initialize an empty repo on gin
2. `datalad create -c text2git opfvta-singularity          `
3. `datalad siblings add -d . --name gin --url git@gin.g-node.org:/asmacdo/opfvta-singularity.git`

### DataLad information

datalad 0.15.6
fedora 36

### Additional context

This error turned out not to be a problem.  
`datalad push --to gin` worked as expected.

The only problem is that this `CommandError` should not be shown to the user, or at least the context (that this error will go away once you have pushed with datalad) should be explained more clearly. 

I'm not sure what would be best, but one idea is that the log message could be improved:

```
[INFO   ] Could not enable annex remote gin. This is expected if gin is an empty repository or a pure Git remote, or if the remote is not accessible. 
```

The info log is present in the datalad handbook, but the commanderror is not.  https://handbook.datalad.org/en/latest/basics/101-139-gin.html

**Comment by yarikoptic** [comment]
Note that your version of datalad is quite aged, someone would need to reproduce with more recent one first.

**Comment by adswa** [comment]
would also be good to know the git-annex version. I tried with today's master of datalad and git annex version 10.20221003 and couldn't reproduce this.

**Comment by asmacdo** [comment]
git-annex version: 8.20211231

I think we can assume this is fixed
