### ISSUE TITLE
datalad install <url>  without "-s" taught me wrong

### ISSUE THREAD

**Issue by asmacdo** [datalad/datalad#7441]
`datalad install https://github.com/datalad-datasets/longnow-podcasts.git` works, despite not being what the man page says.

Because of that, I learned (incorrectly) that url is a positional argument. Seeing that PATH was also a positional argument, I expected this to work.

`datalad install https://github.com/datalad-datasets/longnow-podcasts.git install/here`

IMNO (in my noob opinion) it **would** make sense to have a positional argument for url, and an optional positional url for path. 

I did eventually notice from the help page that i needed -s

`datalad install -s https://github.com/datalad-datasets/longnow-podcasts.git install/here`

**Comment by asmacdo** [comment]
[humorous anecdote] For months I've been doing `datalad install https://github.com/datalad-datasets/longnow-podcasts.git install/here` "Oh right, why didnt  that work? Ill figure it out later `mv longnow install/here/`

If its just me, no worries, but if others are thrown off maybe we should do something different.

**Comment by yarikoptic** [comment]
that is why there is `datalad clone` with a less ambigous, but less "powerful" IMHO interface. 

> `datalad install https://github.com/datalad-datasets/longnow-podcasts.git` works, despite not being what the man page says.

could you explain more -- what does the man page says that contradicts?  could you improve it ? it is built up from https://github.com/datalad/datalad/blob/maint/datalad/distribution/install.py#L64

**Comment by asmacdo** [comment]
The correct usage is mentioned later in the man page but in the syntax declaration there isn't an indication that SOURCE could be a positional argument. 

```
       datalad  install  [-h] [-s SOURCE] [-d DATASET] [-g] [-D DESCRIPTION] [-r] [-R LEVELS] [--reckless [auto|ephemeral|shared-...]]
              [-J NJOBS] [--branch BRANCH] [--version] [PATH ...]
```
I don't think we can make this helptext clearer, because afaik that syntax doesnt account for the special treatment we give PATH. Glancing at the code, it looks like what is happening is that if urls are passed positionally, they are received as paths and a handful of cases are handled to deal with them appropriately. (though, if that interpretation is correct my usecase of `datalad install <url> <path>` should have worked?) 

https://github.com/datalad/datalad/blob/maint/datalad/distribution/install.py#L226-L229

What I would expect would be that `[SOURCE ...]` would be positional and there would be a flag for location. IMHO "when in doubt use git(ish) syntax"

That said, what I have in mind to change here would be backwards incompatible and irritating to scripters. If it were up to me, I'd mark this as a 1.0 blocker but not worry about it until then.

**Comment by yarikoptic** [comment]
the UX problem is that good old `install` is an odd merge of desire of having smth like `apt-get install pkg1 pkg2 ...` (package manager - install multiple targets, might be also local subdataset paths) and `git clone URL [path]` (install a single one). https://github.com/datalad/datalad/issues/3759 might serve as an entry point to the wild land of discussions on interfaces which happened in the past. Overall @mih doesn't like `install` and doesn't use it much for this reason resorting to `clone` + `get` tandem. I do love "a single invocation of `install` does it all" aspect of it although indeed the original idea for flexibility of installing multiple URLs as you would do in distribution is probably not used often.
In a minute I will take my chance to submit a PR improving description there.

**Comment by adswa** [comment]
If I read the conversation in #7445 right, this issue is fixed. Please reopen if you disagree. :)
