### ISSUE TITLE
Split a dataset without touching hosted data

### ISSUE THREAD

**Issue by anikfal** [datalad/datalad#7451]
Following the workflow discussed in https://knowledge-base.psychoinformatics.de/kbi/0013/index.html:

**At the stage below, I faced error (the second "merge" seems to be a typo):**
`git -C target1 annex merge merge git-annex`
```
merge merge 
merge: merge - not something we can merge
failed
merge git-annex 
fatal: refusing to merge unrelated histories
failed
merge: 2 failed
```

**Error after modification (second "merge" has been removed):**
`git -C target1 annex merge git-annex`
```
merge git-annex 
fatal: refusing to merge unrelated histories
failed
merge: 1 failed
```

**Comment by adswa** [comment]
Hey, thank you! There is indeed a line break missing in the write up. it should say:

```
$ git -C target1 annex merge 
merge git-annex
[...]
```

Ie the command is only the first part, the other is output. I'll fix this quickly. Can you try rerunning the correct command? (i.e., nothing else after ``merge``)

**Comment by adswa** [comment]
markup fixed in https://github.com/psychoinformatics-de/knowledge-base/commit/526d0d97af600e8b325c07a573c5731aa2d28836 (browser might need a hard refresh to display it)

**Comment by adswa** [comment]
I'll close this issue for now given that the typo is fixed. But if there merge problem remains, please reopen it, or start a new one. Thanks!

**Comment by anikfal** [comment]
That was okay for the test data. Thanks.

My concern was to move any data in the superdataset into a subdataset. For my case, I have `datasource` (era5 data) in my superdataset. After creating a target subdataset and following the workflow, `datasource` (era5) still will be in the superdataset. So my superdataset cannot get rid of this `datasource`, because it will be the source of the target subdataset.

It seems the lengthy delay in datalad is due to the huge data (era5 > 100T) stored directly in the superdataset.

**Comment by adswa** [comment]
> Does it mean that after creating target subdataset, I must datalad get the contents, and afterwards, I remove the datasource?

Yes. Because it is so much data, I would do it in chunks. e.g., get all data from 1970 in to your new dataset. Declare the original source dead (git annex dead <UUID>). Drop the data from era5.

**Comment by anikfal** [comment]
Yeah that's okay. Thank you. However, today between 17:00 to 19:30 I will participate in a class. So maybe tomorrow if you're available.
