### ISSUE TITLE
[wishlist] save-state and "undo"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#748]
which would record the current state of the repositories (before running the command) and then be able to rewind back

**Comment by mih** [comment]
Idea: have a general flag that makes datalad store the state of all local branches before performing an operation. To be able to undo to that particular state.

**Comment by yarikoptic** [comment]
could be useful beyond "undo" - e.g. comparing fully states difference between collections of repositories (e.g. from previous crawl). Since cheap to store those, I think it might be useful to record such states nearly for every "user initiated" command (crawl, upgrade) reusing the same identifier in case of recursive actions across datasets, but recording in each (e.g. under `.git/states/state-id.json`).  This way no need to pre-figureout which dataset command touches, and information would still be recoverable simply by reusing IDs

**Comment by bpoldrack** [comment]
Do we want to store the exact command call as well? What kind of ID do you think of? Do we store the entire local history?

**Comment by yarikoptic** [comment]
On Mon, 05 Sep 2016, Benjamin Poldrack wrote:

>    Do we want to store the exact command call as well? 

I guess we could but that might be trickier... the point is pretty much
to provide something like a git's reflog  but across collection of the 
repositories while marking all the branches, not just a current
checkout.  So later, in case of a mistake you could go back.  The only
special treatment might be needed for git-annex branch -- i.e. to not
roll that one back since some files might have been dropped.  that
branch has its own life somewhat

> What kind of ID do you think of? 

whatever -- e.g. based on date/time.

> Do we store the entire local history?

do you mean of states? sure -- why not.  It will be tiny in comparison
to anything really.

**Comment by mih** [comment]
Also see #1424

**Comment by mih** [comment]
I am closing this in favor of #1424 -- we do have the "save state" part now with `rev-save`
