### ISSUE TITLE
[wishlist] foreach command

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#749]
thin proxy around `git submodule foreach`   but with an option to not fail entirely if one submodule fails

Additional features which might be added
- [ ] option to "filter" datasets, e.g. `--filter dirty|modified|git|git-annex`.  Not sure yet on how/if bool logic between those should be implemented, and/or such filtering could be relatively easily implemented differently (piping in cli, looping over a subdatasets generator in python)

**Comment by mih** [comment]
Maybe this could be done as a plugin?

**Comment by yarikoptic** [comment]
FWIW, should be built on top of #5022 with options on datasets traversal (bottom up or top down) to define dependencies, and then otherwise be a thin wrapper around 

```python
        yield from ProducerConsumerProgressLog(
            subdatasets_gen,  # chain with current one depending on topdown
            action,
            # probably not needed
            # It is ok to start with subdatasets since top dataset already exists
            safe_to_consume=no_parentds_in_futures if topdown else no_subds_in_futures, # or vise versa
            jobs=jobs
       )
```

PS regular interface should it be, plugins - I see no point in them

**Comment by yarikoptic** [comment]
imho should neither be a plugin and not worth an extension, removed the label but cannot close it -- should be implemented! ;)
