### ISSUE TITLE
Design document on `ThreadedRunner` outdated

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7498]
https://docs.datalad.org/en/stable/design/threaded_runner.html

I did not go through the entire text, but it claims that we use `asyncio.protocols.SubprocessProtocol`, which is no longer the case (since datalad v0.17, 2022-07-07).

Ping @christian-monch

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`0.19.4`](https://github.com/datalad/datalad/releases/tag/0.19.4)
