### ISSUE TITLE
datalad push to multiple siblings simulataneously

### ISSUE THREAD

**Issue by hvgazula** [datalad/datalad#7533]
Currently the `--to` flag for `datalad push` takes only one sibling. Is the option/feature to specify multiple siblings desirable?

**Comment by adswa** [comment]
Hey! I don't think we've thought about this feature for the commandline yet. But there is the 'publish-depends' configuration (also exposed as the '--publish-depends' argument to many create-sibling-* commands) that effectively results in pushing to several siblings at once when it's configured. Would this be sufficient for your use case?

**Comment by yarikoptic** [comment]
FWIW, you can do it for an existing sibling (AKA remote) by simply adding to its config `datalad-publish-depends` option, 
 e.g. in my case I have `.git/config` which has:

```
[remote "origin"]
	url = git@github.com:ReproNim/containers
	fetch = +refs/heads/*:refs/remotes/origin/*
	annex-ignore = true
	datalad-publish-depends = datalad-public

[remote "datalad-public"]
...
```

which says that whenever I `datalad push` to origin, it would first `datalad push` to `datalad-public` remote.

As the `--to` option goes, ATM it is indeed can be specified only once and only with 1 remote name.  You would need just to call `datalad push` multiple times for each remote.

**Comment by hvgazula** [comment]
Thank @yarikoptic I know it has to be called multiple times for each remote hence the question of whether it is a 'desirable feature' to specify all remotes at once.

**Comment by yarikoptic** [comment]
ok, let me re-lable it happen someone decides to take on implementing it ;)
