### ISSUE TITLE
Is `datalad/support/due.py` license BSD-2 or BSD-3?

### ISSUE THREAD

**Issue by zimoun** [datalad/datalad#7535]
### What is the problem?

 + File [`COPYING`](https://github.com/datalad/datalad/blob/maint/COPYING#L43) mentions BSD-3 for the license of `datalad/support/due.py`.
 + File [`datalad/support/due.py`](https://github.com/datalad/datalad/blob/maint/datalad/support/due.py#L24) mentions BSD-2 for its license?

Which one is correct?

**Comment by yarikoptic** [comment]
thanks for asking! due.py comes from https://github.com/duecredit/duecredit/ and that one indeed is BSD-2, so let's fix COPYING here. I will push commit directly fixing that.
