### ISSUE TITLE
published datasets with spaces in the names are not shown in webview

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#754]
http://datasets.datalad.org/webtest/?dir=/indi/fcon1000/
is missing the `Cleveland CCF`  one, although it is physically present on falkor but does miss .git/datalad so I guess datalad ls -r is not doing job correctly

also looking at the hook -- it dumps from all of them into the same debug  file `&> /tmp/datalad-publish-metadata-refresh-$(date +%F).log%  `.  imho better dump to 
```
.git/datalad/logs/datalad-publish-hook-`--iso-8601=s`
```
so we could later inspect

**Comment by yarikoptic** [comment]
Add right @debanjum , this one is somewhat a pressing one needing troubleshooting.

**Comment by debanjum** [comment]
refer [webtest2](http://datasets.datalad.org/webtest2/) for sample test dataset with space
