### ISSUE TITLE
"Convert" .travis.yml into a github workflow

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#7574]
We stopped paying for Travis (grant funds are over) and thus we stopped testing there.  But it was the only one doing a more thorough sweep over various setups and python versions.  We need a replacement github action one the main aspects of which would be a sweep over all supported python versions + running a number of those tricky setups (minimal git-annex version, etc).

the motivator: https://github.com/datalad/datalad/issues/5597#issuecomment-2032099158 which promises those tests to not run correctly on py 3.12 because of our dependency on boto.

**Comment by yarikoptic-gitmate** [comment]
Issue fixed in [`1.0.3`](https://github.com/datalad/datalad/releases/tag/1.0.3)
