### ISSUE TITLE
datalad.wtf() and facility for tracking versions of external tools so code could workaround/warn accordingly

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#76]
In PyMVPA we have this handy function which reports various information about code and externals, which helps to troubleshoot.  It might be nice to adopt similar one here, but ideally probably  through generalization of mvpa2.wtf (and externals etc) functionality in a separate project...  Currently projects need to brew similar but different functionality for the same purpose.  pandas and stats models has some already as well.

**Comment by yarikoptic** [comment]
we should catch those cases like (x<= externals['curl'] < y and externals['git-annex'] <  "5.20150327" and on_osx) -> "you might have problems accessing empty files", (see #79)

**Comment by mih** [comment]
`wtf` could be a plugin

**Comment by mih** [comment]
There is now a minimal `wtf` plugin in master that could be enhanced to do all this.

**Comment by mih** [comment]
`wtf` plugin now reports externals versions.
