### ISSUE TITLE
support authentication via social nets (with oauth or not) via psa

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#761]
just saw that kaggle allows Yahoo or G+ authentication and then remembered that I had left a comment in the code about http://psa.matiasaguirre.net/ with provides such a service.  all easy integration though is for frameworks (flask etc) so not yet sure how easy it would be to plug into plain requests/our credentials/authentication

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
