### ISSUE TITLE
[wishlist] use `git describe` as version provider for the dataset (I guess during aggregation)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#763]
some datasets are more or less nicely versioned by "upstream", e.g.

``` shell
$> datalad ls ds*
ds000001  [annex]  master  2.0.0+4 2016-09-03/20:02:21  OK
ds000002  [annex]  master  1.0.0-3-g0a9f3b6 2016-09-03/20:03:21  OK
ds000003  [annex]  master  1.1.0+4 2016-09-03/20:03:37  OK
ds000005  [annex]  master  2.0.0+3 2016-09-03/20:03:57  OK
ds000006  [annex]  master  2.0.0+2 2016-09-03/20:09:44  OK
ds000007  [annex]  master  2.0.0+3 2016-09-03/20:10:44  OK
ds000008  [annex]  master  2.0.0+2 2016-09-03/20:11:08  OK
ds000009  [annex]  master  2.0.1+1 2016-09-03/20:12:31  OK
```

that version description comes from git repository itself and `+revision` depicts "crawled" revision (I am still tuning things up).  So it would be nice if for such datasets I could state to use `git describe` output for the version

**Comment by mih** [comment]
Just to be sure: Something from git-describe should end up in the aggregated meta data, correct? Just a plain `git describe` call, or maybe we should have a first config option that informs us what parameters are to be used?

**Comment by yarikoptic** [comment]
On September 8, 2016 7:04:10 AM EDT, Michael Hanke <notifications@github.com> wrote:
>Just to be sure: Something from git-describe should end up in the
>aggregated meta data, correct? Just a plain `git describe` call, or
>maybe we should have a first config option that informs us what
>parameters are to be used?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/763#issuecomment-245564530

I think more than that - I would like not to go and edit every dataset meta to specify new version every time it updates - that is done atm via standard git tags mechanism. So I would like to indicate that for specific dataset to use output of git describe as a version. I could of cause adjust crawler to duplicate that information in the tag and in meta, but I don't like duplication

**Comment by yarikoptic** [comment]
@mih may be a compromise could be the output of e.g.
```shell
> git describe --match '[v0-9][0-9.]*' --always --long
2.0.1-0-g7ec9ffd
```
so yes -- we would enforce some kind of semantic versioning, and if none tag existed:
```shell
> git describe --match '[v0-9][0-9.]*' --always --long
abc7de6
```
it should become 
```shell
> echo "0.0.0-`git log --first-parent --pretty=oneline | wc -l`-g`git describe --match '[v0-9][0-9.]*' --always --long`"
0.0.0-29-gabc7de6
```
thus we would have something depicting order (unlike pure treeish),possibly reflecting upstream's version which we "capture" via git tag (after all, all datasets are at least git repositories), but also always with treeish identifier so happen some tag mutates, we could identify the commit.
Sure thing we could also store full treeish in some other field (e.g. `commit` ;-) ), but version itself must be something "sortable" to a human eye imho.  FWIW, above form seems also to be digested ok by LooseVersion:
```
$> python -c 'from distutils.version import LooseVersion as LV, StrictVersion as SV; print LV("0.0.0-2-gabcasdf") >= "0.0.0-3-asdf"' 
False

$> python -c 'from distutils.version import LooseVersion as LV, StrictVersion as SV; print LV("0.0.0-29-gabcasdf") >= "0.0.0-3-asdf"'
True
```
collisions (the same # of commits since tag but different state) might happen, but unlikely, and we would be able to catch those and warn if it happens.

Another (ain't I want to please? ;) ) could be a meld of upstream/semantic and our lovely "date based", e.g.  `2.0.1-0-20160909-g7ec9ffd` thus providing immediate feedback on ordering, age, and also uniquely identifying the commit (and still being digestable by git commands directly which react to `-g???????`.  But yeah -- this one is way too long and we have dedicated field for 'modified' anyways.

**Comment by yarikoptic** [comment]
@mih -- your feedback would be appreciated

**Comment by yarikoptic** [comment]
actually I am getting inclined to not assign any version unless there is a describe based on tag (or from somewhere else), and make a dedicated 'commit' for the 'commit'

**Comment by mih** [comment]
Yes, sounds good: no version without a tag, commit stored in commit. Something like `2.0.1-0-g7ec9ffd` looks good to me.

**Comment by yarikoptic** [comment]
I guess it is for me to work on @mih?

**Comment by yarikoptic** [comment]
In current (codename `meta6` but version indicator `v1`)  version of metadata, the version of the dataset is stored within aggregate_v1.json 
```
$> grep -A20 ds000001 aggregate_v1.json 
"openfmri/ds000001":
{
"content_info":
"objects/87/cn-1d35795a1ba0410f271672d1f11d7c.xz",
"datalad_version":
"0.9.1.dev1",
"dataset_info":
"objects/87/ds-1d35795a1ba0410f271672d1f11d7c",
"extractors":
[
"datalad_core",
"nifti1",
"xmp",
"bids"
],
"id":
"233cc486-7d0e-11e6-855b-002590f97d84",
"refcommit":
"ea98f90157459b3e70a7d7768ce1a0a6bf767746"
},
```
but still lacks comparable version.  Do you think @mih it would be the right place to add it?  what name (`refdescribe`?)

**Comment by mih** [comment]
we should add this info, but not there. I will push some local changes I have here that introduce a better place, i think

**Comment by yarikoptic** [comment]
but I do not see any other place where it could be added really, since ds-* shouldn't be the one changing with every aggregation if metadata doesn't change.  Where do you see it ?

**Comment by mih** [comment]
Ah, check the diff of aggregate.py in that PR. I record the commit hash of the state of the dataset that we are describing. That commit hash will not change, if we only change aggregated info. You could simply describe this hash and get the same stability.

**Comment by yarikoptic** [comment]
yes, it is that hash which should be described, probably right when hash is obtained

**Comment by mih** [comment]
Was done with #2289
