### ISSUE TITLE
[Brew python3.11] Argcomplete dependency

### ISSUE THREAD

**Issue by Servinjesus1** [datalad/datalad#7634]
### What is the problem?

Installing datalad from `brew` fails to install dependency `argcomplete` for `datalad shell-completion`. Because 1.1.1 depends on python 3.11, `argcomplete` must be installed manually to that version via `python3.11 -m pip install argcomplete`

I cannot tell if this is a rather specific case where Mac users need to specifically patch this, or if the `brew` recipe can be updated to automatically do this. In any case, if you do `datalad shell-completion` and get the error about `argcomplete`, you can fix this as above. Do keep in mind which version of python3.11 `datalad` is referencing - in my case I had MacPorts 3.11 (from `xcode`) and brew 3.11 installed (with ports taking preference) making this a convoluted issue to track down...

### DataLad information

v1.1.1 on Mac OS Sonoma 14.5
- had installed `xcode-select --install`
- using `brew` and inadvertantly MacPorts for package management
- using `conda` for python day-to-day

### Have you had any success using DataLad before?

I consider myself a git wizard (colloquially a git). Otherwise a relatively new datalad.

**Comment by Servinjesus1** [comment]
*Brewers on the datalad team, feel free to close this if the brew recipe cannot be updated to do this automatically.*

**Comment by yarikoptic** [comment]
we do not have any brewers on the team, we have conda-forgers, pypids, and debianoids only AFAIK, and some gentooids and GUIXoids are in reach ;-)   may be should be filed against https://github.com/Homebrew/homebrew-core/blob/3e21ecab15d73cb6d55870c0d6cd3f4ffd64070f/Formula/d/datalad.rb or somewhere in that land?  as indeed nothing for us to accomplish in this repo, I will just close
