### ISSUE TITLE
wsl2 subsystem (ubuntu 22.04.3 LTS) can not accurately  datasets with the latest git-annex and datalad

### ISSUE THREAD

**Issue by Zhangzhixiang-laugh** [datalad/datalad#7635]
## First, I created a new python virtual environment and installed the latest git-annex and datalad:
     apt-get install git-annex
     pip install datalad
## Then, I tried to get and parse the target datasets:
    (data_lad) jack@DESKTOP-OU205K5:~$ datalad install -g -J 18 https://datasets.datalad.org/labs/hasson/narratives/derivatives/afni-nosmooth
    [INFO   ] scanning for unlocked files (this may take some time)
    install(ok): /home/jack/afni-nosmooth (dataset)
    (data_lad) jack@DESKTOP-OU205K5:~/afni-nosmooth$ datalad get -r sub-001
    [INFO   ] Ensuring presence of Dataset(/home/jack/afni-nosmooth) to get /home/jack/afni-nosmooth/sub-001
    get(ok): sub-001/func/sub-001_task-pieman_run-1_desc-fwhm_smoothness.tsv (file) [from fcp-indi...]
    get(ok): sub-001/func/sub-001_task-pieman_run-1_desc-model_regressors.1D (file) [from fcp-indi...]
    get(ok): sub-001/func/sub-001_task-pieman_run-1_desc-model_regressors.csv (file) [from fcp-indi...]
    get(ok): sub-001/func/sub-001_task-pieman_run-1_space-MNI152NLin2009cAsym_res-native_desc-clean_bold.nii.gz (file) [from fcp-indi...]
   get(ok): sub-001/func/sub-001_task-pieman_run-1_space-fsaverage6_hemi-L_desc-clean.func.gii (file) [from fcp-indi...]
   get(ok): sub-001/func/sub-001_task-pieman_run-1_space-fsaverage6_hemi-L_desc-tsnr.func.gii (file) [from fcp-indi...]
   get(ok): sub-001/func/sub-001_task-pieman_run-1_space-fsaverage6_hemi-L_roi-EAC_desc-clean_timeseries.1D (file) [from fcp-indi...]
   get(ok): sub-001/func/sub-001_task-pieman_run-1_space-fsaverage6_hemi-L_roi-EAC_desc-mean_timeseries.1D (file) [from fcp-indi...]
  get(ok): sub-001/func/sub-001_task-pieman_run-1_space-fsaverage6_hemi-R_desc-clean.func.gii (file) [from fcp-indi...]
  get(ok): sub-001/func/sub-001_task-pieman_run-1_space-fsaverage6_hemi-R_desc-tsnr.func.gii (file) [from fcp-indi...]
  [26 similar messages have been suppressed; disable with datalad.ui.suppress-similar-results=off]
  get(ok): sub-001 (directory)
action summary:
  get (ok: 37)
 ## Finally, I checked the disk space for the subsets:
    (data_lad) jack@DESKTOP-OU205K5:~/afni-nosmooth/sub-001/func$ ls
   sub-001_task-pieman_run-1_desc-fwhm_smoothness.tsv                                     sub-001_task-pieman_run-2_space- 
   fsaverage6_hemi-L_roi-EAC_desc-clean_timeseries.1D
   sub-001_task-pieman_run-1_desc-model_regressors.1D                                     sub-001_task-pieman_run-2_space- 
   fsaverage6_hemi-L_roi-EAC_desc-mean_timeseries.1D
   sub-001_task-pieman_run-1_desc-model_regressors.csv                                    sub-001_task-pieman_run-2_space- 
   fsaverage6_hemi-R_desc-clean.func.gii
   sub-001_task-pieman_run-1_space-MNI152NLin2009cAsym_res-native_desc-clean_bold.nii.gz  sub-001_task-pieman_run- 
   2_space-fsaverage6_hemi-R_desc-tsnr.func.gii
   sub-001_task-pieman_run-1_space-fsaverage6_hemi-L_desc-clean.func.gii                  sub-001_task-pieman_run-2_space- 
   fsaverage6_hemi-R_roi-EAC_desc-clean_timeseries.1D
   sub-001_task-pieman_run-1_space-fsaverage6_hemi-L_desc-tsnr.func.gii                   sub-001_task-pieman_run-2_space- 
  fsaverage6_hemi-R_roi-EAC_desc-mean_timeseries.1D
  sub-001_task-pieman_run-1_space-fsaverage6_hemi-L_roi-EAC_desc-clean_timeseries.1D     sub-001_task-tunnel_desc- 
  fwhm_smoothness.tsv
  sub-001_task-pieman_run-1_space-fsaverage6_hemi-L_roi-EAC_desc-mean_timeseries.1D      sub-001_task-tunnel_desc- 
  model_regressors.1D
  sub-001_task-pieman_run-1_space-fsaverage6_hemi-R_desc-clean.func.gii                  sub-001_task-tunnel_desc- 
  model_regressors.csv
  sub-001_task-pieman_run-1_space-fsaverage6_hemi-R_desc-tsnr.func.gii                   sub-001_task-tunnel_space- 
   MNI152NLin2009cAsym_res-native_desc-clean_bold.nii.gz                                   ...
 (data_lad) jack@DESKTOP-OU205K5:~/afni-nosmooth/sub-001/func$ du -h
   148K    .
 ## The probem is that the target datsets were not being loaded properly with the correct space size！！！
![image](https://github.com/user-attachments/assets/8d4a679c-c0ea-4f07-a63b-55649a2f6b81)
![image](https://github.com/user-attachments/assets/5a6fb7f2-d632-40d6-9122-36b598eb06a7)
![image](https://github.com/user-attachments/assets/0e5dbe82-b4df-4137-9483-100bd412ff25)

### 1. create new file folder
mkdir afni
### 2. download the index files
cd afni
datalad install -g -J 18 https://datasets.datalad.org/labs/hasson/narratives/derivatives/afni-nosmooth
cd afni-nosmooth
### 3. download the target subsets
datalad get -r sub-001
### 4. check the the files
cd sub-001/func
ls
du -h

### DataLad information

datalad 1.1.1
ubuntu 22.04.3 LTS

**Comment by Zhangzhixiang-laugh** [comment]
The dowloaded files were maily in  \\wsl.localhost\Ubuntu-22.04\home\jack\afni-nosmooth\.git\annex\objects, not the target path.

**Comment by yarikoptic** [comment]
That is how git-annex works -- commits symlinks pointing to actual content under `.git/git-annex/objects`. 
So from above sounds like it all worked out correctly, which is great to hear given WLS, and thus I will close this issue!
I would recommend skimming through https://handbook.datalad.org/en/latest/basics/101-180-FAQ.html#how-can-i-copy-data-out-of-a-datalad-dataset and handbook in general to get a better sense of how things work in git-annex/datalad.

Note: When you use `du` -- add option `-L` to dereference symlinks, otherwise you count only space used by symlinks.
