### ISSUE TITLE
`save` implements confusing path handling

### ISSUE THREAD

**Issue by mih** [datalad/datalad#766]
Discovered when working on #752 that save treats incoming paths to save a relative, but not necessarily relative to the dataset to be saved. I think this is another vaguely (un)defined aspect of the API with respect to the treatment of value coming in from the cmdline -- pretty much like our difficulties with identifying datasets. I guess this should be fixed in one go.

**Comment by mih** [comment]
Somwhate related to #631

**Comment by yarikoptic** [comment]
also I think we should introduce logic as we discussed during Tue hangout on how to treat the non-abs paths:
```
if dataset:  # ie it is specified
   path is relative to the top of the dataset
  # since otherwise why would you specify dataset at all, and it would make it consistent with Python API
  # of ds.action(path_from_top_of_the_dataset) operation
  # consequence -- any ../ path normalized to outside of the dataset should be considered illegal
  # which also would be considered inline with #631 reasoning of analogy with git handling
else:
  path is relative to the current directory
```
and indeed that logic should be centralized.

**Comment by bpoldrack** [comment]
Yes, we discussed this in #598 . Just to reference it here.
