### ISSUE TITLE
annex special remotes must be explicitly enabled in new (updated) clones

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#77]
they don't get automagically enabled because they might require authentication setup etc

so they need to be explicitly enabled.  But some special remotes are quite dummy (e.g. torrent and our archives one) so there seems to be no need for explicit initialization.  It would be nice if special remotes got an option for automatic initialization

**Comment by yarikoptic** [comment]
@hanke and this auto mode availability handling probably would be desired before adding type=git special remote to the gump's annex, otherwise it wouldn't be automagically enabled (I think ;) )

**Comment by yarikoptic** [comment]
Hi @joeyh ,  Shouldn't it be relatively simple to provide some setting for special remotes to get them enabled on any new git-annex clone?  It should simplify things up considerably I think.

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> Hi @joeyh , Shouldn't it be relatively simple to provide some setting for
> special remotes to get them enabled on any new git-annex clone? It should
> simplify things up considerably I think.

Whether that would be possible to to at all depends on the configuration
of the special remote.

But, this would be a divergence from git, in which remotes have to be
set up manually, not automatically. I don't think it makes sense to have
git-annex init enable special remotes when git init doesn't enable git
remotes.

-- 
see shy jo

**Comment by yarikoptic** [comment]
@joeyh regarding "divergance from git" on auto-enabling of special remotes:  annex already different from git in this regard -- git repositories have no clue about available "other" remotes.  The only remote it knows, is the one from which it is cloned,  and it IS added automatically, and thus "enabled".  annex does ship information about remotes within git-annex branch, so unlike with git (so it is not really a "divergance" but an additional "battery" which git doesn't have), it is imho sensible to have per-remote configuration recorded within annex to either that remote should be enabled upon clone.  my 1c.

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> @joeyh regarding "divergance from git" on auto-enabling of special remotes:
> annex already different from git in this regard -- git repositories have no
> clue about available "other" remotes. The only remote it knows, is the one from
> which it is cloned, and it IS added automatically, and thus "enabled". annex
> does ship information about remotes within git-annex branch, so unlike with git
> (so it is not really a "divergance" but an additional "battery" which git
> doesn't have), it is imho sensible to have per-remote configuration recorded
> within annex to either that remote should be enabled upon clone. my 1c.

Currently, git and git-annex have similar workflows for creating a new
remote (git init followed by git remote add, git annex initremote), and
for enabling an existing remote (git remote add, git annex
enableremote). As far as the origin remote, both git and git-annex work
the same in that regard, but that's a special case.

So, making special remotes auto-enable would reduce similarity overall.
And, there are certianly lots of cases where you don't want to try to
enable all special remotes everywhere.

I do think there could be a use case for configuring a special remote
with autoenable=true and have git-annex init try to enable all such remotes.
I'd be willing to consider a todo about doing that.

-- 
see shy jo

**Comment by yarikoptic** [comment]
done : http://git-annex.branchable.com/todo/autoenable__61__true_for_special_remotes/ ;-)

**Comment by joeyh** [comment]
enableremote=true is now implemented in git-annex
