### ISSUE TITLE
Should `save auto_add_changes` default to True?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#776]
As we are moving to a paradigm where every datalad action (bundle) results in a commit, the only changes left are likely user-made modifications outside datalad command. It would make sense to me to set the default to `True`, because in all likelihood users want to save all those changes.

In order to keep the `files` parameter useful and functional. We could fail when `-a` _and_ `files` are given. This would yield the ability to save individual bits, but also to save all at once by default.

**Comment by bpoldrack** [comment]
Not sure about this, because what is "user-made" depends on the point of view. Could be things modified by some other software, the user isn't aware of. In general I agree, but we probably should ask for a confirmation after presenting a list of what modifications will be saved.

**Comment by bpoldrack** [comment]
Or at least a yes-no question without the list for now. "Are sure to save all changes?" if no `files` parameter was used.

**Comment by mih** [comment]
Hmm, ok. But rather than interactivity, I'd leave the default to False in that case.

**Comment by mih** [comment]
Closing, no change will be made.
