### ISSUE TITLE
Unify path handling

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#777]
Unify how and where paths are resolved against a `Dataset`, `AnnexRepo` or `GitRepo`. For the repos there is currently `normalize_paths`, which does pretty much the same.

Not actually an issue. Just opened to enhance the milestone.

**Comment by mih** [comment]
Let's define something concrete to be able to decide when to close this.

**Comment by mih** [comment]
Closing. Add concrete issues to https://github.com/datalad/datalad/milestone/30
