### ISSUE TITLE
Enhance GitRepo.dirty() to be as flexible as GitPython's is_dirty() repo function.

### ISSUE THREAD

**Issue by mih** [datalad/datalad#781]
So we can avoid calling it directly, as done in `save()`.

**Comment by yarikoptic** [comment]
#1268 partially addresses it -- i.e. makes it usable in direct mode

**Comment by bpoldrack** [comment]
I believe, I don't really know, what you mean, @yarikoptic

**Comment by yarikoptic** [comment]
ok, workS for you. greAt

**Comment by yarikoptic** [comment]
we survived without it so I guess it is ok now
