### ISSUE TITLE
`add` does not auto-save changes

### ISSUE THREAD

**Issue by mih** [datalad/datalad#782]
````
mih@meiner /tmp % datalad create some
2016-09-09 13:25:33,191 [INFO   ] Creating a new annex repo at /tmp/some (create.py:217)
Created dataset at /tmp/some.
mih@meiner /tmp % cd some
mih@meiner /tmp/some (git)-[master] % touch test
mih@meiner /tmp/some (git)-[master] % datalad add test
Added test
mih@meiner /tmp/some (git)-[master] % git st
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   test
````

It should commit the changes it made itself.

**Comment by mih** [comment]
I am planing to add a `save` option (True, False, possibly 'amend') to allow for multiple subsequent calls to `add` to result in a single commit.

**Comment by mih** [comment]
Nah, will keep it boolean. Messing with amend could lead to major headache.

**Comment by yarikoptic** [comment]
Yes, power features will be left to power users which could just use git and annex directly when needed
