### ISSUE TITLE
Should `save XXX` add and commit XXX even if it was untracked before?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#784]
This relates to a topic that came up in #775 

Related: Let `save` actually use the top-level `add` instead of `*Repo.add()`

**Comment by mih** [comment]
FTR: I think we need `add` for more than adding local untracked files. However, making users go through an explicit `add` when they already have everything locally seems pointless.

I conclude that `save` should also add previously untracked files (afterall we are trying to get to clean datasets most of the time). For adding, `save` should actually call the top-level `add` interface, not the repo functions, as it does now.

Unless I here objections, I will implement this change.

**Comment by yarikoptic** [comment]
Go ahead, sounds reasonable, and I would provide more concrete feedback when try it out
