### ISSUE TITLE
upgrade should be robust to remote branches being removed

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#793]
e.g. I have "Fixed" some repositories from being incorrectly git-annex init'ed to become back regular git repositories, so they lost their 'git-annex' branch.  now datalad upgrade fails with

```
2016-09-09 23:59:07,998 [INFO   ] Updating dataset '/mnt/scrap/datalad/datasets.datalad.org/indi' ... (update.py:115)
2016-09-09 23:59:08,053 [ERROR  ] 'git fetch -v origin git-annex' returned with exit code 128
| stderr: 'fatal: Couldn't find remote ref git-annex' [cmd.py:wait:332] (GitCommandError) (main.py:259)
datalad update -r  5.07s user 2.80s system 82% cpu 9.522 total
```

so I had to manually remove it first ('git branch -D -r origin/git-annex`)

**Comment by mih** [comment]
I wonder how `update` should behave in this case? Ignore that a remote is not longer an annex? In any other context than human error this would point to a serious issue with the setup.

**Comment by yarikoptic** [comment]
I think it
- must not fail, i.e. indeed ignore that remote is no longer an annex
- we might eventually want to have  some kind of a `--prune` option (of `git fetch` ;-)) which would then prune local git-annex branch... may be first checking that all local branches have no non-represented on remote changes so we do not loose data, and ideally checking that none of the files in any branch tip has an annexed file
