### ISSUE TITLE
testkraut must learn Direct and Non-Direct mode?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#80]
I will disable testkraut tests on Windows ( for now, as part of https://github.com/datalad/datalad/pull/78).  There is a fundamental addition necessary I guess to allow alternative values.  So we could check "either you are a symlink" or "still containing this content" (or just allowing to be a file).

**Comment by yarikoptic** [comment]
actually, may be for now we could just always have "direct" mode operation within those test samples.  Then it must work across platforms, and would provide us actually additional piece of testing.
@bpoldrack could you please look into adjusting it for direct mode?  May be it is also time to move to use our bin/datalad shim, and enhance install with --direct option, so it could all be done then "properly"

**Comment by bpoldrack** [comment]
Are you sure we want the --direct option at UI-level?

**Comment by yarikoptic** [comment]
I think so.  We will also make use of it e.g. while installing using debian packages, where we can guarantee all operations go through datalad/git-annex

**Comment by bpoldrack** [comment]
Well, that's a point.

2015-03-27 14:24 GMT+01:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by yarikoptic** [comment]
For now was work-arounded in 08bec0c77736277bbaf169ee1124f7f07fa86984 by
- making testkraut test operate in direct mode
-  removing the check for the symlink
so I will close this one
