### ISSUE TITLE
Should `Dataset.create_subdataset()` save the dataset addition

### ISSUE THREAD

**Issue by mih** [datalad/datalad#807]
It seems it should, maybe unless instructed to skip that, if we follow the save-anything paradigm.

**Comment by bpoldrack** [comment]
Agree.

**Comment by mih** [comment]
OK, thought about this again. More radical ideas:

#780 is already an indication that we have something backwards/inconsistent in our API design.

I believe we have made a few changes already that require us now to go through with a few more and actually rip out `create_subdataset()`.

Plan:

Either wait for #788 to be merged or amend the following to it, in order to fix #780 .

Replace: `ds.create_subdataset('some')` with ds.create('some')

**Comment by mih** [comment]
All in #788 now.
