### ISSUE TITLE
AnnexRepo.drop() should give more info on failure.

### ISSUE THREAD

**Issue by mih** [datalad/datalad#808]
At present it would fail with `CommandError`. It owuld be good to know, at least, when a failure was due to lacking the minimum number of required copies.

**Comment by yarikoptic** [comment]
On September 12, 2016 6:15:00 AM EDT, Michael Hanke <notifications@github.com> wrote:
>At present it would fail with `CommandError`. It owuld be good to know,
>at least, when a failure was due to lacking the minimum number of
>required copies.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/808

Yes.
We have already introduced sensing for  out of space error , so I guess similar thing needs to be done here and we might as well come up with a central registry for such regular expressions we expect to match annex output to and provide custom detailed derived exception
-- 
Sent from a phone which beats iPhone.

**Comment by yarikoptic** [comment]
@mih, how do you think #1350 would help for such a case?  I guess we would need to have a `"note"` field as well (just didn't spot it in the example output) which could describe in this case why that item was not dropped, correct?

**Comment by mih** [comment]
We have a 'message' field already. Not being dropped due to i sufficient
number of copies is status 'impossible' plus the respective path plus such
a message template string (separate format args, so we could aggregate
similar messages outside).
