### ISSUE TITLE
Integrate with weboob

### ISSUE THREAD

**Issue by Konubinix** [datalad/datalad#81]
Hi,
I really like the idea behind the datalad project.

Since the project will have to get data from the messy web and its primary language is python, I think it has a lot in common with weboob (http://weboob.org/).

Weboob (web outside of browsers) provides a whole infrastructure (including a Browser class) that helps a lot structuring scraping interfaces, modules and applications. I think that if the scraping job would be put into weboob and used into datalad, then it would contribute even more to make this world a better place to live.

**Comment by yarikoptic** [comment]
Hi @Konubinix .  Thanks for chiming in.  Surprisingly I even  had some stale cache from weboob on my laptop -- apparently I have tried it out at some point.  Indeed there could be quite a few common points of contact, we will check it out.

**Comment by mih** [comment]
I will close this `for-our-information`-style issue now, due to its persistent inactive state. This does not mean that support for this will not be added. It just reflects the evident insufficient capacity to work on this any time soon.
