### ISSUE TITLE
mystery of coverage resolved BUT what should we do? ;)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#814]
apparently consistent "-2%" is due to the fact that "Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code." i.e. those env vars I have setup in .travis.yml which enable testing of AWS S3 related code are not available withing pull requests and thus those tests do not run.

Possible resolutions:
1. change nothing    pros: easy to do   cons:  can't do merges on the phone,  -2% haunts me
2. just kill those secure env vars.  pros: easy to do   cons: we wouldn't have that code tested anywhere besides our laptops etc
3. we push our PRs via main repository   pros: easy to do,  cons: harder to tidy up.  Already many of us have way too many of those feature branches etc.  It would be somewhat undesired to get them all into main repo.
3.5:  (I kinda like it)  we make datalad-prs  clone, I set env vars for that one as well (I guess I could duplicate) and then we push PRs via it.   pros: we could rinse its all branches whenever no PRs are staged (if ever such time comes), and we could then quickly "add" quick changes to PRs of others without going through full PR to your clone + merge circle.

Do you may be see any other way?   I meanwhile will setup datalad-prs and see if it would work ;)

**Comment by yarikoptic** [comment]
I think my attempt for 3.5 kinda failed I think in #815 , so the only other "not giving up" choice is 3.

**Comment by mih** [comment]
Maybe I don't get the full picture, but it sounds like the "secret" tests only cover a small portion. So maybe we want to disable them for the main repo, and use a dedicated alternative repo that tracks the main one to run those tests. This will make it impossible to detect breakage in all PRs, but we will see the breakage. The big advantage would be that we don't need a one-of-a-king setup to accept PRs (i.e. wanna get you code in here, don't submit here....). For PRs where we want to see breakage tested, we can always also submit them to that alternative repo, too.

**Comment by yarikoptic** [comment]
few clarifications
- "small portion" is about 2%
- "alternative repo" -- we will rarely would give a damn about those failures then
- "don't submit here" -- nah, people will submit here from their clones, just that those runs will not have "full" coverage. It is somewhat already the case -- we don't run buildbot tests (by default) on PRs which come not from us.

**Comment by yarikoptic** [comment]
ok -- "resolved" by doing nothing and disabling S3 tests within master as well
