### ISSUE TITLE
New general option `on_failure` to indicate action when something goes wrong

### ISSUE THREAD

**Issue by mih** [datalad/datalad#819]
Currently, we sometimes fail, sometimes we continue. I guess it is time for making it explicit and to stick to it.

**Comment by bpoldrack** [comment]
Nice to have, I think. Voting for default `skip`, like git/git-annex do it. But might be a little more effort to implement than one could think at the first glance. With recursive operations, it might not be a one-liner to 'skip' at correct level to not run through a lot of unnecessary skips at deeper levels.

**Comment by yarikoptic** [comment]
FWIW If it would be generic "skip  in case of X, Y, Z" then sure just `--skip` but would be hard to see what it applies to?  E.g. now `--skip-failing` in publish is easier to understand from name.

**Comment by mih** [comment]
Available in #1350 now.
