### ISSUE TITLE
git annex init fails in a submodule on windows

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#82]
To let #44 RIP: annex still blows with submodules under Windows.

ran on smaug under VM under VNC :
```
C:\tmp\datalad>git clone git://github.com/datalad/datalad
C:\tmp\datalad>cd datalad
C:\tmp\datalad>git submodule update --init --recursive
Receiving objects: 100% (4/4), done.                                                                        12:28
Checking connectivity... done.
Submodule path 'datalad/tests/testrepos': checked out '260c4f32feb1519a726cd17838dad10c2ef033fb'
Submodule 'basic/r1' (git://github.com/datalad/testrepo--basic--r1) registered for path 'basic/r1'
Cloning into 'basic/r1'...
remote: Counting objects: 23, done.
remote: Total 23 (delta 0), reused 0 (delta 0), pack-reused 23
Receiving objects: 100% (23/23), done.
Resolving deltas: 100% (3/3), done.
Checking connectivity... done.
Submodule path 'datalad/tests/testrepos/basic/r1': checked out '081d300c9376ca7d8741c9eda915eeda654c2a17'

C:\tmp\datalad>cd datalad/tests/testrepos/basic/r1

C:\tmp\datalad\datalad\tests\testrepos\basic\r1>git annex init
init
  Detected a filesystem without fifo support.

  Disabling ssh connection caching.

  Detected a crippled filesystem.
(merging origin/git-annex into git-annex...)
(recording state in git...)

  Enabling direct mode.

git-annex: ..\..\..\..\..\.git/modules/datalad/tests/testrepos/modules/basic/r1\annex\objects\ae1\21c\SHA256E-s4-
-181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b.dat\: openTempFile: does not exist (No such file or directory)
failed
git-annex: init: 1 failed
```

update1: fixed up git submodule update   line (was git clone again for some reason ;) )

**Comment by yarikoptic** [comment]
annex 5.20150317-g237d5b0
if necessary, @joeyh  you should have access to that VNC... if not -- let me know, I will provide instructions

**Comment by yarikoptic** [comment]
@joeyh still an issue with 20150418

**Comment by joeyh** [comment]
This is the known windows path length problem, it's not particularly related to submodules at all. It appears identical to the failures described at http://git-annex.branchable.com/bugs/__34__git-annex:_direct:_1_failed__34___on_Windows/

**Comment by yarikoptic** [comment]
ah -- indeed -- it is getting there:
```
In [1]: len("C:\tmp\datalad\datalad\tests\testrepos\basic\r1\..\..\..\..\..\.git/modules/datalad/tests/testrepos/modules/basic/r1\annex\objects\ae1\21c\SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b.dat")
Out[1]: 210
```
I guess we could have partially worked around this by using md5sume backend in this test annex so it was friendlier to those cripples ... but also I guess it could have been partially mitigated if operation was done with full path upon its shortening?:

```
*In [2]: len("C:\tmp\datalad\datalad\.git/modules/datalad/tests/testrepos/modules/basic/r1\annex\objects\ae1\21c\SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b.dat")
Out[2]: 174
```

**Comment by yarikoptic** [comment]
actually both estimates were wrong anyways due to '\':
```
*In [5]: len(r"C:\tmp\datalad\datalad\tests\testrepos\basic\r1\..\..\..\..\..\.git/modules/datalad/tests/testrepos/modules/basic/r1\annex\objects\ae1\21c\SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b.dat")
Out[5]: 219

In [6]: len(r"C:\tmp\datalad\datalad\.git/modules/datalad/tests/testrepos/modules/basic/r1\annex\objects\ae1\21c\SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b.dat")
Out[6]: 179
```
so it is 40 characters difference -- significant portion of the allowed filename length imho

**Comment by joeyh** [comment]
I have spent months making it use relative paths, including fixing
multiple hard to track down reversions, because relative paths are on
average shorter..

But it's not a fix, and neither way of spelling the path is a fix.

-- 
see shy jo

**Comment by yarikoptic** [comment]
well -- I never said a "fix" of which the easiest would be "dump windows" or at least any of the crippled filesystems.  So I still wonder what could, at least theoretically, possibly be a more sustainable solution since our paths here is not even that long and consciousely were installed under short path already instead of somewhere under ```C:\Documents and Settings\Joe the neuroscientist\Documents\My Data\Research Projects``` which could well be the default location for someone on "khe khe" Windows shared box.

I am just throwing ideas with a hope some of them have some sanity and would stick:

- submodules: in some cases we could overcome installation of submodules being rooted within the main repo... I guess it should still be possible,  I have just not tried or asked git folks

- since good portion is eaten by the key -- if, on windows, there was e.g. ```C:\annex-data\{repo-UUID}\objects``` which contained objects which otherwise would be somewhere under deeper directories, it could provide some remedy and guaranteed operation:

```
*In [3]: len(r"C:\annex-data\9b49e014-65ed-11e0-af7a-f7428466115a\objects\xyz\abc\SHA256E-s8141923--d00564ff62f85ad59173c0763dd6cefff10eec7b8ac665b68cf4c02971f359ae.tar.gz")
Out[3]: 156
```
at the cost of possible orphaned data, and/or fragile associations if those would "link" back to original annex directories so they could be removed if those disappear.

But overall -- I actually don't give much of a damn about this system... It just would be pity to state that on this platform git-annex/DataLad needs to be used with additional caution since things would (and probably will) break.

Anyways -- with this I will just close this issue -- we have learned our lesson ;)

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> theoretically, possibly be a more sustainable solution since our paths here is
> not even that long and consciousely were installed under short path already
> instead of somewhere under C:\Documents and Settings\Joe the neuroscientist\
> Documents\My Data\Research Projects which could well be the default location
> for someone on "khe khe" Windows shared box.

Indeed, and that's why I went with the relative paths; as long as the
paths within the repo are short enough, the repo can be cloned anywhere
and still work.

> I am just throwing ideas with a hope some of them have some sanity and would
> stick:
> 
>   • submodules: in some cases we could overcome installation of submodules
>     being rooted within the main repo... I guess it should still be possible, I
>     have just not tried or asked git folks

AFAIK submodules work just as well if the git directory is in
submodule/.git as .git/submodule/whatever. Except the minor problem
of updates that remove old submodules leaving the .git directory behind
iirc.

git submodule used to set up those style directories by default even.
I don't think it can be made to do so anymore, but if the submodules are
cloned manually, that can still be accomplished.

That should eliminate a lot of the path distance.

>   • since good portion is eaten by the key -- if, on windows, there was e.g. C:
>     \annex-data\{repo-UUID}\objects which contained objects which otherwise
>     would be somewhere under deeper directories, it could provide some remedy
>     and guaranteed operation:

You lose many of git's invariants this way, like being able to delete a git
repo and have it be gone.

> Anyways -- with this I will just close this issue -- we have learned our lesson

Well, git-annex still has a bug open about this issue anyway.

-- 
see shy jo
