### ISSUE TITLE
how to uninstall a dataset???

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#824]
```shell
$> datalad uninstall --remove-handles zipser-1
2016-09-14 09:18:22,630 [ERROR  ] will not uninstall content in subdatasets without the recursive flag [uninstall.py:__call__:217] (ValueError) (main.py:259)

$> datalad uninstall --remove-handles -r zipser-1
2016-09-14 09:18:28,026 [ERROR  ] will not remove the entire dataset (with history) unless forced [uninstall.py:_uninstall:69] (ValueError) (main.py:259)
```
it is really not clear (not to say that for "forced" there is no "--force" flag seems to me)

**Comment by yarikoptic** [comment]
more of the same "awkward" kind (crcns was installed via `datalad install ///crcns` if you care to try ;) )
```
$> datalad uninstall -r crcns
2016-09-14 09:21:23,788 [ERROR  ] No dataset found [dataset.py:require_dataset:498] (InsufficientArgumentsError) (main.py:255)
usage: datalad uninstall [--version] [-h]
                         [-l {critical,error,warning,info,debug,1,2,3,4,5,6,7,8,9}]
                         [-p {condor}] [-d DATASET] [--dont-remove-data]
                         [--remove-handles] [-r] [--remove-history]
                         [--nocheck] [--if-dirty {fail,save-before,ignore}]
                         [PATH [PATH ...]]
```
to give it some kind of an excuse -- this one still doesn't have ".datalad/config" (should do smth to init that one I guess) and push those changes.  But "no dataset found" and "InsufficientArgumentsError" kinda not intuitive, whenever I did specify what to uninstall (crcns)

**Comment by mih** [comment]
Please read --help of options and suggest what to reword.

**Comment by yarikoptic** [comment]
I did read --help.  And will suggest... meanwhile could you please answer the question? ;)

**Comment by mih** [comment]
Add --remove-history, because you want to wipe it out.

**Comment by yarikoptic** [comment]
will need to digest what next one means for me
```shell
$> datalad uninstall --remove-handles -r --remove-history zipser-1
2016-09-14 10:13:16,973 [ERROR  ] Remote datalad did not have any references [remote.py:refs:514] (AssertionError) (main.py:259)
```

**Comment by mih** [comment]
try putting -d in front of the dataset name.

**Comment by yarikoptic** [comment]
FWIW -d does the trick!  but should it be required?

**Comment by mih** [comment]
BTW: I can replicate this locally. Need to find out what makes them
special....

**Comment by mih** [comment]
It doesnt do the trick, because it wont remove the dataset from the parent.

I think I see the missing condition....

**Comment by yarikoptic** [comment]
regarding "removing from the parent" -- we might need yet another option then ;)  I mean e.g. I 'install ///crcns; cd crcns; install zipser-1; uninstall zipser-1' and theoretically should want to get to the state right before 'install zipser-1' i.e. being able to reinstall it again.  The usecase -- ppl install superdataset, and start exploring it by installing/uninstalling subdatasets

**Comment by mih** [comment]
Indeed. We need to let this sink in for a moment.

**Comment by yarikoptic** [comment]
since in general we can uninstall, closing this issue and will open a new one ;)
