### ISSUE TITLE
Related effort(s): bdbag, bagit, etc

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#828]
http://bd2k.ini.usc.edu/tools/bdbag/
pointing to 
- https://github.com/ResearchObject/bagit-ro describing data structure to describe collections of data, in large minicing
  -  git (tags)
  -  annex (file checksums) entities
  - datalad (json-ld meta-data description, serialization for delivery through tarballs, access to portals with authentication)
    Apparently BagIt format is (they say) widely adopted already for digital preservation etc. Wiki: https://en.wikipedia.org/wiki/BagIt 

possible integration is digestion or export into 'bagit's.  Didn't look into mapping their meta-data descriptions at all yet, but we might want to keep in mind for our 'meta data aggregators' to provide mapping so it could be bi-directional.
- https://github.com/ini-bdds/bdbag (and larger collection of related tools under that organization) -- set of Python (2+3) utilities to interface with BDDS (???) structured BagIts
  - defines "exchange" profiles json description to harmonize exchange of such bagits between consumer/producer software

above projects also mention `ark:/` urls,  https://en.wikipedia.org/wiki/Archival_Resource_Key, and use http://n2t.net (by california digital library) for resolving those ... (yoh) wasn't aware of ARK

**Comment by mih** [comment]
Cool. We should be able to import a BagIt and turn in into a dataset....

**Comment by yarikoptic** [comment]
oh well, we know about them for a while apparently, but it is not an issue ;)

**Comment by mih** [comment]
Started looking into this.

The Python implementation of `bagit` itself is not very useful for us. It only seems to work with all data being present locally, and does not seem to handle `fetch.txt` which is a key feature for us.

https://github.com/fair-research/bdbag seems to be a better base.

**Comment by mih** [comment]
I think we can close this. Pointers to an implementation are in the posts above.
