### ISSUE TITLE
need to implement overlays in handling versioned files

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#831]
I have postponed it apparently but the time has come: https://github.com/poldrack/openfmri/issues/9

**Comment by mih** [comment]
I am afraid that ds113d will be added to that list shortly.

**Comment by yarikoptic** [comment]
thanks for the heads up!  what will be its version after such update of a subset of tarballs?

**Comment by mih** [comment]
I have no idea. BIDS version that I set and openfmri version havent been in
sync.
