### ISSUE TITLE
How to deal with `uninstall` requests that are not undoable

### ISSUE THREAD

**Issue by mih** [datalad/datalad#833]
Currently there is `--remove-history` a dedicated flag that needs to be given, if a repository is completely wiped out. And there is `--nocheck`, that currently makes datalad ignore git annex complaining about an insufficient number of copies of files to be dropped.

However, there is another condition: Removing subdatasets that progressed past the point that they have been recorded in the parent with. Demo based on code based on #832 

````
crcns (git)-[master] % git submodule |grep ac-1
 c1cd8599c3c87fea8128fcb9f8bc1b0e299f3e6b ac-1 (heads/master)
crcns (git)-[master] % datalad uninstall -r --remove-handles --remove-history ac-1
2016-09-15 08:59:12,404 [ERROR  ] Cannot delete module at /home/mih/hacking/datalad/DONTLOOK/datasets.datalad.org/crcns/ac-1 as there are new commits [base.py:remove:838] (InvalidGitRepositoryError) (main.py:259)
````

I can force that already, by not going through the parent

````
crcns (git)-[master] % datalad uninstall -d ac-1 --remove-handles --remove-history
1 item was uninstalled:
Dataset: /home/mih/hacking/datalad/DONTLOOK/datasets.datalad.org/crcns/ac-1
crcns (git)-[master] % git st
On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    ac-1
````

and a subsequent `save -a` of the parent will simply deinit the submodule (at which point we admit that those changes are (intentionally) lost.

````
crcns (git)-[master] % datalad -l debug save -a
2016-09-15 09:09:17,330 [DEBUG  ] Resolved dataset for saving: <Dataset path=/home/mih/hacking/datalad/DONTLOOK/datasets.datalad.org/crcns> (dataset.py:504)
2016-09-15 09:09:18,784 [DEBUG  ] deinit deleted subdataset ac-1 in <Dataset path=/home/mih/hacking/datalad/DONTLOOK/datasets.datalad.org/crcns> (save.py:74)
....
````

It kinda makes sense, but it doesn't feel quite natural. Any suggestions?

**Comment by yarikoptic** [comment]
we might want to do the 'annex merge', 'git push git-annex' (or just `git sync`)  after dropping to inform that remote about data being gone from here

**Comment by yarikoptic** [comment]
we have --kill now
