### ISSUE TITLE
git clone fails in master branch (actually: NOT)

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#843]
Currently we got a lot of cloning failures within the tests. This happens in master branch! Most simple example:

```
$> nosetests -s -v datalad/tests/test_testrepos.py:test_clone
datalad.tests.test_testrepos.test_clone ... ERROR

======================================================================
ERROR: datalad.tests.test_testrepos.test_clone
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ben/Development/datalad/datalad/tests/utils.py", line 686, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/ben/Development/datalad/datalad/tests/utils.py", line 516, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/ben/Development/datalad/datalad/tests/test_testrepos.py", line 39, in test_clone
    output = r.run(["git" , "clone", src, tempdir], log_online=True)
  File "/home/ben/Development/datalad/datalad/cmd.py", line 297, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
CommandError: CommandError: command '['git', 'clone', 'git://github.com/datalad/testrepo--basic--r1', '/tmp/datalad_temp_test_cloneue2vNN']' failed with exitcode 128.
Failed to run ['git', 'clone', 'git://github.com/datalad/testrepo--basic--r1', '/tmp/datalad_temp_test_cloneue2vNN'] under None. Exit code=128. out= err=Cloning into '/tmp/datalad_temp_test_cloneue2vNN'...

-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: Level 5: Done importing datalad.utils
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 6.585s

FAILED (errors=1)
```

I did not manage yet to figure out, what this is about. It happens via direct git calls by the `Runner` class as well as via GitPython. But: Apparently it happens within the context of the tests only. I cannot reproduce it manually. Neither via python nor via the shell. I used the very same calls. I even did it in parallel with the debugger. Stepped to the point where it would be called, and executed the actual call in another terminal. Tried it via Shell command, via `GitRepo`, directly via Gitpython function - no result. It works. Just not within the tests. I even copied all environment variables. I have no idea what is happening atm or how the context the tests are running in differ from what I set up to reproduce it.
So - any idea is welcome.

**Comment by yarikoptic** [comment]
I guess important going is behind those ... In err which we do not see. Run nose with --pdb and interrogate

**Comment by bpoldrack** [comment]
Look again and scroll to the right ... we see it and the only thing it says is "=Cloning into '/tmp/datalad_temp_test_cloneue2vNN'..."  ;-)
Besides from that, I ran the debugger, of course.

**Comment by bpoldrack** [comment]
Update: Not so urgent anymore. Found the reason or at least its effect. And while it seemed to be in master too, it actually isn't.

**Comment by yarikoptic** [comment]
I think this mystery is no longer an issue
