### ISSUE TITLE
add --since handling (similar to publish) to aggregate[-metadata]

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#850]
now it takes it "forever" to get through the datasets in openfmri alone due to invocation of git-annex info etc.  But if nothing changed in those sub-datasets since last generation of their metadata -- nothing should change in the aggregated meta data (if I got it right), so aggregation could be smarter and unless explicitely said to aggregate disregarding previous state (`--since=`) should aggregate data only for sub-datasets  which has changed since the last time their `.datalad/meta` entry was generated.

**Comment by yarikoptic** [comment]
moreover -- I think that all the meta-data should be collected within datasets aggregate-metadata, i.e. super-dataset must not call 'git-annex info'  within subdatasets (only if `-r` then should just invoke aggregate-metadata within subdatasets before aggregating itself).  Now it calls to `_get_implicit_metadata` within each subdataset to get their annex info.  
If such data collected while aggregating within each dataset itself, then this `--since` strategy would work beautifully.

**Comment by mih** [comment]
@yarikoptic here we found anotehr use case for `--since` in addition to `get` and `publish` -- now that it is available in `annotate-paths`

**Comment by mih** [comment]
Now theoretically simple to implement with #1630.

**Comment by mih** [comment]
Closing in favor of the more recent and more general #2164
