### ISSUE TITLE
aggregate-metadata comes up with a new @id for *subdatasets* having none on each run

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#851]
resulting in e.g.

```
commit 27194c805a38fb60b666875d0d980a3fb9c6025d
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Sat Sep 17 15:14:37 2016 -0400

    [DATALAD] aggregated meta data

diff --git a/.datalad/meta/ds000001/meta.json b/.datalad/meta/ds000001/meta.json
index e512e56..4f46d96 100644
--- a/.datalad/meta/ds000001/meta.json
+++ b/.datalad/meta/ds000001/meta.json
@@ -1,7 +1,7 @@
 [
   {
     "@context": "http://schema.org/",
-    "@id": "5be83cbc-7d08-11e6-82a7-002590f97d84",
+    "@id": "e7d63b82-7d0a-11e6-bb94-002590f97d84",
     "availableFrom": [
```

somewhat relates to #850 ;-)

**Comment by yarikoptic** [comment]
I think now it manifested in 
so they show up as '.' (i.e. current) demonstrating my "mistake" assuming that absent location should be indicative that there were no location in the hierarchy of the corresponding dataset... although it was

```shell
$> datalad install smaug:/mnt/datasets/datalad/crawl/
2016-09-19 14:34:19,853 [INFO   ] Installing <Dataset path=/tmp/crawl> from smaug:/mnt/datasets/datalad/crawl/ (install.py:372)
1 installed item is available at
<Dataset path=/tmp/crawl>

$> cd crawl 
crcns/  dicoms/  indi/  kaggle/  labs/  neurovault/  nidm/  openfmri/

$> datalad search -r '' -r name bids        
...
openfmri/ds000119:
 name: Maturational Changes in Anterior Cingulate and Frontoparietal Recruitment Support the Development of Error Processing and Inhibitory Control
.:
 name: UCLA Consortium for Neuropsychiatric Phenomics LA5c Study
openfmri/ds000200:
 name: Pre-adolescents Exposure to Manganese
.:
 name: MyConnectome
openfmri/ds000120:
 name: Developmental changes in brain function underlying the influence of reward processing on inhibitory control
```

and probably relates to the fact that `@id` for those within `dcterms:hasPart` of their super doesn't match their actual ID (I guess was "redone" at some point)

**Comment by mih** [comment]
I am wondering what should be done about this -- not sure if I grasp the nature of this yet. So you have subdatasets that have no ID, but you want the same ID reported each time? For that it would need to be stored.

If that is not happening, this would be the bug.

"aggregate-metadata does not store generated @id for *subdatasets* having none"

correct?

**Comment by yarikoptic** [comment]
On Tue, 27 Sep 2016, Michael Hanke wrote:

>    I am wondering what should be done about this -- not sure if I grasp the
>    nature of this yet. So you have subdatasets that have no ID, but you want
>    the same ID reported each time? For that it would need to be stored.

>    If that is not happening, this would be the bug.

>    "aggregate-metadata does not store generated @id for subdatasets having
>    none"

>    correct?

sounds correct.

since then I have generated ids for all datasets so didn't observe it ,
but I guess if you start from some pure annex/git repos (without
ids), you might still see it

**Comment by mih** [comment]
"Feature" gone in #1630.
