### ISSUE TITLE
When to remove meta data cache?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#859]
May be upon upgrade it should check is cache is present for prev treeish

**Comment by mih** [comment]
I wonder whether we should use Git hooks for this kind of thing, in order to be able to cope with non-datalad access to repositories.

**Comment by mih** [comment]
This also links into #852/ If we would know what files changing on update could possibly yield meta data changes we could trigger this automatically with reasonable confidence to not waste time.

**Comment by yarikoptic** [comment]
boils down
- we probably need maintenance command hooks to be placed into .git/hooks/post-update to cause necessary cleanup actions
- might come handy also to clean up extracted tarballs

but strategy could be to e.g. remove caches which are X days old (for meta or tarballs)

**Comment by mih** [comment]
We even need a rule for schema caches.

I was thinking about something like:

> when older than a month, try downloading and replace if successful

**Comment by yarikoptic** [comment]
that sounds more of a "refresh" than clean up.  Since fetching would happen automatically if/when necessary, may be cleanup could just remove without any refreshing?  or of cause we just add an option `--refresh` which could be applicable for some.  As for duration -- not sure... may be "update" should actually take care about refreshing them -- then it would all be explicit

**Comment by mih** [comment]
I was talking about schema data cache. This is not bound to any particular dataset.

**Comment by yarikoptic** [comment]
rright. but still we could update all relevant to a  dataset information (including global schema).

**Comment by mih** [comment]
The concept of a cache is gone in some sense in current master. Aggregated metadata can be kept as long as desired. Any search index is rebuilt whenever the state of the associate dataset wrt metadat has changes since it was built.
