### ISSUE TITLE
Should save be meta-aware?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#860]
i.e. run aggregate-metadata if anything related to meta-data has changed...  otherwise we would run into problem of keeping aggregated meta and original meta out of sync

**Comment by mih** [comment]
This could a can of worms. What is something that is guaranteed to next affect meta data? We might end up aggregating all the time.

**Comment by yarikoptic** [comment]
Unless we know which files are related to metadata... And we kinda do, so let's keep it in mind for now at least.
And then it could also generalize to the superdataset meta save since it would know which metadata files to see changed

**Comment by mih** [comment]
With #1630 the metadata parser can now be instructed with files to care about, but there is no concept of incremental metadata updates WITHIN a dataset (just across). At the same time the potential runtime delay can only go up with more and more complex parsers. OTOH `save` is called ALL the time. I am 100% confident that nobody wants to pay this price -- in general.

If desired in some specific scenario though, the `--run-after` config switch could be used to run metadata aggregation after `save()`. `aggregate-metadata` will not alter a dataset unless metadata-relevant pieces have changed. It probably won't work out of the box right now, but in principle this is the way I would achieve this.

**Comment by yarikoptic** [comment]
Aggregate-metadata isn't a plugin, but a command ;-) (still not sure what is the fundamental difference besides the visibility etc). I think we will keep running into this until there would be more automagic solution, so I would prefer to keep this one open

**Comment by mih** [comment]
I will close this now (again). Full aggregation can take forever, partial re-aggregation is pretty much fiction with the current setup. A different bu related issue is: https://github.com/datalad/datalad/issues/2341

Sure thing, more complex solutions are possible, but I will not work on this, not did anyone else over the past to years.
