### ISSUE TITLE
(#613) get -r should just not bother calling `get` of non Annex repo (super)datasets

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#864]
```shell
(git)hopa:/tmp/datasets.datalad.org[master]git
$> datalad get -r labs
2016-09-20 08:34:08,068 [INFO   ] Found 3 datasets to operate on. (get.py:235)
2016-09-20 08:34:08,079 [ERROR  ] CommandNotAvailableError: command 'get'.
| Missing annex at <Dataset path=/tmp/datasets.datalad.org> [get.py:__call__:248] (CommandNotAvailableError) (main.py:259)
```

**Comment by bpoldrack** [comment]
Yes and no. I think there should be an error message if you call `get` on a dataset, that isn't able to perform this operation. But it should do it differently, due to `recursive` as pointed out in #862.
So, only spit out an error message if there was no annex involved at all. Agree?

**Comment by yarikoptic** [comment]
here is my take https://github.com/bpoldrack/datalad/pull/34  feel free to adopt /discard

but imho I don't want to be bothered with failures if I am saying "datalad get a_dataset" and apparently it is not an annex and thus already has everything, so IMHO it is more of an info msg level of "concern", thus feel free to rip off raising of exception completely away -- I wouldn't mind ;)

**Comment by yarikoptic** [comment]
actually -- may be  it should raise an exception iff dataset is just a git repo but the pointed to file is a link and it is dangling without any content.  This would be sensible -- I have asked to get something I cannot get
