### ISSUE TITLE
add --since handling (similar to publish) to create-sibling

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#867]
Re #850  (same for aggregate-metadata)

so altogether it is common useful logic to have

ATM there is only `--existing` argument but that is too slow since does require going through all the subdatsets etc.  Wiser would be to "analyze" what new subdatasets were created since last time (as depicted by the last pushed commit for this dataset to that sibling), and operate only on changed ones

**Comment by mih** [comment]
Already there.
