### ISSUE TITLE
Improve upon get_most_obscure_supported_name to equip tests with sweeps over all kinds of weird filenames

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#87]
ATM we do not really have tests excercising various obscure filenames in various places of the test pipelines.  IMHO we should make get_obscure_supported_names which would spit out all supported, and so we could then run parametricly tests with various of those evil names (or just simulate all of them at the same time).

**Comment by yarikoptic** [comment]
and include unicode into those ... see eb12a31c9b4bb065f04e0a5e668a331ccfcc667c  on how to figure out if unicode filenames are supported in the environment.

**Comment by mih** [comment]
done.

**Comment by yarikoptic** [comment]
not really -- the idea was pretty much to get a decorator to do testing on various obscure names, not just one "the most obscure" one.  But I do not think we would ever do/afford to do that, so ok to keep it closed
