### ISSUE TITLE
install must not fail if installing the same thing again

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#871]
```shell
$> datalad install ///      
2016-09-20 11:11:53,296 [INFO   ] Installing dataset at: /tmp/datasets.datalad.org (install.py:498)
2016-09-20 11:11:53,333 [ERROR  ] 'git clone --progress -v http://datasets.datalad.org/.git /tmp/datasets.datalad.org' returned with exit code 128 [cmd.py:wait:327] (GitCommandError) (main.py:259)
(venv-tests) 2 19590 ->1.....................................:Tue 20 Sep 2016 11:11:53 AM EDT:.
hopa:/tmp
$> ls -ld datasets.datalad.org 
drwxr-xr-x 12 yoh yoh 260 Sep 20 08:33 datasets.datalad.org/
(venv-tests) 2 19591.....................................:Tue 20 Sep 2016 11:12:02 AM EDT:.
hopa:/tmp
$> datalad ls datasets.datalad.org
datasets.datalad.org  [git]  master  - 2016-09-20/11:04:18  X
```

**Comment by bpoldrack** [comment]
Just because that's a general point: Using more recent GitPython should lead to a more telling exception raised from git clone (already exists). Increases required version in one of the recent commits already.

Despite from that: I think it should fail, just more informative. You request to install something somewhere, where there is something already. We can detect, that there is not only "something" but a repo and spit this out, but we cannot tell, whether or not that is the thing you just requested. Assuming it's the same thing, just because of the name of the already existing dir is not a good approach from my point of view.

**Comment by bpoldrack** [comment]
So, I'd propose to catch the exception and raise a better one, telling that you either need to specify some `--force` to overwrite the target or to not rely on derived-from-source target and to explicitly specify `path` AND `source` instead.

**Comment by yarikoptic** [comment]
Few points of support in having a way to run the same `install` consecutively without failing and incurring any major cost (like `--force` would do)

#1 (lame one) that is how it works now in released version
#2 datalad walks the line between VCS and "distributions".  With VCS (e.g. git) you expect to fail if you try to clone in the same location twice.  With a "distribution" you expect for "install" to provide a guarantee that whatever you asked it to get installed, it is installed (e.g. run "apt-get install package" twice).  So, at a high level, I would us to prefer to provide "distribution" semantic -- that if someone is asked to be installed, and it was already installed -- we just say "ok".
#3 such situation would keep coming more often in Python code where we want people just to have `ds = install("dataset")` and then jump to analyzing that data, instead of doing all the shebang in removing/reinstalling it every time they run the script, or asking to guard it with `if exists`

Situation with distribution semantic becomes more interesting whenever we make command a bit more "specific". E.g. if I ask to "install package=version" and that is not the version already installed -- it should install requested version, and if it can't -- then fail.  Again -- it just a matter of "fulfilling the promise".

Back to your argument -- `We can detect, that there is not only "something" but a repo and spit this out, but we cannot tell, whether or not that is the thing you just requested`.  Not quite.  We can test if something is what we are asking to be installed  (by taking a URL from the default remote which we use now -- the `origin`, and comparing to the url we are trying to clone from while allowing for optional .git/ and may be difference in protocols... so operating on RIs.hostname and .path would help).  Since we are not asking for a particular version (yet), we would check and fulfill the promise.
Eventually, I would like us to extend syntax of supported URLs so we could somehow state the version to be installed (e.g. `http://example.com/somerepo@some-tag-or-treeish` or better `http://example.com/somerepo#version=some-tag-or-treeish`). Then, besides checking the URL to correspond we would need to check if we are the requested version position and possibly "upgrade".  The same situation is kinda now, if it exists already, but outdated, we might want it to be upgraded.

(Situation would be a bit more evolved also due to -g, and -r flags to provide complete "assurance", but imho doable)

So, altogether, I think we will need to add an option `--existing` which could take following values
- **skip**  just would do nothing and report success (current release behavior I believe)
- **upgrade** which would do operations which would make currently installed version close if not identical to the one you would have got if installed anew (to become default when implemented)
- **replace** which would be what you are suggesting with `--force`
- **error** (the one you suggest)

This would also be somewhat inline with `create-sibling --existing=(skip,replace,error,reconfigure)`

But in the short run, I would prefer us to maintain "skip"

**Comment by bpoldrack** [comment]
Since you marked it for being discussed in hangout, I will go for just a warning and not fail for now. So, it's a "skip" but it isn't completely silent about the issue.

**Comment by yarikoptic** [comment]
yeap -- perfect. Thanks!  Let's close this issue and create a new one pointing to my blurb for further discussion.  I will do that

**Comment by bpoldrack** [comment]
You might want to have a look at: 759c68418c9df7545d9e12950106a22c39b0de64
