### ISSUE TITLE
either save or aggregate-metadata (or may be publish?) still makes pure git repos annexes... grrr

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#872]
didn't catch the bastard yet, but wanted all of you know ;-)
alternative resolution could be is to not init any annex unless explicitly requested!!!!

**Comment by mih** [comment]
I don't think this is a good idea. Our standard case is annex.

**Comment by mih** [comment]
I will close this now. A lot of code has changes since this was reported. Unless we see it again, this issue has served its purpose -- we are on the look.
