### ISSUE TITLE
install --existing to provide "distribution guarantees" ;)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#875]
Originally discussed in https://github.com/datalad/datalad/issues/871#issuecomment-248607035

Few points of support in having a way to run the same `install` consecutively without failing and incurring any major cost (like `--force` would do)
1. (lame one) that is how it works now in released version
2. datalad walks the line between VCS and "distributions".  With VCS (e.g. git) you expect to fail if you try to clone in the same location twice.  With a "distribution" you expect for "install" to provide a guarantee that whatever you asked it to get installed, it is installed (e.g. run "apt-get install package" twice).  So, at a high level, I would us to prefer to provide "distribution" semantic -- that if someone is asked to be installed, and it was already installed -- we just say "ok".
3. such situation would keep coming more often in Python code where we want people just to have `ds = install("dataset")` and then jump to analyzing that data, instead of doing all the shebang in removing/reinstalling it every time they run the script, or asking to guard it with `if exists`

Situation with distribution semantic becomes more interesting whenever we make command a bit more "specific". E.g. if I ask to "install package=version" and that is not the version already installed -- it should install requested version, and if it can't -- then fail.  Again -- it just a matter of "fulfilling the promise".

Back to your argument -- `We can detect, that there is not only "something" but a repo and spit this out, but we cannot tell, whether or not that is the thing you just requested`.  Not quite.  We can test if something is what we are asking to be installed  (by taking a URL from the default remote which we use now -- the `origin`, and comparing to the url we are trying to clone from while allowing for optional .git/ and may be difference in protocols... so operating on RIs.hostname and .path would help).  Since we are not asking for a particular version (yet), we would check and fulfill the promise.
Eventually, I would like us to extend syntax of supported URLs so we could somehow state the version to be installed (e.g. `http://example.com/somerepo@some-tag-or-treeish` or better `http://example.com/somerepo#version=some-tag-or-treeish`). Then, besides checking the URL to correspond we would need to check if we are the requested version position and possibly "upgrade".  The same situation is kinda now, if it exists already, but outdated, we might want it to be upgraded.

(Situation would be a bit more evolved also due to -g, and -r flags to provide complete "assurance", but imho doable)

So, altogether, I think we will need to add an option `--existing` which could take following values
- **skip**  just would do nothing and report success (current release behavior I believe)
- **warn** what will become behavior in 0.3 (succeed but with a warning)
- **upgrade** which would do operations which would make currently installed version close if not identical to the one you would have got if installed anew (to become default when implemented)
- **replace** which would be what you are suggesting with `--force`
- **error** fail with an exception/error

This would also be somewhat inline with `create-sibling --existing=(skip,replace,error,reconfigure)`

But in the short run, I would prefer us to maintain "skip"

**Comment by yarikoptic** [comment]
so we decided that it should be "check and fail if found to be some different dataset"

**Comment by mih** [comment]
FTR: Starting point in #959 is:

````mih@meiner /tmp % datalad install ///openfmri/ds000001
2016-10-03 13:36:35,180 [INFO   ] Installing dataset at: /tmp/ds000001 (install.py:461)
2016-10-03 13:36:47,675 [INFO   ] Initializing annex repo at /tmp/ds000001 (install.py:484)
1 installed item is available at
<Dataset path=/tmp/ds000001>
mih@meiner /tmp % datalad install ///openfmri/ds000001
2016-10-03 13:36:50,550 [INFO   ] Installing dataset at: /tmp/ds000001 (install.py:461)
2016-10-03 13:36:50,638 [INFO   ] <Dataset path=/tmp/ds000001> appears to be installed already. (install.py:176)
2016-10-03 13:36:50,651 [INFO   ] Initializing annex repo at /tmp/ds000001 (install.py:484)
1 installed item is available at
<Dataset path=/tmp/ds000001>
````

**Comment by yarikoptic** [comment]
On Mon, 03 Oct 2016, Michael Hanke wrote:

>    FTR: Starting point in #959 is:

>    ````mih@meiner /tmp % datalad install ///openfmri/ds000001
>    2016-10-03 13:36:35,180 [INFO ] Installing dataset at: /tmp/ds000001
>    (install.py:461)
>    2016-10-03 13:36:47,675 [INFO ] Initializing annex repo at /tmp/ds000001
>    (install.py:484)
>    1 installed item is available at

>    mih@meiner /tmp % datalad install ///openfmri/ds000001
>    2016-10-03 13:36:50,550 [INFO ] Installing dataset at: /tmp/ds000001
>    (install.py:461)
>    2016-10-03 13:36:50,638 [INFO ] appears to be installed already.
>    (install.py:176)
>    2016-10-03 13:36:50,651 [INFO ] Initializing annex repo at /tmp/ds000001
>    (install.py:484)
>    1 installed item is available at

This "initializing annex repo" is confusing to say the least since it
must not reinitialize annex in the installed dataset.  I would vote to
remove that log line from within 'get' (or lower to DEBUG and also
change msg to "Passing to AnnexRepo.__init__ for possible
(re-)initialization" ) and raise log lines in AnnexRepo.__init__
(there is one for initialization with exactly the same message but
trailing ...) to the INFO level.  Then it would be clear when things are
actually initialized or not.

**Comment by mih** [comment]
Reinstall now looks like
````
% datalad install ///openfmri/ds000001
2016-10-03 15:26:10,247 [INFO   ] <Dataset path=/tmp/ds000001> was already installed from http://datasets.datalad.org/openfmri/ds000001/.git. Use `update` to obtain latest updates (install.py:442)
1 installed item is available at
<Dataset path=/tmp/ds000001>
````

**Comment by mih** [comment]
@yarikoptic Please say if this can be closed. And if not, what needs to be done.

**Comment by yarikoptic** [comment]
to say the truth I am not sure yet how feasible is to have it done without much pain and agreeing on desired action(s) to happen.

- Ideally, I see it not exiting early if target is installed already but just possibly skipping some steps if they are already satisfied.  For instance, if I first did `datalad install openfmri`, which installed just top level `openfmri` sub-super-dataset and then call `datalad install -r openfmri` -- it should go and make sure that it recursively got all subdatasets installed as well.  If then I call it again adding `-g` -- it would also fetch all the data.

- related question would be -- should we update/upgrade ("git pull --ff-only" kinda)? e.g. compare with `pip install` -- that one would not "install" a module again if it was installed already (of some version) but would upgrade it to the latest if we say `--upgrade`.  Or in other words -- if I ran `install openfmri` a week ago, its state (on its origin) if I did it now could be different, so if I just skip updating, overall premise for up-to-date openfmri would not be satisfied.  Having explicit `--update` could make it obvious somewhat.

**Comment by mih** [comment]
FTR: this is the situation on #1468 

````
mih@meiner /tmp % datalad --output-format json install ///openfmri/ds000001
[INFO   ] Cloning dataset from 'http://datasets.datalad.org/openfmri/ds000001' to '/tmp/ds000001' 
{"action": "clone", "path": "/tmp/ds000001", "source_url": "///openfmri/ds000001", "status": "ok", "type": "dataset"}
mih@meiner /tmp % datalad --output-format json install ///openfmri/ds000001
{"action": "clone", "path": "/tmp/ds000001", "source_url": "///openfmri/ds000001", "status": "notneeded", "type": "dataset"}
````

Both commands return with zero exit code. `--on-failure` is available as an option to select the desired error behavior.

**Comment by yarikoptic** [comment]
Lovely, thanks.

**Comment by mih** [comment]
FTR: With #1485 

````
mih@meiner /tmp % datalad install ///openfmri/ds000001
[INFO   ] Cloning dataset from 'http://datasets.datalad.org/openfmri/ds000001' to '/tmp/ds000001' 
install(ok): /tmp/ds000001 (dataset)
mih@meiner /tmp % datalad install ///openfmri/ds000001
install(notneeded): /tmp/ds000001 (dataset) [dataset <Dataset path=/tmp/ds000001> was already cloned from 'http://datasets.datalad.org/openfmri/ds000001']
````

**Comment by mih** [comment]
I believe with #1485 and all the PRs before we now have the flexibility needed to make what is desired in this issue.

**Comment by yarikoptic** [comment]
Stroke me... Do we have ability now somehow to use it for scripting ie
```
dspath=`datalad install  --some options url`
cd $dspath
```
?

**Comment by mih** [comment]
What about this sweety:

````
mih@meiner /tmp % datalad --output-format key:path install ///
/tmp/datasets.datalad.org
````

or a little bit further down? ;-)

**Comment by mih** [comment]
I think I'd rather like to have:

````
mih@meiner /tmp % datalad --output-format '{path}' install ///
/tmp/datasets.datalad.org
````

**Comment by mih** [comment]
Coming with #1499

**Comment by mih** [comment]
Merged
