### ISSUE TITLE
uninstall --kill

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#876]
I would like to have an option whenever I could just say -- kill (rmtree) the beast, without any checks/guards/etc.

**Comment by mih** [comment]
So a shortcut for -- recursive --nocheck --remove-handles --remove-history?

I want that too!

**Comment by yarikoptic** [comment]
it is not a "shortcut" per se since it would not invoke any git/annex commands or any checks at all.  Just really kill.  Effect might be indeed as if we provided all those switches but course of action is probably (didn't check) different. BTW #877 does it
