### ISSUE TITLE
provide custom abspath -- builtin resolves symlinks (sometimes)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#878]
``` shell
$> builtin cd /var/tmp/sym\ link; python -c 'from os.path import abspath; print abspath(".")' 
/tmp
$> builtin cd /tmp/sym\ link; python -c 'from os.path import abspath; print abspath(".")'    
/tmp/sym link
```

both are symlinks to /tmp/, but one under it another is outside

Discovered by failing tests of #613 , fixing up for it there but there are other uses in the codebase, so might be worth having a closer look and just use our custom implementation which would purely rely on `getpwd()`

edit: that is when to add another TMPDIR to matrix on travis, although OSX already has it that way , so that is why it failed too ;)

**Comment by bpoldrack** [comment]
Just as a note: We should then probably test for `normpath`, `expandpath` to do similar sh**.

**Comment by mih** [comment]
I am closing this. Quite a few things have changed on the path-resolution battle field.
