### ISSUE TITLE
should may be   save   have  "--allow-empty"?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#885]
just going through fixing the example script, and since we are committing everything by default, `save` invocation depicted as to "assign human readable message to it" is not effective.  Could be mitigated by always allowing empty commit... although that probably would cause more trouble than gain.  So we could just expose `allow-empty` git option.

**Comment by bpoldrack** [comment]
Just to mention it: We are about to allow for passing through any git-option anyway. This is prepared and a PR implementing it is in the queue.

**Comment by bpoldrack** [comment]
On the actual topic: I think instead of an explicit `--allow-empty` for `save`, we should have a common option `--message` for all commands, since they now commit by default. So you would not do:
```
datalad add .
datalad save -m "Better message" --allow-empty
```

but:

```
datalad add . -m "Better message"
```

**Comment by yarikoptic** [comment]
+1 from me and after @mih stoped objecting

**Comment by mih** [comment]
No longer relevant. `add` has `-m`.
