### ISSUE TITLE
setup datalad's "executables" on windows

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#89]
atm I setup a symlink under bin/  which immediately reminded that on windows it wouldn't work, so I would need copies of the shim scripts

windows can run .py scripts (https://docs.python.org/2/faq/windows.html#id3).  It probably also could run "normal way" in a shell (provided by git?) any script with correct (which would be what?) shebang...   since we probably wouldn't want to ask people adjust PATHEXT env, I guess we will just end up with .bat scripts to call into our scripts (which would or would not have .py)

does annex uses git's shell while running external remotes, @joeyh?

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> atm I setup a symlink under bin/ which immediately reminded that on windows it
> wouldn't work, so I would need copies of the shim scripts
> 
> windows can run .py scripts (https://docs.python.org/2/faq/windows.html#id3).
> It probably also could run "normal way" in a shell (provided by git?) any
> script with correct (which would be what?) shebang... since we probably
> wouldn't want to ask people adjust PATHEXT env, I guess we will just end up
> with .bat scripts to call into our scripts (which would or would not have .py)
> 
> does annex uses git's shell while running external remotes, @joeyh?

git-annex generally does not use the shell.

If datalad is running at the console, .BAT files are probably the way to
go. If you want datalad to run without a console window, you will have
to use .VBS launcher files or a similar hack.

-- 
see shy jo

**Comment by yarikoptic** [comment]
.VBS -- didn't hear about them from my 15 years ago experience... THANKS!

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> .VBS -- didn't hear about them from my 15 years ago experience... THANKS!

You can find an example of them in the git-annex windows build.

-- 
see shy jo

**Comment by yarikoptic** [comment]
just for a memory substitute, here is relevant code from within Build/NullSoftInstaller.hs

```haskell
        webappscript <- vbsLauncher tmpdir "git-annex-webapp" "git-annex webapp"
        autostartscript <- vbsLauncher tmpdir "git-annex-autostart" "git annex assistant --autostart"
...
vbsLauncher :: FilePath -> String -> String -> IO String
vbsLauncher tmpdir basename cmd = do
    let f = tmpdir </> basename ++ ".vbs"
    writeFile f $ unlines
        [ "Set objshell=CreateObject(\"Wscript.Shell\")"
        , "objShell.Run(\"" ++ cmd ++ "\"), 0, False"
        ]
    return f
```

**Comment by bpoldrack** [comment]
Why not just using the "Git Bash"? We know it's available, it makes things
more similiar to linux, so why ignore it? I somehow miss the point here.

2015-03-28 6:00 GMT+01:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by yarikoptic** [comment]
datalad  cmdline should be runable from anywhere on the system in a terminal (cmd, FAR manager, etc) without any additional configuration necessary.  For that I see the only way is to provide a datalad.bat which would do "the right thing" to call regular bin/datalad using default Python.  For web frontend (or whatever other frontend we come up with later on) we would need to use the .vbs trick I guess.

**Comment by yarikoptic** [comment]
so -- we need to figure out how for windows installations (only) we should provide .bat shims for all bin/ files
