### ISSUE TITLE
scarry ERROR Failed to get annex.uuid configuration of repository origin while doing some basic operations

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#890]
if you clone annex from github it would not have the uuid, so many operations (e.g. while running our demo example script) would spit out this error message. I am not sure how dangerous to not have uuid, but I think since it is only a log message, we could just move it into DEBUG for now

**Comment by yarikoptic** [comment]
may be we should think more about it... even annex itself seems to not mark that remote (e.g. from github) as annex ignore

**Comment by mih** [comment]
No longer the case.
