### ISSUE TITLE
get silently says "got nothing" whenever outdated annex screams in the background

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#897]
we need to introduce `@require_annex(annex_version)` for methods so they could check/vomit some sensible WARNING or ERROR if required functionality is not provided by installed annex.
Or, easier for now, in AnnexRepo constructor, check (once in a life time) current version of annex and if < than required issue a big fat warning to get recent one installed.  We already have external_versions helper so it is litterally few lines

**Comment by yarikoptic** [comment]
I think that could be a good point, if annex is outdated, to offer to (using ui, if ui.is_interactive) install it.
- On Debian-based systems it could ask additionally either they might just want to enable neurodebian repo and install datalad from it (or just git-annex-standalone)
- on other linuxes and OSX -- standalone build 

FTR here is the script I use to upgrade annex on OSX (wouldn't we need verification ?)
```
#!/bin/bash

curver=$(git annex version | awk '/version:/{print $3;}' | sed -e 's,-.*,,g')
annexdir=/Applications/git-annex.app
curverdir=$annexdir.$curver

rm -f git-annex.dmg
# release
# curl -O https://downloads.kitenet.net/git-annex/OSX/current/10.10_Yosemite/git-annex.dmg
# daily build
curl -O https://downloads.kitenet.net/git-annex/autobuild/x86_64-apple-yosemite/git-annex.dmg

hdiutil attach git-annex.dmg 

if [ ! -z "$curver" ] && [ ! -e "$curverdir" ]; then
	mv $annexdir $curverdir
fi

rsync -a /Volumes/git-annex/git-annex.app /Applications/
hdiutil  detach /Volumes/git-annex/
```

**Comment by yarikoptic** [comment]
Since get is under heavy RF, postponing since might simply be superseded

**Comment by mih** [comment]
Looking into this in #959:

Ruined my installtion for testing (git-annex v5):
````
mih@meiner /tmp/ds000001 (git)-[master] % datalad ls
2016-10-03 18:08:53,030 [ERROR  ] stderr| git-annex: unrecognized option `--raw'
| 
| Usage: git-annex version  [option ...]
| 
| To see additional options common to all commands, run: git annex help options (cmd.py:406)
/tmp/ds000001 (git)-[master] % datalad get sub-01/anat/sub-01_T1w.nii.gz
Got nothing
````

Confirmed bug.

**Comment by yarikoptic** [comment]
how old is your git -annex there?  not sure when --raw was introduced but:
```
*$> /opt/git-annex/old/git-annex version --raw
5.20151116-g76139a9
```
and then in your case I guess datalad should have reported of having no git-annex at all... what does it report for 
```
$> python -c 'from datalad.support.external_versions import external_versions; print repr(external_versions["cmd:annex"])'
```
?

and theoretically first use of AnnexRepo should have failed demanding a newer git-annex.  indeed could be related to swallowing everything in get

**Comment by yarikoptic** [comment]
FWIW --raw was added  in
```
commit 7a44dacb74b6f45b7b4302ab8c744ce6075f8087
Author: Joey Hess <joeyh@joeyh.name>
Date:   Thu Apr 2 15:37:39 2015 -0400

    version: Add --raw
```

**Comment by mih** [comment]
So the issue is that AnnexRepo actually does check the version, but fails hard, because our code it not clever enough to ask an older git-annex for a version (for example) (external_versions.py:119). It then proceeds to treat any *not* AnnexRepo as what it is, which in turn let's datalad fall back on plain GitRepo, which in turn causes all annex-related functionality to become unavailable.

I think the core bug here is that we pretend not ot have an annex whenever we cannot work with the git-annex installation. `AnnexRepo.__init__` needs to do more careful testing and report a _dedicated_ exception that we do not auto-catch upstairs.

In general I dislike that we have a fixed minimal version, because some functionality is not available in an older version, but do not actually know whether we need this. Therefore, I support having a decorator that allows us to tag individual bits with version requirements.

**Comment by mih** [comment]
The actual swallowing happens in `Dataset.repo`, nothing is swallowed in `get` for this issue.

**Comment by mih** [comment]
I installed the oldest possible git-annex version that I could simply install, and would throw some kind of error.

**Comment by yarikoptic** [comment]
yeap -- also reconfirmed locally with a version before --raw was introduced.
I thought about such a decorator myself, but decided against it.  Way too many moving targets atm with git-annex, us asking to add features etc.  Failing some pieces while keeping other pieces going with older annex sounded like just defraying the problem, actually worsening UX (IMHO it is better demand recent one once, than failing at different corners while kinda working some times), asking for trouble also -- that is why I did have that really hard exception thrown. Ok with me to get a dedicated exception, but not sure if those catches should be that wild, as you have already commented on many of them ;-) for now though may be just indeed making a helper `analyze_swallowed_exception(exc)` which would propagate SystemExit, and this annex dedicated one could well be due for a quick fix there

**Comment by mih** [comment]
Current state in #959:

````
% datalad get sub-01/anat/sub-01_T1w.nii.gz
2016-10-03 19:36:05,559 [ERROR  ] stderr| git-annex: unrecognized option `--raw'
| 
| Usage: git-annex version  [option ...]
| 
| To see additional options common to all commands, run: git annex help options (cmd.py:406)
2016-10-03 19:36:05,560 [ERROR  ] Failed to run ['git', 'annex', 'version', '--raw'] under None. Exit code=1. out= err=git-annex: unrecognized option `--raw'
| 
| Usage: git-annex version  [option ...]
| 
| To see additional options common to all commands, run: git annex help options
| 
| 
|  (cmd.py:352)
2016-10-03 19:36:05,590 [ERROR  ] git-annex of version >= 6.20160808 is missing. Install  git-annex-standalone  from NeuroDebian (http://neuro.debian.net). You have version 5.20150327+git27-g6af24b6-1~nd80+1 [annexrepo.py:_check_git_annex_version:259] (OutdatedExternalDependency) (main.py:270)
````

**Comment by yarikoptic** [comment]
great.  I will check later how it would look on raiders where some anatomicals aren't avail
