### ISSUE TITLE
cannot actually specify options to pass to annex get via --annex-get-opts

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#905]
(I don't think they are passed anyways ATM) but apparently argparser starts treating them as options to itself:

``` shell
$> datalad get --annex-get-opts '--key' sub-01_T1w.nii.gz
usage: datalad get [--version] [-h] [-l LEVEL] [-p {condor}] [-s LABEL]
                   [-d PATH] [-r] [--recursion-limit LEVELS]
                   [--git-opts STRING] [--annex-opts STRING]
                   [--annex-get-opts STRING] [-v]
                   [PATH [PATH ...]]
datalad get: error: argument --annex-get-opts: expected one argument
```

may be there is an easy way to tell argparse to really take that argument as the value for the option

**Comment by mih** [comment]
Try this:
````
$> datalad get --annex-get-opts ' --key' sub-01_T1w.nii.gz
````

(note the space at the front of the option string)

This should work in general, if the option string starts with an option. My "fix" would be to put that into the docstring.

**Comment by yarikoptic** [comment]
On September 25, 2016 7:54:00 AM EDT, Michael Hanke <notifications@github.com> wrote:
>Try this:
>````
>$> datalad get --annex-get-opts ' --key' sub-01_T1w.nii.gz
>````
>
>(note the space at the front of the option string)
>
>This should work in general, if the option string starts with an
>option. My "fix" would be to put that into the docstring.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/905#issuecomment-249417471

Yeah, I did that to trick it as well ;-) there is some other issue somewhere that it doesn't get passed along I believe...
But isn't there a more straightforward fix somehow because theoretically it shouldn't be needed, right?

**Comment by mih** [comment]
I don't see one yet. We could ask users to always prefix with some char. But this happens before argparse call type() on the value, so we would have to implement our own parsing. Maybe a different `nargs` would do better...

**Comment by mih** [comment]
Jep. Will fix.

**Comment by mih** [comment]
Actually, nope. argparse doesn't even consider an item as a value if it looks like an option. This would need more complex surgery...

**Comment by bpoldrack** [comment]
I didn't really play with `argparse` yet, but:
May be we can deal with getting these as actual options, if we can figure out, that they came in after `annex-get-opts` and the next option of the command itself? Is there any access to information about original order?

**Comment by yarikoptic** [comment]
On Mon, 26 Sep 2016, Benjamin Poldrack wrote:

>    I didn't really play with argparse yet, but:
>    May be we can deal with getting these as actual options, if we can figure
>    out, that they came in after annex-get-opts and the next option of the
>    command itself? Is there any access to information about original order?

rright!... we could "pre cook" sys.args and introduce that bloody space
or smth like that for a workaround

**Comment by yarikoptic** [comment]
FYI: ;-) if we could pass options (or actually in this case probably we should make it explicit?), datalad get could look like
![get-J4](http://www.onerussian.com/tmp/gkrellShoot_09-26-16_232731.png)

**Comment by bpoldrack** [comment]
Re `datalad get`: Why should it be an option to pass to annex? If interactive, display the progress! And if you really need it, introduce an suppress-progress option.

**Comment by yarikoptic** [comment]
I was talking about -J option for annex

**Comment by yarikoptic** [comment]
But probably we should just have explicit -J/--jobs in our API. Someone fancy might make it to grow automagically etc

**Comment by mih** [comment]
I am closing this issue. `get` doesn't have these options any more. For a generic `--jobs` floag there is #3415
