### ISSUE TITLE
make generated tarball export reproducible

### ISSUE THREAD

**Issue by mih** [datalad/datalad#908]
Not quite sure if doable with standard tarfile module. See #854 for initial thoughts.

**Comment by yarikoptic** [comment]
hm, others seems have gave up and just started to use tar directly: https://github.com/servo/servo/issues/11981

**Comment by mih** [comment]
Yeah, i was think that as well.

**Comment by yarikoptic** [comment]
but never give up!  if just a  matter of time.time call -- we could mock it out! ;)

**Comment by yarikoptic** [comment]
btw -- correct test for reproducible one should generate from a clone (done after that 1sec waiting) at the same checkout point.  Since git doesn't track timestamps -- it should be up to us to use correct times from git history,  etc.
