### ISSUE TITLE
Provide get_file_key for AnnexRepo

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#91]
There will be much more of functionality needed but I just got this one needed so immediately decided to file an issue so we don't forget

usually it is sufficient to use lookupkey  command of annex, but we should figure out how we would handle (exception or None as output) if file is not under annex control but eg straight under git etc

I guess we also should have a little discussion on how our API would in general look here

**Comment by bpoldrack** [comment]
May be there should be different exceptions. First one to indicate the file is actually under git's control instead of git-annex', second to indicate "file not found", third one to say "WTF?".

**Comment by yarikoptic** [comment]
I would try to avoid proliferation of various exceptions types, but if we subclass two of those from IOError, I guess it might make sense and would still allow (I think) to catch them all if necessary.  3rd one could simply be the IOError exception

**Comment by bpoldrack** [comment]
You can catch different types and therefore all exceptions anyway.

2015-03-31 14:59 GMT+02:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by yarikoptic** [comment]
I know that you can catch different types, but I thought it might be worth enabling catching "all of a kind" without listing them all

**Comment by bpoldrack** [comment]
Ok. Agreed.

2015-03-31 15:47 GMT+02:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by bpoldrack** [comment]
https://github.com/datalad/datalad/commit/f06a505a8593ec7dae4f441c9f4521e9e69e6642

**Comment by yarikoptic-private** [comment]
so we have had this one implemented somewhere in f06a505  or nearby
