### ISSUE TITLE
Decommision `datalad.config`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#916]
And replace with `datalad.support.dsconfig`. We use the old code in the following ways:

* datalad/cmd.py [DONE in #922]

  `cfg.getboolean('crawl', 'dryrun', default=False)`

* datalad/crawler/nodes/annex.py:from ... import cfg [DONE in #922]

   ````
   cfg.get('crawl', 'default backend', default='MD5E')
   cfg.getboolean('crawl', 'init direct', default=False)
   cfg.getboolean('crawl', 'pipeline.housekeeping', default=True)
   ````

* datalad/crawler/pipeline.py:from .. import cfg [removed unecessary import in #922]

   Standalone usage of `SafeConfigParserWithIncludes()`

* datalad/downloaders/base.py:from .. import cfg [DONE in #922]

   ````
   cfg.dirs.user_cache_dir
   cfg.getboolean('crawl', 'cache', False)
   ````

* datalad/interface/crawl.py:from .. import cfg [DONE in #922]

   ````
   if 'crawl' not in cfg.sections():
       cfg.add_section('crawl')
   cfg.set('crawl', 'dryrun', "True")
   ````

* datalad/metadata/{__init__.py,search.py}:from datalad import cfg as dlcfg [DONE in #922]

   `dlcfg.dirs.user_cache_dir`

* datalad/support/nda_.py:from datalad import cfg [DONE in #922]

   `cfg.get('externals:nda', 'dbserver', default=DEFAULT_SERVER)`

**Comment by yarikoptic** [comment]
Why? So we don't have confusingly similar .cfg and .config? Why bother with ds prefix?

**Comment by mih** [comment]
This is not about a prefix, but about the removal of this codebase in favor of a Git-based config.

**Comment by mih** [comment]
Together with #915  we could have a simple interactive initial datalad configuration via a series of `cfg.obtain()` calls.

**Comment by mih** [comment]
Merged
