### ISSUE TITLE
`datalad configure` command to initialize/modify basic settings

### ISSUE THREAD

**Issue by mih** [datalad/datalad#918]
Looks through a list of key `datalad.*` config variables, reports the default them and asks for a potential update.

This could be useful to make it more transparent how things are set up (initially), e.g. where is the cache ... Or to change a user's configuration in one go.

Implementation is essentially a loop around `cfg.obtain()` once #915 is merged.

**Comment by yarikoptic** [comment]
BTW, just FTR, there is a number of possible config options which I haven't made config calls for but was going to at some point to make configurable
```shell
$> git grep 'TODO: config'
datalad/cmd.py:            # TODO: config cmd.protocol = null
datalad/cmd.py:                # TODO: config cmd.protocol_prefix = protocol
datalad/crawler/nodes/annex.py:            # TODO: config crawl.subdataset.existing = skip|raise|replace|crawl|adjust
datalad/crawler/nodes/annex.py:            # TODO: config crawl.subdataset.crawl_new = false|true
datalad/crawler/nodes/annex.py:                    # TODO: config.tag.sign
datalad/crawler/nodes/annex.py:                        # TODO: config.tag.allow_override
datalad/crawler/nodes/crawl_url.py:                # TODO: config  -- crawl.failed='skip' should be a config option, for now always skipping
datalad/crawler/nodes/s3.py:            # TODO: config crawl.crawl_s3.versiondb.saveaftereach=True
datalad/customremotes/base.py:        self._contentlocations = DictCache(size_limit=100)  # TODO: config ?
datalad/dochelpers.py:        # TODO: config logging.exceptions.traceback_levels = 1
datalad/interface/add_archive_content.py:                    if not exists(link_path):  # TODO: config  addarchive.symlink-broken='skip'
datalad/interface/crawl.py:                # TODO: config.crawl.failure = full-reset | last-good-master
datalad/log.py:        # TODO: config log.timestamp=True
datalad/log.py:                           # TODO: config log.name, pid
datalad/support/status.py:        # TODO: config crawl.mtime_delta

```

**Comment by mih** [comment]
Thanks for the list. I started in #922.

**Comment by mih** [comment]
After some more thinking: I no longer believe this to be a good idea -- at least at this point. We have no solid understanding of the amount and dependency structure of config items, yet. Until we do such a command can only be a crude hack that is barely more than a `git config` wrapper.

I will instead try to implement support for auto-generated documentation on the available config items.

**Comment by mih** [comment]
Done #939
