### ISSUE TITLE
RFC: create-sibling --wanted=manual

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#925]
So, finally got to play with git meta-data to ease publishing with the content.  It could be quite sweet, e.g.:

``` shell
> git annex wanted datalad-public "not metadata=distribution-restrictions=*"
> git annex copy --to=datalad-public --auto -J6
```

worked out splendidly for http://datasets.datalad.org/?dir=/labs/haxby/raiders - what should have not been published, was not ;)  So, also in light of #820 discussion, I wondered if we just should provide option `--wanted` which would default to `manual` (thus nothing should get copied by default if I got it right), but could as well be `backup` to a complete copy online, or `client` (for all content in working dir but not under "/archive" etc, see [1] for more groups), or `manual` to not copy anything automagically (and thus should be overridden upon specific publish invocation by passing options to annex or specifying PATH(s).  But the point is that at `create-sibling` time we would instrument such a policy, thus possibly avoiding  any manual interactions upon subsequent "publish".

@mih -- are you using preferred content already for your repos?

[1] https://git-annex.branchable.com/preferred_content/standard_groups/

**Comment by bpoldrack** [comment]
Generally I like the approach to set such "policies" to provide a default configuration for `publish` behaviour. But since you mentioned to put this into `create_sibling`: I think this should rather go into `add_sibling` (which is called by `create_sibling`), since this is not about setting up the repo to publish to, but about configuring a remote.

**Comment by yarikoptic** [comment]
Nope. Because those policies iirc are set per remote within git-annex branch for that remote uuid, ie they are omnipresent across all clones. So you don't want to go flipping them back and forth from different clones - anarchy would come.

**Comment by yarikoptic** [comment]
Ok, I will address this one by providing `-w,--wanted` which could be either
- one of the [standard annex groups](https://git-annex.branchable.com/preferred_content/standard_groups/)
- few of our custom groups
    - `backup-unrestricted` -- `not metadata=distribution-restrictions=*`
    - `unique` -- to push derived data (the one present only locally) mostly, but somewhat simplistic since would be just `copies=1` (might consult @joeyh on optimal one).  
   - `unique-unrestricted` -- as unique but with constrained restriction, which we could advise on while defining a sibling if there is any file with 'distribution-restrictions'
- and if not matching any of those -- taken as a [preferred content](https://git-annex.branchable.com/preferred_content/) expression  (or should we be kosher and make those separate?  `--wanted-group` and `--wanted` staying more in line with annex?)

**Comment by yarikoptic** [comment]
so may be specification (to fight combinatorics) should accept multiple entries and also "unify" with notions for what git supposed to push, e.g.:
- `backup` (default), alternatives: `unique`
- `unrestricted` (default), alternatives: `norestrictions`
- `allbranches` (default), alternatives: `branches=branch1*,branch2*` (may be talk about refs, but then would need `tags/` and `heads/` prefixes ... and `alltags`?

**Comment by yarikoptic** [comment]
we really need to boil down common use-cases... may be one switch indeed would not be sufficient and we need `--publish-data`, `--publish-branches`, `--publish-tags` which, if no argument provided would assume . `nodata` for data, `*` for branches, and `*` for tags.  Then, when values are provided , act accordingly (e.g. would be the list of branches, tags, and custom selection for data as outlined above).  May be we could allow for a shortcut `--publish-all` which would be identical to `--publish-data=backup --publish-branches=* --publish-tags=*`.  Those settings in turn would be set within corresponding `remote.{}.datalad-publish-...` configs within `.git/config`, similar to how `remote.{}.datalad-publish-depends` now is set.  Saving those would allow for "publish -r", if reaching a sub-dataset which has no remote yet, to figure out all (?) settings from its parent and invoke correct `create-sibling`, which would simplify life of maintainers of collections of datasets ;)
@bpoldrack  and @mih - what do you think?

**Comment by yarikoptic** [comment]
FWIW, not specifying `--publish-branches` would in effect not provide any setting (recorded as empty in the config to be inherited by sub-datasets) thus making it behave as regular git repository, where the branch is pushed only to the tracking remote.

**Comment by mih** [comment]
Will try to play with preferred content some time soon. I believe a joint brainstorming session would be helpful before anyone starts to write this down.

**Comment by yarikoptic** [comment]
tomorrow during hangout @mih? ;)

**Comment by mih** [comment]
We indeed need to keep in mind that we have to handle annex content and git content. My current concept

`remote.<name>.datalad-publish`

- `all` -> `git push --mirror`, and copy all data (manually in the git annex sense)
- `none` -> refuse to publish anything (pull only remote; safety measure)
- `auto` -> let git annex decide (`annex copy --auto`; could be configured by create-sibling, or obtained via an update of the git-annex branch from any other location)

We should stick with `remote.<name>.push` to configure what Git content to push in more complicated cases.

I am unsure what `create-sibling` should use as default setup when nothing is specified. I am learning towards `auto`, so that restrictions coming with a dataset are obeyed by default. But I don't know enough about preferred content yet to be able to judge that.

**Comment by yarikoptic** [comment]
me as whoever wanted it just usually recall `git annex wanted` line to use and use it manually. Otherwise seems no interest, so let's close
