### ISSUE TITLE
Lazy logging

### ISSUE THREAD

**Issue by mih** [datalad/datalad#929]
At present we have the habit of immediately formatting message strings in (debug) log messages. Given that the amount of logging increases we should consider switching to lazy logging. In practice this means that we pass a format string and the format arguments separately to the log functions.

https://docs.python.org/2/library/logging.html#logging.Logger.debug

I counted 167 cases that would need fixing ;-)

**Comment by mih** [comment]
And maybe in same cases where obtaining the arguments itself is expensive we should pay attention to:

https://docs.python.org/2/howto/logging.html#optimization

ie.

````
if logger.isEnabledFor(logging.DEBUG):
    logger.debug('Message with %s, %s', expensive_func1(),
                                        expensive_func2())
````

**Comment by mih** [comment]
I correct my estimate: it is more like 250+

**Comment by yarikoptic** [comment]
Hm, my habit is the lazy style (I think). I Didn't realize we have so many with unconditional interpolations. Thanks for catching

**Comment by mih** [comment]
There seems to be an even distribution of lazy, old-style direct formatting, and more recently use of `.format()`

**Comment by mih** [comment]
Been here long enough.
