### ISSUE TITLE
datalad.log.py:TraceBack is completely untested (not executed at all)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#930]

**Comment by yarikoptic** [comment]
What do you mean untested - I tested it so many times to work perfectly! But I guess need to copy few unittests from pymvpa where it is from.

**Comment by yarikoptic** [comment]
it is at least smoke tested now (I believe actually more than that), thus closing:
https://codecov.io/gh/datalad/datalad/src/6d7d70ab947422e189b7313ec144ffdf6b3e4d30/datalad/log.py
