### ISSUE TITLE
Full-scale config mechanism

### ISSUE THREAD

**Issue by mih** [datalad/datalad#940]
At this point it seems logical to implement the following upgrade:

Look for `DATALAD_*` environment variables on startup and expose them through the regular ConfigurationManager, as *unsaved* but otherwise just like any other option.

This means we can start documenting env variables in the generated documentation, and we can also standardize access to any config switches to `datalad.cfg`

AND we need a switch to force the UI into non-interactive, even when it is connected to a terminal.

**Comment by mih** [comment]
in #939

**Comment by yarikoptic** [comment]
Nite: There is a bunch of them listed in contributing.md file

**Comment by mih** [comment]
http://docs.datalad.org/en/docs/config.html#miscellaneous-configuration

Most of them still read ugly, but they are all in.

**Comment by yarikoptic** [comment]
On September 28, 2016 8:41:56 AM EDT, Michael Hanke <notifications@github.com> wrote:
>http://docs.datalad.org/en/docs/config.html#miscellaneous-configuration
>
>Most of them still read ugly, but they are all in.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/940#issuecomment-250155271

Sweet!
