### ISSUE TITLE
More consistent config var names

### ISSUE THREAD

**Issue by mih** [datalad/datalad#941]
For example, we have `datalad.log.timestamp`, but `datalad.loglevel` and `datalad.logtraceback`. The latter two with no dot after log. Now that we can consider them git config variables, they would actually be in two different sections.

Also: 'datalad.run.cmdline.tests' could be `datalad.tests.runcmdline` in order to be inline with the other test switches.

**Comment by yarikoptic** [comment]
Feel welcome to change for consistency, I will adapt  with just a bit of cursing ;-)

**Comment by mih** [comment]
Merged.
