### ISSUE TITLE
Install is haunted

### ISSUE THREAD

**Issue by mih** [datalad/datalad#944]
On current master

````
% datalad install -s phase2 speedcheck
2016-09-28 17:32:34,588 [ERROR  ] Got no source to install from. [install.py:__call__:466] (InsufficientArgumentsError) (main.py:266)
% git clone phase2 speedcheck
Cloning into 'speedcheck'...
done.
````

It looses `source` when it calls itself immediately. I must have missed that `install` got this "I perfectly understand any number of arguments" feature back. :(

**Comment by yarikoptic** [comment]
So there is no unittest for such rudimentary usecase? Sad sad... Then they will keep coming and going
-- 
Sent from a phone which beats iPhone.

**Comment by mih** [comment]
Nope, I will rip this code out. This is the job of get. But one at a time.

**Comment by bpoldrack** [comment]
Sorry for being late at this one, but this is not actually fixed. passing `source` was intentionally not done, since it doesn't make sense. The bug is, that apparently we got into that loop, where we should get only if there was no `source` in the first place. So reopening this (and self-assigning)

**Comment by yarikoptic** [comment]
I did look at the code. We do check for source to be unsigned if more than one path, so it looked ok to me

**Comment by mih** [comment]
Guys, please hold on with this issue. I have something in the pipeline to bring this to an end -- think of the scene where the riders leave Helm's deep to die a glorious death....

**Comment by bpoldrack** [comment]
LOL

@yarikoptic : Right, be we also call it recursively, if there's a source and path is a list of length 1. And while this makes the code shorter, it is inefficient and introduced this bug.
