### ISSUE TITLE
NF: install --reckless

### ISSUE THREAD

**Issue by mih** [datalad/datalad#946]
The conclusion from #1 on how to get the fastest, cheapest possible clone of a local dataset was to set `annex.hardlink` after `git clone --local` (default). As this can have unexpected sideeffects, I think it deserves a dedicated option. At the same time I believe this scenario can be common enough to be handled by install directly. And not required a subsequent `git config` call. In particular for `install -r` scenarios.

**Comment by mih** [comment]
So after a bit of playing around it seems like setting annex.hardlink has no sideffects when hardlinking is actually no possible (cross-device, etc....). So `--reckless` could just trigger putting the variable in before `annex init`.

**Comment by yarikoptic** [comment]
I would just call it '--hardlink' to make obvious... some truly reckless might even want a '--symlink' mode ;)  I actually wonder if could be done more or less painlessly somehow by annex, that upon 'annex get' it would check if (local) remotes have that file and symlink it from their .git/annex/objects... should we aask joey?

**Comment by mih** [comment]
Check in #1 it is all in there. It shouldnt do it automatically and even
hardlinks are reckless.

**Comment by mih** [comment]
if annex gets a reckless mode too, we could use that whenever hardlinking isn't possible.

**Comment by yarikoptic** [comment]
yeah, need to re-read.  but keep in mind that my 'reckless' might be someone's 'safe'.  So I would still not call it names, but rather descriptive option.

**Comment by mih** [comment]
That is why I wouldn't call it hardlink. Chances are good that not everybody realizes the implications of inplace modification, etc. If you call it reckless it should raise a flag if anyhow possible.

**Comment by yarikoptic** [comment]
lets agree on --reckless-hardlink then... so people would realize that it is reckless and how come so

**Comment by yarikoptic** [comment]
or --reckless=hardlink even better ;)

**Comment by mih** [comment]
Later. --reckless=rubberspoon first
