### ISSUE TITLE
wishlist: centralized registry for "published" datasets

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#947]
I think we should provide some simple registry service, with which datalad create-sibling and publish should "interact" if sibling was created with --shared True,world,everybody,... and target_url was provided, so it (with uuid) would be registered with "us". Then `publish` for such siblings should update us with new meta-data.

We in turn would submit that to our "ultimate DB", possibly interrogating those target_urls more about content etc ;)
Could be some CS student project/internship.

**Comment by mih** [comment]
Yup, at some point I had a simple cherrypy draft implementation for that kind of thing.

**Comment by yarikoptic** [comment]
From weekly call: brief mind storming leaned toward establishing one as a git branch (e.g. `datalad-datasets`) which would have ria-style hashing per uuid hierarchy of git-annex style files with records per each UUID (lastseen, states (heads), ...). may be to provide flexibility each record could be a json line?

**Comment by yarikoptic** [comment]
@kyleam is working on it but nobody yet had a chance to try it out: https://github.com/datalad/datalad-registry

**Comment by bpoldrack** [comment]
There is  https://github.com/datalad/datalad-registry that is concerned with this. I don't think there's something to do in core at this point.
