### ISSUE TITLE
[wishlist] do not initiate dataset (i.e. add .datalad/config) in aggregate

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#949]
leave initiation of a dataset solely to Dataset.create, and in aggregate just skip (with a warning) those without id yet.

**Comment by mih** [comment]
#965 was merged (thanks!), but the issue was not addressed in full. I think `get_metadata()` also needs to ignore such datasets.

**Comment by yarikoptic** [comment]
ok... indeed probably it should

**Comment by mih** [comment]
With the merge of #1050 this is now fully addressed.
