### ISSUE TITLE
allow get to specify paths while staying outside of any dataset

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#963]
as @chaselgrove ran into as a user, if you install a dataset, you can't get anything until you cd to that dataset:

```shell
hopa:/tmp
$> datalad install -r ///dicoms

2016-09-29 20:07:05,977 [INFO   ] Installing dataset at: /tmp/dicoms (install.py:595)
2016-09-29 20:07:06,205 [INFO   ] Installing subdataset from './dartmouth-phantoms' at: ./dartmouth-phantoms (install.py:552)

hopa:/tmp
$> datalad get dicoms/rosetta/Siemens/Siemens_Trio_B12_dataset/volume_1/
2016-09-29 20:07:35,643 [ERROR  ] No dataset found [dataset.py:require_dataset:507] (NoDatasetArgumentFound) (main.py:266)
usage: datalad get [--version] [-h] [-l LEVEL] [-p {condor}] [-s LABEL]
                   [-d PATH] [-r] [--recursion-limit LEVELS]
                   [--git-opts STRING] [--annex-opts STRING]
                   [--annex-get-opts STRING] [-J NJOBS] [-v]
                   [PATH [PATH ...]]

$> cd dicoms
dartmouth-phantoms/  datapackage.json  dcm2niix-tests/  rosetta/

(git)hopa:/tmp/dicoms[master]
$> datalad get rosetta/Siemens/Siemens_Trio_B12_dataset/volume_1/       
2016-09-29 20:07:48,716 [INFO   ] Found 1 datasets to operate on. (get.py:205)
...
```
since we are 'getting' data from within subdatasets, I feel that there is no technical reason to not allow specifying paths to be 'get'ed while staying outside of those datasets altogether.
I guess to be resolved as a part of #959 or after it

**Comment by mih** [comment]
I agree, this should give the result you anticipated. Will investigate in the context of #959

**Comment by mih** [comment]
So, one of the issues has been addressed. Actually fixing this required a more invasive change in get, where the base dataset now needs to be resolved per given path, if no dataset is specified.

**Comment by yarikoptic** [comment]
yeap per path, but Paths should be all grouped... I would first group by a directory, and then check datasets per each directory and combine

**Comment by mih** [comment]
It is not that simple, unfortunately. There is also the distinction between paths that point to something that exists, and paths that don't. We have this entire search logic implemented that tries to install the world until we can say for sure that something is there, or not there.

I will start simple, and grow special cases from there....
