### ISSUE TITLE
'datalad.locations.cache' should be overriden for duration of test(s) to point to temp location

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#967]
otherwise pollutes main cache and causes tests side-effects

wasn't sure what is the best way to do that given a new config setup, but could be done per each test with some new decorator (e.g. `@with_temp_locations_cache`) which would override setting before and revert back after, or globally in top level `__init__.py` setup/teardown methods.
@mih -- what would be the best way to set/reset cfg value?

**Comment by mih** [comment]
In #1351 there is now a general config override mechanism.

**Comment by bpoldrack** [comment]
Yes, and once #1351 got merged, we can use  top level `__init__.py` setup/teardown methods indeed.
Like in the tests provided this will do the job:
```python
cfg.overrides['datalad.crazy.override'] = 'fromoverride'
```

**Comment by mih** [comment]
This has been approached and fixed a long time ago in a different fashion. We are using a clean and temporary HOME for the tests (unless GIT_HOME is defined). This also prevents other unfortunate interactions with a user configuration.
