### ISSUE TITLE
Adding file to git in direct mode fails

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#97]
I ran into trouble when trying to add a file to git instead of annex in direct mode.
But in https://github.com/datalad/testrepo--basic--r1.git we have this situation and things are as expected in direct mode, if I clone this one. Therefore this situation should be achievable from within direct mode too.

Here is how to reproduce it:

    ben@tree:~/Development$ mkdir testannex
    ben@tree:~/Development$ cd testannex
    ben@tree:~/Development/testannex$ git init
    Initialized empty Git repository in /home/ben/Development/testannex/.git/
    ben@tree:~/Development/testannex$ git annex init
    init  ok
    (recording state in git...)
    ben@tree:~/Development/testannex$ touch testfile
    ben@tree:~/Development/testannex$ git annex direct
    commit
    On branch master
    Initial commit
    Untracked files:
    	testfile
    nothing added to commit but untracked files present
    ok
    direct  ok
    ben@tree:~/Development/testannex$ git annex proxy -- git add testfile
    error: pathspec '.' did not match any file(s) known to git.
    git-annex: Failed to set up proxy work tree.

Why is it '.'?
May be we need something in annex first, so add this file to annex and then try again:

    ben@tree:~/Development/testannex$ git annex add testfile
    add testfile ok
    (recording state in git...)
    ben@tree:~/Development/testannex$ git annex proxy -- git status
    On branch annex/direct/master
    Initial commit
    Changes to be committed:
      (use "git rm --cached <file>..." to unstage)
    	new file:   testfile
    ben@tree:~/Development/testannex$ git annex proxy -- git commit -m firstcommit
    ok
    [annex/direct/master (root-commit) 9cb4be8] firstcommit
     1 file changed, 1 insertion(+)
     create mode 120000 testfile
    ben@tree:~/Development/testannex$ touch testfile2
    ben@tree:~/Development/testannex$ git annex proxy -- git add testfile2
    fatal: pathspec 'testfile2' did not match any files
    ben@tree:~/Development/testannex$ git annex proxy -- git status
    On branch annex/direct/master
    nothing to commit, working directory clean

Additionally, when using absolute path the result surprisingly states, this was outside repository:

    ben@tree:~/Development/testannex$ git annex proxy -- git add /home/ben/Development/testannex/testfile2
    fatal: /home/ben/Development/testannex/testfile2: '/home/ben/Development/testannex/testfile2' is outside repository

So far, I don't see what's wrong here.

**Comment by bpoldrack** [comment]
Forgot version info:

    git annex version
    git-annex version: 5.20150327+git27-g6af24b6-1~nd80+1
    build flags: Assistant Webapp Webapp-secure Pairing Testsuite S3 WebDAV Inotify DBus DesktopNotify XMPP DNS Feeds Quvi TDFA
    key/value backends: SHA256E SHA1E SHA512E SHA224E SHA384E SKEIN256E SKEIN512E MD5E SHA256 SHA1 SHA512 SHA224 SHA384 SKEIN256 SKEIN512 MD5 WORM URL
    remote types: git gcrypt S3 bup directory rsync web bittorrent webdav tahoe glacier ddar hook external
    local repository version: 5
    supported repository version: 5
    upgrade supported from repository versions: 0 1 2 4

**Comment by yarikoptic** [comment]
@joeyh could you please have a look at the above report with some awkward behavior via direct mode proxy?

**Comment by joeyh** [comment]
> pathspec '.' did not match any file(s) known to git

This is because there's no branch available yet at this point, and
git-annex proxy checks out the current branch. I could probably work
around this by having it detect this case and set up the same state in
its temporary work tree. However, it's hard to think of something
git-annex proxy could actually be useful for in this early situation
(see below).

> fatal: pathspec 'testfile2' did not match any files

This is because git-annex proxy sets up a temporary work tree and runs
the git command in there. But files not yet added to git are not present
in that temporary work tree.

> fatal: /home/ben/Development/testannex/testfile2: '/home/ben/Development/testannex/testfile2' is outside repository

Again due to the temporary work tree.


You don't actually need git-annex proxy in this situation. It would work to
run "git -c core.bare=false add testfile2". Since git add does
not update the work tree, it is safe to bypass the direct mode guard this way
in this case.

I can't see a good way to make git-annex proxy support this case, and it's
not the kind of use case I had in mind for it, quite.

I think that the best way to improve git-annex though, would be to
make `git-annex add` not just skip over files that annex.largefiles
doesn't match (the current behavior), but instead add them to git as
regular non-annexed files. I've made this change in git..

    joey@darkstar:~/tmp/d>echo hi > testfile3
    joey@darkstar:~/tmp/d>git config annex.largefiles
    largerthan=100kb
    joey@darkstar:~/tmp/d>git annex add testfile3
    add testfile3 (non-large file; adding to git directly) ok
    (recording state in git...)

-- 
see shy jo

**Comment by bpoldrack** [comment]
Thank you, @joeyh. 

>You don't actually need git-annex proxy in this situation. It would work to
>run "git -c core.bare=false add testfile2". Since git add does
>not update the work tree, it is safe to bypass the direct mode guard this way
>in this case.

Ok. So may be that's the way to go.

>I think that the best way to improve git-annex though, would be to
>make `git-annex add` not just skip over files that annex.largefiles
>doesn't match (the current behavior), but instead add them to git as
>regular non-annexed files. I've made this change in git..

This is nice to have, but I think the file size itself will not be the actual criteria in our case.
Anyway, I'll give it a try using the way you proposed above.

**Comment by joeyh** [comment]
Joey Hess wrote:
> This is because there's no branch available yet at this point, and
> git-annex proxy checks out the current branch. I could probably work
> around this by having it detect this case and set up the same state in
> its temporary work tree. However, it's hard to think of something
> git-annex proxy could actually be useful for in this early situation
> (see below).

I thought of some things. :) Checking out a branch, for example.

So, I've fixed git annex proxy in a newly created repository.

-- 
see shy jo

**Comment by joeyh** [comment]
@bpoldrack you can use other criteria than size, like extension or location.

You could even do this to force git annex add to add the file content to git:

git -c annex.largefiles='exclude=*' annex add foo

**Comment by bpoldrack** [comment]
Thanks again!

>You could even do this to force git annex add to add the file content to git:
>git -c annex.largefiles='exclude=*' annex add foo

May be this will become useful at some point, but for now I will stay with "git -c core.bare=false add foo".
Especially because that way foo remains "unknown" to git-annex in the sense, that "git annex find" won't list it as well as "git annex lookupkey foo" returns nothing. So, there is an easy way to know whether a file belongs to git itself or git-annex and this behaviour is consistent with doing the same in indirect mode.
Nevertheless: Good to know!
