### ISSUE TITLE
uninstall would fail uninstall submodule with special remotes!

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#970]
as an experiment (to improve coverage) in #969 I have made all test repos to have `datalad` special remote initialized.  That lead to a failed uninstall test: https://travis-ci.org/datalad/datalad/jobs/164361520#L3857 which I replicated locally.  yet to whine to GitPython about that... hopefully will not forget but not now :-/

edit1: apparently was RFed upstream and now fails differently, submitted a patch: https://github.com/gitpython-developers/GitPython/pull/521

**Comment by mih** [comment]
Given that this #969 was merged and the failure did not return I assume this can be closed. Please reopen if that is not the case.
