### ISSUE TITLE
API and command to specify meta-data for a dataset

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#980]
ATM we have only import facilities but no way to initiate meta-data descriptor, besides opening an editor, creating a lovely json file for one of the supported formats, saving, aggregating.  But since we know the fields we support from those formats it should be relatively easy to provide, may be simplistic, helper to initiate meta-data.  Will be useful in our code (tests) and to the users

**Comment by mih** [comment]
`metadata` is in master now.
