### ISSUE TITLE
Alternative to `git status`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#992]
I find myself using git status very often (insecure personality). As we are offering functionality to do things recursive across datasets, I find myself being forced to manually recurse in order to figure out what would happen, before having it done conveniently and recursively.

Not sure how, but `ls -r` should somehow be able to give me a _summary_ of how exactly things are dirty, if they are. at present, I only seem to be able to get this, when I list candidates explicitly to the paths.

**Comment by yarikoptic** [comment]
yeah -- I also wanted something like that in `ls` output.  Want to see what has changed from the committed state. Or ideally even from some remote sibling I would specify (e.g. `datalad-public` corresponding to datasets.datalad.org).
Partially could be mitigated I guess whenever someone creates 'foreach' command (#749). Also as a local workaround for quickly checking what has happened I came up with ['lgl' alias for my gitcofig](http://git.onerussian.com/?p=etc/base.git;a=blob;f=.gitconfig;h=998a2661aa66a9f5451f6befd592280083e72059;hb=HEAD#l24)

```shell
hopa:~/datalad/openfmri/ds000001
$> git lgl            
7ec9ffdb  [DATALAD] aggregated meta data                         2.0.1  1 file changed, 14 insertions(+)
bc151f5d  [DATALAD] record generated dataset ID     2.0.0+4-4-gbc151f5  1 file changed, 2 insertions(+)
b279f77a  Merge branch 'incoming-processed'         2.0.0+4-3-gb279f77  52 files changed, 67 insertions(+), 51 deletions(-)
cc6a09ac  Merge branch 'incoming-processed'                    2.0.0+4  2 files changed, 2 deletions(-)
0b449de8  Merge branch 'incoming-processed'                    2.0.0+3  2 files changed, 5 insertions(+), 2 deletions(-)
16f75741  Merge branch 'incoming-processed'                    2.0.0+2  2 files changed, 2 insertions(+), 4 deletions(-)
452a3aee  Merge branch 'incoming-processed'                    2.0.0+1  2 files changed, 4 insertions(+), 2 deletions(-)
05e9fb9c  Merge branch 'incoming-processed'                      2.0.0  1442 files changed, 148 insertions(+), 1337 deletions(-)
14a8dd42  Merge branch 'incoming-processed'                    1.1.0+1  2 files changed, 4 insertions(+), 2 deletions(-)
68bb4ac1  Adjusted crawler configuration: crawl:p     1.1.0-1-g68bb4ac  1 file changed, 2 insertions(+), 2 deletions(-)
3ad92404  Merge branch 'incoming-processed'                      1.1.0  115 files changed, 118 insertions(+), 113 deletions(-)
2ed6cc0a  Merge branch 'incoming-processed'                      1.0.0  1344 files changed, 1423 insertions(+)
```

**Comment by mih** [comment]
Now that @bpoldrack spend much time on testing the behavior of `status` under all conditions, maybe it is time to pour this knowledge into a simple `status` command. If we had such, we might make use of it for datalad internals also, rather then exploring `git status` and `git annex status` edge cases every single time.

**Comment by bpoldrack** [comment]
I could provide a command exposing `Repo.status`, but depends on what we expect this to do.
Note, that `git annex status` itself provides less information about submodules than `git status` does. They are just reported 'modified' no matter whether the 'modification' is untracked content or an actual modification. And it does not distinguish between staged and unstaged changes (for a reason).
Therefore I'm not sure about the value of a `datalad status` in addition to `datalad ls`.
It could be a simple `git annex status` (one that does not fail in submodules without working trees) for a quick overview of a given (CWD?) dataset. Question is: Is this what you imagine?

**Comment by mih** [comment]
It should be a proper cmd with recursive behavior like the others. It could
report status and subdataset status (known, but not there, modified,
updates available,....). Many things. The issue already came up in the
context of `ls`, but never went anywhere.

**Comment by mih** [comment]
We now have `diff` that is fairly functional and can do critical queries of git diff/status for trees of datasets.
