### ISSUE TITLE
`save` <path> injects things into Git, no annex

### ISSUE THREAD

**Issue by mih** [datalad/datalad#994]
This surprised me with several unwanted bits.

**Comment by mih** [comment]
And this relates to the relationship of `add` and `save`, of course.

**Comment by mih** [comment]
Seems todays merge of #987 dealt with this one too.

**Comment by yarikoptic** [comment]
On October 22, 2016 12:12:16 PM EDT, Michael Hanke <notifications@github.com> wrote:
>Seems todays merge of #987 dealt with this one too.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/994#issuecomment-255537325

Like magic :-)
-- 
Sent from a phone which beats iPhone.
